.github/CODEOWNERS
List default owner for sycl/e2e-tests and assign specific owners when they are known (initial version based off of CODEOWNERS from sycl-e2e-test repo)
=> [NFC][Devops] CODEOWNERS: add initial owners for sycl e2e-tests

sycl/source/detail/queue_impl.hpp, sycl/test-e2e/Basic/nested_queue_submit.cpp
As both `sycl::queue` and `sycl::handler` have similar `parallel_for` member functions, it's easy to confuse the two when writing a command group function. This change adds an exception with a clear error message when `queue::submit` is called from a command group function.
=> [SYCL] Clarify runtime error for nested kernel submissions

sycl/source/detail/graph_impl.cpp, sycl/source/detail/graph_impl.hpp, sycl/unittests/Extensions/CommandGraph.cpp
- Store graph nodes inside a vector for more optimal searches
- Replace several depth first search operations with iterations over node storage
- Node successors are now weak_ptrs
- Unit tests updated to reflect changes
=> [SYCL][Graph] Refactor node storage inside graphs

sycl/include/sycl/group_algorithm.hpp
As far as the compiler is concerned, the variable `x` is uninitialized on some control-flow paths and is passed to the function `(ex|in)clusive_scan_over_group`.
In terms of LLVM, the function parameter that `x` is passed to is likely marked `noundef`. This can lead the compiler to take advantage of `undef` rules and assume that the control path in which `x` is defined must happen (otherwise it'd be undefined), and it can essentially remove the guarding `i < N` around the memory accesses. This is, of course, dangerous.
Though, in practice, this is often avoided because the scan function is inlined before LLVM makes that assumption, this should not be relied upon. I've chosen to zero-initialize it. The value of `init` cannot be used because it may be out of bounds for the type pointed to …
=> [SYCL] Provide initialization for variable

sycl/source/detail/xpti_registry.hpp
The static verifier reported a missing user defined copy constructor as delete to match to the existing assignment operator.
=> [SYCL] Add an user-defined copy constructor

sycl/include/sycl/ext/intel/esimd/common.hpp, sycl/include/sycl/ext/intel/esimd/memory.hpp, sycl/include/sycl/ext/intel/experimental/esimd/detail/memory_intrin.hpp, sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp, sycl/test-e2e/ESIMD/lsc/atomic_smoke.cpp
- Added a routine to convert atomic_op to internal integer opcode that might be different depending on the data type;
- Simplified calls of get_num_args() by removing some redundant LSC <-> non-LSC opcode conversions;
- Use fcmpxchg instead of obsolete/less-common fcmpwr alias-sets;
- Outlined FP types check for atomics into a macro __ESIMD_FP_ATOMIC_OP_TYPE_CHECK that may be re-defined if necessary;
- NFC changes in lsc/atomic_smoke.cpp test to avoid potential problems with some types that may not have all required constexpr constructors.
=> [ESIMD][NFC] Fix several NFC issues in atomic_update() implementation

.github/CODEOWNERS
That file is processed line-by-line, so `sycl/test-e2e` generic match by the end of it rewrites previous decisions. Don't do it.
Also, move plugin/esimd/invoke_simd e2e tests ownership to corresponding sections.
=> [DevOps] Fix CODEOWNERS after #11595

mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLOps.h, mlir-sycl/lib/Conversion/SYCLToLLVM/DPCPP.cpp, polygeist/tools/cgeist/Lib/CGExpr.cc, polygeist/tools/cgeist/Lib/clang-mlir.h, polygeist/tools/cgeist/Test/Verification/sycl/array-capture.cpp, polygeist/tools/cgeist/Test/Verification/sycl/constructors.cpp, polygeist/tools/cgeist/Test/Verification/sycl/functions.cpp, polygeist/tools/cgeist/Test/Verification/sycl/issue7835.cpp, sycl/test-e2e/xfail_tests.txt
Generating SYCL specific constructors operations leads to:
1. Not generating code for constructors being abstracted away;
2. Better lowering, as we control that explicitly.
Only supporting memcpyable constructors for now due to polygeist type system inconsistencies.
=> [SYCL-MLIR][cgeist] Codegen specific memcpyable `sycl` constructors

clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/sycl-spirv-ext.c
This fixes loss of optnone attribute when generating spirv in O0 mode.
=> [SYCL][Driver] Enable SPV_INTEL_optnone extension for non-fpga targets

sycl/include/sycl/ext/oneapi/experimental/invoke_simd.hpp, sycl/test/invoke_simd/return-type-struct.cpp, sycl/test/invoke_simd/struct-arg.cpp
This is supposed to be allowed.
Uniform struct return already worked actually, I just reworded the error and function.
=> [SYCL][InvokeSimd] Allow uniform structure arguments and return

buildbot/configure.py
Easier to copy-paste this way, since many CMake flags contain semicolons.
Could be simplified by using shlex.join when Python 3.8 is required.
=> [SYCL] Quote CMake command in buildbot.py output

.github/CODEOWNERS
esimd emulator plugin was removed with https://github.com/intel/llvm/pull/11285. We can remove it from CODEOWNERS
=> [NFC][DEVOPS] CODEOWNERS: Remove esimd emulator plugin owner

sycl/doc/extensions/experimental/sycl_ext_oneapi_annotated_arg.asciidoc, sycl/include/sycl/ext/oneapi/experimental/annotated_arg/annotated_arg.hpp, sycl/test-e2e/Annotated_arg_ptr/annotated_arg.cpp
Adding arithmetic overloaded operators for annotated_arg.
The motivation for adding these is to improve user experience when templating `annotated_arg` with other templated classes that support arithmetic operators. Example, without this change. the following SYCL code results in errors:
```c++
// Some class that has arithmetic operators as member functions.
template<int W, bool S>
class ac_int;
struct MyKernel {
annotated_arg<ac_int<5, true>, ...> arg_a;
annotated_arg<ac_int<5, true>, ...> arg_b;
annotated_arg<ac_int<5, true>*, ...> arg_c;
void operator()() const {
*arg_c = arg_a + arg_b; // error!
}
};
```
After this change, the above code will not result in errors as the new operators will kick in and invoke the add operator from `ac_int`.
Alternatively, we considered what if we direct …
=> [SYCL] Add arithmetic overloaded operators for annotated_arg

sycl-fusion/test/kernel-fusion/check-failed-remapping-cuda.ll, sycl-fusion/test/kernel-fusion/check-remapping-cuda.ll, sycl-fusion/test/kernel-fusion/check-remapping-interproc-cuda.ll
Certain kernel fusion test cases fail when run using a compiler that's not configured with the `--cuda` flag. This change disables these test cases when there's no CUDA support.
=> [SYCL][NFC] Add `cuda` requirement for CUDA tests

sycl/test-e2e/syclcompat/atomic/atomic_memory_acq_rel.cpp
This change addresses errors in devices with less memory available.
The new sizes are extracted from commit https://github.com/intel/llvm/commit/0fb9a95d90f84d70393a1dc5d3bfab16748031be, which addresses the same issue.
=> [SYCL][COMPAT] Decreased memory size for atomic memory_acq_rel tests

sycl/source/handler.cpp, sycl/tools/sycl-trace/sycl_trace_collector.cpp
* Fix unused parameters of function.
* Fix error caused by capturing structured binding which is available in C++20 only.
=> [SYCL] Fix post-commit issues after PR#11548

clang/lib/Driver/ToolChains/SYCL.h, clang/test/Driver/sycl.c
Setting debug information is determined by using -g, as opposed to earlier representation using -Zi specifically for Windows.  The use of codeview is dependent on the target.
When we know that the host target is MSVC based, use the host toolchain setting of the debug format as opposed to the default toolchain which defaults to dwarf.
=> [Driver][SYCL] Adjust debug format for SYCL device on Windows

polygeist/tools/cgeist/Lib/CGExpr.cc, polygeist/tools/cgeist/Test/Verification/sycl/constructors.cpp
As only integer types may cause issues, simply check lack of integer types in argument list beforehand.
=> [SYCL-MLIR][cgeist] Extend set of sycl specific constructors codegened

llvm/lib/SYCLLowerIR/CompileTimeProperties.def, llvm/lib/SYCLLowerIR/CompileTimePropertiesPass.cpp, llvm/test/SYCLLowerIR/CompileTimePropertiesPass/prefetch.ll
The first part: https://github.com/intel/llvm/pull/11458
Adjust the CompileTimePropertiesPass so it can convert new properties into spirv decorations.
=> [SYCL] Adjust CompileTimePropertiesPass for sycl_ext_oneapi_prefetch

sycl/source/detail/global_handler.cpp, sycl/source/detail/global_handler.hpp, sycl/source/detail/scheduler/scheduler.cpp, sycl/source/detail/scheduler/scheduler.hpp
Previously we tried to release internal resources only when the last (likely main) thread exits. For multi threaded applications it could be not functional. e.g. threads are closed during module unload and when main thread exits - other threads are still alive. Adding logic to try non blocking release for every thread exit and blocking for the last one.
=> [SYCL] Add more cleanup points close to the shutdown

sycl/include/sycl/handler.hpp, sycl/test/basic_tests/handler/parallel_for_args.cpp
We have a helper which is used to extract a type of the first SYCL kernel lambda argument to do some error-checking and special handling based on that.
That check, however, was missing a case when a kernel lambda is also accepting `kernel_handler` argument, always falling back to a suggested type in that case. This led to a situations where we couldn't compile code like:
```c++
sycl::queue q;
q.parallel_for(sycl::range{1}, [=](sycl::item<1, false>, kernel_handler) {});
```
This patch adds extra specializations of some internal helpers to fix the error.
This is a follow-up from intel/llvm#11625
=> [SYCL] Fix SYCL kernel lambda argument type detection

sycl/source/detail/scheduler/commands.cpp
Adds missing instructions for storing SyncPoint in events returned by enqueuing copy commands to a command-buffer.
=> [SYCL][Graph] Bugfix missing SyncPoint in copy events

sycl/doc/design/KernelFusionJIT.md, sycl/doc/extensions/experimental/sycl_ext_codeplay_kernel_fusion.asciidoc
Document SYCL features currently not supported by kernel fusion in the implementation documentation.
=> [SYCL][Fusion] Document unsupported features

sycl/test-e2e/AOT/early_aot.cpp
Add a basic E2E test that exercises early-AOT behavior when using -fsycl -fno-sycl-rdc -c -fsycl-targets=spir64_gen when building objects.
=> [NFC][SYCL] Add e2e test for early-AOT behavior

mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLOps.td, mlir-sycl/lib/Dialect/SYCL/IR/SYCLOps.cpp, mlir-sycl/test/Dialect/SYCL/canonicalize.mlir, polygeist/tools/cgeist/Test/Verification/sycl/array-capture.cpp, polygeist/tools/cgeist/Test/Verification/sycl/constructors.cpp, polygeist/tools/cgeist/Test/Verification/sycl/issue7835.cpp
As we only take the first argument from the constructors, we can abstract some casts: `memref.memory_space_cast` and `memref.cast` not modifying the layout.
=> [SYCL-MLIR][sycl] Abstract-away casts from SYCL constructors memref operands

clang/lib/CodeGen/CGCall.cpp, sycl/test/basic_tests/fp-accuracy.cpp
This is to fix a crash in the host compilation when calling any std:: trigonometric function.
=> Fix crash when using -ffp-accuracy and std:: trigonometric functions.

sycl/include/sycl/ext/oneapi/experimental/complex/complex.hpp, sycl/include/sycl/ext/oneapi/experimental/complex/detail/common.hpp, sycl/include/sycl/ext/oneapi/experimental/complex/detail/complex.hpp, sycl/include/sycl/ext/oneapi/experimental/complex/detail/complex_math.hpp, sycl/include/syclcompat/util.hpp, sycl/test-e2e/Complex/sycl_complex_helper.hpp, sycl/test/basic_tests/macros_no_rdc.cpp, sycl/test/extensions/complex/complex.cpp
This PR is the first step toward restructuring the `complex` API.
As discussed in https://github.com/intel/llvm/pull/8647 and https://github.com/intel/llvm/pull/10854, the goal here is to clean the future-to-be `complex` API.
To simplify the review of these changes, a new PR (this PR) is created to not overload https://github.com/intel/llvm/pull/8647.
IF/WHEN this will be approved, the second step which does the same for the `marray`'s complex specialization will be pushed onto https://github.com/intel/llvm/pull/8647
Here's an overview of what has changed:
For the users, the only change is the include.
Instead of including `<sycl/ext/oneapi/experimental/sycl_complex.hpp>`, it will now be `<sycl/ext/oneapi/experimental/complex/complex.hpp>`
The `complex.hpp` header files include all the …
=> [SYCL][COMPLEX] Split complex header file and tests into multiple files

sycl/include/sycl/ext/intel/esimd/detail/memory_intrin.hpp, sycl/include/sycl/ext/intel/esimd/memory.hpp, sycl/include/sycl/ext/intel/experimental/esimd/detail/memory_intrin.hpp, sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp, sycl/test-e2e/ESIMD/unified_memory_api/Inputs/block_load.hpp, sycl/test-e2e/ESIMD/unified_memory_api/Inputs/block_store.hpp, sycl/test-e2e/ESIMD/unified_memory_api/Inputs/common.hpp, sycl/test-e2e/ESIMD/unified_memory_api/block_store_usm.cpp, sycl/test-e2e/ESIMD/unified_memory_api/block_store_usm_pvc.cpp
This change adds the groundwork for adding overloads of the block_store APIs accepting compile time properties. We have 8 overloads total, with various combinations of offset, predicate and simd_view.
=> [SYCL][ESIMD] Add compile time properties overload of USM block store

sycl/doc/design/CommandGraph.md, sycl/source/detail/scheduler/commands.cpp, sycl/test-e2e/Graph/Explicit/basic_buffer.cpp, sycl/test-e2e/Graph/Explicit/buffer_copy.cpp, sycl/test-e2e/Graph/Explicit/buffer_copy_2d.cpp, sycl/test-e2e/Graph/Explicit/buffer_copy_host2target.cpp, sycl/test-e2e/Graph/Explicit/buffer_copy_host2target_2d.cpp, sycl/test-e2e/Graph/Explicit/buffer_copy_host2target_offset.cpp, sycl/test-e2e/Graph/Explicit/buffer_copy_offsets.cpp, sycl/test-e2e/Graph/Explicit/buffer_copy_target2host.cpp, sycl/test-e2e/Graph/Explicit/buffer_copy_target2host_2d.cpp, sycl/test-e2e/Graph/Explicit/buffer_copy_target2host_offset.cpp, sycl/test-e2e/Graph/Explicit/event_status_querying.cpp, sycl/test-e2e/Graph/Explicit/temp_buffer_reinterpret.cpp, sycl/test-e2e/Graph/Explicit/usm_copy.cpp, sycl/test-e2e/Graph/RecordReplay/basic_buffer.cpp, sycl/test-e2e/Graph/RecordReplay/buffer_copy.cpp, sycl/test-e2e/Graph/RecordReplay/buffer_copy_2d.cpp, sycl/test-e2e/Graph/RecordReplay/buffer_copy_host2target.cpp, sycl/test-e2e/Graph/RecordReplay/buffer_copy_host2target_2d.cpp, sycl/test-e2e/Graph/RecordReplay/buffer_copy_host2target_offset.cpp, sycl/test-e2e/Graph/RecordReplay/buffer_copy_offsets.cpp, sycl/test-e2e/Graph/RecordReplay/buffer_copy_target2host.cpp, sycl/test-e2e/Graph/RecordReplay/buffer_copy_target2host_2d.cpp, sycl/test-e2e/Graph/RecordReplay/buffer_copy_target2host_offset.cpp, sycl/test-e2e/Graph/RecordReplay/event_status_querying.cpp, sycl/test-e2e/Graph/RecordReplay/temp_buffer_reinterpret.cpp, sycl/test-e2e/Graph/RecordReplay/usm_copy.cpp, sycl/test-e2e/Graph/RecordReplay/usm_copy_in_order.cpp, sycl/test-e2e/Graph/graph_exception_global_device_extension.cpp
When command-groups uses accessors in SYCL-Graph nodes, our implementation uses the scheduler to wrangle dependencies and then add the node to the graph. This happens at the application level during graph finalization. We currently have a call to `waitForEvents()` when adding nodes, that waits on the device event dependencies of that node command-group. For example, a memory copy command.
However, this corresponds to a call to `piEnqueueWaitForEvents`(), which is an asynchronous call that itself returns an event that must be waited on later. The blocking wait on this returned event is invoked by the scheduler on enqueue of the executable graph.
This patch changes this behaviour to perform blocking waits earlier, on node addition to the PI/UR command-buffer during graph finalization. We …
=> [SYCL][Graph] Blocking wait in finalize on scheduler dependencies

polygeist/tools/cgeist/Lib/CGCall.cc, polygeist/tools/cgeist/Test/Verification/sycl/array-decay.cpp
Array to pointer decay may involve an implicit address space cast. Handle LLVM ABI case in an ad-hoc way, as it is done for the MemRef ABI case.
=> [SYCL-MLIR][cgeist] Handle array to pointer decay with LLVM ABI

sycl/test-e2e/ESIMD/unified_memory_api/Inputs/block_store.hpp
The mask logic was wrong. I manually verified the test on PVC.
=> [SYCL][ESIMD][E2E] Fix compile time properties block store test

sycl/include/sycl/ext/intel/experimental/fpga_lsu.hpp, sycl/include/sycl/ext/intel/experimental/fpga_utils.hpp, sycl/include/sycl/ext/intel/experimental/pipes.hpp, sycl/include/sycl/ext/oneapi/latency_control/properties.hpp
This reverts commit b60828d9d6cc5968209cdd94086a22e6d5088602.
We are looking for improving the clang-generated IR for latency controls further, so backing out my previous header change for 2024.1 for now.
=> Revert "[SYCL] [FPGA] Leverage `add_ir_annotations_member` in latency controls (#11554)"

llvm/utils/git/requirements.txt
This updates the urllib3 version listed in llvm/utils/git/requirements.txt to address two problems reported by Dependabot
=> Update urllib3 version

sycl/test-e2e/Basic/accessor/empty_zero_dim_accessor.cpp
Locally, on a machine with NVIDIA gpu verified to work.
=> [SYCL][HIP][CUDA] Enable cuda / hip support for empty_zero_dim_accessor test.

sycl/include/sycl/ext/oneapi/experimental/annotated_arg/annotated_arg.hpp, sycl/include/sycl/ext/oneapi/experimental/annotated_ptr/annotated_ptr.hpp, sycl/include/sycl/ext/oneapi/experimental/common_annotated_properties/properties.hpp
This change shortens the error messages for the static assertion failures for annotated_arg/ptr. The check is first assigned to a boolean variable that is named to represent the check and this variable is used in the static assertion. This prevents the props for annotated_arg/ptr to printed in the error message. 
For example, the following static assertion: 
```
error: static assertion failed due to requirement 'is_valid_property<ac_int<17, true>, sycl::ext::oneapi::experimental::property_value<sycl::ext::intel::experimental::buffer_location_key, std::integral_constant<int, 0>>>::value': Property is invalid for the given type.
57 |   static_assert(is_valid_property<T, Prop>::value,
|                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
will look like this: 
```
error: static assertion …
```
=> [SYCL] Shortening error messages in annotated_arg/ptr assertion failures

clang/lib/Driver/ToolChains/Cuda.cpp, clang/test/Driver/sycl-cuda-rdc.cpp
This commit fixes an issue with -fgpu-rdc for NVPTX targets in the SYCL driver. When the driver calls the `ptxas` assembling job in relocatable device code compilation mode, we pass `-c` to the command-line to get a relocatable code ELF instead of a statically fully linked object. This is the correct behaviour for the purpose of CUDA separate compilation flow with RDC, but in SYCL it does not make sense for us to do so because we do RDC at a bitcode level rather than PTX. We link the IR modules with llvm-link way earlier and the linking method based on `-fgpu[no]-rdc` is determined there. Hence, we always want a fully linked object from `ptxas` in SYCL. This simplifies the need for adding a `nvlink` job in the pipeline.
Related github issue: https://github.com/intel/llvm/issues/8690
=> [SYCL][Driver] Fix -fgpu-rdc option for CUDA

sycl/source/handler.cpp
The build was broken with:
```
/home/hugh/llvm/sycl/source/handler.cpp:247:48: error: ‘CmdTraceEvent’ was not declared in this scope
247 |       auto EnqueueKernel = [&, CmdTraceEvent = CmdTraceEvent,
|                                                ^~~~~~~~~~~~~
/home/hugh/llvm/sycl/source/handler.cpp:248:42: error: ‘InstanceID’ was not declared in this scope; did you mean ‘distance’?
248 |                             InstanceID = InstanceID]() {
|                                          ^~~~~~~~~~
|                                          distance
```
When XPTI tracing is not used.
=> [SYCL] Fix build when not using XPTI tracing

clang/test/SemaSYCL/accessor_inheritance.cpp, clang/test/SemaSYCL/array-kernel-param.cpp, clang/test/SemaSYCL/basic-kernel-wrapper.cpp, clang/test/SemaSYCL/built-in-type-kernel-arg.cpp, clang/test/SemaSYCL/device_has_ast.cpp, clang/test/SemaSYCL/inheritance.cpp, clang/test/SemaSYCL/kernel-handler.cpp, clang/test/SemaSYCL/parallel_for_wrapper_attr.cpp, clang/test/SemaSYCL/sampler.cpp, clang/test/SemaSYCL/stream.cpp, clang/test/SemaSYCL/union-kernel-param1.cpp, clang/test/SemaSYCL/union-kernel-param2.cpp, clang/test/SemaSYCL/uses_aspects_ast.cpp, clang/test/SemaSYCL/wrapped-accessor.cpp
Due to https://github.com/intel/llvm/commit/f9ead46931aef2978ddf350ba6523638175d7861, the desugared type is now only dumped when visibly
different. This patch updates multiple tests to adjust the expected
output according to this change.
=> [sycl-web] Update expected output of multiple tests.

sycl/source/detail/program_manager/program_manager.cpp
Currently, sycl-post-link tool scans user's device image to detect any undefined function call to items in fallback spirv devicelibs and create a property in final executable to tell which fallback devicelibs are really needed. SYCL runtime will load required fallback spirv libs according to this property.
However, if "SYCL_USE_KERNEL_SPIRV" is used, the kernel is launched from spv file and sycl-post-link tool is not involved to scan and generate the property. Previously, we just load and link all fallback spv files and underlying runtime will remove them when they don't need those code. However, we received a lot of complains about seeing a lot of unnecessary code from underlying runtime. So, this PR is to avoid loading this unnecessary code.
If anyone uses clang++ driver to generate spv …
=> [SYCL] Don't load all fallback spirv when launching from SPIRV file

sycl/include/sycl/ext/intel/experimental/fpga_annotated_properties.hpp, sycl/include/sycl/ext/oneapi/experimental/annotated_arg/annotated_arg.hpp, sycl/include/sycl/ext/oneapi/experimental/annotated_ptr/annotated_ptr.hpp, sycl/test/extensions/annotated_arg/annotated_arg_for_ptr.cpp, sycl/test/extensions/annotated_arg/annotated_arg_negative.cpp, sycl/test/extensions/annotated_arg/annotated_ptr.cpp
This change ensures that there is an error when the user tries to specify both the `conduit` property and the `register_map` property on `annotated_arg` or `annotated_ptr`. 
For example, the following variable: 
```cpp
annotated_arg<int, decltype(properties{conduit, register_map})> a;
```
will generate the following assertion failure: 
```
/p/psg/swip/w/yugteshs/sycl_include_1/sycl/ext/oneapi/experimental/annotated_arg/annotated_arg.hpp:204:17: error: static assertion failed due to requirement 'hasConduitAndRegisterMapProperties': The properties conduit and register_map cannot be specified at the same time.
204 |   static_assert(hasConduitAndRegisterMapProperties,
|                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> [SYCL] Error for conduit and register_map on annotated_arg/ptr

clang/test/Driver/sycl-cuda-rdc.cpp
The test will fail on machines without cudalib
clang: error: cannot find libdevice for sm_61; provide path to different
CUDA installation via '--cuda-path', or pass '-nocudalib' to build
without linking with libdevice
For the driver test, we don't really need the cudalib.
=> [SYCL][CUDA][NFC] Add nocudalib to rdc driver test

polygeist/lib/Dialect/Polygeist/Transforms/LoopRestructure.cpp, polygeist/test/polygeist-opt/loop-restructure-keep-block-arg.mlir, polygeist/tools/cgeist/Test/Verification/do-while-switch.c
When arguments of the loop's blocks are used outside the loop, preserve them as it is done with operation-defined values.
Loop header arguments are skipped as those are already added by default.
=> [SYCL-MLIR][loop-restructure] Preserve block arguments

clang/tools/clang-offload-wrapper/SymPropReader.h
Make sure class member CurrentDeviceImageInitializer is initialized.
=> Initialize ptr variable to nullptr

sycl/include/sycl/detail/vector_convert.hpp, sycl/include/sycl/types.hpp, sycl/test/basic_tests/vectors/vectors.cpp
Introduced ability to perform vector conversions using a single instruction instead of doing so per-element.
=> [SYCL] Refactor `vec::convert` implementation

polygeist/tools/cgeist/Lib/clang-mlir.cc, polygeist/tools/cgeist/Test/Verification/use-global-in-namespace.cpp
When a global variable is refercenced in device code, it should be defined in the device module.
=> [SYCL-MLIR][cgeist] Define global variables in proper context

sycl/test-e2e/Annotated_arg_ptr/annotated_arg.cpp, sycl/test-e2e/Annotated_arg_ptr/annotated_ptr.cpp
reenable ann_arg/ptr e2e test on windows, tagged with unsupported: gpu
issue https://github.com/intel/llvm/issues/11224
=> [SYCL] reenable ann_arg/ptr e2e test on windows

sycl/plugins/unified_runtime/CMakeLists.txt, sycl/test-e2e/Plugin/cuda-max-local-mem-size.cpp
CI for https://github.com/oneapi-src/unified-runtime/pull/931
=> [UR] [CUDA] Changed the output of querying localMemSize

sycl/doc/UsersManual.md
This commit adds the option description of -fpreview-breaking-changes to the SYCL user manual.
=> [SYCL][Docs] Add -fpreview-breaking-changes to the user manual

clang/tools/clang-offload-wrapper/SymPropReader.cpp
On windows ICX build , using int may cause build failures.
clang-offload-wrapper/SymPropReader.cpp(168,34): error: call to member
function 'getAggregateElement' is ambiguous
=> [SYCL][clang-offload-wrapper] Use unsigned int in constexpr to avoid ambiguous call

sycl/test-e2e/Matrix/joint_matrix_bfloat16_16x16x16.cpp, sycl/test-e2e/Matrix/joint_matrix_bfloat16_32x64x16.cpp
Remove XFAIL for GPU for joint_matrix_bfloat16_16x16x16 and joint_matrix_bfloat16_32x64x16 tests
=> [SYCL][Joint Matrix][E2E] Remove xfail for GPU for 2 tests

sycl/test-e2e/USM/dmem_varied.cpp
Test is missing required wait() between initializing ptrs and reading it. This is causing flaky failures.
=> [SYCL][E2E] dmem_varied.cpp test missing required sync point

sycl/include/sycl/ext/intel/esimd/detail/memory_intrin.hpp, sycl/include/sycl/ext/intel/esimd/memory.hpp, sycl/test-e2e/ESIMD/esimd_test_utils.hpp, sycl/test-e2e/ESIMD/unified_memory_api/Inputs/block_load.hpp, sycl/test/esimd/memory_properties.cpp
1) Fix the big mess in E2E test for block_load(). Test did not really
check the mask variant. It also used wrong alignments.
2) Fix the comments for USM and ACC block_load implementations. 
3) Minor optimization for ACC block_load functions that do not accept
the byte_offset operand. We can assume align16 for them.
=> [ESIMD] Fix implementations of block_load(usm, ...) and block_load(acc)

sycl/include/sycl/ext/oneapi/matrix/matrix-hip.hpp
Replace for loop to copy results with `std::memcpy` which showed slightly better performance.
=> [SYCL][HIP] Replace for loop to copy results with std::memcpy.

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/atomic.hpp, sycl/include/syclcompat/memory.hpp, sycl/include/syclcompat/traits.hpp, sycl/test-e2e/syclcompat/atomic/atomic_arith.cpp, sycl/test-e2e/syclcompat/atomic/atomic_bitwise.cpp, sycl/test-e2e/syclcompat/atomic/atomic_comp_exchange.cpp, sycl/test-e2e/syclcompat/atomic/atomic_fixt.hpp, sycl/test-e2e/syclcompat/atomic/atomic_memory_acq_rel.cpp, sycl/test-e2e/syclcompat/atomic/atomic_minmax.cpp
This PR replaces #11338, following discussion with DPCT team. Change summary:
- Remove runtime `memoryOrder` option (no longer needed)
- Define `type_identity_t` and use it to avoid template deduction errors.
- New tests for the above (e.g. `int *` addr with `unsigned int` operand)
- New free function `atomic_fetch_compare_dec`
=> [SYCL][COMPAT] Atomics: Support for multiple datatypes, remove runtime memoryOrder

sycl/source/detail/device_info.hpp
Small fix to strip down additional CPU information from AMD query, like: `gfx90a:sramecc+:xnack-` to just `gfx90a`
=> [SYCL][CUDA][HIP] Fix device architecture extension query

sycl/test-e2e/ESIMD/slm_init_no_inline.cpp
=> [SYCL][ESIMD][E2E] Add ze_debug as unsupported for slm_init_no_inline

mlir/lib/Target/LLVMIR/Dialect/LLVMIR/LLVMToLLVMIRTranslation.cpp, mlir/test/Target/LLVMIR/llvmir.mlir, polygeist/tools/cgeist/Test/Verification/sycl/constructors.cpp, polygeist/tools/cgeist/Test/Verification/sycl/issue7835.cpp, polygeist/tools/cgeist/Test/Verification/sycl/sycl_extern_func.cpp, polygeist/tools/cgeist/Test/Verification/sycl/usm-wrapper.cpp
Make translated call instructions attributes the same as those in the callee function.
=> [SYCL-MLIR][mlir-translate] Set call attributes following callee

sycl/plugins/unified_runtime/CMakeLists.txt
Combines the following L0 changes:
* https://github.com/oneapi-src/unified-runtime/pull/1033
* https://github.com/oneapi-src/unified-runtime/pull/1028
* https://github.com/oneapi-src/unified-runtime/pull/1022
=> [UR] Bump to ec7982bac6cb3a6b9ed610cd6b7cb41fcbc780dc

sycl/include/sycl/types.hpp, sycl/test-e2e/Basic/vec_bool.cpp
Since bool vectors have a backing storage of chars, the unary minus operator was in fact producing `(char)-1`, and thus not adhering to the ABI where bools should be either 0 or 1.
This could manifest itself in bugs, for instance where the "bool" elements wouldn't compare equal to other bools, such as those in arrays.
This only manifested itself in device code (possibly because the array of bools is also an array of bytes under the hood), hence the test case that differs in style somewhat from the rest.
=> [SYCL] Fix `operator-` for `sycl::vec<bool, N>`

mlir/include/mlir/Dialect/LLVMIR/LLVMOps.td, mlir/lib/Dialect/LLVMIR/IR/LLVMDialect.cpp, mlir/lib/Target/LLVMIR/Dialect/LLVMIR/LLVMToLLVMIRTranslation.cpp, mlir/test/Dialect/LLVMIR/calling-conventions.mlir, mlir/test/Dialect/LLVMIR/func.mlir, mlir/test/Dialect/LLVMIR/inlining.mlir
This PR cherry-pick partial 65fedb43942690644869baa1e27a78a516f3f29e.
Despite the fact that the LLVM dialect’s `FuncOp` already supports calling conventions, there was yet no support for them in the ops that actually perform function calls, which led to incorrect LLVM IR being generated if one actually tried setting a `FuncOp`’s calling convention to anything other than `ccc`.
This commit adds support for calling conventions to `LLVM::CallOp` and makes sure that calling conventions are parsed,
printed, and lowered appropriately.
=> [GENX][MLIR] Add support for calling conventions to LLVM::CallOp

mlir/lib/ExecutionEngine/OptUtils.cpp
This is a temporary workaround to disable SLPVectorization until the LLVM-SPIRV translator can handle  `llvm.vector.reduce.*`
=> [GENX]: Disable SLPVectorization

sycl/include/sycl/types.hpp, sycl/test-e2e/Basic/vec_bool.cpp
Since vectors of bools are backed by byte-sized storage, we must ensure that conversion results from other vector types are correctly brought into the expected range of bools, e.g., `(char)0` or `(char)1`.
=> [SYCL] Fix `convert` to `sycl::vec<bool, N>`

clang/include/clang/Basic/DiagnosticCommonKinds.td, clang/lib/CodeGen/Targets/NVPTX.cpp, clang/test/SemaSYCL/lb_sm_90.cpp
Cuda specifies the launch bounds as:
```
__launch_bounds__(maxThreadsPerBlock, minBlocksPerMultiprocessor, maxBlocksPerCluster)
```
making it impossible to specify `maxBlocksPerCluster` without the preceding two attributes (similarly for `minBlocksPerMultiprocessor`), issue warnings and ignore attributes if the condition is not met.
=> [SYCL][CUDA] Issue warnings for incomplete launch bounds attribute set

sycl/test-e2e/Config/select_device.cpp
Fixes generating filters like this one: `DeviceName:{{gfx90a:sramecc\+:xnack\-}},DriverVersion:{{HIP 50422.80}}`
=> [SYCL][Test E2E] Add 2 extra characters to escaping function

clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/sycl-offload.c, sycl/test/basic_tests/parallel_for_type_check.cpp
When using -O0 to disable optimizations, also set -fsycl-disable-range-rounding to further disable optimizations to improve debugability.
=> [Driver][SYCL] Disable parallel for range rounding at -O0

sycl/test-e2e/ESIMD/InlineAsm/asm_glb.cpp
This started causing a hang on a newer GPU driver with O0, we have an internal tracker for this. Force O2 for now.
=> [SYCL][ESIMD][E2E] Require O2 for InlineAsm global test

sycl/include/sycl/ext/intel/esimd/memory.hpp, sycl/include/sycl/ext/intel/esimd/xmx/dpas.hpp
Even though std::max is completely legal/correct to use in SYCL/ESIMD especially in 'constexpr' context, it may cause problems on Windows in some non-trivial configurations with some odd order of includes of system and SYCL header files.
=> [SYCL][ESIMD][NFC] Replace the uses of std::max in ESIMD with ternary op

mlir/include/mlir/Dialect/LLVMIR/GENXOps.td, mlir/test/Target/LLVMIR/genx.mlir
Code generation of `%1 = genx.workitem.id.x : i32` was incorrect, as it always generate `call i64 @_Z12get_local_idj(i32 0)`. This PR adds a proper cast instruction to return the appropriate type.
=> [GENX] Cast device function call to correct type

sycl/include/sycl/ext/intel/esimd/memory.hpp, sycl/test/esimd/memory_properties.cpp
The element-size address alignment is valid from correctness point of view, but using 1-byte and 2-byte alignment implicitly causes performance regression for block_load(const int8_t *, ...) and block_load(const int16_t *, ...) because GPU BE have to generate slower GATHER instead of more efficient BLOCK-LOAD. Without this fix block-load causes up to 44% performance slow-down on some apps that used block_load() with alignment assumptions used before block_load(usm, ..., compile_time_props) was implemented.
The reasoning for the expected/assumed alignment from element-size to 4-bytes for byte- and word-vectors is such:
The idea of block_load() call (opposing to gather() call) is to have
efficient block-load, and thus the assumed alignment is such that
allows to generate block-load. This is …
=> [ESIMD] Fix perf regression caused by assumed align in block_load(usm)

sycl/source/detail/device_info.hpp
According to
https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/experimental/sycl_ext_matrix/sycl_ext_oneapi_matrix.asciidoc#intel-xmx-supported-combinations 
for PVC: `matrix_type::sint8`, `matrix_type::sint8`, `matrix_type::sint32`, `<=8`, `16`, `32` but implementation had a typo: K == 16 instead of 32, fixed by this patch
=> [SYCL][Joint Matrix] Fix typo in matrix_combinations on PVC

sycl/doc/extensions/proposed/sycl_ext_oneapi_kernel_compiler.asciidoc, sycl/doc/extensions/proposed/sycl_ext_oneapi_kernel_compiler_opencl.asciidoc
Add a proposed extension specification for the "kernel compiler", a replacement for the existing "online_compiler" extension.  There are two related extensions specifications:
* sycl_ext_oneapi_kernel_compiler: Defines the API framework for online compilation of kernels from a source string.  This framework allows for kernels to be written in different possible languages.
* sycl_ext_oneapi_kernel_compiler_opencl: Defines the support for online compiled kernels that are written in OpenCL C.
=> [SYCL][Doc] Add kernel compiler extension spec

sycl/doc/extensions/proposed/sycl_ext_oneapi_prefetch.asciidoc
The compiler treats such code:
prefetch(ptr, 8)
as call to void prefetch(void *ptr, Properties properties = {}), instead of void prefetch(T* ptr, size_t count, Properties properties = {});
Adding constraints to avoid this.
=> [SYCL][DOC] Update sycl_ext_oneapi_prefetch

clang/test/SemaSYCL/lb_sm_90.cpp
After adding a warning on incorrect launch bounds sequences this comment needed updating.
A follow up from: https://github.com/intel/llvm/pull/11832/files/d26a275df28690cb556d90b1db6b0e1c545e5385#r1388272985
=> [SYCL][NFC] Update test comment

sycl/doc/extensions/proposed/sycl_ext_oneapi_enqueue_functions.asciidoc
Adds a new extension proposal to simplify enqueuing work to a device.
- Uses different function names for different use-cases.
- Uses free-functions instead of member functions.
- Requires developers to opt-in to the creation of event objects.
=> [SYCL][DOC] Add sycl_ext_oneapi_enqueue_functions

llvm/lib/SYCLLowerIR/GlobalOffset.cpp, llvm/test/CodeGen/AMDGPU/global-offset-removal.ll, llvm/test/CodeGen/NVPTX/global-offset-removal.ll
- Modify the globaloffset pass to remove calls to the `llvm.nvvm.implicit.offset` and `llvm.amdgcn.implicit.offset` from the IR during the SYCL  globaloffset pass when `-enable-global-offset=false`. 
Remove their respective uses, i.e. GEPs and Loads and replace further uses of the latter with 0 constants.
Ensure that these intrinsics do not occur anymore during target lowering.
Before, in some cases a compilation error was thrown because the intrinsic could not be selected for the AMDGPU and NVPTX targets.
Based on the inspection of the IR, any calls of the intrinsic were probably expected to be fully removed after the globaloffset pass.
- Replace Loads from the intrinsic with known constants and enable further optimization of the IR to remove dead code.
In our observed cases, several …
=> [SYCL][CUDA][HIP] Fix enable-global-offset flag

sycl/test-e2e/lit.cfg.py
That is intended to allow running the tests on a simulator (internally for now).
=> [SYCL][E2E] Use "run_launcher" for internal sycl-ls calls

sycl/doc/extensions/experimental/sycl_ext_matrix/sycl_ext_oneapi_matrix.asciidoc, sycl/doc/extensions/experimental/sycl_ext_oneapi_device_architecture.asciidoc, sycl/include/sycl/ext/oneapi/experimental/device_architecture.hpp, sycl/source/detail/device_info.hpp
As a minor addition, I also added tf32 combination to PVC as part of this PR
=> [SYCL][Matrix] Add GNR matrix combinations to spec and runtime query

sycl/include/sycl/ext/oneapi/experimental/annotated_arg/annotated_arg.hpp, sycl/include/sycl/ext/oneapi/experimental/annotated_ptr/annotated_ptr.hpp, sycl/include/sycl/ext/oneapi/experimental/annotated_ptr/annotated_ptr_properties.hpp, sycl/test/extensions/annotated_arg/annotated_arg_negative.cpp, sycl/test/extensions/annotated_arg/annotated_arg_properties.cpp
This change adds specific error messages for invalid properties that are specified on non pointer types. This change is directly in the header annotated_arg.hpp and these checks are done before the `check_property_list` check which previously accounted for this but had a generic error message. 
This change adds static asserts so that the error message specifies the invalid property and that it is invalid due to a non pointer type for the underlying data type.
For example, if the user tries to declare the following variable: 
```cpp
annotated_arg<int, decltype(properties{buffer_location<0>})> a;
```
The following error message is outputted: 
```
error: static assertion failed due to requirement '!has_buffer_location': Property buffer_location cannot be specified for annotated_arg<T> when T …
```
=> [SYCL] Specific error messages for invalid properties on non pointer types

sycl/plugins/unified_runtime/CMakeLists.txt, sycl/plugins/unified_runtime/pi2ur.hpp, sycl/source/backend.cpp, sycl/source/detail/context_impl.cpp
Pulls in fixes from https://github.com/oneapi-src/unified-runtime/pull/1044
=> [SYCL][UR] Combined CTS fixes for CL adapter.

sycl/include/sycl/ext/intel/esimd/detail/memory_intrin.hpp, sycl/include/sycl/ext/intel/esimd/memory.hpp, sycl/include/sycl/ext/intel/experimental/esimd/detail/memory_intrin.hpp, sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp, sycl/test-e2e/ESIMD/unified_memory_api/Inputs/block_store.hpp, sycl/test-e2e/ESIMD/unified_memory_api/block_store_acc.cpp, sycl/test-e2e/ESIMD/unified_memory_api/block_store_acc_pvc.cpp, sycl/test/esimd/memory_properties.cpp
This change implements the new compile time properties API for block_store with accessors.
I also updated the old E2E test to fix alignment issues, added compile-time tests and updated the naming of the old functions.
=> [SYCL][ESIMD] Implement unified memory API - block_store(acc,...)

llvm/test/tools/sycl-post-link/device-code-split/per-joint-matrix-1.ll, llvm/test/tools/sycl-post-link/device-code-split/per-joint-matrix-2.ll, llvm/test/tools/sycl-post-link/device-code-split/per-joint-matrix-3.ll, llvm/test/tools/sycl-post-link/device-code-split/per-joint-matrix-mad-1.ll, llvm/test/tools/sycl-post-link/device-code-split/per-joint-matrix-mad-2.ll, llvm/test/tools/sycl-post-link/device-code-split/per-joint-matrix-mad-3.ll, llvm/test/tools/sycl-post-link/device-code-split/per-joint-matrix-mad-4.ll, llvm/test/tools/sycl-post-link/device-code-split/per-joint-matrix-mad-5.ll, llvm/tools/sycl-post-link/ModuleSplitter.cpp
This patch implements device code split for `joint_matrix` and `joint_matrix_mad`.
Note: the data inside metadata values is sorted, so the order of matrix initialization in the C++ code is not relevant.
=> [SYCL][Joint Matrix] Implement code split for joint_matrix and joint_matrix_mad

clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/sycl-offload-aot.cpp, clang/test/Driver/sycl-spirv-ext.c
This extension is currently enabled for SYCL offloads to CPU backends. It will eventually be eventually be enabled by default for all backends.
Thanks
=> [SYCL][FPBuiltin][SPIRV] Enable SPV_INTEL_fp_max_error extension for SYCL offloads to CPU backends

sycl/plugins/cuda/CMakeLists.txt
This is a prerequisite for implementing dynamic loading of the CUPTI library when XPTI tracing is enabled.
See https://github.com/oneapi-src/unified-runtime/pull/1070
=> [SYCL][PI] Provide a preprocessor macro to locate the CUPTI library for XPTI tracing

libclc/amdgcn-amdhsa/libspirv/atomic/atomic_cmpxchg.cl, libclc/amdgcn-amdhsa/libspirv/atomic/atomic_helpers.h, libclc/amdgcn-amdhsa/libspirv/atomic/atomic_xor.cl
1. Fix a race condition in cmpxchg
2. Change `atomic_xor` to use a CAS loop instead of atomic builtin. This is needed to merge this in UR https://github.com/oneapi-src/unified-runtime/pull/936 so that perf regression can be fixed. The long term fix is to use a compiler flag to choose between builtin and safe CAS implementation, but talks upstream may take some time to figure out the details. See https://github.com/llvm/llvm-project/pull/69229
=> [HIP][libclc] Fix race in cmpxchg and change xor to use CAS instead of atomic builtin

sycl/doc/extensions/experimental/sycl_ext_oneapi_graph.asciidoc
The following features are defined in the specification as unsupported, but have working implementations merged upstream. This PR updates the graphs specification to reflect that and removes some trailing whitespace.
* https://github.com/intel/llvm/pull/11418
* https://github.com/intel/llvm/pull/11505
* https://github.com/intel/llvm/pull/11556
* https://github.com/intel/llvm/pull/11855
=> [SYCL][Graph][Doc] Update spec supported features

clang/test/CodeGenSYCL/add_ir_attributes_function_virtual.cpp, clang/test/CodeGenSYCL/device-indirectly-callable-attr.cpp
Affected by [clang][CodeGen] Ensure consistent mustprogress attribute emission
https://github.com/intel/llvm/commit/970bf07d0b184c7ec35
=> Updated tests after pulldown

.github/workflows/sycl_post_commit.yml, sycl/source/detail/kernel_bundle_impl.hpp, sycl/test-e2e/KernelCompiler/kernel_compiler.cpp, sycl/test-e2e/KernelCompiler/opencl_capabilities.cpp
During post-commit testing, the self build is failing with an `unused-private-field` error naming the `kernel_bundle_impl.Language` member as being unused. That member is only used in asserts right now in the existing code, so I am assuming this is the problem.   Here am I adding an explicit check that should avoid the error.
=> [SYCL] Address unused-private-field error 

clang/test/SemaSYCL/lb_sm_90.cpp
The current test will leave a temp file lb_sm_90.s in the source tree,
this will cause UNRESOLVED test in incremental builds.
=> [SYCL][NFC] Don't output file to source tree in lb_sm_90 test

llvm/lib/Target/ARM/ARMFastISel.cpp
=> [Opaque pointer] Recover ARM changes

sycl/include/sycl/ext/oneapi/experimental/annotated_usm/alloc_base.hpp, sycl/test-e2e/Annotated_usm/annotated_usm_align.cpp
This PR is a small change on the implementation of `aligned_alloc_annotated<T>`, which is a variant of the SYCL annotated USM allocation: 
https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/proposed/sycl_ext_oneapi_usm_malloc_properties.asciidoc
Right now `aligned_alloc_annotated<T>` is implemented by calling `sycl::aligned_alloc` (allocation in bytes) with a specified alignment (which is a combination (i.e. least common multiple) of the compile-time `alignment<K>` property and the runtime argument), and then cast the returned pointer type from `void *` to `T*`
This does not cover the case where T has a extended alignment as follows
```
struct alignas(256) MyStruct {
int x;
};
```
in this case, both the combined alignment and `alignof(T)` should be considered, and the greater …
=> [SYCL] Small patch on annotated USM allocation

sycl/include/sycl/ext/oneapi/bindless_images.hpp, sycl/test/extensions/bindless_images.cpp
This is 1st patch to enable SPIRV path for bindless_images so that we can start
generating SPIRV for testing purpose.
=> [SYCL][Bindless] Enable SPIRV path for bindless_images

sycl/include/sycl/ext/oneapi/experimental/annotated_arg/annotated_arg.hpp, sycl/include/sycl/ext/oneapi/experimental/annotated_ptr/annotated_ptr.hpp
annotated_arg/annotated_ptr are special classes and arguments of the __init() member function become kernel arguments. The classes have decorated_global_ptr or other such type applied on the class members to indicate that these must be in global address-space (or other address space as indicated by the applied type). The goal of applying the type on the member was to ensure that class member gets captured as a global address space pointer when set as kernel argument.
However, the type was applied on class constructor arguments as well. This PR restricts the type to only be present on the __init member function argument, otherwise the presence of the type on constructors causes functional errors on certain backends when objects are constructed in the kernel body. The object constructed …
=> [SYCL] Limit decorations to init function for annotated_arg/ptr classes

sycl/include/sycl/types.hpp
Parts of the vector implementation violates strict aliasing by representing vectors of certain types by another element type and reinterpret-casting to the right type to correctly pass references along. This may especially affect fundamental integral types that are not the default fixed-width integer type of the system.
=> [SYCL] Fix strict alias violations in vec representation

sycl/test-e2e/Basic/built-ins/host_math.cpp, sycl/test-e2e/Basic/built-ins/marray_common.cpp, sycl/test-e2e/Basic/built-ins/marray_geometric.cpp, sycl/test-e2e/Basic/built-ins/marray_math.cpp, sycl/test-e2e/Basic/built-ins/marray_relational.cpp, sycl/test-e2e/Basic/built-ins/vec_common.cpp, sycl/test-e2e/Basic/built-ins/vec_geometric.cpp, sycl/test-e2e/Basic/built-ins/vec_math.cpp, sycl/test-e2e/Basic/built-ins/vec_relational.cpp, sycl/test-e2e/DeviceLib/built-ins/nan.cpp, sycl/test-e2e/DeviceLib/built-ins/scalar_integer.cpp, sycl/test-e2e/USM/math.cpp, sycl/test/basic_tests/relational_builtins.cpp, sycl/test/basic_tests/types.cpp, sycl/test/basic_tests/valid_kernel_args.cpp, sycl/test/regression/abs_diff_host.cpp
The preview flag was intended to be used in a number of builtins tests but were not correctly added to the build steps. This commit amends these tests.
=> [SYCL][Tests] Fix preview flags in testing

sycl/test-e2e/Basic/spirv_device_obj_smoke.cpp
This test called clang++ directly. I think we need to use %clangxx
Thanks
=> [SYCL][test-e2e] Fix how clang++ is called

sycl/doc/extensions/experimental/sycl_ext_oneapi_bindless_images.asciidoc, sycl/include/sycl/ext/oneapi/bindless_images.hpp
- Constructors were added to the `sampled_image_handle` and `unsampled_image_handle` structs to allow creation of image handles from raw handles.
- Removed `sampler_handle` member from `sampled_image_handle` struct, awaiting the LevelZero and SPIR-V extensions to become more mature before deciding whether we need a sampler handle.
- Align naming of raw image handle members between specification and implementation.
=> [Bindless][Exp] Add constructors to image handle structs

.github/workflows/sycl_linux_precommit.yml, .github/workflows/sycl_post_commit.yml, .github/workflows/sycl_windows_precommit.yml
When we add `ignore-lint` label, CI will still run lint and show a failure despite we will ignore it and continue to do further tests.
Since we don't care about lint result, we should ignore running it to avoid wasting machine resource or causing confusion about check results.
=> [CI] Skip lint job when disable-lint is set 

sycl/plugins/unified_runtime/CMakeLists.txt
Pulls in the following fixes to the CUDA and HIP adapters:
* [HIP] Correctly set HIP Kernel Buffer Arguments 
* [HIP] Fix host/device synchronization 
* [HIP][CTS] Fix Device CTS failures 
* [HIP] Fix get mem size segfault 
* [HIP] Implement urMemImageGetInfo
* [HIP] Define all UR entry points
* [CUDA] Add support for binary type query
* [CUDA] Update hint functions to only return warnings instead of errors
=> [UR] Bump tag to 534071e52f84bad1dd7fb210a360414507f3b3ae

sycl/include/sycl/ext/intel/esimd/common.hpp, sycl/include/sycl/ext/intel/esimd/detail/memory_intrin.hpp, sycl/include/sycl/ext/intel/esimd/memory.hpp, sycl/include/sycl/ext/intel/experimental/esimd/common.hpp, sycl/include/sycl/ext/intel/experimental/esimd/detail/memory_intrin.hpp, sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp, sycl/test-e2e/ESIMD/fence.cpp
The new esimd::fence() accepts 3 template enum parameters and is usable only on DG2 and PVC.
It implements the subset of functionality supported by experimental::esimd::lsc_fence(). The functionality that was not included into the public version is a) not supported by hardware and/or GPU drivers
b) too specific and is too risky to use now.
=> [ESIMD] Add non-experimental version of fence() for DG2 and PVC

sycl/include/sycl/ext/intel/experimental/fpga_mem/fpga_mem.hpp
Currently the SPIRV translator has a hard time translating annotations that are in nested types. This bug is actively being worked on. 
In the mean time, this change removes class inheritance from `fpga_mem`, allowing SPIRV translator to properly translate annotations in more cases.
=> Removed inheritance in fpga_mem

mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLMathOps.td, mlir-sycl/lib/Conversion/SYCLToMath/SYCLToMath.cpp, polygeist/tools/cgeist/Lib/CGExpr.cc, polygeist/tools/cgeist/Lib/ValueCategory.cc, polygeist/tools/cgeist/Lib/ValueCategory.h, polygeist/tools/cgeist/Lib/clang-mlir.cc, polygeist/tools/cgeist/Lib/clang-mlir.h, polygeist/tools/cgeist/Lib/utils.cc, polygeist/tools/cgeist/Lib/utils.h, polygeist/tools/cgeist/Test/Verification/sycl/fastmath.cpp
Attach fast math flags to:
- Binary arithmetic operations
- Unary arithmetic operations
- `math.fma` operations
- `sycl.math.*` operations
=> [SYCL-MLIR] Attach fast math flags to codegened operations

sycl/test-e2e/FilterSelector/reuse.cpp, sycl/test-e2e/FilterSelector/select.cpp, sycl/test-e2e/FilterSelector/select_device.cpp, sycl/test-e2e/FilterSelector/select_device_acc.cpp, sycl/test-e2e/FilterSelector/select_device_cpu.cpp, sycl/test-e2e/FilterSelector/select_device_cuda.cpp, sycl/test-e2e/FilterSelector/select_device_level_zero.cpp, sycl/test-e2e/FilterSelector/select_device_opencl.cpp
Removed most uses of `std::cout` from `FilterSelector` E2E tests.
There is no need in positive or informational output in those tests: it is not displayed in CI logs when tests pass, it is not checked by tools like `FileCheck`, etc. Expectation is that less I/O will allow tests to pass quicker
=> [SYCL][NFC] Drop output from FilterSelector E2E tests

sycl/test-e2e/Basic/accessor/accessor.cpp, sycl/test-e2e/Basic/multi_ptr_legacy.cpp, sycl/test-e2e/Basic/parallel_for_offset_integral_t.cpp, sycl/test-e2e/Basic/vector_operators.cpp
Some tests check APIs which are deprecated and it is by design, because those APIs should still work. However, they produce a lot of noise by deprecation warnings.
Added corresponding macro to some of E2E tests to silence those warnings.
=> [SYCL][NFC] Silence deprecated API warnings in tests

sycl/doc/extensions/experimental/sycl_ext_oneapi_annotated_ptr.asciidoc, sycl/include/sycl/ext/oneapi/experimental/annotated_ptr/annotated_ptr.hpp
Fixed two issues:
1. For compound operators, there is an error in the specs. The `tmp = tmp Op rhs` statement is wrong since Op is defined as `+=` and for `+=` it will be `tmp = tmp += rhs`.  Correct the format
2. For compound operators and inc/dec operators, the old implementation is using the non-compound operator which is wrong.
i.e. If T is a customer type with only `+=` operator being defined,  when applying `+=` on `annotated_ref<T>`, the previous implementation errors out since there is no `+` defined in T.
3. Added the missing `const` to inc/dec operators
=> [SYCL] fix a behavior mismatch in ann_ptr operator

sycl/test-e2e/ESIMD/lsc/atomic_smoke.cpp, sycl/test-e2e/ESIMD/lsc/local_accessor_atomic_smoke.cpp
`to_string` helper using in several ESIMD tests didn't cover some of enumerations fully, thus causing warnings in tests.
=> [SYCL][NFC] Silence some warnings in ESIMD E2E tests

sycl/plugins/unified_runtime/CMakeLists.txt
Includes UR changes from [ [OpenCL] Fix memory leak and coverity issue with struct-to-array casts #1048 ](https://github.com/oneapi-src/unified-runtime/pull/1048).
=> [UR] Bump UR tag to 04799e7 to get OpenCL adapter fixes

sycl/include/sycl/ext/oneapi/bindless_images.hpp
- A declaration of `free_image_mem` incorrectly took `sycl::device` as a parameter, which should have been a `sycl::queue`. This is now fixed.
=> [SYCL][Bindless][Exp] Fix free_image_mem declaration

sycl/test-e2e/Matrix/XMX8/element_wise_all_sizes.cpp
This commit disables the Matrix/XMX8/element_wise_all_sizes.cpp on DG2. It was already known to fail, but has also been seen to regularly time out in CI.
=> [SYCL][E2E] Disable Matrix/XMX8/element_wise_all_sizes.cpp on DG2

sycl/include/sycl/types.hpp, sycl/test-e2e/Regression/vec_logical_ops.cpp
Adds a special case logical operator implementation for device code using `std::array`. Fixes #11903.
=> [SYCL] Fix `operator||` and `operator&&` in `vec`

sycl/source/detail/graph_impl.hpp, sycl/test-e2e/Graph/Inputs/debug_print_graph.cpp
Some nodes may not have any associated CommandGroup, e.g. empty nodes. 
This PR therefore changes the way node IDs are assigned in the printed graph. 
Node IDs are now based on the Node address instead of the CommandGroup address. 
The test has been update to generate a node without a CommandGroup.
=> [SYCL][Graph] Fix bug with debug print graph feature

sycl/include/sycl/ext/intel/esimd/memory.hpp, sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp, sycl/test-e2e/ESIMD/unified_memory_api/Inputs/atomic_update.hpp, sycl/test/esimd/memory_properties.cpp
atomic_update API with accessors and one operand. Next is two operands.
I also fixed a problem where we weren't passing props down, it should be noop right now but maybe in the future it will matter.
=> [SYCL][ESIMD] Implement unified memory API - atomic_update(acc,...) with one operand

mlir/lib/Dialect/LLVMIR/IR/LLVMTypes.cpp
In https://github.com/intel/llvm/commit/d49d83e79ca0b59c3d68ff6c46eea69d848b0617, `getCallableResults`/`getResultTypes` changed to return `{}` instead of `LLVMVoidType` for functions that return `void`. 
When `insertArgument()` is invoked, `getTypeWithArgsAndResults()` is indirectly invoked, which then calls `LLVMFunctionType::clone()` with the result of `getResultTypes()` as result type. `LLVMFunctionType::clone()` expects exactly one result type. After d49d83e79ca0b59c3d68ff6c46eea69d848b0617, the number of result types becomes 0.
This PR modifies `LLVMFunctionType::clone()` to allow 0 result types.
=> [GENX] Allow cloning function with void return type

llvm/lib/SYCLLowerIR/ESIMD/ESIMDVerifier.cpp, sycl/test-e2e/InvokeSimd/Regression/address_space_cast.cpp
=> [SYCL][ESIMD] Support sycl::address_space_cast

mlir/include/mlir/Dialect/LLVMIR/GENXOps.td, mlir/lib/Dialect/LLVMIR/IR/GENXOps.cpp, mlir/test/Dialect/LLVMIR/genx-invalid.mlir, mlir/test/Dialect/LLVMIR/genx.mlir, mlir/test/Target/LLVMIR/genx.mlir
1. Added restrictions and corresponding tests for input type, tile_width and tile_height
2. Made tile_height, tile_width and type corrections in existing genx.mlir tests
=> [MLIR][GENX] Add additional verification for genx.matrix.2Dblockstore and load

sycl/test-e2e/Basic/vector/int-convert.cpp, sycl/test-e2e/DeviceLib/built-ins/scalar_integer.cpp, sycl/test-e2e/PreviewBreakingChanges/preview_lib_marker.cpp, sycl/test-e2e/Regression/vec_logical_ops.cpp, sycl/test-e2e/USM/math.cpp, sycl/test-e2e/format.py, sycl/test-e2e/lit.cfg.py
The preview flag testing for E2E testing is currently broken. https://github.com/intel/llvm/pull/11929 attempts to fix it but has shown that some breakages in CUDA and HIP have been hidden behind the broken testing. To allow for proper testing while these failures are being investigated, this PR implements the fixes from https://github.com/intel/llvm/pull/11929 with the caveat that they do not apply when HIP and CUDA devices are part of the testing. This is a temporary solution and does *not* replace https://github.com/intel/llvm/pull/11929.
=> [SYCL][E2E] Fix preview flag testing for non-HIP and non-CUDA devices

sycl/test-e2e/lit.cfg.py
This commit refactors the way we define source programs used to detect the availability of libraries in SYCL e2e LIT testing.
Suggestion by @ldrumm in https://github.com/intel/llvm/pull/11929#discussion_r1402353788.
=> [SYCL][E2E][NFC] Refactor library detection sources

sycl/source/detail/kernel_bundle_impl.hpp, sycl/test-e2e/KernelCompiler/kernel_compiler.cpp, sycl/test-e2e/KernelCompiler/opencl_capabilities.cpp
piProgramBuild must be called with a device list, not individually. BUT no backend presently supports kernel compilation across multiple devices, so the test ensures that any queue/context instantiated is limited to just one device.
=> [SYCL] kernel_compiler and device lists.

mlir/include/mlir/Dialect/LLVMIR/GENXOps.td, mlir/lib/Target/LLVMIR/Dialect/GENX/GENXToLLVMIRTranslation.cpp, mlir/test/Dialect/LLVMIR/genx-invalid.mlir, mlir/test/Dialect/LLVMIR/genx.mlir, mlir/test/Target/LLVMIR/genx.mlir
Add a new operation to the GENX dialect to handle floating point to floating point conversion. 
This operation exposes the following IGC intrinsic functions:
- GenISA_ftof_rte   // round to nearest
- GenISA_ftof_rtn   // round toward negative
- GenISA_ftof_rtp   // round toward positive
- GenISA_ftof_rtz   // round toward zero
=> [GENX]: Add `genx.conv.fptofp` operation

sycl/source/detail/queue_impl.cpp, sycl/unittests/Extensions/CommandGraph.cpp
Throws a invalid exception when memset queue shortcut is used during graph recording since memset is not supported by the current graph implementation. 
Adds a unitest checking that the exception is correctly thrown.
Addresses issue #11940
=> [SYCL][Graph] Add missing exception for USM memset

sycl/doc/extensions/proposed/sycl_ext_oneapi_free_function_queries.asciidoc
Sentence in `sycl_ext_oneapi_free_function_queries` specification had an extra "that".
=> [SYCL][Doc] Fix minor typo in free function queries

sycl/doc/design/DeviceLibExtensions.rst
This PR fixes typo in devicelib extension doc. In doc, we uses the term "cl_intel_devicelib_cassert" but we use "cl_intel_devicelib_assert" in sycl runtime and devicelib implementation. And for other cl_intel_devicelib_* extension aiming to support CXX std library such as math and complex functions, we use "cl_intel_devicelib_math", "cl_intel_devicelib_complex".
To align with other "cl_intel_devicelib_*" extension and sycl runtime& devicelib implementation, we change "cl_intel_devicelib_cassert" to "cl_intel_devicelib_assert".
=> [SYCL] Fix typo in DeviceLibExtension doc

sycl/doc/extensions/experimental/sycl_ext_oneapi_kernel_compiler_opencl.asciidoc
Fix some minor spec problems I noticed while preparing a larger change. None of these affect the implementation.
=> Editorial fixes to opencl kernel compiler spec

sycl/source/detail/graph_impl.cpp, sycl/source/detail/graph_impl.hpp, sycl/source/handler.cpp, sycl/unittests/Extensions/CommandGraph.cpp
The implementation of ext_oneapi_submit_barrier involved exponential slowdown due to unnecessary extra dependencies to barrier nodes. This PR solves this issue by:
1) improving the function that searches for graph leaves (exit nodes) 
2) removing unnecessary dependencies to previous barriers when adding new nodes.
Addresses Issue: #11915
=> [SYCL][Graph] Fixes enqueue barrier slowdown

opencl/opencl-aot/source/main.cpp
This patch fixes a regression in error reporting, previously compiler build log was printed to `std::cerr`, but now it doesn't print by default. It makes it difficult for developers to understand what's going on. So now the compiler build log is printed to `std::cerr` if there is an error message, and to verbose logs if compilation was successful but there is something in the compiler build logs.
=> [opencl-aot] Fix regression in error reporting

sycl/doc/extensions/experimental/sycl_ext_oneapi_kernel_compiler.asciidoc, sycl/doc/extensions/experimental/sycl_ext_oneapi_kernel_compiler_opencl.asciidoc
In #11861 we decided to remove the ability to get the `kernel` object for a free-function kernel using a type-name.  Therefore, we don't need this ability in online-compiled kernels either.  Remove the associated wording from the kernel compiler specs.
=> [SYCL][Doc]Remove APIs to get kernel by type-name

llvm/lib/SYCLLowerIR/ESIMD/LowerESIMD.cpp, llvm/test/SYCLLowerIR/ESIMD/optnone.ll
Previously we never had optnone in the SPIR-V due to the issue in https://github.com/intel/llvm/commit/993fe5b31b43911a903463e414f1daf1ab81337c, but with that fixed we started seeing it and that broke some O0 tests.
=> [SYCL][ESIMD] Remove optnone from ESIMD functions

clang/test/Driver/linker-wrapper-sycl.cpp
There are some build configuration when compiler tools could get picked up from different locations. For this particular test, checking for PATH of these tools is not required. Hence, we are removing the check.
Thanks
=> [TEST_UPDATE_ONLY][NEW_OFFLOAD][CLANG_TOOLS] Remove unnecessary PATH checking

clang/include/clang/Basic/DiagnosticDriverKinds.td, clang/include/clang/Basic/DiagnosticGroups.td, clang/lib/Frontend/CompilerInvocation.cpp, clang/test/CodeGen/fp-accuracy.c, clang/test/Driver/fp-accuracy.c
This implements a new request to make the last fp-accuracy option on the command line wins.
A warning is generated to warn the user.
=> [SYCL] Last fp-accuracy command line wins.

clang/include/clang/Basic/DiagnosticGroups.td, clang/include/clang/Basic/DiagnosticSemaKinds.td, clang/test/SemaSYCL/reqd-sub-group-size-silence-warnings.cpp
As a follow up to https://github.com/intel/llvm/pull/11687, this PR adds a mechanism to silence the warning using dedicated switch `-Wno-incorrect-sub-group-size` that is wrapped in the `-Wno-attribute` group.
=> [SYCL] Provide a mechanism to silence incorrect sub group size warning

sycl/source/detail/kernel_bundle_impl.hpp, sycl/source/detail/kernel_impl.cpp, sycl/source/detail/kernel_impl.hpp, sycl/source/detail/program_manager/program_manager.cpp, sycl/source/detail/scheduler/commands.cpp, sycl/test-e2e/KernelAndProgram/disable-caching.cpp
In #11751, ref counting of kernels objects was changed to be more accurate in order to allow for in-memory caching to be disabled. When getting a kernel form the cache, the ref count the kernel handle is now incremented (when caching is enabled). Thus, a method like `ProgramManager::getOrCreateKernel` will increment the ref count of the kernel it gets. However, in `enqueueImpKernel`, when enqueuing a kernel with a kernel bundle,`ProgramManager::getOrCreateKernel` is called twice, first indirectly by:
https://github.com/intel/llvm/blob/c43a90f28eebfcdf1bc1d55430485e2834790a60/sycl/source/detail/scheduler/commands.cpp#L2527-L2528
and second directly by:
https://github.com/intel/llvm/blob/c43a90f28eebfcdf1bc1d55430485e2834790a60/sycl/source/detail/scheduler/commands.cpp#L2538-L2548
This …
=> [SYCL] Fix issue of acquring kernel twice

sycl/test-e2e/Regression/vec_rel_swizzle_ops.cpp
The commit introducing vec_rel_swizzle_ops missed testing with the preview options due to a fix happening in the interrim. It is supposed to build with the %{build} tag to ensure CUDA and HIP are built with the correct target binaries. This commit fixes this issue.
=> [SYCL][E2E] Fix preview testing of vec_rel_swizzle_ops

sycl/source/detail/scheduler/scheduler.cpp
Full cleanup for fusion placeholder commands is handled by specialized scheduler entry points (`start_fusion`, `cleanUPCmdFusion`). To avoid interference with that mechanism, fusion commands should not be added to the deferred cleanup list.
=> [SYCL][Fusion] Avoid deferred cleanup for fusion

sycl/include/sycl/accessor.hpp
image_accessor constructor was generating following IR in O0 mode:
```
store target("spirv.Image", void, 1, 0, 0, 0, 0, 0, 0) zeroinitializer, ptr addrspace(4) %MImageObj, align 8
```
As a target extension type, spirv.Image currently allows zeroinit.
However, OpConstantNull in spirv spec doesn't allow image type.
Therefore, we're not able to get sycl 1.2.1 image working in O0 mode.
This PR solves the issue by not initializing MImageObj.
=> [SYCL] Don't zero-initialize MImageObj in 1.2.1 image

sycl/test-e2e/Basic/vector/int-convert.cpp
The test sporadically timed out on Windows because default implicit context is disabled in there.
Due to the fact that separate `queue` object was create for every kernel, it caused full re-JIT of the whole device code.
Refactored the test to use a single queue object explicitly to have context and all associated caches to be shared between all kernels in the test.
This resolves intel/llvm#12011
=> [SYCL][NFC] Optimize int-convert.cpp test

sycl/test-e2e/Basic/nested_queue_submit.cpp
Because SYCL will throw an exception, malloced `ptr` will never freed, which is a leak. Use std::vector to make it freed automatically.
=> [SYCL][E2E] fix one test leak

sycl/test-e2e/ESIMD/unified_memory_api/Inputs/block_store.hpp
Originally it seemed the problem was only on Windows, but it seems it happens on Linux too, see [here](https://github.com/intel/llvm/pull/11921#issuecomment-1836638347).
I manually verified it fails consistently before this version and passes consistently after this version.
=> [SYCL][ESIMD][E2E] Add Linux driver version requirement to block_store_slm_acc.cpp

sycl/source/detail/jit_compiler.cpp, sycl/test-e2e/KernelFusion/abort_fusion.cpp
Previously, fusion would fail because an empty list of ND ranges is determined to be incompatible.
=> [SYCL][Fusion] Stop fusion attempt early if nothing is enqueued

sycl/include/sycl/ext/intel/esimd/detail/intrin.hpp, sycl/include/sycl/ext/intel/esimd/detail/simd_obj_impl.hpp, sycl/test/esimd/wrregion.cpp
It is still not prohibited to create 'simd_view' that views beyond the bounds of viewed 'simd' object. And it is not yet prohibited to read using such 'simd_view' object, but the commit 17f893972bed74c1c6e147291edefa78ba16181c prohibited writing beyong simd bounds. The error message was difficult to read and did not give any guidance on the proposed fix.
The old error message only said that __esimd_wrregion call could not be matched. The newly added static assert says that the viewed object in LHS does not fit the value in RHS.
Example of problem situation:
simd<float, 16> vec; // vec is only 16-elements
auto vec_too_bit_view = vec.select<128, 1>();// 128-elems - too many
vec_too_bit_view = simd<float, 128>{0}; //error: write 128-elem to
16-elem storage
=> [ESIMD] Add more user-friendly error msg when write beyond simd obj

sycl/test-e2e/ESIMD/unified_memory_api/atomic_update_acc_pvc.cpp, sycl/test-e2e/ESIMD/unified_memory_api/atomic_update_acc_pvc_stateless.cpp
It's slow so let's at least split the stateless/stateful into separate tests.
=> [SYCL][ESIMD][E2E] Split atomic_update_acc_pvc.cpp into two tests

sycl/test-e2e/ESIMD/unified_memory_api/Inputs/block_load.hpp, sycl/test-e2e/ESIMD/unified_memory_api/Inputs/common.hpp, sycl/test-e2e/ESIMD/unified_memory_api/block_load_acc.cpp, sycl/test-e2e/ESIMD/unified_memory_api/block_load_acc_dg2.cpp, sycl/test-e2e/ESIMD/unified_memory_api/block_load_acc_pvc.cpp, sycl/test-e2e/ESIMD/unified_memory_api/block_load_slm.cpp, sycl/test-e2e/ESIMD/unified_memory_api/block_load_slm_acc_dg2.cpp, sycl/test-e2e/ESIMD/unified_memory_api/block_load_slm_acc_pvc.cpp, sycl/test-e2e/ESIMD/unified_memory_api/block_load_slm_dg2.cpp, sycl/test-e2e/ESIMD/unified_memory_api/block_load_usm.cpp, sycl/test-e2e/ESIMD/unified_memory_api/block_load_usm_dg2.cpp
I added DG2 versions of the block_load unified memory tests. I only did one type of test so we could discuss if this way of doing it is what we want to do.
I manually tested this on DG2 Linux and Windows and PVC Linux.
=> [SYCL][ESIMD][E2E] Add DG2 unified memory block_load tests

clang/test/Driver/clang-offload-wrapper-exe.cpp
Fix a test compilation error with g++ 13 on Ubuntu 23.10. Replace also a C header include with the official C++ one.
Bug context:
```
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/llvm/clang/test/Driver/clang-offload-wrapper-exe.cpp:55:3: error: unknown type name 'uint32_t'
55 |   uint32_t Type;    // pi_property_type
|   ^
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/llvm/clang/test/Driver/clang-offload-wrapper-exe.cpp:56:3: error: unknown type name 'uint64_t'
56 |   uint64_t ValSize; // size of property value in bytes
|   ^
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/llvm/clang/test/Driver/clang-offload-wrapper-exe.cpp:70:3: error: unknown type name 'uint16_t'
70 |   uint16_t Version;
|   ^
/home/rkeryell/Xilinx/Projects/LLVM/worktrees/intel/llvm/clang/test/Driver/cl …
```
=> [SYCL] Missing C++ cstdint include

mlir/lib/Analysis/DataFlow/IntegerRangeAnalysis.cpp, mlir/test/Dialect/Arith/int-range-interface.mlir
- Remove not needed headers being included
- Fix `check-mlir` due to variable being used in label in test
=> [SYCL-MLIR][NFC] Adapt `IntegerRangeAnalysis` changes for upstreaming

sycl/CMakeLists.txt
`mlir-translate` is needed to perform SYCL host code raising. Add to `deploy-sycl-toolchain`.
=> [SYCL-MLIR] Add `mlir-translate` to `deploy-sycl-toolchain`

sycl/test-e2e/Matrix/XMX8/element_wise_all_sizes_no_split.cpp
This patch adds version of element_wise_all_sizes.cpp test with disabled device code split. It is known that the code with disabled device code split fails on GPU due to a bug in IGC. We need to test such case.
=> [SYCL][Matrix][E2E] Add element_wise_all_sizes_no_split.cpp test

llvm/utils/git/requirements.txt
This fixes https://github.com/intel/llvm/security/dependabot/39
=> Update cryptography version in requirements.txt

sycl/test-e2e/ESIMD/unified_memory_api/Inputs/block_store.hpp, sycl/test-e2e/ESIMD/unified_memory_api/block_store_acc.cpp, sycl/test-e2e/ESIMD/unified_memory_api/block_store_acc_dg2.cpp, sycl/test-e2e/ESIMD/unified_memory_api/block_store_slm_acc.cpp, sycl/test-e2e/ESIMD/unified_memory_api/block_store_slm_acc_dg2.cpp, sycl/test-e2e/ESIMD/unified_memory_api/block_store_slm_acc_pvc.cpp, sycl/test-e2e/ESIMD/unified_memory_api/block_store_slm_dg2.cpp, sycl/test-e2e/ESIMD/unified_memory_api/block_store_slm_pvc.cpp, sycl/test-e2e/ESIMD/unified_memory_api/block_store_usm.cpp, sycl/test-e2e/ESIMD/unified_memory_api/block_store_usm_dg2.cpp
DG2 tests for block_store, I ran tests manually on PVC Linux and DG2 Linux/Windows
The SLM accessor tests fail everywhere on DG2 on both Linux and Windows, so I just disabled them directly because the runtime driver check ends up being complicated, and none of the drivers, not even bleeding edge, work. I will file an internal bug for this.
=> [SYCL][ESIMD][E2E] Add DG2 unified memory block_store tests

sycl/source/detail/device_info.hpp
The goal of changing macros to constexpr array of pairs is to have an ability to better maintain this data in the internal project.
=> [SYCL][NFC] Refactor device architecture data structures

sycl-fusion/common/lib/NDRangesHelper.cpp, sycl-fusion/jit-compiler/lib/KernelFusion.cpp, sycl/test-e2e/KernelFusion/abort_fusion.cpp
Some ND-ranges combinations may result in non-uniform work-group sizes in the fused ND-range, e.g., fusing `{{9}, {3}}` and `{512}` would yield `{{512}, {3}}`. Abort fusion in these cases.
=> [SYCL][Fusion] Abort fusion on non-uniform work-group sizes ND-range

sycl/plugins/unified_runtime/CMakeLists.txt
Combines the changes of the follow Unified Runtime pull requests:
* https://github.com/oneapi-src/unified-runtime/pull/1108
* https://github.com/oneapi-src/unified-runtime/pull/988
* https://github.com/oneapi-src/unified-runtime/pull/1071
* https://github.com/oneapi-src/unified-runtime/pull/916
* https://github.com/oneapi-src/unified-runtime/pull/1099
=> [UR] Bump tag to ce4acbc4

clang/lib/Driver/ToolChains/SYCL.cpp, clang/test/Driver/sycl-offload-aot.cpp, clang/test/Driver/sycl-offload.c, sycl/test-e2e/Basic/float_division_precise.cpp
This commit makes the driver pass
`-cl-fp32-correctly-rounded-divide-sqrt` as backend compiler options for SPIR-V targets when the `-fpp-model=precise` option is used.
=> [SYCL][Driver] Force precise division rounding for precise model

sycl/test-e2e/Basic/get_backend.cpp
It seems to fail always as reported in the below bug.
Just XFAIL it for now until we get a new driver, I locally reproduced the issue with the current syclos driver and saw it passing with a newer driver.
Closes: https://github.com/intel/llvm/issues/12117
=> [SYCL][E2E] Mark get_backend.cpp as XFAIL on DG2

sycl/doc/extensions/proposed/sycl_ext_oneapi_raw_kernel_arg.asciidoc
First draft of an extension allowing opaque types to be passed to kernels via their raw byte representation.
=> [SYCL][Doc] Add sycl_ext_oneapi_raw_kernel_arg

sycl/source/detail/kernel_bundle_impl.hpp
CreateProgram and CreateKernel APIs implicitly retain program and kernels. Extra call to retain is incorrect.
=> [SYCL] Fix kernel_compiler leak.

llvm/include/llvm/SYCLLowerIR/GlobalOffset.h, llvm/lib/SYCLLowerIR/GlobalOffset.cpp, llvm/test/CodeGen/AMDGPU/global-offset-dbg.ll, llvm/test/CodeGen/AMDGPU/global-offset-intrinsic-function-mix.ll, llvm/test/CodeGen/AMDGPU/global-offset-multiple-calls-from-one-function.ll, llvm/test/CodeGen/AMDGPU/global-offset-multiple-entry-points.ll, llvm/test/CodeGen/AMDGPU/global-offset-simple.ll, llvm/test/CodeGen/NVPTX/global-offset-dbg.ll, llvm/test/CodeGen/NVPTX/global-offset-intrinsic-function-mix.ll, llvm/test/CodeGen/NVPTX/global-offset-multiple-calls-from-one-function.ll, llvm/test/CodeGen/NVPTX/global-offset-multiple-entry-points.ll, llvm/test/CodeGen/NVPTX/global-offset-simple.ll
Extend #11674 by modifying the globaloffset optimization pass to always
replace uses of Loads from the `llvm.nvvm.implicit.offset` and
`llvm.amdgcn.implicit.offset intrinsics` with constant zeros in the
original non-offset kernel.
Hence, perform the optimization even when
`-enable-global-offset=true` (default).
Duplicate recursively functions containing calls to the implicit offset
intrinsic and let the implicit offset kernel entry point only call
the original functions (i.e. do not call the functions with added offset
arguments).
Remove zero allocations for the original kernel entry points.
=>  [SYCL] Extend global offset intrinsic removal

sycl/test-e2e/Basic/get_backend.cpp
It passes with a newer driver so just check for that.
=> [SYCL][E2E] Move XFAIL to driver check in get_backend.cpp

sycl/test-e2e/Graph/Explicit/work_group_size_prop.cpp, sycl/test-e2e/Graph/RecordReplay/work_group_size_prop.cpp
The CI E2E tests are failing because these tests are passing rather than expectedly failing
* UR nightly CI - https://github.com/oneapi-src/unified-runtime/actions/runs/7160854862/job/19495692574
* intel/llvm CI - https://github.com/intel/llvm/actions/runs/7168248741/job/19516014849
Change the tests to be skipped rather than XFAIL while we investigate
=> [SYCL][Graph] Change property test to unsupported on CUDA

sycl/test-e2e/Basic/float_division_precise.cpp
This commit fixes the flag passed to the compiler when using the MSVC-compatible compiler options.
=> [SYCL][E2E] Fix floating point division precision test on MSVC

sycl/test-e2e/DeviceLib/string_test.cpp
It's passing now so the XFAIL is causing every postcommit run to fail.
=> [SYCL][E2E] Enable string_test.cpp on DG2

sycl/source/detail/graph_impl.cpp, sycl/source/detail/scheduler/commands.cpp, sycl/test-e2e/Graph/Explicit/work_group_size_prop.cpp, sycl/test-e2e/Graph/Inputs/work_group_size_prop.cpp, sycl/test-e2e/Graph/RecordReplay/work_group_size_prop.cpp
Fixes kernel property tests.
Improves PI exception messages.
Removes queue clearing in the executable graph destructor as this is already done by the modifiable graph destructor.
Fixes the temporary disabling of kernel prop test performed by https://github.com/intel/llvm/pull/12137
=> [SYCL][Graph] Kernel property bugfix

clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/sycl-offload-new-driver.c
Right now we use `--`, but in `clang-linker-wrapper` we use the clang Arg infrastructure to match them, and that requires `-`.
At least for me every invocation of SYCL with the new offload model hits this problem. After this, at least `clang-linker-wrapper` gets further and we get some `sycl-post-link` error which I'll look at next.
=> [Driver][SYCL][clang-linker-wrapper] Fix sycl device library arguments

sycl/source/backend/level_zero.cpp, sycl/source/detail/context_impl.cpp, sycl/source/detail/context_impl.hpp, sycl/test-e2e/Basic/interop/ze_context_device.cpp
The Level Zero make_context accepts a vector of SYCL devices. Those devices were not being propagated to the created context, which led to an error during queue creation.
This patch fixes the problem by forwarding those devices to the context constructor.
=> [SYCL] Fix device handling during interop L0 context creation

clang/include/clang/Driver/Action.h, clang/lib/Driver/Driver.cpp, clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/sycl-offload-intelfpga-emu.cpp, clang/test/Driver/sycl-offload-intelfpga-link.cpp
Updates were performed for AOCX/AOCR usage and creation to better support the symbols and properties retention when using -fsycl-link. These changes were not fully Windows supported due to the restrictions in creating libraries.
Fix this situation to create objects that can be added to the Windows library as opposed to just a bundled IR file.
=> [Driver][SYCL] Update aocx/aocr binary usage

sycl/doc/extensions/supported/sycl_ext_intel_cslice.asciidoc, sycl/doc/extensions/supported/sycl_ext_intel_queue_index.asciidoc
The correct name is "Intel(R) Data Center GPU Max Series".
=> [SYCL][Doc] Use correct product name in extensions

sycl/test-e2e/Basic/built-ins/marray_math.cpp
Add missing math functions defined in the sycl::half_precision namespace. Thank you for your review.
=> [SYCL][E2E] Add sycl::half_precision math functions to marray_math.cpp

sycl/test-e2e/Basic/query_emulate_subdevice.cpp
Remove outdated and unstable test Basic/query_emulate_subdevice.cpp. It uses untested, unsupported and partially working debug features of NEO RT. Instead, Basic/query.cpp is using to query real subdevices of discrete graphics cards.
=> [SYCL][E2E] Remove Basic/query_emulate_subdevice.cpp

clang/test/SemaSYCL/attr-syclglobalvar.cpp
This patch updates LIT test by using the sycl.hpp header that uses "#" syntax instead of @Inputs/sycl.hpp@LINE
Fixes https://github.com/intel/llvm/issues/3415
=> [NFC][Sema] Update test

sycl/source/detail/scheduler/commands.cpp, sycl/source/detail/scheduler/commands.hpp, sycl/source/handler.cpp
`signal` can't be emit if no new dependency is added to the dependency graph, based on current implementation. This PR address this issue.
=> [SYCL][XPTI] Emit XPTI signal when new kernel is submitted

sycl/plugins/unified_runtime/CMakeLists.txt
Without the keyword `EXISTS` it just tests if the string is not empty, which it will never be.
Also fix a typo and formatting of the error message.
=> [UR] Fix CMake for in-tree UR checkout

libclc/CMakeLists.txt, sycl/doc/GetStartedGuide.md
Use `LIBCLC_CUSTOM_LLVM_TOOLS_BINARY_DIR` to specify the location of custom toolchain to be used for creation of libclc. This helps with debug build times:
* debug build of sycl-toolchain with libclc built with debug tools:
```sh                                                                                    
$ for f in $(ls lib/clc/*.bc); touch $f; time ninja sycl-toolchain
[0/2] Re-checking globbed directories...                                              
[6/6] Generating ../../lib/clc/remangled-l64-signed_char.libspirv-amdgcn-amd-amdhsa.bc
ninja sycl-toolchain  682.55s user 1.33s system 112% cpu 10:07.81 total               
```
* debug build of sycl-toolchain with libclc built with release tools:
```sh
$ for f in $(ls lib/clc/*.bc); touch $f; time ninja sycl-toolchain 
[0/2] …
```
=> [SYCL][LIBCLC] Allow custom tools location when building libclc

sycl/source/detail/device_info.hpp, sycl/source/detail/queue_impl.hpp, sycl/test-e2e/KernelFusion/lit.local.cfg, sycl/unittests/Extensions/CommandGraph.cpp
The kernel fusion extension document says that an error will be thrown if a `queue` is constructed with `sycl::ext::codeplay::experimental::property::queue::enable_fusion`, but the underlying device does not support fusion (i.e., returns false for `get_info<sycl::ext::codeplay::experimental::info::device::supports_fusion>()`). This change implements this behavior.
Also, kernel fusion is currently not supported for SYCL devices of device type accelerator, as devices such as FPGAs do not support JIT compilation at runtime. Therefore, mark all end-to-end tests related to kernel fusion as unsupported for devices of type accelerator.
In addition, use the newly created file to make the fact that kernel fusion is currently unsupported on Windows more explicit.
=> [SYCL][Fusion] Error if fusion unsupported on device

sycl/test-e2e/ESIMD/slm_init_no_inline.cpp
We actually need a later driver, I manually verified this.
=> [SYCL][ESIMD][E2E] Fix driver check in slm_init_no_inline.cpp

sycl/plugins/unified_runtime/CMakeLists.txt
UR PR https://github.com/oneapi-src/unified-runtime/pull/1185
=> [UR] Pull in patch for coverity issues in CL, hip and cuda adapters.

sycl/include/sycl/backend_types.hpp, sycl/source/backend.cpp, sycl/source/detail/config.cpp, sycl/source/detail/pi.cpp, sycl/test-e2e/Basic/get_backend.cpp, sycl/test-e2e/Regression/device_num.cpp
Renames the `ext_native_cpu` backend type to `ext_oneapi_native_cpu`, making it conformant to the SYCL specification.
=> [SYCL][NATIVECPU]Rename ext_native_cpu to ext_oneapi_native_cpu

.github/workflows/pr-code-format.yml
To experiment with the suggestion in https://github.com/intel/llvm/discussions/12085.
Note that `pull_request_target` means we cannot test this before we merge it.
=> [CI] Enable pr-code-format workflow for intel/llvm repo

sycl/test-e2e/bindless_images/mipmap/mipmap_read_1D.cpp, sycl/test-e2e/bindless_images/mipmap/mipmap_read_2D.cpp, sycl/test-e2e/bindless_images/mipmap/mipmap_read_3D.cpp, sycl/test-e2e/bindless_images/sampling_1D.cpp, sycl/test-e2e/bindless_images/sampling_2D.cpp, sycl/test-e2e/bindless_images/sampling_2D_USM_shared.cpp, sycl/test-e2e/bindless_images/sampling_2D_half.cpp, sycl/test-e2e/bindless_images/sampling_3D.cpp, sycl/test-e2e/bindless_images/user_types/mipmap_read_user_type_2D.cpp, sycl/test-e2e/bindless_images/vulkan_interop/sampled_images.cpp
double type needs -ze-fp64-gen-emu compile flag on DG2. Adding the flag each time is inconvenient for testing.
=> [NFC][SYCL][Bindless] Don't use double type in e2e tests

sycl/source/event.cpp, sycl/unittests/Extensions/CommandGraph.cpp
Throws an appropriate message if profiling is called on an event returned from a queue in record mode. 
Adds a test to check the exception message thrown.
=> [SYCL][Graph] Exception if profiling is called on an event returned from a queue in record mode.

sycl/test/basic_tests/marray/marray.cpp
This patch https://github.com/llvm/llvm-project/pull/75332 would report narrowing conversions with const references, which could lead to "error: constant expression evaluates to 2 which cannot be narrowed to type 'bool'".
=> Avoid sema error in test case

clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/sycl-native-cpu-fsycl.cpp
Similarly to NVPTX and AMD, Native CPU needs to not set ` -emit-only-kernels-as-entry-point` since kernels for this target are not identified by the calling convention.
=> [SYCL] [NATIVECPU] Avoid passing -emit-only-kernels-as-entry-point on native cpu

.github/workflows/pr-code-format.yml
There is bug in this workflow, it fails if we have too many changed files.
eg:
https://github.com/intel/llvm/actions/runs/7291149287/job/19869497941?pr=12226
We also want it to respect the label.
=> [CI] Respect disable-lint in pr-code-format workflow

sycl/test-e2e/ESIMD/unified_memory_api/Inputs/block_store.hpp
We should be using `Size` like the rest of the tests.
=> [SYCL][ESIMD][E2E] Fix unified memory block_store local accessor test

sycl/doc/extensions/proposed/sycl_ext_oneapi_composite_device.asciidoc
Add an extension specification for new APIs that allow an application
to access card-level devices on PVC.
=> [SYCL][Doc] Extension spec for composite devices

sycl/test-e2e/ESIMD/unified_memory_api/block_store_slm_acc.cpp, sycl/test-e2e/ESIMD/unified_memory_api/block_store_slm_acc_dg2.cpp
I should have done this in https://github.com/intel/llvm/commit/a8d6290ef7358257f68317f26981fe086d19bfd2, with the test fixed these pass on DG2 now.
=> [SYCL][ESIMD][E2E] Re-enable unified memory bsycl/tlock_store tests on DG2

sycl/test-e2e/Basic/built-ins/marray_geometric.cpp
=> [SYCL][E2E] add the FP16 tests in marray_geometric

clang-tools-extra/clangd/Compiler.cpp, clang-tools-extra/clangd/test/sycl.test
Add four extra option resets in `disableUnsupportedOptions` when parsing SYCL code. All four are needed to make clangd happily parse code when `-fsycl` is specified in compile commands. Without each of them, the following happens:
* without `SYCLIsDevice=false`: crash on !nullptr assert
* without `DeclareSPIRVBuiltins=false`: crash on !nullptr assert
* without `SYCLUnnamedLambda=false`: `ref_non_value` error, `'T' does not refer to a value`
* without `Triple=HostTriple`: `pp_file_not_found` error, `'gnu/stubs-32.h' file not found`
Fixes intel/llvm#11088 and clangd/clangd#1097
Also add a LIT test which parses the following code:
```cpp
#include <sycl/sycl.hpp>
sycl::queue q{};
```
and checks `symbolInfo` for the symbol `q` against a reference.
=> [clangd] Avoid clangd crash with -fsycl flag

.github/workflows/sycl_linux_precommit.yml, .github/workflows/sycl_post_commit.yml, .github/workflows/sycl_windows_precommit.yml
add sycl-rel-** to the pre-commit/post-commit workflow supported branches
=> [CI] Add support for sycl-rel-** branches to CI

sycl/source/detail/buffer_impl.cpp, sycl/source/detail/context_impl.cpp, sycl/source/detail/context_impl.hpp, sycl/source/detail/kernel_impl.hpp, sycl/source/detail/kernel_program_cache.hpp
* Don't throw exceptions in destructors (they are explicitely marked as noexcept)
* Make sure that MPlatform data member of context_impl is always initialized.
* Assign default value to MCacheMutex* in kernel_impl.
=> [SYCL] Fix issues caught by static analyzer

sycl/include/sycl/exception.hpp
If there is no backend specific error code associated with the sycl::exception then error code must be 0, so initialize with 0 by default, otherwise static analyzer complains about unitialized data member.
=> [SYCL] Initialize error code in sycl::exception

sycl/test-e2e/DeviceArchitecture/device_architecture_on_device_aot.cpp
Problem was fixed, so enable test back.
=> [SYCL][E2E] Enable device_architecture test back on Windows OpenCL

sycl/source/detail/event_impl.cpp
sycl/source/detail/event_impl.cpp:223:24: error: ‘IId’ may be used
uninitialized in this function [-Werror=maybe-uninitialized
=> [SYCL] Fix maybe-uninitialized warning

sycl/include/sycl/ext/oneapi/experimental/annotated_arg/annotated_arg.hpp, sycl/test/extensions/annotated_arg/usm_kind_intel_fpga.cpp
Apply #11623 to `annotated_arg` class
=> [SYCL] Refine annotated_arg addrspace with USM kind property

sycl/doc/extensions/experimental/sycl_ext_intel_data_flow_pipes_properties.asciidoc
Update to pipe properties spec to include axi streaming as a protocol choice.
Existing properties like bits_per_symbol have been explicitly declared as Avalon-only. Although AXI will require many similar controls, the intention will be to add separate AXI-only properties for those. They will be added in the future as we add support for them.
Part of this update includes items 3-8 of this [cleanup case](https://github.com/intel/llvm/issues/9465l) from @GarveyJoe. Of particular note, uses_ready has been extracted from the protocol property into its own property.
=> [SYCL][DOC] Update FPGA pipe properties spec

sycl/test-e2e/Graph/Explicit/work_group_size_prop.cpp, sycl/test-e2e/Graph/RecordReplay/dotp_in_order.cpp, sycl/test-e2e/Graph/RecordReplay/dotp_in_order_with_empty_nodes.cpp, sycl/test-e2e/Graph/RecordReplay/dotp_multiple_queues.cpp, sycl/test-e2e/Graph/RecordReplay/work_group_size_prop.cpp
Adds missing variable initializations.
Temporary disable `work_group_size_prop.cpp` because the failure results from a bug in the emulation layer.
=> [SYCL][Graph] Fix OpenCL backend test fails with CPU device

sycl/test-e2e/ESIMD/unified_memory_api/Inputs/atomic_update_slm.hpp
This is done to avoid problems with those types that may have issues with constexpr operations/constructors/etc.
=> [ESIMD][E2E][NFC] Replace some of constexpr operations with regular

sycl/doc/extensions/template.asciidoc
Update the template for extension specifications to list the new copyright date and the most current core SYCL revision.
=> [SYCL][Doc] Update spec template

sycl/plugins/unified_runtime/CMakeLists.txt
* https://github.com/oneapi-src/unified-runtime/pull/937
* https://github.com/oneapi-src/unified-runtime/pull/938
=> [UR] Bump tag to 1d786360

sycl/plugins/hip/CMakeLists.txt, sycl/plugins/unified_runtime/CMakeLists.txt
The code object finalization for kernel fusion uses the AMD COMGR. The location of the corresponding header changed between ROCm version 4 and 5.
This PR fixes the include for ROCm version 4.
=> [SYCL][UR] Fix include for COMGR

sycl/doc/design/KernelFusionJIT.md
Add further details on local/private memory allocation size, different promotion hints for the same argument and internalization of arguments used on kernels with different ND-ranges.
Update description of metadata used to specify internalization information.
=> [SYCL][Fusion] Update internalization documentation in design document

sycl/source/detail/platform_impl.cpp
Mostly "early continue" and use the same idioms for similar things.
=> [NFCI][SYCL] Refactor device selection in platform_impl.cpp

sycl/include/sycl/backend_types.hpp, sycl/tools/sycl-ls/sycl-ls.cpp
This is to align with the default/recommended usage of `ONEAPI_DEVICE_SELECTOR`. Addresses one part of
https://github.com/intel/llvm/issues/12048.
=> [SYCL] Don't print vendor in sycl-ls' output

polygeist/lib/Dialect/Polygeist/Analysis/MemoryAccessAnalysis.cpp, polygeist/lib/Dialect/Polygeist/Analysis/ReachingDefinitionAnalysis.cpp, polygeist/lib/Dialect/Polygeist/Transforms/AffineCFG.cpp, polygeist/lib/Dialect/Polygeist/Transforms/LoopInternalization.cpp, polygeist/lib/Dialect/Polygeist/Transforms/Mem2Reg.cpp, polygeist/lib/Dialect/Polygeist/Transforms/ParallelLoopDistribute.cpp, polygeist/lib/Dialect/Polygeist/Transforms/SYCLRaiseHost.cpp, polygeist/tools/cgeist/Lib/clang-mlir.cc, polygeist/tools/cgeist/Lib/utils.cc, polygeist/tools/cgeist/driver.cc
- Replace deprecated member function cast-like calls with free
function calls
- Replace `startswith` member function call with `starts_with`
- Use `nodiscard` `ChangeResult` value returned by `setModifier`.
=> [SYCL-MLIR][NFC] Fix warnings in `polygeist`

sycl/doc/extensions/experimental/sycl_ext_oneapi_bindless_images.asciidoc, sycl/include/sycl/ext/oneapi/bindless_images.hpp, sycl/test-e2e/bindless_images/read_1D.cpp
The image handle structs now have default constructors. Default constructed image handles are not valid until the `raw_handle` field of the struct is populated with a previously created and valid image handle.
=> [SYCL][Bindless][Exp] Add default constructors to image handle structs

.github/workflows/sycl_detect_changes.yml, .github/workflows/sycl_linux_build.yml
- Run `check-mlir` when `mlir` or `llvm` change;
- Run `check-mlir-sycl` on `polygeist` or `sycl` dialect changes, SYCL-MLIR test changes, or when `check-mlir` needs to be run;
- Run `check-polygeist` on `polygeist` or `sycl` dialect changes, polygeist test changes, or when `check-mlir` needs to be run;
- Run `check-cgeist` when any of the above needs to be run or the cgeist frontend changes.
=> [SYCL-MLIR][CI] Run relevant tests on changes

sycl/test-e2e/UserDefinedReductions/user_defined_reductions.cpp
... by providing additional `std::ostream operator<<` overloads for custom types used in the test.`
=> [SYCL][E2E] Improve debugability of user_defined_reductions.cpp test

sycl/include/sycl/bit_cast.hpp, sycl/test-e2e/Basic/bit_cast/bit_cast.cpp, sycl/test-e2e/Basic/bit_cast/win_host_compile.cpp
We were attempting to detect the presence of the builtins using the `__has_builtin` macro, but that's only present in Clang and GCC. For MSVC, one simply checks that that version is later than 1928,.
But older versions of GCC don't have the bit_cast builtin, so the non constexpr fallback remains for now.
=> [SYCL] revisit sycl::bit_cast constexpr 

llvm/lib/SYCLLowerIR/ESIMD/LowerESIMD.cpp, sycl/include/sycl/ext/intel/esimd/detail/intrin.hpp, sycl/include/sycl/ext/intel/esimd/detail/memory_intrin.hpp, sycl/include/sycl/ext/intel/esimd/memory.hpp, sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp, sycl/test-e2e/ESIMD/api/svm_gather_scatter.cpp, sycl/test-e2e/ESIMD/unified_memory_api/Inputs/gather.hpp, sycl/test-e2e/ESIMD/unified_memory_api/gather_usm.cpp, sycl/test-e2e/ESIMD/unified_memory_api/gather_usm_dg2_pvc.cpp, sycl/test-e2e/ESIMD/unified_memory_api/gather_usm_legacy.cpp, sycl/test-e2e/ESIMD/unified_memory_api/gather_usm_pvc.cpp, sycl/test/esimd/memory_properties.cpp
This patch also supports gather and masked-gather of any length N if it does not use L1/L2 hints of VS>1.
Additionally for gathers without L1/L2 vs VS>1 this patch replaces the calls of GenX SVM gather calls with LLVM IR
if the macro __ESIMD_GATHER_SCATTER_LLVM_IR is defined by user. If it not defined, then using masked gathers
with pass_thru operand requires DG2/PVC.
=> [ESIMD] Implement property-based gather(usm, ...)

sycl/source/detail/platform_impl.cpp, sycl/test-e2e/DeprecatedFeatures/sycl_device_filter.cpp
The very last commit in #12288
(https://github.com/intel/llvm/pull/12288/commits/f9a1377f835f86ab71fb6886e07f5e201a0f085b) accidentally removed one condition needed to add the device into allowed devices list. Restore it here.
=> [SYCL] Fix device selector bug introduced in #12288

sycl/test-e2e/bindless_images/read_sampled.cpp
Part 2 of https://github.com/intel/llvm/pull/12205
double type needs -ze-fp64-gen-emu compile flag on DG2.
Adding the flag each time is inconvenient for testing.
=> [NFC][SYCL][Bindless] Don't use double type in e2e tests - part 2

clang/include/clang/Basic/Attr.td, clang/lib/Sema/SemaSYCL.cpp, clang/test/SemaSYCL/basic-kernel-wrapper.cpp
`SemaSYCL` introduces kernels calling user-provided kernel body functions to avoid OpenCL limitations on kernel arguments. Mark the original kernel body functions with a new `SYCLKernelObjFunc` attribute to handle them in codegen.
=> [SYCL-MLIR][clang] Attach `SYCLKernelObjFunc` to kernel body functions

sycl/include/sycl/ext/intel/esimd/memory.hpp, sycl/test-e2e/ESIMD/unified_memory_api/Inputs/atomic_update_slm.hpp
For double type the GenX intrinsic expects double vectors without bit-casting them to integer types as for other types.
This fix enables FMAX/FMIN/FCMPXCHG slm_atomic_update() for double type. It requires pretty new GPU driver.
=> [ESIMD] Fix slm_atomic_update() implementation for double type

sycl/include/sycl/ext/intel/esimd/memory.hpp, sycl/test-e2e/InvokeSimd/Regression/slm_gather_scatter.cpp
The previous fix (https://github.com/intel/llvm/pull/12316) added usage of llvm.masked.gather for slm_gather(). Such usage does not work with current GPU drivers if ESIMD function is called via invoke_simd() API.
The fix here returns the previous lowering to GenX instead of llvm.masked.gather.
Using the lowering to llvm.masked.gather can be used if define __ESIMD_GATHER_SCATTER_LLVM_IR macro (turned off by default).
=> [ESIMD] Conditionally revert the recent changes for slm_gather()

clang/lib/Sema/SemaStmtAttr.cpp, clang/test/SemaSYCL/intel-fpga-loops.cpp
This patch diagnose non-identical duplicates as a 'conflicting' loop attributes and suppress duplicate errors in cases where the two match for FPGA SYCL attributes: 'SYCLIntelMaxInterleavingAttr', 'SYCLIntelSpeculatedIterationsAttr', and 'SYCLIntelMaxReinvocationDelayAttr' to align with clang community change (Ref: https://github.com/llvm/llvm-project/pull/70762).
=> [SYCL][FPGA] Refactor statments attributes to align with community the way we handle conflicting vs duplicate values

sycl/doc/extensions/template.asciidoc
Commit b32db9a4cdd7ffd9ca4874e495d06766e10c8889 added some new suggested text to the extension specification template, which was formatted as a quote.  This formatting is inconsistent with the other suggested text, which is not formatted as a quote.  Fix this.
=> [SYCL][Doc] Fix formatting in extension template

sycl/doc/developer/ContributeToDPCPP.md
This small addition signposts interested users to instructions on adding DPC++ extensions. It was motivated by https://github.com/intel/llvm/issues/12251#issuecomment-1879736917
When looking into the logic of the docs, I found there was no signposting from the initial repo readme to tell contributors how to propose their own extensions.
There have been some important third-party contributions to dpc++ and in the future it is possible such contributions could include proposing new oneapi extensions.
=> [SYCL][Doc] Linked extension process readme from dpcpp readme.

sycl/test-e2e/Matrix/joint_matrix_annotated_ptr_impl.hpp, sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_impl.hpp, sycl/test-e2e/Matrix/joint_matrix_colA_rowB_colC_impl.hpp, sycl/test-e2e/Matrix/joint_matrix_out_bounds_impl.hpp, sycl/test-e2e/Matrix/joint_matrix_transposeC_impl.hpp
This change explicitly defines multi_ptr inside the kernel instead of outside the kernel.  Before, we rely on the runtime to correctly treat the lambda capture clause and create correct private copies for each of these variables.  With this change, we are making sure that these variables are correctly captured (private copies) inside the kernel.
=> [SYCL][Matrix tests]make multi_ptr access direct inside the kernel

sycl/pi_win_proxy_loader/pi_win_proxy_loader.cpp
Currently the default search order is used when loading dependencies of the plugins (these dependencies include the Level Zero loader and the ICD loader for opencl and level zero plugins respectively) and that list includes current directory and some other directories which are not considered safe. This patch limits the list of directories when loading the dependencies of the plugins. See: https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryexa for reference.
=> [SYCL] Limit the directories that are searched when loading dependencies of the plugins

mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLBase.td, polygeist/tools/cgeist/Lib/CodeGenTypes.cc, polygeist/tools/cgeist/Test/Verification/sycl/kernel_func_obj.cpp
Attach `sycl.kernel_func_obj` attribute to functions with the `SYCLKernelFuncObj` attribute. The list of symbols referring to the kernels the function implements is obtained from the original attribute.
=> [SYCL-MLIR][cgeist] Propagate SYCLKernelFuncObj attribute

libdevice/cmath_wrapper.cpp, libdevice/cmath_wrapper_fp64.cpp, libdevice/device_math.h, libdevice/fallback-cmath-fp64.cpp, libdevice/fallback-cmath.cpp, sycl/test-e2e/DeviceLib/cmath_fp64_test.cpp, sycl/test-e2e/DeviceLib/cmath_test.cpp
`fabs` was missing for Nvidia compilation
=> [SYCL] Add missing fabs

sycl/source/detail/memory_manager.cpp
Ignore unused `Size` parameter from `memory_manager::ext_oneapi_fill_cmd_buffer`.
This was introduced in PR https://github.com/intel/llvm/pull/11472 and passed as `Req->MMemoryRange` from the command-group requirement but not used for calling the underlying UR function, leading to a
`-Wunused-parameter` error.
It may be that this is needed to support buffers of dimension greater than 1, which there are currently no graphs tests for. This will be investigated as a follow-up once post-commit CI is unblocked with this PR.
=> [SYCL][Graph] Fix post-commit CI after PR #11472

sycl/plugins/unified_runtime/ur/adapters/cuda/README.md, sycl/plugins/unified_runtime/ur/adapters/hip/README.md, sycl/plugins/unified_runtime/ur/adapters/level_zero/README.md, sycl/plugins/unified_runtime/ur/adapters/native_cpu/README.md, sycl/plugins/unified_runtime/ur/adapters/opencl/README.md
Adapters branch of the oneapi-src/unified-runtime repo was merged with main branch, and was deprecated, and it will be removed soon. All development has moved to main branch.
=> [SYCL][UR][NFC] Update readme to the correct location of UR adapters

sycl/test-e2e/lit.cfg.py, sycl/tools/sycl-ls/sycl-ls.cpp
Emit
`[backend:device_type][backend:device_number] <Text...>`
in place of
`[backend:device_type:device_number] <Text...>`
as ONEAPI_DEVICE_SELECTOR accepts either device_type or device_number and not both simultaneously.
=> [SYCL] Align sycl-ls output with ONEAPI_DEVICE_SELECTOR syntax

sycl/doc/extensions/experimental/sycl_ext_intel_online_compiler.asciidoc, sycl/doc/extensions/experimental/sycl_ext_oneapi_kernel_compiler.asciidoc
When referring to the `std` namespace use `a` instead of `an` (because the pronunciation is "a stood namespace" not "an s-t-d namespace"). This is consistent with cppreference and the C++ specification.
=> [SYCL][Doc] Use "a std::" instead of "an std::"

.github/workflows/sycl_post_commit.yml, sycl/test-e2e/PerformanceTests/Reduction/reduce_over_sub_group.cpp, sycl/test-e2e/PerformanceTests/lit.local.cfg, sycl/test-e2e/lit.cfg.py
Just an additional directory under sycl/test-e2e that needs "llvm-lit
--param enable-perf-tests=1" to be executed and changes in post-commit
task to enable running those using a single worker and capturing output
even on PASSes.
I plan on modifying pre-commit to run the same given a label is provided
in a separate PR.
Better infrastructure, like using google benchmark or deeper integration
with CI, is not planned at the moment.
=> [SYCL][E2E] Introduce performance tests

sycl/include/sycl/handler.hpp
Removed 6 includes. The code still compiles. I've tried to do some `grep`ing to ensure that `handler.hpp` doesn't really use anything from those includes. However, it could be that I've missed something and we can still compile because those files are included from somewhere else implicitly.
=> [SYCL][NFC] Cleanup handler.hpp includes

mlir/include/mlir/Dialect/LLVMIR/GENXOps.td, mlir/lib/Target/LLVMIR/Dialect/GENX/GENXToLLVMIRTranslation.cpp, mlir/test/Target/LLVMIR/genx.mlir
This PR resolves https://github.com/intel/intel-xpu-backend-for-triton/issues/164 where sub_group_shuffle_xor calls are duplicated and become conditional causing UB.
=> [GENX] Use convergent attr for sub-group shuffle calls.

polygeist/include/mlir/Dialect/Polygeist/Utils/TransformUtils.h, polygeist/lib/Dialect/Polygeist/Transforms/ArgumentPromotion.cpp, polygeist/lib/Dialect/Polygeist/Transforms/KernelDisjointSpecialization.cpp, polygeist/lib/Dialect/Polygeist/Transforms/LoopInternalization.cpp, polygeist/lib/Dialect/Polygeist/Utils/TransformUtils.cpp, polygeist/test/polygeist-opt/sycl/argpromotion.mlir, polygeist/test/polygeist-opt/sycl/argpromotion_invalid.mlir, polygeist/test/polygeist-opt/sycl/argpromotion_privatize.mlir, polygeist/test/polygeist-opt/sycl/kernel_disjoint_specialization.mlir, polygeist/test/polygeist-opt/sycl/loop_internalization.mlir, polygeist/test/polygeist-opt/sycl/loop_internalization_invalid.mlir, polygeist/test/polygeist-opt/sycl/loop_internalization_unroll.mlir, polygeist/test/polygeist-opt/sycl/matrix_multiply_reduction.mlir
Use this attribute in `FunctionKernelInfo` instead of obtaining the list of kernel body functions by traversing the call-graph.
=> [SYCL-MLIR][polygeist] Use `sycl.kernel_func_obj` attribute in `FunctionKernelInfo`

sycl-fusion/common/include/DynArray.h, sycl-fusion/common/include/Kernel.h, sycl-fusion/passes/cleanup/Cleanup.cpp, sycl-fusion/passes/cleanup/Cleanup.h, sycl-fusion/passes/internalization/Internalization.cpp, sycl-fusion/passes/kernel-fusion/SYCLKernelFusion.cpp, sycl-fusion/passes/kernel-fusion/SYCLKernelFusion.h, sycl-fusion/passes/kernel-info/SYCLKernelInfo.cpp, sycl-fusion/passes/syclcp/SYCLCP.cpp, sycl/source/detail/jit_compiler.cpp, sycl/source/detail/jit_compiler.hpp
Introduces the `jit_compiler::DynArray` template to represent a fixed-sized-but-dynamically allocated array with an `std::array`-compatible interface. `DynArray` is then used to replace the uses of `std::vector` in the `SYCLArgumentDescriptor` struct. Client code was updated to either determine the number of arguments beforehand, or use dynamically-growable containers to collect the relevant info locally and then copy it over to a `DynArray` instance.
*This PR is part of a series of changes to remove uses of STL classes in the kernel fusion interface to prevent ABI issues in the future.*
=> [SYCL][Fusion][NoSTL] Encode argument descriptor using fixed-size arrays

sycl/test-e2e/Reduction/reduction_nd_lambda.cpp
This test is now passing.
It is noted as inconsistently failing, I couldn't reproduce the failure locally and the CI passed, so I'd like to try to re-enable it as we improved the HIP backend significantly since it was disabled.
I will keep an eye out and revert this if it starts failing again.
=> [SYCL][HIP] Re-enable reduction nd lambda test

clang/lib/Sema/SPIRVBuiltins.td, sycl/include/CL/__spirv/spirv_ops.hpp, sycl/include/sycl/detail/spirv.hpp, sycl/include/sycl/ext/oneapi/experimental/address_cast.hpp, sycl/include/sycl/sycl.hpp, sycl/test-e2e/AddressCast/dynamic_address_cast.cpp, sycl/test-e2e/AddressCast/static_address_cast.cpp
- Adds support for OpGenericCastToPtr SPIR-V intrinsic.
- Implements static_address_cast using OpGenericCastToPtr.
- Implements dynamic_address_cast using OpGenericCastToPtrExplicit.
- Adds tests for both new forms of address_cast.
=> [SYCL] Implement sycl_ext_oneapi_address_cast

sycl/include/sycl/ext/oneapi/experimental/tangle_group.hpp, sycl/include/sycl/ext/oneapi/sub_group_mask.hpp, sycl/include/syclcompat/memory.hpp, sycl/source/feature_test.hpp.in, sycl/test-e2e/SubGroupMask/sub_group_mask_ver2.cpp, sycl/test/extensions/macro.cpp, sycl/test/extensions/sub_group_mask.cpp
Was reverted by fb8c82dee68e966dac5854d99cc6bb1a5784eece due to performance regressions on some devices.
It turned out that the problem is not with this patch. So applying it again without any changes.
Previously reviewed here: https://github.com/intel/llvm/pull/11195
=> [SYCL] Reintroduce sub_group_mask version 2

.github/workflows/sycl_detect_changes.yml, .github/workflows/sycl_linux_precommit.yml
Performance tests were added in https://github.com/intel/llvm/pull/12372
to be executed in post-commit. This PR changes the pre-commit behavior.
The tests will run if either some performance test is modified (to keep
post-commit clean) or if `run-perf-tests` label is added to the PR.
=> [SYCL][CI] Add ability to run perf tests in pre-commit CI

sycl/plugins/unified_runtime/pi2ur.hpp
Fixes post-commit CI failure seen here https://github.com/intel/llvm/actions/runs/7559355777/job/20582987874 and caused by merging of https://github.com/intel/llvm/pull/11474
=> [SYCL][Graph] Fix post-commit unused parameter warning

mlir/include/mlir/Dialect/LLVMIR/GENXOps.td, mlir/test/Target/LLVMIR/genx.mlir
The opencl function `get_global_size` is not recognized by IGC:
Given the following Kernel:
``` 
; Function Attrs: nounwind
define spir_kernel void @kernel_0d1d2de(float addrspace(1)* nocapture readonly %0, float addrspace(1)* nocapture %1, i32 %2, float addrspace(3)* nocapture %3) #0 !dbg !265 {
%5 = call spir_func i64 @_Z12get_local_idj(i32 0) #0, !dbg !268
%6 = trunc i64 %5 to i32, !dbg !268
%7 = and i32 %6, 31, !dbg !268
%8 = lshr i32 %6, 3, !dbg !268
%9 = and i32 %8, 15, !dbg !268
%10 = or i32 %9, 16, !dbg !268
%11 = shl i32 %6, 2, !dbg !268
%12 = and i32 %11, 28, !dbg !268
%13 = call spir_func i64 @_Z12get_group_idj(i32 0) #0, !dbg !269
%14 = trunc i64 %13 to i32, !dbg !269
%15 = call spir_func i64 @_Z12get_group_idj(i32 1) #0, !dbg !270
%16 = trunc i64 %15 to i32, !dbg !270
%17 = …
```
=> [GENX]: Use get_global_size IGC builtin instead of opencl function

sycl-fusion/common/include/Kernel.h, sycl-fusion/jit-compiler/lib/translation/KernelTranslation.cpp, sycl-fusion/passes/kernel-fusion/SYCLKernelFusion.cpp, sycl-fusion/passes/kernel-fusion/SYCLKernelFusion.h, sycl-fusion/passes/kernel-info/SYCLKernelInfo.cpp, sycl-fusion/test/kernel-fusion/check-failed-remapping-amdgpu.ll, sycl-fusion/test/kernel-fusion/check-failed-remapping-cuda.ll, sycl-fusion/test/kernel-fusion/check-failed-remapping.ll, sycl-fusion/test/kernel-fusion/check-remapping-amdgpu.ll, sycl-fusion/test/kernel-fusion/check-remapping-cuda.ll, sycl-fusion/test/kernel-fusion/check-remapping-interproc-amdgpu.ll, sycl-fusion/test/kernel-fusion/check-remapping-interproc-cuda.ll, sycl-fusion/test/kernel-fusion/check-remapping-interproc.ll, sycl-fusion/test/kernel-fusion/check-remapping.ll, sycl-fusion/test/kernel-fusion/required_work_group_size.ll, sycl-fusion/test/kernel-fusion/work_group_size_hint.ll, sycl-fusion/test/kernel-info/kernel-info.ll, sycl/source/detail/jit_compiler.cpp
Kernel attributes were previously modeled as an `std::string` name, and an arbitrarily long `std::vector` of string values, however we currently don't need this genericity to represent `reqd_work_group_size` and `work_group_size_hint` attributes. In fact, an attribute kind enum and an `Indices` object (= 3 integers) suffice. 
_This PR is part of a series of changes to remove uses of STL classes in the kernel fusion interface to prevent ABI issues in the future._
=> [SYCL][Fusion][NoSTL] Simplify kernel attributes by making them less generic

sycl/test-e2e/Graph/Explicit/debug_print_graph.cpp, sycl/test-e2e/Graph/Explicit/debug_print_graph_verbose.cpp, sycl/test-e2e/Graph/Inputs/debug_print_graph.cpp, sycl/test-e2e/Graph/Inputs/debug_print_graph_verbose.cpp, sycl/test-e2e/Graph/RecordReplay/debug_print_graph.cpp, sycl/test-e2e/Graph/RecordReplay/debug_print_graph_verbose.cpp
The order of root node in debug print tests was not deterministic. 
This PR updates these tests to make them deterministic by creating dependencies between nodes.
Addresses Issue: #12397
=> [SYCL][Graph] Make debug print tests deterministic

sycl/plugins/unified_runtime/pi2ur.hpp
Calling urAdapterGet is required for the global adapter to be initialized, but it was missing when creating a platform from a native handle. This meant that the adapter's state never got initialized and its refcount remained at 0 (and overflowed on teardown).
This had no visible side-effects until changes in #12403.
=> [UR] call urGetAdapter before creating a platform from native handle

sycl/test-e2e/Matrix/SG32/joint_matrix_bf16_fill_k_cache.cpp, sycl/test-e2e/Matrix/SG32/joint_matrix_bf16_fill_k_cache_init.cpp, sycl/test-e2e/Matrix/SG32/joint_matrix_bf16_fill_k_cache_unroll.cpp, sycl/test-e2e/Matrix/SG32/joint_matrix_bf16_fill_k_cache_unroll_init.cpp, sycl/test-e2e/Matrix/XMX8/joint_matrix_bf16_fill_k_cache.cpp, sycl/test-e2e/Matrix/XMX8/joint_matrix_bf16_fill_k_cache_init.cpp, sycl/test-e2e/Matrix/XMX8/joint_matrix_bf16_fill_k_cache_unroll.cpp, sycl/test-e2e/Matrix/XMX8/joint_matrix_bf16_fill_k_cache_unroll_init.cpp, sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache.cpp, sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_init.cpp, sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_unroll.cpp, sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_unroll_init.cpp
Added -ffp-model=precise to joint_matrix_bf16_fill_k_cache tests as they do math with floating numbers and can get NaN result, which indicates error. Some compiler version may have different fp-model defaults, so this option make the test indipendent of compiler defaults.
=> [SYCL][E2E][Joint Matrix] Added -ffp-model=precise to some tests

sycl/include/sycl/detail/builtins/helper_macros.hpp, sycl/include/sycl/detail/builtins/math_functions.inc
clang rejects dllexport defintion if previous declaration didn't have it, make sure we have declaration/definition in sync when building libsycl.
=> [SYCL] Try to fix internal self-build after builtins refactoring PR

clang/lib/Driver/ToolChains/SYCL.cpp, clang/test/Driver/sycl-ftarget-register-alloc-mode.cpp
We shouldn't add `-options` as per the IGC team.
=> [SYCL][Driver] Fix per-device ocloc argument

sycl-fusion/common/include/DynArray.h, sycl-fusion/jit-compiler/include/Parameter.h, sycl-fusion/jit-compiler/lib/fusion/FusionHelper.cpp, sycl-fusion/jit-compiler/lib/fusion/Hashing.h
Use our custom `DynArray` container instead of an `std::string` to store a JIT constant's bytes.
*This PR is part of a series of changes to remove uses of STL classes in the kernel fusion interface to prevent ABI issues in the future.*
=> [SYCL][Fusion][NoSTL] Store JIT constant data in a DynArray

sycl/test-e2e/Graph/Explicit/work_group_size_prop.cpp, sycl/test-e2e/Graph/RecordReplay/work_group_size_prop.cpp
A couple of graph related tests were marked as `XFAIL`ed on OpenCL backend and it works just fine for intel/llvm. At intel/llvm we launch E2E tests for multiple targets in one LIT run, but there are some side effects of that mechanism like treating `XFAIL` as `UNSUPPORTED`.
We have downstream testing environments where E2E tests are launched for a single target. When those tests are launched on an OpenCL device without graphs support, they do early exit with exit code zero which is equivalent to `PASS` from LIT point of view. That turns into an `XPASS` due to `XFAIL` in the test, causing our CI to report failures.
Changed `XFAIL` to `UNSUPPORTED`, which will work for all possible environments, regardless of amount of targets for E2E tests and status of graphs support on OpenCL devices …
=> [SYCL][NFC] Avoid `XPASS`-es in some graph tests

sycl/test-e2e/Graph/Explicit/memadvise.cpp, sycl/test-e2e/Graph/Explicit/prefetch.cpp, sycl/test-e2e/Graph/RecordReplay/memadvise.cpp, sycl/test-e2e/Graph/RecordReplay/prefetch.cpp
In https://github.com/intel/llvm/pull/11474 it was noted in the documentation that the `prefetch` and `memadvise` handler methods were not supported as graph nodes on the OpenCL command-buffer backend.
However, we never disabled the E2E tests for this target, which wasn't picked up by CI, as CI doesn't use the command-buffer extension in its OpenCL config. This PR corrects this oversight by marking the tests as unsupported for OpenCL.
=> [SYCL][Graph] Skip prefetch/memadvise opencl tests

.github/workflows/sycl_post_commit.yml, sycl/source/builtins/relational_functions.cpp
MacOS' STL is not standard-conformant, try to workaround for that in our code.
=> [SYCL] Try to fix MacOS build after #11956

sycl/test-e2e/ESIMD/aot_mixed.cpp
It looks like we have literally no AOT ESIMD tests enabled, and we recently hit an issue that would have been caught by any AOT ESIMD compilation.
=> [SYCL][ESIMD][E2E] Enable AOT test

sycl/doc/extensions/experimental/sycl_ext_oneapi_device_architecture.asciidoc
This commit makes some editorial changes to the "if_architecture_is" extension specification.  None of the APIs changed, so this has no effect on the implementation.  I'm making this in preparation for some new APIs that I will soon add to this extension.
* Eliminate redundancy with the `architecture` enumeration.  The code synopsis no longer duplicates the enumerators.  These are now entirely defined in the table.
* Add some missing entries to the table defining the enumerators, and fix some obvious cut-and-paste errors with the descriptions.
* Update the function descriptions to our new format, using subsections `Constraints`, `Preconditions`, etc.
* Use our new style where we make a line break after every sentence.
=> [SYCL][Doc]Editorial changes "if_architecture_is"

llvm/lib/SYCLLowerIR/ESIMD/LowerESIMD.cpp, llvm/test/SYCLLowerIR/ESIMD/assert_with_volatile_global.ll, llvm/test/SYCLLowerIR/ESIMD/force_inline.ll, llvm/test/SYCLLowerIR/ESIMD/lower_global_stores.ll
We need to inline some `nolinine` functions because VC doesn't support debugging/`O0`/`-g` in order to at least make user code do the right thing. Otherwise, we get wrong answers or GPU hangs.
This change fixes 4 `-O0`/`-fno-inline-functions` test failures.
=> [SYCL][ESIMD] Require inlining of some noinline functions due to VC limitation

sycl-fusion/passes/kernel-fusion/SYCLKernelFusion.cpp
Obey the end of the `ParamIdentities` list when looking for opportunities to mark arguments of the fused kernel as unused.
=> [SYCL][Fusion] Fix handling of identical parameters

sycl/test-e2e/Plugin/level-zero-usm-capabilities.cpp
usm_atomic_shared_allocations is supported on PVC with newer GPU driver versions.
=> [SYCL][NFC] Fix L0 USM capabilities test

sycl/test-e2e/Plugin/max_malloc.cpp
After PR#12375 user have to explicitly request > 4GB allocation support given the max allocation allowed on that system is less than 4GB. Setting UR_L0_ENABLE_RELAXED_ALLOCATION_LIMITS=1 will allow for the allocations to exceed the max single allocation size limit for that device.
=> [SYCL][E2E][NFC] Fix Plugin/max_malloc.cpp test after PR#12375

sycl/test-e2e/USM/math.cpp
This change fixes the zeMemAllocDevice memory leak in math.cpp
=> [SYCL][USM tests][E2E] Memory leak in math.cpp

sycl/source/detail/queue_impl.cpp, sycl/source/detail/queue_impl.hpp, sycl/source/queue.cpp, sycl/test-e2e/Graph/RecordReplay/in_order_queue_with_host_managed_dependencies.cpp, sycl/test-e2e/Graph/RecordReplay/in_order_queue_with_host_managed_dependencies_memcpy.cpp, sycl/test-e2e/Graph/RecordReplay/in_order_queue_with_host_managed_dependencies_memset.cpp, sycl/unittests/Extensions/CommandGraph.cpp
When a host-task is submitted to in-order queue, dependency between this host-task and the successor is explicitly handled.
However, when we record an in-order queue, the recorded CG are not part of the regular in-order queue execution sequence.
But inter-CG dependencies are managed by the graph implementation.
This PR implements this point and ensures that recording an in-order does not impact the normal execution sequence.
Tests (e2e and unitest) have been added to check it.
=> [SYCL][Graph] Fix bug when host-task is submitted to in-order queue

llvm/lib/SYCLLowerIR/CompileTimePropertiesPass.cpp, llvm/lib/SYCLLowerIR/ESIMD/ESIMDRemoveHostCode.cpp, llvm/lib/SYCLLowerIR/ESIMD/ESIMDUtils.cpp, llvm/lib/SYCLLowerIR/ESIMD/ESIMDVerifier.cpp, llvm/lib/SYCLLowerIR/ESIMD/LowerESIMD.cpp, llvm/lib/SYCLLowerIR/LowerInvokeSimd.cpp, llvm/lib/SYCLLowerIR/MutatePrintfAddrspace.cpp, llvm/lib/SYCLLowerIR/RenameKernelSYCLNativeCPU.cpp, llvm/lib/SYCLLowerIR/SYCLPropagateAspectsUsage.cpp, llvm/lib/SYCLLowerIR/SYCLPropagateJointMatrixUsage.cpp
The method was deprecated in favor of `StringRef::starts_with` in llvm/llvm-project#75491
=> [SYCL][NFC] Modernize use of `StringRef::startswith`

sycl/test-e2e/ESIMD/unified_memory_api/Inputs/block_store.hpp
Those test cases fail even with the most recent GPU drivers, it seems the issue with such N was fixed for slm_block_load(), but not for slm_block_store().
=> [ESIMD][E2E] Disable N=non-power-of-two cases for slm_block_store()

sycl-fusion/common/include/DynArray.h, sycl-fusion/common/include/Kernel.h, sycl-fusion/jit-compiler/include/KernelFusion.h, sycl-fusion/jit-compiler/lib/KernelFusion.cpp, sycl-fusion/jit-compiler/lib/translation/KernelTranslation.cpp, sycl-fusion/passes/kernel-fusion/SYCLKernelFusion.cpp, sycl-fusion/passes/kernel-info/SYCLKernelInfo.cpp, sycl/source/detail/jit_compiler.cpp
Implement a custom string class (backed by a `DynArray<char>`, hence owning its memory) to represent kernel names on the fusion interface.
*This PR is part of a series of changes to remove uses of STL classes in the kernel fusion interface to prevent ABI issues in the future.*
=> [SYCL][Fusion][NoSTL] Use custom string-like class to represent kernel name

sycl-fusion/jit-compiler/include/KernelFusion.h, sycl-fusion/jit-compiler/include/Options.h, sycl-fusion/jit-compiler/lib/KernelFusion.cpp, sycl-fusion/jit-compiler/lib/helper/ConfigHelper.h, sycl/source/detail/jit_compiler.cpp
Untangle the interaction between options and the `Config` class, and hide `Config` (which needs to store options in a map) from the KF interface.
The idea is to introduce free functions to interact with the `thread_local` instance of `Config` held by the existing `ConfigHelper` class, instead of letting the client construct the `Config` object and handing it to over `ConfigHelper` for storing it.
_This PR is part of a series of changes to remove uses of STL classes in the kernel fusion interface to prevent ABI issues in the future._
=> [SYCL][Fusion][NoSTL] Use free functions for configuration management

devops/dependencies.json
=> [GHA] Uplift Linux GPU RT version to 23.43.27642.18

sycl/test-e2e/ESIMD/matrix_transpose_glb.cpp
It's failing in postcommit, we need this to fix the CI.
=> [SYCL][ESIMD][E2E] Disable matrix_transpose_glb.cpp

sycl/test-e2e/InvokeSimd/Spec/ImplicitSubgroup/uniform_retval.cpp, sycl/test-e2e/InvokeSimd/Spec/uniform_retval.cpp
They pass with the new driver.
=> [SYCL][InvokeSimd][E2E] Enable uniform retval tests

sycl/doc/extensions/proposed/sycl_ext_oneapi_free_function_kernels.asciidoc, sycl/doc/extensions/proposed/sycl_ext_oneapi_raw_kernel.asciidoc
Add a proposed extension spec that allows a kernel to be defined as a plain function, where the function arguments are the kernel arguments. This is useful for the sycl_ext_oneapi_kernel_compiler because it allows a kernel to be defined in isolation from its host code.
=> [SYCL][Doc] Add free function kernel extension spec

clang/lib/CodeGen/CGDebugInfo.cpp, clang/test/CodeGen/debug-info-system-typedef.c
Generate debug info for system typedefs even with -fno-system-debug.  Allow this because system typedefs are rare and thus the amount of extra info is small.  Also it is not uncommon to use typedefs supplied in a header file for debugging.  This makes it less likely for -fno-system-debug to cause a debugging problem at a small cost in debug info size.
=> [DebugInfo] Generate debug info for system typedefs with -fno-system-debug

sycl-fusion/common/include/DynArray.h, sycl-fusion/common/include/Kernel.h, sycl-fusion/common/include/View.h, sycl-fusion/jit-compiler/include/KernelFusion.h, sycl-fusion/jit-compiler/include/Parameter.h, sycl-fusion/jit-compiler/lib/KernelFusion.cpp, sycl-fusion/jit-compiler/lib/fusion/FusionHelper.h, sycl-fusion/jit-compiler/lib/fusion/JITContext.h, sycl/source/detail/jit_compiler.cpp
Implement a very simple view class to transport the input vector's raw data pointers and sizes across the fusion interface, and modify `FusionResult` to work without `std::string` and `std::variant`.
_This PR is part of a series of changes to remove uses of STL classes in the kernel fusion interface to prevent ABI issues in the future._
=> [SYCL][Fusion][NoSTL] Implement custom view class to replace input vector references

libclc/ptx-nvidiacl/libspirv/atomic/atomic_cmpxchg.cl
CTS fix: CUDA backend uses "success" atomic order for cas.
There was a bug in the cas impl for nvptx in libclc that lead to CTS test failures for the CUDA backend.
This fixes the bug in a simple way by simply replacing the cases where the failure order differs from the success order (when failure order is either `release` or `acquire`), so that the failure order matches the success order (`acq_rel`). This is safe even if the cas performs the failure operation, because acq_rel can be used for both acquire (load) and release (store) atomic ops in ptx. I think that this is the only valid way to implement cas for nvptx, because the cas operation only takes one order argument.
Now the sycl cts passes for acq_rel atomics for the cuda backend.
=> [libclc][cuda] CTS fix: CUDA backend uses "success" atomic order for cas.

sycl/include/sycl/ext/intel/esimd/memory.hpp, sycl/test/esimd/intrins_trans.cpp
Some corner cases with interger scalar operands of gather() may cause ambiguous call error. Examples of such calls:
// 0 may be treated as vector `simd_mask` or scalar 'global_offset'
auto res1 = gather<T, N>(acc, offsets_simd, 0);
// This case is more tricky, but also can confuse C++ FE.
auto res2 = gather<T, N>(acc, offsets_simd, 0, mask);
=> [ESIMD] Fix the ambiguous call error for a corner case of gather()

llvm/lib/SYCLLowerIR/CompileTimePropertiesPass.cpp, llvm/test/SYCLLowerIR/CompileTimePropertiesPass/sycl-grf-mode.ll
It's already checked up-front at compile time in the SYCL headers. I can provide more background for this change offline if required.
=> [SYCL] Don't assert for unsupported GRF sizes in CompileTimePropertiesPass

sycl/test-e2e/Basic/get_backend.cpp
I manually tested this on DG2.
=> [SYCL][E2E] Update minimum driver version for get_backend.cpp

sycl/test-e2e/Graph/RecordReplay/in_order_queue_with_host_managed_dependencies_memcpy.cpp, sycl/test-e2e/Graph/RecordReplay/in_order_queue_with_host_managed_dependencies_memset.cpp
Fix memory leaks in newly added graph tests in https://github.com/intel/llvm/pull/12433.
=> [SYCL][Graph] Fix memory leaks in new graph tests

sycl-fusion/common/include/Kernel.h, sycl-fusion/common/lib/ModuleInfo.h, sycl-fusion/jit-compiler/lib/fusion/FusionPipeline.h, sycl-fusion/passes/kernel-fusion/SYCLKernelFusion.h, sycl-fusion/passes/kernel-info/SYCLKernelInfo.h
Move `SYCLModuleInfo` class to its own header under the `common` directory (because it has users from `jit-compiler` and `passes`).
_This PR is part of a series of changes to remove uses of STL classes in the kernel fusion interface to prevent ABI issues in the future._
=> [SYCL][Fusion][NoSTL][NFC] Move SYCLModuleInfo to its own header

mlir/lib/Conversion/GPUToGENX/LowerGpuOpsToGENXOps.cpp, mlir/test/Conversion/GPUToGENX/gpu-to-genx.mlir
This fixes the error below:
```
error: undefined reference to `__builtin_spirv_OpenCL_sin_f64'
in function: '__builtin_spirv_OpenCL_sin_f64' called by kernel: 'kernel_0d1d'
```
=> [GENX][GPUToGENX] change symbols to khronos format

sycl/plugins/unified_runtime/CMakeLists.txt
- Fix native kernel usage given no kernel creation in kernel map
- fix set of kernel function pointer given multi device
- Fix Global WorkSize variable to use a local variable to avoid invalid memory access.
- pre-commit PR for https://github.com/oneapi-src/unified-runtime/pull/1289
=> [UR][L0] Fix native kernel usage, multi device kernel pointer and WorkSize

.github/workflows/gh_pages.yml
This should fix the installation of GitHub Actions dependencies broken by recent updates. See https://github.com/intel/llvm/pull/12498#issuecomment-1914328314 for more details.
=> [CI] Uplift Ubuntu version for GH pages workflow.

sycl/source/detail/queue_impl.cpp, sycl/source/detail/queue_impl.hpp, sycl/unittests/scheduler/InOrderQueueSyncCheck.cpp
Fixes warnings introduced in https://github.com/intel/llvm/pull/11758
=> [SYCL] Fix unused variable warnings

clang/test/Driver/sycl-offload-amdgcn.cpp, clang/test/Driver/sycl-triple-dae-flags.cpp, clang/test/Driver/sycl-unsupported-arch.cpp
A few tests in the driver area require amdgpu or nvptx targets to be built in order to properly run.  Add these requirements to the tests.
=> [NFC][SYCL] Set some target restrictions for some tests

sycl/test-e2e/Basic/get_backend.cpp
It fails sporadically on DG2 even with the new driver. It does not sporadically fail on Gen12 with the new driver. I made an internal ticket to get to the bottom of it.
=> [SYCL][E2E] Disable get_backend.cpp on DG2

sycl/plugins/unified_runtime/pi2ur.hpp
This ensures that global setup has completed and interop objects will function correctly even if an application bootstraps directly in at the context level.
=> [UR] Call PiGetAdapter in piextContextCreateWithNativeHandle

sycl/doc/extensions/experimental/sycl_ext_oneapi_device_architecture.asciidoc
Update the "if_architecture_is" extension spec to allow greater-than and less-than comparisons between architecture values.
=> [SYCL][Doc]Comparisons in "if_architecture_is"

sycl/test-e2e/ESIMD/matrix_transpose_glb.cpp
It was fixed with the driver update. I can reproduce the failure with the old driver and reproduced it passing with the new driver.
=> [SYCL][ESIMD][E2E] Re-enable matrix_transpose_glb.cpp

sycl/unittests/scheduler/InOrderQueueHostTaskDeps.cpp
Fixes remaining warnings introduced in https://github.com/intel/llvm/pull/11758
=> [SYCL] Fix CTAD related warnings

sycl/test-e2e/KernelFusion/Reduction/reduction.cpp
XFAIL failing test on CPU until the issue is fixed.
=> [SYCL][Fusion][Test] XFAIL `KernelFusion/Reduction/reduction.cpp`

sycl/doc/design/KernelFusionJIT.md, sycl/source/detail/jit_compiler.cpp, sycl/test-e2e/KernelFusion/different_nd_ranges.cpp, sycl/test-e2e/KernelFusion/private_internalization.cpp, sycl/test-e2e/KernelFusion/two_dimensional.cpp
Enable, test, and document the support for fusing rounded range kernels. This mostly worked already – we just have to query the original kernel's global size, and use that to compute the private memory size used for internalization.
=> [SYCL][Fusion] Enable fusion of rounded-range kernels

sycl/test-e2e/Matrix/SG32/element_wise_all_ops.cpp, sycl/test-e2e/Matrix/element_wise_all_ops.cpp
This will make the two tests run in the presence of either CPU OR GPU and not requiring both to be present to run.
=> [SYCL][Joint matrix tests] Fix test execution env setting for two tests

sycl-fusion/common/include/Kernel.h, sycl-fusion/common/lib/NDRangesHelper.cpp, sycl-fusion/common/lib/NDRangesHelper.h, sycl-fusion/jit-compiler/lib/KernelFusion.cpp, sycl-fusion/jit-compiler/lib/fusion/FusionHelper.cpp, sycl-fusion/jit-compiler/lib/fusion/FusionHelper.h, sycl/test-e2e/KernelFusion/abort_fusion.cpp, sycl/test-e2e/KernelFusion/abort_internalization.cpp
Show detailed error messages when users try to fuse kernels with incompatible ND-ranges, showing different errors for each different scenario. Also combine the validation and fusion logic to reduce the number of ND-ranges list traversals.
=> [SYCL][Fusion] Improve error messages on incompatible ND-ranges

sycl/include/syclcompat/launch.hpp
Due to the way the inliner works, the launched function may become very large and go above the inline threshold. This results with a short kernel which only call one function.
The patch adds an always_inline on the call site to force the user function to be inline in the SYCL kernel to reduce overhead.
=> [SYCL][COMPAT] Force device function to be inlined

sycl/source/detail/jit_compiler.cpp
Silence unused variable warning which tripped post-commit checks for #12492.
=> [SYCL][Fusion] Silence warning

sycl-fusion/passes/internalization/Internalization.cpp, sycl-fusion/test/internalization/promote-private-non-unit.ll, sycl/test-e2e/KernelFusion/internalize_vfunc.cpp
Upstream now canonicalizes constant GEPs to represent byte offsets, i.e. using `i8` as source element type. This PR adapts the internalization pass to this change by also remapping GEPs with a constant offset, if that offset is a multiple of the internalized accessor's element size.
=> [SYCL][Fusion] Handle GEPs that were canonicalized to byte offsets

sycl/include/sycl/ext/intel/esimd/common.hpp, sycl/include/sycl/ext/intel/esimd/memory.hpp, sycl/include/sycl/ext/intel/experimental/esimd/common.hpp, sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp, sycl/test-e2e/ESIMD/unified_memory_api/Inputs/scatter.hpp, sycl/test-e2e/ESIMD/unified_memory_api/scatter_usm.cpp, sycl/test-e2e/ESIMD/unified_memory_api/scatter_usm_dg2_pvc.cpp, sycl/test/esimd/memory_properties.cpp
This implements the unified memory API for scatter with USM pointers.
=> [SYCL][ESIMD] Implement unified memory API for scatter(usm, ...)

sycl/test-e2e/ESIMD/lsc/local_accessor_atomic_smoke_cmpxchg.cpp, sycl/test-e2e/ESIMD/lsc/lsc_slm_atomic_smoke.cpp
They started failing in the recent driver update. I can't reproduce it locally with the same driver version but the hardware we have is a little different, maybe that's why. I made an internal tracker for this.
=> [SYCL][ESIMD][E2E] Disable two LSC tests on DG2

sycl/include/sycl/queue.hpp, sycl/source/detail/queue_impl.hpp, sycl/source/queue.cpp, sycl/test-e2e/Assert/check_resource_leak.cpp
https://github.com/intel/llvm/pull/6837 enabled asynchronous buffer destruction for buffers constructed without host data. However, initial fallback assert implementation in
https://github.com/intel/llvm/pull/3767 predates it and as such had to place the buffer inside `queue_impl` to avoid unintended synchronization point. I don't know if there was the same crash observed on the end-to-end test added as part of this PR prior to
https://github.com/intel/llvm/pull/3767, but it doesn't even matter because the "new" implementation is both simpler and doesn't result in a crash.
I suspect that without it (with the buffer for fallback assert implementation being a data member of `sycl::queue_impl`) we had a cyclic dependency somewhere leading to resource leak and ultimately to the assert in …
=> [SYCL] Fix resource leak related to SYCL_FALLBACK_ASSERT

sycl/test-e2e/USM/usm_pooling.cpp
See https://github.com/intel/llvm/issues/12397, the test is flaky in post-commit.
=> [SYCL][E2E] Disable USM/usm_pooling.cpp on gpu-intel-dg2

mlir/lib/Dialect/LLVMIR/IR/GENXOps.cpp, mlir/lib/Target/LLVMIR/Dialect/GENX/GENXToLLVMIRTranslation.cpp, mlir/test/Dialect/LLVMIR/genx-invalid.mlir, mlir/test/Target/LLVMIR/genx.mlir
1. Support user to pass packed i32 type for A and B operands.
2. Pack the A and B operands to i32 type if the user pass non-packed value.
=> Changes to the DPAS op.

sycl-fusion/common/lib/NDRangesHelper.cpp, sycl/doc/design/KernelFusionJIT.md, sycl/test-e2e/KernelFusion/abort_fusion.cpp
Do not allow fusion when one of the kernels has an explicit local size
and it requires ID remapping, i.e., it has a different number of
dimensions w.r.t. the fused ND-range or different global size in
dimensions [2, N). In this case, two work-items belonging to the same
work-group may not belong to the same work-group in the fused ND-range.
=> [SYCL][Fusion] Handle fusion leading to synchronization issues 

sycl/plugins/cuda/pi_cuda.cpp
https://github.com/oneapi-src/unified-runtime/pull/1070 and https://github.com/intel/llvm/pull/11952 introduced a new variant of the `enableCUDATracing` function that takes a context pointer parameter, replacing the parameterless variant of that function. The older variant will be removed from UR once this PR is merged.
=> [UR][CUDA] Use new variant of the enableCUDATracing function

sycl/test-e2e/Matrix/joint_matrix_gemm_cuda.hpp, sycl/test-e2e/Matrix/joint_matrix_tensorcores_sm70.cpp, sycl/test-e2e/Matrix/joint_matrix_tensorcores_sm72.cpp, sycl/test-e2e/Matrix/joint_matrix_tensorcores_sm80.cpp
Improved joint_matrix layout test coverage.
The test framework that the cuda backend tests use has been updated to support all possible `joint_matrix` gemm API combinations, including all matrix layouts. the gemm header is backend agnostic; hence all backends could use this test framework in the future.
This test framework can also act as an example to show how to deal with different layout combinations when computing a general GEMM.
=> [SYCL][CUDA] Improved joint_matrix layout test coverage.

clang/lib/CodeGen/CodeGenTypes.cpp, clang/lib/Driver/Driver.cpp, clang/lib/Driver/ToolChains/Linux.cpp, clang/lib/Driver/ToolChains/SYCL.cpp, clang/lib/Driver/ToolChains/SYCL.h, clang/lib/Sema/SemaExpr.cpp, clang/lib/Sema/SemaSYCL.cpp, clang/tools/clang-offload-deps/ClangOffloadDeps.cpp, llvm/lib/SYCLLowerIR/ESIMD/ESIMDUtils.cpp, llvm/lib/SYCLLowerIR/ESIMD/LowerESIMD.cpp, llvm/lib/SYCLLowerIR/PrepareSYCLNativeCPU.cpp, llvm/lib/Support/PropertySetIO.cpp, llvm/lib/Support/SimpleTable.cpp, llvm/lib/TargetParser/Triple.cpp, llvm/lib/Transforms/InstCombine/InstCombineCasts.cpp, llvm/lib/Transforms/Instrumentation/SPIRITTAnnotations.cpp, llvm/tools/sycl-post-link/ModuleSplitter.cpp, llvm/tools/sycl-post-link/SYCLDeviceLibReqMask.cpp, llvm/tools/sycl-post-link/SpecConstants.cpp, llvm/tools/sycl-post-link/sycl-post-link.cpp
Replace some deprecated 'startswith' and 'endswith' with 'starts_with' and 'ends_with' to clear some warnings when building SYCL compiler.
=> [SYCL][NFC] Fix some 'startswith/endswith' related to SYCL

clang/include/clang/Driver/Options.td, clang/lib/Driver/ToolChains/MSVC.cpp, clang/test/Driver/Xarch.c, clang/test/Driver/cl-options.c
We currently support -O3 for Linux compilations, expand this to also be available on Windows.  This also better aligns with our existing product offerings.
=> [Driver] Allow for -O3 on Windows using clang-cl

sycl/include/sycl/detail/pi.h, sycl/plugins/cuda/pi_cuda.cpp, sycl/plugins/hip/pi_hip.cpp, sycl/plugins/level_zero/pi_level_zero.cpp, sycl/plugins/native_cpu/pi_native_cpu.cpp, sycl/plugins/opencl/pi_opencl.cpp, sycl/plugins/unified_runtime/CMakeLists.txt, sycl/plugins/unified_runtime/pi2ur.hpp, sycl/plugins/unified_runtime/pi_unified_runtime.cpp, sycl/source/detail/buffer_impl.cpp, sycl/source/detail/memory_manager.cpp, sycl/source/interop_handle.cpp, sycl/test-e2e/HostInteropTask/interop-task-hip.cpp, sycl/unittests/helpers/PiMockPlugin.hpp
We want to change the signature of `piMemGetNativeHandle` for reasons explained here https://github.com/oneapi-src/unified-runtime/pull/1199
Corresponding UR PR: https://github.com/oneapi-src/unified-runtime/pull/1226
A previous PR added a new entry point https://github.com/intel/llvm/pull/12199 but it was decided that it is better to modify the existing entry point
=> [SYCL][HIP][CUDA] Use new version of piMemGetNativeHandle and add test

sycl/include/sycl/ext/intel/esimd/memory.hpp, sycl/test-e2e/ESIMD/unified_memory_api/Inputs/scatter.hpp
Problems found by Gregory (thanks!):
1) There were some duplicated tests, remove those
2) We didn't test non-LSC mask on Gen12
3) We get an ambiguous call because we had an old function that didn't have VS, but the new functions have default VS=1, so we don't need the old one.
4) When we pass a simd_view for the vals, we got a template match failure. This is the same issue we hit in the compile-time tests where even if we have a simd_view overload the compiler can't infer N, so we need to provide T,N anyway, so add that in the tests.
I tested this on Gen12.
=> [SYCL][ESIMD] Fix a few issues with scatter(usm, ...)

sycl/plugins/native_cpu/CMakeLists.txt
Adding `EXCLUDE_FROM_ALL` to the `add_subdirectory` for the OneAPI Construction Kit, in order to to avoid building its components unless they are required by the SYCL toolchain.
=> [SYCL] [NATIVECPU] Add OCK subdirectory with EXCLUDE_FROM_ALL

sycl/test-e2e/AddressCast/dynamic_address_cast.cpp
The FPGA emulator is currently affected by the same issue as the CPU runtime.
=> [SYCL] Disable dynamic_address_cast test on FPGA

sycl/source/detail/memory_manager.cpp, sycl/test-e2e/Graph/Explicit/buffer_fill_2d.cpp, sycl/test-e2e/Graph/Explicit/buffer_fill_3d.cpp, sycl/test-e2e/Graph/Inputs/buffer_fill_2d.cpp, sycl/test-e2e/Graph/Inputs/buffer_fill_3d.cpp, sycl/test-e2e/Graph/RecordReplay/buffer_fill_2d.cpp, sycl/test-e2e/Graph/RecordReplay/buffer_fill_3d.cpp
Adds support for 2d and 3d buffer fill ops (implementation based on the regular buffer fill submission). 
Adds tests that verify 2d and 3d buffer fill.
=> [SYCL][Graph] Support for 2d and 3d buffer fill ops

sycl/test-e2e/syclcompat/atomic/atomic_class.cpp, sycl/test-e2e/syclcompat/atomic/atomic_memory_acq_rel.cpp
Fix UB in test by using a single thread task.
A shared USM variable was being simultaneously written to by multiple threads without using atomics. AFAIK this is generally not a well defined program, and was leading to invalid values.
seq_cst also requires sm_70 on CUDA, so the compilation invocation is updated to reflect this.
The CI device is >= sm_70 so it can use seq_cst. However this test did not compile for >=sm_70.
=> [syclcompat][CUDA] FIX UB in test / seq_cst requires sm_70 on CUDA.

sycl/test-e2e/Assert/assert_in_multiple_tus.cpp, sycl/test-e2e/Assert/assert_in_multiple_tus_one_ndebug.cpp
See https://github.com/intel/llvm/issues/8832, the test is flaky in post-commit/nightly.
=> [SYCL][E2E] Disable assert_in_multiple_tus[_one_ndebug].cpp on cuda

sycl/source/detail/pi.cpp
A future PR will add support for magic numbers other than four bytes. Refactor the code to make those future changes easier to review.
=> [NFCI][SYCL] Refactor getBinaryImageFormat

sycl/doc/extensions/experimental/sycl_ext_oneapi_device_architecture.asciidoc, sycl/doc/extensions/proposed/sycl_ext_oneapi_device_if.asciidoc
The change was made based on a comment
https://github.com/intel/llvm/pull/12259#pullrequestreview-1843169980
=> [SYCL][Doc][NFC] Rename 'fallback' to 'generic' in two specs

sycl/include/sycl/detail/builtins/relational_functions.inc, sycl/test-e2e/Basic/built-ins/marray_relational.cpp, sycl/test-e2e/Basic/built-ins/scalar_relational.cpp, sycl/test-e2e/Basic/built-ins/vec_relational.cpp
This regressed after #11956 as return type wasn't correctly converted from SPIR-V intrinsic back to SYCL types. This PR fixes that.
In addition, I'm also adding tests for `sycl::select` builtin that was left unaffected only because we couldn't use SPIR-V intrinsic for its implementation.
=> [SYCL] Fix bitselect builtin for integer types

sycl/test-e2e/ESIMD/api/functional/ctors/ctor_fill_core.cpp, sycl/test-e2e/ESIMD/api/functional/ctors/ctor_fill_fp_extra.cpp
The tests are passing with the latest xmain/driver
=> [SYCL][ESIMD] Remove no-fast-math option for tests

sycl/source/detail/jit_compiler.cpp
Remove names of individual and internal ticket IDS from TODO comments in code.
=> [SYCL][Fusion][NFC] Remove name and ticket ID from TODOs

sycl/test-e2e/lit.cfg.py, sycl/tools/sycl-ls/sycl-ls.cpp
As per the ONEAPI_DEVICE_SELECTOR [documentation](https://github.com/intel/llvm/blob/sycl/sycl/doc/EnvironmentVariables.md#oneapi_device_selector), the device type can only be cpu, gpu, or fpga (or any combination of those). Currently, 'acc' is also accepted by ONEAPI_DEVICE_SELECTOR as a valid device type, which is incorrect.
This PR modifies lit.cfg.py and sycl-ls  to use 'fpga' instead of 'acc' in ONEAPI_DEVICE_SELECTOR.
=> [SYCL] Update test scripts and sycl-ls to use 'fpga' with ONEAPI_DEVICE_SELECTOR

sycl/test-e2e/ESIMD/aot_mixed.cpp
If we pass `%gpu_aot_target_opt` that compiles for all GPUs and we hit an ocloc bug when compiling for  xe-lpgplus-a0 in the new driver. This is blocking driver uplift. I will make an internal ticket for the IGC team.
=> [SYCL][ESIMD][E2E] Run aot_mixed.cpp only on Gen12 for now

clang/lib/Driver/ToolChains/SYCL.cpp, clang/test/Driver/sycl-device-lib.cpp
User can enable Asan for SYCL device code via -Xarch_device, we need to link Asan device library with user's device image in such case.
=> [SYCL][Driver] Link Asan device lib when enabling Asan via Xarch_device

sycl/test-e2e/ESIMD/linear/linear.cpp, sycl/test-e2e/InvokeSimd/Spec/simd_size/simd8.cpp, sycl/test-e2e/KernelFusion/jit_caching_multispirv.cpp, sycl/test-e2e/KernelFusion/jit_caching_multitarget.cpp
Adjusted `REQUIRES` clauses in SYCL E2E tests to better represent their requirements: those tests were either gated by wrong device types, or they were gated by specific HW identifier instead of an aspecto/optional feature.
All changed tests fail in my local environment without the patch.
=> [SYCL][NFC] Make E2E more robust in different environments

sycl/doc/extensions/experimental/sycl_ext_oneapi_graph.asciidoc
The merged PR https://github.com/intel/llvm/pull/11472 added support for `handler::fill` and `handler::memset` nodes in a graph, while merged PR
https://github.com/intel/llvm/pull/11474 added support for `handler::prefetch` and `handler::mem_advise`. Remove mentions of these as limitations from the specification, as they are now supported.
=> [SYCL][Graph] Remove expired limitations from specification

sycl/doc/extensions/experimental/sycl_ext_oneapi_complex.asciidoc
This PR is the updated version of the "complex support for sycl::marray" extension, which used to be a separate extension.
However, after discussing whether it should be a separate extension versus an expansion (https://github.com/intel/llvm/pull/8852), the complex expansion has been decided.
Following the proposal for `sycl::ext::oneapi::experimental::complex` which adds the support of complex for SYCL, this expansion proposes to incorporate complex support for `sycl::marray` and new complex math features.
@gmlueck @steffenlarsen 
Implementation: https://github.com/intel/llvm/pull/8647
=> [SYCL][DOC] Expand complex extension with complex support for sycl::marray

sycl/plugins/unified_runtime/pi2ur.hpp
This solves the same issues as #12432, but for `urDeviceCreateWithNativeHandle`. I considered a more generalized solution (e.g., calling `urGetAdapter` in `piPluginInit`), but I'm not sure that's worth it considering PI is going away. All the other `CreateWithNativeHandle` functions require either platform or a device to already exist.
=> [UR] call urGetAdapter before creating a device from native handle

sycl/doc/design/KernelFusionJIT.md
Document reduction strategies supported by kernel fusion and how users should use reductions in their code.
=> [SYCL][Fusion][Doc] Document reductions support

.github/workflows/sycl-linux-precommit.yml, .github/workflows/sycl-post-commit.yml, .github/workflows/sycl-windows-precommit.yml
Let me see if this works, I want to use this param in an E2E test.
=> [CI] Pass gpu-intel-gen12=True when running on Gen12

sycl/doc/extensions/proposed/sycl_ext_oneapi_group_sort.asciidoc
From the implementation perspective it's important to have `memory_required` in `default_sorters` dependent on the SYCL device. It happens because `default_sorters` has no specified algorithm inside it can depend on the specific SYCL device. `radix_sorters` has specific algorithm (radix sorter) that doesn't depend on the backend.
Removed `constexpr` for default sorters since it's extra there. It's still fine for radix sorters since the algorithm is fixed and can't depend on the backend
Signed-off-by: Fedorov, Andrey <andrey.fedorov@intel.com>
=> [SYCL][DOC] Add an overload for memory_required in joint_sorter

sycl/include/sycl/detail/builtins/common_functions.inc, sycl/include/sycl/detail/builtins/integer_functions.inc, sycl/source/builtins/common_functions.cpp, sycl/source/builtins/integer_functions.cpp
SYCL2020, revision 8 defines two separate clamp functions - once in integer functions and once in common functions. Follow the same in the implementation so that clamp's handling is uniform with other common/integer functions.
=> [SYCL] Split sycl::clamp implementation in two

sycl/doc/extensions/proposed/sycl_ext_oneapi_forward_progress.asciidoc
sycl_ext_oneapi_launch_queries was originally part of sycl_ext_oneapi_forward_progress. When we split things into two extensions, we forgot to update one of the links.
=> [SYCL][Doc] Fix broken link in forward_progress

sycl/doc/extensions/proposed/sycl_ext_oneapi_root_group.asciidoc
Adding new enum "execution_scope" and few member functions
=> [SYCL][DOC] Extend sycl_ext_oneapi_root_group

sycl/test-e2e/ESIMD/aot_mixed.cpp
Arg was wrong. Manually tested this. CI is current broken because of this,
=> [SYCL][ESIMD][E2E] Fix aot_mixed.cpp

sycl/doc/extensions/experimental/sycl_ext_oneapi_complex.asciidoc
This PR apply the modifications asked in the https://github.com/intel/llvm/pull/11792 PR made by @Pennycook
=> [SYCL][DOC] Update the 'constraints' for the complex specification

sycl/source/detail/allowlist.cpp, sycl/source/detail/config.cpp, sycl/source/detail/config.hpp, sycl/source/detail/device_filter.cpp, sycl/unittests/allowlist/ParseAllowList.cpp
As per the ONEAPI_DEVICE_SELECTOR [documentation](https://github.com/intel/llvm/blob/sycl/sycl/doc/EnvironmentVariables.md#oneapi_device_selector), the device type can only be cpu, gpu, or fpga (or any combination of those). Currently, 'acc' is also accepted by ONEAPI_DEVICE_SELECTOR as a valid device type, which is incorrect.
This PR modifies drops support of 'acc' in ONEAPI_DEVICE_SELECTOR in favor of 'fpga'. We have already updated existing test cases (#12551), testing scripts (#12596 ) to use 'fpga' with ONEAPI_DEVICE_SELECTOR.
=> [SYCL] Drop 'acc' in favor of 'fpga' from ONEAPI_DEVICE_SELECTOR

sycl/doc/design/CompilerAndRuntimeDesign.md
This simple PR fix the `libspriv` typo and removes the unnecessary trailing whitespace.
=> [SYCL][DOC] Trim trailing whitespace and fix typo

sycl/source/detail/queue_impl.cpp, sycl/source/detail/queue_impl.hpp, sycl/source/detail/scheduler/commands.cpp, sycl/source/handler.cpp
The old variable name for support of discarding PI events (MHasDiscardEventsSupport) made it easy to confuse with discarding SYCL events (MDiscardEvents), especially since we could have a situation where MHasDiscardEventsSupport is false, but MDiscardEvents is true.
Rename the variable for discarding PI events and reword its comment to make the distinction clearer.
=> [SYCL][NFC] Reduce ambiguity between discarding SYCL and PI events

sycl/include/sycl/builtins_preview.hpp, sycl/include/sycl/detail/builtins/integer_functions.inc, sycl/include/sycl/detail/builtins/relational_functions.inc
There are some issues with them as well (both in naming and bugs in implementation), to be fixed in a separate PR to ease review.
=> [NFC][SYCL] Move helpers from builtins_preview.hpp to their single uses

sycl/test-e2e/ESIMD/unified_memory_api/Inputs/atomic_update.hpp, sycl/test-e2e/ESIMD/unified_memory_api/Inputs/atomic_update_slm.hpp
Reverts intel/llvm#12639
This regressed atomic_update_acc_dg2_pvc_cmpxchg.cpp
=> Revert "[ESIMD][E2E] Enable few cases in atomic_update after gpu driver update"

sycl/test-e2e/lit.cfg.py
In PR#https://github.com/intel/llvm/pull/12596, we changed the output of sycl-ls to use 'fpga' instead of 'acc'. This has caused several tests to fail when fpga is available on the system. This PR fixes that.
In retrospect, we should have enabled testing on FPGA in pre-commit testing as this bug could have been caught earlier.
=> [SYCL][E2E] Fix the test script after changing sycl-ls output

sycl/include/sycl/builtins_preview.hpp, sycl/include/sycl/builtins_utils_scalar.hpp, sycl/include/sycl/detail/builtins/helper_macros.hpp, sycl/include/sycl/detail/builtins/integer_functions.inc, sycl/include/sycl/detail/builtins/relational_functions.inc, sycl/source/builtins/host_helper_macros.hpp, sycl/source/builtins/integer_functions.cpp, sycl/source/builtins/relational_functions.cpp, sycl/test/basic_tests/builtins/builtin_unit_tests.cpp
In case of vectors/swizzles of integer types only fixed width types are
allowed per SYCL 2020 revision 8. Update the implementation to match
that.
=> [SYCL] Fix SFINAE rules for integer builtins/bitselect

sycl/source/detail/scheduler/graph_builder.cpp, sycl/test-e2e/KernelFusion/Reduction/group_reduce_and_last_wg_detection.cpp, sycl/test-e2e/KernelFusion/queue-shortcut-functions.cpp
`sycl::queue` shortcut functions, e.g., `sycl::queue::memcpy`, may not
create a command group, so events coming from those will not have a
command group attached. Avoid deadlock when going through event list
in fusion mode.
=> [SYCL][Fusion] Avoid deadlock on events with no command group

sycl/include/sycl/kernel_bundle.hpp, sycl/source/detail/device_image_impl.hpp, sycl/test-e2e/SpecConstants/2020/image_selection.cpp
If -fsycl-add-default-spec-consts-image option is used then DPCPP generates a device image where default values of specialization constants are inlined (in addition to regular device image).
Currently we always choose regular device image if somebody calls `set_specialization_constant ` API.
This PR improves this behavior: if  `set_specialization_constant` sets the value equal to default value then we can choose  the device image where default values of specialization constants are inlined.
=> [SYCL] Choose image with inlined default values if default value is set explicitly

sycl/plugins/unified_runtime/pi2ur.hpp
- Remove the restriction in pi2ur such that piMemBufferCreate can pass the pi_mem_properties as the pNext properties to the UR Adapters.
=> [UR] Pass pi_mem_properties in pi2ur for piMemBufferCreate

sycl/include/sycl/access/access.hpp, sycl/test/type_traits/type_traits.cpp
Previous implementation was incorrect because multiple specialization were matching resulting in an ambiguity.
=> [SYCL] Fix remove_decoration for cv-qual decorated ponters/refs

sycl/include/sycl/detail/spirv.hpp, sycl/include/sycl/ext/oneapi/experimental/non_uniform_groups.hpp, sycl/include/sycl/ext/oneapi/sub_group_mask.hpp, sycl/include/sycl/group.hpp
Follow-up for https://github.com/intel/llvm/pull/12674, updating places where `ConvertToOpenCLType_t` was used with a plain cast instead of `convertDataToType`.
Not touching `multi_ptr` related uses just yet.
=> [NFCI][SYCL] Use convertToOpenCLType in more places

sycl/source/detail/scheduler/graph_builder.cpp
Add comment stating event dependencies on any commands part of a different active fusion leads to the abortion of that fusion.
=> [SYCL][Fusion][NFC] Comment fusion abortion on inter-fusion dependency

sycl/plugins/unified_runtime/CMakeLists.txt, sycl/plugins/unified_runtime/pi2ur.hpp
The new entry-points added by https://github.com/oneapi-src/unified-runtime/pull/1089 are currently unused by SYCL-Graph, but will be build upon later in https://github.com/intel/llvm/pull/12486
=> [SYCL][UR][Graph] Bump UR commit to kernel update

sycl/source/detail/program_manager/program_manager.cpp
The -ze-take-global-address IGC option was required for IGC to correctly record addresses of device globals. This should be on automatically in newer IGC versions however, so this commit removes the option.
=> [SYCL] Remove the implicitly passed -ze-take-global-address IGC option

sycl/doc/design/KernelFusionJIT.md, sycl/test-e2e/KernelFusion/GroupAlgorithm/permute.cpp, sycl/test-e2e/KernelFusion/GroupFunctions/group_broadcast_remapping.cpp
Add tests for `group_broadcast` and `permute_group_by_xor` when remapping is needed.
Document support for group algorithms and functions in the kernel fusion design document. Kernel fusion supports these constructs, as local range, group id and local id do not change due to remapping.
=> [SYCL][Fusion] Test and document group algorithms/function support

sycl-fusion/jit-compiler/lib/fusion/FusionHelper.cpp, sycl-fusion/passes/cleanup/Cleanup.cpp, sycl-fusion/passes/internalization/Internalization.cpp, sycl-fusion/passes/kernel-fusion/Builtins.cpp, sycl-fusion/passes/kernel-fusion/SYCLKernelFusion.cpp, sycl-fusion/passes/target/TargetFusionInfo.cpp
Set `IsNewDbgInfoFormat` to the default value for functions created in the SYCL Kernel Fusion pipeline. This prepares `sycl-fusion` for migration to the new debug info format.
=> [SYCL][Fusion] Set `IsNewDbgInfoFormat` when creating new functions

sycl/test-e2e/lit.cfg.py
Include the necessary environment paths during the test-e2e build for `CUDA` and `HIP` backends.
The absence of the added path leads to the inability to locate libdevice for specific architectures, resulting in a failure. 
Below is the reported error when expected `CUDA_PATH` is missing
`
clang++: error: cannot find libdevice for `sm_50`; provide path to different `CUDA` installation via '--cuda-path', or pass '-nocudalib' to build without linking with libdevice
`
=> [CUDA][HIP][TEST-E2E] Include the necessary environment paths during the test-e2e build for CUDA and HIP backends.

sycl/test-e2e/syclcompat/kernel/kernel_win.cpp
-shared flag is a clang/linux option. On Windows we need to be cognizant of possibly using MSVC compatible driver (e.g. icx) Needs `/clang` passthrough when using non MSVC options
=> [SYCL] fix for syclcompat test on Windows

sycl/include/sycl/types.hpp
This commit does a partial revert of https://github.com/intel/llvm/pull/12396. This is to avoid an issue where the new friend operators wouldn't accept the arguments as l-value references.
=> [SYCL] Revert friend changes to assignment and incr/decr for swizzles

sycl/include/sycl/ext/intel/esimd/memory.hpp, sycl/test-e2e/ESIMD/unified_memory_api/Inputs/atomic_update.hpp
atomic_update() for USM and ACC N=16,32 were lowered to SVM/DWORD atomic
intrinsics even though the HW instructions on Gen12 supported only
N up to 8 for USM and up to 16 for ACC.
GPU had legalization pass for N that split longer vectors to smaller and available in HW.
That GPU optimization/legalization workes incorrectly for USM as it
splits longer vectors assuming instruction is available for N=16 in case
of USM, which is not correct.
The patch here implements splitting of N=16 and N=32 cases for
atomic_update(usm, ...) to N=8 vectors until GPU fixes the legalization
for USM atomic_update.
=> [ESIMD] Fix atomic_update() implementation for N=16 and N=32 on Gen12

sycl/cmake/modules/AddSYCL.cmake
This is a generalization of the existing workarounds:
https://github.com/intel/llvm/blob/sycl/sycl/plugins/unified_runtime/CMakeLists.txt#L40-L54
etc.
=> [SYCL] Disable warnings when compiling plugins from UR sources

sycl/test-e2e/Config/default-context.cpp
despite having a unit test for default context, realized there is not one to affirm the new default configuration.
=> [SYCL] add overlooked default context test . 

mlir/lib/Dialect/LLVMIR/IR/GENXOps.cpp, mlir/lib/Target/LLVMIR/Dialect/GENX/GENXToLLVMIRTranslation.cpp, mlir/test/Dialect/LLVMIR/genx-invalid.mlir, mlir/test/Target/LLVMIR/genx.mlir
`@llvm.genx.GenISA.sub.group.dpas.v8f32.v8f32.v4i32.v8i32` is not valid on PVC.
This reverts commit 40a18fa33230a92566dc348aec70da1e253f65ca.
=> [GEN] Revert "Changes to the DPAS op. (#12554)"

sycl/plugins/unified_runtime/pi_unified_runtime.cpp
`LoaderConfig` is created and stored in a local pointer and never released when done using, causing it to be leaked.
This patch releases the `LoaderConfig` when finished using it.
=> Fix a leak in pi_unified_runtime.cpp.

sycl/include/sycl/builtins_legacy_scalar.hpp, sycl/include/sycl/detail/generic_type_traits.hpp
Old builtins implementation is going to be removed in the next ABI breaking window and that helper is only used there.
=> [NFC][SYCL] Move a helper to its single legacy use

mlir/include/mlir/Dialect/LLVMIR/GENXOps.td, mlir/lib/Target/LLVMIR/Dialect/GENX/GENXToLLVMIRTranslation.cpp, mlir/test/Target/LLVMIR/genx.mlir
Rounding mode is not needed for extension.
=> [GEN] Make `RoundingMode` optional for `FpToFpOp`

clang/test/SemaHLSL/standard_conversion_sequences.hlsl
The test fails due missing warning, the warning was added in SYCL web
long time ago, vs e4f5d55f91f19ebc13852e3cdd60b39d68251bab
The test is newly added test from change:
5c57fd717d5d6a285efeb8402c6fe0c8f70592f3
=> [SYCL] Disable implicit-float-size-conversion warning in community tests

sycl/test-e2e/ESIMD/accessor_global.cpp, sycl/test-e2e/ESIMD/accessor_local.cpp, sycl/test-e2e/ESIMD/api/simd_view_copy_move_assign.cpp, sycl/test-e2e/ESIMD/dpas/dpas_common.hpp, sycl/test-e2e/ESIMD/esimd_test_utils.hpp, sycl/test-e2e/ESIMD/ext_math.cpp, sycl/test-e2e/ESIMD/grf.cpp, sycl/test-e2e/ESIMD/histogram.cpp, sycl/test-e2e/ESIMD/histogram_256_slm.cpp, sycl/test-e2e/ESIMD/histogram_256_slm_spec_2020.cpp, sycl/test-e2e/ESIMD/histogram_2d.cpp, sycl/test-e2e/ESIMD/histogram_raw_send.cpp, sycl/test-e2e/ESIMD/lsc/Inputs/lsc_surf.hpp, sycl/test-e2e/ESIMD/lsc/lsc_argument_type_deduction.cpp, sycl/test-e2e/ESIMD/lsc/lsc_predicate.cpp, sycl/test-e2e/ESIMD/lsc/lsc_predicate_stateless.cpp, sycl/test-e2e/ESIMD/lsc/lsc_slm.cpp, sycl/test-e2e/ESIMD/lsc/lsc_slm_atomic_smoke.cpp, sycl/test-e2e/ESIMD/named_barriers/exec_in_order.cpp, sycl/test-e2e/ESIMD/named_barriers/exec_in_order_branched.cpp, sycl/test-e2e/ESIMD/named_barriers/loop.cpp, sycl/test-e2e/ESIMD/named_barriers/loop_extended.cpp, sycl/test-e2e/ESIMD/named_barriers/multiple_wg.cpp, sycl/test-e2e/ESIMD/named_barriers/single_wg.cpp, sycl/test-e2e/ESIMD/noinline_call_from_func.cpp, sycl/test-e2e/ESIMD/radix_sort.cpp, sycl/test-e2e/ESIMD/regression/Inputs/complex-lib-sycl.cpp, sycl/test-e2e/ESIMD/regression/Inputs/dgetrf.hpp, sycl/test-e2e/ESIMD/regression/big_const_initializer.cpp, sycl/test-e2e/ESIMD/regression/dgetrf_8x8.cpp
Warnings fixed:
- deprecated scatter_rgba
- deprecated get_cl_code
- deprecated lsc_fence
- deprecated uchar type usage
- deprecated get_access on HOST
- deprecated get_pointer
- usage of isfinite with -ffast-math
- deprecated dpas_argument_type::s1
- deprecated gpu_selector()
Also, the memory alloc/free in historgram*.cpp tests were updated to simplify the potential memory leak avoidance.
=> [ESIMD][NFC][E2E] Fix 570 compilation warnings in ESIMD E2E tests

sycl/test-e2e/Basic/accessor/empty_zero_dim_accessor.cpp
The behavior seems to have changed after
https://github.com/intel/llvm/pull/12764.
=> [SYCL][E2E] Remove XFAIL from Basic/accessor/empty_zero_dim_accessor.cpp

sycl/source/detail/queue_impl.cpp, sycl/source/detail/queue_impl.hpp, sycl/test-e2e/Basic/stream/auto_flush.cpp
Now that submitting a task to an in-order queue can lock its main mutex, the vector of stream service events (which can be accessed during that same submission) should use a different mutex to avoid deadlocks.
=> [SYCL] Fix a stream related in-order queue hang

sycl/source/detail/allowlist.cpp, sycl/source/detail/config.cpp, sycl/source/detail/config.hpp, sycl/source/detail/device_filter.cpp, sycl/unittests/allowlist/ParseAllowList.cpp
The output of getSyclDeviceTypeMap() is different for SYCL_DEVICE_ALLOWLIST and ONEAPI_DEVICE_SELECTOR. However, currently, we return a reference to a 'static const' type, which causes calls to getSyclDeviceTypeMap() return the same value, irrespective of 'supportAcc'. This results in several test failures.
This PR makes 'supportAcc' a template parameter instead.
=> [SYCL] Make 'supportAcc' a template variable in getSyclDeviceTypeMap

sycl/source/detail/platform_impl.cpp, sycl/test-e2e/Basic/get_backend.cpp, sycl/test-e2e/Config/select_device.cpp
So that the first one would contain the most preferrable device in case SYCL applications/library performs manual device selection and defaults to the first available device.
=> [SYCL] Sort platforms in platform::get_platforms()

sycl/include/sycl/usm/usm_allocator.hpp, sycl/test-e2e/USM/usm_allocator_zero_allocation.cpp
Currently, usm allocator throws when the allocation size is zero. However, this behavior is not aligned with that of std::allocator.
Refer https://github.com/KhronosGroup/SYCL-Docs/issues/355 for discussion regarding this. The spec says that the allocation functions must succeed when the size is zero.  The value returned in this case is unspecified (it can either be a NULL pointer or a non-NULL pointer)
This PR makes USM allocator return a null pointer when the allocation size is zero.
=> [SYCL] Return nullptr when allocation size is zero in usm allocator

sycl/include/sycl/ext/oneapi/experimental/ballot_group.hpp, sycl/include/sycl/ext/oneapi/experimental/fixed_size_group.hpp, sycl/test-e2e/NonUniformGroups/ballot_group.cpp, sycl/test-e2e/NonUniformGroups/fixed_size_group.cpp, sycl/test-e2e/NonUniformGroups/opportunistic_group.cpp, sycl/test-e2e/NonUniformGroups/tangle_group.cpp
Not all sub-groups are necessarily the max size of sub-groups in the kernel invocation. As such, non-uniform groups should handle these sub-groups properly. However, due to how the mask for the false-group in ballot_group creates its mask, it thinks it has full 32-element size no matter how big the actual sub-group is. This commit fixes this issue.
=> [SYCL] Fix ballot_group when the sub-group is not full size

sycl/plugins/unified_runtime/CMakeLists.txt
- fix to address a multi device crash given many devices causing a stack overflow. Event Caches per device are now explicitly allocated.
- pre-commit PR for https://github.com/oneapi-src/unified-runtime/pull/1366
=> [UR][L0] Fix the multi device event cache to allocate lists as pointers

sycl/include/CL/__spirv/spirv_ops.hpp, sycl/include/sycl/ext/oneapi/matrix/matrix-intel.hpp
In order to support OpCooperativeMatrixConstructCheckedINTEL instruction the builtin name must be updated to the corresponding spelling: __spirv_CooperativeMatrixConstructCheckedINTEL
=> [SYCL][Matrix] Update builtin name for the checked matrix construct SPIR-V instruction

clang/lib/Driver/ToolChains/MSVC.cpp, clang/test/Driver/sycl-offload.c
This PR is addressing the following scenario:
clang-cl -I[path to sycl headers] sycl_program.cpp # program compiled but without sycl libs
clang-cl -fsycl sycl_program.obj # user expects sycl libs to be linked automatically here.
Without this fix this scenario fails at link step because sycl libraries are not pulled in.
This scenario already works for clang driver, so only clang-cl needs a fix.
=> [SYCL][Driver] Link with sycl libs at link step of clang-cl -fsycl

sycl/include/sycl/ext/intel/esimd/memory.hpp, sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp, sycl/test-e2e/ESIMD/unified_memory_api/Inputs/scatter.hpp, sycl/test-e2e/ESIMD/unified_memory_api/scatter_acc.cpp, sycl/test-e2e/ESIMD/unified_memory_api/scatter_acc_dg2_pvc.cpp, sycl/test/esimd/memory_properties.cpp
This implements the new compile-time properties API for scatter with accessors. I believe this is the last missing piece.
=> [SYCL][ESIMD] Implement compile-time properties version of scatter(acc, ...)

sycl/test/tools/sycl-ls.test, sycl/tools/sycl-ls/sycl-ls.cpp
This PR adds a '--ignore-device-selectors' CLI option to sycl-ls that prints all platforms available in the user's system, irrespective of the DPCPP filter environment variables like ONEAPI_DEVICE_SELECTOR.
=> [SYCL] Add '--ignore-device-selectors' CLI option to sycl-ls and improve warning messages

sycl/test-e2e/Config/select_device.cpp
Started to fail in post commit after
https://github.com/intel/llvm/pull/12719. This looks like a pre-existing bug in the test so I'm going to temporarily disable the test instead of reverting. Will work on the fix with highest priority after that.
=> [SYCL][E2E] Disable select_device.cpp on Arc GPU

.github/workflows/sycl-detect-changes.yml, .github/workflows/sycl-linux-precommit.yml, sycl/test-e2e/ESIMD/lit.local.cfg, sycl/test-e2e/ESIMD/printf.cpp
=> [CI] Run ESIMD tests on Arc in precommit when ESIMD changed

sycl/test-e2e/USM/usm_leak_check.cpp
**Problem:**
USM/usm_leak_check.cpp fails on multi-card PVC because the number of zeMemAlloc* and zeMemFree calls doesn't match what the test expects. This is mainly because of the recent changes to USM memory allocation, like a different memory pool logic.
**Proposed Fix**
Since the objective of this test is to just check for USM leaks, I don't think that we even have to check the output of UR_L0_LEAKS_DEBUG=1. It is my understanding that UR_L0_LEAKS_DEBUG=1 will abort upon finding a mismatch in the number of alloc/free calls. So, this PR removes explicit checks for zeMemAlloc* and zeMemFree calls.
=> [SYCL][E2E] Fix USM/usm_leak_check.cpp test for multi-card PVC

sycl/doc/extensions/proposed/sycl_ext_oneapi_free_function_kernels.asciidoc
We decided that simple "range" kernels are hard to implement with the free function kernel syntax.  This commit removes them from the extension specification.  See the "Resolved issues" section for the rationale.
=> [SYCL][Doc] No free function "range" kernels

sycl/test-e2e/bindless_images/user_types/mipmap_read_user_type_2D.cpp, sycl/test-e2e/bindless_images/user_types/read_write_user_type.cpp
Because VERBOSE_PRINT is also used inside file user_types_common.hpp
=> [NFC][SYCL][Bindless] Define VERBOSE_PRINT before include user_types_common.hpp

sycl/include/sycl/ext/oneapi/bindless_images.hpp
A declaration of get_mip_level_mem_handle incorrectly took sycl::device as a parameter, which should have been a sycl::queue. This is now fixed.
=> [SYCL][Bindless][Exp] Fix get_mip_level_mem_handle declaration.

libclc/ptx-nvidiacl/libspirv/synchronization/barrier.cl
- make relaxed fence a no op to satisfy the SYCL spec.
- make acquire/release/acq_rel use the lighter acq_rel fence for sm_70 instead of the seq_cst fence.
=> [CUDA][LIBCLC] Fix fence impl to satisfy SYCL 2020.

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/device.hpp, sycl/test-e2e/syclcompat/device/device.cpp, sycl/test-e2e/syclcompat/memory/memory_management_diff_queues.cpp
This PR adds mechanisms to change the default queue of the current device both via the device extension and a free function.
=> [SYCL][COMPAT] Add set_default_queue functionality

sycl/include/sycl/ext/intel/esimd/detail/bfloat16_type_traits.hpp, sycl/include/sycl/ext/oneapi/bfloat16.hpp, sycl/test-e2e/ESIMD/regression/bfloat16_vector_plus_scalar.cpp, sycl/test-e2e/ESIMD/regression/bfloat16_vector_plus_scalar_pvc.cpp, sycl/test/type_traits/half_operator_types.cpp
Aligns implementation with the spec: https://github.com/intel/llvm/blob/48ec4dd6ff45b25b405b99d63f3c5b8537b1475d/sycl/doc/extensions/supported/sycl_ext_oneapi_bfloat16.asciidoc
=> [SYCL] Limit bfloat16 operators to scalar datatypes convertible to float

sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp, sycl/test/esimd/nbarriers.cpp
=> [SYCL][ESIMD] named_barrier_signal should have a fence

clang/test/CodeGenSYCL/address-space-conversions.cpp, clang/test/CodeGenSYCL/amd-address-space-conversions.cpp, clang/test/CodeGenSYCL/cuda-address-space-conversions.cpp
Per @Naghasan 
The view in upstream is different as there is no device filtering yet (IIRC). sycl_device isn't there yet regardless (hence why it needs to be re-added) and in intel/llvm, nothing is emitted until you reach calls made by sycl_device function, causing the "reordering". 
1. Add __attribute__((sycl_device)) to so that the IR won't be empty.
2. Replace CHECK with CHECK-DAG because of the function order
3. Replace dso_local to {{*}} because of linkage
4. Replace declaration of tmpl to empty define tmpl..{} to avoid compilation error.
=> [SYCL-WEB] Fix test failures in address-space-conversions

mlir/include/mlir/Dialect/LLVMIR/GENXOps.td, mlir/test/Target/LLVMIR/genx.mlir
We use `genx.barrier` to lower `gpu.barrier` and the latter doesn't have attributes to specify any fence scope. We should be fine using local fences for `genx.barrier` unconditionally for now.
=> [GEN] Change barrier to use local fence

sycl/include/syclcompat/memory.hpp
group_local_memory becomes an issue for performance due to the initialization phase.
group_local_memory_for_overwrite allocates memory similarly without initialization, so, if initialization is needed, the user is now responsible for it.
More info: https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_oneapi_local_memory.asciidoc
=> [SYCL][COMPAT] Avoid local memory initialization through group_local_memory_for_overwrite

llvm/test/tools/sycl-post-link/spec-constants/SYCL-2020-zeroinitializer-array-of-arrays.ll, llvm/test/tools/sycl-post-link/spec-constants/SYCL-2020-zeroinitializer.ll, llvm/test/tools/sycl-post-link/spec-constants/SYCL-2020.ll, llvm/test/tools/sycl-post-link/spec-constants/SYCL2020-struct-with-undef-padding.ll, llvm/test/tools/sycl-post-link/spec-constants/bool.ll, llvm/test/tools/sycl-post-link/spec-constants/composite-O2.ll, llvm/test/tools/sycl-post-link/spec-constants/composite-default-value-padding.ll, llvm/test/tools/sycl-post-link/spec-constants/composite-no-sret.ll, llvm/test/tools/sycl-post-link/spec-constants/composite-padding-desc.ll, llvm/test/tools/sycl-post-link/spec-constants/default-value/bool.ll, llvm/test/tools/sycl-post-link/spec-constants/default-value/device-image.ll, llvm/test/tools/sycl-post-link/spec-constants/default-value/esimd.ll, llvm/test/tools/sycl-post-link/spec-constants/default-value/struct-with-padding.ll, llvm/test/tools/sycl-post-link/spec-constants/nested-struct.ll, llvm/test/tools/sycl-post-link/spec-constants/remove-dead-private-constants.ll, llvm/test/tools/sycl-post-link/spec-constants/struct-with-padding-in-the-middle.ll, llvm/test/tools/sycl-post-link/spec-constants/struct-with-undef-padding-2.ll, sycl/test/basic_tests/SYCL-2020-spec-constants.cpp
Recent changes made to specialization constants tests relied on `--debug-only` option, which is only enabled when assertions are enabled. This commit guards the commands using such an option to be run only when assertions are enabled.
This should fix the post-commit CI failure observed after #12647 was merged.
=> [SYCL] Fix failing specialization constants tests.

sycl/doc/extensions/experimental/sycl_ext_oneapi_spec_constant_length_alloca.asciidoc, sycl/doc/extensions/experimental/sycl_ext_private_alloca.asciidoc
Document extension proposal for specialization constant length private memory allocations. Users will be able to perform dynamic memory allocations using specialization constants and new `private_alloca` and `aligned_private_alloca` functions returning a `private_ptr` to a memory region of automatic storage duration.
This is included as an experimental extension as implementation will shortly follow once the extension is approved.
=> [SYCL][Doc] Add specialization constant-length alloca extension proposal

sycl/source/builtins/math_functions.cpp, sycl/test-e2e/Basic/built-ins/vec_math.cpp
The ones with FP/int vector parameters were implemented incorrectly.
=> [SYCL] Fix typo in host impl for some math builtins

clang/lib/CodeGen/BackendUtil.cpp, llvm/lib/SYCLLowerIR/PipelineSYCLNativeCPU.cpp
Fixes post commit failure from https://github.com/intel/llvm/pull/12659.
=> [SYCL][NATIVECPU] Move pipeline creation to CodeGen

sycl/include/sycl/types.hpp, sycl/test-e2e/InvokeSimd/Spec/clang_run_error/sycl_vec_argument.cpp
bfloat16 type reinterpretation may cause problems when aggressive optimizations are employed. Splitting them off to avoid this.
=> [SYCL] vec<bfloat16> optimization fix

sycl/doc/design/spirv-extensions/SPV_INTEL_function_pointers.asciidoc
=> [SYCL][Doc] Fix typo in SPV_INTEL_function_pointers

sycl/test-e2e/USM/usm_leak_check.cpp
usm_leak_check.cpp seems to be passing now on DG2 (https://github.com/intel/llvm/actions/runs/8055002796/job/22002608145) after my change in https://github.com/intel/llvm/commit/1b5719ec3c0af051f237023f7e2ca65e5374c680.
This PR removes XFAIL from this test on DG2.
=> [SYCL] [E2E] Remove XFAIL from usm_leak_check.cpp on DG2

sycl/doc/extensions/proposed/sycl_ext_oneapi_address_cast.asciidoc
This PR contains three improvements to the specification:
- Default address_cast to no decoration.
- Add overloads for generic multi_ptr.
- Add address_space shorthands.
This allows developers using generic raw pointers to cast to `multi_ptr` without worrying about decoration:
```c++
float* ptr = ...;
auto mptr = syclex::static_address_cast<syclex::local_space>(ptr);
```
...or to opt-in to decoration by using a generic multi-pointer, which propagates decoration information:
```c++
multi_ptr<float, syclex::generic_space, access::decorated::yes> decorated_in = ...;
auto decorated_out = syclex::static_address_cast<syclex::local_space>(decorated_in);
```
=> [SYCL][Doc] Update address_cast specification

sycl/doc/extensions/proposed/sycl_ext_oneapi_free_function_queries.asciidoc
- Removes get_linear_id(), get_id() and get_item()
- Renames get_group() to get_work_group()
- Adds deprecated functionality section
- Renames this_kernel namespace to this_work_item
=> [SYCL][Doc] Update free function queries extension

sycl/source/builtins/integer_functions.cpp, sycl/test-e2e/Basic/built-ins/marray_integer.cpp
In https://github.com/intel/llvm/pull/12856 I misunderstood what the spec meant by
> When the inputs are scalars, returns |x - y|. Otherwise, returns
> |x[i]- y[i]| for each element of x and y. The subtraction is done
> without modulo overflow. The behavior is undefined if the result
> cannot be represented by the return type.
Fix it here. We still differ from non-preview mode in return type - it used to be `unsigned` prior to SYCL2020 revision 8, I believe.
=> [SYCL] Fix abs_diff host implementation

clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/sycl-spirv-ext.c
SPV_KHR_bit_instructions is required when using __builtin_bitreverse32(). SYCL code that was compiled without that extension enabled and would fail when __builtin_bitreverse32() were present in source.
=> [SYCL] Enable SPV_KHR_bit_instructions for SYCL code

sycl/test-e2e/ESIMD/lsc/lsc_store_2d_u16.cpp, sycl/test-e2e/ESIMD/lsc/lsc_usm_store_u8_u16.cpp, sycl/test-e2e/ESIMD/lsc/lsc_usm_store_u8_u16_64.cpp
The tests fail with a JIT compilation error:
"add3 src operand only supports integer D/W type".
The tests should be enabled again when the issue in fixed in GPU driver.
=> [ESIMD][E2E] Disable lsc_*store_2d_u16* tests

sycl/test-e2e/AtomicRef/add.h, sycl/test-e2e/AtomicRef/and.h, sycl/test-e2e/AtomicRef/assignment.h, sycl/test-e2e/AtomicRef/compare_exchange.h, sycl/test-e2e/AtomicRef/exchange.h, sycl/test-e2e/AtomicRef/load.h, sycl/test-e2e/AtomicRef/max.h, sycl/test-e2e/AtomicRef/min.h, sycl/test-e2e/AtomicRef/or.h, sycl/test-e2e/AtomicRef/store.h, sycl/test-e2e/AtomicRef/sub.h, sycl/test-e2e/AtomicRef/xor.h
This duplicates existing SYCL atomic tests that use buffers with identical tests that use USM and memory allocated using `sycl::malloc_shared`. The motivation behind exercising atomics on `malloc_shared`-allocated memory is to catch issues such as https://github.com/ROCm/ROCm/issues/848 where native atomic instructions may fail when crossing the PCIe bus.
=> [SYCL] Add tests for atomic operations on malloc_shared-allocated memory

sycl/test/check_device_code/native_cpu/vectorization.cpp, sycl/test/lit.cfg.py, sycl/test/lit.site.cfg.py.in, sycl/test/native_cpu/barrier-external.cpp, sycl/test/native_cpu/barrier-simple.cpp
Currently the oneAPI Construction Kit is an optional dependency for the Native CPU backend, so we need to differentiate test requirements based on whether or not it is available.
=> [SYCL][NATIVECPU] Separate lit tag for oneAPI Construction Kit

sycl/test-e2e/Basic/built-ins/helpers.hpp, sycl/test-e2e/Basic/built-ins/marray_common.cpp
=> Revert "[SYCL][E2E] Refactor Basic/built-ins/marray_common.cpp"

sycl/doc/extensions/proposed/sycl_ext_oneapi_forward_progress.asciidoc
An automated renaming led to the sycl part of the namespace appearing in the wrong place.
=> [SYCL][Doc] Fix namespace in forward_progress spec

clang/lib/CodeGen/CGSYCLRuntime.cpp, clang/lib/Sema/SemaSYCL.cpp, clang/test/CodeGenSYCL/Inputs/sycl.hpp, clang/test/CodeGenSYCL/sycl-pf-work-item.cpp
Previously, we would mark parallel_for_work_item FunctionDecl only
when called directly from a parallel_for_work_group region.  This
change marks it when called even indirectly.
=> [SYCL] Mark parallel_for_work_item even when called indirectly

sycl/source/detail/config.hpp, sycl/test-e2e/OneapiDeviceSelector/empty_input_string.cpp, sycl/test-e2e/OneapiDeviceSelector/illegal_input.cpp, sycl/test/basic_tests/device-selectors-exception.cpp
```ONEAPI_DEVICE_SELECTOR=""``` causes SYCL runtime to silently not select/initialize any device at all. This PR makes SYCL runtime to throw an error when input to ONEAPI_DEVICE_SELECTOR is null.
=> [SYCL] Make ONEAPI_DEVICE_SELECTOR reject an empty string

sycl/test-e2e/Plugin/level_zero_usm_residency.cpp
**Problem:**
Plugin/level_zero_usm_residency.cpp fails on **Multi-card PVC** due to unexpected number of calls to zeContextMakeMemoryResident. The test was expecting just one call to zeContextMakeMemoryResident upon piextUSMDeviceAlloc. However, 
`// RUN: env SYCL_PI_TRACE=-1 UR_L0_DEBUG=-1 %{l0_leak_check} %{run} %t.out 2>&1`
produces two calls to zeContextMakeMemoryResident.
```
---> piextUSMDeviceAlloc(
<unknown> : 0x7ffc41c1d888
<unknown> : 0x3086680
<unknown> : 0x3084230
<unknown> : 0x7ffc41c1d8b0
<unknown> : 4
<unknown> : 4
ZE ---> zeMemAllocDevice(Context->ZeContext, &ZeDesc, Size, Alignment, Device->ZeDevice, ResultPtr)
ZE ---> zeDeviceCanAccessPeer(D->ZeDevice, Device->ZeDevice, &P2P)
ZE ---> zeContextMakeMemoryResident(Context->ZeContext, D->ZeDevice, Ptr, Size)
ZE ---> …
```
=> [SYCL][E2E] Fix Plugin/level_zero_usm_residency.cpp on Multi-card PVC

sycl/include/sycl/ext/intel/experimental/grf_size_properties.hpp
https://github.com/intel/llvm/pull/12831 inadverdently removed the detail namespace opening from the GRF size property header. This commit returns this namespace.
=> [SYCL] Fix GRF size property header

sycl/test-e2e/Plugin/level_zero_usm_residency.cpp
Plugin/level_zero_usm_residency.cpp started passing in post-commit on DG2 (https://github.com/intel/llvm/actions/runs/8148488311/job/22271712949) after my change in https://github.com/intel/llvm/pull/12844.
=> [SYCL] [E2E] Remove XFAIL from Plugin/level_zero_usm_residency.cpp

clang/lib/Sema/SemaDeclAttr.cpp, clang/test/CodeGenSYCL/intel-fpga-device-global-host.cpp, clang/test/SemaSYCL/intel-fpga-device-global-host.cpp, clang/test/SemaSYCL/intel-fpga-device-global.cpp
https://github.com/intel/llvm/pull/12785 added support for non-const device_global variables on all FPGA memory attributes.  FPGA memory attributes should only work for device codes. They should have no effect on host code. This patch fixes bug where we emitted error when attributes are applied to device_globals variables for host compilation.
=> [SYCL][FPGA] Allow memory attributes on device_global variables for device compilation

sycl/doc/extensions/experimental/sycl_ext_oneapi_private_alloca.asciidoc
- Rename some C++ names used in the text for clarification
- Minor rephrasing
- Add example creating a `sycl::span` out of the returned pointer
=> [SYCL][Doc] Non semantic changes to `sycl_ext_oneapi_private_alloca`

sycl/doc/extensions/experimental/sycl_ext_oneapi_non_uniform_groups.asciidoc
The current extension for non-uniform groups state that ballot groups are numbered 0 if the predicate was true and 1 if the predicate was false. However, the implementation has the inverse numbering. This commit changes the extension to make the numbering consistent with the implementation, in turn making the group numbering directly convertible to a boolean value equal to the corresponding predicate.
=> [SYCL][Docs] Invert group numbering for ballot groups

sycl/source/detail/device_info.hpp
This patch relaxes reporting of unsupported HW for matrix_combinations
query.
Before: exception thrown in case customer uses matrix_combinations
query on platform unsupported by ext_oneapi_device_architecture.
With this patch: customer gets empty vector from matrix_combinations
query on platform unsupported by ext_oneapi_device_architecture.
=> [SYCL][Joint Matrix] Relax matrix_combinations error handling

sycl/include/sycl/kernel_handler.hpp, sycl/test/basic_tests/SYCL-2020-spec-constants.cpp
Lower enumeration specialization constants to `SpecConstant` in SPIR-V instead of `SpecConstantComposite`, thus handling them using their underlying integral types.
=> [SYCL] Correct handling of enumeration specialization constants

llvm-spirv/lib/SPIRV/libSPIRV/SPIRVEntry.h, llvm-spirv/test/extensions/INTEL/SPV_INTEL_fp_fast_math_mode/fp_contract_reassoc_fast_mode.ll
This reverts commit 339c1c6024e284a6becfc0abfbb1d3d63fa6527d.
It's a good-tiny fix, but we have to revert it for now.
=> Revert "Map FPFastMathModeINTEL on SPV_INTEL_fp_fast_math_mode (#2360)"

sycl/doc/extensions/proposed/sycl_ext_oneapi_profiling_tag.asciidoc
This commit clarifies the meaning of command_start on profiling tags.
=> [SYCL][Docs] Specify command_start meaning for profiling tags

clang/include/clang/Basic/Attr.td, clang/include/clang/Basic/Builtins.td, clang/include/clang/Basic/DiagnosticSemaKinds.td, clang/include/clang/Sema/Sema.h, clang/lib/CodeGen/CGBuiltin.cpp, clang/lib/CodeGen/CodeGenFunction.h, clang/lib/Sema/SemaChecking.cpp, clang/lib/Sema/SemaDeclAttr.cpp, clang/lib/Sema/SemaSYCL.cpp, clang/test/CodeGenSYCL/Inputs/private_alloca.hpp, clang/test/CodeGenSYCL/Inputs/sycl.hpp, clang/test/CodeGenSYCL/builtin-alloca.cpp, clang/test/SemaSYCL/Inputs/private_alloca.hpp, clang/test/SemaSYCL/Inputs/sycl.hpp, clang/test/SemaSYCL/builtin-alloca-errors-device.cpp, clang/test/SemaSYCL/builtin-alloca-errors-host.cpp, clang/test/SemaSYCL/builtin-alloca.cpp, clang/test/SemaSYCL/sycl-type-attr-ast.cpp, llvm/docs/LangRef.rst, llvm/include/llvm/IR/Intrinsics.td
The [`sycl_ext_oneapi_private_alloca`](https://github.com/intel/llvm/blob/56e9067ba69809fb6ea1fd4328456ca3a009f984/sycl/doc/extensions/experimental/sycl_ext_oneapi_private_alloca.asciidoc) adds new functions returning a pointer to a specialization constant length SYCL private memory allocation. This commit adds codegen support for these functions.
The `sycl::private_alloca` function is implemented as an alias to a new `__builtin_intel_sycl_alloca` builtin. This is needed to guarantee the call will lower to just an `alloca` instruction defining the private memory allocation.
This builtin lowers to a SYCL builtin call to `__builtin_sycl_unique_stable_id` and a call to a new `llvm.sycl.alloca` intrinsic. This intrinsic receives three arguments encoding the specialization constant used as …
=> [SYCL][SCLA] Add CodeGen capabilities for `sycl_ext_oneapi_private_alloca`

.github/ISSUE_TEMPLATE/2-bug-report-cuda.yml, .github/ISSUE_TEMPLATE/3-bug-report-hip.yml
The format from https://github.com/intel/llvm/pull/12910 was invalid.
This PR attempts to fix it.
Note: Descriptions have a 200 character limit.
=> [CUDA][HIP] Fix bug report template descriptions

sycl/source/queue.cpp, sycl/test-e2e/Regression/ext_oneapi_barrier_opt.cpp
Fix for https://github.com/intel/llvm/issues/12177
Now even if the waitlist consists of only empty events we still invoke the scheduler to submit barrier command. Scheduler creates sycl event with associated Barrier Command but doesn't actually enqueue a barrier because waitlist is empty  (consists of only empty events).  As a result, the event returned by such barrier doesn't have PI handle but it supposed to have. If such event is then passed to some another command later as a dependency then it leads to nullptr dereference.
So, filter out such events from waitlist to avoid going to sheduler in such scenarios.
Test provided by Andrey Alekseenko <andrey.alekseenko@scilifelab.se>
Co-authored-by:  Andrey Alekseenko <andrey.alekseenko@scilifelab.se>
=> [SYCL] Filter out empty events for the barrier with waitlist

sycl/include/sycl/detail/generic_type_traits.hpp, sycl/include/sycl/types.hpp, sycl/test/regression/vec_value_type.cpp
This PR adds the value_type alias for the data type of a sycl::vec object as described in the spec.
=> [SYCL] Add value_type alias to sycl::vec class

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/math.hpp, sycl/include/syclcompat/syclcompat.hpp, sycl/include/syclcompat/util.hpp, sycl/test-e2e/syclcompat/math/math_complex.cpp, sycl/test-e2e/syclcompat/math/math_complex_datatype.cpp, sycl/test-e2e/syclcompat/math/math_fast_length_test.cpp, sycl/test-e2e/syclcompat/math/math_vectorized_isgreater_test.cpp, sycl/test-e2e/syclcompat/math/math_vectorized_max_test.cpp, sycl/test-e2e/syclcompat/math/math_vectorized_min_test.cpp
This PR prepares SYCLcompat to receive multiple PRs containing updates to the helper headers.
It will substitute the previous opened PR as it grew in scope too much, as in case of issues it would be difficult to track and resolve effectively the problem.
Edit: Previous PR was https://github.com/intel/llvm/pull/11267
=> [SYCL][COMPAT] util header split in math and util headers

sycl/include/sycl/sub_group.hpp
This PR cleans up the API of the sub-group class by either removing functions that do not appear in the spec or marking them deprecated. The only exception is the set of load/store functions, which after some discussion with the spec team, it was suggested to leave them as is for now.
=> [SYCL] Clean up sub-group class API

.github/workflows/sycl-nightly.yml
E2E are ignored since we added "tests_selector: cts"
=> [CI] Fix sycl-nightly workflow

sycl/include/sycl/kernel.hpp, sycl/source/kernel.cpp, sycl/test-e2e/Basic/kernel_info.cpp
The get_info<> API returns a std::string which should be handled through detail::string, ABI-neutral way.
=> [SYCL] Fix kernel->get_info() in the pre-C++11 ABI scenario

sycl/source/detail/device_impl.cpp
- Removes printing to cout from check for ext_oneapi_graph
- Caused garbled output when running sycl-ls and LIT
=> [SYCL] Remove print to cout from aspect check

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/math.hpp, sycl/test-e2e/syclcompat/math/math_length_test.cpp
Adds a templated wrapper to sycl::length in syclcompat, that wraps over `sycl::vec<ValueT,N>` up to N == 4, and calculates the length with N > 4.
=> [SYCL][COMPAT] Adds sycl::length wrapper to SYCLcompat

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/math.hpp, sycl/test-e2e/syclcompat/common.hpp, sycl/test-e2e/syclcompat/math/math_complex.cpp, sycl/test-e2e/syclcompat/math/math_fixt.hpp, sycl/test-e2e/syclcompat/math/math_vectorized.cpp
This PR adds multiple binary and unary ops through callable structs:
- abs 
- abs_diff 
- add_sat
- rhadd 
- hadd 
- maximum
- minimum
- sub_sat
It also adds `vectorized_sum_abs_diff`.
To facilitate testing, it also incorporates a set of fixtures/helper classes to simplify future additions to math.hpp
=> [SYCL][COMPAT] Added Vectorized binary and unary ops

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/util.hpp, sycl/test-e2e/syclcompat/util/util_occupancy_calculation.cpp
Adds helpers to calculate the occupancy of the GPU
Testing currently only addresses API.
=> [SYCL][COMPAT] Added helpers for occupancy calculation in Intel GPUs

sycl-fusion/CMakeLists.txt, sycl-fusion/common/CMakeLists.txt, sycl-fusion/jit-compiler/CMakeLists.txt, sycl-fusion/jit-compiler/lib/fusion/FusionHelper.cpp, sycl-fusion/passes/CMakeLists.txt, sycl-fusion/passes/internalization/Internalization.cpp, sycl-fusion/passes/kernel-fusion/SYCLKernelFusion.cpp, sycl-fusion/passes/syclcp/SYCLCP.cpp, sycl-fusion/passes/target/TargetFusionInfo.cpp
Treat warnings as errors, and fix the last remaining warnings in the fusion library.
=> [SYCL][Fusion] Enable -Werror for fusion library

sycl/source/detail/context_impl.cpp, sycl/unittests/Extensions/CMakeLists.txt, sycl/unittests/Extensions/CompositeDevice.cpp
According to `sycl_ext_oneapi_composite_device` documentation a component device is considered to be a descendent from a composite device it belongs to.
This implies that context created for a composite device work with component devices as well.
In order to achieve this, this patch changes `context_impl` constructor to include all component devices into context's device list if a composite device was passed by user to the constructor.
=> [SYCL] Fix component device as descendent device handling

sycl-fusion/passes/target/TargetFusionInfo.cpp
Add attribute to argument only used in an assertion.
=> [SYCL][Fusion][NIT] Add `maybe_unused` attribute to argument

sycl/source/detail/graph_impl.hpp
- Fix `COPY_WITHOUT_ASSIGN` warning in `node_impl` by adding copy-assignment operator.
- Fix (false positive?) `REVERSE_INULL` in `graph_impl.hpp` by adding braces to make it explicit what is being dereferenced.
=> [SYCL][Graph] Fix coverity warnings in graph code

sycl-fusion/passes/kernel-fusion/SYCLKernelFusion.cpp
Silences a warning reported by GCC 12.
=> [SYCL][Fusion] Fix implicit narrowing conversion

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/device.hpp, sycl/include/syclcompat/launch.hpp, sycl/test-e2e/syclcompat/id_query/id_query_fixt.hpp, sycl/test-e2e/syclcompat/launch/launch.cpp, sycl/test-e2e/syclcompat/launch/launch_fixt.hpp
This PR is mostly cleanup:
- adds a free function to call to wrap queue wait and throw, which was in the documentation but not implemented.
- It reduces testing coupling by including the relevant headers.
- Adds a missing header in launch.cpp, which was detected when fixing the testing header includes.
- Fixes a lot of function definitions in the documentation which didn't match the actual definition in the library.
=> [SYCL][COMPAT] Added wait and throw free function. Minor fixes in documentation.

sycl/test-e2e/README.md, sycl/test-e2e/lit.cfg.py
I chose `gpu-intel-pvc-vg` instead of `gpu-intel-pvcvg` to match the device_arch [here](https://github.com/intel/llvm/blob/a0cdd9f741c70e7586d7638b88e7b750eb2d540c/sycl/doc/UsersManual.md?plain=1#L51).
=> [SYCL][E2E] Add gpu-intel-pvc-vg LIT param

llvm/include/llvm/IR/IntrinsicInst.h, llvm/lib/IR/IntrinsicInst.cpp, llvm/test/tools/sycl-post-link/spec-constants/SYCL-alloca.ll, llvm/tools/sycl-post-link/SpecConstants.cpp, sycl/include/sycl/detail/defines.hpp, sycl/include/sycl/ext/oneapi/experimental/alloca.hpp, sycl/include/sycl/multi_ptr.hpp, sycl/source/feature_test.hpp.in, sycl/test-e2e/PrivateAlloca/Inputs/private_alloca_test.hpp, sycl/test-e2e/PrivateAlloca/private_alloca_bool_size.cpp, sycl/test-e2e/PrivateAlloca/private_alloca_decorated.cpp, sycl/test-e2e/PrivateAlloca/private_alloca_host.cpp, sycl/test-e2e/PrivateAlloca/private_alloca_legacy.cpp, sycl/test-e2e/PrivateAlloca/private_alloca_multiple.cpp, sycl/test-e2e/PrivateAlloca/private_alloca_raw.cpp
After a1050551296b implementing CodeGen capabilities for `sycl_ext_oneapi_private_alloca`, this patch handles the generated intrinsic in `sycl-post-link` for targets with native specialization constants support.
Headers for the new extension are also added, as well as a feature test macro.
`multi_ptr` definitions in the SYCL headers are annotated with the `__sycl_detail__::sycl_type` to be detected by the frontend.
=> [SYCL][SCLA] Add basic `sycl_ext_oneapi_private_alloca` functionality

sycl/include/sycl/types.hpp, sycl/test/basic_tests/vectors/swizzle_aliases.cpp
Vector swizzles are currently missing the value_type and vector_t aliases, as should be inherited from vec. This commit adds these aliases.
=> [SYCL] Add missing aliases to swizzles

sycl/plugins/unified_runtime/CMakeLists.txt
This patch and its counterpart in oneapi-src/unified-runtime#1410 add CMake support for fetching an individual Unified Runtime adapter's source code from a different repo/tag combination using the new `fetch_adapter_source()` CMake function. Only the source is cloned, it is not added to the build directly.
Instead, the path to the adapter source is passed into Unified Runtime clone described by the `UNIFIED_RUNTIME_REPO` and `UNIFIED_RUNTIME_TAG` CMake variables. This clone is the source of truth for the Unified Runtime API and drives the build of the external adapter source.
Using `fetch_adapter_source()` is optional.
=> [UR] Support fetch adapter source individually

libclc/CMakeLists.txt
This mirrors a change made to upstream LLVM in https://github.com/llvm/llvm-project/pull/85634, but since we've made downstream changes we have to do the work in two places.
Some of this will cause merge conflicts when pulling down upstream LLVM but I don't know how we can avoid that.
Some of the other files changed in the upstream PR have been left alone
here since we'll soon pull those in anyway.
=> [libclc] Convert tabs to spaces in CMake

sycl/plugins/native_cpu/CMakeLists.txt
Updates git tag for the oneAPI Construction Kit.
=> [SYCL][NATIVECPU]Update OCK tag

sycl/test-e2e/UserDefinedReductions/user_defined_reductions.cpp
This patch enables user_defined_reductions.cpp for cuda and hip.
It's been verified that the test is now supported for cuda and hip now, this closes https://github.com/intel/llvm/issues/12613
=> [CUDA][HIP] Enable user_defined_reductions for cuda and hip.

clang/lib/Driver/Driver.cpp, clang/test/Driver/sycl-link-add-targets.cpp
When using the -fsycl-link-targets option, we inadvertently were triggering the additional device linking steps that are performed for -fsycl-link.  Prevent this from happening.  Also do a little cleanup of some code that is not needed.
=> [Driver][SYCL] Do not perform link step with -fsycl-link-targets

sycl/include/CL/__spirv/spirv_ops.hpp, sycl/test-e2e/Basic/built-ins.cpp, sycl/test-e2e/DeviceLib/built-ins/printf.cpp, sycl/test-e2e/ESIMD/printf.cpp, sycl/test-e2e/Printf/float.cpp, sycl/test/extensions/experimental-printf.cpp
Currently, the implementation of printf uses a variadic implementation by default. This proved to be problematic as the implementation would promote float arguments to doubles, implicitly requring fp64. As a result of this, an alternative implementation was introduced, but was made enableable using a __SYCL_USE_NON_VARIADIC_SPIRV_OCL_PRINTF__ directive to avoid problems with targets that did not support it. We expect most relevant backends to support it now, so we flip the default.
=> [SYCL] Flip default printf implementation

.github/CODEOWNERS
Merged PR https://github.com/intel/llvm/pull/12837 split `CommandGraph.cpp` into a directory of files, however this was not reflected in the CODEOWNERS file.
=> [SYCL][CODEOWNERS][Graph] Update Graph Unittest codeowners

mlir/include/mlir/Dialect/Arith/IR/ArithBase.td, mlir/include/mlir/Dialect/Arith/IR/ArithOps.td, mlir/include/mlir/Dialect/Arith/IR/ArithOpsInterfaces.td, mlir/lib/Conversion/ArithToAMDGPU/ArithToAMDGPU.cpp, mlir/lib/Conversion/ArithToLLVM/ArithToLLVM.cpp, mlir/lib/Conversion/ArithToSPIRV/ArithToSPIRV.cpp, mlir/lib/Dialect/Arith/Transforms/ExpandOps.cpp, mlir/test/Dialect/Arith/ops.mlir
Add rounding mode attributes to `arith`. Use it in `arith.truncf` for now.
=> [MLIR][Arith] Add rounding mode attribute to `arith.truncf`

.github/workflows/sycl-linux-run-tests.yml
Unfortunately, our E2E tests use custom LIT format so I wasn't able to make `llvm-lit` generate the results into a JSON file. That meant that I have to redirect the entire output into a log file and Github Actions won't be able to show intermediate progress until `llvm-lit` finishes execution.
Another thing worth mentioning is that these summaries aren't "searchable" via Github's search queries (unlike comments), but I think it's still a usability improvement because it would allow to see all the failures on a single page.
=> [CI] Create Github Job Summary for failing E2E tasks

clang/include/clang/Basic/LangOptions.def, clang/include/clang/Basic/LangOptions.h, clang/include/clang/Driver/Options.td, clang/lib/Driver/Driver.cpp, clang/lib/Driver/ToolChains/Clang.cpp, clang/lib/Frontend/InitPreprocessor.cpp, clang/lib/Sema/SemaSYCL.cpp, clang/test/CodeGenSYCL/integration_header_ppmacros.cpp, clang/test/Driver/sycl-offload-intelfpga.cpp, clang/test/Driver/sycl-offload.c, clang/test/Preprocessor/predefined-macros.c, sycl/doc/design/ParallelForRangeRounding.md, sycl/include/sycl/handler.hpp, sycl/test-e2e/Basic/parallel_for_range_roundup.cpp
Adds a new preference for range rounding, force, such that if the compile flag is used, only the range rounded parallel_for kernel will be generated. This can make binaries smaller as there is no duplication of SYCL range kernels across range rounded and unrounded versions.
I have also added the flag: -fsycl-range-rounding, which can have values: on, force or disable. This flag aims to supercede the fsycl-disable-range-rounding flag.
I have also added to existing tests to check for the functionality of the new flag and refactored the range rounding sycl-e2e test. Also added brief description of flag's behaviour in `doc`
=> [SYCL] Add force range rounding option and introduce new compiler flag

sycl/test-e2e/TaskSequence/concurrent-loops.cpp, sycl/test-e2e/TaskSequence/in-order-async-get.cpp, sycl/test-e2e/TaskSequence/mult-and-add.cpp, sycl/test-e2e/TaskSequence/multi-kernel-task-function-reuse.cpp, sycl/test-e2e/TaskSequence/producer-consumer.cpp, sycl/test-e2e/TaskSequence/struct-array-args-and-return.cpp
=> [SYCL][E2E] Disable TaskSequence/* tests on Linux

sycl/doc/design/CommandGraph.md, sycl/plugins/unified_runtime/CMakeLists.txt
Tests UR PR https://github.com/oneapi-src/unified-runtime/pull/1447 that only reports support for UR command-buffers on ROCm 5.5.1 and later to work around HIP driver bugs related to HIP-Graph in earlier version.
This requirement is also explicitly mentioned in the design doc.
=> [SYCL][Graph][HIP] Set minimum ROCm version for graphs

devops/cts_exclude_filter
also turn off h_item due to fail - https://github.com/intel/llvm/issues/12926
=> [CI] Reduce cts_exclude_filter

libclc/utils/libclc-remangler/LibclcRemangler.cpp
I've bunched these together as I don't think any are controversial and it seems a waste of time to review each independently.
-----
[libclc] Update deprecated method use in remangler
llvm::StringRef::startswith -> llvm::StringRef::starts_with
-----
[libclc] Fix up improper use of ExitOnError
ExitOnError takes a llvm::Expected, but we were passing it the result of
llvm::parseIR - std::unique_ptr<llvm::Module> - which, even when null, is
not an error condition. Thus invalid IR input was silently being
accepted until it would segfault on accessing the module.
-----
[libclc] Open remangler file system at PWD, not root
I don't think there's any reason to open it at root. Opening it at the
current working directory is more intuitive for developers using
relative paths for input/output files. …
=> [libclc] Several little QOL improvements to libclc-remangler

libclc/CMakeLists.txt, libclc/generic/include/clc/math/fract.inc, libclc/generic/include/clc/math/frexp.inc, libclc/generic/include/clc/math/modf.inc, libclc/generic/include/clc/math/remquo.h, libclc/generic/include/clc/math/sincos.inc, libclc/generic/include/spirv/spirv_builtins.h, libclc/generic/lib/math/fract.inc, libclc/generic/lib/math/frexp.cl, libclc/generic/lib/math/modf.inc, libclc/generic/lib/math/remquo.cl, libclc/generic/lib/math/remquo.inc, libclc/generic/lib/math/sincos.inc, libclc/generic/libspirv/math/fract.inc, libclc/generic/libspirv/math/frexp.cl, libclc/generic/libspirv/math/lgamma_r.cl, libclc/generic/libspirv/math/lgamma_r.inc, libclc/generic/libspirv/math/modf.inc, libclc/generic/libspirv/math/remquo.cl, libclc/generic/libspirv/math/remquo.inc, libclc/generic/libspirv/math/sincos.inc, sycl/test-e2e/USM/math.cpp
The generic implementations of the math builtins which take pointer arguments were using unqualified address spaces. This could either resolve to the generic address space or the private address space, depending on whether the target supports the generic address space or not.
The newer unified OpenCL C specification is clearer in mandating that all targets must provide overloads on the explicitly qualified 'private' address space, as well as optionally defining ones on the (unqualified) generic address space. This meant that most of these math builtins were lacking one overload: either the private or generic one, depending on which target was compiling the builtins.
One notable exception here is NVIDIA, which maps the private and generic
address spaces to the same target address space. …
=> [SYCL][libclc] Add generic addrspace overloads of math builtins

sycl/test-e2e/SpecConstants/2020/image_selection.cpp
Using `,` in requires is equivalent to `&&`, and a device can't support simultaneously `opencl` and `level-zero`, so this test was always skipped. This patch corrects this by requiring either `opencl` or `level-zero`, but not both simultaneously.
=> [SYCL][E2E] Stop skipping image_selection.cpp test.

.github/workflows/sycl-linux-build.yml, .github/workflows/sycl-windows-build.yml, sycl/cmake/modules/AddSYCLUnitTest.cmake, sycl/unittests/xpti_trace/QueueIDCheck.cpp
This PR enables testing unittests in CI.
=> [CI] Enable check-sycl-unittests in CI

sycl/test-e2e/Plugin/level_zero_ext_intel_cslice.cpp, sycl/test-e2e/Plugin/level_zero_ext_intel_queue_index.cpp, sycl/test-e2e/Plugin/level_zero_sub_sub_device.cpp
ZEX_NUMBER_OF_CCS not yet working in FLAT mode, the new default on PVC. Shoring up the tests in the interim.
=> [SYCL] ensuring ZEX_NUMBER_OF_CCS is only used on COMPOSITE hierarchy mode

clang/include/clang/Sema/Sema.h
In ac74d9ec0f73898713dd6e0d33f148c13a51875d declarations in Sema.h were regrouped by file. This change moves the SYCL code into the correct section.
=> [clang][NFC] Regroup Sema SYCL declarations

mlir/include/mlir/Conversion/ArithCommon/AttrToLLVMConverter.h, mlir/include/mlir/Dialect/LLVMIR/LLVMEnums.td, mlir/include/mlir/Dialect/LLVMIR/LLVMInterfaces.td, mlir/include/mlir/Dialect/LLVMIR/LLVMIntrinsicOps.td, mlir/include/mlir/Target/LLVMIR/ModuleImport.h, mlir/include/mlir/Target/LLVMIR/ModuleTranslation.h, mlir/lib/Conversion/ArithCommon/AttrToLLVMConverter.cpp, mlir/lib/Conversion/ArithToLLVM/ArithToLLVM.cpp, mlir/lib/Target/LLVMIR/ModuleImport.cpp, mlir/lib/Target/LLVMIR/ModuleTranslation.cpp, mlir/test/Conversion/ArithToLLVM/arith-to-llvm.mlir, mlir/test/Dialect/LLVMIR/roundtrip.mlir, mlir/test/Target/LLVMIR/Import/intrinsic.ll, mlir/test/Target/LLVMIR/llvmir-intrinsics.mlir
Add operation mapping to the LLVM
`llvm.experimental.constrained.fptrunc.*` intrinsic.
The new operation implements the new
`LLVM::ExceptionBehaviorOpInterface` and
`LLVM::RoundingModeOpInterface` interfaces.
Add translation to LLVM IR and conversion from `arith.truncf` receiving the optional `rounding_mode` attribute.
=> [MLIR][LLVM] Add `llvm.experimental.constrained.fptrunc` operation

mlir/lib/Conversion/GENToLLVM/CMakeLists.txt
`MLIRGENToLLVM` is missing symbols defined in
`MLIRLLVMCommonConversion`. Add library to link list and clean this list.
=> [GEN] Fix `MLIRGENToLLVM` linker error

llvm/lib/SYCLLowerIR/ESIMD/LowerESIMD.cpp
Even though the fresh ESIMD headers do not use 'lsc_load_stateless()` intrinsic, the static libraries compiled by an old compiler may still have the calls of 'lsc_load_stateless' in them.
The patch https://github.com/intel/llvm/pull/12935 caused regressions in some MKL tests.
This patch here restores the lowering of lsc_load_stateless for sycl-post-link backward compatibility.
=> [ESIMD] Restore the lowering of lsc_load_stateless in sycl-post-link

sycl/include/sycl/detail/reduction_forward.hpp, sycl/include/sycl/reduction.hpp, sycl/test-e2e/AddressCast/dynamic_address_cast.cpp, sycl/test-e2e/AddressCast/static_address_cast.cpp
Otherwise, `<sycl/detail/core.hpp>` isn't enough to invoke non-reduction `parallel_for`.
=> [SYCL] Move AreAllButLastReductions to reduction_forward.hpp

mlir/include/mlir/Conversion/ArithCommon/AttrToLLVMConverter.h, mlir/lib/Conversion/ArithCommon/AttrToLLVMConverter.cpp, mlir/lib/Conversion/ArithToLLVM/ArithToLLVM.cpp
Errors:
- Fixed build errors with some Clang versions due to mismatch in template parameters number. Changed compile time checks to enforce the target operation implements `LLVM::ExceptionBehaviorOpInterface` and drop `arith::ArithRoundingModeInterface` check for source operation.
Warnings:
- Added `llvm_unreachable` after switch statement in `convertArithRoundingModeToLLVM`.
=> [MLIR][Arith] Fix Arith to LLVM build errors and warnings

sycl/test-e2e/Plugin/interop-level-zero-image.cpp
6246e20e40e10 wasn't enough, as the test still fails on Arc GPUs. Mark this as entirely unsupported until someone can properly fix the root cause as per https://github.com/intel/llvm/issues/13090
=> [test-e2e] Disable broken test part 2

sycl/tools/sycl-trace/generate_ze_pretty_printers.py
This prevents a warning being shown on some versions of python.
=> [SYCL] Use raw string for python regex. NFC

clang/include/clang/Basic/DiagnosticDriverKinds.td, clang/lib/Driver/Driver.cpp, clang/test/Driver/sycl-offload-amdgcn.cpp
If multiple SYCL targets are provided, asking users to specify `-Xsycl-target-backend --offload-arch` will fail for another reason, which isn't a nice user experience.
Instead, we can conditionally tweak the error message so it shows the most concise invocation required for it to work every time. This preserves the old form when only one SYCL target is used - mostly for consistency - but provides the more verbose form when it's required.
=> [SYCL][AMDGCN] Provide a more helpful --offload-arch error

sycl/doc/extensions/supported/sycl_ext_intel_esimd/sycl_ext_intel_esimd.md, sycl/doc/extensions/supported/sycl_ext_intel_esimd/sycl_ext_intel_esimd_functions.md, sycl/include/sycl/ext/intel/esimd/memory.hpp
The adds a new file `sycl/doc/extensions/supported/sycl_ext_intel_esimd/sycl_ext_intel_esimd_functions.md`
describing the new memory API including:
* block_load(), slm_block_load()
* block_store(), slm_block_store()
* gather(), slm_gather()
* scatter(), slm_scatter()
* atomic_update(), slm_atomic_update()
* prefetch()
Only the block_load/store functions are described in more details at this moment. They include the functions restrictions and hardware requirements/implications from using various features (mask, cache-hints, sizes, etc).
=> [ESIMD][NFC][DOC] Describe the new memory API accepting properties

sycl/plugins/unified_runtime/CMakeLists.txt
Bumps commit to UR PR https://github.com/oneapi-src/unified-runtime/pull/1461
=> [SYCL][Graph][L0] Test Coverity fix

sycl/include/sycl/ext/oneapi/memcpy2d.hpp, sycl/include/sycl/handler.hpp, sycl/include/sycl/queue.hpp, sycl/include/sycl/sycl.hpp, sycl/include/sycl/usm.hpp, sycl/source/detail/memory_manager.cpp, sycl/source/detail/usm/usm_impl.cpp, sycl/source/handler.cpp, sycl/test-e2e/USM/memops2d/memops2d_utils.hpp
`handler.hpp`/`queue.hpp` now contain declarations of the methods only,
definitions have been moved into a dedicated file. That way these
headers (and subsequently `sycl/detail/core.hpp`) don't need to depend on
`sycl/usm/*.hpp` headers.
=> [SYCL] Move ext_oneapi_memcpy2d impl into dedicated header

sycl/test-e2e/Annotated_arg_ptr/annotated_arg.cpp, sycl/test-e2e/Annotated_arg_ptr/annotated_ptr.cpp, sycl/test-e2e/Annotated_arg_ptr/common.hpp
It didn't bring any readability benefits.
=> [NFC][SYCL][E2E] Drop Annotated_arg_ptr/common.hpp

sycl/doc/extensions/supported/sycl_ext_intel_esimd/sycl_ext_intel_esimd_functions.md, sycl/include/sycl/ext/intel/esimd/memory.hpp, sycl/test/esimd/slm_gather_scatter.cpp
It also adds a deprecated warning for l3_flush_instructions, l3_flush_texture_data, l3_flush_constant_data, l3_flush_rw_data enums as they in fact refer to L2 cache, not L3. Corresponding l2_* enums were added.
=> [ESIMD][NFC][DOC] Add fence to the ESIMD SPEC functions

sycl/test-e2e/SpecConstants/2020/image_selection.cpp
`image_selection.cpp` test was skipped for level zero backend because the proper spelling is `level_zero` (underscore) rather than `level-zero` (dash). This patch corrects such an error.
=> [SYCL][E2E] Enable image_selection.cpp for level zero.

sycl/include/sycl/ext/oneapi/experimental/builtins.hpp
Old builtins implementation is soon to be dropped during ABI breaking window. Ensure that this extension implementation doesn't rely on it.
=> [NFCI][SYCL] Don't use builtins' internals in ext_oneapi_native_math impl

sycl/doc/extensions/experimental/sycl_ext_oneapi_graph.asciidoc
Merged PR https://github.com/intel/llvm/pull/11324 introduced the ability to profile an executable graph submission. However, the specification limitation section was not updated to reflect this, which is addressed in this PR.
=> [SYCL][Graph][Doc] Remove outdated limitation from spec

sycl/include/sycl/ext/intel/esimd/memory.hpp
We shouldn't assert, just redirect to LSC. I wasn't able to add a test because it seems we always hit similar limitations in the LSC variant.
=> [SYCL][ESIMD] Use LSC for unsupported surface index block stores

sycl/test-e2e/SpecConstants/2020/image_selection.cpp
`SYCL_PI_TRACE` log in Windows have some differences compared to Linux:
- Hexadecimal values don't start with `0x`, so this patch makes it optional.
- Hexadecimal values are printed with capital letters (A-F), so this patch accounts for that.
- Zero value is printed like `0000000000000000`, rather than simply `0` like in Linux. This patch accounts for that.
=> [SYCL][E2E] Update expected output to work with Windows

clang/include/clang/Driver/Options.td, clang/test/Driver/sycl-add-default-spec-consts-image.cpp
The -fsycl-add-default-spec-consts-image was added to only be used from the clang and clang++ command lines.  Update this to also allow for clang-cl usage, better matching the other fsycl based options.
=> [Driver][SYCL] Update visibility of option to allow for clang-cl usage

sycl/source/detail/graph_impl.cpp, sycl/source/detail/kernel_bundle_impl.hpp, sycl/source/detail/kernel_impl.cpp, sycl/source/detail/kernel_impl.hpp, sycl/source/detail/scheduler/commands.cpp, sycl/test-e2e/KernelAndProgram/kernel-bundle-find-run.cpp
The `kernel_impl` has been storing a `program_impl` pointer.  But none of the users of the `kernel_impl` need that, they just need the `PIProgram` .  Conversely, some of the callers constructing `kernel_impl` don't have a `program_impl` ptr and so we were using nullptr, which leads to crashes in some simple use cases.   
Replacing the `program_impl` ptr with a `PIProgram` member var instead and ensuring that all callers provide one, with the least amount of change to the `kernel_impl` interface. Simple test added as well - it crashes without this PR.
=> [SYCL] No nullptr program_impl

libclc/generic/include/clc/shared/vload.h, libclc/generic/include/clc/shared/vstore.h, libclc/generic/lib/shared/vload.cl, libclc/generic/lib/shared/vload_half.inc, libclc/generic/lib/shared/vstore.cl, libclc/generic/lib/shared/vstore_half.inc, libclc/generic/libspirv/shared/vload.cl, libclc/generic/libspirv/shared/vstore.cl, libclc/generic/libspirv/shared/vstore_half.inc
These definitions and declarations were missing, which would be problematic for a target which supports the generic address space where that address space is uniquely mangled. As with the maths builtins, the NVIDIA target wouldn't see this problem as the 'generic' address space is mangled identically to the 'private' one, so we were serendipitously providing the builtins through these.
I couldn't seem to make SYCL actually generate these builtins, but there is a path from SPIR-V to them (through the OpenCL SPIR-V environment), so providing them is prudent irregardless. In the absence of tests I manually verified that there are now as many 'AS0' overloads of these builtins as there 'AS5'/'AS1'/etc overloads.
=> [SYCL][libclc] Add generic addrspace overloads of vload/vstore builtins

clang/include/clang/Basic/Attr.td, clang/lib/Sema/SemaDeclAttr.cpp, clang/test/SemaSYCL/intel-fpga-local.cpp
This patch uses MutualExclusions tablegen support to allow us to remove a custom diagnostic checking codes with FPGA attributes: [[intel:fpga_register]] and [[intel::fpga_memory]].
=> [SYCL][FPGA] Allow tablegen handle mutually exclusive decl attrs (SYCLIntelRegister and SYCLIntelMemory)

sycl/test-e2e/ESIMD/lsc/lsc_usm_atomic_cachehint.cpp
All it's doing is setting doubleGRF, just do that using the first-class API.
Manually tested this on Win.
=> [SYCL][ESIMD][E2E] Remove setenv call from lsc_usm_atomic_cachehint.cpp

sycl/test-e2e/ESIMD/fp_call_from_func.cpp
Tested manually on Win/Lin with many runs, doesn't hang anymore.
Closes: https://github.com/intel/llvm/issues/8815
=> [SYCL][ESIMD][E2E] Re-enable fp_call_from_func.cpp

.github/workflows/sycl-aws.yml, .github/workflows/sycl-containers.yaml, .github/workflows/sycl-detect-changes.yml, .github/workflows/sycl-docs.yml, .github/workflows/sycl-linux-build.yml, .github/workflows/sycl-linux-matrix-e2e-on-nightly.yml, .github/workflows/sycl-linux-precommit-aws.yml, .github/workflows/sycl-linux-precommit.yml, .github/workflows/sycl-linux-run-tests.yml, .github/workflows/sycl-macos-build-and-test.yml, .github/workflows/sycl-nightly.yml, .github/workflows/sycl-post-commit.yml, .github/workflows/sycl-stale-issues.yml, .github/workflows/sycl-sync-main.yml, .github/workflows/sycl-update-gpu-driver.yml, .github/workflows/sycl-windows-build.yml, .github/workflows/sycl-windows-run-tests.yml
per OSSF (https://securityscorecards.dev/viewer/?uri=github.com/intel/llvm) all workflows should have default top level permission set. Which we set to below as per recommendation
permissions:
contents: read
then within actual jobs, when needed, we added additional privileges. 
These changes were generated by the recommended OSSF tool 
This PR changes those workflows created/owned by intel/llvm repo. Will do seperate PR for issues found in llvm/llvm-project inherited workflows.
=> [CI][OSSF] Add default permissions to work flows

sycl/source/builtins/relational_functions.cpp
Previously we were hard-coding an -O2 optimization level for the 'signbit' builtin for all versions of GCC.
Despite this workaround, I found locally that I was unable to build with GCC versions 12.2, 12.3, and 13.2. Reducing the optimization level to -O1 allowed me to progress. This seems to follow the bug report already linked, which had test cases at -O2 which were also failing.
With this in mind, we can also restrict the GCC versions we apply the workaround to, so that more modern compilers should "just work" without us having to do anything. That should save someone having to investigate a performance report a year or so down the line...
=> [SYCL] Adjust GCC workaround and its scope

.github/workflows/sycl-docs.yml, .github/workflows/sycl-linux-build.yml, .github/workflows/sycl-linux-matrix-e2e-on-nightly.yml, .github/workflows/sycl-linux-precommit.yml, .github/workflows/sycl-macos-build-and-test.yml, .github/workflows/sycl-nightly.yml, .github/workflows/sycl-post-commit.yml, .github/workflows/sycl-stale-issues.yml, .github/workflows/sycl-sync-main.yml, .github/workflows/sycl-update-gpu-driver.yml, .github/workflows/sycl-windows-build.yml, .github/workflows/sycl-windows-precommit.yml, .github/workflows/sycl-windows-run-tests.yml
the OSSF tool sucks and don't use its recommended default settings. It suggested permissions content:read as default, but that broke most of our workflows, instead use the GitHub recommended
permissions: read-all
=> [CI] Fix bad OSSF recomendations 

clang/include/clang/Basic/DiagnosticSemaKinds.td, clang/lib/Sema/SemaChecking.cpp, clang/test/SemaSYCL/builtin-alloca-errors-device.cpp
Replace check for cv-unqualified object types with a check for cv-unqualified trivial types to be in line with the `sycl_ext_oneapi_private_alloca` extension specification:
> `ElementType` must be a cv-unqualified trivial type
=> [SYCL][SCLA] Check allocated types are trivial

sycl/source/detail/program_manager/program_manager.cpp
After https://github.com/intel/llvm/commit/370aa2a0171199d07f70096fb396810137f26e50 
grf_size control values changed to 128 and 256 values instead of values like "small", "large".
> 2) Adds two new kernel properties
> `sycl::ext::intel::experimental::grf_size` and
> `sycl::ext::intel::experimental::grf_size_automatic`, as per the spec.
> `grf_size` adds the `sycl-grf-size` metadata with a value of the
> template parameter **(`128` or `256`)**. `grf_size_automatic` adds the
> `sycl-grf-size` metadata with a value of `0`.
and user is expected to specify value like this:
syclex::properties kernel_properties{intelex::grf_size<128>};
syclex::properties kernel_properties{intelex::grf_size<256>};
=> [SYCL][NFC] Rename IsLargeGRF to Is256GRF

.github/workflows/sycl-update-gpu-driver.yml, devops/dependencies.json, devops/scripts/update_drivers.py
This is the 1st PR in prepare of enabling dev IGC test for some of the
SYCL tests.
Ref: https://github.com/intel/llvm/pull/11552
Tested https://github.com/intel/llvm/actions/runs/8461815185/job/23182202059
=> [CI] Add IGC dev as new dependency

sycl/doc/EnvironmentVariables.md
Just try to fix a broken link found when reading https://intel.github.io/llvm-docs/EnvironmentVariables.html
=> [SYCL][Doc] Correct range-rounding link

sycl/doc/extensions/experimental/sycl_ext_oneapi_graph.asciidoc, sycl/source/queue.cpp, sycl/test-e2e/Graph/RecordReplay/barrier_multi_queue.cpp, sycl/test-e2e/InorderQueue/in_order_ext_oneapi_submit_barrier.cpp, sycl/unittests/Extensions/CommandGraph/Barrier.cpp
Fix for https://github.com/intel/llvm/issues/13066
The special case for using barriers on an in-order queue is that the last event/node submitted to the queue is used as an event for the barrier to depend on.
Looking at the last command submitted to the queue isn't correct for a graph, because previous commands
submitted to a graph could have been added explicitly or from recording another queue. Therefore, there is not guaranteed that the last command submitted by the in-order queue is correct dependency for the barrier node in the graph.
=> [SYCL][Graph] in-order queue barrier fix

sycl/plugins/unified_runtime/CMakeLists.txt
https://github.com/oneapi-src/unified-runtime/pull/1460
=> [UR] Remove unused function prototypes

sycl/test-e2e/Assert/assert_in_kernels_win.cpp, sycl/test-e2e/Assert/assert_in_multiple_tus_one_ndebug_win.cpp, sycl/test-e2e/Assert/assert_in_multiple_tus_win.cpp, sycl/test-e2e/Assert/assert_in_one_kernel_win.cpp, sycl/test-e2e/Assert/assert_in_simultaneous_kernels_win.cpp
=> [SYCL][E2E] Fix checks for assertion tests on Windows

sycl/source/detail/kernel_compiler/kernel_compiler_opencl.cpp
problem discovered when using -fsanitize=address on the KernelCompiler tests
=> [SYCL] fix for kernel_compiler

sycl/test-e2e/Complex/sycl_complex_include_order.cpp
Author: Marcos Maronas <marcos.maronas@intel.com>
=> [SYCL][E2E] Pass -std=c++17 to the compiler provided via -fsycl-host-compiler

sycl/include/sycl/sycl.hpp, sycl/test-e2e/ESIMD/api/functional/value.hpp, sycl/test-e2e/ESIMD/kmeans/kmeans.cpp, sycl/test/basic_tests/fp-accuracy.cpp, sycl/test/basic_tests/no_math_in_global_ns.cpp, sycl/test/check_device_code/fp-accuracy.cpp
Any user code relying on those included implicitly is wrong and we don't consider it a breaking change, just a bug fix.
Reverts https://github.com/intel/llvm/pull/11326.
We agreed that this isn't an ABI break as the code relying on this wasn't standard conforming. However, ABI break is next week, so I'll be merging it then. Meanwhile, adding `abi-break` label to ease documentation update later.
=> [SYCL] Don't include <cmath>/<complex> by default

sycl/include/sycl/detail/assert_happened.hpp, sycl/include/sycl/detail/defines_elementary.hpp, sycl/include/sycl/queue.hpp
Try to reland PR: https://github.com/intel/llvm/pull/5698
Author: Sergei Kanaev, s-kanaev
=> [SYCL] Declare __devicelib_assert_read only when fallback assert is enabled

sycl/test-e2e/bindless_images/vulkan_interop/mipmaps.cpp
* fix missed scope for `equal_vec` in Vulkan interop `mipmaps.cpp` test.
=> [SYCL][Bindless][E2E] fix missing scope when using equal_vec function

sycl/source/detail/graph_impl.cpp
- Fix uninitialized pointer values leading to trying to call piExtCommandBufferReleaseCommand on backends which don't support update, which may return as an unsupported feature. Initializing pointers to 0 prevents this call from happening.
=> [SYCL][Graph] Fix potential issue with command buffer commands

sycl/include/sycl/handler.hpp, sycl/test-e2e/Assert/assert_in_multiple_tus.hpp, sycl/test-e2e/DiscardEvents/discard_events_accessors.cpp, sycl/test-e2e/ESIMD/bfn.cpp, sycl/test-e2e/ESIMD/ext_math.cpp, sycl/test-e2e/ESIMD/local_accessor_gather_scatter.cpp, sycl/test-e2e/ESIMD/local_accessor_gather_scatter_rgba.cpp, sycl/test-e2e/ESIMD/lsc/atomic_smoke.cpp, sycl/test-e2e/ESIMD/lsc/lsc_local_accessor_gather_scatter.cpp, sycl/test-e2e/ESIMD/unified_memory_api/Inputs/atomic_update.hpp, sycl/test-e2e/KernelFusion/abort_fusion.cpp, sycl/test-e2e/KernelFusion/abort_internalization.cpp, sycl/test-e2e/KernelFusion/diamond_shape_local.cpp, sycl/test-e2e/KernelFusion/existing_local_accessor.cpp, sycl/test-e2e/KernelFusion/internalize_array_wrapper_local.cpp, sycl/test-e2e/KernelFusion/local_internalization.cpp, sycl/test-e2e/KernelFusion/non_unit_local_size.cpp, sycl/test-e2e/KernelFusion/struct_with_array.cpp, sycl/test-e2e/Tracing/code_location_queue_parallel_for.cpp, sycl/test-e2e/XPTI/buffer/accessors.cpp, sycl/test-e2e/XPTI/kernel/basic.cpp, sycl/test/check_device_code/native_cpu/native_cpu_builtins.cpp, sycl/unittests/Extensions/CommandGraph/Update.cpp
Enables the change from https://github.com/intel/llvm/pull/11067 by default.
=> [ABI-Break][SYCL] Restrict nd_range parallel_for to nd_item

sycl/include/sycl/sycl.hpp
Not used, was faiting for an ABI breaking window to be removed.
=> [ABI-Break][SYCL] Remove `sycl::make_unique_ptr`

.github/workflows/sycl-containers.yaml
After https://github.com/intel/llvm/pull/13173 , we are not able to push container images.
See https://github.com/intel/llvm/actions/runs/8485593107/job/23250649681
```
------
> pushing ghcr.io/intel/llvm/ubuntu2204_base:2f03ef85fee5e867c8250d535f561f2e52e5260c with docker:
------
ERROR: denied: installation not allowed to Write organization package
Error: buildx failed with: ERROR: denied: installation not allowed to Write organization package
```
We need to update the docker images, so need to write packages.
Push permission tested through non PR workflow run here: https://github.com/intel/llvm/actions/runs/8516878870
=> [CI][OSSF] Allow package write in sycl-container build

sycl/test-e2e/Matrix/XMX8/joint_matrix_opt_kernel_feature.cpp, sycl/test-e2e/Matrix/joint_matrix_opt_kernel_feature.cpp, sycl/test-e2e/Matrix/joint_matrix_opt_kernel_feature_unsupported_hw.cpp
This macro and its usages were removed here: https://github.com/intel/llvm/pull/11813
=> [SYCL][NFC] Remove legacy SYCL_EXT_ONEAPI_MATRIX_VERSION usages

clang/lib/Driver/Driver.cpp, clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/sycl-int-footer.cpp
To try and alleviate improper dependency information generated when -fsycl is enabled, an additionl dependency compilation step was created. This additional step, while creating the needed information causes issues when we use -save-temps.  These issues being assosiated with bad dependencies for the integration header.
Clean up these pathways to be more in line with a typical 'device' and 'host' only compilation, relying on the dependency information from the device side.
Additional changes can be made when we can clean up the dependency generation from the host compilation step when we are building the temporary file.  Removing the append file step would clear this up as well.
=> [Driver][SYCL] Cleanup redundant dependency steps

sycl/include/sycl/detail/builtins/relational_functions.inc
To indicate that they are still part of the specification and cannot be removed from the implementation.
=> [NFC][SYCL] Use __SYCL2020_DEPRECATED macro for any/all builtins

sycl/test-e2e/Matrix/joint_matrix_apply_two_matrices_impl.hpp
https://github.com/intel/llvm/commit/7fb3b20688c64761e73a0797a12c6df5c1f6da0a replaces `#include <sycl/sycl.hpp>` to `#include <sycl/detail/core.hpp>` in common.hpp. core.hpp doesn't include usm.hpp, used in the header file modified by this patch.
=> [SYCL] Fix compilation of joint_matrix_apply_two_matrices.cpp

sycl/include/sycl/multi_ptr.hpp, sycl/test-e2e/Basic/multi_ptr_null_relational_operators.cpp
`multi_ptr` relational operators taking a `std::nullptr_t` are written in a way that assume it is the lowest possible value
(example https://github.com/intel/llvm/blob/sycl/sycl/include/sycl/multi_ptr.hpp#L1575). However the C++ specs states there is no ordering requirement (https://eel.is/c++draft/expr.rel#4.3).
In practice, this is causing issues in the CUDA and AMDGPU backend. For instance, in CUDA the nullptr in the local address space is a non `0` value and `0` in this address space is the root of the allocated local memory.
=> [SYCL] Fix multi_ptr relational operators customised for nullptr.

sycl/test-e2e/README.md, sycl/test-e2e/lit.cfg.py, sycl/test-e2e/lit.site.cfg.py.in
Also provide a more helpful error message when it is not provided.
This should make it more intuitive and easier to test multiple different architectures without having to reconfigure CMake.
=> [SYCL][E2E] Allow setting amd_arch through a parameter

sycl/test-e2e/Matrix/XMX8/element_wise_all_ops_int8.cpp, sycl/test-e2e/Matrix/XMX8/element_wise_all_ops_int8_packed.cpp, sycl/test-e2e/Matrix/XMX8/element_wise_all_sizes.cpp, sycl/test-e2e/Matrix/XMX8/element_wise_all_sizes_no_split.cpp
These tests should pass in the current environment on both A770 and A750.
Closes #11538.
Closes #11912.
=> [SYCL][Matrix] Enable tests on DG2 GPU

sycl/test-e2e/Basic/multi_ptr_null_relational_operators.cpp
- change `sycl::id<1>` to `sycl::nd_item<1>` in a parallel_for with `sycl::nd_range`, which caused a build error in HIP backend.
=> Fix a build failure shown in HIP backend in multi_ptr_null_relational_operators.cpp test

llvm/lib/SYCLLowerIR/ESIMD/LowerESIMD.cpp, llvm/test/SYCLLowerIR/esimd_lower_nbarriers.ll, sycl/include/sycl/ext/intel/experimental/esimd/detail/memory_intrin.hpp, sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp, sycl/test/esimd/nbarriers.cpp
Need a new driver supporting the new intrinsic.
=> [SYCL][ESIMD] Use old intrinsic for named_barrier_signal for now 

sycl/doc/design/spirv-extensions/SPV_INTEL_bindless_images.asciidoc
Create a new extension to enable SPIR-V to support handle conversion to image and sampler types for the bindless images extension.
=> [SYCL][Bindless][Doc] Introduce SPIR-V spec for enabling bindless images on Intel devices

sycl/include/sycl/detail/builtins/math_functions.inc, sycl/test-e2e/Basic/sycl_2020_images/common.hpp, sycl/test/warnings/sycl_2020_deprecations.cpp
It's not provided by the SYCL 2020 specification and has been marked as deprecated some time ago.
=> [SYCL] Remove `sycl::abs` FP overload

sycl/test-e2e/Regression/nop_event_profiling.cpp
Test is failing on devices without fp64 aspect.
Test doesn't actually need to use double type.
=> [SYCL][E2E] Don't use fp64 aspect in the test that doesn't need it

.github/workflows/sycl-containers.yaml
Address review comments from https://github.com/intel/llvm/pull/13272#discussion_r1552471814
=> [CI] Refactor sycl-containers to use matrix

sycl/include/sycl/sub_group.hpp
Add an alternative in the deprecation message for barrier() method on a sub-group. This should help clients move closer to conformant code.
=> [SYCL] Add alternative to deprecated barrier() function for sub-group

.github/workflows/sycl-containers.yaml, devops/containers/ubuntu2204_intel_drivers.Dockerfile, devops/dependencies.json, devops/scripts/install_drivers.sh
- Add flag in install_driver to install igc dev driver
- Add options to build devigc containers
Ref: https://github.com/intel/llvm/pull/11552
=> [CI] Install igc dev in devigc docker image

libdevice/cmake/modules/SYCLLibdevice.cmake
Otherwise we will hit problems with compiling with `-fsycl-targets=spirv64`.
Eventually we will need to expand this for the non-JIT `spirv64` targets, but those aren't supported today. 
We only build on Linux today because of ptrdiff_t size differences causing compiler errors on Windows.
Found this also while working on thinLTO.
=> [SYCL][libdevice] Build for spirv64 on Linux

sycl/test-e2e/Graph/Explicit/basic_buffer.cpp, sycl/test-e2e/Graph/Explicit/buffer_copy.cpp, sycl/test-e2e/Graph/Explicit/buffer_copy_2d.cpp, sycl/test-e2e/Graph/Explicit/buffer_copy_host2target.cpp, sycl/test-e2e/Graph/Explicit/buffer_copy_host2target_2d.cpp, sycl/test-e2e/Graph/Explicit/buffer_copy_host2target_offset.cpp, sycl/test-e2e/Graph/Explicit/buffer_copy_offsets.cpp, sycl/test-e2e/Graph/Explicit/buffer_copy_target2host.cpp, sycl/test-e2e/Graph/Explicit/buffer_copy_target2host_2d.cpp, sycl/test-e2e/Graph/Explicit/buffer_copy_target2host_offset.cpp, sycl/test-e2e/Graph/Explicit/buffer_fill.cpp, sycl/test-e2e/Graph/Explicit/buffer_fill_2d.cpp, sycl/test-e2e/Graph/Explicit/buffer_fill_3d.cpp, sycl/test-e2e/Graph/Explicit/event_status_querying.cpp, sycl/test-e2e/Graph/Explicit/queue_constructor_buffer.cpp, sycl/test-e2e/Graph/RecordReplay/basic_buffer.cpp, sycl/test-e2e/Graph/RecordReplay/buffer_copy.cpp, sycl/test-e2e/Graph/RecordReplay/buffer_copy_2d.cpp, sycl/test-e2e/Graph/RecordReplay/buffer_copy_host2target.cpp, sycl/test-e2e/Graph/RecordReplay/buffer_copy_host2target_2d.cpp, sycl/test-e2e/Graph/RecordReplay/buffer_copy_host2target_offset.cpp, sycl/test-e2e/Graph/RecordReplay/buffer_copy_offsets.cpp, sycl/test-e2e/Graph/RecordReplay/buffer_copy_target2host.cpp, sycl/test-e2e/Graph/RecordReplay/buffer_copy_target2host_2d.cpp, sycl/test-e2e/Graph/RecordReplay/buffer_copy_target2host_offset.cpp, sycl/test-e2e/Graph/RecordReplay/buffer_fill.cpp, sycl/test-e2e/Graph/RecordReplay/buffer_fill_2d.cpp, sycl/test-e2e/Graph/RecordReplay/buffer_fill_3d.cpp, sycl/test-e2e/Graph/RecordReplay/event_status_querying.cpp, sycl/test-e2e/Graph/RecordReplay/queue_constructor_buffer.cpp
Enables buffer tests which were disabled on https://github.com/intel/llvm/pull/11133 due to a failure which is no longer reproducible.
=> [SYCL][Graphs][CUDA] Re-enable buffer tests

sycl/plugins/unified_runtime/CMakeLists.txt
pre-commit PR for https://github.com/oneapi-src/unified-runtime/pull/1486
=> [UR][L0] Fix DeviceInfo global mem free to report unsupported given MemCount==0

sycl/plugins/unified_runtime/CMakeLists.txt
This patch makes use of the recently introduced `fetch_adapter_source()` utility function to decouple fetching all UR adapter source in the event that a different repo/tag pair is used. To facilitate this `fetch_adapter_source()` was updated to only perform a fetch if the adapter name is present in the `SYCL_ENABLE_PLUGINS` variable and the repo/tag pair does not match the values set in the `UNFIED_RUNTIME_REPO` and `UNIFIED_RUNTIME_TAG` variables.
To exercise the newly decoupled adapter source mechanism the OpenCL adapter is bumped to 3609afc7.
=> [UR] Decouple adapter tags & bump OpenCL 3609afc7

sycl/doc/extensions/experimental/sycl_ext_oneapi_root_group.asciidoc, sycl/include/sycl/ext/oneapi/experimental/root_group.hpp, sycl/test-e2e/GroupAlgorithm/root_group.cpp, sycl/test/warnings/free_functions_deprecation.cpp
That aligns it with the free_function_queries extension.
=> [SYCL] Update root_group extension to use `this_work_item` namespace

mlir/include/mlir/Conversion/GENToLLVM/GENToLLVM.h, mlir/include/mlir/Conversion/Passes.h, mlir/include/mlir/Conversion/Passes.td, mlir/include/mlir/InitAllExtensions.h, mlir/lib/Conversion/GENToLLVM/CMakeLists.txt, mlir/lib/Conversion/GENToLLVM/GENToLLVM.cpp, mlir/lib/Dialect/GEN/IR/GENDialect.cpp, mlir/test/Conversion/GENToLLVM/gen-to-llvm.mlir
Make GEN implement `ConvertToLLVMPatternInterface` so it can be converted to LLVM using the `-convert-to-llvm` pass.
Also make some improvements to `-convert-gen-to-llvm`:
- Rename files and classes to match other dialects;
- Make it a `OperationPass<>` so it can be run using any operation as its root;
- Leverage MLIR TableGen infrastructure to define constructor instead of doing it manually;
- Use operations from dialects other than `llvm` in conversion tests.
=> [GEN] Make GEN implement `ConvertToLLVMPatternInterface`

mlir/include/mlir/Conversion/Passes.td, mlir/lib/Conversion/GENToLLVM/GENToLLVM.cpp, mlir/test/Conversion/GENToLLVM/gen-to-llvm.mlir
Add option to control whether 32 or 64 bit integers are used.
=> [GEN] Add `use-64bit-index` option to `-convert-gen-to-spirv`

clang/include/clang/Sema/Sema.h, clang/include/clang/Sema/SemaBase.h, clang/include/clang/Sema/SemaOpenACC.h, clang/lib/Sema/CMakeLists.txt, clang/lib/Sema/Sema.cpp, clang/lib/Sema/SemaBase.cpp, clang/lib/Sema/SemaOpenACC.cpp
This is a follow-up to #84184. Multiple reviewers there pointed out to
me that we should have a common base class for `Sema` and `SemaOpenACC`
to avoid code duplication for common helpers like `getLangOpts()`. On
top of that, `Diag()` function was requested for `SemaOpenACC`. This
patch delivers both.
The intent is to keep `SemaBase` as small as possible, as things there
are globally available across `Sema` and its parts without any
additional effort from usage side. Overused, this can undermine the
whole endeavor of splitting `Sema` apart.
Apart of shuffling code around, this patch introduces a helper private
function `SemaDiagnosticBuilder::getDeviceDeferredDiags()`, the sole
purpose of which is to encapsulate member access into (incomplete)
`Sema` for function templates defined in the …
=> [clang][NFC] Introduce `SemaBase` (#87634)

sycl/include/sycl/detail/pi.h
In native assert design (https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_oneapi_assert.asciidoc), fallback implementation is used only when native support is not available for underlying device(OCL CPU/GPU, level 0 GPU). The fallback implementation for assert is provided via sycl device libraries and fallback mechanism requires that any underlying device which provides native assert should also expose 'cl_intel_devicelib_assert' extension for sycl runtime to check. Latest OCL cpu runtime has already provided native assert and expose this ext string, but we find the fallback implementation is still used instead of native version on OCL CPU device.
The reason is sycl runtime used a different string for checking: "pi_ext_intel_devicelib_assert", so this PR …
=> [SYCL] Align assert ext name with libdevice implementation

sycl/plugins/unified_runtime/CMakeLists.txt
Following up from #13278 change the calls to `fetch_adapter_source()` to use the `UNIFIED_RUNTIME_REPO` variable by default. This should ensure that existing UR testing PR's are using the intended fork.
=> [UR] Use UNIFIED_RUNTIME_REPO for adapter source fetches

.github/workflows/sycl-containers.yaml
When we push the built docker image with tags, it will be stored in github as a package.
The default package is private.
When we create name image names,  they are all private by default.
Hence we can't access `_unstable` or `_devigc` images after refactoring. 
See https://github.com/intel/llvm/actions/runs/8574917864/job/23502927206?pr=13305
> /usr/bin/docker pull "ghcr.io/intel/llvm/ubuntu2204_intel_drivers_devigc:latest"
>   Error response from daemon: Head "https://ghcr.io/v2/intel/llvm/ubuntu2204_intel_drivers_devigc/manifests/latest": unauthorized
>   Warning: Docker pull failed with exit code 1, back off 2.664 seconds before retry."
Also the package permission control is in github org level, not in repo level, 
so even the repo admin can't mark them as public.
To avoid applying for …
=> [CI] Use same image name but different tag

sycl/include/syclcompat/memory.hpp
This PR cleanses up a the memory header to prepare for the next update:
- device_memory wrapper now accepts a queue argument (to be consistent with the rest of the memory calls)
- read_only usm property protected behind a feature macro
- removed `syclcompat::` verbosity from some internal implementations
- Doxygen docs reviewed
- Variable names improved (M -> Mem, D -> Dim, Val -> Value)
=> [SYCL][COMPAT] Memory Header cleanup

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/util.hpp
This PR adds an experimental approach to support `select_from_sub_group`,
`shift_sub_group_left`, `shift_sub_group_right`, and `permute_sub_group_by_xor` functions  on SPIRV devices.
As these are based on still to be supported intrinsics, tests have been left out.
=> [SYCL][COMPAT] Support for experimental masked shifts

sycl/plugins/unified_runtime/CMakeLists.txt
Revert https://github.com/oneapi-src/unified-runtime/pull/1448, pulls in OpenCL adapter changes from https://github.com/oneapi-src/unified-runtime/pull/1496.
=> [UR][OpenCL] Revert urMemBufferCreate extension function lookup error

sycl/test-e2e/ESIMD/srnd.cpp
We didn't catch this in CI because it's a PVC only test.
=> [SYCL][ESIMD][E2E] Include cmath in srnd.cpp

clang/lib/Driver/ToolChains/MSVC.cpp, clang/test/Driver/sycl-offload.c
This reverts commit d6eecfa0e709ec280db6c15fa84d9f573e6a9d42.
This was commit was trying to cover the scenario:
```
clang-cl -I[path to sycl headers] sycl_program.cpp 
clang-cl -fsycl sycl_program.obj
```
and automatically link with sycl library at link step in such case.
But problem is that at link step there is no way to know if -fsycl -MDd option was used at compile step or not.
if -fsycl -MDd is used at compilation step then driver adds --dependent-lib=msvcrtd --dependent-lib=sycl7d options:
`clang-cl -fsycl -MDd  sycl_program.cpp  # --dependent-lib=msvcrtd --dependent-lib=sycl7d`
If then user links the program like this (without  -MDd):
`clang-cl -fsycl sycl_program.obj` then we will also link with sycl7 library (release version) which will cause a problem.
Because at link step we …
=> Revert "[SYCL][Driver] Link with sycl libs at link step of clang-cl -fsycl (#12793)"

clang-tools-extra/clangd/test/sycl.test
Line number of the queue constructor changed after https://github.com/intel/llvm/pull/13241
=> [SYCL] Update clangd test after queue.hpp change in PR#13241

llvm/lib/Transforms/Instrumentation/AddressSanitizer.cpp, llvm/test/Instrumentation/AddressSanitizer/spir_skip_builtin.ll
Disable device sanitizer instrument following case:
%0 = load i64, ptr addrspace(1) getelementptr inbounds (i8,
ptr addrspace(1) @__spirv_BuiltInGlobalInvocationId, i64 8)
=> [DeviceSanitizer] Strip off pointer casts and inbounds GEPs

sycl/test-e2e/Basic/kernel_max_wg_size.cpp
SYCL E2E test for https://github.com/oneapi-src/unified-runtime/pull/1495
Currently this test case works fine for opencl but doesn't work for level_zero.
=> [SYCL][E2E] Test kernel with kernel_device_specific::work_group_size WG size and large register file

clang/lib/Driver/CMakeLists.txt
Fix `llvm/SYCLLowerIR/DeviceConfigFile.inc: No such file or directory` when compiling clang Driver.cpp
The inc file is generated by tablegen_target DeviceConfigFile.
=> [SYCL][Driver] Add target DeviceConfigFile to DEPENDS of clangDriver

sycl/plugins/unified_runtime/CMakeLists.txt, sycl/source/detail/event_info.hpp
https://github.com/intel/llvm/pull/9944 introduced a hack in the OpenCL PI plugin which maps PI_EVENT_QUEUED to PI_EVENT_SUBMITTED. This hack is problematic because it will make SYCL-RT assume that an event has been flushed when it might not have been. At the moment, this could result in buggy behaviour on the OpenCL backend when using multiple queues. The OpenCL specification states:
> "To use event objects that refer to commands enqueued in a command-queue as event objects to wait on by commands enqueued in a different command-queue, the application must call a clFlush or any blocking commands that perform an implicit flush of the command-queue where the commands that refer to these event objects are enqueued."
This PR, moves the mapping from UR to `get_event_info()` inside sycl-rt …
=> [SYCL] Handle PI_EVENT_STATUS_QUEUED return value

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/device.hpp, sycl/test-e2e/syclcompat/device/device.cpp, sycl/test-e2e/syclcompat/device/device_threaded.cpp
- Adds multiple properties to syclcompat's device_info class.
- Usage of `sycl::id` deprecated in favour of `sycl::range`.
- Refactored queue creation, implementation moved to a private method. 
- Device name truncated if it's name exceeds the maximum buffer size (256 by default).
Minor:
- Updated format of device tests to match the current test style used for other headers.
=> [SYCL][COMPAT] Extended device_info properties.

sycl/test-e2e/Graph/RecordReplay/valid_no_end.cpp, sycl/test-e2e/Graph/ValidUsage/empty_graph.cpp
- Temporarily disable tests failing on Arc in post-commit CI while the issue is investigated
Failing tests reported and and issue tracked in #13301
=> [SYCL][Graph] Disable graph tests failing on Arc

sycl/test-e2e/syclcompat/math/math_complex.cpp, sycl/test-e2e/syclcompat/memory/memory_fixt.hpp, sycl/test-e2e/syclcompat/memory/memory_management_shared.cpp, sycl/test-e2e/syclcompat/memory/memory_management_test2.cpp, sycl/test-e2e/syclcompat/memory/usm_allocations.cpp, sycl/test-e2e/syclcompat/memory/usm_shared_allocations.cpp
Some tests were being completely skipped entirely because a part of them required `aspect::usm_shared_allocations`.
This PR splits the tests in various files to disable only the usages of shared memory.
=> [SYCL][COMPAT] shared memory test split from main tests

opencl/opencl-aot/CMakeLists.txt
This change is to avoid DLL hijacking security issue.
=> [OpenCL] Config dependent-load flag to exclude CWD from DLL search path

sycl/doc/extensions/supported/sycl_ext_intel_esimd/sycl_ext_intel_esimd_functions.md, sycl/include/sycl/ext/intel/esimd/memory.hpp, sycl/test/esimd/memory_properties.cpp
SVM doesn't support less than 4 bytes on Gen12, we either get an error or the wrong answer.
=> [SYCL][ESIMD] atomic_update with data size less than 4 bytes should use LSC atomics

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/math.hpp, sycl/test-e2e/syclcompat/math/math_extend.cpp
Adds support for addition, substraction, min, and max operations extended from 32 to 33 bit.
Adds an extra API for each operation where a transform binaryop can be applied to the result of the defined `extend` operation.
=> [SYCL][COMPAT] Added 33 bit extend operations with and without saturation

sycl/plugins/unified_runtime/CMakeLists.txt
Bump UR commit to include a bugfix for HIP UR adapter dereferencing a nullptr https://github.com/oneapi-src/unified-runtime/pull/1357
=> [UR] Bump HIP tag to 760eaa38

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/util.hpp
Implement masked compat shuffle function on cuda:
- select_from_sub_group
- shift_sub_group_left
- shift_sub_group_right
- permute_sub_group_by_xor
=> [SYCL[COMPAT][CUDA] Impl masked compat shuffles on cuda.

sycl/plugins/unified_runtime/CMakeLists.txt
Run CI for https://github.com/oneapi-src/unified-runtime/pull/1310
=> [UR][CUDA] Remove unused function variant

.github/workflows/email-check.yaml
https://github.com/intel/llvm/commit/1bed6397a3c47eb3ca19b70f8d15a7860da0792d resolved a merge conflict in .github/workflows/email-check.yaml by reintroducing a removed "uses" key. However, this makes for an invalid configuration. This commit removes the invalid conflict resolution.
Additionally, it changes the check for repository in the workflow to require intel/llvm. This should make it run as part of our CI.
=> [CI] Redirect and fix email-check workflow

sycl/plugins/unified_runtime/CMakeLists.txt
https://github.com/oneapi-src/unified-runtime/pull/1489
=> [UR] [NATIVECPU] CI for: Extended usm fill to bigger patterns than 1 byte

sycl/plugins/unified_runtime/CMakeLists.txt
https://github.com/oneapi-src/unified-runtime/pull/1317
=> [UR] Bump CUDA tag to 68e525a4

sycl/test/basic_tests/handler/handler_generic_lambda_interface.cpp, sycl/test/basic_tests/handler/parallel_for_arg_restrictions.cpp
All pre-existing preview features have been uplifted to be available by default.
=> [SYCL] Remove preview guard from a few tests

.github/workflows/sycl-linux-run-tests.yml, devops/dependencies.json
Ref: #11552
Tested here: https://github.com/intel/llvm/actions/runs/8673951174/job/23785766750
=> [CI] Add option to install driver with dev igc

.github/workflows/sycl-linux-precommit.yml
This reverts commit 66a741bc9d0056e7b350ceed2a01b8531b156af6.
UR can build fine with ROCm 6.0 now, so we should be good to revert this
=> Revert "Try to fix pre-commit CI with a hack (#12201)"

clang/lib/Driver/SanitizerArgs.cpp, clang/test/Driver/sycl-device-sanitizer.cpp, llvm/lib/Transforms/Instrumentation/AddressSanitizer.cpp, sycl/test/check_device_code/device_asan_no_ctor.cpp
The removed code fails to prevent ctor/dtor generation.
=> [SYCL][DeviceSanitizer] Use -asan-constructor-kind=none to disable ctor/dtor

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/math.hpp, sycl/test-e2e/syclcompat/common.hpp, sycl/test-e2e/syclcompat/math/math_compare.cpp
Adds the following ordered and unordered comparisons:
- compare
- undered_compare
- compare_both (wrapper for sycl::vec<ValueT, 2>)
- undered_compare_both (wrapper for sycl::vec<ValueT, 2>)
- compare_mask
- unordered_compare_mask
=> [SYCL][COMPAT] Added compare and unordered compare operations

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/defs.hpp, sycl/test-e2e/syclcompat/defs.cpp
This PR:
- unifies the names of the definitions in `defs.hpp` from `sycl_compat` to `syclcompat`
- extends definitions to work with MSVC
- Adds a macro to handle error codes from expressions that could throw `sycl::exception`.
=> [SYCL][COMPAT] defs.hpp update with Windows macros. SYCLCOMPAT_CHECK_ERROR added.

sycl/source/detail/queue_impl.cpp, sycl/source/detail/queue_impl.hpp, sycl/source/detail/scheduler/scheduler.cpp, sycl/source/detail/scheduler/scheduler.hpp, sycl/source/handler.cpp, sycl/unittests/Extensions/CommandGraph/InOrderQueue.cpp
Commit https://github.com/intel/llvm/pull/11758 added extra event as dependency to fix host task vs kernel dependencies for inorder queue. That logic missed part when we try to bypass scheduler for kernel with no dependencies. This commit fixes it and allows to bypass scheduler if previous commands are enqueued (no host task is involved).
=> [SYCL] Fix kernel shortcut path for inorder queue

.github/workflows/sycl-nightly.yml
Nightly packages haven't been published in a while and looking at the logs the job failed with 403.
The `softprops/action-gh-release` documentation says it needs `contents: write` permissions, which makes sense as it's creating a tag.
=> [CI] Fix permissions on nightly releases

sycl/include/syclcompat/memory.hpp, sycl/test-e2e/syclcompat/memory/memory_management_test1.cpp, sycl/test-e2e/syclcompat/memory/memory_management_test3.cpp
This PR replaces #11340
This PR extends the memory header to include 2 byte and 4 byte memsets.
- memset remains unchanged.
- 2D / 3D memsets are templated and wrap `sycl::fill`. Functionality remains unchanged as it is exposed through `detail::memset<unsigned char>`, equivalent to what we had before.
- memset_d16 and memset_d32 calls are added wrapped around `sycl::fill`  using 2-byte and 4-byte datatypes
Added tests for memset_d16 and memset_d32.
=> [SYCL][COMPAT] Adding 2-byte and 4-bytes memset operations to headers

sycl/plugins/unified_runtime/CMakeLists.txt
Pulls in fixes
https://github.com/oneapi-src/unified-runtime/pull/1492
https://github.com/oneapi-src/unified-runtime/pull/1494
https://github.com/oneapi-src/unified-runtime/pull/1507
=> [UR][L0] Pull in a batch of L0 fixes

clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/sycl-spirv-ext.c
Do not enable SPV_KHR_bit_instructions until downstream tools are ready.  For example, enabling SPV_KHR_bit_instructions can cause llvm.bitreverse.* intrinsics to be unlowered by llvm-spirv, but some backends may not be ready to support llvm.bitreverse.*
=> [SYCL] Do not enable SPV_KHR_bit_instructions until downstream tools are ready

sycl/test-e2e/Plugin/level_zero_eager_init.cpp
If the test is run with UR_L0_LEAKS_DEBUG var set, UR will print ze call count summary. This summary can cause the test to fail as it will contain zeCommandQueueCreate, etc.
Fix this by making CHECK-NOT only match output generated by UR_L0_DEBUG.
=> [UR][L0] fix ze commands matching in level_zero_eager_init.cpp

clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/sycl-offload-new-driver.c
Gather all SPIR-V translator options and pass that to clang-linker-wrapper via the "--llvm-spirv-options" option.
Thanks
=> [SYCL][New offload driver][LLVM-SPIRV] Send all translator options to linker wrapper

sycl/test-e2e/bindless_images/read_norm_types.cpp
XFAIL the read_norm_types test as it is currently broken until an appropriate fix is figured out.
=> [E2E][Bindless] XFAIL broken read_norm_types test

sycl/source/detail/pi.cpp, sycl/test-e2e/OneapiDeviceSelector/illegal_input_hang.cpp
There's a gcc std::call_once bug that leads to a hang when the function passed to it throws an exception: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66146 Replace std::call_once with a static variable workaround until this is fixed.
=> [SYCL] Fix a hang with invalid values of ONEAPI_DEVICE_SELECTOR

sycl/source/detail/graph_impl.hpp
Fixes an issue found by Coverity in `addEventForNode` about dereferencing the `EventImpl` before a null check.
=> Fix Coverity dereference before null check issue

llvm/lib/SYCLLowerIR/ESIMD/LowerESIMD.cpp
We don't need it anymore and it causes a warning on the new `spirv64` target. 
I found this working on thinLTO.
=> [SYCL][ESIMD] Don't override target triple to genx64

sycl/source/detail/kernel_compiler/kernel_compiler_opencl.cpp
This should have been gotten with https://github.com/intel/llvm/pull/13214  but was accidentally overlooked. Errors discovered by sanitization.
=> [SYCL] kernel_compiler opencl query fix

sycl/source/handler.cpp, sycl/test-e2e/Regression/default-constructed-local-accessor.cpp
According to [4.7.6.11.1. Interface for local accessors](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_interface_for_local_accessors), passing a default constructed local accessor to a kernel function is allowed, as long as no accesses to the data elements are made.
When default constructing a `local_accessor`, it will default construct its `local_accessor_base` 
https://github.com/intel/llvm/blob/3f841ff1d21bac2601beaf087bc3d09170af6d35/sycl/include/sycl/accessor.hpp#L2803-L2805 
leading its `LocalAccessorImplHost` to be constructed with `MDims == 0`. When setting the kernel arguments corresponding to the local accessor, this caused `piKernelSetArg` to be called with `arg_size == 0`, which then causes an error. This PR fixes this by checking if `MDims` would be …
=> [SYCL] Fix launching a kernel with a default constructed local accessor

clang/tools/clang-linker-wrapper/LinkerWrapperOpts.td
Many other upstream options in the same file do this, and right now we have a few options that don't work because the driver passes the wrong dashes. We could fix the driver, but just simplify the whole thing.
=> [SYCL][ClangLinkerWrapper] Support single or double dash for SYCL options

sycl/include/sycl/sub_group.hpp, sycl/test-e2e/SubGroup/generic-shuffle.cpp, sycl/test-e2e/SubGroup/shuffle.cpp, sycl/test-e2e/SubGroup/shuffle_fp16.cpp, sycl/test-e2e/SubGroup/shuffle_fp64.cpp
=> Revert "[SYCL] Remove deprecated shuffles from the sub-group class"

.github/workflows/sycl-linux-run-tests.yml, .github/workflows/sycl-nightly.yml
Right now it is extremely confusing because the name is shown as SYCL CTS on Gen12 machine, basically implying that tests are run on GPU. And gpu device is shown as selected in the list of devices. 
This confusion may cost somebody a lot of time trying to reproduce issue on wrong backend when analyzing nightly failures.
=> [CI] Clarify that SYCL CTS nightly testing is on OpenCL CPU

sycl/include/sycl/sub_group.hpp
=> Revert "[ABI-Break][SYCL] Remove collectives in the sub-group class"

sycl/test-e2e/KernelAndProgram/test_cache_jit_aot.cpp
On Windows the persistent cache is still working but the path string when writing is one mishmash of Linux and Win separators and on read a different mishmash for the same file.  Corrects this test on Win.
Also am expanding it to confirm write/reuse/reuse is working on both Lin and Win, not just Win.
=> [SYCL] fix persistent cache test

sycl/source/detail/scheduler/commands.cpp, xpti/src/xpti_proxy.cpp
Coverity is complaining about `ProxyLoader` and `DemangleHandle` classes not having a copy constructor, even though these classes destroy/free resources in their destructor. If these classes are copy-constructed, this may cause use-after-free errors.
This PR fixes this by disallowing copy constructors in these classes - we don't use them in the code anyway.
=> [SYCL][XPTI] Fix Coverity issues by disabling copy constructors

sycl-fusion/jit-compiler/CMakeLists.txt, sycl-fusion/jit-compiler/include/KernelFusion.h, sycl-fusion/jit-compiler/include/Options.h, sycl-fusion/jit-compiler/ld-version-script.txt, sycl-fusion/jit-compiler/lib/KernelFusion.cpp, sycl-fusion/jit-compiler/lib/helper/ConfigHelper.h, sycl/source/CMakeLists.txt, sycl/source/detail/device_info.hpp, sycl/source/detail/jit_compiler.cpp, sycl/source/detail/jit_compiler.hpp
So far, the SYCL JIT library, used e.g. to implement the kernel fusion extension, was linked directly into `libsycl`.
This led to a significant increase in library binary size of `libsycl`. To avoid the corresponding startup overhead, in particular if applications do not use the kernel fusion extension, this PR implement lazy loading of the JIT library. 
Instead of linking the library into `libsycl`, the JIT library is built as a standalone shared library (`libsycl-fusion.so`). This library is only loaded at runtime on the first use of the JIT compiler and applications not using a feature that requires the JIT will not load the library at all. 
The dynamic loading happens through `dlopen` and `dlsym`, through existing functionality provided by PI and also used for the SYCL online compiler …
=> [SYCL][JIT] Load SYCL JIT lazily

clang/lib/AST/DeclPrinter.cpp
This is related to https://github.com/intel/llvm/commit/71c0784dc4a2ef40039a97af122ba78549193120. And now it's aligned with https://github.com/intel/llvm/blob/sycl/clang/lib/AST/DeclPrinter.cpp#L1097.
Fixes 12 lit.
=> Fix wrong resolution.

sycl/include/sycl/ext/oneapi/experimental/device_architecture.hpp, sycl/test/extensions/device_architecture/device_architecture.cpp
This patch updates device headers of sycl_ext_oneapi_device_architecture extension to prepare to support API in JIT. New functionality is always disabled now as it breaks the existing functionality, and will be enabled when the feature is fully implemented by updating other components.
=> [SYCL] Update sycl_ext_oneapi_device_architecture device headers to support JIT

sycl/source/detail/event_impl.hpp
making event() constructor fail fast if ONEAPI_DEVICE_SELECTOR is malformed.  
The config::get() call checks/parses env var exactly once, so there should not be any performance penalty for any event but the first.
=> [SYCL] event() fail fast

clang/include/clang/Basic/DiagnosticGroups.td, clang/include/clang/Basic/DiagnosticSemaKinds.td, clang/lib/Sema/SemaChecking.cpp, clang/test/CodeGenSYCL/builtin-alloca.cpp, clang/test/SemaSYCL/builtin-alloca-errors-device.cpp, clang/test/SemaSYCL/builtin-alloca.cpp
According to the extension specification:
> *`SizeSpecName` must have a default value of at least 1* and not be
set to a value less than 1 during program execution. Violation of these conditions results in undefined behavior.
Warn users on default values lesser than 1 used for `private_alloca` sizes.
=> [SYCL][SCLA] Emit warning on invalid default size value

clang/lib/Driver/Driver.cpp, sycl/test/check_device_code/native_cpu/sycl-native-cpu-libclc.cpp
This PR makes it so we select the right module for `libclc` when compiling for Native CPU.
=> [SYCL] [NATIVECPU] Select right libclc file for native cpu

sycl/test-e2e/CMakeLists.txt
On windows the lit setup in the bin directory is `llvm-lit.py`, this helps CMake find it.
=> [SYCL][E2E] Add llvm-lit.py to LIT binary names

sycl/plugins/unified_runtime/CMakeLists.txt
* https://github.com/oneapi-src/unified-runtime/pull/1032
* https://github.com/oneapi-src/unified-runtime/pull/1183
* https://github.com/oneapi-src/unified-runtime/pull/1243
=> [UR] Bump main tag to 31d0fe15

llvm/include/llvm/ADT/StringRef.h
Revert https://github.com/intel/llvm/commit/4ec9a662d388db8a2bb862dbaa7fc3fd809d1240 since vc-intrinsics-src is still using deprecated api.
=> Fix build error.

libclc/cmake/modules/AddLibclc.cmake
Some generators like Unix Makefiles wouldn't automatically ensure that this directory exists, which can break the build.
=> [libclc] Ensure directory exists for libclc files

sycl/doc/design/CommandGraph.md, sycl/plugins/unified_runtime/CMakeLists.txt, sycl/plugins/unified_runtime/pi2ur.hpp
Test the UR commit that enables updating kernel commands in a command-buffer in the OpenCL adapter https://github.com/oneapi-src/unified-runtime/pull/1358
=> [SYCL][Graph] Bump UR commit to OpenCL kernel update

sycl/include/sycl/ext/oneapi/experimental/enqueue_functions.hpp, sycl/include/sycl/sycl.hpp, sycl/test-e2e/EnqueueFunctions/barrier.cpp, sycl/test-e2e/EnqueueFunctions/common.hpp, sycl/test-e2e/EnqueueFunctions/kernel_shortcut_with_kb.cpp, sycl/test-e2e/EnqueueFunctions/kernel_shortcuts.cpp, sycl/test-e2e/EnqueueFunctions/kernel_submit.cpp, sycl/test-e2e/EnqueueFunctions/kernel_submit_with_event.cpp, sycl/test-e2e/EnqueueFunctions/kernel_submit_with_event_and_kb.cpp, sycl/test-e2e/EnqueueFunctions/kernel_submit_with_kb.cpp, sycl/test-e2e/EnqueueFunctions/mem_advise.cpp, sycl/test-e2e/EnqueueFunctions/memops.cpp, sycl/test-e2e/EnqueueFunctions/prefetch.cpp
This commit implements the [sycl_ext_oneapi_enqueue_functions](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/proposed/sycl_ext_oneapi_enqueue_functions.asciidoc) extension with enqueue free functions.
Optimization for avoiding event creation will happen in a follow-up patch.
=> [SYCL] Implement enqueue free functions extension

sycl/test-e2e/Basic/kernel_info.cpp, sycl/test-e2e/GroupAlgorithm/root_group.cpp, sycl/test-e2e/KernelCompiler/opencl_queries.cpp
For https://github.com/intel/llvm/pull/13528
All three have internal trackers.
=> [SYCL][E2E] XFAIL three tests for driver update

sycl/test-e2e/GroupAlgorithm/root_group.cpp, sycl/test-e2e/KernelCompiler/opencl_queries.cpp
For https://github.com/intel/llvm/pull/13528, follow up for https://github.com/intel/llvm/pull/13543. Failures are tracked internally.
=> [SYCL][E2E] Fix XFAILs for driver update

sycl/test-e2e/GroupAlgorithm/root_group.cpp
For https://github.com/intel/llvm/pull/13528, follow up for
https://github.com/intel/llvm/pull/13543 and https://github.com/intel/llvm/pull/13547. Failures are tracked
internally.
=> [SYCL][E2E] Even more XFAIL fixes for driver update

.github/workflows/sycl-detect-changes.yml, .github/workflows/sycl-linux-precommit.yml
When we are doing dependencies-igc-dev.json update,
we will rebuild the docker image, but we can't use that image
immediately in the same CI for testing.
So we need to run the test by using the install driver option.
=> [CI] Install driver when doing tests for dependencies-igc-dev.json update

sycl/source/detail/context_impl.hpp, sycl/unittests/Extensions/CompositeDevice.cpp
Fixed a case where it was not possible to create a queue for a component device using context for a composite device.
=> [SYCL] Fix descendent device support for composite/component devices

libclc/generic/lib/math/cosh.cl, libclc/generic/lib/math/lgamma_r.cl, libclc/generic/lib/math/sinh.cl, libclc/generic/libspirv/math/clc_pow.cl, libclc/generic/libspirv/math/clc_pown.cl, libclc/generic/libspirv/math/clc_powr.cl, libclc/generic/libspirv/math/clc_rootn.cl, libclc/generic/libspirv/math/lgamma_r.cl
While we have mostly been getting away with this, in certain circumstances (constant propagation, inlining) the compiler would be able to tell that the double cannot fit into the resulting integer type, which produces a poison value in LLVM IR.
=> [libclc] Fix UB in double->int conversions

sycl/test-e2e/Graph/RecordReplay/valid_no_end.cpp, sycl/test-e2e/Graph/ValidUsage/empty_graph.cpp, sycl/test-e2e/Graph/lit.local.cfg
- Test are failing sporadically in post-commit
- Disable while investigating
- Remove unsupported for DG2 from 2 specific tests
=> [SYCL][Graph] Disable all tests on DG2

clang/include/clang/Basic/FPOptions.def
Let MathErrno reference the previous item FPAccuracy.
Fix:
Clang::AST/ast-dump-fpfeatures.cpp
Clang::AST/ast-dump-fpfeatures.m
Clang::AST/ast-dump-late-parsing.cpp
=> Fix AST lit failures.

.github/workflows/sycl-linux-run-tests.yml
https://github.com/intel/llvm/pull/13421 reduced parellization when trying to avoid early build failouts. Use `ninja`'s `-k0` to do the same without undesired side effects. Also run individual tests in parallel as well.
=> [CI][SYCL-CTS] Ensure link/test runs are parallel

sycl/test/abi/layout_handler.cpp
Not an actual ABI break, just make sure that building/testing the project with more GCC/STL versions would pass.
=> [SYCL] Support more STL versions in abi/layout_handler.cpp CHECKS

sycl/CMakeLists.txt
In compile.py we are using -t sycl-toolchain to build the sycl
toolchain. However, sycl-toolchain is not added by default target.
So when I configure the project , then build the default target,
eg: `ninja`
some of the libs eg: libdevice will not be built even if they are in the
"LLVM_ENABLE_PROJECTS" list.
eg: One of the typical failures are missing sycl-devicelib-host.
```
/iusers/jinsongj/llvm/build/bin/clang++   -fsycl -fsycl-targets=spir64 /iusers/jinsongj/llvm/sycl/test-e2e/Matrix/XMX8/element_wise_abc.cpp
$ /iusers/jinsongj/llvm/build/bin/clang++   -fsycl -fsycl-targets=spir64 /iusers/jinsongj/llvm/sycl/test-e2e/Matrix/XMX8/element_wise_abc.cpp
/usr/bin/ld: cannot find -lsycl-devicelib-host: No such file or directory
clang++: error: linker command failed with exit code 1 (use -v to …
```
=> [SYCL][CMake] Build sycl-toolchain by default

.github/workflows/sycl-linux-precommit.yml, devops/dependencies.json
Right now we don't run all the tests in precommit on Arc when drivers change.
=> [CI] Run all tests on Arc if drivers change

sycl/doc/extensions/experimental/sycl_ext_oneapi_root_group.asciidoc, sycl/include/sycl/ext/oneapi/experimental/root_group.hpp, sycl/test-e2e/GroupAlgorithm/root_group.cpp
get_child_group() was originally designed assuming there would be a fixed
hierarchy of groups, and is therefore incompatible with extensions that would
modify the hierarchy (e.g., "clusters" on NVIDIA GPUs).
This interface should be replaced by a more general and explicit mechanism for
partitioning groups that does not make such assumptions.
Signed-off-by: John Pennycook <john.pennycook@intel.com>
=> [SYCL] Remove get_child_group()

sycl/plugins/unified_runtime/CMakeLists.txt, sycl/plugins/unified_runtime/pi2ur.hpp
- Bumps commit only and includes minimal pi2ur changes for new descriptor members
- In-order path not currently used, enable profiling by default (match previous behaviour)
UR PR: https://github.com/oneapi-src/unified-runtime/pull/1442
=> [SYCL][Graph] Bump UR commit for in-order L0 optimization

clang/include/clang/Basic/Builtins.td, clang/include/clang/Basic/DiagnosticSemaKinds.td, clang/lib/CodeGen/CGBuiltin.cpp, clang/lib/CodeGen/CodeGenFunction.h, clang/lib/Sema/SemaChecking.cpp, clang/test/CodeGenSYCL/Inputs/private_alloca.hpp, clang/test/CodeGenSYCL/builtin-alloca.cpp, clang/test/SemaSYCL/Inputs/private_alloca.hpp, clang/test/SemaSYCL/builtin-alloca-errors-device.cpp, clang/test/SemaSYCL/builtin-alloca-errors-host.cpp, clang/test/SemaSYCL/builtin-alloca.cpp, sycl/include/sycl/ext/oneapi/experimental/alloca.hpp, sycl/test-e2e/PrivateAlloca/UnsupportedDevice/exception_unsupported_backend.cpp, sycl/test-e2e/PrivateAlloca/ValidUsage/Inputs/private_alloca_test.hpp, sycl/test-e2e/PrivateAlloca/ValidUsage/private_alloca_bool_size.cpp, sycl/test-e2e/PrivateAlloca/ValidUsage/private_alloca_decorated.cpp, sycl/test-e2e/PrivateAlloca/ValidUsage/private_alloca_legacy.cpp, sycl/test-e2e/PrivateAlloca/ValidUsage/private_alloca_multiple.cpp, sycl/test-e2e/PrivateAlloca/ValidUsage/private_alloca_raw.cpp, sycl/test-e2e/PrivateAlloca/private_alloca_host.cpp, sycl/test/extensions/private_alloca.cpp, sycl/test/optional_kernel_features/private_alloca.cpp
Add support for `aligned_private_alloca`. Use new `__builtin_intel_sycl_alloca_with_align` builtin in implementation.
Revamp diagnostic messages to support the new builtin.
Add SPIR-V integration tests.
=> [SYCL][SCLA] Add `aligned_private_alloca` support

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/util.hpp, sycl/test-e2e/syclcompat/util/util_nd_range_barrier_test.cpp
AMD ~~and CUDA~~ devices still not supported.
~~CUDA to be supported in https://github.com/intel/llvm/pull/12516~~
Edit: Since #12516 has been merged, CUDA is also `seq_cst` by default.
=> [SYCL][COMPAT] nd_range barriers seq_cst by default in supported devices

sycl/include/sycl/types.hpp, sycl/include/sycl/vector_preview.hpp
This PR prepares the ground for https://github.com/intel/llvm/pull/13270 by adding a header for containing ABI-breaking changes in `sycl::vec`.
Separating header creation from #13270 results in a cleaner `git diff` and helps highlighting the core changes made in #13270 for using `std::array` as storage type on device.
`vector_preview.hpp` is intended to have the exact same content as `vector.hpp`.
=> [NFC] Copy sycl::vec implementation into a dedicated preview header

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/util.hpp, sycl/test-e2e/syclcompat/util/util_match_all_over_group.cpp, sycl/test-e2e/syclcompat/util/util_match_any_over_group.cpp
Added support to match_any_over_sub_group and match_all_over_sub_group functions to compare values across work-items withing a sub-group.
=> [SYCL][COMPAT] match_any and match_all over sub group support

clang/include/clang/Basic/DiagnosticSemaKinds.td, clang/lib/Sema/SemaChecking.cpp, clang/test/SemaSYCL/builtin-alloca-aot.cpp, sycl/doc/extensions/experimental/sycl_ext_oneapi_private_alloca.asciidoc
`sycl_ext_oneapi_private_alloca` needs JIT compilation to function properly. Aspects cannot rely on querying whether a kernel is AOT compiled or not, so we just error out at compile time.
=> [SYCL][SCLA] Error out on AOT compilation of `[aligned_]private_alloca`

sycl/source/detail/kernel_compiler/kernel_compiler_opencl.cpp, sycl/test-e2e/KernelCompiler/opencl_queries.cpp
Improves kernel_compiler WA for CL_DEVICE_PROFILE query. 
Currently ocl query returns some extra symbols we want to eliminate from final result returned to user. 
Removes all special symbols now. To be removed once ocl query is fixed.
=> [SYCL] Fix WA for ocl query of CL_DEVICE_PROFILE 

sycl/include/CL/sycl.hpp, sycl/test/warnings/sycl_2020_deprecations.cpp, sycl/unittests/SYCL2020/AtomicFenceCapabilities.cpp, sycl/unittests/SYCL2020/AtomicMemoryScopeCapabilities.cpp, sycl/unittests/queue/DeviceCheck.cpp
Fixes https://github.com/intel/llvm/issues/13592. Also update unittests not to use the deprecated header file.
=> [SYCL] Silence warnings for `#warning` directive in `CL/sycl.hpp`

sycl/include/sycl/half_type.hpp, sycl/include/sycl/vector.hpp
This commit changes the internal representation of sycl::vec<sycl::half, N> to use sycl::half directly instead of the wrapper implementation used inside them. This avoids strict alias violation in the operator[] for the host implementation.
=> [SYCL] Change internal host vec representation

sycl/test-e2e/Matrix/XMX8/joint_matrix_bf16_fill_k_cache_unroll.cpp, sycl/test-e2e/Matrix/XMX8/joint_matrix_int8_vnni.cpp
Remove xfail for Matrix/XMX8/joint_matrix_bf16_fill_k_cache_unroll.cpp and XMX8/joint_matrix_int8_vnni.cpp
Resolves https://github.com/intel/llvm/issues/13593
=> [Joint Matrix][E2E] Remove xfail for 2 tests

.github/workflows/sycl-linux-precommit-aws.yml, .github/workflows/sycl-linux-precommit.yml
Follow up from:
* https://github.com/intel/llvm/pull/13606
That reverted the build job, this also reverts the test jobs
=> [CI] Revert AMD and Nvidia test image to known working

sycl/include/sycl/ext/intel/esimd/detail/memory_intrin.hpp, sycl/include/sycl/ext/intel/esimd/memory.hpp, sycl/test/esimd/lsc.cpp, sycl/test/esimd/memory_properties.cpp
The actual mask is a scalar. ESIMD passed a vector mask, which worked because GPU driver ignored that until an unwanted assert there was added in December 2023.
Even though the assert was removed in GPU driver today(Apr30'2024), it will take long until it reaches our CI.
This fix resolves these test fails on PVC:
SYCL :: ESIMD/lsc/lsc_load_2d_compare.cpp
SYCL :: ESIMD/lsc/lsc_load_2d_u16.cpp
SYCL :: ESIMD/lsc/lsc_load_2d_u32.cpp
SYCL :: ESIMD/lsc/lsc_load_2d_u64.cpp
SYCL :: ESIMD/lsc/lsc_load_2d_u8.cpp
SYCL :: ESIMD/lsc/lsc_load_store_2d_compare.cpp
SYCL :: ESIMD/lsc/lsc_prefetch_2d_u16.cpp
SYCL :: ESIMD/lsc/lsc_prefetch_2d_u32.cpp
SYCL :: ESIMD/lsc/lsc_prefetch_2d_u64.cpp
SYCL :: ESIMD/lsc/lsc_prefetch_2d_u8.cpp
SYCL :: ESIMD/lsc/lsc_store_2d_u32.cpp
SYCL :: …
=> [ESIMD] Use 1-element mask for load_2d()/store_2d()/prefetch_2d()

sycl/test-e2e/Basic/kernel_info.cpp
Closes: https://github.com/intel/llvm/issues/13615
=> [SYCL][E2E] Fix XPASS in kernel_info.cpp on FPGA

sycl/test/extensions/private_alloca.cpp
See https://github.com/intel/llvm/issues/13625.
=> [SYCL] Require "asserts" build for `sycl/test/extensions/private_alloca.cpp`

clang/lib/Driver/Driver.cpp, clang/lib/Driver/ToolChains/SYCL.cpp, clang/test/Driver/sycl-bfloat16-lib.cpp, clang/test/Driver/sycl-device-lib-win.cpp, clang/test/Driver/sycl-device-lib.cpp, clang/test/Driver/sycl-early-device-link.cpp, clang/test/Driver/sycl-force-target.cpp, clang/test/Driver/sycl-instrumentation.c, clang/test/Driver/sycl-no-rdc-fat-archive-win.cpp, clang/test/Driver/sycl-no-rdc-fat-archive.cpp, clang/test/Driver/sycl-no-rdc-win.cpp, clang/test/Driver/sycl-no-rdc.cpp, clang/test/Driver/sycl-offload-new-driver.c, libdevice/cmake/modules/SYCLLibdevice.cmake
This is try #2 for this - original change was suspected of breaking the device library builds.
This change represents 2 changes.
1.  Update the build to create LLVM-IR based device libraries.
This is done by using the existing -fsycl-device-only functionality to create the device libraries that are used during device link.
2.  Update the compiler driver to use the LLVM-IR based device libraries.
When performing the device linking instead of performing a full unbundle of the device libraries and using the device binary that was extracted.
This streamlines the device linking behaviors, completely removing the cumbersome unbundling step from the process, freeing up a number of exteral tool calls.
=> [Driver][SYCL] Use LLVM-IR based device libraries for device linking

sycl/doc/extensions/experimental/sycl_ext_oneapi_in_order_queue_events.asciidoc, sycl/source/detail/queue_impl.cpp, sycl/test-e2e/InOrderEventsExt/get_last_event.cpp
This commit makes the following changes to the
sycl_ext_oneapi_in_order_queue_events experimental extension:
* The external event set using `queue::ext_oneapi_set_external_event()` is now required to finish after the latest command submitted to the corresponding queue.
* The external event set using `queue::ext_oneapi_set_external_event()` will now be returned by `queue::ext_oneapi_get_last_event()` if no command has been submitted to the queue since the call.
* Calling `queue::wait()` and similar on a queue with an external event set will now only wait on that event, as it is expected to finish only after other commands in the queue has finished (see previous point.)
=> [SYCL][Docs] Behavioral changes to in-order queue events extension

sycl/include/sycl/ext/oneapi/bindless_images.hpp, sycl/include/sycl/ext/oneapi/bindless_images_mem_handle.hpp, sycl/include/sycl/ext/oneapi/bindless_images_memory.hpp, sycl/include/sycl/handler.hpp, sycl/include/sycl/queue.hpp, sycl/source/detail/memory_manager.cpp, sycl/source/handler.cpp, sycl/test/include_deps/sycl_detail_core.hpp.cpp
Keep the amount of code processed by the C++ front end at absolute minimum. Part of ongoing efforts to reduce the amount of the SYCL code required to process when including `sycl/detail/core.hpp`.
=> [SYCL] Process less bindless images code in handler/queue headers

mlir/lib/Conversion/GENToSPIRV/GENToSPIRV.cpp, mlir/test/Conversion/GENToSPIRV/gen-to-spirv.mlir
When lowering ND-range operations from GEN to SPIR-V, with a constant dimension, use CompositeExtract instead of VectorExtractDynamic.
=> [GEN] Prefer CompositeExtract over VectorExtractDynamic
