sycl/doc/syclcompat/README.md, sycl/include/syclcompat/util.hpp
This PR attempts to fix the failing `SYCL :: syclcompat/util/util_nd_range_barrier_test.cpp` tests in the CUDA backend
=> [SYCL][COMPAT] Reverted nd_barrier atomic_ref to acq_rel (NVPTX)

sycl/include/sycl/ext/oneapi/experimental/alloca.hpp, sycl/test-e2e/PrivateAlloca/private_alloca_host.cpp
Throw a `sycl::exception` with `feature_not_supported` error code instead of an instance of the deprecated `sycl::feature_not_supported` on `[aligned_]private_alloca` use on host.
=> [SYCL][SCLA] Throw `sycl::exception` with `feature_not_supported` error code

sycl/include/syclcompat/math.hpp, sycl/include/syclcompat/util.hpp, sycl/test-e2e/syclcompat/util/util_cast_value_test.cpp
In line with other recent PRs, the objective is to improve compilation times and be clear about dependencies from each header. 
Will be retained as draft until all current opened PRs for the util and math headers are merged as these pending PRs may require to include additional header files.
=> [SYCL][COMPAT] Removed sycl/sycl.hpp include

sycl/include/CL/__spirv/spirv_ops.hpp, sycl/include/sycl/ext/oneapi/matrix/matrix-intel.hpp
There were incorrectly named and had incorrect operands.
See https://github.com/intel/llvm/pull/12497
=> [SYCL][Matrix] Fix checked matrix instructions

clang/lib/Basic/Targets.cpp, clang/lib/Basic/Targets/SPIR.h, clang/test/CodeGenCUDASPIRV/copy-aggregate-byval.cu, clang/test/CodeGenCUDASPIRV/kernel-argument.cu, clang/test/SemaSYCL/mangle-kernel.cpp, clang/test/SemaSYCL/msvc-fixes-x86.cpp, clang/test/SemaSYCL/msvc-fixes.cpp
This is text from OpenCL SPIR Spec 2.0 (https://registry.khronos.org/SPIR/specs/spir_spec-2.0.pdf)
The OpenCL size_t, ptrdiff_t,uintptr_t, intptr_t, atomic_size_t, atomic_ptrdiff_t, atomic_uintptr_t and atomic_intptr_t data types are mapped to LLVM i32 when the device address width is equal to 32 bits and to LLVM i64 when the device address width is equal 64 bits.
After some analysis though, I see that the windows os based customizations made for the SPIR target (https://github.com/intel/llvm/pull/325) are necessary for successful compilation on windows.
Also, they do not seem to be violating the spec. It's just that 'long' and 'long long' mean different things on windows and linux. On 64-bit linux, long type has 8 bytes, but on 64-bit windows, long type has 4 bytes.
Hence, I have …
=> [SPIR-V][Headers] Enable programs that include system headers on Windows for SPIRV32 and SPIRV64 targets

libdevice/cmake/modules/SYCLLibdevice.cmake
The root cause for disabling it on Windows was fixed in https://github.com/intel/llvm/commit/d0744751abe535c1470ca8833d5dd3b3d1a72c6b.
=> [SYCL][Libdevice] Build for spirv64 on Windows

.github/workflows/sycl-linux-precommit.yml
Allow to use default igc with label so that we may ignore regressions in
igc dev when needed.
=> [CI] Run Pre-commit E2E tests on Arc with igc-dev by default

.github/workflows/sycl-linux-run-tests.yml, devops/dependencies-igc-dev.json, devops/scripts/install_drivers.sh
We need some way to show different igc we used in the test.
Save the tag info into install folder and show it in the run.
(Also fix a bug in install driver and update the igc dev driver)
=> [CI] Show IGC TAG in run tests

sycl/include/sycl/properties/accessor_properties.hpp, sycl/source/detail/image_accessor_util.cpp, sycl/source/platform.cpp, sycl/source/sampler.cpp, sycl/test/include_deps/sycl_accessor.hpp.cpp, sycl/test/include_deps/sycl_detail_core.hpp.cpp
To reduce amount of the code required by `sycl/detail/core.hpp` and make more granular includes possible.
=> [SYCL] Remove `image.hpp` dependency from the `accessor.hpp`

sycl/source/detail/program_manager/program_manager.cpp, sycl/unittests/kernel-and-program/KernelBuildOptions.cpp
This is required to compile images on some platforms. I manually verified this fixes the issue in the repro. There will be a separate fix for AOT.
=> [SYCL] Always pass -ftranslate-legacy-memory-intrinsics to IGC for ESIMD images

llvm/lib/SYCLLowerIR/CMakeLists.txt, opencl/CMakeLists.txt, opencl/opencl-aot/CMakeLists.txt, sycl-fusion/CMakeLists.txt, sycl/CMakeLists.txt, sycl/test-e2e/CMakeLists.txt, xpti/CMakeLists.txt, xptifw/CMakeLists.txt
LLVM requires CMake 3.20 and up, which is specified in all the "built in" LLVM projects. This change bumps the DPCPP/SYCL specific projects to match that version.
=> [CMake] Bump required CMake version to 3.20.0

sycl/include/sycl/ext/oneapi/experimental/root_group.hpp, sycl/include/sycl/ext/oneapi/experimental/use_root_sync_prop.hpp, sycl/include/sycl/handler.hpp, sycl/include/syclcompat/id_query.hpp, sycl/include/syclcompat/memory.hpp, sycl/include/syclcompat/util.hpp, sycl/test-e2e/Assert/check_resource_leak.cpp, sycl/test-e2e/Regression/range-rounding-this-id.cpp, sycl/test/include_deps/sycl_detail_core.hpp.cpp
To avoid inclusion of the entire `root_group.hpp` in `handler.hpp`.
=> [SYCL] Move `use_root_sync_key` property into its own header

sycl/include/sycl/ext/intel/esimd/memory.hpp
I verified that this code is hit by tests and the current code is correct. The intrinsic itself is a bit weird.
=> [SYCL][ESIMD] Fix warning in legacy scatter

.github/workflows/sycl-linux-precommit-aws.yml
The update-check started to fail 2 months ago in https://github.com/intel/llvm/actions/runs/8461500755.
Last CUDA e2e success was https://github.com/intel/llvm/actions/runs/8460746056 2 months ago!!
So looks like a problem caused by #13173 again..
=> [CI] Fix status (update-check) permission for sycl cuda e2e

sycl/include/sycl/ext/intel/esimd/memory.hpp, sycl/test/esimd/media_block_load.cpp
This is legacy code, so let's not spend too much time on it. Just add an assert.
Note we don't see the same issue for media_block_store.
Closes: https://github.com/intel/llvm/issues/2635
=> [SYCL][ESIMD] Add power of 2 check for media_block_load

sycl/test-e2e/LLVMIntrinsicLowering/bitreverse.cpp
Now that the SPIR-V extension SPV_KHR_bit_instructions is not enabled by default, it is safe to test bitreverse with default options.
=>  [SYCL][E2E] Test bitreverse with default options

clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/sycl-spirv-ext.c
Only add SPV_INTEL_arbitrary_precision_integers for FPGA and emulation targets.
=> [Driver] Arbitrary precision integers are only for FPGA and emulation

sycl/source/detail/program_manager/program_manager.cpp, sycl/unittests/kernel-and-program/KernelBuildOptions.cpp
This reverts commit 4d5c25c5b57a4bb595caffc77a62fb1192e9110c.
This breaks Arc postcommit.
=> Revert "[SYCL] Always pass -ftranslate-legacy-memory-intrinsics to IGC for ESIMD images (#13662)"

llvm/utils/git/requirements.txt
Bumps idna to v3.7 to resolve identified security vulnerability in 3rd party dependency.
Refer to [idna's releases notes](https://github.com/kjd/idna/releases)
=> Bump idna from 3.7 in llvm/utils

sycl/plugins/native_cpu/CMakeLists.txt
OCK now contains all required passes for SYCL Native CPU inside a compiler_passes directory so use this directly. This resolves a lot issues, including verbose output, required tools and additional target name duplication.
=> [SYCL] [NATIVECPU] Fetch latest OCK using compiler_passes subdirectory for SYCL Native CPU

sycl/test-e2e/ESIMD/fma.cpp, sycl/test-e2e/ESIMD/fma_pvc.cpp
Windows driver is too old on some internal testing systems.
=> [SYCL][ESIMD] Add driver check for FMA tests on Windows

clang/lib/Driver/Driver.cpp, clang/lib/Driver/ToolChains/SYCL.cpp, clang/test/Driver/sycl-offload-intelfpga.cpp
The change that introduced the ability to use device libraries as IR files does not play well with the FPGA target.  The IR generated with spir64_fpga is different, causing issues as the bitcode based device libraries are built with spir64.
Update the compilation flow specific to FPGA to use the bundled device libraries as opposed to the bitcode files.
=> [Driver][SYCL][FPGA] Use bundled device libraries for FPGA targets

sycl-fusion/common/include/DynArray.h, sycl-fusion/common/include/Kernel.h, sycl-fusion/jit-compiler/include/KernelFusion.h
Replace `jit_compiler::DynString` uses with `sycl::detail::string`.
=> [SYCL][Fusion][NoSTL] Use `sycl::detail::string` in interface

sycl/test-e2e/Graph/Explicit/host_task_single.cpp, sycl/test-e2e/Graph/RecordReplay/host_task_single.cpp
`Inputs/host_task_single.cpp` has a call to `malloc_host` (https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/Graph/Inputs/host_task_single.cpp#L24) but the LIT requirement for USM host allocation support is missing.
=> [SYCL][Graph] Missing Lit test aspect

sycl/doc/extensions/experimental/sycl_ext_oneapi_graph.asciidoc
Clarify that C++ code in the command group function won’t be recorded during SYCL-Graph record & replay graph construction, and advise to move it to a host-task if that is required.
=> [SYCL][Graph] Add wording about arbitrary C++ code in CGFs

devops/dependencies-igc-dev.json
=> [GHA] Uplift Linux IGC Dev RT version to igc-dev-b456477

sycl/include/sycl/ext/intel/esimd/detail/memory_intrin.hpp, sycl/include/sycl/ext/intel/esimd/memory.hpp, sycl/include/sycl/ext/intel/experimental/esimd/detail/memory_intrin.hpp, sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp, sycl/test-e2e/ESIMD/named_barriers/exec_in_order.cpp, sycl/test-e2e/ESIMD/named_barriers/exec_in_order_branched.cpp, sycl/test-e2e/ESIMD/named_barriers/loop.cpp, sycl/test-e2e/ESIMD/named_barriers/loop_extended.cpp, sycl/test-e2e/ESIMD/named_barriers/multiple_wg.cpp, sycl/test-e2e/ESIMD/named_barriers/single_wg.cpp, sycl/test/esimd/genx_func_attr.cpp, sycl/test/esimd/nbarriers.cpp
The new intrinsic works in the drivers used in CI now, previously it didn't. The only change is adding the `Fence` parameter for named_barrier_signal.
I manually ran the tests on PVC.
=> [SYCL][ESIMD] Move named barrier functions to supported and use new intrinsic

sycl/test-e2e/XPTI/basic_event_collection_linux.cpp
If `CHECK-DAG`s don't cover all the sub-entries then the next entry cannot be `CHECK-NEXT` because the last `CHECK-DAG`ed sub-entry might not be the last emitted and it's possible there is an unchecked line inbetween it and the next entry.
=> [SYCL][E2E] Fix XPTI/basic_event_collection_linux.cpp

sycl/include/syclcompat/math.hpp
This PR makes the `max` and `min` functions inline. It resolves a linker issue that occurs when a library that includes the SYCLCompat headers is linked to an executable that also includes the SYCLCompat headers. In which case the linker found multiple definitions of these functions.
=> [SYCL][COMPAT] Add inline in max and min functions

sycl/test-e2e/bindless_images/read_norm_types.cpp
Fix the read_norm_types test failure by moving the calculation of work item ids inside dimension selecting constexprs. get_global_id(x) where x is greater than NDims in the nd_item causes the kernel to crash.
Remove XFAIL from the test.
Also, fixup the test as it was not sampling the whole image correctly or validating every element in the image.
Addresses issue: https://github.com/intel/llvm/issues/13281
=> [Bindless][E2E] Fix read_norm_types test failure

sycl/plugins/unified_runtime/CMakeLists.txt
pre-commit PR for https://github.com/oneapi-src/unified-runtime/pull/1591
=> [UR][L0] Disable Usage of Driver In order Lists by default

sycl/doc/design/PrivateAlloca.md, sycl/doc/index.rst
Add design document for the `sycl_ext_oneapi_private_alloca` extension documenting builtin aliases for the API functions, intrinsic used in codegen and SPIR-V translator handling of LLVM IR output by the compiler.
=> [SYCL][SCLA][Doc] Add `sycl_ext_oneapi_private_alloca` design document

sycl-fusion/common/CMakeLists.txt, sycl-fusion/jit-compiler/CMakeLists.txt, sycl-fusion/passes/CMakeLists.txt
Targets under `sycl-fusion` use `sycl::detail::string`, from the SYCL headers. Make sure these are available in `<build-dir>/include/` by adding dependency on the `sycl-headers` target.
=> [SYCL][Fusion][Build] Add `sycl-fusion` dependency on `sycl-headers`

sycl/test-e2e/Graph/Update/Explicit/whole_update_double_buffer.cpp, sycl/test-e2e/Graph/Update/RecordReplay/whole_update_double_buffer.cpp
https://github.com/intel/llvm/issues/13731
Disable whole graph update tests on CUDA, as they are flaky and failing on unrelated PRs, until such a time as the fail can be investigated and fixed.
=> [SYCL][Graph][CUDA] Disable failing update test.

clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/sycl-spirv-ext.c
This reverts commit 31f1f1c7535b5bd9b4c5874238064096b6d7ed4f.
Arbitrary precision integers are needed for targets besides FPGA and emulation because LLVM optimizations can generate non-standard integers (e.g. i24 by SROA).
=> Revert "[Driver] Arbitrary precision integers are only for FPGA  (#13379)"

sycl/unittests/helpers/PiImage.hpp
This value is the size of the data associated with the property, but for `PI_PROPERTY_TYPE_UINT32`, the data is always `nullptr` so this should be 0.
I suspect the initial patch meant to construct a vector of 4 values of 0, but that initializer list construct a vector of 2 values with 4 and 0 instead.
Should fix: https://github.com/intel/llvm/issues/13737
=> [SYCL] Fix assert unit test warning

devops/containers/ubuntu2204_build.Dockerfile
This partially reverts the changes made in https://github.com/intel/llvm/pull/13619 to use libstdc++-12-dev without gcc12.
This also seems to work fine to build dpc++ within the docker. But should come without the CI failures that might have been induced by the gcc uplift:
- https://github.com/intel/llvm/issues/13736
- https://github.com/intel/llvm/issues/13735
If the above issues were not caused by the gcc version uplift, then this patch should also reveal that.
=> [CI][HIP] Install libstdc++-12-dev without gcc12.

sycl/doc/extensions/experimental/sycl_ext_oneapi_bindless_images.asciidoc, sycl/include/sycl/ext/oneapi/bindless_images.hpp, sycl/test-e2e/bindless_images/cubemap/cubemap_sampled.cpp
Add HintT template parameter to the fetch_cubemap and sample_cubemap funcs in the bindless spec.
Add HintT template parameter and doxygen to the fetch_cubemap and sample_cubemap implementation.
Modify existing cubemap_sampled.cpp test to test the sampling with a user-defined type.
=> [Bindless][SYCL][Doc] Add HintT tparam to cubemap fetch and sample

sycl/include/sycl/ext/oneapi/experimental/graph.hpp, sycl/source/detail/graph_impl.cpp, sycl/test/abi/sycl_symbols_windows.dump
The symbols for templated methods `node::update_range()` and `node::update_nd_range()` were not having their symbols exported on Windows DLLs. Leading to link errors when running clang in the Graph E2E tests `Update/update_nd_range.cpp` and `Update/update_range.cpp`
Fixed by adding `__SYCL_EXPORT` to the templated specializations are recommended by the [__SYCL_EXPORT Macro documentation](https://intel.github.io/llvm-docs/developer/ABIPolicyGuide.html#sycl-export-macro)
Also removed duplicate forward declaration of `command_graph` from `graph.hpp`. It is already forward declared earlier on in the file on line 43.
=> [SYCL][Graph] Export missing graph node symbols

sycl/test-e2e/BFloat16/bfloat16_builtins.cpp, sycl/test-e2e/BFloat16/bfloat16_builtins.hpp
As stated in https://github.com/intel/llvm/issues/10010 the bfloat16 functions will be emulated on any device that does not support them natively, so tests that use these should not require the ext_oneapi_bfloat16_math_functions aspect. This commit removes this requirement and removes unnecessary lit lines from sycl/test-e2e/BFloat16/bfloat16_builtins.hpp.
Fixes https://github.com/intel/llvm/issues/10010
=> [SYCL][E2E] Removed ext_oneapi_bfloat16_math_functions aspect check

clang-tools-extra/clangd/test/sycl.test
We check line numbers in clangd sycl compilation test,
this is fragile, as everytime we have sycl header change,
we may have to update the test.
Use regex to match the line no instead to reduce the maintainece effort.
=> [NFC][SYCL] Avoid hardcoding line no in clangd test

sycl/test-e2e/Basic/kernel_info.cpp, sycl/test-e2e/GroupAlgorithm/root_group.cpp
They are passing on CPU in the nightlies.
Closes: https://github.com/intel/llvm/issues/13735
=> [SYCL][E2E] Fix two XPASSes on OCL CPU

devops/containers/ubuntu2204_build.Dockerfile
Switch to using apt packages instead of amdgpu-install.
This uses c++-11-dev libraries so hopefully avoids the problems caused by https://github.com/intel/llvm/pull/13752
=> [CI][HIP] Use apt to install rocm6.1.1

sycl/test/abi/layout_exception.cpp
In different version of glibc , we may get `struct` instead of `class`.
To avoid noisy failures, we can remove the keyword check here.
=> [NFC][SYCL] Relax the check in layout_exception

sycl/include/sycl/accessor.hpp, sycl/unittests/accessor/LocalAccessorDefaultCtor.cpp
Local accessors only have their memory allocated on device when a kernel starts executing. Any pointer that refers to local memory on host before kernel execution has begun is therefore invalid.
> This function may only be called from within a [SYCL kernel function](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sycl-kernel-function).
Table 78 in
https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_interface_for_local_accessors
=> [SYCL] Get pointer should not be called on host for local accessors

buildbot/configure.py, clang/lib/Driver/Driver.cpp, sycl/test/check_device_code/native_cpu/sycl-native-cpu-libclc.cpp
This PR makes it so we build the remangled variants for Native CPU libclc, and ensures that the driver selects it.
=> [SYCL][NATIVECPU][DRIVER] Select remangled libclc variant for Native CPU

clang/lib/Driver/ToolChains/SYCL.cpp, clang/lib/Driver/ToolChains/SYCL.h, clang/test/Driver/sycl-ftarget-register-alloc-mode.cpp
When compiling for AOT GPU, we passed along default device settings for PVC regardless of intended device.  Update this behavior to only pass along the PVC specific options to ocloc when the matching device (i.e. -device pvc) is also supplied.
The device can be specific with the typical device value (pvc) or via the -fsycl-targets=intel_gpu_pvc option setting or -device values that match with PVC that match a given version or HEX value.
The default values will continue to be passed along for JIT.
=> [Driver][SYCL] Do not pass along implied PVC specific values for AOT

sycl/test-e2e/Graph/Explicit/host_task2_multiple_roots.cpp, sycl/test-e2e/Graph/Explicit/host_task_multiple_roots.cpp, sycl/test-e2e/Graph/RecordReplay/host_task2_multiple_roots.cpp, sycl/test-e2e/Graph/RecordReplay/host_task_multiple_roots.cpp, sycl/test-e2e/USM/host_task.cpp
On a CUDA & Windows setup when shared USM is used there is an issue with using the allocations concurrently in both device commands and host-tasks. This is based on an underlying CUDA restriction: https://forums.developer.nvidia.com/t/cudamallocmanaged-clarification-needed/67611
> Applications running on Windows (whether in TCC or WDDM mode) or macOS will use the basic Unified Memory model as on pre-6.x architectures even when they are running on hardware with compute capability 6.x or higher.”
> “Simultaneous access to managed memory on devices of compute capability lower than 6.x is not possible,”
Therefore, simultaneous access to managed memory on Windows is not possible.
This appears in SYCL-Graph tests where the graph has multiple roots, allowing host-tasks branching from one root to …
=> [SYCL][Graph][CUDA] Skip unsupported Windows E2E tests

sycl/source/detail/device_impl.cpp
The merge of https://github.com/intel/llvm/pull/13389 has caused post-commit failures due to three unused variable warnings. 
This PR fixes that. One of these warnings also revealed a bug in my original PR.
=> [SYCL] Fix unused variable errors on post-commit for forward_progress extension

libdevice/cmake/modules/SYCLLibdevice.cmake
Add "-fPIC" for compiling intel math function host code.
=> [SYCL] Add -fPIC for intel math function host code

sycl/plugins/unified_runtime/CMakeLists.txt
pre-commit PR for https://github.com/oneapi-src/unified-runtime/pull/1611
=> [UR][L0] ensure a valid kernel handle for the device when reading max wg

sycl/test-e2e/Graph/Explicit/host_task_single.cpp, sycl/test-e2e/Graph/RecordReplay/host_task_single.cpp
After PR https://github.com/intel/llvm/pull/13685 merged to re-enabling running graph E2E tests on Windows with immediate command lists, a non-deterministic leak has appeared in post-commit CI for a different PR https://github.com/intel/llvm/actions/runs/9097140304/job/25008463548
To keep CI green, don't run the test on Windows with immediate command lists until the leak can be investigated and fixed.
```quote
env SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=1 env UR_L0_LEAKS_DEBUG=1 SYCL_ENABLE_DEFAULT_CONTEXTS=0 env ONEAPI_DEVICE_SELECTOR=level_zero:gpu  D:\github\actions-runner\_work\llvm\llvm\build-e2e\Graph\Explicit\Output\host_task_single.cpp.tmp.out 2>&1 | d:\github\actions-runner\_work\llvm\llvm\install\bin\filecheck.exe …
```
=> [SYCL][Graph] Disable Windows test with L0 leak

sycl/unittests/Extensions/CommandGraph/Update.cpp
These tests were originally intended to be enabled after checks for node and edge ordering were added to the whole graph update implementation. However, after further investigation, the team concluded that such checks are not possible. As a consequence, these tests no longer make sense.
=> [SYCL][Graph] Delete tests for wrong node/edge order

sycl/test-e2e/Matrix/SG32/get_coord_int8_matB.cpp, sycl/test-e2e/Matrix/get_coord_int8_matB.cpp, sycl/test-e2e/Matrix/joint_matrix_annotated_ptr.cpp
Disabled xfail in following tests:
SYCL :: Matrix/SG32/get_coord_int8_matB.cpp
SYCL :: Matrix/get_coord_int8_matB.cpp
SYCL :: Matrix/joint_matrix_annotated_ptr.cpp
=> [LLVM][SYCL][E2E] Disable xfail for passing tests

sycl/doc/extensions/experimental/sycl_ext_matrix/sycl_ext_oneapi_matrix.asciidoc
This is a clarification to match all the matrix spec that `Rows` and `Cols` are in the range of the logical dimensions, independently from the memory layout.
For instance, in the `ext_intel_packed` (or VNNI) layout case, prefetch will look like:
`joint_matrix_prefetch<TK, TN>(sg, B + sg_starty / SG_SZ * TN * vnniFactor,
N * vnniFactor, layout::ext_intel_packed,
syclex::properties{syclex::prefetch_hint_L1});
`
instead of 
`joint_matrix_prefetch<TK / vnniFactor, TN * vnniFactor>(
sg, B + sg_starty / SG_SZ * TN * vnniFactor, N * vnniFactor, layout::ext_intel_packed,
syclex::properties{syclex::prefetch_hint_L1});
`
=> [SYCL][Joint matrix] clarify the range of the prefetch templated arguments

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/math.hpp, sycl/test-e2e/syclcompat/math/math_funnelshift.cpp
Adds `funnelshift_*` math functions to SYCLcompat, and corresponding tests.
=> [SYCL][COMPAT] Add funnelshift APIs and corresponding tests

sycl/include/sycl/ext/oneapi/experimental/group_load_store.hpp, sycl/test-e2e/GroupAlgorithm/load_store/basic.cpp, sycl/test-e2e/GroupAlgorithm/load_store/conversions_load.cpp, sycl/test-e2e/GroupAlgorithm/load_store/conversions_store.cpp, sycl/test-e2e/GroupAlgorithm/load_store/odd_sized_type.cpp, sycl/test-e2e/GroupAlgorithm/load_store/odd_wg_size.cpp, sycl/test-e2e/GroupAlgorithm/load_store/partial_sg.cpp
Continuation of changes started in https://github.com/intel/llvm/pull/12890.
=> [SYCL] Use `sycl/detail/core.hpp` in `test-e2e/GroupAlgorithm/load_store/*`

sycl/include/sycl/detail/core.hpp, sycl/include/sycl/sycl.hpp
Non-functional because it has been there transitively from `sycl/ext/oneapi/sub_group_mask.hpp`. Make that inclusion explicit so that it would remain there in future even if we will decouple that extension out of "core".
=> [NFC][SYCL] Include `sycl/feature_test.hpp` in `sycl/detail/core.hpp`

sycl/include/sycl/ext/oneapi/experimental/user_defined_reductions.hpp, sycl/test-e2e/UserDefinedReductions/user_defined_reductions.cpp, sycl/test-e2e/UserDefinedReductions/user_defined_reductions_wg_size_larger_than_data_size.cpp
Continuation of changes started in https://github.com/intel/llvm/pull/12890.
=> [SYCL] Use `sycl/detail/core.hpp` in `test-e2e/UserDefinedReductions/*`

libclc/CMakeLists.txt
Customs dirs path was [asserting on the existence of `llvm-spirv` and `libclc-remangler`](https://github.com/jchlanda/llvm/blob/jakub/libclc_customs_fix/libclc/CMakeLists.txt#L104), however those tools have not been set up.
Also only search for llvm-spirv if it has not been set in the custom tools path.
=> [LIBCLC] Correctly set up llvm-spirv and libclc-remangler

sycl/source/detail/graph_impl.hpp
This reverts commit c02f915d42ac9bd1a3c4f2215d703b49b3a2173d since this Coverity issue is a false positive. `EventImpl` is always set when we pass it in the runtime, but the previous change suggests it might be null. The Coverity hit should be ignored instead.
=> Revert "Fix Coverity dereference before null check issue (#13456)"

sycl/doc/extensions/experimental/sycl_ext_oneapi_bindless_images.asciidoc, sycl/include/sycl/ext/oneapi/bindless_images_descriptor.hpp, sycl/include/sycl/ext/oneapi/bindless_images_mem_handle.hpp, sycl/test-e2e/bindless_images/read_sampled.cpp
1. Add default constructor for `image_descriptor` on the spec side. The implementation already had it, but it was not initializing values, this has been fixed.
2. Rename `image_mem_handle::handle_type` to `image_mem_handle::raw_handle_type` to follow the Bindless Images spec.
Added basic tests for both.
=> [SYCL][Bindless] Default ctr for image_descriptor

sycl/test-e2e/Regression/compile_on_win_with_mdd.cpp
Test is e2e but was put to sycl/test/ directory. Move it to the e2e test directory.
=> [SYCL][E2E] Move e2e test to proper directory

sycl/source/detail/device_impl.cpp, sycl/source/detail/device_info.hpp, sycl/unittests/Extensions/CompositeDevice.cpp
The sycl_ext_oneapi_composite_device extension specifies that the composite_devices query should throw if a device returns false for device::has with ext_oneapi_is_composite. However, the current implementation simply returns an empty device list if the backend of the device is not L0. This commit fixes this discrepancy.
=> [SYCL] Fix exception thrown for composite_devices query

sycl/doc/extensions/experimental/sycl_ext_oneapi_annotated_arg.asciidoc, sycl/doc/extensions/experimental/sycl_ext_oneapi_annotated_ptr.asciidoc, sycl/doc/extensions/proposed/sycl_ext_oneapi_usm_malloc_properties.asciidoc, sycl/include/sycl/ext/oneapi/experimental/annotated_arg/annotated_arg.hpp, sycl/include/sycl/ext/oneapi/experimental/annotated_ptr/annotated_ptr.hpp, sycl/include/sycl/ext/oneapi/experimental/annotated_usm/alloc_base.hpp, sycl/include/sycl/ext/oneapi/experimental/annotated_usm/alloc_device.hpp, sycl/include/sycl/ext/oneapi/experimental/annotated_usm/alloc_host.hpp, sycl/include/sycl/ext/oneapi/experimental/annotated_usm/alloc_shared.hpp, sycl/include/sycl/ext/oneapi/properties/properties.hpp, sycl/test/extensions/properties/mock_compile_time_properties.hpp, sycl/test/extensions/properties/properties_ctor_constexpr.cpp, sycl/test/extensions/properties/properties_ctor_negative.cpp
The [compile-time properties extension](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/experimental/sycl_ext_oneapi_properties.asciidoc) specifies that the variadic ctor has the following behavior:
>Available only when each argument in props is an object of a property
value. Construct a property list with zero or more property values. This constructor can accept both runtime and compile-time constant property values. Each property in the property list (as determined by PropertyValuesT) that is not default constructable must have an object provided in props.
However, the current implementation does not adhere to these requirements. This commit makes the following changes to adhere to the required behavior:
* The ctor is now SFINAE'd out when arguments are non-property types.
* …
=> [SYCL][Docs] Fix variadic properties ctor

sycl/source/detail/queue_impl.hpp, sycl/unittests/scheduler/InOrderQueueSyncCheck.cpp
The `finalizeHandler` function on queue_impl has a `CGType` argument, but the information in this argument could be queried directly from the handler instead. This commit removes the argument and makes the member function call `handler::getType()` instead.
=> [SYCL][NFCI] Remove unnecessary CG type argument in finalizeHandler

sycl/test-e2e/DeviceLib/math_fp64_windows_test.cpp, sycl/test-e2e/DeviceLib/math_windows_test.cpp, sycl/test-e2e/QueueFlushing/queue_flushing.cpp, sycl/test-e2e/README.md, sycl/test-e2e/Regression/compile_on_win_with_mdd.cpp, sycl/test-e2e/SubGroup/generic_reduce.cpp, sycl/test-e2e/no_sycl_hpp_in_e2e_tests.cpp
Fine-grained includes should be used instead for the benefits of
compile-time. So far, the feature is still internal, customer code
should continue using standard header files only.
We can consider adding a Nightly workflow running E2E tests with extra
compilation flag `-include sycl/sycl.hpp` if people think that would be
important to have. I personally think that any potential discrepancies
between full `sycl.hpp` and individual includes can be caught in
compile-time and it should be enough to have tests in `sycl/test`.
=> [SYCL] Prohibit usage of `<sycl/sycl.hpp>` in E2E tests

sycl/test-e2e/Matrix/joint_matrix_bfloat16_packedB.cpp, sycl/test-e2e/Matrix/joint_matrix_rowmajorA_rowmajorB.cpp, sycl/test-e2e/Matrix/joint_matrix_rowmajorA_rowmajorB_impl.hpp
This change is partially addressing requirement to enable 1d block load testing (IGC_JointMatrixLoadStoreOpt=2) for only big combinations 32x64x16, 1x64x16, 16x16x16.
This environment variable was added to as minimum tests as possible, while keeping the coverage of big combinations to maximum.
This environment variable was not added to Matrix/element_wise_ops.cpp yet, because, IGC compiler needs to be fixed to pass this test with IGC_JointMatrixLoadStoreOpt=2
=> [SYCL Joint Matrix][E2E] Add 1d vector load/store tests for big combinations

sycl/test-e2e/LLVMIntrinsicLowering/bitreverse.cpp, sycl/test-e2e/LLVMIntrinsicLowering/sub_byte_bitreverse.cpp
Ensure that lowering of llvm.bitreverse.i2/i4 by llvm-spirv is functionally correct.
=> [SYCL][E2E] Ensure lowering of llvm.bitreverse for 2/4-bit scalars is functionally correct

.github/workflows/sycl-issues-ping-assignee.yml
There is a set of "backlog" issues we'd like to handle. The new process is to confirm the issue and add the `confirmed` label, so the issue will be automatically copied to our system and then assigned to the appropriate team.
Sometimes the issue has an assignee but doesn't get any updates for a long time. We decided that in this case we'd like to occasionally ping the assignee to progress the work on this issue. There is also a big bunch of old issues with an assignee and no updates.
=> [CI] New workflow to ping issue assignee

clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/sycl-offload-new-driver.c
This change is made to align the list of SYCL device library files used in the new offload model with that of the old offload model. A gap in implementation was identified and this PR fixes this gap.
=> [SYCL][Device libs][New offload] Add missing fallback SYCL device library files

sycl/test-e2e/Plugin/level_zero_ext_intel_cslice.cpp, sycl/test-e2e/Plugin/level_zero_ext_intel_queue_index.cpp, sycl/test-e2e/Plugin/level_zero_sub_sub_device.cpp, sycl/test-e2e/lit.cfg.py
PVC 1T systems have some issues with partitioning.  Disabling these tests on those systems while awaiting driver fixes.
=> [SYCL] Screen tests on PVC-1T systems

sycl/test-e2e/LLVMIntrinsicLowering/sub_byte_bitreverse.cpp
https://github.com/intel/llvm/pull/13875 made sycl/sycl.hpp include in E2E tests prohibited. However,
LLVMIntrinsicLowering/sub_byte_bitreverse.cpp snuck in without this check. This commit fixes the includes in that test.
=> [SYCL][E2E] Fix sycl/sycl.hpp use in sub_byte_bitreverse.hpp

sycl/test-e2e/syclcompat/kernel/Inputs/kernel_function.cpp
Avoid conflicts of Windows headers with std::max using `#define NOMINMAX`
The patch fixes the build error seen in [kernel_win.cpp](https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/syclcompat/kernel/kernel_win.cpp)
=> [TEST-E2E] Avoid conflicts of Windows headers with std::max.

sycl/test-e2e/Basic/bit_cast/bit_cast.cpp
Address [test-e2e/Basic/bit_cast/bit_cast.cpp](https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/Basic/bit_cast/bit_cast.cpp) build's missing triple on Windows.
=> [TEST-E2E] Address test build's missing triple on Windows. 

sycl/source/detail/scheduler/commands.cpp, sycl/source/handler.cpp, sycl/unittests/scheduler/HostTaskAndBarrier.cpp
Fixes two things:
1) Prevent submitting empty wait list to piEVentsWait from host task execution handler. Backend treats empty wait list as not valid and reports error. If barrier with wait list is submitted with empty list or with host tasks as dependencies - it (barrier) is not submitted to backend and has null pi handle. Null pi handle means that it will be filtered out from wait list.
2) host tasks in wait list could not be handled by backend so we should add them as dependencies to enable dependencies handling by scheduler.
=> [SYCL] Fix barrier with wait list handling

sycl/test/check_device_code/atomic_fence.cpp, sycl/test/check_device_code/device_global_ptr_use.cpp, sycl/test/check_device_code/fpga_datapath_constructor.cpp, sycl/test/check_device_code/fpga_datapath_global.cpp, sycl/test/check_device_code/fpga_datapath_local.cpp, sycl/test/check_device_code/fpga_mem_constructor.cpp, sycl/test/check_device_code/fpga_mem_global.cpp, sycl/test/check_device_code/fpga_mem_local.cpp, sycl/test/check_device_code/task_sequence_intel_no_explicit_get.cpp, sycl/test/check_device_code/usm_pointers.cpp
Changed some of the simpler test cases to use SYCL_EXTERNAL functions instead of submitting to a queue.
=> [SYCL] Change some check_device_code tests to use SYCL_EXTERNAL

sycl/include/sycl/buffer.hpp
Right now it's a no-op/NFC as it is still included transitively somewhere, but in my local prototype workspace this `remove_pointer_t` is latest use of it there. I think it's OK to upload this PR right now to decrease number of out-of-tree changes in my experimental branch.
=> [SYCL] Don't include `type_traits.hpp` explicitly from `buffer.hpp`

sycl/include/sycl/detail/common.hpp, sycl/source/detail/device_binary_image.hpp, sycl/source/detail/plugin.hpp, sycl/test/include_deps/sycl_buffer.hpp.cpp
The ones being removed had no documentation nor known uses.
=> [SYCL] Remove `*SUPPRESS*` macros and move some others to `source/`

clang/lib/CodeGen/CGBuiltin.cpp, clang/test/CodeGenSYCL/Inputs/sycl.hpp, clang/test/CodeGenSYCL/builtin-alloca.cpp, clang/test/SemaSYCL/Inputs/sycl.hpp, sycl/test/extensions/private_alloca.cpp
As pointed out in
https://github.com/intel/llvm/pull/13514#discussion_r1595643260, `sycl::multi_ptr` pointer member is always decorated in DPC++. Drop unneeeded `addrspacecast` to the generic address space when `[aligned_]private_alloca` returns a `raw_private_ptr`.
=> [SYCL][SCLA] Drop unneeded `addrspacecast` instruction

clang/test/Driver/sycl-offload-intelfpga.cpp
The sycl-offload-intelfpga.cpp test was recently modified to check that the proper device library objects are picked up.  The test was not using the local testing sysroot to pick up the files, causing problems when the actual libraries are not built with the compiler before the test is run.
=> [NFC][SYCL] Fix test to properly pick up device libraries

clang/lib/Driver/Driver.cpp, clang/test/Driver/sycl-offload-new-driver.c
When using the new offloading model, the values being passed to -fsycl-targets were not fully being realized when attempting to target specific architectures.  Uses of -fsycl-targets=intel_gpu_* were not properly setting the arch values that are used down the line (namely the packaging step).
Improve this situation by populating the assocated architecture mappings with what is seen when parsing the -fsycl-targets option.  This applies to all intel_gpu, nvidia_gpu and amd_gpu targets.
=> [Driver][SYCL][NewOffloadModel] Improve arch association for device

clang/lib/Sema/SemaSYCL.cpp, clang/test/CodeGenSYCL/Inputs/sycl.hpp, sycl/include/sycl/ext/oneapi/experimental/builtins.hpp
- Addresses a build error seen when using `printf` for CUDA backend on Windows.
- The mentioned build error can be seen in [test-e2e/Basic/built-ins.cpp](https://github.com/mmoadeli/llvm/blob/sycl/sycl/test-e2e/Basic/built-ins.cpp)
- Remove dead code as `printf` in SYCL cuda /amd device code   calls `__builtin_printf`
=> [SYCL][CUDA] Fix support of `printf` for CUDA backend on Windows.

sycl/source/detail/device_info.hpp, sycl/unittests/Extensions/CompositeDevice.cpp
This commit allows the backend to return an empty result or an unsupported-feature error when being queried about component devices.
=> [SYCL] Allow empty and unsupported case for component_devices

sycl/test-e2e/Basic/fpga_tests/fpga_pipes_mixed_usage.cpp
The test is marked as `XFAIL` until #13887 gets fixed in OCL FPGA EMU.
Signed-off-by: Yilong Guo <yilong.guo@intel.com>
=> [E2E Test] Add regression test for #13887

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/kernel.hpp
Updated classes in  `sycl/include/syclcompat/kernel.hpp`  to have constexpr constructors and align to SYCLomatic's latest `kernel.hpp` header.
=> [SYCL][COMPAT] kernel_function and kernel_library constexpr constructors

llvm/lib/Transforms/Utils/Local.cpp, sycl/test-e2e/ESIMD/regression/bitreverse.cpp, sycl/test-e2e/Regression/bitreverse.cpp
This is https://github.com/intel/llvm/pull/13634 from Slava rebased and with a minor target check change.
Co-authored-by: Klochkov, Vyacheslav N <vyacheslav.n.klochkov@intel.com>
=> [SYCL] Disable bitreverse recognition for non-std widths

sycl/plugins/unified_runtime/CMakeLists.txt
This caused issues in local builds because if the specific adapter source is reset to the main UR checkout, the cache variable pointing to the adapter specific checkout would stick around, and the adapter would still be built from that older checkout which would eventually caused build failures.
=> [SYCL][UR] Fix fetch adapter source cache variable

sycl/plugins/unified_runtime/CMakeLists.txt
pre-commit PR for https://github.com/oneapi-src/unified-runtime/pull/1667
=> [UR][L0] Fix Multi Device Event Cache for shared Root Device

libclc/generic/libspirv/atomic/atomic_add.cl, libclc/generic/libspirv/atomic/atomic_and.cl, libclc/generic/libspirv/atomic/atomic_cmpxchg.cl, libclc/generic/libspirv/atomic/atomic_max.cl, libclc/generic/libspirv/atomic/atomic_min.cl, libclc/generic/libspirv/atomic/atomic_or.cl, libclc/generic/libspirv/atomic/atomic_sub.cl, libclc/generic/libspirv/atomic/atomic_xchg.cl, libclc/generic/libspirv/atomic/atomic_xor.cl, sycl/include/sycl/ext/intel/esimd/math.hpp, sycl/test-e2e/ESIMD/ext_math.cpp
Following up to https://github.com/intel/llvm/pull/13428, this PR implements the overloads for the generic AS that are missing in the `generic` libclc target.
=> Implement missing overloads for generic AS in generic target

libdevice/cmath_wrapper.cpp, libdevice/cmath_wrapper_fp64.cpp, libdevice/device_math.h, libdevice/fallback-cmath-fp64.cpp, libdevice/fallback-cmath.cpp, sycl/test-e2e/DeviceLib/cmath_fp64_test.cpp, sycl/test-e2e/DeviceLib/cmath_test.cpp
Add support for multiple missing math ops;
- ceilf
- copysignf
- cospif
- fmaxf
- fminf
=> [SYCL] Add support for multiple missing math ops

sycl/test-e2e/Graph/Explicit/basic_usm.cpp, sycl/test-e2e/Graph/Explicit/basic_usm_host.cpp, sycl/test-e2e/Graph/Explicit/basic_usm_mixed.cpp, sycl/test-e2e/Graph/Explicit/basic_usm_shared.cpp, sycl/test-e2e/Graph/Explicit/host_task2_multiple_roots.cpp, sycl/test-e2e/Graph/Explicit/host_task_multiple_deps.cpp, sycl/test-e2e/Graph/Explicit/host_task_multiple_roots.cpp, sycl/test-e2e/Graph/Explicit/multiple_exec_graphs.cpp, sycl/test-e2e/Graph/Explicit/queue_constructor_usm.cpp, sycl/test-e2e/Graph/Explicit/queue_shortcuts.cpp, sycl/test-e2e/Graph/Explicit/sub_graph.cpp, sycl/test-e2e/Graph/RecordReplay/after_use.cpp, sycl/test-e2e/Graph/RecordReplay/barrier_with_work.cpp, sycl/test-e2e/Graph/RecordReplay/basic_usm.cpp, sycl/test-e2e/Graph/RecordReplay/basic_usm_host.cpp, sycl/test-e2e/Graph/RecordReplay/basic_usm_mixed.cpp, sycl/test-e2e/Graph/RecordReplay/basic_usm_shared.cpp, sycl/test-e2e/Graph/RecordReplay/host_task2_multiple_roots.cpp, sycl/test-e2e/Graph/RecordReplay/host_task_multiple_deps.cpp, sycl/test-e2e/Graph/RecordReplay/host_task_multiple_roots.cpp, sycl/test-e2e/Graph/RecordReplay/multiple_exec_graphs.cpp, sycl/test-e2e/Graph/RecordReplay/queue_constructor_usm.cpp, sycl/test-e2e/Graph/RecordReplay/queue_shortcuts.cpp, sycl/test-e2e/Graph/RecordReplay/sub_graph.cpp
Several of the SYCL-Graph E2E tests occasionally fail in CI on Windows for unrelated PRs. We can replicate this locally with a lot of effort, but have not yet been able to diagnose the root cause of find a fix. Disable all the tests which have been documented as sporadically failing on Windows at any point.
See related GitHub Issues:
* https://github.com/intel/llvm/issues/13951
* https://github.com/intel/llvm/issues/12941
* https://github.com/intel/llvm/issues/11852
=> [SYCL][Graph] Disable flaky windows tests

sycl/test-e2e/AbiNeutral/device-info.cpp
SYCL_ENABLE_DEFAULT_CONTEXTS=1 is needed to run on Windows.
=> [SYCL][E2E] Add an env var to run on Windows

sycl/test-e2e/ProfilingTag/common.hpp
An include of sycl/sycl.hpp snuck in with https://github.com/intel/llvm/pull/12838. This commit fixes this.
=> [SYCL][E2E] Fix include of sycl/sycl.hpp in profiling tag tests

sycl/doc/syclcompat/README.md
Reduce line length to 80 characters.
=> [SYCL][Doc] Fix typos and formating of SYCLCompat README

sycl/test-e2e/ProfilingTag/profiling_queue.cpp
Due to a problem in the reported timings of the fallback implementation on the FPGA emulator, the profiling_queue.hpp test fails. This disables the test for those devices.
=> [SYCL][E2E] Disable profiling_queue.hpp for FPGA

clang/lib/CodeGen/CGBuiltin.cpp, sycl/test-e2e/PrivateAlloca/ValidUsage/Inputs/private_alloca_test.hpp, sycl/test-e2e/PrivateAlloca/ValidUsage/private_alloca_bool_size.cpp, sycl/test-e2e/PrivateAlloca/ValidUsage/private_alloca_decorated.cpp, sycl/test-e2e/PrivateAlloca/ValidUsage/private_alloca_legacy.cpp, sycl/test-e2e/PrivateAlloca/ValidUsage/private_alloca_multiple.cpp, sycl/test-e2e/PrivateAlloca/ValidUsage/private_alloca_raw.cpp
- `DecorateAddressIndex` is not used. Drop to avoid warnings.
- Modify `test` function implementing tests so it does not read from stdin, but receive its parameter as an argument and read these arguments from stdin in `main`.
- Manually inline `allocate` function as this usage of `[aligned_]private_alloca` is undefined behavior
=> [SYCL][SCLA][NFC] Fix warning and potential test errors

sycl/source/detail/device_filter.cpp, sycl/test-e2e/OneapiDeviceSelector/discard_filters.cpp
Currently, ONEAPI_DEVICE_SELECTOR incorrectly parses '!', used for discard filters.
=> [SYCL] Fix ONEAPI_DEVICE_SELECTOR handling of discard filters.

.github/workflows/sycl-detect-changes.yml, .github/workflows/sycl-linux-precommit.yml
Even the Windows detect changes job requires a Linux build machine today, and that can cause a bottleneck.
We may still get bottlenecked in the Linux tree because of the low number of Linux build systems, but there are more Windows build systems, so that tree might see a speedup.
We can hit a similar thing for the determine arc tests job, so update that too.
Also remove a comment that seems out of date.
=> [CI] Allow detect changes and detect Arc tests to run on more Linux machines

sycl/test-e2e/Basic/buffer/buffer_create.cpp
The buffer_create test expects to know whether a device is integrated based on a deprecated device info query. This was changed in good faith to a seemingly equivalent aspect, but that aspect is not an exact equivalent when it comes to checking for integrated devices. This commit changes the test to instead use L0 interop to get information about the device type directly from the L0 interfaces.
=> [SYCL][E2E] Fix buffer_create by using L0 interop

sycl-fusion/common/include/View.h, sycl/source/detail/jit_compiler.cpp
Make `View` constructor more generic, e.g., accepting `std::array` and `std::initializer_list` as inputs. Also drop deduction guide. These changes try to address compilation error found in https://github.com/intel/llvm/actions/runs/9315099170/job/25640579916.
Making constructors implicit goes in line with `std::span` and `llvm::ArrayRef`.
=> [SYCL][Fusion][NoSTL] Update `jit_compiler::View` constructor and drop deduction guide

libdevice/msvc_math.cpp
- Enable support of msvc math functions for NVPTX target.
- Adding the support fix the build errors seen in [cmath_test.cpp](https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/DeviceLib/cmath_test.cpp) and [math_test.cpp](https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/DeviceLib/math_test.cpp) tests.
=> [SYCL][CUDA] Enable support of msvc math functions for nvptx target.

sycl/source/detail/device_info.hpp, sycl/unittests/Extensions/CompositeDevice.cpp
As mentioned in https://github.com/oneapi-src/unified-runtime/pull/1678#discussion_r1620274932 the error code returned for unsupported info queries is `UR_RESULT_ERROR_UNSUPPORTED_ENUMERATION`, which maps to `PI_ERROR_INVALID_VALUE`, so the component devices query should check this error code instead of `PI_ERROR_UNSUPPORTED_FEATURE`.
=> [SYCL] Change expected unsupported error for device info query

sycl/test-e2e/DeviceLib/string_test.cpp
Both `accelerator` and `cpu` are unsupported due to the same reason, there is no unique FPGA-related bug here. 
Closes #12683.
=> [SYCL][E2E] Merge `UNSUPPORTED` directives in `DeviceLib/string_test.cpp`

llvm/lib/SYCLLowerIR/ESIMD/LowerESIMD.cpp, llvm/test/SYCLLowerIR/ESIMD/lower_llvm_intrin.ll, sycl/include/sycl/ext/intel/esimd/detail/math_intrin.hpp, sycl/include/sycl/ext/intel/esimd/math.hpp, sycl/include/sycl/ext/intel/experimental/esimd/detail/math_intrin.hpp, sycl/include/sycl/ext/intel/experimental/esimd/math.hpp, sycl/test-e2e/ESIMD/clz_ctz.cpp, sycl/test-e2e/ESIMD/popcount.cpp
This PR has three types of changes:
1) Move some math operations to SPIR-V intrinsics. They are:
```
__esimd_abs to __spirv_ocl_fabs and __spirv_ocl_s_abs
__esimd_fmin to __spirv_ocl_fmin
__esimd_fmadd to __spirv_ocl_fma
```
2) Support three new functions using SPIR-V intrinsics
```
popcount
clz
ctz
```
There are some more functions I will move to SPIR-V intrinsincs once driver issues are fixed.
3) Remove code that breaks up the fmuladd intrinsic generated by the FE as the drivers we support can handle it now.
=> [SYCL][ESIMD] Move a few math operations to SPIR-V intrinsics and support new functions

llvm/utils/git/requirements.txt
Bumps requests (pip) from 2.32.0 to resolve identified security vulnerability in 3rd party dependency.
When making requests through a Requests Session, if the first request is made with verify=False to disable cert verification, all subsequent requests to the same origin will continue to ignore cert verification regardless of changes to the value of verify. This behavior will continue for the lifecycle of the connection in the connection pool.
Upgrading will resolve this issue.
Refer to https://github.com/psf/requests/pull/6655
=> Bump requests (pip) from 2.32.0 in llvm/utils/git/requirements.txt

clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/sycl-offload-new-driver.c
Additional options can be passed along to the clang-offload-wrapper via -Xsycl-target-backend and -Xsycl-target-link.  Hook up the ability to pass the values from these options along to the clang-linker-wrapper.
=> [Driver][SYCL][NewOffloadModel] Hook up options for the offload-wrapper

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/device.hpp, sycl/test-e2e/syclcompat/device/device.cpp
-  `_image1d_max`, `_image2d_max`, and `_image3d_max` member attributes
- Updates the `_max_nd_range_size` implementation conditionally set the value based on the availability of SYCL_EXT_ONEAPI_MAX_WORK_GROUP_QUERY.
- Updated documentation accordingly.
Minor fix:
- Added missing new line to the output from `test_not_enough_devices`.
=> [SYCL][COMPAT] Add Image Max dims to device_info. Updated Max ND Range Size

libclc/amdgcn-amdhsa/libspirv/atomic/atomic_add.cl, llvm/lib/Target/AMDGPU/AMDGPUOclcReflect.cpp, sycl/test/check_device_code/hip/atomic/amdgpu_unsafe_atomics.cpp
Atomic fadd can fail for malloc_shared allocations if the PCIe bus doesn't support PCIe atomics. This makes the default CAS atomics, so that atomics are guaranteed to work. Fast, unsafe atomics can be used if the flag -mllvm --amdgpu-oclc-unsafe-fp-atomics=true is used.
Testing is updated to test this new option.
Ping @konradkusiak97
=> [AMDGPU][SYCL] Make unsafe atomic fadd opt in

sycl/plugins/unified_runtime/CMakeLists.txt
Windows has an archaic 260 char path length limit by default. This patch replaces `unified-runtime` with `ur` prefix used for `FetchContent` in the `fetch_adapter_source()` helper function. This aims to mitigate creation of paths which exceed the 260 char default limit, especially when executed in a Jenkins runner.
=> [UR] Shorten FetchContent build paths

sycl/test-e2e/lit.cfg.py
This PR helps to avoid hardcoded path symbols and let OS dependent tools to work with paths.
Original version produces `path/....\lib\xptifw.lib` which causes skip of library linkage on windows.
`os.path.normpath` is the main change here that helps to handle path separators properly.
=> [SYCL] Fix XPTI FW lib path for test-e2e on Win

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/device.hpp, sycl/test-e2e/syclcompat/device/device.cpp
This PR migrates changes to `get_version`, `get_major_version` and `get_minor_version`, adds new free function equivalents which accept a `sycl::device` argument, and adds relevant tests and documentation.
=> [SYCL][COMPAT] Migrate bug fixes & refactor of get_*version APIs

sycl/plugins/unified_runtime/CMakeLists.txt
Bump UR L0 commit to https://github.com/oneapi-src/unified-runtime/pull/1694 so that the SYCL device aspect for supporting update in graphs is correctly reported for L0 devices. Currently, support can be incorrectly reported.
=> [SYCL][Graph][L0] Correctly report when device supports update

sycl/source/detail/graph_impl.cpp
Running the `Graph/Update` E2E tests on Level Zero with `UR_L0_LEAKS_DEBUG=1` shows that we are leaking a PI kernel and module.
On investigation this was because we are retaining these objects in `getOrCreateKernel()` but not releasing them. Added release calls similar to how it is done in [enqueueImpCommandBufferKernel](https://github.com/intel/llvm/blob/b49303c7e13ca0a69454eaaaeb8c3d094916218d/sycl/source/detail/scheduler/commands.cpp#L2550) by the scheduler
=> [SYCL][Graph] Fix PI Kernel leak in graph update

devops/containers/ubuntu2204_build.Dockerfile
This upgrades the docker to use the cuda 12.5 image.
I've ran the test-e2e locally using cuda 12.5 and all is well. cuda 12.5 also fixed an issue introduced by the cuda 12.4 driver: see https://github.com/intel/llvm/pull/13661#issuecomment-2140088722
=> [CI][CUDA] Uplift docker to use cuda 12.5 image.

clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/sycl-lto.cpp, libdevice/cmake/modules/SYCLLibdevice.cmake
This is the first change in my work on thinLTO for SYCL.
=> [SYCL] Allow specifying -foffload-lto with the new offload driver and build libdevice with thinLTO

devops/dependencies-igc-dev.json
=> [GHA] Uplift Linux IGC Dev RT version to igc-dev-8b999ec

sycl/test-e2e/ProfilingTag/profiling_queue.cpp
See https://github.com/intel/llvm/issues/14053
=> [SYCL][E2E] Disable flaky profiling_queue.cpp test on CUDA

sycl/include/sycl/reduction.hpp, sycl/include/sycl/vector.hpp, sycl/include/sycl/vector_preview.hpp, sycl/test/esimd/simd.cpp
This is required by f46d1463b [clang] require template arg list after template kw (#80801).
=> [SYCL] Remove redundant template keywords.

sycl/test-e2e/Matrix/joint_matrix_apply_cuda.hpp
This change avoids the ambiguity between the deprecated `sycl::ext::oneapi::sub_group` and `sycl::sub_group` when both namespaces are used. This fixes a failure on windows for cuda.
=> [test-e2e][cuda] Fully qualify `sycl::sub_group` to avoid namespace ambiguity

sycl/unittests/scheduler/EnqueueWithDependsOnDeps.cpp
See https://github.com/intel/llvm/issues/14060
=> [SYCL] Disable flaky test EnqueueNoMemObjTwoHostTasks on Windows

clang/lib/AST/ASTContext.cpp, clang/test/CodeGenSYCL/force-emit-device-virtual-funcs.cpp
We only emit unused member functions if they have been explicitly annotated with `sycl_device` attribute (through `SYCL_EXTERNAL` macro).
SYCL extension for virtual functions introduces an alternative markup for specifying which function and that markup is SYCL compile-time properties that we turn into attributes implicitly under the hood.
Essentially, we now have a situation where an implicit `sycl_device` attribute on a member function should be treated as an explicit one, because it could be a result of SYCL compile-time property being applied to that method.
=> [SYCL] Force-emit more member functions into device code

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/device.hpp, sycl/include/syclcompat/memory.hpp, sycl/test-e2e/syclcompat/memory/memory_async.cpp, sycl/test-e2e/syclcompat/memory/memory_management_test3.cpp
This PR adds a `wait_and_free` func. This makes it safer and less likely to release memory during or before it is used by enqueued commands.
`async_free` is renamed `enqueue_free`, to make its behaviour clearer
This PR updates the comments and tests accordingly
=> [SYCL][COMPAT] Add wait_and_free plus rename async_free in syclcompat

.github/workflows/sycl-linux-precommit-aws.yml, .github/workflows/sycl-linux-precommit.yml
temp fix for problems from cuda 12.5 uplift that were caused by https://github.com/intel/llvm/pull/14049. Should fix https://github.com/intel/llvm/issues/14071
=> [CI] pre-commit/aws pointed back to old image.

sycl/test-e2e/Plugin/cuda-max-local-mem-size.cpp
- C++ thrown exception message not shown when running from Windows terminal.
- The patch fixes [cuda-max-local-mem-size.cpp](https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/Plugin/cuda-max-local-mem-size.cpp) test failure.
=> [SYCL][TEST-E2E] Refactor the test to address Windows not printing the exception message

sycl/test-e2e/Plugin/sycl-ls-gpu-default-any.cpp
Extend the `sycl-ls-gpu-default.cpp` test to cover the support of Intel GPUs through OpenCL.
The patch fixes the failure when running the test on a system with Intel and CUDA gpus.
=> [SYCL][TEST-E2E] Extend  `sycl-ls-gpu-default.cpp` test to cover Intel GPUs through OpenCL.

sycl/test-e2e/BFloat16/bfloat16_builtins.hpp
Fixes ansi-alias violation and reads from uninitialized buffers. Fixes https://github.com/intel/llvm/issues/13790.
=> [SYCL][E2E] Refactor/fix bfloat16 test

sycl/test-e2e/NonUniformGroups/ballot_group_algorithms.cpp
Fails in Nightly testing on the self-hosted CUDA runner: https://github.com/intel/llvm/issues/12995.
=> [SYCL][E2E] Disable NonUniformGroups/ballot_group_algorithms.cpp on CUDA

.github/CODEOWNERS
CODEOWNERS seems to be missing a line attributing `sycl/test/check_device_code/matrix` tests to intel/sycl-matrix-reviewers (As per [this discussion](https://github.com/intel/llvm/pull/14063#discussion_r1629880980)). This PR remedies this.
Although, I noticed the current CODEOWNERS section for the matrix reviewers uses paths; Let me know if I should use `sycl/**/matrix` instead.
=> [SYCL][Matrix] Amend CODEOWNERS for check_device_code matrix tests

.github/workflows/sycl-nightly.yml
The runner seems to be broken, don't run the tests until it's fixed.
=> [CI] Don't run E2E tests on self-hosted CUDA in Nightly

clang/test/Driver/pch-fsycl-error.cpp, clang/test/Driver/sycl-add-default-spec-consts-image.cpp, clang/test/Driver/sycl-offload-aot.cpp
This is required by 24a12a9c8 [clang] Diagnose problematic diagnostic messages (#93229).
=> [SYCL] Update diagnostic messages in tests to match community convention.

sycl/test-e2e/GroupAlgorithm/SYCL2020/reduce_over_group_size.cpp, sycl/test-e2e/HierPar/hier_par_wgscope_O0.cpp, sycl/test-e2e/Regression/unoptimized_stream.cpp
This was tracked down to a bug in ROCm that seems to be fixed with newer
versions, and the CI is now on ROCm 6+ so these should be fine.
ROCm ticket: https://github.com/ROCm/clr/pull/13
The reduce over group test works on W6800 and MI210, but it seems for
gfx1031 it reports not supporting shared USM, note that HIP for gfx1031
isn't officially supported by AMD.
=> [SYCL][HIP] Remove unsupported from O0 tests on AMD

sycl/test-e2e/ESIMD/regression/bit_shift_vector_compilation_test.cpp
We don't actually need cpp20, this was left over from a previous iteration of the test.
=> [SYCL][ESIMD][E2E] Fix bit shift vector test to not use c++20

sycl/doc/extensions/proposed/sycl_ext_oneapi_free_function_kernels.asciidoc, sycl/doc/extensions/proposed/sycl_ext_oneapi_work_group_memory.asciidoc
Add a proposed extension specification for `work_group_memory`, a
lighter weight API to allocate device local memory for an nd-range
kernel.
Also related, add a list of restrictions that, when followed, provide a
guarantee that a kernel written in the free-function kernel syntax can
be launched directly via Level Zero or OpenCL.
=> [SYCL][Doc] Extension spec for "work_group_memory"

sycl/include/sycl/detail/group_sort_impl.hpp, sycl/include/sycl/ext/oneapi/experimental/group_helpers_sorters.hpp
Currently `std::byte*` scratch pointer is not aligned and `reinterpret_cast`ed as `T*` where type `T` may have alignment requirement different from `byte*`, this is UB.
As a solution, use `std::align` to align the required buffer in the scratch and use placement `new` so that dynamic type of the buffer in the scratch will be `T*`.
=> [SYCL] Fix UB and alignment issues in the SYCL default sorter

sycl/test-e2e/syclcompat/memory/memory_management_test3.cpp
This change is intended to fix a CI failure on the OpenCL backend for the `memory_management_test3`. This is because the memory is allocated on a different q to the one it is released on.
=> [SYCL][COMPAT] Fix memory_management_test3

sycl/test-e2e/Graph/Update/whole_update_dynamic_param.cpp
In the `Graph/Update/whole_update_dynamic_param.cpp` test there is no dependency defined on the out-of-order queue between initalizing the data and running the graph which uses it.
On immediate command-list L0 backends in particular this manifests as a fail.
Fixed by adding a wait between data initialization and use.
=> [SYCL][Graph] Missing test dependency after data init

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/math.hpp, sycl/test-e2e/syclcompat/math/math_byte_dot_product.cpp
This PR adds the dp4a, d2pa_lo and dp2a_hi helpers to the math header in SYCLcompat.
Created a test case, documentation updated.
=> [SYCL][COMPAT] Added two-way and four-way dot product accumulate (dp4a, dp2a)

sycl/plugins/unified_runtime/CMakeLists.txt
Bumps the L0 adapter UR commit to include several merged fixes to the L0 adapter for implementing the SYCL-Graph update feature:
* [Use fence rather than event for sync in L0 command-buffer update](https://github.com/oneapi-src/unified-runtime/pull/1629)
* [Fix lifetime of pointer used in L0 update](https://github.com/oneapi-src/unified-runtime/pull/1721)
* [Fix L0 Event leak without return sync point](https://github.com/oneapi-src/unified-runtime/pull/1706)
=> [SYCL][Graph] Combined L0 Graph Update fixes

sycl/test-e2e/Graph/Explicit/add_nodes_after_finalize.cpp
`test-e2e/Graph/Explicit/add_nodes_after_finalize.cpp` has been reported as failing on an unrelated PR on Windows - https://github.com/intel/llvm/issues/11852#issuecomment-2151687966
Disable this test in line with how other flaky graphs tests have been disabled on Windows in https://github.com/intel/llvm/pull/13966
The `RecordReplay` equivalent of this Explicit test is already disabled on Windows.
=> [SYCL][Graph] Disable flaky Windows test

sycl/include/sycl/ext/oneapi/experimental/group_helpers_sorters.hpp, sycl/include/sycl/ext/oneapi/experimental/group_sort.hpp, sycl/test-e2e/GroupAlgorithm/SYCL2020/sort.cpp
Current implementation is aligned with the first version of the extension: https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/experimental/sycl_ext_oneapi_group_sort.asciidoc
This second version of the extension:
https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/proposed/sycl_ext_oneapi_group_sort.asciidoc changes the API by introducing separate sorter objects for sort_over_group and joint_sort APIs.
Save both versions of API until the second version is not fully implemented. When PRs supporting the second version will be fully merged and macro will be updated, then old APIs will be removed.
Currently PR doesn't include array input and key/value sorting support.
It's split from larger PR: https://github.com/intel/llvm/pull/13713
Co-authored-by: "Andrei Fedorov …
=> [SYCL] Initial changes for the second version of sycl_ext_oneapi_group_sort extension

clang/lib/Driver/Compilation.cpp, clang/lib/Driver/Driver.cpp, clang/lib/Driver/ToolChains/Clang.cpp, clang/lib/Driver/ToolChains/CommonArgs.cpp, clang/lib/Driver/ToolChains/SYCL.cpp
Move away from using .equals to '==' for string comparisons.  This puts us in line with community.
=> [Driver][NFC] Update equals usage in driver sources

clang/test/AST/ast-attr-add-ir-annotations-pack.cpp, clang/test/AST/ast-attr-add-ir-attributes-misc.cpp, clang/test/AST/ast-attr-add-ir-attributes-packs.cpp, clang/test/SemaSYCL/device_has_ast.cpp, clang/test/SemaSYCL/initiation_interval_ast.cpp, clang/test/SemaSYCL/intel-fpga-no-global-work-offset-ast.cpp, clang/test/SemaSYCL/intel-max-global-work-dim-device-ast.cpp, clang/test/SemaSYCL/lb_sm_90_ast.cpp, clang/test/SemaSYCL/loop_fusion_ast.cpp, clang/test/SemaSYCL/max-concurrency-ast.cpp, clang/test/SemaSYCL/reqd-sub-group-size-ast.cpp, clang/test/SemaSYCL/scheduler_target_fmax_mhz_ast.cpp, clang/test/SemaSYCL/uses_aspects_ast.cpp
The format was changed in 1a2f33097 [clang] Improve ast-dumper text printing of TemplateArgument (#93431).
=> [SYCL] Properly format AST dump of TemplateArgument in tests.

sycl/test-e2e/Graph/Update/update_with_indices_ptr_3D.cpp
Add an E2E regression test for updating kernel nodes with 3 dimensions. Test contains a graph with two nodes, the first node with an NDRange containing a user specified local size, and the second node containing a Range with implementation determined local size.
=> [SYCL][Graph] 3D kernel update regression test

clang/lib/Driver/Driver.cpp, clang/test/Driver/sycl-fno-libspirv-warn.cpp, clang/test/Driver/sycl-offload-new-driver.c
Reverts intel/llvm#14091 due to failure in Clang :: Driver/sycl-offload-new-driver.c in post-commit.
=> Revert "[Driver][SYCL][NewOffload] Fix duplication of device targets"

.github/workflows/sycl-linux-precommit-aws.yml
We have limited build systems and these tasks can run on basically any Linux hardware.
Right now sometimes I have to wait over an hour for `update-check` to run even after that actual task that runs on the GPU succeeds.
=> [CI] Allow aux CUDA jobs to run on more machines

clang/lib/Driver/Driver.cpp, clang/test/Driver/sycl-fno-libspirv-warn.cpp, clang/test/Driver/sycl-offload-new-driver.c
When passing along multiple targets in the form of -fsycl-targets=intel_gpu_dg1,intel_gpu_pvc, the number of the device compilations was n*n as opposed to just n.  Due to how we were handling duplicate entries for toolchain generation, the different names used even though they had the same target triple (spir64_gen) we being considered as unique, causing the multiple entries.
This is the second attempt to push this one in, updated the sycl-offload-new-driver.c test to reflect ordering issues encountered.
=> [Driver][SYCL][NewOffload] Fix duplication of device targets

clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/linker-wrapper-sycl-win.cpp, clang/test/Driver/sycl-linker-wrapper-image.cpp, clang/test/Driver/sycl-offload-new-driver.c
clang-linker-wrapper is not target-specific. i.e. it is not called for a single target device. It is called only once.
Currently, clang-linker-wrapper is called only with device images with spir64 targets. So, the existing approach to capture the first target triple in the list of triples and use it for gathering sycl-device-library files is valid. As we plan to add support for more targets (AOT), we need to gather sycl-device-libraries for all targets. This PR addresses this change.
Also, the triple should not be passed to the linker wrapper. The linker wrapper should get the triples from device images.
Thanks
=> [New offload driver][Device lib] Add SYCL device library files for all targets

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/device.hpp
Required for specific use-cases in SYCLomatic.
=> [SYCL][COMPAT] Added non-const image2d_max and image3d_max getters

sycl/test-e2e/Graph/UnsupportedDevice/device_query.cpp
The `Graph/UnsupportedDevice/device_query.cpp` test asserts that L0 devices will never have full graph support. This is not the case, depending on the L0 device and driver version full graphs support is possible.
Update the test to remove asserting on this, as diving into these details is out of the scope of the test. This was previously decided when discussion how to check the OpenCL backend for similar possible variances in aspect support.
=> [SYCL][Graph] Update L0 aspect test

sycl/test-e2e/Plugin/cuda_queue_priority.cpp, sycl/test-e2e/Plugin/interop-cuda-experimental.cpp, sycl/test-e2e/Plugin/interop-experimental-single-TU-SYCL-CUDA-compilation.cpp, sycl/test-e2e/lit.cfg.py, sycl/test-e2e/lit.site.cfg.py.in
`cuda_dev_kit` is not set properly in [test-e2e/lit.cfg.py](https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/lit.cfg.py) due to invalid CUDA paths.
Fixing the paths showed errors in [14115](https://github.com/intel/llvm/issues/14115) and [14116](https://github.com/intel/llvm/issues/14116) which are XFAILed.
The patch fixes the failure of [cuda_queue_priority.cpp](https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/Plugin/cuda_queue_priority.cpp) on Windows / CUDA.
=> [SYCL][E2E] Fix CUDA include and lib paths.

sycl/test-e2e/InorderQueue/in_order_get_property.cpp, sycl/test-e2e/InorderQueue/in_order_kernels.cpp, sycl/test-e2e/InorderQueue/in_order_usm_implicit.cpp
- `InorderQueue/in_order_get_property.cpp` -> Use non-deprecated `sycl::exception`, add check for errc to ensure we are still catching the correct exception
- `InorderQueue/in_order_kernels.cpp` -> Use group `get_group_id` function instead of deprecated `get_id`
- `InorderQueue/in_order_usm_implicit.cpp` -> Use queue `mem_advice` function that uses `int` instead of `pi_mem_advice`
=> [SYCL][E2E] Fix deprecated warnings in `InorderQueue` e2e tests

sycl/plugins/level_zero/CMakeLists.txt
Currently Level Zero plugin uses loader and headers fetched by the Level Zero adapter (LevelZeroLoader-Headers, LevelZeroLoader targets).  Currently downloaded loader code is not used, only headers are used for xpti.
So, get headers location from LevelZeroLoader-Headers target instead and remove unnecessary code.
=> [SYCL] Remove redundant code from L0 plugin's cmake file

sycl/include/sycl/detail/group_sort_impl.hpp, sycl/include/sycl/ext/oneapi/experimental/group_helpers_sorters.hpp, sycl/include/sycl/ext/oneapi/experimental/group_sort.hpp, sycl/test-e2e/GroupAlgorithm/SYCL2020/group_sort/common.hpp, sycl/test-e2e/GroupAlgorithm/SYCL2020/group_sort/group_and_joint_sort.cpp, sycl/test-e2e/GroupAlgorithm/SYCL2020/group_sort/key_value_sort.cpp, sycl/test-e2e/GroupAlgorithm/SYCL2020/sort.cpp
Add group_key_value_sorter sorters and sort_key_value_over_group APIs based on https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/proposed/sycl_ext_oneapi_group_sort.asciidoc extension.
This PR was split out from larger PR: https://github.com/intel/llvm/pull/13713
Co-authored-by: "Andrei Fedorov [andrey.fedorov@intel.com](mailto:andrey.fedorov@intel.com)"
Co-authored-by: "Romanov Vlad [vlad.romanov@intel.com](mailto:vlad.romanov@intel.com)"
=> [SYCL] Add support for key/value sorting APIs

clang/lib/Sema/SemaSYCL.cpp
6b755b0cf split SemaDeclAttr.cpp. But not all SYCL changes are properly
handled. This patch serves as a follow up and fixes most LIT failures.
=> [SYCL] Port changes in 414c1e5e6 to SemaSYCL.cpp.

libdevice/cmath_wrapper.cpp, libdevice/cmath_wrapper_fp64.cpp, libdevice/device_math.h, libdevice/fallback-cmath-fp64.cpp, libdevice/fallback-cmath.cpp, sycl/test-e2e/DeviceLib/cmath_fp64_test.cpp, sycl/test-e2e/DeviceLib/cmath_test.cpp
[SYCL] Adding support for missing math ops:
- truncf
- sinpif
- rsqrtf
- exp10f
=> [SYCL] Adding support for missing math ops

sycl/doc/developer/ContributeToDPCPP.md
Add section to the contribution guide detailing the current process for integrating Unified Runtime updates into DPC++.
=> [Doc] Document Unified Runtime update process

sycl/source/detail/kernel_program_cache.hpp, sycl/source/detail/program_manager/program_manager.cpp, sycl/unittests/kernel-and-program/OutOfResources.cpp
I'm observing cache overflow when running heavy tests on OCL backend with gpu. Clear cache in case of PI_ERROR_OUT_OF_HOST_MEMORY as well as for PI_ERROR_OUT_OF_RESOURCES.
Using as reference: https://github.com/intel/llvm/pull/11987
=> [SYCL] Clear cache in case of PI_ERROR_OUT_OF_HOST_MEMORY

sycl/test-e2e/Basic/barrier_order.cpp
Closes https://github.com/intel/llvm/issues/7330.
=> [SYCL] Re-enable `Basic/barrier_order.cpp`

sycl/test-e2e/ESIMD/rotate.cpp
The rotate functions are technically c++20 and MSVC hasn't implemented them yet.
=> [SYCL][ESIMD][E2E] Fix rotate.cpp on Windows

clang/lib/Driver/Driver.cpp, clang/test/Driver/sycl-offload-new-driver.c
One of the models that is used for specifying the device architecture for spir64_gen is to use the -Xsycl-target-backend "-device arg" syntax on the command line.
Hook up the ability to scan the target backend values to embed the proper information in the packaged binary when using the new offload model.
=> [Driver][SYCL][NewOffloadModel] Incorporate -device settings for GPU

devops/containers/ubuntu2204_build.Dockerfile
Updating the docker to 12.5 led to the below described problems. Since the testing output of 12.1 matches 12.5, and we don't actually use any cuda features later than 12.1 (which are minor updates) in the compiler, this PR reverts back to the 12.1 image.
We can update the docker later only when we really need to (probably when cuda 13 is released). For the purposes of intel/llvm CI 12.1 is sufficient.
This fixes the "latest" docker image, allowing other updates to the docker image to be made in the future.
CUDA docker issues:
Depending on the host setup of the runners, there are various issues on recent nvidia docker images related to interactions with the host, whereby nvidia devices are not visible.
- https://github.com/NVIDIA/nvidia-container-toolkit/issues/48
- …
=> [CI] Use cuda 12.1 docker image again.

sycl/source/detail/global_handler.cpp, sycl/source/detail/global_handler.hpp, sycl/source/detail/platform_impl.cpp, sycl/source/detail/sycl_mem_obj_t.cpp, sycl/test-e2e/IntermediateLib/Inputs/simple_lib.cpp, sycl/test-e2e/IntermediateLib/Inputs/simple_lib.h, sycl/test-e2e/IntermediateLib/dynamic_app_linux.cpp, sycl/test-e2e/IntermediateLib/static_app.cpp
On Linux, the TensorFlow library (which uses SYCL .so) is having a problem wherein its own releasing of resource is running afoul ours. The solution is to stop deferring any new memory releases once we know we are shutting down. To that end I've broken the shutdown into two parts (early and late) and added a flag for whether its OK to defer memory or not.  This has been confirmed to fix the problem.  
It is not entirely clear to me what, exactly, the underlying cause of the problem is on the TensorFlow side. But I realized that while SYCL is used by several intermediate libs we have no testing of this scenario, so I've begun to add some.
Lastly, on Windows, I've got encouraging results that this approach may help us unify shutdown so it's the same on both Linux and Win, but that is a …
=> [SYCL] fix for tensorflow, linux only

sycl/doc/design/CommandGraph.md, sycl/plugins/unified_runtime/CMakeLists.txt, sycl/test-e2e/Graph/ValidUsage/linear_graph_copy.cpp
- Update UR tag to include L0 command-buffer copy engine optimization
- Add test which mixes copy and kernel commands
- Update design doc to detail copy engine optimization
Co-authored By:
* Ben Tracy <ben.tracy@codeplay.com>
* Ewan Crawford <ewan@codeplay.com>
=> [SYCL][Graph] Update design doc for copy optimization and add test 

sycl/include/sycl/vector_preview.hpp, sycl/test/basic_tests/vectors/vectors.cpp
Failure: https://github.com/intel/llvm/actions/runs/9493008325/job/26161455039
=> [SYCL] Fix nightly CTS failure after e7defabd

sycl/source/detail/device_info.hpp
The file in this patch was accidentally missing during commit and push for #14077, adding it here.
=> [SYCL] Update error handling for sycl_ext_oneapi_device_architecture in SYCL RT

sycl/test-e2e/UserDefinedReductions/user_defined_reductions.cpp, sycl/test-e2e/UserDefinedReductions/user_defined_reductions_wg_size_larger_than_data_size.cpp
Use `multi_ptr` `get()` method, instead of implicitly converting to a pointer.
=> [SYCL][E2E] Remove deprecated multi_ptr use in `UserDefinedReductions` e2e tests

sycl/test-e2e/Scheduler/DataMovement.cpp, sycl/test-e2e/Scheduler/InOrderQueueDeps.cpp, sycl/test-e2e/Scheduler/MemObjRemapping.cpp, sycl/test-e2e/Scheduler/MultipleDevices.cpp
- Replace use of buffer `get_access` calls in host with `host_accessor` constructor
- Replace use of old device selector with new callable selector
- Replace use of old sycl exceptions
=> [SYCL][E2E] Fix deprecated warnings in `Scheduler` e2e tests

clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/linker-wrapper-sycl-win.cpp, clang/test/Driver/linker-wrapper-sycl.cpp, clang/test/Driver/sycl-offload-new-driver.c, clang/test/Driver/sycl-post-link-options-win.cpp, clang/test/Driver/sycl-post-link-options.cpp, clang/tools/clang-linker-wrapper/ClangLinkerWrapper.cpp, clang/tools/clang-linker-wrapper/LinkerWrapperOpts.td
In an earlier PR (https://github.com/intel/llvm/pull/14101), we added support to generate sycl-post-link options (that partly depend on target triple) in clang Driver and then update the options using target triple information in the clang-linker-wrapper.
This PR cleans up that implementation by fully generating these options inside the clang-linker-wrapper. This requires some more user-specified options to be passed into the clang-linker-wrapper.
Thanks
=> [New offload model] Cleanup the way sycl-post-link options are generated

clang/lib/CodeGen/CGCall.cpp, clang/lib/Frontend/CompilerInvocation.cpp, llvm/include/llvm/SYCLLowerIR/CompileTimePropertiesPass.h
Uses have already been removed upstream and downstream, so remove the remaining ones here.
=> [NFC] Remove uses of deprecated StringRef::equals

clang/lib/Sema/SemaChecking.cpp
Remove ElementTypeIndex from the capture list. It's not used and generates a warning.
=> [NFC] Remove unused lambda capture

clang/include/clang/Basic/DiagnosticDriverKinds.td, clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/sycl-lto.cpp
This is really complicated to support so we decided to disallow it for now.
I also fixed the condition to be more of what we want.
=> [SYCL][Driver][thinLTO] Error for -foffload-lto and -fsycl-device-code-split=off

sycl/plugins/unified_runtime/CMakeLists.txt
https://github.com/oneapi-src/unified-runtime/pull/1623
=> [UR] Bump L0 tag to 2a31795d

llvm/lib/SYCLLowerIR/ESIMD/LowerESIMDSlmReservation.cpp
ScopeStartCI is only used in an assert so a warning is given in release builds. Add a reference so -Werror builds can succeed.
=> [NFC] Add a variable use to silence 'set but not used' warning

sycl/source/detail/scheduler/commands.cpp, sycl/test-e2e/Graph/Update/Explicit/whole_update_double_buffer.cpp, sycl/test-e2e/Graph/Update/RecordReplay/whole_update_double_buffer.cpp
- Could cause overlap of graph execution and initial h2d copy when updated with previously unused buffers
- Re-enable update double buffer tests on CUDA as this should fix failures observed in #13731
=> [SYCL][Graph] Wait instead of flush dep events in update command

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/device.hpp, sycl/test-e2e/syclcompat/device/device.cpp, sycl/test-e2e/syclcompat/device/device_fixt.hpp
This PR adds the syclcompat free function `device_count`.
It provides testing for this new function and for `get_device_id()`
=> [SYCL][COMPAT] Add device_count and testing

sycl/test-e2e/HostInteropTask/host-task-dependency2.cpp, sycl/test-e2e/HostInteropTask/host-task-dependency3.cpp, sycl/test-e2e/HostInteropTask/host-task.cpp
Replace use of buffer `get_access` calls in host with `get_host_access` for `HostInteropTask` e2e tests.
=> [SYCL][E2E] Fix deprecated warnings in `HostInteropTask` e2e tests

sycl/include/sycl/detail/group_sort_impl.hpp, sycl/include/sycl/ext/oneapi/experimental/group_helpers_sorters.hpp, sycl/include/sycl/ext/oneapi/experimental/group_sort.hpp, sycl/include/sycl/ext/oneapi/properties/property.hpp, sycl/test-e2e/GroupAlgorithm/SYCL2020/group_sort/array_input_sort.cpp, sycl/test-e2e/GroupAlgorithm/SYCL2020/group_sort/common.hpp
These PR covers (1), (2), (3) from  https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/proposed/sycl_ext_oneapi_group_sort.asciidoc#functions-with-fixed-size-arrays.
PR doesn't include key/value sorting with fixed-size array input which will be added in a separate PR.
=> [SYCL] Add sorting APIs for fixed-size private array input

sycl/source/detail/queue_impl.hpp, sycl/test-e2e/Graph/RecordReplay/barrier_multi_graph.cpp, sycl/unittests/Extensions/CommandGraph/Regressions.cpp
Recording barrier submissions to from the same queue to a different graph current produces the following error with added regression test:
```
Terminate called after throwing an instance of 'sycl::_V1::exception'
what():  Graph nodes cannot depend on events from another graph.
```
This is because the queue implementation doesn't clear all the state around what the last queue submission was between graph recordings.
Fixed by clearing all members of the barrier book keeping struct in the queue.
=> [SYCL][Graph] Fix queue recording barrier to different graphs

sycl/test-e2e/HostInteropTask/interop-task-cuda-buffer-migrate.cpp, sycl/test-e2e/HostInteropTask/interop-task-cuda.cpp
Add a basic interop test for CUDA, as well as an interop test that
ensures that memory migration will occur between devices in the same
context, when using host tasks. This is currently broken for CUDA but a fix
is TODO. This fix is nontrivial so will take some time.
=> [UR] Add interop testing for CUDA

sycl/source/detail/scheduler/commands.cpp
- Basic/image/srgba-read.cpp will fail with SYCL_PREFER_UR=1 and ONEAPI_DEVICE_SELECTOR=opencl:cpu, the piKernelSetArg returns PI_ERROR_INVALID_MEM_OBJECT.
```
---> piKernelSetArg(
<unknown> : 0x3339020
<unknown> : 0
<unknown> : 8
<unknown> : 0x7ffc5b159bb0
) --->  pi_result : -38
[out]pi_mem * : 0x7ffc5b159bb0[ 0x214cd00 ... ]
```
- Many device sanitizer tests and other sycl e2e tests with device sanitizer will fail the same way.
Without SYCL_PREFER_UR=1, SYCL will pick the opencl plugin, which is actually a thin wrapper for UR implementation now, but there still differences. For opencl plugin, the `MemArg` in the function will be a cl_mem object, then it can be simply passed to `clSetKernelArg()`, which is what essentially `piKernelSetArg()` (which for UR is `urKernelSetArgValue()`) …
=> Fix Basic/image/srgba-read.cpp failure under SYCL_PREFER_UR with ONEAPI_DEVICE_SELECTOR=opencl:cpu 

llvm/utils/git/requirements.txt
Bump urllib3 (pip) from 2.2.1 -> 2.2.2.
When using urllib3's proxy support with ProxyManager, the Proxy-Authorization header is only sent to the configured proxy, as expected.
However, when sending HTTP requests without using urllib3's proxy support, it's possible to accidentally configure the Proxy-Authorization header even though it won't have any effect as the request is not using a forwarding proxy or a tunneling proxy. In those cases, urllib3 doesn't treat the Proxy-Authorization HTTP header as one carrying authentication material and thus doesn't strip the header on cross-origin redirects.
Upgrading will resolve this issue.
=> Bump urllib3 from 2.2.1 in llvm/utils

devops/dependencies-igc-dev.json
=> [GHA] Uplift Linux IGC Dev RT version to igc-dev-92c2e4b

clang/lib/Driver/Driver.cpp, clang/test/Driver/sycl-offload-aot.cpp
When performing AOT and using -save-temps, make sure that the output files are created with an extension.  This is done for 'ocloc' behaviors as if an -output value does not have an extension, 'ocloc' will create a file with a default '.bin' extension causing issues with file consumption down the line.
=> [Driver][SYCL] Force an extension for AOT tool output files

sycl/test-e2e/ESIMD/unified_memory_api/atomic_update_acc_dg2_pvc_cmpxchg.cpp
Test is failing and causing a GPU reset on Windows with earlier driver versions.
=> [SYCL][ESIMD][E2E] Add Windows driver check for atomic update test

sycl/test-e2e/AtomicRef/atomic_memory_order_acq_rel.cpp, sycl/test-e2e/AtomicRef/atomic_memory_order_seq_cst.cpp
- Remove deprecated use of `get_pointer` in `atomic_memory_order_acq_rel.cpp`
- Compile `atomic_memory_order_acq_rel.cpp` and `atomic_memory_order_seq_cst.cpp` with cuda backend flags, only if there is a cuda device
=> [SYCL][E2E] Fix warnings in `AtomicRef` e2e tests

sycl/test-e2e/CMakeLists.txt, sycl/test-e2e/lit.cfg.py, sycl/test-e2e/lit.site.cfg.py.in
https://github.com/intel/llvm/pull/13976 adds support for using the `Architecture` output of `sycl-ls` when configuring `e2e` tests. This PR adds an opt-in option to allow configuring `e2e` tests when the architecture is `unknown`.
=> [SYCL][E2e] Optionally allow unknown architectures in e2e

sycl/doc/extensions/experimental/sycl_ext_matrix/sycl_ext_oneapi_matrix.asciidoc, sycl/test-e2e/Matrix/joint_matrix_gemm_cuda.hpp, sycl/test-e2e/Matrix/joint_matrix_tensorcores_sm70.cpp
For some sm_7x devices it is important to compile using the sm version (compute capability) matching the device that will run the joint_matrix code. This adds a note in docs explaining this.
Also specify `sycl::fabs` in joint_matrix_gemm_cuda.hpp to avoid ambiguity between `sycl::native::fabs`.
=> [MATRIX][DOC][E2E] Add note on sm version nvidia device issue.

sycl/include/sycl/vector_preview.hpp, sycl/test/basic_tests/min_max_test.cpp
windows.h defines min/max macros which conflict with std::min  causing compilation failure. 
sycl/test/basic_tests/min_max_test.cpp is supposed to test that but it was not testing the case when -fpreview-breaking-changes is used.
Enable the test for -fpreview-breaking-changes and fix one case doing std::min -> (std::min) which is the common workaround for this issue.
=> [SYCL] Fix conflict with min/max macro from windows.h for -fpreview-breaking-changes

devops/dependencies-igc-dev.json
=> [GHA] Uplift Linux IGC Dev RT version to igc-dev-6fe460a

sycl/test-e2e/GroupAlgorithm/root_group.cpp
root_group.cpp can pass with OpenCL fpga emulator.
=> [SYCL][E2E] Exclude root_group.cpp XFAIL on opencl accelerator

sycl/source/detail/graph_impl.cpp, sycl/test-e2e/Graph/Update/whole_update_barrier_node.cpp, sycl/test-e2e/Graph/Update/whole_update_empty_node.cpp, sycl/unittests/Extensions/CommandGraph/Exceptions.cpp, sycl/unittests/Extensions/CommandGraph/Update.cpp
In order to enable the minimum viable GROMACS use case for the Whole Graph Update feature,  allow graphs to contain empty nodes and barrier nodes during update.
See discussion thread https://github.com/intel/llvm/pull/13253#discussion_r1617321717 on SYCL-Graph spec PR for publicizing the availability of the Whole Graph Update feature.
=> [SYCL][Graph] Permit empty & barrier nodes in WGU

sycl/doc/extensions/proposed/sycl_ext_oneapi_work_group_static.asciidoc
Several changes to the specification for this proposed extension:
* Change the name to `work_group_static`.  This name is more consistent with our other extension named `work_group_memory`.
* Change the phrase "work-group-specific memory" to "device local memory".  This is the same phrase the core SYCL spec uses to describe this memory, and the word "specific" no longer makes sense now that we changed the name of the extension.
* Change the constraint for the `T` template parameter.  We cannot simply require `T` to be trivially constructible / destructible because this is not true for an unbounded array type.
* The restrictions about the legal scopes for a `work_group_static` variable seem confusing.  I'm not sure what we intended, so I just added an issue for now.
=> [SYCL][Doc] Update work-group-specific extension

libdevice/cmake/modules/SYCLLibdevice.cmake
For compilation on non-Intel architectures, the flags `-fcf-protection=full` must be checked against the compiler flags supported for the architecture. This adds a similar check to that done in HandleLibcxxabiFlags.cmake to check whether the architecture supports it.
=> Add a check to see if -fcf-protection=full is supported by the compiler

sycl/plugins/unified_runtime/pi2ur.hpp
OpaqueFD/Win32Handle is used in InteropMemDesc.pNext.
Their scope should be the same as of InteropMemDesc.
=> [SYCL][Bindless] Fix OpaqueFD/Win32Handle's scope in piextImportExternalMemory/Semaphore

sycl/include/sycl/nd_item.hpp, sycl/test-e2e/SeparateCompile/sycl-external-within-staticlib.cpp
Static library linking mechanism uses symbols pulled in by the host linker to determine what parts of device code to include during its linking. The exceptions thrown from nd_item on host interfere with that, since all the following host code for the kernel can get optimized away.
This change removes those exceptions since nd_item can't be constructed on the host side.
=> [SYCL] Fix SYCL_EXTERNAL device code when linking with a static lib

sycl/source/detail/context_impl.hpp, sycl/source/detail/device_impl.cpp, sycl/source/detail/device_info.hpp, sycl/unittests/Extensions/CompositeDevice.cpp
The current implementation of component and composite devices makes multiple checks for the backend in order to bind the behavior of the extension to L0. However, this should instead be done by the backends, having them report missing support when possible, and allowing backends to potentially support the extension in the future without needing to change the SYCL runtime.
=> [SYCL] Detach composite/component devices from L0

clang/test/SemaSYCL/lb_sm_90.cpp
This fails for me constantly in `check-clang` locally because I don't build nvptx. I verified this is UNSUPPORTED when nvptx is not built and runs and passes when it is built.
=> [Clang][SYCL][LIT] Fix lb_sm_90.cpp when nvptx target is not enabled

.github/ISSUE_TEMPLATE/1-bug-report.yml, .github/ISSUE_TEMPLATE/2-bug-report-cuda.yml, .github/ISSUE_TEMPLATE/3-bug-report-hip.yml
The patch changes the way of where prompts are shown:
- previously it was a placeholder, it means that when customer starts to type something in the textbox, the prompt disappears and customer discovers that they doesn't know what to write next, so they doesn't provide other essential info described in these prompts to us
- now the prompt is written as text in textboxs, so the list of required things is not disappeared, so customer needs to modify the content of that textbox
=> [CI] Improve issue templates by continue showing prompt after typing starts

clang/test/CodeGenSYCL/image_accessor.cpp, clang/test/CodeGenSYCL/sampler.cpp
Test needs update after cbf6e93ce 2024-05-28 [clang codegen] Delete unnecessary GEP cleanup code. (#90303).
Change made by  @premanandrao
=> Fix tests after cbf6e93ce

clang/test/Driver/sycl-offload.c
clang-cl -O2/-Ot now implies -O3, update test to match
=> [NFC] Update test to reflect expect optimization settings with clang-cl

clang/test/Driver/sycl-offload-new-driver.c
The failure was a result of 255986e27 [Driver] BuildOffloadingActions: Stabilize iteration order.
=> [SYCL] Fix Clang :: Driver/sycl-offload-new-driver.c test failure.

clang/lib/CodeGen/CGBuiltin.cpp, clang/test/CodeGen/fp-accuracy.c
This fixes the following LIT tests:
* clang/test/CodeGen/fp-accuracy.c
* clang/test/CodeGenSYCL/fp-accuracy.cpp
* sycl/test/optional_kernel_features/fp-accuracy.c
* sycl/test/optional_kernel_features/fp-accuracy.cpp.
=> [SYCL] Integrate the newly-added llvm.tan and llvm.experimental.constrained.tan intrinsics with fp-accuracy.

llvm/include/llvm/SYCLLowerIR/ModuleSplitter.h, llvm/lib/SYCLLowerIR/ModuleSplitter.cpp, llvm/tools/sycl-post-link/sycl-post-link.cpp
--support-dynamic-linking affects behavior of ModuleSplitter.cpp.  Move option from sycl-post-link.cpp to ModuleSplitter.cpp so it does not have to be passed through many function calls.
=> [NFC][sycl-post-link] Move -support-dynamic-linking option

sycl/test-e2e/Basic/info.cpp
- Remove use of `strstream` in favor of `stringstream`.
- Use callable default device selector, instead of device selector object
- NOTE: This test still has many warnings related to deprecated `get_info` calls. However since the purpose of the test is to use those, they remain unchanged.
=> [SYCL][E2E] Fix warnings in `Basic/info.cpp` e2e test

sycl/test-e2e/TaskSequence/concurrent-loops.cpp, sycl/test-e2e/TaskSequence/in-order-async-get.cpp, sycl/test-e2e/TaskSequence/mult-and-add.cpp, sycl/test-e2e/TaskSequence/multi-kernel-task-function-reuse.cpp, sycl/test-e2e/TaskSequence/producer-consumer.cpp, sycl/test-e2e/TaskSequence/struct-array-args-and-return.cpp
This patch fixes errors like "call to 'XXX' is ambiguous" and also disables all TaskSequence tests on Windows because they fail in the same way as on Linux. Github issue was created against that and comment in tests was updated.
=> [SYCL][E2E] Fix one of the compfails of TaskSequence tests

sycl/include/sycl/backend.hpp, sycl/include/sycl/exception.hpp, sycl/test-e2e/Basic/exceptions-SYCL-2020.cpp
It had been removed from the specification in
https://github.com/KhronosGroup/SYCL-Docs/pull/431. Originally introduced in https://github.com/intel/llvm/pull/4298 the implementation has never been completed, so, while technically a breaking change, no customer code can be really using it.
=> [SYCL] Remove `sycl::errc_for`

sycl/test-e2e/FilterSelector/select_device_level_zero.cpp
Fixing test that was missed in #14162
=> [SYCL][E2E] Use callable device selector in `FilterSelector/select_device_level_zero.cpp`

clang/lib/Driver/ToolChains/SYCL.cpp, clang/test/Driver/sycl-unsupported.cpp
When using -fsycl --coverage, we should not enable code coverage for device compilations as code coverage for device is not supported at this time.
=> [Driver][SYCL] Restrict --coverage for SYCL device

sycl/test-e2e/ProfilingTag/in_order_profiling_queue.cpp, sycl/test-e2e/ProfilingTag/profiling_queue.cpp
Due to some confusion about the output from the in_order_profiling_queue test on L0, the test was disabled. However, the test can be safely reenabled for that target, while keeping it disabled for FPGA.
Additionally, the failure in profiling_queue is believed to be due to the same issue, so the JIRA has been added to it and the note in in_order_profiling_queue has been updated to reflect the known information about the failure.
=> [SYCL][E2E] Reenable in_order_profiling_queue for L0

sycl/test-e2e/ESIMD/unified_memory_api/atomic_update_usm_dg2_pvc_cmpxchg.cpp
A similar test was disabled in https://github.com/intel/llvm/commit/672b225e137b15de2465b62837ba32d17ab750a8, and this test was found to have the same issue.
=> [SYCL][ESIMD][E2E] Disable atomic_update test on Windows until new driver

sycl/test-e2e/Basic/linear-sub_group.cpp, sycl/test-e2e/Regression/get_subgroup_sizes.cpp, sycl/test-e2e/SubGroup/attributes.cpp, sycl/test-e2e/SubGroup/helper.hpp, sycl/test-e2e/SubGroup/info.cpp, sycl/test-e2e/SubGroup/reduce.cpp, sycl/test-e2e/SubGroup/reduce_fp16.cpp, sycl/test-e2e/SubGroup/reduce_fp64.cpp, sycl/test-e2e/SubGroup/reduce_spirv13.cpp, sycl/test-e2e/SubGroup/reduce_spirv13_fp16.cpp, sycl/test-e2e/SubGroup/reduce_spirv13_fp64.cpp, sycl/test-e2e/SubGroup/scan.cpp, sycl/test-e2e/SubGroup/scan_fp16.cpp, sycl/test-e2e/SubGroup/scan_fp64.cpp, sycl/test-e2e/SubGroup/scan_spirv13.cpp, sycl/test-e2e/SubGroup/scan_spirv13_fp16.cpp, sycl/test-e2e/SubGroup/scan_spirv13_fp64.cpp, sycl/test-e2e/SubGroup/vote.cpp
Subgroups are core sycl functionality which should be tested on all backends.
=> [SYCL][E2E] Remove subgroup supported checks from e2e tests

sycl/include/sycl/handler.hpp, sycl/source/detail/jit_compiler.cpp
The helper function storePlainArg in handler and jit_compiler reinterpret-casts pointers to memory in vectors of char in order to store arguments in them. However, this violates strict aliasing and is unnecessary as the resulting pointers are immediately converted to void* after all calls to the function. As such, this patch simplfies these implementations to always return void* and use memcpy to avoid the alias violation.
=> [SYCL] Simplify storePlainArg to avoid alias violations

sycl/source/detail/scheduler/commands.cpp
Part of getting rid of the deprecated `exception::get_cl_code`.
=> [SYCL] Use SYCL 2020 exception in `DispatchHostTask::operator()`

sycl/plugins/unified_runtime/CMakeLists.txt
https://github.com/oneapi-src/unified-runtime/pull/1804
=> [UR] Bump main tag to aaf0810

llvm/lib/Transforms/Instrumentation/AddressSanitizer.cpp, llvm/test/Instrumentation/AddressSanitizer/SPIRV/skip_referenced_indirectly.ll
When we create SLM __AsanLaunchInfo and store newly added kernel arg __asan_launch into the SLM, the SLM is loaded in asan report function. If instructions in referenced-indirectly function are instrumented, the report function is called. However, access to SLM in referenced- indirectly function isn't supported in intel-graphics-compiler yet.
=> [DeviceSanitizer] Don't instrument referenced-indirectly functions

sycl/include/sycl/buffer.hpp, sycl/include/sycl/detail/common.hpp, sycl/include/sycl/image.hpp, sycl/include/syclcompat/device.hpp, sycl/source/detail/context_impl.cpp, sycl/source/detail/device_image_impl.hpp, sycl/source/detail/event_impl.cpp, sycl/source/detail/global_handler.cpp, sycl/source/detail/graph_impl.cpp, sycl/source/detail/kernel_impl.cpp, sycl/source/detail/pi_utils.hpp, sycl/source/detail/program_impl.cpp, sycl/source/detail/queue_impl.hpp, sycl/source/detail/sampler_impl.cpp, sycl/source/detail/thread_pool.hpp, sycl/unittests/thread_safety/ThreadUtils.h
Destructors are implicitly noexcept, so we must ensure they don't actually throw exceptions. No change to API or ABI with this PR.
=> [SYCL] no exceptions leaking from destructors

clang/lib/Driver/Driver.cpp, clang/test/Driver/sycl-offload-new-driver.c
When compiling for -fsycl-targets values of nvptx64-nvidia-cuda and amdgcn-amd-gpu, the default arch behaviors were not applied to the compilation.  Updates to do the following:
- Add default of sm_50 for nvptx64 if not provided
- Emit diagnostic if no arch provided for amd
- Parse -Xsycl-backend-target for offload-arch values
=> [Driver][SYCL][NewOffload] Fix arch settings for nvptx and amd

llvm/test/CodeGen/SPIRV/transcoding/TransFNeg.ll, sycl/source/detail/physical_mem_impl.hpp
Totally broken on all platforms right now.
```
/__w/llvm/llvm/src/sycl/source/detail/physical_mem_impl.hpp:33:3: error: default label in switch which covers all enumeration values [-Werror,-Wcovered-switch-default]
33 |   default:
```
and
https://github.com/intel/llvm/issues/14372
=> [SYCL] Fix postcommit

sycl/source/detail/physical_mem_impl.hpp
Fixes precommit after unsuccessful post-commit fix at https://github.com/intel/llvm/pull/14373.
=> [SYCL] Fix precommit

llvm-spirv/lib/SPIRV/libSPIRV/SPIRVDecorate.cpp
Breaks were lost in 5fd4877, restoring them. When the breaks are lost, literals are enconded/decoded twice, which is wrong. 
** This is done in this repo because this piece of code is not present in Khronos repo. **
=> [spirv] Restoring breaks incorrectly dropped

sycl/source/detail/scheduler/commands.cpp
This should address the post-commit failure introduced in https://github.com/intel/llvm/pull/14353
=> [SYCL] Remove unused parameter in InteropFreeFunc

sycl/doc/extensions/experimental/sycl_ext_oneapi_graph.asciidoc, sycl/source/detail/graph_impl.cpp, sycl/source/detail/graph_impl.hpp, sycl/source/handler.cpp, sycl/unittests/Extensions/CommandGraph/Barrier.cpp, sycl/unittests/Extensions/CommandGraph/Exceptions.cpp
Changes the semantics of [sycl_ext_oneapi_enqueue_barrier](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_oneapi_enqueue_barrier.asciidoc) commands recorded from a queue into a SYCL-Graph.
The current semantics are that a barrier without a wait-list will depend on all leaf nodes in the graph, and be a dependency of any subsequent node added to the graph.
After discussion with users, this change updates the behavior of barriers to only depend on leaf nodes from the same recording queue, and only commands recorded from the same queue will have a dependency on the barrier.
=> [SYCL][Graph] Refine barrier semantics

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/dims.hpp, sycl/test-e2e/syclcompat/dim.cpp
This PR adds a default constructor for `syclcompat::dim3`, and changes the type of members `x`,`y`,`z` from `const size_t` to `unsigned int`. The default constructor sets all 3 dimensions to `1`. This means patterns like this are now possible:
```cpp
syclcompat::dim3 myDim3;
myDim3.x = 32;
```
=> [SYCL][COMPAT] Add default ctor to dim3 and update tests/docs

sycl/test-e2e/ESIMD/api/functional/operators/operator_logical_not.cpp, sycl/test-e2e/ESIMD/api/replicate_smoke.cpp, sycl/test-e2e/ESIMD/api/replicate_smoke_pvc.cpp, sycl/test-e2e/ESIMD/fp_in_phi.cpp, sycl/test-e2e/ESIMD/fp_in_select.cpp, sycl/test-e2e/ESIMD/noinline_call_from_func.cpp
=> [SYCL][ESIMD][E2E] Enable some tests

sycl/source/detail/program_impl.cpp, sycl/source/detail/sycl_mem_obj_t.cpp, sycl/unittests/scheduler/StreamInitDependencyOnHost.cpp
=> [SYCL] Fix postcommit again

sycl/test-e2e/Basic/stream/blocking_pipes_and_stream.cpp
=> [SYCL][E2E] Disable test: blocking_pipes_and_stream.cpp

sycl/test-e2e/BFloat16/bfloat16_vec.cpp, sycl/test-e2e/Basic/stream/stream.cpp, sycl/test-e2e/Complex/sycl_complex_stream_test.cpp
https://github.com/intel/llvm/issues/14397
The hang causes all jobs after to fail because the install dir can't be deleted, we need to disable these ASAP.
=> [SYCL][E2E] Disable three hanging tests on Gen12 Win

.github/workflows/sycl-nightly.yml
Today we don't pass the gpu lit params so we see things running and failing in the nightly that are already disabled in pre/postcommit.
Example:
https://github.com/intel/llvm/actions/runs/9754298775/job/26921343546
```
FAIL: SYCL :: Regression/in_order_barrier_profiling.cpp (1746 of 2090)
******************** TEST 'SYCL :: Regression/in_order_barrier_profiling.cpp' FAILED ********************
Exit Code: -6
Command Output (stdout):
--
/__w/llvm/llvm/toolchain/bin//clang++   -fsycl -fsycl-targets=spir64  /__w/llvm/llvm/llvm/sycl/test-e2e/Regression/in_order_barrier_profiling.cpp -o /__w/llvm/llvm/build-e2e/Regression/Output/in_order_barrier_profiling.cpp.tmp.out
env ONEAPI_DEVICE_SELECTOR=opencl:gpu  /__w/llvm/llvm/build-e2e/Regression/Output/in_order_barrier_profiling.cpp.tmp.out
```
and …
=> [CI] Pass GPU lit options for nightly tests

sycl/test-e2e/KernelFusion/cancel_fusion.cpp, sycl/test-e2e/KernelFusion/complete_fusion.cpp, sycl/test-e2e/KernelFusion/cooperative_kernel.cpp, sycl/test-e2e/KernelFusion/different_nd_ranges.cpp, sycl/test-e2e/KernelFusion/event_wait_cancel.cpp, sycl/test-e2e/KernelFusion/internal_explicit_dependency.cpp, sycl/test-e2e/KernelFusion/jit_caching_multitarget.cpp, sycl/test-e2e/KernelFusion/math_function.cpp, sycl/test-e2e/KernelFusion/non-kernel-cg.cpp, sycl/test-e2e/KernelFusion/non_unit_local_size.cpp, sycl/test-e2e/KernelFusion/sync_acc_mem_op.cpp, sycl/test-e2e/KernelFusion/sync_buffer_destruction.cpp, sycl/test-e2e/KernelFusion/sync_event_wait.cpp, sycl/test-e2e/KernelFusion/sync_host_accessor.cpp, sycl/test-e2e/KernelFusion/sync_host_task.cpp, sycl/test-e2e/KernelFusion/sync_queue_destruction.cpp, sycl/test-e2e/KernelFusion/sync_queue_wait.cpp, sycl/test-e2e/KernelFusion/sync_second_queue.cpp, sycl/test-e2e/KernelFusion/sync_two_queues_requirement.cpp, sycl/test-e2e/KernelFusion/sync_usm_mem_op.cpp, sycl/test-e2e/KernelFusion/usm_no_dependencies.cpp, sycl/test-e2e/KernelFusion/work_group_barrier.cpp, sycl/test-e2e/KernelFusion/wrapped_usm.cpp
Improve the kernel fusion end-to-end tests:
* Remove the flag to embed IR on CUDA and AMD backend from the tests that abort execution before requiring access to IR.
* Check for the number of kernel launches to make sure fusion did not fail silently.
=> [SYCL][Fusion] Improve kernel fusion e2e tests

llvm/lib/Transforms/Scalar/CMakeLists.txt
https://github.com/intel/llvm/pull/14339 moved the FPBuiltinFnSelection pass, but post-commit testing is failing due to the Transform/Scalar CMake not linking with TargetParser. This commit fixes this issue.
=> [LLVM] Add missing TargetParser link in FPBuiltinFnSelection

sycl/include/sycl/exception.hpp, sycl/include/sycl/usm/usm_allocator.hpp, sycl/test/warnings/sycl_2020_deprecations.cpp
Not part of SYCL 2020. Wider used exception subclasses will be removed in individual PRs to ease review.
=> [SYCL] Remove rarely/un-used SYCL 1.2 exceptions

sycl/include/sycl/exception.hpp, sycl/include/sycl/ext/intel/experimental/online_compiler.hpp, sycl/test/abi/sycl_symbols_windows.dump
SYCL 1.2 exception classes don't use `context` argument so it can be removed. `online_compile_error` was the single user of an overload, so I've removed it and change the ctor used by it.
=> [NFCI] Remove/inline [rarely|never] used `exception` ctor overloads

sycl/test-e2e/syclcompat/launch/launch.cpp
The sycl/test-e2e/syclcompat/launch/launch.cpp test was marked XFAIL but seems to be passing in post-commit. This commit changes in to UNSUPPORTED.
=> [SYCL][E2E] Change launch.cpp on dg2 to unsupported

clang/lib/CodeGen/Targets/NVPTX.cpp, clang/test/CodeGenSYCL/launch_bounds_nvptx.cpp
While the PTX directive is "minnctapersm", the NVVM annotation is "minctasm". This can be seen in the NVPTX backend, and in the NVVM IR spec, section 13.3.
=> [SYCL][NVPTX] Fix NVVM annotation for min_work_groups_per_cu attribute

clang/include/clang/Basic/AttrDocs.td
Declaring upfront that `reqd_work_group_size` has the same semantics between OpenCL and SYCL is misleading because the dimensionality is different. The docs for `work_group_size_hint` were better in clarifying the difference, so those have been copied and adapted.
Describe OpenCL upfront as it's simpler, and won't be buried by the wordier SYCL documentation.
Try and re-enforce the SYCL dimensionality rules to aid people more familiar with OpenCL and other similar languages.
Clarify that the `max_work_group_size` attribute (at least currently) behaves like `reqd_work_group_size` but we require *all* dimensions to be supplied.
=> [SYCL] Clarify a few work-group attribute docs

sycl/include/syclcompat/util.hpp
Fixes the path for `x <= 2` in `int_as_queue_ptr`, which was returning an address to a temporary pointer.
=> [SYCL][COMPAT] Fix using address of a temporary queue_ptr in util.hpp

sycl/source/platform.cpp, sycl/unittests/Extensions/CompositeDevice.cpp
This patch intended to be an improvement for composite device implementation code coverage, but it turned out that it also helped to find a bug in the implementaiton.
=> [SYCL] Fix reporting duplicate composite devices

sycl/unittests/helpers/PiMock.hpp
Does scheduler cleanup explicitly. Windows path has some "cut" code in prepareSchedulerForRelease (due to shutdown features) that makes this function useless for UT PiMock cleanup.
fixes https://github.com/intel/llvm/issues/13457
=> [SYCL][UT] Fix scheduler resources cleanup in PiMock dtor

sycl/include/sycl/detail/group_sort_impl.hpp, sycl/include/sycl/detail/spirv.hpp, sycl/include/sycl/ext/oneapi/experimental/ballot_group.hpp, sycl/include/sycl/ext/oneapi/experimental/fixed_size_group.hpp, sycl/include/sycl/ext/oneapi/experimental/opportunistic_group.hpp, sycl/include/sycl/ext/oneapi/experimental/root_group.hpp, sycl/include/sycl/ext/oneapi/experimental/tangle_group.hpp, sycl/include/sycl/ext/oneapi/sub_group_mask.hpp, sycl/include/sycl/group_algorithm.hpp, sycl/include/sycl/sub_group.hpp, sycl/test-e2e/Assert/check_resource_leak.cpp, sycl/test-e2e/Basic/image/image.cpp, sycl/test-e2e/Basic/image/image_accessor_readsampler.cpp, sycl/test-e2e/Basic/image/image_array.cpp, sycl/test-e2e/DeviceLib/assert.cpp, sycl/test-e2e/DeviceLib/rand_test.cpp, sycl/test/check_device_code/extensions/sub_group_as.cpp, sycl/test/check_device_code/vector/vector_convert_bfloat.cpp, sycl/test/include_deps/sycl_detail_core.hpp.cpp
Not needed anymore after deprecated shuffles/collectives were removed.
=> [SYCL] Drop `sycl/ext/oneapi/functional.hpp` include from `sycl/sub_group.hpp`

sycl/source/detail/graph_impl.cpp, sycl/test-e2e/Graph/Update/whole_update_dynamic_param.cpp, sycl/test-e2e/Graph/Update/whole_update_kernel_type_mismatch.cpp, sycl/unittests/Extensions/CommandGraph/Update.cpp
We cannot currently update the kernel binary of a node in Whole Graph Update. Rather than silently accepting inconsistent kernel functions, which indicates the graphs aren't topologically identical, throw an error when the kernel types of two nodes are mismatched.
This change requires removing the unittest for barrier nodes in Whole Graph Update as the mock infrastructure does not
setup the internal `CG` class to the depth required to test working functionality. This
functionality is already covered by `test-e2e/Graph/Update/whole_update_barrier_node.cpp`
=> [SYCL][Graph] Test WGU kernel mismatch

llvm/utils/git/requirements.txt
Bump certifi to 2024.07.04
Certifi 2024.07.04 removes root certificates from "GLOBALTRUST" from the root store. These are in the process of being removed from Mozilla's trust store.
GLOBALTRUST's root certificates are being removed pursuant to an investigation which identified "long-running and unresolved compliance issues". Conclusions of Mozilla's investigation can be found [here](https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI).
Upgrading will resolve this issue.
=> Bump certifi to 2024.07.04 in llvm/utils

.github/workflows/sycl-nightly.yml
I missed this in https://github.com/intel/llvm/commit/4a87b2ccfad6a918d66073ded6ac466542cf448e so the change didn't actually do anything.
=> [CI] Fix nightly extra lit options

sycl/test-e2e/ESIMD/lsc/lsc_usm_store_u32.cpp
I verified manually this option fixes the issue that was being tracked internally.
Thanks to @aelovikov-intel for help finding the option that was required.
=> [SYCL][ESIMD][E2E] Re-enable LSC DG2 Windows test with correct flags

sycl/tools/sycl-ls/sycl-ls.cpp
This is mostly relevant when sycl-ls might be run in the context of really old drivers/lzloader.  It is a workaround for some Win test systems.
=> [SYCL] suppression of error dialogs in Win sycl-ls. 

sycl/include/sycl/detail/cg_types.hpp, sycl/source/detail/error_handling/error_handling.cpp, sycl/test-e2e/Basic/cuda_max_wgs_error.cpp
Not removing the exception subclass itself as that would result in merge conflicts with our PRs.
=> [SYCL] Remove uses of `nd_range_error` exception

llvm/lib/SYCLLowerIR/ESIMD/LowerESIMD.cpp, sycl/include/sycl/ext/intel/esimd/common.hpp, sycl/include/sycl/ext/intel/esimd/memory.hpp, sycl/test-e2e/ESIMD/lsc/atomic_smoke.cpp, sycl/test-e2e/ESIMD/lsc/local_accessor_atomic_smoke.cpp, sycl/test-e2e/ESIMD/lsc/lsc_slm_atomic_smoke.cpp, sycl/test-e2e/ESIMD/unified_memory_api/Inputs/atomic_update.hpp, sycl/test-e2e/ESIMD/unified_memory_api/Inputs/atomic_update_slm.hpp
It never worked, VC doesn't support it, and nobody has ever reported it broken so there's no use in emulating it.
=> [SYCL][ESIMD][ABI Break] Remove predec atomic op

sycl/include/sycl/detail/array.hpp, sycl/include/sycl/detail/image_accessor_util.hpp, sycl/source/context.cpp, sycl/source/detail/config.hpp, sycl/source/detail/context_impl.cpp, sycl/source/detail/image_impl.cpp, sycl/source/detail/kernel_impl.cpp, sycl/source/detail/sycl_mem_obj_t.cpp, sycl/source/device.cpp, sycl/source/handler.cpp, sycl/source/stream.cpp, sycl/test-e2e/Basic/context_platforms.cpp, sycl/test-e2e/DeprecatedFeatures/kernel_interop.cpp, sycl/unittests/stream/stream.cpp
Not removing the exception subclass itself as that would result in merge conflicts with our PRs.
=> [SYCL] Remove uses of `invalid_parameter_error` exception

sycl/test-e2e/AddressSanitizer/common/demangle-kernel-name.cpp
The implementation of kernel name detangling is standard lib dependent, and both libstdc++ and libc++ are likely to be used, so we should make the test pass both with libstdc++ and libc++.
=> [DeviceSanitizer][test] Update test to satisfy both libstdc++ and libc++

sycl/include/sycl/ext/oneapi/properties/properties.hpp, sycl/test-e2e/KernelCompiler/kernel_compiler_sycl.cpp, sycl/test/extensions/kernel_compiler_constraints.cpp
fixing minor sfinae problem in all_props_are_keys_of and updating tests accordingly.
at the moment the kernel_compiler is the only user of `all_props_are_keys_of`
=> [SYCL] all_props_are_keys_of fix

sycl/include/syclcompat/math.hpp, sycl/test-e2e/syclcompat/math/math_byte_dot_product.cpp
Fixes the Nvidia backend code path for int8 intrinsics in syclcompat.
* Was using previously __CUDA_ARCH__ instead of __SYCL_CUDA_ARCH__
* Updates the test to compile to the minimum supported architecture `sm61`
=> [SYCL][COMPAT] fixed byte-dot products to properly call cuda intrinsics

llvm-spirv/lib/SPIRV/SPIRVWriter.cpp
This reverts commit ead840494a6ecbd534f9161190217c02d3c6189a.
The commit was W/A which should be removed to align with Khronos translator code base.
It resolves p.2 of #7592 "adds extra code" section.
=> Revert "[SPIR-V] W/A for builtin vars translation (#7632)"

sycl/source/detail/graph_impl.cpp, sycl/source/detail/scheduler/commands.cpp, sycl/source/detail/scheduler/commands.hpp, sycl/source/handler.cpp
It only returns `PI_SUCCESS` through normal control flow, all the errors result in an exception thrown. In other words, there is no `return NOT_A_PI_SUCCESS` inside its body, so we can simply make it `void` and simplify its callers.
=> [NFC][SYCL] Change `enqueueImpKernel` to return `void`

clang/test/Driver/sycl-native-cpu-fsycl.cpp
This fixes the failure in the nightly (https://github.com/intel/llvm/actions/runs/9867495007/job/27247963704) introduced by https://github.com/intel/llvm/pull/13979 by adding a mock file for the Native CPU utils lib, and using the `--sysroot` option so that the driver picks it up, similarly to how it's done for e.g. [sycl-device-lib.cpp](https://github.com/intel/llvm/blob/sycl/clang/test/Driver/sycl-device-lib.cpp).
=> [SYCL][NATIVECPU] Use mock file for native cpu lib

sycl/test-e2e/ESIMD/accessor_global.cpp, sycl/test-e2e/ESIMD/private_memory/private_memory.cpp, sycl/test-e2e/ESIMD/unified_memory_api/Inputs/copyto_copyfrom.hpp
Partially changes implementation of the fix from
https://github.com/intel/llvm/commit/97e43dddcebfaa44214533888d072fa4cf3f24d5
=> [NFCI][SYCL][ESIMD][E2E] Drop unnecessary `template` keyword

sycl/include/sycl/ext/oneapi/backend/hip.hpp, sycl/include/sycl/ext/oneapi/bf16_storage_builtins.hpp, sycl/source/backend.cpp, sycl/source/detail/config.hpp, sycl/source/detail/error_handling/error_handling.cpp, sycl/source/detail/filter_selector_impl.cpp, sycl/source/detail/kernel_bundle_impl.hpp, sycl/source/detail/memory_manager.cpp, sycl/source/detail/pi.cpp, sycl/source/detail/platform_util.cpp, sycl/source/detail/plugin.hpp, sycl/source/detail/program_manager/program_manager.cpp, sycl/source/detail/queue_impl.cpp, sycl/source/detail/scheduler/commands.cpp, sycl/source/detail/scheduler/graph_processor.cpp, sycl/source/detail/scheduler/scheduler.cpp, sycl/source/detail/spec_constant_impl.cpp, sycl/source/detail/sycl_mem_obj_t.hpp, sycl/source/detail/usm/usm_impl.cpp, sycl/source/device_selector.cpp, sycl/source/handler.cpp, sycl/test-e2e/Config/env_vars.cpp, sycl/test-e2e/FilterSelector/select.cpp, sycl/test-e2e/Tracing/code_location_queue_submit.cpp, sycl/unittests/SYCL2020/KernelID.cpp
... instead of deprecated SYCL 1.2 subclasses that we're going to remove during this ABI breaking window. In many cases there is no clear choice of using `errc::runtime` vs `errc::invalid` or something else. I tried to use my best judgement. Reviewers, feel free to start inline discussions in comments if you disagree with my choice(s).
=> [SYCL] More cleanup to use SYCL 2020 `exception`

clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/sycl-offload-new-driver.c, clang/test/Driver/sycl-post-link-options-win.cpp, clang/test/Driver/sycl-post-link-options.cpp, clang/tools/clang-linker-wrapper/ClangLinkerWrapper.cpp
This errors out anyway, so it was just wrong.
=> [SYCL][thinLTO] Don't pass -properties and -ir-output-only to sycl-post-link

sycl/include/sycl/vector_preview.hpp
There seems to be a bug in CodeGen for OpenCL CPU which causes a seg-fault in `vec::convert<>`, when converting to `vec<long, 8>` at O0.
To unblock https://github.com/intel/llvm/pull/14317, this PR proposes a non-functional change as a workaround for the CodeGen bug.
=> [SYCL] Workaround for seg fault in `vec::convert<>` for OpenCL CPU at O0

sycl/test-e2e/Graph/RecordReplay/host_task_last.cpp
The RecordReplay/host_task_last.cpp test failed in https://github.com/intel/llvm/pull/14498 which appears to be the same as was previously reported in https://github.com/intel/llvm/issues/14473. This commit disables the test.
=> Disable RecordReplay/host_task_last

sycl/test-e2e/syclcompat/math/math_byte_dot_product.cpp
The compiler needs to be told which device the `--cuda-gpu-arch` parameter applies to.
=> [SYCL][E2E] Fix another test in multi-device mode

sycl/test-e2e/ESIMD/named_barriers/exec_in_order.cpp, sycl/test-e2e/ESIMD/named_barriers/exec_in_order_branched.cpp, sycl/test-e2e/ESIMD/named_barriers/loop.cpp, sycl/test-e2e/ESIMD/named_barriers/loop_extended.cpp, sycl/test-e2e/ESIMD/named_barriers/multiple_wg.cpp, sycl/test-e2e/ESIMD/named_barriers/single_wg.cpp, sycl/test-e2e/InvokeSimd/Regression/nbarrier_basic.cpp, sycl/test-e2e/InvokeSimd/Regression/nbarrier_exec_in_order.cpp, sycl/test-e2e/InvokeSimd/Regression/nbarrier_loop.cpp, sycl/test-e2e/InvokeSimd/Regression/nbarrier_multiple_wg.cpp
Broken after https://github.com/intel/llvm/commit/b30e6f04766d6ce83c781151d43112ac6e3aa40f but since we don't test on PVC in CI it can only get caught manually.
Thanks to @AlexeySachkov for finding this.
=> [SYCL][ESIMD][E2E] Fix PVC test compilation

sycl/source/detail/plugin.hpp
Remove the version that throws old SYCL 1.2 exception subclasses, inline a few single-use macros.
=> [SYCL] Switch `checkPiResult` to throw SYCL 2020 exceptions only

sycl/include/sycl/detail/group_sort_impl.hpp, sycl/include/sycl/detail/key_value_iterator.hpp
Current name (even though it is in sycl::detail namespace) somehow affects accessor_iterator causing the nightly cts failure: https://github.com/intel/llvm/issues/14517
So rename the function as an easy fix.
=> [SYCL][NFC] Rename custom swap to avoid collision

sycl/test-e2e/lit.cfg.py
Since #9078 (itself a fix for #8854), the SYCL E2E lit config would change the working directory and never set it back. This impeded LIT's ability to discover tests and test suites, when tasked with sourcing multiple.
For example:
llvm-lit sycl/test/A sycl/test/B
LIT would discover test 'A' by appending its relative path to the CWD (e.g., `root/sycl/test/A`) and load up the SYCL E2E lit.cfg. This would change directory into the SYCL build directory. When discovering test 'B' it would append its relative path to the SYCL binary dir and fail to find it (e.g., `root/build/tools/sycl/test-e2e/sycl/test/B`).
This would also have the effect of loading the SYCL E2E LIT config a second time, even though it was already loaded.
With this change, we maintain the CWD but open the temp files using …
=> [SYCL][E2E] Fix multiple test suite discovery

sycl/test-e2e/ESIMD/assert.cpp
When run in parallel with other tests, this is causing a GPU hang and having a significant effect on internal testing.
=> [SYCL][ESIMD][E2E] Disable assert.cpp on Gen12

sycl/source/detail/kernel_program_cache.hpp, sycl/source/detail/scheduler/graph_builder.cpp
Exception subclasses have been removed in SYCL 2020.
=> [SYCL] Remove last uses of `sycl::runtime_error`

sycl/test-e2e/ESIMD/hardware_dispatch.cpp
We need to use tgllp instead of bdw on Windows because the Windows driver doesn't support bdw anymore.
I ran the test manually and it passes, I need to fix some stuff in the CI to get it running here.
Closes: https://github.com/intel/llvm/issues/14336
=> [SYCL][ESIMD][E2E] Fix hardware_dispatch.cpp on Windows

clang/tools/clang-linker-wrapper/ClangLinkerWrapper.cpp
In the old offloading model we have an indirect target dependency because -properties is mutually exclusive with -ir-output-only, and the later option does depend on the triple.
However in the new offloading model we currently don’t ever pass -ir-output-only, so we should always be able to pass -properties, at least for now.
=> [SYCL][ClangLinkerWrapper] Unconditionally pass -properties to sycl-post-link

llvm/lib/SYCLLowerIR/SYCLPropagateAspectsUsage.cpp, sycl/test/check_device_code/optional_kernel_features/fp64-conv-emu-convert.cpp, sycl/test/check_device_code/optional_kernel_features/fp64-conv-emu-test-call-convert.cpp, sycl/test/check_device_code/optional_kernel_features/fp64-conv-emu-test-call.cpp, sycl/test/check_device_code/optional_kernel_features/fp64-conv-emu-with-recursive-type-decls.cpp, sycl/test/check_device_code/optional_kernel_features/fp64-conv-emu.cpp
There are cases where some instructions use data structures that contain double data type deeply nested inside multiple levels.
Example:
struct T1 {
double x;
};
struct T2 {
struct T1 y;
};
T2 x;
In such case, the fp64 emulation support in SYCLPropagateAspectUsage pass was not correctly identifying T2 as a type that has doubles. This led to wrong behavior when adding fp64 aspect.
This PR fixes the issue.
Thanks
=> [SYCL][fp64][SYCLLowerIR] Fix an issue when double type inside multiple nested structs is not identified

clang/lib/Sema/SemaSYCL.cpp
It's caused a build warning when `-Wpedantic` enabled.
=> [NFC] Remove extra semicolon

sycl/test/abi/sycl_classes_abi_neutral_test.cpp
It is difficult to understand how to detect all possible data members which can cross ABI boundaries and cause problems because of dual ABI issue. For now using this approach which  covers most of the classes, more than currently covered by "sycl/test/abi/layout*" tests.
Current hits are in sycl::detail CG classes and subclasses (MFileName, MFunctinName, MKernelName and PipeName string data members). Even though I'm not sure if those cross ABI boundaries or not, I think we have to be conservative and fix those too.
Using -fdump-record-layouts-complete to get  dump for all complete record types, see description in  https://reviews.llvm.org/D104484 for details.
=> [SYCL][Test] Add test for ABI-neutrality of sycl classes

.github/workflows/sycl-windows-run-tests.yml
The `LIT_OPTS` were different compared to Linux so the output logs from CI runs is different. I noticed this when searching for passed tests in the Windows log and noticed it wasn't there.
=> [CI] Make Windows LIT_OPTS match Linux

sycl/test-e2e/OptionalKernelFeatures/fp64-conv-emu.cpp, sycl/test-e2e/ProgramManager/uneven_kernel_split.cpp
I recently found out ocloc tests weren't running in Windows CI because the ocloc tool wasn't installed on the runners.
When trying to fix it, I [hit](https://github.com/intel/llvm/actions/runs/9909706895/job/27379893885?pr=14114) two failures that would have always failed if we were testing (the other two are going to be fixed [here](https://github.com/intel/llvm/pull/14556)).
The first fix disables the test on Windows because it is using `pvc` which is not available on Windows.
The seconds add a requirement for the OCL CPU driver to be installed because the test is using `ocloc-aot`, as per the [ocloc-aot doc](https://github.com/intel/llvm/blob/56e88d591c52a978abdd5e4279853311cae4a55e/opencl/opencl-aot/README.md?plain=1#L11).
The CI testing in this PR is only confirming I didn't break …
=> [SYCL][E2E] Fix two Windows ocloc tests

sycl/source/detail/kernel_compiler/kernel_compiler_sycl.cpp, sycl/test-e2e/KernelCompiler/kernel_compiler_sycl.cpp
kernel_compiler include_file support shouldn't have files that might collide. Spec has been recently clarified as well  ( https://github.com/intel/llvm/pull/11985/commits/a6d875830cf489b6148e543ef2b515c428a4a38c )
=> [SYCL] kernel_compiler include file paths collision fix

sycl/include/syclcompat/device.hpp, sycl/test-e2e/syclcompat/device/device.cpp, sycl/test-e2e/syclcompat/device/device_profiling.cpp
The codepath which enabled profiling in syclcompat queues was neither working nor properly tested.
- Fixes `sycl::property::queue::enable_profiling` being added to queue properties if SYCLCOMPAT_PROFILING_ENABLED is defined
- Tests added for both SYCLCOMPAT_PROFILING_ENABLED defined and undefined.
- Refactors `create_queue_impl` to accept a list of properties instead of a series of bools to enable properties.
- Refactor does not affect public API.
=> [SYCL][COMPAT] Fixes SYCLCOMPAT_PROFILING_ENABLED codepath

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/defs.hpp, sycl/test-e2e/syclcompat/defs.cpp
This PR defines a version for SYCLcompat via `SYCLCOMPAT_VERSION` and related macros. It also defines a release process for SYCLcompat with respect to oneAPI's product releases.
=> [SYCL][COMPAT] Add version & release process

sycl/test-e2e/syclcompat/math/math_vectorized_isgreater_test.cpp
The second test case in sycl/test-e2e/syclcompat/math/math_vectorized_isgreater_test.cpp uses vector of sycl::half, which requires devices to support aspect::fp16. This commit makes the test skip this case if the device does not support the aspect.
=> [syclcompat][E2E] Skip case in math_vectorized_isgreater_test if fp16 unsupported

sycl/doc/extensions/supported/sycl_ext_intel_device_info.md
When an aspect is not supported by a device, the `ext_intel_device_info` spec says to throw an invalid object runtime error when calling `get_info` with the corresponding descriptor. This error description is both vague and not very descriptive of the actual thing that went wrong, namely that the query is simply not supported by a device. This PR changes that to instead say to throw a feature not supported runtime error.
=> [SYCL] Change the ext_intel_device_info spec to throw a feature not supported error when a query is not supported

sycl/test-e2e/AOT/double.cpp, sycl/test-e2e/AOT/reqd-sg-size.cpp
Windows ocloc currently doesn't run in CI, and I'm trying to enable it. I hit failures here when trying to enable it. See run [here](https://github.com/intel/llvm/actions/runs/9960990637/job/27525889216?pr=14114).
```
...
...
```
=> [SYCL][E2E] Fix more Windows AOT tests

sycl/test-e2e/syclcompat/math/math_extend.cpp, sycl/test-e2e/syclcompat/math/math_extend_v_2.cpp, sycl/test-e2e/syclcompat/math/math_extend_v_4.cpp
The `math_extend*cpp` tests were very slow despite not doing a huge amount of work. This PR accelerates these tests with the following changes:
- Split into several different kernels
- Replace `parallel_for` with `single_task`
- Avoid branching return statements
- Avoid storing function names as `char` arrays in kernel
- Avoid `sycl::stream` for output
Locally, the `math_extend_v_4.cpp` tests are about 5x faster. The other 2 are around 2x faster.
=> [SYCL][COMPAT] Fix slow math_extend tests

sycl/test-e2e/ESIMD/lsc/lsc_usm_store_u32_64.cpp
Same as https://github.com/intel/llvm/commit/9b4b4ddb1957cdc8c2a68b9c873772f04a3eafeb but for this version of the test.
=> [SYCL][ESIMD][E2E] Fix another LSC test on Windows

.github/workflows/sycl-post-commit.yml
You can see it seems to work [here](https://github.com/intel/llvm/actions/runs/9980873784).
Example:
```
build-win / Build + LIT
Canceling since a higher priority waiting request for 'SYCL Post Commit-14606' exists
```
=> [CI] Cancel postcommit jobs on new commit

sycl/include/sycl/kernel.hpp, sycl/test/basic_tests/handler/unnamed-lambda-functor.cpp, sycl/test/basic_tests/handler/unnamed-lambda-negative.cpp
Currently the SYCL headers checks for unnamed lambdas in the case where they have been disabled. However, this falsely flags functor objects which should not be covered by the unnamed lambda restriction. Luckily, the compiler already issues diagnostics for illegal unnamed lambdas, so this patch removes the check from the headers and instead relies on the frontend for issuing diagnostics for the illegal cases.
=> [SYCL] Remove unnamed lambda check from headers

sycl/include/sycl/detail/group_sort_impl.hpp, sycl/include/sycl/ext/oneapi/experimental/group_helpers_sorters.hpp, sycl/test-e2e/GroupAlgorithm/SYCL2020/group_sort/key_value_sort.cpp
* Change `memory_required` queries to return the exact size of local memory which needs to be allocated for `group_sort` algorithm, currently it is a bit more than required.
* Fix a bug in `align_key_value_scratch` where I didn't take into account that `std::align` changes value of `KeysScratchSpace`. To find scratch of the values I need to use original value of this variable.
* Fix mistake in the test where keys/values were mixed up. This is more of a cosmetic change.     
RunSortKeyValueOverGroup functions accepts two vectors - the first is considered keys, and the second is considered values.
Verification is done in the same function (with the same assumption that the first vector is keys and the second is values).
So it doesn't actually matter in which order  aforementioned arguments …
=> [SYCL] Follow up fixes for group_sort extension

sycl/test-e2e/Basic/built-ins/marray_geometric.cpp, sycl/test-e2e/KernelCompiler/kernel_compiler_spirv.cpp
These are passing in the nightly after the CPU RT uplift a few days ago
https://github.com/intel/llvm/actions/runs/9984827095/job/27595152217
```
Unexpectedly Passed Tests (2):
SYCL :: Basic/built-ins/marray_geometric.cpp
SYCL :: KernelCompiler/kernel_compiler_spirv.cpp
```
Closes: https://github.com/intel/llvm/issues/13397
=> [SYCL][E2E] Remove XFAIL from two passing tests

sycl/test/abi/layout_handler.cpp
The layout of handler was recently changed, which changed the layout_handler ABI test. However, part of the check is slightly different on other systems, so this commit relaxes the check slightly.
=> [SYCL][NFC] Relax layout_handler test after recent handler changes

sycl/unittests/Extensions/CMakeLists.txt, sycl/unittests/Extensions/ProfilingTag.cpp
This commit adds unit tests for the sycl_ext_oneapi_profiling_tag extension implementation.
=> [SYCL][Unittests] Add sycl_ext_oneapi_profiling_tag unit tests

sycl/test/native_cpu/vector-add.cpp
Data was not guaranteed to be copied back in `sycl/test/native_cpu/vector-add.cpp`, this PR fixes it.
=> [SYCL][NATIVECPU] Fix vector add test

.github/workflows/sycl-windows-run-tests.yml, sycl/test-e2e/lit.cfg.py
Example run: https://github.com/intel/llvm/actions/runs/9986151153/job/27599398329#step:12:2215
=> [CI] Fix detection of `level_zero_dev_kit` LIT feature on Win CI with L0

clang/lib/Driver/Driver.cpp, clang/lib/Driver/ToolChains/SYCL.cpp, clang/lib/Driver/ToolChains/SYCL.h, clang/test/Driver/sycl-device-traits-macros.cpp
The SYCL device traits settings were being performed within the old model specific action builder class.  Move this to the SYCL toolchain area to be accessible by both the new and old offloading model.  Also hookup the new offloading model portion of this.
=> [Driver][SYCL] Move traits macros settings to enable new model

sycl/doc/extensions/supported/sycl_ext_intel_device_info.md
Clarify the specification of the `ext::intel::info::device::free_memory` query.
=> [SYCL][Doc] Clarify "free_memory" query

sycl/source/handler.cpp
https://github.com/intel/llvm/pull/14638 introduced a warning in post-commit, which is in turn handled like an error. This commit fixes this warning.
=> [SYCL][NFC] Fix post-commit build failure

.github/CODEOWNERS
These are testing a feature owned by the tools team.
=> [SYCL] Update CODEOWNERS for new offloading model E2E tests

.github/workflows/sycl-linux-run-tests.yml
Fix was [merged](https://github.com/KhronosGroup/SYCL-CTS/pull/907) to CTS.
Manual nightly run with this change: https://github.com/intel/llvm/actions/runs/10045951175/job/27765157126
Closes: https://github.com/intel/llvm/issues/14478
=> [CI] Remove SYCL CTS build workaround

sycl/include/sycl/aliases.hpp, sycl/include/sycl/detail/common.hpp, sycl/include/sycl/detail/defines_elementary.hpp, sycl/include/sycl/detail/generic_type_lists.hpp, sycl/include/sycl/detail/vector_arith.hpp, sycl/include/sycl/sub_group.hpp, sycl/include/sycl/vector_preview.hpp, sycl/test/abi/layout_vec.cpp, sycl/test/basic_tests/vectors/size_one_checks.cpp, sycl/test/check_device_code/vector/vector_bf16_builtins.cpp, sycl/test/check_device_code/vector/vector_convert_bfloat.cpp, sycl/test/check_device_code/vector/vector_math_ops.cpp
Template vs. non-template conversion operator behave differently for
```
sycl::vec<int, 1> v;
std::ignore = static_cast<bool>(v);
```
where non-template path selects the conversion operator and then uses implicit `int->bool` conversion while the example fails to compile when operator is a template.
This is important because the spec requires `vec::x()` and other swizzles to return a swizzle class and not a `const DataT &` that it currently does. However, if we'd fix the swizzle without addressing this issues first the code like
```
sycl::vec<int, 8> v = {...};
if (v.x() == 42)
...
```
would fail to compile.
=> [SYCL] Make `vec` conversion operator to scalar non-template

sycl/unittests/SYCL2020/IsCompatible.cpp, sycl/unittests/SYCL2020/KernelBundle.cpp, sycl/unittests/SYCL2020/KernelBundleStateFiltering.cpp, sycl/unittests/buffer/KernelArgMemObj.cpp, sycl/unittests/helpers/MockKernelInfo.hpp, sycl/unittests/helpers/PiImage.hpp, sycl/unittests/helpers/TestKernel.hpp, sycl/unittests/kernel-and-program/Cache.cpp, sycl/unittests/kernel-and-program/MultipleDevsCache.cpp, sycl/unittests/kernel-and-program/OutOfResources.cpp, sycl/unittests/pipes/host_pipe_registration.cpp, sycl/unittests/queue/GetProfilingInfo.cpp
Introduced a macro to hide bolierplate of specializing `KernelInfo` structs.
Added a helper function to generate default image to avoid repeating the same code in every test.
=> [SYCL][NFC] Introduce more helpers to unittests

clang/include/clang/Driver/Options.td, clang/test/Driver/flink-huge-device-code.cpp, clang/test/Driver/sycl-deprecated.cpp, sycl/doc/UsersManual.md
The `-fsycl-link-huge-device-code` option has been deprecated for over a
year in favor of `-flink-huge-device-code`. This change removes the
deprecated option.
=> [Driver][SYCL] Remove `-fsycl-link-huge-device-code`

clang/lib/Basic/Targets/NVPTX.cpp, clang/test/Preprocessor/cuda-ptx-versioning.cu
Define __PTX_VERSION__ macro to indicate the used PTX version.
Usually each new PTX version brings a new sm version and the associated instructions. However, some of these instructions can also be made avialable to older sm. This allows applications to check more accuratly for available instructions.
=> [clang][NVPTX] Define macro indicating the PTX version

clang/tools/clang-linker-wrapper/ClangLinkerWrapper.cpp, sycl/test-e2e/NewOffloadDriver/buffer.cpp
I hit this working on thinLTO using the SPIR-V backend, but it's reproducible just with the triple.
=> [SYCL][ClangLinkerWrapper] Fix SYCL binary creation with spirv64 triple

sycl/test-e2e/EnqueueNativeCommand/custom-command-cuda.cpp, sycl/test-e2e/EnqueueNativeCommand/custom-command-multiple-dev-cuda.cpp, sycl/test-e2e/Printf/char.cpp, sycl/test-e2e/Printf/float.cpp, sycl/test-e2e/Printf/long.cpp, sycl/test-e2e/syclcompat/atomic/atomic_class.cpp, sycl/test-e2e/syclcompat/atomic/atomic_fixt.hpp
- The test [atomic_class.cpp](https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/syclcompat/atomic/atomic_class.cpp) modified to call host function after kernel function finishes. This is because CUDA on Windows does not support accessing host memory while a kernel is running, as discussed in [this forum post](https://forums.developer.nvidia.com/t/cudamallocmanaged-clarification-needed/67611) and [this bug report](https://developer.nvidia.com/bugs/4763389). 
- A number of previously XFAILed printf tests have been enabled for execution on Windows/CUDA. 
- Updated the relevant tests to include the necessary CUDA library and include paths for running tests on Windows.
=> [SYCL][E2E] Disable unsupported tests and enable validated tests for Windows/CUDA

sycl/test-e2e/KernelCompiler/sycl_device_flags.cpp
After my last fix, another problem appeared (but only in post-commit). This is a blind fix for that.  Let me see if I can run that post-commit pass from GitHub Actions.
The premature exit if compilation is not available was leading to test failures once the test tried to call grep. I'm moving that check into the test app itself, rather than use a `// RUN: ` directive.
Ultimately, we may want something like `// REQUIRE: kernel_compiler::lang::sycl`  but this is not the time/place for that.
=> [SYCL][E2E] Only grep if compilation is supported in KernelCompiler/sycl_device_flags.cpp

clang/lib/Driver/Driver.cpp, clang/test/Driver/sycl-host-compiler-old-model.cpp
When using -save-temps, the driver will break down each compilation step to multiple steps (preprocess, ir, asm, obj) for a good gathering of all of the files needed for compilation.  When performing offload compilations, this behavior is valid with the exception of using a third party compiler with -fsycl-host-compiler.  The reason it does not work is due to the fact that the third party compiler may or may not support these separate step creations, so we error out letting the user know.
Update the behavior of the driver to collapse all of these compilation steps into one so only the object creation step is performed when doing the third party compilation.
=> [SYCL][Driver] Allow for -save-temps to work with -fsycl-host-compiler

clang/lib/Driver/SanitizerArgs.cpp, clang/test/Driver/sycl-device-sanitizer.cpp
We have enabled private mem check by default, but we don't have plan to support use-after-return and use-after-scope check now. So, disable related options by default now.
=> [DeviceSanitizer] Disable unsupported features for private mem check

sycl-fusion/passes/kernel-fusion/SYCLSpecConstMaterializer.cpp, sycl/source/detail/program_manager/program_manager.cpp
This commit avoids the following warnings in post-commit testing:
* SYCLSpecConstMaterializer had a loop purely for debug printing. If `NDEBUG` is defined, the loop variable is unused, which causes a warning. To address this, the use of `LLVM_DEBUG` is moved to outside the full debug printing body.
* In program_manager, debug printing now checks whether debug printing is enabled using `if constexpr`. This now means that `getFormatStr` is unused, which in turn causes a warning. This commit marks it as potentially unused to avoid this warning.
=> [SYCL][NFC] Avoid warnings in SYCLSpecConstMaterializer and program_manager

sycl/test-e2e/AddressSanitizer/lit.local.cfg
Following the merge of https://github.com/intel/llvm/pull/13450 there were reports of failures on PVC & DG2:
* https://github.com/intel/llvm/pull/14720#issuecomment-2248649742
* https://github.com/intel/llvm/pull/13450#issuecomment-2249736888
This patch the suggestion in https://github.com/intel/llvm/pull/14720#issuecomment-2249798071 to disable AddressSanitizer testing on PVC & DG2 devices.
=> [SYCL][ASan] Mark PVC & DG2 as unsupported in E2E tests

sycl/include/sycl/ext/intel/esimd/memory.hpp, sycl/test-e2e/ESIMD/regression/fp_atomic_update.cpp, sycl/test/check_device_code/esimd/memory_properties_atomic_update.cpp
FP/double atomic support is emulated on PVC, and the types need to be accurate for the emulation to work correctly. We already do a similar thing for slm_atomic_update.
=> [SYCL][ESIMD] Don't cast data to int for atomic_update

sycl/test-e2e/VirtualFunctions/2/2/single-construct-single-use.cpp, sycl/test-e2e/VirtualFunctions/helpers.hpp
Test plan can be found in #10540. This PR introduces a basic test case for a scenario where object of a polymorphic class is constructed in one kernel, but used in another kernel.
=> [SYCL] Add one more test for virtual functions

sycl/test-e2e/DeviceLib/imf_fp32_rounding_test.cpp, sycl/test-e2e/DeviceLib/imf_fp64_rounding_test.cpp, sycl/test-e2e/KernelCompiler/sycl_device_flags.cpp
This PR makes minor fixes to a few tests.  
Improves sycl_device_flags.cpp so that it not dependent on the stable but inscrutable hash `OCL_asmaf99e2d4667ef6d3` appearing in any file names.  Removes some stray comment markers.
=> [SYCL] small e2e test fixes

sycl/include/sycl/ext/intel/experimental/fpga_kernel_properties.hpp, sycl/include/sycl/ext/oneapi/experimental/enqueue_functions.hpp, sycl/include/sycl/ext/oneapi/kernel_properties/properties.hpp, sycl/include/sycl/ext/oneapi/properties/property.hpp, sycl/include/sycl/handler.hpp, sycl/test/extensions/properties/kernel_properties_negative.cpp, sycl/test/extensions/properties/properties_kernel.cpp, sycl/test/extensions/properties/properties_kernel_fpga.cpp, sycl/unittests/Extensions/CMakeLists.txt, sycl/unittests/Extensions/KernelProperties.cpp
The current implementation of the enqueue free functions taking both a launch_config and a kernel do not properly process the properties. This commit addresses this and adds a static assert about the properties passed to these only applying to the launch of the kernel and not how the compiler handles compiling the kernel.
=> [SYCL] Fix enqueue functions taking both kernel and properties

.github/workflows/docs.yml, .github/workflows/release-documentation.yml, .github/workflows/release-doxygen.yml, .github/workflows/sycl-docs.yml, sycl/doc/GetStartedGuide.md, sycl/plugins/unified_runtime/CMakeLists.txt, sycl/test-e2e/Basic/get_info_aspect.cpp
Testing PR for: https://github.com/oneapi-src/unified-runtime/pull/1430
=> [UR] Bump UR version and enable dynamic linking with UMF

devops/dependencies-igc-dev.json, sycl/test-e2e/ESIMD/hardware_dispatch.cpp, sycl/test-e2e/lit.cfg.py, sycl/test-e2e/lit.site.cfg.py.in
=> [GHA] Uplift Linux IGC Dev RT version to igc-dev-15caa46

llvm/test/tools/sycl-post-link/multiple-filtered-outputs.ll, llvm/tools/sycl-post-link/sycl-post-link.cpp
Previously, when compiling with any `intel_gpu_*` target, the device image only had the generic `spir64_gen` as its value for the [`DeviceTargetSpec`](https://github.com/intel/llvm/blob/450683b6fa1d1be1b9391905f43073b7a9555aa1/sycl/include/sycl/detail/pi.h#L1143) in its device image, so there was no way to differentiate device images compiled for a specific GPU in the runtime. Now, a new property is added to the image specifying the specific `intel_gpu_*` value it is compiled for.
=> [SYCL] Add compile target to device image properties

llvm/lib/Transforms/Instrumentation/AddressSanitizer.cpp, llvm/test/Instrumentation/AddressSanitizer/SPIRV/no_return.ll
'__asan_handle_no_return' is used to unpoison stack before non return calls.
And we didn't poison stack in device code, so we don't need to handle such
case.
=> [DeviceSanitizer] Disable handling no return calls

.github/workflows/sycl-macos-build-and-test.yml, sycl/plugins/unified_runtime/CMakeLists.txt
`hwloc` became a dependency after https://github.com/intel/llvm/pull/13343 was merged. CI infrastructure has been updated to have `hwloc` installed, but it's still missing on macOS runner.
Additionally, UMF compile options caused errors on SYCL runners that should be resolved after UR version bump included in this patch.
Logs: https://github.com/intel/llvm/actions/runs/10106492701/job/27948711331 and https://github.com/intel/llvm/actions/runs/10106492701/job/27948711538.
=> [CI] Fix CI issues caused by recent UR version bump

sycl/test-e2e/Basic/fpga_tests/fpga_pipes.cpp
I am unable to recreate #14308, and there is not enough information about when this case flakes. To collect this information, I have:
- Re-enabled fpga_pipes.cpp
- Added debug prints
Which would provide more insight when the test fails.
=> [SYCL][E2E] Temporarily re-enable Basic/fpga_tests/fpga_pipes.cpp

sycl/source/detail/device_info.hpp, sycl/test-e2e/Basic/get_info_aspect.cpp
This PR implements specializations of `get_device_info` function for the queries defined in [sycl_ext_intel_device_info](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_intel_device_info.md) so that when a device does not support the corresponding aspect for a query, an exception is thrown with error code set to `errc::feature_not_supported` as stipulated in the extension spec.
=> [SYCL] Throw exception when device does not support queries in sycl_ext_intel_device_info

sycl/test-e2e/TaskSequence/in-order-async-get.cpp, sycl/test-e2e/TaskSequence/mult-and-add.cpp, sycl/test-e2e/TaskSequence/multi-kernel-task-function-reuse.cpp, sycl/test-e2e/TaskSequence/producer-consumer.cpp, sycl/test-e2e/TaskSequence/struct-array-args-and-return.cpp
This change disables task sequence tests that are failing in post-commit. The tests will be reenabled when the fpga emulator changes are in.
=> Disable all Task Sequence tests

sycl/doc/design/SharedLibraries.md
Describe behavior of sycl-post-link in support of dynamic linking
=> [NFC] Describe sycl-post-link support for dynamic linking

.github/CODEOWNERS
https://github.com/intel/llvm/pull/14145 added, moved, and removed files owned by the `unified-runtime-reviewers` team. This patch updates the CODEOWNERS file accordingly.
=> Update UR codeowners after removing PI

llvm/lib/SYCLLowerIR/ESIMD/LowerESIMD.cpp, llvm/test/SYCLLowerIR/ESIMD/lower_llvm_intrin.ll, sycl/include/sycl/ext/intel/esimd/detail/math_intrin.hpp, sycl/include/sycl/ext/intel/esimd/math.hpp, sycl/include/sycl/ext/intel/experimental/esimd/detail/math_intrin.hpp, sycl/include/sycl/ext/intel/experimental/esimd/math.hpp, sycl/test/regression/esimd/abs.cpp, sycl/test/regression/esimd/clz.cpp, sycl/test/regression/esimd/ctz.cpp, sycl/test/regression/esimd/fabs.cpp, sycl/test/regression/esimd/fma.cpp, sycl/test/regression/esimd/fmax.cpp, sycl/test/regression/esimd/fmin.cpp, sycl/test/regression/esimd/popcount.cpp
ESIMD headers declare some of `__spirv_ocl_*` built-ins as template functions, but those built-ins are also automatically declared by the compiler implicitly when used.
On Windows, redeclarations in headers cause compilation issues, because by some reason they take priority, but template arguments for them couldn't be inferred.
This commit effectively introduces new tests to cover affected scenarios and reverts a couple of ESIMD commits to fix the issue:
- intel/llvm#14020 is completely reverted
- intel/llvm#13383 is partially reverted to preserve new interfaces and tests, but stop declaring `__spirv_ocl_*` built-ins
I suppose that both PRs were made in attempt to move away from custom ESIMD intrinsic to standard SPIR-V ones, but that should be done without manually declaring the latter. …
=> [SYCL] Fix using some of math built-ins when ESIMD is included

sycl-fusion/passes/kernel-fusion/SYCLSpecConstMaterializer.cpp
Two concurrent PRs added a new use of and simultaneously removed this enum. Commit 63c61d85 added a new use, while dc37699b was trying to delete it.
=> [SYCL] Fix use of removed ArchType enum

sycl/test-e2e/AddressSanitizer/common/kernel-debug.cpp, sycl/test-e2e/AddressSanitizer/multiple-reports/multiple_kernels.cpp, sycl/test-e2e/AddressSanitizer/multiple-reports/one_kernel.cpp, sycl/test-e2e/AddressSanitizer/use-after-free/quarantine-free.cpp
These are due to a known regression introduced by the PI removal patch, we have a fix but for now it's more expedient to simply disable the tests and unblock the nightly workflow.
=> [SYCL] Mark ASAN tests that are failing the nightly as unsupported.

sycl/include/sycl/bit_cast.hpp, sycl/include/sycl/detail/group_sort_impl.hpp, sycl/include/sycl/detail/memcpy.hpp, sycl/include/sycl/detail/spirv.hpp, sycl/include/sycl/ext/oneapi/experimental/bfloat16_math.hpp, sycl/include/sycl/ext/oneapi/experimental/builtins.hpp, sycl/include/sycl/ext/oneapi/sub_group_mask.hpp
`detail::memcpy`, even though in a different namespace, can cause ambiguity with libc's `memcpy`, due to argument dependent lookup (ADL).
For example, the compiler throws a compilation error due to `memcpy` ambiguity in the following code:
```
#include <sycl/vector.hpp>
template <typename T>
void foo(T *dst, T *src, size_t count) {
memcpy(dst, src, count * sizeof(T));
}
using T = sycl::vec<int, 1>;
SYCL_EXTERNAL void bar(T *dst, T *src, size_t count) {
foo(dst, src, count * sizeof(T));
}
```
Compilation error:
```
memcpy_test.cpp:5:4: error: call to 'memcpy' is ambiguous
5 |           memcpy(dst, src, count * sizeof(T));
|           ^~~~~~
memcpy_test.cpp:11:4: note: in instantiation of function template specialization 'foo<sycl::vec<int, 1>>' requested here
11 |           foo(dst, src, …
```
=> [SYCL] Rename `detail::memcpy` to `detail::memcpy_no_adl`

sycl/test-e2e/ESIMD/unified_memory_api/atomic_update_acc_dg2_pvc_cmpxchg.cpp, sycl/test-e2e/ESIMD/unified_memory_api/atomic_update_usm_dg2_pvc_cmpxchg.cpp
When using L0 we always see the x.y.zzzzz style version, even on Windows. These tests were incorrectly running on Windows because of this problem.
=> [SYCL][ESIMD] Fix driver check in two tests

sycl/test-e2e/Matrix/get_coord_int8_matB.cpp
It's passing in the new driver uplift:
https://github.com/intel/llvm/actions/runs/10164787306/job/28112343861
=> [SYCL] Fix XPASS of Matrix test on new GPU driver

sycl/test-e2e/syclcompat/memory/memory_async.cpp
These are failing intermittently, possibly due to runtime race condition.
=> [SYCL][COMPAT] Disable memory_async.cpp tests

sycl/test-e2e/ESIMD/addc.cpp, sycl/test-e2e/ESIMD/subb.cpp
https://github.com/intel/llvm/issues/14868
=> [SYCL][ESIMD][E2E] Disable two tests hanging on Windows

sycl/doc/extensions/proposed/sycl_ext_oneapi_barrier.asciidoc
ptrdiff_t is declared in std namespace.
Define syclex namespace alias used in the usage examples.
=> [SYCL][Doc] Fix ptrdiff_t type namespace qualifier

sycl/source/detail/device_binary_image.cpp, sycl/source/detail/program_manager/program_manager.cpp, sycl/test-e2e/Basic/reqd_work_group_size.cpp, sycl/test-e2e/DeviceGlobal/device_global_arrow.cpp, sycl/test-e2e/DeviceGlobal/device_global_device_only.cpp, sycl/test-e2e/DeviceGlobal/device_global_operator_passthrough.cpp, sycl/test-e2e/DeviceGlobal/device_global_subscript.cpp, sycl/test-e2e/KernelFusion/lit.local.cfg, sycl/test-e2e/NewOffloadDriver/diamond_shape.cpp
SYCL properties weren't converted when calling creatreURProgram, leading to issue in finalization during KernelFusion for AMD.
Fixes #14841
=> [SYCL][AMD] Propagate metadata in createURProgram

llvm/include/llvm/SYCLLowerIR/SpecConstants.h, llvm/lib/Passes/PassBuilder.cpp, llvm/lib/Passes/PassRegistry.def, llvm/lib/SYCLLowerIR/SpecConstants.cpp, llvm/test/SYCLLowerIR/SpecConstants/literal-address-alloca-asan.ll
Adjust spec constant pattern match for base alloca + offset case in device sanitizer.
Address sanitizer merges static allocas into a large layout base alloca and original alloca is replaced with base + offset.
=> [sycl-post-link] Fix spec constant pattern match for DeviceSanitizer

sycl/cmake/modules/FetchUnifiedRuntime.cmake, sycl/test-e2e/Basic/host-task-dependency.cpp, sycl/test-e2e/DiscardEvents/discard_events_accessors.cpp, sycl/test-e2e/DiscardEvents/discard_events_using_assert.cpp, sycl/test-e2e/DiscardEvents/discard_events_using_assert_ndebug.cpp, sycl/test-e2e/DiscardEvents/discard_events_usm.cpp, sycl/test-e2e/DiscardEvents/discard_events_usm_ooo_queue.cpp, sycl/test-e2e/ESIMD/sycl_esimd_mix.cpp, sycl/test-e2e/Plugin/level_zero_batch_barrier.cpp, sycl/test-e2e/Plugin/level_zero_dynamic_batch_test.cpp, sycl/test-e2e/Scheduler/HostAccDestruction.cpp, sycl/test-e2e/Scheduler/MemObjRemapping.cpp
Tests https://github.com/oneapi-src/unified-runtime/pull/1884
Fixes #14704 
Fixes #14721
=> Bump UR tag to include PrintTrace fix

sycl/test-e2e/XPTI/basic_event_collection_linux.cpp
The test was expecting 'kernel_name' metadata on an edge_create event which should not exist
It was still sometimes matching anyway but appears to have been a fluke and not intended behavior.
Fixes https://github.com/intel/llvm/issues/14744
=> [SYCL] Fix XPTI/basic_event_collection_linux failure

sycl/cmake/modules/FetchUnifiedRuntime.cmake, sycl/test-e2e/AddressSanitizer/bad-free/bad-free-minus1.cpp, sycl/test-e2e/AddressSanitizer/bad-free/bad-free-plus1.cpp, sycl/test-e2e/AddressSanitizer/double-free/double-free.cpp, sycl/test-e2e/AddressSanitizer/use-after-free/quarantine-no-free.cpp, sycl/test-e2e/AddressSanitizer/use-after-free/use-after-free.cpp
Reverts intel/llvm#14513
This reverts commit 56b1410652d39deba76c3d7075d0c1e93d732232.
Build in postcommit broken https://github.com/intel/llvm/actions/runs/10196353773
=> Revert "[UR][DeviceSantizer] Enable Symoblizer for UR santizer layer (#14513)

sycl/test/abi/sycl_classes_abi_neutral_test.cpp
Layout is slightly different on systems like RHEL8 with older libstdc++. Adjust regexp accordingly.
=> [SYCL] Fix abi-neutrality test for older libstdc++ versions

sycl/test-e2e/Graph/Explicit/kernel_bundle.cpp, sycl/test-e2e/Graph/RecordReplay/kernel_bundle.cpp
For https://github.com/intel/llvm/issues/14763
=> Re-enable test-e2e/Graph/RecordReplay/kernel_bundle.cpp

sycl/test-e2e/OneapiDeviceSelector/illegal_input.cpp
replace XFAIL approach with "not" usage in RUN
=> [SYCL][NFC] change negative test verification for ONEAPI_DEVICE_SELECTOR

sycl/test-e2e/bindless_images/dx12_interop/read_write_unsampled.cpp, sycl/test-e2e/bindless_images/dx12_interop/read_write_unsampled.h
- fix for https://github.com/intel/llvm/pull/14444
=> [SYCL][Bindless] Fix dx12 interop samples for new external type names

sycl/source/detail/program_manager/program_manager.cpp, sycl/unittests/program_manager/arg_mask/EliminatedArgMask.cpp
`map.insert` doesn't insert values if the set already contains them. This can happen when UR/PI happens to reuse the same program pointer that it used for a previous program.
--
This was causing some tests in the PI 2 UR conversion to randomly fail, including at least #14765 .
Fixes #14819.
=> [SYCL] Change NativePrograms.insert to `[]` access

sycl/CMakeLists.txt
This to align with what we had before PI removal.
We need at least the /EHsc flag to be able to build UR in some Windows
systems.
=> [SYCL] Move MSVC flags setting before FetchUR

sycl/include/sycl/ext/oneapi/bindless_images_mem_handle.hpp
Fix debug build issue
[-Werror,-Wmicrosoft-include] llvm\include\sycl\handler.hpp:52:
=> [SYCL] Include sycl path in Bindless image hpp

devops/cts_exclude_filter_L0_GPU, devops/cts_exclude_filter_OCL_CPU
https://github.com/intel/llvm/issues/14819 has been fixed, so turning the tests back on.
=> [CI][CTS] Turn on test_queue & spec_constants

clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/linker-wrapper-sycl.cpp, clang/test/Driver/sycl-dump-device-code-old-model.cpp, clang/test/Driver/sycl-dump-device-code.cpp, clang/tools/clang-linker-wrapper/ClangLinkerWrapper.cpp, clang/tools/clang-linker-wrapper/LinkerWrapperOpts.td
This option allows to save generated SPIRV files in the specified directory.
=> [SYCL][NewOffloadingModel] Add sycl-dump-device-code command line option

sycl/test-e2e/ESIMD/api/functional/ctors/ctor_load_usm_fp_extra.cpp
The test was disabled on Linux but the error message shows it failed on Windows:
```
```
`AppData` is a Windows folder and the linked PRs show it failing in the Windows job (example [here](https://github.com/intel/llvm/actions/runs/9994419232/job/27630212012))
The test isn't failing on Windows where the issue was reported to occur, so just remove the wrong `UNSUPPORTED` line.
Closes: https://github.com/intel/llvm/issues/14650
=> [SYCL][ESIMD][E2E] Re-enable ctor_load_usm_fp_extra.cpp

sycl/test-e2e/Graph/Explicit/host_task_last.cpp, sycl/test-e2e/Graph/RecordReplay/host_task_last.cpp
We were using the `x` prefix to the `RUN` lit command to comment out a `RUN` check. However, LIT still detects this as a `RUN` command, which illustrated in a CI fail of this test recently https://github.com/intel/llvm/actions/runs/10198164930/job/28215254220
Fixed by changing `xRUN` to `RUNx` which I've verified locally is not detected as a `RUN` command by LIT, and can be used to comment the `RUN` command out.
Relates to https://github.com/intel/llvm/issues/14473
=> [SYCL][Graph] Fix E2E disabled RUN lines 

sycl/cmake/modules/FetchUnifiedRuntime.cmake
Included PRs:
* https://github.com/oneapi-src/unified-runtime/pull/1917
* https://github.com/oneapi-src/unified-runtime/pull/1906
* https://github.com/oneapi-src/unified-runtime/pull/1896
* https://github.com/oneapi-src/unified-runtime/pull/1810
* https://github.com/oneapi-src/unified-runtime/pull/1812
* https://github.com/oneapi-src/unified-runtime/pull/1929
=> bump UR to 9b93cb1c

sycl/source/detail/program_manager/program_manager.cpp, sycl/source/detail/program_manager/program_manager.hpp
4f86ab replaced `insert` with `[]` in order to fix a pointer re-use issue, however that was not the correct fix. Instead, a multimap was incorrectly converted to a regular map during the PI->UR conversion.
This change reverts the rest of 4f86ab (besides the test, which is still valid), and converts NativePrograms back to a multimap.
---
Thanks to @AlexeySachkov for finding the real issue in https://github.com/intel/llvm/pull/14873#issuecomment-2268881513
=> [SYCL] Switch NativePrograms back to using multimap

sycl/test/CMakeLists.txt
e.g.
```
$ ninja check-sycl-dumps
[...]
```
=> [SYCL] Add missing test dependency on FileCheck

llvm/lib/Transforms/Instrumentation/AddressSanitizer.cpp, llvm/test/Instrumentation/AddressSanitizer/SPIRV/byval_arg.ll
If a function argument has byval attribute, asan pass will alloca a memory in function
body and copy the argument's value to it. We need to make sure the argument and alloca
memory have the same address space to avoid type mismatch problem.
=> [DeviceSanitizer] Fix addr space mismatch for byval arguments

llvm/lib/SYCLLowerIR/SYCLCreateNVVMAnnotations.cpp
This was quite rightly breaking the post-commit MacOS build.
=> [SYCLLowerIR] Fix size_t/uint64_t confusion

sycl/include/sycl/backend.hpp, sycl/test-e2e/EnqueueNativeCommand/custom-command-cuda.cpp, sycl/test-e2e/EnqueueNativeCommand/custom-command-multiple-dev-cuda.cpp
UR cast is using reinterpret cast under the hood, which was failing for an 
unsigned long being cast to an unsigned long long. From the C++ spec:
> An expression of integral, enumeration, pointer, or pointer-to-member 
type can be converted to its own type. The resulting value is the same as 
the value of expression.
Since `unsigned long` is not the same type as `unsigned long long`, the
`reinterpret_cast` fails.
Ping @aarongreig
=> [SYCL][UR] Use static cast instead of ur::cast

sycl/source/detail/kernel_compiler/kernel_compiler_opencl.cpp, sycl/test-e2e/KernelCompiler/opencl_queries.cpp
The optional parameter `VersionPtr` is `nullptr` by default. But, the code assumes it is a valid pointer.
So, the fix is to guard with an `if` conditional phrase.
=> [SYCL] Fix Kernel Compiler OpenCLC_Supports_Extension

.github/workflows/sycl-linux-precommit.yml, .github/workflows/sycl-post-commit.yml
The HIP runner is unstable, so move it to post-commit for now.
=> [CI] Move HIP testing to post-commit

sycl/source/detail/memory_manager.cpp, sycl/source/detail/scheduler/commands.cpp
This was pointed out by Coverity: it would seem that some functions are missing assertions to prevent dereferencing null pointers.
=> [SYCL] Added assertions to prevent null pointer dereferences

devops/dependencies-igc-dev.json
=> [GHA] Uplift Linux IGC Dev RT version to igc-dev-cd26fa9

sycl/test-e2e/DiscardEvents/discard_events_l0_inorder.cpp
Related to issue [14121](https://github.com/intel/llvm/issues/14121)
This test probably fixed by one of the fixes submitted as I tested it on L0 ARC device and it was passing normally.
=> Reenable discard_events_l0_inorder test

clang/include/clang/Driver/Options.td, clang/test/Driver/sycl-offload-old-model.cpp
Accept -fsycl-allow-device-dependencies with clang-cl.
1. Also add testing for -fno-sycl-allow-device-dependencies.
2. Remove RUNx commands that were in preparation for connecting -support-dynamic-linking to -shared. -support-dynamic-linking will only be connected to -fsycl-allow-device-dependencies.
3. Rename CHECK names to use "SADD" (SYCL Allow Device Dependencies) instead of "SHARED".
=> [SYCL][Driver] Support -fsycl-allow-device-dependencies on clang-cl

sycl/test-e2e/AddressSanitizer/common/config-red-zone-size.cpp, sycl/test-e2e/AddressSanitizer/common/kernel-debug.cpp, sycl/test-e2e/AddressSanitizer/multiple-reports/multiple_kernels.cpp, sycl/test-e2e/AddressSanitizer/multiple-reports/one_kernel.cpp, sycl/test-e2e/AddressSanitizer/use-after-free/quarantine-free.cpp
Fixes #14825
Fixes #14658
these were disabled pending a UR fix which has now merged and upstreamed
=> [SYCL] Re-enable xfailed AddressSanitizer tests

sycl/test-e2e/Assert/check_resource_leak.cpp, sycl/test-e2e/DeprecatedFeatures/sampler_ocl.cpp
sampler_ocl test is fixed with [UR PR](https://github.com/oneapi-src/unified-runtime/pull/1896). Fixes [14679](https://github.com/intel/llvm/issues/14679), [14806](https://github.com/intel/llvm/issues/14806)
=> Reenable check_resource_leak and sampler_ocl tests

llvm/lib/SYCLLowerIR/ESIMD/LowerESIMD.cpp, llvm/test/SYCLLowerIR/ESIMD/lower_llvm_intrin.ll, sycl/include/sycl/ext/intel/esimd/detail/intrin.hpp, sycl/include/sycl/ext/intel/esimd/detail/math_intrin.hpp, sycl/include/sycl/ext/intel/esimd/detail/memory_intrin.hpp, sycl/include/sycl/ext/intel/esimd/math.hpp, sycl/include/sycl/ext/intel/experimental/esimd/detail/math_intrin.hpp, sycl/include/sycl/ext/intel/experimental/esimd/detail/memory_intrin.hpp, sycl/include/sycl/ext/intel/experimental/esimd/math.hpp
This is a partial revert of 0228c2328167244d1ca9a04b8071c69e7e60ebc8, with the root cause that required the revert fixed.
Clang declares SPIR-V intrinsics for many operations, however it only supports vector size 2, 3, 4, 8, and 16 as per [here](https://github.com/intel/llvm/blob/sycl/clang/lib/Sema/SPIRVBuiltins.td#L349). 
On Windows, the ESIMD-declared intrinsics conflicted with the Clang declared intrinsics causing a compilation error and thus the revert in the above commit. We can't use the Clang intrinsics because we support any N including 1 and non-power of 2.
This comment fixes the issue by applying an existing pattern done with other intrinsics declared by SPIR-V, but I originally did these intrinsics in a different way, causing the problem.
This fixes the original issue (as …
=> [SYCL][ESIMD] Move some math operations back to SPIR-V intrinsics

sycl/cmake/modules/FetchUnifiedRuntime.cmake, sycl/test-e2e/USM/dmem_varied.cpp
Testing PR for https://github.com/oneapi-src/unified-runtime/pull/1699.
`sycl/test-e2e/USM/dmem_varied.cpp` is passing on Native CPU with the corresponding UR changes.
=> [SYCL][NATIVECPU] Implement urUSMGetMemAllocInfo and aligned alloc

.github/workflows/sycl-post-commit.yml
We need `reset_gpu` to be false, to use the correct image, and to use a static library build becuase `lld` is not packaged correctly into the binary for shared library build. 
I'll investigate the `lld` issue separately (https://github.com/intel/llvm/issues/14986), but let's unbreak CI.
=> [CI] Fix HIP postcommit

.github/workflows/sycl-linux-matrix-e2e-on-nightly.yml, .github/workflows/sycl-linux-precommit.yml, .github/workflows/sycl-linux-run-tests.yml, .github/workflows/sycl-nightly.yml, .github/workflows/sycl-post-commit.yml
It only works for Intel GPUs. 
Based on feedback from [here](https://github.com/intel/llvm/pull/14980#discussion_r1707213892).
=> [CI][NFC] Rename reset_gpu variable

llvm/utils/git/code-format-helper.py
The code formatting workflow broke just before pulldown from LLVM trunk.
This PR cherry-picks the relevant commits from LLVM trunk to fix the bug: https://github.com/llvm/llvm-project/commit/b3c450d4dc8f21f70a4fa35bdcbd4bfaf852ccd7 and https://github.com/llvm/llvm-project/commit/9572388a849c494d45df334f9facd8ee6663953f
Example run: https://github.com/intel/llvm/pull/14998
Fixes https://github.com/intel/llvm/issues/14737
=> [CI] Fix code formatting workflow

sycl/test-e2e/Config/select_device.cpp
1. For L0 driver, there are version numbers like `[1.3.30049+6]`, which if we don't perform the escape, then the `+` would interfere the matching.
2. Why not? there is no harm in doing so.
=> [SYCL][E2E] always escape version number in test select_device.cpp

sycl/source/detail/scheduler/commands.cpp, sycl/test-e2e/ProfilingTag/profile_tag_leak.cpp
Due to a bug in the L0 UR adapter, the profiling tag extension leaks UR events on out-of-order queues. This is not due to the profiling tag events themselves, but rather due to the need for a barrier enforcing correct ordering of the inserted tag. Since the barrier ensures completion prior to the profiling tag executing, the output event is not needed, but the L0 adapter leaks the event if no output event is specified. To combat this, this work-around passes an output event and immediately frees it after the barrier has been submitted.
See https://github.com/oneapi-src/unified-runtime/issues/1947.
=> [SYCL] Add work-around for event leak in profiling tag

sycl/test-e2e/bindless_images/vulkan_interop/mipmaps.cpp, sycl/test-e2e/bindless_images/vulkan_interop/sampled_images.cpp, sycl/test-e2e/bindless_images/vulkan_interop/sampled_images_USM.cpp, sycl/test-e2e/bindless_images/vulkan_interop/vulkan_common.hpp
Vulkan interop in L0 backend currently has an issue that image sizes are not correctly passed to graphics memory management (GMM). Using dedicated allocation is an approach to solve the issue. In this case, image and device memory has 1:1 mapping and GMM is aware of the image info.
This PR enables VK_KHR_GET_MEMORY_REQUIREMENTS_2_EXTENSION_NAME extension and checks if VkMemoryDedicatedRequirements.requiresDedicatedAllocation is true. The value is false by default in CUDA and L0 backends.
=> [SYCL][E2E][Bindless] Check and use DedicatedAllocation in vulkan interop test for L0

clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/sycl-lto.cpp
In early splitting with thinLTO, we could be generating an `.o` to be linked in with other files later. Right now, passing `-emit-only-kernels-as-entry-points` to `sycl-post-link` can cause functions to get dropped even though they are used by some other `.o`.
We will need to prune non-entry points inside the thinLTO processing inside `clang-linker-wrapper`, but that's not implemented yet.
=> [SYCL][Driver][thinLTO] Don't pass -emit-only-kernels-as-entry-points to sycl-post-link in early splitting

sycl/test-e2e/Basic/kernel_bundle/kernel_bundle_api.cpp, sycl/test-e2e/Basic/vector/load_store.cpp, sycl/test-e2e/EnqueueNativeCommand/custom-command-cuda.cpp, sycl/test-e2e/EnqueueNativeCommand/custom-command-multiple-dev-cuda.cpp, sycl/test-e2e/Matrix/element_wise_all_ops.cpp, sycl/test-e2e/Matrix/element_wise_all_ops_1d.cpp, sycl/test-e2e/Matrix/element_wise_all_ops_1d_cont.cpp, sycl/test-e2e/Matrix/element_wise_all_ops_scalar.cpp, sycl/test-e2e/Matrix/element_wise_all_sizes.cpp
Fixes [14795](https://github.com/intel/llvm/issues/14795), [14749](https://github.com/intel/llvm/issues/14749), [14804](https://github.com/intel/llvm/issues/14804), [14805](https://github.com/intel/llvm/issues/14805)
=> [SYCL-E2E] Re-enable a bunch of working tests

sycl/test-e2e/syclcompat/launch/launch_policy_lmem.cpp
It's failing with the new driver (not yet merged, will merge after this PR is merged)
https://github.com/intel/llvm/issues/14974
=> [SYCL][E2E] XFAIL launch_policy_lmem.cpp on Arc

sycl/test-e2e/AmdNvidiaJIT/kernel_and_bundle.cpp
It [passes](https://github.com/intel/llvm/actions/runs/10295214614/job/28494750636) in the nightly somehow but fails in postcommit.
https://github.com/intel/llvm/issues/14989
=> [SYCL][E2E] Move kernel_and_bundle.cpp test to unsupported

sycl/test-e2e/syclcompat/launch/launch_policy_lmem.cpp
This reverts commit 050687a46b98212bc049f3b4b88b3207e7f5345f.
Somehow it's passing now.
=> Revert "[SYCL][E2E] XFAIL launch_policy_lmem.cpp on Arc (#14975)"

sycl/cmake/modules/FetchUnifiedRuntime.cmake, sycl/doc/design/CommandGraph.md
Tests UR PR https://github.com/oneapi-src/unified-runtime/pull/1910
=> [SYCL][Graph] Fix bugs with HIP/CUDA UR sync points.

sycl/CMakeLists.txt
Currently the backend macros are only defined when the runtime adapters for the given backend are built.
It's more accurate to use whether or not the compiler can target these backends, regardless of whether the runtime elements are present.
It should be possible to compile an application for a backend without having to install the matching runtime.
=> [SYCL][CUDA][HIP] Define backend macros based on compiler

sycl/cmake/modules/FetchUnifiedRuntime.cmake
Fix L0 build log, https://github.com/oneapi-src/unified-runtime/pull/1923
=> [UR][L0] Return the build log on compilation failure

sycl/test-e2e/AddressSanitizer/invalid-argument/host-pointer.cpp
Previously this test failed on machines without level_zero gpu due to not finding a device of the requested type.
=> [SYCL][E2E] Use `%{run}` instead of `%{run-unfiltered-devices}` in AddressSanitizer test

sycl/include/sycl/ext/oneapi/experimental/virtual_functions.hpp, sycl/test-e2e/VirtualFunctions/2/1/1/missing-overrides.cpp, sycl/test-e2e/VirtualFunctions/2/1/1/more-complex-hierarchy.cpp, sycl/test-e2e/VirtualFunctions/2/1/1/simple-hierarchy.cpp, sycl/test-e2e/VirtualFunctions/2/2/single-construct-single-use.cpp, sycl/test/virtual-functions/calls-indirectly-ir.cpp, sycl/test/virtual-functions/diagnostics-negative.cpp, sycl/test/virtual-functions/diagnostics-positive.cpp, sycl/test/virtual-functions/indirectly-callable-ir.cpp, sycl/test/virtual-functions/properties-negative.cpp, sycl/test/virtual-functions/properties-positive.cpp
Corresponding SYCL extension proposal (intel/llvm#10540) has been recently updated to change naming of properties it introduces.
This patch aligns the implementation with the proposed extension spec.
=> [SYCL] Rename virtual function properties

sycl/test-e2e/Plugin/dll-detach-order.cpp
Fixes #14767 
This test passes against all adapters both on my own machine and Github CI and should now be re-enabled.
=> [SYCL][E2E] Re-enable dll-detach-order.cpp

llvm/lib/SYCLLowerIR/ModuleSplitter.cpp, llvm/test/tools/sycl-post-link/device-code-split/amd-kernel-split.ll, sycl/test-e2e/KernelAndProgram/free_function_apis.cpp, sycl/test-e2e/KernelAndProgram/free_function_kernels.cpp
`free_function_kernels.cpp` test had a bug where the kernels with demangled name for free functions will be deleted in the `sycl-post-link` step of compilation. And this happened as AMD kernels was not detected due to a missing condition. This was not detected before as the HIP device on CI doesn't have `usm_shared_allocations` aspect available so it was detected as unsupported but when I tried it locally with a device with `usm_shared_allocations` aspect available, the test was failing.
=> [SYCL] Add AMDGPU_kernel calling convention to detected kernels

buildbot/configure.py, libdevice/cmake/modules/SYCLLibdevice.cmake, llvm/lib/SYCLNativeCPUUtils/CMakeLists.txt, sycl/CMakeLists.txt, sycl/cmake/modules/FetchUnifiedRuntime.cmake, sycl/doc/GetStartedGuide.md, sycl/tools/sycl-trace/CMakeLists.txt
Rename `SYCL_ENABLE_PLUGINS` to `SYCL_ENABLE_BACKENDS`
Also rename `SYCL_PI_UR_USE_FETCH_CONTENT` to `SYCL_UR_USE_FETCH_CONTENT`
and `SYCL_PI_UR_SOURCE_DIR` to `SYCL_UR_SOURCE_DIR`
For https://github.com/intel/llvm/issues/14927
=> [SYCL] Rename SYCL_ENABLE_PLUGINS to SYCL_ENABLE_BACKENDS

sycl/cmake/modules/FetchUnifiedRuntime.cmake
Tests UR PR https://github.com/oneapi-src/unified-runtime/pull/1960 for fixing a UR CTS bug in the L0 adapter for command-buffers.
=> [SYCL][Graph] Bump L0 UR Tag

clang/include/clang/Basic/SourceManager.h, clang/lib/Frontend/PrintPreprocessedOutput.cpp, clang/lib/Lex/PPLexerChange.cpp
The same functionality was needed at the 2 different places, and I inadvertently created 2 functions. This patch refactors it.
=> [NFC][SYCL] Remove multiple definitions of ComputeValidFooterFileID.

sycl/include/sycl/range.hpp
There is no need to use the detail::array::get() with bounds checking as it is guaranteed that we don't go out-of-bounds in this case, so just use underlying storage directly to calculate the size.
This is also necessary because accessor::size() and buffer::size() methods are noexcept by spec and their implementation use range::size();
=> [SYCL] Make range::size() exception-free

sycl/source/detail/handler_impl.hpp
The C-style structs used by the `handler_impl` for bindless images are not initialized. Although their values get initialized later in execution, when it is decided this information is actually used, leaving these values uninitialized still leave the possibility of vulnerabilities. This PR initializes them.
I'd like to bring attention to the fact that we could also use `std::optional` here, although that'll increase the size used for each field here. Zero initializing these structs is also an option, although I noticed many of these structs have default values, so I default initialized instead. If `std::optional` or zero initializing would be a better option here, please let me know and I'll make the changes. Thanks!
=> [SYCL] Default-initialize UR structs used in handler_impl

sycl/unittests/scheduler/EnqueueWithDependsOnDeps.cpp
This one is failing too. Also tracked in https://github.com/intel/llvm/issues/15049
=> [SYCL]  Disable SchedulerTest/ShortcutFunctionWithWaitList on Windows

llvm/lib/Transforms/Instrumentation/AddressSanitizer.cpp, llvm/test/Instrumentation/AddressSanitizer/SPIRV/instrument_private_address_space.ll
For global, local shadow memory, we will cleanup it before using it. So, we also need to do this for private shadow memory to avoid shadow value pollutions.
=> [DeviceSanitizer] Always cleanup private shadow memory before using it

sycl/include/sycl/detail/builtins/builtins.hpp
Fixes https://github.com/intel/llvm/issues/15063.
=> [SYCL] Clean `-Wcomment` warning

clang/include/clang/Basic/DiagnosticGroups.td, clang/include/clang/Basic/DiagnosticSemaKinds.td, clang/include/clang/Basic/LangOptions.h, clang/lib/Sema/SemaDeclAttr.cpp, clang/lib/Sema/SemaSYCL.cpp, clang/test/SemaSYCL/implicit_kernel_type.cpp
As a continuation of [#14544](https://github.com/intel/llvm/pull/14544) this PR turns off attribute propagation specified by sycl-1.2.1. It also removes rest of 2017/121 things like a definition of Sycl2017Compat which had been turned off in [#14239](https://github.com/intel/llvm/pull/14239)
=> [SYCL] Turning off the deprecated attribute propagation and Sycl2017Compat option specification

clang/test/Driver/sycl-host-compiler-old-model.cpp
Negative test was not formulated correctly, allowing for a pass even when the negative case occurs.
=> [NFC][Driver] Fix negative test check

sycl/test-e2e/Plugin/level_zero_barrier_optimization.cpp
- Test2 in level_zero_barrier_optimization.cpp will only see Event Create or Host Reset if counting events are not used from the cache, which is default for immediate command list and in order list use.
- counting events cannot be reset so neither of these prints would be seen so this is optional.
=> [SYCL][E2E] Fix L0 barrier test to handle counting events

sycl/unittests/program_manager/CompileTarget.cpp
This commit fixes a build failure resulting from https://github.com/intel/llvm/pull/14909.
=> [SYCL][Unittest] Fix build in CompileTarget unittest

sycl/test-e2e/DeprecatedFeatures/deprecated_intel_ext_device.cpp
The deprecated_intel_ext_device was disabled for L0 a while ago. This commit attempts to reenable it under the expectation that the queries have been fixed in the L0 driver.
=> [SYCL] Reenable deprecated_intel_ext_device for L0

sycl/test-e2e/Annotated_usm/annotated_usm_align.cpp, sycl/test-e2e/Annotated_usm/annotated_usm_negative.cpp, sycl/test-e2e/Annotated_usm/annotated_usm_shared_align.cpp
Some of the annoated USM tests were disabled on GPU, but based on PVC testing, these seem to be working for GPU now. This commit enables these tests.
=> [SYCL][E2E] Enable annotated usm tests on GPU

llvm/lib/SYCLLowerIR/ComputeModuleRuntimeInfo.cpp, llvm/lib/Transforms/IPO/DeadArgumentElimination.cpp, llvm/lib/Transforms/Instrumentation/AddressSanitizer.cpp, llvm/test/Instrumentation/AddressSanitizer/SPIRV/sycl_esimd.ll
We don't have a way to check if the kernel has been extended on Unified Runtime, so we always extend kernel argument for ESIMD kernel and SYCL kernel, even it will not be instrumented by any asan functions
=> [DeviceSanitizer] Fix device image contains both ESIMD kernel and SYCL kernel

.github/workflows/sycl-nightly.yml
This typo caused the job to always get skipped.
Confirmed this fixes it [here](https://github.com/intel/llvm/actions/runs/10405372513/job/28818960269) compared to [before](https://github.com/intel/llvm/actions/runs/10398087484/job/28796039560).
=> [CI] Fix Nightly Windows E2E testing

sycl/test-e2e/ESIMD/hardware_dispatch.cpp
The test requires gen12 but we were running it on DG2.
Closes: https://github.com/intel/llvm/issues/15096
=> [SYCL][ESIMD] Disable hardware_dispatch on DG2

sycl/cmake/modules/FetchUnifiedRuntime.cmake, sycl/source/backend.cpp, sycl/source/backend/level_zero.cpp, sycl/source/detail/device_impl.cpp, sycl/source/device.cpp
The api now takes a ur_adapter_handle_t instead of a ur_platform_handle_t, which is easier for sycl RT to correctly provide and enables a fix for a few instances where we were illegally passing nullptr.
=> [SYCL][UR] Pull in update that changes urDeviceCreateWithNativeHandle.

sycl/include/sycl/ext/oneapi/bfloat16.hpp
```
struct A {  // Fails to compile with clang 8.0.1, ok 9.0.0
constexpr A& operator=(const A&) = default;
~A() = default;
};
struct B {  // Ok with either version
~B() = default;
constexpr B& operator=(const B&) = default;
};
int main() {
A a;
B b;
return 0;
}
```
Since the workaround isn't hurting readability/maintenance might just do it even if the support for such old clang is questionable.
=> [SYCL] Fix `bfloat16` to compile with clang < 9.0.0

sycl/test-e2e/Basic/diagnostics/non-uniform-wk-gp-test.cpp
As shown in https://github.com/intel/llvm/issues/15111, currently sycl::stream will leak resources if an exception is thrown during launch of its associated command. This was in turn causing sycl/test-e2e/Basic/diagnostics/non-uniform-wk-gp-test.cpp to leak resources simply because it was using the stream in its testing. However, since the kernel should never execute, the stream did not serve a fundamental function in the test and was only there for additional debugging information in the case where the test would fail. As such, it is arguably better to improve coverage than to disable cases because of some potentially helpful additional output in the failing case.
=> [SYCL][E2E] Remove leaking part of non-uniform-wk-gp-test

sycl/source/detail/global_handler.cpp, sycl/source/detail/ur.cpp
As part of removing the plugin interface a check was added for the use of the `SYCL_PI_TRACE` environment variable. However, this was only applied on the Windows path. This patch moves this check to a common path for both Windows and Linux.
=> [SYCL] Also check for use of SYCL_PI_TRACE on Linux

sycl/test/regression/ambigious-memcpy.cpp
`detail::memcpy`, even though in a different namespace, can cause ambiguity with libc's memcpy, due to argument dependent lookup (ADL). This compile-only
test checks for ambiguity in call to `detail::memcpy`.
As discussed in https://github.com/intel/llvm/pull/14836#issuecomment-2266136834
=> [SYCL] Add LIT regression test for ambiguous call to `memcpy`

sycl/include/sycl/ext/intel/experimental/esimd/detail/math_intrin.hpp, sycl/include/sycl/ext/intel/experimental/esimd/math.hpp, sycl/test-e2e/ESIMD/frem.cpp
Add support for the frem function.
Support for this was just added to IGC, so we aren't using the driver in CI yet, so the test won't actually run.
I manually tested single type which works with the version in `REQUIRES-INTEL-DRIVER`, but I found an issue in the driver with double so it's disabled in the test for now.
=> [SYCL][ESIMD] Add frem function

sycl/gdb/libsycl.so-gdb.py, sycl/test/CMakeLists.txt, sycl/test/gdb/printers.cpp, sycl/test/lit.cfg.py, sycl/test/lit.site.cfg.py.in
Incremental improvements to GDB debugging for SYCL data structures. Python code was formatted using the 'black' utility according to the coding standard.
Some examples follow:
BEFORE
------
(gdb) whatis accessor_1d_read_write
type = sycl::_V1::accessor<int, 1, (sycl::_V1::access::mode)1026, (sycl::_V1::access::target)2014, (sycl::_V1::access::placeholder)0, sycl::_V1::ext::oneapi::accessor_property_list<> >
(gdb) print buffer_3d
$1 = (sycl::_V1::buffer<int, 3> &) @0x7fffffff8c48: sycl::_V1::buffer<int, 3> = {impl=0x7fffffff8c48}
(gdb) print accessor_1d[7]
Failed to call 'sycl::_V1::accessor<int, 1, (sycl::_V1::access::mode)1024, (sycl::_V1::access::target)2014, (sycl::_V1::access::placeholder)0, sycl::_V1::ext::oneapi::accessor_property_list<> > *.operator[](int)'
$2 = void
AFTER
----- …
=> [SYCL][GDB] Incremental improvement to GDB printers for SYCL types/values

llvm/lib/Transforms/Instrumentation/AddressSanitizer.cpp, llvm/test/Instrumentation/AddressSanitizer/SPIRV/non-spirv-turn-off-asan-stack.ll
The logic of `ClSpirOffloadPrivates` controlling`PoisonStack` is problematic, lead to host sanitizer cannot disable the stack instrument with `-asan-stack=0`.
=> [DeviceSanitizer] Fix the problem of asan-stack=0 not working as expected.

sycl/test-e2e/syclcompat/common.hpp, sycl/test-e2e/syclcompat/lit.local.cfg
Removes c++20 features from the e2e tests to avoid introducing c++20 in SYCLcompat by accident
=> [SYCL][COMPAT][E2E] Removes std++20 usage from syclcompat e2e tests

sycl/test-e2e/InlineAsm/Negative/asm_bad_opcode.cpp, sycl/test-e2e/InlineAsm/Negative/asm_bad_operand_syntax.cpp, sycl/test-e2e/InlineAsm/Negative/asm_duplicate_label.cpp, sycl/test-e2e/InlineAsm/Negative/asm_illegal_exec_size.cpp, sycl/test-e2e/InlineAsm/Negative/asm_missing_label.cpp, sycl/test-e2e/InlineAsm/Negative/asm_missing_region.cpp, sycl/test-e2e/InlineAsm/Negative/asm_simple.cpp, sycl/test-e2e/InlineAsm/Negative/asm_undefined_decl.cpp, sycl/test-e2e/InlineAsm/Negative/asm_undefined_pred.cpp, sycl/test-e2e/InlineAsm/Negative/asm_wrong_declare.cpp
The tests in sycl/test-e2e/InlineAsm/Negative are disabled due to reported module leaks. The reason for this "leak" is because the modules fail to build, and as such are never actually created. The false positive has been reported in
https://github.com/oneapi-src/unified-runtime/issues/1990. This commit adds a link to this issue in the affected tests.
=> [SYCL][E2E] Add comment with issue for inline ASM leaks

sycl/cmake/modules/FetchUnifiedRuntime.cmake
Fix race condition in CUDA stream creation in the UR CUDA adapter
See https://github.com/oneapi-src/unified-runtime/pull/1984
=> [UR][CUDA] Fix race condition in CUDA stream creation

sycl/test-e2e/bindless_images/vulkan_interop/sampled_images.cpp
Fix cast to char emitting a warning causing an error when -werror is used.
=> [SYCL][E2E][Bindless] Fix cast to char failing with -werror

sycl/test-e2e/KernelAndProgram/multiple-kernel-linking.cpp, sycl/test-e2e/Regression/commandlist/gpu.cpp, sycl/test-e2e/SubGroup/sub_group_as.cpp, sycl/test-e2e/SubGroup/sub_group_as_vec.cpp, sycl/test-e2e/SubGroupMask/Basic.cpp, sycl/test-e2e/SubGroupMask/GroupSize.cpp
This commit reenables a selection of tests for ze_debug as they no longer seem to be failing for this option.
=> [SYCL][E2E] Reenable ze_debug cases

sycl/cmake/modules/FetchUnifiedRuntime.cmake, sycl/test-e2e/XPTI/Inputs/test_collector.cpp, sycl/test-e2e/XPTI/basic_event_collection_linux.cpp, sycl/tools/sycl-prof/collector.cpp, sycl/tools/sycl-sanitize/collector.cpp, sycl/tools/sycl-trace/collector.cpp, sycl/tools/sycl-trace/main.cpp
=> [XPTI] Rename `ur` to `ur.call` in XPTI

libdevice/nativecpu_utils.cpp
Multiple declarations were missing for shuffle and broadcast operations,  in particular work group broadcast ones. This adds them.
=>  [SYCL][NATIVECPU] Fix missing declarations for broadcast and shuffle operations

sycl/source/detail/kernel_compiler/kernel_compiler_opencl.cpp, sycl/test-e2e/KernelCompiler/multi_device.cpp
Currently if there is only single device in the context then kernel
compiler passes ip version of that device via -device option to ocloc
when compiling OpenCL program to spirv to let ocloc enable all extensions
supported by that device. Problem is that ocloc -spv_only doesn't produce
spirv file when multiple devices are provided via  -device option.
That's why in this case  enable common extensions supported by all devices
manually. To do that use ocloc query to get common supported features
for the list of devices and then process the return and enable features
via ocloc -internal_options -cl-ext=+feature1,...
=> [SYCL] Fix OpenCL C to spirv kernel_compiler for the multi-device case

clang/include/clang/Basic/DiagnosticDriverKinds.td, clang/lib/Driver/Driver.cpp, clang/lib/Driver/ToolChains/Clang.cpp, clang/lib/Driver/ToolChains/SYCL.cpp, clang/test/Driver/sycl-MD-default.cpp, clang/test/Driver/sycl-offload-old-model.c, clang/test/Driver/sycl-offload.c
As we are working towards upstreaming the SYCL support in the compiler, a few areas need to be cleaned up for readability and improved logic to reduce some repetitious output.  Does not impact behaviors in general.
=> [Driver][SYCL][NFC] Cleanup various code entries

sycl/source/detail/buffer_impl.cpp, sycl/source/detail/image_impl.cpp, sycl/source/detail/sycl_mem_obj_t.cpp, sycl/source/detail/sycl_mem_obj_t.hpp
Restores missed context analysis for host pointer update.
Regression is caused by https://github.com/intel/llvm/commit/3dc75a75b624ae2d3fd2e2335a7c6ee054b75366
=> [SYCL] Fix regression in update_host

sycl/test-e2e/Functor/kernel_functor.cpp
I don't know if this change the intention of this test, but there is a problem of buffer out-of-bound access in the test. `Buf` is originally a size `1` buffer, but in line 186, the range is set to 10, which would lead to buffer access out-of-bound in `FunctorMulti F`.
=> [SYCL][E2E] Fix a test buffer out-of-bound problem

llvm/lib/Transforms/Scalar/LoopIdiomRecognize.cpp
We added some codes to prevent "LoopIdiomRecognize" from converting loop to memset, so that it won't conflict with host Asan. Now we needn't this fix anymore.
=> [DeviceSanitizer] Revert LoopIdiomRecognize changes for asan

sycl/test-e2e/Basic/buffer/buffer_release.cpp, sycl/test-e2e/Basic/buffer/subbuffer.cpp, sycl/test-e2e/Basic/build_log.cpp, sycl/test-e2e/Basic/enqueue_barrier.cpp, sycl/test-e2e/Basic/event_profiling_info.cpp, sycl/test-e2e/Basic/image/image_accessor_readsampler.cpp, sycl/test-e2e/Basic/image/image_max_size.cpp, sycl/test-e2e/Basic/image/image_sample.cpp, sycl/test-e2e/CompositeDevice/composite_device.cpp, sycl/test-e2e/DiscardEvents/invalid_event.cpp
This commit reenables a selection of tests that have previously been disabled, most for different reasons.
Additionally, the subbuffer test still seems to fail on Gen12 OpenCL, so this commit adds a comment with a link to the GH issue.
=> [SYCL][E2E] Reenable old tests

sycl/cmake/modules/FetchUnifiedRuntime.cmake
Testing PR for https://github.com/oneapi-src/unified-runtime/pull/1873
=> [SYCL][NATIVECPU] Support UR_DEVICE_INFO_MAX_MEM_ALLOC_SIZE

sycl/test-e2e/Basic/vector/vec_binary_scalar_order_logical.cpp, sycl/test-e2e/Basic/vector/vec_binary_scalar_order_relational.cpp
The functionality has been promoted to default during the past ABI breaking window.
=> [NFC][E2E] Enable few `vec` tests outside `-fpreview-breaking-changes`

clang/lib/Sema/SemaSYCL.cpp, clang/test/CodeGenSYCL/free_function_int_header.cpp, clang/test/CodeGenSYCL/int-header-empty-signatures.cpp, clang/test/CodeGenSYCL/integration_header.cpp, clang/test/CodeGenSYCL/kernel-param-acc-array-ih.cpp, clang/test/CodeGenSYCL/kernel-param-member-acc-array-ih.cpp, clang/test/CodeGenSYCL/kernel-param-pod-array-ih.cpp, clang/test/CodeGenSYCL/union-kernel-param-ih.cpp, clang/test/CodeGenSYCL/wrapped-accessor.cpp
We create a kernel_names array in the integration header even when the list of names is empty.
This leads to diagnostics about zero-length arrays in pedantic modes.   This change adds an empty
string as a sentinel node to all kernel_names arrays so the array is never empty.
=> [SYCL] Add a sentinel empty string to kernel names array

sycl/include/sycl/vector.hpp
I think previous implementation was based on C++14 or even C++11 standard. We can do better now.
=> [NFCI] Refactor `sycl::vec`'s variadic ctor

clang/lib/Sema/SemaSYCL.cpp, clang/test/CodeGenSYCL/device_global_int_footer_header.cpp, clang/test/CodeGenSYCL/device_globals_with_spec_ids.cpp, clang/test/CodeGenSYCL/host_pipe_int_footer_header.cpp, clang/test/CodeGenSYCL/int_header_without_kernels.cpp, sycl/test/basic_tests/header_footer_diagnostics.cpp
When -Wreserved-identifer or -Wold-style-cast is enabled, some of the constructs used in
integration headers and footers for device_globals and host_pipes trigger a diagnostic.
This change adds a pragma to the generated files that suppress the diagnostic prior to
the construct and reenabled the diagnostic after.
=> [SYCL] Disable clang pedantic diagnostics in header/footer

sycl/include/sycl/detail/usm_impl.hpp, sycl/source/detail/usm/usm_impl.cpp
`alignedAllocHost` was introduced as part of what was described as a bugfix in 01869a033a76 wherin `alignedAlloc` was simply renamed to `alignedAllocHost`, but the `Kind` parameter (host|device|shared) was left unchanged, and the bugfix actually appears to be in the calling code. I'm not quite sure what happened there, but in any case we shouldn't have a `Kind` parameter if we only ever intend to work on the host (indeed the existing code treats Kind == host as an invariant, returning an error otherwise).
It looks like a couple of other people tried to work around this when adding other features (e.g. in 7df39237b30) but didn't fix this due to perceived ABI breaks. However, this function hasn't been exposed as part of the abi due to a declaration / definition mismatch between the header …
=> [SYCL] remove `alignedAllocHost`'s `Kind` param

sycl/test-e2e/DeviceCodeSplit/grf.cpp, sycl/test-e2e/ESIMD/grf.cpp
The L0 adapter tracing interferes with regular tracing, so don't use the normal env var to enable tracing in these tests.
=> [SYCL][E2E] Bypass L0 adapter tracing in grf tests

clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/sycl-spirv-ext-old-model.c, clang/test/Driver/sycl-spirv-metadata-old-model.cpp, clang/test/Driver/sycl-spirv-obj-old-model.cpp, clang/test/Driver/sycl-spirv-obj.cpp, clang/tools/clang-linker-wrapper/ClangLinkerWrapper.cpp
Reverts intel/llvm#14992
Breaks InvokeSimd on dev-igc.
=> Revert "[SYCL][Driver] Enable SPV_INTEL_memory_access_aliasing extension"

libdevice/msvc_math.cpp, sycl/test-e2e/DeviceLib/cmath_fp64_test.cpp, sycl/test-e2e/DeviceLib/separate_compile_test.cpp, sycl/test-e2e/DeviceLib/std_complex_math_fp64_test.cpp, sycl/test-e2e/DeviceLib/std_complex_math_test.cpp
There are three test cases that added in https://github.com/intel/llvm/pull/14329 that do not match the expected result on Windows. This is due to the fact the supporting the std math functions on device Windows is partially determined by the MSVC implementation of the math functions. 
- `tanh(-inf + nan * i)` and `tanh(-inf + -inf * i)` should both be `1 + 0*i`, but the MSVC implementation does not obey this equation even on host. This PR changes the test to ignore these cases on windows.
- `exp(1e6 + -0.1*i)` should be `inf + -inf*i`, but was `inf + inf*i`. This equation holds for MSVC implementation on host. Indeed this was problem with an implementation of the `_FExp` helper function that `exp(std::complex)` is implemented with. This is fixed in this PR.
Additionally, this PR changes …
=> [SYCL] Fix windows exp(complex) edge case

sycl/test-e2e/Config/kernel_from_file.cpp, sycl/test-e2e/SeparateCompile/test.cpp
The `-c` flag is not used when used in conjunction with the `-fsycl-device-only` flag. This patch removes uses of `-c` in such situations.
This caused failures in internal testing, because the closed source compiler reports this as an `unused-command-line-argument` warning, however syclos does not report this.
=> [SYCL][E2E] Remove -c flags on run lines that use -fsycl-device-only

sycl/test-e2e/ESIMD/frem.cpp
It's fixed in a newer driver, same driver version. Not used in CI yet.
=> [SYCL][ESIMD][E2E] Enable frem double test

sycl/doc/extensions/experimental/sycl_ext_oneapi_graph.asciidoc, sycl/source/detail/graph_impl.cpp, sycl/unittests/Extensions/CommandGraph/CommandGraph.cpp
Since future features may add more properties/state to queue recording it is now an error to call `begin_recording()` on the same queue more than once, rather than a no-op. This is particularly relevant in scenarios where a recording queue is shared between multiple threads. Applications are now encouraged to manage queue state from a single thread rather than freely call `begin/end_recording()` from any thread.
- Calling begin_recording on a recording queue is now always an error.
- Update spec, implementation and unit tests to reflect changes.
=> [SYCL][Graph] Make calling begin_recording repeatedly an error

sycl/test-e2e/Basic/built-ins/marray_common.cpp
We've observed some failures due to produced results being not exact 180/`M_PI`, e.g. due to the use of FMA instructions. `half` versions of the test cases already used a delta to perform comparison, use the same for `float`/`double`.
=> [SYCL][E2E] Add non-zero "delta" for `degrees`/`radians` tests

llvm/include/llvm/SYCLLowerIR/DeviceConfigFile.td, sycl/test-e2e/NonUniformGroups/ballot_group_algorithms.cpp
The aspect is supported since [OpenCL CPU 2024.2](https://github.com/intel/llvm/releases/download/2024-WW25/oclcpuexp-2024.18.6.0.02_rel.tar.gz)
=> [SYCL][CPU] Add ext_oneapi_ballot_group aspect to spir64_x86_64 target

sycl/cmake/modules/FetchUnifiedRuntime.cmake, sycl/doc/GetStartedGuide.md
Cleaning up some remaining `PI` references found in the UR CMake fetch file.
Renaming `SYCL_PI_UR_OVERRIDE_FETCH_CONTENT_REPO` and `SYCL_PI_UR_OVERRIDE_FETCH_CONTENT_TAG` to `SYCL_UR_OVERRIDE_FETCH_CONTENT_REPO` and `SYCL_PI_UR_OVERRIDE_FETCH_CONTENT_TAG`.
=> Remove PI from UR override fetch variables

devops/dependencies-igc-dev.json
=> [GHA] Uplift Linux IGC Dev RT version to igc-dev-427a492

sycl/doc/extensions/experimental/sycl_ext_oneapi_graph.asciidoc, sycl/test-e2e/Graph/RecordReplay/ext_oneapi_enqueue_functions.cpp, sycl/test-e2e/Graph/RecordReplay/ext_oneapi_enqueue_functions_submit.cpp, sycl/test-e2e/Graph/RecordReplay/ext_oneapi_enqueue_functions_submit_with_event.cpp
Add tests to verify support for using the [sycl_ext_oneapi_enqueue_functions](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/experimental/sycl_ext_oneapi_enqueue_functions.asciidoc) extension to add nodes to a graph in queue recording.
=> [SYCL][Graph] Support sycl_ext_oneapi_enqueue_functions

sycl/test-e2e/InvokeSimd/invoke_simd_conv.cpp, sycl/test-e2e/InvokeSimd/invoke_simd_smoke.cpp
The local lit configuration specifies that a GPU device is required to run InvokeSimd tests, so the default selector works just fine. In addition, the custom selector in the tests could only select GPUs.
=> [SYCL][E2E] Remove unnecessary custom device selector from InvokeSimd tests

sycl/test-e2e/NonUniformGroups/ballot_group_algorithms.cpp
Follow-up of https://github.com/intel/llvm/pull/15165
The test should run on either CPU or GPU.
=> [SYCL][E2E] Fix ballot_group_algorithms test condition

sycl/doc/extensions/template.asciidoc
The current version of the SYCL 2020 specification is now rev 9. Also define `endnote` which nore specs are starting to use.
=> [SYCL][Doc] Update revision of SYCL spec

sycl/test-e2e/Basic/built-ins/marray_common.cpp, sycl/test-e2e/syclcompat/math/math_ops.cpp
We've seen those tests failing when release testing. It boils down to the fact that `icpx` will by default (with no user input) enable fast math mode.
* `marray_common.cpp` - uses golden values alongside allowed delta, however in fast math mode the calculation error is greater than the delta
* `math_ops.cpp` - uses `isnan`, which compilers are not obliged to honour in fast math mode.
If nothing else, those tests are a perfect example of how forcing fast math mode on can cause non-obvious errors in, otherwise sound, user code when floating point types are being used.
=> [SYCL] Disable fast math in math_ops and marray_common tests

sycl/source/detail/graph_impl.cpp, sycl/source/detail/graph_impl.hpp, sycl/source/handler.cpp
Use `std::enable_shared_from_this` to remove need for passing a shared pointer of `this` as a function parameter.
`std::enable_shared_from_this` usage was previously introduced to graph code in https://github.com/intel/llvm/pull/14453#discussion_r1681412183
=> [SYCL][Graph] `enable_shared_from_this` refactor

sycl/doc/extensions/proposed/sycl_ext_oneapi_cache_size.asciidoc
Adds an extension for querying the availability and size of different levels of cache within a device.
=> [SYCL][Doc] Add sycl_ext_oneapi_cache_size draft

sycl/test-e2e/EnqueueNativeCommand/custom-command-hip.cpp, sycl/test-e2e/HostInteropTask/interop-task-hip.cpp, sycl/test-e2e/lit.cfg.py
This patch fixes running the interop HIP tests on setups where the ROCm installation is not in `/opt/rocm`.
=> [SYCL][HIP] Fix hardcoded ROCm path in lit tests

clang/lib/Driver/Driver.cpp, clang/lib/Driver/ToolChains/SYCL.cpp, clang/test/CodeGenSYCL/sycl-libdevice-cmath.cpp, clang/test/Driver/sycl-device-lib-nvptx.cpp, clang/test/Driver/sycl-offload-nvptx.cpp, libclc/CMakeLists.txt, libclc/cmake/modules/AddLibclc.cmake, libdevice/CMakeLists.txt, libdevice/cmake/modules/SYCLLibdevice.cmake
Create one single bitcode library for NVPTX by compiling each libdev file into
bitcode first, linking these together and running opt on them.
Strip away metadata by reusing prepare_builtins from libclc.
Remove NVPTX bundles from the libdev object files and remove any unbundling
action spawned by the Clang driver for the SYCL toolchain when compiling for the
NVPTX backend.
Make the driver link against the single bitcode libraries for NVPTX for the SYCL
toolchain when device library linkage is not excluded.
Ensure that the clang tests check for the correctness of the new clang driver
actions and check if the driver still links the device code against the itt
device libraries when device library linkage has been excluded.
Refactor SYCLLibdevice.cmake by creating functions and grouping e.g. …
=> [SYCL][NVPTX] Create one bitcode library for NVPTX

sycl/include/sycl/stl_wrappers/assert.h, sycl/include/sycl/stl_wrappers/cassert, sycl/test-e2e/Assert/assert_in_kernels_win.cpp, sycl/test-e2e/Assert/assert_in_multiple_tus_one_ndebug_win.cpp, sycl/test-e2e/Assert/assert_in_multiple_tus_win.cpp, sycl/test-e2e/Assert/assert_in_one_kernel_win.cpp, sycl/test-e2e/Assert/assert_in_simultaneous_kernels_win.cpp, sycl/test-e2e/Assert/assert_in_simultaneously_multiple_tus.cpp, sycl/test-e2e/Assert/assert_in_simultaneously_multiple_tus_one_ndebug.cpp, sycl/test/include_deps/sycl_accessor.hpp.cpp, sycl/test/include_deps/sycl_buffer.hpp.cpp, sycl/test/include_deps/sycl_detail_core.hpp.cpp
This PR fixes a device assertion bug on Windows where the assertion message and information are not printed when an assertion is triggered. Also re-enabled some tests failing because of it. See https://github.com/intel/llvm/issues/12797.
=> [SYCL] Fix device assertion bug on windows

sycl/source/detail/device_impl.cpp, sycl/source/detail/kernel_program_cache.hpp, sycl/source/detail/plugin.hpp, sycl/source/detail/ur.cpp
Replace the name of OCL specific macro to reflect the move from OpenCL
API to UR API.
=> [SYCL][NFC] plugin.hpp code cleanup

sycl/doc/extensions/proposed/sycl_ext_oneapi_reduction_properties.asciidoc
Defines new compile-time properties that provide developers with greater control over how a reduction may be implemented.
Closes #1621 .
=> [SYCL][Doc] Add reduction properties extension

sycl/doc/extensions/proposed/sycl_ext_oneapi_joint_for.asciidoc
Adds a proposed extension for encapsulating the pattern of distributing loops across the work-items in a group.
=> [SYCL][Doc] Add draft of sycl_ext_oneapi_joint_for

clang/lib/Sema/SemaSYCL.cpp, clang/test/CodeGenSYCL/int-header-empty-signatures.cpp, clang/test/CodeGenSYCL/kernel-param-acc-array-ih.cpp, clang/test/CodeGenSYCL/kernel-param-member-acc-array-ih.cpp, clang/test/CodeGenSYCL/kernel-param-pod-array-ih.cpp, clang/test/CodeGenSYCL/union-kernel-param-ih.cpp, clang/test/CodeGenSYCL/wrapped-accessor.cpp
A sentinel value added in #15175 fixed the problem of empty arrays, but for non-empty arrays was just concatenated to the last valid value. This produced warnings when compiling SYCL applications, and also meant that there is no sentinel value in the non-empty arrays.
=> [SYCL] Fix -Wstring-concatenation in integration headers

sycl/test-e2e/AOT/fpga-aoc-archive-early.cpp, sycl/test-e2e/AOT/fpga-aoc-archive-early2.cpp, sycl/test-e2e/AOT/fpga-aoc-archive2.cpp, sycl/test-e2e/lit.cfg.py
Split fpga AOC tests fpga-aoc-archive and fpga-aoc-archive-early to address random timeouts even after the initial split in commit 4af4d4b. This update further divides the tests into smaller units to minimize the number of compile and run sequences.
=> [NFC][SYCL] Split fpga AOC archive tests to address random timeouts

sycl/doc/extensions/experimental/sycl_ext_codeplay_enqueue_native_command.asciidoc
Another solution would be to change the spec to bring it closer to
how AdaptiveCpp does things. But here we make the example
align with the extension spec, host_task spec, and the implementation.
Fixes #15254
=> [SYCL][ext][NFC] Fix example in codeplay_enqueue_native_command

sycl/gdb/libsycl.so-gdb.py
Three issues are addressed:
1. Printing non-sycl types may generate a python exception.
2. Accessor subscripts using size_t report an unsupported subscript type.
3. Multi-dimensional accessors calculate the wrong array layout.
=> [SYCL][GDB] Fixes for three issues in GDB xmethods.

xpti/include/xpti/xpti_trace_framework.hpp
Using `getenv` on Windows is deprecated, creating failures in XPTI e2e tests #15026. This patch adds GCC diagnostics pragma around the use of `getenv` to ignore this warning.
=> [XPTI] Use GCC diagnostics pragma around getenv

sycl/source/detail/jit_compiler.cpp
Fix compilation failure in post-commit CI due to some arguments currently being unused.
=> [SYCL] Mark arguments as potentially unused

sycl/test-e2e/BFloat16/bfloat16_builtins.cpp, sycl/test-e2e/BFloat16/bfloat16_builtins_cuda_generic.cpp, sycl/test-e2e/BFloat16/bfloat16_conversions.cpp, sycl/test-e2e/BFloat16/bfloat16_example.cpp, sycl/test-e2e/BFloat16/bfloat16_type.cpp, sycl/test-e2e/BFloat16/bfloat16_vec.cpp, sycl/test-e2e/DeviceLib/string_test.cpp, sycl/test-e2e/GroupAlgorithm/SYCL2020/group_sort/group_and_joint_sort.cpp, sycl/test-e2e/KernelAndProgram/spec_constants_after_link.cpp, sycl/test-e2e/KernelCompiler/kernel_compiler_opencl.cpp, sycl/test-e2e/KernelCompiler/kernel_compiler_sycl.cpp, sycl/test-e2e/KernelCompiler/opencl_capabilities.cpp, sycl/test-e2e/KernelCompiler/opencl_queries.cpp, sycl/test-e2e/Regression/unoptimized_stream.cpp, sycl/test-e2e/SpecConstants/2020/handler-api.cpp, sycl/test-e2e/SpecConstants/2020/kernel-bundle-api.cpp, sycl/test-e2e/SpecConstants/2020/vector-convolution-demo.cpp
This commit enables tests that have been marked UNSUPPORTED for accelerator targets.
=> [SYCL][E2E] Enable UNSUPPORTED:accelerator tests

sycl/source/detail/sycl_mem_obj_t.cpp, sycl/source/detail/sycl_mem_obj_t.hpp, sycl/test-e2e/Regression/multithread_write_accessor.cpp
Fixes a flaky failure when getting write access to a buffer from multiple threads.
=> [SYCL] Guard access to MCreateShadowCopy

llvm/include/llvm/SYCLLowerIR/DeviceConfigFile.td, sycl/test-e2e/NonUniformGroups/ballot_group.cpp, sycl/test-e2e/NonUniformGroups/ballot_group_algorithms.cpp, sycl/test-e2e/NonUniformGroups/fixed_size_group.cpp, sycl/test-e2e/NonUniformGroups/fixed_size_group_algorithms.cpp, sycl/test-e2e/NonUniformGroups/opportunistic_group.cpp, sycl/test-e2e/NonUniformGroups/opportunistic_group_algorithms.cpp, sycl/test-e2e/NonUniformGroups/tangle_group.cpp, sycl/test-e2e/NonUniformGroups/tangle_group_algorithms.cpp
Also enable non-uniform group tests for CPU JIT and AOT.
=> [SYCL] Add more aspects to CPU AOT target

clang/include/clang/Basic/DiagnosticDriverKinds.td, clang/include/clang/Driver/Options.td, clang/lib/Driver/Driver.cpp, clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/sycl-MD-default.cpp, clang/test/Driver/sycl-offload-old-model.c, clang/test/Driver/sycl-offload.c, sycl/test/basic_tests/accessor/no_offset_error.cpp, sycl/test/check_device_code/esimd/slm_init_specconst_size.cpp
Update -fsycl-device-only usage to be an alias to --offload-device-only. This requires an additional unique check for SYCL enabling due to the expectation that -fsycl-device-only also implies -fsycl.
Update associated tests that use -fsycl-device-only -emit-llvm.  Our default is already bitcode output, fixing this up aligns better with community expectations when using --offload-device-only.
Also do some variable cleanup to better be in sync with community variable names. And use a more common diagnostic for invalid options with -fsycl.
=> [Driver][SYCL] Use existing option for device-only and some cleanup

sycl/test-e2e/syclcompat/launch/launch_policy_lmem.cpp
Failing in new driver, see https://github.com/intel/llvm/issues/15275.
It will XPASS in this PR, but once this is merged I will immediately merge the driver update PR.
=> [SYCL][E2E] XFAIL launch_policy_lmem.cpp

sycl/test-e2e/OneapiDeviceSelector/no_duplicate_devices.cpp
It's failing in the new GPU driver.
https://github.com/intel/llvm/issues/15288
=> [SYCL][E2E] XFAIL no_duplicate_devices.cpp on Linux Gen12

sycl/source/backend.cpp, sycl/source/detail/kernel_bundle_impl.hpp, sycl/source/detail/plugin.hpp, sycl/source/virtual_mem.cpp
This PR fixes many Coverity hits:
- Adds checks ensuring potentially nullable values are not dereferenced
- Adds a sanity check on get_mem_granularity, ensuring memory granularity can never be 0
- This is done to fix a divide by 0 coverity hit, as the return result of get_mem_granularity is used directly in division.
I'd like to bring attention to the error codes I am using, especially in backend.cpp, in `make_kernel_bundle`. I am using `errc:build` as according to the SYCL 2020 spec, this is for errors "from an online compile or link operation when compiling, linking, or building a kernel bundle for a device". However, in the specifications for `make_kernel_bundle`, the SYCL 2020 spec states:
> Throws an exception with the errc::invalid error code if any error is produced by the [SYCL …
=> [SYCL] Fix Coverity null reference hits, divide by 0 hits

sycl/test-e2e/Basic/built-ins/marray_geometric.cpp, sycl/test-e2e/syclcompat/math/math_vectorized_isgreater_test.cpp
Very much the same as https://github.com/intel/llvm/pull/15223/
* `marray_geometric` - golden values against delta, which in fast math mode is not accurate enough,
* `math_cectorized_isgreater_test` - uses compiler builtins (`__builtin_isgreaterequal`, `__builtin_isgreater`), when combined with fast math mode all bets are off.
=> [SYCL] Disable fast math in marray_geometric and math_vectorized_isgreater_test

sycl/test-e2e/GroupAlgorithm/shuffle_marray.cpp
This commit fixes a case for XOR permute shuffles in sycl/test-e2e/GroupAlgorithm/shuffle_marray.cpp when sub-group sizes are uneven.
=> [SYCL][E2E] Fix shuffle_marray XOR permute shuffle for uneven SG

sycl/include/sycl/detail/cg_types.hpp, sycl/test/abi/vtable.cpp
The changes in https://github.com/intel/llvm/pull/14460 removed the seemingly unused functions for running kernels on on host. However, this turned out to be used by debuggers as they need the kernel code to be in the host executable.
This commit adds a simplified version of the kernel instantiation that the aforementioned patch removed.
=> [SYCL] Add host kernel instantiation for debuggers

sycl/test-e2e/syclcompat/launch/launch_policy_lmem.cpp
It actually fails on OCL only, not L0.
Fixes postcommit.
=> [SYCL][E2E] Fix XFAIL condition in launch_policy_lmem.cpp

sycl/test-e2e/DeviceArchitecture/device_architecture_on_host.cpp
Now that sycl_ext_oneapi_device_architecture returns unknown for unknown architectures, the test should work for all device targets. This commit enables it for accelerator.
=> [SYCL][E2E] Enable device_architecture_on_host for accelerator

sycl/cmake/modules/FetchUnifiedRuntime.cmake
-pre-commit PR for https://github.com/oneapi-src/unified-runtime/pull/2062
=> [UR][L0] Fix Command List Cache to correctly set In order List property

sycl/include/sycl/detail/cg_types.hpp, sycl/test/abi/vtable.cpp
The changes in https://github.com/intel/llvm/pull/15256 unintentionally broke ABI by reordering the virtual member functions of HostKernelBase. This commit amends this by moving the new function to the end of the new member function.
Additionally, this fixes a typo in the new function.
=> [SYCL] Fix unintentional vtable ABI break in HostKernelBase

sycl/test-e2e/syclcompat/launch/launch_policy_lmem.cpp
It's XPASSing in the nightly somehow, but fails in pre/postcommit.
https://github.com/intel/llvm/actions/runs/10731711170/job/29762580737
=> [SYCL][E2E] Move launch_policy_lmem.cpp to UNSUPPORTED on XFAILed platforms

sycl/test-e2e/Plugin/sycl-ls.cpp
Make sure that the devices that belong to unsupported platforms are not counted, this is required to match the number of devices when `sycl-ls` is run in and out of the `verbose` mode.
=> [SYCL] Discard unsupported platforms output in sycl-ls test

devops/containers/ubuntu2204_base.Dockerfile
Render group is required for the sycl user to access the PVC card in the docker container.
https://dgpu-docs.intel.com/driver/installation.html#installing-gpu-drivers
=> [CI][Container] Add sycl user to the render group

sycl/source/detail/kernel_program_cache.hpp, sycl/source/detail/program_manager/program_manager.cpp, sycl/unittests/kernel-and-program/OutOfResources.cpp
Currently if program manager faces one of the errors  - UR_RESULT_ERROR_OUT_OF_RESOURCES or UR_RESULT_ERROR_OUT_OF_HOST_MEMORY - during the program building/linking then it will clear the cache and make another attempt. 
This PR adds the following changes:
* Additionally take into account UR_RESULT_ERROR_OUT_OF_DEVICE_MEMORY error which is also possible in addition to aforementioned error codes.
* Parameterize the existing unit test by error code (which allows to avoid excessive code duplication) and add UR_RESULT_ERROR_OUT_OF_DEVICE_MEMORY value to testing.
=> [SYCL] Take into account UR_RESULT_ERROR_OUT_OF_DEVICE_MEMORY error code in Program Manager

sycl/test-e2e/lit.cfg.py
When append_path is True, value is normalized to lowercase on Windows at
https://github.com/llvm-mirror/llvm/blob/2c4ca6832fa6b306ee6a7010bfb80a3f2596f824/utils/lit/lit/llvm/config.py#L139
For env value that isn't a path, the normalization is unexpected.
For env value that is a path, it doesn't make sense to append_path
unconditionally. Test driver should append path when necessary before
setting a env.
=> [SYCL][E2E LIT] Remove append_path=True from config.extra_environment handling

llvm/lib/SYCLNativeCPUUtils/PipelineSYCLNativeCPU.cpp, llvm/lib/SYCLNativeCPUUtils/PrepareSYCLNativeCPU.cpp, sycl/test/check_device_code/native_cpu/local_module_scope.cpp
Although local scope variables inside the kernel are less common in SYCL, they can happen with hierarchical.
This fixes the problem by adding a pass to replace the local scope variables which start life as globals with a struct which is allocated on the stack.
Additionally, this required updating of the code which renames and removes kernel based on wrappers and vecz success. To simplify this we run the OCK utility pass TransferKernelMetadata which adds metadata to store the original kernel name. This in turn simplifies this code significantly.
Note this fixes fails in kernel/kernel_attributes_wg_hint.cpp SYCL CTS for native cpu, which is being tested locally.
=> [SYCL][NATIVECPU] Fix local scope module variables for native cpu

llvm/include/llvm/SYCLLowerIR/ComputeModuleRuntimeInfo.h, llvm/include/llvm/SYCLLowerIR/SpecConstants.h, llvm/lib/SYCLLowerIR/ComputeModuleRuntimeInfo.cpp, llvm/lib/SYCLLowerIR/SpecConstants.cpp, llvm/test/tools/sycl-post-link/spec-constants/default-value/bool.ll, llvm/tools/sycl-post-link/sycl-post-link.cpp
Computing information about spec consts is difficult for callers when module properties generation and splitting are separate. Simplify it by storing information in module we can use invisibly to the caller.
This will be used for thinLTO, where we split early and compute module properties later. 
This should be basically NFC.
=> [SYCL] Simplify arguments to computeModuleProperties

sycl/unittests/scheduler/GraphCleanup.cpp
A month ago, we had a strange intermittent failure of one of the unit tests: https://github.com/intel/llvm/issues/15049  and in response to that we disabled the test.  It is unclear why that might have been failing.
But that was when there were some other disrupting changes, and fallout from that has since been fixed. 
I have retested this on Windows for 100,000 iterations, and not a single failure seen. Tested on the CI, ran successfully there too.
I'd like to reenable this test with this PR. If the CI system starts failing on PR, we can just revert this PR in coming days.
=> [SYCL] re-enable Scheduler StreamBufferDeallocation unit test

.github/workflows/sycl-linux-precommit-aws.yml, .github/workflows/sycl-linux-precommit.yml, .github/workflows/sycl-post-commit.yml
Reverts https://github.com/intel/llvm/pull/14074. This will allow us to use latest docker images.
=> Revert '[CI] pre-commit/aws pointed back to old image'

sycl/source/detail/event_impl.hpp, sycl/source/detail/scheduler/commands.cpp, sycl/test-e2e/Regression/barrier_waitlist_with_interop_event.cpp
Currently Command::getUrEventsBlocking is responsible for preparing a waitlist of UR events for the barrier.
This method used wrong assumption that if isEnqueued() returns false for the event then it doesn't have UR handle because it was not enqueued. So if there is an associated command we would enqueue it to get the desired UR handle, or we would just ignore this event if there is no associated command.  
Problem is that sycl::event created with interoperability constructor has isEnqueued() as false (as it is not enqueued by SYCL RT)  but it has UR handle provided by user. 
Before this patch we just ignored such event as it doesn't have associated command and we didn't put it to the resulting list.
This patch fixes this problem by handling interop events properly in this code path.
=> [SYCL] Fix handling of interop events for barrier with waitlist

sycl/test-e2e/OnlineCompiler/online_compiler_L0.cpp, sycl/test-e2e/OnlineCompiler/online_compiler_OpenCL.cpp, sycl/test-e2e/OnlineCompiler/online_compiler_common.hpp
This commit fixes an issue where the online_compiler_OpenCL test would assume that the clCreateProgramWithIL function is supported by all OpenCL targets, while it was only supported with >=2.1 and had an extension in older versions. This also enables the test for accelerator.
=> [SYCL][E2E] Fix online compiler test for accelerator

llvm/utils/git/requirements.txt
PR to bump dependency version to resolve security vulnerability found. 
pyca/cryptography's wheels include a statically linked copy of OpenSSL. The versions of OpenSSL included in cryptography 37.0.0-43.0.0 are vulnerable to a security issue. More details about the vulnerability itself can be found in https://openssl-library.org/news/secadv/20240903.txt.
=> Bump cryptography to 43.0.1 in llvm/utils/git/requirements.txt

llvm/include/llvm/SYCLLowerIR/SpecConstants.h, llvm/lib/SYCLLowerIR/ComputeModuleRuntimeInfo.cpp, llvm/lib/SYCLLowerIR/SpecConstants.cpp, llvm/tools/sycl-post-link/sycl-post-link.cpp
Addressing review feedback from https://github.com/intel/llvm/pull/15271
=> [SYCL][NFCI] Rework spec constants metadata used for split

sycl/source/detail/queue_impl.hpp, sycl/unittests/scheduler/HostTaskAndBarrier.cpp
PR includes the following fixes:
* When submitting a command to an out-of-order queue we don't need to add the dependency from the last barrier to the scheduler if command is enqueued via UR because that means that UR backend will take care of the command from barrier.
* We used to update the last barrier only if barrier which is being submitted to the sycl::queue is not enqueued to the backend which is not correct, because there might be host tasks following that barrier which have to depend on it.
=> [SYCL] Add sync for host task after barrier

sycl/unittests/scheduler/InOrderQueueDeps.cpp
The test needs to reset the variable used to check when a UR call is made.
=> [SYCL][NFC] Fix InOrderQueueIsolatedDeps when run repeatedly

sycl/source/detail/device_info.hpp
New Intel GPU devices with matrix support have been added to https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/experimental/sycl_ext_oneapi_device_architecture.asciidoc#new-enumeration-of-architectures, namely:
- Battlemage and Lunar Lake that share same matrix combinations as PVC in the matrix query 
- Arrow Lake H that shares the same matrix combinations  as DG2
Hence, this PR updates the matrix query to includes these 3 new devices.
=> [SYCL][Joint Matrix] Additional devices with Joint Matrix support

sycl/cmake/modules/FetchUnifiedRuntime.cmake
Includes a few small fixes:
https://github.com/oneapi-src/unified-runtime/pull/2083
https://github.com/oneapi-src/unified-runtime/pull/2080
https://github.com/oneapi-src/unified-runtime/pull/2072
=> [UR] Bump UR tag to f31160d

sycl/test-e2e/Basic/launch_queries/max_num_work_groups.cpp
The previous global work size was exceeding the limits of INT_MAX on the intel opencl fpga emulator device and thus failing the test. This commit also cleans up the test checks validation by leaving the `assert`ions and removing the `if` conditions.
=> [SYCL] Fix launch config in the max_num_work_groups e2e test

libclc/cmake/modules/AddLibclc.cmake
While processing bc files, the OUT_DIR should exist. Since we have a separate target for LIBCLC_LIBRARY_OUTPUT_INTDIR, we add a dependency on it instead of forcing directory creation during bc processing.
=> [CLC][cmake] Add missing dependency on LIBCLC_LIBRARY_OUTPUT_INTDIR

llvm/lib/SYCLLowerIR/SpecConstants.cpp, llvm/lib/SYCLNativeCPUUtils/CMakeLists.txt, llvm/lib/SYCLNativeCPUUtils/PipelineSYCLNativeCPU.cpp, llvm/lib/SYCLNativeCPUUtils/PrepareSYCLNativeCPU.cpp, sycl/cmake/modules/FetchUnifiedRuntime.cmake, sycl/source/kernel_bundle.cpp, sycl/test-e2e/SpecConstants/2020/kernel-bundle-api.cpp
Adds support to specialization constants by scheduling the `SpecConstantsPass` in the Native CPU pass pipeline. A small change is needed in that pass since, due to ABI, the return type of the spec const builtins can't be used to determine the type of the spec constant, so for Native CPU we use the default value instead.
UR PR: https://github.com/oneapi-src/unified-runtime/pull/1821
=> [SYCL][NATIVECPU] Support specialization constants on Native CPU

llvm-spirv/lib/SPIRV/SPIRVWriter.cpp, llvm-spirv/test/transcoding/builtin_function_readnone_attr.ll
This reverts commit f87204892e58d7ffe73e80edbb631603d51f6a7f.
=> [SPIR-V] Revert "[SPIR-V] Add W/A for readnone function parameter attribute (#7669)"

sycl/test-e2e/ESIMD/unified_memory_api/Inputs/copyto_copyfrom.hpp
Easy fix, verified with UR_L0_LEAKS_DEBUG=1
=> [SYCL][ESIMD][E2E] Fix memleak in copyto_copyfrom USM tests

clang/tools/clang-offload-extract/ClangOffloadExtract.cpp
Add a "q" flag for clang-offload-extract that supresses printing. For use in cmake or script files that don't want to display the generated files.
=> [Extractor] Add quiet option to offload extractor

clang/include/clang/Basic/DiagnosticDriverKinds.td, clang/lib/Driver/Driver.cpp, clang/test/Driver/sycl-offload.c
When using -fsycl-device-obj, we would effectively ignore any bad arguments and default to 'llvmir'. Add a diagnostic to inform the user of the bad argument and what we are doing with our default behavior.
=> [Driver][SYCL] Add diagnostic for bad argument with -fsycl-device-obj

clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/sycl-offload-old-model.cpp, llvm/lib/SYCLLowerIR/ModuleSplitter.cpp, llvm/test/tools/sycl-post-link/emit_imported_symbols.ll, llvm/test/tools/sycl-post-link/exclude_external_functions.ll, llvm/test/tools/sycl-post-link/exclude_external_functions_source.ll, llvm/test/tools/sycl-post-link/internalize_functions.ll, llvm/test/tools/sycl-post-link/virtual-functions/module-cleanup.ll
Rename sycl-post-link option "-support-dynamic-linking" to "-allow-device-image-dependencies".  This is consistent with the clang option that is tied to this sycl-post-link option, and is also consistent with what is being done inside sycl-post-link.
=> [SYCL][NFC] Rename support dynamic linking

sycl/test-e2e/Basic/interop/get_native_ze.cpp, sycl/test-e2e/Plugin/sycl-ls-gpu-default-any.cpp, sycl/test-e2e/Plugin/sycl-ls-gpu-level-zero.cpp, sycl/test-e2e/Regression/device_num.cpp
A handful of L0 tests were disabled with bd3370af22cd49f3bde48254b5a659fe9c0634bd a while ago, so it is time to retry enabling them.
=> [SYCL][E2E] Reenable L0 tests for sycl-ls, get_native_ze and device_num

sycl/test-e2e/Basic/image/image_array.cpp, sycl/test-e2e/Printf/mixed-address-space.cpp, sycl/test-e2e/Printf/percent-symbol.cpp, sycl/test-e2e/USM/align.cpp
This commit enables a selection of tests with UNSUPPORTED:gpu that seems to have been fixed since their disablement.
Additionally, it restricts expected failure of image_array to just Gen12, with tracker https://github.com/intel/llvm/issues/15398.
=> [SYCL][E2E] Enable passing UNSUPPORTED:gpu tests

.github/workflows/sycl-linux-precommit.yml, .github/workflows/sycl-linux-run-tests.yml
This PR refactors sycl-linux-precommit workflow to simplify passing `igc-dev` related variables.
=> [CI] Simplify passing igc-dev related variables

sycl/doc/extensions/proposed/sycl_ext_oneapi_address_cast.asciidoc, sycl/include/sycl/ext/oneapi/experimental/address_cast.hpp, sycl/test-e2e/AddressCast/dynamic_address_cast.cpp, sycl/test-e2e/AddressCast/static_address_cast.cpp, sycl/test/check_device_code/extensions/address_cast.cpp
Reflects spec changes from https://github.com/intel/llvm/pull/12689
=> [SYCL] Align `sycl_ext_oneapi_address_cast` impl with the spec

clang/test/Driver/sycl.c
Test is failing - disable for now until we can find a fix.
=> [SYCL][NFC] Temporarily disable Driver/sycl.c test on Windows

sycl/test-e2e/Basic/image/image_array.cpp
https://github.com/intel/llvm/pull/15391 enabled the image_array test for all other GPU devices than Gen12. However, in post-commit the test seems to fail on arc sporadically. As such this commit disables it again.
=> [SYCL][E2E] Redisable image_array test for all GPUs

sycl/doc/extensions/deprecated/sycl_ext_oneapi_group_load_store.asciidoc, sycl/include/sycl/sub_group.hpp, sycl/test-e2e/InvokeSimd/Feature/popcnt_emu.cpp, sycl/test-e2e/InvokeSimd/Feature/scale.cpp, sycl/test-e2e/InvokeSimd/Feature/void_retval.cpp, sycl/test-e2e/InvokeSimd/Regression/call_vadd_1d_spill.cpp, sycl/test-e2e/InvokeSimd/Regression/debug_symbols.cpp, sycl/test-e2e/InvokeSimd/Spec/ESIMD_to_unmarked_function.cpp, sycl/test-e2e/InvokeSimd/Spec/function_overloads.cpp, sycl/test-e2e/InvokeSimd/Spec/nested_ESIMD_to_ESIMD.cpp, sycl/test-e2e/InvokeSimd/Spec/nested_SPMD_to_ESIMD.cpp, sycl/test-e2e/InvokeSimd/Spec/uniform_retval.cpp, sycl/test-e2e/Matrix/slm_utils.hpp, sycl/test-e2e/SubGroup/sub_group_as.cpp, sycl/test-e2e/SubGroup/sub_group_as_vec.cpp, sycl/test/warnings/deprecated_group_load_store.cpp
Newer version is under `proposed/`, I'm going to move it to `experimental/` in a separate PR for a cleaner `git diff`.
=> [SYCL] Deprecate old `sycl_ext_oneapi_group_load_store`

sycl/source/detail/scheduler/commands.cpp, sycl/source/detail/scheduler/commands.hpp, sycl/source/handler.cpp, sycl/unittests/scheduler/InOrderQueueDeps.cpp
Runtime could submit kernel directly to scheduler if no buffers/streams are used and if event dependencies are already handled by queue (in case if it is in-order one). Although check if dependencies are submitted to the same queue was missed. Now we add events submitted to another queue but on the same context to event list in kernel launching.
=> [SYCL] Fix in-order queue dependencies for no scheduler path

sycl/cmake/modules/FetchUnifiedRuntime.cmake, sycl/test-e2e/InlineAsm/Negative/asm_bad_opcode.cpp, sycl/test-e2e/InlineAsm/Negative/asm_bad_operand_syntax.cpp, sycl/test-e2e/InlineAsm/Negative/asm_duplicate_label.cpp, sycl/test-e2e/InlineAsm/Negative/asm_illegal_exec_size.cpp, sycl/test-e2e/InlineAsm/Negative/asm_missing_label.cpp, sycl/test-e2e/InlineAsm/Negative/asm_missing_region.cpp, sycl/test-e2e/InlineAsm/Negative/asm_simple.cpp, sycl/test-e2e/InlineAsm/Negative/asm_undefined_decl.cpp, sycl/test-e2e/InlineAsm/Negative/asm_undefined_pred.cpp, sycl/test-e2e/InlineAsm/Negative/asm_wrong_declare.cpp
Reverts intel/llvm#15130 because https://github.com/oneapi-src/unified-runtime/issues/1990 was fixed
=> [SYCL][E2E] Revert "Add comment with issue for inline ASM leaks"

sycl/test-e2e/Basic/offset-accessor-get_pointer.cpp, sycl/test-e2e/DiscardEvents/discard_events_accessors.cpp, sycl/test-e2e/GroupAlgorithm/different_types.cpp
- replaced with `get_multi_ptr().get()` in `DiscardEvents/discard_events_accessors.cpp` and `GroupAlgorithm/different_types.cpp`
- Use `-DSYCL2020_DISABLE_DEPRECATION_WARNINGS` in place of `-Wno-error=deprecated-declarations` in `Basic/offset-accessor-get_pointer.cpp` due to `accessor::get_pointer`'s deliberate use. This brings it in line with `Basic/multi_ptr_legacy.cpp` which also uses it deliberately.
=> [SYCL][E2E] Remove deprecated use of `accessor::get_pointer` 

sycl/cmake/modules/FetchUnifiedRuntime.cmake, sycl/test-e2e/AddressSanitizer/memory-leak/memory-leak.cpp, sycl/test-e2e/AddressSanitizer/multiple-reports/multiple_kernels.cpp, sycl/test-e2e/AddressSanitizer/multiple-reports/one_kernel.cpp
UR Part: https://github.com/oneapi-src/unified-runtime/pull/1808
=> [UR][DeviceSanitizer] Update UR and add e2e tests for detecting memory leaks

sycl/test-e2e/Matrix/SG32/joint_matrix_bfloat16_packedB.cpp, sycl/test-e2e/Matrix/SPVCooperativeMatrix/SG32/joint_matrix_bfloat16_packedB.cpp
These 2 tests should not be run on DG2, since SG32 is not currently supported there for Joint Matrix. They started to run because we now use aspect to define which tests to run. Hence, adding UNSUPPORTED tag.
=> [SYCL][E2E][Joint Matrix] Make 2 SG32 tests UNSUPPORTED on Arc

sycl/test-e2e/USM/align.cpp
The USM/align.cpp E2E test does not correctly require USM support on the device it runs on. This commit adds the requirements.
Fixes https://github.com/intel/llvm/issues/15444
=> [SYCL][E2E] Add USM requirements to USM/align test

sycl/test-e2e/AddressSanitizer/invalid-argument/out-of-bounds.cpp, sycl/test-e2e/AddressSanitizer/invalid-argument/released-pointer.cpp, sycl/test-e2e/AddressSanitizer/nullpointer/global_nullptr.cpp
This commit disables the AddressSanitizer/invalid-argument/out-of-bounds.cpp and sycl/test-e2e/AddressSanitizer/invalid-argument/released-pointer.cpp tests for DG2, following the enabling of address sanitizer tests for DG2 in https://github.com/intel/llvm/pull/14891.
Additionally, it fixes the compilation failure in
sycl/test-e2e/AddressSanitizer/nullpointer/global_nullptr.cpp which should hopefully allow it to pass as expected.
=> [SYCL][E2E] Disable and fix address sanitizer tests for DG2

sycl/test-e2e/AddressSanitizer/nullpointer/global_nullptr.cpp
The sycl/test-e2e/AddressSanitizer/nullpointer/global_nullptr.cpp test had compilation errors whe first enabled on DG2. The compilation error was fixed in https://github.com/intel/llvm/pull/15450, but the test fails during execution on DG2. This commit disables the test for DG2.
See https://github.com/intel/llvm/issues/15453.
=> [SYCL][E2E] Disable AddressSanitizer/nullpointer/global_nullptr.cpp on DG2

clang/include/clang/Basic/DiagnosticSemaKinds.td, clang/test/SemaSYCL/device-indirectly-callable-attr.cpp, clang/test/SemaSYCL/device_global_external.cpp, clang/test/SemaSYCL/sycl-device.cpp
We were issuing a diagnostic when applying attributes like [[sycl_device]] or [[intel::device_indirectly_callable]] on functions/variables without external linkage - but the diagnostic text assumed that this occurred only with static entities or entities within unnamed namespaces.
The following example demonstrates a case where the previous diagnostic text was misleading:
```
namespace {
struct S {};
}
[[sycl_device]] void foo(S);
```
=> [SYCL] Fix diagnostic about non-external function/variable

clang/test/Driver/sycl.c
The issue dealt with the resetting of the PATH environment variable.  This was masking potential runtime dependencies (DLLs and such) for other tools being used when running the test.  The solution is to append the PATH for the dummy `aoc` instead of overwriting.
=> [SYCL][NFC] Re-enable sycl.c test on Windows

sycl/test-e2e/Matrix/SPVCooperativeMatrix/SG32/element_wise_all_ops_half.cpp, sycl/test-e2e/Matrix/SPVCooperativeMatrix/SG32/joint_matrix_half.cpp, sycl/test-e2e/Matrix/SPVCooperativeMatrix/element_wise_all_ops_half.cpp, sycl/test-e2e/Matrix/SPVCooperativeMatrix/joint_matrix_half.cpp
Add UNSUPPORTED for SPR for Joint Matrix fp16 tests in SPVCooperativeMatrix folder to avoid unexpected pass.
=> [SYCL][E2E][Joint Matrix] Make half tests UNSUPPORTED on some arch

sycl/source/detail/global_handler.cpp
This PR fixes the uncuahgt exception in dllMain() reported by static analysis tool by adding a try-catch block.
=> [SYCL] Fix uncaught exception reported by analysis

sycl/cmake/modules/FetchUnifiedRuntime.cmake
This should fix flaky e2e tests on gen12.
=> [UR] revert "Phase 2 of Counter-Based Event"

sycl/include/sycl/ext/oneapi/experimental/address_cast.hpp
The extension is aligned with core SYCL wording for `address_space_cast`, both do not expect decorated C++ pointers as operands. Long-term plans are to replace `multi_ptr` with `annotated_ptr`, so carefully crafting the wording in both SYCL core and the extension isn't a priority right now.
=> [SYCL] Remove `TODO`/fix typos in `address_cast.hpp`

sycl/test-e2e/Config/config.cpp, sycl/test-e2e/Config/env_vars.cpp, sycl/test-e2e/ESIMD/slm_alloc.cpp, sycl/test-e2e/ESIMD/slm_alloc_many_kernels_many_funcs.cpp, sycl/test-e2e/ESIMD/slm_alloc_many_kernels_one_func.cpp, sycl/test-e2e/GroupAlgorithm/SYCL2020/reduce_over_group_size.cpp, sycl/test-e2e/HierPar/hier_par_wgscope_O0.cpp, sycl/test-e2e/NewOffloadDriver/aot-cpu.cpp, sycl/test-e2e/OptionalKernelFeatures/is_compatible/is_compatible_with_aspects.cpp, sycl/test-e2e/OptionalKernelFeatures/throw-exception-for-unsupported-aspect.cpp, sycl/test-e2e/PropagateOptionsToBackend/sycl-opt-level-opencl.cpp, sycl/test-e2e/Regression/2020-spec-constants-debug-info.cpp, sycl/test-e2e/Regression/DAE-separate-compile.cpp, sycl/test-e2e/Regression/default-constructed-local-accessor.cpp, sycl/test-e2e/Regression/optimization_level_debug_info_intopt.cpp, sycl/test-e2e/Regression/unoptimized_stream.cpp, sycl/test-e2e/lit.cfg.py
Changes the `%no_opt` expansion introduced in #15364, to `%O0` to reduce confusion in between different methods of disabling optimizations.
=> [SYCL][E2E] Change `%no_opt` expansion to `%O0`

libdevice/sanitizer_utils.cpp, sycl/test-e2e/AddressSanitizer/nullpointer/global_nullptr.cpp
The content of "global_nullptr.cpp" was same with "private_nullptr.cpp".
This patch fix this.
=> [DeviceSanitizer] Fix wrong test for nullptr detection

sycl/test-e2e/DiscardEvents/discard_events_using_assert.cpp, sycl/test-e2e/KernelAndProgram/build-log.cpp
sycl/test-e2e/DiscardEvents/discard_events_using_assert.cpp and sycl/test-e2e/KernelAndProgram/build-log.cpp no longer show leaks when run with SYCL_UR_TRACE, so they can once again be enabled for ze_debug.
=> [SYCL][E2E] Enable discard_events_using_assert and build-log for leak

sycl/test-e2e/USM/buffer_location.cpp
This commit fixes and issue in buffer_location where the code would attempt to read from a device USM allocation. According to the SYCL specification, these allocations must be explicitly copied to/from host.
=> [SYCL][E2E] Fix buffer_location test for GPU

.github/CODEOWNERS
This commit assigns the codeowners for the SYCL Graph code to the
intel/sycl-graphs-reviewers team.
=> [CI][CODEOWNERS] Adjust CODEOWNERS for SYCL Graph

libdevice/cmath_wrapper_fp64.cpp
This is a follow-up for intel/llvm#15162
There are no new tests added with this PR, because we already have this edge case covered by existing tests here:
https://github.com/intel/llvm/blob/3e98b3a09254863423f82d10aa7d40a8b64dbdd3/sycl/test-e2e/DeviceLib/std_complex_math_fp64_test.cpp#L202
But we don't have a Windows machine with a GPU which supports `fp64` and therefoere this edge case went unnoticed by our CI. The change was locally tested in the right environment.
Patch-By: Justin Cai <justin.cai@intel.com>
=> [SYCL] Fix `std::exp(complex<double>)` edge case on Windows

sycl/test-e2e/LLVMIntrinsicLowering/bitreverse.cpp, sycl/test-e2e/LLVMIntrinsicLowering/sub_byte_bitreverse.cpp
Bitreverse lowering tests check a SPV file to ensure that SPIRV bitreverse insn is not used.
Ensure that only one SPV file is generated to facilitate SPV file checking.  Use -fno-sycl-allow-device-dependencies
to ensure only one file is generated.
=> [NFC] Ensure only one SPV file is generated in bitreverse lowering tests

.github/workflows/sycl-docs.yml, buildbot/configure.py, sycl/doc/extensions/supported/sycl_ext_intel_esimd/README.md, sycl/doc/extensions/supported/sycl_ext_intel_esimd/sycl_ext_intel_esimd.md, sycl/doc/extensions/supported/sycl_ext_intel_esimd/sycl_ext_intel_esimd_functions.md, sycl/doc/index.rst
Prequel of https://github.com/intel/llvm/pull/15483
This PR removes Doxygen docs/links from intel.github.io/llvm-docs/. This is done to reduce the size of the website so that it can be hosted via artifacts in #15483. [intel/llvm-docs](https://github.com/intel/llvm-docs) repository will soon be decommissioned.
=> [CI] Remove Doxygen docs from intel.github.io/llvm-docs/

sycl/include/sycl/detail/common.hpp, sycl/include/sycl/detail/generic_type_lists.hpp, sycl/include/sycl/detail/generic_type_traits.hpp, sycl/include/sycl/detail/type_traits.hpp, sycl/source/detail/program_manager/program_manager.hpp, sycl/test/basic_tests/generic_type_traits.cpp, sycl/test/type_traits/type_traits.cpp
Even if think that some of them might be useful one day, I would still prefer to drop them. SYCL headers a *very* heavy and they are one of the main reasons why SYCL compilation is so slow comparing to regular C++.
=> [SYCL][NFC] Drop unused type traits from public headers

sycl/include/sycl/handler.hpp, sycl/test/virtual-functions/properties-negative.cpp
We perform correctness check of compile-time properties in `handler::processProperties` helper function. That function was specialized by kernel name, meaning that if we have two kernels with absolutely the same properties applied to them there will be two instantiations of `processProperties`. That consumes compilation time for both front-end which has to emit extra isntantiations and for host compilation pass which gets more functions (with the same body!) to handle.
The only use of kernel name within `processProperties` is to check if that kernel is a ESIMD kernel. That can be done at caller side and propagated to `processProperties` as a simple boolean, thus reducing amount of instantiations of that function.
This patch does exactly that.
Please note that this is technically a …
=> [SYCL] Optimize handling of compile-time properties

devops/scripts/install_drivers.sh
Level Zero started building for ubuntu 24.04 as well as 22.04, so we need to update our script to download the 22.04 one, as we use 22.04 for our docker images.
See https://github.com/oneapi-src/level-zero/releases/tag/v1.17.44
=> [CI] Fix level_zero deb file name in install_drivers.sh script

clang/tools/clang-linker-wrapper/ClangLinkerWrapper.cpp
The problem was the buffer gets freed when we go out of the `if` because the `unique_ptr` is created there, so just make a copy that will stay alive as long as we need it. Confirmed fix with valgrind.
This is already tested by `sycl/test-e2e/NewOffloadDriver/multisource.cpp` and it fails sporadically which led me to this fix.
=> [SYCL][ClangLinkerWrapper] Fix read of invalid memory

sycl/test-e2e/DeviceDependencies/free_function_kernels.cpp, sycl/test-e2e/LLVMIntrinsicLowering/bitreverse.cpp, sycl/test-e2e/LLVMIntrinsicLowering/sub_byte_bitreverse.cpp
intel/llvm#15407 deprecated a flag without updating its uses in tests which fail due to `-Werror`.
=> [SYCL][E2E] Fix regression in tests

sycl/doc/design/DeviceAspectTraitDesign.md
Fixed a mistake in the `DeviceAspectTraitDesign.md` oneAPI design document where  `any_device_has_v` was misspelled as `any_devices_has_v`.
=> [SYCL][doc] Fix a spelling mistake in any_device_has_v aspect trait

sycl/test-e2e/AddressSanitizer/common/option-redzone-size.cpp
The filename is not updated accordingly with PR https://github.com/intel/llvm/pull/15293, this PR fixs this problem.
=> [SYCL][E2E][DeviceSanitizer] update filename in the FileCheck line

sycl/include/sycl/ext/intel/math/imf_half_trivial.hpp, sycl/test-e2e/DeviceLib/imf_fp16_trivial_test.cpp
Missing "inline" will lead to multiple definition linker error for these trivial functions. The scenario can be described as following:
a.cpp
#include <sycl/sycl.hpp>
#include <sycl/ext/intel/math.hpp>
b.cpp
#include <sycl/sycl.hpp>
#include <sycl/ext/intel/math.hpp>
int main() { return 0; }
clang++ -fsycl a.cpp b.cpp
=> [SYCL] Inline trivial util functions for half/half2 in intel math header

sycl/test-e2e/Plugin/level_zero_ext_intel_cslice.cpp, sycl/test-e2e/Plugin/level_zero_ext_intel_queue_index.cpp, sycl/test-e2e/Plugin/level_zero_sub_sub_device.cpp, sycl/test-e2e/Plugin/sycl-ls-uuid-subdevs.cpp
This commit removes the UNSUPPORTED marker with 1-tile PVC for a selection of tests. sycl-ls-uuid-subdevs seems to now pass and the rest are XFAIL on PVC which is wider than disabling for just 1-tile.
=> [SYCL][E2E] Remove 1-tile PVC UNSUPPORTED from tests

sycl/test-e2e/BFloat16/bfloat16_example.cpp
The test was recently refactored and got accidentally enabled on HIP, causing post-commit failure. It failed because it had been originally written to only support JIT targets.
There seems to be no good reason for this test not to be run on CUDA & HIP backends, so instead of restricting devices it should be run on this patch refactors it to support AOT targets as well.
=> [SYCL][E2E] Enable bfloat16_example test everywhere

sycl/test-e2e/Plugin/enqueue-arg-order-image.cpp
Closes https://github.com/intel/llvm/issues/11434. The issue has been fixed in the underlying GPU RT.
=> [SYCL][E2E] Re-enable `Plugin/enqueue-arg-order-image.cpp`

sycl/source/detail/thread_pool.hpp, sycl/test-e2e/Regression/unwaited_for_host_task.cpp
The flag that kills the threads waiting for work was an atomic bool, but that is not enough: any modification of a condition must be made under the mutex associated with that condition variable. Otherwise, the bool value flip and the call to notify might happen after the condition check in the other thread, but before it starts waiting for notifications.
=> [SYCL] Fix a thread pool data race during shutdown

sycl/cmake/modules/FetchUnifiedRuntime.cmake, sycl/test-e2e/Basic/get_info_aspect.cpp, sycl/test-e2e/Plugin/level_zero_device_free_mem.cpp
-pre-commit PR for https://github.com/oneapi-src/unified-runtime/pull/2017
=> [UR][L0] Use zesInit for SysMan API usage

sycl/test/check_device_code/native_cpu/native_cpu_attrs.cpp
Removes the check for `__mux_work_group_barrier` since on Native CPU work group barriers are materialized by OCK's WorkItemLoopPass, and since now we correctly remove unused functions from the module, there are no more references to `__mux_work_group_barrier`.
=> [SYCL][NATIVECPU] Update Native CPU attributes test

sycl/test-e2e/Graph/Explicit/interop-level-zero-launch-kernel.cpp, sycl/test-e2e/Graph/Inputs/interop-level-zero-launch-kernel.cpp, sycl/test-e2e/Graph/RecordReplay/interop-level-zero-launch-kernel.cpp
Re-enable the interop-level-zero-launch-kernel.cpp E2E test on PVC by making the following correctness changes to the native L0 code:
* Both `zeKernelSetGroupSize` and `ZeGroupCount` were set to have 1024 in the X dimensions when this is the total size of the USM allocation, and therefore the number of work items we want. Updated to use `zeKernelSuggestGroupSize` to work calculate the correct group sizes and count.
* Update `zeKernelSetArgumentValue` call so that the size parameter is the size of the pointer rather than size of the USM allocation.
=> [SYCL][Graph] Reenable L0 interop test on PVC

llvm/include/llvm/SYCLLowerIR/ModuleSplitter.h, llvm/lib/SYCLLowerIR/ComputeModuleRuntimeInfo.cpp, llvm/lib/SYCLLowerIR/ModuleSplitter.cpp, llvm/test/tools/sycl-post-link/sycl-esimd/assert.ll, llvm/test/tools/sycl-post-link/sycl-esimd/basic-esimd-lower.ll, llvm/tools/sycl-post-link/sycl-post-link.cpp
We need to know if a module is an ESIMD split or not split at all to set some image properties.
Right now we compute if a module is ESIMD or not by looking at the functions in the module and checking they are all ESIMD, except for allowed exceptions.
A new exception was found related to using `assert` in user code where there is a scalar SYCL function that correctly remains in the ESIMD split. The end result is we don't set the ESIMD property because we don't think this is the ESIMD split and do the wrong thing at runtime. Instead of just adding this new exception to the list, I reworked what I consider to be flaky logic (that I wrote originally, whoops) to figure out the splits.
Just save metadata in the module of what kind of split it is before we try to compute module properties. 
We …
=> [SYCL] Fix ESIMD split detection in module properties computation

sycl/doc/extensions/experimental/sycl_ext_oneapi_bindless_images.asciidoc, sycl/include/sycl/sampler.hpp, sycl/test-e2e/bindless_images/helpers/sampling.hpp, sycl/test-e2e/bindless_images/read_sampled.cpp
'addressing_mode::clamp' is not descriptive enough and neither does it align with what is commonly used in other graphics APIs. It is proposed to use 'addressing_mode::ext_oneapi_clamp_to_border' instead.
=> [SYCL][Bindless][Doc] Add 'addressing_mode::ext_oneapi_clamp_to_border' to replace 'addressing_mode::clamp'

sycl/test-e2e/DeviceCodeSplit/grf.cpp, sycl/test-e2e/KernelAndProgram/target_register_alloc_mode.cpp
Re-enable the KernelAndProgram/target_register_alloc_mode.cpp and DeviceCodeSplit/grf.cpp E2E tests on PVC by adding compiler flag for DeviceCodeSplit/grf.cpp in runs when old API is used and changing expected output in KernelAndProgram/target_register_alloc_mode.cpp to `urProgramBuildExp` instead of `urProgramBuild`.
=> [SYCL] Re-enable tests on PVC

.github/workflows/sycl-linux-precommit.yml, .github/workflows/sycl-nightly.yml, .github/workflows/sycl-post-commit.yml
NEO runtime has env variables to emulate multiple root devices: `NEOReadDebugKeys=1 CreateMultipleRootDevices=[num_devices]` which seems to be useful to write E2E tests for multi-device scenario.
It turns out those env variables don't work under docker container in our CI because of missing system directory. Add additional volume mapping to fix this.
=> [CI] additional docker volume mapping for E2E on Intel GPUs

clang/lib/Driver/ToolChains/SYCL.cpp, clang/test/Driver/sycl-device-lib-amdgcn.cpp, clang/test/Driver/sycl-device-lib-nvptx.cpp
Add the -only-needed flag for AMDGCN when linking against devicelib.
Fixes several test cases that use kernel bundles.
=> [SYCL][HIP] Add --only-needed flag to llvm-link for AMDGCN

sycl/include/sycl/context.hpp, sycl/include/sycl/detail/info_desc_helpers.hpp, sycl/include/sycl/exception.hpp, sycl/include/sycl/handler.hpp, sycl/include/sycl/stream.hpp, sycl/source/detail/context_info.hpp, sycl/source/detail/device_impl.cpp, sycl/source/detail/device_info.hpp, sycl/source/detail/event_info.hpp, sycl/source/detail/kernel_info.hpp, sycl/source/detail/platform_impl.cpp, sycl/source/detail/platform_impl.hpp, sycl/source/detail/platform_info.hpp, sycl/source/detail/program_manager/program_manager.cpp, sycl/source/detail/ur_info_code.hpp, sycl/source/handler.cpp, sycl/test/include_deps/sycl_accessor.hpp.cpp, sycl/test/include_deps/sycl_buffer.hpp.cpp, sycl/test/include_deps/sycl_detail_core.hpp.cpp
The main change is that specializations of `UrInfoCode` were moved into library, because they are not used in public headers.
Also removed some of unnecessary `#include`s here and there.
=> [SYCL][NFC] Public headers cleanup

sycl/doc/design/OffloadDesign.md
Document SYCL offloading using `--offload-arch` to Intel CPUs, Intel GPUs, NVidia GPUs and AMD GPUs.
=> [SYCL] Update SYCL --offload-arch option.

sycl/test-e2e/HostInteropTask/host-task-two-queues.cpp, sycl/test-e2e/Plugin/sycl-ls.cpp
The two tests reenabled in this test were disabled due to flaky failure on L0. This commit tries to reenable them.
=> [SYCL][E2E] Reenable flaky L0 tests

sycl/test-e2e/RawKernelArg/arg_struct.cpp, sycl/test-e2e/RawKernelArg/arg_vector.cpp
This PR introduces tests for user-defined data types such as `struct`s
=> [SYCL][E2E] Extend `raw_kernel_arg` extension testing

clang/lib/Driver/Driver.cpp, clang/test/Driver/sycl-offload-old-model.c, clang/test/Driver/sycl-offload.c
When passing -fsycl-targets to specify targets to offload to, the user can pass multiple targets.  When those targets are meant to set various associated architectures, those architectures should only be set for a singular given toolchain/target.
Specifying a setting like -fsycl-targets=nvptx64,spir64_gen was setting the wrong device architecture for the spir64_gen compilation.  The associated boundarch for nvptx64 (in this case sm_50) was being pushed to the spir64_gen target, causing the wrong device value to be used for the AOT compilation.
Fix this issue by fixing the logic in which we were assigning the bound architecture to a given triple.  The logic was not taking into account non-spir64_gen targets, assigning the wrong arch when spir64_gen was encountered after the nvptx64 target.
=> [Driver][SYCL] Bound architecture mismatch with multiple targets

.github/workflows/sycl-windows-run-tests.yml
Look for any open processes inside the folders we extract to. I tried a few ideas but this one was the simplest and most stable.
The command only shows processes by the current user by default, and the account isn't an administrator so we can't do anything weird.
=> [CI] Detect hung tests on Windows

sycl/test-e2e/bindless_images/array/fetch_sampled_array.cpp, sycl/test-e2e/bindless_images/array/read_sampled_array.cpp, sycl/test-e2e/bindless_images/array/read_write_unsampled_array.cpp, sycl/test-e2e/bindless_images/cubemap/cubemap_unsampled.cpp, sycl/test-e2e/bindless_images/helpers/common.hpp, sycl/test-e2e/bindless_images/read_sampled.cpp, sycl/test-e2e/bindless_images/read_write_unsampled.cpp
A significant number of bindless images tests use image sizes that are far larger then necessary. This commit reduces them to decrease times that bindless images tests take to complete and adds deterministic varying of local and global sizes in bindless tests.
=> [SYCL][Bindless][E2E] Improve bindless images E2E test times

sycl/test-e2e/Graph/Update/regression_padded_parameter.cpp
Add test that checks graph update functionality when the parameters for the kernel node are large structs with padding added by the compiler.
=> [SYCL][Graph] Add graph test for padded struct parameters

clang/test/CodeGenSYCL/free_function_int_header.cpp, clang/test/CodeGenSYCL/free_function_kernel_params.cpp, clang/test/SemaSYCL/free_function_array_kernel_param.cpp, sycl/test-e2e/KernelAndProgram/free_function_kernels.cpp
Arrays cannot be passed by value as function parameters, so they won’t be supported as free function parameters. To pass an array the simplest way is to wrap it in a struct and pass the struct. This PR adds tests for the case
=> [SYCL] Add testing for arrays as free function kernel parameters

sycl/unittests/Extensions/DeviceGlobal.cpp, sycl/unittests/Extensions/USMMemcpy2D.cpp, sycl/unittests/Extensions/VirtualFunctions/RuntimeLinking.cpp, sycl/unittests/SYCL2020/IsCompatible.cpp, sycl/unittests/SYCL2020/KernelBundle.cpp, sycl/unittests/SYCL2020/KernelBundleStateFiltering.cpp, sycl/unittests/SYCL2020/KernelID.cpp, sycl/unittests/SYCL2020/SpecializationConstant.cpp, sycl/unittests/assert/assert.cpp, sycl/unittests/helpers/UrImage.hpp, sycl/unittests/kernel-and-program/Cache.cpp, sycl/unittests/kernel-and-program/KernelBuildOptions.cpp, sycl/unittests/pipes/host_pipe_registration.cpp, sycl/unittests/program_manager/CompileTarget.cpp, sycl/unittests/program_manager/DynamicLinking.cpp, sycl/unittests/program_manager/arg_mask/EliminatedArgMask.cpp, sycl/unittests/program_manager/passing_link_and_compile_options.cpp, sycl/unittests/scheduler/CommandsWaitForEvents.cpp
This is a first patch in series of detaching unit-test classes from UR names.
In a previous attempts to do so (#14815) there were concerns about what to do with `UrArray` and this PR is another attempt (see also #15014) to do that.
This PR renames `UrArray` into `LifetimeExtender` to better communicate its purpose: data structures emitted by the compiler (and therefore used by the runtime) to describe device image and their properties do not store data, but only hold pointers to them. Therefore when we mock those in our unit-tests we need to ensure that their lifetime is long enough to cover the whole test.
This is a non-functional change by its spirit, but what used to be `UrArray` is now hidden from writers of unit-tests and the interface is switched to `std::vector` - that is done to …
=> [SYCL][NFCI] Refactor `unittest::UrArray`

sycl/test-e2e/Basic/queue/release.cpp, sycl/test-e2e/KernelAndProgram/disable-caching.cpp, sycl/test-e2e/Regression/context_is_destroyed_after_exception.cpp, sycl/test-e2e/Regression/pi_release.cpp, sycl/test-e2e/Scheduler/ReleaseResourcesTest.cpp
These e2e tests started failing after PI removal and replacing it with UR ([PR](https://github.com/intel/llvm/pull/14145)) However, they were not related to it.
On Windows, dlls unloading is inconsistent and if we try to release these UR objects manually, inconsistent hangs happen due to a race between unloading the UR adapters dlls (in addition to their dependency dlls) and the releasing of these UR objects (The proxy loader have solved this problem partially [here](https://github.com/intel/llvm/pull/15262)). So, we currently shutdown without releasing them and windows should handle the memory cleanup.
This behaviour is the same old behaviour as before removing PI as on Investigations on this. This was only hidden before PI removal as it was calling the PI entry-point but doesn't make it …
=> [SYCL] Remove UR objects release checks on Windows

clang/test/Driver/sycl-device-lib-amdgcn.cpp, clang/test/Driver/sycl-device-lib-nvptx.cpp
These tests failed on non Cuda or Hip host machines due to missing installations. Additionally, the `-only-needed` tests don't need `libspirv` so passing `-fno-sycl-libspirv` to the invocation is also required to succeed.
=> [SYCL][Driver] Fix sycl-device-lib test failures for non NVPTX or AMDGPU builds of DPC++

sycl/test-e2e/Basic/recursion-in-constexpr.cpp
Recently we allowed any C++ features to be used in manifestly constant-evaluated expressions in device code. This is an E2E test case testing that recursion can be safely used in this way.
=> [SYCL][E2E] Test recursion in device code

libdevice/imf_rounding_op.hpp
The internal util functions "get_grs_bits" used by rounding mode related functions for both fp32 and fp64 should be marked as static, otherwise linker will report multiple definition error when developers use fp32 and fp64 intel math function in the same compiling unit.
=> [SYCL] Make internal function to be static in imf rounding utils

sycl/doc/extensions/proposed/sycl_ext_oneapi_free_function_kernels.asciidoc, sycl/doc/extensions/proposed/sycl_ext_oneapi_work_group_memory.asciidoc
Fix a couple syntax errors in the examples of some extension specifications.
=> [SYCL][Doc] Fix syntax errors in documentation

sycl/doc/extensions/proposed/sycl_ext_oneapi_free_function_kernels.asciidoc
I forget if we identified this already as an advantage to the enqueue function approach, but it came up recently in a discussion with @tahonermann.  I wanted to record it here, so we don't forget when we get around to implementing this.
=> Elaborate open issue with free function kernels

sycl/doc/extensions/experimental/sycl_ext_intel_cache_controls.asciidoc
This extension has been implemented for a while, and I think we just forgot to update the specification.
=> Make "sycl_ext_intel_cache_controls" experimental

clang/lib/Driver/Driver.cpp, clang/test/Driver/sycl-offload-intelfpga-emu.cpp, clang/test/Driver/sycl-offload-intelfpga-link.cpp
When using -fintelfpga -fsycl-link=image, the host objects were packaged as objects as they would a regular archive.  This was not handled in the same way as -fsycl-link=early, causing an issue with how the objects can be read in, especially on Windows.
Update the -fsycl-link=image behavior when packaging the host objects to match that of -fsycl-link=early.  This allows for the host objects to be unbundled and used as actual objects during the link.  The Microsoft linker does not expect 'main' to be in a library, so breaking this out allows for proper linking with -fsycl-link=image archives.
=> [Driver][SYCL] Host objects usage improvements with -fsycl-link=image

sycl/doc/extensions/proposed/sycl_ext_oneapi_free_function_kernels.asciidoc, sycl/doc/extensions/proposed/sycl_ext_oneapi_get_kernel_info.asciidoc
Add a proposed extension to query a kernel's information descriptor without creating a kernel bundle.
=> [SYCL][DOC] Propose "get_kernel_info" extension

sycl/test-e2e/Basic/image/image_write.cpp, sycl/test-e2e/Basic/image/image_write_fp16.cpp
With the bindless image work already in those tests should be fixed. Test pass consistently in our local testing.
=> [SYCL] Enable image write tests for CUDA

libdevice/nativecpu_utils.cpp
Fixes some issues in Native CPU's libdevice:
* Remove an unused definition of `DefineBroadCastImpl`
* Fix typo in `DefineBroadCastImpl` that lead to incorrect results for broadcast
* Define  `__spirv_GroupAny`/` __spirv_GroupAll` for work groups
=> [SYCL][NATIVECPU] Implement missing work group collectives in Native CPU libdevice

sycl/include/sycl/ext/intel/esimd/detail/math_intrin.hpp, sycl/include/sycl/ext/intel/esimd/math.hpp, sycl/test/check_device_code/esimd/rsqrt_double.cpp
The driver added a perf optimization for this case and asked us to use `__spirv_ocl_rsqrt` instead of `inv(sqrt)` or `__spirv_ocl_native_rsqrt` for double `rsqrt` only.
There is already an E2E test for rsqrt.
=> [SYCL][ESIMD] Use SPIR-V rsqrt for double

clang/test/Driver/sycl-device-traits-macros-amdgcn.cpp
Adding missing `FileCheck` line for `-fsycl-targets=amd_gpu_gfx941` after the pipe `|` to fix the test.
=> [SYCL][Driver] Fix sycl-device-traits-macros-amdgcn test

llvm/lib/SYCLLowerIR/ComputeModuleRuntimeInfo.cpp
I don't know if we consider this NFC but it's pretty close. This was suggested by a code checking tool.
=> [SYCL] Add assert for split type metadata

sycl/test-e2e/ESIMD/group_barrier.cpp
This version is available in a new public released driver and it still fails, I double checked the required version and it was wrong, so fix it.
=> [SYCL][ESIMD][E2E] Fix group barrier test driver check

sycl/include/sycl/ext/oneapi/backend/level_zero.hpp
`find_matching_descendent_device` return type is `std::optional`, meaning it does not need to return a match if none is found. The calling code anticipates this.  But the assert here precludes that path. Removing.
This is causing a bug on one of our big systems so we need the fix. But I'm not sure if a test needs to be added nor how to write such, as we don't see this problem on the lab or CI systems.
=> [SYCL] removal of interfering assert 

sycl/source/queue.cpp, sycl/test-e2e/Graph/RecordReplay/transitive_queue_barrier.cpp
It has been discovered that when a graph event is passed as a dependency to a barrier operation on another in-order queue. This does not trigger the queue to record the operation as it should. Fix this with regression test.
=> [SYCL][Graph] Fix barrier transitive queue recording

clang/lib/Driver/ToolChains/Cuda.cpp, clang/test/Driver/sycl-nvptx-fast-math.cpp
The generation of approximate div/sqrt in the NVPTX backend is driven by the "unsafe-fp-math" function attribute. Presumably when the optimization was first added there was no way of getting at this information from ISel, or even that there was no suitable instruction-level representation to begin with.
Even today, the `afn` fast-math flag is appropriate for relaxing sqrt to an approximate version, but while some targets apply that reasoning to fdiv, it's not clear that's a valid reading of the language reference manual.
The problem with using the function attribute is that when inlining it must be set on *both* caller/callee functions, otherwise it is wiped.
Since CUDA's devicelib bytecode library has hundreds functions with unsafe-fp-math explicitly disabled, if we inline those …
=> [SYCL][NVPTX] Enable approximate div/sqrt with -ffast-math

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/defs.hpp, sycl/test-e2e/syclcompat/defs.cpp
This is done to avoid conflict with upper-case macros redefining e.g. `SUCCESS`. 
I'm also bumping to `0.2.0`.
=> [SYCL][COMPAT] Convert error names to lower case

sycl/include/CL/__spirv/spirv_ops.hpp, sycl/test-e2e/Basic/built-ins.cpp, sycl/test-e2e/DeviceLib/built-ins/printf.cpp, sycl/test-e2e/ESIMD/printf.cpp, sycl/test-e2e/Printf/float.cpp, sycl/test/warnings/variadic_ocl_printf.cpp
The default was flipped in https://github.com/intel/llvm/pull/13055, we can deprecate now and remove during the next ABI breaking window. Also, guard with `__INTEL_PREVIEW_BREAKING_CHANGES` to ensure that removal will actually happen.
=> [SYCL] Deprecate `__SYCL_USE_VARIADIC_SPIRV_OCL_PRINTF__`

sycl/source/accessor.cpp, sycl/source/detail/context_impl.cpp, sycl/source/detail/sampler_impl.cpp, sycl/source/detail/stream_impl.cpp, sycl/source/detail/usm/usm_impl.cpp
fixes post commit build for https://github.com/intel/llvm/pull/15253
=> Fix build failure due to unused variables

sycl/include/sycl/detail/property_list_base.hpp
Unlike GCC 11, GCC 12 doesn't happen to `#include` it implicitly from `<algorithm>`.
=> [SYCL] Add missed `#include <functional>` for `property_list_base.hpp`

sycl/source/detail/program_manager/program_manager.cpp, sycl/test-e2e/DeviceDependencies/math_device_lib.cpp
Handle devicelib requirements of image dependecies, not just the main image.
=> [SYCL] Fix devicelib handling when linking multiple images

sycl/include/sycl/builtins_utils_scalar.hpp, sycl/include/sycl/detail/type_list.hpp, sycl/include/sycl/detail/type_traits.hpp, sycl/source/builtins/integer_functions.cpp, sycl/test/basic_tests/generic_type_traits.cpp, sycl/test/type_traits/type_list.cpp, sycl/test/type_traits/type_traits.cpp
We only used that for `sycl::mad_sat`/`sycl::mul_hi` host implementations. We can just perform the computation on `[u]int64_t` and let the compiler optimize it.
=> [SYCL] Remove `detail::make_larger`

sycl/include/sycl/ext/intel/esimd/memory.hpp, sycl/test-e2e/ESIMD/mask_expand_load.cpp
The unread elements had undefined values, causing sporadic failures.
We can't use the pass_thru arg to gather because that breaks Gen12 which was working before.
Closes: https://github.com/intel/llvm/issues/15257
Closes: https://github.com/intel/llvm/issues/15653
=> [SYCL][ESIMD] Use passthrough for mask_expand_load

sycl/test-e2e/USM/memops2d/memcpy2d_shared_to_dhost.cpp
This was missed in https://github.com/intel/llvm/pull/15649, but it's failing [here](https://github.com/intel/llvm/actions/runs/11277066097/job/31362696913?pr=15626).
=> [SYCL][E2E] XFAIL one more test failing on new driver

devops/dependencies.json
=> [GHA] Uplift Linux GPU RT version to 24.35.30872.22

clang/lib/Driver/Driver.cpp, clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/sycl-offload-intelfpga-emu.cpp, clang/test/Driver/sycl-offload-intelfpga-link.cpp
The recent commit https://github.com/intel/llvm/commit/2df7d3f048c0b65d7aebc365b498370b0806aeab introduced an issue when passing along the host objects in the early (AOCR) archive and consumed by the image (AOCX) archive. Package up (wrap) the images instead of just the list of images by using the -batch functionality with the clang-offload-wrapper.
=> [Driver][SYCL] Properly pass object contents with FPGA archives

llvm/lib/SYCLLowerIR/MutatePrintfAddrspace.cpp, llvm/test/SYCLLowerIR/printf_addrspace/no_matching_store.ll
In SYCLMutatePrintfAddrspacePass, when analyzing a format pointer to printf, do not crash when analyzing backwards through load/stores if no matching store is found.
=> [SYCL] Do not crash if no matching store found

sycl/test-e2e/AddressSanitizer/invalid-argument/out-of-bounds.cpp, sycl/test-e2e/AddressSanitizer/invalid-argument/released-pointer.cpp, sycl/test-e2e/Matrix/SPVCooperativeMatrix/joint_matrix_apply_two_matrices.cpp, sycl/test-e2e/USM/memops2d/copy2d_dhost_to_shared.cpp, sycl/test-e2e/USM/memops2d/copy2d_host_to_shared.cpp, sycl/test-e2e/USM/memops2d/copy2d_shared_to_dhost.cpp, sycl/test-e2e/USM/memops2d/copy2d_shared_to_host.cpp, sycl/test-e2e/USM/memops2d/memcpy2d_dhost_to_shared.cpp, sycl/test-e2e/USM/memops2d/memcpy2d_host_to_shared.cpp, sycl/test-e2e/USM/memops2d/memcpy2d_shared_to_dhost.cpp, sycl/test-e2e/USM/memops2d/memcpy2d_shared_to_host.cpp, sycl/test-e2e/no-xfail-without-tracker.cpp
The USM failures are sporadic, so let's make them unsupported. Also one matrix test is passing. The ASAN tests always fail so XFAIL those.
=> [SYCL][E2E] Fix Arc postcommit

llvm/lib/Transforms/Instrumentation/AddressSanitizer.cpp, llvm/test/Instrumentation/AddressSanitizer/SPIRV/ignore_target_ext_type.ll
We don't know exactly what size it is, so just ignore that type.
=> [DeviceSanitizer] Ignore target extension type

clang/lib/Driver/ToolChains/SYCL.cpp, clang/test/Driver/sycl-device-lib-amdgcn.cpp, clang/test/Driver/sycl-device-lib-nvptx.cpp, clang/test/Driver/sycl-nvptx-link.cpp, clang/test/Driver/sycl-offload-amdgcn.cpp, libdevice/cmake/modules/SYCLLibdevice.cmake
Use AMD and NVIDIA target triples in the names of our generated
devicelib files to be more concise.
=> [SYCL] Rename devicelib files

sycl/doc/extensions/experimental/sycl_ext_oneapi_in_order_queue_events.asciidoc, sycl/source/detail/queue_impl.hpp, sycl/source/queue.cpp, sycl/test-e2e/InOrderEventsExt/get_last_event.cpp, sycl/unittests/Extensions/CMakeLists.txt, sycl/unittests/Extensions/GetLastEvent.cpp
This commit changes the behavior for queue::ext_oneapi_get_last_event when the queue either does not currently have a last event or the last event was discarded. In these cases, the implementation will now insert a marker event at the end of the queue which signifies the work related to the last command in the queue.
Additionally, this allows us to relax the requirements for the extension to now allow it to be used on queues where discarding of events is enabled.
=> [SYCL][Docs] Allow discarded events case for ext_oneapi_get_last_event

sycl/include/sycl/detail/id_queries_fit_in_int.hpp, sycl/include/sycl/handler.hpp, sycl/test/include_deps/sycl_detail_core.hpp.cpp
Outlined runtime checks related to `-fsycl-id-queries-fit-in-int` into a separate header file which is only used in host compilation.
=> [SYCL][NFC] Optmize handler.hpp compilation for device [1/N]

sycl/cmake/modules/FetchUnifiedRuntime.cmake
Updates UR to the latest version that no longer
needlessly fetches CUDA headers.
=> [UR] disable UMF CUDA provider

sycl/source/detail/queue_impl.cpp, sycl/unittests/scheduler/InOrderQueueDeps.cpp
Currently we mistakenly don't mark commands like memcpy, copy, fill etc. as enqueued, this happens because they are enqueued differently bypassing the scheduler.
Problem is that if barrier is submitted depending on such event then it is just omitted.
So, fix the problem by marking such commands as enqueued.
=> [SYCL] Fix barrier submission after command which bypasses the scheduler

libclc/generic/include/math/clc_ldexp.h, libclc/generic/libspirv/math/clc_ldexp.cl, libclc/native_cpu-unknown-linux/libspirv/integer/popcount.cl
`ldexp` in `generic` (for `half`) and `popcount` in `native_cpu` are implemented using clang builtins. This PR makes it so we call the correct "overload" of the builtin:
* `__builtin_ldexpf16` for `half`
* `__builtin_popcountg` for unsigned integer types
* for signed integer types the implicit cast to `int` performed by calling `__builtin_popcount` doesn't work due to sign extension, so we explicitly cast to `unsigned char` or `unsigned short`, and use `__builtin_popcountg`.
=> [SYCL][LIBCLC][NATIVECPU] Fix ldexp and popcount on Native CPU

sycl/test-e2e/no-xfail-without-tracker.cpp
Tracker was added to one of the tests here: https://github.com/intel/llvm/pull/15650
so total number of tests without a tracker need to be reduced.
=> [SYCL][E2E] Update number of tests without XFAIL-TRACKER

sycl/include/sycl/detail/generic_type_lists.hpp, sycl/include/sycl/detail/generic_type_traits.hpp, sycl/include/sycl/vector.hpp, sycl/test/basic_tests/generic_type_traits.cpp
`std::is_same_v` is much clearer when checking for a single specific type, and the helper in `sycl/vector.hpp` could include more than these two types to increase its readability too.
=> [NFC][SYCL] Drop scalar `half`/`bfloat16` type traits

sycl/include/sycl/accessor_image.hpp, sycl/include/sycl/detail/generic_type_traits.hpp
It's only used in a single header for extra filtering of `cl_int` and `cl_float`. We don't need the entirety of "generic" integer types to do that.
Note `(Dims > 0) && ` that I'm dropping here seemed to have no effect as `IsValidCoordDataT` helper ensures `Dims` can't be non-positive. Also, it would be a compiler error and not an SFINAE-based selection because of that helper anyway.
=> [NFC][SYCL] Inline/drop `is_genint_v` type trait

sycl/include/sycl/ext/oneapi/memcpy2d.hpp, sycl/include/sycl/handler.hpp
Moved some of the code under `#ifndef __SYCL_DEVICE_ONLY__`, because it is related to various runtime checks, namely:
- `throwOnLocalAccessorMisuse`
- `checkIfPlaceholderIsBoundToHandler`
- `throwIfGraphAssociated`
This should reduce amount of template insantiations which are performed during device compilation.
Note that implementation of a couple of `memcpy` methods were made completely host-only.
=> [SYCL][NFC] Optmize handler.hpp compilation for device [2/N]

sycl/include/sycl/detail/helpers.hpp, sycl/include/sycl/ext/oneapi/experimental/invoke_simd.hpp, sycl/test/invoke_simd/no_callee_found.cpp
C++17 implementation is about as readable as boost-based one, and we want to drop the external boost dependency for upstreaming purposes.
=> [NFCI][SYCL] Remove `boost::mp11` dependency from `invoke_simd.hpp`

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/device.hpp
Signed-off-by: Jiang, Zhiwei <zhiwei.jiang@intel.com>
=> [SYCL][COMPAT] Add a free function version of has_capability_or_fail

sycl/cmake/modules/FetchUnifiedRuntime.cmake
UR Part: https://github.com/oneapi-src/unified-runtime/pull/2127
=> [UR][DeviceSanitizer] Refactor the code to manage shadow memory

sycl/test-e2e/DeviceImageDependencies/free_function_kernels.cpp
I finally got us a working AMDGPU runner. This test consistently fails and is the only failure. 
With this change we should be able to get all green postcommit CI since what seems like forever.
Ex [here](https://github.com/intel/llvm/actions/runs/11385190600/job/31674912072)
=> [SYCL][E2E] XFAIL test failing on AMD HIP

sycl/cmake/modules/FetchUnifiedRuntime.cmake
-pre-commit PR for https://github.com/oneapi-src/unified-runtime/pull/2063
=> [UR][L0] Refactor to remove default constructor inits

clang/lib/Driver/ToolChains/SYCL.cpp, clang/test/Driver/sycl-ftarget-register-alloc-mode-old-model.cpp, clang/test/Driver/sycl-ftarget-register-alloc-mode.cpp
The use of ocloc -device_options arg only allows for the arg to be a device ID or a version value.
=> [Driver][SYCL] do not pass along HEX values to -device_options

llvm/include/llvm/SYCLLowerIR/ESIMD/ESIMDUtils.h
Need to follow rule of three since there is a user defined destructor, the copy constructor is called never hit at runtime, the copy assignment constructor is never called.
=> [SYCL][ESIMD][NFCI] Fix coverity issues in use of demangler

clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/sycl-host-compiler-old-model.cpp
When using -fsycl-host-compiler, be sure that we only use the available PATH settings to find the compiler given (if given without a full PATH qualifier).  This allows for only known locations to be searched for the given compiler instead of possible internal settings unknown to the user.
=> [Driver][SYCL] Use only PATH when searching for user host compiler

clang/lib/Driver/ToolChains/SYCL.cpp, clang/test/Driver/sycl-offload.cpp
When -fsycl-targets= -fsycl-targets=arg is passed on the command line, the empty -fsycl-targets= is processed and crashes due to the empty argument.  Update the specific option parsing to use 'getLastArg' to avoid this situation.  When the last arg has an empty argument, the driver will diagnose this situation and emit a friendly diagnostic.
=> [Driver][SYCL] Fix crash with empty -fsycl-targets option

llvm/lib/SYCLNativeCPUUtils/CMakeLists.txt
Last pulldown from llvm (2f5b08) breaks the current ock pull. Update to latest where llvm usage matches.
=> [SYCL][NATIVECPU] Fix ock pull down ref to resolve latest llvm pulldown
