llvm/lib/SYCLLowerIR/SYCLVirtualFunctionsAnalysis.cpp, llvm/test/SYCLLowerIR/SYCLVirtualFunctionsAnalysis/calls-indirectly-propagation-4.ll
`computeFunctionToKernelsMapping` did not compute the mapping correctly for leaves of its call graph if the call graph for leaves 3 levels or more deep, which results in some kernels not having inferred `calls-indirectly` being attached. This fixes the logic and cleans up the duplication a bit in the function.
=> [SYCL] Fix logic in virtual function analysis

sycl/gdb/libsycl.so-gdb.py
Modify the local_accessor printer to display data as a linear index from a decorated pointer. This is necessary to retain the address space qualifier.
A simple array printer was added to print local memory like a vector.  The array printer limits the elements displayed based on GDB's print options to avoid displaying large data sets. This can be adjusted in GDB:
(gdb) p -elements 4 -- local_accessor_1d
$1 = sycl::local_accessor range 10 = {0, 1, 2, 3...}
(gdb) show print elements
Limit on string chars or array elements to print is 200.
=> [SYCL][GDB] Display local_accessor elements using a decorated pointer.

sycl/include/sycl/ext/intel/esimd/memory.hpp, sycl/test-e2e/ESIMD/PerformanceTests/BitonicSortK.cpp, sycl/test-e2e/ESIMD/PerformanceTests/BitonicSortKv2.cpp, sycl/test-e2e/ESIMD/PerformanceTests/matrix_transpose.cpp, sycl/test-e2e/ESIMD/api/simd_copy_to_from_stateful.cpp, sycl/test-e2e/ESIMD/api/simd_copy_to_from_stateful_pvc.cpp
We can use block_load and block_store for these functions now in most cases, except when stateful mode is enabled and we're using accessors due to alignment and size requirements.
We also see better performance as seen in the perf test updates with fewer instructions.
The tests were written by Slava in an earlier version of this PR.
=> [SYCL][ESIMD] Simplify the copy_to() and copy_from() implementation

sycl/test-e2e/USM/memops2d/copy2d_dhost_to_shared.cpp, sycl/test-e2e/USM/memops2d/copy2d_host_to_shared.cpp, sycl/test-e2e/USM/memops2d/copy2d_shared_to_dhost.cpp, sycl/test-e2e/USM/memops2d/copy2d_shared_to_host.cpp, sycl/test-e2e/USM/memops2d/memcpy2d_dhost_to_shared.cpp, sycl/test-e2e/USM/memops2d/memcpy2d_host_to_shared.cpp, sycl/test-e2e/USM/memops2d/memcpy2d_shared_to_dhost.cpp, sycl/test-e2e/USM/memops2d/memcpy2d_shared_to_host.cpp
These tests fail sporadically on HIP, as well as DG2. I've updated the [issue](https://github.com/intel/llvm/issues/15648) to track the HIP failures too.
Examples:
https://github.com/intel/llvm/actions/runs/11438947494/job/31821989889
https://github.com/intel/llvm/actions/runs/11434776085/job/31809454917
=> [SYCL][E2E] Disable some USM tests on HIP AMD

llvm/lib/SYCLLowerIR/SYCLJointMatrixTransform.cpp, llvm/test/SYCLLowerIR/JointMatrixTransform/access-chain-no-uses.ll, llvm/test/SYCLLowerIR/JointMatrixTransform/access_chain_bf16.ll
These corner cases are:
1. AccessChain uses are optimized out of LLVM IR modules, leaving the call unused;
2. AccessChain result is used in GEP 0,0 instruction for bfloat16 (instead of the immidiate use by load or store).
All of these issues are or will be fixed in our drivers, but since the cadence of the driver update is relatively big the W/A is added in the frontend for an immediate fix.
=> [SYCL][Matrix] Add W/A for several corner cases of AccessChain usage

sycl/test-e2e/syclcompat/launch/kernel_properties.cpp
Fixing the options for another test that slipped through the cracks of #15364
=> [SYCL][E2E] Use `/clang:` flag on test failing on MSVC driver

.github/workflows/sycl-containers.yaml, .github/workflows/sycl-nightly.yml, sycl/doc/developer/DockerBKMs.md
This container is a version of the intel_drivers container that is built on top of our build container, instead of base. This container is needed to be able to build all e2e tests.
=> [CI][Container] Create new container that combines build and intel driver containers

sycl/doc/extensions/experimental/sycl_ext_matrix/sycl_ext_intel_matrix.asciidoc, sycl/doc/extensions/experimental/sycl_ext_matrix/sycl_ext_oneapi_matrix.asciidoc
This PR:
1. adds more types to PVC combinations, 
2. adds more shapes to PVC combinations,
3. updates the matrix combinations appendix to includes  3 new devices, namely: Battlemage and Lunar Lake that share same matrix combinations as PVC, Arrow Lake H that shares the same matrix combinations as DG2 (Note that these new Intel GPU devices with matrix support have been added to https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/experimental/sycl_ext_oneapi_device_architecture.asciidoc#new-enumeration-of-architectures)
=> [SYCL][Docs][Joint Matrix] Add more devices support and more types and shape combinations 

sycl/test-e2e/SubGroup/attributes.cpp, sycl/test-e2e/SubGroup/info.cpp
The failures related to these two tests were masked due to using unsupported rather than xfail.
This patch also removes the check for OpenCL version before querying `sub_group_independent_forward_progress`, as it masks the failure on the fpga emulator device.
=> [SYCL][E2E] Change UNSUPPORTED to XFAIL in two SubGroup tests

sycl/test-e2e/FilterSelector/select_device.cpp, sycl/test-e2e/FilterSelector/select_device_opencl.cpp
Use new device selector callables, instead of deprecated device selector objects.
These tests do not run on CI because they require multiple devices, so they were missed by the addition of `-Werror` to e2e tests.
=> [SYCL][E2E] Remove use of deprecated device selectors in FilterSelector tests

sycl/doc/extensions/experimental/sycl_ext_matrix/sycl_ext_intel_matrix.asciidoc, sycl/doc/extensions/experimental/sycl_ext_matrix/sycl_ext_oneapi_matrix.asciidoc
- Add missing restriction on the stride of the checked variants of load/store
- Add new overloads of `joint_matrix_load` and `joint_matrix_store` where the offsets are separated from the base pointer and added as separate arguments. I kept the same name as the expectation is to remove the regular variants once the new ones are used instead.
- Add restrictions on both the regular and the offset `joint_matrix_load/store`  on PVC since  in the current implementation, no runtime checks are added as they are expensive. The fall back to 1d load/store is done using a flag instead.
=> [SYCL][Docs][Joint matrix] Add overloads and restrictions for the offset load store

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/device.hpp
Signed-off-by: chenwei.sun <chenwei.sun@intel.com>
=> [SYCL][COMPAT] Add one helper function get_local_mem_size() to get local memory size

sycl/test-e2e/VirtualMem/vector_with_virtual_mem.cpp
Fixed compilation issues with the test and re-enabled it: `usm_shared_allocations` aspect requirement was not spelled correctly and therefore the test was always skipped
=> [SYCL][E2E] Fix VirtualMem tests

sycl/test-e2e/DeviceLib/exp/exp-std-complex-edge-cases.hpp
test-e2e/DeviceLib/exp/exp-std-complex-double-edge-cases.hpp
Removed redundant info, fixed the device code input data, turned off one case for win
=> [SYCL] Update the test

sycl/test-e2e/ESIMD/ext_math.cpp, sycl/test-e2e/ESIMD/ext_math_fast_pvc.cpp, sycl/test-e2e/ESIMD/ext_math_pvc.cpp, sycl/test-e2e/ESIMD/ext_math_saturate.cpp, sycl/test-e2e/ESIMD/ext_math_saturate_pvc.cpp
We need a newer driver for the PVC version of the test.
=> [SYCL][ESIMD][E2E] Add driver requirement to sqrt tests

sycl/test-e2e/AOT/double.cpp, sycl/test-e2e/AOT/half.cpp, sycl/test-e2e/AOT/reqd-sg-size.cpp
cfl support is dropped in the new version of the driver, so remove cfl AOT from tests.
=> [SYCL][E2E] Fix aot tests after driver update

libdevice/cmath_wrapper_fp64.cpp, libdevice/msvc_math.cpp, sycl/test-e2e/DeviceLib/exp/exp-std-complex-edge-cases.hpp
Currently, some corner case test is disabled in exp complex edge test due to some bug in _Exp util function in libdevice, this PR fixes it.
=> [SYCL][libdevice] Fix complex exp corner cases on Windows

sycl/test-e2e/AddressSanitizer/lit.local.cfg
Will re-enable them when post-commit failure
https://github.com/intel/llvm/actions/runs/11474026543/job/31930862668 is fixed.
=> [DeviceASAN] Temporarily disable device address sanitizer tests

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/math.hpp, sycl/test-e2e/syclcompat/math/math_fixt.hpp, sycl/test-e2e/syclcompat/math/math_ops.cpp, sycl/test-e2e/syclcompat/math/math_vectorized.cpp
Add vectorized_ternary and vectorized_with_pred.
Update relu and vectorized_binary.
Signed-off-by: Tang, Jiajun jiajun.tang@intel.com
=> [SYCL][COMPAT] Add vectorized_ternary and vectorized_with_pred.

sycl/test-e2e/Compression/compression.cpp, sycl/test-e2e/Compression/compression_multiple_tu.cpp
Failure: https://github.com/intel/llvm/actions/runs/11468699849/job/31915329901
=> [SYCL] Disable failing compression E2E tests on HIP

sycl/test/no-xfail-without-tracker.cpp
We have all the info at compile time, no need to run this on a device every time. 
Note the directory is moved from `test-e2e` to `test`, it's hard to see in the github UI.
We can drop the `--exclude` since the test isn't in the same folder anymore.
Using `../` is a little gross, but it's worth it to save the resources of running E2E tests multiple times trying to fix failures in this test.
Also manually tested that changing the XFAIL number causes the test to fail in `check-sycl`.
=> [SYCL] Move XFAIL tracker checker test to compile-time

buildbot/configure.py
It's a temporary fix for local build issues with intel/llvm when zstd is not available.
I'll revert this after triaging and fixing the build issue.
=> [SYCL] Temporarily turn off zstd, except on CI

.github/workflows/pr-code-format.yml
It looks like this has been disabled since September(!!) due to a bad merge [here](https://github.com/intel/llvm/commit/9379d84d1784fdac81b427508eb64a119fe82a5b#diff-6860ad0dc3584a2d702e231d5e9e9937e24f43777fd16954ce741eed68e94d50L12).
Thanks to Udit for finding this.
=> [CI] Re-enable clang-format workflow

llvm/lib/SYCLLowerIR/SpecConstants.cpp, llvm/test/SYCLLowerIR/SpecConstants/SYCL-alloca.ll, llvm/test/tools/sycl-post-link/spec-constants/default-value/SYCL-alloca.ll
This allows testing SpecConstantsPass with different modes.
=> [NFC][SYCL][SYCLLowerIR] Add cl::opt SpecConstantMode for LIT testing

sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_arg_dim.cpp, sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_runtime_dim.cpp, sycl/test/no-xfail-without-tracker.cpp
Description: 
The failure of the tests joint_matrix_bf16_fill_k_cache_arg_dim.cpp and joint_matrix_bf16_fill_k_cache_runtime_dim.cpp has been addressed in commit https://github.com/intel/intel-graphics-compiler/commit/92236dc2d0c769b97ba3700b361652013b2cf1c8. The commit solves the issue by changing the Acc 32x64 and Acc 32x32 matrix types from using the array type [2 x <float x 64>] to a structure type { <float x 64>, <float x 64> }
=> [SYCL][Joint Matrix][E2E] Remove xfail from Joint Matrix runtime dimension tests

libdevice/sanitizer_utils.cpp, sycl/test-e2e/AddressSanitizer/invalid-argument/bad-context.cpp, sycl/test-e2e/AddressSanitizer/invalid-argument/host-pointer.cpp, sycl/test-e2e/AddressSanitizer/invalid-argument/out-of-bounds.cpp, sycl/test-e2e/AddressSanitizer/invalid-argument/released-pointer.cpp, sycl/test-e2e/AddressSanitizer/lit.local.cfg
*Re-enable device sanitizer tests for dg2 device
*Update some invalid-argument tests
=> [DeviceASAN] Fix missing return in MemToShadow function for DG2

sycl/unittests/Extensions/CMakeLists.txt
They were disabled because some helpers were missing in UR mock infrastructure. However, they can be built just fine, meaning that the mock infrastructure gap has been already closed.
=> [SYCL] Re-enable unit-tests for virtual functions

buildbot/configure.py
=> Disable zstd even under --ci-defaults for now

sycl/test-e2e/AddressSanitizer/invalid-argument/out-of-bounds.cpp, sycl/test-e2e/AddressSanitizer/invalid-argument/released-pointer.cpp, sycl/test/no-xfail-without-tracker.cpp
They're [passing](https://github.com/intel/llvm/actions/runs/11500888153/job/32012969913) now. I updated the Github issue.
=> [SYCL][DeviceSanitizer] Re-enable XPASSing tests on DG2

buildbot/configure.py, llvm/cmake/config-ix.cmake
**Problem:**
When we use `LLVM_ENABLE_ZSTD=ON` along with `LLVM_USE_STATIC_ZSTD=ON`, LLVM config fails with the following error when libzstd.a is not found but libzstd.so is found:
```
CMake Error at lib/Support/CMakeLists.txt:327 (get_property):
get_property could not find TARGET zstd::libzstd_static.  Perhaps it has
not yet been created.
CMake Error at lib/Support/CMakeLists.txt:330 (get_property):
get_property could not find TARGET zstd::libzstd_static.  Perhaps it has
not yet been created.
```
The bug is in upstream and in the following lines: https://github.com/intel/llvm/blob/sycl/llvm/lib/Support/CMakeLists.txt#L32 - In the `else()`, the code just assumes that static libraries are available.
**Solution:**
When user specifies `LLVM_USE_STATIC_ZSTD=ON`, we should enable ZSTD only if …
=> [SYCL] Fix zstd build when static zstd libraries are not found

sycl/test-e2e/ESIMD/rdtsc.cpp
We test on some platforms where the driver is too old. Also cleaned up the test a bit. Manually verified this version is right, we have it in CI here already too.
=> [SYCL][ESIMD][E2E] Add driver version check to rdtsc test

clang/test/Driver/linker-wrapper-sycl-win.cpp, clang/test/Driver/linker-wrapper-sycl.cpp, clang/test/Driver/linker-wrapper.c, clang/tools/clang-linker-wrapper/ClangLinkerWrapper.cpp
In clang-linker-wrapper, we do not explicitly check if --linker-path is not provided.
This PR adds a check to capture this.
Thanks
=> [clang-linker-wrapper] Add error handling for missing linker path

sycl/test-e2e/Basic/interop/get_native_ocl.cpp
This test was never ran due to requiring the feature `opencl_dev_kit`. This patch replaces this with the feature `opencl_icd`, and fixes the build line to use the `%opencl_lib` expansion.
Fixes part of #15838
=> [SYCL][E2E] Re-enable and fix `Basic/interop/get_native_ocl.cpp` test

sycl/test-e2e/Basic/interop/interop_all_backends.cpp
This test was failing on post commit in these cases after being re-enabled. 
https://github.com/intel/llvm/actions/runs/11523103039
=> [SYCL][E2E] Add more xfails to recently re-enabled test

llvm-spirv/test/DebugInfo/X86/constant-loclist.ll
Cherry-pick of
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2756
The test has evolved upstream since it was forked into this repository and started failing now.  Re-align the invocations and FileCheck patterns with the test in llvm-project.
=> [SPIRV] Align constant-loclist test to upstream

clang/lib/Driver/ToolChains/SYCL.cpp, clang/test/Driver/sycl-ftarget-register-alloc-mode-old-model.cpp, clang/test/Driver/sycl-ftarget-register-alloc-mode.cpp, clang/test/Driver/sycl-offload-new-driver.c
The use of -Xsycl-target-backend=target "opts" was not properly being captured when attempting to find device values to set default values to be used during AOT compilations for GEN.
=> [Driver][SYCL] Fix parsing of device values in backend target opts

sycl/cmake/modules/UnifiedRuntimeTag.cmake
https://github.com/oneapi-src/unified-runtime/pull/2219
Fixes #9964
=> [UR][CL] Support using old ICD loaders

sycl/test-e2e/bindless_images/dx12_interop/read_write_unsampled_semaphore.cpp
The test, dx12_interop/read_write_unsampled_semaphore, non-deterministically fails. We are XFAIL-ing the test until a fix is implemented.
=> [SYCL][Bindless][E2E] XFAIL DX12 read_write_unsampled_semaphore

sycl/test-e2e/Graph/Inputs/buffer_copy_2d.cpp, sycl/test-e2e/Graph/Inputs/buffer_copy_host2target_2d.cpp, sycl/test-e2e/Graph/Inputs/buffer_copy_target2host_2d.cpp, sycl/test-e2e/Graph/Threading/submit.cpp
- Reduce sizes used in some graph tests that were excessively large
- Improves testing performance in performance-limited testing scenarios
=> [SYCL][Graph] Reduce data sizes of some graph E2E tests

sycl/cmake/modules/UnifiedRuntimeTag.cmake
-pre-commit PR for https://github.com/oneapi-src/unified-runtime/pull/2242
=> [L0] Enable Sysman Thru Env by default and have zesInit be optional

sycl/include/sycl/ext/oneapi/experimental/virtual_functions.hpp
We've been using simpler way to define them since
https://github.com/intel/llvm/pull/12831 but somehow that extension missed that.
=> [NFC][SYCL] Simplify properties' definitions in `virtual_functions.hpp`

sycl/include/sycl/ext/oneapi/properties/property.hpp, sycl/include/sycl/ext/oneapi/properties/property_utils.hpp, sycl/include/sycl/ext/oneapi/properties/property_value.hpp, sycl/test/include_deps/sycl_detail_core.hpp.cpp
This should make it easier to follow the logic and understand if template parameters (like `PropertyT`) refer to keys or values.
=> [NFCI][SYCL] Move `IsProperty[*Value]` to `property[_value].hpp`

sycl/include/sycl/ext/oneapi/experimental/prefetch.hpp, sycl/include/sycl/ext/oneapi/properties/property.hpp
Simplified key creation was introduced in
https://github.com/intel/llvm/pull/12831 but this one was never updated. I think it happened because this property never defined `PropKind` enum entry and I'm not even sure how it worked or what are scenarios where it was broken.
Regardless, fix and unify with all other properties with this PR.
=> [SYCL] Modernize prefetch property_key creation

clang/lib/Driver/ToolChains/HIPUtility.cpp, clang/test/Driver/sycl-offload-wrapper-compression.cpp, sycl/test-e2e/Compression/compression.cpp, sycl/test-e2e/Compression/compression_multiple_tu.cpp
Fixes: https://github.com/intel/llvm/issues/15829
**Problem**
`--offload-compress` is being used by HIP in `clang-offload-bundler` and by us in `clang-offload-wrapper`. When we use ` --offload-compress` for SYCL offloading to HIP, the device images gets compressed twice: once in `offload-bundler` and then in `offload-wrapper`.
**~Solution~ Workaround** 
This PR intends to disable compression in `clang-offload-bundler` when offloading to HIP.
=> [Driver] Do not compress bundle when offloading to HIP

libdevice/cmake/modules/SYCLLibdevice.cmake
Add an new function in libdevice CMake to provide a way to pass arbitrary compiling flags when building a device library file. This is preparatory work to add AOT device asan library targeting for different GPU/CPU platforms.
=> [SYCL] Provide a flexible way to compile a single devicelib with specified CFLAGS

sycl/test-e2e/USM/lit.local.cfg
Different tests randomly fail, so disabling the ones that happen to fail isn't productive. Just disable them all. I'll ping HIP people on the GH [issue](https://github.com/intel/llvm/issues/15648) to look into this ASAP.
Examples: [one](https://github.com/intel/llvm/actions/runs/11571336819/job/32209524859), [two](https://github.com/intel/llvm/actions/runs/11555099026/job/32160351729)
=> [SYCL][E2E] Disable USM tests on HIP because they randomly fail

libclc/CMakeLists.txt, libclc/cmake/modules/AddLibclc.cmake, libclc/generic/lib/SOURCES
This splits off several key parts of the build system into utility methods. This will be used in upcoming patches to help provide additional sets of target-specific builtin libraries.
Running llvm-diff on the resulting LLVM bytecode binaries, and regular diff on SPIR-V binaries, shows no differences before and after this patch.
---------
This is a cherry-pick of upstream commit 183b38eb2261164fdfd6b7deac002edf27a39fe7. The conflicts weren't trivial so I thought I'd resolve them myself and not wait for a pulldown. CC @jsji
=> [libclc] Split off library build system into helpers

sycl/test-e2e/Basic/interop/interop_all_backends.cpp
Fails in the nightly [here](https://github.com/intel/llvm/actions/runs/11566567172/job/32196076831). I updated the GH [issue](https://github.com/intel/llvm/issues/15819).
=> [SYCL][E2E] Disable interop_all_backends on L0 Linux

sycl/doc/extensions/experimental/sycl_ext_oneapi_non_uniform_groups.asciidoc
Commit 5d515df02440cde73b85cb2ec0dacf5d68c553c2 moved the `sycl_ext_oneapi_root_group.asciidoc` to `experimental` section. This PR adjusts sources to changes.
=> [SYCL][Doc] Update `sycl_ext_oneapi_root_group.asciidoc` reference

llvm/lib/Transforms/Instrumentation/AddressSanitizer.cpp, llvm/test/Instrumentation/AddressSanitizer/SPIRV/ignore_target_ext_type.ll
The load/store is from sycl header. Skip them since sanitizer is mostly interested in user code.
This avoids backend compiler from removing the unneeded instrumentation when lowering joint matrix access.
=> [DeviceSanitizer] Ignore load/store from joint matrix AccessChain

sycl/test-e2e/Basic/accessor/accessor.cpp, sycl/test-e2e/Basic/fpga_tests/fpga_pipes_mixed_usage.cpp, sycl/test-e2e/Basic/image/srgba-read.cpp, sycl/test-e2e/DeprecatedFeatures/set_arg_interop.cpp, sycl/test-e2e/DeviceArchitecture/device_architecture_comparison_on_device_aot.cpp, sycl/test-e2e/ESIMD/assert.cpp, sycl/test-e2e/LLVMIntrinsicLowering/sub_byte_bitreverse.cpp, sycl/test-e2e/Plugin/interop-cuda-experimental.cpp, sycl/test-e2e/Plugin/interop-experimental-single-TU-SYCL-CUDA-compilation.cpp, sycl/test-e2e/VirtualFunctions/multiple-translation-units/separate-call.cpp, sycl/test-e2e/VirtualFunctions/multiple-translation-units/separate-vf-defs-and-call.cpp, sycl/test-e2e/VirtualFunctions/multiple-translation-units/separate-vf-defs.cpp, sycl/test-e2e/lit.cfg.py, sycl/test-e2e/syclcompat/launch/launch_policy_lmem.cpp, sycl/test/e2e_test_requirements/no-unsupported-without-info.cpp, sycl/test/e2e_test_requirements/no-xfail-without-tracker.cpp
Update the tests that already contain a link.
Also update lit config and tests to not include `.c` files, we don't have such tests in SYCL.
=> [SYCL][E2E] Update some XFAIL tests

llvm/cmake/config-ix.cmake
Currently, if we pass `LLVM_USE_STATIC_ZSTD=ON` and `LLVM_ENABLE_ZSTD=FORCE_ON`, we silently ignore zstd and proceed to build the compiler.
With `LLVM_ENABLE_ZSTD=FORCE_ON`, we should throw an error instead.
Thanks @tcreech-intel for find this.
=> [LLVM] Fail if `LLVM_ENABLE_ZSTD` is `FORCE_ON` but static zstd libraries are not found

sycl/cmake/modules/UnifiedRuntimeTag.cmake
Pulls in a few L0 and sanitizer changes, and an optimization for the tracing layer.
https://github.com/oneapi-src/unified-runtime/pull/2230
=> [UR] update to latest

sycl/include/syclcompat/util.hpp
This uses a ptx instruction to specialize `syclcompat::bit_reverse` for NVPTX backend.
=> [SYCL][COMPAT] Specialize reverse_bits for nvptx

sycl/doc/extensions/proposed/sycl_ext_oneapi_work_group_memory.asciidoc
We decided that it was too easy to mistakenly use the default constructor like this, with the expectation that it statically allocates work-group local memory:
```
void device_code() {
syclex::work_group_memory<int> mem;
}
```
To make this error less likely, we add a parameter to the constructor named `indeterminate`:
```
void device_code() {
syclex::work_group_memory<int> mem{syclex::indeterminate};
}
```
We hope this will make it more apparent that `mem` is just a dummy object, and it needs to be assigned to some other `work_group_memory` object before it can be used.
=> [SYCL][Doc] Add indeterminate to work_group_memory

sycl/doc/extensions/supported/sycl_ext_oneapi_peer_access.asciidoc
The extension document was out of date since it stated that P2P access only worked on CUDA. This updates it to clarify that P2P access is also supported on hip and l0 backends.
=> [doc][ext] Update HIP/L0 support in p2p doc

sycl/test-e2e/Basic/built-ins.cpp, sycl/test/e2e_test_requirements/no-unsupported-without-info.cpp, sycl/test/e2e_test_requirements/no-xfail-without-tracker.cpp
This is causing page faults on every run, which may be contributing to the instability of the runner.
=> [SYCL][E2E] Disable HIP test causing kernel page fault

sycl/test-e2e/bindless_images/3_channel_format.cpp, sycl/test-e2e/bindless_images/examples/example_3_1D_mipmap_anisotropic_filtering_and_levels.cpp, sycl/test-e2e/bindless_images/examples/example_5_sample_cubemap.cpp
Added `%{run}` to lit lines that execute the test binary.
Same change as #15636 to some tests that were added recently.
=> [SYCL][E2E] Add `%{run}` to new tests that did not use it

sycl/test-e2e/DeviceGlobal/device_global_arrow.cpp, sycl/test-e2e/DeviceGlobal/device_global_arrow_dis.cpp, sycl/test-e2e/DeviceGlobal/device_global_device_only.cpp, sycl/test-e2e/DeviceGlobal/device_global_device_only_dis.cpp, sycl/test-e2e/DeviceGlobal/device_global_operator_passthrough.cpp, sycl/test-e2e/DeviceGlobal/device_global_operator_passthrough_dis.cpp, sycl/test-e2e/DeviceGlobal/device_global_static.cpp, sycl/test-e2e/DeviceGlobal/device_global_subscript.cpp, sycl/test-e2e/DeviceGlobal/device_global_subscript_dis.cpp, sycl/test/e2e_test_requirements/no-unsupported-without-info.cpp
This commit adds the UNSUPPORTED-TRACKER line to device_global E2E tests.
=> [SYCL][E2E] Add UNSUPPORTED trackers to device_global tests

sycl/source/detail/device_impl.cpp
Recently added devices `architecture::intel_gpu_bmg_g21, architecture::intel_gpu_lnl_m, and architecture::intel_gpu_arl_h` have matrix support. 
This patch updates the aspect `aspect::ext_intel_matrix` so things like `sycl-ls --verbose` and kernel query show this support when used on these new devices.
=> [SYCL][Joint Matrix] Add missing arch with matrix support to matrix aspect

sycl/source/detail/kernel_program_cache.hpp, sycl/test-e2e/KernelAndProgram/trace_kernel_program_cache.cpp
I'm working on implementing cache eviction and it gets difficult to debug/write test cases without tracing. So, this PR implements tracing for in-memory kernel and program cache.
=> [SYCL] Implement tracing for in-memory kernel and program cache

sycl/include/sycl/ext/oneapi/properties/property.hpp
Missed those in https://github.com/intel/llvm/pull/12831.
=> [NFC][SYCL] Update comments in `sycl/ext/oneapi/properties/property.hpp`

devops/cts_exclude_filter_L0_GPU, devops/cts_exclude_filter_OCL_CPU, sycl/include/sycl/multi_ptr.hpp, sycl/test-e2e/Basic/multi_ptr_legacy.hpp
Apparently, we perform some hacks around constant address space that I wasn't aware of. Make sure new address cast helpers are called consistently with the previous behavior.
=> [SYCL] Fix SYCL-CTS regression after https://github.com/intel/llvm/pull/15543

sycl/unittests/Extensions/CommandGraph/Update.cpp, sycl/unittests/helpers/UrMock.hpp
- Add a unit test and mocking functions that check the command handle behaviour changes from #15522
=> [SYCL][Graph] Add unit test/mocking for command handle behaviour

sycl/test-e2e/KernelCompiler/kernel_compiler_sycl.cpp
in some of the post commit testing the SYCL support of the kernel_compiler is not available. Previously, the test just quietly exited,  but for the cache support the test grew a bit. Now we check the availability before proceeding.
Post commit checks for this are presently running here: https://github.com/intel/llvm/actions/runs/11636755314/job/32408707610
=> [SYCL] fix post-commit failures from kernel_compiler sycl cache PR

sycl/test-e2e/SubGroup/info.cpp
=> [SYCL][E2E] Re-enable `Subgroup/info.cpp` e2e test on FPGA

.github/workflows/sycl-macos-build-and-test.yml
Github Actions no longer [supports](https://github.com/actions/runner-images/issues/10721) MacOS 12 and it's causing postcommit to [fail](https://github.com/intel/llvm/actions/runs/11669376491/job/32491193990). This is confirmed working [here](https://github.com/intel/llvm/actions/runs/11669692319/job/32492218310?pr=15978), build in progress but the runner starts now. Will confirm build passes before merging.
=> [CI] Move Mac runner to MacOS 13

clang/include/clang/Driver/Driver.h, clang/include/clang/Driver/ToolChain.h, clang/lib/Driver/Compilation.cpp, clang/lib/Driver/Driver.cpp, clang/lib/Driver/ToolChain.cpp, clang/lib/Driver/ToolChains/Clang.cpp, clang/lib/Driver/ToolChains/SYCL.cpp, clang/test/Driver/sycl-int-footer-old-model.cpp, clang/test/Driver/sycl-int-header-footer.cpp, clang/test/Driver/sycl-offload-aot.cpp, clang/test/Driver/sycl-offload-intelfpga.cpp, clang/test/Driver/sycl-offload-new-driver.c, clang/test/Driver/sycl-offload-save-temps-old-model.cpp, clang/test/Driver/sycl-offload-save-temps.cpp, clang/test/Driver/sycl-preprocess-old-model.cpp, clang/test/Driver/sycl-preprocess.cpp, clang/test/Driver/sycl-unique-prefix-old-model.cpp, clang/test/Driver/sycl-unique-prefix.cpp
To better match up with what is occurring in the upstream, sync up the changes in the driver.  This sync-up should make it easier to push future changes upstream and reduce confusion as items are pulled down.
Changes include updates to function names, comment updates and some restructuring of how options are passed to the clang -cc1 step.
=> [Driver][SYCL][NFC] Updates to sync up with upstream

sycl/include/syclcompat/math.hpp, sycl/test-e2e/syclcompat/math/math_vectorized.cpp
We add support for logical operators with `vectorized_binary` as well as the relevant unit-tests.
=> [SYCL][COMPAT] Extended vectorized_binary support to logical operators + Tests

sycl/test-e2e/Matrix/slm_utils.hpp
Using `uint` here caused failures in internal testing on windows due to deprecated warnings. This patch replaces it with `unsigned int`.
=> [SYCL][E2E] Replace `uint` with `unsigned int` in `Matrix/slm_utils.hpp`

sycl/test-e2e/Compression/no_zstd_warning.cpp
Currently, when this test is built with a compiler that accepts MSVC-style flags, compilation fails because `-O0` is unrecognized. This PR updates the test to replace `-O0` with `%O0`.
Internal bug report: CMPLRTST-26037
=> [E2E] Fix no_zstd_warning.cpp when built with `clang-cl`

clang/lib/Driver/ToolChains/Clang.cpp, sycl/test-e2e/Compression/compression_separate_compile.cpp
When compiling and linking device images separately, compression related flags are not propagated correctly to `offload-wrapper`. This PR fixes that and updates the test accordingly.
=> [Clang] Fix passing `-offload-compress` when compiling and linking device images separately

sycl/include/sycl/ext/intel/esimd/memory_properties.hpp, sycl/include/sycl/ext/intel/experimental/kernel_execution_properties.hpp, sycl/include/sycl/ext/oneapi/experimental/cluster_group_prop.hpp, sycl/include/sycl/ext/oneapi/kernel_properties/properties.hpp, sycl/include/sycl/ext/oneapi/latency_control/properties.hpp, sycl/include/sycl/ext/oneapi/properties/properties.hpp, sycl/include/sycl/ext/oneapi/properties/property.hpp, sycl/include/sycl/ext/oneapi/properties/property_value.hpp, sycl/include/sycl/kernel_bundle.hpp, sycl/test/abi/sycl_classes_abi_neutral_test.cpp, sycl/test/extensions/annotated_usm/fake_properties.hpp, sycl/test/extensions/properties/mock_compile_time_properties.hpp
This lays some ground base for subsequent refactoring PRs by isolating simple but noisy diff into a separate change.
We're anticipating at least two changes that would be built on top of this:
* Change implementation of `has_property`/`get_property` to be inheritance-based vs type-lists/boost.
* Bigger design-wise refactoring of the compile time properties, e.g. removal of `property_value` class template.
=> [NFCI][SYCL] Introduce `oneapi::experimental::detail::property_base`

libdevice/fallback-complex-fp64.cpp, libdevice/fallback-complex.cpp, sycl/test-e2e/DeviceLib/exp/exp-std-complex-double-edge-cases.cpp, sycl/test-e2e/DeviceLib/exp/exp-std-complex-edge-cases.hpp, sycl/test-e2e/DeviceLib/exp/exp-std-complex-float-edge-cases.cpp, sycl/test/e2e_test_requirements/no-unsupported-without-info.cpp
Follow-up to https://github.com/intel/llvm/pull/15672
This patch updates float behavior
=> [SYCL] Add missing special values to exp(complex)

sycl/cmake/modules/UnifiedRuntimeTag.cmake
Update UR tag to pull in https://github.com/oneapi-src/unified-runtime/pull/2279
=> Bump UR tag to ed9fe09 for L0 loader update

sycl/test-e2e/DeviceGlobal/device_global_copy.cpp
The new test device_global_copy fails to build on Windows due to unrecognized -std option. This commit fixes the flag.
=> [SYCL][E2E] Fix build flag for device_global_copy

sycl/test-e2e/DeviceLib/exp/exp-std-complex-edge-cases.hpp
To cover the rest of checks from https://en.cppreference.com/w/cpp/numeric/complex/exp
=> [SYCL][E2E] Add more checks to exp-std-complex-edge-cases.hpp

sycl/test-e2e/Regression/pf-wg-atomic64.cpp
This DISABLED does nothing. As I understand this test should be run on a device without atomic64 support.
=> [SYCL][E2E] Update pf-wg-atomic64.cpp

sycl/include/sycl/pointers.hpp, sycl/test/check_device_code/extensions/address_cast.cpp, sycl/test/multi_ptr/aliases.cpp
https://github.com/KhronosGroup/SYCL-Docs/pull/598 adds these aliases to the spec. Prepare for spec change by adding them to the implementation beforehand.
Extend tests so all `multi_ptr` aliases are checked.
=> [SYCL] Add `(raw|decorated)_generic_ptr` aliases

.github/workflows/sycl-linux-build.yml, .github/workflows/sycl-macos-build-and-test.yml, sycl/unittests/CMakeLists.txt
`SYCL_PI_TESTS` was deprecated and changed to `SYCL_UR_TESTS`.
=> Change SYCL_PI_TESTS to SYCL_UR_TESTS in CI

devops/cts_exclude_filter_L0_GPU, devops/cts_exclude_filter_OCL_CPU
These tests were turned off as we used some unstable runner previously. Turning them on since we moved to reliable runners.
=> [CI] Turn on test_kernel_bundle and marray

sycl/cmake/modules/UnifiedRuntimeTag.cmake
Pulls in https://github.com/oneapi-src/unified-runtime/pull/2179/
=> [UR] Update UR tag to 9a209aa

sycl/include/sycl/info/device_traits_2020_deprecated.def, sycl/include/sycl/info/device_traits_deprecated.def, sycl/include/sycl/info/info_desc.hpp, sycl/test-e2e/Basic/windows_version_agnostic_sycl_lib.cpp, sycl/test-e2e/Config/kernel_from_file.cpp, sycl/test-e2e/DeviceLib/separate_compile_test.cpp, sycl/test-e2e/SeparateCompile/test.cpp, sycl/test/include_deps/sycl_accessor.hpp.cpp, sycl/test/include_deps/sycl_detail_core.hpp.cpp, sycl/test/warnings/warnings_deprecated.cpp
1. A separate .def file was created for deprecated features that are not part of SYCL 2020 spec
2. info::device::atomic64 was deprecated
3. Test for  info::device::atomic64 deprecated was added into separate file due to -Wno-deprecated-declarations flag in warnings.cpp tests file.
=>  info::device::atomic64 is deprecated

sycl/test-e2e/DeviceLib/imf_fp16_trivial_test.cpp
The imf_fp16_trivial_test has a clangxx invocation with only object files. On Windows, this invocation may have /EHsc, which in this case will be ignored. This issues a warning, which in turn becomes an error when -Werror is set. To avoid this, we ignore unused-argument warnings for this specific invocation.
=> [SYCL][E2E] Avoid unused argument warning for imf_fp16_trivial_test

sycl/include/sycl/group_algorithm.hpp, sycl/include/sycl/nd_item.hpp, sycl/include/sycl/stream.hpp, sycl/include/sycl/sub_group.hpp, sycl/test-e2e/AOT/reqd-sg-size.cpp, sycl/test-e2e/Basic/linear-sub_group.cpp, sycl/test-e2e/Basic/sub_group_size_prop.cpp, sycl/test-e2e/Graph/Inputs/sub_group_prop.cpp, sycl/test-e2e/GroupAlgorithm/SYCL2020/group_sort/common.hpp, sycl/test-e2e/GroupAlgorithm/SYCL2020/permute_select.hpp, sycl/test-e2e/GroupAlgorithm/SYCL2020/shift_left_right.hpp, sycl/test-e2e/GroupAlgorithm/different_types.cpp, sycl/test-e2e/GroupAlgorithm/load_store/partial_sg.cpp, sycl/test-e2e/GroupAlgorithm/reduce_sycl2020.cpp, sycl/test-e2e/GroupAlgorithm/shuffle_marray.cpp, sycl/test-e2e/PerformanceTests/Reduction/reduce_over_sub_group.cpp, sycl/test-e2e/SubGroup/helper.hpp, sycl/test-e2e/SubGroup/sub_group_as.cpp, sycl/test-e2e/SubGroup/sub_group_by_value_semantics.cpp, sycl/test-e2e/SubGroup/sub_groups_sycl2020.cpp, sycl/test-e2e/SubGroupMask/Basic.cpp, sycl/test-e2e/SubGroupMask/GroupSize.cpp, sycl/test-e2e/SubGroupMask/sub_group_mask_ver2.cpp, sycl/test-e2e/XPTI/kernel/content.cpp, sycl/test/include_deps/sycl_detail_core.hpp.cpp
This PR will also allow us to remove `sub_group.hpp` from `sycl.hpp` to make the former an opt-in header (for better compile-times).
=> [SYCL] Make `core.hpp` independent from `sub_group.hpp`

clang/lib/Driver/ToolChains/SYCL.cpp
When using AOT for GPU, we will setup implied options for PVC targets. The strings that are formed need to be added to the vector to be processed later.  One of these strings was a StringRef so the pointed to location can go away.  Make a copy of the string to satisfy the sanitizer.
=> [Driver][SYCL][NFC] Fix memory sanitizer issue for AOT

sycl/source/detail/context_impl.cpp, sycl/source/detail/program_manager/program_manager.cpp, sycl/unittests/helpers/MockDeviceImage.hpp
llvm/sycl/source/detail/context_impl.cpp:496:48: error: 'std::set' may
not intend to support class template argument deduction
[-Werror,-Wctad-maybe-unsupported]
=> [SYCL][NFC] Fix ctad warnings

sycl/test-e2e/LLVMIntrinsicLowering/intrinsic_cmp.cpp
Requires https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2741 to be present in intel/llvm before merging.
=> [SYCL] Add e2e test for llvm.scmp/ucmp.*

.github/CODEOWNERS
Currently, the owners of [sycl/test-e2e/LLVMIntrinsicLowering/*](https://github.com/intel/llvm/tree/sycl/sycl/test-e2e/LLVMIntrinsicLowering) are SYCL RT reviewers but I see that all the test cases here related to llvm-spirv.
I propose changing the code owners of these tests to intel/dpcpp-spirv-reviewers instead.
=> [CI] Change CODEOWNERS of `sycl/test-e2e/LLVMIntrinsicLowering/*` to intel/dpcpp-spirv-reviewers

devops/scripts/install_drivers.sh
Fix the installation failures.
dpkg: error processing archive intel-igc-opencl-devel_2.1.0+0_amd64.deb (--install):
trying to overwrite '/usr/local/bin/iga64', which is also in package intel-igc-media 1.0.17791.9
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Setting up intel-igc-core-2 (2.1.0) ...
=> [CI] force overwrite for iga64 in igc dev driver

clang/tools/clang-offload-wrapper/ClangOffloadWrapper.cpp, sycl/tools/sycl-trace/collector.cpp
`CollectorLibraryWrapper` and `BinaryWrapper` had a custom destructor, but no copy constructor and no copy assignment operator, so they were not complying with the Rule of Three. Explicitly add the two latter as deleted to comply.
=> [SYCL] Make CollectorLibraryWrapper and BinaryWrapper classes comply with Rule of Three.

sycl/test-e2e/AddressSanitizer/nullpointer/private_nullptr.cpp, sycl/test/e2e_test_requirements/no-xfail-without-tracker.cpp
Reverts intel/llvm#15995
@AllanZyne - It looks like this still fails on Arc in post-commit.
=> Revert "[DeviceASAN] Enable e2e test "private_nullptr.cpp""

sycl/include/sycl/ext/oneapi/experimental/annotated_ptr/annotated_ptr.hpp, sycl/include/sycl/ext/oneapi/properties/property_utils.hpp
We want to get rid of it for the upstreaming purposes.
=> [SYCL] Don't use boost/mp11 for properties filtering

sycl/cmake/modules/UnifiedRuntimeTag.cmake
Includes new low-power events API (https://github.com/oneapi-src/unified-runtime/pull/2253) and fixes to urProgramGetInfo (https://github.com/oneapi-src/unified-runtime/pull/2313).
=> [UR] update UR to latest

devops/dependencies-igc-dev.json, devops/scripts/install_drivers.sh, sycl/test-e2e/ESIMD/PerformanceTests/matrix_transpose.cpp, sycl/test/e2e_test_requirements/no-xfail-without-tracker.cpp
=> [GHA] Uplift Linux IGC Dev RT version to igc-dev-ad75a20

sycl/include/sycl/ext/oneapi/properties/properties.hpp, sycl/include/sycl/ext/oneapi/properties/property_utils.hpp, sycl/test/extensions/properties/properties_kernel_negative.cpp
New `merge_properties` can work on property lists containing run-time properties as long as their keys don't conflict. That functionality isn't used anywhere as of now though, hence `NFC` tag.
=> [NFC][SYCL] Refactor `merged_properties_t`

devops/dependencies-igc-dev.json
=> [GHA] Uplift Linux IGC Dev RT version to igc-dev-6ba42ba

sycl/test-e2e/VirtualMem/vector_with_virtual_mem.cpp
XPASSing rarely like [here](https://github.com/intel/llvm/actions/runs/11859980629/job/33054700795). I updated the GH issue.
=> [SYCL][E2E] Move sporadicly passing test vector_with_virtual_mem.cpp to UNSUPPORTED

.github/workflows/sycl-windows-run-tests.yml
If the tests fail or the job is cancelled this should run.
=> [CI] Windows test hang detection should always run

sycl/include/sycl/ext/intel/experimental/fpga_annotated_properties.hpp, sycl/include/sycl/ext/oneapi/experimental/annotated_arg/annotated_arg.hpp, sycl/include/sycl/ext/oneapi/experimental/annotated_ptr/annotated_ptr.hpp, sycl/include/sycl/ext/oneapi/experimental/annotated_ptr/annotated_ptr_properties.hpp, sycl/include/sycl/ext/oneapi/experimental/annotated_usm/alloc_util.hpp
First, `properties` itself has an interface that does exactly that. Second, this trait uses `std::tuple` which is relatively expensive to instantiate and that happens *on top* of the normal `properties` instantation that doesn't use `std::tuple` anymore.
Remaining uses are related to `ConflictingProperties` which is ugly enough to be addressed in a separate PR.
=> [NFCI][SYCL] Remove most uses of `ContainsProperty`

sycl/source/detail/kernel_program_cache.hpp, sycl/source/detail/program_manager/program_manager.cpp
Build options were removed from Kernel cache key in https://github.com/intel/llvm/pull/11351 to reduce the kernel lookup overhead.
This PR removes build options from fast kernel cache key as well.
Quoting https://github.com/intel/llvm/pull/11351
> This can be done because they are either empty or set by the environment variable so they stay the same for the entire program lifecycle for the purposes of in-memory caching.
=> [SYCL] Remove build options from fast kernel cache key

sycl/include/sycl/ext/oneapi/experimental/profiling_tag.hpp, sycl/source/detail/scheduler/commands.cpp, sycl/unittests/Extensions/ProfilingTag.cpp
This commit fixes an issue where the barrier before the timestamp enqueued for the profiling tag in an out-of-order queue did not prevent future work from being enqueued prior to the start/end of the profiling tag.
=> [SYCL] Fix the barrier dependency for OOO profiling tags

clang/lib/Sema/SemaSYCL.cpp, clang/test/CodeGenSYCL/free_function_default_template_arguments.cpp
Somehow even if the outer type was canonical, TypePrinter manages to skip nns printing in case of nested default template arguments. See added test case for the example.
=> [clang][SYCL] Print canonical types in free function shim functions

clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/sycl-spirv-default-options-old-model.c, clang/test/Driver/sycl-spirv-default-options.c, clang/tools/clang-linker-wrapper/ClangLinkerWrapper.cpp
It's left disabled only for FPGA target.
=> [SYCL] Enable nonsemantic.shader.debuginfo.200 by default

sycl/test/check_device_code/native_cpu/shuffle_abi.cpp
Fixes the headers included in `sycl/test/check_device_code/native_cpu/shuffle_abi.cpp`, using just `sycl/sycl.hpp`.
=> [SYCL][NATIVECPU] Fix header inclusion in shuffle_abi test

sycl/test-e2e/InvokeSimd/Spec/simd_mask.cpp, sycl/test-e2e/InvokeSimd/Spec/simd_mask_merge.cpp
I believe that was the last explicit usage of it in the project. Can't remove CMake support for it still because we use boost's `unordered_*map` that depends on mp11.
=> [NFC][SYCL][ESIMD] Don't use boost/mp11 in e2e tests

sycl/test-e2e/lit.cfg.py
Tests can fail if `OCL_ICD_VENDORS` is needed but not set.
=> [SYCL] Pass OCL_ICD_VENDORS to LIT

llvm/lib/SYCLLowerIR/SYCLJointMatrixTransform.cpp
Can be exposed in windows debug build on the tests added by the original patch: LLVM::SYCLLowerIR/JointMatrixTransform/access-chain-no-uses.ll
Author: Jinsong Ji <jinsong.ji@intel.com>
=> Fix the invalid interator after removal

sycl/include/sycl/ext/intel/experimental/grf_size_properties.hpp, sycl/include/sycl/ext/intel/experimental/pipes.hpp, sycl/include/sycl/ext/intel/experimental/task_sequence.hpp, sycl/include/sycl/ext/oneapi/experimental/annotated_usm/alloc_base.hpp, sycl/include/sycl/ext/oneapi/experimental/annotated_usm/alloc_util.hpp, sycl/include/sycl/ext/oneapi/kernel_properties/properties.hpp, sycl/include/sycl/ext/oneapi/properties/properties.hpp, sycl/include/sycl/ext/oneapi/properties/property_utils.hpp, sycl/test/extensions/properties/mock_compile_time_properties.hpp
* Modify `detail::ConflictingProperties` to accept `properties` list instead of `std::tuple` with individual property values
* Remove some "useless" helpers
* Change `detail::ValueOrDefault` type-trait to `detail::get_property_or` as it seems a better interface (and can, in theory, work with runtime properties too)
=> [NFCI][SYCL] More `properties`-related refactoring

sycl/test-e2e/bindless_images/dx12_interop/read_write_unsampled.cpp
this should fix the compfail on this test when using clang-cl.
=> [SYCL][E2E] Use `/clang:` when using MSVC driver on bindless images test

sycl/include/sycl/ext/oneapi/properties/properties.hpp, sycl/include/sycl/kernel_bundle.hpp
First, rename it, because it's just the accident that all its current users only supply runtime properties that just happen to be property keys in addition to being property values.
Second, use C++17.
=> [NFC][SYCL] Refactor `all_props_are_keys_of`

llvm/test/CodeGen/SPIRV/transcoding/TransFNeg.ll
=> Reenable CodeGen/SPIRV/transcoding/TransFNeg.ll on Windows

llvm/include/llvm/ADT/StringRef.h
These functions have been deprecated since:
commit 5ac12951b4e9bbfcc5791282d0961ec2b65575e9
Author: Kazu Hirata <kazu@google.com>
Date:   Sun Dec 17 15:52:50 2023 -0800
=> [ADT] Remove StringRef::{startswith,endswith} (#89548)

sycl/cmake/modules/FetchUnifiedRuntime.cmake, sycl/cmake/modules/UnifiedRuntimeTag.cmake
https://github.com/oneapi-src/unified-runtime/pull/2326
=> [UR] Update tag to b0f9293 for UR#2326

sycl/test-e2e/Graph/Update/dyn_cgf_different_arg_nums.cpp
CI is showing fails like https://github.com/intel/llvm/actions/runs/11969728548/job/33373742453?pr=15843
```
FAIL: SYCL :: Graph/Update/dyn_cgf_different_arg_nums.cpp (1219 of 2194)
******************** TEST 'SYCL :: Graph/Update/dyn_cgf_different_arg_nums.cpp' FAILED ********************
Exit Code: 1
Command Output (stdout):
--
/__w/llvm/llvm/toolchain/bin//clang++  -Werror  -fsycl -fsycl-targets=nvptx64-nvidia-cuda  /__w/llvm/llvm/llvm/sycl/test-e2e/Graph/Update/dyn_cgf_different_arg_nums.cpp -o /__w/llvm/llvm/build-e2e/Graph/Update/Output/dyn_cgf_different_arg_nums.cpp.tmp.out
env SYCL_UR_TRACE=2 env SYCL_PI_CUDA_ENABLE_IMAGE_SUPPORT=1 ONEAPI_DEVICE_SELECTOR=cuda:gpu  /__w/llvm/llvm/build-e2e/Graph/Update/Output/dyn_cgf_different_arg_nums.cpp.tmp.out | …
```
=> [SYCL][Graph] Fix E2E Filecheck regex

clang/lib/Sema/SemaSYCL.cpp, clang/test/CodeGenSYCL/int_footer_with_explicit_specialization.cpp
A recent change to sycl headers revealed a bug in integration footer - missing nns in case of an explicit template specialization in some of device_global's template arguments.
=> [clang][SYCL] Emit canonical types in integration footer

sycl/test-e2e/Basic/empty_command.cpp
We currently have a bug here and ignore some required dependencies. That will be addressed in a separate functional PR.
=> [E2E][SYCL] Test for empty command group behavior

sycl/doc/extensions/experimental/sycl_ext_intel_cache_controls.asciidoc, sycl/doc/extensions/experimental/sycl_ext_intel_fpga_task_sequence.asciidoc, sycl/doc/extensions/experimental/sycl_ext_oneapi_device_global.asciidoc, sycl/doc/extensions/experimental/sycl_ext_oneapi_kernel_arg_properties.asciidoc, sycl/doc/extensions/experimental/sycl_ext_oneapi_kernel_compiler.asciidoc, sycl/doc/extensions/experimental/sycl_ext_oneapi_kernel_properties.asciidoc, sycl/doc/extensions/experimental/sycl_ext_oneapi_properties.asciidoc, sycl/doc/extensions/proposed/sycl_ext_intel_fpga_kernel_arg_properties.asciidoc, sycl/doc/extensions/proposed/sycl_ext_intel_fpga_kernel_interface_properties.asciidoc, sycl/doc/extensions/proposed/sycl_ext_oneapi_forward_progress.asciidoc, sycl/doc/extensions/proposed/sycl_ext_oneapi_free_function_kernels.asciidoc, sycl/doc/extensions/proposed/sycl_ext_oneapi_work_group_static.asciidoc, sycl/include/sycl/ext/oneapi/experimental/cluster_group_prop.hpp, sycl/include/sycl/ext/oneapi/kernel_properties/properties.hpp, sycl/include/sycl/ext/oneapi/properties/property.hpp, sycl/test/extensions/annotated_arg/annotated_arg_properties.cpp, sycl/test/extensions/annotated_ptr/annotated_ptr_properties.cpp, sycl/test/extensions/annotated_usm/fake_properties.hpp, sycl/test/extensions/device_global/device_global_properties.cpp, sycl/test/extensions/fpga_mem/fpga_mem_properties.cpp, sycl/test/extensions/properties/properties_device_global.cpp, sycl/test/extensions/properties/properties_is_property_key.cpp, sycl/test/extensions/properties/properties_kernel.cpp, sycl/test/extensions/properties/properties_kernel_cache_config.cpp, sycl/test/extensions/properties/properties_kernel_fpga.cpp, sycl/test/extensions/properties/properties_latency_control.cpp, sycl/test/extensions/properties/properties_pipe.cpp, sycl/test/extensions/properties/properties_task_sequence.cpp, sycl/test/extensions/task_sequence/task_sequence_properties.cpp, sycl/test/virtual-functions/properties-positive.cpp
This is an API-breaking change, but for an experimental feature and we don't expect this particular interface was used by customers.
=> [SYCL] Remove `sycl::ext::oneapi::experimental::is_property_key`

devops/dependencies-igc-dev.json
=> [GHA] Uplift Linux IGC Dev RT version to igc-dev-7dad678

sycl/unittests/kernel-and-program/MultipleDevsCache.cpp
This test case didn't work properly (incorrect number of retains/releases) before the fix for multi-device case: https://github.com/intel/llvm/pull/15546
=> [SYCL][Test] Extend MultipleDevsCache test to check different order of devices

sycl/include/sycl/detail/os_util.hpp, sycl/source/detail/os_util.cpp, sycl/source/detail/persistent_device_code_cache.hpp, sycl/tools/sycl-trace/collector.cpp, sycl/ur_win_proxy_loader/ur_win_proxy_loader.cpp
These are used internally in the DSO and don't need to be exposed outside.
`OSUtil::getDirName` will become `static` inside single TU under the `-fpreview-breaking-changes` flag and `private` for the time being without the flag (to make sure no new uses will be added outside the TU).
`OSUtil::getCurrentDSODir` is used in several TUs, so simply make it `__SYCL_DLL_LOCAL` to remove from exported symbols during the next ABI-breaking window.
=> [SYCL] Remove some `OSUtil::*` funcs from ABI under `-fpreview-breaking-changes`

sycl/include/sycl/property_list.hpp
Coverity suggested this optimization.
Internal tracker: CMPLRLLVM-63376
=> [SYCL] Use `std::move` instead of copy

sycl/doc/extensions/experimental/sycl_ext_oneapi_graph.asciidoc, sycl/test-e2e/Graph/Explicit/free_function_kernels.cpp, sycl/test-e2e/Graph/Inputs/free_function_kernels.cpp, sycl/test-e2e/Graph/RecordReplay/free_function_kernels.cpp, sycl/test-e2e/Graph/Update/FreeFunctionKernels/free_function_kernels.hpp, sycl/test-e2e/Graph/Update/FreeFunctionKernels/update_before_finalize.cpp, sycl/test-e2e/Graph/Update/FreeFunctionKernels/update_with_indices_multiple_exec_graphs.cpp, sycl/test-e2e/Graph/Update/FreeFunctionKernels/update_with_indices_ordering.cpp, sycl/test-e2e/Graph/Update/FreeFunctionKernels/update_with_indices_ptr.cpp, sycl/test-e2e/Graph/Update/FreeFunctionKernels/update_with_indices_ptr_3D.cpp, sycl/test-e2e/Graph/Update/FreeFunctionKernels/update_with_indices_ptr_double_update.cpp, sycl/test-e2e/Graph/Update/FreeFunctionKernels/update_with_indices_ptr_multiple_nodes.cpp, sycl/test-e2e/Graph/Update/FreeFunctionKernels/update_with_indices_ptr_multiple_params.cpp, sycl/test-e2e/Graph/Update/FreeFunctionKernels/update_with_indices_ptr_subgraph.cpp, sycl/test-e2e/Graph/Update/FreeFunctionKernels/update_with_indices_scalar.cpp, sycl/test-e2e/Graph/graph_common.hpp
Dynamic parameters in SYCL Graphs should be used for now with free_function_kernels extension since then the order of kernel arguments is well defined. 
The tests are a copy of few selected ones from `Graph/Update` and modified such that they use the extension. They live in `Graph/Update/FreeFunctionKernels`.
Since the free function kernels are not yet implemented on CUDA, we should keep for now both copies of the tests (with and without free functions).
=> [SYCL][GRAPH] Add graph E2E tests which use free function extension

sycl/source/detail/device_impl.cpp
A C-style array with unspecified bounds allows the array to grow as new members are added, while avoiding the heap allocation of `std::vector` that is immediately freed.
=> [SYCL] Avoid a short-lived heap allocation

sycl/source/detail/scheduler/commands.cpp, sycl/source/handler.cpp, sycl/test-e2e/Basic/empty_command.cpp, sycl/test-e2e/WeakObject/weak_object_utils.hpp, sycl/test-e2e/XPTI/image/accessors.cpp
This is a recommit of https://github.com/intel/llvm/pull/16180. Post-commit CI had a few tests failing so the original PR was reverted. The reason of the failures is that with proper dependencies tracking we now try to actually create images on the device and it might fail if device isn't capable of that. This updated version of the PR also modifies those failing tests to skip checks on unsupported devices
=> [SYCL] Honor dependencies of empty command groups

sycl/test-e2e/Basic/built-ins/marray_common.cpp
https://github.com/intel/llvm/pull/15223 updated the normal build command but not the `preview-breaking-changes` one. Fix that here.
=> [E2E][SYCL] Actually disable fast math in `marray_common.cpp` test

sycl/test-e2e/syclcompat/launch/launch.cpp
The `int_ptr` is pointed to random memory, which causes the Device Address Sanitizer to complain that it points to unknown memory.
=> [SYCL][E2E] set pointer to nullptr to avoid Device Address Sanitizer complain about invalid pointer.

llvm/include/llvm/SYCLLowerIR/ESIMD/ESIMDUtils.h, llvm/lib/SYCLLowerIR/ESIMD/ESIMDUtils.cpp, llvm/lib/SYCLLowerIR/ESIMD/LowerESIMD.cpp, llvm/lib/SYCLLowerIR/ESIMD/LowerESIMDKernelAttrs.cpp, llvm/test/SYCLLowerIR/ESIMD/prop_metadata.ll
The internal compiler uses aggressive inlining, and we have a case where a wrapper function that calls an ESIMD function has had the ESIMD functions body inlined into it. The parent function does not have the ESIMD attribute, so this causes the pass that propagates the ESIMD attribute to fail, which ends up causing `sycl-post-link` to do the wrong thing. It works fine when the inlining does not happen because this pass propagates the attribute. Extend the ESIMD attribute propagation pass to also consider functions that call ESIMD intrinsics as ESIMD functions.
=> [SYCL][ESIMD] Fix propagation of ESIMD attribute for inlined functions

devops/dependencies-igc-dev.json
=> [GHA] Uplift Linux IGC Dev RT version to igc-dev-6ee988a

libclc/amdgcn-amdhsa/libspirv/atomic/atomic_helpers.h, libclc/ptx-nvidiacl/libspirv/atomic/atomic_cmpxchg.cl, libclc/ptx-nvidiacl/libspirv/atomic/atomic_helpers.h, libclc/ptx-nvidiacl/libspirv/atomic/atomic_load.cl, libclc/ptx-nvidiacl/libspirv/atomic/atomic_store.cl, sycl/test-e2e/AtomicRef/work_item_scope.cpp
Add Invocation case, that falls back to a coarser grained scope, to libclc atomic functions. This prevents hangs on AMD and crashes on NVIDIA when using atomic_ref functionality with work_item scope.
Add a test which simply checks that the kernel does not crash when using atomic_ref with work_item scope.
See issue: https://github.com/intel/llvm/issues/16037
=> [SYCL][libclc][E2E] atomic work_item scope fallback

devops/cts_exclude_filter_L0_GPU, devops/cts_exclude_filter_OCL_CPU
After https://github.com/intel/llvm/pull/15389 and https://github.com/KhronosGroup/SYCL-CTS/pull/935 got merged, these CTS tests can be reenabled.
=> [CI][CTS] Turn on `test_multi_ptr`

sycl/test-e2e/lit.cfg.py
In an environment with no devices this variable is never set, causing a confusing error when we try to define the `clangxx` expansion. Here we set it to an empty string by default so that instead of exiting with a python error we report all tests as unsupported (due to having no devices).
This same issue is why `arch_flag` was set in build-only mode, so I removed the line that did that too.
=> [SYCL][E2E] Initialize `arch_flag` to an empty string by default

sycl/include/sycl/ext/oneapi/device_global/device_global.hpp
This commit fixes an issue where the function extracting the initial value of a device_global would return it as a reference to a different type, which in turn could cause some unexpected behavior.
=> [SYCL] Fix return type of initialization value extraction

sycl-jit/jit-compiler/include/KernelFusion.h, sycl-jit/jit-compiler/lib/KernelFusion.cpp, sycl-jit/jit-compiler/lib/rtc/DeviceCompilation.cpp, sycl-jit/jit-compiler/lib/rtc/DeviceCompilation.h, sycl/source/detail/jit_compiler.cpp, sycl/test-e2e/KernelCompiler/kernel_compiler_sycl_jit.cpp
Adds support for correct error message routing and the `save_log` property to the SYCL-RTC implementation based on the SYCL-JIT library. 
The diagnostic messages associated with any errors encountered during runtime compilation is stored in the `what` of the exception thrown. 
If the user passes the `save_log` property defined in the `kernel_compiler` extension, all diagnostics encountered during compilation (errors, warnings, notes and remarks) are stored in the user-provided string.
=> [SYCL][RTC] Add support for errors and build log in JIT-based RTC

sycl-jit/jit-compiler/lib/rtc/DeviceCompilation.cpp
Fix warning resulting from default case covering other cases, causing post-commit to fail.
=> [SYCL][RTC] Fix warning caused by default case

clang/lib/CodeGen/CGVTables.cpp, clang/test/CodeGenSYCL/dont-emit-cxx-pure-virtual.cpp
This special symbol is used to handling calls to pure virtual functions in regular C++ program. However, for SYCL device code we do not have a guarantee that this symbol will be provided by SYCL backend compilers.
Considering that pure virtual function call is an undefined behavior anyway, this PR replaces `@__cxa_pure_virtual` uses with `null` during SYCL device compilation to avoid issues with unresolved symbols.
=> [SYCL] Don't emit @__cxa_pure_virtual into device code

sycl/test-e2e/syclcompat/launch/launch_policy_lmem.cpp
test is working on PVC.  
Will need to close issue https://github.com/intel/llvm/issues/14826 once this PR is merged.
=> [SYCL] reenable launch_policy test on PVC. 

.github/workflows/sycl-containers.yaml, devops/containers/ubuntu2404_base.Dockerfile, devops/scripts/install_build_tools.sh, sycl/doc/developer/DockerBKMs.md
dev-igc requites Ubuntu 24.04 now (because of glibc requirement). I need to update the dev-igc container creation/run to use Ubuntu 24.04, but first I need to add the base image that I can base the dev-igc image on, it can't be done in the same PR.
The changes to the install script are because of changes in 24.04, there should be no net effect.
Some of the Docker CI runs are going to fail here, but they will fail in every PR even without this change because of the new dev-igc requirement, we just need to make sure the new container I added here passes, which it [did](https://github.com/intel/llvm/actions/runs/12145849016/job/33868646520?pr=16250).
=> [CI] Add Ubuntu 24.04 base image

sycl/test-e2e/Matrix/element_wise_all_ops_impl.hpp, sycl/test-e2e/Matrix/element_wise_ops_impl.hpp, sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_arg_dim.cpp, sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_impl.hpp, sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_runtime_dim.cpp, sycl/test-e2e/Matrix/joint_matrix_rowmajorA_rowmajorB_impl.hpp, sycl/test/e2e_test_requirements/no-xfail-without-tracker.cpp
Description:
The support for combination 32x32x16 on DG2 has been implemented in commit https://github.com/intel/intel-graphics-compiler/commit/6a06c93eed6f512ee8d713c179f3eab5e419ef9b.  This PR re-enables the Joint Matrix tests for the combination 32x32x16, which were previously unsupported.
This PR also adds XFAIL: gpu to two tests, joint_matrix_bf16_fill_k_cache_arg_dim.cpp and joint_matrix_bf16_fill_k_cache_runtime_dim.cpp, because the driver has not yet been updated to include the necessary changes in IGC to support these tests. As a result, these tests should not be tested in CI at this time.
=> [SYCL][Joint Matrix][E2E] Uncomment the Joint Matrix tests for combination 32x32x16

clang/lib/Driver/ToolChains/SYCL.cpp, clang/test/Driver/sycl-device-lib-bfloat16.cpp
When using -fsycl-targets=spir64_gen -Xsycl-target-backend "-device pvc" the driver will pull in the native bfloat16 device library.  This was not occurring when using -fsycl-targets=intel_gpu_pvc
=> [Driver][SYCL] Allow for intel_gpu_pvc to pull in the native bfloat lib

sycl/test-e2e/lit.cfg.py
=> [SYCL][E2E] Change pattern matching to if-else statements in `lit.cfg.py`

sycl/test-e2e/ESIMD/acc_gather_scatter_rgba_stateless_64.cpp, sycl/test-e2e/ESIMD/accessor_gather_scatter_stateless_64.cpp, sycl/test-e2e/ESIMD/accessor_load_store_stateless_64.cpp, sycl/test-e2e/ESIMD/accessor_stateless_64.cpp, sycl/test-e2e/ESIMD/accessor_stateless_ctor_64.cpp, sycl/test-e2e/ESIMD/dpas/dpas_tf32.cpp, sycl/test-e2e/ESIMD/lsc/lsc_block_load_store_stateless_64.cpp, sycl/test-e2e/ESIMD/lsc/lsc_gather_scatter_stateless_64.cpp, sycl/test-e2e/ESIMD/lsc/lsc_load_store_2d_compare.cpp, sycl/test-e2e/ESIMD/slm_init_no_inline.cpp
Follow-up after https://github.com/intel/llvm/pull/15905
These tests use `using` directive for both `sycl` and `esimd` namespaces and `info` is available in both, so we have to explicitly specify namespace in this case to avoid ambiguity.
Hasn't been noticed before because tests run only on pvc.
=> [SYCL][ESIMD][E2E] Fix ambiguity in device descriptor usages in ESIMD tests

sycl-jit/common/include/Kernel.h, sycl-jit/jit-compiler/CMakeLists.txt, sycl-jit/jit-compiler/lib/KernelFusion.cpp, sycl-jit/jit-compiler/lib/rtc/DeviceCompilation.cpp, sycl-jit/jit-compiler/lib/rtc/DeviceCompilation.h, sycl-jit/jit-compiler/lib/rtc/ESIMD.cpp, sycl-jit/jit-compiler/lib/rtc/ESIMD.h, sycl/test-e2e/KernelCompiler/kernel_compiler_sycl_jit.cpp
Adds support for compiling source strings that contain ESIMD kernels *only*, hence require no device splitting. I'm using a simplified version of the driver logic in `sycl-post-link`. The pass pipeline construction helper `lowerEsimdConstructs` is also copied from `sycl-post-link`.
=> [SYCL][RTC] Preliminary support for ESIMD kernels

sycl/cmake/modules/UnifiedRuntimeTag.cmake
https://github.com/oneapi-src/unified-runtime/pull/2353
https://github.com/oneapi-src/unified-runtime/pull/2413
=> [UR] Update tag to 3fdf7e3 for UR #2353 and #2413

sycl/source/detail/scheduler/commands.cpp
Manually reproduced the error and confirmed the fix. No idea why we need to do this though.
=> [SYCL] Fix build again after d0d8a56

.github/workflows/sycl-containers-igc-dev.yaml, .github/workflows/sycl-containers.yaml, .github/workflows/sycl-linux-precommit.yml, devops/containers/ubuntu2404_intel_drivers.Dockerfile, devops/containers/ubuntu2404_intel_drivers_igc_dev.Dockerfile, devops/dependencies-igc-dev.json, devops/scripts/install_drivers.sh, sycl/doc/developer/DockerBKMs.md
dev_igc and unstable need Ubuntu 24.04 now based on the IGC packaging, so move our Dockerfiles and CI to use 24.04 for these.
I needed to manually bump the dev-igc version because the artifacts for the current one are expired so they can't be downloaded anymore so we can't make the Docker image.
The dev-igc CI run is expected to fail here, it always uses the official intel/llvm Docker images, even if the current PR updates them, so we need to wait for this PR to be merged to test it. I'll watch it once we merge.
=> [CI] Use Ubuntu 24.04 for dev-igc and unstable

.github/workflows/sycl-linux-precommit.yml, .github/workflows/sycl-post-commit.yml
`clang` seems to produce more warnings which causes build failures with `-werror` which is enabled by default in CI, so use `clang` in precommit to catch those issues before merging.
=> [CI] Use clang in precommit and gcc in postcommit for Linux builds

sycl/include/sycl/detail/backend_traits_cuda.hpp, sycl/include/sycl/detail/backend_traits_hip.hpp, sycl/include/sycl/detail/backend_traits_level_zero.hpp, sycl/include/sycl/detail/backend_traits_opencl.hpp, sycl/include/sycl/handler.hpp, sycl/include/sycl/image.hpp, sycl/include/sycl/kernel_bundle.hpp, sycl/include/sycl/queue.hpp, sycl/include/sycl/usm.hpp, sycl/source/platform.cpp
Replaced them with forward declarations. Unfortunatly, it isn't enough of a cleanup to actually reduce amount of dependencies of `core.hpp` because of image and buffer properties.
=> [SYCL][NFC] Cleanup includes of `context.hpp`

sycl/doc/extensions/experimental/sycl_ext_oneapi_graph.asciidoc, sycl/test-e2e/Graph/Explicit/work_group_memory.cpp, sycl/test-e2e/Graph/Explicit/work_group_memory_free_function.cpp, sycl/test-e2e/Graph/Inputs/free_function_kernels.cpp, sycl/test-e2e/Graph/Inputs/work_group_memory.cpp, sycl/test-e2e/Graph/Inputs/work_group_memory_free_function.cpp, sycl/test-e2e/Graph/RecordReplay/work_group_memory.cpp, sycl/test-e2e/Graph/RecordReplay/work_group_memory_free_function.cpp
Document support for using [sycl_ext_oneapi_work_group_memory](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/experimental/sycl_ext_oneapi_work_group_memory.asciidoc) inside a graph kernel node, with E2E tests for verification.
E2E Tests for `work_group_memory` update in executable graphs is has been included in PR https://github.com/intel/llvm/pull/16025 , as it requires a UR fix that is part of that PR.
=> [SYCL][Graph] Support work_group_memory extension

sycl/include/sycl/ext/intel/experimental/pipes.hpp, sycl/include/sycl/ext/oneapi/experimental/graph.hpp
The former is defined by the toolchain while the latter is part of SDK, so using `_WIN32` is preferrable. The issue was exposed downstream due to recent changes from https://github.com/intel/llvm/pull/16178 and https://github.com/intel/llvm/pull/16194.
=> [SYCL] Prefer `_WIN32` over `WIN32` in `#if` expressions

libclc/utils/libclc-remangler/LibclcRemangler.cpp
Add copy constructor and copy assignment operator.
=> [libclc][BumpPointerAllocator] fix coverity issue: Rule Of Three

llvm/lib/Transforms/Instrumentation/AddressSanitizer.cpp
https://github.com/llvm/llvm-project/pull/113331 deprecates usage of getPointerTo, llvm::PointerType::get is recommended instead. This updates AddressSanitizer to use the recommended function in place of the deprecated one.
=> [DevASAN] Remove usage of deprecated getPointerTo from AddressSanitizer

sycl/include/sycl/context.hpp, sycl/include/sycl/detail/info_desc_helpers.hpp, sycl/include/sycl/device.hpp, sycl/include/sycl/event.hpp, sycl/include/sycl/kernel.hpp, sycl/include/sycl/platform.hpp, sycl/include/sycl/queue.hpp, sycl/test-e2e/Basic/backend_info.cpp
It doesn't seem that the interfaces match the spec, so it's highly likely that these methods will be deprecated/removed anyway, so there is little point in fixing them to work in `_GLIBCXX_USE_CXX11_ABI=0` mode.
On the other hand, using `_GLIBCXX_USE_CXX11_ABI=0` causes segmentation fault crashes due to ABI mismatches in runtime, so emitting compile-time error is a better thing to do here.
=> [SYCL] Emit error when `get_backend_info` is used under `_GLIBCXX_USE_CXX11_ABI=0`

sycl/test-e2e/OptionalKernelFeatures/fp64-conv-emu-1.cpp, sycl/test-e2e/OptionalKernelFeatures/fp64-conv-emu-2.cpp
Updated the test to cover more HW so that there is a less change that we will simply skip it.
Note that FP64 emulation is only enabled by default on DG2. Therefore, we include HW which
natively supports `fp64`, but can't include any HW without `fp64` support except for DG2 unless
we tweak the environment to force-enable emulation on those platforms.
=> [SYCL][E2E] Expand fp64 emulation testing

sycl/include/sycl/accessor.hpp, sycl/source/detail/config.cpp
Two changes were made:
Special `padding` field in accessors is now zero-initialized. We construct a `host_accessor` object in our stream implementation and static analyzer complained that some of the accessor's fields were uninitialized. It is not like we even reference `padding` field from anywhere, but the code change seems small, so I decided to add the initializer.
Fixed a condition to prevent access to an array of `N` elements at index `N`, which is outside of the array because they are 0-indexed.
=> [SYCL][NFCI] Address static analyzer concerns

sycl/test-e2e/Graph/Update/dyn_cgf_accessor_spv.cpp
The E2E SYCL-Graph test `Update/dyn_cgf_accessor_spv.cpp` checks that after the first execution of the graph, the accessor referencing `bufferB` has not been written to. This is done by checking for zero on the line
```cpp
assert(check_value(i, 0, HostDataB[i], "HostDataB"));
```
However, we never explicitly initialize `bufferB` to zero in the test, it is still uninitialized at the point of this assert. Therefore this check against zero is based on UB. This patch fixes the test by initializing the buffers to zero at the beginning of the test.
=> [SYCL][Graph] Fix dyn_cgf_accessor_spv.cpp Test

devops/containers/ubuntu2204_base.Dockerfile, devops/containers/ubuntu2204_build.Dockerfile, devops/containers/ubuntu2204_intel_drivers.Dockerfile, devops/containers/ubuntu2204_preinstalled.Dockerfile, devops/containers/ubuntu2404_base.Dockerfile, devops/containers/ubuntu2404_intel_drivers.Dockerfile, devops/containers/ubuntu2404_intel_drivers_igc_dev.Dockerfile, devops/scripts/docker_entrypoint.sh
Linter/checker used: [trivy v0.58.0](https://github.com/aquasecurity/trivy/releases/tag/v0.58.0)
Issues addressed:
- AVD-DS-0017 (HIGH): The instruction 'RUN <package-manager> update' should always be followed by '<package-manager> install' in the same RUN statement.
See https://avd.aquasec.com/misconfig/ds017
- AVD-DS-0002 (HIGH): Specify at least 1 USER command in Dockerfile with non-root user as argument
See https://avd.aquasec.com/misconfig/ds002
- AVD-DS-0002 (HIGH): Last USER command in Dockerfile should not be 'root'
Issues remaining:
- AVD-DS-0026 (LOW): Add HEALTHCHECK instruction in your Dockerfile
See https://avd.aquasec.com/misconfig/ds026
I didn't add `HEALTHCHECK` command to our containers, because I don't know if that makes sense and which command to launch. I.e. our …
=> [SYCL][Devops] Fix `DockerFile` linting issues discovered by trivy

sycl/test/check_device_code/extensions/annotated_arg/restrict.cpp, sycl/test/check_device_code/extensions/annotated_ptr/restrict.cpp
This commit fixes an overly strict expectation in both restrict.cpp tests introduced in https://github.com/intel/llvm/pull/16090.
=> [SYCL][Test] Fix expectation in restrict property tests

sycl/source/detail/ur.cpp
This code seems to be redundantly duplicated.
=> [UR] Don't set codeLocationCallback/ASAN layer twice

sycl/include/sycl/handler.hpp, sycl/include/sycl/reduction.hpp, sycl/source/handler.cpp
This function might be useful only when an accessor is connected with different
CG that was used during a construction of the accessor. Currently it’s helpful 
only in single case of reduction, and in this case the accessor can be connected
to a right CG in the constructor. Modify the use case and remove all calls to 
addAccessorReq().
=> [SYCL] Do not use handler::addAccessorReq()

xpti/CMakeLists.txt
When building xpti we arrange to copy xpti headers into the build
directory. On Windows we may instead be building the debug version,
xptid, so copy the headers in that case too.
=> [XPTI][CMake] Make xptid depend on xpti-headers as well

sycl/source/detail/kernel_bundle_impl.hpp, sycl/source/detail/program_manager/program_manager.cpp
All of these Coverity issues are related to using `std::move()` instead of variable copy.
=> [SYCL] Fix Coverity issues after #16228

sycl/test-e2e/Adapters/interop-l0-direct.cpp
Also, fix a leak caught by Device Address Sanitizer.
=> [SYCL][E2E] Update test case to turn off unwanted DeviceAddressSanitizer invalid argument detection.

llvm/lib/Transforms/Instrumentation/AddressSanitizer.cpp, llvm/test/Instrumentation/AddressSanitizer/SPIRV/ignore_target_ext_type.ll
If element type is bfloat16 its storage will be accessed via GEP. So need to skip this GEP during AccessChain handling.
=> [SYCL][DeviceASAN] Fix AcceeChain to a matrix for bfloat16

llvm/lib/SYCLLowerIR/LowerWGLocalMemory.cpp, llvm/test/SYCLLowerIR/work_group_static.ll, llvm/test/SYCLLowerIR/work_group_static_nv.ll, sycl/test-e2e/WorkGroupScratchMemory/dynamic_alloc_local_accessor.cpp, sycl/test-e2e/WorkGroupScratchMemory/dynamic_alloc_ptr_alias.cpp, sycl/test-e2e/WorkGroupScratchMemory/dynamic_allocation.cpp
Fixes https://github.com/intel/llvm/issues/16285, local testing was done using arc only initially and didn't exibit any of the seen behaviour elsewhere.
Tested locally with OpenCL CPU and OpenCL gpu (PVC).
also partially addresses https://github.com/intel/llvm/issues/16072
=> fix work_group_scrach_memory

libdevice/cmake/modules/SYCLLibdevice.cmake
Seems like the IMF fallback libraries are not collected in the merged libdevice for NVPTX and AMDGPU, because the name of the CMake property was wrong.
I don't know why our testing does not catch this. I have seen this result in unresolved symbols earlier, but I have been sitting on this patch for a while and did not try with current trunk.
=> [SYCL][libdevice][CMake][Trivial] Fix imf-fallback missing in NVPTX

sycl/source/detail/kernel_impl.hpp, sycl/source/kernel.cpp
This addresses Coverity issues.
=> [SYCL][NFC] Use move on `queue` parameters

.github/workflows/sycl-nightly.yml
I noticed that this job runs in my local fork, although needed steps were skipped.
=> [CI] Avoid running redundant cuda-aws-stop

sycl/test/check_device_code/extensions/properties/properties_kernel_launch_bounds.cpp, sycl/test/check_device_code/extensions/properties/properties_kernel_max_work_group_size.cpp, sycl/test/extensions/properties/properties_kernel_device_has_warning.cpp, sycl/test/extensions/properties/properties_kernel_negative_device.cpp, sycl/test/virtual-functions/diagnostics-positive.cpp, sycl/test/virtual-functions/properties-positive.cpp
The overloads for single_task and parallel_for in the sycl_ext_oneapi_kernel_properties extension are being deprecated as mentioned in https://github.com/intel/llvm/pull/14785. So I'm rewriting tests containg such overloads so that they can still run after the deprecation.
=> [SYCL] Rewrite Tests Containing Deprecated Overloads #1

sycl/cmake/modules/FetchUnifiedRuntime.cmake, sycl/cmake/modules/UnifiedRuntimeTag.cmake, sycl/test-e2e/format.py, sycl/test-e2e/lit.cfg.py
This patch adds a variable to enable image support for HIP, and updates
the one for CUDA to use the UR naming.
SYCL images support is similar for CUDA and HIP, so it makes sense to
treat them the same, and any future work on this will focus on bindless
images rather than SYCL images.
UR side PR: https://github.com/oneapi-src/unified-runtime/pull/2356
=> [SYCL][CUDA][HIP] Update images enable variable

clang/test/CodeGenSYCL/nvptx-short-ptr.cpp
This test forwards an option on to the NVPTX backend so must have the NVPTX target registered. This issue was noticed downstream.
=> [SYCL] Require NVPTX registered target for CodeGenSYCL test

sycl/test-e2e/bindless_images/vulkan_interop/sampled_images.cpp, sycl/test-e2e/bindless_images/vulkan_interop/sampled_images_semaphore.cpp
The test extends sampled_images.cpp test with semaphore import/wait. Only sycl waiting for vulkan semaphore is tested.
Vulkan waiting for sycl semaphore isn't added, because the test's output is buffer and interop between vulkan and sycl buffers isn't supported.
=> [SYCL][E2E][Bindless] Add Vulkan interop test sampled_images_semaphore.cpp

sycl/test-e2e/Basic/subdevice_pi.cpp
On intel cpu device, the number of subdevices was the same as cpu count. The number could be large on a server. In `shared` subtest, all subdevices belong to the same context and device program is built for every subdevice. Device code compilation may take long time. This PR reduces test time from 10s to 0.4s on 160-core ICX. When device sanitizer is enabled, test time is reduced from ~10min to 14s.
=> [SYCL][E2E][Subdevice] Reduce run time of test subdevice_pi.cpp

sycl/test-e2e/USM/fill_any_size.cpp
~~Update the UR tag to include https://github.com/oneapi-src/unified-runtime/pull/2273 fixing `queue::fill` for the CUDA and HIP backends. It was previously producing incorrect outputs for any pattern size other than 1, 2, or a multiple of 4 bytes. A new optimisation is also added which speeds up the fill greatly if the pattern equals to the first word repeated throughout (e.g. all zeros). See the UR PR for more details.~~
_The UR tag update was collected in https://github.com/intel/llvm/pull/16040 so now this PR only adds an e2e test as stated below._
Add a new e2e test to validate `queue::fill` outputs for any pattern size between 1 and 32 bytes. This test fails for CUDA and HIP before the UR change and passes with this PR. Other backends already worked correctly.
=> Add e2e test for queue::fill with a range of pattern sizes

clang/test/Driver/sycl-instrumentation-old-model.c
There is no guarantee that the device libraries are going to be built for a given built compiler.  Use the internal sysroot setting to allow for proper inclusion of dependent device libraries for SYCL testing.
=> [Driver][NFC] Update test to use internal sysroot for device libs

sycl/source/detail/helpers.cpp, sycl/source/detail/persistent_device_code_cache.cpp, sycl/source/detail/persistent_device_code_cache.hpp, sycl/source/detail/program_manager/program_manager.cpp, sycl/source/detail/program_manager/program_manager.hpp, sycl/source/detail/scheduler/commands.cpp
Fixes places with copy instead of usage by reference or move.
Protected potential but unlikely constant overflow with exception.
=> [SYCL] Fix warnings in source/detail code

sycl/cmake/modules/FetchUnifiedRuntime.cmake, sycl/cmake/modules/UnifiedRuntimeTag.cmake
Bumps UR commit to https://github.com/oneapi-src/unified-runtime/pull/2454 which contains a fix for using kernel bundles associated with a multi-device context in a SYCL-Graph
=> [SYCL][Graph] Fix L0 multi-device kernel bundles

.github/workflows/sycl-post-commit.yml, .github/workflows/sycl-windows-build.yml, .github/workflows/sycl-windows-run-tests.yml, devops/actions/setup_windows_oneapi_env/action.yml, sycl/source/CMakeLists.txt, sycl/source/detail/windows_ur.cpp, sycl/unittests/assert/assert.cpp
Getting this working was an unbelievable amount of work. I hit so many weird issues caused by dumb Windows things (case insensitivity, cmd vs bash, bugs in cmake/ninja/sccache themselves) but finally I got something that consistently passes. 
You can see the funniest dumb Windows issue in the comment in the CMake file change.
The basic idea is to extend the Windows build workflow to allow using `icx`, add an action to setup the oneAPI environment, call it from the build action and the test action (since we need some of the shared libs on path even for testing), and fix some oneAPI-only build issues.
We need to do some Powershell magic after calling the oneAPI setup bat script because the environment variables get lost since it's run in a subprocess.
We also switch to `ccache` instead of …
=> [CI] Use oneAPI for Windows postcommit builds

sycl/include/sycl/vector.hpp, sycl/test/basic_tests/vectors/swizzle.cpp
It brings it closer to SYCL spec and makes more consistent by having "named"
swizzle member functions (like `.hi()`/`.lo()`) and `.swizzle<...>()` behave in
a similar way, i.e. we still have a bug when doing a swizzle on an expression
tree.
Note that the whole "expression tree" machinery is not standard-conformant and
will be completely removed separately (under `-fpreview-breaking-changes` flag).
I still want to implement this partial bugfix so that I could switch to a
unified mixin-based implementation for swizzles on `vec`/`swizzle` classes,
instead of doing preprocessor tricks with `swizzles.def` file.
=> [SYCL] Implement "swizzle" member function on swizzles

sycl/test/check_device_code/hip/atomic/amdgpu_unsafe_atomics.cpp
The need for updated check was caused by a move from using AMD builtins in favour of IR instructions with correct metadata attached, see: https://github.com/intel/llvm/commit/b5e63cc533b5e752eb475ac657f09b9bb5eb2373
I travelled back in time to:
* intel/llvm: https://github.com/intel/llvm/commit/358b777f259c9f03099dc853fe874ec531e77416
* unified-runtime: https://github.com/oneapi-src/unified-runtime/commit/640687999e9689b001ee3e010e2dac4fc0abf0dd
and verified that generated assembly (cpp -> IR -> s) is the same for before and after the builtin change.
=> [SYCL] Update checks in unsafe atomics test for AMDGPU

.github/workflows/sycl-rel-nightly.yml
Surprisingly env is not accessible everywhere. Replacing it by hardcoded branch name.
=> [CI] Update sycl-rel-nightly.yml

.github/workflows/sycl-windows-build.yml, .github/workflows/sycl-windows-run-tests.yml
Speeds up repo checkout from [about](https://github.com/intel/llvm/actions/runs/12311103089/job/34360737703) 1m15s to [about](https://github.com/intel/llvm/actions/runs/12324659657/job/34416446316?pr=16367) 30sec
We need double escaping of the path because bash only works with Windows-style paths for `\\`, so we need to escape twice.
=> [CI] Used cached checkout on Windows

.github/workflows/sycl-containers.yaml, devops/containers/ubuntu2404_build_oneapi.Dockerfile
Add a Ubuntu 24.04 based oneAPI build image. Once I add a build non-oneAPI image I will make sure they share most of the code.
I just took the existing 22.04 build image code and added the official oneAPI apt repo and install oneAPI from there.
I need to have the Docker image present in HEAD before I can test it in in CI, so this is only the first step and nothing is using it yet.
The other Docker CI fail isn't related.
=> [CI] Add Ubuntu 24.04 oneAPI build image

sycl/include/sycl/detail/type_traits.hpp, sycl/include/sycl/detail/vector_arith.hpp, sycl/include/sycl/ext/oneapi/properties/properties.hpp, sycl/include/sycl/ext/oneapi/properties/property_utils.hpp, sycl/test/check_device_code/vector/vector_math_ops.cpp
This PR separates the "base" case functional implementation from templates/overloads/constraints. The latter doesn't match even the current SYCL spec and that is not taking into account proposed vec/swizzle changes.
Making this change would allow to share more code between non-preview/preview implementation paths when implementing proposed SYCL vec/swizzle changes.
=> [SYCL] Refactor `vector_arith*`

sycl/source/backend/opencl.cpp
I'm only able reproduce link error downstream for this API (and don't know what exactly is causing it), but the
change is the same in nature as parts of
https://github.com/intel/llvm/pull/16178,
https://github.com/intel/llvm/pull/16194 and
https://github.com/intel/llvm/pull/16267
=> [SYCL] Use `inline` guarded by `_WIN32` for `has_extension`

.github/workflows/sycl-containers-igc-dev.yaml, .github/workflows/sycl-linux-precommit.yml, devops/dependencies-igc-dev.json, devops/scripts/install_drivers.sh, sycl/test-e2e/ESIMD/PerformanceTests/invoke_simd_smoke.cpp, sycl/test-e2e/ESIMD/PerformanceTests/matrix_transpose.cpp, sycl/test-e2e/ESIMD/accessor_local.cpp, sycl/test-e2e/ESIMD/local_accessor_block_load_store.cpp, sycl/test-e2e/ESIMD/local_accessor_copy_to_from.cpp, sycl/test-e2e/ESIMD/lsc/lsc_local_accessor_block_load_store.cpp, sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_arg_dim.cpp, sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_runtime_dim.cpp
igc-dev is using `libigc.so.2` and released igc is using `libigc.so.1`, and there's no symlink to `libigc.so` in the dev-igc packages, so we need to do it ourselves.
Also, fix the workflow so it runs on changes to the driver install script and XFAIL failing tests.
And manually update the igc-dev version since the one we are using here is too old and the artifacts are expired so we can't build the image. The new version also contains an important fix for the joint matrix team.
Closes: https://github.com/intel/llvm/issues/16088
Closes: https://github.com/intel/llvm/issues/16251
=> [CI] Fix igc-dev Docker container and bump version

.github/workflows/sycl-containers.yaml, devops/actions/build_container/action.yml
Extended build containers action with an extra argument which specifies a password that will be assigned to the `sycl_ci` user created within containers.
For now this new secret is unused, so this changes is expected to have no impact on our CI.
This is outlined from #16361 to improve testing for that PR: for security reasons actions are only invoked from the default branch and never from a PR branch. Therefore, to actually test that this secret is properly used without errors we need to update the action first.
=> [SYCL][Devops] Propagate a new secret to containers build

.github/workflows/sycl-containers.yaml, sycl/doc/developer/DockerBKMs.md
We need this to bump the stable GPU driver, which requires Ubuntu 24.04 now. We already use a similar version of this image based on the same Dockerfile for the unstable and igc-dev images.
=> [CI] Add Ubuntu 24.04 stable drivers image

sycl/test-e2e/KernelAndProgram/kernel-bundle-merge-options.cpp, sycl/test-e2e/lit.cfg.py
The kernel-bundle-merge-options test was recently marked XFAIL (and tracker #16309 opened).  
The root problem is that when using the MSVC CL compiler, the tests set the `debug_option` flag to `/DEBUG` but it is `/Zi` that gets converted to `-g` when the device driver is called. Updating that python var and removing the `XFAIL` from the test.
=> [SYCL] test improvement, issue 16309

sycl/test-e2e/Graph/Inputs/whole_update_raw_arg.cpp
Update is only allowed if the kernel object that the graph is being updated with is the same as the kernel that the graph was created with. Calling `ext_oneapi_get_kernel` is creating a new SYCL kernel object for each invocation, since the implementation doesn't cache kernels for kernel bundles.
The user should not assume the caching of kernels, so must use the same kernel objects each time for update.
=> [SYCL][Graphs] Fix whole graph update raw arg test

sycl/source/detail/graph_impl.cpp
We were checking `if (NewEvent != nullptr)` but later we were dereferencing NewEvent without the check. At this point in the code NewEvent should be valid so no assertion is necessary.
Fixes https://github.com/intel/llvm/issues/16332
=> [SYCL] [Graph] Fixed potential dereference of a nullptr

llvm/lib/Transforms/Instrumentation/AddressSanitizer.cpp, llvm/lib/Transforms/Instrumentation/MemorySanitizer.cpp
Fix llvm-spirv: Invalid SPIR-V module: Casts from private/local/global address space are allowed only to generic
=> [DeviceSAN] Fix kernel name addressspace

clang/tools/clang-offload-bundler/CMakeLists.txt, clang/tools/clang-offload-packager/CMakeLists.txt, libclc/CMakeLists.txt, libclc/cmake/modules/AddLibclc.cmake, libclc/utils/libclc-remangler/CMakeLists.txt, libdevice/CMakeLists.txt, libdevice/cmake/modules/SYCLLibdevice.cmake, llvm/tools/append-file/CMakeLists.txt, llvm/tools/file-table-tform/CMakeLists.txt, llvm/tools/llvm-ar/CMakeLists.txt, llvm/tools/llvm-foreach/CMakeLists.txt, llvm/tools/sycl-post-link/CMakeLists.txt
When performing cross builds, we need native versions of various tools, we cannot assume the cross builds that are part of the current build are executable. LLVM provides the setup_host_tool function to handle this, either picking up versions of tools from LLVM_NATIVE_TOOL_DIR, or implicitly building native versions as needed. Use this in more places.
This applies the changes from LLVM #97392 and #97811 and adapts them to DPC++, and makes the same changes in other places that are only needed for DPC++.
Tested with a suitable cross compilation toolchain file:
```console
$ mkdir build
$ cat >build/aarch64-linux.cmake <<EOF
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_C_COMPILER "aarch64-linux-gnu-gcc" CACHE STRING "")
set(CMAKE_CXX_COMPILER …
```
=> [SYCL][libclc] Fix cross builds

sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_arg_dim.cpp, sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_runtime_dim.cpp
The Joint Matrix tests, joint_matrix_bf16_fill_k_cache_arg_dim.cpp and joint_matrix_bf16_fill_k_cache_runtime_dim.cpp fail on DG2 machine for matrix combination 32x32x16. A new Jira issue has been created to track this problem. This PR updates the XFAIL-TRACKER to this new Jira issue for these two tests.
=> [SYCL][E2E]  Update XFAIL-TRACKER for runtime dimension tests

clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/sycl-device-optimizations.cpp, clang/test/Driver/sycl-offload-intelfpga.cpp, sycl/test-e2e/InvokeSimd/Regression/ImplicitSubgroup/debug_symbols.cpp, sycl/test-e2e/InvokeSimd/Regression/debug_symbols.cpp
Set `O0` as the default SYCL device optimization if `-g` is passed and optimization level is not provided explicitly.
Use of `'-g'` without any optimization-level option will turn off compiler optimizations similar to use of `'-O0'`.
=> [SYCL] Set -O0 as the default SYCL device optimization if -g is passed

.github/workflows/sycl-linux-run-tests.yml, devops/containers/ubuntu2204_base.Dockerfile, devops/containers/ubuntu2204_build.Dockerfile, devops/containers/ubuntu2204_intel_drivers.Dockerfile, devops/containers/ubuntu2204_preinstalled.Dockerfile, devops/containers/ubuntu2404_base.Dockerfile, devops/containers/ubuntu2404_build_oneapi.Dockerfile, devops/containers/ubuntu2404_intel_drivers.Dockerfile, devops/containers/ubuntu2404_intel_drivers_igc_dev.Dockerfile, devops/scripts/create-sycl-user.sh, devops/scripts/docker_entrypoint.sh, sycl/doc/developer/DockerBKMs.md
This is a re-submit of #16290 with fixes from #16324 and some more extra changes.
Issues addressed:
- AVD-DS-0017 (HIGH): The instruction 'RUN <package-manager> update' should always be followed by '<package-manager> install' in the same RUN statement.
See https://avd.aquasec.com/misconfig/ds017
- AVD-DS-0002 (HIGH): Specify at least 1 USER command in Dockerfile with non-root user as argument
See https://avd.aquasec.com/misconfig/ds002
- AVD-DS-0002 (HIGH): Last USER command in Dockerfile should not be 'root'
Issues remaining:
- AVD-DS-0026 (LOW): Add HEALTHCHECK instruction in your Dockerfile
See https://avd.aquasec.com/misconfig/ds026
I didn't add `HEALTHCHECK` command to our containers, because I don't know if that makes sense and which command to launch. I.e. our containers they only …
=> [SYCL][Devops] Fix DockerFile linting issues discovered by `trivy`

.github/workflows/sycl-containers.yaml, .github/workflows/sycl-linux-run-tests.yml, devops/actions/build_container/action.yml, devops/containers/ubuntu2204_base.Dockerfile, devops/containers/ubuntu2204_build.Dockerfile, devops/containers/ubuntu2404_base.Dockerfile, devops/containers/ubuntu2404_build_oneapi.Dockerfile, devops/scripts/create-sycl-user.sh, sycl/doc/developer/DockerBKMs.md
Apparently, I overlooked part of the documentation saying that docker secrets are only available for containers running as a service which isn't the case for our build/test CI pipeline.
Therefore, I'm partially reverting #16411 so that our containers once again use `sycl` user which has password-less `sudo` access.
This PR also reverts #16436 to re-enable GPU reset.
=> [SYCL][Devops] Revert requiring password for `sudo`

sycl/test-e2e/OptionalKernelFeatures/fp64-conv-emu-1.cpp, sycl/test-e2e/OptionalKernelFeatures/fp64-conv-emu-2.cpp
On Windows clang tries to mimic `cl.exe` interface and it has a different spelling for `-O0` (`/Od`).
Updated a couple of tests to make them work on Windows as well by using a substitution instead of a flag directly.
=> [SYCL][E2E] Use correct subtitution for `-O0`

sycl/test-e2e/Basic/build_log.cpp, sycl/test-e2e/Basic/query.cpp, sycl/test-e2e/ESIMD/dp4a.cpp, sycl/test-e2e/InvokeSimd/Regression/ImplicitSubgroup/dp4a.cpp, sycl/test-e2e/InvokeSimd/Regression/dp4a.cpp, sycl/test-e2e/README.md, sycl/test-e2e/lit.cfg.py
So that the user won't have to manually specify `--param gpu-intel-dg1=True` to run tests on DG1.
https://github.com/intel/llvm/pull/16220#discussion_r1865940378
=> [E2E] Replace `gpu-intel-dg1` with `arch-intel_gpu_dg1` LIT feature

sycl/test-e2e/Matrix/get_coordinate_ops.cpp
It's passing now after the driver update.
https://github.com/intel/llvm/actions/runs/12433578741/job/34716640805
=> [SYCL][E2E] Remove XFAIL in get_coordinate_ops.cpp

sycl/test-e2e/Matrix/get_coordinate_ops_impl.hpp
This PR resolves the reqd_sub_group_size issue and refactors the code in get_coordinate_ops_imp.hpp
=> [SYCL][E2E] Resolve reqd_sub_group_size issue for get_coordinate tests

.github/workflows/sycl-containers-igc-dev.yaml, .github/workflows/sycl-containers.yaml, devops/containers/ubuntu2204_intel_drivers.Dockerfile, devops/containers/ubuntu2404_intel_drivers.Dockerfile
IMO, `use_latest` is confusing - does it mean to use latest docker container image or latest driver? `use_unstable_driver` would be more appropriate.
=> [CI][NFC] Rename `use_latest` container build argument to `use_unstable_driver`

sycl/test-e2e/bindless_images/dx12_interop/read_write_unsampled.cpp, sycl/test-e2e/bindless_images/helpers/common.hpp, sycl/test-e2e/bindless_images/vulkan_interop/sampled_images.cpp, sycl/test-e2e/bindless_images/vulkan_interop/unsampled_images.cpp, sycl/test-e2e/bindless_images/vulkan_interop/vulkan_common.hpp
Also disable failing unsampled unorm tests on intel gpu.
=> [SYCL][E2E][Bindless] Add 3-channel unorm_int8 and half vulkan-interop subtests for L0

llvm/lib/SYCLLowerIR/SanitizerKernelMetadata.cpp, llvm/test/tools/sycl-post-link/device-sanitizer/asan.ll, llvm/test/tools/sycl-post-link/device-sanitizer/msan.ll
OpenCL CPU requires the type of device global wraps with structure type
=> [DeviceSanitizer] Fix device global type of KernelMetadata

sycl/test-e2e/Matrix/SG32/get_coordinate_ops.cpp
This test is able to compile so I am adding `XFAIL: run-mode` so that it doesn't `XPASS` on build-only mode. Should fix the pre-commit CI.
=> [SYCL][E2E] Fix unexpectedly passing test on build-only mode

sycl/test-e2e/OnlineCompiler/online_compiler_OpenCL.cpp
It's failing [here](https://github.com/intel/llvm/actions/runs/12433578741/job/34716641336). The test manually calls the GPU driver even when running on CPU or FPGA. 
XFAIL it since it's failing. Root issue will be addressed in the Github issue.
=> [SYCL][E2E] Disable online_compiler_OpenCL.cpp on FPGA

sycl/doc/extensions/experimental/sycl_ext_oneapi_group_load_store.asciidoc, sycl/include/sycl/ext/oneapi/experimental/group_load_store.hpp, sycl/test/check_device_code/group_load.cpp, sycl/test/check_device_code/group_store.cpp, sycl/test/extensions/group_load_store_negative.cpp
Before this patch we were failing with more obscure errors like
```
no member named 'has_property' in ...property_value<...data_placement_key...>
```
=> [SYCL] `Properties` must be a properties list in `group_load/store`

.github/workflows/sycl-containers.yaml, devops/containers/ubuntu2404_build.Dockerfile, sycl/doc/developer/DockerBKMs.md
This adds the remaining Dockerfiles we'll need for Ubuntu 24.04. 
There will be two more containers added to the workflow after this PR, I can't add them now because they require changes in this PR and CI doesn't use the files from precommit.
=> [CI] Add remaining Ubuntu 24.04 Dockerfile

sycl/include/sycl/vector.hpp
Apparently, some versions of MSVC (e.g. 14.29.30133) fail to compile it
```
error C3779: 'sycl::_V1::detail::SwizzleOp<VecT,OperationLeftT,OperationRightT,OperationCurrentT,Indexes...>::get_vec_idx': a function that returns 'auto' cannot be used before it is defined
```
when used with `-fsycl-host-compiler`. This has been caught by the existing `bit_cast_win.cpp` test in a downstream environment.
=> [SYCL] Use explicit return type in `get_vec_idx` helper

llvm/lib/SYCLLowerIR/SYCLJointMatrixTransform.cpp, llvm/test/SYCLLowerIR/JointMatrixTransform/access_chain.ll
The new corner case is: AccessChain is used on arrays of Joint Matrices
Fix for CMPLRLLVM-64465
=> [SYCL][Matrix] Extend W/A for more corner cases of AccessChain usage

compiler-rt/lib/builtins/CMakeLists.txt
Cherry pick of https://github.com/llvm/llvm-project/commit/a4c8ef0f401d86040594cc6f01bcdad9392e8ee2, we need this for building with GCC 13.
=> [compiler-rt] Fix detecting _Float16 support for secondary targets 

sycl/include/sycl/ext/intel/fpga_lsu.hpp, sycl/test/abi/layout_vec.cpp
For the ABI check, the problem is libstdc++ changed the name of the template, so change the check to be more general.
For the header, my guess is the new libstdc++ version doesn't include this header internally in some header we include anymore.
=> [SYCL] Fix errors when building with GCC 13

sycl/test-e2e/Assert/assert_in_multiple_tus.cpp
Test was verified on Arc using the following driver versions: 
24.22.29735.20 - fail
24.31.30508.7 - fail
24.39.31294.12 - pass
24.45.31740.9 - pass
So, re-enable the test and add the minimal required driver version.
Closes https://github.com/intel/llvm/issues/14557
=> [SYCL][E2E] Re-enable assert_in_multiple_tus.cpp on Arc

.github/workflows/sycl-nightly.yml
Precommit uses the nightly compiler to build, and user branches not merged into HEAD won't build on 24.04, so we get a glibc error because the nightly was built on 24.04 but the current job is running on 22.04.
Build the nightly on 22.04 to not break precommit and anyone using the nightly images directly.
=> [CI] Build the nightly on Ubuntu 22.04

.github/workflows/sycl-nightly.yml
We use AWS machines for CUDA Nightly testing and the kernel driver AWS has installed is [too old](https://github.com/intel/llvm/actions/runs/12549000224/job/34989741902) for the CUDA version in the 24.04 image, so use 22.04.
=> [CI] Use Ubuntu 22.04 for nightly CUDA AWS testing

sycl/include/sycl/vector.hpp
`public` `size()` can be used instead.
=> [NFCI][SYCL] Remove `vec`/`swizzle`'s `getNumElements`

libdevice/cmath_wrapper.cpp, libdevice/cmath_wrapper_fp64.cpp
Failed to compile OneDNN using DPCPP on AMD with sycl because the code [here](https://github.com/oneapi-src/oneDNN/blob/c852fdc60073a1ae298618c4faf26487b4144755/src/gpu/generic/sycl/eltwise_kernels.hpp#L137) that will run on the device actually calls `nearbyintf` [here](https://github.com/oneapi-src/oneDNN/blob/c852fdc60073a1ae298618c4faf26487b4144755/src/common/math_utils.hpp#L120-L131) , but `nearbyintf` lacks a symbolic definition.
Same solution as https://github.com/intel/llvm/pull/11177 but go straight to the `__ocml` symbols
=> [SYCL][HIP] add missing nearbyint and rint

.github/workflows/sycl-linux-matrix-e2e-on-nightly.yml, .github/workflows/sycl-linux-precommit-aws.yml, .github/workflows/sycl-linux-precommit.yml, .github/workflows/sycl-linux-run-tests.yml, .github/workflows/sycl-nightly.yml, .github/workflows/sycl-post-commit.yml, .github/workflows/sycl-rel-nightly.yml, sycl/test-e2e/lit.cfg.py
Instead of `ext_oneapi_[level_zero|cuda|hip]`, we should use `level_zero/cuda/hip` backend name in LIT, which is in alignment with `ONEAPI_DEVICE_SELECTOR` terminology and `sycl-ls` output.
=> [CI] Drop support `ext_oneapi_[level_zero|cuda|hip]` in `sycl_devices` LIT parameter

sycl/include/sycl/detail/os_util.hpp, sycl/source/detail/os_util.cpp
For older gcc versions (< 8), use `std::experimental::filesystem`.
=> [NFC][SYCL] Refactor OSUtils to use std::filesystem

clang/test/CodeGenSYCL/kernel_binding_decls.cpp, clang/test/SemaSYCL/binding_decl_lambda_nullptr.cpp
A recent community change:
70965ef259 [Clang] Prevent assignment to captured structured bindings inside immutable lambda
issues diagnostics for a construct used inside these tests. 
The assignments within the lambda are not central to the test, so this change just removes those.
=> [SYCL] Fix tests that check capture of bindings

.github/workflows/sycl-nightly.yml
We updated the action version recently but that version is [broken](https://github.com/intel/llvm/actions/runs/12592108759/job/35118108288).
=> [CI] Fix nightly releases

clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/sycl-offload-aot.cpp, clang/test/Driver/sycl-offload-nvptx.cpp, clang/test/Driver/sycl-offload-with-split-old-model.c
After the switch to using clang to build the wrapped object the embedded target in the IR is caused a warning to be emitted.  Fix this by adjusting the clang-offload-wrapper call to use the same host triple that is used when performing a regular compilation.  Matching these up allows for no diagnostic to be emitted.
Warning emitted: warning: overriding the module target triple with
x86_64-pc-windows-msvc19.29.30154 [-Woverride-module]
=> [Driver][SYCL] warning emitted when compiling wrapped object

sycl/cmake/modules/FetchUnifiedRuntime.cmake, sycl/cmake/modules/UnifiedRuntimeTag.cmake
Test PR for UR [PR](https://github.com/oneapi-src/unified-runtime/pull/2503)
=> Bump for uninitialized-cuda-events-fix

clang/include/clang/Driver/ToolChain.h, clang/lib/Driver/ToolChain.cpp, clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/mlong-double-128.c, clang/test/Driver/sycl-mlong-double.cpp
Make sure that `-mlong-double-64` option is supported on HIP/Cuda.
=> [Driver][SYCL] Support 64bit long double for SYCL GPU compilation

sycl/include/sycl/detail/vector_convert.hpp
* `vector_t` is expected to be removed in https://github.com/KhronosGroup/SYCL-Docs/pull/676
* We already create `OpenCLVec[TR]`, can use them directly
=> [SYCL] Don't use `vec::vector_t` in `vec::convert` implementation

README.md, sycl/doc/GetStartedGuide.md, sycl/doc/developer/DockerBKMs.md
We will soon no longer provide pre-built Docker containers, so update the relevant doc to reference the Dockerfile instead.
=> [SYCL][Doc] Reword Docker doc to reference Dockerfiles

.github/workflows/sycl-nightly.yml
They [fixed](https://github.com/softprops/action-gh-release/commit/c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda) the bug.
=> [CI] Update nightly build upload action

sycl/test-e2e/ESIMD/regression/dgetrf_8x8.cpp
=> [SYCL][ESIMD][E2E] Fix printf's format specifier in dgetrf_8x8.cpp

.github/workflows/sycl-linux-run-tests.yml
We need this to access private Docker containers. The Linux build YAML already has the right permissions.
=> [CI] Set package read permission in Linux run tests YAML 

sycl/include/sycl/sub_group.hpp
`sycl::vec(vector_t)` ctor is implemented as `bit_cast` itself, so having two steps has no advantage over doing all that in once.
Part of the efforts to eliminate `vector_t` usage in the code base before its removal from the SYCL specification.
=> [NFCI] Avoid double `bit_cast` in `sub_group::load`

sycl/include/sycl/detail/builtins/builtins.hpp, sycl/include/sycl/detail/memcpy.hpp, sycl/include/sycl/ext/oneapi/experimental/group_load_store.hpp, sycl/test-e2e/Regression/group_load_fortified.cpp, sycl/test/check_device_code/group_load.cpp
The implementation of group_load and marray builtins currently use std::memcpy, which currently may fail to compile on device when the user sets -D_FORTIFY_SOURCE=2. This commit fixes this by using sycl::detail::memcpy_no_adl instead.
This solution should be replaced by a devicelib implementation of `__memcpy_chk` when device-side abort/assertions work as intended.
=> [SYCL] Fix use of memcpy in group_load and marray builtins

sycl/include/sycl/detail/type_traits/vec_marray_traits.hpp, sycl/include/sycl/detail/vector_arith.hpp, sycl/test/check_device_code/vector/vector_math_ops.cpp
Reverts intel/llvm#16529 due to failure to build on Windows and MacOS in post-commit.
=> Revert "[SYCL] Refactor `sycl::vec`'s operators implementation"

sycl/include/sycl/ext/intel/fpga_lsu.hpp, sycl/test/abi/layout_vec.cpp
For the ABI check, the problem is libstdc++ changed the name of the template, so change the check to be more general.
For the header, my guess is the new libstdc++ version doesn't include this header internally in some header we include anymore.
=> [SYCL] Fix errors when building with GCC 13 (#16480)

sycl/include/sycl/detail/type_traits/vec_marray_traits.hpp, sycl/include/sycl/detail/vector_arith.hpp, sycl/test/check_device_code/vector/vector_math_ops.cpp
* Don't use `sycl::vec::vector_t`, as it is planned to be removed from the SYCL 2020 (KhronosGroup/SYCL-Docs#676). Note
that this implementation is NOT required to use it, so this PR can be merged before the specification change.
* Use `ext_vector_type`-based optimized implementation whenever it's available and not on device only.
This is a recommit of https://github.com/intel/llvm/pull/16529 with an additional `#if __clang_major__ >= 20` guard around `static_assert` on the expression that wasn't constant in clang-19.
=> [SYCL] Refactor sycl::vec's operators implementation

.github/workflows/sycl-linux-precommit.yml, sycl/test-e2e/KernelAndProgram/persistent-cache-multi-device.cpp, sycl/test-e2e/ProgramManager/multi_device_bundle/build_twice.cpp, sycl/test-e2e/ProgramManager/multi_device_bundle/device_libs_and_caching.cpp
`by-path` dir is required for `NEOReadDebugKeys=1 CreateMultipleRootDevices=[num_devices]`to work correctly.
Same as https://github.com/intel/llvm/pull/15563
=> [CI][SYCL][E2E] Mount `by-path` dir in docker container on PVC

sycl/source/detail/kernel_compiler/kernel_compiler_sycl.cpp, sycl/test-e2e/KernelCompiler/kernel_compiler_sycl.cpp
We can use experimental filesystem when compiling SYCL with GCC 7, which means we can remove the #ifdef hacks from the kernel_compiler.
=> [SYCL] kernel_compiler remove GCC < 8 workarounds.

.github/workflows/sycl-linux-build.yml, .github/workflows/sycl-linux-precommit.yml, .github/workflows/sycl-rel-nightly.yml, .github/workflows/sycl-windows-build.yml, .github/workflows/sycl-windows-precommit.yml
The workflow was introduced with errors. Fix them and also turn off the pre-commit for changes in this workflow.
=> [CI] Fix sycl-rel-nightly.yml

sycl/doc/syclcompat/README.md, sycl/include/syclcompat/math.hpp, sycl/test-e2e/syclcompat/math/math_emu_simd_from_syclomatic.cpp, sycl/test-e2e/syclcompat/math/math_vectorized.cpp
Signed-off-by: Jiang, Zhiwei <zhiwei.jiang@intel.com>
=> [SYCLCompat] Fix vectorized_binary impl to make SYCLomatic migrated code run pass

sycl/source/detail/jit_compiler.cpp, sycl/source/detail/jit_compiler.hpp, sycl/source/detail/kernel_compiler/kernel_compiler_opencl.cpp
Fixes memory leaks in jit_compiler and kernel_compiler_opencl classes.
Libraries loaded to provide compilation utils have to be released.
=> [SYCL] Unload libraries in jit_compiler and kernel_compiler_opencl destructors

libdevice/include/sanitizer_defs.hpp
Ensure that `__USE_SPIR_BUILTIN__` is defined to the value `0` when `defined(__SPIR__) || defined(__SPIRV__)` is false to fix build errors like this:
libdevice/include/sanitizer_defs.hpp:51:25: error: expected value in expression
51 | #if __USE_SPIR_BUILTIN__
|                         ^
=> [DeviceSanitizer] Ensure __USE_SPIR_BUILTIN__ has a value

clang/test/Driver/sycl-offload-jit.cpp
Update test to use --offload-new-driver.  Current default is to use the old offloading model, the new offloading model is the default in the community.  This test is specific to the new offloading model behaviors.
=> Update test for expected device defaults and offloading model

sycl/source/detail/program_manager/program_manager.cpp, sycl/source/detail/program_manager/program_manager.hpp
The JITCompilationIsRequired in a selection of build functions default to false and are never set by any callers. Given this, the argument can be removed. As a side-effect of this, the CheckJITCompilationForImage function will return immediately if the JITCompilationIsRequired was false, and since it always was the function is obsolete and can be removed.
=> [SYCL][NFC] Remove dead arg and check

sycl/cmake/modules/UnifiedRuntimeTag.cmake
Pre-commit MR for https://github.com/oneapi-src/unified-runtime/pull/2048
=> [UR] Use reference counting on factories

sycl/test-e2e/AOT/fpga-aoc-archive-split-per-kernel.cpp, sycl/test-e2e/AOT/fpga-aoc-archive2.cpp
These tests are testing various combinations of compilation modes using FPGA -fsycl-link.  The mixing and matching were a bit over-kill.  Update these tests to cover the various modes, but reduce the combinations.
=> [SYCL][E2E] Cleanup compilation redundancies for FPGA archive tests

sycl/test-e2e/AOT/fpga-aoc-archive-early.cpp, sycl/test-e2e/AOT/fpga-aoc-archive-early2.cpp, sycl/test-e2e/AOT/fpga-aoc-archive-image.cpp, sycl/test-e2e/AOT/fpga-aoc-archive.cpp
This particular TU has no device code so can be pre-compiled and passed as an object file to final link invocations without affecting the tests' purpose.
I'm not touching `fpga-aoc-archive-split-per-kernel.cpp`/ `fpga-aoc-archive2.cpp` as these two are the slowest and would need other changes.
=> [SYCL][E2E] Pre-compile `fpga_main.cpp` into `.o` file

sycl/test-e2e/Basic/vector/vec_binary_scalar_order.hpp, sycl/test-e2e/Basic/vector/vec_binary_scalar_order_arith.cpp, sycl/test-e2e/Basic/vector/vec_binary_scalar_order_bitwise.cpp, sycl/test-e2e/Basic/vector/vec_binary_scalar_order_logical.cpp, sycl/test-e2e/Basic/vector/vec_binary_scalar_order_relational.cpp
First, full coverage belongs to CTS, not to unit tests. Second, implementation is heavily templated and there isn't much differences potential for many intger types or vector sizes.
This PR eliminates test cases that are unlikely to excercise the code not covered by the remaining ones. The purpose of this is to reduce the time these tests takes as they're very close to be a bottleneck on machines with lots of cores where total wall clock time is defined by the longest tests in the suite.
=> [SYCL][E2E] Don't cover full combinations in `vec_binary_scalar_order*`

.github/workflows/sycl-linux-run-tests.yml, .github/workflows/sycl-nightly.yml
Disabled some redundant steps for run-only mode.
Test-run: https://github.com/intel/llvm/actions/runs/12708106400
=> [CI] Update nightly sycl-cts

sycl/test-e2e/Reduction/reduction_internal.hpp, sycl/test-e2e/Reduction/reduction_internal_nd_range_1dim.cpp, sycl/test-e2e/Reduction/reduction_internal_range_1dim.cpp, sycl/test-e2e/Reduction/reduction_internal_range_2dim.cpp, sycl/test-e2e/Reduction/reduction_internal_range_3dim.cpp
The test is long enough to be a bottleneck for the total wall clock time when running E2E tests on a machine with enough cores (like our PVC/SPR runners in CI).
=> [NFC][SYCL][E2E] Split `Reduction/reduction_internal.cpp`

sycl/test-e2e/USM/fill_any_size.cpp
Test added in #16544 was originally flagged as UNSUPPORTED for OpenCL CPU device only, but has now been observed to fail also for other OpenCL devices. Flag the test as UNSUPPORTED for all OpenCL devices.
=> [SYCL][E2E] Flag USM/fill_any_size UNSUPPORTED for all opencl devices

sycl/test-e2e/ESIMD/lit.local.cfg
This only worked when `gpu-intel-dg2` was passed explicitly at the command line. Now we automatically add it based on the device architecture, but it's per-device, so check for it in any device like we do for PVC.
=> [SYCL][ESIMD][E2E] Fix DG2 check in lit.local.cfg

sycl/include/sycl/ext/oneapi/experimental/group_load_store.hpp, sycl/test/check_device_code/group_load.cpp, sycl/test/check_device_code/group_store.cpp
Those built-ins are mentioned here https://registry.khronos.org/OpenCL/extensions/intel/cl_intel_subgroups_short.html
and visible here as well:
https://github.com/intel/intel-graphics-compiler/blob/master/IGC/BiFModule/Implementation/group.cl#L1727
https://github.com/intel/intel-graphics-compiler/blob/master/IGC/BiFModule/Implementation/group.cl#L1927
=> [SYCL] Map group load/store to built-ins for 16 shorts

sycl/test-e2e/lit.cfg.py
Fixes CMPLRLLVM-64568
`-shared` is invalid with `icx` on Windows. This PR makes use of `/LD` instead when compiler accepts MSVC-style args.
=> [SYCL][E2E] Fix `zstd` support detection in LIT with icx on Windows

sycl/test-e2e/Basic/accessor/host_task_accessor_deduction.cpp, sycl/test-e2e/DeprecatedFeatures/set_arg_interop.cpp, sycl/test-e2e/ESIMD/named_barriers/loop.cpp, sycl/test-e2e/ESIMD/named_barriers/loop_extended.cpp, sycl/test-e2e/GroupAlgorithm/reduce_sycl2020.cpp
These tests were disabled/XFAILed in https://github.com/intel/llvm/pull/14720.
[sycl/test-e2e/DeprecatedFeatures/set_arg_interop.cpp](https://github.com/intel/llvm/pull/16577/files#diff-9a41bc14675723afa4f98932225243790a5fc5b0fbfc54e732ca1ef84cef7df3) is XPASSing flakily (see https://github.com/intel/llvm/issues/16576) so I've marked it unsupported.
=> [SYCL][E2E] Fix tests disabled during PVC enablement in CI

sycl/test-e2e/USM/lit.local.cfg
Different tests randomly fail, so disabling the ones that happen to fail isn't productive. Just disable them all. I'll ping HIP people on the GH [issue](https://github.com/intel/llvm/issues/15648) to look into this ASAP.
Examples:
[one](https://github.com/intel/llvm/actions/runs/11571336819/job/32209524859), [two](https://github.com/intel/llvm/actions/runs/11555099026/job/32160351729)
=> [SYCL][E2E] Disable USM tests on HIP because they randomly fail (#15913)

sycl/test-e2e/USM/lit.local.cfg
I think `import platform` is not required.
Found in https://github.com/intel/llvm/pull/16591#discussion_r1910675290
=> [E2E][NFCI] Remove `import platform` from USM LIT cfg file

sycl/test/check_device_code/native_cpu/vectorization.cpp
Since merging in upstream LLVM changes, we now see a splat.
=> [SYCL][NativeCPU] Update lit test.

sycl/test-e2e/syclcompat/math/math_emu_simd_from_syclomatic.cpp
Signed-off-by: Jiang, Zhiwei <zhiwei.jiang@intel.com>
=> [SYCLCompat][E2E] Add sycl::free for allocated memory

.github/workflows/sycl-rel-nightly.yml, .github/workflows/sycl-windows-run-tests.yml
Added merge_ref to inputs. Use ref instead of undeclared build_ref.
=> [CI] Update sycl-windows-run-tests.yml

devops/dependencies.json
We are currently using `24.52.32224.5` and the corresponding IGC version is v.2.5.6 as per [here](https://github.com/intel/compute-runtime/releases/tag/24.52.32224.5). The script doesn't update it, I'll fix it tomorrow but for now just manually bump it.
=> [CI] Bump IGC version

devops/bandit.config
B320 & B410 were deleted - https://github.com/PyCQA/bandit/releases/tag/1.8.1
This patch fixes the action - https://github.com/intel/llvm/actions/workflows/bandit.yml
=> [CI] Update bandit.config

sycl/test-e2e/Assert/assert_in_kernels_ndebug.cpp, sycl/test-e2e/Assert/assert_in_multiple_tus_one_ndebug.cpp, sycl/test-e2e/Assert/assert_in_multiple_tus_one_ndebug_win.cpp, sycl/test-e2e/Assert/assert_in_one_kernel_ndebug.cpp, sycl/test-e2e/Assert/assert_in_simultaneously_multiple_tus_one_ndebug.cpp, sycl/test-e2e/BFloat16/bfloat16_builtins.cpp, sycl/test-e2e/BFloat16/bfloat16_builtins_cuda_generic.cpp, sycl/test-e2e/Basic/multisource.cpp, sycl/test-e2e/Basic/multisource_spv_obj.cpp, sycl/test-e2e/DeviceImageDependencies/dynamic.cpp, sycl/test-e2e/DeviceImageDependencies/objects.cpp, sycl/test-e2e/NewOffloadDriver/multisource.cpp, sycl/test-e2e/NewOffloadDriver/sycl-external-with-optional-features.cpp, sycl/test-e2e/OneapiDeviceSelector/illegal_input.cpp, sycl/test-e2e/OptionalKernelFeatures/sycl-external-with-optional-features.cpp, sycl/test-e2e/README.md, sycl/test-e2e/Regression/DAE-separate-compile.cpp, sycl/test-e2e/Regression/commandlist/gpu.cpp, sycl/test-e2e/Regression/multiple-targets.cpp, sycl/test-e2e/SeparateCompile/same-kernel.cpp, sycl/test-e2e/SeparateCompile/sycl-external-within-staticlib.cpp, sycl/test-e2e/SeparateCompile/sycl-external.cpp, sycl/test-e2e/format.py, sycl/test-e2e/lit.cfg.py, sycl/test-e2e/syclcompat/kernel/kernel_lin.cpp, sycl/test-e2e/syclcompat/kernel/kernel_win.cpp
...and use it to pass `amd_arch` options to compilation only when
compiling for AMD triples instead of unconditional usage in `%clangxx`
substitution.
That would avoid passing the option unnecessary when running `llvm-lit`
with multiple target devices and a given test isn't supported for HIP.
We might not have such configuration presently, but the same logic will
be applied for "split" build/run of E2E tests and we'd definitely want
to build tests for all the possible targets at once.
Another use case for it is the "spirv backend" testing where we'd want
to pass extra option for any compilations targeting spirv triple.
=> [SYCL][E2E] Introduce `%{sycl_target_opts}` substitution

.github/workflows/sycl-linux-precommit.yml
`ubuntu2404_intel_drivers:latest` container was used here previously because there was no Ubuntu 24 version of the `alldeps` container, and we were only building for the `spir64` triple. This container has since been added so we can use it instead. This will allow us to compile for the other triples in the `build-only` step in the future.
=> [CI] Use `intel_drivers:alldeps` container on `build_e2e_tests` precommit step

sycl/test-e2e/Graph/Update/FreeFunctionKernels/update_with_indices_ordering.cpp, sycl/test-e2e/Graph/Update/update_with_indices_ordering.cpp
On certain setups these two tests take a long time to execute, impairing the ability to run the whole suite of graph E2E tests in lit.
Reduce the number of graph execution iterations used in tests to alleviate this situation. There is an issue with free-function kernels taking longer that the non-free function equivalent, documented in CMPLRLLVM-64841, so only use a single execution iteration for now.
=> [SYCL][Graph][E2E] Reduce work in intensive update tests running

sycl/test-e2e/Basic/max_linear_work_group_size_props.cpp, sycl/test-e2e/Basic/max_work_group_size_props.cpp, sycl/test-e2e/Basic/work_group_size_prop.cpp, sycl/test-e2e/Graph/Inputs/work_group_size_prop.cpp, sycl/test-e2e/GroupAlgorithm/root_group.cpp, sycl/test-e2e/Properties/cache_config.cpp, sycl/test-e2e/VirtualFunctions/2/1/1/missing-overrides.cpp, sycl/test-e2e/VirtualFunctions/2/1/1/more-complex-hierarchy.cpp, sycl/test-e2e/VirtualFunctions/2/1/1/simple-hierarchy.cpp, sycl/test-e2e/VirtualFunctions/2/2/single-construct-single-use.cpp, sycl/test-e2e/VirtualFunctions/misc/math.cpp, sycl/test-e2e/forward_progress/forward_progress_kernel_param_L0_gpu.cpp, sycl/test-e2e/forward_progress/forward_progress_kernel_param_ocl_cpu.cpp
The overloads for single_task and parallel_for in the sycl_ext_oneapi_kernel_properties extension are being deprecated as mentioned in https://github.com/intel/llvm/pull/14785. So I'm rewriting tests containg such overloads so that they can still run after the deprecation.
=> [SYCL][E2E] Rewrite Tests Containing Deprecated Overloads #2

sycl/test-e2e/README.md, sycl/test-e2e/format.py, sycl/test-e2e/lit.cfg.py
We introduce here SPIR-V Backend support in LIT config by adding a new LIT feature 'spirv-backend', and in a way that substitutions in end-to-end tests are aware about the new LIT feature.
=> [CI] Introduce SPIR-V Backend support in LIT config

sycl/test-e2e/PerformanceTests/CompileTime/core_hpp.cpp, sycl/test-e2e/PerformanceTests/CompileTime/single_task_overhead.cpp, sycl/test-e2e/PerformanceTests/CompileTime/sycl_hpp.cpp, sycl/test/e2e_test_requirements/no_sycl_hpp_in_e2e_tests.cpp
We run `test-e2e/PerformanceTests` in post-commit and that can be used for
* tracking the compilation time on these tests over time
* running them in pre-commit to measure expected improvements
I also think that since PerformanceTests are "opt-in" in precommit, there is little sense in enforcing no `<sycl/sycl.hpp>` header in them.
=> [SYCL][E2E] Add some compile-time "tracking" tests

sycl/test-e2e/DeviceArchitecture/device_architecture_comparison_on_device_aot.cpp
fixes https://github.com/intel/llvm/issues/16662
Add missing `.wait()` after `queue.submit()`.
=> [SYCL][E2E] Fix `DeviceArchitecture/device_architecture_comparison_on_device_aot.cpp`

llvm/lib/SYCLLowerIR/ESIMD/ESIMDOptimizeVecArgCallConv.cpp, llvm/lib/SYCLLowerIR/ESIMD/LowerESIMD.cpp, llvm/lib/SYCLLowerIR/GlobalOffset.cpp, llvm/lib/SYCLLowerIR/LocalAccessorToSharedMemory.cpp, llvm/lib/SYCLLowerIR/LowerInvokeSimd.cpp, llvm/lib/SYCLLowerIR/LowerWGScope.cpp, llvm/lib/SYCLLowerIR/SpecConstants.cpp, llvm/lib/SYCLNativeCPUUtils/PrepareSYCLNativeCPU.cpp
=> [SYCL][NFC] Stop using deprecated `InsertionPoint` constructor

sycl/include/sycl/detail/is_device_copyable.hpp, sycl/include/sycl/reduction.hpp, sycl/test/basic_tests/is_device_copyable.cpp
This was discussed in
https://github.com/intel/llvm/pull/15342#discussion_r1751868640 and the consensus seemed to be that we should drop it right away in a separate PR, do it here.
Technically, it is a breaking change that could also be considered a bugfix. An example of a class failing the updated check is
```
struct Kernel {
Kernel(int);
Kernel(const Kernel&) = default;
Kernel& operator=(const Kernel&) { return *this; } // non-trivial
};
```
An additional minor reason (other than not being SYCL-conformant) to drop it right away is to save a tiny bit of compile time that is currently used to support something violating the spec.
This required some fixes in the reductions implementation to make sure the kernel we submit internally are actually device copyable.
=> [SYCL] Remove `IsDeprecatedDeviceCopyable`

.github/workflows/sycl-nightly.yml, devops/containers/nightly.Dockerfile, sycl/doc/developer/DockerBKMs.md
Have a single docker image created with all the dependencies pre-installed so that it could be used for all internal CI needs for every target. Other workflows should be changed after this is merged and new image is uploaded to the registry.
=> [CI] Simplify nightly docker images

sycl/include/sycl/detail/is_device_copyable.hpp, sycl/test/basic_tests/is_device_copyable_neg.cpp
First, that's what idiomatic C++17 is (folds over recursion), second compile of folds scales much better than recursion when the number of fields/bases grow.
=> [NFC] Use C++17 fold expressions in `detail::CheckDeviceCopyable`

sycl/test-e2e/Graph/Explicit/work_group_static_memory.cpp, sycl/test-e2e/Graph/Inputs/work_group_static_memory.cpp, sycl/test-e2e/Graph/RecordReplay/work_group_static_memory.cpp, sycl/test-e2e/Graph/Update/work_group_static_memory_with_dyn_cgf_and_dyn_params.cpp
Two e2e tests were added:
- `Inputs/work_group_static_memory.cpp` checks if using the extension in a static graph works,
- `Update/work_group_static_memory_with_dyn_cgf_and_dyn_params.cpp` tests the work_group extension against graph with dynamic CGF which at the same time, uses one dynamic parameter
=> [SYCL] [Graph] Add E2E tests for Graphs using sycl_ext_oneapi_work_group_static extension 

sycl/cmake/modules/UnifiedRuntimeTag.cmake
https://github.com/oneapi-src/unified-runtime/pull/1536
Align the UR clang-format version with intel/llvm.
=> [UR] Unified clang format

sycl/include/syclcompat/util.hpp, sycl/test-e2e/syclcompat/util/util_permute_sub_group_by_xor.cpp
`syclcompat::permute_sub_group_by_xor` was reported to flakily fail on L0. Closer inspection revealed that the implementation of `permute_sub_group_by_xor` is incorrect for cases where `logical_sub_group_size != 32`, which is one of the test cases. This implies that the test itself is wrong.
In this PR we first optimize the part of the implementation that is valid assuming that Intel spirv builtins are correct (which is also the only case realistically a user will program): case `logical_sub_group_size == 32`, in order to:
- Ensure the only useful case is working via the correct optimized route.
- Check that this improvement doesn't break the suspicious test.
A follow on PR can fix the other cases where `logical_sub_group_size != 32`: this is better to do later, since
- the only use case …
=> [SYCLCompat] Optimize/(fix?) permute_sub_group_by_xor if `logical_sub_group_size == 32`

sycl/cmake/modules/UnifiedRuntimeTag.cmake
https://github.com/oneapi-src/unified-runtime/pull/2582
=> [UR] Update tag to 8b7a9957 for https://github.com/oneapi-src/unified-runtime/pull/2582

sycl/doc/extensions/proposed/sycl_ext_oneapi_launch_queries.asciidoc
Adopt the longer Constraints/Effects/Returns format from ISO C++, which clarifies how the different overloads are intended to work.
=> [SYCL][Doc] Reformat launch queries extension

sycl/test-e2e/ProgramManager/multi_device_bundle/device_libs_and_caching.cpp
By using `4.0` instead of `4.0f`, we're using a `double`, implicitly requiring support for `aspect::fp64`. We don't really require it.
=> [SYCL] Drop undesired fp64 aspect requirement.

sycl/doc/extensions/experimental/sycl_ext_oneapi_bindless_images.asciidoc
This PR adds more fine-grained information about the types of USM allocations are supported with bindless images.
Signed-off-by: Georgi Mirazchiyski <georgi.mirazchiyski@codeplay.com>
=> [SYCL][Bindless] Clarify the types of supported USM memory in bindless images

sycl/test-e2e/Basic/fpga_tests/fpga_pipes.cpp
to address post-commit failure here:
https://github.com/intel/llvm/issues/16693
This fpga_pipe.cpp test has been passing because it was using the wrong binary operation to fold together test results. I fixed this in this and some other tests recently. My PR passed the CI because, apparently, we don't have exercise the FPGA accelerator (or emulator) there.
fpga_pipe.cpp tests 12 different combinations, the last two ( `test_array_th_nb_pipe` and `test_array_th_bl_pipe` ) are failing. Opening a JIRA.
=> [SYCL] disabling two test clauses while opening a JIRA

devops/dependencies.json
=> [GHA] Uplift Linux GPU RT version to 24.52.32224.5

sycl/test-e2e/DeviceGlobal/device_global_copy.cpp
On some Windows configurations, the /std:c++23 option is not recognized. To address this, we instead instruct the compiler to accept it as a clang flag.
=> [SYCL][E2E] Fix c++23 option in device_global_copy

sycl/test-e2e/bindless_images/3_channel_format.cpp
This patch should fix the post-commit failure resulting from enabling the 3-channel image PR in https://github.com/intel/llvm/pull/16537
This is done by adding a `// REQUIRES-INTEL-DRIVER:` comment for LIT to ignore the test until the necessary driver for the functionality is introduced to the GitHub CI.
=> [SYCL][Bindless][E2E] Fix post-commit from PR #16537

.ci/metrics/requirements.lock.txt
PR to bump dependency version to resolve security vulnerability found.
In current version, The wrong string if check is run for iss checking, resulting in "acb" being accepted for "_abc_".
Additional details:
Weaknesses: CWE-697
CVE ID: CVE-2024-53861
=> Bump PyJWT to 2.10.1 in .ci/metrics/requirements.lock.txt

sycl/doc/extensions/supported/sycl_ext_intel_device_info.md
SYSMAN is now enabled by default, so this note is no longer accurate.
=> [SYCL][DOC] Remove note on explicitly enabling SYSMAN

clang/include/clang/Basic/Attr.td, clang/include/clang/Basic/DiagnosticSemaKinds.td, clang/include/clang/Sema/SemaSYCL.h, clang/lib/CodeGen/CodeGenFunction.cpp, clang/lib/CodeGen/CodeGenModule.cpp, clang/lib/CodeGen/CodeGenModule.h, clang/lib/Sema/SemaDeclAttr.cpp, clang/lib/Sema/SemaSYCL.cpp, clang/lib/Sema/SemaSYCLDeclAttr.cpp, clang/test/CodeGenSYCL/registered-kernel-names.cpp, clang/test/SemaSYCL/registered-kernel-names.cpp
This change adds support for a new attribute
``__sycl_detail::__registered_kernels__``, which appears at translation
unit scope.  The parameter for this attribute is a list of pairs like:
```
[[__sycl_detail__::__registered_kernels__(
{"foo", foo},
{"(void(*)(int, int*))iota", (void(*)(int, int*))iota},
{"kernel<float>", kernel<float>}
)]];
```
The first element in each pair is a string, and the second element is a
constant expressiton for a pointer to a SYCL free function kernel.
The change creates the kernel's wrapper function and generates
module-level metadata of the form:
```
!sycl_registered_kernels = !{!0, !1}
!0 = !{!"foo", !"mangled-name-of-wrapper-for-foo"}
!1 = !{!"kernel<float>", !"mangled-name-of-wrapper-for-kernel<float>"}
```
where the first element in the pair of strings, …
=> [SYCL] Add support for __registered_kernels__

devops/scripts/install_build_tools.sh
This is intended to improve test coverage as some `llvm-spirv` tests require `spirv-tools` to execute.
=> [CI] Install `spirv-tools` on Linux docker containers

.github/workflows/sycl-linux-run-tests.yml, devops/actions/run-tests/cts/action.yml, devops/actions/run-tests/e2e/action.yml
Two reasons:
* Make the workflow more maintainable as we're in the process of adding another option (benchmarks)
* I want to move E2E build-only from a separate job to a step during `sycl-linux-build.yml`. My first thought was to use in-tree E2E configuration but then it mismatches how we'd run the tests (in a standalone mode) and we have a bunch of tests using `rpath` during compilation which can't work with such mismatch. As such, outlining E2E support into a composite action would allow to share code between build/run e2e tests in distinct jobs (build vs matrix run-tests).
=> [CI] Split E2E/CTS tests into composite action

sycl/doc/extensions/proposed/sycl_ext_oneapi_device_image_backend_content.asciidoc
We decided in KhronosGroup/SYCL-Docs#667 to use this wording for SYCL APIs that require C++ features added after C++17.  The next version of the SYCL spec formally adopts this wording in
KhronosGroup/SYCL-Docs#680.
=> [SYCL][Doc] Update spec wording regarding C++20

sycl/include/sycl/context.hpp, sycl/include/sycl/detail/info_desc_helpers.hpp, sycl/include/sycl/device.hpp, sycl/include/sycl/event.hpp, sycl/include/sycl/info/device_traits_deprecated.def, sycl/include/sycl/info/sycl_backend_traits.def, sycl/include/sycl/kernel.hpp, sycl/include/sycl/platform.hpp, sycl/include/sycl/queue.hpp, sycl/source/detail/context_impl.cpp, sycl/source/detail/device_impl.cpp, sycl/source/detail/event_impl.cpp, sycl/source/detail/kernel_impl.cpp, sycl/source/detail/platform_impl.cpp, sycl/source/detail/queue_impl.cpp, sycl/test-e2e/Basic/backend_info.cpp, sycl/test/warnings/deprecated_get_backend_info.cpp, sycl/test/warnings/sycl_2020_deprecations.cpp
The `get_backend_info()` functions implemented in https://github.com/intel/llvm/pull/12906 are returning some info descriptors that are not backend-specific info descriptors but SYCL core info descriptors. This leads to problems as described in https://github.com/intel/llvm/pull/16272 . Therefore, its current implementations are being deprecated, and removed under the `__INTEL_PREVIEW_BREAKING_CHANGES` flag.
=> [SYCL] Deprecate current implementations of get_backend_info()

.github/workflows/sycl-linux-build.yml, .github/workflows/sycl-windows-build.yml, llvm-spirv/test/lit.cfg.py
https://github.com/intel/llvm/pull/16724 installed `spirv-tools` on Linux docker containers and now some llvm-spirv tests are failing due to this (example: https://github.com/intel/llvm/actions/runs/12915358763/job/36017038536).
In this PR, we disable detection of `spirv-tools` LIT feature temporarily in CI to fix post-commit.
=> [CI] Temporarily disable tests requiring `spirv-tools` in CI

sycl/test-e2e/KernelCompiler/kernel_compiler_opencl.cpp, sycl/test-e2e/KernelCompiler/kernel_compiler_sycl.cpp, sycl/test-e2e/KernelCompiler/kernel_compiler_sycl_jit.cpp, sycl/test-e2e/KernelCompiler/multi_device.cpp, sycl/test-e2e/KernelCompiler/sycl_and_cache.cpp, sycl/test-e2e/KernelCompiler/sycl_device_flags.cpp, sycl/test/e2e_test_requirements/no-unsupported-without-info.cpp, sycl/test/e2e_test_requirements/no_sycl_hpp_in_e2e_tests.cpp
moving kernel_compiler sycl cache testing to its own test. Also updating some of the 'unsupported-intended' information.  This also increments the #include <sycl.hpp> counter, not because the new test does that (it does not), but the kernel string it contains does and that's incorrectly getting picked up by the no_sycl_in_hpp test.
=> [SYCL] moving kernel_compiler sycl cache testing to its own test.

.github/workflows/pr-code-format.yml, .github/workflows/sycl-linux-precommit.yml, .github/workflows/sycl-post-commit.yml, .github/workflows/sycl-windows-precommit.yml
It was originally added in https://github.com/intel/llvm/pull/10002, back when we used `pull_request_target` for pre-commit trigger. Now that `pull_request` is used it isn't (as) necessary.
I'm also adding a `workflow_dispatch` trigger for the post-commit job for cases when somebody wants to test extensive non-CI changes with post-commit before the merge. I think that will work but it's impossible to verify before merging this due to how GHA work.
This will address the following usage scenario:
* Push CI-related changes to `sycl-devops-pr` (possibly several iterations)
* Result are ok, open a PR from that branch
- extra post-commit task is spawned for the commit that has been tested already (this duplication will remain, unfortunately)
* Address review feedback with a new upload
- two …
=> [CI] Remove `sycl-devops-pr/**` hack

.github/workflows/sycl-post-commit.yml, .github/workflows/sycl-windows-precommit.yml
That input parameter was introduced to `sycl-windows-build.yml` in https://github.com/intel/llvm/pull/16560 but it's unclear why.
Note that linux version has had it for quite some time, but we started unsetting it explicitly in https://github.com/intel/llvm/pull/10720. The reason we had it for Linux in the first place is because `GITHUB_SHA` pointed to the PR's source branch for the `pull_request_target` trigger that we used at that time. With switching to `pull_request` trigger it became unnecessary as `GITHUB_SHA` points to the merge commit already.
This change should fix current race condition when a post-commit CI job can test change landed after the current commit if there is a delay with runner allocation.
=> [CI] Fix race condition by unsetting `merge_ref` for Windows tasks

sycl/include/sycl/detail/is_device_copyable.hpp, sycl/test/basic_tests/is_device_copyable.cpp, sycl/test/basic_tests/is_device_copyable_neg.cpp
Restore (logically) previous condition while keeping the rest of cleanups in place. Deprecation warning never worked, so I'm not even trying to implement that.
=> Partially revert a5e820976484 [SYCL] Remove `IsDeprecatedDeviceCopyable` (#16615)

.github/workflows/sycl-linux-build.yml, .github/workflows/sycl-linux-precommit.yml, devops/actions/run-tests/e2e/action.yml
This will allow us to save time on runner setup and toolchain download/unpacking.
=> [CI] Prebuild E2E tests as part of build workflow

.github/workflows/sycl-post-commit.yml, .github/workflows/sycl-windows-build.yml
It was the math flags.
We can't use `/Qno-intel-libs` and remove the env setup requirement from the e2e phase because of some insane linking errors I can't figure out and I don't think it's worth the time to investigate it any more.
Closes: https://github.com/intel/llvm/issues/16362
=> [CI] Fix Windows oneAPI test failures

sycl/test-e2e/CMakeLists.txt
Our CI uses "standalone" configuration for running E2E tests, but interactive development is (likely) mostly using in-tree configuration. With this change we can enable more tests running by default in such mode.
=> [SYCL][E2E] Pass freshly built OpenCL/L0 to e2e tests for in-tree configuration

.github/workflows/sycl-linux-build.yml, .github/workflows/sycl-linux-precommit-aws.yml, .github/workflows/sycl-linux-precommit.yml, .github/workflows/sycl-linux-run-tests.yml, .github/workflows/sycl-nightly.yml, .github/workflows/sycl-post-commit.yml, .github/workflows/sycl-rel-nightly.yml, .github/workflows/sycl-weekly.yml, .github/workflows/sycl-windows-build.yml, .github/workflows/sycl-windows-precommit.yml, .github/workflows/sycl-windows-run-tests.yml, devops/actions/cached_checkout/action.yml, devops/actions/run-tests/e2e/action.yml
There were a few places that didn't pass explicit `''` and all of them were actual bugs:
* `sycl-nightly.yml` didn't pass it for windows build and run-tests
* `sycl-nightly.yml` didn't pass it for `ubuntu2404_oneapi_build` job (passed for other linux build jobs)
=> [CI] Switch default `merge_ref` to empty

sycl/include/sycl/ext/oneapi/experimental/device_architecture.hpp
Based on the code for supported architectures the macro should start
with only two underscores.
=> [NFC][SYCL] Remove spurious underscore in comments

sycl/include/syclcompat/math.hpp, sycl/test-e2e/syclcompat/math/math_compare.cpp
The `compare_mask` and `unordered_compare_mask` implementations were placing the results of the comparison operations in the wrong 2-byte segments of the 4-byte output.
The `math_compare.cpp` test has also been fixed, where the "expected" results were previously incorrect, they now reflect the values returned by the corresponding CUDA math functions.
=> [SYCLCompat] Fix `compare_mask` implementations and test

.github/workflows/sycl-linux-build.yml, .github/workflows/sycl-linux-precommit.yml, .github/workflows/sycl-linux-run-tests.yml, devops/actions/run-tests/e2e/action.yml
Reduce number of input parameters and make the logic a bit cleaner (IMO). This PR also uses that updated logic to make building E2E tests optional in `sycl-linux-build.yml` and makes enabled in pre-commit only for now, effectively fixing the regression in Nightly CI introduced in https://github.com/intel/llvm/pull/16682.
=> [CI] Refactor build/run-only logic in `run-tests/e2e/action.yml`

llvm/include/llvm/SYCLLowerIR/SYCLOptimizeBackToBackBarrier.h, llvm/lib/Passes/PassBuilder.cpp, llvm/lib/Passes/PassRegistry.def, llvm/lib/SYCLLowerIR/CMakeLists.txt, llvm/lib/SYCLLowerIR/SYCLOptimizeBackToBackBarrier.cpp, llvm/test/SYCLLowerIR/SYCLOptimizeBackToBackBarrier/remove-back-to-back-barrier.ll
This pass removes redundant __spirv_ControlBarrier call (as well as ITT annotations surrounding it) in case if it's neighboring another __spirv_ControlBarrier call with the same memory scope and memory semantics arguments. If the calls have different
execution scope arguments - then pick the one with the 'bigger' scope.
=> [SYCL] Optimize back-to-back ControlBarrier calls

sycl/test-e2e/format.py
Currently if a test contains a malformed directive, the following exception is raised along with the original parsing error:
```plaintext
Exception during script execution:
(original error)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "llvm/llvm/utils/lit/lit/worker.py", line 76, in _execute_test_handle_errors
result = test.config.test_format.execute(test, lit_config)
File "llvm/sycl/test-e2e/format.py", line 232, in execute
script = self.parseTestScript(test)
File "llvm/sycl/test-e2e/format.py", line 105, in parseTestScript
return lit.Test.Result(Test.UNRESOLVED, str(e))
NameError: name 'Test' is not defined
```
The test ends up as UNRESOLVED either way, but fixing it is easy and improves the error message greatly.
=> [SYCL][E2E][NFC] Fix NameError if directive fails to parse

devops/scripts/install_build_tools.sh
`pkg-config` is required for `llvm-spirv` to detect `spirv-tools` installation.
See https://github.com/intel/llvm/pull/16743#issuecomment-2614079031 for more info.
=> [CI] Install `pkg-config` in docker container

devops/scripts/update_drivers.py
IGC public CI has been failing for months and we got confirmation even if the public CI fails the change has already been internally validated.
We can confirm this change works as below:
[Old link](https://api.github.com/repos/intel/intel-graphics-compiler/actions/workflows/build-IGC.yml/runs?status=success)
[New link](https://api.github.com/repos/intel/intel-graphics-compiler/actions/workflows/build-IGC.yml/runs)
=> [CI] Update dev-igc even if IGC CI failed

sycl/test/regression/vec_array_windows.cpp
Test to isolate `sycl::vec` regression after https://github.com/intel/llvm/pull/14130. This PR caused `sycl::vec` to use `std::array` as its underlying storage. However, operations on `std::array` may emit debug-mode-only functions, on which the device compiler may fail.
=> [SYCL][Test] Add regression test for `sycl::vec` compilation error in windows, debug

llvm/lib/SYCLNativeCPUUtils/CMakeLists.txt
Update to newer OCK to pull in fixes for subgroups.
https://github.com/uxlfoundation/oneapi-construction-kit/compare/d983db7aa87fc1a6f7cdb46e3ced63f6f145749e...846a5c6118826171fb1c93702dd12b004053165c
=> [SYCL][NativeCPU] Update OCK.

sycl/test-e2e/Graph/Update/Explicit/whole_update_local_acc.cpp, sycl/test-e2e/Graph/Update/Explicit/whole_update_local_acc_multi.cpp, sycl/test-e2e/Graph/Update/Explicit/whole_update_work_group_memory.cpp, sycl/test-e2e/Graph/Update/RecordReplay/whole_update_local_acc.cpp, sycl/test-e2e/Graph/Update/RecordReplay/whole_update_local_acc_multi.cpp, sycl/test-e2e/Graph/Update/RecordReplay/whole_update_work_group_memory.cpp
Re-enable whole graph update tests using local memory on Level-Zero.
=> [SYCL][Graph] Re-enable SLM update tests

sycl/test-e2e/Matrix/joint_matrix_hip_gfx90a.cpp, sycl/test-e2e/Matrix/joint_matrix_hip_half_gfx90a.cpp, sycl/test-e2e/Matrix/joint_matrix_tensorcores_sm70.cpp, sycl/test-e2e/Matrix/runtime_query_hip_gfx90a.cpp
As of #16725 tests that do not build for `spir64` do not need to be marked as exceptions for split build/run with `REQUIRES: build-and-run-mode`, instead we can mark them as `REQUIRES: target-<nvidia/amd>`.
This patch replaces the `REQUIRES: build-and-run-mode` directives in Matrix tests with `REQUIRES: target-amd` or `REQUIRES: target-nvidia`.
=> [SYCL][Matrix][E2E] Remove `REQUIRES: build-and-run-mode` from Matrix tests

.github/workflows/sycl-linux-build.yml, .github/workflows/sycl-windows-build.yml, llvm-spirv/test/lit.cfg.py
Reverts intel/llvm#16743. After installing `pkg-config` in CI, `llvm-spirv` can correctly find `spriv-tools` so this workaround is no longer needed.
Example run: https://github.com/intel/llvm/actions/runs/12996166493/job/36244369469?pr=16801#step:14:16
=> Revert "[CI] Temporarily disable tests requiring `spirv-tools` in CI"

libclc/clc/include/clc/clcfunc.h
These 4 macros were moved in 4602c16a6823, but added back by b400aa4586c4, resuling in duplicate definitions in this file.
=> [NFC][libclc] Fix clcfunc.h merge conflict resolve in b400aa4586c4

.github/workflows/sycl-linux-precommit.yml, .github/workflows/sycl-linux-run-tests.yml, .github/workflows/sycl-nightly.yml, .github/workflows/sycl-post-commit.yml, .github/workflows/sycl-rel-nightly.yml, .github/workflows/sycl-weekly.yml, sycl/test-e2e/DeprecatedFeatures/opencl_interop.cpp, sycl/test-e2e/KernelCompiler/kernel_compiler_spirv.cpp, sycl/test-e2e/Regression/device_num.cpp
First step on unifying our "base" image into a single "fat" container similarly to what's been done with nightly images at https://github.com/intel/llvm/pull/16680.
=> [CI] Simplify CI by using `alldeps` image whenever possible

sycl/test-e2e/format.py
We've been getting
```
.../sycl/test-e2e/format.py:34: SyntaxWarning: invalid escape sequence '\.'
win = re.search("win: *([0-9]{3}\.[0-9]{4})", line)
```
before this PR.
=> [SYCL][E2E] Use "raw string" in `re.search(r"", ...)`

sycl/test-e2e/Adapters/cuda_queue_priority.cpp, sycl/test-e2e/Adapters/dll-detach-order.cpp, sycl/test-e2e/syclcompat/kernel/kernel_win.cpp, sycl/test-e2e/syclcompat/launch/launch_properties.cpp, sycl/test-e2e/syclcompat/memory/local_memory_ptr_to_integer.cpp
As of #16725 tests can properly react to features that affect compilation on build-only mode (i.e., libraries or OS), additionally we can also mark if a test should only be built for a specific triple using the `target-*` features.
This pr removes `REQUIRES: build-and-run-mode` from syclcompat and Adapters tests, and either lets the test be marked as unsupported due to requiring a missing build feature (`windows` or `cuda_dev_kit`), or the test is marked as unsupported for `spir` by requiring `target-nvidia`
=> [SYCL][E2E] Remove `REQUIRES: build-and-run-mode` from `syclcompat` and `Adapters` tests

clang/lib/CodeGen/CGCall.cpp, clang/test/CodeGenSYCL/sycl_unaliased_property.cpp, sycl/doc/extensions/experimental/sycl_ext_oneapi_kernel_arg_properties.asciidoc, sycl/include/sycl/ext/oneapi/experimental/common_annotated_properties/properties.hpp, sycl/include/sycl/ext/oneapi/properties/property.hpp, sycl/test-e2e/Annotated_arg_ptr/annotated_arg_unaliased.cpp, sycl/test-e2e/Annotated_arg_ptr/annotated_ptr_unaliased.cpp, sycl/test/check_device_code/extensions/annotated_arg/unaliased.cpp, sycl/test/check_device_code/extensions/annotated_ptr/unaliased.cpp
This commit renames the `restrict` kernel argument property to `unaliased` to avoid conflicting with common code patterns in C/C++ projects.
=> [SYCL][Docs] Rename restrict property to unaliased

sycl/CMakeLists.txt
CMake's check_linker_flag does no split flags by spaces, so the current call passes the single option `"/OPT:REF LINKER:/OPT:ICF"` with a space in it to link.exe. (The first `LINKER:` prefix is parsed). This was also broken before ede906ce6cb425718638091322f425b84676047f ([CMake][MSVC] Wrap more Linker flags for ICX (#16284)), where it would pass `"/OPT:REF /OPT:ICF"` as a single option.
This results in the check failing and so the build does not ever enable these flags, even though they would be supported if the check was correct.
Use comma as the separator as supported by the `LINKER:` syntax to fix it.
=> [SYCL][CMake][MSVC] Fix link.exe /OPT detection

sycl/cmake/modules/UnifiedRuntimeTag.cmake
https://github.com/oneapi-src/unified-runtime/pull/2594
=> [UR][CL] Fix invalid use of dlopen()

sycl/include/syclcompat/device.hpp
There should be no logic based on the compiler version within the actual compiler: it can only have one version.
Note: does not take into account time-travel :)
=> [compat] Remove usage of __SYCL_COMPILER_VERSION

sycl/cmake/modules/UnifiedRuntimeTag.cmake, sycl/source/detail/graph_impl.cpp
Reflects UR change from https://github.com/oneapi-src/unified-runtime/pull/2578 where we no longer need to manually manage the lifetimes of the individual commands in a UR command-buffer.
=> [SYCL][Graph] Remove calls to urCommandBufferReleaseCommandExp

sycl/test/abi/layout_array.cpp
The layout_array test is currently prone to failure if any of the types it checks are instantiated by the headers rather than by the test itself. This means that unrelated changes to the SYCL headers may make the test fail due to one of the types being instantiated earlier than the test instantiates other types that go before it. To avoid this issue, this commit makes the test use specific headers, reducing the chance of instantiations.
This commit also fixes a faulty expectation in the `nd_item` test case.
=> [SYCL][E2E] Make layout_array.cpp use specific headers

.github/workflows/sycl-linux-precommit.yml, sycl/test-e2e/AddressSanitizer/bad-free/bad-free-host.cpp, sycl/test-e2e/AddressSanitizer/bad-free/bad-free-minus1.cpp, sycl/test-e2e/AddressSanitizer/bad-free/bad-free-plus1.cpp, sycl/test-e2e/AddressSanitizer/common/options-invalid-values.cpp, sycl/test-e2e/AddressSanitizer/double-free/double-free.cpp, sycl/test-e2e/AddressSanitizer/out-of-bounds/DeviceGlobal/device_global.cpp
`not --crash` changes are necessary because run-only mode has slightly different way of running the tests due to https://github.com/intel/llvm/blob/e8564403232c13b3716aa68190084880f2a98a6c/sycl/test-e2e/format.py#L368-L372
=> [CI] Use pre-built e2e tests for Arc GPU and Dev IGC PVC pre-commit

devops/containers/nightly.Dockerfile, devops/containers/ubuntu2204_intel_drivers.Dockerfile, devops/containers/ubuntu2404_intel_drivers.Dockerfile, devops/containers/ubuntu2404_intel_drivers_igc_dev.Dockerfile
This is leftover from some reverted Dockerfile changes. We only create a `sycl` user now, so use that like we did before those changes.
=> [CI] Remove sycl_ci user from Dockerfiles

llvm/lib/Transforms/Scalar/FPBuiltinFnSelection.cpp, llvm/test/CodeGen/NVPTX/fp-builtin-intrinsics-nvvm-approx.ll, llvm/test/CodeGen/NVPTX/fp-builtin-intrinsics-nvvm-max-error-0.5.ll, llvm/test/CodeGen/NVPTX/fp-builtin-intrinsics-nvvm-max-error-3.0.ll
AltMathLibrary is lacking implementation for llvm.fpbuiltin intrinsics
for NVPTX target. This patch adds type-dependent mapping for
llvm.fpbuiltin.fdiv with max-error > 2.0 and llvm.fpbuiltin.sqrt with
max-error > 1.0 on nvvm intrinsics:
fp32 scalar @llvm.fpbuiltin.fdiv -> @llvm.nvvm.div.approx.f
fp32 scalar @llvm.fpbuiltin.sqrt -> @llvm.nvvm.sqrt.approx.f
vector or non-fp32 scalar llvm.fpbuiltin.fdiv -> fdiv
vector or non-fp32 scalar llvm.fpbuiltin.sqrt -> llvm.sqrt
Additionally it maps max-error=0.5 fpbuiltin.fadd, fpbuiltin.fsub.
fpbuiltin.fmul, fpbuiltin.fdiv, fpbuiltin.frem, fpbuiltin.sqrt and
fpbuiltin.ldexp intrinsic functions of LLVM's math operations or
https://llvm.org/docs/LangRef.html#standard-c-c-library-intrinsics
TODO in future patches:
- add preservation of debug info in …
=> [SYCL][NVPTX] Set default fdiv and sqrt for llvm.fpbuiltin

.github/CODEOWNERS
This is to reflect the reviewers team being updated to remove the "pi"
element.
=> [CODEOWNERS] Update nativecpu codeowners entry.

sycl/test-e2e/Graph/Update/FreeFunctionKernels/update_with_indices_ordering.cpp
The code comment in `Update/FreeFunctionKernels/update_with_indices_ordering.cpp` mentions that it is unknown why the execution time is slower than the equivalent `Update/update_with_indices_ordering.cpp` test without free functions.
This has now been investigated in CMPLRLLVM-64841 and has found to be due to the explicit arguments in the free function signature avoiding constant folding from lambdas. Note that we want to keep these parameters as the test is stressing the case where multiple args are passed to the free function.
=> [SYCL][Graph] Refine E2E test comment

sycl/test-e2e/Adapters/level_zero_batch_event_status.cpp
- Updated the Level Zero batch event test to correctly check only for the necessary messages to be printed proving the functionality is behaving correctly.
fixes #16695
=> [SYCL][test][e2e][L0] Fix L0 batch event test reliability

devops/scripts/windows_detect_hung_tests.ps1
This is just the existing code we have in the run-tests yaml moved to a script.
In a subsequent PR I'm going to expand these checks to fix recent hangs we've seen, and I can't use an action because that requires a checkout which will fail if there's a hung test, so we need a normal script.
=> [CI] Add PS script to detect hung tests on Windows

sycl/test/e2e_test_requirements/check_e2eexpr_logic.cpp
so that it would work on systems with `python3` but without `python`.
=> [SYCL][Tests] Use `%python` in check_e2eexpr_logic.cpp

llvm-spirv/lib/SPIRV/libSPIRV/SPIRVInstruction.h, llvm-spirv/test/transcoding/OpLessOrGreater.ll, llvm-spirv/test/transcoding/subgroup_spirv_1_5.cl
For SPIR-V 1.4 and earlier, the Id operand of
OpGroupNonUniformBroadcast must come from a constant instruction.
Ensure that any emitted SPIR-V module using a non-constant Id operand declares SPIR-V version 1.5. Bail out if the maximum SPIR-V version was restricted to < 1.5, to avoid producing invalid SPIR-V.
Original commit:
KhronosGroup/SPIRV-LLVM-Translator@64fe75e388dc3b7
This reverts commit bbf3800adf1209d062ddb49555bb4f36120575ad
The reland is possible after switch to SPIR-V 1.5
=> [SPIR-V] Reland "Fix OpGroupNonUniformBroadcast version requirement"

sycl/test-e2e/AddressSanitizer/out-of-bounds/DeviceGlobal/device_global.cpp, sycl/test-e2e/lit.cfg.py
Closes https://github.com/intel/llvm/issues/16850.
=> [SYCL][E2E] Hack `AddressSanitizer/.../device_global.cpp` to pass CI

sycl/doc/extensions/proposed/sycl_ext_oneapi_syclbin.asciidoc
This commit adds the sycl_ext_oneapi_syclbin for loading a new SYCLBIN file format to `kernel_bundle`.
=> [SYCL][Docs] Add sycl_ext_oneapi_syclbin extension

sycl/test-e2e/OptionalKernelFeatures/is_compatible/is_compatible_amdgcn.cpp, sycl/test-e2e/OptionalKernelFeatures/is_compatible/is_compatible_nvptx64.cpp, sycl/test-e2e/SpecConstants/2020/non_native/cuda.cpp
These tests should only build on `build-only` if we have either `target-nvidia` or `target-amd` enabled. Currently they build regardless of what triples are available, and this was not detected because these tests set the triple explicitly rather than through the `%{sycl_target_opts}` expansion.
=> [SYCL][E2E] Use target feature in 3 tests that explicitly set the triple 

sycl/test-e2e/Basic/kernel_max_wg_size.cpp, sycl/test-e2e/Basic/sub_group_size_prop.cpp, sycl/test-e2e/ClusterLaunch/cluster_launch_parallel_for.cpp, sycl/test-e2e/ClusterLaunch/enqueueLaunchCustom_check_event_deps.cpp, sycl/test-e2e/DeviceCodeSplit/grf.cpp, sycl/test-e2e/Graph/Inputs/sub_group_prop.cpp, sycl/test-e2e/VirtualFunctions/misc/group-barrier.cpp, sycl/test-e2e/VirtualFunctions/misc/range-non-uniform-vf-2.cpp, sycl/test-e2e/VirtualFunctions/misc/range-non-uniform-vf.cpp, sycl/test-e2e/VirtualFunctions/misc/range-uniform-vf.cpp, sycl/test-e2e/WorkGroupScratchMemory/copy_dynamic_size.cpp, sycl/test-e2e/WorkGroupScratchMemory/dynamic_alloc_local_accessor.cpp, sycl/test-e2e/WorkGroupScratchMemory/dynamic_alloc_ptr_alias.cpp, sycl/test-e2e/WorkGroupScratchMemory/dynamic_allocation.cpp, sycl/test-e2e/WorkGroupScratchMemory/dynamic_unused.cpp
The overloads for single_task and parallel_for in the sycl_ext_oneapi_kernel_properties extension are being deprecated as mentioned in https://github.com/intel/llvm/pull/14785. So I'm rewriting tests containg such overloads so that they can still run after the deprecation.
=> [SYCL][E2E] Rewrite Tests Containing Deprecated Overloads #3

.github/workflows/trivy.yml, devops/.trivyignore.txt, devops/.trivyignore.yaml
This patch adds a workflow to perform trivy check as required by our public release policy.
=> [CI] Add Trivy workflow

libclc/libspirv/include/libspirv/spirv.h, libclc/libspirv/include/libspirv/workitem/get_local_linear_id.h, libclc/libspirv/lib/amdgcn-amdhsa/group/collectives.cl, libclc/libspirv/lib/generic/SOURCES, libclc/libspirv/lib/generic/workitem/get_local_linear_id.cl, libclc/libspirv/lib/ptx-nvidiacl/group/collectives.cl
This allows the builtin to be called in implementation of other builtins.
=> [libclc][libspirv] Add generic implementation of __spirv_LocalInvocationIndex

.github/CODEOWNERS
Transfer over code owners from https://github.com/oneapi-src/unified-runtime/blob/main/.github/CODEOWNERS mapping to existing teams as closely as possible.
=> [UR] Prepare CODEOWNERS file for repo move

devops/scripts/windows_detect_hung_tests.ps1
For whatever reason `tskill` seems to be able to kill processes `Stop-Process` can't. Manually tested this on a runner with hung tests.
=> [CI] Improve windows hang detection script

sycl/test-e2e/DeviceImageBackendContent/test_plan.md
This PR adds the test plan for [sycl_ext_oneapi_device_image_backend_content](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/proposed/sycl_ext_oneapi_device_image_backend_content.asciidoc) extension.
=> [SYCL][Doc] Add test plan for sycl_ext_oneapi_device_image_backend_content extension

sycl/test-e2e/ESIMD/lit.local.cfg, sycl/test-e2e/InvokeSimd/lit.local.cfg
These tests fail to build for nvptx/amdgcn so instead of marking unsupported based on the backend they should be marked as unsupported based on the build target.
=> [SYCL][E2E] Use target features instead of backend for ESIMD unsupported statements

sycl/cmake/modules/FetchUnifiedRuntime.cmake
Update the CMake build system to use the `<intel/llvm>/unified-runtime` directory if it exists. Fallback to using `FetchContent` when it does not exist.
This is in preparation for moving UR development into the intel/llvm repo.
=> [UR] Choose in-tree unified-runtime directory if present

devops/actions/run-tests/e2e/action.yml
The CUDA dev kit is already installed in the image we use but we don't pass these CMake vars so it isn't found.
It should be fine to do this unconditionally, lit.py does a full compile with required files and checks the compiler return code, so even if it isn't actually installed it won't cause any problems. The compile is failing today because we don't pass the vars anyway.
Manually tested this on the runners.
Confirming working in [this](https://github.com/intel/llvm/actions/runs/13164735078/job/36742725212?pr=16892) run, as `Adapters/cuda_queue_priority.cpp` passed which requires the feature.
=> [CI] Fix cuda_dev_kit detection on runners

sycl/doc/extensions/supported/sycl_ext_oneapi_backend_level_zero.md
The interop_handle example in the L0 backend specification uses a L0 context handle, but it may be unclear to users how that context handle is accessible. Since it needs to be at least associated with the corresponding device, it seems proper to be explicit in the example about how to get it from the interop_handle.
=> [SYCL][Docs] Add get_native_context call to interop_handle example

devops/actions/run-tests/e2e/action.yml, sycl/test-e2e/CMakeLists.txt, sycl/test-e2e/README.md
Add autodetection of the CUDA SDK using CMake's builtin `find_package`.
I didn't remove the LIT params or handling in lit.py as to not break anyone who may want to use a custom install.
Confirmed working [here](https://github.com/intel/llvm/actions/runs/13166519697/job/36748743079?pr=16896) as `Adapters/cuda_queue_priority.cpp` passed.
=> [SYCL][E2E] Add CUDA SDK autodetection

sycl/include/sycl/builtins_utils_scalar.hpp, sycl/include/sycl/builtins_utils_vec.hpp, sycl/include/sycl/detail/builtins/builtins.hpp, sycl/include/sycl/detail/builtins/relational_functions.inc
Main reason is to avoid having partial specializations for swizzles in the implementation of the traits as we're going to have big changes in that area. Between this change and having to update the traits this approach seemed better.
=> [NFCI][SYCL] Inline some traits related to fixed width int types

sycl/test-e2e/CMakeLists.txt
Follow-up from https://github.com/intel/llvm/pull/16896
=> [SYCL][E2E] Don't override CUDA CMake vars if set

sycl/test-e2e/DeviceImageBackendContent/OCL_interop_test.cpp
Add `XFAIL: accelerator` to `OCL_interop_test.cpp` because of [this](https://github.com/intel/llvm/actions/runs/13187415776/job/36814982904) and remove a rogue print statement meant for debugging purposes during development which is most likely unrelated to the failure.
An issue for the failure has also been created https://github.com/intel/llvm/issues/16914
=> [SYCL] Add XFAIL for fpga to OCL_interop_test.cpp

sycl/include/sycl/detail/type_traits.hpp
Avoid using partial specialization for swizzles as it depends on the swizzles implementation and we'll be making significant changes there to align with the proposed specification changes.
=> [NFCI][SYCL] Refactor `sycl::detail::make_unsigned`

sycl/include/sycl/ext/oneapi/experimental/group_load_store.hpp, sycl/test/check_device_code/group_load.cpp, sycl/test/check_device_code/group_load_store_native_key.cpp
Simplify handling of multiple address spaces and alignment checks. Additional improvement regarding alignment checks is being done here (to perform compile-time alignment check instead of expensive dynamic check): https://github.com/intel/llvm/pull/16882
Also this PR fixes alignment requirement for local address space: 16-byte alignment is required for both load and store.
=> [SYCL] Simplify group load/store implementation

sycl/include/sycl/builtins_utils_scalar.hpp, sycl/include/sycl/builtins_utils_vec.hpp, sycl/include/sycl/detail/builtins/geometric_functions.inc, sycl/include/sycl/detail/type_traits.hpp
That would match with pre-existing `check_type_in_v`.
=> [NFC][SYCL] Substitute `is_valid_size_v` with `check_value_in_v`

sycl/test-e2e/AddressSanitizer/dependency/shadow-virtual-mem.cpp
1. not treating not having two GPU devices as an error, but skip the test instead.
2. If the two GPU devices are not the same model, skip the test(not our targeted setup).
=> [DeviceASAN][test] Update shadow-virtual-mem.cpp

devops/scripts/install_build_tools.sh
pigz is a parallel implementation of gzip. coverity accepts a small range of archive formats: gzip, zip, lzma, xz or bz2. So using pigz to speed up the compression of build for coverity.
Also remove the duplicate of zstd.
=> [CI] Install pigz in docker container

sycl/test-e2e/Config/config.cpp, sycl/test-e2e/ESIMD/PerformanceTests/BitonicSortK.cpp, sycl/test-e2e/ESIMD/PerformanceTests/BitonicSortKv2.cpp, sycl/test-e2e/ESIMD/PerformanceTests/Stencil.cpp, sycl/test-e2e/ESIMD/PerformanceTests/invoke_simd_smoke.cpp, sycl/test-e2e/ESIMD/PerformanceTests/matrix_transpose.cpp, sycl/test-e2e/ESIMD/PerformanceTests/stencil2.cpp, sycl/test-e2e/ESIMD/preemption.cpp, sycl/test-e2e/KernelAndProgram/trace_kernel_program_cache.cpp, sycl/test-e2e/KernelCompiler/kernel_compiler_cache_eviction.cpp, sycl/test-e2e/format.py, sycl/test-e2e/lit.cfg.py
Previously to explicitly mark that a `RUN:` line should run on the run-stage the `%if run-mode %{...%}` markup was used. However, this markup is misleading given that the entire line is skipped in `build-only` mode, not just the bit enclosed in the braces. This PR replaces this markup with `%{run-aux}`, to avoid this issue.
=> [SYCL][E2E] Change method for setting a `RUN:` line to execute at run stage

clang/tools/clang-linker-wrapper/ClangLinkerWrapper.cpp
InputFiles variable defined in the function is not used. If statements below define local scope variables with the same name.
=> [clang-linker-wrapper][NFC] Remove dead code

devops/dependencies-igc-dev.json, devops/scripts/update_drivers.py, sycl/test-e2e/ESIMD/accessor_local.cpp, sycl/test-e2e/ESIMD/local_accessor_block_load_store.cpp, sycl/test-e2e/ESIMD/local_accessor_copy_to_from.cpp, sycl/test-e2e/ESIMD/lsc/lsc_local_accessor_block_load_store.cpp
Script was failing because there's no Ubuntu 22.04 artifacts anymore. Bump the igc-dev version which fixes some tests.
=> [CI] Fix driver update script script and bump igc-dev

sycl/test-e2e/VirtualFunctions/misc/group-barrier.cpp
Purpose of this PR is re-enabling `VirtualFunctions/group-barrier` e2e test for CPU and Windows OS.
=> [SYCL][E2E] Limit XFAIL only to CPU and Linux in VirtualFunctions/group-barrier test

sycl/include/sycl/detail/vector_arith.hpp, sycl/include/sycl/vector.hpp, sycl/test/check_device_code/vector/vector_bf16_builtins.cpp, sycl/test/check_device_code/vector/vector_convert_bfloat.cpp, sycl/test/check_device_code/vector/vector_math_ops.cpp
We don't want constraints on non-template hidden friend operators to be implemented by templatizing it. It would be trivial with C++20 concepts, but we're limited to C++17. The proposed class hierarchy for `vecto_arith` helper had intended that, but implementation was only partial.
We want to fix that while implementing the proposed specification changes to the vec/swizzle so setup infrastructure to do so now, to minimize the amount of "preview-breaking-changes" customizations later.
The idea is to split each operator into an individual unrestrained mixin, so that the constraints could be implemented on top of it via `detail::ApplyIf` helper. This particular PR only implements such a change for unary operators. The rest will be implemented in a subsequent change to ease review process.
=> [NFCI][SYCL] Split vec's unary ops into individual mixins

sycl/include/sycl/detail/vector_arith.hpp, sycl/test/check_device_code/vector/vector_math_ops.cpp
Continuing refactoring before implementing functional changes under preview guard. Not that this availability would need to be shared between vec/swizzle, so it makes sense to outline it outside of macros.
=> [NFC][SYCL] Add `is_op_available_for_type` helper for `sycl::vec` impl

sycl/test-e2e/bindless_images/helpers/common.hpp, sycl/test-e2e/bindless_images/vulkan_interop/sampled_images.cpp, sycl/test-e2e/bindless_images/vulkan_interop/unsampled_images.cpp
We can't use sycl::vec<T, 3> to access mapped memory of 3-channel vulkan image because the sycl type is aligned to 4 elements but there are only 3 elements per pixel in vulkan image memory.
=> [SYCL][E2E][Bindless] Fix access to mapped memory of 3-channel vulkan image

.github/workflows/sycl-linux-build.yml, .github/workflows/sycl-linux-precommit.yml, sycl/test-e2e/Matrix/joint_matrix_tensorcores_sm72.cpp, sycl/test-e2e/Matrix/joint_matrix_tensorcores_sm80.cpp, sycl/test-e2e/Regression/build_log.cpp, sycl/test-e2e/Regression/kernel_bundle_ignore_sycl_external.cpp, sycl/test-e2e/WorkGroupScratchMemory/copy_dynamic_size.cpp
Reduces time for precommit nvidia job from around 20m to around 5m
=> [CI][E2E] Run E2E tests on NVIDIA with prebuilt binaries in precommit

sycl/include/sycl/detail/vector_arith.hpp, sycl/test/check_device_code/vector/vector_bf16_builtins.cpp, sycl/test/check_device_code/vector/vector_convert_bfloat.cpp, sycl/test/check_device_code/vector/vector_math_ops.cpp
Refer to https://github.com/intel/llvm/pull/16946 for the context.
=> [NFCI][SYCL] Complete refactoring from `vec_arith` to individual mixins

.github/workflows/sycl-nightly.yml
Back when this task was added we only had runners with both AMD CPU and GPUs. Recently, we excluded the only remaining such runner as it's GPU isn't officially supported (we rely on the runner provided by Codeplay). However, we can keep using this old runner for the AMD CPU testing in Nightly as it was originally designed.
=> [CI] Change AMD CPU job in Nightly to use proper label

llvm/include/llvm/Analysis/TargetLibraryInfo.h, llvm/include/llvm/IR/IntrinsicInst.h, llvm/lib/Analysis/TargetLibraryInfo.cpp, llvm/lib/IR/IntrinsicInst.cpp, llvm/lib/Transforms/Scalar/FPBuiltinFnSelection.cpp
This is an upstream from a closed source repository.
Co-author: Stasenko, Alexander P <alexander.p.stasenko@intel.com>
=> [NFCI][SYCL] Refactor selection of FP builtin calls

clang/lib/Driver/ToolChains/Clang.cpp, clang/test/Driver/sycl-spirv-ext-old-model.c, clang/test/Driver/sycl-spirv-ext.c, clang/test/Driver/sycl-spirv-metadata-old-model.cpp, clang/test/Driver/sycl-spirv-obj-old-model.cpp, clang/test/Driver/sycl-spirv-obj.cpp, clang/tools/clang-linker-wrapper/ClangLinkerWrapper.cpp, clang/tools/clang-sycl-linker/ClangSYCLLinker.cpp
Since a pass that cleans up unnecessary llvm.fpbuiltin intrinsics was removed from
https://github.com/intel/llvm/pull/16107 we need to enable the extension by default to
successfully translate them.
=> [SYCL] Enable SPV_INTEL_fp_max_error by default

sycl/test-e2e/AddressSanitizer/out-of-bounds/local/group_local_memory.cpp
Disable the test temporarily due to two issues that appear after PR #16356:
* Local memory in the test is optimized out before AddressSanitizerPass.
* https://github.com/intel/llvm/issues/16979
=> [SYCL][E2E] Disable device AddressSanitizer test group_local_memory.cpp

.github/workflows/coverity.yml
It takes ~10mins for gzip to compress the cov-int dir. Use pigz (parallel implementation of gzip) to speed it up.
formats supported by coverity: gzip, zip, lzma, xz or bz2
https://github.com/intel/llvm/pull/16945
=> [CI] Use pigz in coverity

sycl/test-e2e/bindless_images/sampling_3D.cpp
This fixes the gfx1030 3D sampling failure mentioned here: https://github.com/intel/llvm/issues/16933
by marking this device unsupported in the test
=> [SYCL][E2E][Bindless] 3d sampler unsupported for gfx1030

sycl/doc/design/KernelProgramCache.md, sycl/source/detail/kernel_program_cache.hpp, sycl/source/detail/program_manager/program_manager.cpp
Remove the unused Spec Consts component of the kernel fast cache key.
=> [SYCL] Remove the unused Spec Consts variable

sycl/test-e2e/README.md
Add new sections to the table of contents and make them subsections.
=> [NFC][Doc] Update test-e2e/readme.md

llvm/lib/SYCLLowerIR/LowerWGLocalMemory.cpp, llvm/test/SYCLLowerIR/group_local_memory.ll, llvm/test/SYCLLowerIR/work_group_static.ll
This fixes "error: undef deprecator failed" in pre-commit test of #16356
=> [SYCL][SYCLLowerWGLocalMemoryPass] replace undef with poison

sycl/include/sycl/detail/vector_arith.hpp
So that more code could be unified between non-preview/preview code paths.
=> [NFC][SYCL] Restructure `bit_not` special handling in `sycl::vec`

sycl/include/sycl/vector.hpp, sycl/test/check_device_code/vector/vector_bf16_builtins.cpp, sycl/test/check_device_code/vector/vector_convert_bfloat.cpp, sycl/test/check_device_code/vector/vector_math_ops.cpp
...in preparation of a future functional change that would require `sycl::vec` to have different ctors depending on the number of elements in it (as will be require by the now-proposed changes to the SYCL specification).
=> [NFCI][SYCL] Introduce `sycl::detail::vec_base`

sycl/include/sycl/ext/oneapi/experimental/graph.hpp
PR https://github.com/intel/llvm/pull/16788 broke the windows post-commit CI when building with `icx`/`icpx` https://github.com/intel/llvm/actions/runs/13310637099/job/37172065867
```
D:\github\_work\llvm\llvm\build\include\sycl\ext\oneapi\experimental\graph.hpp(577,8): error: 'dllexport' attribute ignored [-Werror,-Wignored-attributes]
577 | struct __SYCL_EXPORT
|        ^
D:\github\_work\llvm\llvm\build\include\sycl\detail\export.hpp(23,34): note: expanded from macro '__SYCL_EXPORT'
23 | #define __SYCL_EXPORT __declspec(dllexport)
|                                  ^
In file included from D:\github\_work\llvm\llvm\src\sycl\unittests\Extensions\EventMode.cpp:9:
In file included from D:\github\_work\llvm\llvm\build\include\sycl\sycl.hpp:11:
In file included from …
```
=> [Sycl][Graph] Remove SYCL_EXPORT from template to fix build error

sycl/test-e2e/DeviceImageBackendContent/OCL_interop_test.cpp, sycl/test-e2e/VirtualMem/vector_with_virtual_mem.cpp
Remove `UNSUPPORTED: linux && gpu-intel-dg2` from `vector_with_virtual_mem.cpp` as the test is passing consistently now.
Closes: https://github.com/intel/llvm/issues/15812
=> [SYCL] Remove UNSUPPORTED from vector_with_virtual_mem.cpp

.github/workflows/sycl-linux-precommit.yml
... and stop limiting number of tests running on Intel Arc GPUs. With the speedup of using pre-built binaries we can afford full coverage.
=> [CI] Move more pre-commit E2E jobs to use pre-built binaries

.github/workflows/sycl-nightly.yml
Add E2E tests execution on L0 x [PVC, Arc, BMG] and self hosted CUDA runners. We'll keep nightly testing in single target device, full (build + run) mode.
=> [CI] Extend Nightly E2E testing

sycl/source/handler.cpp
There is no need to pass by value in this case.
Shows up in coverity.
=> [SYCL][NFC] Pass impl by reference in fill_copy_arg

.github/workflows/sycl-detect-changes.yml, .github/workflows/ur-build-hw.yml, .github/workflows/ur-precommit.yml, .github/workflows/ur-source-checks.yml
~~Last commit included just to verify if `test_job` will be executed.~~
With extra dummy changes (now missing in PR) we just didn't skip the `test_job`, e.g. here: https://github.com/intel/llvm/actions/runs/13040807649/job/36382037543
=> [UR][CI] Add first version of UR workflow

sycl/test-e2e/DeviceLib/imf_simd_emulate_test.cpp
Seems sporadically failing there too, see [here](https://github.com/intel/llvm/issues/17008).
=> [SYCL][E2E] Disable imf_simd_emulate_test.cpp on igc-dev Arc

sycl/test-e2e/MemorySanitizer/check_device_global.cpp
Temporarily disable on all required platforms because of https://github.com/intel/llvm/issues/16978
Fail shows up on unrelated PRs.
=> [SYCL][E2E] Temporarily disable MemorySanitizer/check_device_global.cpp

clang/lib/Driver/Driver.cpp, clang/test/Driver/sycl-target-mismatch.cpp
The use of -fsycl-force-target=arg allows for a user to override the default target triple that is used to unbundle device objects from the fat objects.  A diagnostic warning is emitted to inform the user that the expected target values within the given objects is not found.  This diagnostic is not valid when -fsycl-force-target is used with the matching target value.
Avoid emitting this warning when the -fsycl-force-target=arg matches what is found in the incoming objects.
=> [Driver][SYCL] Do not emit mismatch warning with -fsycl-force-target

sycl/include/syclcompat/launch_policy.hpp
This is important when passing a CUTensorMap argument to a descriptor, since taking the address of a copy of a CUTensorMap will cause runtime issues. e.g.
```
UR CUDA ERROR:
Value:           700
Name:            CUDA_ERROR_ILLEGAL_ADDRESS
Description:     an illegal memory access was encountered
Function:        operator()
Source Location: /home/finlay/llvm/build/_deps/unified-runtime-src/source/adapters/cuda/queue.cpp:231
```
=> [SYCLCOMPAT] Forward launch arguments to avoid copies

sycl/include/sycl/known_identity.hpp, sycl/test/basic_tests/reduction/infinite_identity.cpp
Technically a workaround, this fixes the problem with `known_identity<minOp/maxOp>` being incorrect when using `-ffast-math`.  It works because we have a `__FAST_MATH__` macro that is defined when that flag is used. Better,  would be to detect `-fno-honor-infinities`. Opening a JIRA/discussion for that, but this is a big improvement in the interim.
See discussion https://github.com/intel/llvm/issues/13813
=> [SYCL] Fix min/max known_identity<> wrong when -ffast-math is used.

sycl/test-e2e/Matrix/joint_matrix_out_bounds.cpp
Computing reference values on host is slow at default `-O0`, making this test very slow. Before this PR, from CI precommit:
```
Slowest Tests:
--------------------------------------------------------------------------
174.00s: SYCL :: Matrix/joint_matrix_out_bounds.cpp
77.60s: SYCL :: KernelCompiler/kernel_compiler_sycl_jit.cpp
```
=> [SYCL][E2E] Add `-O2` to `Matrix/joint_matrix_out_bounds.cpp`

sycl/doc/extensions/experimental/sycl_ext_oneapi_graph.asciidoc, sycl/source/detail/graph_impl.cpp, sycl/source/detail/graph_impl.hpp, sycl/source/detail/scheduler/commands.cpp, sycl/test-e2e/Graph/Inputs/whole_update_host_task.cpp, sycl/test-e2e/Graph/Inputs/whole_update_host_task_accessor.cpp, sycl/test-e2e/Graph/Update/Explicit/whole_update_host_task.cpp, sycl/test-e2e/Graph/Update/Explicit/whole_update_host_task_accessor.cpp, sycl/test-e2e/Graph/Update/RecordReplay/whole_update_host_task.cpp, sycl/test-e2e/Graph/Update/RecordReplay/whole_update_host_task_accessor.cpp, sycl/test-e2e/Graph/Update/dyn_cgf_host_task_accessor.cpp, sycl/test-e2e/Graph/Update/dyn_cgf_host_task_usm.cpp
- Update spec wording to allow updating host-task function in graphs
- Support host-tasks in dynamic command-groups
- Support host-tasks in whole graph update
- Add E2E tests for both scenarios
- Fix passing incorrect accessors to graph update command after update which could cause issues if the graph was destroyed while the scheduler still had graph execution commands alive
=> [SYCL][Graph] Enable host-task update in graphs

unified-runtime/source/adapters/native_cpu/enqueue.cpp, unified-runtime/source/adapters/native_cpu/event.cpp, unified-runtime/source/adapters/native_cpu/event.hpp, unified-runtime/source/adapters/native_cpu/kernel.hpp
We were reading the kernel arguments at kernel execution time, but kernel arguments are allowed to change between enqueuing and executing. Make sure to create a copy of kernel arguments ahead of time.
This was previously approved as a unified-runtime PR: https://github.com/oneapi-src/unified-runtime/pull/2700
=> [SYCL][NativeCPU] Fix kernel argument passing.

libclc/CMakeLists.txt
This is an alternative fix to #17052.
The merge resolution in 98f847a accidentally stopped the compilation of all libspirv builtins, resulting in an empty library.
The libspirv directory structure is almost identical to the OpenCL directory structure, except that it also has a native-cpu directory. Thus we introduce a new variable to manage libspirv directories, which starts out inheriting from the OpenCL directories.
=> [libclc] Resolve bad merge; fix libspirv LIT failures

.github/workflows/ur-build-hw.yml, .github/workflows/ur-precommit.yml, .github/workflows/ur-source-checks.yml, unified-runtime/.github/scripts/install_hwloc.sh
First part of changes in UR workflow, after moving its content here.
Use detect-changes to only enable UR jobs if UR is affected, plus use the new location of ur project (local instead of clonging UR repo).
=> [CI] UR workflow update

sycl/test-e2e/Adapters/interop-level-zero-image-ownership.cpp, sycl/test-e2e/Adapters/level_zero_barrier_optimization.cpp, sycl/test-e2e/Adapters/level_zero_batch_barrier.cpp, sycl/test-e2e/Adapters/level_zero_batch_event_status.cpp, sycl/test-e2e/Adapters/level_zero_batch_test.cpp, sycl/test-e2e/Adapters/level_zero_batch_test_copy_with_compute.cpp, sycl/test-e2e/Adapters/level_zero_device_scope_events.cpp, sycl/test-e2e/Adapters/level_zero_eager_init.cpp, sycl/test-e2e/Adapters/level_zero_memory_fill.cpp, sycl/test-e2e/Adapters/level_zero_usm_device_read_only.cpp, sycl/test-e2e/Adapters/level_zero_usm_residency.cpp, sycl/test-e2e/Basic/buffer/buffer_create.cpp, sycl/test-e2e/KernelAndProgram/level-zero-static-link-flow.cpp, sycl/test-e2e/Properties/cache_config.cpp, sycl/test-e2e/USM/usm_pooling.cpp
from UR_L0_DEBUG.
L0 API logging will most likely be moved to the
L0 loader and we would like to keep formatting
consistent with current logger format, this means
no "ZE --->" prefix.
=> [test-e2e][L0] do not rely on specific log format

sycl/test-e2e/WorkGroupScratchMemory/copy_dynamic_size.cpp, sycl/test-e2e/WorkGroupScratchMemory/dynamic_unused.cpp
Some devices don't support work group sizes of 1024, so use the maximum
size if it is smaller in the copy_dynamic_size.cpp and dynamic_unused.cpp tests.
=> [SYCL][E2E] Limit work group size in WorkGroupScratchMemory tests

unified-runtime/source/common/CMakeLists.txt
Update UMF to the commit:
```
commit 5a515c56c92be75944c8246535c408cee7711114
Author: Lukasz Dorau <lukasz.dorau@intel.com>
Date:   Mon Feb 17 10:56:05 2025 +0100
Merge pull request #1086 from vinser52/svinogra_l0_linking
```
to fix the issue in LLVM (SYCL/CUDA):
https://github.com/intel/llvm/issues/16944
[SYCL][CUDA] Nsys profiling broken after memory providers change
Moved from: https://github.com/oneapi-src/unified-runtime/pull/2708
Fixes: https://github.com/intel/llvm/issues/16944
=> [SYCL][CUDA] Update UMF in UR to fix issue in LLVM

unified-runtime/source/adapters/level_zero/v2/api.cpp, unified-runtime/source/adapters/level_zero/v2/command_buffer.cpp, unified-runtime/source/adapters/level_zero/v2/command_list_manager.cpp, unified-runtime/source/adapters/level_zero/v2/command_list_manager.hpp, unified-runtime/source/adapters/level_zero/v2/queue_immediate_in_order.cpp
Adds implements calls shared between command buffer and queue in unified-runtime level-zero v2 adapter and moves the shared code to `command_list_manager.cpp`
=> [UR] Add remaining calls shared with queue in level-zero v2 adapter

unified-runtime/source/adapters/opencl/command_buffer.cpp, unified-runtime/source/adapters/opencl/command_buffer.hpp
After the [spec bump of cl_khr_command_buffer to 0.9.7](https://github.com/KhronosGroup/OpenCL-Docs/), in the OpenCL adapter we no longer need to worry about the in-order/out-of-order property of the internal queue used on command-command-buffer creation matching the queue used to enqueue the command-buffer.
We can therefore take advantage of the in-order flag passed on UR command-buffer creation to use an in-order queue for command-buffer creation, and omit using sync points.
**Note:** This UR patch was previously approved and ready-to-merge prior to the UR repo move in https://github.com/oneapi-src/unified-runtime/pull/2681
=> [UR] In-order path for OpenCL command-buffers

unified-runtime/cmake/helpers.cmake
Fixes #16677 by only setting `-pie` linker option in Release builds on executables rather than on any type of target.
=> [UR] Don't set -pie on shared objects

unified-runtime/source/adapters/level_zero/command_buffer.cpp, unified-runtime/source/adapters/level_zero/command_buffer.hpp, unified-runtime/test/conformance/exp_command_buffer/update/local_memory_update.cpp
- Fix group count not being recalculated when a user only passes a new local work size and no new global size
- Remove CTS test skips for local update on L0
=> [UR][L0] Fix issue with command-buffer local mem update

sycl/CMakeLists.txt
When copying the UR headers to `build/include` make sure that the `sycl-headers` target knowns about the dependencies upon the headers in `unified-runtime/include` and make sure that they are copied when changed.
This should hopefully also stop occasional failures in CI:
```
In file included from /__w/llvm/llvm/src/unified-runtime/source/adapters/native_cpu/ur_interface_loader.cpp:11:
/__w/llvm/llvm/build/include/ur_api.h:15: error: unterminated #ifndef
```
=> [SYCL][UR] Improve header copy dependencies

sycl/test-e2e/Regression/multithread_write_accessor.cpp
This test flakily times out on Arc + OpenCL. Disable it for now.
Example:
https://github.com/intel/llvm/actions/runs/13409625069/job/37483063620
https://github.com/intel/llvm/actions/runs/13417907780/job/37485889352
=> [SYCL][E2E] Disable `Regression/multithread_write_accessor.cpp` on Arc + OpenCL

.github/workflows/ur-benchmarks-reusable.yml, .github/workflows/ur-benchmarks.yml, unified-runtime/scripts/benchmarks/benches/oneapi.py, unified-runtime/scripts/benchmarks/main.py, unified-runtime/scripts/benchmarks/options.py, unified-runtime/scripts/benchmarks/requirements.txt
This is a first step towards reenabling UR performance testing CI. This introduces the reusable yml workflow and a way to trigger it manually.
Here's an example how it looks:
https://github.com/pbalcer/llvm/pull/2#issuecomment-2671230460
=> [UR][CI] add manually triggered benchmark action

.github/workflows/sycl-linux-precommit.yml
BMG runner is offline so disabling testing on BMG for now to unblock pre-commit
=> [CI] Temporarily disable BMG in precommit

sycl/test-e2e/ESIMD/Prefix_Local_sum2.cpp, sycl/test-e2e/ESIMD/Prefix_Local_sum3.cpp
They're sporadically failing.
https://github.com/intel/llvm/issues/17075
=> [SYCL][ESIMD][E2E] Disable failing prefix sum tests

unified-runtime/scripts/benchmarks/benches/compute.py
```
running graph_api_benchmark_sycl SinKernelGraph graphs:0, numKernels:5, iteration 0... complete (graph_api_benchmark_sycl SinKernelGraph graphs:0, numKernels:5: 28.533 μs).
running graph_api_benchmark_sycl SinKernelGraph graphs:1, numKernels:5, iteration 0... complete (graph_api_benchmark_sycl SinKernelGraph graphs:1, numKernels:5: 45.884 μs).
running graph_api_benchmark_sycl SinKernelGraph graphs:0, numKernels:100, iteration 0... complete (graph_api_benchmark_sycl SinKernelGraph graphs:0, numKernels:100: 353.814 μs).
running graph_api_benchmark_sycl SinKernelGraph graphs:1, numKernels:100, iteration 0... complete (graph_api_benchmark_sycl SinKernelGraph graphs:1, numKernels:100: 386.979 μs).
running graph_api_benchmark_l0 SinKernelGraph graphs:0, numKernels:5, iteration 0... complete …
```
=> [UR][PERF] add L0, UR, and SYCL Sin Kernel Graph benchmark

unified-runtime/CMakeLists.txt
In standalone UR builds, when the relative xpti/xptifw directories exist, use those instead of using `FetchContentSparse_Declare` helper.
=> [UR] Use relative xpti/xptifw source when available

sycl/test/extensions/DeviceImageBackendContent/negative_test.cpp
Do not include entire `<sycl/sycl.hpp>` in `sycl/test/extensions/DeviceImageBackendContent/negative_test.cpp`
Use more fine-grained includes instead. For E2E tests, this is a matter of performance, but in this case including all the SYCL headers can go as far as causing compilation issues in environments that require `c++20` but whose `gcc` does not fully implement `c++20` features.
=> [SYCL] Do not use entire sycl/sycl.hpp in small tests

unified-runtime/source/adapters/level_zero/command_buffer.cpp
There has been some synchronization issues found in the implementation of `zeCommandListImmediateAppendCommandListsExp`. Since the immediate append path relies on this entrypoint, we need to disable it until the issues are fixed.
=> [UR][L0] Disable command-buffer immediate append path 

sycl/test-e2e/WorkGroupScratchMemory/copy_dynamic_size.cpp, sycl/test-e2e/WorkGroupScratchMemory/dynamic_unused.cpp
The max work group size is a `size_t`, rather than an `unsigned long`.
This trips up older versions of MSVC where `size_t` happens to be
`unsigned long long`.
=> [SYCL][E2E] Use size_t rather than unsigned long in WorkGroupScratchMemory tests

unified-runtime/include/ur_api.h, unified-runtime/scripts/core/device.yml, unified-runtime/scripts/core/exp-bindless-images.yml, unified-runtime/scripts/core/platform.yml, unified-runtime/scripts/core/program.yml, unified-runtime/source/adapters/cuda/device.cpp, unified-runtime/source/adapters/hip/device.cpp, unified-runtime/source/adapters/level_zero/device.cpp, unified-runtime/source/adapters/native_cpu/device.cpp, unified-runtime/source/adapters/opencl/device.cpp, unified-runtime/test/conformance/device/urDeviceGetInfo.cpp, unified-runtime/test/conformance/device/urDevicePartition.cpp, unified-runtime/test/conformance/testing/include/uur/checks.h, unified-runtime/test/conformance/testing/include/uur/fixtures.h, unified-runtime/test/conformance/testing/include/uur/utils.h, unified-runtime/test/conformance/testing/source/utils.cpp
Migrated from https://github.com/oneapi-src/unified-runtime/pull/2597
- Rework urDeviceGetInfoTest to move all enums to their own tests instead of a switch case - https://github.com/oneapi-src/unified-runtime/issues/2290
- Remove the UR/OpenCL Device enum map function - no point maintaining both a switch case and a separate mapping function
- Update some spec wording for consistency
- Add missing Device info enums to OpenCL adapater
- Add new urDevicePartition test for checking UR_DEVICE_INFO_PARENT_DEVICE
- Move UUR_RETURN_ON_FATAL_FAILURE and UUR_ASSERT_SUCCESS_OR_UNSUPPORTED to join similar macros in checks.h
- Update spec to say info queries that return char[] are null-terminated
- Add missing unsupported device enums to HIP adapter
- Reverted bindless image types back to size_t
- …
=> [UR] Improvements to align CTS and Spec for Device

sycl/test-e2e/LLVMIntrinsicLowering/sub_byte_bitreverse.cpp
It's crashing in IGC and potentially contributing to runner instability.
=> [SYCL][E2E] Move crashing sub_byte_bitreverse test to unsupported

unified-runtime/source/adapters/level_zero/CMakeLists.txt
In ['add_ur_library'](https://github.com/intel/llvm/blob/sycl/unified-runtime/cmake/helpers.cmake#L193) we're already setting up proper value (0x2000) for that flag, for all UR libs.
// Moving PR from UR: https://github.com/oneapi-src/unified-runtime/pull/2703
=> [UR] Update dependentloadflag for L0 adapters dlls

libclc/libspirv/lib/generic/math/copysign.cl
This mirrors the OpenCL copysign builtin, and brings benefits in keeping types in vectors as opposed to scalarizing.
=> [libspirv] Have SPIR-V copysign use CLC copysign

libclc/CMakeLists.txt
Upstream commit 15c2d1b fixed dependencies on the generated conversion builtins by automatically identifying targets that produce a generated files. It does so by taking the file name and finding a target with the same name but a prefix 'generate-'.
When this commit was pulled down into DPC++, this was missed and so the target dependencies were incorrect on the (downstream) SPIR-V conversion builtins.
=> [libspirv] Fix target dependency on SPIR-V conversion builtins

devops/scripts/windows_detect_hung_tests.ps1
We just had a unit test hang issue [here](https://github.com/intel/llvm/issues/17168) that broke a ton of PRs, so improve the script to detect that case.
=> [CI] Improve Windows hang detection script for unittests

clang/lib/Driver/Driver.cpp, clang/test/Driver/sycl-offload-old-model.cpp, clang/test/Driver/sycl-target-mismatch.cpp
The use of -l:libname.a was not properly recognizing the library passed in to be considered as an archive that contains SYCL kernels.  Update the parsing behaviors to check for this syntax.
=> [Driver][SYCL] Allow for -l:libname.a to be recognized for SYCL kernels

.github/workflows/sycl-linux-run-tests.yml, devops/actions/run-tests/cts/action.yml
This patch adds a new input to fix the specific version of cts. In general it's needed for sycl-rel as the cts is continuously changing.
=> [CI][CTS] Add fixed ref for cts

unified-runtime/include/ur_api.h, unified-runtime/include/ur_print.hpp, unified-runtime/scripts/core/device.yml, unified-runtime/source/adapters/cuda/device.cpp, unified-runtime/test/conformance/device/urDeviceGetInfo.cpp, unified-runtime/tools/urinfo/urinfo.hpp
Migrated from [PR 2653](https://github.com/oneapi-src/unified-runtime/pull/2653)
=> [UR][CUDA] Change MAX_MEMORY_BANDWIDTH device query to uint64

.github/workflows/sycl-aws.yml, .github/workflows/sycl-containers-igc-dev.yaml, .github/workflows/sycl-containers.yaml, .github/workflows/sycl-linux-precommit-aws.yml, .github/workflows/sycl-stale-issues.yml, .github/workflows/sycl-sync-main.yml, .github/workflows/sycl-update-gpu-driver.yml, .github/workflows/sycl-update-igc-dev-driver.yml
We need to remove 20.04 because of https://github.com/actions/runner-images/issues/11101, so just move everything to latest. 
This has no effect on our self-hosted runners.
Nightly [here](https://github.com/intel/llvm/actions/runs/13525863179).
=> [CI] Actions using GitHub runners should use latest Ubuntu

.github/workflows/sycl-linux-precommit.yml, .github/workflows/sycl-linux-run-tests.yml, .github/workflows/sycl-nightly.yml
The out-of-tree kernel driver for PVC enables a different framebuffer driver that takes the `dri/0` spot, so on those runners `dri/1` is the one with the `i915_wedged` file. 
Just find all folders with `i915_wedged` and reset those.
=> [CI] Re-enable GPU resetting for PVC

sycl/test-e2e/Adapters/level_zero_eager_init.cpp
With ze_debug UR emits summary of leaks that contains ze*Create function names.
=> [SYCL][E2E] Do not run level_zero_eager_init.cpp under ze_debug

sycl/test-e2e/CMakeLists.txt, sycl/test-e2e/lit.cfg.py, sycl/test-e2e/lit.site.cfg.py.in
Based on the output of `clang++ --print-targets`
=> [SYCL][E2E] Add autodetection for build targets

sycl/test-e2e/Assert/lit.local.cfg, sycl/test-e2e/InlineAsm/asm_multiple_instructions.cpp, sycl/test-e2e/InlineAsm/letter_example.cpp, sycl/test-e2e/InlineAsm/malloc_shared_32.cpp
I reproduced the assert tests locking up the whole machine and causing GPU resets, so just disable them all for now. This is probably one of the major causes of the instability.
For some reason `letter_example.cpp` is causing GPU resets on BMG, which is another good candidate as for the runner instability, so just move all XFAILing InlineAsm tests to UNSUPPORTED so they don't run at all on failing platforms.
=> [SYCL][E2E] Disable tests that sporadically fail on BMG 

libclc/libspirv/lib/generic/math/acosh.cl, libclc/libspirv/lib/generic/math/asinh.cl, libclc/libspirv/lib/generic/math/atan.cl, libclc/libspirv/lib/generic/math/atan2.cl, libclc/libspirv/lib/generic/math/cbrt.cl, libclc/libspirv/lib/generic/math/clc_exp10.cl, libclc/libspirv/lib/generic/math/clc_fmod.cl, libclc/libspirv/lib/generic/math/clc_hypot.cl, libclc/libspirv/lib/generic/math/clc_remainder.cl, libclc/libspirv/lib/generic/math/cos.cl, libclc/libspirv/lib/generic/math/cosh.cl, libclc/libspirv/lib/generic/math/erf.cl, libclc/libspirv/lib/generic/math/erfc.cl, libclc/libspirv/lib/generic/math/exp.cl, libclc/libspirv/lib/generic/math/exp2.cl, libclc/libspirv/lib/generic/math/expm1.cl, libclc/libspirv/lib/generic/math/fdim.cl, libclc/libspirv/lib/generic/math/frexp.cl, libclc/libspirv/lib/generic/math/log.cl, libclc/libspirv/lib/generic/math/log10.cl, libclc/libspirv/lib/generic/math/log1p.cl, libclc/libspirv/lib/generic/math/log2.cl, libclc/libspirv/lib/generic/math/logb.cl, libclc/libspirv/lib/generic/math/sin.cl
`__builtin_<name>()` without a suffix is equivalent to the C math function `<name>()`, these functions take and return `double` values.
Instead of using these use the `f16` suffixed builtins which take and return `half` values.
On CPU targets these will be usually lowered to
the single precision library calls (with promotion/truncation). On other targets (for example GPUs) the half builtins might be lowered directly to hardware instructions.
Some of the builtins are not available for half precision, in these cases use the `f` suffixed builtins (which take and return `float`s).
=> [SYCL][LIBCLC] Use half builtins for generic math functions

libclc/clc/include/clc/math/unary_def_with_int_ptr.inc, libclc/clc/include/clc/math/unary_def_with_ptr.inc, libclc/clc/lib/generic/math/clc_frexp.cl
This adds some missing generic address space overloads of CLC functions: frexp, and whichever functions make use of the
unary_def_with_(int_)?ptr.inc files.
Note that this commit doesn't map the equivalent SPIR-V functions to these CLC implementations. This is because the generic SPIR-V implementation of FP16 types currently use the clang builtins as opposed to the software implementations. As discussed in #17163, this is not the proper behaviour for generic implementations, as not all targets support the builtins. In future work we will need to either provide target-specific overrides for the builtin implementations, or provide an easy mechanism by which the CLC implementations can select between builtins or software implementations automatically.
=> [libspirv] Restore overloads of generic address space

llvm/lib/SYCLLowerIR/ESIMD/LowerESIMD.cpp, llvm/lib/SYCLLowerIR/GlobalOffset.cpp
CMPLRLLVM-63532
Deprecated getPointerTo() got replaced with llvm::PointerType::get(LLVMContext)
=> [SYCL] Remove deprecated getPointerTo

sycl/include/sycl/atomic_ref.hpp
This became possible sometime after one/all of
* https://github.com/intel/llvm/pull/15394
* https://github.com/intel/llvm/pull/15543
* https://github.com/intel/llvm/pull/16604
=> [SYCL] Unify SPIR/non-SPIR paths for `atomic_ref` ctor

sycl/include/sycl/accessor.hpp, sycl/source/accessor.cpp, sycl/source/detail/accessor_impl.hpp
Ideally, there should be zero but we can't fix that without ABI break (both present, and potential future one for unanticipated future changes).
Reduce what we can now:
- don't allocate memory on host (no host device, APIs accessing memory must be called from inside "command")
- Use `std::make_shared` to fold two allocation into one for pImpl idiom
=> [SYCL] Reduce heap allocations from `sycl::local_accessor`

sycl/test-e2e/Experimental/launch_queries/max_sub_groups.cpp
This commit adds an XFAIL for FPGA in the
sycl/test-e2e/Experimental/launch_queries/max_sub_groups.cpp as it currently triggers an assert.
See https://github.com/intel/llvm/issues/17209.
=> [SYCL][E2E] XFAIL max_sub_groups test for FPGA

unified-runtime/CMakeLists.txt, unified-runtime/third_party/requirements.txt
The clang-format used as part of the CI jobs and code generation has
been bumped to match the same version used in intel/llvm.
=> [UR] Bump clang-format to 19 to match intel/llvm

unified-runtime/source/adapters/cuda/CMakeLists.txt
`cupti` shouldn't be linked against the adapter, when it is the adapter is unusable if the library is not available, instead of just the tracing being affected.
The code is already setup to dynamically load `cupti` so this can just be removed.
=> [SYCL][CUDA] Fix adapter cupti linking

llvm-spirv/lib/SPIRV/SPIRVReader.cpp, llvm-spirv/lib/SPIRV/SPIRVWriter.cpp, llvm-spirv/lib/SPIRV/libSPIRV/SPIRVModule.cpp, llvm-spirv/lib/SPIRV/libSPIRV/SPIRVModule.h, llvm-spirv/test/extensions/INTEL/SPV_INTEL_joint_matrix/cooperative_matrix_checked.ll, llvm-spirv/test/extensions/INTEL/SPV_INTEL_joint_matrix/cooperative_matrix_prefetch.ll, llvm-spirv/test/extensions/KHR/SPV_KHR_cooperative_matrix/cooperative_matrix.ll
This reverts commit 45da76224aa9878841dcb64942999469687b19f1.
And resolves #17079
The change should be relanded once the OCL CPU RT driver is updated.
=> Revert "Align translation of `OpCooperativeMatrixLengthKHR` to match the spec"

sycl/test-e2e/DeviceLib/built-ins/offload-prec-div-sqrt.cpp
Adding missing `sycl::free` calls to sycl/test-e2e/DeviceLib/built-ins/offload-prec-div-sqrt.cpp.
=> [SYCL] Fix memory leaks.

.github/CODEOWNERS, llvm/lib/Transforms/Instrumentation/ThreadSanitizer.cpp, llvm/test/Instrumentation/ThreadSanitizer/SPIRV/basic.ll, llvm/test/Instrumentation/ThreadSanitizer/SPIRV/extend_launch_info_arg.ll
This PR is going to support thread sanitizer for device offloading (IR part)
1.defined a new class 'ThreadSanitizerOnSpirv' to do SPIR-V specific
instrumentation.
2.added an extra argument '__tsan_launch' to each spir kernels.
3.disable inserting module ctor for kernel code.
4.created a new global '__TsanKernelMetadata' to record spir kernels'
information.
=> [DevTSAN] Support thread sanitizer for device offloading in TSAN pass

buildbot/configure.py
This requires SPIR-V Tools to be installed, which we did on all the self hosted Windows runners and it's in the docker for the Linux ones.
This flag was somewhat recently added, and before that it used SPIR-V tools automatically if it could find it, so this _might_ also be returning us to old behavior.
Either way, let's enable it if `--ci-defaults` is passed, some tests could rely on this in the future.
=> [CI] Build llvm-spirv with spirv-dis support

sycl/include/sycl/ext/oneapi/bfloat16.hpp, sycl/include/sycl/ext/oneapi/experimental/bfloat16_math.hpp
bfloat16.hpp defines two help functions to cast between 16-bit integer and bfloat16 types. These fucntions duplicate logic of sycl::bit_cast standard function.
=> [NFC][SYCL] Use bit_cast for bfloat16 casts.

sycl/test-e2e/USM/memops2d/copy2d_dhost_to_shared.cpp, sycl/test-e2e/USM/memops2d/copy2d_host_to_shared.cpp, sycl/test-e2e/USM/memops2d/copy2d_shared_to_dhost.cpp, sycl/test-e2e/USM/memops2d/copy2d_shared_to_host.cpp, sycl/test-e2e/USM/memops2d/memcpy2d_dhost_to_shared.cpp, sycl/test-e2e/USM/memops2d/memcpy2d_host_to_shared.cpp, sycl/test-e2e/USM/memops2d/memcpy2d_shared_to_dhost.cpp, sycl/test-e2e/USM/memops2d/memcpy2d_shared_to_host.cpp, sycl/test-e2e/USM/usm_pooling.cpp
These are all working now on DG2 and should be reenabled.
https://github.com/intel/llvm/issues/16568
https://github.com/intel/llvm/issues/15648
=> [SYCL] reenabling USM tests on DG2

libclc/generic/lib/math/log2.cl
This was a mistaken resolution of f8948d3c4754e06cdd3e2903bfbfe74438f6b463, which removed the builtin from the OpenCL layer.
=> [libspirv] Fix missing OpenCL log2 builtin

libclc/libspirv/lib/generic/math/ldexp.cl
This header was moved in d5038b3774485d617e1300cf2f7b98c2460b9042 but wasn't spotted when pulling down.
=> [libspirv] Fix missing header in ldexp.cl

libclc/CMakeLists.txt
Upstream, this warning was moved from being universal to applying only to the OpenCL builtins. A pulldown thus also disabled it from libspirv. Until the warnings in libspirv are fixed, we should keep disabling the warning there to avoid needlessly noisy builds.
=> [libspirv] Disable bitwise-conditional-parentheses warning

.github/workflows/ur-build-hw.yml, unified-runtime/cmake/FetchLevelZero.cmake, unified-runtime/source/adapters/level_zero/CMakeLists.txt, unified-runtime/source/adapters/level_zero/adapter.cpp, unified-runtime/source/adapters/level_zero/platform.cpp, unified-runtime/test/adapters/level_zero/urKernelCreateWithNativeHandle.cpp, unified-runtime/test/adapters/level_zero/v2/command_list_cache_test.cpp, unified-runtime/test/adapters/level_zero/v2/deferred_kernel.cpp, unified-runtime/test/adapters/level_zero/v2/event_pool_test.cpp
Migrated from https://github.com/oneapi-src/unified-runtime/pull/2667
=> [UR] [L0] Update UR to link the Loader as static

unified-runtime/source/adapters/level_zero/v2/command_list_cache.cpp, unified-runtime/source/adapters/level_zero/v2/queue_immediate_in_order.cpp
Fixes issues with v2 level zero adapter in UR command buffer implementation, that resulted in failure of some tests in sycl/test-e2e/Graph/RecordReplay when using level zero adapter v2
=> [SYCL] [UR] Fix issues that cause graph tests to fail

sycl/test-e2e/E2EExpr.py
This should be a build-specific feature. We use it to decide whether we should build tests like [`Regression/msvc_crt.cpp`](https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/Regression/msvc_crt.cpp).
=> [SYCL][E2E] Add `cl_options` to build features list

sycl/test-e2e/Adapters/level_zero_sub_sub_device.cpp, sycl/test-e2e/ESIMD/srnd.cpp
We don't actually run these on windows, but if we enable `build-only` these will build.
=> [SYCL][E2E] Fix compilation of 2 PVC tests on windows

unified-runtime/scripts/benchmarks/benches/compute.py, unified-runtime/scripts/benchmarks/benches/llamacpp.py, unified-runtime/scripts/benchmarks/benches/syclbench.py, unified-runtime/scripts/benchmarks/benches/velocity.py, unified-runtime/scripts/benchmarks/main.py
Enable benchmarking sycl for cuda adapter through VelocityBench and SyclBench in benchmarking scripts.
=> [SYCL][BENCHMARK] Enable velocityBench and SyclBench for cuda adapter

sycl/test-e2e/Basic/image/image_array.cpp
Fix issue https://github.com/intel/llvm/issues/15398 by adding group barriers between write and read statements. Also revised the parameters of the second write-read test case (from `42, 42` to `53, 55`) to prevent failures from it been covered by success of the first write-read test case.
=> [SYCL] Fix image_array.cpp on GPU

sycl/include/sycl/detail/generic_type_traits.hpp, sycl/include/sycl/ext/oneapi/bfloat16.hpp, sycl/include/sycl/vector.hpp, sycl/test/check_device_code/vector/vector_math_ops.cpp, sycl/test/check_device_code/vector/vector_math_ops_preview.cpp
This change makes a few changes aiming to make the code more readable.
* Move declaration of the bfloat16 class right on top of the header file
and move all declarations with the implementation helpers after the
class declaration.
* Converted ConvertToBfloat16 class to namespace. The class doesn't
represent any object, it's a collection of static methods.
* Declare public API of the class first.
* Move Bfloat16StorageT declaration from the detail namespace directly
into bfloat16 class definition.
* Co-locate declaration of functions with similar functionality (e.g.
conversion functions).
* Simplified uniry operator- implementation by removing additional
branch for the SPIR target. Generic code for SPIR target produces
exactly the same code.
* Added compile time checks for the array size …
=> [SYCL][bfloat16] Simplify bfloat16 class

unified-runtime/test/adapters/cuda/context_tests.cpp, unified-runtime/test/adapters/cuda/memory_tests.cpp, unified-runtime/test/conformance/enqueue/helpers.h, unified-runtime/test/conformance/enqueue/urEnqueueKernelLaunch.cpp, unified-runtime/test/conformance/enqueue/urEnqueueKernelLaunchAndMemcpyInOrder.cpp
Also removes a test and adds known failures where appropriate (typically where the test only runs when multiple devices are available so the skip doesn't affect behaviour of single-device runs).
The test removed is `cudaUrContextCreateTest.ActiveContext`. This test seems to be testing the assumption that a `urQueueCreate` followed by `urMemBufferCreate` will set the active cuda context to the one associated with the context passed to those calls. Neither of these calls set the active context, this may have changed at some point as the test dates back to a PI unit test. The test currently passes as long as only one device is available because a previous `urDeviceGetInfo` sets the active context to the one associated with that device, which is inevitably the same as the one associated with …
=> [UR] Fix some tests that are broken when run with multiple cuda devices available.

unified-runtime/source/adapters/cuda/CMakeLists.txt, unified-runtime/source/adapters/cuda/tracing.cpp
This patch fixes loading the cupti library on Linux to rely on the dynamic linker to figure out where the library is.
It also disable cupti tracing on Windows, as far as I know this is only used on Linux at the moment since the tracing tools don't support Windows. Additionally there are some potential security issues of loading the library just by name on Windows, so we just leave Windows support out for now.
This is following up on the discussions on https://github.com/oneapi-src/unified-runtime/pull/1070, statically linking the cupti library was also ruled out as it makes the adapter library go from around 600KiB to around 32MiB.
=> [SYCL][CUDA] Fix cupti library dynamic loading

sycl/cmake/modules/FetchUnifiedRuntime.cmake, unified-runtime/CMakeLists.txt, unified-runtime/cmake/helpers.cmake
The `UR_EXTERNAL_DEPENDENCIES` option can be used to specify a list of CMake targets that all libraries and executables in the UR build should depend on, e.g. the `sycl-headers` target.
Following on from https://github.com/intel/llvm/pull/17093
=> [UR] Add UR_EXTERNAL_DEPENDENCIES CMake option

.github/workflows/sycl-windows-run-tests.yml
Fixes this warning
```
D:\github\_work\llvm\llvm\build-e2e\lit.site.cfg.py:22: SyntaxWarning: invalid escape sequence '\g'
config.level_zero_libs_dir = "D:\github\level-zero_win-sdk\lib"
D:\github\_work\llvm\llvm\build-e2e\lit.site.cfg.py:23: SyntaxWarning: invalid escape sequence '\g'
config.level_zero_include = "D:\github\level-zero_win-sdk\include"
```
Tests using the L0 SDK such as `SYCL :: Adapters/interop-level-zero.cpp` passed, so it seems this didn't break anything.
=> [CI] Fix lit warning from L0 SDK path

llvm/include/llvm/SYCLLowerIR/ComputeModuleRuntimeInfo.h, llvm/lib/SYCLLowerIR/ComputeModuleRuntimeInfo.cpp, llvm/lib/SYCLLowerIR/SanitizerKernelMetadata.cpp, llvm/test/tools/sycl-post-link/device-sanitizer/tsan.ll, llvm/tools/sycl-post-link/sycl-post-link.cpp
This PR is going to support thread sanitizer for device offloading (sycl-tool-chain part)
1.defined a new helper function 'isModuleUsingTsan'
2.fix attribute for '__TsanKernelMetadata'
=> [DevTSAN] Support thread sanitizer for device offloading in sycl-tool-chain

unified-runtime/source/common/ur_singleton.hpp, unified-runtime/test/conformance/device/urDevicePartition.cpp, unified-runtime/test/conformance/testing/source/fixtures.cpp
- Don't use iterators that may be at the end
- Use references for param tuples
- Avoid integer overflow
=> [UR] Fix various defects from static analysis

sycl/test-e2e/EnqueueNativeCommand/custom-command-hip.cpp, sycl/test-e2e/HostInteropTask/interop-task-hip.cpp, sycl/test-e2e/lit.cfg.py
`ROCM_PATH` and the `%rocm_path` substitutions need to be set for compilation.
The `FIXME` in these tests dates from where the ROCm path was hardcoded, it should've been removed when the substitutions were introduced, so removing it now.
Fixes: https://github.com/intel/llvm/issues/17018
=> [SYCL][E2E] Fix lit ROCM_PATH setup for build-only

clang/lib/CodeGen/CGDebugInfo.cpp, llvm/include/llvm/IR/DIBuilder.h, llvm/lib/IR/DIBuilder.cpp, llvm/lib/IR/DebugInfo.cpp, llvm/lib/SYCLNativeCPUUtils/CMakeLists.txt, llvm/lib/Transforms/Coroutines/CoroFrame.cpp, llvm/lib/Transforms/Scalar/SROA.cpp, llvm/lib/Transforms/Utils/Debugify.cpp, llvm/lib/Transforms/Utils/Local.cpp, llvm/lib/Transforms/Utils/PromoteMemoryToRegister.cpp, llvm/unittests/IR/IRBuilderTest.cpp, llvm/unittests/Transforms/Utils/CloningTest.cpp
This restores the build of NativeCPU with oneAPI Construction Kit after the latest LLVM pulldown.
[reland][DebugInfo] Update DIBuilder insertion to take InsertPosition (#126967)
After #124287 updated several functions to return iterators rather than
Instruction *, it was no longer straightforward to pass their result to
DIBuilder. This commit updates DIBuilder methods to accept an
InsertPosition instead, so that they can be called with an iterator
(preferred), or with a deprecation warning an Instruction *, or a
BasicBlock *. This commit also updates the existing calls to the
DIBuilder methods to pass in iterators.
As a special exception, DIBuilder::insertDeclare() keeps a separate
overload accepting a BasicBlock *InsertAtEnd. This is because despite
the name, this method does not insert …
=> [SYCL][NativeCPU] Update OCK and cherry-pick compatibility fix.

sycl/test-e2e/Regression/multithread_write_accessor.cpp
Test is [failing](https://github.com/intel/llvm/issues/16877) for a ton of people and I don't want anyone to have to deal with it until it's fixed.
=> [SYCL][E2E] Disable flaky test multithread_write_accessor.cpp

sycl/test-e2e/USM/memops2d/lit.local.cfg
Still sporadically failing on Windows, see [here](https://github.com/intel/llvm/issues/8126).
=> [SYCL][E2E] Disable memops2d tests on Windows again

.github/workflows/sycl-linux-precommit-aws.yml, .github/workflows/sycl-linux-precommit.yml, .github/workflows/sycl-linux-run-tests.yml, .github/workflows/sycl-nightly.yml, .github/workflows/sycl-post-commit.yml, .github/workflows/sycl-rel-nightly.yml, .github/workflows/sycl-weekly.yml
As discussed in https://github.com/intel/llvm/pull/17074, renamed ref to repo_ref.
=> [CI][NFC] Renamed `ref` to `repo_ref` in sycl-linux-run-tests.yml

.github/workflows/sycl-post-commit.yml
We test differently in pre and postcommit, and we need to also test driver updates in postcommit to ensure there are no failures.
=> [CI] Run postcommit when GPU driver changes

sycl/test-e2e/AOT/early_aot.cpp, sycl/test-e2e/ProgramManager/uneven_kernel_split.cpp, sycl/test-e2e/SpecConstants/2020/image_selection.cpp
Failing in more cases in the nightly
https://github.com/intel/llvm/actions/runs/13667656648
=> [SYCL][E2E] Disable AOT tests on more platforms

llvm/tools/llvm-foreach/llvm-foreach.cpp
This resolves https://github.com/intel/llvm/issues/15177
Currently, we have a 'while' loop that keeps checking for child processes to complete. This causes llvm-foreach to run and consume resources when its child processes are active.
Instead, we can use blocking waits to wait for child processes. During blocking waits. parent process is idle and does not consume resources.
I tested this on a fairly large program compilation (with AOT) and it seems to work as expected.
No new tests are needed.
Thanks
=> [llvm-foreach] Avoid running llvm-foreach when waiting for child processes

clang/lib/Sema/SemaSYCL.cpp, clang/test/SemaSYCL/accessor-type-diagnostics.cpp, clang/test/SemaSYCL/deferred-diagnostics-emit.cpp, clang/test/SemaSYCL/int128.cpp
The patch makes querries to the TargetInfo to determine if builtin types are supported on the device side.
=> [SYCL] Account for target when checking types

llvm/lib/SYCLLowerIR/ESIMD/LowerESIMD.cpp, llvm/test/SYCLLowerIR/ESIMD/lower_llvm_intrin.ll, sycl/include/sycl/ext/intel/esimd/detail/intrin.hpp, sycl/include/sycl/ext/intel/esimd/detail/math_intrin.hpp, sycl/include/sycl/ext/intel/esimd/detail/memory_intrin.hpp, sycl/include/sycl/ext/intel/esimd/math.hpp, sycl/include/sycl/ext/intel/experimental/esimd/detail/math_intrin.hpp, sycl/include/sycl/ext/intel/experimental/esimd/detail/memory_intrin.hpp, sycl/include/sycl/ext/intel/experimental/esimd/math.hpp, sycl/test/check_device_code/esimd/rsqrt_double.cpp
These require a new driver driver than the minimum supported version by customers, so we need to revert.
=> [SYCL][ESIMD] Revert some SPIR-V intrinsic changes

.github/workflows/email-check.yaml
https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request
> By default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened.
By adding `types: - opened`, we are restricting this workflow to run only when the PR is first opened. I don't see a good reason to do that. This PR removed it and also makes sure that this workflow is triggered only on certain branches.
=> [CI] Fix workflow to check use of private emails

clang/lib/CodeGen/CGBuiltin.cpp, clang/test/CodeGen/fp-accuracy.c
This patch resolves conflicts introduced by:
cd269fee05a0 - (2024-12-14) [StrTable] Switch Clang builtins to use string tables - Chandler Carruth
=> [SYCL] Fix FP accuracy regressions

sycl/test-e2e/KernelCompiler/kernel_compiler_sycl.cpp, sycl/test-e2e/KernelCompiler/kernel_compiler_sycl_jit.cpp, sycl/test-e2e/KernelCompiler/kernel_compiler_sycl_jit_cache.cpp
The debug story for sycl-jit is not determined yet, so supporting the `-g` flag for the kernel_compiler is not a strict requirement. 
Meanwhile, on the SPIR-V side we are changing some opcodes to be extensions.  This upshot of all that is that between the open source and closed source side, drivers and code gen, the -g flag, *when passed to the kernel_compiler*, is leading to errors. This will resolve itself once both the open source and closed source sides of the compiler, and the matching drivers, have all made the switch to the same SPIRV symbols. In the meantime, these tests are being adjusted so they pass in all contexts.
=> [SYCL][E2E] minor test change to ease release

sycl/test-e2e/bindless_images/sampling_2D.cpp
This test has been failing flakily on HIP.
Example: https://github.com/intel/llvm/actions/runs/13632741740/job/38160479157
=> [E2E] Disable flaky `bindless_images/sampling_2D.cpp` on HIP

sycl/test-e2e/Graph/RecordReplay/lit.local.cfg, sycl/test-e2e/Graph/Update/lit.local.cfg, sycl/test-e2e/Graph/lit.local.cfg
We currently only disable the RecordReplay variant of E2E testing on battlemage, however we have many other tests and the likihood is that if the RecordReplay tests are failing then other tests will start failing too.
Disable all Graphs tests until Graph support on Windows battlemage can be investigated more thoroughly.
See https://github.com/intel/llvm/issues/17165
=> [SYCL][Graph] Disable all Graph E2E testing on Windows Battlemage

sycl/test/syclcompat/launch/launch_policy_neg.cpp
=> [SYCL] Disable launch_policy_neg.cpp on Windows

llvm/lib/SYCLLowerIR/SYCLJointMatrixTransform.cpp
Fix use of uninitialized memory ASAN report.
=> [NFC][SYCL] Fix constant propagation for matrix layout

unified-runtime/third_party/requirements.txt
Unified-runtime is formatted using black, so include it in the Python
environment. `packaging` was also bumped since it is a dependency.
This does not make any changes to CI or cmake.
=> [UR] Install `black` in requirements.txt

sycl/CMakeLists.txt
Without this patch the header wasn't getting re-generated when the `.def` files are changed, which causes build failures on existing builds when new aspects are introduced.
=> [SYCL] Fix device aspect macro header CMake dependency

sycl/test-e2e/WorkGroupScratchMemory/copy_dynamic_size.cpp
I don't know what fixed it, but this is fixed on the `sycl` branch and in the latest nightlies.
Fixes https://github.com/intel/llvm/issues/16968
=> [SYCL][E2E] Re-enable copy_dynamic_size on CUDA

devops/actions/cached_checkout/action.yml
Without this cached checkout is slow.
Note this is only when we re-create the cache, which only happens if it got deleted/doesn't exist for some reason.
=> [CI] Run `git gc` when creating a repo cache

sycl-jit/common/include/Kernel.h, sycl-jit/jit-compiler/lib/KernelFusion.cpp, sycl-jit/jit-compiler/lib/rtc/DeviceCompilation.cpp, sycl-jit/jit-compiler/lib/rtc/DeviceCompilation.h, sycl/source/detail/jit_compiler.cpp, sycl/source/detail/jit_compiler.hpp, sycl/source/detail/jit_device_binaries.cpp, sycl/source/detail/jit_device_binaries.hpp, sycl/test-e2e/KernelCompiler/sycl_device_flags.cpp
Ensures that `-Xs` option arguments are baked into the device image(s), from which they are picked up by the progam manager.
=> [SYCL][RTC] Propagate `-Xs` options along in-memory pipeline

.github/workflows/sycl-windows-build.yml
The new Windows runner is a NUMA system with 2 CPUs, and for whatever reason `lit` seems to only detect the non-hyperthreaded cores on one of the CPUs, so just explicitly set it.
=> [CI] Explicitly set number of jobs for lit on Windows

sycl/source/detail/kernel_bundle_impl.hpp, sycl/test-e2e/KernelCompiler/kernel_compiler_basic.cpp, sycl/test-e2e/KernelCompiler/kernel_compiler_context_error.cpp, sycl/test/e2e_test_requirements/no_sycl_hpp_in_e2e_tests.cpp
Detect error scenarios in `sycl::ext::oneapi::build` and throw the errors specified in the extension.
This handles two scenarios:
- Calling build where one of the devices given in the list does not support the source language of the bundle.
- Calling build where one of the devices given in the list does not belong to the context of the source bundle.
=> [SYCL][RTC] Implement specified error behavior

.github/workflows/coverity.yml
We are not interested in project/binaries/libraries which are not a part of the `sycl-toolchain` target - they are already being scanned by the upstream LLVM.
=> [SYCL][CI] Reduce scope of Coverity scan

sycl/test-e2e/Graph/ValidUsage/linear_graph_copy_D2H.cpp
Following https://github.com/intel/llvm/pull/16830, this PR adds an additional e2e graph test to invoke copy engine on L0 devices and test its behaviour.
=> [SYCL][Graph[E2E] Add an extra test to invoke copy engine on L0

.github/workflows/sycl-linux-build.yml
We don't need to build default `all` target, `sycl-toolchain` is enough for us.
=> [SYCL][CI] Limit the scope of Linux pre-commit build

unified-runtime/include/ur_api.h, unified-runtime/scripts/core/context.yml, unified-runtime/scripts/core/device.yml, unified-runtime/source/adapters/opencl/device.cpp, unified-runtime/source/loader/ur_libapi.cpp, unified-runtime/source/ur_api.cpp, unified-runtime/test/conformance/device/urDeviceGetGlobalTimestamps.cpp, unified-runtime/test/conformance/enqueue/urEnqueueUSMFill2D.cpp
Similar to urContextSetExtendedDeleter this entry point isn't supported
by devices that report a CL version < 2.1. We aren't going to support
versions this old forever, so it's simplest to just allow the
UNSUPPORTED_FEATURE return for now.
Also cleans up some weird api usage I noticed in a fixture along the
way.
Fixes https://github.com/oneapi-src/unified-runtime/issues/2633
=> [UR] Add UNSUPPORTED_FEATURE return for urDeviceGetGlobalTimestamps

sycl/test/basic_tests/header_footer_diagnostics.cpp, sycl/test/basic_tests/is_group_trait.cpp, sycl/test/esimd/slm_init_local_accessor.cpp
This occasionally causes errors on windows when multiple files compile to the same output file.
See #7872 for more context
=> [SYCL][NFC] Use no output file instead of default output file in LIT tests

sycl/test-e2e/DeviceLib/assert-windows.cpp
This test was xfailed because previously we would ignore features in `build-only` mode so it would be incorrectly ran on Linux, despite the Windows requirement. This was fixed in #16725.
Fixes #16507
=> [SYCL][E2E] Remove XFAIL from `DeviceLib/assert-windows.cpp` test

llvm/lib/Transforms/Scalar/FPBuiltinFnSelection.cpp, llvm/test/Transforms/FPBuiltinFnSelection/Generic/fp-builtin-intrinsics-preserve-fpmath.ll
FPBuiltinFnSelection pass is modified to create fpmath metadata during replacement of
llvm.fpbuiltin.* intrinsics with native LLVM instructions or LLVM std intrinsics.
=> [SYCL] Preserve fpbuiltin-max-error information in fpmath metadata

sycl/source/handler.cpp
This is shortcut path for Kernel CG only. 
It handles only device kernels that means that there is no necessity to check if event is a host event.
I also do not see necessity to check if Handle != nullptr since there is a separated path for discarded event case. That means that in path for kernel + no discarding events this check is not necessary at all.
=> [SYCL] Remove redundant check if Kernel is on host

.github/workflows/ur-benchmarks-reusable.yml
On PRs based on main, the scripts location is "old" and not accesible. Temporarily allow both locations. If pip installation fail we'll know it in next steps. Step 'gather info' is a nice-to-have anyway.
E.g. failure:
https://github.com/intel/llvm/actions/runs/13787698847/job/38559543731#step:6:6
=> [CI] Allow 2 bench scripts locations

buildbot/configure.py, sycl/doc/GetStartedGuide.md, sycl/doc/design/SYCLNativeCPU.md
Hundreds of `--cmake-opt=-DFOO=BAR` on the command line make it hard to see the wood for the trees, so introduce an alternative which is to simply pass unknown argument flags straight through to cmake. This should make using the wrapper a little more pleasant and readable.
=> Enable cmake argument passthrough in the SYCL configure wrapper

.github/workflows/sycl-linux-precommit.yml
There's recurring instabilities on the AMD pre-commit runs, everytime they fail two things will happen:
* 1 or more test will fail with a memory access fault
* 1 or more test will hang and end up timing out
This seemingly only happens when running the pre-built E2E tests in parallel.
It is quite difficult to debug and could potentially be an issue in the AMD drivers.
So as a workaround until we can figure out what's going on, this patch switches the AMD E2E prebuit tests to run in a single thread.
This is obviously slower than running the tests in parallel, but because the instability causes hangs that end up hitting the 10 minutes timeout, a one thread run is faster than a failing multi-thread run. So we get consistent runs that are slower but may actually end up going through the job …
=> [CI] Limit AMD E2E tests to 1 thread

sycl/test-e2e/Basic/event_profiling_info.cpp
Already a GH issue, seems to fail on many configurations.
=> [SYCL][E2E] Disable flaky test event_profiling_info.cpp

sycl/unittests/Extensions/CommandGraph/CMakeLists.txt, sycl/unittests/Extensions/CommandGraph/Regressions.cpp
- Re-enable command graph extension tests
- Fix test that could incorrectly let buffers be destroyed before the command_graph they were used in
Resolves #17168
=> [SYCL][Graph] Fix issue with unit tests hanging

unified-runtime/.gitattributes
This patch extends the `.gitattributes` file to mark all generated source files with the `linguist-generated=true` attribute. This results in PR diffs to not display changes to these files by default to avoid distracting reviewers. The diffs can still be expanded by users who wish to review their content.
=> [UR] Generated code hidden by default in PR diffs

unified-runtime/scripts/benchmarks/utils/utils.py
Previously, the default value for `timeout` was bound at function definition time using `options.timeout`, which become outdated if `options.timeout` changes later. This commit changes the default value to `None` and assigns the current `options.timeout` inside the function, ensuring that the latest value is used when no explicit timeout is provided.
=> [BENCHMARK] fix default timeout parameter

sycl/source/CMakeLists.txt
Enable frame pointers on sycl runtimes when the build configuration is
Debug or RelWithDebInfo. (Though setting this will typically be a no-op
for Debug builds.)
Frame pointers improve the effectiveness of profilers, tracers, and
other introspection tools.
=> [SYCL][CMake] Build RelWithDebInfo sycl runtimes with frame pointers

llvm/lib/SYCLLowerIR/ModuleSplitter.cpp, sycl/test/warnings/undefined_functions.cpp
In the following simple example (simplicity for sake of discussion),
```c++
#include <sycl/sycl.hpp>
SYCL_EXTERNAL int external_f1(int A, int B);
void hostf(...) {
...
cgh.parallel_for<class Test>(range, [=](sycl::id<1> ID) {
accC[ID] = external_f1(accA[ID], accB[ID]);
});
});
}
```
"external_f1" is a user function which is not defined in this module. Linking this module stand-alone will successfully create an executable. During run-time. there will be a run-time error saying that there is an unresolved symbol. This PR addresses a user request to alert the user of this behavior during compile-time by emitting a warning message.
Thanks
=> [sycl-post-link] Emit helpful warning message for undefined user functions in a fully linked device image

.github/workflows/sycl-linux-precommit.yml, .github/workflows/sycl-linux-run-tests.yml, .github/workflows/sycl-nightly.yml, sycl/test-e2e/KernelAndProgram/persistent-cache-multi-device.cpp, sycl/test-e2e/ProgramManager/multi_device_bundle/build_twice.cpp, sycl/test-e2e/ProgramManager/multi_device_bundle/device_libs_and_caching.cpp
I talked to the KMD team and they recommended doing it this way for the `xe` module.
Maybe this will improve stability.
I hardcoded the PCI ID but we only have one Linux BMG runner so it should be fine for now.
Confirmed this works by checking the dmesg log of the runner.
=> [CI] Add GPU reset for BMG

.github/workflows/ur-benchmarks-reusable.yml, devops/scripts/benchmarks/benches/compute.py
=> Bump compute bench

unified-runtime/source/loader/layers/sanitizer/sanitizer_common/linux/backtrace.cpp
`backtrace()` would return buffers with return addresses, which is one instruction past the call. If that instruction belongs to other source lines, then the llvm-symbolizer would give out wrong result.
Test will be added internally. It is hard to write test for this using SYCL as SYCL does not generate code with that pattern.
=> [DeviceSanitizers] Adjust backtrace addresses to call instruction

sycl/doc/extensions/experimental/sycl_ext_oneapi_kernel_compiler.asciidoc
The description of the `build` shorthand uses `ctxt`, despite there being no such argument associated. This commit fixes this by using the devices from the `sourceBundle` argument.
=> [SYCL][Docs] Correctly use sourceBundle in build shorthand description

unified-runtime/cmake/helpers.cmake, unified-runtime/test/conformance/enqueue/urEnqueueEventsWaitMultiDevice.cpp
Also remove a cfi exclusive KNOWN_FAILURE as it couldn't be reproduced across a few platforms.
closes https://github.com/oneapi-src/unified-runtime/issues/2647
=> [UR] Fix typo in cfi flags handling.

clang/lib/Sema/SemaDeclAttr.cpp, clang/test/SemaSYCL/float128.cpp
Cherry-pick of: https://github.com/llvm/llvm-project/pull/128513
Fixes: https://github.com/intel/llvm/issues/16903
------
This diagnostic is disabled for device compilation as float128 is not supported on the device side.
Other diagnostics are already covering the cases where float128 is actually used in the kernel code, and it's already tested for in the existing test.
This is expanding on the patch 318bff6 that handled this for cuda compilation.
=> [clang][SYCL] Disable float128 device mode diagnostic (#128513)

.github/workflows/sycl-detect-changes.yml, .github/workflows/ur-build-hw.yml
Latest distros don't allow global pip installations.
=> [UR][CI] Install python deps in venv

unified-runtime/source/adapters/level_zero/CMakeLists.txt, unified-runtime/source/adapters/level_zero/v2/command_buffer.cpp, unified-runtime/source/adapters/level_zero/v2/command_buffer.hpp, unified-runtime/source/adapters/level_zero/v2/command_list_manager.cpp, unified-runtime/source/adapters/level_zero/v2/command_list_manager.hpp, unified-runtime/source/adapters/level_zero/v2/lockable.hpp, unified-runtime/source/adapters/level_zero/v2/queue_immediate_in_order.cpp, unified-runtime/source/adapters/level_zero/v2/queue_immediate_in_order.hpp
Changes:
Command_list_manager no longer synchronize its calls, instead the responsibility to ensure exclusivity belongs to the caller.
To add synchronization I implemented the mechanism similar to rust lock as suggested in https://github.com/intel/llvm/pull/17061#discussion_r1963023035.
=> [UR] [V2] Fix synchronization between command_list_manager usages

unified-runtime/cmake/FetchLevelZero.cmake
Caller might set CMAKE_MSVC_RUNTIME_LIBRARY to MultiThreaded to do
static linking of MSVC runtime. However, UMF is not yet ready for static
linking. Override the CMAKE_MSVC_RUNTIME_LIBRARY to fix lnking failures.
=> [UR][CMake]Set CMAKE_MSVC_RUNTIME_LIBRARY to fix UMF linking issues

sycl/test-e2e/Regression/static-buffer-dtor.cpp, unified-runtime/source/common/CMakeLists.txt
Bump UMF to v0.11.0-dev4.
From now on disjoint_pool is part of libumf,
instead of being a separate library.
=> [UR] Bump UMF to v0.11.0-dev4

unified-runtime/source/adapters/level_zero/v2/command_buffer.cpp
`urCommandBufferEnqueueExp` was changed in https://github.com/intel/llvm/pull/16984 to `urEnqueueCommandBufferExp` but added back accidentally to the v2 L0 adapter in https://github.com/intel/llvm/pull/17297
=> [UR][NFC] Remove unused function from v2 adapter

sycl/include/sycl/detail/vector_arith.hpp
The type of (ext_vector<int8_t, 2>{1, 0} == 0)[1] has type char, not int8_t, and therefore depending on whether -funsigned-char is in effect may either have the value -1 or have the value 255. Cast to int8_t to ensure it always gets taken as signed. This is only needed for the static_assert: the rest of the code already works for signed and unsigned plain char alike.
=> [SYCL] Fix static_assert with -funsigned-char

libdevice/fallback-cmath.cpp
For input '-0', __spirv_ocl_sin returns +0 for float and returns -0 for double, MSVC complex math implementation does depend on this, discarding the signbit for sin(-0) will lead to some corner case failures in exp(std::complex<float>) e2e tests. This patch is a workaround for the issue.
=> [SYCL][libdevice] Keep sign bit of result for std::sin(-0)

unified-runtime/include/ur_api.h, unified-runtime/include/ur_print.hpp, unified-runtime/scripts/YaML.md, unified-runtime/scripts/core/PROG.rst, unified-runtime/scripts/core/device.yml, unified-runtime/scripts/templates/helper.py, unified-runtime/scripts/templates/print.hpp.mako, unified-runtime/scripts/templates/stype_map_helpers.hpp.mako, unified-runtime/scripts/templates/tools-info.hpp.mako, unified-runtime/source/adapters/cuda/device.cpp, unified-runtime/source/adapters/hip/device.cpp, unified-runtime/source/adapters/level_zero/device.cpp, unified-runtime/source/adapters/native_cpu/device.cpp, unified-runtime/source/adapters/opencl/device.cpp, unified-runtime/test/conformance/device/urDeviceGetInfo.cpp, unified-runtime/test/conformance/testing/include/uur/utils.h, unified-runtime/test/conformance/testing/source/utils.cpp, unified-runtime/tools/urinfo/urinfo.hpp
* Add support for deprecation of enum values in UR spec.
* Deprecate UR_DEVICE_INFO_BFLOAT16.
* Remove testing for UR_DEVICE_INFO_BFLOAT16.
* Remove UR_DEVICE_INFO_BFLOAT16 support from adapters.
* Resolves https://github.com/oneapi-src/unified-runtime/issues/2385.
=> [UR] Deprecate UR_DEVICE_INFO_BFLOAT16

sycl/include/sycl/accessor.hpp, sycl/include/sycl/accessor_image.hpp, sycl/include/sycl/context.hpp, sycl/include/sycl/detail/impl_utils.hpp, sycl/include/sycl/device.hpp, sycl/include/sycl/event.hpp, sycl/include/sycl/ext/oneapi/backend/level_zero.hpp, sycl/include/sycl/ext/oneapi/experimental/graph.hpp, sycl/include/sycl/ext/oneapi/virtual_mem/physical_mem.hpp, sycl/include/sycl/handler.hpp, sycl/include/sycl/image.hpp, sycl/include/sycl/kernel.hpp, sycl/include/sycl/kernel_bundle.hpp, sycl/include/sycl/platform.hpp, sycl/include/sycl/queue.hpp, sycl/source/context.cpp, sycl/source/detail/kernel_bundle_impl.hpp, sycl/source/detail/program_manager/program_manager.cpp, sycl/source/detail/program_manager/program_manager.hpp, sycl/source/detail/queue_impl.cpp, sycl/source/detail/queue_impl.hpp, sycl/source/detail/scheduler/commands.cpp, sycl/source/event.cpp, sycl/source/handler.cpp, sycl/source/kernel_bundle.cpp
This PR tries to decrease the number of times the copy ctor of `std::shared_ptr` is called.
Before this PR the `createSyclObjFromImpl` function took `std::shared_ptr` as an argument by value.
=> [SYCL] Optimize createSyclObjFromImpl usage

sycl/source/detail/sampler_impl.cpp, sycl/source/detail/sampler_impl.hpp, sycl/source/detail/scheduler/commands.cpp, sycl/source/detail/scheduler/commands.hpp, sycl/source/sampler.cpp
Update `sampler_impl` to use `context_impl` instead of `context`.
These changes decrease the amount of `std::shared_ptr` copies to improve performance.
=> [SYCL] Update sampler_impl to use context_impl instead of context

unified-runtime/cmake/helpers.cmake, unified-runtime/source/loader/layers/sanitizer/msan/msan_shadow.hpp
There were a number of problems preventing CFI from being enabled, this hopefully fixes them.
As part of this, an unused variable compile error in `clang` was fixed.
=> [UR] Fix cfi initialization

sycl/test-e2e/Basic/handler/handler_mem_op.cpp, sycl/test-e2e/InorderQueue/in_order_usm_host_dependency.cpp, sycl/test-e2e/USM/copy.cpp, sycl/test-e2e/syclcompat/memory/memory_management_test1.cpp, sycl/test-e2e/syclcompat/memory/memory_management_test1_usmnone.cpp, sycl/test-e2e/syclcompat/memory/memory_management_test2.cpp, sycl/test-e2e/syclcompat/memory/memory_management_test2_usmnone.cpp, sycl/test-e2e/syclcompat/memory/memory_management_test3.cpp, sycl/test-e2e/syclcompat/memory/memory_management_test3_usmnone.cpp
This reverts commit 6733ee2d2d6577068db36c65abfa731235e62ab8.
The driver version on CI is new enough already,.
=> Revert "[SYCL][E2E] mark failing tests on v2 L0 adapter"

sycl/source/detail/event_impl.hpp, sycl/source/detail/graph_impl.cpp, sycl/source/detail/graph_impl.hpp, sycl/source/detail/queue_impl.hpp, sycl/source/event.cpp, sycl/source/handler.cpp, sycl/source/queue.cpp
Introduce functions checking if the command graph exists, which can be used instead of getting the command graph shared ptr by value.
=> [SYCL][Graph] Avoid command graph shared_ptr return

sycl/source/detail/queue_impl.cpp, sycl/source/detail/scheduler/scheduler.cpp, sycl/source/detail/scheduler/scheduler.hpp, sycl/source/handler.cpp, sycl/test-e2e/XPTI/basic_event_collection_linux.cpp, sycl/unittests/scheduler/EnqueueWithDependsOnDeps.cpp
1) Aling scheduler bypass conditions for CG and for memory ops. 
2) Connect an event returned from scheduler bypass case with dependent events.
=> [SYCL] Extend scope of scheduler bypass to safe to bypass events

.github/workflows/sycl-post-commit.yml
I forgot to do this when I updated the workflow to run on driver updates, so it wasn't using the new driver.
=> [CI] Correctly set install_igc_driver in postcommit

.github/workflows/sycl-linux-build.yml, buildbot/configure.py, sycl/CMakeLists.txt, sycl/doc/EnvironmentVariables.md, unified-runtime/source/adapters/level_zero/v2/README.md, unified-runtime/source/loader/ur_adapter_registry.hpp
L0 v2 adapter is expected to be shipped as part of 2025.2 release.
Refactor params to configure.py into a single 'choice' param.
=> [SYCL] Build L0 v2 adapter by default

.github/workflows/docs.yml, .github/workflows/pr-code-format.yml
due to found CVE-2025-30066.
Ref. https://github.com/advisories/GHSA-mrrh-fwg8-r2c3
=> [CI] Bump tj-actions/changed-files to v46

.github/workflows/sycl-nightly.yml, .github/workflows/sycl-windows-run-tests.yml, devops/actions/run-tests/windows/cts/action.yml
This patch adds SYCL-CTS build&launch on Win.
Also prepare the workflow for separate actions like it was done for Linux.
=> [CI] Add SYCL-CTS on Win

sycl/source/detail/event_impl.cpp, sycl/source/detail/event_impl.hpp, sycl/source/detail/queue_impl.cpp, sycl/source/detail/queue_impl.hpp, sycl/source/handler.cpp, sycl/unittests/scheduler/InOrderQueueSyncCheck.cpp
Reduced the number of event_impl allocations on the kernel enqueue path to one, for the scheduler bypass fast path.
=> [SYCL] Avoid multiple event_impl allocations on kernel enqueue

devops/dependencies.json
This is a prerequisite for https://github.com/intel/llvm/pull/17150
=> [CI] bump level-zero version

devops/dependencies.json
Reverts intel/llvm#17485
It's causing arc and gen12 jobs to fail:
https://github.com/intel/llvm/actions/runs/13930776997/job/38988553691?pr=17513
https://github.com/intel/llvm/actions/runs/13931604336/job/38990417392
=> Revert "[CI] bump level-zero version"

unified-runtime/source/adapters/cuda/enqueue_native.cpp, unified-runtime/source/adapters/hip/enqueue_native.cpp
This UR entry point calls a user function pointer, which may throw exceptions so we need an exception catchall there to ensure they don't cross the UR C API boundary.
It's unclear if exceptions should even be allowed in these user functions, but this is still a worthwhile precaution.
=> [UR][CUDA][HIP] Add missing catch for native commands

sycl/doc/extensions/experimental/sycl_ext_oneapi_kernel_compiler.asciidoc
Update the non-normative section in the `kernel_compiler` extension to reflect what's currently supported in DPCPP.
=> [SYCL][Doc][RTC] Document [un]supported features and `build_options`

.github/workflows/sycl-windows-run-tests.yml, devops/actions/run-tests/windows/cts/action.yml
https://github.com/intel/llvm/pull/17501 enabled CTS on win. But for this patch I used the old version of cts/action.yml (before https://github.com/intel/llvm/pull/17228). So it caused the Nightly failure - https://github.com/intel/llvm/actions/runs/13938048645. This patch aligns windows/cts/action.yml with the linux version.
=> [CI] Align `windows/cts/action.yml` with linux

sycl/doc/design/CommandGraph.md, sycl/source/detail/graph_impl.cpp, sycl/source/detail/graph_impl.hpp, sycl/unittests/Extensions/CommandGraph/CMakeLists.txt, sycl/unittests/Extensions/CommandGraph/TopologicalSort.cpp
The current implementation of the topological sort algorithm relies on a recursive function. This causes stack overflow issues when the graphs are very large. There is also a performance issue in the current implementation related to the way std::find() is being used.
This commit reimplements the topological sort algorithm to fix these issues:
- Uses an iterative approach instead of recursive.
- Removes the use of std::find() and instead relies on keeping the state with a helper variable.
- Reimplements the cycle checking algorithm to use the same topological sort function as the one used during scheduling.
- Fixes a bug with make_edge() not removing the dest node from the list of root nodes.
=> [Sycl][Graph] Reimplement topological sort algorithm

sycl/test-e2e/bindless_images/read_write_1D_subregion.cpp
This test has been flakily failing on Windows + BMG.
See https://github.com/intel/llvm/issues/17439
=> [Bindless][E2E] Disable bindless_images/read_write_1D_subregion.cpp on BMG, Windows

sycl/test-e2e/lit.cfg.py
`open_check_file` creates files in `config.sycl_obj_root`, make sure we are in that directory when trying to compile those check files.
Fixes incorrect `preview-breaking-changes-supported` detection in in-tree configuration (which most people are likely to use locally/interactively).
=> [SYCL][E2E] Update current directory in `with test_env:`

unified-runtime/test/adapters/level_zero/v2/CMakeLists.txt
The level_zero v2 tests define a function named "add_unittest", which
clashes with a function of the same name from LLVM.
=> [UR] Fix function name collision in l0 v2 tests

.github/CODEOWNERS
Scripts enabling CI for benchmarking has gotten pretty big and complicated: https://github.com/intel/llvm/pull/17545
Most of this code were developed by the UR team, and thus it no longer makes sense to ask dpcpp-devops-reviewers for PR approvals. This PR updates CODEOWNERS to ask llvm-reviewers-benchmarking for benchmarking scripts instead.
**Note:** The current path here puts `/devops/scripts/benchmarks` under llvm-reviewers-benchmarking: This path currently does not exist, but is chosen on purpose in anticipation for https://github.com/intel/llvm/pull/17545.
The folder `/devops/scripts/benchmarking` will be removed in the future as a part of the effort to unify SYCL and UR benchmarking CI infrastructure; See https://github.com/intel/llvm/pull/17229
=> [CODEOWNERS] Add llvm-reviewers-benchmarking to CODEOWNERS

unified-runtime/source/adapters/native_cpu/common.hpp, unified-runtime/source/adapters/native_cpu/context.cpp, unified-runtime/source/adapters/native_cpu/device.cpp, unified-runtime/source/adapters/native_cpu/kernel.cpp, unified-runtime/source/adapters/native_cpu/memory.cpp, unified-runtime/source/adapters/native_cpu/program.cpp
The whole point of surrounding a macro definition in `do { } while (0)` is to safely handle the case of missing braces in an if statement. Remove the semicolon from the definitions of `DIE_NO_IMPLEMENTATION`, and `CONTINUE_NO_IMPLEMENTATION`; and put them around all its uses.
=> remove terminating semicolons from do-while-0

sycl/tools/sycl-ls/sycl-ls.cpp, unified-runtime/source/common/linux/ur_lib_loader.cpp
Changes:
* change the log level to "error" for all errors related to adapter dependencies during UR adapter loading
* enable the printing of UR adapter errors in sycl-ls from platform::get_platforms() using environment variables
With this PR, there will be no changes for the user in the default scenario where some adapters exist and some are missing (a missing adapter is not considered an error). In cases where a dependency is missing, the following example message will be displayed:
```
<LOADER>[ERROR]: failed to load adapter 'libur_adapter_level_zero.so.0' with error: libumf.so.0: cannot open shared object file: No such file or directory
```
Here is the message for missing symbols (a case where a dependency is not compatible with the rest of the libraries):
```
<LOADER>[ERROR]: failed …
```
=> [SYCL][UR] Log `sycl-ls` error messages related to adapter loading

sycl/cmake/modules/AddSYCLUnitTest.cmake, sycl/include/sycl/detail/os_util.hpp, sycl/source/backend.cpp, sycl/source/detail/buffer_impl.cpp, sycl/source/detail/context_impl.cpp, sycl/source/detail/device_image_impl.hpp, sycl/source/detail/device_impl.cpp, sycl/source/detail/event_impl.cpp, sycl/source/detail/kernel_impl.hpp, sycl/source/detail/os_util.cpp, sycl/source/detail/queue_impl.cpp, sycl/source/detail/queue_impl.hpp, sycl/source/detail/sycl_mem_obj_t.cpp, sycl/source/device.cpp, sycl/source/event.cpp, sycl/source/kernel.cpp, sycl/test/Unit/lit.cfg.py, sycl/unittests/CMakeLists.txt, sycl/unittests/Extensions/CompositeDevice.cpp, sycl/unittests/SYCL2020/GetNativeOpenCL.cpp, sycl/unittests/helpers/KernelInteropCommon.hpp, sycl/unittests/helpers/UrMock.hpp, sycl/unittests/mock_opencl/CMakeLists.txt, sycl/unittests/mock_opencl/mock_opencl.cpp, sycl/unittests/queue/InteropRetain.cpp
At various points, OpenCL native handles need to be retained to ensure
SYCL semantics. Previously, this relied on the fact that UR handles were
typecast CL handles and shared the same reference count.
However, the SYCL RT shouldn't assume this, so instead we call the
appropriate (dynamically looked-up) CL functions on the native handles
instead.
This is in preperation for https://github.com/oneapi-src/unified-runtime/pull/1176 .
This change should also have no observable effect for SYCL code; there
is no change in lifetime semantics.
=> [UR] Replace calls to UR in native handle functions to proper OpenCL functions

devops/dependencies.json, sycl/test-e2e/Matrix/SG32/get_coordinate_ops.cpp, sycl/test-e2e/Matrix/SG32/joint_matrix_annotated_ptr.cpp, sycl/test-e2e/Matrix/SG32/joint_matrix_colA_rowB_colC.cpp, sycl/test-e2e/Matrix/SG32/joint_matrix_int8_rowmajorA_rowmajorB.cpp, sycl/test-e2e/Matrix/SG32/joint_matrix_out_bounds.cpp, sycl/test-e2e/Matrix/SG32/joint_matrix_prefetch.cpp, sycl/test-e2e/Matrix/joint_matrix_16bit_colmajorA_colmajorB.cpp, sycl/test-e2e/Matrix/joint_matrix_colA_rowB_colC.cpp, sycl/test-e2e/Matrix/joint_matrix_out_bounds_colmajor.cpp, sycl/test-e2e/Matrix/joint_matrix_transposeAB.cpp
=> [GHA] Uplift Linux GPU RT version to 25.09.32961.5

sycl/source/detail/os_util.cpp
https://github.com/intel/llvm/pull/17016#issuecomment-2743521236
=> [SYCL][UR] Fix post commit Windows failure

unified-runtime/test/conformance/exp_command_buffer/native-command/common.h
All UR command-buffer CTS tests are marked as XFail on V2 [See CTS generic base class for command-buffer](https://github.com/intel/llvm/blob/sycl/unified-runtime/test/conformance/exp_command_buffer/fixtures.h#L48)
This was omitted by accident from the new command-buffer CTS tests added in https://github.com/intel/llvm/pull/17494 which don't derive from that base class. Fixed by adding in now.
=> [UR] Skip new command-buffer CTS test on L0 V2

.github/workflows/sycl-nightly.yml, .github/workflows/sycl-rel-nightly.yml, .github/workflows/sycl-windows-run-tests.yml
Rename `ref` to `repo_ref` as it was done for linux: https://github.com/intel/llvm/pull/17277
=> [CI][NFC] Rename `ref` to `repo_ref`

sycl/include/sycl/handler.hpp, sycl/include/sycl/queue.hpp
There is a single unique value for it since
https://github.com/intel/llvm/pull/16118, so there is no reason for having it.
=> [NFC][SYCL] Inline `_KERNELFUNCPARAM` macro

sycl/test-e2e/BFloat16/bfloat16_example_aot_gpu.cpp
It fails in precommit L0 Gen12 but passes in postcommit L0 Gen12, weird.
=> [SYCL][E2E] Mark bfloat16 AOT test unsupported

clang/lib/Sema/SemaExpr.cpp, clang/lib/Sema/SemaSYCL.cpp, clang/test/SemaSYCL/constexpr-function-pointer.cpp
=> Revert "[SYCL] Move function pointer diagnostics to BuildResolvedCallExpr"

clang/lib/Driver/OffloadBundler.cpp, clang/test/Driver/clang-offload-bundler-skip-for-symtbl.c, clang/test/Driver/clang-offload-bundler-skip-for-symtbl.c.ll
`__MsanDeviceGlobalMetadata` etc are sanitizer internal variables, and should not be bundled to the symbol table.
=> [DeviceSanitizer] Skip adding device sanitizers internal variable to bundler symbol table

sycl/cmake/modules/FetchUnifiedRuntime.cmake
~~Update UR to statically link UMF with hwloc on Linux.~~
This will enable hwloc support in UMF on Linux.
~~Also, always use the v2.9.3 hwloc version for hwloc builds.~~
=> [UR] Enable hwloc in UMF linux build

.github/workflows/sycl-weekly.yml
sycl_cts_artifact is required for build-sycl-cts step. Also update name & comments.
=> [CI] Update sycl-weekly.yml

buildbot/configure.py, sycl/doc/GetStartedGuide.md, sycl/doc/design/SYCLNativeCPU.md
Hundreds of `--cmake-opt=-DFOO=BAR` on the command line make it hard to see the wood for the trees, so introduce an alternative which is to simply pass unknown argument flags straight through to cmake. This should make using the wrapper a little more pleasant and readable.
CHERRY-PICK OF: c62abaeee9e6cb48d04fb623075705710089bd3f
=> Enable cmake argument passthrough in the SYCL configure wrapper (#17189)

sycl/source/detail/compression.hpp, sycl/source/detail/device_binary_image.hpp
Fixed the following warning when DPC++ is built in Release mode with gcc 13:
```
In member function 'void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = char]',
inlined from 'std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = char; _Dp = std::default_delete<char>]' at /usr/include/c++/13/bits/unique_ptr.h:404:17,
inlined from 'static std::unique_ptr<char> sycl::_V1::detail::ZSTDCompressor::DecompressBlob(const char*, size_t, size_t&)' at /tmp/llvm/sycl/source/detail/compression.hpp:139:3,
inlined from 'void sycl::_V1::detail::CompressedRTDeviceBinaryImage::Decompress()' at /tmp/llvm/sycl/source/detail/device_binary_image.cpp:258:54:
/usr/include/c++/13/bits/unique_ptr.h:99:9: error: 'void operator delete(void*, std::size_t)' called on pointer returned from a mismatched …
```
=> [SYCL] Fix `mismatched-new-delete` warning in compression.hpp

sycl/doc/GetStartedGuide.md
This patch reformats the pre-requisites in a table (doesn't look great in the markdown, but looks good when generated).
It also updates the required versions for CMake and Python to link to the versions required by LLVM. For CMake we were already documenting the same version as LLVM. For Python we didn't document any minimum version, but we extensively use LLVM scripts like `lit`, so we really should be aligned with it.
There's a few requirements for which we don't have minimum versions, but we can update that if we ever run into issues with them.
Addresses https://github.com/intel/llvm/issues/17478 by documenting the minimum required python version.
=> [SYCL][Doc] Update GetStartedGuide pre-requisiste

clang/include/clang/Driver/Options.td, clang/lib/Driver/ToolChains/SYCL.cpp, clang/test/Driver/sycl-ftarget-register-alloc-mode.cpp, clang/test/Driver/sycl-unsupported.cpp
Perform a few updates to clean up some LIT testing issues
- Update `-nocudalib` to be available for Windows
- Remove -forder-file-instrumentation usage (option removed)
- Update arch= usage in testing with new offload model
=> [Driver][SYCL] Update tests and option availability

clang/test/Driver/linker-wrapper-sycl.cpp, clang/tools/clang-linker-wrapper/ClangLinkerWrapper.cpp, clang/tools/clang-linker-wrapper/LinkerWrapperOpts.td
Despite the option name sycl-dump-device-code it enables dumping of only SPIR-V files emitted by the translator tool. This change dumps device code right before embedding it into the fat object. The tool dumps offloading image of any format.
=> [clang-linker-wrapper] Dump any device code format

llvm/lib/SYCLLowerIR/ESIMD/ESIMDVerifier.cpp
According to https://github.com/llvm/llvm-project/blob/main/llvm/unittests/Demangle/OutputBufferTest.cpp, `OutputBuffer` has to be manually freed.
=> [SYCL] Fix memory leak.

unified-runtime/source/adapters/cuda/CMakeLists.txt, unified-runtime/source/adapters/cuda/common.cpp, unified-runtime/source/adapters/cuda/common.hpp, unified-runtime/source/adapters/cuda/device.cpp, unified-runtime/source/adapters/cuda/device.hpp, unified-runtime/test/adapters/cuda/CMakeLists.txt, unified-runtime/test/conformance/device/urDeviceGetInfo.cpp
Tests were not added because there are existing conformance tests which cover this functionality.
=> [SYCL][CUDA] Add implementation of new device descriptors

llvm/lib/Transforms/Instrumentation/AddressSanitizer.cpp, llvm/lib/Transforms/Instrumentation/MemorySanitizer.cpp, llvm/test/Instrumentation/AddressSanitizer/SPIRV/device_global.ll, llvm/test/Instrumentation/MemorySanitizer/SPIRV/instrument_device_global.ll
DeviceSanitizer cannot handle nameless globals, but we cannot skip instrumenting them either. Therefore, we set names to nameless globals and process them like regular globals.
Also, this PR update two now deprecated API usage of `getFirstNonPHI`
=> [DeviceSanitizers] Set names to nameless globals

llvm/lib/Transforms/Instrumentation/MemorySanitizer.cpp, llvm/test/Instrumentation/MemorySanitizer/SPIRV/instrument_global_address_space.ll, unified-runtime/source/loader/layers/sanitizer/msan/msan_ddi.cpp
- Simplify "instrument_global_address_space.ll" test
- Handle no "noundef" attribute in arguments and return value
=> [DeviceMSAN] Fix no "noundef" attribute in parameters and return value

sycl/test-e2e/OptionalKernelFeatures/is_compatible/is_compatible_amdgcn.cpp, sycl/test-e2e/OptionalKernelFeatures/is_compatible/is_compatible_nvptx64.cpp, sycl/test-e2e/OptionalKernelFeatures/is_compatible/is_compatible_several_targets.cpp, sycl/test-e2e/OptionalKernelFeatures/is_compatible/is_compatible_spir64.cpp, sycl/test-e2e/OptionalKernelFeatures/is_compatible/is_compatible_spir64_gen.cpp, sycl/test-e2e/OptionalKernelFeatures/is_compatible/is_compatible_spir64_x86_64.cpp, sycl/test-e2e/OptionalKernelFeatures/is_compatible/is_compatible_with_aspects.cpp
Due to incorrect REQUIRES these tests are never launched.
=> [SYCL][E2E] Update is_compatible tests

sycl/test/self-contained-headers/lit.local.cfg, sycl/test/self-contained-headers/sycl/ext/oneapi/experimental/backend/cuda.hpp.cpp
This header needs a sepcific macro to be defined when it is included which is why the generic test gives out warnings. Add a specific test for it so we can define the macro.
=> [SYCL] Fix CUDA interop self-contained-headers test

sycl/include/sycl/handler.hpp
The change improves "host" compilation times for cases with multiple kernels.
=> [NFC][SYCL] Avoid unnecessary `std::unique_ptr<HostKernel<...>>` instantiations

sycl/source/detail/config.hpp, sycl/source/detail/jit_compiler.cpp, sycl/source/detail/jit_compiler.hpp, sycl/source/detail/scheduler/scheduler.cpp, sycl/source/detail/scheduler/scheduler.hpp
Avoid copying by:
- Making the `Queue` parameter of `completeSpecConstMaterialization` passed by a const reference. Also changes `materializeSpecConstants`, `getTargetInfo` and `getTargetFormat` to accomodate this change.
- Makes returned `DefaultValue` string non const so that the move ctor is called automatically in two `get` functions.
- Remove dead if statement that copied value for a function call.
=> [SYCL] Fix 'move instead of copy' Coverity hits

unified-runtime/include/ur_api.h, unified-runtime/scripts/core/device.yml, unified-runtime/scripts/core/manifests.yml
Update spec to clarify that this is not a value to be returned.
Fixes https://github.com/intel/llvm/issues/17527
=> [UR] Clarify UR_DEVICE_TYPE_ALL usage.

sycl/test-e2e/MemorySanitizer/check_device_global.cpp
We can't reproduce https://github.com/intel/llvm/issues/16978 locally, try to enable it again because maybe it has been fixed by other patch.
=> [DeviceMSAN] Re-enable device global test

unified-runtime/source/loader/layers/sanitizer/ur_sanitizer_layer.cpp
There is uncaught exception through logger creation in sanitizer layer `context_t` 's creation. We catch exceptions here and die if the creation of sanitizer layer context fails.
=> [DeviceSanitizer][Coverity] die when fail to create context

devops/scripts/benchmarks/benches/compute.py, devops/scripts/benchmarks/benches/llamacpp.py, devops/scripts/benchmarks/benches/syclbench.py, devops/scripts/benchmarks/benches/velocity.py, devops/scripts/benchmarks/main.py
Enable benchmarking sycl for hip adapter through VelocityBench and SyclBench in benchmarking scripts.
=> [SYCL][BENCHMARK] Add HIP to benchmarks scripts

.github/workflows/sycl-post-commit.yml
We only have one runner which is constantly overloaded and we already test AMDGPU in precommit.
=> [CI] Remove AMDGPU testing from postcommit

llvm/lib/SYCLLowerIR/ESIMD/ESIMDVerifier.cpp
Delete copy and move assignment operators to comply with Rule of Five.
=> [NFC][SYCL][ESIMD] Delete copy and move assignment operators.

unified-runtime/source/common/ur_pool_manager.hpp
This should fix coverity issues in `ur_pool_manager.hpp`, `ur_util.hpp` and `ur_adapter_registry.hpp` files reported in: https://coverity.devtools.intel.com/prod6/#/project-view/26752/10020
=> [Coverity][UR] Remove noexcept keywords from pool_manager methods

sycl/include/sycl/detail/type_traits/vec_marray_traits.hpp, sycl/include/sycl/detail/vector_convert.hpp, sycl/include/sycl/vector.hpp, sycl/test/abi/layout_vec.cpp, sycl/test/basic_tests/vectors/storage.cpp, sycl/test/check_device_code/vector/bf16_builtins.cpp, sycl/test/check_device_code/vector/convert_bfloat.cpp, sycl/test/check_device_code/vector/math_ops.cpp, sycl/test/regression/vec_array_windows.cpp
The problem with using `std::array` in `sycl::vec` is that we cannot compile it in some environments (namely, Windows) because the former may use something that is illegal in SYCL device code.
intel/llvm#17025 fixed that, but only did so under preview breaking changes mode, which does not satisfy some of our customers immediately.
This PR introduces two main changes:
- it allows to opt-in for new behavior through passing `-D__SYCL_USE_NEW_VEC_IMPL=1` macro without using `-fpreview-breaking-changes` flag. That allows for a more gradual opt-in from customers who are interested in this fix
- it switches the imlpementation to use the new approach with C-style arrays if their size and alignment is the same as for the corresponding `std::array` - in that case their memory layout is expected to …
=> [SYCL] Switch to use plain array in `sycl::vec` in more cases

sycl/test-e2e/Matrix/SG32/get_coordinate_ops.cpp, sycl/test-e2e/Matrix/SG32/joint_matrix_int8_colmajorA_colmajorB.cpp, sycl/test-e2e/Matrix/joint_matrix_int8_colmajorA_colmajorB.cpp
XPASSing in [nightly](https://github.com/intel/llvm/actions/runs/14050841978) but failing in pre/postcommit, make them XFAIL only where they actually fail.
=> [SYCL][E2E][Matrix] Restrict XFAIL in some tests to DG2

unified-runtime/source/adapters/level_zero/image.cpp, unified-runtime/source/adapters/level_zero/platform.cpp, unified-runtime/source/adapters/level_zero/platform.hpp
- Implements the spec version of the L0 Extension External Semaphores
- Implements handling the translation of handles if the driver only supports the EXP functions.
=> [UR][L0] Enable support for using L0 spec External Semaphores

unified-runtime/source/adapters/level_zero/device.cpp, unified-runtime/source/adapters/level_zero/image.cpp
Enable L0 to directly import the memory allocated for NPU/iGPU and let SYCL kernel running on iGPU be able to directly access the data it will reduce the overhead of data movement between NPU/iGPU and iGPU.
=> [UR][L0] Memory interop support given external buffer

devops/scripts/benchmarks/benches/umf.py
Beside the new class for fragmentation measurements, ComputeUMFBenchmark base class is directly replaced by GBench. Methods and attributes previously included in ComputeUMFBenchmark have been relevant only for Google Benchmark, therefore inheriting from ComputeUMFBenchmark would have been pointless for benchmarks using other frameworks.
Additionally, each benchmark is run separately in order to avoid any impact of benchmarks on each other. Benchmarks using glibc are excluded from fragmentation measurements.
=> [CI][Benchmark] add UMF benchmarks for fragmentation measurements

unified-runtime/include/ur_api.h, unified-runtime/scripts/core/exp-async-alloc.yml, unified-runtime/source/loader/layers/validation/ur_valddi.cpp, unified-runtime/source/loader/ur_libapi.cpp, unified-runtime/source/ur_api.cpp
This null pointer check is already performed as the parameter isn't marked optional, so we don't need to manually specify it.
=> [UR] Fix unnecessary check in async alloc extension

unified-runtime/source/adapters/hip/CMakeLists.txt, unified-runtime/source/adapters/hip/context.cpp, unified-runtime/source/adapters/hip/device.cpp, unified-runtime/source/adapters/hip/kernel.hpp
I don't have access to a device to validate it's all perfect at runtime, but these fixes did let me build everything successfully, and the compiler was able to build Blender GPU kernels library on Windows, using HIP SDK 6.2.4 and VS2022 17.12.1.
=> [UR][HIP] Fix HIP adapter compilation on Windows

llvm/lib/SYCLLowerIR/ESIMD/ESIMDVerifier.cpp
The buffer seems to be allocated in the call to `NameNode->print(NameBuf)`, so we need to move the RAII deleter after that call, otherwise the buffer keeps leaking because when the RAII deleter is created, there's no buffer yet.
=> [ESIMD] Move RAII deleter init after buffer allocation.

sycl/test-e2e/CMakeLists.txt, sycl/test-e2e/EnqueueNativeCommand/custom-command-hip.cpp, sycl/test-e2e/Graph/NativeCommand/hip_explicit_usm.cpp, sycl/test-e2e/Graph/NativeCommand/hip_record_buffer.cpp, sycl/test-e2e/Graph/NativeCommand/hip_record_usm.cpp, sycl/test-e2e/HostInteropTask/interop-task-hip.cpp, sycl/test-e2e/README.md, sycl/test-e2e/lit.cfg.py, sycl/test-e2e/lit.site.cfg.py.in
We already have features for Level Zero and CUDA, add one for HIP.
=> [SYCL][E2E] Add LIT feature for HIP

llvm/lib/SYCLNativeCPUUtils/PrepareSYCLNativeCPU.cpp
When we rename wrapper functions to take the name of the original, that leaves in place a call to the original meaning the original cannot be removed. When we take its name, the original's name would be cleared. Append ".orig" instead to make it easier to keep track of which is which.
=> [SYCL][NativeCPU][NFC] Prevent generating unnamed functions

sycl/include/sycl/detail/os_util.hpp, sycl/unittests/mock_opencl/CMakeLists.txt
The name of OpenCL may vary between different implementations, but
libur_adapter_opencl.so shouldn't.
=> [SYCL] Use libur_loader_opencl.so rather than libOpenCL.so on Linux

devops/actions/run-tests/cts/action.yml, devops/actions/run-tests/windows/cts/action.yml
Otherwise `cat` may return 1 and fail the step.
=> [CI][CTS] Check if the cts_exclude_filter exists

llvm/cmake/modules/AddSecurityFlags.cmake
CMake has a notion of scopes for variables and we fell into a pitfall of setting local variables instead of applying changes globally to the whole project.
For reference, see:
- https://cmake.org/cmake/help/v3.20/command/set.html
- https://cmake.org/cmake/help/v3.20/command/include.html
=> [SYCL] Fix AddSecurityFlags having no side effects

sycl/source/detail/cg.hpp, sycl/source/detail/context_impl.cpp, sycl/source/detail/handler_impl.hpp, sycl/source/detail/memory_pool_impl.cpp, sycl/source/detail/scheduler/commands.cpp
This patch fixes a couple static analysis issues with the recent [async alloc patch](https://github.com/intel/llvm/pull/16900):
* Use `std::move` for shared pointer in `CGAsyncAlloc` constructor. It is already passed by-value to the constructor so we can just move it when assigning it to the member.
* Assert that the queue is available in `AsyncFree`
* Catch any exceptions from the memory pool destructor
* Initialize AsyncAlloc fields in handler
* Add `[[maybe_unused]]` for parameter only used in assert
=> [SYCL][AsyncAlloc] Fix minor async alloc issues

sycl/test-e2e/Adapters/interop-level-zero-buffer-multi-dim.cpp, sycl/test-e2e/Adapters/interop-level-zero-buffer-ownership.cpp, sycl/test-e2e/Adapters/interop-level-zero-buffer.cpp, sycl/test-e2e/Adapters/interop-level-zero-get-native-mem.cpp, sycl/test-e2e/Adapters/interop-level-zero-image-get-native-mem.cpp, sycl/test-e2e/Adapters/interop-level-zero-image-ownership.cpp, sycl/test-e2e/Adapters/interop-level-zero-image.cpp, sycl/test-e2e/Adapters/interop-level-zero-keep-ownership.cpp, sycl/test-e2e/Adapters/interop-level-zero.cpp, sycl/test-e2e/Adapters/level_zero_batch_barrier.cpp
Level Zero loader is now linked statically with adapters and tests. This means that both adapters and tests need to call zeInit to initalize the loader.
=> [SYCL][E2E] Add missing zeInit to interop tests

unified-runtime/source/adapters/level_zero/v2/memory.cpp, unified-runtime/source/adapters/level_zero/v2/memory.hpp, unified-runtime/test/adapters/level_zero/CMakeLists.txt, unified-runtime/test/adapters/level_zero/urMemBufferCreateWithNativeHandleShared.cpp
The implementation incorrectly assumed that hDevice is always set for memory type other than host which resulted in nullptr dereference in ur_discrete_buffer_handle_t ctor.
The assumption is not true for shared allocations.
Implement a separate handle type to handle shared allocations: the implementation will just use the allocation directly.
=> [SYCL][UR][L0 v2] Fix urMemBufferCreateWithNativeHandle

unified-runtime/source/adapters/level_zero/program.cpp, unified-runtime/source/loader/layers/sanitizer/tsan/tsan_interceptor.cpp
Looks like this slipped through the cracks and wasn't formatted.
=> [UR][NFC] Run formatter

sycl/test-e2e/Matrix/Inputs/joint_matrix_bf16_fill_k_cache_impl.hpp, sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_unroll.cpp, sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_unroll_init.cpp
Since drivers are updated in SYCLOS CI, removed couple workarounds.
=> [SYCL][E2E][Joint Matrix] Remove some workarounds

.github/workflows/sycl-nightly.yml
The job's name is `ubuntu2204_shared_build`  while we use `ubuntu2404_intel_drivers` docker image to build DPCPP.
Example: https://github.com/intel/llvm/actions/runs/14121213165/job/39561695852#step:2:22
=> [CI] Fix shared build job name in Nightly

.github/workflows/sycl-linux-run-tests.yml, devops/actions/run-tests/e2e/action.yml
We have it in `LIT_OPTS` already but we see sometimes it doesn't work, let's try this.
=> [CI] Set e2e test timeout to 1 hour

unified-runtime/source/adapters/cuda/usm.cpp
CUDA did not introduce the maxSize property to CUmemPoolProps until version 12.2. In the case where the user has set a maxSize > 0, and their CUDA version is < 12.2, return an error.
This commit fixes the compilation error associated with setting this property in older CUDA versions.
Also fix incorrect error reporting when creating a memory pool.
=> [AsyncAlloc][CUDA] Don't set pool maxSize if CUDA version < 12.2

clang/lib/CodeGen/CodeGenModule.cpp, clang/test/CodeGenSYCL/kernel-op-calls.cpp, sycl/test/check_device_code/esimd/dae.cpp
`kernel_arg_addr_space`, `kernel_arg_access_qual`, `kernel_arg_type`, `kernel_arg_base_type` and `kernel_arg_type_qual` metadata are designed to provide information about kernel arguments to [clGetKernelInfo](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#_kernel_object_queries) function.
SYCL does not provide similar information through API.
=> [NFC][SYCL] Don't emit OpenCL metadata for SYCL

.github/workflows/sycl-detect-changes.yml
https://github.com/intel/llvm/actions/runs/14151976801/job/39646329170?pr=17710
The step will crash if the change files are huge.
=> [CI] Don't try to run detect changes for large PR

sycl/test-e2e/lit.cfg.py
I've looked through logs of some recent pre-commit jobs (both Lin/Win) and the only test that was longer than 5 min on just some occasions is `KernelCompiler/sycl.cpp`. I talked to Chris and he'll upload a change to reduce its time soon. The rest seemed to be comfortably under 5 minutes, so set per-test timeout to that value in run-only mode.
=> [SYCL][E2E] Decrease per-test timeout in run-only mode

unified-runtime/README.md, unified-runtime/test/adapters/cuda/CMakeLists.txt, unified-runtime/test/adapters/hip/CMakeLists.txt
These tests require device code, which isn't available if `UR_DPCXX`
is not set.
=> [UR] Don't build hip/cuda adapter tests if dpcpp isn't available

devops/scripts/benchmarks/benches/umf.py
Land https://github.com/intel/llvm/pull/17608 into `sycl` branch as well
Original PR was by @EuphoricThinking, here is her original PR description:
Beside the new class for fragmentation measurements, ComputeUMFBenchmark base class is directly replaced by GBench. Methods and attributes previously included in ComputeUMFBenchmark have been relevant only for Google Benchmark, therefore inheriting from ComputeUMFBenchmark would have been pointless for benchmarks using other frameworks.
Additionally, each benchmark is run separately in order to avoid any impact of benchmarks on each other. Benchmarks using glibc are excluded from fragmentation measurements.
=> [CI][Benchmark] Merge "add UMF benchmarks for fragmentation measurements" into sycl

sycl/source/detail/global_handler.cpp, sycl/source/detail/global_handler.hpp
This PR optimizes global object singleton creation by removing the `getOrCreate()` from the hot path for most of the global objects.
- `getOrCreate()` method locks mutex on every call 
- We cannot just use the C++11 way of creating static singleton variables inside corresponding methods because we need to control the destruction order of global objects. Therefore, we use static variables to cache the result of the `getOrCreate()` method so that it calls only once per global object.
- The optimization is not done for the `GlobalHandler::getPlatformToDefaultContextCache` method because there are public methods of the `GlobalHandler` that can set the `MPlatformToDefaultContextCache` back to `nullptr`.
=> [SYCL] Optimize creation of global objects in GlobalHandler

unified-runtime/source/adapters/level_zero/device.cpp
Returning native and preferred vector widths using an heuristic based on native simd width is incorrect.
Especially on simd8 GPUs (Intel Arc Alchemist and Flex Series), this approach doesn't match what OpenCL returns.
This set of changes aligns the behavior with OpenCL, defined here: https://github.com/intel/compute-runtime/blob/291745cdf76d83f5dc40e7ef41d347366235ccdb/opencl/source/cl_device/cl_device_caps.cpp#L236
=> [UR][L0] Fix level-zero vector width queries

.github/workflows/sycl-detect-changes.yml
Problem
Output Access: The output from the changed_files step is being accessed
incorrectly. The changed_files step returns a value, but it's not being
stored in a way that can be directly accessed in the if condition.
Type Mismatch: The output from the changed_files step is likely a
string, and you're trying to compare it as a number. This can lead to
unexpected behavior.
Solution
To fix the issue, you need to ensure that the output from the
changed_files step is correctly stored and accessed
Why It Works for steps.result.outputs.result for
steps.result.outputs.result
Direct Access: The script directly accesses
context.payload.pull_request.changed_files and performs the comparison
within the JavaScript environment, which is more flexible and allows for
direct manipulation of data.
Output …
=> [CI] 2nd attempt to skip filtering large PR

sycl/include/sycl/detail/common.hpp
If assertions are disabled this warning is treated as an error: warning C4101: 'e': unreferenced local variable
=> [SYCL] Void unused variable

sycl/include/sycl/detail/common.hpp
If assertions are disabled this warning is treated as an error: warning
C4101: 'e': unreferenced local variable
CHERRY-PICK OF 9303f5a8c7947f3c7d7c8cd0a7043513a7023092
=> [SYCL] Void unused variable (#17766)

unified-runtime/source/adapters/level_zero/v2/command_list_cache.cpp
Copy offload is not very stable on BMG. Enabling copy offload results in ~40 failing tests. Add option to force disable the feature for easier debugging.
=> [SYCL][UR][L0 v2] Add env variable to control copy offload

llvm/cmake/modules/AddSecurityFlags.cmake
This is a cherry-pick of intel/llvm#17690
---
CMake has a notion of scopes for variables and we fell into a pitfall of setting local variables instead of applying changes globally to the whole project.
For reference, see:
- https://cmake.org/cmake/help/v3.20/command/set.html
- https://cmake.org/cmake/help/v3.20/command/include.html
=> [SYCL][sycl-rel] Fix AddSecurityFlags having no side effects

sycl/include/syclcompat/memory.hpp, sycl/include/syclcompat/util.hpp
The functions `syclcompat::detail::fill` and `syclcompat::detail::memcpy` define SYCL kernels. Any translation unit including the `memory.hpp` or `util.hpp` headers will contain these kernels, as DPC++'s 2-pass compiler is not currently able to reason about which kernels are actually used.
Adding a dummy template parameter (typename T = void) ensures that these functions (and thus their kernels) are only instantiated if used.
=> [SYCL][COMPAT] Add dummy template params to memory APIs to delay kernel instantiation

unified-runtime/source/adapters/level_zero/v2/command_buffer.cpp, unified-runtime/source/adapters/level_zero/v2/command_buffer.hpp, unified-runtime/source/adapters/level_zero/v2/command_list_manager.cpp, unified-runtime/source/adapters/level_zero/v2/command_list_manager.hpp, unified-runtime/source/adapters/level_zero/v2/queue_immediate_in_order.cpp, unified-runtime/source/adapters/level_zero/v2/queue_immediate_in_order.hpp, unified-runtime/test/conformance/exp_command_buffer/fill.cpp, unified-runtime/test/conformance/exp_command_buffer/fixtures.h, unified-runtime/test/conformance/exp_command_buffer/update/invalid_update.cpp
According to @MichalMrozek, zeCommandListImmediateAppendCommandListsExp has the same requirements as zeCommandQueueExecuteCommandLists, because of this, the command list must not be referenced by device when it is enqueued. This PR fixes this issue by adding event to synchronize append and execution
=> [UR] [V2] Add wait before enqueue in command buffer

sycl/test-e2e/KernelCompiler/opencl.cpp, sycl/test-e2e/KernelCompiler/sycl.cpp, sycl/test-e2e/KernelCompiler/sycl_device_globals.cpp
We don't need to run twice (once with leak check, once without).  If the leak check isn't there, it still runs
=> [SYCL] Reduce test time for kernel compiler tests

devops/scripts/benchmarks/benches/compute.py
Meaning 'SubmitKernel' benchmarks are now grouped into: "SubmitKernel In Order", "SubmitKernel Out of Order" + "With Completion" variants.
=> [CI][Benchmarks] rename SubmitKernel group to include order

devops/scripts/benchmarks/benches/base.py, devops/scripts/benchmarks/benches/compute.py, devops/scripts/benchmarks/html/index.html, devops/scripts/benchmarks/html/scripts.js, devops/scripts/benchmarks/utils/result.py
This is useful for more accurate comparisons between multiple labels.
=> [CI][Benchmarks] add an option to adjust y-axis per benchmark

sycl/test-e2e/lit.cfg.py
The `shlex.quote` API doesn't do the right thing on Windows and that is documented [here](https://docs.python.org/3/library/shlex.html#shlex.quote), so do it manually.
Manually verified it's broken without this change and this fixes it.
I looked and couldn't find any single utility that covers this functionality.
=> [SYCL][E2E] Fix SDK detection on Windows

sycl/include/sycl/vector.hpp, sycl/test/basic_tests/vectors/cxx_conversions.cpp
Implements https://github.com/KhronosGroup/SYCL-Docs/pull/669.
=> [SYCL] Add vec explicit conversion

sycl/tools/sycl-ls/sycl-ls.cpp, unified-runtime/source/common/linux/ur_lib_loader.cpp
Log sycl-ls adapter errors in verbose mode. Additionally, inform the user about verbose mode when no platforms are found.
=> [SYCL][UR] Log sycl-ls adapter errors in verbose mode

devops/dependencies.json
Theory from [here](https://github.com/intel/llvm/pull/17774#issuecomment-2769890613) is we need to match the version from [here](https://github.com/intel/compute-runtime/blob/25.09.32961.7/manifests/manifest.yml#L50-L56).
=> [CI] Bump Level Zero version to 1.20.6

devops/dependencies.json
Reverts intel/llvm#17778
Same problem
=> Revert "[CI] Bump Level Zero version to 1.20.6"
