sycl/include/CL/sycl/id.hpp
sycl/include/CL/sycl/range.hpp

This should be a NFC, refactoring the hardcoded operators in the range 
and id classes into macros to generate them so that the classes are a 
little more concise to read.

[SYCL][NFC] id.hpp & range.hpp operator tidyup

---

sycl/source/detail/program_manager/program_manager.cpp

Remove redundant call to fix https://github.com/intel/llvm/issues/26

[SYCL] Remove redundant call

---

buildbot/configure.sh

[SYCL] do clean build if incremental cmake command failed

---

sycl/include/CL/sycl/types.hpp
sycl/test/basic_tests/vectors.cpp

[SYCL] Implement broadcasting vec::operator=

---

clang/include/clang/Driver/Options.td
clang/lib/Driver/Driver.cpp
clang/lib/Driver/ToolChains/Clang.cpp
clang/lib/Driver/ToolChains/Gnu.cpp
clang/lib/Driver/ToolChains/SYCL.cpp
clang/lib/Driver/ToolChains/SYCL.h
clang/test/Driver/openmp-offload.c
clang/test/Driver/sycl-offload.c

Signed-off-by: Michael Toguchi <michael.d.toguchi@intel.com>

[SYCL][OpenMP] Add driver support for fat archives

---

sycl/include/CL/sycl/detail/program_impl.hpp

[SYCL] Updating program compile, link and build options per spec clarifications

---

sycl/include/CL/sycl/buffer.hpp

[SYCL][NFC] Remove return from void function

---

sycl/doc/extensions/sub_group_ndrange/sub_group_ndrange.md

Signed-off-by: John Pennycook <john.pennycook@intel.com>

[SYCL] Add ND-range sub-group extension docs

---

clang/lib/Sema/SemaSYCL.cpp
clang/test/CodeGenSYCL/Inputs/sycl.hpp
clang/test/CodeGenSYCL/integration_header.cpp
clang/test/CodeGenSYCL/sampler.cpp
clang/test/SemaSYCL/Inputs/sycl.hpp
clang/test/SemaSYCL/sampler.cpp
sycl/CMakeLists.txt
sycl/include/CL/__spirv/spirv_types.hpp
sycl/include/CL/sycl.hpp
sycl/include/CL/sycl/detail/sampler_impl.hpp
sycl/include/CL/sycl/detail/scheduler/commands.cpp
sycl/include/CL/sycl/sampler.hpp
sycl/source/detail/sampler_impl.cpp
sycl/source/sampler.cpp
sycl/test/basic_tests/sampler/sampler.cpp

[SYCL] sampler implementation

---

sycl/include/CL/sycl/multi_ptr.hpp

[SYCL] updated multi_ptr implementation, added const void specialization

---

sycl/include/CL/sycl/detail/cg.hpp
sycl/source/detail/scheduler/commands2.cpp

Pass nullptr if work group size is not provided by user.

[SYCL] Fixed intialization of work group size.

---

sycl/include/CL/sycl/detail/sampler_impl.hpp

[SYCL] Default member variable initialization of m_Sampler

---

sycl/CMakeLists.txt

[SYCL] fix misprint in cmake target.

---

sycl/ReleaseNotes.md

[SYCL] Release notes for May'19 release.

---

sycl/doc/GetStartedWithSYCLCompiler.md

[SYCL] Add info about experimental RT to doc.

---

sycl/source/detail/sampler_impl.cpp

1. Using CHECK_OCL_CODE_NO_EXC in ~sampler_impl and
2. Adding clCreateSamplerWithProperties to use when clCreateSampler is
deprecated

[SYCL] Fixing compiler warnings in sampler implementation

---

sycl/include/CL/sycl/buffer.hpp

[SYCL] fix two buffer constructors

---

sycl/test/basic_tests/swizzle_op.cpp
sycl/test/functor/kernel_functor.cpp

Signed-off-by: Alexey Voronov <alexey.voronov@intel.com>

[SYCL] Enable swizzle_op and kernel_functor tests on non host devices.

---

sycl/test/sub_group/helper.hpp
sycl/test/sub_group/load_store.cpp

Also updated results checking using ULP due half type precision
limitations.

[SYCL] Enable sub-group load_store test on GPU

---

sycl/include/CL/sycl/handler.hpp
sycl/test/kernel-and-program/kernel-and-program.cpp

Signed-off-by: Alexey Voronov <alexey.voronov@intel.com>

[SYCL] Enable sampler support in set_arg(s) method.

---

sycl/include/CL/sycl/handler.hpp

[SYCL] Fix build after old scheduler removal

---

sycl/ReleaseNotes.md

[SYCL] Release notes for June'19 release.

---

sycl/include/CL/sycl/buffer.hpp
sycl/source/detail/scheduler/commands.cpp
sycl/source/detail/stream_impl.cpp

* Warnings were fixed.
* Bug in assertion was fixed.

[SYCL] Minor fixes after stream class implementation.

---

sycl/include/CL/sycl/detail/buffer_impl.hpp
sycl/test/basic_tests/buffer/buffer.cpp

[SYCL] Enable set_final_data for shared_ptr

---

sycl/doc/extensions/usm/usm.adoc

[SYCL] Fix typo in USM extension specification

---

sycl/test/basic_tests/stream.cpp

[SYCL] Temporary disable stream LIT test.

---

CONTRIBUTING.md
sycl/doc/GetStartedWithSYCLCompiler.md

- Add development process description to contributing guide
- Add info about skipping LIT tests targetting OpenCL device
if corresponding RT is missed.

[SYCL] Update documents with recent project changes

---

sycl/include/CL/sycl/accessor.hpp

It looks like in the following case:
template<int T>
some_class_method(typename std::enable_if<[some type of the argument],
[some condition that doesn't depend on T] && T != 1>::type Arg) {
...
}
MSVC emits the error:
'type': is not a member of of any direct or indirect base class of
'std::enable_if<false,...'
This could be work arounded by changing the order of && arguments.
Probably the reason is that of first argument of && is false then we
don't even take into account the second argument.

[SYCL] Fix SFINAE for accessor class to work with MSVC

---

sycl/include/CL/sycl/detail/buffer_impl.hpp

[SYCL] Make buffer iterator c'tors SFINAE friendly

---

sycl/source/detail/builtins.cpp

This is for SYCL Windows build

[SYCL] Fixing warnings "unsafe use of type bool in operation"

---

README.md

This should help to get consistent links in the forks.

[SYCL][NFC] Make links in README relative to the repository

---

clang/include/clang/Basic/Attr.td
clang/include/clang/Basic/AttrDocs.td
clang/include/clang/Basic/DiagnosticSemaKinds.td
clang/lib/CodeGen/CodeGenModule.cpp
clang/lib/Sema/SemaDeclAttr.cpp
clang/test/CodeGenSYCL/intel-fpga-local.cpp
clang/test/SemaSYCL/intel-fpga-local.cpp

Signed-off-by: Viktoria Maksimova <viktoria.maksimova@intel.com>

[SYCL][FPGA] Enable merge, max_replicates and simple_dual_port attributes

---

sycl/source/detail/platform_impl.cpp

[SYCL] Fix platform selection with no OpenCL platforms available

---

sycl/include/CL/__spirv/spirv_types.hpp
sycl/include/CL/sycl/detail/helpers.hpp

Signed-off-by: Alexey Sachkov <alexey.sachkov@intel.com>

[NFC] Make getSPIRVMemorySemantics constexpr

---

sycl/include/CL/sycl/detail/stream_impl.hpp
sycl/include/CL/sycl/stream.hpp
sycl/test/basic_tests/stream.cpp

[SYCL] Enhance SYCL stream to support h_item

---

sycl/test/aot/with-llvm-bc.cpp

...  for more friendly diagnostics in case an exception is raised in kernel.
Signed-off-by: Sergey Zverev <sergey.i.zverev@intel.com>

[SYCL] Update for aot/with-llvm-bc.cpp to catch exceptions.

---

clang/test/CodeGenSYCL/unique-stable-name.cpp

Adjust to new address space handing rules for raw pointers.

[SYCL] Fix unique-stable-name test after rebase

---

sycl/CMakeLists.txt
sycl/include/CL/cl_usm_ext.h
sycl/include/CL/sycl/detail/clusm.hpp
sycl/source/detail/usm/clusm.cpp
sycl/source/detail/usm/opencl_shim.cpp
sycl/test/usm/clext.cpp
sycl/test/usm/clusm.cpp

Implements OpenCL Extension for USM (cl_usm_ext.h).
Attempts to use native support for the extension, if it exists.  If not, CLUSM implements the extension over OpenCL 2.0 SVM.

[SYCL][USM] Initial commit for OpenCL Shim and CLUSM.

---

clang/include/clang/Sema/Sema.h
clang/lib/Parse/ParseAST.cpp
clang/lib/Sema/SemaSYCL.cpp
clang/test/CodeGenSYCL/device-variables.cpp

[SYCL] Add global variables to device code

---

sycl/include/CL/sycl/types.hpp

Replace loops in vector class device code implementation with vector code.

[SYCL] Vector class minor fixes and optimizations

---

sycl/test/basic_tests/stream.cpp

[SYCL] Enable stream lit test on CPU

---

sycl/test/lit.site.cfg.in

[SYCL] Fix lit config for Windows

---

sycl/include/CL/sycl/accessor.hpp
sycl/source/detail/program_manager/program_manager.cpp

Signed-off-by: KarachunIvan <ivan.karachun@intel.com>

[SYCL] Minor build fixes

---

sycl/include/CL/sycl/accessor.hpp

host_image.
- tests to be added after scheduler support is added for image class.
Signed-off-by: Garima Gupta <garima.gupta@intel.com>

[SYCL] Support for read_write access mode for accessors with target

---

sycl/test/basic_tests/buffer/buffer_dev_to_dev.cpp
sycl/test/basic_tests/group.cpp
sycl/test/basic_tests/id.cpp
sycl/test/basic_tests/item.cpp
sycl/test/basic_tests/nd_item.cpp
sycl/test/basic_tests/nd_range.cpp
sycl/test/basic_tests/platform.cpp
sycl/test/basic_tests/queue.cpp
sycl/test/basic_tests/range.cpp
sycl/test/basic_tests/sampler/sampler.cpp
sycl/test/basic_tests/vectors.cpp

Signed-off-by: Klochkov <vyacheslav.n.klochkov@intel.com>

[SYCL][NFC] Fix obsolete compilation style used in some LIT tests

---

sycl/include/CL/cl_usm_ext.h

A conflict was discovered for the initial values.  Updated to resolve.

[SYCL][USM] Update enum values.

---

sycl/include/CL/sycl/detail/os_util.hpp
sycl/include/CL/sycl/detail/pi.hpp
sycl/source/CMakeLists.txt

Signed-off-by: Klochkov <vyacheslav.n.klochkov@intel.com>

[SYCL] Use dllimport for Plugin Interface globals

---

sycl/include/CL/sycl/group.hpp
sycl/test/hier_par/hier_par_basic.cpp

[SYCL] Implement cl::sycl::private_memory class.

---

sycl/include/CL/sycl/detail/clusm.hpp

Signed-off-by: Klochkov <vyacheslav.n.klochkov@intel.com>

[SYCL] Fix unresolved reference in USM module on Windows

---

sycl/include/CL/sycl/accessor.hpp
sycl/test/basic_tests/accessor/addrspace_exposure.cpp

[SYCL] Fix accessor exposing concrete address space pointers/references

---

sycl/source/detail/scheduler/commands.cpp
sycl/test/usm/depends_on.cpp

[SYCL] Simplify event checking and bug fix.

---

sycl/include/CL/sycl/detail/common.hpp

[SYCL] Fix stability issue - taking a reference of a temporary object.

---

llvm/test/tools/llvm-objcopy/COFF/add-section.test
llvm/tools/llvm-objcopy/COFF/COFFObjcopy.cpp

[llvm-objcopy] Added support for --add-section=... option for COFF

---

sycl/doc/extensions/usm/README.md
sycl/doc/extensions/usm/cl_intel_unified_shared_memory.asciidoc

[SYCL][DOC] Initial add for CL ext for USM

---

clang/lib/Sema/SemaType.cpp
clang/test/SemaSYCL/sycl-cconv.cpp

[SYCL] Supress diagnostic about variadic function declaration

---

sycl/include/CL/sycl/context.hpp
sycl/include/CL/sycl/detail/context_impl.hpp
sycl/include/CL/sycl/detail/queue_impl.hpp
sycl/include/CL/sycl/exception.hpp
sycl/include/CL/sycl/exception_list.hpp
sycl/include/CL/sycl/queue.hpp
sycl/source/CMakeLists.txt
sycl/source/context.cpp
sycl/source/detail/context_impl.cpp
sycl/source/exception.cpp
sycl/source/exception_list.cpp
sycl/source/queue.cpp

- Align exception_list class with SYCL specification.
- Move exception_list class to separate file

[SYCL][NFC] Refactoring exception_list class 

---

sycl/source/detail/os_util.cpp

Signed-off-by: Narayanaswamy <ravi.narayanaswamy@intel.com>

[SYCL] Add support for Windows getOSModuleHandle

---

sycl/include/CL/__spirv/spirv_vars.hpp
sycl/include/CL/sycl/detail/cg.hpp
sycl/include/CL/sycl/detail/common.hpp
sycl/include/CL/sycl/detail/helpers.hpp
sycl/include/CL/sycl/group.hpp
sycl/include/CL/sycl/handler.hpp
sycl/test/basic_tests/group.cpp
sycl/test/regression/group.cpp

- Fix group::get_group_range to return correct range based on proper SPIRV built-in

Fix group::get_group_range and get_linear_id() bugs

---

sycl/include/CL/sycl/types.hpp

When such an operator is called for a 1-element vector, the latter
is implicitly casted to a scalar, and only then is the operation
performed. Thereby, a scalar 0/1 logic is followed for a vector case,
which requires 0/-1 return value instead.
In future, SYCL may have to enforce scalar behaviour for 1-element vector,
thus avoiding any ambiguities.
Co-authored by Alexey Bader <alexey.bader@intel.com>

[SYCL] Fix vector class relational/logical operations for length 1

---

sycl/test/sub_group/info.cpp

[SYCL] Make sub_group info test running on CPU

---

sycl/test/separate-compile/test.cpp

[SYCL] Adjust sycl/test/separate-compile/test.cpp for Windows

---

sycl/include/CL/sycl/detail/context_impl.hpp
sycl/include/CL/sycl/detail/program_manager/program_manager.hpp
sycl/include/CL/sycl/detail/scheduler/commands.hpp
sycl/include/CL/sycl/detail/scheduler/scheduler.hpp
sycl/source/detail/context_impl.cpp
sycl/source/detail/event_impl.cpp
sycl/source/detail/program_manager/program_manager.cpp
sycl/source/detail/scheduler/graph_builder.cpp
sycl/source/detail/scheduler/scheduler.cpp
sycl/test/scheduler/ReleaseResourcesTest.cpp

Added releasing for scheduler commands, programs and kernels.

[SYCL] Fix memory leaks in SYCL RT

---

sycl/test/basic_tests/image_array.cpp
sycl/test/hier_par/hier_par_wgscope.cpp

[SYCL][NFC] Do not enforce -std=c++11 for 2 LIT tests on Windows

---

sycl/include/CL/sycl/detail/pi.h
sycl/source/detail/pi_opencl.cpp
sycl/source/detail/program_manager/program_manager.cpp
sycl/test/scheduler/ReleaseResourcesTest.cpp

Signed-off-by: Ivan Karachun <ivan.karachun@intel.com>

[SYCL] Fixed return of uninitialized cl_program from PI

---

sycl/include/CL/sycl/detail/os_util.hpp
sycl/source/detail/os_util.cpp

Signed-off-by: Yu <jennifer.yu@intel.com>

[SYCL] Fix unresolved reference for ExeModuleHandle.

---

sycl/test/scheduler/MultipleDevices.cpp

Previous scenario:
data was transferred from host and cpu devices
Added new scenatio:
data is transferred between two cpu devices.

[SYCL] Refactor MultipleDevices test

---

sycl/source/detail/program_manager/program_manager.cpp

is_compiler_available may be false if there is no JIT compiler
available.  One example is an FPGA.  If loadProgram finds a SPIR-V or
LLVM BC image, it will eventually call createProgramWithIL, which may
not be supported on a device.
For non-native images, check that at least one Device in the Context
supports is_compiler_available.  If not, throw a feature_not_supported
exception. For a SPIR-V image, check that compiler for IL is available.
Signed-off-by: Mark Mendel <mark.p.mendell@intel.com>

[SYCL] Throw if loadProgram of SPIR-V/BC and no compiler available

---

sycl/source/detail/scheduler/scheduler.cpp

[SYCL] Fix data races in scheduler

---

sycl/source/detail/builtins_common.cpp
sycl/source/detail/builtins_math.cpp

[SYCL] Fix unresolved references to half type builtins on Windows

---

sycl/test/basic_tests/stream.cpp

[SYCL] Fix pointer checks in stream lit test

---

sycl/include/CL/sycl/handler.hpp
sycl/test/basic_tests/set_arg_interop.cpp

Let USM pointers work with Interop.

[SYCL][USM] Enable USM with interop

---

sycl/test/usm/clext.cpp
sycl/test/usm/clusm.cpp
sycl/test/usm/findplatforms.hpp

[SYCL][USM] Fix tests to deal with multiple CLs being installed

---

sycl/include/CL/sycl/detail/stream_impl.hpp

[SYCL] Remove unnecessary array initializations in stream class

---

sycl/include/CL/sycl/detail/kernel_desc.hpp
sycl/test/regression/kernel_name_class.cpp

[SYCL] Allow bool as kernel name

---

clang/include/clang/Basic/Attr.td
clang/include/clang/Basic/AttrDocs.td
clang/include/clang/Basic/DiagnosticSemaKinds.td
clang/lib/CodeGen/CodeGenFunction.cpp
clang/lib/Sema/SemaDeclAttr.cpp
clang/test/CodeGenSYCL/device-indirectly-callable-attr.cpp
clang/test/Misc/pragma-attribute-supported-attributes-list.test
clang/test/SemaSYCL/device-indirectly-callable-attr.cpp

See documentation in AttrDocs.td
Signed-off-by: Alexey Sachkov <alexey.sachkov@intel.com>

[SYCL] Add intel::device_indirectly_callable attribute

---

sycl/ReleaseNotes.md

[SYCL] Release notes for August SYCL implementation update

---

sycl/include/CL/sycl/detail/generic_type_traits.hpp
sycl/test/usm/math.cpp

Signed-off-by: Joshua Cranmer <joshua.cranmer@intel.com>

[SYCL] Add support for regular pointers to math functions for USM.

---

sycl/test/scheduler/MultipleDevices.cpp

[SYCL] Fix expected exception type in MultipleDevices

---

clang/lib/Driver/ToolChains/Clang.cpp
clang/test/Preprocessor/sycl-macro.cpp
clang/test/Preprocessor/sycl-macro2.cpp
clang/test/SemaSYCL/delayed-parsing.cpp
clang/test/SemaSYCL/delayed-parsing2.cpp

This is a continuation of: intel/llvm#446

[SYCL] Windows MS-Compatibility changes

---

sycl/test/hier_par/hier_par_basic.cpp
sycl/test/hier_par/hier_par_wgscope.cpp

[SYCL] Enable hier LIT test on GPU device.

---

clang/test/Driver/sycl.c

Signed-off-by: Michael D Toguchi <michael.d.toguchi@intel.com>

[SYCL] Improve phase testing for -fsycl-device-only

---

sycl/source/detail/context_impl.cpp

[SYCL] Fix an error message reported by context::get()

---

clang/test/Driver/sycl-offload-tempfile.cpp

Signed-off-by: Michael D Toguchi <michael.d.toguchi@intel.com>

[SYCL] Update tempfile test to only use driver output and FileCheck

---

sycl/include/CL/sycl/detail/cg.hpp
sycl/include/CL/sycl/group.hpp
sycl/test/hier_par/hier_par_basic.cpp
sycl/test/hier_par/hier_par_wgscope.cpp
sycl/test/regression/group.cpp

Signed-off-by: Gainullin <artur.gainullin@intel.com>

[SYCL] Fix memory leaks

---

clang/lib/Driver/Driver.cpp
clang/lib/Driver/ToolChains/Clang.cpp
clang/lib/Driver/ToolChains/CommonArgs.cpp
clang/lib/Driver/ToolChains/Gnu.cpp
clang/lib/Driver/ToolChains/Gnu.h
clang/lib/Driver/ToolChains/MSVC.cpp
clang/lib/Driver/ToolChains/MSVC.h
clang/lib/Driver/ToolChains/SYCL.cpp

[SYCL][NFC] Apply clang-format against [32f0cd57c8982]

---

sycl/include/CL/sycl/buffer.hpp
sycl/test/basic_tests/buffer/reinterpret.cpp

Before this patch `reinterpret` method didn't take into account new
shape and offset. This patch partially solves this problem.  For now,
`reinterpret` method recalculates an offset in elements of reinterpreted type.
Currently this way works only for 1D to 1D subbuffer reinterpretation.
To enable all sorts of reinterpretation (from any dimension to
any dimension with different types) some significant changes needs to be done
in SYCL runtime library

[SYCL] Subbuffer reinterpretation

---

sycl/doc/extensions/USM/USM.adoc

[SYCL][USM] Fix documentation bug.

---

sycl/include/CL/sycl/detail/array.hpp

Signed-off-by: Mikhail Lychkov <mikhail.lychkov@intel.com>

[SYCL] Improve cl::sycl::detail::array default constructors code

---

sycl/source/detail/program_manager/program_manager.cpp

https://www.khronos.org/registry/OpenCL/sdk/2.1/docs/man/xhtml/cl_khr_il_program.html

[SYCL] Fix typo in Program Manager

---

sycl/test/basic_tests/sampler/sampler.cpp

[SYCL][NFC] Fix typo in the comments

---

sycl/include/CL/sycl.hpp
sycl/include/CL/sycl/detail/queue_impl.hpp
sycl/include/CL/sycl/detail/stream_impl.hpp
sycl/include/CL/sycl/info/info_desc.hpp
sycl/include/CL/sycl/ordered_queue.hpp
sycl/source/CMakeLists.txt
sycl/source/detail/scheduler/scheduler.cpp
sycl/source/ordered_queue.cpp
sycl/source/queue.cpp
sycl/test/basic_tests/ordered_buffs.cpp
sycl/test/basic_tests/ordered_queue.cpp
sycl/test/usm/ordered_dmemll.cpp

Signed-off-by: Dounia <dounia.khaldi@intel.com>

[SYCL][USM] Add ordered queue extension

---

sycl/include/CL/sycl/detail/boolean.hpp
sycl/include/CL/sycl/types.hpp
sycl/test/basic_tests/swizzle_op.cpp

Signed-off-by: Alexey Voronov <alexey.voronov@intel.com>

[SYCL] Fix vec<T, 3> the underlying type.

---

sycl/test/basic_tests/sampler/sampler.cpp
sycl/test/regression/image_access.cpp

[SYCL] Skip sampler and image_access tests for ACC device

---

sycl/test/built-ins/vector_math.cpp

Revert "[SYCL] Disable failing test to unblock CI process"
This reverts commit dbca9c4bec8a73bb33fbbe6cecbad610f5316065.

[SYCL][NFC] Re-enable failing lit test

---

sycl/include/CL/sycl/detail/cg.hpp
sycl/test/basic_tests/parallel_for_range.cpp

Signed-off-by: Joshua Cranmer <joshua.cranmer@intel.com>

[SYCL] Throw an error instead of assert/SIGFPE on bad range sizes.

---

clang/lib/Basic/Targets/SPIR.h
sycl/test/hier_par/hier_par_basic.cpp
sycl/test/hier_par/hier_par_wgscope.cpp
sycl/test/usm/allocator_vector.cpp
sycl/test/usm/allocator_vector_fail.cpp
sycl/test/usm/allocatorll.cpp
sycl/test/usm/clusm.cpp
sycl/test/usm/depends_on.cpp
sycl/test/usm/dmemll.cpp
sycl/test/usm/dmemllaligned.cpp
sycl/test/usm/hmemll.cpp
sycl/test/usm/hmemllaligned.cpp
sycl/test/usm/memadvise.cpp
sycl/test/usm/memcpy.cpp
sycl/test/usm/memset.cpp
sycl/test/usm/mixed.cpp
sycl/test/usm/ordered_dmemll.cpp
sycl/test/usm/smemll.cpp
sycl/test/usm/smemllaligned.cpp

Signed-off-by: Melanie Blower <melanie.blower@intel.com>

[SYCL]  resetDataLayout bug on win64, pointer width should be 64 not 32

---

sycl/test/basic_tests/image.cpp

[SYCL] Enable LIT image.cpp

---

sycl/doc/GetStartedWithSYCLCompiler.md

[SYCL][DOC] Add notes for low level runtime setup/installation

---

sycl/source/detail/builtins_integer.cpp
sycl/test/built-ins/scalar_integer.cpp
sycl/test/built-ins/vector_integer.cpp

[SYCL] Fix for cl::sycl::sub_sat() issue on host

---

sycl/doc/extensions/USM/USM.adoc

Missed an update to the doc from pointer to reference

Update doc to reflect API

---

sycl/ReleaseNotes.md

[SYCL] Release notes for September SYCL implementation update

---

sycl/source/detail/builtins_integer.cpp
sycl/test/built-ins/scalar_integer.cpp

This patch fixes incorrect handling of negative arguments in host
implementation of the mul_hi built-in.

[SYCL] Fix the mul_hi built-in on host device

---

sycl/include/CL/sycl/detail/aligned_allocator.hpp
sycl/include/CL/sycl/detail/memory_manager.hpp
sycl/include/CL/sycl/detail/queue_impl.hpp
sycl/include/CL/sycl/ordered_queue.hpp
sycl/include/CL/sycl/queue.hpp
sycl/source/detail/memory_manager.cpp
sycl/source/detail/queue_impl.cpp
sycl/source/detail/usm/usm_impl.cpp
sycl/test/usm/allocator_vector.cpp
sycl/test/usm/allocator_vector_fail.cpp
sycl/test/usm/allocatorll.cpp
sycl/test/usm/depends_on.cpp
sycl/test/usm/dmemll.cpp
sycl/test/usm/dmemllaligned.cpp
sycl/test/usm/hmemll.cpp
sycl/test/usm/hmemllaligned.cpp
sycl/test/usm/math.cpp
sycl/test/usm/memadvise.cpp
sycl/test/usm/mixed.cpp
sycl/test/usm/smemll.cpp
sycl/test/usm/smemllaligned.cpp

Enable USM on HOST device.  Run USM tests on HOST device.

[SYCL][USM] Enable USM on HOST device

---

buildbot/configure.py

[SYCL][Buildbot] Enable build with asserts in CI

---

sycl/include/CL/sycl/types.hpp

Signed-off-by: Alexey Voronov <alexey.voronov@intel.com>

[SYCL] Add a requirement for "as" method return type of vec class.

---

sycl/doc/extensions/USM/cl_intel_unified_shared_memory.asciidoc
sycl/include/CL/cl_usm_ext.h

[SYCL][DOC][USM] Update CL USM Extension from Rev E to Rev G and update header.

---

sycl/include/CL/sycl/detail/aligned_allocator.hpp
sycl/include/CL/sycl/detail/array.hpp
sycl/include/CL/sycl/detail/buffer_impl.hpp
sycl/include/CL/sycl/detail/clusm.hpp
sycl/include/CL/sycl/detail/device_impl.hpp
sycl/include/CL/sycl/detail/event_impl.hpp
sycl/include/CL/sycl/detail/kernel_impl.hpp
sycl/include/CL/sycl/detail/kernel_info.hpp
sycl/include/CL/sycl/detail/os_util.hpp
sycl/include/CL/sycl/detail/pi.hpp
sycl/include/CL/sycl/detail/platform_impl.hpp
sycl/include/CL/sycl/detail/program_manager/program_manager.hpp
sycl/include/CL/sycl/detail/stream_impl.hpp
sycl/include/CL/sycl/intel/sub_group.hpp
sycl/include/CL/sycl/intel/sub_group_host.hpp
sycl/source/detail/context_impl.cpp
sycl/source/detail/device_impl.cpp
sycl/source/detail/device_info.cpp
sycl/source/detail/force_device.cpp
sycl/source/event.cpp
sycl/source/platform.cpp
sycl/source/spirv_ops.cpp

[SYCL][NFC] Align include order with LLVM coding guidelines

---

sycl/include/CL/sycl/detail/pi.hpp
sycl/include/CL/sycl/half_type.hpp
sycl/include/CL/sycl/types.hpp

[SYCL][NFC] Add parentheses around macro parameters

---

sycl/include/CL/sycl/detail/cg.hpp
sycl/include/CL/sycl/detail/memory_manager.hpp
sycl/include/CL/sycl/detail/usm_dispatch.hpp
sycl/include/CL/sycl/handler.hpp
sycl/include/CL/sycl/ordered_queue.hpp
sycl/include/CL/sycl/queue.hpp
sycl/source/detail/memory_manager.cpp
sycl/source/detail/scheduler/commands.cpp
sycl/source/detail/usm/usm_dispatch.cpp
sycl/test/usm/prefetch.cpp

Signed-off-by: Joshua Cranmer <joshua.cranmer@intel.com>

[SYCL] [USM] Implement prefetch.

---

sycl/include/CL/sycl/accessor.hpp

[SYCL] Stop placeholder accessor acting like host accessor.

---

sycl/test/basic_tests/host_image_accessor_read.cpp

Avoid having two host accessor simultaneously.

[SYCL] Fix host_image_accessor_read

---

buildbot/configure.py

Signed-off-by: Xiaodong, Li <xiaodong.li@intel.com>
Modify for cmake install

[SYCL CI] Add CMAKE_INSTALL_PREFIX for compilation

---

sycl/doc/extensions/USM/USM.adoc

[SYCL][DOC][USM] Fix bug in example

---

sycl/include/CL/sycl/detail/usm_impl.hpp
sycl/include/CL/sycl/usm/usm_allocator.hpp
sycl/source/detail/usm/usm_impl.cpp
sycl/test/usm/mixed2.cpp

malloc(... kind) when kind == host wasn't using the right method.

[SYCL][USM] Fix bug with malloc(..., kind) impl and host allocations

---

clang/lib/Driver/ToolChains/Clang.cpp

[SYCL][Driver][NFC] Fix typo in comment

---

sycl/CMakeLists.txt

[SYCL] Deploy SYCL RT with toolchain

---

sycl/test/basic_tests/half_type.cpp

[SYCL] Allow test execution on machines with multiple RTs

---

clang/test/Driver/clang-offload-wrapper.c
clang/tools/clang-offload-wrapper/ClangOffloadWrapper.cpp

This patch adds "-entries" option to clang-offload-wrapper which allows
to specify a file listing all function entries that are contained within
an image. This file is generated by the sycl-post-link tool and the entry
table will then be used in SYCL runtime to select a binary based on the
requested kernel.

[SYCL] Add entry table generation by wrapper for SYCL offload

---

sycl/CMakeLists.txt

[SYCL] Add missed tool to deploy list

---

sycl/CMakeLists.txt

[SYCL] Add pi_opencl library to the deploy list

---

sycl/test/lit.cfg.py

Fix some LIT tests after
https://github.com/intel/llvm/commit/0d4e6519c5dd81034935d4da9c519c17e41b1202

[SYCL] Update LIT config

---

sycl/doc/extensions/KernelRestrictAll/README.md
sycl/doc/extensions/KernelRestrictAll/SYCL_INTEL_kernel_restrict_all.asciidoc
sycl/doc/extensions/UnnamedKernelLambda/README.md
sycl/doc/extensions/UnnamedKernelLambda/SYCL_INTEL_unnamed_kernel_lambda.asciidoc

Signed-off-by: Michael Kinsner <michael.kinsner@intel.com>

[SYCL][Doc] Add two extension drafts (unnamed lambda and kernel restrict all)

---

clang/lib/Sema/SemaDeclAttr.cpp
clang/test/SemaSYCL/sycl-cconv.cpp

[SYCL] Suppress warning about cdecl calling convention on host

---

clang/lib/Driver/Driver.cpp

[SYCL][Driver][NFC] Drop obsolete function calls

---

sycl/include/CL/__spirv/spirv_ops.hpp
sycl/include/CL/sycl/intel/sub_group.hpp
sycl/test/sub_group/load_store.cpp

Signed-off-by: Dounia <dounia.khaldi@intel.com>

[SYCL] Add support of 1 byte type to load and store subgroup operations

---

clang/lib/Sema/SemaSYCL.cpp

- Remove dead code
- Move code to keep it structured by the components: integration header
generation, OpenCL kernel generation, Semantic Analysis, etc.
- Fix typos and alignment
- Apply clang-format

[SYCL][NFC] Refactor SemaSYCL.cpp to improve readability

---

sycl/doc/GetStartedWithSYCLCompiler.md

[SYCL][Doc] Add instruction for setting FPGA emulator device

---

sycl/doc/SYCLCompilerAndRuntimeDesign.md

[NFC][SYCL][Doc] Improve OpenCL kernel generation doc

---

sycl/include/CL/sycl/detail/context_info.hpp
sycl/include/CL/sycl/detail/device_impl.hpp
sycl/include/CL/sycl/detail/device_info.hpp
sycl/include/CL/sycl/detail/event_info.hpp
sycl/include/CL/sycl/detail/kernel_info.hpp
sycl/include/CL/sycl/detail/platform_impl.hpp
sycl/include/CL/sycl/detail/platform_info.hpp
sycl/source/detail/context_impl.cpp
sycl/source/detail/device_impl.cpp
sycl/source/detail/device_info.cpp
sycl/source/detail/event_impl.cpp
sycl/source/detail/kernel_impl.cpp
sycl/source/detail/platform_impl.cpp
sycl/source/detail/scheduler/commands.cpp

[SYCL][NFC] Improve readability of info query methods

---

sycl/doc/extensions/deduction_guides/SYCL_INTEL_deduction_guides.asciidoc

Signed-off-by: Roland Schulz <roland.schulz@intel.com>

[SYCL][Doc] Add deduction guides extension

---

sycl/ReleaseNotes.md

[SYCL][Doc] Fix links to prerequisites in the release notes

---

sycl/include/CL/sycl/detail/memory_manager.hpp
sycl/include/CL/sycl/detail/scheduler/commands.hpp
sycl/include/CL/sycl/detail/scheduler/scheduler.hpp
sycl/source/detail/memory_manager.cpp
sycl/source/detail/queue_impl.cpp
sycl/source/detail/scheduler/commands.cpp
sycl/source/detail/scheduler/graph_builder.cpp

This flag is not needed anymore as the problem it was used for is
resolved.

[SYCL][NFC] Remove UseExclusiveQueue flag

---

sycl/test/hier_par/hier_par_basic.cpp
sycl/test/hier_par/hier_par_wgscope.cpp

[SYCL] Enable hierarchical lit tests on Windows for GPU

---

sycl/source/detail/pi.cpp

[SYCL][NFC] Fix "unused variable" warning

---

clang/test/CodeGenSYCL/intel-restrict.cpp

Signed-off-by: Andrew Savonichev <andrew.savonichev@intel.com>

[SYCL] Do not include sycl.hpp in clang LIT test

---

clang/include/clang/Basic/Attr.td
clang/include/clang/Basic/AttrDocs.td
clang/include/clang/Basic/DiagnosticSemaKinds.td
clang/lib/Sema/SemaDeclAttr.cpp
clang/test/CodeGenSYCL/Inputs/sycl.hpp
clang/test/CodeGenSYCL/image_accessor.cpp
clang/test/Misc/pragma-attribute-supported-attributes-list.test
clang/test/SemaSYCL/Inputs/sycl.hpp
clang/test/SemaSYCL/kernel-attribute-on-non-sycl.cpp
clang/test/SemaSYCL/kernel-attribute.cpp
clang/test/SemaSYCL/restrict-recursion.cpp
clang/test/SemaSYCL/sycl-restrict.cpp
sycl/include/CL/sycl/handler.hpp

Apply https://reviews.llvm.org/D60455.

[SYCL] Add sycl_kernel attribute diagnostics

---

clang/include/clang/Basic/AttributeCommonInfo.h
clang/test/CodeGenSYCL/reqd-sub-group-size.cpp
clang/test/SemaSYCL/reqd-sub-group-size.cpp

[SYCL] Make cl::intel_reqd_sub_group_size applicable to lambdas

---

llvm/tools/sycl-post-link/sycl-post-link.cpp

Instead of cloning full module and removing redundant definitions
from cloned module, clone only needed definitions.
This change can significantly improve device code split time for big
enough test cases.

[SYCL] Improve device code split performance

---

opencl-aot/CMakeLists.txt

Signed-off-by: Dmitry Vodopyanov <dmitry.vodopyanov@intel.com>

[SYCL][CPU] Remove extra messages in opencl-aot CMakeLists.txt

---

sycl/test/device-code-split/aot-cpu.cpp

[SYCL][NFC] Finalize the transition to opencl-aot for SYCL AOT tests

---

sycl/include/CL/sycl/detail/accessor_impl.hpp
sycl/include/CL/sycl/handler.hpp
sycl/test/basic_tests/set_arg_interop.cpp

[SYCL] Support the case when local accessor is a temporary object

---

clang/include/clang/Basic/AttrDocs.td
sycl/doc/extensions/SubGroupNDRange/SubGroupNDRange.md

[NFC][SYCL] Update doc about cl::intel_reqd_sub_group_size attribute

---

sycl/test/basic_tests/stream/auto_flush.cpp
sycl/test/basic_tests/stream/stream.cpp
sycl/test/hier_par/hier_par_basic.cpp
sycl/test/hier_par/hier_par_wgscope.cpp

[SYCL][NFC] Remove TODO comments from the already-fixed tests

---

sycl/include/CL/sycl/usm.hpp

[SYCL][NFC] Remove unused include to internal USM header

---

sycl/include/CL/sycl/queue.hpp
sycl/test/usm/pfor_flatten.cpp

[SYCL][API Simplification] Make flattened parallel_fors use const ref vecs.

---

sycl/CMakeLists.txt

[SYCL][NFC] Remove unused tools from SYCL tool chain build

---

sycl/doc/extensions/OrderedQueue/OrderedQueue_v2.adoc

New proposal meant to replace Ordered Queue.

[SYCL][DOC][Ordered Queue] Queue Property Proposal

---

sycl/doc/SYCLCompilerUserManual.md

Signed-off-by: Mariya Podchishchaeva mariya.podchishchaeva@intel.com

[SYCL][Doc] Add device code split options to user manual

---

sycl/doc/extensions/USM/cl_intel_unified_shared_memory.asciidoc

Signed-off-by: Ben Ashbaugh <ben.ashbaugh@intel.com>

Update CL USM Extension from Rev G to Rev O

---

sycl/include/CL/sycl/detail/circular_buffer.hpp
sycl/include/CL/sycl/detail/scheduler/scheduler.hpp
sycl/test/basic_tests/circular_buffer.cpp
sycl/test/scheduler/LeafLimit.cpp

[SYCL][NFC] Fix missing cstddef includes

---

clang/test/CodeGenSYCL/intel-fpga-local.cpp
clang/test/SemaSYCL/intel-fpga-local.cpp

This PR introduces changes to both sema and codegen tests.
Changes for codegen test:
* Renamed all FileCheck labels to avoid alphabetical changes in future
* Change all variables and function names to meaningful ones
* Remove duplicate test cases
Changes for sema test:
* Change all variables and function names to meaningful ones

[SYCL][FPGA] Improve intel-fpga-local tests

---

sycl/test/function-pointers/pass-fp-through-buffer.cpp

[SYCL][NFC] Remove idle space

---

sycl/doc/extensions/USM/USM.adoc

[SYCL][Doc][USM] Add refactored pointer and device queries to USM spec.

---

sycl/source/detail/os_util.cpp

[SYCL][NFC] Fix unreferenced variable warning

---

sycl/plugins/opencl/pi_opencl.cpp

[SYCL][NFC] Fix a couple of typos in the comments

---

sycl/include/CL/sycl/access/access.hpp

[SYCL][NFC] Remove dead code

---

sycl/source/detail/stream_impl.cpp

Signed-off-by: Igor Dubinov <igor.dubinov@intel.com>

[SYCL] Fix sporadic auto_flush lit tests fail

---

buildbot/testlist.cfg

[SYCL] Disable tests which take more than 5 minutes

---

sycl/test/lit.cfg.py

This will stabilize the CI system while #1262 is not resolved.

[SYCL][Test] Temporally disable LIT tests on Windows/FPGA

---

sycl/test/CMakeLists.txt

[SYCL][Test] Fix SYCL library location path for LIT tests

---

clang/lib/CodeGen/SYCLLowerIR/LowerWGScope.cpp
sycl/include/CL/sycl/device.hpp
sycl/include/CL/sycl/queue.hpp
sycl/plugins/opencl/pi_opencl.cpp
sycl/source/detail/platform_impl.hpp
sycl/source/detail/queue_impl.hpp

[SYCL][NFC] Format the code with clang-format

---

sycl/LICENSE.TXT
sycl/include/CL/sycl/handler.hpp
sycl/source/handler.cpp

Also update year in LICENSE.TXT.

[SYCL][NFC] Update copyright header in handler files

---

clang/lib/Sema/SemaSYCL.cpp

Signed-off-by: Soumi Manna <soumi.manna@intel.com>

[SYCL][NFC] Fix static code analysis concerns

---

sycl/doc/EnvironmentVariables.md

[SYCL][Doc] Mention PI_CUDA as a possible SYCL BE envvar value

---

clang/lib/CodeGen/CGLoopInfo.cpp

[SYCL][NFC] Update a misleading comment on IVDep IR generation

---

clang/lib/Driver/Driver.cpp
clang/test/Driver/sycl.c

Signed-off-by: Joshua Cranmer <joshua.cranmer@intel.com>

[SYCL] Emit textual IR when -S -fsycl-device-only is used.

---

sycl/test/ordered_queue/prop.cpp

[SYCL]: indicate direct OpenCL usage in test/ordered_queue/prop.cpp

---

sycl/include/CL/sycl/detail/pi.hpp

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=56480

[SYCL][NFC] Workaround for bug in GCC older than 7

---

sycl/CMakeLists.txt
sycl/source/CMakeLists.txt

Signed-off-by: Vyacheslav Zakharin <vyacheslav.p.zakharin@intel.com>

Make sycl depend on libsycldevice.

---

clang/lib/Sema/Sema.cpp
clang/test/SemaSYCL/inline-asm.cpp

[SYCL] Allow asm statements in kernel code.

---

sycl/source/detail/plugin.hpp
sycl/source/detail/program_manager/program_manager.cpp

[SYCL][NFC] Make the RT::PiPlugin object private

---

llvm/lib/SYCLLowerIR/LowerWGScope.cpp
llvm/test/SYCLLowerIR/byval_arg.ll
llvm/test/SYCLLowerIR/convergent.ll
llvm/test/SYCLLowerIR/pfwg_and_pfwi.ll

Implements a few code simplification/unification for LowerWGScope
Signed-off-by: Victor Lomuller <victor@codeplay.com>

[SYCL] Simplify handing of builtins in LowerWGScope

---

sycl/source/detail/program_manager/program_manager.cpp

Pending change from spec constants code review.

[SYCL] Change runtime check to assert in program_manager.cpp

---

sycl/doc/GetStartedGuide.md

[SYCL][NFC] Fix formatting in GetStartedGuide

---

.github/workflows/linux_post_commit.yml
buildbot/configure.py

Update post-commit checks to validate builds with and without
assertions.

[CI][BuildBot] Fix configure parameter to turn on/off assertions

---

.github/CODEOWNERS

[CI] Fix CODEOWNERS file syntax

---

README.md

Two badges showing status of post-commit checks on Linux and Doxygen
documentation generator.

[NFC] Add GitHub actions badges to README file

---

llvm/test/CMakeLists.txt
llvm/tools/file-table-tform/LLVMBuild.txt

Fix check-llvm dependencies

---

sycl/ReleaseNotes.md

[SYCL][Doc] Fix link to GetStartedGuide.md

---

llvm/lib/SYCLLowerIR/LowerWGScope.cpp

[SYCL] Minor fixes in LowerWGScope

---

README.md

[SYCL][Doc] Remove obsolete parens from README

---

sycl/CMakeLists.txt

[SYCL] Fix xmethod script deployment

---

.github/CODEOWNERS

[SYCL][NFC] Add code owner for reduction extension

---

sycl/doc/extensions/ExtendedAtomics/SYCL_INTEL_extended_atomics.asciidoc

Signed-off-by: John Pennycook <john.pennycook@intel.com>

[SYCL][Doc] Add memory_scope to ExtendedAtomics

---

sycl/source/detail/queue_impl.hpp

Signed-off-by: Ruyman Reyes <ruyman@codeplay.com>

[SYCL] Throw error when mismatched plugins on queue

---

clang/lib/Sema/SemaSYCL.cpp

[SYCL][NFC] Fix a few typos.

---

sycl/source/detail/program_manager/program_manager.cpp

[SYCL][NFC] Improve program_manager readability

---

sycl/include/CL/sycl/intel/sub_group.hpp
sycl/test/sub_group/load_store.cpp

Signed-off-by: Ivan Karachun <ivan.karachun@intel.com>

[SYCL] Added support of sub_group_load/store for local AS

---

sycl/doc/GetStartedGuide.md

Remove incorrect syntax specifier in Get Started Guide to fix Sphinx rendering warnings.

[SYCL][Doc] Fix Sphinx rendering

---

sycl/doc/GetStartedGuide.md
sycl/tools/install.bat

- Allow to run out of directory where it is located;
- Fix version check and diagnostics;
- Update GetStarted.md to fix naming and highlight TBB
installation on windows.

[SYCL] Fix windows OpenCL CPU RT install process

---

sycl/include/CL/sycl/detail/usm_impl.hpp

[SYCL][USM] Remove unnecessary headers from usm impl header.

---

buildbot/dependency.conf

Uplift Windows GPU version

---

buildbot/check.py
buildbot/compile.py
buildbot/configure.py
buildbot/dependency.py

Format build commands so that it be easily accessible.
Signed-off-by: yinyangsx <yin.yang@intel.com>

[BuildBot] Format build commands for CI test log

---

clang/include/clang/Sema/Sema.h
clang/test/SemaSYCL/esimd-private-glob.cpp

Signed-off-by: Denis Bakhvalov <denis.bakhvalov@intel.com>

[SYCL][ESIMD] Fix ESIMD private global detection.

---

sycl/source/detail/program_impl.cpp

Signed-off-by: Alexander Flegontov <alexander.flegontov@intel.com>

[SYCL] Fix assert when calling get_binaries() on host

---

sycl/test/check_device_code/usm_pointers.cpp

[SYCL][NFC] Fix usm_pointers.cpp test failure

---

clang/lib/Sema/SemaSYCL.cpp

This patch changes a few variable names to make the code easier to understand. 
Patch also removes code which is not required after struct decomposition support (added in commit 0b2de9ebd).
Signed-off-by: Elizabeth Andrews <elizabeth.andrews@intel.com>

[SYCL][NFC] Minor refactor for array handling in kernel body creation

---

sycl/doc/extensions/QueueShortcuts/QueueShortcuts.adoc
sycl/doc/extensions/QueueShortcuts/queue.hpp

Add generic lambda support description
Add range shortcuts description
Signed-off-by: Ruslan Arutyunyan <ruslan.arutyunyan@intel.com>

[SYCL][Doc] Modify queue shortcuts extension

---

sycl/plugins/level_zero/pi_level0.cpp

[SYCL] Fix memory leak in L0 plugin

---

llvm/lib/SYCLLowerIR/LowerWGScope.cpp

https://github.com/intel/llvm/commit/368a5e3a666ff38432be538370c46ff800fface1 
Signed-off-by: amochalo <anastasiya.mochalova@intel.com>

Replacement deprecated method

---

sycl/plugins/level_zero/pi_level0.cpp
sycl/source/detail/program_impl.cpp
sycl/source/detail/scheduler/graph_builder.cpp

[SYCL] Fix warnings from static analysis tool

---

clang/lib/CodeGen/CodeGenModule.cpp

[SYCL][NFC] Fix potential null-pointer access

---

sycl/test/hier_par/hier_par_wgscope_O0.cpp
sycl/test/sub_group/generic-shuffle.cpp

Enable LIT test which were disabled to unblock submission of PR #2148
Fixes https://github.com/intel/llvm/issues/2228

[NFC][SYCL] Enable temporarily disabled LIT tests

---

sycl/plugins/level_zero/pi_level_zero.cpp

[SYCL] Check pointer to event before dereferencing

---

buildbot/dependency.conf

Add download link for TBBs
Signed-off-by: yinyangsx <yin.yang@intel.com>

[Buildbot] Add download link for TBBs

---

sycl/doc/conf.py

[SYCL][Doc] Fix relative links handling for Sphinx

---

sycl/CMakeLists.txt

[SYCL] Deploy Level Zero loader in scope of deploy-sycl-toolchain

---

clang/lib/Driver/Driver.cpp

Signed-off-by: Harini Chilamantula <harini.chilamantula@intel.com>

[Driver][SYCL]Null Check for a dereferenced pointer

---

clang/test/CodeGenSYCL/intel-restrict.cpp

Addresses comment - https://github.com/intel/llvm/pull/2288#discussion_r470012665
Signed-off-by: Elizabeth Andrews <elizabeth.andrews@intel.com>

[SYCL][NFC] Apply clang format to a test

---

llvm/include/llvm/Support/PropertySetIO.h
llvm/lib/Support/Base64.cpp
llvm/lib/Support/PropertySetIO.cpp

[SYCL][NFC] Fix comparison warnings in Base64, PropertySetIO

---

sycl/tools/sycl-ls/CMakeLists.txt

Make the "sycl-ls" utility installed and available.

[SYCL] Install sycl-ls

---

sycl/include/CL/sycl/handler.hpp
sycl/include/CL/sycl/queue.hpp
sycl/test/usm/fill.cpp

Implements the fill operation for USM as defined in SYCL 2020 provisional.

[SYCL][USM] Initial commit of USM fill operation

---

clang/lib/Sema/SemaSYCL.cpp

In an effort to clean up the visitor/redo some array handling, I
noticed that the enter-field/leave-field mechanism is inconsistent with
the design of the visitor.  This patch starts the effort to remove it
entirely, and move the field-based dependence BACK to the individual
fields as required.
This DID require adding a field to the special visitor types for bases,
which generally seems to make these functions completely unnecessary.

[NFC][SYCL] Remove enterField/leaveField from int-header

---

sycl/doc/extensions/USM/cl_intel_unified_shared_memory.asciidoc

Fixes enum typo in table.
Fixes #2352.
Signed-off-by: Ben Ashbaugh <ben.ashbaugh@intel.com>

Update CL USM Extension from Rev Q to Rev R

---

sycl/test/inline-asm/asm_arbitrary_ops_order.cpp
sycl/test/inline-asm/asm_multiple_instructions.cpp

Signed-off-by: Aleksander Fadeev <aleksander.fadeev@intel.com>
Signed-off-by: yanfeng xiao <yanfeng.xiao@intel.com>

Specify asm test with unsupported cuda

---

buildbot/dependency.conf

This reverts commit 5f38e4b1906a8e634a170172fc4ff0d833b969a4.

Revert "Uplift GPU RT version for Linux to 20.33.17675 (#2374)"

---

sycl/plugins/level_zero/pi_level_zero.cpp

Signed-off-by: rbegam <rehana.begam@intel.com>

[SYCL] Fix incorrect data type

---

clang/test/Driver/print-internal-defines-for-sycl.c

Signed-off-by: haonanya <haonan.yang@intel.com>

[Driver][Test] Disable the test on Win32.

---

sycl/test/basic_tests/image_accessor_readsampler.cpp

Disable flaky test basic_tests/image_accessor_readsampler.cpp on leve-zero

[SYCL][LIT] Disable flaky test basic_tests/image_accessor_readsampler.cpp on leve-zero

---

sycl/doc/extensions/SPIRV/SPV_INTEL_variable_length_array.asciidoc

This is a preview extension specification, initial revision.

Add SPV_INTEL_variable_length_array extension

---

buildbot/dependency.conf

Uplift GPU RT version for Linux to 20.35.17767

[SYCL CI][Linux GPU RT Uplift] Uplift GPU RT version for Linux CI Process

---

sycl/plugins/level_zero/pi_level_zero.cpp

Signed-off-by: rbegam <rehana.begam@intel.com>

[SYCL] Fix the return data type for subgroup info queries.

---

sycl/test/spec_const/spec_const_hw.cpp
sycl/test/spec_const/spec_const_neg.cpp
sycl/test/spec_const/spec_const_redefine.cpp

[SYCL] Enable spec constant tests for LevelZero.

---

buildbot/dependency.conf
sycl/test/basic_tests/buffer/buffer_full_copy.cpp
sycl/test/hier_par/hier_par_wgscope.cpp
sycl/test/sub_group/generic_reduce.cpp
sycl/test/sub_group/load_store.cpp

Revert "[SYCL][Deps]Uplift Windows GPU RT from 8673 to 8778"

---

sycl/CMakeLists.txt

(after "[SYCL] Implement SYCL_ONEAPI_accessor_properties")

[SYCL] Up library version after f7d073d1c85

---

sycl/doc/extensions/SpecConstants/README.md

[SYCL] Add Specialization constants extension intro document.

---

sycl/test/abi/layout_array.cpp
sycl/test/abi/layout_vec.cpp

Check host layout of vec, item, nd_item, id and range

[SYCL][NFC] Cover more classes with ABI tests

---

buildbot/dependency.conf

Uplift GPU RT version for Linux to 20.41.18123

[BuildBot] Uplift GPU RT version for Linux CI Process

---

clang/lib/Sema/SemaSYCL.cpp

Remove emitWithoutAnonNamespaces function since it's functionality is
covered by setting SuppressUnwrittenScope property of printing policy.
Remove emitCPPTypeString function because it only called
emitWithoutAnonNamespaces function and created printing policy which
is now created once for almost all use cases.

[NFC][SYCL] Remove unnecessary functions

---

sycl/include/CL/sycl/detail/pi.hpp
sycl/test/basic_tests/diagnostics/non-uniform-wk-gp-test.cpp

Signed-off-by: Eugene T Damiba <eugene.t.damiba@intel.com>

[SYCL] Added regression test for non uniform work group size.

---

buildbot/dependency.conf

OpenCL CPU RT: 2020.11.10.0.05 -> 2020.11.11.0.04
OpenCL FPGAEMU RT:  2020.11.10.0.05 -> 2020.11.11.0.04
TBB Linux:  2021.1.10.2267 -> 2021.1.053
TBB Win:  2021.1.10.2267 -> 2021.1.049
OpenCL FPGA RT Linux: 20200913_000017 -> 20201021_000005
OpenCL FPGA RT Windows: 20200913_000017 -> 20201022_000005

[BuildBot] OpenCL CPU/FPGAEMU driver uplift

---

sycl/tools/sycl-ls/sycl-ls.cpp

[SYCL][NFC] avoid redundant copies of platform/device vector 

---

.github/CODEOWNERS

Signed-off-by: Andrew Savonichev <andrew.savonichev@intel.com>

Update Github CODEOWNERS

---

sycl/doc/GetStartedGuide.md

Align with LLVM's Getting Started document:
https://llvm.org/docs/GettingStarted.html#checkout-llvm-from-git
Closes #2809.

[SYCL][Doc] Update source checkout instructions for Windows

---

sycl/source/detail/os_util.cpp
sycl/source/detail/pi.cpp
sycl/source/detail/platform_impl.cpp
sycl/source/detail/program_manager/program_manager.cpp
sycl/source/detail/scheduler/graph_builder.cpp
sycl/source/detail/windows_pi.cpp
xpti/src/xpti_proxy.cpp

The effort of compiler self build has revealed a number of errors that can be cleaned.
This is an effort to improve the code and reduce the errors.

[SYCL][NFC] Code clean up revealed by compiler self build. 

---

clang/test/Driver/clang-offload-bundler-tgtsym.c
clang/tools/clang-offload-bundler/ClangOffloadBundler.cpp

This patch changes clang-offload-bundler tool to add a new section .tgtsym to
fat object file. This section contains names of symbols defined in the embedded
target objects prefixed by the offload target id "<kind>-<triple>". Prefixed
symbol names are separated by '\0' character in the section data.

[clang-offload-bundler] Add .tgtsym section with target symbol names to fat object

---

.github/workflows/sync-main.yml

@bader The updated script has been tested on my private fork, please help to review and merge, thanks!

[Github Action] Update cron to run main branch sync every 10 min

---

sycl/source/detail/device_info.hpp

OpenCL extensions may result in returning partition_properties that are not yet defined for SYCL (eg. CL_DEVICE_PARTITION_BY_NAMES_INTEL)
Here we filter out those properties. 
Signed-off-by: Chris Perkins <chris.perkins@intel.com>

[SYCL] filtering partition properties to exclude non-SYCL ones

---

sycl/test/abi/layout_accessors_host.cpp

This is a followup for https://github.com/intel/llvm/pull/2923

[SYCL][NFC] Add more ABI checks

---

sycl/plugins/level_zero/pi_level_zero.cpp

Signed-off-by: rbegam <rehana.begam@intel.com>

[SYCL] Fix for the build error with --no-assertions.

---

buildbot/dependency.conf
buildbot/windows.vrd

Add ocloc on windows.
Signed-off-by: yinyangsx <yin.yang@intel.com>

[Buildbot] Add windows ocloc for windows CI process

---

.github/CODEOWNERS

Mariya will be focused on other components.

Update CODEOWNERS to reflect CFE changes

---

llvm/tools/sycl-post-link/SPIRKernelParamOptInfo.cpp

[sycl-post-link][NFC] Use range-based for loop.

---

sycl/test/atomic_ref/add.cpp
sycl/test/atomic_ref/sub.cpp

Fix for the regression introduced by: #2765

[SYCL] Remove XFAIL for passing tests

---

.github/CODEOWNERS

Add 1 more code owner for ESIMD sources.

---

sycl/doc/extensions/LevelZeroBackend/LevelZeroBackend.md
sycl/doc/extensions/README.md

Describes Level-Zero backend and SYCL's interoperability with Level-Zero runtime.

[SYCL][NFC] Introduce Level-Zero backend specification

---

llvm/lib/SYCLLowerIR/CMakeLists.txt

[ESIMD] Update vc-intrinsics revision

---

sycl/doc/GetStartedGuide.md

Signed-off-by: gejin <ge.jin@intel.com>

[SYCL][DOC] Update doc for building SYCL runtime with LLVM libcxx

---

sycl/doc/CompilerAndRuntimeDesign.md

Added description for managing address spaces in SYCL mode.

[SYCL][Doc] Fill address spaces handling section in design documentation

---

.github/workflows/clang-format.yml

[CI] Skip "test" directories for clang-format check

---

README.md

Adding information about openmp branch and project. This project is a staging
area for late-outline OpenMP and OMP Offload.
Signed-off-by: Pavel V Chupin <pavel.v.chupin@intel.com>

[Doc][NFC] Adding homepage info on openmp project

---

sycl/plugins/level_zero/pi_level_zero.cpp

[SYCL] Do only PI calls tracing in L0 plugin under SYCL_PI_TRACE=-1

---

sycl/CMakeLists.txt
sycl/cmake/modules/AddSYCLExecutable.cmake
sycl/cmake/modules/AddSYCLUnitTest.cmake
sycl/plugins/CMakeLists.txt
sycl/plugins/level_zero/CMakeLists.txt
sycl/plugins/opencl/CMakeLists.txt
sycl/source/CMakeLists.txt

Use 2 spaces as indentation across the project.

[SYCL][CMake][NFC] Unify indentation format for DPC++ runtime CMake

---

sycl/doc/KernelProgramCache.md

- add support for persistent cache on-disk;
- describe cache eviction mechanism;
- define support for caching of device code built with build options;
- describe configuration parameters for caches;
- optimize in-memory cache keys.

[SYCL][Doc] Improvements design for program cache

---

buildbot/dependency.conf

Upgrade Windows GPU driver to 27.20.100.9316
Signed-off-by: yinyangsx <yin.yang@intel.com>

[Buildbot] Upgrade Windows GPU driver to 27.20.100.9316

---

clang/test/SemaSYCL/intel-fpga-global-const.cpp

-fsycl is not supported by Frontend anymore.

[SYCL] Update run command for intel-fpga-global-const.cpp

---

llvm/tools/sycl-post-link/SYCLDeviceLibReqMask.h

[SYCL][NFC] Fix pragma setting in sycl-post-link

---

sycl/include/CL/sycl/queue.hpp

Signed-off-by: Sergey Kanaev <sergey.kanaev@intel.com>

[SYCL] Fix build when DISABLE_SYCL_INSTRUMENTATION_METADATA is defined

---

sycl/include/CL/sycl/INTEL/esimd/esimd_memory.hpp

Signed-off-by: Gang Y Chen <gang.y.chen@intel.com>

[SYCL][ESIMD] always put in the slm-fence in esimd barrier for HW

---

sycl/gdb/libsycl.so-gdb.py

Minor enhancement to handle accessor::operator[] overloads which take id
wrapped in cl::sycl::item as an argument.

[GDB] Support cl::sycl::item argument in op[]

---

sycl/plugins/level_zero/pi_level_zero.cpp
sycl/plugins/level_zero/pi_level_zero.hpp

[SYCL] Support for >1 Level-Zero drivers

---

sycl/include/CL/sycl/detail/common.hpp
sycl/source/detail/error_handling/enqueue_kernel.cpp

[SYCL] Replace OpenCL API with Native API in error reporting.

---

.github/CODEOWNERS

Adding Aaron to help with the FE reviews.

---

sycl/source/detail/platform_impl.cpp

[SYCL] Absorb errors in plugin initialization.

---

sycl/plugins/level_zero/pi_level_zero.cpp
sycl/plugins/level_zero/pi_level_zero.hpp
sycl/source/detail/scheduler/commands.cpp
sycl/unittests/scheduler/InOrderQueueDeps.cpp

Reverts intel/llvm#3396 due to issues found

Revert "[SYCL][L0] Support DPC++ extension Queue Order Properties."

---

llvm/lib/SYCLLowerIR/LowerESIMD.cpp
llvm/lib/SYCLLowerIR/LowerESIMDVLoadVStore.cpp
llvm/lib/SYCLLowerIR/LowerWGScope.cpp

[NFC][SYCL] Fix warnings in LowerWGScope.cpp and ESIMD passes.

---

clang/lib/CodeGen/CodeGenAction.cpp

Signed-off-by: Zahira Ammarguellat <zahira.ammarguellat@intel.com>

[NFC] Fix the comment

---

sycl/source/detail/platform_impl.cpp

Do not stop loading next pluging if the current one fails to initialize.

[SYCL] Try to load next plugins if plugin fails

---

sycl/plugins/level_zero/pi_level_zero.cpp

[SYCL] Report support for IEEE rounded sqrt/div

---

sycl/plugins/level_zero/CMakeLists.txt

Signed-off-by: rbegam <rehana.begam@intel.com>

[BuildBot] Upgrade L0Loader version for Win.

---

llvm/lib/Passes/PassBuilder.cpp
llvm/lib/Passes/PassRegistry.def
llvm/test/Transforms/SPIRITTAnnotations/itt_atomic_load.ll
llvm/test/Transforms/SPIRITTAnnotations/itt_atomic_store.ll
llvm/test/Transforms/SPIRITTAnnotations/itt_barrier.ll
llvm/test/Transforms/SPIRITTAnnotations/itt_start_finish.ll

[SYCL] Register SPIRITTAnnotations pass for New PM

---

sycl/plugins/level_zero/pi_level_zero.cpp

[SYCL] Adjust total number of created command-list as they are destroyed.

---

sycl/plugins/level_zero/pi_level_zero.cpp
sycl/plugins/level_zero/pi_level_zero.hpp

[SYCL] Meet queue capabilities on how large pattern fill it can process.

---

llvm/test/tools/sycl-post-link/spec-constants/spec_const_and_split.ll

Fix post-commit failure after https://github.com/intel/llvm/pull/3739 
https://github.com/intel/llvm/runs/2604002244

[sycl-post-link] Fix post-commit failure

---

sycl/source/detail/scheduler/scheduler.cpp

This patch fixes memory leak in SYCL context which happened
after expected exception

[SYCL] Fix memory leak in SYCL context after expected exception

---

sycl/plugins/level_zero/pi_level_zero.cpp

[SYCL] Temporarily turning off copy engine support for memory fill operations

---

sycl/include/sycl/ext/intel/experimental/esimd/detail/esimd_util.hpp

No public APIs changed, no new tests needed.
Signed-off-by: kbobrovs <Konstantin.S.Bobrovsky@intel.com>

[SYCL][ESIMD] Remove dead code and simplify implementation in esimd_util.hpp

---

openmp/libomptarget/plugins/opencl/CMakeLists.txt
openmp/libomptarget/plugins/opencl/src/ompt-opencl.cpp
openmp/libomptarget/plugins/opencl/src/rtl-trace.h
openmp/libomptarget/plugins/opencl/src/rtl.cpp

OpenCL plugin for target offload

[libomptarget] Add OpenCL plugin files

---

sycl/include/sycl/ext/intel/experimental/esimd.hpp
sycl/include/sycl/ext/intel/experimental/esimd/common.hpp
sycl/include/sycl/ext/intel/experimental/esimd/detail/host_util.hpp
sycl/include/sycl/ext/intel/experimental/esimd/detail/intrin.hpp
sycl/include/sycl/ext/intel/experimental/esimd/detail/math_intrin.hpp
sycl/include/sycl/ext/intel/experimental/esimd/detail/memory_intrin.hpp
sycl/include/sycl/ext/intel/experimental/esimd/detail/region.hpp
sycl/include/sycl/ext/intel/experimental/esimd/detail/sycl_util.hpp
sycl/include/sycl/ext/intel/experimental/esimd/detail/types.hpp
sycl/include/sycl/ext/intel/experimental/esimd/detail/util.hpp
sycl/include/sycl/ext/intel/experimental/esimd/math.hpp
sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp
sycl/include/sycl/ext/intel/experimental/esimd/simd.hpp
sycl/include/sycl/ext/intel/experimental/esimd/simd_view.hpp
sycl/test/esimd/block_load_store.cpp
sycl/test/esimd/simd_copy_to_copy_from.cpp

Signed-off-by: kbobrovs <Konstantin.S.Bobrovsky@intel.com>

[SYCL][ESIMD] Make source naming consistent.

---

sycl/test/check_device_code/id_queries_fit_int.cpp

Signed-off-by: Sergey Kanaev <sergey.kanaev@intel.com>

[SYCL] Fix 'ID queries fit in int' test

---

sycl/include/CL/sycl/queue.hpp

[SYCL] Fix syntax error introduced in #3401

---

sycl/include/sycl/ext/intel/experimental/esimd/detail/math_intrin.hpp
sycl/include/sycl/ext/intel/experimental/esimd/math.hpp
sycl/test/esimd/regression/bit_ops.cpp

E2E test: https://github.com/intel/llvm-test-suite/pull/301
Signed-off-by: kbobrovs <Konstantin.S.Bobrovsky@intel.com>

[SYCL][ESIMD] Fix bit operation compilation errors, add test.

---

.github/workflows/gh_pages.yml

This should fix latest CI failure.

[Doc] Fix deployment paths

---

sycl/plugins/esimd_cpu/pi_esimd_cpu.cpp

Warnings from unused variable in pi_esimd_cpu.cpp are suppressed

[SYCL][ESIMD] Suppress warning from unused variable in pi_esimd_cpu

---

sycl/doc/KernelProgramCache.md
sycl/doc/extensions/fpga_io_pipes_design.rst

A few typos and bugs in code examples.

[SYCL][Doc] Fix markdown linter issues

---

sycl/plugins/level_zero/pi_level_zero.cpp

This changes cleanupAfterEvent not to query status of a fence when
the InUse flag indicates that the fence is not in use. This wasn't
a bug, but just unnecessary.
There is no associated unit test because whether the fence will have
been already queried and reset is very dependent on order that SYCL
RT calls piEventsWait, and also on timing of GPU itself.  And so
I believe unit test would be very prone to breakage on unrelated
changes.
I did verify by hand that this change causes significantly fewer calls
to zeFenceQueryStatus.

[SYCL][PI][L0]Changes cleanupAfterEvent not to query reset fence

---

sycl/plugins/level_zero/pi_level_zero.cpp

[SYCL][L0] Wait for all events completion to do full cleanup

---

clang/test/Driver/sycl-intelfpga-aoco-win.cpp
clang/test/Driver/sycl-offload-intelfpga.cpp
clang/test/Driver/sycl-offload-win.c
clang/test/Driver/sycl-offload.c

A few tests don't play well in the x86 host arena.  Modify the tests
to force the expected target.

[NFC] Update tests to better work for x86 Windows host

---

llvm/include/llvm/Demangle/ItaniumDemangle.h

Signed-off-by: kbobrovs <Konstantin.S.Bobrovsky@intel.com>

Fix debug build mangler test after PR#3992 (8f38045).

---

sycl/source/detail/global_handler.cpp
sycl/source/detail/global_handler.hpp

This should fix hangs introduced by intel/llvm#2805
Either this patch or #4045 should be merged prior to #2805.

[SYCL] Introduce per-field lock in global handler

---

sycl/include/CL/sycl.hpp
sycl/include/CL/sycl/atomic.hpp
sycl/include/CL/sycl/atomic_fence.hpp
sycl/include/CL/sycl/detail/spirv.hpp
sycl/include/CL/sycl/memory_enums.hpp
sycl/test/check_device_code/atomic_fence.cpp
sycl/test/warnings/sycl_2020_deprecations.cpp

Link to the spec: https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:barriers-fences

[SYCL] SYCL 2020 atomic_fence

---

sycl/plugins/level_zero/CMakeLists.txt

Uplift level-zero loader from v1.2.3 to v1.4.1

Uplift level-zero loader from v1.2.3 to v1.4.1

---

clang/include/clang/Driver/Options.td

[SYCL][Driver] Make clang help a bit prettier

---

sycl/include/sycl/ext/intel/experimental/esimd/math.hpp

Part 1.
Documented the following APIs:
sat, abs,
shl, shr, rol, ror, asr, lsr
qout, mod, div
min, max
dp2, dp3, dp4, dph, line
frc

[ESIMD][doc] Added documentation for some ESIMD math APIs

---

sycl/tools/CMakeLists.txt
sycl/tools/get_device_count_by_type.cpp

This will be required to add ROCm support to the lit tests.

[SYCL][ROCm] Add ROCm to get_device_count_by_type

---

sycl/plugins/level_zero/pi_level_zero.cpp

[SYCL][L0] Start using blitter engine for in-order queues

---

libclc/ptx-nvidiacl/libspirv/group/collectives.cl

This patch fixes https://github.com/intel/llvm/issues/3955

[SYCL][LIBCLC] Add support for non-uniform [I/F]Mul op in ptx-nvidiacl

---

sycl/include/CL/sycl/detail/cg.hpp
sycl/include/CL/sycl/handler.hpp
sycl/source/detail/scheduler/commands.cpp
sycl/source/detail/scheduler/commands.hpp
sycl/source/detail/scheduler/graph_builder.cpp
sycl/source/detail/scheduler/scheduler.cpp
sycl/source/detail/scheduler/scheduler.hpp
sycl/source/handler.cpp
sycl/test/abi/layout_handler.cpp
sycl/test/abi/vtable.cpp
sycl/test/regression/check_simple_name_collisions.cpp
sycl/unittests/scheduler/SchedulerTestUtils.hpp
sycl/unittests/scheduler/StreamInitDependencyOnHost.cpp

Expansion of the class "CG" to "CommandGroup" to avoid possible name collisions.

[SYCL] Expansion of the class CG to CommandGroup

---

sycl/include/CL/sycl/backend.hpp

Signed-off-by: rehana begam <rehana.begam@intel.com>

[SYCL] Maintain back compatibility with no ownership for interop queues.

---

sycl/include/sycl/ext/intel/experimental/esimd/simd.hpp

Corresponding E2E test: https://github.com/intel/llvm-test-suite/pull/379

[ESIMD] Fix a bug in simd::replicate_w API

---

sycl/ReleaseNotes.md

Contributors: @s-kanaev , @vladimirlaz

[SYCL][Doc] Add release notes for July release

---

clang/lib/Driver/ToolChains/Clang.cpp
clang/test/Driver/sycl-spirv-ext.c

Signed-off-by: Leonid Pauzin leonid.pauzin@intel.com

[SYCL][FPGA] Enable RuntimeAlignedINTEL SPIR-V extension

---

sycl/plugins/level_zero/pi_level_zero.cpp
sycl/plugins/level_zero/pi_level_zero.hpp

[WIP][SYCL][L0] move waiting from piEventRelease to Event->cleanup()

---

sycl/plugins/opencl/pi_opencl.cpp

[SYCL] ignore unused input

---

sycl/plugins/level_zero/pi_level_zero.cpp
sycl/plugins/level_zero/pi_level_zero.hpp

[SYCL][L0] added proper caching of immutable Level-Zero object properties

---

.github/CODEOWNERS

Added one mode code owner for ESIMD runtime library

---

sycl/plugins/level_zero/pi_level_zero.cpp

[SYCL][PI][L0] Re-enable copy engine use in L0 plugin for memory fill operations

---

libclc/amdgcn-amdhsa/libspirv/SOURCES
libclc/amdgcn-amdhsa/libspirv/atomic/loadstore_helpers.ll
libclc/amdgcn-amdhsa/libspirv/cl_khr_int64_extended_atomics/minmax_helpers.ll

Add atomic load and store builtins for amdgcn-amdhsa

[SYCL][LIBCLC] Add atomic builtins for amdgcn-amdhsa

---

buildbot/dependency.conf

Signed-off-by: Yang <yin.yang@intel.com>

[Buildbot] Upgrade Windows GPU driver to 100.9805

---

sycl/plugins/level_zero/pi_level_zero.cpp
sycl/plugins/level_zero/pi_level_zero.hpp

[SYCL][L0] Wait for events to finish at external queue release

---

README.md

Add oneAPI logo to the README file.

---

sycl/plugins/cuda/pi_cuda.cpp

The SYCL CTS recently merged an [extensive set of additional tests](https://github.com/KhronosGroup/SYCL-CTS/blob/dc506f54f6905ada8b141c7c056b9775775f5e48/tests/handler/handler_copy.cpp) for the explicit copy operations APIs. Running these tests with the DPC++ CUDA backend reveals that copies are failing for strided accessors (i.e. copying from/to an accessor that has an offset and/or a range smaller than the buffer).
Previously, when passing 0 for row/slice pitches for source and/or destination to `commonEnqueueMemBufferCopyRect`, the function would infer the row/slice pitches from the copied region. This does not work when copying with an offset, as `cuMemcpy3DAsync` checks whether the pitches are at least as large as the offset + copied range, otherwise returning …

[SYCL][CUDA] Don't infer memcpy src/dst pitches from copied region

---

clang/lib/Driver/ToolChains/Clang.cpp
clang/test/Driver/sycl-spirv-ext.c

Signed-off-by: Alexey Sotkin <alexey.sotkin@intel.com>

[SYCL] Enable SPV_INTEL_bfloat16_conversion extension

---

sycl/plugins/level_zero/pi_level_zero.cpp

[SYCL][L0] Assert that L0 device is found to properly free memory

---

sycl/plugins/level_zero/pi_level_zero.cpp

[SYCL][L0] Indicate event no longer in a reset command-list

---

.github/CODEOWNERS

Make @kbobrovs the code owner for ESIMD CPU emulator plugin.

New code owner for sycl/plugins/esimd_cpu

---

sycl/include/CL/sycl/backend.hpp
sycl/include/CL/sycl/backend/level_zero.hpp
sycl/include/CL/sycl/context.hpp
sycl/include/CL/sycl/device.hpp
sycl/include/CL/sycl/platform.hpp
sycl/test/basic_tests/interop-level-zero-2020.cpp

[SYCL] Make Level-Zero interop API SYCL 2020 compliant for platform, device and context

---

CONTRIBUTING.md

[Doc] Specify clang-format version in contribution guide

---

buildbot/dependency.conf

Signed-off-by: Yin Yang <yin.yang@intel.com>

[Buildbot] Upgrade Windows GPU driver to 100.9864

---

sycl/source/detail/scheduler/scheduler.cpp

`GraphBuilder::getMemObjRecord` does not change the graph and thus does not need a write-lock. Lowering the lock to a read-lock allows merging the acquisition with the following read-lock acquisition.

[SYCL] Merge two lock acquisitions in Scheduler::removeMemoryObject

---

sycl/include/sycl/ext/oneapi/matrix/static-query.hpp

Signed-off-by: Dounia <dounia.khaldi@intel.com>

[SYCL][NFC] Minor correction to debug message

---

sycl/doc/OptionalDeviceFeatures.md

The SYCL 2020 spec was recently amended to rename the C++ attribute
`[[sycl::requires()]]` to `[[sycl::device_has()]]`.  Update references
to this attribute in the optional device features design doc.

[SYCL][Doc] Rename attribute in optional feature design doc

---

.github/CODEOWNERS

[SYCL] Add backup code owner for PI

---

sycl/plugins/level_zero/pi_level_zero.cpp
sycl/plugins/level_zero/pi_level_zero.hpp

[SYCL][L0] Re-use event pools

---

llvm/lib/SYCLLowerIR/CMakeLists.txt

[ESIMD] Refactor vc-intrinsics build for easier sync with custom builds.

---

llvm/lib/SYCLLowerIR/CMakeLists.txt

[ESIMD] Update vc-intrinsics repo hash tag.

---

.github/workflows/sycl_precommit.yml
devops/actions/clang-format/action.yml

Enable basic SYCL build and in-tree LIT tests on GitHub Actions in pre-commit as an experiment

[CI] Enable GitHub Actions in pre-commit

---

sycl/include/sycl/ext/intel/experimental/esimd/detail/memory_intrin.hpp

[SYCL][ESIMD] Fix for a bug in SVM gather/scatter emulation on host

---

devops/actions/clang-format/action.yml
sycl/test/check_device_code/no_offset.cpp

Hotfix of post-commit fail for no_asserting configuration.

[SYCL] no_offset accessor property post-commit hotfix

---

.github/CODEOWNERS

[SYCL] Remove Artur from PI owners

---

sycl/doc/EnvironmentVariables.md
sycl/doc/GetStartedGuide.md

Update the HIP sections of the GetStartedGuide and EnvironmentVariables documentation with details regarding usage, requirements and current implementation status.

[SYCL][DOC][HIP] Update documentation for HIP backend

---

buildbot/dependency.conf

Signed-off-by: Yin Yang <yin.yang@intel.com>

[Buildbot] Upgrade Windows GPU driver to 101.1069

---

buildbot/configure.py
opencl/CMakeLists.txt
sycl/CMakeLists.txt
sycl/cmake/modules/AddSYCLUnitTest.cmake
sycl/unittests/Extensions/CMakeLists.txt
sycl/unittests/SYCL2020/CMakeLists.txt
sycl/unittests/allowlist/CMakeLists.txt
sycl/unittests/config/CMakeLists.txt
sycl/unittests/pi/CMakeLists.txt
sycl/unittests/pi/cuda/CMakeLists.txt
sycl/unittests/program_manager/CMakeLists.txt

Make SYCL headers warning free.

[SYCL] Fix warnings in configuration and compilation

---

sycl/plugins/level_zero/pi_level_zero.cpp

[SYCL] Enlarge the maximum batch size to 64

---

.github/workflows/sycl_linux_build_and_test.yml
.github/workflows/sycl_post_commit.yml

Fix duplicate name of post-commit configuration and incorrect logic for main pipeline config selection.

[CI] Fix a few typos in GitHub Actions configs

---

.github/workflows/sycl_nightly.yml

Apply fixes from https://github.com/intel/llvm/pull/5084 to nightly config as well.

[CI] Fix nightly build configuration

---

sycl/include/CL/sycl/device_event.hpp
sycl/include/CL/sycl/group.hpp

Fixes https://github.com/intel/llvm/issues/4959
Note: This should not break SYCL library ABI but can affect device-code ABI. @pvchupin approval required.

[SYCL] Fix dangling pointer in device_event

---

sycl/source/detail/filter_selector_impl.cpp

This fixes the `FilterSelector/select.cpp` test of `llvm-test-suite`

[SYCL][HIP] Add HIP support to filter selector

---

.github/workflows/gh_pages.yml
sycl/doc/index.rst

Add missing blank line and fix documentation path

[SYCL][Doc] Fix typos to fix doc build

---

sycl/include/CL/sycl/group_algorithm.hpp
sycl/include/sycl/ext/oneapi/experimental/group_sort.hpp

Changes for the spec: https://github.com/intel/llvm/pull/4666
Test: https://github.com/intel/llvm-test-suite/pull/633
Signed-off-by: Fedorov, Andrey <andrey.fedorov@intel.com>

[SYCL][Group algorithms] Move group sort extension to experimental

---

.github/workflows/sycl_linux_build_and_test.yml

[CI] Switch labels for OCL x64 job

---

sycl/plugins/level_zero/pi_level_zero.cpp

Signed-off-by: Byoungro So <byoungro.so@intel.com>

[SYCL][L0] Return error code when ZE_DEBUG=4 detects memory leaks

---

buildbot/configure.py
sycl/CMakeLists.txt
sycl/doc/GetStartedGuide.md

- Enabled by '--enable-esimd-emulator'

[SYCL][ESIMD][EMU] Disable esimd_emulator build by default

---

sycl/plugins/level_zero/pi_level_zero.cpp

[SYCL] Modify L0 plugin support for copy engines to address scenario when main copy engine is not available

---

xpti/include/xpti/xpti_data_types.h

Fix build issues introduced by #5259

[SYCL] Fix CI failure

---

sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp

[ESIMD] Removed elems-per-addr parameter from gather/scatter APIs

---

sycl/include/sycl/ext/oneapi/matrix/matrix-jit.hpp

[SYCL] Add missing Layout template parameter for CompositeConstruct

---

.github/workflows/sycl_linux_build_and_test.yml

They have been disabled by accident.

[CI] Enable in-tree LITs back

---

sycl/doc/extensions/experimental/SYCL_EXT_INTEL_ESIMD/README.md

[ESIMD] Update README.md

---

sycl/plugins/level_zero/pi_level_zero.cpp

[SYCL] Fix a possible null reference in L0 plugin code

---

sycl/include/sycl/ext/intel/experimental/esimd.hpp
sycl/include/sycl/ext/intel/experimental/esimd/detail/region.hpp
sycl/include/sycl/ext/intel/experimental/esimd/detail/simd_mask_impl.hpp
sycl/include/sycl/ext/intel/experimental/esimd/detail/simd_obj_impl.hpp
sycl/include/sycl/ext/intel/experimental/esimd/detail/simd_view_impl.hpp
sycl/include/sycl/ext/intel/experimental/esimd/simd.hpp
sycl/include/sycl/ext/intel/experimental/esimd/simd_view.hpp

[ESIMD] Doxygen update VI - overall structure, misc clean-up, additions.

---

sycl/unittests/scheduler/InOrderQueueSyncCheck.cpp

fixes post-commit check for https://github.com/intel/llvm/pull/5551

[SYCL] Fix warning for InOrderQueueSyncCheck unit test build

---

.github/workflows/sycl_stale_issues.yml

[CI] Allow stale issue bot to analyze more issues

---

buildbot/dependency.conf

Signed-off-by: Yin Yang <yin.yang@intel.com>

[Buildbot] Update Windows GPU version to 101.1340

---

clang/lib/Driver/ToolChains/Clang.cpp

Use of -fopenmp-new-driver allows for multiple inputs, the assertion
against this fact is no longer valid and has been removed.  Also perform
a small refactor of code to better fit with community.

[Driver][SYCL] Remove obsolete assert for -fopenmp-new-driver usage

---

sycl/plugins/level_zero/pi_level_zero.cpp
sycl/plugins/level_zero/pi_level_zero.hpp

[SYCL][L0] Restructure code in preparation for submitting to multiple compute queues

---

.github/CODEOWNERS

Update the code reviewers to match the new documentation directory
structure.

[SYCL] Update code reviewers for docs

---

sycl/plugins/esimd_emulator/CMakeLists.txt

- CM_EMU update to prevent CMRT from generating 'cmrt_dump.txt'

[SYCL][ESIMD][EMU] Update CM_EMU library git repo hash

---

sycl/doc/design/spirv-extensions/SPV_INTEL_global_variable_decorations.asciidoc

Add validation rules to the SPIR-V extension
SPV_INTEL_global_variable_decorations.

[SYCL][DOC] Add validation rules to SPIR-V ext

---

.github/CODEOWNERS

* Added Tianfei for Release Notes
* Added ESIMD reviewers for SYCLLowerIR/CMakeLists.txt

[CODEOWNERS] Update with new names

---

devops/containers/ubuntu2004_base.Dockerfile

- Add `sycl` user to sudoers
- Add script to install drivers

[CI] Prepare base container for driver installation

---

.github/CODEOWNERS

[ESIMD] Update CODEOWNERS to include new/moved ESIMD files

---

sycl/tools/sycl-prof/collector.cpp

Static analysis tool complained about this code.

[SYCL] Fix potential nullptr dereference

---

clang/test/CodeGenSYCL/kernel-arg-accessor-pointer.cpp

[NFC][SYCL] Remove hard-coded checks in kernel-arg-accessor-pointer.cpp

---

sycl/include/CL/sycl/half_type.hpp

[NFC][SYCL] Fix formatting and typos

---

.github/workflows/sycl_linux_build_and_test.yml
devops/test_configs.json

Reset Intel GPUs before each test run to avoid side effects of GPU driver bugs.

[CI] Reset GPU

---

sycl/plugins/level_zero/pi_level_zero.cpp

* Fix spec violation while using custom queue index.
https://spec.oneapi.io/level-zero/latest/core/api.html#_CPPv4N23ze_command_queue_desc_t5indexE

[SYCL][L0] Add proper handling of queue indexing

---

sycl/doc/design/CompileTimeProperties.md

Signed-off-by: Peter Colberg <peter.colberg@intel.com>

[SYCL][Doc] Fix links to sycl_ext_oneapi_properties extension

---

sycl/include/sycl/ext/intel/esimd/common.hpp
sycl/include/sycl/ext/intel/esimd/detail/atomic_intrin.hpp
sycl/include/sycl/ext/intel/esimd/detail/elem_type_traits.hpp
sycl/include/sycl/ext/intel/esimd/detail/memory_intrin.hpp
sycl/include/sycl/ext/intel/experimental/esimd/detail/math_intrin.hpp
sycl/include/sycl/ext/intel/experimental/esimd/detail/memory_intrin.hpp

[ESIMD][NFC] Replace the deprecated feature_not_supported exception

---

.github/workflows/sycl_precommit.yml

Modifications in these files do not impact SYCL pre-commit results.

[CI] Add more ignore paths for pre-commit

---

sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp

[SYCL][ESIMD] Rename sbarrier => split_barrier

---

sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp
sycl/test/esimd/nbarriers.cpp

[SYCL][ESIMD] Rename nbarrier => named_barrier

---

devops/scripts/install_build_tools.sh

Required for dependencies script to work.

[CI] Install wget into container

---

.github/CODEOWNERS

* Reassign top level uncovered items to myself
* Rely on group codeowners for clang-offload-*

[NFC][CODEOWNERS] Update codeowners

---

sycl/tools/sycl-trace/CMakeLists.txt

Co-authored-by: Artur Gainullin <artur.gainullin@intel.com>

[SYCL] Fix cmake file for sycl-trace

---

sycl/source/detail/program_manager/program_manager.cpp

[SYCL] Fix SYCL_DUMP_IMAGES handling to also dump when spec constants are on

---

sycl/plugins/level_zero/pi_level_zero.cpp

[SYCL][L0] Add control to hold mutex lock while queue is synchronizing

---

sycl/include/CL/sycl/reduction.hpp
sycl/include/sycl/ext/oneapi/reduction.hpp

This should fix recent post-commit failures.

[SYCL][NFC] Fix unused arguments in reductions

---

sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp
sycl/test/esimd/check_lsc.cpp

[ESIMD] Add compile-time parameter checks to lsc APIs.

---

sycl/include/CL/sycl/builtins.hpp

This patch solves https://github.com/intel/llvm/issues/6068

[SYCL] Fix bug for -ffast-math and double

---

sycl/include/CL/sycl/usm.hpp

Addressing https://github.com/intel/llvm/pull/6205#discussion_r883555501

[SYCL][USM] Follow-up for #6205 - loosen alignment

---

.github/workflows/sycl_update_gpu_driver.yml
devops/scripts/update_drivers.py

Added a workflow that updates the GPU driver version in the `dependecies.json`. 
It creates the PRs with the new version for Linux and Linux staging separately once per week.

[CI] Add automation for GPU driver version update

---

clang/include/clang/Driver/Options.td
sycl/doc/UsersManual.md

Add additional details to the help and the UserManual for the
-fsycl-instrument-device-code option.

[NFC] Update documentation for -fsycl-instrument-device-code

---

llvm/tools/sycl-post-link/CMakeLists.txt

Fix shared library build mode failure introduced by #6160

---

sycl/source/detail/pi.cpp

This fixes Linux build post-commit failures from https://github.com/intel/llvm/pull/6256.

[SYCL] Fix unused parameter in getELFHeaderType

---

sycl/plugins/level_zero/pi_level_zero.cpp

- Cleanup device selection.
Signed-off-by: Jaime Arteaga <jaime.a.arteaga.molina@intel.com>

[SYCL][L0] Improve L0 timestamps (2)

---

sycl/plugins/level_zero/pi_level_zero.cpp
sycl/plugins/level_zero/pi_level_zero.hpp
sycl/plugins/level_zero/usm_allocator.cpp
sycl/plugins/level_zero/usm_allocator.hpp

[SYCL][L0] Bump minimum shared read-only allocation slab to 2M

---

sycl/doc/developer/ABIPolicyGuide.md

Preparation for the next major library version release

[SYCL][Doc] Announce ABI-breaking window

---

.github/workflows/sycl_cleanup.yml

[SYCL][CI] Update cleanup workflow

---

sycl/plugins/level_zero/pi_level_zero.cpp

[SYCL][L0] Perform P2P capability check for buffer migration

---

clang/include/clang/Basic/Attr.td

[SYCL] Use InternalOnly attribute for internal only SYCL attributes

---

sycl/include/sycl/ext/intel/esimd/memory.hpp

Update API spec for fence_mask::sw_barrier.

[SYCL][ESIMD][NFC] Update document for fence_mask::sw_barrier.

---

devops/containers/ubuntu2004_build.Dockerfile

Latest available CUDA development tools have fixes for building SYCL-CTS.

[CI] Update CUDA docker image to 11.7

---

.github/workflows/sycl_linux_build_and_test.yml

Also fixes similar potential issue with lts test suite.

[CI] Skip AWS job if nothing to run there

---

sycl/doc/design/OptionalDeviceFeatures.md

[SYCL] Add a list of Intel GPU device IDs to the optional device features design.

---

sycl/test/abi/layout_handler.cpp

Revert some accidental changes from https://github.com/intel/llvm/pull/6555

[SYCL][NFC] Fix handler layout test with clang + shared lib build

---

devops/dependencies.json

[GHA] Uplift Linux GPU RT version to 22.32.23937

---

llvm/lib/SYCLLowerIR/ESIMD/LowerESIMD.cpp

The purpose of this PR is to fix an incorrect conversion between double and unsigned int types

[SYCL][ESIMD] Fix an issue causing incorrect conversion involving unsigned types

---

sycl/doc/GetStartedGuide.md

Just doing this to get familiar with submission process, no functional change
Signed-off-by: Sarnie, Nick <nick.sarnie@intel.com>

[SYCL] Fix doc typos

---

sycl/source/queue.cpp

This in non-functional changes, will only make the document more
readable.
Signed-off by: Yuan, Alex <alexyuan150298224@gmail.com>

[SYCL][NFC] Clean-up code to improve readability

---

.github/CODEOWNERS
.github/workflows/sycl_linux_build_and_test.yml
devops/actions/cached_checkout/action.yml
devops/actions/clang-format/action.yml

This PR adds the sycl-mlir unit tests to the list of tests that should be run before a PR can be merged.

[SYCL-MLIR]: Add sycl-mlir test to list of test run automatically on github

---

mlir-sycl/doc/developer/ContributeToSYCLMLIR.md

This PR outlines contributing instructions for the sycl-mlir branch.

[SYCL-MLIR]: Update contributing instructions.

---

polygeist/tools/cgeist/Test/Verification/sycl/constructors.cpp

[SYCL-MLIR]: Add lit test for accessor constructor

---

sycl/doc/extensions/proposed/sycl_ext_oneapi_flush.asciidoc
sycl/doc/extensions/proposed/sycl_ext_oneapi_prod.asciidoc

[SYCL][DOC] Extension to add hints to stop batching and start executing

---

clang/lib/Sema/SemaSYCL.cpp

Signed-off-by: Elizabeth Andrews <elizabeth.andrews@intel.com>

[NFC][Sema] Minor code quality change in SemaSYCL.cpp

---

llvm/tools/sycl-post-link/CMakeLists.txt

[SYCL] Fix sycl-post-link shared lib build failure after #6835.

---

sycl/source/detail/queue_impl.cpp

Fix of the following error: https://github.com/intel/llvm/actions/runs/3108535055/jobs/5037840960

[SYCL] Fix error caused by template deduction warning

---

sycl/include/sycl/accessor.hpp

Resolve min/max conflict in the same way as it was done here: https://github.com/intel/llvm/pull/1339
Needed to fix this failure: https://github.com/intel/llvm/actions/runs/3107743966/jobs/5036187282

[SYCL] Resolve min/max conflict

---

devops/dependencies.json

[GHA] Uplift Linux GPU RT version to 22.37.24175

---

sycl/include/sycl/reduction.hpp

Follow-up for #6858 based on post-commit review.

[SYCL][Reduction] Check aspect::usm_device_allocations before using it

---

llvm/lib/SYCLLowerIR/LowerInvokeSimd.cpp

[SYCL] Fix Klocwork issue in LowerInvokeSimd.cpp.

---

polygeist/include/polygeist/BarrierUtils.h
polygeist/lib/polygeist/Passes/ParallelLoopDistribute.cpp
polygeist/tools/cgeist/Lib/ValueCategory.h
polygeist/tools/cgeist/Lib/clang-mlir.h
polygeist/tools/cgeist/driver.cc

Remove functions that are not used.

[SYCL-MLIR]: Remove unused functions

---

llvm/lib/SYCLLowerIR/ESIMD/ESIMDOptimizeVecArgCallConv.cpp
llvm/test/SYCLLowerIR/ESIMD/vec_arg_call_conv.ll

Unwrap sret memory type before comparison, to make vector type and a wrapper struct around the vector type equivalent.
Follow-up for https://github.com/intel/llvm/pull/6835

[ESIMD] Fix ESIMDOptimizeVecArgCallConv to cover more cases, add test.

---

devops/dependencies.json

[GHA] Uplift Linux GPU RT version to 22.38.24278

---

clang/test/SemaSYCL/array-kernel-param.cpp
clang/test/SemaSYCL/inheritance.cpp
clang/test/SemaSYCL/union-kernel-param2.cpp

size_t is different on windows and linux.
Signed-off-by: Elizabeth Andrews <elizabeth.andrews@intel.com>

[NFC] Fix test

---

sycl/plugins/level_zero/pi_level_zero.cpp

This patch makes it possible to access individual CCSs of a single-tile (where Level Zero reports 0 sub-devices).
The CCSs in this case a returned as the sub-devices of the root device.

[SYCL][L0] Report multiple CCS as SYCL sub-devices on a single tile machine

---

buildbot/configure.py

[SYCL] Align variable names with cmake file

---

polygeist/tools/cgeist/Lib/CGCall.cc
polygeist/tools/cgeist/Lib/CGExpr.cc
polygeist/tools/cgeist/Lib/clang-mlir.cc
polygeist/tools/cgeist/Lib/clang-mlir.h

Refactor and cleanup GetOrCreateMLIRFunction

[SYCL-MLIR]: Refactor and cleanup GetOrCreateMLIRFunction 

---

polygeist/tools/cgeist/Lib/clang-mlir.cc
polygeist/tools/cgeist/Lib/clang-mlir.h

[SYCL-MLIR]: Refactor code in clang-mlir.cc

---

polygeist/tools/cgeist/driver.cc

Found a bug in intel/llvm#7001, will recommit with the fix.
Reverts intel/llvm#7001

Revert "[SYCL-MLIR][cgeist] Add support to emit LLVM bitcode"

---

llvm/lib/Transforms/AggressiveInstCombine/AggressiveInstCombine.cpp

In the case of non-opaque pointers, when combining consecutive loads,
need to bitcast the pointer source to the combined type size, otherwise
asserts are triggered.
Differential Revision: https://reviews.llvm.org/D135249

[AggressiveInstCombine] Fix cases where non-opaque pointers are used

---

llvm/lib/SYCLLowerIR/SYCLPropagateAspectsUsage.cpp
llvm/test/SYCLLowerIR/PropagateAspectsUsage/PropagateFunctionWithSyclDetailAspect/propagate-aspects-from-function-with-sycl-detail-1.ll
llvm/test/SYCLLowerIR/PropagateAspectsUsage/PropagateFunctionWithSyclDetailAspect/propagate-aspects-from-function-with-sycl-detail-2.ll
llvm/test/SYCLLowerIR/PropagateAspectsUsage/PropagateFunctionWithSyclDetailAspect/propagate-aspects-from-function-with-sycl-detail-3.ll

Pass should also collect & propagate function's aspects defined by "!sycl_used_aspect" metadata

[SYCL] Improve SYCLPropagateAspectsUsage pass

---

.github/workflows/gh_pages.yml
.github/workflows/issue-release-workflow.yml
.github/workflows/llvm-tests.yml
.github/workflows/sycl_containers.yaml
.github/workflows/sycl_linux_build_and_test.yml
.github/workflows/sycl_nightly.yml
.github/workflows/sycl_post_commit.yml
.github/workflows/sycl_precommit.yml
.github/workflows/sycl_update_gpu_driver.yml
.github/workflows/sycl_windows_build_and_test.yml
.github/workflows/sync-main.yml
.github/workflows/version-check.yml
devops/actions/aws-ec2/action.yml
devops/actions/aws-ec2/package.json
devops/actions/build_container/action.yml
devops/actions/cached_checkout/action.yml
devops/actions/cleanup/action.yml

Required to resolve CI deprecation warnings

[CI][NFC] Uplift versions of github actions

---

mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLOps.td

[SYCL-MLIR] Fix SYCLItemGetIDOp documentation

---

clang/lib/CodeGen/CodeGenTypes.cpp
clang/test/CodeGenSYCL/matrix.cpp

Signed-off-by: Sidorov, Dmitry <dmitry.sidorov@intel.com>

[SYCL][SPIR-V] Don't use 'print' to get JointMatrix typename

---

.github/workflows/gh_pages.yml
.github/workflows/issue-release-workflow.yml
.github/workflows/llvm-tests.yml
.github/workflows/sycl_containers.yaml
.github/workflows/sycl_nightly.yml
.github/workflows/sycl_post_commit.yml
.github/workflows/sycl_precommit.yml
.github/workflows/sycl_update_gpu_driver.yml
.github/workflows/sycl_windows_build_and_test.yml
.github/workflows/sync-main.yml
.github/workflows/version-check.yml
devops/actions/aws-ec2/action.yml
devops/actions/aws-ec2/package.json
devops/actions/build_container/action.yml
devops/actions/cached_checkout/action.yml
devops/actions/cleanup/action.yml

Sync from https://github.com/intel/llvm/commit/7038ec5845071a60682cd66a145880994f70b995

[SYCL-MLIR][CI] Uplift versions of actions/checkout

---

.github/workflows/sycl_linux_build_and_test.yml

[SYCL-MLIR] Execute script to set up environment for TBB

---

.github/workflows/sycl_linux_build_and_test.yml

[SYCL-MLIR] Fix `source: not found` error

---

.github/workflows/sycl_containers.yaml

Revert "[SYCL-MLIR] Change `sycl_containers.yaml` push branch to `sycl-mlir`"

---

sycl/plugins/level_zero/pi_level_zero.cpp

Reverts intel/llvm#6946 due to reported regressions

Revert "[SYCL][L0] Report multiple CCS as SYCL sub-devices on a single tile machine"

---

.github/workflows/sycl_linux_build_and_test.yml
devops/actions/llvm_test_suite/action.yml

[SYCL-MLIR] Test with llvm_test_suite

---

.github/workflows/issue-release-workflow.yml
.github/workflows/llvm-tests.yml
.github/workflows/sycl_linux_build_and_test.yml
.github/workflows/sycl_nightly.yml
.github/workflows/sycl_post_commit.yml
.github/workflows/sycl_windows_build_and_test.yml
.github/workflows/version-check.yml
devops/actions/build_container/action.yml
devops/actions/llvm_test_suite/action.yml

Commits from `sycl` branch:
- [CI][NFC] Uplift versions of github actions: https://github.com/intel/llvm/commit/429c09eb1123b44926243821910681b5f947a1d4
- [CI] Set one hour time limit for llvm-test-suite: https://github.com/intel/llvm/commit/f3ca15689d161b84e60d02a1e34c5513a51dcb50

[SYCL-MLIR][CI][NFC] Uplift versions of github actions

---

.github/workflows/sycl_containers.yaml

Continuation of #7055
There will be more patches, e.g. it's appeared that download-artifact is not
fixed yet: https://github.com/actions/download-artifact/issues/185

[CI][NFC] Fix more github action warnings

---

sycl/include/CL/__spirv/spirv_ops.hpp

Signed-off-by: Sidorov, Dmitry <dmitry.sidorov@intel.com>

[SYCL][Matrix] Fix __spirv_JointMatrixUUMadINTEL

---

sycl/source/detail/event_impl.cpp
sycl/unittests/scheduler/QueueFlushing.cpp

Some events may have no native handle even at the point of cross queue dependency flushing (e.g. those produced by a 0 size memset, where no PI call is actually made). This patch changes the assertion of native handle's existence into a check so that we handle this case properly.

[SYCL] Fix event status query during queue flushing

---

mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLOps.td
mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLOpsTypes.h
mlir-sycl/lib/Conversion/SYCLToLLVM/SYCLToLLVM.cpp
mlir-sycl/lib/Dialect/IR/SYCLOpsAlias.cpp
mlir-sycl/lib/Dialect/IR/SYCLOpsDialect.cpp
mlir-sycl/lib/Dialect/IR/SYCLOpsTypes.cpp
mlir-sycl/lib/Dialect/IR/SYCLTraits.cpp
mlir-sycl/test/Conversion/SYCLToLLVM/sycl-types-to-llvm.mlir
mlir-sycl/test/Dialect/IR/SYCL/types.mlir
polygeist/tools/cgeist/Lib/clang-mlir.cc
polygeist/tools/cgeist/Test/Verification/sycl/types.cpp

Add parsing, printing and lowering support for nd_range.

[SYCL-MLIR] Add nd_range type

---

polygeist/tools/cgeist/Test/Verification/sycl/functions.cpp

As suggested by @etiotto [here](https://github.com/intel/llvm/pull/7172#discussion_r1004529895)

[SYCL-MLIR][NFC] Refactor functions.cpp lit tests

---

sycl/include/sycl/reduction.hpp

It seems that those were mostly to process variadic templates but that
acn be done without extra functions (at least in C++17).
I've inlined those that either had just one callsite or were short
enough.

[NFC][SYCL][Reduction] Inline some helpers to improve code locality

---

sycl/include/sycl/handler.hpp
sycl/include/sycl/reduction.hpp

Became dead in #6646: https://github.com/intel/llvm/commit/1660a6166d4564e11ad07202e692cfc5c93421a7#diff-b2b881baf4af17b5de77ee38a9f201f59e259d79ccf34463b3695076ec191e03L2408-L2414

[NFC][SYCL][Reduction] Remove dead withAuxHandler

---

sycl/source/detail/program_manager/program_manager.cpp

The cache key used while building kernel binaries will have the spec constant data moved to it to avoid repeated copies of a potentially large data structure. However, when building for multiple devices the spec constant data is moved each time a the cache key is created, which can corrupt the cache key. This commit fixes this by creating the cache key once and mutating it for each insertion, preserving common parts of they key and preventing use-after-move.

[SYCL] Fix use-after-move bug in building for multiple devices

---

sycl/plugins/level_zero/pi_level_zero.cpp

[SYCL][L0] Fix 'resource leak' type of Coverity issues

---

sycl/include/sycl/handler.hpp

to cover more internals of sycl::handler class so that reductions implementations can use less handler's private APIs.

[NFC][SYCL][Reduction] Increase scope of handler::withAuxHandler

---

sycl/plugins/level_zero/pi_level_zero.cpp

[SYCL][L0] In piextQueueGetNativeHandle create a L0 queue if it was not yet created

---

sycl/include/sycl/accessor.hpp

[SYCL-MLIR]: Remove unroll directive in accessor.hpp

---

polygeist/tools/cgeist/Lib/CGExpr.cc
polygeist/tools/cgeist/Lib/clang-mlir.cc
polygeist/tools/cgeist/Test/Verification/sycl/constructors.cpp

[SYCL-MLIR] Use GlobalVarAddressSpace for globals

---

sycl/test/basic_tests/known_identity.cpp

[SYCL][LIT] Fix narrowing type conversion for marray in test

---

sycl/plugins/level_zero/pi_level_zero.cpp

Workaround for the issue described in https://github.com/intel/llvm/issues/4255

[SYCL][L0] Support some kernel work sizes greater than UINT32_MAX

---

sycl/source/detail/platform_impl.cpp

https://github.com/intel/llvm/pull/7309 post-commit failure fix

[SYCL] Fix unused parameter error in macOS post-commit

---

polygeist/tools/cgeist/Lib/clang-mlir.cc

[SYCL-MLIR}: Remove unnecessary code

---

.github/workflows/sycl_containers.yaml
.github/workflows/sycl_nightly.yml
.github/workflows/sycl_precommit.yml
devops/containers/ubuntu2204_preinstalled.Dockerfile
libclc/ptx-nvidiacl/libspirv/atomic/atomic_helpers.h
sycl/doc/GetStartedGuide.md
sycl/include/sycl/info/info_desc.hpp
sycl/include/sycl/queue.hpp
sycl/include/sycl/reduction.hpp
sycl/include/sycl/reduction_forward.hpp
sycl/plugins/cuda/pi_cuda.cpp
sycl/plugins/hip/pi_hip.cpp
sycl/source/detail/kernel_info.hpp
sycl/unittests/queue/CMakeLists.txt
sycl/unittests/queue/ShortcutFunctions.cpp

Please do not to squash and merge this PR.

[SYCL-MLIR] Merge from intel/llvm sycl branch

---

sycl/include/sycl/reduction.hpp

Previously the helper abstraction consisted of two implicitly tied pieces that had to be used together and used member variable MOutBufPtr to pass some data behind the scene. Change that to a new abstraction withInitializedMem accepting a callable argument to make the data flow explicit and more immediately clear.
This change also allows to change/optimize this piece in one place without the need to modify multiple uses.

[NFC][SYCL][Reduction] Rethink getReadWriteAccessorToInitializedMem helper

---

polygeist/tools/cgeist/Lib/clang-mlir.cc
polygeist/tools/cgeist/Test/Verification/sycl/functions.cpp

[SYCL-MLIR] Remove some unsupported functions

---

sycl/test/basic_tests/known_identity.cpp
sycl/test/lit.cfg.py

[LIT][SYCL] Reduce compilation time for known_identity test

---

mlir-sycl/CMakeLists.txt
mlir-sycl/lib/Dialect/IR/SYCLOpsDialect.cpp
mlir-sycl/lib/Transforms/SYCLMethodToSYCLCall.cpp

Use C++ 17 fold expressions when possible.

[SYCL-MLIR] Enable C++ 17 support in the SYCL dialect

---

polygeist/tools/cgeist/Test/Verification/sycl/parallel_for.cpp

[SYCL-MLIR][NFC] Fix typo

---

polygeist/tools/cgeist/driver.cc

[SYCL-MLIR][NFC]: Fix clang-tidy warning in driver.cc

---

clang/lib/Driver/ToolChains/Clang.cpp
clang/test/Driver/sycl-spirv-ext.c

Signed-off-by: Sidorov, Dmitry <dmitry.sidorov@intel.com>

[SYCL] Enable SPV_INTEL_masked_gather_scatter extension

---

polygeist/tools/cgeist/Lib/clang-mlir.cc
polygeist/tools/cgeist/Lib/clang-mlir.h

[SYCL-MLIR][NFC] Refactor CommonFieldLookup for SYCL type

---

clang/test/CodeGenSYCL/remove-restriction-builtin-printf.cpp

Fixes post-commit failure reported in https://github.com/intel/llvm/pull/7483

[SYCL] Fix post commit failure on Windows.

---

sycl/doc/extensions/template.asciidoc

Update the core SYCL spec rev to the latest.

[SYCL][DOC] Update extension template spec rev

---

sycl/unittests/helpers/PiImage.hpp

Added missing deduction guides for `PiArray`

[SYCL] Fix -Werror build of unit-tests

---

mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLOps.td
polygeist/tools/cgeist/Lib/clang-mlir.cc

[SYCL-MLIR][NFC]: Types Refactor

---

libclc/cmake/modules/AddLibclc.cmake
libclc/test/CMakeLists.txt
libclc/utils/libclc-remangler/CMakeLists.txt
libclc/utils/libclc-remangler/LibclcRemangler.cpp

Revert "[LIBCLC] Generate FunctionDecl to remangle substituted entries"

---

sycl/source/detail/global_handler.cpp

[SYCL] Fix post commit failure for #6837

---

sycl/include/sycl/ext/intel/esimd/xmx/dpas.hpp
sycl/include/sycl/ext/intel/experimental/esimd/detail/math_intrin.hpp

[ESIMD][NFC] Minor corrections to xmx::dpas() implementation

---

sycl/doc/extensions/experimental/sycl_ext_intel_esimd/esimd_emulator.md

- Environment variable update : SYCL_DEVICE_FILTER to ONEAPI_DEVICE_SELECTOR

[SYCL][ESIMD][DOC] Update on CM_RT_PLATFORM for ESIMD Emulator

---

sycl/unittests/queue/Wait.cpp

Failed in https://github.com/intel/llvm/actions/runs/3689466995/jobs/6245440471

[SYCL] Fix Wctad-maybe-unsupported warning

---

sycl/plugins/level_zero/pi_level_zero.cpp

E2E test: https://github.com/intel/llvm-test-suite/blob/intel/SYCL/Plugin/level_zero_batch_barrier.cpp

[SYCL][L0] Allow barrier batching

---

sycl/plugins/level_zero/pi_level_zero.cpp
sycl/plugins/level_zero/pi_level_zero.hpp
sycl/plugins/level_zero/usm_allocator.cpp
sycl/plugins/opencl/pi_opencl.cpp
sycl/plugins/unified_runtime/adapters/level_zero/ur_level_zero.cpp
sycl/plugins/unified_runtime/adapters/level_zero/ur_level_zero.hpp

[SYCL][L0] Address static analyzer issues

---

sycl/plugins/level_zero/pi_level_zero.cpp

[SYCL][L0] Address static analyzer issue with Queue->LastCommandEvent

---

buildbot/dependency.conf

OpenCL CPU RT:  2022.14.8.0.04 -> 2022.15.12.0.01
OpenCL FPGAEMU RT: 2022.14.8.0.04 -> 2022.15.12.0.01
OpenCL FPGA RT Linux: 20220710_000003 -> 20221104_143714
OpenCL FPGA RT Windows: 20220710_000003 -> 20221104_143951

[BuildBot] Uplift CPU/FPGAEMU RT version to 2022.15.12.0.01

---

.github/workflows/sycl_precommit.yml
devops/test_configs.json

Revert "[CI] Add CUDA on AWS run in pre-commit"

---

CONTRIBUTING.md
README.md
sycl/doc/developer/ContributeToDPCPP.md

* Add what to do with unexpected fails
* Add some cross-doc links

[SYCL][Doc] Add info on PR merge process

---

sycl/include/sycl/detail/defines.hpp

Signed-off-by: Zahira Ammarguellat <zahira.ammarguellat@intel.com>

Fix build issue that appeared in self-build using clang-15 version.

---

.github/workflows/sycl_windows_build_and_test.yml
.github/workflows/windows_test_comment_trigger.yml
sycl/CMakeLists.txt

Trying to trigger windows build and testing if a specific comment is posted.
The are complications:
1. For some reason, a workflow triggered by a comment is not displayed in the PR status(where all github actions are displayed). So, trying to update it manually.
2. The github hash provided for the default branch rather than for the PR branch.

windows if label

---

sycl/plugins/unified_runtime/pi_unified_runtime.cpp

[SYCL] Unused parameters

---

.github/workflows/windows_test_comment_trigger.yml

Move env section earlier so that $SHA is initialized before run section.
Remove commented out code.

[SYCL] Fix to windows on comment testing

---

sycl/plugins/level_zero/CMakeLists.txt

[SYCL] Properly install L0 loader

---

sycl/plugins/level_zero/CMakeLists.txt

[SYCL][L0] Prevent L0 loader from exporting extra symbols

---

clang/test/Driver/sycl-cuda-include-wrapper.cu

This solves https://github.com/intel/llvm/pull/7352#issuecomment-1369799280.

[SYCL][CUDA] Fix sycl-cuda-include-wrapper test

---

sycl/doc/UsersManual.md
sycl/doc/design/CompilerAndRuntimeDesign.md
sycl/doc/design/NonRelocatableDeviceCode.md
sycl/doc/design/NonReusableDeviceCode.md
sycl/doc/design/images/NoRDCFatArchive.svg
sycl/doc/design/images/NoRDCFatObject.svg
sycl/doc/index.rst

Update doc for No RDC mode.
I considered updating the diagrams or adding new ones, but the current ones are very simplified, contain no conditional logic and already skip cases today. We would need complex diagrams with conditional logic to accurately capture this feature which would become a barrier for users understanding the driver flow in most cases. An accurate diagram is available in the source code as a comment [here](https://github.com/intel/llvm/blob/sycl/clang/lib/Driver/Driver.cpp#L5435).
Signed-off-by: Sarnie, Nick <nick.sarnie@intel.com>

[SYCL][Doc] Update doc for No RDC mode

---

sycl/include/sycl/aliases.hpp
sycl/test/aliases-opencl.cpp

[SYCL] Implement sycl::opencl::cl_* aliases

---

clang/test/SemaSYCL/sub-group-size2.cpp

When PR #7918 was submitted, a test wasn't added along with it.

[SYCL] Test for PR #7918 - invalid value in named_sub_group_size

---

polygeist/tools/cgeist/Lib/CGCall.cc
polygeist/tools/cgeist/Lib/CGExpr.cc

[SYCL-MLIR][NFI]: Refactor CGExpr.cc and CGCall.cc

---

mlir-sycl/lib/Conversion/SYCLToLLVM/SYCLToLLVM.cpp
mlir-sycl/lib/Dialect/IR/SYCLOpsDialect.cpp
mlir-sycl/lib/Transforms/SYCLMethodToSYCLCall.cpp
polygeist/lib/polygeist/Ops.cpp
polygeist/lib/polygeist/Passes/AffineCFG.cpp
polygeist/lib/polygeist/Passes/CanonicalizeFor.cpp
polygeist/lib/polygeist/Passes/ConvertPolygeistToLLVM.cpp
polygeist/lib/polygeist/Passes/LoopRestructure.cpp
polygeist/lib/polygeist/Passes/Mem2Reg.cpp
polygeist/lib/polygeist/Passes/OpenMPOpt.cpp
polygeist/tools/cgeist/Lib/Attributes.cc
polygeist/tools/cgeist/Lib/clang-mlir.cc

[SYCL-MLIR][NFI]: Fix compilation warnings

---

sycl/plugins/level_zero/CMakeLists.txt

[SYCL][L0] Check that the L0 loader was built by us at install

---

polygeist/tools/cgeist/CMakeLists.txt
polygeist/tools/cgeist/Lib/CGDecl.cc
polygeist/tools/cgeist/Lib/clang-mlir.cc
polygeist/tools/cgeist/Lib/clang-mlir.h

[SYCL-MLIR][NFI]: Refactor and fix clang-tidy warnings 

---

sycl/include/sycl/detail/pi_error.def

[SYCL] Fix PI error messages

---

mlir-sycl/lib/Dialect/IR/SYCLOpsDialect.cpp
polygeist/tools/cgeist/Test/Verification/sycl/types.cpp

Addressed post commit review comments I gave in https://github.com/intel/llvm/pull/7729. 

[SYCL-MLIR] Post commit review comments for stream type

---

sycl/doc/extensions/experimental/sycl_ext_intel_esimd/sycl_ext_intel_esimd.md
sycl/include/sycl/ext/intel/esimd/xmx/common.hpp

[ESIMD][DOC][NFC] Document xmx::dpas() implementation

---

llvm/lib/ExecutionEngine/Interpreter/CMakeLists.txt
llvm/lib/ExecutionEngine/Interpreter/Interpreter.h

We will revert this change once we resolve the dependency on NEAT.

[OpenCL] Update Interpreter to support OpenCL CPU test

---

sycl/source/detail/global_handler.cpp
sycl/source/detail/global_handler.hpp
sycl/source/detail/scheduler/scheduler.cpp

[SYCL] Allow unittests to use drainThreadPool method on Win

---

polygeist/tools/cgeist/Lib/ValueCategory.cc
polygeist/tools/cgeist/Test/Verification/sycl/structvec.cpp

This PR fixes the bug reported in https://github.com/intel/llvm/pull/7822#pullrequestreview-1221786095.

[SYCL-MLIR] Fix store integer to vector pointer

---

sycl/include/sycl/ext/oneapi/experimental/bfloat16_math.hpp

Reverts intel/llvm#7959
See https://github.com/intel/llvm/issues/8040#issuecomment-1397753899

Revert "[SYCL] Add generic impl for bf16 fabs"

---

sycl/include/sycl/reduction.hpp

* reduction_impl(RedOutVar &Acc) ctor is dead
* associateWithHandler/placeholder accessor support in reduction_impl ctor isn't necessary in SYCL 2020 reductions as we can't have a placeholder accessor as an input here anymore (was removed with ext::oneapi::reduction support removal)
* With the above change, using "if constexpr" became even more appealing

[NFCI][SYCL] Simplify reduction.hpp around dead code
