llvm/lib/Transforms/Instrumentation/AddressSanitizer.cpp
llvm/lib/Transforms/Instrumentation/MemorySanitizer.cpp

Fix Coverity reported auto-copy issues.

[DviceSanitizer][Coverity] Fix auto-copy issues

---

libdevice/sanitizer/tsan_rtl.cpp
llvm/lib/Transforms/Instrumentation/ThreadSanitizer.cpp
llvm/test/Instrumentation/ThreadSanitizer/SPIRV/cleanup_private_shadow.ll
sycl/test-e2e/ThreadSanitizer/check_both_read.cpp
sycl/test-e2e/ThreadSanitizer/check_no_race.cpp

We need to skip the check for private memory, otherwise OpenCL CPU device may generate false positive reports due to stack re-use in different threads. However, SPIR-V builts 'ToPrivate' doesn't work as expected on OpenCL CPU device. So we need to manually cleanup private shadow before each function exit point.

[DevTSAN] Cleanup private shadow memory when function exit

---

unified-runtime/source/adapters/level_zero/v2/command_buffer.cpp
unified-runtime/source/adapters/level_zero/v2/command_list_manager.cpp
unified-runtime/source/adapters/level_zero/v2/command_list_manager.hpp
unified-runtime/source/adapters/level_zero/v2/queue_immediate_in_order.cpp

getSignalEvent in ur_command_list_manager returned nullptr when queue was not set. This was the case when initializing the command list manager in queue ctor called from urQueueCreateWithNativeHandle.
Fix this by passing queue to the command list manager and removing the default nullptr value from the ctor (to avoid this issue in future).
Also, even if queue is nullptr, return the event instead of nullptr from getSignalEvent. This event is mostly functional, it just cannot be used for profiling.

[SYCL][UR][L0 v2] fix urQueueCreateWithNativeHandle

---

sycl/doc/design/CommandGraph.md
sycl/doc/extensions/experimental/sycl_ext_oneapi_graph.asciidoc
sycl/source/detail/graph_impl.cpp
unified-runtime/scripts/core/EXP-COMMAND-BUFFER.rst
unified-runtime/source/adapters/opencl/device.cpp
unified-runtime/test/conformance/exp_command_buffer/fill.cpp

To support the SYCL-Graph extension on an OpenCL backend, we currently only require the presence of the `cl_khr_command_buffer` extension. This PR introduces an extra requirement on the [CL_COMMAND_BUFFER_SIMULTANEOUS_USE_KHR](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#CL_COMMAND_BUFFER_SIMULTANEOUS_USE_KHR) capability being present.
This is based on the [graph execution wording](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/experimental/sycl_ext_oneapi_graph.asciidoc#765-new-handler-member-functions) on the definition of `handler::ext_oneapi_graph()` that:
>  Only one instance of graph will execute at any time. If graph is submitted multiple times, dependencies are automatically added by the runtime to prevent concurrent executions of an …

[SYCL][UR][Graph] Require OpenCL simultaneous use

---

unified-runtime/source/adapters/cuda/queue.cpp
unified-runtime/source/adapters/hip/queue.cpp
unified-runtime/source/common/cuda-hip/stream_queue.hpp

This patch simplifies the stream queue constructor by using in-class initialization when appropriate. And uses the constructors to initialize the stream vectors.

[UR][CUDA][HIP] Create stream vectors in queue constructor

---

sycl/include/sycl/detail/vector_convert.hpp
sycl/include/sycl/vector.hpp
sycl/test/abi/layout_vec.cpp
sycl/test/basic_tests/vectors/storage.cpp
sycl/test/check_device_code/vector/vector_bf16_builtins.cpp
sycl/test/check_device_code/vector/vector_convert_bfloat.cpp
sycl/test/check_device_code/vector/vector_math_ops.cpp
sycl/test/regression/vec_array_windows.cpp

The problem with using `std::array` in `sycl::vec` is that we cannot compile it in some environments (namely, Windows) because the former may use something that is illegal in SYCL device code.
intel/llvm#17025 fixed that, but only did so under preview breaking changes mode, which does not satisfy some of our customers immediately.
This PR introduces two main changes:
- it allows to opt-in for new behavior through passing `-D__SYCL_USE_NEW_VEC_IMPL=1` macro without using
`-fpreview-breaking-changes` flag. That allows for a more gradual opt-in from customers who are interested in this fix
- it switches the imlpementation to use the new approach with C-style arrays if their size and alignment is the same as for the corresponding `std::array` - in that case their memory layout is expected to …

[SYCL] Switch to use plain array in `sycl::vec` in more cases (#17656)

---

clang/test/Driver/linker-wrapper-sycl-win.cpp
sycl/test/basic_tests/header_footer_diagnostics.cpp
sycl/test/basic_tests/is_group_trait.cpp
sycl/test/esimd/slm_init_local_accessor.cpp
sycl/test/syclcompat/launch/launch_policy_neg.cpp

This is a joined cherry-pick of intel/llvm#17367, intel/llvm#17362 and intel/llvm#17746 intended to fix a few remaining issues we see in 6.1 nightly validation run.
Descriptions of cherry-picked commits:
---
[SYCL] Disable launch_policy_neg.cpp on Windows (#17367)
Fails to compile on new MSVC.
Patch-by: Sarnie, Nick <nick.sarnie@intel.com>
---
[SYCL] Avoid testing race condition
Use no output file instead of default output file in LIT tests.
This occasionally caused errors on windows when multiple files compile
to the same output file. Using `-fsyntax-only` hjere also avoids running the full compiler pipeline
See #7872 for more context
Patch-By: David Garcia Orozco <david.garcia.orozco@intel.com>
---
[SYCL] Fix clang-linker-wrapper Windows test (#17746)
Failing now because I recently …

[SYCL][sycl-rel] Stabilize 6.1 nightly

---

sycl/test-e2e/Graph/Profiling/event_profiling_info.cpp
sycl/test-e2e/Graph/Profiling/event_profiling_info_usm.cpp
sycl/test-e2e/Graph/Update/lit.local.cfg
sycl/test-e2e/Graph/lit.local.cfg

The V2 adapter now has all required functionality.

[SYCL][E2E] enable graph tests for L0 v2 adapter

---

devops/scripts/benchmarks/utils/compute_runtime.py

To fix compilation issue with the newest compute-runtime

[SYCL][UR][Bench] bump IGC depdency version fro benchmarks

---

sycl/source/detail/queue_impl.hpp

by avoiding unnecessary temp shared_ptr creation

[SYCL] optimize finalizeHandlerPostProcess

---

sycl/source/detail/graph_impl.cpp

by using `const auto &` instead of `auto`.

[SYCL][Graph] Removing unnecessary copy of KernelName

---

.github/workflows/sycl-detect-changes.yml
.github/workflows/sycl-linux-precommit.yml

Our Ubuntu 22.04 container has CUDA 12.1 installed while Ubuntu 24.04 image has CUDA 12.6.1 installed.
If a PR changes CUDA adapter, we should test the change with both CUDA versions.

[CI] Run build on Ubuntu 22, pre-commit if CUDA adapter changes.

---

sycl/test-e2e/Basic/image/image_max_size.cpp

This test requires a significant amount of host memory. It has been observed that sometimes (very rarely) the test may fail with OUT_OF_HOST_MEMORY error, especially when run in parallel with other "high-overhead" tests. Refer CMPLRLLVM-66341.
This PR makes the test ignore failure if that happens. An alternative is to check for the available host memory and skip the test if it is too low. However, that approach is still susceptible to race conditions.

[SYCL][E2E] Fix flaky failure of `Basic/image/image_max_size.cpp`

---

.github/workflows/sycl-linux-precommit.yml
.github/workflows/sycl-windows-precommit.yml

A number of changes to UR won't have any observable effects on SYCL
builds, so no point in running a full SYCL build and e2e test for them.

[CI] Don't run SYCL testing for changes that only affect UR

---

sycl/test-e2e/bindless_images/bindless_aspects.cpp
sycl/test-e2e/bindless_images/image_get_info.cpp
sycl/test-e2e/bindless_images/image_reqs_get_info.cpp

image_get_info.cpp previously comprised three types of tests which have been split into separate test files
- testing queries of a `oneapi::experimental::image_mem` instance (image_get_info.cpp)
- testing device queries for image requirements (either max image dimensions or pitch alignment) (image_reqs_get_info.cpp)
- testing device queries for bindless images aspects (bindless_aspects.cpp)
This PR splits up these tests which is useful for diagnosing problems on different backends:
- image_get_info.cpp is currently only unsupported on the HIP backend (Known issue)
- image_reqs_get_info.cpp is currently only unsupported on the L0 backend https://github.com/intel/llvm/issues/17663
- bindless_aspects.cpp has been fixed on L0 backend so it now passes on all backends, by only querying …

[BINDLESS][E2E] Split image_get_info into three tests

---

unified-runtime/test/conformance/context/urContextSetExtendedDeleter.cpp
unified-runtime/test/conformance/enqueue/urEnqueueEventsWaitMultiDevice.cpp
unified-runtime/test/conformance/enqueue/urEnqueueKernelLaunch.cpp
unified-runtime/test/conformance/enqueue/urEnqueueKernelLaunchAndMemcpyInOrder.cpp
unified-runtime/test/conformance/exp_command_buffer/fixtures.h
unified-runtime/test/conformance/kernel/urKernelCreate.cpp
unified-runtime/test/conformance/memory-migrate/urMemBufferMigrateAcrossDevices.cpp
unified-runtime/test/conformance/memory/urMemBufferPartition.cpp
unified-runtime/test/conformance/memory/urMemImageCreateWithImageFormatParam.cpp
unified-runtime/test/conformance/program/urProgramCreateWithIL.cpp
unified-runtime/test/conformance/program/urProgramLink.cpp
unified-runtime/test/conformance/sampler/urSamplerCreate.cpp
unified-runtime/test/conformance/source/environment.cpp
unified-runtime/test/conformance/testing/include/uur/checks.h
unified-runtime/test/conformance/testing/include/uur/environment.h
unified-runtime/test/conformance/testing/include/uur/fixtures.h
unified-runtime/test/conformance/testing/include/uur/known_failure.h

The driver I have at least has a number of issues, the largest of which
is that it lacks an IR compiler. This updates tests so that they are
skipped if required.

[UR] Improve testing for gfx1100 on OpenCL

---

sycl/source/detail/async_alloc.cpp
sycl/source/detail/cg.hpp
sycl/source/detail/handler_impl.hpp
sycl/source/handler.cpp

This patch removes unused handler_impl members.

[AsyncAlloc][SYCL][Exp] Remove unused handler members

---

sycl/include/sycl/handler.hpp
sycl/test-e2e/GroupAlgorithm/root_group.cpp

Address issue https://github.com/intel/llvm/issues/16451 , where property `use_root_sync` is not processed properly. Also revised `sycl/test-e2e/GroupAlgorithm/root_group.cpp` to not use the deprecated version of `parallel_for`. (Which was previously blocked by this issue about `use_root_sync`).
Also here's some explanation for the change in `handler.hpp`:
This is where the previous code doesn't handle `use_root_sync` correctly: `processLaunchProperties` will be called twice, first for the property list returned by the kernel functor's `get(properties_tag)` method, and then for `Props` that is passed in as a parameter to `parallel_for`. Therefore, if the `get(properties_tag)` method specifies `use_root_sync` and `Props` is empty or doesn't contain `use_root_sync`, what will be done is:
- …

[SYCL] Fix use_root_sync handling

---

unified-runtime/test/CMakeLists.txt

This contains a fix for https://github.com/google/googletest/pull/4036 ,
which we encounter if we are outputting JSON and the test runner finds
no adapters.

[UR] Bump googletest version

---

unified-runtime/test/conformance/exp_command_buffer/fill.cpp

This PR disables flaky fill test for command buffer that was enabled in https://github.com/intel/llvm/pull/17709. 
The issue is connected to the bug in the driver that is patched in new version, but the CI machines still have the old one, which causes it to sometimes fail (for example https://github.com/intel/llvm/actions/runs/14250564960/job/39942652796?pr=17836)

Disable fill test for command buffer v2

---

unified-runtime/test/conformance/context/urContextGetInfo.cpp
unified-runtime/test/conformance/event/urEventGetInfo.cpp
unified-runtime/test/conformance/kernel/urKernelGetInfo.cpp
unified-runtime/test/conformance/platform/urPlatformGetInfo.cpp
unified-runtime/test/conformance/program/urProgramGetInfo.cpp
unified-runtime/test/conformance/queue/urQueueGetInfo.cpp
unified-runtime/test/conformance/sampler/urSamplerGetInfo.cpp

This tests that converting a UR handle to a native handle, then back
into a UR handle preserves/recreates any handles contained within it.
The event test is a special case; since urEventCreateWithNativeHandle
doesn't accept a queue paramater. For this, we tollerate a different
queue being created, as long as they both have the same underlying
native handle.

[UR] Added "roundtrip" GetInfo comformance tests

---

.github/workflows/sycl-linux-build.yml

This patch adds a step to conditionally pack pure sycl-toolchain for release.

[CI] Pack release build

---

sycl/include/sycl/handler.hpp

We've removed host device support some time ago.

[NFCI][SYCL] `DPCPP_HOST_DEVICE_*` can't be set

---

unified-runtime/source/adapters/level_zero/command_buffer.cpp
unified-runtime/source/adapters/level_zero/common.hpp
unified-runtime/source/adapters/level_zero/context.cpp
unified-runtime/source/adapters/level_zero/device.cpp
unified-runtime/source/adapters/level_zero/device.hpp
unified-runtime/source/adapters/level_zero/event.cpp
unified-runtime/source/adapters/level_zero/platform.cpp
unified-runtime/source/adapters/level_zero/platform.hpp
unified-runtime/source/adapters/level_zero/queue.cpp

@nrspruit's [patch ](https://github.com/intel/llvm/pull/17106)rebased and posted here as I work on fixing this patch. 
- Refactor's the check for driver in order lists into one place, but still disables driver in order lists by default.

Updated Driver In order lists check and required version

---

clang/lib/Driver/ToolChains/Clang.cpp
clang/test/Driver/sycl-host-compiler-old-model.cpp

Addresses https://github.com/intel/llvm/issues/15120
This patch emits an error when `-fsycl-unnamed-lambda` is used in conjunction with `-fsycl-host-compiler`
Also, use of `-fsycl-host-compiler` implicitly adds `-fno-sycl-unnamed-lambda` to the list of command line arg strings.

[SYCL][Driver] '-fsycl-unnamed-lambda' is not supported with '-fsycl-host-compiler'

---

devops/scripts/benchmarks/options.py
devops/scripts/benchmarks/utils/compute_runtime.py

Latest IGC doesn't build on the compilers on the perf testing systems due to warnings. This patch bumps up the driver to latest and also adds -Wno-error when building IGC.
Nightly is broken: https://github.com/oneapi-src/unified-runtime/actions/runs/14297928864, this fixes it. Please prioritize this @intel/llvm-reviewers-benchmarking.

[CI][Benchmarks] update compute runtime and fix IGC build

---

devops/scripts/benchmarks/benches/llamacpp.py
devops/scripts/benchmarks/utils/oneapi.py
devops/scripts/benchmarks/utils/utils.py

This patch updates llama.cpp to the latest available version, uses a new, more relevant, GGUF model, and updates oneAPI to 2025.1.
I was trying to avoid updating oneAPI, but the latest llama.cpp internal pooling logic seems to be broken on 2025.0, resulting in double-free errors when using older oneAPI components.
The utils.download function also had to be updated, because it was using a deprecated features and didn't work on some configurations.

[CI][Benchmarks] update llama.cpp and requirements to latest

---

devops/scripts/benchmarks/benches/compute.py

```
running graph_api_benchmark_sycl SubmitGraph numKernels:4 ioq 0 measureCompletion 0, iteration 0... 
graph_api_benchmark_sycl SubmitGraph numKernels:4 ioq 0 measureCompletion 0 complete (graph_api_benchmark_sycl SubmitGraph numKernels:4 ioq 0 measureCompletion 0: 14.738 μs).
running graph_api_benchmark_sycl SubmitGraph numKernels:4 ioq 0 measureCompletion 1, iteration 0... 
graph_api_benchmark_sycl SubmitGraph numKernels:4 ioq 0 measureCompletion 1 complete (graph_api_benchmark_sycl SubmitGraph numKernels:4 ioq 0 measureCompletion 1: 15.132 μs).
running graph_api_benchmark_sycl SubmitGraph numKernels:10 ioq 0 measureCompletion 0, iteration 0... 
graph_api_benchmark_sycl SubmitGraph numKernels:10 ioq 0 measureCompletion 0 complete (graph_api_benchmark_sycl SubmitGraph numKernels:10 ioq …
```

[Benchmarks][CI] add UR SubmitGraph benchmark

---

sycl/source/detail/kernel_program_cache.hpp

When the `traceKernel` function is called with a C-string as a parameter, a temporary `std::string` object is created. This PR change the `traceKernel` function to accept `std::string_view` instead `const std::string &`.

[SYCL] Fix `traceKernel` function to avoid temporary string creation

---

sycl/test-e2e/Basic/interop/get_native_ze.cpp
sycl/test-e2e/Graph/Inputs/interop-level-zero-get-native-mem.cpp
sycl/test-e2e/Graph/Inputs/interop-level-zero-launch-kernel.cpp
sycl/test-e2e/Graph/NativeCommand/level-zero_usm.cpp
sycl/test-e2e/Graph/NativeCommand/level-zero_usm_D2H_copy.cpp

Continuation of: https://github.com/intel/llvm/pull/17699

[UR][E2E] add missing zeInit calls to interop tests

---

unified-runtime/source/loader/layers/sanitizer/asan/asan_interceptor.cpp
unified-runtime/source/loader/layers/sanitizer/asan/asan_shadow.cpp
unified-runtime/source/loader/layers/sanitizer/asan/asan_shadow.hpp
unified-runtime/test/layers/sanitizer/asan.cpp

Two fixes for asan:
* The test has been updated to run on all adapters and also skip HIP
and OpenCL (which don't support the required VirtualMem functions).
* GetShadowMemory has been changed to CreateShadowMemory. Previously,
shadow memory had a static lifetime, while the Context that was used
to construct it only had a lifetime of the `AsanInterceptor` object.
It has been changed and now each `AsanInterceptor` creates its own
shadow memory.

[UR] ASan layer fix and test update

---

sycl/include/sycl/detail/builtins/helper_macros.hpp
sycl/include/sycl/detail/builtins/math_functions.inc
sycl/include/sycl/detail/builtins/relational_functions.inc
sycl/include/sycl/detail/spirv.hpp
sycl/include/sycl/detail/vector_convert.hpp
sycl/include/sycl/vector.hpp
sycl/test-e2e/DeviceLib/built-ins/printf.cpp
sycl/test/basic_tests/generic_type_traits.cpp
sycl/test/basic_tests/vectors/assign.cpp
sycl/test/basic_tests/vectors/swizzle_aliases.cpp

https://github.com/KhronosGroup/SYCL-Docs/pull/676

[SYCL] Remove underspecified `vec::vector_t`

---

unified-runtime/source/adapters/opencl/command_buffer.cpp
unified-runtime/source/adapters/opencl/device.hpp

* When creating a command buffer, we might encounter errors and leaked
the queue. Now it is released if required.
* When creating a device, we assert that getting the type was
successful. This should never be false since none of the errors apply
(it shouldn't allocate any memory either).

[UR] Fix two issues flagged by coverity

---

sycl/test-e2e/Matrix/Inputs/joint_matrix_bf16_fill_k_cache_impl.hpp

Fixes #17516
Tests that include `joint_matrix_bf16_fill_k_cache_impl.hpp` may fail on windows with the following message `error: no member named 'high_resolution_clock' in namespace 'std::chrono'`. Including chrono resolves this.

[Matrix][E2E] Include `chrono` in Matrix test on Windows

---

libclc/test/CMakeLists.txt
libclc/test/lit.cfg.py

Multiple libclc test targets were running essentially the same test suite in parallel. This could result in data races when one target writes a file another target is reading.
This commit fixes the issue by creating a unique test execution directory per target. We already have a unique libclc target known as an 'arch suffix' in CMake. This suffix is used as the unique builtins file name. We pass this through to LIT via a parameter to create the execution directory. Note this use of LIT (i.e., having one suite called multiple times in different configurations) is unconventional so there aren't many similar examples in LLVM.
Patch proposed by @bader.

[libclc] Fix data races in libclc/libspirv LIT tests

---

.github/CODEOWNERS

Changes in the cts_exclude_filter dir only affect CI.

[CODEOWNERS] Assign sycl/cts_exclude_filters to devops

---

sycl/source/detail/program_manager/program_manager.cpp

Avoid constructing a platform object to get the platform_impl shared_ptr.

[SYCL] Get platform_impl shared_ptr directly

---

sycl/source/detail/program_manager/program_manager.cpp

The change reduces the overhead of a root device search, if the given device is already a root device. It also removes the unnecessary UR call and shared_ptr copy in such a case.

[SYCL] Reduce overhead of root device search

---

sycl/source/handler.cpp

Avoid the event_impl shared_ptr copy by removing a temporary variable and using a reference instead.

[SYCL] Avoid event_impl shared_ptr copy

---

sycl/test-e2e/Graph/Inputs/compile_time_local_memory.cpp

With the current way that the local_memory extension is implemented, accessing the local memory requires the use of parenthesis to avoid using the [] operator from the multi-ptr.

[SYCL][Graphs] Fix issue with compile time local memory test

---

unified-runtime/test/conformance/enqueue/urEnqueueTimestampRecording.cpp

The test is flaky on V2, similarly to
urEnqueueTimestampRecordingExpTest.SuccessBlocking

[SYCL][UR][CTS] Mark known failure on L0 v2

---

unified-runtime/cmake/FetchLevelZero.cmake

- Fix to use the version of the L0 Loader which addresses the issues with dynamically enabling the tracing layer during execution. Previously, this path was not working correctly to allow intercepting the UR calls.

[UR][L0] Update L0 static loader to fix dynamic tracing

---

libdevice/sanitizer/tsan_rtl.cpp
llvm/lib/Transforms/Instrumentation/ThreadSanitizer.cpp
llvm/test/Instrumentation/ThreadSanitizer/SPIRV/instrument_barrier.ll
sycl/test-e2e/ThreadSanitizer/check_device_barrier.cpp
sycl/test-e2e/ThreadSanitizer/check_group_barrier.cpp
unified-runtime/source/loader/layers/sanitizer/tsan/tsan_ddi.cpp
unified-runtime/source/loader/layers/sanitizer/tsan/tsan_libdevice.hpp

Barrier instructions will synchronize work items execution status, we
need to sync thread clocks before/after barrier call to avoid false
positive reports.

[DevTSAN] Sync thread clocks before/after barrier call

---

unified-runtime/scripts/templates/helper.py
unified-runtime/scripts/templates/valddi.cpp.mako
unified-runtime/source/loader/layers/validation/ur_valddi.cpp
unified-runtime/test/layers/validation/leaks.cpp
unified-runtime/test/layers/validation/leaks.out.match

On handle release, the validation layer reports event handles obtained via enqueue functions as invalid. This patch should fix this behavior.

[UR] Track handles from enqueue functions in validation layer

---

sycl/test-e2e/Basic/free_function_queries/free_function_queries.cpp
sycl/test-e2e/Basic/free_function_queries/free_function_queries_sub_group.cpp
sycl/test/e2e_test_requirements/no-unsupported-without-info.cpp

This patch:
* enables free function tests
* re-writes them in terms of `sycl::ext::oneapi::this_work_item` (instead of, now deprecated, `sycl::ext::oneapi::experimental::this_id` and friends)
* fixes build failure caused by the removal of `core_sg_supported`
* removes a test from `free_function_queries.cpp` as it was only checking correct translation between old and new spelling of the extension

[SYCL] [E2E] Fix free funcs tests

---

.github/workflows/sycl-linux-build.yml
.github/workflows/sycl-nightly.yml

This PR addresses https://github.com/intel/llvm/issues/17609, which introduces `--no-assertions` for the archive `sprod_shared`/`linux_shared_build`.
This archive is currently not used anywhere: The intention is that we could leverage it for CI runs where performance matters (e.g. benchmarking).

[CI] Disable assertions for linux_shared_build in sycl-linux-build.yml

---

sycl/source/detail/program_manager/program_manager.cpp
sycl/source/detail/program_manager/program_manager.hpp
sycl/unittests/program_manager/Cleanup.cpp

The handler calls the `ProgramManager::kernelUsesAssert` with `const char *` argument. It resulted in a temporary `std::string` creation. This PR changes the `ProgramManager::kernelUsesAssert` to accept template parameter and uses heterogeneous lookup feature of `std::set`

[SYCL] Fix `ProgramManager::kernelUsesAssert` to avoid tmp string creation

---

sycl/test-e2e/AddressSanitizer/common/options-statistics.cpp
unified-runtime/source/loader/layers/sanitizer/asan/asan_interceptor.cpp
unified-runtime/source/loader/layers/sanitizer/asan/asan_shadow.cpp
unified-runtime/source/loader/layers/sanitizer/asan/asan_shadow.hpp

- Create the internal context in "ShadowMemory" constructor
- Remove "static" in "ShadowMemory::Setup" and "ShadowMemory::Destroy", because `AsanInterceptor::getOrCreateShadowMemory` is single thread

[DeviceASAN] Fix multiple contexts in memory overhead statistics

---

sycl/include/sycl/detail/export.hpp

Right now it's applied globally, affecting code other than SYCL headers when included. After removing the pragma, no additional warnings are observed when building on Windows.

[SYCL][NFC] Drop suppression of export related warnings

---

sycl/source/detail/scheduler/commands.cpp
sycl/source/detail/scheduler/commands.hpp

Change the `emitKernelInstrumentationData` to accept `std::string_view` instead of `std::string` to avoid temporary `std::string` object creation on a hot path.

[SYCL] Change `emitKernelInstrumentationData` to avoid temporary `std::string` object creation

---

sycl/CMakeLists.txt
sycl/source/detail/scheduler/scheduler.hpp
sycl/tools/sycl-ls/CMakeLists.txt
sycl/unittests/CMakeLists.txt
sycl/unittests/SYCL2020/GetNativeOpenCL.cpp
sycl/unittests/SYCL2020/SpecializationConstant.cpp
sycl/unittests/buffer/BufferLocation.cpp
sycl/unittests/buffer/Image.cpp
sycl/unittests/context_device/DeviceRefCounter.cpp
sycl/unittests/kernel-and-program/Cache.cpp
sycl/unittests/kernel-and-program/InMemCacheEviction.cpp
sycl/unittests/kernel-and-program/KernelBuildOptions.cpp
sycl/unittests/kernel-and-program/KernelInfo.cpp
sycl/unittests/kernel-and-program/KernelRelease.cpp
sycl/unittests/kernel-and-program/MultipleDevsCache.cpp
sycl/unittests/kernel-and-program/OutOfResources.cpp
sycl/unittests/program_manager/BuildLog.cpp
sycl/unittests/program_manager/CompileTarget.cpp
sycl/unittests/program_manager/itt_annotations.cpp
sycl/unittests/scheduler/RequiredWGSize.cpp

Currently, we suppress all deprecation warnings when building the runtime. This patch limits it to just those coming from the SYCL API.

[SYCL][NFC] Suppress only SYCL deprecation warnings when building

---

.github/workflows/sycl-rel-nightly.yml

The customer doesn't want to have this feature because of the big binary size.

[CI][sycl-rel] Disable sycl-jit

---

.github/workflows/sycl-windows-build.yml

Follow up to https://github.com/intel/llvm/pull/17781

[CI] Pack release build on Win

---

.github/workflows/ur-build-hw.yml

Setting ZE_DEBUG impacts test execution time and introduces delays that can hide problems in the UR adapters.
Also, with ZE_DEBUG logs generated by CI jobs are tens of megabytes in size which makes it difficult to analyze then (at least online).

[SYCL][CI] do not set ZE_DEBUG when running UR tests

---

sycl/source/detail/graph_impl.cpp

Fix coverity hit regarding an opportunity in `graph_impl` to use `std::move` instead of implicitly copying.

[SYCL][Coverity] Fix COPY_INSTEAD_OF_MOVE hit in Coverity

---

unified-runtime/source/adapters/opencl/adapter.cpp
unified-runtime/source/adapters/opencl/adapter.hpp
unified-runtime/source/adapters/opencl/command_buffer.cpp
unified-runtime/source/adapters/opencl/common.hpp
unified-runtime/source/adapters/opencl/context.cpp
unified-runtime/source/adapters/opencl/context.hpp
unified-runtime/source/adapters/opencl/enqueue.cpp
unified-runtime/source/adapters/opencl/kernel.cpp
unified-runtime/source/adapters/opencl/memory.cpp
unified-runtime/source/adapters/opencl/program.cpp
unified-runtime/source/adapters/opencl/usm.cpp

Rather than using atexit handles to drop the adapter (which causes ordering issues with SYCL atexit handlers), `urAdapterRetain/Release` now update a reference counter. When the last adapter handle is Released, the adapter is dropped.
Since it is now simple to do so, the function cache has been moved to be a member of the adapter itself rather than being a separate global.

[UR] Add reference counting and ext. fn cache to OpenCL adapters

---

clang/lib/Sema/SemaSYCL.cpp

This PR is quick fix to avoid error 
clang/lib/Sema/SemaSYCL.cpp:6584:25: error: private field 'Policy' is not used [-Werror,-Wunused-private-field]

[SYCL] remove unused class field

---

sycl/cmake/modules/FetchUnifiedRuntime.cmake
unified-runtime/CMakeLists.txt

This doesn't affect the behaviour of UR_EXTERNAL_DEPENDENCIES - since it gets used as a list, if you try to set it to a string that cmake can't convert to a list you get a fatal error (e.g. doing `set(UR_EXTERNAL_DEPENDENCIES "my-dep my-other-dep")` rather than `set(UR_EXTERNAL_DEPENDENCIES "my-dep;my-other-dep")`).
The list of valid cache variable types is here https://cmake.org/cmake/help/latest/prop_cache/TYPE.html

[UR][SYCL] Fix cmake LIST cache variables - LIST is not a valid cache type.

---

devops/scripts/benchmarks/benches/base.py

Define base.Benchmark and base.Suite as abstract classes. They are not meant to be instantiated.

[CI][Benchmarks] Define abstract classes

---

sycl/test-e2e/MemorySanitizer/check_large_access.cpp
sycl/test-e2e/MemorySanitizer/local/parallel_for_work_group.cpp

[Failing](https://github.com/intel/llvm/issues/17959) in nightly

[SYCL][E2E] Disable MemorySanitizer tests failing on OCL CPU

---

.github/workflows/sycl-nightly.yml

Some people use the nightly and we don't want to require users to have it installed.
Manually verified the fix both by reproducing the original error and DependencyWalker.
Closes: https://github.com/intel/llvm/issues/17950

[CI] Don't require SPIR-V Tools in Windows nightly

---

sycl/source/detail/program_manager/program_manager.cpp

In `ProgramManager::removeImages`, we cleanup our KernelName2KernelID mapping, before using that exact mapping retrieve KernelIDs in order to clean up our KernelIDs2BinImage mapping. This PR cleans up `m_KernelID2BinImage` mapping before cleaning up `m_KernelName2KernelIDs` maping.
This is inteded to fix a hit raised by Coverity.

[SYCL][Coverity] Fix invalid iterator coverity hit

---

clang/lib/Driver/ToolChains/Clang.cpp
clang/test/Driver/sycl-device-optimizations.cpp
sycl/test-e2e/InvokeSimd/Regression/ImplicitSubgroup/debug_symbols.cpp
sycl/test-e2e/InvokeSimd/Regression/debug_symbols.cpp

Reverts https://github.com/intel/llvm/pull/16408

[SYCL][Driver] Revert -O0 as the default SYCL device optimization if -g is passed.

---

unified-runtime/source/adapters/hip/CMakeLists.txt
unified-runtime/source/adapters/hip/usm.cpp
unified-runtime/source/adapters/hip/usm.hpp
unified-runtime/test/conformance/usm/urUSMPoolCreate.cpp

This patch fixes up and enable memory pools for the HIP adapter, it is based on https://github.com/oneapi-src/unified-runtime/pull/1689 and on the CUDA adapter implementation.
The initial patch had segmentation faults in the CI that we couldn't reproduce locally. That happened as well in this patch and I couldn't reproduce the segfaults locally either.
However I noticed that it failed in `urUSMHostAlloc`, and that entry point was different from the CUDA adapter version, in that the HIP adapter was using a "helper" function. It turns out that the helper function was using a device pool instead of a host pool to do the allocation, which seemed obviously wrong. Replacing the helper by similar code used in the CUDA adapter fixes the crash in the CI.

[UR][HIP] Enable usm pools

---

unified-runtime/source/adapters/opencl/device.hpp

Follow up from https://github.com/intel/llvm/pull/17931, additional fix for URT-903.

[UR] Retain and release device handles for sub-devices

---

libdevice/cmake/modules/SYCLLibdevice.cmake
libdevice/nativecpu_utils.cpp

This ensures that functions have the right linkage.
Several functions are marked as used to prevent them from being removed as dead code before the work item loop pass and `PrepareSYCLNativeCPUPass` run.

[SYCL][NativeCPU] Process nativecpu_utils with prepare_builtins

---

unified-runtime/source/adapters/cuda/CMakeLists.txt
unified-runtime/source/adapters/cuda/usm.cpp
unified-runtime/source/adapters/hip/CMakeLists.txt
unified-runtime/source/adapters/hip/device.cpp
unified-runtime/source/adapters/hip/usm.cpp

Pool tracking is now always enabled for UMF and cannot be disabled, so we can remove these ifdefs.

[UR][CUDA][HIP] Remove umf pool tracking ifdefs

---

sycl/doc/design/CompileTimeProperties.md
sycl/doc/extensions/experimental/sycl_ext_oneapi_kernel_properties.asciidoc
sycl/doc/extensions/proposed/sycl_ext_intel_fpga_kernel_interface_properties.asciidoc
sycl/include/sycl/handler.hpp
sycl/include/syclcompat/launch_policy.hpp
sycl/test-e2e/Basic/max_linear_work_group_size_props.cpp
sycl/test-e2e/Basic/max_work_group_size_props.cpp
sycl/test-e2e/Basic/sub_group_size_prop.cpp
sycl/test-e2e/Basic/work_group_size_prop.cpp
sycl/test-e2e/Graph/Inputs/sub_group_prop.cpp
sycl/test-e2e/Graph/Inputs/work_group_size_prop.cpp
sycl/test-e2e/GroupAlgorithm/root_group.cpp
sycl/test/check_device_code/extensions/properties/properties_kernel_launch_bounds.cpp
sycl/test/check_device_code/extensions/properties/properties_kernel_max_work_group_size.cpp
sycl/test/extensions/properties/properties_kernel_device_has_warning.cpp
sycl/test/extensions/properties/properties_kernel_negative.cpp
sycl/test/extensions/properties/properties_kernel_negative_device.cpp
sycl/test/virtual-functions/diagnostics-positive.cpp
sycl/test/virtual-functions/properties-positive.cpp
unified-runtime/test/conformance/device_code/fixed_sg_size.cpp
unified-runtime/test/conformance/device_code/fixed_wg_size.cpp
unified-runtime/test/conformance/device_code/max_wg_size.cpp
unified-runtime/test/conformance/device_code/subgroup.cpp

Currently some of our docs suggest using `get(properties_tag) {...}` member in kernel functors to specify kernel properties while some suggest using `get(properties_tag) const {...}`. But actually `get(properties_tag) {...}` might not work under certain conditions, so we should update the incorrect docs that they suggest readers to use `get(properties_tag) const {...}` rather than  `get(properties_tag) {...}`.
Also as @Pennycook suggested, added a diagnostic warning to indicate the user when:
-they have declared a `get(properties_tag)` member in the kernel functor
AND
-they declared `get(properties_tag){...}` rather than `get(properties_tag) const {...}`
Updated the tests containing the non-const version of `get(properties_tag)` as well.

[SYCL] Correct spec about constness of get(properties_tag) member and add respective warning

---

sycl/test-e2e/E2EExpr.py
sycl/test-e2e/lit.cfg.py

We need to set `cuda-path`/`hip-path` on Windows as the autodetection isn't implemented upstream, it seems only implemented for Linux.
Also fix a double assign and a missed update in `E2EExpr`
This was tested with some other pending changes [here](https://github.com/intel/llvm/actions/runs/14389689524/job/40353640119?pr=14114) and [here](https://github.com/intel/llvm/actions/runs/14389689487/job/40353627543?pr=14114).

[SYCL][E2E] Fix CUDA/HIP options on Windows

---

libclc/libspirv/lib/native_cpu/SOURCES
libclc/libspirv/lib/native_cpu/workitem/get_global_id.cl
libclc/libspirv/lib/native_cpu/workitem/get_global_size.cl
libclc/libspirv/lib/native_cpu/workitem/get_num_sub_groups.cl
libclc/libspirv/lib/native_cpu/workitem/get_sub_group_size.cl
libdevice/nativecpu_utils.cpp

Several functions were being defined both in libclc and in libdevice, but had different definitions between the two. This commit changes it so that they are only defined once, in libclc, with the definition that we had in libdevice that we were relying on taking precedence.

[SYCL][NativeCPU] Unify definitions of __spirv_* functions.

---

unified-runtime/source/adapters/level_zero/event.cpp
unified-runtime/source/adapters/level_zero/queue.cpp

- Fix barrier wait cleanup of events given an out event such that an additional refcnt release is done and with multi command lists and in order, the active barrier is properly cleared before reassignment.

[UR][L0] Fix Barrier Event Cleanup

---

sycl/include/sycl/handler.hpp

Follows what I started in https://github.com/intel/llvm/pull/17838.

[SYCL][NFCI] More refactoring around "kernel wrapping"

---

sycl/test-e2e/KernelAndProgram/cache_env_vars.cpp
sycl/test-e2e/KernelAndProgram/cache_env_vars_lin.cpp

Logically, it affects subsequent `%{run}` lines so must be done in run-mode, not in build-mode.

[SYCL][E2E] Use `%{run-aux}` when removing `%t/cache_dir`

---

devops/scripts/update_drivers.py

Neil suggested we do this, and the prerelease versions probably won't have binaries anyway so trying to use the artifact will fail.
Formatter made me fix some unrelated stuff too.

[CI] Don't use prereleases for Level Zero

---

unified-runtime/source/loader/layers/sanitizer/ur_sanitizer_layer.cpp

`die()` would write to the logger, bringing the potential exception.

[DeviceSanitizer][Coverity] Fix uncaught exception issue

---

unified-runtime/source/adapters/cuda/usm.cpp
unified-runtime/source/adapters/cuda/usm.hpp
unified-runtime/source/adapters/hip/usm.cpp
unified-runtime/source/adapters/hip/usm.hpp

There's no need for a wrapper here we can directly throw `ur_result_t`.

[UR][CUDA][HIP] Remove unnecessary USM exception wrapper

---

unified-runtime/source/adapters/cuda/image.cpp
unified-runtime/source/adapters/cuda/kernel.cpp
unified-runtime/source/adapters/cuda/memory.cpp
unified-runtime/source/adapters/cuda/platform.cpp
unified-runtime/source/adapters/cuda/usm.cpp
unified-runtime/source/adapters/hip/command_buffer.cpp
unified-runtime/source/adapters/hip/device.cpp
unified-runtime/source/adapters/hip/enqueue.cpp
unified-runtime/source/adapters/hip/image.cpp
unified-runtime/source/adapters/hip/kernel.cpp
unified-runtime/source/adapters/hip/memory.cpp
unified-runtime/source/adapters/hip/platform.cpp
unified-runtime/source/adapters/hip/usm.cpp

Most of the parameter checking is done in the UR validation layer, so we don't need to re-do it in the adapters.
The adapters should only do parameter checking that can't be done in the validation layer.

[UR][CUDA][HIP] Remove duplicated parameter checking

---

sycl/doc/extensions/experimental/sycl_ext_oneapi_graph.asciidoc

SYCL-Graph contains two aspects for a device to report extension support. Make the relationship between the two aspects clearer to readers, as it wasn't immediately obvious to reviewers of an [application PR](https://github.com/ggml-org/llama.cpp/pull/12873) using these aspects.

[NFC][SYCL][Graph][Doc] Clarify aspect relationship

---

sycl/source/detail/ur.cpp

Fixes #18012 by having the `urLoggerCallback()` ignore messages which are not warnings as errors should be handled via other mechanisms, i.e. UR error codes translated into exception messages or by explicitly enabling logging.

[SYCL][UR] Ignore errors in logger callback

---

sycl/include/sycl/handler.hpp

This is a "reduction" overload that just happens to dispatch immediately to the non-reduction range+properties version of `parallel_for`. Going through the simpler overload (unused before this PR) seems to be cheaper.
E.g., for
```
template <typename...> struct Name;
template <typename Krn> struct Invoker {
static void call(void *p, int i) { (*static_cast<Krn *>(p))(i); }
};
void invoke(void (*)(void *, int));
struct Kernel {
using PointersVariant =
std::variant<std::int8_t *, std::int16_t *, std::uint8_t *,
std::uint16_t *, float *, double *, sycl::half *>;
PointersVariant lhs;
PointersVariant rhs;
std::size_t sz;
PointersVariant out;
template <typename T>
Kernel(T *l, T *r, std::size_t size, T *o)
: lhs(l), rhs(r), sz(size), out(o) {}
void operator()(sycl::handler &h) {
std::visit( …
```

[SYCL][NFCI] Don't go through variadic for `parallel_for(range<N>, krn)`

---

sycl/include/sycl/handler.hpp

After https://github.com/intel/llvm/pull/18015 `wrap_kernel` is powerful enough to substitute it with just a minor tweak.

[SYCL][NFCI] Remove `single_task_lambda_impl` helper

---

devops/dependencies.json
devops/scripts/update_drivers.py

Level Zero had a new full-quality release and it has binaries so we can use it now.
Also, we've had this issue forever:
```
The following packages have unmet dependencies:
intel-igc-cm : Depends: intel-igc-core (>= 1.0.9995) but it is not installabl
```
The problem was the prerelease version of CM has bad dependencies, use the latest released version which works fine, and we don't really use CM anyway.
Formatter made me fix some unrelated areas again.

[CI] Bump L0 version and fix dpkg dep issue

---

unified-runtime/source/common/logger/ur_logger.hpp

Change #17095 introduced a failure in the logger_validation test due to
an incorrect merging of the default and "current" log level. This
change reverts to the old behavior where an invalid `output` value causes
the logger to use the default `level`.

[UR] Fix logger_validation test

---

libdevice/sanitizer/asan_rtl.cpp

The latest asan libdevice source triggers a compiler warning: llvm/libdevice/sanitizer/asan_rtl.cpp:342:3: warning: label at end of compound statement is a C++23 extension [-Wc++23-extensions]
This trivial pr removes it.

[DeviceSanitizer][NFC] Remove unnecessary warning for asan libdevice

---

sycl/include/sycl/handler.hpp

None of the E2E tests fail in "preview" mode so the functionality hasn't even been tested for awhile. Separate the code into a separate legacy helper to avoid touching in future refactorings for the up-to-date code.

[SYCL] Deprecate overloads accepting both `sycl::kernel` and lambda

---

llvm/lib/Transforms/Instrumentation/ThreadSanitizer.cpp

Also set default name to nameless globals since sanitizer cannot handle nameless globals.

[DevTSAN] Disable checks for vtable and atomics

---

unified-runtime/source/adapters/cuda/common.cpp
unified-runtime/source/adapters/cuda/usm.cpp

This fixes debug builds of UR with CUDA enabled; in that configuration
the `test-adapter-cuda` emits a call to `umf::umf2urResult` which
requires an implementaiton of `umf::getProviderNativeError`.

[UR] Implement `getProviderNativeError` in CUDA adptr. tests

---

unified-runtime/source/adapters/level_zero/command_buffer.cpp
unified-runtime/source/adapters/level_zero/context.cpp
unified-runtime/source/adapters/level_zero/device.cpp
unified-runtime/source/adapters/level_zero/enqueue_native.cpp
unified-runtime/source/adapters/level_zero/usm.hpp
unified-runtime/source/adapters/level_zero/v2/command_list_manager.cpp
unified-runtime/source/adapters/level_zero/v2/queue_create.cpp
unified-runtime/source/adapters/native_cpu/context.cpp
unified-runtime/test/adapters/hip/test_event.cpp
unified-runtime/test/conformance/testing/include/uur/known_failure.h

I missed several-many invalid uses of `std::ignore = unused_variable` in the level zero adapter in 82d8ed7b. This brings us up to date. I've additionally removed the unnecessary inclusion of `<tuple>` or `<utility>` where they're no longer needed.
Plus a bonus (void) of a nodiscard function in a hip test.

More std::ignore cleanups after 82d8ed7b1e

---

unified-runtime/source/common/ur_util.hpp
unified-runtime/source/loader/ur_lib.cpp
unified-runtime/test/conformance/device/urDeviceGetSelected.cpp

`native_cpu` is now accepted as a valid backend, and having a different
backend to the one matching the platform is now valid.
`native_cpu:*;level_zero:*` now works properly.

[UR] Fix backend parsing in `ONEAPI_DEVICE_SELECTOR`

---

.github/workflows/sycl-ur-perf-benchmarking.yml

This PR:
- Fixes missing default values for benchmarking CI manual trigger
- When splitting conditionals into multiple lines, if there is a newline at the end of the expression the github yml appends a newline if you use `|` or `>` (which, by definition, should have gotten rid of the newline): This PR folds the conditional expression back into 1 line

[CI] Fix defaults values in benchmark CI

---

sycl/test-e2e/Basic/sycl_2020_images/host_task_unsampled_image_write.cpp

Flaky fail, see https://github.com/intel/llvm/issues/18085

[SYCL][E2E] Disable host_task_unsampled_image_write.cpp on Gen12 Win

---

unified-runtime/test/conformance/device/urDeviceGetInfo.cpp

This test checked that two successive calls to
`urDeviceGetInfo(UR_DEVICE_INFO_GLOBAL_MEM_FREE)` return the same value.
This doesn't make sense as allocations (perhaps from other processes or
threads) can happen or be freed between the calls.
Instead we only check to see that a value has been written.

[UR] `SuccessGlobalMemoryFreeSize` test updated to check once

---

clang/tools/clang-linker-wrapper/ClangLinkerWrapper.cpp
sycl/test-e2e/NewOffloadDriver/multisource.cpp
sycl/test-e2e/NewOffloadDriver/split-per-source-main.cpp
sycl/test-e2e/NewOffloadDriver/sycl-external-with-optional-features.cpp

`-lto-emit-asm` was used previously for cuda kernels pipeline when `-flto` was also used to generate ptx assembly. But after removing lto for cuda kernels, we don't need this option, instead we should use `-S` clang option to generate the ptx assembly for cuda kernels.
Fixing issue [17812](https://github.com/intel/llvm/issues/17812)

[SYCL][clang-linker-wrapper] Replace -lto-emit-asm option with -S for cuda pipeline

---

sycl/test-e2e/Adapters/interop-level-zero-buffer.cpp
unified-runtime/source/adapters/level_zero/v2/memory.cpp

In case of creating a buffer from native host memory pointer, there was a missing initialization step. Host memory content was not being copied to the underlying buffer device memory.

[SYCL][UR][L0 v2] fix urMemBufferCreateWithNativeHandle for host memory

---

sycl/source/detail/device_info.hpp

Before the change: two allocations plus copy between them, after: one allocation plus zero-init of it so should be a strict improvement.

[SYCL][NFC] Avoid double allocation in `device_impl::get_device_info_string`

---

llvm/lib/Transforms/Instrumentation/ThreadSanitizer.cpp
llvm/test/Instrumentation/ThreadSanitizer/SPIRV/cleanup_private_shadow.ll

For dynamic allocas, sometime it will not dominate exit BB, we need to
skip them.

[DevTSAN] Don't insert cleanup instruction for dynamic allocas

---

clang/lib/Sema/SemaDeclAttr.cpp
clang/test/SemaSYCL/Inputs/vectorcall.hpp
clang/test/SemaSYCL/sycl-cconv-win.cpp

Cherry pick upstream commit https://github.com/llvm/llvm-project/commit/257b72758424f56103d38e3d016cfb6baa4da613
Closes: https://github.com/intel/llvm/issues/7738

[clang][Sema][SYCL] Fix MSVC STL usage on AMDGPU (#135979)

---

clang/include/clang/Driver/Options.td
clang/include/clang/Driver/Types.def
clang/lib/Driver/Driver.cpp
clang/lib/Driver/OffloadBundler.cpp
clang/lib/Driver/ToolChains/Clang.cpp
clang/lib/Driver/ToolChains/Gnu.cpp
clang/lib/Driver/ToolChains/Gnu.h
clang/lib/Driver/ToolChains/MSVC.cpp
clang/lib/Driver/ToolChains/MSVC.h
clang/lib/Driver/ToolChains/SYCL.cpp
clang/lib/Driver/ToolChains/SYCL.h
clang/test/Driver/sycl-unsupported.cpp

Following https://github.com/intel/llvm/commit/491915b2ac92caf76f611e804644abce30e148ae, remove the remaining items in the driver that support FPGA.
Small exceptions to this include any specific diagnostic behaviors that inform the user of option usage that is not supported due to the removal of FPGA.  Cleanup of those items can occur following a later major release.  The extension enabling options for the `sycl-post-link` tool specific for fpga also remain for now.

[Driver][NFC][FPGA] Remove remaining FPGA offload support in driver

---

sycl/test-e2e/OptionalKernelFeatures/is_compatible/is_compatible_amdgcn.cpp

It's fixed now.
Closes: https://github.com/intel/llvm/issues/17515

[SYCL][E2E] Enable is_compatible_amdgcn.cpp on Windows

---

sycl/source/detail/adapter.hpp

The Tracing Mutex doesn't seem to ever be used.

[SYCL] Eliminate unused mutex

---

sycl/test-e2e/bindless_images/examples/example_1_1D_read_write.cpp

Fixes #16923 'example_1_1D_read_write.cpp' has a sporadic failure on battlemage where it fails to validate the data. This is likely due to a missing 'q.wait_and_throw()' between copying the data from the device to host and verifying it. Adding the wait should fix this failure.

[SYCL][Bindless][E2E] Add missing wait in test between copy and verification

---

unified-runtime/test/conformance/device/urDeviceGetSelected.cpp

The `setenv` and `unsetenv` functions are not available on Windows, instead use `_putenv_s` wrapped in our own interfaces to fix the UR CTS build on Windows.

[UR] Fix Windows build of urDeviceGetSelected tests

---

llvm/include/llvm/SYCLPostLink/ComputeModuleRuntimeInfo.h
llvm/include/llvm/SYCLPostLink/ModuleSplitter.h
llvm/lib/SYCLPostLink/ComputeModuleRuntimeInfo.cpp
llvm/lib/SYCLPostLink/ModuleSplitter.cpp
llvm/tools/sycl-module-split/sycl-module-split.cpp
llvm/tools/sycl-post-link/sycl-post-link.cpp
sycl-jit/jit-compiler/lib/rtc/DeviceCompilation.cpp

This commit moves the "allow-device-image-dependencies" option out of the ModuleSplitter. This allows tools using the utility to control this option explicitly rather than the option bleeding into their option-space.

[SYCL] Move allow-device-image-dependencies out of ModuleSplitter

---

unified-runtime/source/adapters/level_zero/adapter.cpp

This should not be set for level zero entry points.

[UR] Don't define LO Adapter Logger Callbacks with __cdecl/default linkage

---

sycl/include/sycl/detail/builtins/builtins.hpp

Resolve warnings by changing comment format from // to /* */

Resolve warnings by changing comment format from // to /* */

---

sycl/source/detail/device_image_impl.hpp

Changes in #17380 introduced some Coverity detected issues. This commit fixes the following issues:
1. Removes noexcept from get_bin_image_ref as it can now potentially throw through std::variant interfaces.
2. Adheres to rule-of-three in ManagedDeviceGlobalsRegistry and ManagedDeviceBinaries.

[SYCL] Coverity scan fixes for #17380

---

sycl/source/detail/bindless_images.cpp

The case of `image_type::gather` would lead to an exception being thrown in `free_image_mem`/ `std::terminate` in `~image_mem_impl`. I missed this in https://github.com/intel/llvm/pull/17322.
This fixes that.
Note that this doesn't fully address https://github.com/intel/llvm/issues/16331 since the call to UR could still throw in theory. However, in order to avoid such a UR call in a destructor the implementation would have to be completely changed. As it is, if for some unusual circumstance the image free did fail in UR, I think there is at least an argument it be better that this does lead to `std::terminate`. So I'm leaving this for discussion.

[SYCL][BINDLESS] Fix mem_image_free for gather array

---

unified-runtime/source/adapters/cuda/common.cpp
unified-runtime/source/adapters/cuda/common.hpp
unified-runtime/source/adapters/cuda/device.cpp
unified-runtime/source/adapters/cuda/enqueue.cpp
unified-runtime/source/adapters/cuda/event.cpp
unified-runtime/source/adapters/cuda/image.cpp
unified-runtime/source/adapters/cuda/kernel.cpp
unified-runtime/source/adapters/cuda/memory.cpp
unified-runtime/source/adapters/cuda/queue.cpp
unified-runtime/source/adapters/cuda/sampler.cpp
unified-runtime/source/adapters/hip/common.cpp
unified-runtime/source/adapters/hip/common.hpp
unified-runtime/source/adapters/hip/device.cpp
unified-runtime/source/adapters/hip/device.hpp
unified-runtime/source/adapters/hip/event.cpp
unified-runtime/source/adapters/hip/image.cpp
unified-runtime/source/adapters/hip/kernel.cpp
unified-runtime/source/adapters/hip/memory.cpp
unified-runtime/source/adapters/hip/memory.hpp
unified-runtime/source/adapters/hip/program.cpp
unified-runtime/source/adapters/hip/queue.cpp
unified-runtime/source/adapters/hip/sampler.cpp

This patch cleans up most of the uses of `die()` in the CUDA and HIP adapters, it was replaced by:
* Using regular `assert()`
* Using `UR_CHECK_ERROR`
* Returning an appropriate error code
* Throw an appropriate error code
* Return an adapter specific error code with a message

[UR][CUDA][HIP] Cleanup use of assertions and die

---

sycl/doc/design/spirv-extensions/SPV_INTEL_function_pointers.asciidoc

This relaxes the return type of the **OpConstantFunctionPointerINTEL** to be any pointer (typed or untyped).

[Doc][SPIR-V] Allow function pointers to be used with SPV_KHR_untyped_pointers

---

sycl/source/detail/allowlist.cpp
sycl/source/detail/device_impl.cpp
sycl/source/detail/device_info.hpp

Previously, it used `DeviceImplPtr` (`std::shared_ptr<device_impl>`) but that isn't necessary and was preventing a future change to initialzie device aspects when creating `device_impl` object.
Also, searching for a correct `std::shared_ptr` via `getOrMakeDeviceImpl` (e.g., in `device_impl::get_info`) is just wasteful.

[NFCI][SYCL] Change `get_device_info_impl` to operate on `device_impl`

---

sycl/test-e2e/KernelCompiler/sycl_cache.cpp

cache eviction might occur earlier than test expects on multi-tile systems. Solution is to use a context of just one device.

[SYCL] fix for cache tests interacting with multi tile devices

---

.github/workflows/sycl-windows-run-tests.yml

We already do this on Linux but missed it here.

[CI] Don't pack/upload Windows E2E binaries if job cancelled

---

libdevice/sanitizer/msan_rtl.cpp
unified-runtime/source/loader/layers/sanitizer/msan/msan_interceptor.cpp
unified-runtime/source/loader/layers/sanitizer/sanitizer_common/sanitizer_options.cpp
unified-runtime/source/loader/layers/sanitizer/sanitizer_common/sanitizer_options.hpp

Unlike ASAN, MSAN needs "__devicelib_exit()" because if "j" is an uninitialized value in "data[j]", this will cause memory crash on CPU.
But sometimes "__devicelib_exit()" will hang on OpenMP (GPU), so I added a new option "recover" to control it.

[DeviceMSAN] Fix e2e tests crashed on OpenCL CPU

---

sycl/include/sycl/__spirv/spirv_vars.hpp

This is a simpler logic, the `#else` branch already assumes built-in SPIR-V variables anyway, so any future target would not want to take it. Also this removes one point that needs to be modified if new targets were to be added.
NOTE:
I could have flipped the logic to make the `#if` positive, but I didn't that to make this a smaller diff. Let me know if that would be preferable.

[SYCL] Use defined(__SPIRV__) instead of !defined(all other targets) (NFC)

---

devops/scripts/benchmarks/benches/compute.py

Enable computeBench to run on sycl with cuda backend via the benchmarking scripts.

[SYCL][Benchmark] Enable computeBench for cuda

---

libclc/libspirv/lib/amdgcn-amdhsa/misc/sub_group_shuffle.cl

This was mistakenly renamed in commit 316418d, which modified the AMDGCN sub-group shuffle builtins.

[libspirv][AMD] Fix misnamed sub-group shuffle builtin

---

unified-runtime/source/loader/layers/sanitizer/asan/asan_statistics.cpp

Old: overhead = (shadow + redzone) / (user + shadow + redzone)
New: overhead = (shadow + redzone) / user

[DeviceASAN] Correct overhead formula

---

unified-runtime/source/adapters/opencl/command_buffer.cpp

The merged PR https://github.com/intel/llvm/pull/17658 added the requirement for OpenCL cl_khr_command_buffer implementations to support the simultaneous use capability in order to support UR command-buffers.
There was an oversight in this PR where the simultaneous use property wasn't set on command-buffer creation in the OpenCL adapter. This is rectified in this patch.

[UR][OpenCL][Graph] Set simultaneous-use property

---

sycl/source/detail/program_manager/program_manager.cpp
sycl/source/detail/program_manager/program_manager.hpp

This PR guards accesses to `m_DeviceImage` and `m_VFSet2BinImage` caches/maps in the Program Manager using `m_KernelIDsMutex` in situations where multiple threads may be accessing the maps at the same time.
I am opting to use `m_KernelIDsMutex` here as both maps are commonly accessed while holding said mutex: In fact, a lot of maps/caches in the program manager use `m_KernelIDsMutex`  (This is not the most optimal solution, but that is out of the scope of this PR, see #18165)
This PR addresses Coverity hits that needs to have fixes submitted before the code cutoff.

[SYCL][Coverity] Fix MISSING_LOCK coverity hits in the program manager

---

unified-runtime/CMakeLists.txt
unified-runtime/test/adapters/cuda/CMakeLists.txt
unified-runtime/test/adapters/hip/CMakeLists.txt
unified-runtime/test/adapters/level_zero/CMakeLists.txt
unified-runtime/test/adapters/level_zero/v2/CMakeLists.txt
unified-runtime/test/conformance/CMakeLists.txt
unified-runtime/test/conformance/device_code/CMakeLists.txt

If we are not a standalone build (that is, we are built as part of
intel/llvm) and `UR_DPCXX` is not specified as part of the cmake
options, we use the `clang` built by `intel/llvm` to generate device
binaries.
Likewise, if no `UR_DEVICE_CODE_EXTRACTOR` is specified and we are
not standalone, the `clang-offload-extractor` from intel/llvm is used.
This change should not affect CI, but does mean that the UR testing
targets can be built in an intel/llvm local build.

[UR] For non-standalone builds, use built DPCXX/Extractor

---

unified-runtime/source/loader/ur_adapter_registry.hpp
unified-runtime/source/loader/ur_lib.cpp
unified-runtime/test/conformance/device/urDeviceGetSelected.cpp
unified-runtime/test/loader/adapter_registry/prefilter.cpp

The prefilter.cpp test was failing, this fixes it as follows:
* Strings that can't be parsed are now treated as `*:*` rather than
`!*:*`.
* Backend names are validated; any invalid ones cause the entire string
to be rejected.
* In ur_lib.cpp, the parser is updated to handle failing to parse the
string (doesn't affect the test, but a nice to have).
* Some selector strings in the test itself were invalid and updated.
This was done according to the specification of ONEAPI_DEVICE_SELECTOR
located at https://github.com/intel/llvm/blob/sycl/sycl/doc/EnvironmentVariables.md#oneapi_device_selector .

[UR] Make ONEAPI_DEVICE_SELECTOR prefilter test pass

---

sycl/test-e2e/syclcompat/memory/memory_management_test1_usmnone.cpp

See https://github.com/intel/llvm/issues/17966

[SYCL][E2E] Disable memory_management_test1_usmnone.cpp on Gen12 Linux

---

sycl/source/detail/platform_impl.cpp
sycl/source/detail/platform_impl.hpp

This is a pre-requisite to eliminate `PlatformImplPtr` and use `platform_impl` by raw pointer/reference throught the SYCL RT library.

[NFCI][SYCL] Make sure `platform_impl` could only be owned by `GlobalHandler`

---

sycl/source/detail/bindless_images.cpp
sycl/source/detail/context_impl.hpp
sycl/source/detail/memory_pool_impl.cpp
sycl/source/detail/usm/usm_impl.cpp
sycl/source/virtual_mem.cpp

To reduce the amount of boilerplate code necessary without it. As a nice side effect avoids creation of temporary `std::shared_ptr` where using references would have been enough.

[NFC][SYCL] Introduce `get_ur_handles` helper

---

sycl/include/sycl/backend.hpp
sycl/source/backend.cpp
sycl/source/detail/device_impl.cpp
sycl/source/detail/device_impl.hpp

This effectively reverts part of the changes made in https://github.com/intel/llvm/pull/13483 in favor of a simpler solution. The tests added there are unchanged and are verifying this PR.
This made one `device_impl` ctor overload unused with another already dead prior to this. Removing them both here and making some other simplifications following from that removal.

[SYCL] Use `platform_impl::getOrMakeDeviceImpl` in `make_device`

---

sycl/include/sycl/queue.hpp
sycl/source/detail/handler_impl.hpp
sycl/source/detail/queue_impl.hpp
sycl/source/handler.cpp
sycl/source/queue.cpp
sycl/unittests/SYCL2020/KernelBundle.cpp

Reverts #18045 and #17967
I'll create a follow-up PR to:
1. Remove Secondary queue from fallback (which is legal)
2. Have separate code paths, one when user specifies secondary queue and one without it.

[SYCL] Reintroduce secondary queue by reverting #18045 and #17967

---

devops/scripts/benchmarks/benches/compute.py
devops/scripts/benchmarks/history.py

This patch updates to the latest revision of compute-benchmarks and updates the scripts to match.
There two important changes:
- the addition of syclpreview SubmitKernel benchmarks
- introduction of "eventless" variants of SubmitKernel for L0 and UR. These will now be grouped together for easy comparison.

[CI][Benchmarks] update to latest compute-benchmarks, add syclpreview

---

unified-runtime/source/adapters/opencl/kernel.cpp
unified-runtime/source/adapters/opencl/kernel.hpp

Saves the function pointer for clSetKernelArgMemPointerINTEL when the kernel is created.  This eliminates the need to query the context for the kernel and look up the function pointer in the extension function pointer cache each time a pointer is set as a kernel argument.
Additionally:
* Adds a few missing error conditions.
* Adds a few missing kernel info queries, for devices that support them.

[UR][OpenCL] Save the function pointer for clSetKernelArgMemPointerINTEL per kernel

---

unified-runtime/test/conformance/exp_command_buffer/commands.cpp
unified-runtime/test/conformance/exp_command_buffer/fill.cpp

There are currently limitations on what commands can be added to a SYCL-Graph that we document in the [design doc](https://github.com/intel/llvm/blob/sycl/sycl/doc/design/CommandGraph.md#opencl) and mark as unsupported in Graph E2E tests.
However, we never marked the equivalent UR command-buffer commands as unsupported in the CTS, so they will currently fail when testing against an OpenCL backend with support for the extension. Address this by marking CTS tests which use these commands as unsupported.
Note that this will conflict with https://github.com/intel/llvm/pull/18177 in that some CTS tests can be re-enabled, but I can resolve that based on whatever merges first.

[UR][Graph] command-buffer unsupported OpenCL CTS tests

---

sycl/test-e2e/MemorySanitizer/local/parallel_for_work_group.cpp

It's XPASSING, see [here](https://github.com/intel/llvm/actions/runs/14632659184).

[SYCL][E2E] Enable XPASSing parallel_for_work_group.cpp on OCL CPU

---

unified-runtime/source/adapters/level_zero/v2/queue_immediate_in_order.cpp

The logger might throw leading to an abort.
The error message will be printed anyway if the PrintTrace is set.

[UR][L0 v2] Do not use logger::error in queue dtor

---

sycl/source/detail/scheduler/graph_processor.cpp
sycl/unittests/scheduler/FailedCommands.cpp
sycl/unittests/scheduler/SchedulerTestUtils.hpp

reverting "[SYCL] reset enqueue status so that buffer can be used after …failure is addressed (#17871)"
This PR accidentally introduced a very subtle flaky failure/seg fault. I quickly tried the immediate and obvious fixes but no luck. Given that the original problem is lower priority, I'm reverting the commit before we cement in the instability.
Addresses issue: https://github.com/intel/llvm/issues/17965
This reverts commit a827836a167c3e075db0916421c176cbe5c176ce.

[SYCL] Revert  (#17871), enqueue status reset.  

---

unified-runtime/source/adapters/level_zero/v2/command_list_manager.hpp

getWaitListView assumed that calling data() on ane empty vector will return nullptr - this is not guaranteed.
This lead to assert in operator bool() trigerring.
Implement a constructor for wait_list_view that will set the handles to NULL if num is 0.

[SYCL][UR][L0 v2] fix wait_list_view contruction

---

llvm/lib/Transforms/Instrumentation/MemorySanitizer.cpp
llvm/test/Instrumentation/MemorySanitizer/SPIRV/instrument_shuffle_vector.ll

For Spirv target, we need to make sure poison mask always point to a
clean shadow to avoid pollution of launch info clean shadow.

[DevMSAN] Always make sure poison shuffle mask point to clean shadow

---

libclc/libspirv/lib/generic/geometric/dot.cl
libclc/libspirv/lib/generic/relational/all.cl
libclc/libspirv/lib/generic/relational/any.cl

They only accept vector input per SPIR-V spec.

[libspirv] Remove scalar Dot, All and Any built-ins

---

unified-runtime/source/loader/layers/sanitizer/asan/asan_ddi.cpp
unified-runtime/source/loader/layers/sanitizer/msan/msan_ddi.cpp

Device ASAN and Device MSAN have not yet supported that API, this patch addresses that problem. Some sycl e2e tests failed with device sanitizers enabled because of the lack of this API support.

[DeviceSanitizer] Add support for urEnqueueCooperativeKernelLaunchExp for ASAN and MSAN

---

clang/lib/Frontend/InitPreprocessor.cpp

MSVC's inline definitions of stdio functions such as printf() are only meant for host code; device code cannot call them. Device code can, however, call ext::oneapi::experimental::printf() which depending on the target is implemented as a call to the global printf(). The availability of a definition of the global host printf() makes it more difficult to handle in device code, so hide it.

[SYCL] Hide inline definitions of stdio functions

---

sycl/source/detail/graph_impl.cpp
sycl/source/detail/queue_impl.cpp

This fixes the build with `SYCL_ENABLE_XPTI_TRACING=OFF`.

[SYCL] Fix missing xpti ifdefs

---

devops/scripts/update_drivers.py

The public IGC CI is a bloodbath as usual, and now the LLVM 14 builds are failing while 15 is passing, so use those.

[CI] Use the LLVM 15 dev-igc artifact

---

sycl/test-e2e/bindless_images/dx12_interop/read_write_unsampled_semaphore.cpp
sycl/test-e2e/lit.cfg.py

These tests were failing on Windows when using a msvc-like compiler such as `clang-cl`, so this patch makes sure we're using the correct style of options depending on the compiler.

[SYCL] Fix bindless images tests with windows cl

---

sycl/source/detail/event_impl.cpp
sycl/source/detail/event_impl.hpp
sycl/source/detail/queue_impl.cpp
sycl/source/handler.cpp

The code was added in 64546e7, but locks are superfluous.

[SYCL] Do not lock event_impl when it not shared with other threads

---

devops/containers/ubuntu2204_build.Dockerfile

[CI] Upgrade ROCm to 6.3 on UB22.04 per requirement from f1ac2afe213f

---

sycl/gdb/libsycl.so-gdb.py
sycl/include/sycl/detail/impl_utils.hpp
sycl/source/backend.cpp
sycl/source/backend/level_zero.cpp
sycl/source/detail/allowlist.cpp
sycl/source/detail/buffer_impl.cpp
sycl/source/detail/context_impl.cpp
sycl/source/detail/context_impl.hpp
sycl/source/detail/device_impl.cpp
sycl/source/detail/device_impl.hpp
sycl/source/detail/device_info.hpp
sycl/source/detail/global_handler.cpp
sycl/source/detail/global_handler.hpp
sycl/source/detail/kernel_impl.cpp
sycl/source/detail/platform_impl.cpp
sycl/source/detail/platform_impl.hpp
sycl/source/detail/program_manager/program_manager.cpp
sycl/source/detail/usm/usm_impl.cpp
sycl/source/device.cpp
sycl/source/platform.cpp
sycl/test/gdb/printers.cpp
sycl/unittests/program_manager/SubDevices.cpp
sycl/unittests/queue/DeviceCheck.cpp

`GlobalHandler::MPlatformCache` keeps (shared) ownership of `platform_impl` objects, so none of them could be destroyed until SYCL RT library shutdown/unload process. As such, using raw pointers/reference to `platform_impl` throughout the SYCL RT is totally fine and would avoid extra costs of `std::shared_ptr`. However, our unittests don't work the same way and lifetimes are actually managed by all the data member `std::shared_ptr`s (e.g., see `CurrentDevice.cpp` as the most obvious case), so simply switching all `PlatformImplPtr` to raw pointer/reference doesn't work right now. I think it will be possible with an ABI break if we'd remove all the shared pointers but the one in the `GlobalHandler`.
What I'm doing here instead is the following:
* Try to keep lifetime management the same, …

[SYCL] Less `shared_ptr` for `platform_impl`

---

sycl/tools/syclbin-dump/CMakeLists.txt

This commit avoids a warning produced by
https://github.com/intel/llvm/pull/16873 when building syclbin-dump using compilers other than gcc and clang, where the -fno-rtti option isn't available.

[SYCL] Fix syclbin-dump build on non clang/gcc compilers

---

sycl/tools/syclbin-dump/CMakeLists.txt

This commit changes the use of -fno-rtti to, instead of being compiler ID dependent, be dependent on whether the compiler recognizes the flag.

[SYCL] Check for -fno-rtti support when compiling syclbin-dump

---

sycl/source/detail/graph_impl.cpp
sycl/source/detail/graph_impl.hpp

We were creating queue_impl each time we were enqueueing a node or updating it. It makes sense to cache queue_impl as a private member of `exec_graph_impl`.

[SYCL] [Graph] Reduce number of queue_impl creation

---

sycl/test-e2e/SubGroup/attributes_cuda_hip.cpp
sycl/test-e2e/syclcompat/launch/launch_policy.cpp

These tests are using `redq_sub_group_size(32)` so they should require the feature.
This is visible on certain AMD GPUs that use a 64 thread sub-group size instead of 32 threads.

[SYCL][E2E] Add missing sg-32 requires

---

sycl/test-e2e/Adapters/level_zero/eager_init.cpp
sycl/test-e2e/Reduction/reduction_ctor.cpp
sycl/test-e2e/USM/hmemll.cpp

Fixes #18067 and #17582 
These were fixed with the Windows driver being updated.

[SYCL][E2E] Re-enable tests hanging on Windows BMG

---

sycl/test-e2e/lit.cfg.py
sycl/test/lit.cfg.py

SYCL header files contain some uses of deprecated declarations. When SYCL headers are found via a user header search path specified by the `CPATH` environment variable or the `-I` option, these uses can cause warnings to be produced that then cause tests that use `-Werror` to fail. This change updates lit configuration files to use `C_INCLUDE_PATH` and `CPLUS_INCLUDE_PATH` instead of `CPATH` and to use `-isystem` instead of `-I` to nominate header search paths for SYCL header files.

[SYCL][E2E] Use system header search paths for SYCL headers in SYCL lit tests.

---

sycl/source/detail/helpers.cpp
sycl/source/detail/memory_manager.cpp
sycl/source/detail/program_manager/program_manager.cpp
sycl/source/detail/program_manager/program_manager.hpp
sycl/source/kernel_bundle.cpp

Just a simple code refactoring.

[SYCL] use raw pointer to device_impl in ProgramManager (where possible)

---

sycl/test-e2e/Graph/RecordReplay/ext_oneapi_enqueue_functions.cpp
sycl/test-e2e/Graph/RecordReplay/usm_copy_in_order.cpp

This patch improves coverage for recording a `memcpy` by modifying an existing test.

[SYCL][Graph] Improve in-order test coverage and output

---

sycl/tools/sycl-trace/CMakeLists.txt

sycl/detail/spinlock.hpp is included in ze_trace_collector.cpp. ze_trace_collector target should either depend on sycl-headers target or include sycl_inc_dir.

[NFC][SYCL] fix flaky build fail in ze_trace_collector target

---

sycl/include/sycl/vector.hpp
sycl/test/check_device_code/vector/convert_bfloat_preview.cpp

This is limited to the preview mode where the regression happened while re-implementing vec/swizzle.

[SYCL] Don't value-initialize `sycl::vec` unnecessarily

---

sycl/source/detail/device_impl.cpp
sycl/source/detail/device_impl.hpp
sycl/source/detail/platform_impl.cpp
sycl/unittests/program_manager/SubDevices.cpp
sycl/unittests/queue/DeviceCheck.cpp

Once that is guaranteed, it can enable further refactoring in subsequent PRs.

[SYCL][NFCI] Ensure `device_impl` is only created via `platform_impl::getOrMakeDeviceImpl`

---

unified-runtime/source/adapters/opencl/usm.cpp
unified-runtime/source/adapters/opencl/usm.hpp

Fixes https://github.com/oneapi-src/unified-runtime/issues/1837
The UR OpenCL adapter expects patterns of 2 for USM allocs, and fallsback to using clHostMemAllocINTEL_fn for non patterns of 2. Some devices/platforms don't support this extension so we can just use a regular malloc instead.

[UR][CL] Use regular malloc where clHostMemAllocINTEL_fn is not supported for USM allocs.

---

.github/workflows/sycl-windows-build.yml
.github/workflows/sycl-windows-run-tests.yml

Similar what we do for Linux [here](https://github.com/intel/llvm/blob/sycl/devops/scripts/install_drivers.sh#L53).

[CI] Use GITHUB_TOKEN to download hang script

---

llvm/lib/SYCLLowerIR/CMakeLists.txt
llvm/tools/sycl-post-link/CMakeLists.txt
sycl-jit/jit-compiler/CMakeLists.txt

The target isn't defined when using `find_package` to use the preinstalled version, and we don't need it even when using `FetchContent`.

[SYCL] Remove usage of LLVMGenXIntrinsics CMake target

---

sycl/source/detail/global_handler.cpp
sycl/source/detail/global_handler.hpp
sycl/source/detail/platform_impl.cpp
sycl/source/detail/platform_impl.hpp
sycl/unittests/context_device/DeviceRefCounter.cpp
sycl/unittests/helpers/UrMock.hpp

After that devices are never destroyed until the SYCL RT library shutdown. In practice, that means that before the change a simple
```
int main() { sycl::device d; }
```
went into `platform` ctor, then queried all the platform's devices to check that it has some, returned from ctor and those `sycl::device`s created on stack were already destroyed. After that, when creating user's `sycl::device d` we were re-creating device hierarchy for the platform at SYCL level again (including some calls to `urDeviceGetInfo` during `device_impl` creation).
After the changes, devices created when veryfing that platform isn't empty are preserved inside the `platform_impl` object and this existing SYCL devices hierarchy is used when creating user's device object.
A note on the implementation: …

[SYCL] Keep `platform_impl`'s `device_impl`s alive until shutdown

---

clang/lib/Driver/Driver.cpp
clang/test/Driver/sycl-obj-remove.cpp

Typical behaviors when the compilation fails is to have the resulting output object to be removed. Due to the fact that there are multiple compilations that occur during an offload compilation, the actual final output object may not be directly associated with the compile causing it to not be removed.
Update the cleanup file list to remove the output result file regardless of the associated job action when we are performing offload.

[Driver][SYCL] Remove object upon failure

---

sycl/include/sycl/accessor.hpp

Some customers complained that having `fprintf` used in our library makes their security policy trigger an error.

[NFC][SYCL] Don't use `fprintf` as deemed "unsafe"

---

unified-runtime/test/conformance/exp_command_buffer/CMakeLists.txt
unified-runtime/test/conformance/exp_command_buffer/regression/usm_copy.cpp

Create a UR CTS test based on the E2E test [Graph/RecordReplay/usm_copy_in_order.cpp](https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/Graph/RecordReplay/usm_copy_in_order.cpp) to help debug https://github.com/intel/llvm/pull/18169
Disabled for Level-Zero v1 adapter (passes on v2) as [test fails with](https://github.com/intel/llvm/actions/runs/14733668954/job/41355110585?pr=18241):
```
[ RUN      ] urCommandBufferUSMCopyInOrderTest.Success/Intel_R__oneAPI_Unified_Runtime_over_Level_Zero__Intel_R__Data_Center_GPU_Max_1100_ID0ID____________________
/home/test-user/actions-runner/sycl-ur-01/_work/llvm/llvm/unified-runtime/test/conformance/exp_command_buffer/regression/usm_copy.cpp:140: Failure
Expected equality of these values:
result3
Which is: 3656
output[i]
Which is: 170
```
This …

[UR][Graph] in-order USM Memcpy regression CTS test

---

devops/scripts/benchmarks/benches/compute.py

Add multithreaded benchmarks with copy offload
disabled to track any performance regression
for copy offload feature.

[SYCL][Bench] extend compute-benchmark suite

---

sycl/CMakeLists.txt
sycl/cmake/modules/FetchUnifiedRuntime.cmake
sycl/unittests/CMakeLists.txt
unified-runtime/CMakeLists.txt

There were two issues:
1) Setting `UR_ENABLE_TRACING` on the command line didn't work because the SYCL code calling the FetchUR CMake files didn't use `CACHE`, also fixed two other vars with the same problem.
2) XPTI SYCL tests were built even if XPTI wasn't built, causing a build failure.
Also add two errors so the problem isn't discovered in a build failure.

[SYCL] Fix build with XPTI disabled

---

sycl/test-e2e/Adapters/level_zero/interop-get-native-mem.cpp
sycl/test-e2e/Graph/Explicit/interop-level-zero-get-native-mem.cpp
sycl/test-e2e/Graph/RecordReplay/interop-level-zero-get-native-mem.cpp

Been failing in postcommit for days, see [here](https://github.com/intel/llvm/issues/18273).

[SYCL][E2E] XFAIL failing native memory tests

---

sycl/test-e2e/ESIMD/group_barrier.cpp

[SYCL][ESIMD][E2E] Query max workgroups in group barrier test

---

llvm/lib/SYCLLowerIR/CMakeLists.txt

Shared library build is currently failing due to my change [here](https://github.com/intel/llvm/pull/18249).
The problem is the public build target dependencies of SYCLLowerIR didn't add the vc-intrinsics headers/binaries so the include/link fails.
This wasn't happening before because users of SYCLLowerIR manually added the missing dependencies in their targets.
Manually verified this on static/shared library build on both preinstalled vc-intrinsics and system vc-intrinsics.

[SYCL][SYCLLowerIR] Fix shared library build

---

sycl/source/detail/allowlist.cpp

I'll plan to further simplify/unify/eliminate that particular helper. This change would make subsequent PR(s) easier to review.

[NFC][SYCL] Don't use `get_platform_info` outside `platform_impl`

---

sycl/test-e2e/KernelCompiler/sycl_join.cpp

This commit removes the explicit kernel launch in sycl_join, as the use of the set_args assumes the layout of arguments in the kernel, which is not guaranteed to be as expected.

[SYCL][E2E] Remove UB kernel launch in sycl_join

---

sycl/doc/extensions/experimental/sycl_ext_oneapi_kernel_compiler.asciidoc
sycl/include/sycl/kernel_bundle.hpp
sycl/test-e2e/KernelCompiler/sycl_join.cpp

This commit adds a constraint to sycl::join specifying that it is not available when the kernel bundle state is source-based.

[SYCL][Docs] Disallow sycl::join with source-based kernel_bundle

---

unified-runtime/source/adapters/level_zero/image_common.cpp

An iterator was being used after being erased, which is UB.

[UR][L0] Fix iterator invalidation issue

---

unified-runtime/scripts/generate_docs.py

Contrary to the comment in the code macros do have API documentation, so they should be linked to. Currently there seems to be no macros in the rst sources, but I noticed this while working on an extension that would add one.

[UR][Docs] Transform reference to macros in specs to links

---

unified-runtime/test/conformance/enqueue/urEnqueueMemBufferWriteRect.cpp
unified-runtime/test/conformance/exp_command_buffer/CMakeLists.txt
unified-runtime/test/conformance/exp_command_buffer/copy.cpp
unified-runtime/test/conformance/exp_command_buffer/fill.cpp
unified-runtime/test/conformance/exp_command_buffer/fixtures.h
unified-runtime/test/conformance/exp_command_buffer/read.cpp
unified-runtime/test/conformance/exp_command_buffer/rect_read.cpp
unified-runtime/test/conformance/exp_command_buffer/rect_write.cpp
unified-runtime/test/conformance/exp_command_buffer/update/invalid_update.cpp
unified-runtime/test/conformance/exp_command_buffer/write.cpp

Adds some tests that check most basic command buffer functionalities

[SYCL] [UR] Add command buffer operations tests

---

libclc/utils/prepare-builtins.cpp

Upstream recently bumped the default AMD code object version to 6, which is only supported by ROCm 6.3 and above.
There is a flag `-mcode-object-version=` to make the compiler use an older version. But before this patch it broke at the libclc linking stage since libclc had the default value in a module flag.
So this patch makes the prepare builtin tool remove this module flag from the libclc bitcode libraries.

[LIBCLC] Drop AMD code object version from libclc

---

unified-runtime/source/adapters/cuda/common.hpp
unified-runtime/source/adapters/hip/common.hpp

`cuPrint` and `hipPrint` were deleted but the declaration wasn't, these aren't used anywhere, they were replaced by the UR logger.

[NFC][UR] Remove unused print functions

---

unified-runtime/cmake/FetchLevelZero.cmake
unified-runtime/source/adapters/level_zero/common.hpp

I'm trying to make dpcpp more friendly to packaging by Linux distros, and we should be using system-installed dependencies by default.
Find the system-installed compute-runtime headers and use them if they exist instead of downloading the upstream repo.
Also fix an include that doesn't work with system headers.

[UR] Use pre-installed compute-runtime L0 headers if found

---

sycl/include/sycl/detail/id_queries_fit_in_int.hpp
sycl/test-e2e/Basic/range_offset_fit_in_int.cpp

checkValueRange is used to determine if an nd_range is compatible with -fsycl-queries-fit-in-int, and is run as part of every kernel launch.
The previous implementation checked the size of each component of the global range, local range, offset, and global range + offset, and also checked the linearized version of each of these values.
The new implementation simplifies these checks, based on the following logic:
- The linear global range size must be >= every component of the global range.
If the linear global range fits in int, we don't need to check anything else.
- Each value in the global range must be >= the value in the local range.
If the global range fits in int, we don't need to check the local range.
- There is no need to check offset-related values if the offset is zero.
The …

[SYCL] Optimize checkValueRange

---

sycl/source/detail/platform_impl.cpp
sycl/source/detail/platform_impl.hpp

So that we wouldn't need explicit instantiations. Instead, `platform.cpp` would implicitly instantiate all of them when processing explicit ones for `platform::get_info`.

[NFC][SYCL] Move `platform_impl::get_info` impl to the header

---

sycl/include/sycl/known_identity.hpp
sycl/test/basic_tests/reduction/infinite_identity.cpp

Some time ago we fixed a bug in `sycl::known_identity` where it was incorrectly using `std::numeric_limits<T>::infinity()` even in cases where `::infinity()` should not have been available. At the time, the fix was to simply test for `__FAST_MATH__`.  
That worked, but was not ideal. Now we are tightening this to use the `__FINITE_MATH_ONLY__` macro which is more accurate.  
see https://github.com/intel/llvm/issues/13813
`__FINITE_MATH_ONLY__`  will be set when both the `-fno-honor-infinities` and `-fno-honor-nans` flags are used. It was felt by the FE team that there is no reasonable case where one of the flags would be used without the other and therefore `__FINITE_MATH_ONLY__` is sufficient for this problem ( and superior to the `__FAST_MATH__` macro we were using before).

[SYCL] tighten known_identity to finite_math macro

---

.github/workflows/sycl-nightly.yml
.github/workflows/sycl-windows-build.yml

After I merge this I'll remove the `build` label from the slow machines and remove all runners using the `build-e2e` label.

[CI] Use the build label for all Windows builds

---

sycl/test-e2e/Adapters/level_zero/interop-get-native-mem.cpp
sycl/test-e2e/Graph/Explicit/interop-level-zero-get-native-mem.cpp
sycl/test-e2e/Graph/RecordReplay/interop-level-zero-get-native-mem.cpp
sycl/test/e2e_test_requirements/no-unsupported-without-info.cpp

[XPASSing](https://github.com/intel/llvm/actions/runs/14787981688) in the nightly for some reason but failing in postcommit, so make them `UNSUPPORTED`.

[SYCL][E2E] Mark failing interop native mem tests as UNSUPPORTED

---

.github/workflows/sycl-linux-precommit.yml

If it fails, lock the runner and let driver team debug.

[CI] Remove `-j 50` limit from PVC E2E tasks

---

sycl/source/CMakeLists.txt

This commit adds the -Wl,--gc-sections flags to the linking of the SYCL libraries when available. This enables link-time section garbage collection, removing dead code in the binary, potentially reducing the size of it.

[SYCL][CMake] Garbage-collect in libsycl linking

---

unified-runtime/scripts/core/EXP-COMMAND-BUFFER.rst
unified-runtime/source/adapters/opencl/command_buffer.cpp
unified-runtime/source/adapters/opencl/command_buffer.hpp
unified-runtime/test/conformance/exp_command_buffer/CMakeLists.txt
unified-runtime/test/conformance/exp_command_buffer/enqueue.cpp
unified-runtime/test/conformance/exp_command_buffer/update/enqueue_update.cpp

Update the UR command-buffer enqueue semantics such that command-buffer submissions are ordered with a dependency on previous submissions of the same command-buffer.
That is the same semantic as we currently specify for executable graph objects in the SYCL-Graph extension. Allowing for a more efficient SYCL-RT implementation on top of UR where less UR events need to be created (future work).
OpenCL is the only adapter that needs updated to provide these semantics, where we now track the `cl_event` returned from the most recent submission of a command-buffer, so that it can be used as a dependency of any future command-buffer submissions.

[UR][Graph] Serialize submissions of the same command-buffer

---

unified-runtime/source/adapters/level_zero/queue.cpp

In a scenario where the AsyncPool freelist contains an entry tied to a free event that hasn't completed yet, performing freelist cleanup before queue sync can result in freeing memory that's actively in use.

[UR][L0] Move async pool cleanup after queue sync

---

devops/scripts/benchmarks/history.py

Fix the following warning during benchmarks run:
```
RuntimeWarning: 'NoneType' object value of non-optional type compute_runtime detected when decoding BenchmarkRun.
```
https://github.com/intel/llvm/actions/runs/14850915457/job/41694529398#step:19:810

[CI][Perf] Fix BenchmarkRun 'NoneType' warning

---

sycl/test-e2e/Adapters/level_zero/events_caching.cpp
sycl/test-e2e/Adapters/level_zero/events_caching_leak.cpp
sycl/test-e2e/KernelCompiler/sycl.cpp
sycl/test-e2e/Regression/static-buffer-dtor.cpp

Fixes #17255
Fixes #17916
These are no longer slow after updating the drivers

[SYCL][E2E] Re-enable Windows BMG tests that are no longer slow/hanging

---

.github/workflows/sycl-linux-build.yml
.github/workflows/sycl-post-commit.yml
.github/workflows/sycl-windows-build.yml
.github/workflows/sycl-windows-run-tests.yml
devops/actions/run-tests/e2e/action.yml
devops/actions/run-tests/windows/e2e/action.yml

We have `cxx` and `cxx_compiler`, very similar names so it can be confusing. `cxx` is used to build the project, while `cxx_compiler` is the compiler produced so renaming the latter to `sycl_compiler`. Additionally aligning the Windows with the Linux build job by renaming `compiler` to `cxx`.
Addresses comments from #18322

[CI] Rename compiler variables

---

sycl/test-e2e/USM/fill_any_size.cpp

Closes https://github.com/oneapi-src/unified-runtime/issues/2440

[SYCL][E2E] Re-enable test-e2e/USM/fill_any_size.cpp for OpenCL as it now passes

---

unified-runtime/source/adapters/hip/common.cpp

Rearrange switch fallthrough to avoid unassigned error string invoking UB when printed
Fixes https://github.com/intel/llvm/issues/18336

[UR][HIP] Fix comgr error handling

---

sycl/source/detail/adapter.hpp
sycl/source/interop_handle.cpp
unified-runtime/source/adapters/cuda/adapter.cpp
unified-runtime/source/adapters/cuda/common.cpp
unified-runtime/source/adapters/cuda/common.hpp
unified-runtime/source/adapters/cuda/enqueue.cpp
unified-runtime/source/adapters/hip/common.cpp
unified-runtime/source/adapters/hip/common.hpp
unified-runtime/source/adapters/level_zero/adapter.cpp
unified-runtime/source/adapters/level_zero/common.cpp
unified-runtime/source/adapters/level_zero/common.hpp
unified-runtime/source/adapters/native_cpu/common.cpp
unified-runtime/source/adapters/native_cpu/common.hpp
unified-runtime/source/adapters/opencl/common.cpp
unified-runtime/source/adapters/opencl/common.hpp
unified-runtime/source/adapters/opencl/kernel.cpp

Fixes https://github.com/intel/llvm/issues/18260
Also updates `checkUrResult` in SYCL RT to remove warning level check as `urAdapterGetLastError` is now only used for errors.

[SYCL][UR] Update setErrorMessage to use int32_t instead of ur_result_t for the urAdapterGetLastError entry point

---

unified-runtime/source/adapters/level_zero/v2/memory.cpp
unified-runtime/source/adapters/level_zero/v2/memory.hpp

ur_integrated_buffer_handle_t was missing logic for writing back memory to the hostPtr suplied during buffer construction.
getDevicePtr and mapHostPtr did not take into account offset.

[SYCL][UR][L0 v2] fix mem buffer for integrated graphics

---

unified-runtime/source/adapters/level_zero/event.cpp
unified-runtime/test/conformance/enqueue/urEnqueueEventsWait.cpp

The path for non-immediate command lists was incorrect. queue->synchronize() was called without closing and executing command lists leading to deadlock.
Fix this by replacing synchronize() call with executeCommandList()

[SYCL][UR][L0] Fix urEnqueueEventsWait

---

sycl/test-e2e/FreeFunctionKernels/test-plan.md

Updates based on feedback to the previous PR which has already been merged with test plan for free function kernels extension.
Changes done:
- moved check related to aliases into unit-tests category.
- added two new checks into e2e category related to treating free function kernel as device or host function.
- updated `Interaction with additional kernel properties` part.
- updated description for `get_kernel_id` what mean valid kernel identifier in context of unit-testing.
- most of changes were related to refactoring text into consistent column limit (which is 80) for markdown doc.
Previous PR: https://github.com/intel/llvm/pull/17886
Docs: https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/proposed/sycl_ext_oneapi_free_function_kernels.asciidoc

[SYCL][Doc] Update to the test plan for free function kernels extension

---

sycl/test-e2e/bindless_images/lit.local.cfg
sycl/test-e2e/lit.cfg.py

The addition of "vulkan" to `config.available_features` was moved to `bindless_images/lit.local.cfg` in #18220. This broke the `// REQUIRES: vulkan` directive, and tests were reporting as being unsupported despite vulkan being available on the system.
This patch moves the check and addition of vulkan to the available features back to `test-e2e/lit.cfg.py` to fix the issue.

[SYCL][E2E] Fix LIT requires vulkan directive

---

unified-runtime/source/adapters/opencl/common.cpp
unified-runtime/source/adapters/opencl/kernel.cpp

Fixes https://github.com/oneapi-src/unified-runtime/issues/2555
Also handles checking for CL_INVALID_KERNEL_DEFINITION inside urKernelCreate.

[UR][OpenCL] Add missing mapping for CL_INVALID_KERNEL to UR OpenCL adapter and handle CL_INVALID_KERNEL_DEFINITION in urKernelCreate

---

unified-runtime/source/loader/layers/validation/ur_leak_check.hpp

Fixes https://github.com/intel/llvm/issues/18341

[UR] Use std::move so vector is not copied in validation layer RefRuntimeInfo struct

---

sycl/source/detail/device_impl.cpp
sycl/source/detail/device_impl.hpp

Use `get_info_impl*` helpers from
https://github.com/intel/llvm/pull/18358 and add a new `has_info_desc` of a similar nature.

[NFC][SYCL] Reduce boilerplate in aspects implementation

---

sycl/test-e2e/USM/fill_any_size.cpp

Reverts intel/llvm#18153
This test appears flaky so re-enabling for now, investigating a fix for this.

Revert "[SYCL][E2E] Re-enable test-e2e/USM/fill_any_size.cpp for OpenCL as it now passes"

---

sycl/include/sycl/ext/oneapi/experimental/event_mode_property.hpp

This commit fixes the mention of event_mode_property.hpp in the copyright notice of its own header.

[SYCL][NFC] Fix event_mode_property name in copyright header

---

sycl/source/detail/device_binary_image.cpp

The use of std::aligned_alloc requires the size of the memory allocated to be a multiple of the alignment. This patch fixes the use of std::aligned_alloc in DynRTDeviceBinaryImage to adhere to these requirements. Note that _aligned_malloc from MSVC does not have this requirement.

[SYCL] Fix potential misaligned allocation size

---

unified-runtime/source/adapters/level_zero/image.cpp

`ur_exp_image_mem_native_handle_t` is a `ur_bindless_mem_handle_t *`,
but was incorrectly being treated as a `ur_mem_handle_t` on destruction.

[UR][L0] Correctly destroy images

---

sycl/test-e2e/Basic/image/image_max_size.cpp

The test was allocating images that were bigger than necessary. This makes the test run slower and use more memory.

[SYCL][E2E] Reduce memory requirements on image_max_size

---

unified-runtime/source/adapters/level_zero/kernel.cpp

The `WorkDim` is not respected in the process, leading to an OOB access when `WorkDim < 3`.

[UR][L0 Adapter] Fix an OOB access

---

unified-runtime/source/adapters/level_zero/v2/memory.cpp

getDevicePtr and mapHostPtr for ur_usm_handle_t.
We never actually use the handle with non-zero offset but we may change that in future.

[SYCL][UR][L0 v2] add missing offset calculation to

---

sycl/include/sycl/detail/kernel_desc.hpp
sycl/test-e2e/KernelParams/has-special-captures.cpp

Detecting which kernel functions have special captures (i.e., anything that isn't a standard layout class or pointer) will enable us to introduce a fast path for those kernels.
Note that supporting this functionality requires all of the kernel descriptor functions to be constexpr. This was already the case for the functions generated for the integration header, but was not true for some of the new builtins and placeholder functions in kernel_desc.hpp.
---
As a note to reviewers: I do have some prototype functionality ready that uses this, but I thought that splitting things into two separate pull requests would make things easier to review.

[SYCL] Add hasSpecialCaptures() constexpr function

---

devops/scripts/benchmarks/benches/compute.py

to be able to compare performance with and without events and copy offload.

[SYCL][Benchmarks] group MemcpyExecute benchmarks

---

sycl/source/detail/event_impl.cpp
sycl/test-e2e/Basic/profile_host_task.cpp

The submission time for host_task events was previously obtained using `std::chrono::steady_clock`, while the command start and end times were derived from `high_resolution_clock`. This discrepancy in clock epochs led to meaningless duration calculations when users used submission time as a reference.
This update standardizes the clock source by switching the submission time to use `high_resolution_clock`, ensuring consistent and meaningful timing results for host_task events.
Note: `steady_clock` is not related to wall clock. See https://en.cppreference.com/w/cpp/chrono/steady_clock

[SYCL][host_task] Align host_task event submission clock with start/end clock

---

unified-runtime/test/conformance/exp_command_buffer/copy.cpp
unified-runtime/test/conformance/exp_command_buffer/read.cpp
unified-runtime/test/conformance/exp_command_buffer/write.cpp

The comparison on the assert conditions was incorrect, and should be flipped to verify that the allocation size is greater than or equal to the bytes being copied/read/written. Discovered during local testing with a debug build
```
[ RUN      ] urCommandBufferMemcpyCommandsTest.Buffer/NVIDIA_CUDA_BACKEND__NVIDIA_GeForce_GT_1030_ID0ID______W_________B______size__256__offset_src__127__offset_src__127__copy_size__128
test-exp_command_buffer: unified-runtime/test/conformance/exp_command_buffer/copy.cpp:28: virtual void urCommandBufferMemcpyCommandsTest::SetUp(): Assertion `size <= offset_src + copy_size' failed.
Aborted (core dumped)
```
We could just remove these asserts, as they are not present in other CTS tests, but I think they do add some value in catching programmer error when adding …

[UR][CTS] Flip command-buffer assert condition

---

unified-runtime/source/adapters/cuda/enqueue.cpp
unified-runtime/test/conformance/enqueue/urEnqueueUSMAdvise.cpp
unified-runtime/test/conformance/enqueue/urEnqueueUSMPrefetch.cpp

When we exit early we still need to return a proper event.
This fixes segfaults in the UR CTS, the HIP version of these entry points was already handling this properly, so remove the known failures for both.

[UR][CUDA] Fix prefetch/advise early exit

---

sycl/source/detail/device_impl.cpp
sycl/source/detail/device_impl.hpp

It's known in compile-time for all the uses, no need to keep it as a run-time value. Might enable extra refactoring on top of this.

[NFC][SYCL] Pass `ur_device_info_t` via template in `get_info_impl*`

---

sycl/include/sycl/detail/memcpy.hpp

Older gcc when used as host compiler may trigger memaccess warning. This simple cast avoids that warning.

[SYCL] workaround for memaccess warning from older hostcompiler

---

unified-runtime/test/conformance/source/environment.cpp
unified-runtime/test/conformance/testing/include/uur/environment.h

Allow explicitly overriding the name of the target to load kernel sources for. This is useful if the backend supports multiple targets, and a test wants to load the source for a specific one. Multiple targets might for example be SPIR-V and native binary format for the OpenCL or Level Zero backend, or future vendor specific intermediate representations.
The overload taking a platform is unchanged, it will load a the source for the "default" target for the backend, which is the same as before.

[UR][Test] Explicit target name in KernelsEnvironment::LoadSource (NFCI)

---

sycl/include/sycl/detail/id_queries_fit_in_int.hpp

The code previously cast to unsigned, assuming that checking the lower 32 bits would be sufficient for the overflow calculation.
This is not true, because casting a `size_t` to `unsigned` could result in a very small number, e.g. `std::numeric_limits<unsigned>::max() + 1` casts to 0.

[SYCL] Fix checkValueRange

---

llvm/lib/SYCLPostLink/ModuleSplitter.cpp

Adding `std::move` to variables that can be moved to prevent copies.

[SYCL][NFC] Move instead of copy.

---

sycl/test-e2e/KernelAndProgram/cache_env_vars.cpp
sycl/test-e2e/KernelAndProgram/cache_env_vars_lin.cpp
sycl/test-e2e/KernelCompiler/opencl.cpp
sycl/test-e2e/KernelCompiler/sycl_cache_pm.cpp

See https://github.com/intel/llvm/issues/18416

[SYCL][E2E] XFAIL failing DG2 tests

---

sycl/source/detail/device_impl.cpp
sycl/source/detail/device_impl.hpp

https://github.com/intel/llvm/pull/18425 has ensured that current manually specified return type and the auto-deduced one are the same.

[NFC][SYCL] Auto-deduce return type for `device_impl::get_info_impl*`

---

sycl/test-e2e/lit.cfg.py

Fixes https://github.com/intel/llvm/issues/18416

[SYCL][E2E] Fix level_zero v2 specifier being stripped too early

---

unified-runtime/source/adapters/level_zero/queue.cpp
unified-runtime/source/adapters/level_zero/usm.cpp
unified-runtime/source/adapters/level_zero/usm.hpp

The forEachPool method stops iterating if the callback function returns false. As a result, during EnqueuedPools cleanup, pools later in the chain could be skipped if ealier pools didn't require cleanup.
Additionally, ensure that user-created pools associated with the given queue handle are properly cleaned up during urQueueFinish and urQueueRelease calls.

[UR][L0] Fix pool iteration during freelist cleanup

---

unified-runtime/source/adapters/cuda/command_buffer.cpp
unified-runtime/source/adapters/cuda/command_buffer.hpp

The `ur_exp_command_buffer_handle_t_` definition in the CUDA adapter was missed in https://github.com/intel/llvm/pull/17118 in the changes to inherit from a base handle.
Discovered by seeing segfaults in the UR CTS tests locally, and git bisecting back to that change.

[UR][CUDA] Fix command-buffer handle inheritance

---

sycl/test-e2e/Basic/std_array.cpp

Post-commit failure introduced by https://github.com/intel/llvm/pull/18400 and tracked in https://github.com/intel/llvm/issues/18458.

[SYCL-E2E] Disable Basic/std_array.cpp for GEN12 on Windows

---

devops/scripts/benchmarks/requirements.txt

Mako is required for building IGC from source.

[CI][Benchmarks] add mako to requirements

---

sycl/source/detail/device_impl.hpp

I tracked the appearance of `_nocheck` down to
https://github.com/intel/llvm/pull/937 and James doesn't remember anything specific requiring that vs "checked" version. Also, some similar USM-related aspects (those that don't just delegate to `get_info`) do use "checked" APIs, so it seems logical to unify this processing.
The main reason I do this is that it would be a bit easier to cache the values of "checked" interfaces by pre-computing USM support in `device_impl`'s ctor. Note that we perform at least some of those every time we allocate USM memory, so doing the caching is desirable (even for the sake of cleaning up our traces).

[NFCI][SYCL] Use `get_info_impl` (not `_nocheck`) for USM info descriptors

---

.github/workflows/sycl-rel-nightly.yml

After a recent change the target device must be specified.

[CI][sycl-rel] Specify device for win-e2e

---

sycl/doc/developer/ABIPolicyGuide.md

This commit makes a mention of ABI breaking changes being made under preview macro guards to help ensuring they get promoted during the ABI breaking window.

[SYCL][Docs] Mention preview macro for early ABI breaks

---

llvm/cmake/modules/AddSecurityFlags.cmake

This reverts commit dda1c1598a69e311c36938466528031f4025541e.

Revert "[SYCL] Refresh hardening flags applied to the project (#18447)"

---

unified-runtime/include/ur_api.h
unified-runtime/scripts/core/EXP-COMMAND-BUFFER.rst
unified-runtime/scripts/core/exp-command-buffer.yml
unified-runtime/source/adapters/cuda/command_buffer.cpp
unified-runtime/source/adapters/cuda/command_buffer.hpp
unified-runtime/source/adapters/hip/command_buffer.cpp
unified-runtime/source/adapters/hip/command_buffer.hpp
unified-runtime/source/adapters/level_zero/command_buffer.cpp
unified-runtime/source/adapters/level_zero/command_buffer.hpp
unified-runtime/source/adapters/mock/ur_mockddi.cpp
unified-runtime/source/loader/layers/tracing/ur_trcddi.cpp
unified-runtime/source/loader/layers/validation/ur_valddi.cpp
unified-runtime/source/loader/ur_ldrddi.cpp
unified-runtime/source/loader/ur_libapi.cpp
unified-runtime/source/ur_api.cpp
unified-runtime/test/conformance/exp_command_buffer/CMakeLists.txt
unified-runtime/test/conformance/exp_command_buffer/commands.cpp
unified-runtime/test/conformance/exp_command_buffer/in-order.cpp
unified-runtime/test/conformance/exp_command_buffer/native-command/append_native_L0.cpp
unified-runtime/test/conformance/exp_command_buffer/native-command/append_native_cuda.cpp
unified-runtime/test/conformance/exp_command_buffer/native-command/append_native_hip.cpp
unified-runtime/test/conformance/exp_command_buffer/native-command/append_native_opencl.cpp

Closes issue https://github.com/intel/llvm/issues/18330 to enhance the semantics of the UR command-buffer in-order property such that sync-point dependencies will always be ignored.
Also fixes up an artifact in the UR command-buffer spec where it says that descriptors to the command-buffer creation API can be optional, when after https://github.com/intel/llvm/pull/17058 they are mandatory.

[UR][Graph] Strengthen in-order command-buffer property

---

sycl/test-e2e/KernelAndProgram/cache_env_vars.cpp
sycl/test-e2e/KernelAndProgram/cache_env_vars_lin.cpp
sycl/test-e2e/KernelCompiler/opencl.cpp
sycl/test-e2e/KernelCompiler/sycl_cache_pm.cpp

Reverts intel/llvm#18445
The root cause for the test failure was fixed in https://github.com/intel/llvm/pull/18420.
This now leads to unexpectedly passing tests.

Revert "[SYCL][E2E] XFAIL failing DG2 tests"

---

clang/lib/Driver/ToolChains/Clang.cpp
clang/test/Driver/sycl-host-compiler-old-model.cpp

The use of `-fsycl-host-compiler=arg` allows a user to specify a 3rd party compiler to perform host compilation when using `-fsycl`.  The compilation will also include the SYCL specific headers.  Pass in these headers as system headers with `-isystem` so they are treated as system headers as opposed to user headers.

[Driver][SYCL] Pass as system headers for external SYCL host compilation

---

sycl/doc/extensions/experimental/sycl_ext_oneapi_graph.asciidoc

This note on L0 implementation known issues doesn't exist with out immediate append path in the L0 adapter.

[SYCL][Graph] Remove outdated known issue

---

xptifw/CMakeLists.txt
xptifw/CMakeLists.txt.in
xptifw/samples/sycl_perf_collector/sycl_perf_collector.cpp
xptifw/src/CMakeLists.txt
xptifw/src/xpti_trace_framework.cpp
xptifw/unit_test/CMakeLists.txt

This PR is first of many XPTI changes to address the performance issues that have been reported.
(1) xpti::Framework::instance() - testing the use of std::call_once against current implementation 
(2) Added cleanup for default stream "xpti.framework"
(3) Switched to EmHash instead of std::unordered_map that improve notification performance by 10%
Most of the performance overheads are from xptiRegisterObject() and xptiAddMetadata(). This requires changes in the SYCL runtime an will be addressed in a subsequent PR

[XPTI][INFRA] Fixes minor standalone build and code issues

---

libclc/utils/prepare-builtins.cpp

In #17999 I changed prepare-builtins to clear target-cpu and target-features for NativeCPU, and attempted to preserve existing behavior for other targets. For NativeCPU, two errors cancelled each other out so we do the right thing there, but for other targets, that is not the case and target-cpu and target-features were also being cleared unintentionally.

[SYCL] Revert prepare-builtins change for non-NativeCPU.

---

sycl/ur_win_proxy_loader/ur_win_proxy_loader.cpp
unified-runtime/source/adapters/level_zero/adapter.cpp
unified-runtime/source/adapters/level_zero/common.cpp
unified-runtime/source/adapters/level_zero/v2/common.hpp

This reapplies some of the changes from https://github.com/intel/llvm/pull/17536 (without changes to leak_checker which broke internal testing).
This fixes: https://github.com/intel/llvm/issues/18463

[SYCL][UR][L0 v2] Implement API logging using L0 loader

---

libdevice/cmake/modules/SYCLLibdevice.cmake

Two problems:
1) The option was renamed to `--gcc-install-dir`
2) We forgot to pass the flag for the IMF build.

[SYCL] Fix build with non-standard GCC install directory

---

sycl/include/sycl/stl_wrappers/corecrt.h

Header definitions should be `inline` to avoid multiple definitions error.

[SYCL] Use `inline` in device definition of `_invalid_parameter`

---

libdevice/sanitizer/asan_rtl.cpp
libdevice/sanitizer/msan_rtl.cpp

fix: https://github.com/intel/llvm/issues/18516 CMPLRLLVM-67822

[DeviceSAN] Fix asan and msan lit tests crashed on CPU

---

sycl/source/detail/graph_impl.cpp
sycl/source/detail/graph_impl.hpp

Changes some functions in the sycl graph implementation to pass shared pointers by reference instead of by value.
Fixes: #18412

[SYCL][Graph]Fix coverity issues by passing shared pointer by reference.

---

devops/scripts/benchmarks/benches/gromacs.py

In PR #17934, CI run of Gromacs benchmark was unable to find libraries - fixed. Additionaly, minor fixes from comments

[UR][Benchmarks] Fix of #17934 - Gromacs benchmark

---

sycl/ur_win_proxy_loader/ur_win_proxy_loader.cpp
unified-runtime/cmake/FetchLevelZero.cmake

- Add support for L0 teardown notification in the static L0 loader.
- Add loading of the L0 dynamic loader in the windows proxy loader to ensure that the L0 dynamic loader is usable during teardown.

[UR][L0] Add L0 teardown notification support and simply teardown with proxy loader support

---

sycl/test-e2e/lit.cfg.py

Checking the output of `get_sycl_ls_verbose` expected the function to
update a global `sp` variable. Since it didn't do that, this resulted
in an error when trying to print the command output.
This patch changes the function to return the subprocess directly, which
is used during error message generation.

[SYCL][E2E] Fix error reporting in e2e lit config

---

libdevice/cmake/modules/SYCLLibdevice.cmake
libdevice/include/group_utils.hpp
libdevice/include/sanitizer_defs.hpp

We defined some group/subgroup util functions in device sanitizer specific headers, these functions will be used by other libdevice functions, so move them to a separate header.

[SYCL][libdevice] Move common group utils from sanitizer specific header

---

unified-runtime/source/adapters/level_zero/v2/event.cpp
unified-runtime/source/adapters/level_zero/v2/queue_handle.hpp

ur_queue_handle_t_ was not inheriting from ur::handle_base resulting in *reinterpret_cast<ur_dditable_t **>(hQueue) not working correctly.
For some reason this worked on some platforms, and only manifested on PVC.

[SYCL][UR][L0 v2] fix ur_queue_handle_t_ after #17118

---

sycl/gdb/libsycl.so-gdb.py
sycl/source/detail/device_impl.cpp
sycl/source/detail/device_impl.hpp
sycl/source/detail/program_manager/program_manager.cpp
sycl/source/detail/queue_impl.cpp
sycl/source/detail/scheduler/commands.cpp
sycl/test/gdb/printers.cpp

I think this is better than a simpler https://github.com/intel/llvm/pull/18450 as it allows much easier experiments/tuning on what should be cached and how.

[NFCI][SYCL] Generalize `device_impl`'s properties caching

---

.github/workflows/sycl-post-commit.yml
devops/actions/run-tests/windows/e2e/action.yml
sycl/test-e2e/Basic/std_array.cpp

The issue is specific to the post-commit CI using OneAPI compiler to build SYCL RT (see https://github.com/intel/llvm/issues/18458). Ideally, we'd like to use `/Qno-intel-lib` during such build but OneAPI seems to have a bug related to that (reported internally). It will take an official release for it to reach this CI even after it's implemented, so we need to disable the test on that specific configuration only for the time being.

[SYCL][E2E][CI] Disable `std_array.cpp` at CI level

---

unified-runtime/source/adapters/level_zero/program.cpp
unified-runtime/source/adapters/level_zero/program.hpp

Refactor the code to make it easier to add support for different IL formats (besides SPIR-V) in the future.
The only functional change is that SPIR-V binaries with invalid magic number are now rejected by returning UR_RESULT_ERROR_INVALID_BINARY from urProgramCreateWithIL.

[UR][L0] Refactor IL code handling allowing future extension

---

sycl/doc/extensions/experimental/sycl_ext_oneapi_bindless_images.asciidoc

The missed changelog entry for adding `unmap_...` functions has been added.
Some outdated notes relating to backend support have been removed/updated.

[SYCL][Bindless][Doc] Add missed changelog entry. Remove outdated comments.

---

sycl/source/CMakeLists.txt
sycl/source/detail/compiler.hpp
sycl/source/detail/device_binary_image.cpp
sycl/source/detail/jit_compiler.cpp
sycl/source/detail/program_manager/program_manager.cpp
sycl/test/CMakeLists.txt
sycl/unittests/Extensions/DeviceGlobal.cpp
sycl/unittests/Extensions/VirtualFunctions/RuntimeLinking.cpp
sycl/unittests/helpers/MockDeviceImage.hpp
sycl/unittests/pipes/host_pipe_registration.cpp
sycl/unittests/program_manager/Cleanup.cpp
sycl/unittests/program_manager/CompileTarget.cpp
sycl/unittests/program_manager/DynamicLinking/DynamicLinking.cpp
sycl/unittests/program_manager/arg_mask/EliminatedArgMask.cpp
sycl/unittests/program_manager/passing_link_and_compile_options.cpp

Reverts intel/llvm#16763 - Turns out UCRT is causing a problem for this on Windows. We need https://github.com/intel/llvm/pull/18200 before we can reintroduce it.

Revert "[SYCL] Link and include LLVMSupport in SYCL library"

---

sycl/test-e2e/Experimental/free_functions/templates_cpp_non_integral_type.cpp

The test in sycl/test-e2e/Experimental/free_functions/templates_cpp_non_integral_type.cpp misspelled "templated" as "tempalted". This commit fixes the spelling.

[SYCL][E2E][NFC] Fix spelling in templates_cpp_non_integral_type

---

sycl/source/detail/adapter.hpp
sycl/source/detail/scheduler/scheduler.cpp

Add UR error code when throwing exception from Scheduler::enqueueCommandForCG.
Remove message string from non adapter specific error exception in checkUrResult as it's only used in the adapter specific error path.
This is related to https://github.com/oneapi-src/unified-runtime/issues/2440 and https://github.com/intel/llvm/pull/18423 where `clEnqueueMemFillINTEL` was failing with -30 (`CL_INVALID_VALUE`) but no detail was provided in the log:
```
terminate called after throwing an instance of 'sycl::_V1::exception'
what():  Enqueue process failed.
Aborted (core dumped)
```
This is because the first exception thrown from `checkUrResult` was being hidden by a second exception thrown from `Scheduler::enqueueCommandForCG`. I've modified this second exception to include the UR result. The …

[SYCL] Add UR error code when throwing exception from Scheduler::enqueueCommandForCG

---

libclc/utils/libclc-remangler/LibclcRemangler.cpp

This commit adds some checks to the remangler. It prevents it from generating clones or renaming functions if a function with the target name already exists in the module.
This can happen if the libspirv source provides, e.g., both a char and a signed char version of a builtin and the remangler wants to remangle char to signed char.
In such cases we'd previously generate new unreachable builtins as to avoid the naming clash LLVM would give them a random suffix like renaming _Z3fooi to _Z3fooi24234. We can't know that the functions are equivalent but this situtation is no worse than before - we'd be calling into the 'wrong' builtin in any case.
This removes around 2000 unreachable builtins from the 'l64' remangled libraries and 300 from the 'l32' ones.
This commit does introduce some new …

[libspirv] Avoid duplicating builtins during remangling

---

sycl/source/detail/global_handler.cpp
sycl/source/detail/global_handler.hpp

A follow up on the code review of https://github.com/intel/llvm/pull/18081

[SYCL] Get rid of vector reallocations for kernel name caches

---

unified-runtime/test/conformance/testing/include/uur/utils.h

For ease of debugging, the platform name also prepends the name of the
adapter, resulting in test names like:
`urEventGetProfilingInfoTest/ReleaseEventAfterQueueRelease/UR_BACKEND_OPENCL__AMD_Accelerated_Parallel_Processing__gfx1100_ID5ID_` .

[UR] Include the backend name in the platform string for testing

---

.github/workflows/sycl-nightly.yml

Sometimes the job hangs and reaches the 360m limit.

[CI] Set a time limit for sycl-cts

---

unified-runtime/test/conformance/exp_command_buffer/in-order.cpp

CTS test `urInOrderUSMCommandBufferExpTest.WithHints` has been reported as failing on unrelated PRs on PVC in GitHub CI https://github.com/intel/llvm/issues/18544 which were added recently in #18444
Disable the UR CTS in-order tests on Level-Zero V1 adapter until this bug is investigated and resolved. I've disabled more than the specific test that fails, as the others UR tests inheriting from the base fixture are variants, and it is not unlikely that we'd end up seeing flaky fails in CI for them too.

[UR][Graph] Disable flaky PVC CTS test

---

libdevice/sanitizer/tsan_rtl.cpp
llvm/lib/Transforms/Instrumentation/ThreadSanitizer.cpp
sycl/test-e2e/ThreadSanitizer/aot/Inputs/usm_data_race.cpp
sycl/test-e2e/ThreadSanitizer/check_buffer.cpp
sycl/test-e2e/ThreadSanitizer/check_device_global.cpp
sycl/test-e2e/ThreadSanitizer/check_device_usm.cpp
sycl/test-e2e/ThreadSanitizer/check_host_usm.cpp
sycl/test-e2e/ThreadSanitizer/check_no_race.cpp
sycl/test-e2e/ThreadSanitizer/check_shared_usm.cpp
sycl/test-e2e/ThreadSanitizer/check_sub_buffer.cpp

According to sycl spec, these is no dependency between each work item. So we'd better treat each work item as a thread.
* Fix one minor bug to calculate thread id
* Make e2e tests more robust

[DevTSAN] Treat each work item as a thread for both CPU & GPU device

---

clang/include/clang/Basic/DiagnosticDriverKinds.td
clang/lib/Driver/Driver.cpp
clang/lib/Driver/SanitizerArgs.cpp
clang/lib/Driver/ToolChains/AMDGPU.h
clang/lib/Driver/ToolChains/Clang.cpp
clang/lib/Driver/ToolChains/SYCL.cpp
clang/test/Driver/sycl-unsupported.cpp

Allow `-gline-tables-only` for the SYCL host compilation only, providing a warning that `-gline-tables-only` does not apply to device compilation.
Example:
```
clang++ -### -fsycl -gline-tables-only syclfile.cpp
ignoring `-gline-tables-only` option as it is not currently supported for target 'spir64';only supported for SYCL host compilation
```

[SYCL][Driver] Allow -gline-tables-only for the SYCL host compilation only.

---

devops/scripts/benchmarks/benches/compute.py

Currently L0/opencl benchmarks is still built on computeBench even when we specify that we need to benchmark sycl on top of cuda that creates an error sometimes when the execution environment doesn't have L0 setup. That PR will close building L0/opencl benchmarks on computeBench when we specify cuda target for benchmarking.

[Benchmark] Switch off L0 for computeBench on SYCL for CUDA

---

sycl/source/detail/device_impl.hpp

Follow-up for https://github.com/intel/llvm/pull/18477.

[SYCL] Fix `-Werror=unused-but-set-variable` warning with old gcc

---

libclc/CMakeLists.txt
libclc/clc/include/clc/clcfunc.h
libclc/generic/include/clc/clc.h
libclc/libspirv/include/libspirv/spirv.h

Having the macros defined in either the SPIR-V headers or OpenCL headers left it easy for the generic address space macros to be undefined. What's worse is there was no warning or error that this was happening.
This commit moves the definition of these macros into a common shared header that all three builtin libraries see. It also ensures the build will fail on the use of any undefined macro. This mirrors how upstream will (likely) eventually place the code, though in all likelihood it will differ slightly.

[libclc] Ensure CLC builtins see the generic addrspace

---

unified-runtime/test/conformance/exp_command_buffer/enqueue.cpp

As tracked in https://github.com/intel/llvm/issues/18610 there have been fails for the
`urEnqueueCommandBufferExpTest.SerializeOutofOrderQueue` UR CTS test on the Level-Zero V2 adapter on unrelated PRs.
Disabling test on V2 until issue can be investigated/resolved to help keep CI stable.

[UR][Graph] Disable flaky CTS test on L0 v2

---

libclc/clc/lib/generic/math/clc_sincos.inc

Having CLC sincos call back to SPIR-V sincos would (in the 'generic' target) end up in a recursive loop as SPIR-V sincos defers to CLC sincos.

[libspirv] Align __clc_sincos with upstream

---

libclc/CMakeLists.txt
libclc/clc/include/clc/clcfunc.h
libclc/libspirv/include/libspirv/conversion/GenericCastToPtrExplicit.h

After a merge resolution we were left with two essentially equivalent methods of enabling generic address space support in libclc and libspirv. This commit removes the old downstream implementation.
There was also a merge conflict resolution bug in that we were multiply-defining a macro, which could lead to errors when compiling.
One downstream-specific libspirv builtin was unconditionally assuming generic AS support, which we don't assume upstream. This presumably isn't a problem in our regular SYCL builds, but other upstream libclc targets fail when hitting this code.

[libclc] Align generic AS support with upstream

---

unified-runtime/scripts/core/INTRO.rst
unified-runtime/test/conformance/testing/include/uur/fixtures.h
unified-runtime/test/conformance/testing/include/uur/known_failure.h

This adds a platform blacklist that causes all tests on that platform
to be skipped. The AMD OpenCL device is currently the only platform
on this list (as we don't officially support it - users should use
the HIP backend instead).

[UR] Skip CTS testing on certain platforms

---

sycl/include/syclcompat/kernel.hpp
sycl/source/detail/kernel_compiler/kernel_compiler_opencl.cpp
sycl/source/detail/kernel_program_cache.hpp
sycl/source/detail/program_manager/program_manager.cpp

std::locale::global() in a user app can impact the SYCL library by side-effect, causing numbers (include hex) to be formatted with commas and periods where we might not expect such.  In most cases, our use of std streams is for user facing messages. But in some cases they are used in places where unexpected formatting could cause errors. This PR attempts to shore these places up.

[SYCL] protect against possible data corruption cause by std::locale side effect

---

sycl/test-e2e/Config/select_device.cpp

The allowList can be empty when performing the check on the line changed. This is usually not an issue, as it ends up evaluating to false, however when using GCC 15, and compiling with `-O0` this will crash instead. Adding the empty check to avoid this crash.

[SYCL][E2E] Fix `Config/select_device.cpp` when using GCC 15

---

clang/lib/Driver/ToolChains/Clang.cpp

This is defined in the a few lines before [here](https://github.com/intel/llvm/blob/e7ab07d4a827e1d3cb121a27acb2d519dd477465/clang/lib/Driver/ToolChains/Clang.cpp#L5676).

[clang][SYCL] Remove redundant default opt level in clang toolchain

---

unified-runtime/test/conformance/enqueue/urEnqueueKernelLaunchAndMemcpyInOrder.cpp
unified-runtime/test/conformance/enqueue/urEnqueueUSMAdvise.cpp
unified-runtime/test/conformance/enqueue/urEnqueueUSMMemcpy.cpp
unified-runtime/test/conformance/enqueue/urEnqueueUSMPrefetch.cpp
unified-runtime/test/conformance/memory-migrate/urMemBufferMigrateAcrossDevices.cpp
unified-runtime/test/conformance/memory/urMemGetInfo.cpp
unified-runtime/test/conformance/queue/urQueueGetInfo.cpp

Failing gtest doesn't fail right away. Wrap all calls to base class
"SetUp" methods in the `UUR_RETURN_ON_FATAL_FAILURE` macro.
This also includes cases where these functions were the last line in
the function, making it a NFC, but updating those for consistency.

[UR] Ensure all CTS SetUp functions check their results

---

libclc/libspirv/include/libspirv/atomic/atomic_xchg.h

This fixes build errors seen after #18613 in NativeCPU and AMD.

[libspirv] Fix atomic_xchg declarations.

---

unified-runtime/scripts/core/INTRO.rst

Current documentation states the `UR_LAYER_FULL_VALIDATION ` env var enables `UR_LAYER_PARAMETER_VALIDATION` and `UR_LAYER_LEAK_CHECKING` but in the [code](https://github.com/intel/llvm/blob/375974ee85bef7e504550a0e7595d109bfe9bcd7/unified-runtime/source/loader/layers/validation/ur_valddi.cpp#L12313) it also enables `UR_LAYER_BOUNDS_CHECKING` and `UR_LAYER_LIFETIME_VALIDATION`.

Update description of UR_LAYER_FULL_VALIDATION in docs to reflect behaviour in code

---

sycl/doc/extensions/experimental/sycl_ext_oneapi_tangle.asciidoc

This PR cares about potential leftover / typo in  https://github.com/intel/llvm/edit/sycl/sycl/doc/extensions/experimental/sycl_ext_oneapi_tangle.asciidoc#:~:text=320-,321,-322: as suggested by @AlexeySachkov here https://github.com/intel/llvm/pull/16151#discussion_r1868084750

Fix leftover in sycl_ext_oneapi_tangle.asciidoc

---

devops/scripts/benchmarks/html/scripts.js

Fixes benchmark results presentation on https://oneapi-src.github.io/unified-runtime/performance/
The same runs now have the same color on subsequent charts

[UR][Benchmarks] fix bench charts colors

---

unified-runtime/source/adapters/level_zero/device.cpp
unified-runtime/test/adapters/level_zero/CMakeLists.txt
unified-runtime/test/adapters/level_zero/urDeviceSelectBinary.cpp

We would like to extend urDeviceSelectBinary downstream to allow for device-specific binary targets. This commit refactors the current handling to make this easier.
Additionally L0 specific tests are added for urDeviceSelectBinary to verify that the fallback logic works as expected.

[UR][L0] Refactor urDeviceSelectBinary, allow more fallbacks (NFC)

---

libclc/libspirv/lib/amdgcn-amdhsa/group/collectives_helpers.ll
libclc/libspirv/lib/ptx-nvidiacl/group/collectives_helpers.ll

To align with the comment in the file that specifies 32 storage locations and 128 bits per warp.
Change file to opaque pointer mode.
Add more global variables for different sizes to resolve `Reducing storage for small data types`.

[libspirv][ptx-nvidiacl] Change __clc__group_scratch size to 32 x i128

---

libclc/libspirv/lib/ptx-nvidiacl/math/nextafter.cl

The macro __CLC_FUNCTION is special and is used in CLC headers. Defining it here in an implementation file - nextafter.cl - for another purpose then including half_nextafter.inc which pulls in the SPIR-V headers results in a macro redefinition, which is warned about.
Sicne the name isn't important and is local to this one file, this commit just changes the macro definition to fix the issue.

[libspirv] Avoid macro redefinition

---

unified-runtime/source/loader/layers/sanitizer/asan/asan_interceptor.cpp

Some resource destruction is done in the destructor, but if we don't manually clear the map, then the destructor is called after the adapter release, which leads to the leak report and maybe some UB(trying to use adapter after it is released).

[DeviceASAN] Fix a UR_L0_LEAKS_DEBUG leak report

---

sycl/source/handler.cpp

After https://github.com/intel/llvm/pull/18437, the runtime library is producing a warning about an unused variable AccTarget in handler.cpp. This is due to the variable only being used in assert, which may in turn be removed when assertions are disabled. This commit removes the variable in favor of making the conversion inside the assert.

[SYCL][NFC] Avoid unused variable AccTarget

---

sycl/test-e2e/lit.cfg.py
sycl/test-e2e/lit.site.cfg.py.in

The proprietary Intel Compiler (ICX) uses a different installation layout then clang. It puts tools into a bin/compiler subdirectory (to not expose them on the PATH by default). Handle this by not assuming that the compiler is in the same directory as other llvm tools. Ask the compiler for the path to `llvm-config` for the tools directory, using the `-print-prog-name` option.
`llvm-config` was choosen because lit already assumes it is in the tools directory see for example: [llvm/utils/lit/lit/llvm/config.py:285][1]
[1]: https://github.com/llvm/llvm-project/blob/9cac4bf485e64f7992f2c01bb9517f6379e58164/llvm/utils/lit/lit/llvm/config.py#L285

[SYCL][E2E] Better handle the Intel Compiler in standalone build (NFC)

---

libclc/libspirv/include/libspirv/image/image.h
libclc/libspirv/include/libspirv/spirv_types.h

These are technically required by OpenCL but not observed since downstream we unconditionally build libclc with all extensions enabled. Since this won't fly upstream, this commit prepares the ground for a more correct building of these libraries.

[libspirv] Add include guards where appropriate

---

sycl/test-e2e/AsyncAlloc/device/async_alloc_from_default_pool.cpp
sycl/test-e2e/AsyncAlloc/device/async_alloc_from_pool.cpp
sycl/test-e2e/AsyncAlloc/device/async_alloc_zero_init.cpp
sycl/test-e2e/AsyncAlloc/device/ooo_queue_async_alloc_from_pool.cpp
sycl/test-e2e/AsyncAlloc/lit.local.cfg
unified-runtime/source/adapters/level_zero/CMakeLists.txt
unified-runtime/source/adapters/level_zero/async_alloc.cpp
unified-runtime/source/adapters/level_zero/enqueued_pool.cpp
unified-runtime/source/adapters/level_zero/enqueued_pool.hpp
unified-runtime/source/adapters/level_zero/usm.hpp
unified-runtime/source/adapters/level_zero/v2/context.cpp
unified-runtime/source/adapters/level_zero/v2/context.hpp
unified-runtime/source/adapters/level_zero/v2/queue_immediate_in_order.cpp
unified-runtime/source/adapters/level_zero/v2/queue_immediate_in_order.hpp
unified-runtime/source/adapters/level_zero/v2/usm.cpp
unified-runtime/source/adapters/level_zero/v2/usm.hpp
unified-runtime/test/adapters/level_zero/CMakeLists.txt

This PR ports USM alloc enqueue API introduced to L0 adapter in https://github.com/intel/llvm/pull/17112 to L0 adapter v2.

[UR][L0 v2] Port USM alloc to adapter v2

---

unified-runtime/source/adapters/offload/adapter.cpp
unified-runtime/source/adapters/offload/context.cpp
unified-runtime/source/adapters/offload/device.cpp
unified-runtime/source/adapters/offload/enqueue.cpp
unified-runtime/source/adapters/offload/event.cpp
unified-runtime/source/adapters/offload/kernel.cpp
unified-runtime/source/adapters/offload/platform.cpp
unified-runtime/source/adapters/offload/program.cpp
unified-runtime/source/adapters/offload/queue.cpp
unified-runtime/source/adapters/offload/ur2offload.hpp
unified-runtime/source/adapters/offload/ur_interface_loader.cpp
unified-runtime/test/conformance/adapter/urAdapterGetInfo.cpp

This patch fixes a lot of small issues in order to boost the CTS pass
rate. Specifically:
* A number of optional entry points have been created with a stub entry
point that just returns UNSUPPORTED.
* Some trivial `getInfo` queries have been implemented.
* Some `getInfo` queries advertise absent features as "not supported".
* Trying to run `urEnqueueKernelLaunch` with dimensions greater than 1
fails gracefully.
* `urPlatformGetApiVersion` returns the actual API version.
* `OL_ERRC_NOT_FOUND` is mapped to
`UR_RESULT_ERROR_INVALID_KERNEL_NAME`.
* A conformance test has been updated to accept the Offload enum.
Note that something marked unsupported here does not imply that it
will never be supported; it just isn't supported in the current
version.

[UR][Offload] Small test fixes for CTS

---

unified-runtime/source/common/logger/ur_logger_details.hpp

When the callback sink and the standard sink are both enabled using `std::forward<Args>(args)...` results in a use-after-move. This patches fixes the issue by letting the r-value references decay to l-value references when expanding the `args...` parameter pack and allowing the parameter pack to be passed to multiple functions. The `logger::log()` member function does not need to take ownership of the objects being passed in.

[UR] Fix logger use after move (Coverity)

---

devops/dependencies.json
sycl/test-e2e/ESIMD/group_barrier.cpp

[GHA] Uplift Linux GPU RT version to 25.18.33578.6

---

llvm/lib/SYCLPostLink/CMakeLists.txt

Manually verified the fix, error seen [here](https://github.com/intel/llvm/actions/runs/15280153119/job/42976816882), fix [here](https://github.com/intel/llvm/actions/runs/15283845466).
```
/usr/bin/ld: lib/SYCLPostLink/CMakeFiles/LLVMSYCLPostLink.dir/ESIMDPostSplitProcessing.cpp.o: in function `llvm::sycl::lowerESIMDConstructs(llvm::module_split::ModuleDesc&, bool, bool)':
ESIMDPostSplitProcessing.cpp:(.text._ZN4llvm4sycl20lowerESIMDConstructsERNS_12module_split10ModuleDescEbb+0xb67): undefined reference to `llvm::SROAPass::SROAPass(llvm::SROAOptions)'
/usr/bin/ld: ESIMDPostSplitProcessing.cpp:(.text._ZN4llvm4sycl20lowerESIMDConstructsERNS_12module_split10ModuleDescEbb+0xceb): undefined reference to `llvm::SROAPass::SROAPass(llvm::SROAOptions)'
/usr/bin/ld: …
```

[SYCL] Fix shared library build

---

sycl/test/extensions/free_function_kernels/free_function_kernels_diagnostics.cpp

This PR updates test for free function kernels extension that checks emitted diagnostics if kernel violates restrictions specified in spec for declaration of free function kernel.
https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/proposed/sycl_ext_oneapi_free_function_kernels.asciidoc#defining-a-free-function-kernel
Test introduced based on test plan: https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/FreeFunctionKernels/test-plan.md

[SYCL] Update test for free function kernels extension that checks emitted diagnostics if kernel violates restrictions

---

.github/workflows/sycl-linux-build.yml
.github/workflows/sycl-nightly.yml

There was a case where we broke build for the `all` target but `sycl-toolchain` worked, so build `all` to catch this.
Nightly run [here](https://github.com/intel/llvm/actions/runs/15302502386), failures not because of this.
We need the `||` part in ` ${{ inputs.build_target || 'sycl-toolchain' }}` because for the `workflow_dispatch` case, we already have 10 input args which is the max so we can't always have a `inputs.build_target` available without more work.
Closes: https://github.com/intel/llvm/issues/18648

[CI] Test 'all' cmake target in nightly

---

sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_SLM.cpp

It's XPASSing after the latest driver update, see [here](https://github.com/intel/llvm/actions/runs/15296757125/job/43028280618).

[SYCL][E2E][Matrix] Remove XFAIL from cache SLM test on DG2

---

sycl/source/detail/allowlist.cpp
sycl/unittests/allowlist/DeviceIsAllowed.cpp

`std::locale::global()` is a very common way for apps to initialize string localization for numeric and monetary values.  Unfortunately, it is global. 
In this very limited fix, we are preventing it from interfering with the allowlist check which uses `std::stringstream`.  The insertion of commas into numbers for the locale support messes with the expected values.
We'll probably have to audit the other uses of std streams to see if they would be similarly vulnerable.

[SYCL] fix for std::locale::global interfering with allowlist check

---

unified-runtime/source/adapters/level_zero/command_buffer.cpp
unified-runtime/source/adapters/level_zero/memory.cpp
unified-runtime/source/adapters/level_zero/memory.hpp

Revert [[L0] Refactor Copy Engine Usage checks for Performance](https://github.com/intel/llvm/commit/781e5761928e82bba6de5f9172ed9fe70d7ea93e) and always disable copy-engine in SYCL-Graph on DG2 as a workaround for CMPLRLLVM-68064.

[L0] Revert copy engine refactor and disable copy-engine for SYCL-Graph on DG2

---

libclc/CMakeLists.txt
libclc/cmake/modules/AddLibclc.cmake

The remangler is for libspirv. Don't run remangler on OpenCL library until there is a use case. This would avoids confusions on unused remangled OpenCL library in build folder.

[libclc] Don't run remangler on OpenCL library

---

sycl/test-e2e/Graph/lit.local.cfg

Disable SYCL-Graph DG2 E2E testing on the Level-Zero adapter. https://github.com/intel/llvm/issues/18579 and https://github.com/intel/llvm/issues/18668 report large numbers of tests sporadically failing.
Rather than continuing to mark individual tests as unsupported, skip all DG2 graph testing on the V2 adapter until this issue can be investigated and resolved.

[SYCL][Graph]Disable DG2 testing on L0 V2

---

unified-runtime/source/adapters/level_zero/v2/command_buffer.cpp
unified-runtime/source/adapters/level_zero/v2/command_list_manager.cpp
unified-runtime/source/adapters/level_zero/v2/command_list_manager.hpp
unified-runtime/source/adapters/level_zero/v2/kernel.cpp
unified-runtime/source/adapters/level_zero/v2/kernel.hpp
unified-runtime/source/adapters/level_zero/v2/memory.cpp
unified-runtime/source/adapters/level_zero/v2/memory.hpp
unified-runtime/source/adapters/level_zero/v2/queue_immediate_in_order.cpp

There migration logic is always the same, there's no need to pass callback to every getDevicePtr/map/unmap function.

[SYCL][UR][L0 v2] get rid of std::function in memory.hpp

---

devops/actions/run-tests/benchmark/action.yml

Fixes environment setup for level zero V2 in the benchmarking CI

[CI] Fix L0v2 in benchmarking CI

---

llvm/lib/SYCLNativeCPUUtils/PrepareSYCLNativeCPU.cpp
sycl/test/native_cpu/multiple_definitions.cpp

Taking the kernel name and renaming the original function afterwards caused recently a number of check-sycl tests to fail on Windows:
```
SYCL :: check_device_code/native_cpu/native_cpu_builtins.cpp
SYCL :: check_device_code/native_cpu/vectorization.cpp
SYCL :: native_cpu/link-noinline.cpp
SYCL :: native_cpu/no-opt.cpp
SYCL :: native_cpu/vector-add.cpp
```
This is a quick fix for these fails by removing the Comdat from such kernels. Maintaining the Comdat info properly for such kernels will be addressed in a subsequent PR.
A new test was added to ensure launches from functions with multiple definitions work.

[SYCL][NATIVECPU] remove Comdat from kernel whose name was taken/renamed

---

sycl/source/handler.cpp

In 3a5ee6e secondary queue was set by mistake, it must be not for this constructor.

[SYCL] Do not set secondary queue when one is not passed

---

libclc/libspirv/lib/ptx-nvidiacl/images/image.cl

These functions at most do some casting, and have effectively zero register overhead at default opt level, therefore there should be no usage circumstance that brings a downside to always inlining.
This brings the nvptx libclc image backend in line with the amd one which requires no such changes. amd libclc backend already does the same thing via consistent usage of the _CLC_DECL macro for all functions. Whilst not immediately obvious to the libclc programmer, _CLC_DECL macro calls  `__attribute__((always_inline))`.
There's a few cases that had low register usage that I've added the `inline` hint to also, being probably overly cautious.

[LIBCLC][BINDLESS][CUDA] always inline redirection functs

---

unified-runtime/test/adapters/lit.local.cfg.py

This doesn't affect the `check-unified-runtime-adapter` target, but does
fix the main `check-unified-runtime` target.

[UR][CI] Skip adapter testing for adapters that haven't been built

---

unified-runtime/test/CMakeLists.txt

This list is used in `llvm-lit` to map source configs to their generated
versions. This enables the use of `llvm-lit path/to/test/source/file`
e.g. `llvm-lit ~/dpcpp/unified-runtime/test/adapters/level_zero/confirm_version.cpp`

[UR] Add generated lit files to the `LLVM_LIT_CONFIG_FILES` list

---

unified-runtime/source/adapters/level_zero/v2/queue_immediate_in_order.cpp
unified-runtime/test/conformance/exp_command_buffer/enqueue.cpp
unified-runtime/test/conformance/exp_command_buffer/fixtures.h

[UR] fix: synchronize resubmission of the same command buffer

---

clang/lib/CodeGen/CGExpr.cpp

Re-add routine parameters lost during conflict resolution.
* 0dcd674f - Merge from 'main' to 'sycl-web' (30 commits)
Fixes test:
* CLANG :: CodeGenSYCL/intel-fpga-ivdep-array.cpp

[SYCL] Fix intel-fpga-ivdep-array regression.

---

unified-runtime/source/adapters/level_zero/v2/memory.hpp

It needs to inherit from ur::handle_base<ur::level_zero::ddi_getter>
Previously, only ur_mem_buffer_t inherited from the handle_base which happened to work in most cases as ur_mem_handle_t_ is a variant over few different types, all inheriting from ur_mem_handle_t_.

[SYCL][UR][L0 v2] Fix ur_mem_handle_t_

---

sycl/test-e2e/Basic/multi_context_wait.cpp
unified-runtime/source/adapters/opencl/event.cpp
unified-runtime/test/conformance/event/urEventWait.cpp

SYCL allows creating cross-context dependencies. It automatically handles cases where contexts are from different adapters. However, events from a single adapter are always passed directly to urEventWait (even if they are from different contexts). This causes problems with opencl CPU (it returns CL_INVALID_CONTEXT from clWaitForEvents). In general, OpenCL spec does not guarantee that passing events from different contexts works for any function. The same problem exists for all enqueue functions but in practice SYCL does not mix events in the waitList - it will always use urEventWait for synchronization.

[SYCL][UR][OpenCL] allow passing events from multiple contexts to urEventWait

---

sycl/source/detail/kernel_impl.hpp
sycl/source/detail/scheduler/commands.cpp
sycl/source/detail/scheduler/commands.hpp
sycl/source/kernel.cpp
sycl/unittests/Extensions/CMakeLists.txt
sycl/unittests/Extensions/RootGroup.cpp

Certain branches in functions related to the root group extension's work item query were not covered by any tests. This change removes a subset of them (conditionally, using the `__INTEL_PREVIEW_BREAKING_CHANGES` macro, to maintain the ABI) and adds tests for the others.

[SYCL] Increase test coverage for root group extension

---

llvm/lib/Transforms/Instrumentation/ThreadSanitizer.cpp
llvm/test/Instrumentation/ThreadSanitizer/SPIRV/ignore_target_ext_type.ll

we can't know exactly what size of joint matrix type is, so we need to ignore it.

[DevTSAN] Ignore check for joint matrix access

---

devops/scripts/benchmarks/CONTRIB.md
devops/scripts/benchmarks/benches/base.py
devops/scripts/benchmarks/benches/compute.py
devops/scripts/benchmarks/benches/test.py
devops/scripts/benchmarks/benches/umf.py
devops/scripts/benchmarks/html/scripts.js
devops/scripts/benchmarks/main.py
devops/scripts/benchmarks/output_markdown.py
devops/scripts/benchmarks/utils/result.py

Move `explicit_group` attribute to benchmark metadata object, use it for groups charts display

[Benchmarks] Make group names mutable

---

sycl/include/sycl/ext/oneapi/sub_group_mask.hpp
sycl/test-e2e/SubGroupMask/sub_group_mask_ver2.cpp
sycl/test-e2e/WorkGroupMemory/basic_usage.cpp

Dropped include of SYCL math built-ins, removed use of non-standard `assert` from device code.

[SYCL][NFC] `sub_group_mask.hpp` cleanup

---

sycl/source/detail/queue_impl.cpp
sycl/source/detail/queue_impl.hpp

As that's what it is and not a generic/universal no-event mode.

[NFC] Rename `queue_impl`'s `MNoEventMode`->`MNoLastEventMode`

---

sycl/test-e2e/Assert/Inputs/kernels_in_file2.cpp

`Buf` is uninitialized in this test case, which would lead to device memory sanitizer reporting the error. This patch addresses this problem.

[SYCL][E2E] fix an uninitialized memory usage in test case

---

sycl/test-e2e/Graph/Explicit/basic_buffer.cpp
sycl/test-e2e/Graph/Explicit/buffer_copy.cpp
sycl/test-e2e/Graph/Explicit/buffer_copy_2d.cpp
sycl/test-e2e/Graph/Explicit/buffer_interleave_eager.cpp
sycl/test-e2e/Graph/Explicit/buffer_ordering.cpp
sycl/test-e2e/Graph/Inputs/buffer_interleave_eager.cpp
sycl/test-e2e/Graph/Inputs/buffer_ordering.cpp
sycl/test-e2e/Graph/RecordReplay/basic_buffer.cpp
sycl/test-e2e/Graph/RecordReplay/buffer_interleave_eager.cpp
sycl/test-e2e/Graph/RecordReplay/buffer_ordering.cpp
sycl/test-e2e/Graph/RecordReplay/queue_constructor_buffer.cpp
sycl/test-e2e/Graph/lit.local.cfg

PR https://github.com/intel/llvm/pull/18566 fixes the DG2 SYCL-Graph E2E tests fails seen on DG2 for the V2 adapter. Re-enable tests and add a new test with a reduced version of  `buffer_ordering.cpp` that also exposed the bug.
See:
* https://github.com/intel/llvm/issues/18668
* https://github.com/intel/llvm/issues/18579

[SYCL][Graph][L0 v2] Re-enable DG2 E2E tests

---

llvm/include/llvm/SYCLLowerIR/DeviceConfigFile.td

We were previously reporting all USM aspects as supported on all CUDA devices. This is incorrect behaviour as many devices do not support USM system allocations, nor atomic host/shared USM allocations.
Unfortunately it is very difficult to get a conclusive list of which devices support which features.
Links such as [1] suggest that pageable memory access (which the UR adapater uses to determine the runtime equivalents of these aspects) is limited to a Grace Hopper device or newer, or  with Linux systems with HMM enabled. HMM is not something we can currently determine at compile time for these aspects. This change is therefore conservative for older devices (SM6.X) with HMM enabled, where we will now report "false".
For atomic host/shared allocations, the documentation on the …

[SYCL] Redistribute USM aspects among CUDA devices

---

unified-runtime/source/adapters/level_zero/usm.cpp
unified-runtime/source/adapters/level_zero/v2/context.cpp
unified-runtime/source/adapters/level_zero/v2/context.hpp
unified-runtime/source/adapters/level_zero/v2/queue_immediate_in_order.cpp
unified-runtime/source/adapters/level_zero/v2/usm.cpp
unified-runtime/source/adapters/level_zero/v2/usm.hpp
unified-runtime/test/conformance/usm/urUSMGetMemAllocInfo.cpp

This PR mirrors fixes implemented in https://github.com/intel/llvm/pull/18406 to adapter L0 v1.
To cleanup async pools properly, USM pool handles must be tracked. This feature enables `UR_USM_ALLOC_INFO_POOL`  prop to be implemented in `urUSMGetMemAllocInfo`.

[UR][L0 v2] Add USM pool tracking in context and fix async pool cleanup

---

clang/lib/Headers/__clang_spirv_builtins.h
clang/lib/Sema/SemaDeclAttr.cpp
clang/test/CodeGenSPIRV/Builtins/generic_cast_to_ptr_explicit.c
clang/test/Headers/spirv_functions.cpp

__builtin_spirv_generic_cast_to_ptr_explicit was added upstreaming but because it has limited SYCL support, tests can't run properly.

lGeneric cast integration for SYCL

---

sycl/source/detail/kernel_name_based_cache_t.hpp
sycl/source/detail/kernel_program_cache.hpp

We assume that in most cases, there is only a single context/device per kernel. Considering that using a vector instead of the hash map performs better on a common case scenarios.

[SYCL] use vector instead of map as a kernel cache container

---

sycl/source/detail/graph_impl.cpp
sycl/source/detail/graph_impl.hpp
sycl/source/detail/graph_memory_pool.cpp
sycl/source/detail/graph_memory_pool.hpp
sycl/source/detail/scheduler/commands.cpp
sycl/source/detail/scheduler/commands.hpp

- Fix copy instead of move (522061, 522073)
- Fix auto causing copy (524557)
- Fix uncaught exceptions in `graph_mem_pool` destructor (522004)
Fixes: #18510

[Coverity][Graph] Address coverity issues with graphs

---

sycl/test-e2e/Graph/Update/lit.local.cfg

The Level-Zero V2 has had support for graph update since https://github.com/intel/llvm/pull/17925

[SYCL][Graph] Enable Update tests on L0 V2

---

sycl/source/detail/async_alloc.cpp
sycl/source/detail/graph_impl.cpp
sycl/source/detail/graph_impl.hpp
sycl/source/handler.cpp
sycl/unittests/Extensions/CommandGraph/InOrderQueue.cpp

`foo(const std::shared_ptr<queue_impl> &)` doesn't provide any information about possible `nullptr` arguments. It could provide information about possibility of creating a copy if used sparsely, but when entire codebase passes all objects like this it's meaningless too.
Instead of that, the WIP refactoring across the entire codebase is to pass by raw ptr/ref (depending on the possibility of `nullptr` value) and extending lifetimes with explicit `shared_from_this()`.
This PR is limited to `graph_impl.hpp` interfaces accepting `queue_impl`, clean up after https://github.com/intel/llvm/pull/18715.

[NFCI][SYCL][Graph] Cleanup after `enable_shared_from_this` for `queue_impl`

---

devops/scripts/benchmarks/benches/compute.py

to benchmarks that require it after recent changes in Compute Benchmarks: https://github.com/intel/compute-benchmarks/commit/3e0aa91099eb84d9c6f0c071dc7bf8fdeaf19501 
Fixes benchmark failures:
https://github.com/oneapi-src/unified-runtime/actions/runs/15523865105/job/43700615169#step:15:838
https://github.com/oneapi-src/unified-runtime/actions/runs/15523865105/job/43700615169#step:15:862

[Benchmarks] Add withCopyOffload argument

---

sycl/test-e2e/Graph/Inputs/multiple_exec_graphs.cpp

The multiple_exec_graphs test enqueues multiple instances of executable graphs without any dependencies. However, there is a data race because the test uses an out-of-order queue and every executable graph modifies the same usm memory pointer. This commit solves the issue by using an in-order queue instead.

[SYCL][Graph] Fix data race in the multiple_exec_graphs test

---

devops/scripts/benchmarks/benches/base.py
devops/scripts/benchmarks/benches/compute.py
devops/scripts/benchmarks/benches/llamacpp.py
devops/scripts/benchmarks/benches/syclbench.py
devops/scripts/benchmarks/benches/umf.py
devops/scripts/benchmarks/benches/velocity.py
devops/scripts/benchmarks/main.py

Create metadata during dry runs for all benchmarks even when --sycl, --ur, and --umf options are not set

[Benchmarks] Dry run without phony sycl or ur args

---

sycl/source/detail/device_impl.cpp
unified-runtime/source/adapters/cuda/device.cpp
unified-runtime/source/adapters/level_zero/device.cpp

Current "submission time" calculation is inaccurate because we don't use both synchronized timestamps returned by zeDeviceGetGlobalTimestamps but using only device timestamp from that call and use std::chrono "close" to that call to record the host time. This estimation becomes inaccurate pretty quickly. This PR fixes this problem using the known fact that L0 runtime implementation uses CLOCK_MONOTONIC_RAW on Linux and QueryPerformanceCounter on Windows.
So, with this fix, at the first call, we use both device and host timestamps from zeDeviceGetGlobalTimestamps, subsequent calls (when device timestamp is not requested) will return corresponding host timestamp only, without making the `zeDeviceGetGlobalTimestamps`  call which has high latency.
Even though this approach improves accuracy …

[SYCL][UR] Fix the accuracy of command submission timestamp

---

sycl/test-e2e/lit.cfg.py

They're read as strings, not booleans. Need to be processed as such.

[SYCL][E2E][LIT] Fix processing of boolean parameters

---

sycl/test-e2e/Graph/lit.local.cfg

As reported in CMPLRTST-27275 there are windows test fails on Lunar Lake. Disable these tests until issues can be investigated and fixed.

[SYCL][Graph] Disable Windows tests on LNL

---

clang/lib/Sema/SemaSYCL.cpp
clang/test/SemaSYCL/Inputs/dummy_failed_assert
clang/test/SemaSYCL/__glibcxx_assert_fail.cpp

GCC-15 introduced __glibcxx_assert_fail function used in -O0 for many STL functions' runtime check. Its behavior is similar to normal 'assert', so we have supported it in libdevice in the same way as 'assert'. However, compfail will happen in some scenario reporting "undefined function without SYCL_EXTERNAL" error for "__glibcxx_assert_fail" declared in c++config.h, we have to allow this as exception in SemaSYCL.

[SYCL] Allow __glibcxx_assert_fail in SemaSYCL

---

unified-runtime/scripts/check-hardening.sh
unified-runtime/source/mock/CMakeLists.txt

Firstly, rename `ur_mock_headers` to `ur_mock` as this is a shared library not header only library.
Secondly, when part of a subbuild, ensure that the `ur_mock` target depends on the specified `UR_EXTERNAL_DEPENDENCIES`, this is handled by using `add_ur_library()` in place of `add_library()`.

[UR] Ensure mock target depends on UR_EXTERNAL_DEPENDENCIES

---

buildbot/configure.py

https://github.com/intel/llvm/pull/18547 introduced new flag, unsupported by the 6_2 release.

[sycl-rel][NFC] Add --use-zstd to configure.py

---

clang/lib/Sema/SemaSYCL.cpp

This resolves Coverity issue `440250`
(https://scan.coverity.com/projects/intel-llvm?tab=overview).
We know that `ND` cannot be `nullptr`, but presence of the check makes Coverity think that earlier accesses (within the `while` loop condition) are potentially unsafe.

[SYCL][NFC] Drop unnecessary `nullptr` check

---

sycl/include/sycl/detail/common.hpp
sycl/source/detail/common.cpp
sycl/source/detail/queue_impl.cpp
sycl/test/abi/layout_tls_code_loc_t.cpp

This PR decreases the number of TLS accesses in the `NestedCallsTracker` and `tls_code_loc_t`. The idea is to cache TLS location in the reference. As a result, we have only a single lookup for the TLS location.

[SYCL] Optimize TLS usage in `NestedCallsTracker` and `tls_code_loc_t`

---

.github/workflows/coverity.yml
.github/workflows/sycl-linux-build.yml
.github/workflows/sycl-macos-build-and-test.yml
.github/workflows/sycl-windows-build.yml
buildbot/configure.py

Follow up of https://github.com/intel/llvm/pull/18547

[CI] Move setting `--use-zstd` flag from workflow files to configure.py

---

sycl/test-e2e/Adapters/level_zero/interop-direct.cpp

The fix is no longer need and not working at the moment since it does not come with `%{run}`.

[DeviceSanitizer] Remove not needed test fix.

---

sycl/cts_exclude_filter/compfails

https://github.com/intel/llvm/issues/18947

[CI][sycl-cts] Disable test_event

---

llvm-spirv/test/DebugInfo/X86/dbg-value-range.ll

This update is necessary following the change in 28bda778.

Update dbg-value-range.ll following MCAsmInfo syntax change.

---

sycl/cmake/modules/FetchEmhash.cmake

Technically we should include it before using it.

[SYCL][CMake] Add missing include for FetchContent

---

sycl/include/sycl/detail/info_desc_helpers.hpp
sycl/include/sycl/device.hpp
sycl/include/sycl/info/info_desc.hpp
sycl/source/detail/device_impl.hpp
sycl/source/detail/kernel_info.hpp

There are helper function templates which are only used within `source/` directory, so they were moved in there to reduce the size and complexity of our public headers.
Some legacy dead code have been removed along the way as well.

[SYCL][NFC] Cleanup public headers

---

.github/workflows/sycl-rel-nightly-launch.yml

[CI] Add permissions to sycl-rel-nightly-launch workflow

---

unified-runtime/source/adapters/level_zero/kernel.cpp

zeKernelSetGroupSize needs to use the same L0 kernel handle as zeKernelSuggestMaxCooperativeGroupCount below.

[SYCL][UR][L0] Fix urKernelSuggestMaxCooperativeGroupCount

---

sycl/source/detail/queue_impl.cpp
sycl/source/detail/queue_impl.hpp
sycl/source/detail/scheduler/graph_builder.cpp
sycl/source/detail/scheduler/scheduler.cpp
sycl/source/detail/scheduler/scheduler.hpp
sycl/source/handler.cpp

Part of the ongoing refactoring to prefer raw ptr/ref for SYCL RT objects by default with explicit `shared_from_this` when lifetimes need to be extended.

[NFC][SYCL] Pass `context_impl` by raw ptr/ref in `scheduler.hpp`

---

sycl/source/detail/device_image_impl.hpp

Part of the ongoing refactoring to prefer raw ptr/ref for SYCL RT objects by default with explicit `shared_from_this` when lifetimes need to be extended.

[NFC][SYCL] Pass `context_impl` by raw ptr/ref in `device_image_impl.hpp`

---

clang/lib/Driver/ToolChains/Cuda.cpp
clang/test/Driver/sycl-nvptx-id-queries-fit-in-int.cpp
libclc/libspirv/lib/ptx-nvidiacl/workitem/get_global_id.cl

The NVPTX target was unable to properly optimize the global ID query, despite the user specifying the -fsycl-id-queries-fit-in-int flag.
This is because, once linked, the compiler sees the global ID builtin as (i64 add (mul (i64 zext i32 A), (i64 zext i32 B), (i64 zext i32 C))). Despite knowing that each of A, B and C are 32-bit values, and the final result fits in a 32-bit value, it is not legal to replace this sequence with (i64 zext (add i32 (mul i32 A, B), C)), which is the ideal code here.
The solution to this problem is a new opt-in 'reflection' in the NVPTX implementation of the global ID builtin, which selects a more optimal version. The driver enables this reflection only when the user passes -fsycl-id-queries-fit-in-int.

[SYCL][NVPTX] Optimize ID queries when they fit in int

---

sycl/doc/design/SYCLBINDesign.md

The correct test is already there: https://github.com/intel/llvm/blob/253228255b8c56bc5d4d8919a2020bcc7847f1ac/clang/test/Driver/fsyclbin.cpp#L8-L14

[SYCL][Doc] Specify usage of `-fsyclbin` and `-fsycl-device-only` together

---

libdevice/crt_wrapper.cpp
sycl/test-e2e/DeviceLib/rand_test.cpp
sycl/test/e2e_test_requirements/no-unsupported-without-info.cpp

This enables building rand for CUDA and HIP and enables the test.

[SYCL] Enable rand with CUDA and HIP

---

sycl/source/detail/cg.hpp
sycl/source/detail/graph_impl.hpp
sycl/source/detail/queue_impl.hpp
sycl/source/detail/scheduler/commands.cpp
sycl/source/detail/scheduler/commands.hpp
sycl/source/detail/scheduler/graph_builder.cpp
sycl/source/handler.cpp
sycl/unittests/buffer/BufferReleaseBase.hpp
sycl/unittests/scheduler/BlockedCommands.cpp
sycl/unittests/scheduler/FailedCommands.cpp
sycl/unittests/scheduler/GraphCleanup.cpp
sycl/unittests/scheduler/LeafLimit.cpp
sycl/unittests/scheduler/LeafLimitDiffContexts.cpp
sycl/unittests/scheduler/LeavesCollection.cpp
sycl/unittests/scheduler/MemObjCommandCleanup.cpp
sycl/unittests/scheduler/QueueFlushing.cpp
sycl/unittests/scheduler/SchedulerTestUtils.hpp

Continuation of the refactoring efforts in
https://github.com/intel/llvm/pull/18715
https://github.com/intel/llvm/pull/18748
https://github.com/intel/llvm/pull/18830
https://github.com/intel/llvm/pull/18907
https://github.com/intel/llvm/pull/18983

[NFC][SYCL] Pass `queue_impl` by raw ptr in `commands.hpp`

---

unified-runtime/source/adapters/level_zero/v2/command_buffer.cpp
unified-runtime/source/adapters/level_zero/v2/command_buffer.hpp
unified-runtime/source/adapters/level_zero/v2/command_list_manager.cpp
unified-runtime/source/adapters/level_zero/v2/command_list_manager.hpp
unified-runtime/source/adapters/level_zero/v2/queue_immediate_in_order.cpp
unified-runtime/source/adapters/level_zero/v2/queue_immediate_in_order.hpp

When releasing executionEvent in the commandBuffer we need to also retain the queue. Otherwise event->release() in commandBuffer's destructor might attempt to release the event to an event pool that has already been destroyed.
Also, make sure eventPool is destroyed after commandListManager to avoid any issues with events owned by the commandListManager and move context retain/release from commandListManager to queue/command_buffer.
The implementation of commandListManager marked move ctor and assignment operator as defaulted which was wrong - the implementation would have to account for context and device retain/release calls. To avoid this, move the logic to queue/commandBuffer which can have move ctors/assignments operators removed.

[SYCL][UR][L0 v2] Fix issues with event lifetime

---

llvm/lib/SYCLLowerIR/LowerWGScope.cpp
llvm/test/SYCLLowerIR/convergent_ptr_size_in_addrspace.ll

In LowerWGScope pass, getSizeTTy is used as return type of local id functions. We should use pointer size in global address space, to ensure size_t is sufficient to represent the global range.

[SYCL][LowerWGScope] Fix getSizeTTy to use pointer size in global address space

---

sycl/source/detail/helpers.hpp
sycl/source/detail/memory_manager.hpp
sycl/source/enqueue_functions.cpp
sycl/source/queue.cpp
sycl/unittests/Extensions/USMMemcpy2D.cpp
sycl/unittests/program_manager/arg_mask/EliminatedArgMask.cpp

Continuation of the refactoring efforts in
https://github.com/intel/llvm/pull/18715
https://github.com/intel/llvm/pull/18748
https://github.com/intel/llvm/pull/18830
https://github.com/intel/llvm/pull/18907
https://github.com/intel/llvm/pull/18983

[NFC][SYCL] Pass `queue_impl` by raw ptr/ref in misc files

---

libdevice/include/group_utils.hpp
libdevice/sanitizer/tsan_rtl.cpp

We selected up to 4 work items in each work group to do detection, the whole number of selected work items no more than kThreadSlotCount.

[DevTSAN] Refine thread mapping algorithm for better performance

---

clang/lib/Driver/OffloadBundler.cpp
clang/test/Driver/clang-offload-bundler-skip-for-symtbl.c
clang/test/Driver/clang-offload-bundler-skip-for-symtbl.c.ll
compiler-rt/cmake/builtin-config-ix.cmake
unified-runtime/source/loader/layers/sanitizer/ur_sanitizer_layer.cpp

Cherry-pick commits that reached the internal branch between intel/llvm cutoff and release branch pulldown.

[sycl-rel] Cherry-pick sanitizer patches

---

sycl/doc/extensions/supported/sycl_ext_intel_device_info.md
unified-runtime/source/adapters/cuda/CMakeLists.txt
unified-runtime/source/adapters/cuda/common.cpp
unified-runtime/source/adapters/cuda/common.hpp
unified-runtime/source/adapters/cuda/device.cpp
unified-runtime/source/adapters/cuda/device.hpp
unified-runtime/test/adapters/cuda/CMakeLists.txt
unified-runtime/test/conformance/device/urDeviceGetInfo.cpp

Cherry-pick commits that reached the internal branch between intel/llvm cutoff and release branch pulldown.

[sycl-rel] Cherry-pick patches for sycl_ext_intel_device_info

---

sycl/test-e2e/Graph/Explicit/interop-level-zero-launch-kernel.cpp
sycl/test-e2e/Graph/Explicit/memadvise.cpp
sycl/test-e2e/Graph/Explicit/opencl_local_acc.cpp
sycl/test-e2e/Graph/Explicit/prefetch.cpp
sycl/test-e2e/Graph/Explicit/raw_kernel_arg.cpp
sycl/test-e2e/Graph/Explicit/spec_constants_handler_api.cpp
sycl/test-e2e/Graph/Explicit/spec_constants_kernel_bundle_api.cpp
sycl/test-e2e/Graph/RecordReplay/barrier_multi_graph.cpp
sycl/test-e2e/Graph/RecordReplay/interop-level-zero-get-native-mem.cpp
sycl/test-e2e/Graph/RecordReplay/interop-level-zero-launch-kernel.cpp
sycl/test-e2e/Graph/RecordReplay/memadvise.cpp
sycl/test-e2e/Graph/RecordReplay/opencl_local_acc.cpp
sycl/test-e2e/Graph/RecordReplay/prefetch.cpp
sycl/test-e2e/Graph/RecordReplay/raw_kernel_arg.cpp
sycl/test-e2e/Graph/RecordReplay/spec_constants_handler_api.cpp
sycl/test-e2e/Graph/RecordReplay/spec_constants_kernel_bundle_api.cpp

As resported in https://github.com/intel/llvm/issues/19034 these tests have started failing in CI which is disruptive.
Disable them until they can be investigated and fixed

[SYCL][Graph][L0 V2] Disable failing test in CI

---

clang/lib/Basic/Targets.cpp
clang/lib/Basic/Targets/SPIR.h
clang/test/CodeGenSYCL/kernel-arg-accessor-pointer.cpp
clang/test/Preprocessor/sycl-macro-target-specific.cpp

Add TargetInfo for MSVC ARM64 host with SPIR64 or SPIRV64 device target.

[SYCL][Clang] Add ARM64_SPIRV64 and ARM64SPIR64 target info

---

devops/scripts/benchmarks/benches/compute.py

- Bump compute-benchmarks git_hash
- Add definition for FinalizeGraph benchmark in compute.py

[CI] Add graph finalize benchmark from compute-benchmarks

---

unified-runtime/source/adapters/cuda/enqueue.cpp
unified-runtime/test/conformance/enqueue/urEnqueueMemBufferMap.cpp

Buffers mapped with `UR_MAP_FLAG_WRITE_INVALIDATE_REGION` need to copy back to the buffer's device memory when unmapped. The HIP adapter was already doing this, seems like an accidental omission in the CUDA adapter.

[UR][CUDA] Fix unmap of buffer WRITE_INVALIDATE_REGION mappings

---

sycl/test-e2e/Matrix/lit.local.cfg

arch-intel_gpu_pvc is not a part of available_features when the lit.local.cfg file is executed. This led
to Matrix tests not being skiped on PVC for V2 as
expected.
Fix this by parsing config.sycl_dev_features, similarly to MemorySanitizer/lit.local.cfg

[E2E] fix check in Matrix/lit.local.cfg

---

unified-runtime/source/common/linux/ur_lib_loader.cpp

Found when enabled with `UR_USE_ASAN`.

[UR] fix a logger invocation error

---

unified-runtime/source/adapters/native_cpu/common.hpp
unified-runtime/source/adapters/native_cpu/kernel.hpp
unified-runtime/source/adapters/native_cpu/memory.hpp

For parameters, we were inferring a suitable alignment from the requested size, but for global and local memory we were not doing the same.
Ideally we would keep track of what alignment we need, but UR does not expose this information to us so assume the worst.

[SYCL][NativeCPU] Fix alignment of global and local memory.

---

sycl/include/sycl/multi_ptr.hpp
sycl/test/regression/multiptr-prefetch.cpp

The regression was introduced in intel/llvm#18839 and the error looks like:
```
/include/sycl/multi_ptr.hpp:397:5: error: no matching function for call to '__spirv_ocl_prefetch'
397 |     __spirv_ocl_prefetch(reinterpret_cast<ptr_t>(get_decorated()), NumBytes);
/include/sycl/multi_ptr.hpp:397:5: note: candidate function not viable: no known conversion from 'ptr_t' (aka 'const __global char *') to 'const __global signed char *' for 1st argument
397 |     __spirv_ocl_prefetch(reinterpret_cast<ptr_t>(get_decorated()), NumBytes);
```
We previously switched to use `__spirv_ocl_prefetch` that is automatically defined by the compiler instead of having its forward-declaration in our headers. However, compiler-provided declaration does not define an overload for plain `char` for some reason. …

[SYCL] Fix `multi_ptr::prefetch` regression

---

unified-runtime/source/adapters/opencl/context.hpp

`ur_context_handle_t` was incrementing the adapter reference count on
construction and decrementing it on destruction. This is pointless
because the adapter will always be valid if the context is.

[UR][OpenCL] Don't hold a reference to the adapter in `context`

---

sycl/test-e2e/NonUniformGroups/ballot_group.cpp
sycl/test-e2e/NonUniformGroups/ballot_group_algorithms.cpp
sycl/test-e2e/NonUniformGroups/fixed_size_group.cpp
sycl/test-e2e/NonUniformGroups/fixed_size_group_algorithms.cpp
sycl/test-e2e/NonUniformGroups/opportunistic_group.cpp
sycl/test-e2e/NonUniformGroups/opportunistic_group_algorithms.cpp
sycl/test-e2e/NonUniformGroups/tangle_group.cpp
sycl/test-e2e/NonUniformGroups/tangle_group_algorithms.cpp

A number of e2e tests use `opencl-aot` raw in their `RUN:` commands, this causes tests to fail when the tool is not present on the `PATH`. This patch adds `REQUIRES: opencl-aot` to avoid those test failures.

[SYCL][E2E] Add REQUIRES: opencl-aot to tests

---

sycl/source/detail/kernel_program_cache.hpp
sycl/unittests/kernel-and-program/OutOfResources.cpp

The runtime tries to build a kernel again if compilation fails. But if UR returns a memory error the attempt counter was not compared against the maximum number of attempts, so the compiler was continuously called and eventually the loop counter would have overflowed.

[SYCL] Avoid infinite loop when kernel fails to compile with memory error

---

clang/lib/CodeGen/TargetInfo.cpp
clang/test/CodeGenSYCL/sycl-device-module-flag.cpp
clang/test/CodeGenSYCL/unique_stable_name_windows_diff.cpp

We had this previously, but I refactored it upstream again and we lost it.
Also I updated some tests that have `-fsycl-device-only` but no triple, and we want that case to assert.
Also I fixed the stable name test to do the same check using native cpu, and also fix it to actually check the `WIN:` prefix which it wasn't doing before.

fix native cpu and some tests

---

sycl/unittests/Extensions/RootGroup.cpp

Changes the `MockDeviceImage` and `MockDeviceImageArray` to static variables so that they're not created in each test case. Relates to #19068 and #19074. Fixes #18892.

[SYCL] Fix lifetime bug in root group unit tests

---

sycl/test-e2e/FreeFunctionKernels/test-plan.md

This PR removes `sampled_image_accessor` and unsampled_image_accessor from planned test regarding structs that containing special types such as  `accessor` and `local_accessor`.
It's fix because it was not removed in previous PR: https://github.com/intel/llvm/pull/18994

[SYCL][NFC]  Remove `sampled_image_accessor` and `unsampled_image_accessor` from test plan for free function kernels extension

---

unified-runtime/source/adapters/cuda/device.cpp
unified-runtime/source/adapters/hip/device.cpp
unified-runtime/source/adapters/level_zero/device.cpp
unified-runtime/source/adapters/native_cpu/device.cpp
unified-runtime/source/adapters/opencl/device.cpp
unified-runtime/source/ur/ur.hpp

This query isn't accessible publicly, removing it has not caused any test failures.

[UR] Remove unused UR_EXT_DEVICE_INFO_OPENCL_C_VERSION

---

sycl/source/detail/context_impl.cpp
sycl/source/detail/device_global_map.hpp
sycl/source/detail/program_manager/program_manager.cpp
sycl/source/detail/program_manager/program_manager.hpp
sycl/unittests/program_manager/Cleanup.cpp

This commit moves the implementation and protection of the device_global variable registration entries into a separate structure for cleaner separation. This should make it simpler to let kernel_bundle manage lifetime and isolate device_global variables for SYCLBIN in a future patch.

[SYCL][NFCI] Move device_global map into separate structure

---

sycl/test-e2e/FreeFunctionKernels/address_test.cpp

The `--save-temps` flag seems to have been forgotten in a test when doing local debugging. Its functionality is not used in the test at all. This PR removes it.

[SYCL][E2E] Remove unused command line option from test

---

sycl/source/detail/scheduler/commands.cpp
sycl/source/detail/scheduler/commands.hpp
sycl/source/detail/scheduler/graph_builder.cpp

Continuation of the refactoring in
https://github.com/intel/llvm/pull/18795
https://github.com/intel/llvm/pull/18877
https://github.com/intel/llvm/pull/18966
https://github.com/intel/llvm/pull/18979
https://github.com/intel/llvm/pull/18980
https://github.com/intel/llvm/pull/18981
https://github.com/intel/llvm/pull/19007
https://github.com/intel/llvm/pull/19030

[NFC][SYCL] Return raw `context_impl *` from `Command::getWorkerContext`

---

sycl/source/backend.cpp
sycl/source/detail/graph_impl.cpp
sycl/source/detail/queue_impl.hpp
sycl/source/detail/scheduler/graph_builder.cpp
sycl/source/detail/sycl_mem_obj_i.hpp
sycl/source/detail/sycl_mem_obj_t.hpp
sycl/source/queue.cpp
sycl/unittests/scheduler/HostTaskAndBarrier.cpp
sycl/unittests/scheduler/LinkedAllocaDependencies.cpp

Splitting into two PRs would result in unnecessary temporarily adjustments and merge conflicts later on between these changes, so perform in a single PR. They are both small enough anyway.
Continuation of the refactoring in
https://github.com/intel/llvm/pull/18795
https://github.com/intel/llvm/pull/18877
https://github.com/intel/llvm/pull/18966
https://github.com/intel/llvm/pull/18979
https://github.com/intel/llvm/pull/18980
https://github.com/intel/llvm/pull/18981
https://github.com/intel/llvm/pull/19007
https://github.com/intel/llvm/pull/19030
https://github.com/intel/llvm/pull/19123

[NFC][SYCL] Raw `context_impl` in `getInteropContext` and `queue_impl` ctor

---

sycl/test-e2e/FreeFunctionKernels/address_test.cpp
sycl/test-e2e/FreeFunctionKernels/free_function_kernels_as_device_host_functions.cpp

In follow up to an earlier PR, this PR removes the `--save-temps` option from 2 E2E tests where it is unused and causing errors in certain QA testing configurations. It is probably a remnant of local debugging.

[SYCL][E2E] Remove unused command line arguments from tests

---

devops/dependencies.json

Reverts intel/llvm#19107
@igchor found it's randomly crashing, we're working with Neil.

Revert "[GHA] Uplift Linux GPU RT version to 25.18.33578.6"

---

sycl/source/detail/graph/graph_impl.hpp

Fixes post-commit windows CI failure introduced by #19045

[SYCL] [Graph] Remove unnecesary SYCL_EXPORT

---

sycl/source/detail/sampler_impl.cpp
sycl/source/detail/sampler_impl.hpp
sycl/source/detail/scheduler/commands.cpp
sycl/source/detail/scheduler/commands.hpp
sycl/source/sampler.cpp

`SetArgBasedOnType` argument is only used to pass to the `sampler_impl` ctor so update it.
`getCGKernelInfo` is only called in a function that also calls `sampler_impl` ctor so updating its signuature allows to update that caller's local `ContextImpl` variable, so makes sense to do as part of this PR as well.
Continuation of the refactoring in
https://github.com/intel/llvm/pull/18795
https://github.com/intel/llvm/pull/18877
https://github.com/intel/llvm/pull/18966
https://github.com/intel/llvm/pull/18979
https://github.com/intel/llvm/pull/18980
https://github.com/intel/llvm/pull/18981
https://github.com/intel/llvm/pull/19007
https://github.com/intel/llvm/pull/19030
https://github.com/intel/llvm/pull/19123
https://github.com/intel/llvm/pull/19126

[NFC][SYCL] Use `context_impl &` in `sampler_impl` ctor and near it

---

sycl/source/detail/platform_impl.cpp
sycl/source/detail/platform_impl.hpp
sycl/source/detail/queue_impl.hpp
sycl/source/platform.cpp

Noticed this code as part of the ongoing refactoring to prefer raw ptrs/refs for SYCL RT `*_impl` objects. The usage of this API in `queue_impl` doesn't need to go through user-visible SYCL objects, so move the implementation and use the internal interfrace in `queue_impl` and delegate `platform::khr_get_default_context` to `platform_impl`.

[NFC][SYCL] Move `platform::khr_get_default_context` impl to `platform_impl.cpp`

---

sycl/test-e2e/KernelCompiler/opencl.cpp
sycl/test-e2e/KernelCompiler/opencl_cache.cpp

breaking opencl kernel_compiler test up to not hit timeouts when building `-O0`

[SYCL][E2E] Minor OpenCL KernelCompiler Test Reorg

---

unified-runtime/tools/urinfo/urinfo.cpp

- Fix to urinfo to properly call release of adapters otherwise crucial teardown calls for adapters are missing. This was causing issues in UR only builds with adapters like L0 which have cleanup calls in the Adapter Release.

[UR] Fix urinfo to correctly release Adapters before loader teardown

---

devops/scripts/benchmarks/options.py

Results look OK:
https://oneapi-src.github.io/unified-runtime/performance/?tags=L0&runs=Baseline_BMG_L0v2%2C25_22_8_BMG_L0v2
https://oneapi-src.github.io/unified-runtime/performance/?tags=L0&runs=Baseline_PVC_L0v2%2C25_22_8_PVC_L0v2
There is a very slight regression in SubmitKernel In Order with completion:
But it looks like it's simply a case of an optimization being reverted.

[CI][Benchmarks] update compute runtime

---

sycl/include/sycl/handler.hpp
sycl/source/detail/async_alloc.cpp
sycl/source/detail/backend_impl.hpp
sycl/source/detail/bindless_images.cpp
sycl/source/detail/device_image_impl.hpp
sycl/source/detail/event_impl.hpp
sycl/source/detail/graph/graph_impl.hpp
sycl/source/detail/handler_impl.hpp
sycl/source/detail/helpers.cpp
sycl/source/detail/kernel_impl.hpp
sycl/source/detail/queue_impl.cpp
sycl/source/detail/scheduler/commands.cpp
sycl/source/handler.cpp

Subsequently, use `getContextImpl` instead of `getContextImplPtr` when possible.
Continuation of the refactoring in
https://github.com/intel/llvm/pull/18795
https://github.com/intel/llvm/pull/18877
https://github.com/intel/llvm/pull/18966
https://github.com/intel/llvm/pull/18979
https://github.com/intel/llvm/pull/18980
https://github.com/intel/llvm/pull/18981
https://github.com/intel/llvm/pull/19007
https://github.com/intel/llvm/pull/19030
https://github.com/intel/llvm/pull/19123
https://github.com/intel/llvm/pull/19126

[NFC][SYCL] Prefer `context_impl &` as locals/temporaries

---

sycl/source/detail/queue_impl.cpp

This shortens the critical section for in-order and out-of-order cases and avoids taking the lock entirely is MNoEventMode is set.

[SYCL] optimize wait() for in-order queue

---

llvm/lib/SYCLNativeCPUUtils/PrepareSYCLNativeCPU.cpp

This fixes LLVMIntrinsicLowering/intrinsic_cmp.cpp with -mavx.
Target attributes can affect the ABI, and the subkernel and kernel need to agree on the ABI in order for the call to work.

[SYCL][NativeCPU] Set target attrs for subkernels.

---

sycl/include/sycl/detail/common.hpp
sycl/include/sycl/vector.hpp

`vec_base` ctor already uses a private helper to pass `std::index_sequence`, no reason to go through another such helper.

[NFC][SYCL] Drop `RepeatValue` helper

---

clang/test/Driver/cuda-nvptx-target.cpp
clang/test/Driver/sycl-libspirv-toolchain.cpp
clang/test/Driver/sycl-offload-nvptx.cpp

* **PR #19130 (THIS ONE)**
* PR #19131
* PR #19134
* PR #19135
* PR #19136
In the next commits I'd like to refactor and fix SYCL libspirv linking.
This adds a few tests to cover the current behavior. Some of it is
buggy, and not consistent between NVPTX and AMDGPU, it will be improved
in the next commits.

[SYCL][Driver] Improve SYCL libspirv linking test coverage (NFC)

---

sycl/include/sycl/ext/oneapi/properties/properties.hpp
sycl/include/sycl/ext/oneapi/properties/property.hpp
sycl/test/regression/grf_properties_wa.cpp

Due to a bug in the compiler, certain conditions give false compiler errors for return types of constexpr lambdas. This commit implements workarounds for cases that affect the SYCL headers when using properties.

[SYCL] Add workaround for undeterminable constexpr lambda return

---

sycl/include/sycl/ext/oneapi/experimental/graph/modifiable_graph.hpp
sycl/source/detail/graph/graph_impl.cpp
sycl/source/detail/graph/node_impl.cpp
sycl/test-e2e/Graph/AsyncAlloc/Inputs/async_alloc_device_memory_reuse_zero_init.cpp

Fixes https://github.com/intel/llvm/issues/19177

[SYCL] [Graph] Fix print_graph

---

clang/lib/Driver/Driver.cpp
clang/lib/Driver/ToolChains/Cuda.cpp
clang/lib/Driver/ToolChains/HIPAMD.cpp
clang/lib/Driver/ToolChains/SYCL.cpp
clang/lib/Driver/ToolChains/SYCL.h
clang/test/Driver/sycl-libspirv-toolchain.cpp

* PR #19130
* **PR #19131 (THIS ONE)**
* PR #19134
* PR #19135
* PR #19136
Move the logic for finding and linking libspirv into SYCLInstallationDetector.
This code was basically duplicated between the CUDA and HIP toolchains,
and was also present in the Driver sources.
This is NFC, aside from the fact that the code in the HIP toolchain
lacked the special handling for the `-###` driver option present in the
other two places.

[SYCL][Driver] Deduplicate libspirv logic

---

devops/dependencies.json

We don't use this and it's all done manually, and JSON doesn't support comments, so just remove it to prevent confusion.
The `tbb` and `oclcpu` ones aren't used either, but it's updated by the team to have the download link we use to manually install, so keep those.
Issue: https://github.com/intel/llvm/issues/19192

[CI][NFC] Remove Windows driver listing in dependencies.json

---

sycl/source/detail/graph/graph_impl.cpp
unified-runtime/source/adapters/level_zero/command_buffer.cpp

Small fixes flagged by static analyzer:
- Added missing `UR_CALL` and `UR_CALL_NOCHECK` to `ur::level_zero` function calls in Command Buffer,
- Removed one redundant copy of `shared_ptr`

[SYCL] [UR] [Graphs] Added missing UR_CALLs

---

clang/lib/Driver/ToolChains/SYCL.cpp
clang/test/Driver/sycl-libspirv-toolchain.cpp

* PR #19130
* PR #19131
* **PR #19134 (THIS ONE)**
* PR #19135
* PR #19136
... instead of the resource directory. This matches the behaviour of
SYCL device libraries. The resource directory has nothing to do with
libspirv, and it might be changed by the `-resource-dir` option, which
would lead us to not find it.

[SYCL][Driver] Base libspirv path on sycl install candidates

---

sycl/unittests/program_manager/BuildLog.cpp
sycl/unittests/program_manager/DynamicLinking/DynamicLinking.cpp
sycl/unittests/program_manager/arg_mask/EliminatedArgMask.cpp

[NFC][SYCL] Prepare `unittests/program_manager` for `getSyclObjImpl` to return raw ref

---

sycl/unittests/kernel-and-program/Cache.cpp
sycl/unittests/kernel-and-program/InMemCacheEviction.cpp
sycl/unittests/kernel-and-program/MultipleDevsCache.cpp
sycl/unittests/kernel-and-program/OutOfResources.cpp

[NFC][SYCL] Prepare `unittests/kernel-and-program` for `getSyclObjImpl` to return raw ref

---

sycl/unittests/scheduler/BarrierDependencies.cpp
sycl/unittests/scheduler/CommandsWaitForEvents.cpp
sycl/unittests/scheduler/EnqueueWithDependsOnDeps.cpp
sycl/unittests/scheduler/GraphCleanup.cpp
sycl/unittests/scheduler/HostTaskAndBarrier.cpp
sycl/unittests/scheduler/LeafLimit.cpp
sycl/unittests/scheduler/LeafLimitDiffContexts.cpp
sycl/unittests/scheduler/MemObjCommandCleanup.cpp
sycl/unittests/scheduler/SchedulerTestUtils.hpp

[NFC][SYCL] Prepare `unittests/scheduler` for `getSyclObjImpl` to return raw ref

---

sycl/source/detail/graph/graph_impl.cpp
sycl/source/detail/graph/graph_impl.hpp
sycl/source/detail/graph/node_impl.hpp
sycl/unittests/Extensions/CommandGraph/Barrier.cpp
sycl/unittests/Extensions/CommandGraph/CommandGraph.cpp
sycl/unittests/Extensions/CommandGraph/Common.hpp
sycl/unittests/Extensions/CommandGraph/Exceptions.cpp
sycl/unittests/Extensions/CommandGraph/InOrderQueue.cpp
sycl/unittests/Extensions/CommandGraph/MultiThreaded.cpp
sycl/unittests/Extensions/CommandGraph/Queries.cpp
sycl/unittests/Extensions/CommandGraph/Subgraph.cpp
sycl/unittests/Extensions/CommandGraph/TopologicalSort.cpp

I also did `s/sycl::detail::getSyclObjImpl/getSyclObjImpl/g` here to increase readability and to make it simpler to perform the future patch by simple `sed` (and avoid multiline changes).
This PR originated in `unittests/Extensions/CommandGraph`, but I had to modify `isSimilar` and `hasSimilarStructure` in the implementation itself too.

[NFC][SYCL][Graph] Prepare for getSyclObjImpl to return raw ref

---

sycl/source/detail/kernel_bundle_impl.hpp

[NFC][SYCL] Prepare `kernel_bundle_impl.hpp` for `getSyclObjImpl` to return raw ref

---

unified-runtime/source/loader/layers/sanitizer/sanitizer_common/sanitizer_utils.cpp

Add some parameter checks for `PrintUrBuildLogIfError()` to avoid calling underlying API with invalid parameters.

[DeviceSanitizer] Add check for PrintUrBuildLogIfError()

---

sycl/source/detail/async_alloc.cpp
sycl/source/detail/graph/memory_pool.cpp
sycl/source/detail/graph/memory_pool.hpp

[NFC][SYCL] Prepare `memory_pool`/`async_alloc` for `getSyclObjImpl` to return raw ref

---

sycl/source/detail/bindless_images.cpp

I've updated all the known uses when it was introduced in https://github.com/intel/llvm/pull/18168 but then
https://github.com/intel/llvm/pull/17865 added code that didn't use the helper.

[NFC][SYCL] Use `get_ur_handles` in `bindless_images.cpp`

---

clang/test/SemaSYCL/intel-fpga-loops.cpp

As in title. Original patch by jinsong.ji@intel.com

[NFC] Update intel-fpga-loops after 0ff95c9

---

unified-runtime/source/adapters/level_zero/device.hpp
unified-runtime/test/conformance/context/urContextCreate.cpp

This use case seems to be allowed. For example, according to: https://intel.github.io/llvm/MultiTileCardWithLevelZero.html#context "Both root-devices and sub-devices can be within single context, but they all should be of the same SYCL platform."
Before change CollectDevicesAndSubDevices was resulting in duplicate devices being returned which leads to an error in https://github.com/intel/llvm/blob/6af08fe9c6fd4dc8e433555646606898c71d92fb/unified-runtime/source/common/ur_pool_manager.hpp#L178-L179 because of the duplicate pool descriptors.

[UR] Fix creation of context with parent device and its sub-devices

---

sycl/source/detail/global_handler.cpp
sycl/source/detail/global_handler.hpp
sycl/unittests/helpers/MockDeviceImage.hpp

The implementation of mock images try to unload the images using __sycl_unregister_lib. However, this is a no-op on Windows under the assumption that shutdown will handle the images. This causes unittests, like RootGroup, to leave dead binaries in the program manager that subsequent test runs may pick up. This commit fixes this issue by having the mock image arrays forciby remove the images from the program manager instead.

[SYCL][Unittests] Fix unloading of mock images on Windows

---

clang/tools/clang-linker-wrapper/ClangLinkerWrapper.cpp
llvm/include/llvm/Object/SYCLBIN.h
llvm/lib/Object/SYCLBIN.cpp
llvm/lib/SYCLPostLink/ComputeModuleRuntimeInfo.cpp
llvm/test/tools/sycl-post-link/emit_kernel_names.ll
llvm/unittests/Object/SYCLBINTest.cpp
sycl/doc/design/PropertySets.md
sycl/source/detail/syclbin.cpp
sycl/test-e2e/SYCLBIN/basic_executable.cpp
sycl/test-e2e/SYCLBIN/basic_input.cpp
sycl/test-e2e/SYCLBIN/basic_object.cpp
sycl/test-e2e/SYCLBIN/dae_executable.cpp
sycl/test-e2e/SYCLBIN/dae_input.cpp
sycl/test-e2e/SYCLBIN/dae_object.cpp
sycl/test-e2e/SYCLBIN/dg_executable.cpp
sycl/test-e2e/SYCLBIN/dg_input.cpp
sycl/test-e2e/SYCLBIN/dg_object.cpp
sycl/test-e2e/SYCLBIN/optional_kernel_features_executable.cpp
sycl/test-e2e/SYCLBIN/optional_kernel_features_input.cpp
sycl/test-e2e/SYCLBIN/optional_kernel_features_object.cpp
sycl/test/syclbin/simple_kernel.cpp

This commit makes the following changes to make SYCLBINs work for CUDA and HIP:
* Fixes kernel detection when generating kernel name property sets for PTX and AMDGPU IR binaries.
* Adds target triple to the metadata for native device code images.
* Generates target triple for IR modules, as required by the property set metadata design.
* Adds detection of target spec in native device code images based on the new target information.
This allows us to enable most SYCLBIN tests on HIP and CUDA.

[SYCL] Fix SYCLBIN for CUDA and HIP targets

---

unified-runtime/include/ur_print.hpp
unified-runtime/scripts/templates/print.hpp.mako

ur_bool_t was being printed as a c-style string, which led to random characters in traces where boolean values should have been.

[UR] fix ur_bool_t printing

---

libclc/opencl/include/clc/opencl/as_type.h
libclc/opencl/include/clc/opencl/convert.h

These don't appear to be necessary, are incorrectly named, and incorrectly placed as they appear before the copyright.
If they are in fact necessary it would be best done upstream instead.

[libclc] Remove downstream include guards. NFCI.

---

sycl/include/sycl/handler.hpp
sycl/source/handler.cpp

This function is no longer used in preview breaking mode.

[SYCL][NFC] Remove overload of saveCodeLoc under ABI-break flag

---

sycl/source/backend.cpp
sycl/source/backend/level_zero.cpp
sycl/source/context.cpp
sycl/source/detail/adapter_impl.hpp
sycl/source/detail/context_impl.cpp
sycl/source/detail/context_impl.hpp
sycl/source/detail/device_global_map_entry.cpp
sycl/source/detail/event_impl.cpp
sycl/source/detail/event_impl.hpp
sycl/source/detail/event_info.hpp
sycl/source/detail/memory_manager.cpp
sycl/source/detail/platform_impl.cpp
sycl/source/detail/platform_impl.hpp
sycl/source/detail/scheduler/commands.cpp
sycl/source/detail/ur.cpp
sycl/source/detail/ur.hpp
sycl/source/device.cpp
sycl/source/kernel.cpp
sycl/source/platform.cpp

It's a part of larger refactoring effort to pass adapter via reference instead of pointer everywhere in the codebase.
Follow-up of:
https://github.com/intel/llvm/pull/19186
https://github.com/intel/llvm/pull/19184
https://github.com/intel/llvm/pull/19187

[SYCL][NFC] Pass adapter by ref in ur::getAdapter and event:getAdapter

---

unified-runtime/source/adapters/level_zero/device.cpp

When NumDevices is not zero and when phDevice is null, the user cannot query the number of devices. This addresses that issue.

[UR][L0] urDevice when numdevices is not zero

---

devops/scripts/benchmarks/benches/benchdnn.py
devops/scripts/benchmarks/benches/compute.py
devops/scripts/benchmarks/benches/gromacs.py
devops/scripts/benchmarks/benches/llamacpp.py
devops/scripts/benchmarks/benches/syclbench.py
devops/scripts/benchmarks/benches/test.py
devops/scripts/benchmarks/benches/umf.py
devops/scripts/benchmarks/benches/velocity.py
devops/scripts/benchmarks/utils/result.py

This field is not used anywhere in scripts nor in the dashboard. It was merely saved in the results objects in run json files and copied into data.json making the file significantly bigger.

[Benchmarks] Remove stdout field from results

---

sycl/doc/PreprocessorMacros.md
sycl/include/sycl/sycl.hpp
sycl/test/warnings/no_fsycl_flag.cpp
sycl/tools/sycl-ls/CMakeLists.txt

To improve user experience.
Fixes https://github.com/intel/llvm/issues/12052

[SYCL][NFC] Throw warning when sycl.hpp is included without `-fsycl` flag.

---

sycl/source/detail/device_image_impl.hpp
sycl/source/detail/jit_compiler.hpp
sycl/source/detail/kernel_compiler/kernel_compiler_sycl.hpp

This fixes the compilation error if the JIT is disabled in the build as reported in #19291.

[SYCL] Fix compilation when JIT is disabled

---

sycl/source/detail/context_impl.cpp
sycl/source/detail/device_global_map_entry.cpp
sycl/source/detail/device_global_map_entry.hpp
sycl/source/detail/graph/graph_impl.cpp
sycl/source/detail/memory_manager.cpp
sycl/source/detail/queue_impl.cpp
sycl/source/detail/queue_impl.hpp
sycl/source/detail/scheduler/commands.cpp
sycl/source/detail/ur_utils.hpp
sycl/source/interop_handle.cpp

It's a part of larger refactoring effort to pass adapter via reference instead of pointer everywhere in the codebase.
Follow-up of:
https://github.com/intel/llvm/pull/19186
https://github.com/intel/llvm/pull/19184
https://github.com/intel/llvm/pull/19187
https://github.com/intel/llvm/pull/19202

[SYCL][NFC] Make queue::getAdapter() return adapter ref instead of ptr

---

sycl/unittests/CMakeLists.txt

After https://github.com/intel/llvm/pull/19279, `ninja check-sycl` produces hundreds of warning about including `sycl.hpp` without `-fsycl` flag."
This PR disables those warnings for unittests.

[SYCL][NFC] Disable sycl/sycl.hpp warning in unittests

---

sycl/source/detail/kernel_bundle_impl.hpp

The current implementation of link() only properly filters duplicates of the device_image_impl objects, but compiling the same device binary image twice may have yielded image impls that do not compare equal. Instead, we can compare the underlying binary images and only add owners once.

[SYCL] Fix link() duplicate image detection

---

sycl/cmake/modules/AddSYCLUnitTest.cmake

The SYCL unittests include the SYCL headers without using -fsycl. To avoid the new warning for cases that uses this include pattern, we override the warning by defining the
SYCL_DISABLE_FSYCL_SYCLHPP_WARNING preprocessor macro for all unittests.

[SYCL][Unittest] Disable SYCL header warning in unittests

---

sycl/test-e2e/ESIMD/mandelbrot/mandelbrot_spec.cpp

The GPU driver team recommended this change, the loss of accuracy causes it to fail, there is no real issue.

[SYCL][ESIMD][E2E] Disable fast math for mandelbrot_spec.cpp

---

.github/workflows/sycl-docs.yml

#19128 had an undocumented change https://github.com/intel/llvm/commit/3b04aeb7d1d4ad5bbe64fb257f4ca6e5284ec5d0#diff-e0c290ed8fe811027fdd5f6642d02a9f0e20e9982e0219cbc45da666b014534cR1180 that breaks previous configuration files. This PR fixes our benchmark dashboard configuration to adhere to this new change.

[CI] Fix data load failure in benchmark dashboard

---

sycl/test-e2e/ESIMD/mandelbrot/mandelbrot.cpp

Did this for the other mandeltest test, do it for this too.

[SYCL][ESIMD][E2E] Disable fast math for second mandelbrot test

---

clang/lib/Driver/ToolChains/SYCL.cpp

Originally, SYCLInstallationDetector just had a single constructor parameter D, and filled InstallationCandidates. In the process of upstreaming this, unused arguments HostTriple and Args were added, and InstallationCandidates was removed. Then, when the upstreamed version was pulled into DPC++, we ended up with two constructors, one which did fill InstallationCandidates and one which did not, for no reason.
Ideally, we would align with upstream and use that new constructor everywhere. However, we use SYCLInstallationDetector in places where do not have that information, we need to be able to construct a SYCLInstallationDetector from only a Driver, so using only the upstream constructor is not an option.
Using only the single-argument constructor is also not a good idea, as it makes …

[NFC] Fix SYCLInstallationDetector InstallationCandidates.

---

sycl/source/detail/error_handling/error_handling.cpp
sycl/source/detail/error_handling/error_handling.hpp
sycl/source/detail/kernel_impl.cpp
sycl/source/detail/kernel_impl.hpp
sycl/source/detail/kernel_info.hpp
sycl/source/detail/scheduler/commands.cpp

It's a part of larger refactoring effort to pass adapter via reference instead of pointer everywhere in the codebase.
Follow-up of:
https://github.com/intel/llvm/pull/19186
https://github.com/intel/llvm/pull/19184
https://github.com/intel/llvm/pull/19187
https://github.com/intel/llvm/pull/19202
https://github.com/intel/llvm/pull/19299
https://github.com/intel/llvm/pull/19312

[SYCL][NFC] Make `kernel_impl::getAdapter()` return by reference

---

libclc/cmake/modules/AddLibclc.cmake
libdevice/CMakeLists.txt
libdevice/cmake/modules/SYCLLibdevice.cmake

The libdevice project included a CMake file from libclc to complete some work. This is an undesirable link for several reasons.
For one, libclc is upstream and libdevice isn't. This means that it's easy to accidentally pull in changes from upstream that alter how libdevice is built. We can see this in the FOLDER property of the link_bc target, which was set to 'libclc/Device IR/Linking'. This would be confusing for any user building DPC++ in an IDE.
For two, this sharing of code also necessitated making downstream changes to libclc, which make maintenance more difficult. This can be seen in the RSP_DIR argument to link_bc, which was never set in libclc to anything other than the upstream value.
This commit therefore starts to sever this dependency by just copying over the two utility …

Start to reduce libdevice dependencies on libclc

---

clang/lib/Driver/Driver.cpp
clang/lib/Driver/ToolChains/SYCL.cpp
clang/test/Driver/sycl-native-cpu-fsycl.cpp

This matches what is done for CUDA and HIP.

[SYCL][NativeCPU] Add libclc at compile time.

---

devops/scripts/benchmarks/benches/umf.py

Fix wrong path to umf library when passing a path without a trailing slash:
`Warning: LD_LIBRARY_PATH component does not exist: /home/patrykka/unified-memory-framework/buildlib`
Example of a failing run: https://github.com/oneapi-src/unified-memory-framework/actions/runs/16023907732/job/45207108065

[Benchmarks] Fix umf library path

---

llvm/cmake/modules/AddSecurityFlags.cmake
unified-runtime/cmake/helpers.cmake

The problem here is that the macro is actually handled by glibc and value `3` isn't supported with older compiler/glibc combinations, causing warnings about the macro redefinition.
We still have to support older compilers/glibc and therefore two changes were made:
- UR skips setting their own `_FORTIFY_SOURCE` in favor of a global one if it is built as part of LLVM (i.e. not standalone)
- Before setting `_FORTIFY_SOURCE` globally we check the compiler and  fallback to value `2` for older gcc

[SYCL][CMAKE] Fix _FORTIFY_SOURCE=3

---

sycl/source/detail/graph/memory_pool.hpp
sycl/source/detail/graph/node_impl.hpp

Coverity suggested to add these to follow the rule-of-three (https://en.cppreference.com/w/cpp/language/rule_of_three.html)

[SYCL][NFC] Add user-defined destructor and assignment operator

---

.github/workflows/sycl-detect-changes.yml
.github/workflows/ur-build-offload.yml
.github/workflows/ur-precommit.yml

Add a new job that verifies that the offload adapter can be built.
It does not attempt to run any tests or detect any hardware.

[CI][UR][Offload] Add Offload build-only job

---

devops/scripts/benchmarks/main.py
devops/scripts/benchmarks/utils/utils.py

1. The `umf` benchmarks uses `GBench` to create a csv from the benhcmark's output. Mixing up `stdout` with `stderr` led to a resulting csv header resolvment to fail.
2. Fail the scripts also when any suite setup fails with `--exit-on-failure` option enabled
3. Abort scripts when no benchmarks are defined.
Don't allow for creating html and markdown files in case it's not a dry run and no benchmarks were properly set up.

[CI][Benchmarks] Fix umf benchmarks failures

---

sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp
sycl/test-e2e/ESIMD/thread_id_test.cpp

Same for sub device id API. The appropriate SPIR-V extension used for them previously is deprecated.

[SYCL][ESIMD] Make get_hw_thread_id to return 0

---

sycl/doc/extensions/proposed/sycl_ext_oneapi_free_function_kernels.asciidoc

Update links as the dependent extensions have been promoted to either "experimental" or "supported".

[SYCL][Doc] Fix links in free function kernel spec

---

libclc/cmake/modules/AddLibclc.cmake

The builtins need to be written to the LIBCLC_LIBRARY_OUTPUT_INTDIR in order for the tests to pass. This also cleans up the conflict resolutions.

[sycl-web] Correct conflict resolutions and output path.

---

clang/lib/Driver/ToolChains/SYCL.h

Having them in the comments seems unnecessary.

[NFC][Clang] Remove spurious forward slashes.

---

clang/lib/Driver/Driver.cpp

Remove useless variables HasSYCLTargetsOption, GpuInitHasErrors and
ShouldAddDefaultTriple.
This also flips the return value of initializeGpuArchMap to return
`true` when initiazation is successful.

[NFC][Driver] Simplify -fsycl-targets handling

---

clang/lib/Driver/Driver.cpp

Changed the logic from
```c++
if ( not NVPTX and not AMDGCN) {
if (Intel) {
// process Intel case
continue;
}
// process targets which are not Intel, NVPTX or AMDGCN
} else {
// process NVPTX and AMDGCN case
}
```
to more readable (in my opinion)
```c++
if (NVPTX or AMDGCN) {
// process NVPTX and AMDGCN case
} else if (Intel) {
// process Intel case
} else {
// process targets which are not Intel, NVPTX or AMDGCN
}
```
Inside NVPTX and AMDGCN branch replaced
```c++
auto it = find_if(...);
if (it == end)
...
```
to
```c++
if (none_of(...))
...
```

[NFC][Driver] Refactor SYCLTargetInfoList init.

---

sycl/test-e2e/AsyncAlloc/device/memory_pool.cpp
unified-runtime/source/adapters/level_zero/async_alloc.cpp
unified-runtime/source/adapters/level_zero/enqueued_pool.cpp
unified-runtime/source/adapters/level_zero/enqueued_pool.hpp
unified-runtime/source/adapters/level_zero/usm.cpp
unified-runtime/source/adapters/level_zero/usm.hpp
unified-runtime/source/adapters/level_zero/v2/usm.cpp
unified-runtime/source/adapters/level_zero/v2/usm.hpp
unified-runtime/test/conformance/exp_command_buffer/rect_write.cpp

Support pool query via urUSMPoolGetInfoExp for information about reserved or in-use memory and their peak sizes.
Fixes https://github.com/intel/llvm/issues/17772.

[UR][L0] Add pool statistics

---

clang/lib/Sema/SemaDeclCXX.cpp
clang/lib/Sema/SemaExpr.cpp

To allow all C++ features in constexpr contexts we need to track constexpr initializers of variables. The mentioned commit moved some code to handle consteval better but we need the code where it used to be since it is not only consteval that we care about.

[SYCL][clang] Fix after conflict with 6a99326

---

devops/scripts/benchmarks/compare.py

The introduction of logger to compare.py broke logging altogether: This PR fixes it.

[Benchmark] Fix logging in compare.py

---

unified-runtime/source/adapters/level_zero/program.cpp
unified-runtime/test/conformance/program/urMultiDeviceProgramCreateWithIL.cpp

The size of the value returned from UR_PROGRAM_INFO_BINARIES query was incorrect, we need to return the size of array of pointers (for each device associated with the program) according to doc:
https://oneapi-src.github.io/unified-runtime/core/api.html?highlight=urprogramgetinfo#ur-program-info-t
This bug was leading to crashes when using persistent cache in sycl in scenarios with multi-device context, newly added test emulates that scenario when we recreate program from the saved binary.

[UR][L0] Fix UR_PROGRAM_INFO_BINARIES query

---

.github/workflows/sycl-linux-precommit.yml

Only the Matrix team has committed to investigating failures on the IGC side. See discussion in https://github.com/intel/llvm/pull/18818

[CI] Only run Matrix tests for dev-igc

---

sycl/test/syclbin/input_files.cpp
sycl/tools/syclbin-dump/syclbin-dump.cpp

This commit fixes an issue with unhandled LLVM errors and prints additional information for some error-conditions in syclbin-dump.
Fixes https://github.com/intel/llvm/issues/19404

[SYCL] Fix error handling and add more failure info to syclbin-dump

---

.github/workflows/ur-precommit.yml

The packages it requires haven't been updated since the 3rd of July (as
of this commit), so disable for now.

[CI] Disable liboffload job

---

unified-runtime/source/adapters/offload/kernel.cpp
unified-runtime/source/adapters/offload/kernel.hpp

Recent liboffload changes have changed this interface a little

[UR][Offload] Update to use ol_symbol_handle_t

---

llvm/cmake/modules/AddSecurityFlags.cmake

We rely on CMake to set the right set of compliation and link flags to enable positition independent code and position independent execution.
Before this commit, necessary compliation flags were applied just fine, but link flags were missing. To get link flags, some extra CMake functions should be called.

[SYCL][CMake] Properly enable `-pie` hardening flag

---

llvm/test/Bitcode/invalid.test

The duplicate line accidentally appeared during conflict resolution in https://github.com/intel/llvm/commit/a03339b2c144e8b8c95a7a677da24f438c2e3056#diff-ace782300c94221dade4e5f02a303d4b47440f4d43b8f3915d15ce37a59f3cf9R2

[NFC] Remove extra line from the test

---

libclc/CMakeLists.txt
libclc/utils/CMakeLists.txt

It doesn't look as if we needed the extra link components for prepare_builtins.

[libclc] Reduce diff with upstream. NFC

---

buildbot/configure.py
llvm/cmake/modules/AddSecurityFlags.cmake
sycl/include/sycl/ext/oneapi/experimental/device_architecture.hpp
unified-runtime/cmake/helpers.cmake

This PR contains several cherry-picks and some unique changes which have not been applied to the `sycl` branch yet.
The intent of this PR is to enable as much (quickly) possible hardening flags to be in better compliance with our SDL requirements.
The main thing this PR is after are things like immediate bindings, fortify source, stack protection and `relro`.
The thing that this PR is **not** after are extra warning flags - some of them we can't apply globally because LLVM itself isn't warning free, some of them we can't apply even locally to SYCL RT because we haven't fixed corresponding warnings yet.
Patches which were cherry-picked from the `sycl` branch:
- [SYCL] Fix AddSecurityFlags having no side effects (https://github.com/intel/llvm/pull/17690)
- Patch-By: Alexey Sachkov …

[SYCL][CMake] Fix and apply hardening flags to `sycl-rel-6_2`

---

unified-runtime/source/adapters/level_zero/adapter.cpp

The change making L0 v2 adapter default for BMG broke handling of UR_ADAPTERS_FORCE_LOAD. Depending on the platform, urAdapterGet could return 0 available adapter even if force loadded.

[SYCL][UR][L0] Fix handling of UR_ADAPTERS_FORCE_LOAD

---

.github/workflows/email-check.yaml

fixes https://github.com/intel/llvm/issues/17675
Currently, in the workflow, we only check the email that was used for the latest commit in the PR. This email can differ from the email settings on the GH UI, from which PR will be authored, once we merge it.

[CI] Fix detecting usage of private emails

---

sycl/source/detail/context_impl.cpp
sycl/source/detail/context_impl.hpp
sycl/source/detail/device_image_impl.hpp
sycl/source/detail/device_impl.hpp
sycl/source/detail/helpers.hpp
sycl/source/detail/kernel_bundle_impl.hpp
sycl/source/detail/program_manager/program_manager.cpp
sycl/source/detail/program_manager/program_manager.hpp
sycl/source/kernel_bundle.cpp

https://github.com/intel/llvm/pull/18251 extended `device_impl`s' lifetimes until shutdown and https://github.com/intel/llvm/pull/18270 started to pass devices as raw pointers in some of the APIs.
This PR builds on top of that and extends usage of raw pointers/references/`device_range` as the devices are known to be alive and extra `std::shared_ptr`'s atomic increments aren't necessary and could be avoided.
Since we change the type of `device_image_impl::MDevices`, other APIs in that class and in `program_manager` don't need to operate in terms of `sycl::device` or `std::shared_ptr<device_impl>` and we can switch them to use `devices_range` instead. A small number of other modifications are caused by these APIs' changes and are necessary to keep the code buildable.
One extra change is the …

[NFCI][SYCL] Change `device_image_impl::MDevices` to store raw `device_impl *`

---

sycl/include/sycl/half_type.hpp

This is a patch in a series of fixing warnings emitted by `-Wconversion` flag which is necessary according to our SDL processes.

[SYCL][NFCI] Fix `-Wconversion` in `half` implementation

---

clang/lib/Driver/ToolChains/Clang.cpp
clang/lib/Driver/ToolChains/MSVC.cpp
clang/test/Driver/sycl-offload-old-model.c
clang/test/Driver/sycl-offload.c

The usage of `-fms-runtime-lib=val` will pull in the default libraries for MSVC linking as well as the dependent SYCL libraries when using the Linux based driver with the MSVC target triple.  There are special interactions with the --dependent-lib=msvcrtd library we have that control the inclusion of sycl.lib to prevent linktime problems.
Extend these behaviors to usage of `-fms-runtime-lib=dll_dbg`, preventing duplicate instances of the sycl.lib in the --dependent-lib usage as well as when performing the final link.

[Driver][SYCL] Update sycl lib linking with -fms-runtime-lib

---

sycl/source/detail/graph/graph_impl.cpp
sycl/source/detail/graph/node_impl.hpp
sycl/unittests/Extensions/CommandGraph/Barrier.cpp
sycl/unittests/Extensions/CommandGraph/CommandGraph.cpp
sycl/unittests/Extensions/CommandGraph/Exceptions.cpp
sycl/unittests/Extensions/CommandGraph/InOrderQueue.cpp
sycl/unittests/Extensions/CommandGraph/MultiThreaded.cpp
sycl/unittests/Extensions/CommandGraph/Subgraph.cpp

Continuation of https://github.com/intel/llvm/pull/19295 and https://github.com/intel/llvm/pull/19332.

[NFC][SYCL][Graph] Store raw `node_impl *` in `MPredecessors`/`MSuccessors`

---

unified-runtime/source/adapters/offload/device.cpp
unified-runtime/source/adapters/offload/program.cpp

Offload consumes both IL and binaries through the same entrypoint, so
there's no point in drawing a distinction.

[UR][Offload] Implement urProgramCreateWithIL

---

sycl/test-e2e/Graph/Update/independent_kernels_update.cpp
unified-runtime/source/adapters/cuda/command_buffer.cpp
unified-runtime/source/adapters/hip/command_buffer.cpp

- Fix issue where updating multiple nodes with the same UR kernel handle would give incorrect results due to arg caching.
- Add SYCL E2E test based on the example in the issue that reported this.
Addresses issue reported in #19450

[UR][CUDA][HIP] Fix command buffer update with shared kernel handles

---

unified-runtime/source/adapters/level_zero/adapter.cpp
unified-runtime/source/adapters/level_zero/common.cpp
unified-runtime/source/adapters/level_zero/v2/command_buffer.cpp

- catch potential exception in ~ur_exp_command_buffer_handle_t_
- move ZeUSMImport definition to adapter.cpp:
ZeUSMImport is used by global adapter constructor (on Windows).
It needs to be initialized before the global adapter.
According to Coverity:
The constructor of global object "GlobalAdapter" itself makes use
of global object "ZeUSMImport" defined in another compilation unit.
The order of construction is unspecified, so "GlobalAdapter" might
be created before "ZeUSMImport" is available.

[SYCL][UR][L0 v2] Coverity fixes

---

sycl/test-e2e/AsyncAlloc/device/async_alloc_from_default_pool.cpp
sycl/test-e2e/AsyncAlloc/device/async_alloc_from_pool.cpp
sycl/test-e2e/AsyncAlloc/device/async_alloc_zero_init.cpp
sycl/test-e2e/AsyncAlloc/device/memory_pool.cpp
sycl/test-e2e/AsyncAlloc/device/ooo_queue_async_alloc_from_pool.cpp
unified-runtime/source/adapters/level_zero/usm.cpp
unified-runtime/source/adapters/level_zero/v2/api.cpp
unified-runtime/source/adapters/level_zero/v2/usm.cpp
unified-runtime/source/adapters/level_zero/v2/usm.hpp

L0v2 adapter was marked as unsupported in some async alloc tests due to missing features.
Those tests were failing because of the missing functions: `urUSMPoolGetInfoExp`, `urUSMPoolSetInfoExp`, `urUSMPoolCreateExp`, `urUSMPoolDestroyExp`, `urUSMPoolGetDefaultDevicePoolExp`.
Closes #18488

[UR][L0v2][SYCL] Enable e2e tests

---

sycl/source/detail/program_manager/program_manager.hpp
sycl/unittests/program_manager/Cleanup.cpp

It was changed to a string view in preview builds of the library under the assumption that such strings are always owned by one of the loaded images.
Bfloat16 device library images are an exception to that rule, where the dynamic device binary image ends up using a reference to the string from another binary. If that binary is unloaded, the string view keys will be invalidated.
Since this particular map lies outside of the kernel submission hotpath (and it's the only one with a string view key type that gets filled out for bfloat16 device binary images), this patch just reverts the key type back to a string.

[SYCL] Revert m_ExportedSymbolImages key type back to a string

---

sycl/source/detail/program_manager/program_manager.cpp
sycl/test-e2e/README.md
sycl/test-e2e/lit.cfg.py
sycl/test-e2e/lit.site.cfg.py.in
unified-runtime/source/adapters/offload/device.cpp

Enable the Offload backend in the E2E tests. The Offload UR adapter is still experimental and a WIP, the purpose of E2E testing now is purely to help develop the adapter and liboffload itself. The Offload adapter is not built by default.

[SYCL][Offload] Enable Offload backend in E2E tests

---

sycl/source/handler.cpp

https://github.com/intel/llvm/pull/19203 changed current reduction implementation but the old one was inlined into user applications and it relied on the `handler::MIsFinalized` hacky behavior. As such, we have to keep it in non-preview mode.

[SYCL] Fix ABI break after "Refactor HandlerAccess::postProcess"

---

unified-runtime/source/adapters/cuda/device.cpp
unified-runtime/source/adapters/cuda/usm.cpp

This is an optimisation that uses a direct memcopy from host to device.

[SYCL] Support UR_DEVICE_INFO_USM_CONTEXT_MEMCPY_SUPPORT_EXP on Cuda

---

llvm/lib/Target/SPIRV/SPIRVBuiltins.td
llvm/test/CodeGen/SPIRV/transcoding/builtin_calls.ll

The mapping ensures the function is lowered to SPIR-V built-in variables in SPIR-V. This can fix pre-commit CI fail in https://github.com/intel/llvm/pull/19359
(cherry picked from commit 64205adc3bfdaab0f35f7909de59dadd20ef6e6a) This is a partial cherry-pick since 27c9b55659c9 isn't in intel/llvm yet.

[SPIR-V] Map SPIR-V friendly work-item function to built-in variables(#148567)

---

unified-runtime/test/conformance/adapter/urAdapterRelease.cpp
unified-runtime/test/conformance/adapter/urAdapterRetain.cpp
unified-runtime/test/conformance/context/urContextRetain.cpp
unified-runtime/test/conformance/device/urDeviceRelease.cpp
unified-runtime/test/conformance/device/urDeviceRetain.cpp
unified-runtime/test/conformance/enqueue/urEnqueueEventsWait.cpp
unified-runtime/test/conformance/enqueue/urEnqueueEventsWaitWithBarrier.cpp
unified-runtime/test/conformance/enqueue/urEnqueueKernelLaunch.cpp
unified-runtime/test/conformance/enqueue/urEnqueueMemBufferCopy.cpp
unified-runtime/test/conformance/enqueue/urEnqueueMemBufferCopyRect.cpp
unified-runtime/test/conformance/enqueue/urEnqueueMemBufferReadRect.cpp
unified-runtime/test/conformance/enqueue/urEnqueueMemBufferWriteRect.cpp
unified-runtime/test/conformance/enqueue/urEnqueueMemImageCopy.cpp
unified-runtime/test/conformance/enqueue/urEnqueueUSMFill.cpp
unified-runtime/test/conformance/enqueue/urEnqueueUSMFill2D.cpp
unified-runtime/test/conformance/enqueue/urEnqueueUSMMemcpy.cpp
unified-runtime/test/conformance/event/urEventWait.cpp
unified-runtime/test/conformance/exp_command_buffer/enqueue.cpp
unified-runtime/test/conformance/exp_command_buffer/rect_read.cpp
unified-runtime/test/conformance/exp_command_buffer/release.cpp
unified-runtime/test/conformance/exp_command_buffer/update/invalid_update.cpp
unified-runtime/test/conformance/kernel/urKernelRetain.cpp
unified-runtime/test/conformance/program/urProgramRetain.cpp
unified-runtime/test/conformance/queue/urQueueRetain.cpp
unified-runtime/test/conformance/virtual_memory/urVirtualMemMap.cpp
unified-runtime/test/conformance/virtual_memory/urVirtualMemReserve.cpp

`EXPECT` doesn't return from the current function, so a number of tests
would keep going if they failed, in one case segfaulting due to writing
to memory that was not allocated correctly.
Standardise the test suite so that it always returns on the first
failure using `ASSERT` where possible.

[UR][CTS] Use `ASSERT` instead of `EXPECT` in test bodies

---

sycl/test/tools/Inputs/mock_renderd_access.c
sycl/test/tools/render-group.cpp
sycl/tools/sycl-ls/sycl-ls.cpp

This patch adds a check in sycl-ls to verify that the user has permission to access /dev/dri/renderD* device nodes, if they are present. If a device node exists but cannot be opened due to insufficient permissions (typically because the user is not in the render group), a clear warning is printed.
This helps users quickly identify missing group membership as the cause of device enumeration failures, instead of silently failing and requiring time-consuming troubleshooting.

[SYCL] Check access to /dev/dri/renderD* in sycl-ls

---

unified-runtime/source/adapters/cuda/device.hpp

`UR_CHECK_ERROR` throws an exception so we can't use it from a destructor.
Since devices only get released at application shutdown, there's not much we can do if `nvmlShutdown` reports an error, and the OS will promptly cleanup anything left as it tears down the process anyway.
So just skip checking the error code from `nvmlShutdown`, this is already what we do for other cleanup/shutdown in this destructor.
Fixes: https://github.com/intel/llvm/issues/19500

[UR][CUDA][Coverity] Don't check nvmlShutdown return in destructor

---

sycl/include/sycl/ext/intel/esimd/detail/types_elementary.hpp
sycl/test/self-contained-headers/lit.local.cfg

We can't use the alias here, we need to use the original type.
Also it fixed some self contained header test for some reason so remove the XFAIL for that.

[SYCL][ESIMD] Fix warning in header

---

devops/scripts/benchmarks/benches/base.py
devops/scripts/benchmarks/benches/benchdnn.py
devops/scripts/benchmarks/benches/compute.py
devops/scripts/benchmarks/benches/gromacs.py
devops/scripts/benchmarks/benches/llamacpp.py
devops/scripts/benchmarks/benches/syclbench.py
devops/scripts/benchmarks/benches/test.py
devops/scripts/benchmarks/benches/umf.py
devops/scripts/benchmarks/benches/velocity.py
devops/scripts/benchmarks/git_project.py
devops/scripts/benchmarks/utils/compute_runtime.py

- don't rebuild any of the Compute Runtime components if none of them has changed
- rebuild Compute Runtime and all of its components if any of them has changed
- refactor components directories' names to be more consistent
~Requires: #19158~
~Please, review only the last commit~

[CI][Benchmarks] Refactor Compute Runtime builds

---

unified-runtime/source/adapters/offload/event.cpp

The issue causing the crash upstream has been fixed (it was an unhandled
llvm::Error), so we can now delete events properly.

[UR][Offload] Enable olDestroyEvent

---

sycl/source/detail/device_impl.hpp
sycl/source/detail/graph/node_impl.hpp
sycl/source/detail/helpers.hpp

`std::weak_ptr<node_impl>` aren't used to create `nodes_range` anymore (https://github.com/intel/llvm/pull/19438 being the last change that enabled that, I think) and we also added `SyclTy` template parameter to `variadic_iterator` so that the dereference operator can be implemented in a generic way in the base class.

[NFC][SYCL] Simplify `variadic_iterator` usage

---

sycl/source/backend.cpp
sycl/source/detail/adapter_impl.hpp
sycl/source/detail/context_impl.cpp
sycl/source/detail/context_impl.hpp
sycl/source/detail/device_image_impl.cpp
sycl/source/detail/device_image_impl.hpp
sycl/source/detail/kernel_bundle_impl.hpp
sycl/source/detail/kernel_name_based_cache_t.hpp
sycl/source/detail/kernel_program_cache.cpp
sycl/source/detail/kernel_program_cache.hpp
sycl/source/detail/memory_manager.cpp
sycl/source/detail/program_manager/program_manager.cpp
sycl/source/detail/program_manager/program_manager.hpp
sycl/source/detail/scheduler/commands.cpp
sycl/unittests/program_manager/arg_mask/EliminatedArgMask.cpp

There was `ProgramManager::ProgramPtr` alias over `std::unique_ptr` with a custom deleter to RAII-manage `ur_program_handle_t` lifetime but it was applied in just a few places with the rest of the usage left with C-style explicit management.
This PR introduce a dedicated helper class to manage all UR handle types that I think is more convenient than `ProgramManager::ProgramPtr`. I'm also switching all the objects that stored `ur_program_handle_t` and then `urProgramRelease`d them to use that new helper, while leaving the full refactoring (i.e., create those `Managed` objects at `urProgramCreate*`/`urProgramRetain` point) to a subsequent PRs to ease review process.
Other `ur*_handle_t`s are left to subsequent changes as well.

[NFC][SYCL] Better "managed" `ur_program_handle_t`

---

sycl/cmake/modules/AddSYCLUnitTest.cmake
sycl/unittests/scheduler/CMakeLists.txt

intel/llvm#19399 made layout of `scheduler` class dependent on whether or not XPTI instrumentation is enabled. This caused issues with layout mismatch when `scheduler.hpp` is included directly from unit-tests, because macro enabling XPTI were not aligned between the RT and unit-tests.
The issue was caught for scheduler unit-tests and fixed in intel/llvm#19399, but apparently we have more unit-tests which need scheduler. Internal testing discovered issues with buffer unit-tests.
Therefore, re-applied the fix from intel/llvm#19399 globally to all unit-tests to prevent issues like this appearing in new and other existing unit-tests.

[SYCL][Unit] Fix unit-tests after intel/llvm#19399

---

unified-runtime/source/adapters/offload/enqueue.cpp
unified-runtime/source/adapters/offload/event.cpp
unified-runtime/source/adapters/offload/event.hpp
unified-runtime/source/adapters/offload/queue.cpp
unified-runtime/source/adapters/offload/queue.hpp
unified-runtime/test/conformance/event/urEventGetProfilingInfo.cpp

* Implemented device infos for event handles.
* Fixed event being deleted before it should have been.
* Make the tests consider profiling info optional.

[UR][Offload] Improvements to offload event handling

---

unified-runtime/source/adapters/native_cpu/enqueue.cpp

We were creating excessive numbers of threads. When we know we want a given amount of threads, just divide the number of workgroups by the number of threads and have each thread process that many workgroups.
This implementation also means we no longer need to resize workgroups, which was not generally safe.

[NativeCPU] Simplify enqueue.

---

sycl/include/sycl/stl_wrappers/__sycl_cmath_wrapper_impl.hpp
sycl/test/check_device_code/math-builtins/cmath-fallback-ld.cpp

Make sure to not define `long double` wrappers in the cmath wrapper. We unintentionally defined these for two or three argument functions with mixed types. These definitions fail to compile if we try to use them, because there are no SPIR-V builtins for long double. By not defining them, overload resolution will pick the "host" versions. We can't make overload resolution fail, because function bodies that are not called on the device still need to be semantically valid for the device.
This was discovered by the SYCL CTS, in its reference implementation for the builtins. That code is never called on the device, but it needs to compile without errors.

[SYCL][NVPTX][AMDGCN] Fix compilation for cmath long double

---

devops/scripts/install_build_tools.sh

I'm planning to add a build using libc++ to the nightly, so we need clang and libc++ installed.
Installing clang shouldn't cause a problem with the wrong clang being used for LIT testing as we pass the absolute path to the built clang, ex here.
build-e2e:
```
Run cmake -GNinja -B./build-e2e -S./llvm/sycl/test-e2e \ 
-DCMAKE_CXX_COMPILER="$GITHUB_WORKSPACE/toolchain/bin/clang++" -DLLVM_LIT="$PWD/llvm/llvm/utils/lit/lit.py" 
```
run-e2e:
```
echo PATH=$PWD/toolchain/bin/:$PATH >> $GITHUB_ENV
```
We need to specify the clang version to install because of some Ubuntu nonsense.

[CI] Install clang and libc++ in build containers

---

.github/workflows/sycl-rel-nightly-launch.yml

In general it works without token, but sometimes the default limit is not enough.

[sycl-rel][CI] Add a token to bypass request limit

---

sycl/include/sycl/kernel_bundle.hpp
sycl/source/backend.cpp
sycl/source/detail/helpers.cpp
sycl/source/detail/kernel_bundle_impl.hpp
sycl/source/detail/kernel_impl.cpp
sycl/source/detail/kernel_impl.hpp
sycl/source/detail/program_manager/program_manager.cpp
sycl/source/detail/scheduler/commands.cpp
sycl/source/kernel_bundle.cpp
sycl/test/abi/sycl_symbols_windows.dump
sycl/unittests/program_manager/arg_mask/EliminatedArgMask.cpp

* Avoid unnecessary copies
* Use rvalue-reference if param is getting moved from
* Remove `DeviceImageImplPtr` type alias (not too many uses remaining, doesn't bring much value anymore)
* Inline some temporaries so that explicit `std::move` wouldn't be needed
* Switch some sets to use raw `device_image_impl *` ptr
* `kernel_impl::getDeviceImage` to return raw reference

[NFC][SYCL] `std::shared_ptr<device_image_impl>` cleanups

---

.github/workflows/sycl-detect-changes.yml
.github/workflows/sycl-linux-build.yml
.github/workflows/sycl-windows-build.yml
libdevice/cmake/modules/ImfSrcConcate.cmake

We check this in the windows/linux build workflows but we never set it, so use the existing `sycl` specifier.
Closes: https://github.com/intel/llvm/issues/19573

[CI] Detect changes to libdevice

---

unified-runtime/source/adapters/offload/context.cpp
unified-runtime/source/adapters/offload/device.cpp
unified-runtime/source/adapters/offload/platform.cpp

And also a small comment explaining why context isn't supported.

[UR][Offload] Native handle wrappers for device and platform

---

llvm-spirv/lib/SPIRV/CMakeLists.txt
llvm-spirv/tools/llvm-spirv/CMakeLists.txt

Cherry pick of https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/3274
Needed to fix shared library build.

Fix build when linking against SPIRVLib with SPIR-V backend

---

sycl/source/detail/device_global_map_entry.cpp
sycl/source/detail/device_global_map_entry.hpp

Using `nullptr` for not having an event is just fine.

[NFC][SYCL] No need for `std::optional<ur_event_handle_t>` in `device_global_map_entry`

---

sycl/test-e2e/SYCLBIN/link_mixed_opt_input.cpp
sycl/test-e2e/SYCLBIN/link_mixed_opt_object.cpp

https://github.com/intel/llvm/pull/19547 unintentionally removed the mixed optimization level tests for SYCLBIN. This commit adds them back.

[SYCL][E2E][SYCLBIN] Add back mixed opt SYCLBIN tests

---

sycl/source/detail/scheduler/commands.cpp
sycl/source/detail/scheduler/scheduler.cpp
sycl/source/detail/scheduler/scheduler.hpp

Before this PR, its implementation had code paths for `nullptr` argument, but it's never `nullptr` at any of the call sites. Originally, this method was added in https://github.com/intel/llvm/pull/7531 and was called with `nullptr` argument from some fusion code (at least), but it doesn't seem to be the case anymore (and fusion support has been removed from the project).
Also, for some reason it was accepting `std::shared_ptr<event_impl>` by value and not by reference (no idea why), and the name was `NewEvent` without any comments/documentation. The former is irrelevant after this change, and for the latter I'm changing the name to a neutral "Event". If someone has a better understanding, please let me know.

[NFCI][SYCL] Change `scheduler::enqueueCommandForCG` to accept `event_impl &`

---

sycl/test/lit.site.cfg.py.in

The CMake value used for this LIT variable is just a normal boolean CMake variable set by the main LLVM CMake infrastructure, not an option that uses `ON` or `OFF`, and the lit python code expects all variables values to be option values, so just make the value of this variable match option values.

[SYCL][LIT] Fix value of sycl_use_libcxx LIT variable

---

libdevice/cmake/modules/SYCLLibdevice.cmake

We need to apply the custom flags both to the libdevice BC file generation and the imf host compile, as these flags could contain paths to stdlibc++ or glibc which are used in both.
I forgot to do this in my [change](https://github.com/intel/llvm/pull/19521) adding this flag.

[SYCL][CMake] Apply SYCL_LIBDEVICE_CXX_FLAGS to IMF host compile

---

sycl/source/detail/device_impl.cpp

Looks like it was necessary when we used `std::shared_ptr<device_impl>` a lot more. No need for it now.

[NFCI][SYCL] Don't get `&Self` in `device_impl` from `MPlatform`

---

sycl/test-e2e/Basic/buffer/buffer_full_copy.cpp
sycl/test-e2e/Basic/fill_accessor.cpp
sycl/test-e2e/Basic/fill_accessor_ur.cpp
sycl/test-e2e/Basic/handler/handler_mem_op.cpp
sycl/test-e2e/Basic/queue/queue_shortcut_functions.cpp
sycl/test-e2e/KernelAndProgram/kernel-bundle-get-kernel-ids.cpp
sycl/test-e2e/MemorySanitizer/track-origins/check_host_usm.cpp
sycl/test-e2e/MemorySanitizer/track-origins/check_host_usm_initialized_on_host.cpp
sycl/test-e2e/MemorySanitizer/track-origins/check_kernel_memcpy.cpp
sycl/test-e2e/MemorySanitizer/track-origins/check_kernel_memmove_no_overlap.cpp
sycl/test-e2e/MemorySanitizer/track-origins/check_kernel_memmove_overlap.cpp
sycl/test-e2e/MemorySanitizer/track-origins/check_shared_usm.cpp
sycl/test-e2e/ProfilingTag/profiling_queue.cpp

[XPASSing](https://github.com/intel/llvm/actions/runs/16559376045) in the nightly for some reason but failing in precommit.

[SYCL][E2E] Move XPASSing tests in nightly to UNSUPPORTED

---

devops/scripts/benchmarks/CONTRIB.md

Add information on the dashboard generation in the contribution guide.
Preview: https://github.com/PatKamin/llvm/blob/contrib-guide/devops/scripts/benchmarks/CONTRIB.md

[CI][Benchmarks] Add dashboard info in contrib

---

devops/scripts/benchmarks/html/scripts.js
devops/scripts/benchmarks/html/styles.css

Don't truncate legend, always display all legend items.

[CI][Benchmarks] Display all legend items in charts

---

unified-runtime/source/adapters/level_zero/context.cpp

addresses event pool leak when SYCL_PI_LEVEL_ZERO_DISABLE_EVENTS_CACHING is set to 1

Event pool cache leak fix

---

.github/workflows/sycl-linux-build.yml
.github/workflows/sycl-nightly.yml
sycl/unittests/misc/CMakeLists.txt

We are trying to be more packagable by Linux distros so I cleaned up libc++ support, add a build job to lock it down in the nightly.
Run results [here](https://github.com/intel/llvm/actions/runs/16603313011/job/46968573846), `check-clang` fail unrelated, I'm fixing it in another PR.

[CI] Add libc++ build job to nightly

---

libclc/cmake/modules/AddLibclc.cmake

The add_custom_command depends on builtins_lib, but not on prepare-${obj_suffix} target that generates builtins_lib. cmake documentation doesn't mention that the add_custom_command will automatically depends on prepare-${obj_suffix} target.
The dependency was removed in f07c1fa1d88a. However, our downstream repo reintroduced it to fix build error in CMPLRLLVM-57824, where builtins_lib is used while still being generated.
This PR adds the dependency back. Then, cmake will create a target-level dependency to make sure prepare-${obj_suffix} target is built before target "remangled-${long_width}-${signedness}_char.${obj_suffix_mangled}".

[libclc] Let builtins_remangle_path generating command depend on prepare-${obj_suffix} target

---

devops/scripts/benchmarks/CONTRIB.md
devops/scripts/benchmarks/history.py
devops/scripts/benchmarks/main.py
devops/scripts/benchmarks/options.py

Archived runs older than 3 times the specified days are not included in the dashboard, i.e.. when archiving data older than 7 days, runs older than 21 days are not included.
This change will prevent the archived data file used in the dashboard from a limitless size grow.

[CI][Benchmarks] Archive cutoff date

---

clang/lib/Headers/__clang_spirv_builtins.h
clang/test/CodeGenSPIRV/Builtins/ids_and_ranges.c
clang/test/Headers/spirv_ids.cpp

https://github.com/intel/llvm/commit/27c9b55659c99fad4583fb6fa29dd079ea8b9582 was added upstream, but because it has limited SYCL support, tests can't run properly.

[SPIRV] id and range builtins integration for SYCL

---

.github/workflows/sycl-linux-build.yml

Dumb interaction between github workflow variable usage in bash scripts, the variable happens to contain quotes only for the oneAPI build so that broke when I added these bash `if` statements. Make it a bash var to fix it.
Bad: https://github.com/intel/llvm/actions/runs/16612784850/job/47040968439 (HEAD)
Good: https://github.com/intel/llvm/actions/runs/16627822780/job/47051427259 (this PR)

[CI] Fix Linux OneAPI build LIT tests

---

.github/workflows/sycl-linux-build.yml
.github/workflows/sycl-linux-precommit-aws.yml
.github/workflows/sycl-linux-precommit.yml
.github/workflows/sycl-linux-run-tests.yml
.github/workflows/sycl-nightly-benchmarking.yml
.github/workflows/sycl-nightly.yml
.github/workflows/sycl-post-commit.yml
.github/workflows/sycl-ur-perf-benchmarking.yml
.github/workflows/sycl-weekly.yml
.github/workflows/sycl-windows-build.yml
.github/workflows/sycl-windows-precommit.yml
.github/workflows/sycl-windows-run-tests.yml

* Group all artifact-related inputs in `sycl-linux-build.yml`. I plan on refactoring artifacts for E2E tests/release toolchain in a subsequent PR.
* Unify inputs/outputs names between `sycl-*-build.yml` and `sycl-*-run-tests.yml`. Windows still has less flexibility, but for the inputs that exist there the names still match Linux and the inputs are ordered similarly to Linux.
* Add `${{ needs.build.outputs.toolchain_artifact }}` instead of duplicating the artifact name. Aligns usage with actual filename/decompress command.

[CI] Refactor toolchain-artifact related inputs/outputs

---

.github/workflows/sycl-linux-build.yml
.github/workflows/sycl-linux-precommit.yml

Also changed default install directory to avoid ugly copy.

[CI] Control each kind of pre-built E2E tests by its own input

---

sycl/test-e2e/KernelCompiler/sycl.cpp
sycl/test-e2e/KernelCompiler/sycl_imf.cpp
sycl/test-e2e/KernelCompiler/sycl_join.cpp

Passing in nightly [here](https://github.com/intel/llvm/actions/runs/16639139151/job/47086848029).
Updated https://github.com/intel/llvm/issues/18390

[SYCL][E2E] Remove XFAIL from passing KernelCompiler tests in preview mode

---

clang/include/clang/Basic/LangOptions.def

This field is no longer referenced by Native CPU.

[SYCL][NATIVECPU] remove unneeded SYCLIsNativeCPU LangOpt

---

clang/lib/Basic/Targets/NativeCPU.cpp
clang/test/CodeGenSYCL/native_cpu_target_features.cpp

For compilations without an aux target, the data layout string is not used by us because it only appears in device libs where it will be overwritten when the device lib gets merged in.
For compilations with an aux target, the data layout string should be set to that of the aux target, the aux target may be relying on that.

[NativeCPU] Use host data layout.

---

sycl/test-e2e/Reduction/reduction_big_data.cpp
sycl/test-e2e/Reduction/regression_after_pr_6343.cpp

If we see more Reduction failures I'll disable the whole directory.
Issue: https://github.com/intel/llvm/issues/19680

[SYCL][E2E] Disable two reduction tests sporadically failing

---

devops/actions/run-tests/e2e/action.yml
devops/actions/run-tests/windows/e2e/action.yml
sycl/test-e2e/Basic/bit_cast/bit_cast.cpp

Use a separate step so that the logs would be available if the workflow was cancelled. Also changes the "failing" step to only show the names of the failing tests instead of the whole e2e run log (that is still available in a separate foldable step).

[CI] Refactor processing of E2E failures

---

.github/workflows/sycl-linux-run-tests.yml

We also have "official" releases like "v6.1.0" but they have different archive name format *and* lack necessary tools for running E2E tests (like `FileCheck`, etc.). As such, limit support for "Nightly" releases format.

[CI] Add "Nightly" releases support for manual runs of `sycl-linux-run-tests.yml`

---

unified-runtime/source/adapters/level_zero/enqueued_pool.cpp
unified-runtime/source/adapters/level_zero/enqueued_pool.hpp
unified-runtime/test/adapters/level_zero/enqueue_alloc.cpp

This PR updates the allocation management algorithm to address cases where it fails to find suitable allocations due to how it performs lower bound searches.
Example:
```
Freelist {
Allocation(align=64, size=128),
Allocation(align=64, size=256),
Allocation(align=4096, size=128),
Allocation(align=4096, size=1024),
}
```
If we request `align=64`, `size=512`, the current code looks at `Allocation(align=4096, size=128)` and skips the rest, even though `Allocation(align=4096, size=1024)` would work.
This PR introduces grouping the allocations by queue and alignment.

[UR][L0] Fix allocation lookup in EnqueuedPool

---

.github/workflows/sycl-linux-precommit.yml
.github/workflows/sycl-post-commit.yml

We swapped self-build clang and GCC in 5e0db3edfa.
Update the step name to avoid confusion.

[CI][NFC] Fix the step name after 5e0db3edfa

---

sycl/include/sycl/detail/cg_types.hpp

Marked base and derived destructors as noexcept to resolve compiler error: exception specification of overriding function is more lax than base version.

[SYCL] Fix noexcept mismatch in HostKernel destructors

---

clang/lib/Basic/Targets/NativeCPU.cpp
clang/lib/Basic/Targets/NativeCPU.h
clang/test/CodeGenSYCL/native_cpu_target_features.cpp

Some clang targets (for example for Arm) may not initialize `DataLayoutString` in their TargetInfo constructor, which meant calls `getDataLayoutString`  right after the constructor cause an assert.
This PR defers the initialization of the NativeCPU TargetInfo to after the call of `handleTargetFeatures`  of the host cpu Target info, which on Arm initializes `DataLayoutString`, but may also catch more initializations.

[SYCL][NATIVECPU] Fix TargetInfo initialization (DataLayoutString)

---

sycl/test-e2e/Adapters/level_zero/interop-thread.cpp

Found by running the test with (loader) leak checking enabled.

[SYCL][test-e2e] Fix leaks in interop-thread.cpp

---

unified-runtime/source/adapters/offload/device.cpp

Offload changed the semantics of `OL_DEVICE_INFO_MAX_WORK_GROUP_SIZE`, so
update UR to follow.

[UR][Offload] Handle `MAX_WORK_GROUP_SIZE` changes

---

sycl/test-e2e/NewOffloadDriver/multisource.cpp
sycl/test-e2e/NewOffloadDriver/split-per-source-main.cpp
sycl/test-e2e/NewOffloadDriver/sycl-external-with-optional-features.cpp

So that I can pre-build E2E binaries for use in trunk backward compatibility CI.

[SYCL][E2E] Use `UNSUPPORTED: target-nvidia` instead of `cuda`

---

unified-runtime/test/CMakeLists.txt

Don't fetch and build it if a compatible version is installed on the system.
GMock is considered part of GTest to CMake (and not even a component) but in some Linux distros its a separate package, so we need to handle the case where one is installed but not the other.
Issue: https://github.com/intel/llvm/issues/19635

[UR][CMake] Support preinstalled GTest

---

llvm/lib/Target/SPIRV/SPIRVInstructionSelector.cpp
llvm/lib/Target/SPIRV/SPIRVUtils.cpp
llvm/lib/Target/SPIRV/SPIRVUtils.h
llvm/test/CodeGen/SPIRV/llvm-intrinsics/fp-intrinsics.ll
sycl/test-e2e/DeviceLib/cmath_fp64_test.cpp
sycl/test-e2e/DeviceLib/cmath_test.cpp
sycl/test-e2e/DeviceLib/math_fp64_test.cpp
sycl/test-e2e/DeviceLib/math_test.cpp

Cherry-pick the patch llvm/llvm-project@1d02de28dd6:
```
Based on
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/3100, I'm
adding translation for `llvm.modf.*` intrinsics.
```
And reenable tests that were unsupported because of this issue.
Fixes #17813.

"[SPIRV] Implement translation for llvm.modf.* intrinsics (#147556)" cherry-pick

---

sycl/test-e2e/lit.cfg.py

Before the PR we had two modes:
* Default, auto-detect preview support in toolchain and have individual tests run dedicated `RUN`-lines
* `--param test-preview-mode=<anything but False>`, run entire suite in preview mode using non-preview `RUN`-lines. Special `RUN`-lines dedicated to preview are ignored.
This PR changes it to this:
* Only allow `test-preview-mode` to be unset or set to True/False, fatal error on any other value.
* If True/unset behave as in two previous scenarios
* If False, only execute `RUN`-lines without preview markup
I need this for compatibility testing because preview mode isn't backward ABI-compatible and I'm going to cherry-pick this to `sycl-rel-6_[23]`
For trunk, I think we should just remove special `RUN`-lines and rely on "full preview" mode job in CI, but …

[SYCL][E2E] Better control of testing `preview-mode`

---

unified-runtime/cmake/FetchOpenCL.cmake

The problem was `OpenCL_FOUND` was getting set to `TRUE` on the second invocation of the module because `find_package` was finding the `FetchContent` clone in `SOURCE_TREE/build/__deps`.
We use `OpenCL_FOUND` to specifically refer to external system-wide installs, so use `NO_CMAKE_PACKAGE_REGISTRY` to make sure we don't find FetchContent clones.
Also not related to the fix here but re-order `FetchContent_Declare` `FetchContent_GetProperties`, the `Declare` should come first and we `MakeAvailable` should not be inside the `if`, we only check if it's populated to print the message.
Closes: https://github.com/intel/llvm/issues/19737

[UR][CMake] Fix OpenCL target error on rebuild

---

devops/actions/run-tests/e2e/action.yml

https://github.com/intel/llvm/pull/19719 broke `workflow_dispatch` mode for manual E2E task invocation for compatibility testing as we don't have the required `binaries_artifact` input in that mode. Github limits number of input parameters in `workflow_dispatch` mode, so restore the functionality without introducing extra input.

[CI] Use E2E container binaries in `run-only` manual E2E task dispatch

---

.github/workflows/sycl-rel-nightly-launch.yml
.github/workflows/sycl-rel-nightly.yml

Currently there are two release branches and both of them should be tested with Nightly.

[CI] Update sycl-rel-nightly-launch.yml

---

llvm/lib/Analysis/ConstantFolding.cpp
llvm/test/Transforms/Inline/inline_constprop.ll

Constant folding should meet any accuracy requirements enforceby the
fpbuiltin intrinsic as it provides correctly-rounded implementation.

[Inline] Enable constant folding for fpbuiltin sqrt

---

sycl/test-e2e/AbiNeutral/catch-exception.cpp
sycl/test-e2e/AbiNeutral/device-info.cpp
sycl/test-e2e/AbiNeutral/submit-kernel.cpp

We test that combination in Nightly unconditionally on SPR/PVC https://github.com/intel/llvm/blob/efe036e5b5f0229824f874d3fc489377877a0115/.github/workflows/sycl-nightly.yml#L120-L132 and that functionality isn't device/backend-dependent, so no need for extra RUN lines.

[SYCL][E2E] Remove preview/CXX11_ABI RUN lines from `AbiNeutral/*`

---

unified-runtime/source/adapters/cuda/enqueue.cpp

A couple function signatures changed.
Only UR change here.
Choice of `CU_MEM_LOCATION_TYPE_HOST_NUMA_CURRENT` for host advice is somewhat arbitrary.
Full CUDA 13 support requires a compiler driver patch from upstream (12eab1a7b8).

[UR][CUDA] Add support for CUDA 13

---

sycl/source/detail/config.hpp
sycl/unittests/config/ConfigTests.cpp

Bad / nonsensical values in `SYCL_PARALLEL_FOR_RANGE_ROUNDING_PARAMS` result in division by 0 crashes. This PR:
- Adds guards to check that range rounding factors are set to sensical values
- Adds test to ensure only valid range rounding factors can be set

[SYCL] Add validation + exception handling to SYCL_PARALLEL_FOR_RANGE_ROUNDING_PARAMS

---

clang/include/clang/Driver/CudaInstallationDetector.h
clang/include/clang/Driver/LazyDetector.h
clang/include/clang/Driver/RocmInstallationDetector.h
clang/include/clang/Driver/SyclInstallationDetector.h
clang/lib/Driver/ToolChain.cpp
clang/lib/Driver/ToolChains/AMDGPU.cpp
clang/lib/Driver/ToolChains/AMDGPU.h
clang/lib/Driver/ToolChains/AMDGPUOpenMP.cpp
clang/lib/Driver/ToolChains/AMDGPUOpenMP.h
clang/lib/Driver/ToolChains/Clang.cpp
clang/lib/Driver/ToolChains/CommonArgs.cpp
clang/lib/Driver/ToolChains/Cuda.h
clang/lib/Driver/ToolChains/Darwin.h
clang/lib/Driver/ToolChains/Gnu.h
clang/lib/Driver/ToolChains/HIPAMD.cpp
clang/lib/Driver/ToolChains/HIPAMD.h
clang/lib/Driver/ToolChains/HIPSPV.h
clang/lib/Driver/ToolChains/MSVC.h
clang/lib/Driver/ToolChains/MinGW.h
clang/lib/Driver/ToolChains/ROCm.h
clang/lib/Driver/ToolChains/SYCL.h
sycl-jit/jit-compiler/lib/rtc/DeviceCompilation.cpp

By using installation detectors we can move away from creating full toolchains and querying them.

[SYCL] Simplify detection of device bitcode libraries for RTC

---

.github/workflows/sycl-linux-build.yml
buildbot/configure.py
sycl/CMakeLists.txt

[CI] Install DeviceConfigFile independently

---

libdevice/sanitizer/msan_rtl.cpp

Currently, we always define stride in elements when writing to destination pointer. However, according to spirv spec, the stride can only be applied to global ptr.

[DevMSAN] Correctly apply stride for dest/src pointer when do async copy

---

libclc/libspirv/lib/generic/math/half_cos.cl
libclc/libspirv/lib/generic/math/half_divide.cl
libclc/libspirv/lib/generic/math/half_exp.cl
libclc/libspirv/lib/generic/math/half_exp10.cl
libclc/libspirv/lib/generic/math/half_exp2.cl
libclc/libspirv/lib/generic/math/half_log.cl
libclc/libspirv/lib/generic/math/half_log10.cl
libclc/libspirv/lib/generic/math/half_log2.cl
libclc/libspirv/lib/generic/math/half_powr.cl
libclc/libspirv/lib/generic/math/half_recip.cl
libclc/libspirv/lib/generic/math/half_rsqrt.cl
libclc/libspirv/lib/generic/math/half_sin.cl
libclc/libspirv/lib/generic/math/half_sqrt.cl
libclc/libspirv/lib/generic/math/half_tan.cl

Also delete double/half type implementations, which are not allowed per spec.
llvm-diff shows lots of changes in libspirv-amdgcn--amdhsa.bc and libspirv-nvptx64--nvidiacl.bc, due to use of __ocml_* and __nv_* built-ins in clc and libspirv in intel/llvm repo.
Based on review comment in https://github.com/llvm/llvm-project/pull/153328, libclc shouldn't use __ocml_*. So bitcode change in this PR is expected.

[libspirv] Use clc function in libspirv generic math half_* functions

---

sycl/doc/extensions/experimental/sycl_ext_oneapi_forward_progress.asciidoc

This commit moves the sycl_ext_oneapi_forward_progress extension to experimental, following its implementation in
https://github.com/intel/llvm/pull/13389.

[SYCL][Docs] Move sycl_ext_oneapi_forward_progress to experimental

---

unified-runtime/test/conformance/event/urEventSetCallback.cpp

Before this patch, urEventSetCallbackTest assumed that the callback
would be executed during and blocking urEventWait or urEventRelease.
This change removes that assumptions by having the main thread wait
until the callback is complete.

[UR][CTS] Update urEventSetCallback test to not assume sync. events

---

unified-runtime/include/ur_api.h
unified-runtime/scripts/core/program.yml
unified-runtime/source/adapters/offload/program.cpp
unified-runtime/source/adapters/offload/ur_interface_loader.cpp
unified-runtime/source/loader/ur_libapi.cpp
unified-runtime/source/ur_api.cpp
unified-runtime/test/conformance/program/urProgramGetFunctionPointer.cpp

This is primarily for liboffload which doesn't support it yet, and
probably never will for AMD devices (which don't seem to have this
functionality). In theory it will also affect level zero, at least
according to a comment, but urProgramGetFunctionPointer seems to be
implemented there.

[UR] Allow `urProgramGetFunctionPointer` to return `UNSUPPORTED`

---

unified-runtime/source/adapters/level_zero/v2/command_list_manager.cpp

Implement urBindlessImagesSignalExternalSemaphoreExp and urBindlessImagesWaitExternalSemaphoreExp. The implementation is the same as in the legace adapter, except that we don't to a fallback in case old loader is used (v2 is supposed to be used with a new enough L0 loader version).

[SYCL][UR][L0 v2] Implement missing bindless images functionality

---

devops/scripts/benchmarks/benches/compute.py

Don't write invalid value of stddev into Results json.

[Benchmarks] Validate stddev in Compute Benchmarks

---

sycl/test-e2e/Adapters/level_zero/ext_intel_queue_index.cpp

This test is currently failing on Windows DG2 machines. Same reasoning as https://github.com/intel/llvm/pull/19811: as mentioned in https://github.com/intel/llvm/issues/18576, the root cause here is that DG2 never supported ZEX_NUMBER_OF_CCS. Therefore, XFAIL-ing this test on all DG2 machines (previously it is only XFAIL-ed on Linux DG2 machines).

[SYCL] XFAIL ext_intel_queue_index.cpp on DG2

---

devops/actions/run-tests/benchmark/action.yml
devops/scripts/benchmarks/compare.py
devops/scripts/benchmarks/options.py

Much easier to figure out what's wrong with the benchmarking CI runs when it tells you what's wrong immediately: https://github.com/intel/llvm/actions/runs/16789472825

[CI][Bench] Create summary reports for benchmarking CI run results

---

clang/include/clang/Driver/Options.td

When -fp-accuracy was added to intel/llvm, some customization tags were inadvertently added along with it.  Clean these out.

[Driver][NFC] Clean out unwanted customization tags

---

sycl/include/sycl/accessor.hpp
sycl/include/sycl/accessor_image.hpp
sycl/include/sycl/buffer.hpp
sycl/include/sycl/context.hpp
sycl/include/sycl/detail/impl_utils.hpp
sycl/include/sycl/device.hpp
sycl/include/sycl/event.hpp
sycl/include/sycl/ext/oneapi/bindless_images_memory.hpp
sycl/include/sycl/ext/oneapi/experimental/async_alloc/memory_pool.hpp
sycl/include/sycl/ext/oneapi/virtual_mem/physical_mem.hpp
sycl/include/sycl/image.hpp
sycl/include/sycl/kernel.hpp
sycl/include/sycl/kernel_bundle.hpp
sycl/include/sycl/platform.hpp
sycl/include/sycl/sampler.hpp
sycl/include/sycl/stream.hpp

Unfortunately, can't simplify further in C++17.
In C++20 that could be changed to
```
template <class T>
requires(is_sycl_common_reference_semantics_class_v<T>)
struct std::hash<T> {
// sycl_obj_hash impl inlined here.
};
```
But even in C++17 this PR removes copy-paste and places the implementation in a single place.

[NFC][SYCL] Add `sycl::detail::sycl_obj_hash` helper

---

unified-runtime/source/adapters/offload/context.hpp
unified-runtime/source/adapters/offload/enqueue.cpp
unified-runtime/source/adapters/offload/event.cpp
unified-runtime/source/adapters/offload/queue.cpp
unified-runtime/source/adapters/offload/queue.hpp
unified-runtime/source/adapters/offload/ur_interface_loader.cpp
unified-runtime/source/adapters/offload/usm.cpp

Some functions were added, the barrier event now is reference counted
(rather than being dropped when the event is destroyed) and empty events
no longer cause an error.

[UR][Offload] Various small fixes for offload adapter

---

sycl/unittests/context_device/DeviceRefCounter.cpp
sycl/unittests/helpers/UrMock.hpp

Windows shutdown/teardown doesn't have the exact same timing as on Linux, and even more in the the unit tests which are statically compiled ( so no DllMain() call, which means no space between the calls to `shutdown_early()` and `shutdown_late()` ).  Here we remove a race between the platform deletion in the mock and the win shutdown. This fixes a flaky failure we are seeing in a couple of the unit tests.

[SYCL] fix for flaky ~event failure in Win unit tests

---

unified-runtime/source/adapters/level_zero/image.cpp
unified-runtime/source/adapters/level_zero/image_common.cpp
unified-runtime/source/adapters/level_zero/platform.cpp
unified-runtime/source/adapters/level_zero/platform.hpp
unified-runtime/source/adapters/level_zero/v2/command_list_manager.cpp

- Intel L0 GPU Driver no longer supports the Driver Exp Implementation of External Semaphore and the code has been removed from the codebase, therefore the support needs to be removed from the adapter to allow compiling with newer ze_intel_gpu.h headers. 
- L0 Spec implementation is the only version required for customer support.

[UR][L0] Remove Driver Exp Implementation of External Semaphore

---

sycl/source/detail/helpers.hpp

variadic_iterator was recently introduced and is used by several routines that are marked as noexcept, some being API.  Changing its operator++ to be noexcept to prevent issues and put Coverity's mind at ease

[SYCL] variadic_iterator noexcept

---

sycl/source/device.cpp
sycl/test-e2e/USM/P2P/p2p_access_across_platforms.cpp

The current P2P extension implementation assumes that the devices are from the same platform, which may not be the case. In cases where they are not the same, the adapters will try to access the handles as if they were the layout of the corresponding adapter, which may manifest as invalid accesses or unexpected read internal handle values, which can in turn conflict with actual device handles, potentially causing false positives. This commit adds a check that the devices are from the same platform before requesting the information from the backend.

[SYCL] Fix reported P2P accessibility across platforms

---

sycl/source/detail/syclbin.hpp

This commit fixes the following Coverity issues:
* Adds explicit destructor to the SYCLBIN and SYCLBINBinaries classes, adhering to the rule-of-three.
* Removes noexcept from SYCLBINBinaries::getState() as the access to GlobalMetadata may throw an exception.

[SYCL] Fix SYCLBIN-related Coverity issues

---

README.md

This removes the mention of the old unused openmp branch from the top-level readme.
Closes https://github.com/intel/llvm/issues/11489.

[Docs] Remove OpenMP branch mention from README

---

sycl/test/extensions/free_function_kernels/free_function_host_compiler.cpp

This PR fixes issue when g++ is used as host compiler and its version does not support C++17 by default.
So by adding this flag ` -fsycl-host-compiler-options="-std=c++17"` we ensure that the lit test is compiled with C++17 standard which is required by SYCL.

[SYCL] Fix for free_function_host_compiler lit test

---

unified-runtime/test/conformance/event/urEventGetProfilingInfo.cpp

These tests now better handle the query being unsupported.

[UR][CTS] Small fixes for urEventGetProfilingInfo tests

---

libdevice/cmake/modules/SYCLLibdevice.cmake

This is a cherry-pick of intel/llvm#19780
Previously, we stopped building and deploying native/fallback bfloat16 spv files since latest compiler will embed required files into user's executable. However, we found some developers hadn't switched to latest compiler, then compatibility issue would happen. This PR continues to build and deploy, we will remove the files util a marjor release.

[SYCL] Keep bfloat16 native and fallback spv for compatibility 

---

unified-runtime/source/adapters/native_cpu/enqueue.cpp

Adds missing event handling to `urEnqueueUSMPrefetch` in the Native CPU adapter. This aims to fix random fails in `SYCL/USM/dep_events.cpp`.
Also removes unneeded call to `urEventWait`.

[SYCL][NATIVECPU] added event handling to urEnqueueUSMPrefetch

---

unified-runtime/cmake/helpers.cmake

`${Python3_EXECUTABLE}` is what is set by FindPython3 and is what is used everywhere else.
`${PYTHON_EXECUTABLE}` may be unset depending, causing the build to fail.
This failure case gets hit when compiling under NixOS for example
There's a few instances of  `PYTHON_EXECUTABLE` left in upstream LLVM, though I haven't verified whether it builds properly with those changed to `Python3_EXECUTABLE`, so they're untouched here.

[UR] Update PYTHON_EXECUTABLE to Python3_EXECUTABLE in cmake

---

sycl/test-e2e/Reduction/lit.local.cfg

Failing sporadically on basically all platforms and OSs.
https://github.com/intel/llvm/issues/19680
https://github.com/intel/llvm/issues/19767

[SYCL][E2E] Temporarily disable reduction test execution

---

sycl/source/detail/device_binary_image.hpp
sycl/source/detail/global_handler.cpp

This is a cherry-pick of intel/llvm#19807

[SYCL][NFC] Fix Coverity hits

---

devops/scripts/benchmarks/PERFORMANCE_TUNING.md
devops/scripts/benchmarks/README.md

Preview: https://github.com/PatKamin/llvm/blob/perf-setup-readme/devops/scripts/benchmarks/PERFORMANCE_TUNING.md

[CI][Benchmarks] Benches OS setup guide

---

llvm/lib/Object/SYCLBIN.cpp

When building on 32-bit build configurations, SYCLBIN.cpp would require inexplicit type narrowing from uint64_t to size_t. This commit fixes the type narrowing issues.
Fixes https://github.com/intel/llvm/issues/19891.

[SYCLBIN] Fix size_t type narrowing

---

xptifw/src/CMakeLists.txt

There's no CMake install target or pkg-config file, so we have to just search for the headers.
https://github.com/intel/llvm/issues/19635

[SYCL][CMake] Support pre-installed parallel-hashmap

---

unified-runtime/source/adapters/offload/enqueue.cpp

The event pointer can be nullptr if the event is a "no-op". This was
previously not handled in the `waitOnEvents helper`, now it is.

[UR][Offload] Fix waiting on empty events

---

unified-runtime/source/adapters/offload/device.cpp
unified-runtime/source/adapters/offload/queue.cpp
unified-runtime/source/adapters/offload/queue.hpp
unified-runtime/source/adapters/offload/ur_interface_loader.cpp
unified-runtime/source/adapters/offload/usm.cpp

With this change, the CTS tests for queues are now all passing. This
patch introduces the following changes:
* All `UR_DEVICE_INFO_QUEUE` values are handled.
* `UR_DEVICE_INFO_QUEUE_ON_DEVICE_PROPERTIES` now is 0 to match the UR
HIP/Nvidia backends.
* A stub function for `urUSMGetMemAllocInfo` is implemented. This is
required because now `UR_DEVICE_INFO_QUEUE_CONTEXT` is implemented,
the validation layer will try to call it.

[UR][Offload] Make all queue UR CTS tests pass

---

unified-runtime/source/adapters/level_zero/image.cpp

- When SYCl Calls the L0 adapter without a signal event, L0 creates an internal event.
- Given in order command queue, the internal event for the wait/signal is implicitly added to the wait list of the next command if executeCommandList is called.
- This ensures that the internal event is properly synchronized with the command queue during that next call given SYCL is failing to create a UR event for tracking the wait/signal.

[UR][L0] Fix Implict Event sync during external semaphore wait/signal

---

sycl/include/sycl/ext/oneapi/experimental/bfloat16_math.hpp
sycl/include/sycl/ext/oneapi/experimental/complex/detail/complex_math.hpp
sycl/include/sycl/stl_wrappers/__sycl_complex_impl.hpp
sycl/test-e2e/DeviceLib/exp/exp-std-complex-edge-cases.hpp

This commit replaces the uses of NAN and INFINITY in the SYCL complex headers with std::numeric_limits<float>::quiet_NaN() and std::numeric_limits<float>::infinity() respectively. This avoids issues where the definition of the macros could cause issues with differing constexpr'ness between platforms.
Fixes https://github.com/intel/llvm/issues/19114.

[SYCL] Use numeric_limits instead of NAN And INFINITY macros

---

libdevice/sanitizer/msan_rtl.cpp
unified-runtime/source/loader/layers/sanitizer/asan/asan_buffer.cpp
unified-runtime/source/loader/layers/sanitizer/asan/asan_ddi.cpp
unified-runtime/source/loader/layers/sanitizer/asan/asan_interceptor.cpp
unified-runtime/source/loader/layers/sanitizer/asan/asan_interceptor.hpp
unified-runtime/source/loader/layers/sanitizer/sanitizer_common/sanitizer_utils.cpp
unified-runtime/source/loader/layers/sanitizer/sanitizer_common/sanitizer_utils.hpp
unified-runtime/source/loader/layers/sanitizer/tsan/tsan_buffer.cpp
unified-runtime/source/loader/layers/sanitizer/tsan/tsan_ddi.cpp
unified-runtime/source/loader/layers/sanitizer/tsan/tsan_interceptor.cpp
unified-runtime/source/loader/layers/sanitizer/tsan/tsan_interceptor.hpp

This is a combined cherry-pick of:
---
[DevSAN] Cache internal queue to avoid repeated create/destroy (https://github.com/intel/llvm/pull/19540)
Patch-By: Maosu Zhao <maosu.zhao@intel.com>
---
[DevTSAN] Move AllocInfo into DeviceInfo to support indirect access (https://github.com/intel/llvm/pull/19634)
If we maintain AllocInfo in ContextInfo, this will cause the pointer
which is allocated by another context can't be poisoned.
Patch-By: Maosu Zhao <maosu.zhao@intel.com>
---
[DevMSAN] Correctly apply stride for dest/src pointer when do async copy (https://github.com/intel/llvm/pull/19766)
Currently, we always define stride in elements when writing to
destination pointer. However, according to spirv spec, the stride can
only be applied to global ptr.
Patch-By: Maosu Zhao …

[SYCL] Cherry-pick sanitizer patches

---

clang/lib/Sema/SemaSYCL.cpp
clang/test/CodeGenSYCL/free-function-kernel-templated-arg-with-enum.cpp
clang/test/CodeGenSYCL/free_function_default_template_arguments.cpp
clang/test/CodeGenSYCL/free_function_int_header.cpp
sycl/test-e2e/FreeFunctionKernels/accessor_as_kernel_parameter.cpp
sycl/test-e2e/FreeFunctionKernels/template_specialization.cpp

This is a cherry-pick of intel/llvm#19535
When free function kernel is a function template which in turn has arguments that are also templates, we may not print the latter properly into integration header.
Specifically, if an argument of a templated free function kernel has an `enum` template argument of its own then namespace qualifiers for it will be missing.
This patch fixed that.

[SYCL] Free function kernels bugfix 

---

.github/workflows/sycl-check-ready-to-merge-prs.yml

This workflow checks for ready-to-merge PRs - if a PR is open, not a draft, passed all checks, and has been approved, it will ping @intel/llvm-gatekeepers if this group has not already been mentioned or if the last mention was more than $days days ago.

[CI] Add a workflow to check ready PRs

---

devops/dependencies-igc-dev.json
sycl/test-e2e/Matrix/SG32/get_coordinate_ops.cpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_arg_dim.cpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_runtime_dim.cpp

[GHA] Uplift Linux IGC Dev RT version to igc-dev-46629d9

---

clang/lib/CodeGen/CodeGenModule.cpp
clang/test/CodeGenSPIRV/Builtins/generic_cast_to_ptr_explicit.c
clang/test/CodeGenSPIRV/Builtins/ids_and_ranges.c

This patch fixes test failures caused by the upstream patch that adds sycl_external attribute and restricts emitting device code.

Resolve sycl-web test failures caused by https://github.com/llvm/llvm-project/pull/140282

---

sycl/test-e2e/HostInteropTask/host-task-two-queues.cpp

This commit fixes the target for accessors used in a host_task from implicit target::device to explicit target::host_task.
Additionally, this PR removes the S = sycl alias and replaces the use of the old access::mode enum with the newer access_mode enum.

[SYCL][E2E] Fix target in host-task-two-queues

---

sycl/test-e2e/bindless_images/copies/host_to_host_pitched.cpp
sycl/test-e2e/bindless_images/sampling_2D_USM_host.cpp

Those tests should not be launched only on CUDA, because they already have an aspect requirement.
However, they do not pass on L0 yet because of missing functionality there.
They don't pass on HIP either - still `XFAIL` is a better approach than `REQUIRES`

[SYCL][E2E] Replace REQUIRES with XFAIL

---

unified-runtime/source/adapters/level_zero/device.cpp
unified-runtime/source/adapters/level_zero/device.hpp

- disable using immediate command lists by default on MTL/ARL Linux to
achieve the best performance without user environment changes

[UR][L0] Disable Immediate Command Lists by default on MTL/ARL Linux

---

sycl/test-e2e/Regression/commandlist/Inputs/main.cpp

`nthreadsGPU` is used to declare an array at 
https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/Regression/commandlist/Inputs/main.cpp#L102 which throws an error:
```
error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
```
This PR marks this variable as constexpr.

[SYCL][E2E][NFC] Mark `nthreadsGPU` as `constexpr`

---

sycl/test/self-contained-headers/lit.local.cfg
sycl/test/self-contained-headers/sycl/stl_wrappers/__sycl_cmath_wrapper_impl.hpp.cpp

The test is flaky and has no value in general.

[SYCL] Disable self-contained-headers test on Windows

---

clang/lib/Frontend/InitPreprocessor.cpp
clang/test/Preprocessor/sycl-macro-target-specific.cpp
sycl/include/sycl/atomic_ref.hpp

This PR removes `SYCL_USE_NATIVE_FP_ATOMICS` macro.
It's removed because we don't support FPGA anymore and macro was defined for all target except FPGA.
https://github.com/intel/llvm/blob/45cf4436aac62b68c55c7ba8ba994004b88220f7/clang/lib/Frontend/InitPreprocessor.cpp#L1548-L1551

[SYCL] Remove `SYCL_USE_NATIVE_FP_ATOMICS` macro

---

sycl/source/detail/program_manager/program_manager.cpp
sycl/source/detail/program_manager/program_manager.hpp

The data race was detected by a unit test while working on #19843.

Fix data race in the ProgramManager::getOrCreateDeviceKernelInfo

---

sycl/source/detail/queue_impl.hpp
sycl/unittests/queue/Barrier.cpp

Currently for the pattern like this:
```
sycl::event eb1 = q1.ext_oneapi_submit_barrier();
q2.ext_oneapi_submit_barrier({ eb1 });
```
the second barrier ignores `eb1` in the waitlist because it is not marked as enqueued even though it is supposed to. This PR fixes that.
Fixes https://github.com/intel/llvm/issues/19777

[SYCL] Fix barrier on barrier dependency between queues

---

sycl-jit/jit-compiler/CMakeLists.txt

Failed after https://github.com/intel/llvm/pull/19924.
`remangled-*` requiring `libspirv-builtins` on top of `libclc` is technically a separate issue but I realized it while working on fixing the CI, so can go in in the same PR.

[SYCL-RTC] Fix MacOS post-commit build failure

---

sycl/source/detail/device_binary_image.cpp
sycl/source/detail/device_binary_image.hpp
sycl/unittests/compression/CompressionTests.cpp

**Problem**
There can be race during image decompression. Consider the case when one thread is reading the decompressed buffer while another thread modifies it. This can lead to invalid SPIRV errors emitted by IGC.
**Proposed solution**
Use `std::call_once` to ensure that only one thread does the decompression of an image.

[SYCL] Fix race during image decompression

---

sycl/source/detail/queue_impl.cpp

This is a cherry-pick of intel/llvm#19906

[SYCL] Fix a stale handler_impl reference with reductions 

---

llvm/lib/SYCLLowerIR/LowerWGLocalMemory.cpp
llvm/test/SYCLLowerIR/work_group_static.ll
sycl/test-e2e/FreeFunctionKernels/free_function_kernel_local_memory.cpp

This is a cherry-pick of intel/llvm#19837
When a kernel uses implicit local memory such as by way of the `get_work_group_scratch_memory` function, the library is supposed to mark the kernel with the appropriate attribute `WORK_GROUP_STATIC_ATTR` to get things to work at runtime. This is done through the properties passed to the kernel invocation call. For free function kernels however, the infrastructure is not there to do this marking process and usage of the above mentioned function typically results in a UR error.
This PR makes some changes at the middle-end level to traverse the call graph wherever the compiler built-in functions
`__sycl_allocateLocalMemory` and `__sycl_dynamicLocalMemoryPlaceholder` are used and mark each of the kernels found during this traversal , including free …

[SYCL] Allow work group scratch memory to be used with free function kernels

---

sycl-jit/jit-compiler/CMakeLists.txt
sycl-jit/jit-compiler/lib/rtc/DeviceCompilation.cpp
sycl-jit/jit-compiler/utils/generate.py

Follows https://github.com/intel/llvm/pull/19924 that did the same with headers. With this PR all SYCL Toolchain dependencies are linked as resources into the `libsycl-jit.so` and not accessing DPCPP installation on disk in runtime.

[SYCL-RTC] Distribute `libdevice`'s `*.bc` files inside `libsycl-jit.so`

---

unified-runtime/source/adapters/level_zero/context.cpp
unified-runtime/source/adapters/level_zero/context.hpp
unified-runtime/source/adapters/level_zero/event.cpp
unified-runtime/source/adapters/level_zero/event.hpp
unified-runtime/source/adapters/level_zero/queue.cpp

When using internal events we do not clean up after execution. In the case of repeated call to urEnqueueKernelLaunch we eventually return UR_RESULT_ERROR_OUT_OF_RESOURCES.

[UR][L0] Event cleanup in urEnqueueKernelLaunch

---

sycl/source/detail/cg.hpp
sycl/source/detail/graph/graph_impl.cpp
sycl/source/detail/graph/node_impl.hpp
sycl/source/detail/handler_impl.hpp
sycl/source/detail/program_manager/program_manager.cpp
sycl/source/detail/program_manager/program_manager.hpp
sycl/source/detail/scheduler/commands.cpp
sycl/source/detail/scheduler/commands.hpp
sycl/source/handler.cpp
sycl/unittests/program_manager/arg_mask/EliminatedArgMask.cpp
sycl/unittests/scheduler/SchedulerTestUtils.hpp
sycl/unittests/scheduler/StreamInitDependencyOnHost.cpp

Additional cleanups enabled by https://github.com/intel/llvm/pull/19117.

[NFCI][SYCL] More use of `CompileTimeKernelInfoTy`/`DeviceKernelInfo`

---

sycl/include/sycl/ext/intel/experimental/usm_properties.hpp
sycl/source/detail/usm/usm_impl.cpp
sycl/test-e2e/Adapters/level_zero/usm_device_read_only.cpp
sycl/test-e2e/USM/properties.cpp

This is a cherry-pick of intel/llvm#19890
* Fix `verifyUSMAllocatorProperties` to allow supported properties
* No need to specialize `is_property<...>` for USM properties - `std::base_of_v<>`-based implementation covers that.

[SYCL] Fixes for `usm_allocator` properties 

---

sycl/source/detail/program_manager/program_manager.cpp

Works around an internal compiler error that's observed in Jenkins precommit.
```
sycl/source/detail/program_manager/program_manager.cpp:1845:75: internal compiler error: in replace_placeholders_r, at cp/tree.c:2804
KernelName, CompileTimeKernelInfoTy{detail::string_view(KernelName)});
```

[SYCL] Fix build with older gcc

---

libdevice/cmake/modules/SYCLLibdevice.cmake

Compiler warning reported when building imf libdevice on Windows:
imf_rounding_op.hpp: warning: constexpr if is a C++17 extension [-Wc++17-extensions]
This PR fixes it.

[SYCL] Remove imf libdevice build warning on Windows

---

sycl/source/detail/device_impl.cpp
sycl/test-e2e/Adapters/level_zero/context_create_sub_sub_device.cpp
unified-runtime/source/adapters/level_zero/device.hpp
unified-runtime/source/adapters/level_zero/usm.cpp
unified-runtime/source/adapters/level_zero/v2/usm.cpp

This is a cherry-pick of intel/llvm#19921
Context creation was failing when sub-sub-devices were exposed, because the Level Zero adapter attempted to add multiple USM pools with identical descriptors. This occurred since, for the L0 backend, sub-sub-devices and their parent sub-devices share the same Level Zero device handle and should use the same USM pool.
This PR resolves the issue by ensuring only devices with unique Level Zero
handles are collected for USM pool creation, preventing duplicate pools.
Additionally, this PR fixes an issue with an uninitialized `ur_device_partition_property_t` variable passed to UR. Previously, this could result in an unexpected value for `value.affinity_domain` when the property type was `UR_DEVICE_PARTITION_BY_CSLICE` resulting on error from
adapter.

[UR] Fix usm pools creation failure at context initialization 

---

unified-runtime/source/common/CMakeLists.txt

bump UMF to 1.0.3
major changes:
* make topology_init faster
* workaround build failure when building for jemalloc with ninja
* initialize hwloc topology only before first fork, not always
* load libcuda.so.1 instead of libcuda.so on linux
full changelog: https://github.com/oneapi-src/unified-memory-framework/compare/v1.0.0...v1.0.3

[UR] Bump UMF to v1.0.3

---

devops/scripts/benchmarks/benches/compute.py

Host task data makes comparison charts unreadable, so we disable it for now.

[CI][Benchmarks] SYCL Graph: Disable host task and enable SYCL preview

---

unified-runtime/source/adapters/offload/program.cpp
unified-runtime/source/adapters/offload/program.hpp
unified-runtime/source/adapters/offload/ur_interface_loader.cpp
unified-runtime/test/conformance/program/urProgramBuild.cpp
unified-runtime/test/conformance/program/urProgramLink.cpp

The CTS tests for the program part of the API now pass (or are skipped).
This mostly was a matter of implementing olProgramGetBuildInfo and
olProgramLink (but only for one binary - specifying more than one is an
error). The build failure tests have also been tweaked a bit to better
reflect their optional nature.

[UR] Make offload program CTS tests pass

---

unified-runtime/source/common/logger/ur_sinks.hpp
unified-runtime/source/common/ur_util.hpp
unified-runtime/source/loader/ur_lib.cpp

Valgrind reports issues with the logger code that manipulates strings.

[UR] Refactor logging processing code

---

sycl/test-e2e/Basic/buffer/buffer_create.cpp

It fails because L0v2 adapter behaves differently from v1 when it comes to buffer creation. This test contains a hardcoded check involving implementation details of the adapter.

[SYCL][UR][L0v2] Mark Basic/buffer/buffer_create.cpp test as unsupported

---

sycl/source/detail/device_binary_image.cpp
sycl/source/detail/device_binary_image.hpp
sycl/unittests/compression/CompressionTests.cpp

This is a cherry-pick of intel/llvm#19981
**Problem**
There can be race during image decompression. Consider the case when one thread is reading the decompressed buffer while another thread modifies it. This can lead to invalid SPIRV errors emitted by IGC.
**Proposed solution**
Use `std::call_once` to ensure that only one thread does the decompression of an image.

[SYCL] Fix race during image decompression 

---

sycl/doc/extensions/proposed/sycl_ext_oneapi_free_function_kernels.asciidoc

Add some more requirements that the application must follow when launching a free function kernel directly with Level Zero or Open CL.

[SYCL][Doc] Clarify launch of kernels with L0

---

unified-runtime/include/ur_api.h
unified-runtime/scripts/core/kernel.yml
unified-runtime/scripts/core/memory.yml
unified-runtime/scripts/core/sampler.yml
unified-runtime/source/adapters/offload/CMakeLists.txt
unified-runtime/source/adapters/offload/kernel.cpp
unified-runtime/source/adapters/offload/memory.cpp
unified-runtime/source/adapters/offload/sampler.cpp
unified-runtime/source/adapters/offload/ur_interface_loader.cpp
unified-runtime/source/loader/ur_libapi.cpp
unified-runtime/source/ur_api.cpp
unified-runtime/test/conformance/kernel/urKernelSetArgSampler.cpp
unified-runtime/test/conformance/sampler/urSamplerCreate.cpp
unified-runtime/test/conformance/testing/include/uur/checks.h

Image support is optional and depends on UR_DEVICE_INFO_IMAGE_SUPPORT.
Now, entrypoints that involve images should return UNSUPPORTED_FEATURE
if image support is unavailable.
The offload plugin now defines image functions as stubs that return this
"UNSUPPORTED_FEATURE" value.
CTS testing is more rebust. Support for images is now checked before
trying to load the kernel binary, since that binary will not be
available for platforms that don't support images.

[UR] Improve handling for devices/platforms that don't support images

---

sycl/source/detail/device_kernel_info.cpp

See https://github.com/intel/llvm/issues/20134

[SYCL] Work around an assertion failing with handler CTS

---

llvm/lib/SYCLNativeCPUUtils/compiler_passes/vecz/source/transform/control_flow_conversion_pass.cpp

In multiple places, we take a reference to an element in LoopMasks and expect that reference to remain valid. LoopMasks is a DenseMap which does not promise that references to existing elements remain valid as new elements are inserted. We pre-populate LoopMasks to try and avoid this becoming a problem, but we were pre-populating it only with top-level loops, when sub-loops may also cause references to become invalid. Adjust the pre-population to take all loops into account.

[SYCL][Native CPU] Avoid dangling references.

---

sycl/CMakeLists.txt

This PR changes the way CMake sets `__SYCL_COMPILER_VERSION` from using the date of compilation to:
- using `-DSYCL_COMPILER_VERSION=...` if set
- otherwise, running git to get the timestamp of the latest commit, and using that
- falling back to the old behavior if the first two fail
See #19692 for the rationale behind this. TL;DR: Make `__SYCL_COMPILER_VERSION` reproducible. Closes #19692.

[SYCL] set __SYCL_COMPILER_VERSION from CMake variable or git commit timestamp

---

sycl/doc/design/CompilerAndRuntimeDesign.md

Remove mention of manifest, since it is not used in the current design, and soon will be removed from the codebase.

[SYCL][NFC][Doc] Minor cleanup in CompilerAndRuntimeDesign.md

---

clang/lib/Sema/SemaSYCL.cpp
clang/test/CodeGenSYCL/free-function-kernel-expr-as-template-arg.cpp

`constexpr` variables are not forward-declarable so if one is used as a template parameter of a free function kernel argument, we cannot reference the variable, but must inline the value into the integration header.

[SYCL] Allow free function kernel args be templated on integer expressions

---

sycl/include/sycl/detail/vector_arith.hpp
sycl/include/sycl/detail/vector_convert.hpp
sycl/include/sycl/ext/oneapi/experimental/cuda/builtins.hpp
sycl/include/sycl/marray.hpp
sycl/include/sycl/vector.hpp

Highlights:
* No `<exception>` for device compilation
* limit `half`/`bfloat16` to forward declarations
* `is_device_copyable.hpp` is lightweight but it triggers an FE bug when using PCH for device code, so I limited it to forward declaration for now too.
* Remove duplicate/redundant includes

[NFC][SYCL] Cleanup `marray`/`vector` includes

---

sycl/test-e2e/MultiDevice/set_arg_pointer.cpp
unified-runtime/source/adapters/level_zero/command_buffer.cpp
unified-runtime/source/adapters/level_zero/helpers/kernel_helpers.cpp
unified-runtime/source/adapters/level_zero/helpers/kernel_helpers.hpp
unified-runtime/source/adapters/level_zero/kernel.cpp
unified-runtime/source/adapters/level_zero/kernel.hpp

In multi-device context, ensure that pointer kernel arguments are set only for the device associated with the queue being used for kernel launch. Previously, arguments were set for all devices in the kernel's device map, which was unnecessary and potentially incorrect when launching on a specific device.
Same will be done for v2 adapter here: https://github.com/intel/llvm/pull/20179

[UR][L0] Set pointer kernel arguments only for queue's associated device

---

sycl-jit/jit-compiler/lib/rtc/DeviceCompilation.cpp

After https://github.com/intel/llvm/pull/20204 it's easy to stop using the translated command line to compute the hash (by doing that on user's options + format), which in turn allows us to perform this translation in a single place.

[NFCI][SYCL RTC] Move `createCommandline` call to `SYCLToolchain::run`

---

sycl/test-e2e/Basic/fill_accessor.cpp
sycl/test-e2e/Basic/image/image_write.cpp
sycl/test-e2e/FreeFunctionKernels/enum_parameter.cpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_arg_dim.cpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_runtime_dim.cpp
sycl/test-e2e/Matrix/joint_matrix_bfloat16_accumulator.cpp
sycl/test-e2e/Matrix/joint_matrix_half_accumulator.cpp
sycl/test-e2e/bindless_images/array/fetch_sampled_array.cpp
sycl/test-e2e/bindless_images/array/read_sampled_array.cpp
sycl/test-e2e/bindless_images/read_sampled.cpp

Nightly https://github.com/intel/llvm/actions/runs/18101444316

[SYCL][E2E] Fix failing/XPASSsing tests in nightly after driver update

---

sycl/include/sycl/detail/os_util.hpp
sycl/source/detail/os_util.cpp
unified-runtime/source/loader/ur_manifests.hpp

**Problem**
SYCL RT loads `libur_adapter_opencl.so` (https://github.com/intel/llvm/blob/0ff1a5c2b4e4bc56799ec2dd17a89c3c57608890/sycl/include/sycl/detail/os_util.hpp#L129) while UR loads `libur_adapter_opencl.so.0` (https://github.com/intel/llvm/blob/0031df16e41bd0665e85af635b7bfd4e187ce7cd/unified-runtime/source/loader/ur_manifests.hpp#L35).  Note that SYCL RT calls `dlopen()` with `RTLD_NOLOAD` flag, which causes `dlopen()` to fail if this library wasn’t loaded before.
Now, in our Linux compiler packages, `libur_adapter_opencl.so` and `libur_adapter_opencl.so.0` are symlinked so they are the same file, that’s why call to `dlopen()` in SYCL RT succeeds. However, the problem happens with DPCPP PyPi  package, which doesn’t support symlinked files, so call to dlopen() fails because these …

 [SYCL] Lookup versioned OpenCL adapter library as fallback

---

devops/scripts/benchmarks/CONTRIB.md
devops/scripts/benchmarks/benches/base.py
devops/scripts/benchmarks/benches/benchdnn.py
devops/scripts/benchmarks/benches/compute.py
devops/scripts/benchmarks/benches/gromacs.py
devops/scripts/benchmarks/benches/llamacpp.py
devops/scripts/benchmarks/benches/syclbench.py
devops/scripts/benchmarks/benches/test.py
devops/scripts/benchmarks/benches/umf.py
devops/scripts/benchmarks/benches/velocity.py
devops/scripts/benchmarks/git_project.py
devops/scripts/benchmarks/main.py
devops/scripts/benchmarks/utils/flamegraph.py
devops/scripts/benchmarks/utils/unitrace.py
devops/scripts/benchmarks/utils/utils.py

Use GitProject for git operations instead of utility methods. Plus, remove `directory` path in suites' ctors as this path can be obtained from the `options` module.

[Benchmarks] Use GitProject for git operations

---

clang/lib/Sema/SemaSYCL.cpp
clang/test/CodeGenSYCL/free-function-kernel-expr-as-template-arg.cpp
clang/test/CodeGenSYCL/free-function-kernel-type-alias-arg.cpp

This is joined cherry-pick of intel/llvm#20187 and intel/llvm#20123
---
[SYCL] Allow free function kernel args be templated on integer expressions (https://github.com/intel/llvm/pull/20187)
`constexpr` variables are not forward-declarable so if one is used as a
template parameter of a free function kernel argument, we cannot
reference the variable, but must inline the value into the integration
header.
---
[SYCL] Fix error with type aliases used as free function kernel args (https://github.com/intel/llvm/pull/20123)
This PR fixes type name that is being printed as free function kernel
argument type in its forward-declaration in the integration header.
Before the change, we used the original argument type name, which could
be an alias - this patch makes use of the canonical type's name to …

[SYCL][6.3] Cherry-pick free function kernel fixes

---

devops/scripts/benchmarks/git_project.py
devops/scripts/benchmarks/utils/compute_runtime.py

To speed up cloning big repositories, add an option for a shallow clone.

[Benchmarks] Add option for shallow clones

---

sycl/test-e2e/ESIMD/regression/bit_shift_vector_compilation_test_pvc.cpp
sycl/test-e2e/ESIMD/rotate_pvc.cpp

Remove `-std=c++20` from a couple of tests. It is not needed, and if it is then we should use `%cxx_std_optionc++20` instead, for Windows

[SYCL][E2E] minor clean up of test directives

---

llvm/include/llvm/SYCLPostLink/ModuleSplitter.h
llvm/lib/SYCLPostLink/ComputeModuleRuntimeInfo.cpp
llvm/lib/SYCLPostLink/ModuleSplitter.cpp

Apply a few style suggestions from clang-tidy.

[SYCLPostLink][NFC] Fix a few coding style issues.

---

sycl/doc/extensions/proposed/sycl_ext_oneapi_usm_shortcuts.asciidoc

Add a proposed extension specification which allows the application to allocate and deallocate USM without specifying a context or device.

[SYCL][Doc] Add spec for USM shortcuts w/o context

---

devops/scripts/benchmarks/benches/compute.py

Fixes SubmitGraph CPU count scenarios being drawn in the same charts as
SubmitGraph time measurement scenarios making them hard to read.
Also, refactor a bit the `compute.py` module.

[Benchmarks] Fix SubmitGraph CPU count scenarios grouping

---

sycl/source/detail/scheduler/commands.cpp
unified-runtime/include/ur_api.h
unified-runtime/scripts/core/exp-command-buffer.yml
unified-runtime/source/adapters/cuda/command_buffer.cpp
unified-runtime/source/adapters/hip/command_buffer.cpp
unified-runtime/source/adapters/mock/ur_mockddi.cpp
unified-runtime/source/loader/layers/tracing/ur_trcddi.cpp
unified-runtime/source/loader/layers/validation/ur_valddi.cpp
unified-runtime/source/loader/ur_ldrddi.cpp
unified-runtime/source/loader/ur_libapi.cpp
unified-runtime/source/ur_api.cpp

Do not set a zeroed GlobalOffset in kernel parameters - the Unified Runtime layer will handle this correctly.
Note that there is already a similar optimization in https://github.com/intel/llvm/blob/sycl/sycl/source/detail/scheduler/commands.cpp#L2477

[SYCL] do not set zeroed GlobalOffset in kernel parameters

---

sycl/source/detail/program_manager/program_manager.cpp

error: use of deleted function ‘sycl::_V1::detail::Managed<URResource>::Managed(const sycl::_V1::detail::Managed<URResource>&) [with URResource = ur_program_handle_t_*]’
167 |   for (auto Elem : Vec)
|   ^~~

[SYCL][NFC] Fix debug printing of device binary

---

sycl-jit/jit-compiler/lib/rtc/DeviceCompilation.cpp

[NFC][SYCL RTC] Use `std::move` in a few places

---

sycl/source/detail/queue_impl.cpp

Graph recording support was added in [#20250](https://github.com/intel/llvm/pull/20250), but the assertion was not removed.

[SYCL] Remove assertion for graph support for handler-less kernel submit

---

sycl/include/sycl/ext/oneapi/experimental/enqueue_functions.hpp
sycl/include/sycl/khr/free_function_commands.hpp
sycl/include/sycl/queue.hpp

Add a fallback path (handler-based submission) for the handler-less kernel submission path, if kernel function properties are provided.

[SYCL] Fallback path for handler-less kernel properties

---

.github/workflows/sycl-macos-build-and-test.yml
.github/workflows/ur-precommit.yml

MacOS 13 will soon be deprecated on GHA
// https://github.blog/changelog/2025-09-19-github-actions-macos-13-runner-image-is-closing-down/

[CI][UR] Bump MacOS version used in workflows

---

unified-runtime/source/adapters/level_zero/event.cpp
unified-runtime/source/adapters/level_zero/event.hpp
unified-runtime/source/adapters/level_zero/v2/event.cpp
unified-runtime/source/adapters/level_zero/v2/event.hpp

This is a workaround for a case where L0 driver fails to retrieve a timestamp but doesn't return an error. In such case, when event profiling info is queried we check the timestamp value and assume the event was not timestamped even though it was.
This scenario can happen on newer platform with not yet full driver support.

[UR][L0][L0v2] Explicitly mark timestamped events
