mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLOps.td
mlir-sycl/test/Dialect/IR/SYCL/constructor.mlir

[SYCL-MLIR] Add memref of maximum to list of SYCL memrefs

---

libdevice/cmath_wrapper_fp64.cpp
sycl/include/sycl/detail/iostream_proxy.hpp
sycl/include/sycl/detail/pi.hpp

MSVC's defs are different in C++ and CMake :)

Fix a typo in checks for MSVC

---

polygeist/tools/cgeist/Lib/CGCall.cc
polygeist/tools/cgeist/Lib/CGExpr.cc
polygeist/tools/cgeist/Lib/clang-mlir.cc
polygeist/tools/cgeist/Lib/clang-mlir.h
polygeist/tools/cgeist/Lib/utils.cc
polygeist/tools/cgeist/Lib/utils.h
polygeist/tools/cgeist/Test/Verification/sycl/assert.cpp

`Basic/group_local_id.cpp` passes after this PR.

[SYCL-MLIR] Generate LLVM functions in `gpu.module`

---

mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLOpInterfaces.td
mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLOpTraits.h
mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLOps.td
mlir-sycl/lib/Dialect/IR/SYCLTraits.cpp
mlir-sycl/test/Dialect/IR/SYCL/invalid.mlir
mlir-sycl/test/Dialect/IR/SYCL/ops.mlir

Define high-level operations to retrieve information from the SYCL index space.

[SYCL-MLIR] Define SYCL index space operations

---

sycl/include/sycl/ext/oneapi/experimental/bfloat16_math.hpp

Signed-off-by: jinge90 <ge.jin@intel.com>

[SYCL] Add generic fabs imp for bf16

---

sycl/include/sycl/buffer.hpp

[SYCL] Fix missed hostData in buffer constructor

---

sycl/doc/extensions/experimental/sycl_ext_intel_esimd/sycl_ext_intel_esimd.md

[ESIMD][DOC][NFC] Fix the DPAS operand types table for PVC

---

mlir-sycl/lib/Dialect/IR/SYCLOpsTypes.cpp
mlir-sycl/lib/Transforms/Inliner.cpp
polygeist/lib/polygeist/Passes/Mem2Reg.cpp
polygeist/tools/cgeist/Lib/CGExpr.cc

[SYCL-MLIR][NFC] Fix warnings in polygeist and mlir-sycl

---

buildbot/configure.py
mlir-sycl/.clang-tidy
polygeist/.clang-tidy
polygeist/lib/polygeist/Passes/AffineReduction.cpp

This PR refactors the polygeist AffineReduction pass and adds debug traces to the pass. 

[SYCL-MLIR][NFI]: Refactor affine reduction

---

.github/CODEOWNERS

Add code owner for OpenCL CPU RT and SYCL transform folders.

[OpenCL] Add code owner for OpenCL CPU RT

---

sycl/plugins/opencl/CMakeLists.txt
sycl/plugins/opencl/pi_opencl.cpp
sycl/plugins/opencl/pi_opencl.hpp
sycl/test/abi/pi_opencl_symbol_check.dump

This reverts commit dcbd6e500fb95248f96ec24deeefa6ca37c346fc.

Revert "[OpenCL] Add support for cslice partitioning (#7963)"

---

mlir-sycl/test/Conversion/SYCLToSPIRV/grid-ops.mlir

This attribute is not needed and may lead to confusion.

[SYCL-MLIR][Test] Drop optional attribute in SYCLToSPIRV tests

---

sycl/plugins/unified_runtime/pi2ur.hpp

[SYCL][NFC] Remove unused variable

---

sycl/plugins/unified_runtime/pi_unified_runtime.cpp

[SYCL][NFC] Remove unused variables

---

sycl/plugins/level_zero/pi_level_zero.cpp

[SYCL][L0] Use copy engine for buffer init/copy and 1D read/write

---

sycl/plugins/cuda/pi_cuda.cpp

This `ReleaseGuard` was only used in one entry point, for the `parent_buffer` in buffer partition, but the constructor of `_pi_mem` is already retaining the parent buffer, so it would retain it twice, and since the guard is getting dismissed in the entry point, it's likely we were having parent buffers with an incorrect reference count.

[SYCL][CUDA] Remove unused ReleaseGuard class

---

.github/workflows/windows_test_comment_trigger.yml

The old version is deprecated.

[CI] Update github-script version

---

libclc/utils/libclc-remangler/LibclcRemangler.cpp

In addition to slightly reducing the cognitive overhead of all the different string types, this fixes two real-live bugs:
1.  `std::atoi` is impossible to use correctly. We'd incorrectly assume invalid address spaces mangling as AS0 because `atoi` return zero on error. This has been replaced with `StringRef::getAsInteger`
2. A crash handling nested names due to incorrect use of `string::find_first_not_of("__spv::")` which searches for the first character that is not one one of the list of characters given by the first argument. The intention was to split on that substring, which `StringRef` has easy interfaces for achieving. Names in nested namespaces can now be parsed without a crash

[libclc] Prefer StringRef fixing string handling bugs

---

sycl/source/detail/device_global_map_entry.cpp

Fix post-commit: https://github.com/intel/llvm/actions/runs/4244006981/jobs/7377519363

[SYCL] Fix copy elision warning

---

llvm/lib/Support/SimpleTable.cpp

This change fixes the following issues:
1. AUTO_CAUSES_COPY
2. Improper use of negative values.
Thanks

Fix static analyzer issues

---

sycl-fusion/passes/kernel-fusion/SYCLKernelFusion.cpp
sycl/source/detail/jit_compiler.cpp

As the SYCL runtime compares raw memory to detect identical parameter values for JIT compilation, it may detect two parameters as identical that have identical byte size, but different types in LLVM, e.g., `i64` and `[1 x i64]`. 
In this case, both parameters need to be preserved. This PR adds this logic to the JIT compiler. 
It also skips identical parameter detection for scalar arguments and instead prefers constant propagation to remove scalar parameters as part of the JIT compilation process.

[SYCL][Fusion] Improve std_layout param handling

---

polygeist/tools/cgeist/Lib/clang-mlir.cc
polygeist/tools/cgeist/Test/Verification/cmp.cpp
polygeist/tools/cgeist/Test/Verification/combif.c
polygeist/tools/cgeist/Test/Verification/sec.c
polygeist/tools/cgeist/Test/Verification/snus.c

Ensure same fcmp order as clang.

[SYCL-MLIR] Ensure same fcmp order as clang

---

polygeist/lib/Dialect/Polygeist/Transforms/RaiseToAffine.cpp

Also added traces and transformation report.

[SYCL-MLIR]: Raise to affine refactor

---

.github/workflows/sycl_stale_issues.yml

[CI] Update stale action version

---

sycl-fusion/passes/kernel-fusion/Builtins.cpp

C++ does not define the evaluation order of function call arguments, which was causing a different output with different compilers. This fixes this issue and fixes lit test reported here: https://github.com/intel/llvm/pull/8504#issuecomment-1464192942.

[SYCL][Fusion] Make GID remapping instruction order deterministic

---

sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp

Complementary test PR https://github.com/intel/llvm-test-suite/pull/1645

[SYCL][ESIMD] Fix lsc_prefetch_2d

---

llvm/test/Transforms/SPIRITTAnnotations/itt_atomic_load.ll
llvm/test/Transforms/SPIRITTAnnotations/itt_atomic_store.ll
llvm/test/Transforms/SPIRITTAnnotations/itt_barrier.ll
llvm/test/Transforms/SPIRITTAnnotations/itt_start_finish.ll

Remove useless option. option was renamed in https://reviews.llvm.org/D146103.

Remove renamed options

---

llvm/test/SYCLLowerIR/printf_addrspace/generic_as.ll
llvm/test/SYCLLowerIR/printf_addrspace/generic_as_no_opt.ll
llvm/test/SYCLLowerIR/printf_addrspace/generic_as_variadic.ll
llvm/test/SYCLLowerIR/printf_addrspace/generic_as_variadic_no_opt.ll

Remove useless option. option was renamed in https://reviews.llvm.org/D146103.

Remove useless option

---

llvm/test/CodeGen/AMDGPU/global-offset-dbg.ll
llvm/test/CodeGen/AMDGPU/global-offset-multiple-calls-from-one-function.ll
llvm/test/CodeGen/AMDGPU/global-offset-multiple-entry-points.ll
llvm/test/CodeGen/AMDGPU/global-offset-simple.ll
llvm/test/CodeGen/AMDGPU/local-accessor-to-shared-memory-basic-transformation.ll
llvm/test/CodeGen/AMDGPU/local-accessor-to-shared-memory-multiple-functions.ll
llvm/test/CodeGen/AMDGPU/local-accessor-to-shared-memory-no-entry-points.ll
llvm/test/CodeGen/AMDGPU/local-accessor-to-shared-memory-preserves-types.ll
llvm/test/CodeGen/NVPTX/global-offset-dbg.ll
llvm/test/CodeGen/NVPTX/global-offset-multiple-calls-from-one-function.ll
llvm/test/CodeGen/NVPTX/global-offset-multiple-entry-points.ll
llvm/test/CodeGen/NVPTX/global-offset-simple.ll
llvm/test/CodeGen/NVPTX/local-accessor-to-shared-memory-basic-transformation.ll
llvm/test/CodeGen/NVPTX/local-accessor-to-shared-memory-multiple-annotations.ll
llvm/test/CodeGen/NVPTX/local-accessor-to-shared-memory-multiple-functions.ll
llvm/test/CodeGen/NVPTX/local-accessor-to-shared-memory-no-entry-points.ll
llvm/test/CodeGen/NVPTX/local-accessor-to-shared-memory-preserves-types.ll
llvm/test/SYCLLowerIR/byval_arg.ll
llvm/test/SYCLLowerIR/convergent.ll
llvm/test/SYCLLowerIR/group_local_memory.ll
llvm/test/SYCLLowerIR/printf_addrspace/diagnose_bad_wrapper_inlining.ll
llvm/test/SYCLLowerIR/printf_addrspace/diagnose_compile_time_unknown.ll
llvm/test/SYCLLowerIR/printf_addrspace/diagnose_extra_user_wrapper_no_opt.ll
llvm/test/SYCLLowerIR/printf_addrspace/generic_as_negative_checks.ll

Update sycl only tests after https://reviews.llvm.org/D146103.

Rename -enable-new-pm -> -bugpoint-enable-legacy-pm

---

mlir-sycl/include/mlir/Conversion/SYCLPasses.td
mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLOps.td
mlir-sycl/lib/Conversion/SYCLToLLVM/SYCLToLLVM.cpp
mlir-sycl/test/Conversion/SYCLToLLVM/sycl-methods-to-llvm-m32.mlir

Address code review comment https://github.com/intel/llvm/pull/8703#discussion_r1144868678.

[SYCL-MLIR][SYCLToLLVM] Add option `indexBitwidth`

---

clang/lib/Driver/ToolChains/Clang.cpp
clang/test/Driver/sycl-spirv-ext.c

Right now it's only working for FPGA H/W while it should also work for FPGA emulator.

[SYCL] Enable SPV_INTEL_fpga_invocation_pipelining_attributes

---

sycl/test-e2e/ExtraTests/README.md

...after the llvm-test-suite merge.

[NFC][SYCL] Update sycl/test-e2e/ExtraTests/README.md

---

.github/workflows/sycl_linux_build_and_test.yml
.github/workflows/sycl_post_commit.yml
.github/workflows/sycl_precommit.yml
devops/actions/e2e-tests/action.yml
devops/test_configs.json

* Rename the action
* Remove test_ref param
* Rename check_sycl_all -> targets in parameters

[CI][SYCL] Cleanup post llvm-test-suite move

---

sycl/plugins/unified_runtime/CMakeLists.txt
sycl/plugins/unified_runtime/pi2ur.hpp
sycl/plugins/unified_runtime/ur/adapters/level_zero/ur_level_zero.cpp
sycl/plugins/unified_runtime/ur/adapters/level_zero/ur_level_zero_common.cpp
sycl/plugins/unified_runtime/ur/adapters/level_zero/ur_loader_interface.cpp

Compile UR L0 adapter as a standalone library
Signed-off-by: Brandon Yates <brandon.yates@intel.com>

[SYCL][UR] Link UR PI against UR Loader

---

.github/workflows/sycl_linux_build_and_test.yml
.github/workflows/sycl_post_commit.yml
.github/workflows/sycl_precommit.yml
devops/actions/e2e-tests/action.yml
devops/test_configs.json

* Rename the action
* Remove test_ref param
* Rename check_sycl_all -> targets in parameters

[CI][SYCL] Cleanup post llvm-test-suite move (#8894)

---

polygeist/lib/Dialect/Polygeist/Transforms/LICM.cpp

Add `LICMCandidate` class to indicate all the other operations an operation depends on to be hoisted.
It will also be used to store version conditions needed for the operation to be hoisted.

[SYCL-MLIR][NFC][LICM] Add `LICMCandidate` class 

---

mlir-sycl/lib/Conversion/SYCLToLLVM/SYCLToLLVM.cpp
mlir-sycl/test/Conversion/SYCLToLLVM/sycl-grid-ops-to-llvm-typed-pointer.mlir
mlir-sycl/test/Conversion/SYCLToLLVM/sycl-grid-ops-to-llvm.mlir
mlir-sycl/test/Conversion/SYCLToLLVM/sycl-methods-to-llvm-typed-pointer.mlir
mlir-sycl/test/Conversion/SYCLToLLVM/sycl-methods-to-llvm.mlir

Assume OpenCL backend for now.

[SYCL-MLIR] Use `-client-api` option in `-convert-sycl-to-llvm`

---

sycl/test-e2e/InvokeSimd/Feature/ImplicitSubgroup/popcnt.cpp
sycl/test-e2e/InvokeSimd/Feature/popcnt.cpp
sycl/test-e2e/InvokeSimd/Regression/call_vadd_1d_loop.cpp
sycl/test-e2e/InvokeSimd/Regression/nbarrier_exec_in_order.cpp
sycl/test-e2e/InvokeSimd/Regression/slm_load_store.cpp

Driver issue fixed some time ago. Recently it started to pass 'unexpectedly' in some CIs.

Enable InvokeSimd/call_vadd_1d_loop for PVC, disable InvokeSimd popcnt tests

---

sycl/test-e2e/InvokeSimd/Spec/simd_mask_merge.cpp

Right now it's returning 1 so the test is failing.

[SYCL][ESIMD] Fix return value for test

---

polygeist/tools/cgeist/driver.cc

`applyPassManagerCLOptions` now returns a `LogicalResult`. Propagate on failure.

[SYCL-MLIR] Propagate applyPassManagerCLOptions failures

---

sycl/plugins/esimd_emulator/pi_esimd_emulator.cpp

[SYCL][NFC] Fix unused parameter warnings in esimd emu plugin

---

.github/CODEOWNERS

Added end to end tests and kernel fusion design document.

[CODEOWNER] Update onwership for kernel fusion

---

mlir/lib/Target/LLVMIR/ModuleImport.cpp
mlir/test/Target/LLVMIR/Import/basic.ll

In LLVM, having an invoke instruction branching to a block with a phi
node receiving the invoke instruction result as an argument is
perfectly legal. However, the translation of this construct to MLIR
would result in an invoke with its result being used as a block
argument to a successor, i.e., the operation result would be used in
its definition.
In order to fix this issue due to different IR structures (phi nodes
vs block arguments), this construct is interpreted with an llvm.invoke
operation branching to a dummy block having a single llvm.br operation
passing the required block arguments (including the result of the
llvm.invoke operation) to the actual successor block.
Differential Revision: https://reviews.llvm.org/D148313

[mlir][llvm] Handle invoke op branching to block with its result as an argument

---

sycl/doc/extensions/template.asciidoc

Update the extension template to list the latest rev of the SYCL spec.

[SYCL][DOC] Update SYCL rev in extension template

---

sycl/doc/developer/ABIPolicyGuide.md

update guide with dates for current ABI breaking window and document steps of what to do when you break

[SYCL] [NFC] update ABI policy guide

---

sycl/unittests/xpti_trace/QueueApiFailures.cpp

Tracked in https://github.com/intel/llvm/issues/9137

[SYCL] Disable flaky QueueKernelAsync test

---

sycl/plugins/level_zero/pi_level_zero.cpp
sycl/plugins/level_zero/pi_level_zero.hpp
sycl/plugins/unified_runtime/CMakeLists.txt
sycl/plugins/unified_runtime/ur/adapters/level_zero/ur_level_zero.cpp
sycl/plugins/unified_runtime/ur/adapters/level_zero/ur_level_zero.hpp
sycl/plugins/unified_runtime/ur/adapters/level_zero/ur_level_zero_common.cpp
sycl/plugins/unified_runtime/ur/adapters/level_zero/ur_level_zero_common.hpp
sycl/plugins/unified_runtime/ur/adapters/level_zero/ur_level_zero_mem.cpp

and replace pi_cast with ur_cast
Signed-off-by: Jaime Arteaga <jaime.a.arteaga.molina@intel.com>

[SYCL][UR][L0] Move some code to ur_level_zero_common

---

devops/scripts/generate_test_matrix.js

The AWS CUDA testing in pre-commit unwillingly got disabled in #8656.
This PR re-enables the AWS CUDA testing in pre-commit.

[CI] Fix AWS CUDA CI in precommit

---

sycl/source/detail/kernel_arg_mask.hpp
sycl/source/detail/kernel_program_cache.hpp

Fix build failure reported in https://github.com/intel/llvm/issues/9168

[SYCL] Fix build by adding missing includes

---

sycl/test-e2e/Regression/same_unnamed_kernels.cpp

https://github.com/intel/llvm/issues/9174

Disable failing Regression/same_unnamed_kernels.cpp

---

sycl/source/detail/context_impl.cpp

Fixes post-commit failure after https://github.com/intel/llvm/pull/9215.

[SYCL][NFC] Ignore unused argument in copy from host

---

sycl/test-e2e/InvokeSimd/Regression/ImplicitSubgroup/nbarrier_basic.cpp
sycl/test-e2e/InvokeSimd/Regression/nbarrier_basic.cpp

I manually confirmed these pass with the latest GPU driver.

[SYCL][ESIMD][E2E] Reenable tests that pass now

---

sycl/plugins/level_zero/pi_level_zero.cpp

Fixes regression introduced by https://github.com/intel/llvm/pull/8601

[SYCL][L0] Avoid leak of active barriers' events

---

llvm/lib/SYCLLowerIR/CMakeLists.txt
llvm/test/tools/sycl-post-link/sycl-post-link-test.ll

It has an important opaque pointers fix.

[SYCL][ESIMD] Bump vc-intrinsics version

---

sycl/test-e2e/GroupAlgorithm/SYCL2020/reduce_over_group_size.cpp
sycl/test-e2e/SubGroup/scan_spirv13.cpp
sycl/test-e2e/USM/copy2d.cpp
sycl/test-e2e/USM/memcpy2d.cpp

[SYCL-MLIR][Test E2E] Make tests that time out fail early

---

sycl/test-e2e/Basic/image/image_array.cpp

Fixup after f5ea811a4ebcdc5fe0c51378e0dbb511f04f738c

[SYCL] Fix unsupported platform for image_array.cpp

---

sycl/gdb/libsycl.so-gdb.py

Here are two small formatting patches and one patch that helps GDB to support reading local_accessors on GPU from SLM.
Detailed explanation is in the commit msg.

[SYCL][GDB] Xmethods slm support

---

sycl/include/sycl/ext/oneapi/experimental/device_architecture.hpp

Spec update: https://github.com/intel/llvm/pull/8840

[SYCL] Remove lambda parameter to "if_architecture_is"

---

sycl/gdb/libsycl.so-gdb.py

[GDB] Add note on coding standards and formatting with black.

---

sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp

2D block stateless load/store API.

[SYCL][ESIMD] Fix bug in get methods in config_2d_mem_access class for

---

sycl/include/sycl/stream.hpp

This PR fixes [stream](https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/Basic/stream/stream.cpp#L1) tests that resulted in hangs for CUDA.
An implication of using `-ffast-math` is that the compiler is not required to honour `nan` and `inf`. As a result calls to [checkForInfNan](https://github.com/intel/llvm/blob/sycl/sycl/include/sycl/stream.hpp#L378) were optimized away breaking the logic of `ScalarToStr`. The patch  provides a manual way of detecting `nan` and `inf` when in fast math mode.

[SYCL] Correctly handle special values in fast math mode

---

sycl/include/sycl/image.hpp

The SYCL 1.2.1 image class publicly inherits from unsampled_image_common which exposes both set_final_data and set_write_back, but the image class itself redefines these in the exact same way. This commit removes the redundant definitions of these member functions in the image class, making it rely solely on the interfaces defined by unsampled_image_common.

[SYCL] Remove redundant set_final_data and set_write_back members

---

sycl/test-e2e/ESIMD/BitonicSortKv2.hpp
sycl/test-e2e/ESIMD/BitonicSortKv2_emu.cpp

Another unrolling issue, similar to https://github.com/intel/llvm/commit/6a13e45c5abd3f3d74d81efba23e1578095afd67
Also fix a typo.

[SYCL][ESIMD][E2E] Fix BitonicSortKv2 tests on emulator

---

llvm/lib/SYCLLowerIR/CMakeLists.txt

It has another important opaque pointers fix.

[SYCL][ESIMD] Bump VC intrinsics version

---

sycl/test-e2e/Matrix/XMX8/joint_matrix_bf16_fill_k_cache.cpp
sycl/test-e2e/Matrix/XMX8/joint_matrix_bf16_fill_k_cache_init.cpp
sycl/test-e2e/Matrix/XMX8/joint_matrix_bf16_fill_k_cache_unroll.cpp
sycl/test-e2e/Matrix/XMX8/joint_matrix_bf16_fill_k_cache_unroll_init.cpp
sycl/test-e2e/Matrix/XMX8/joint_matrix_bfloat16_array.cpp
sycl/test-e2e/Matrix/element_wise_all_ops_int8_impl.hpp
sycl/test-e2e/Matrix/element_wise_all_ops_int8_packed_impl.hpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache.cpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_impl.hpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_init.cpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_unroll.cpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_unroll_init.cpp
sycl/test-e2e/Matrix/joint_matrix_bfloat16_array.cpp
sycl/test-e2e/Matrix/joint_matrix_bfloat16_array_impl.hpp

New tests for arrays of Joint Matrix

[SYCL][JointMatrix] New tests for arrays of Joint Matrix

---

sycl/include/sycl/detail/generic_type_lists.hpp
sycl/include/sycl/types.hpp
sycl/plugins/level_zero/pi_level_zero.cpp
sycl/plugins/opencl/pi_opencl.cpp
sycl/test-e2e/ESIMD/regression/Inputs/dgetrf.hpp
sycl/test-e2e/ESIMD/regression/dgetrf.cpp
sycl/test-e2e/ESIMD/slm_alloc_many_kernels_one_func.cpp
sycl/test/basic_tests/vectors/vectors.cpp

[SYCL-MLIR] pulldown (20230526)

---

sycl/include/sycl/sycl_span.hpp

Thank you for reviewing the PR for #9348

[SYCL] fix the error SIZE_MAX not declared

---

mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLTypes.h
mlir-sycl/lib/Dialect/SYCL/IR/SYCLTypes.cpp
polygeist/include/mlir/Dialect/Polygeist/Transforms/Passes.h
polygeist/lib/Dialect/Polygeist/Analysis/MemoryAccessAnalysis.cpp
polygeist/lib/Dialect/Polygeist/Transforms/KernelDisjointSpecialization.cpp
polygeist/lib/Dialect/Polygeist/Transforms/LoopInternalization.cpp
polygeist/test/polygeist-opt/sycl/loop_internalization.mlir

Only transforms kernel body function with `nd_item` argument.

[SYCL-MLIR][LoopInternalization] Add limitations on candidates

---

clang/lib/Driver/OffloadBundler.cpp

I believe the issue has been introduced in #9572.

[OffloadBundler] Fix build with clang-10

---

devops/scripts/install_build_tools.sh

I will remove unneeded package (lz4 or/and zstd) once we settle which one is the best for our use.

[SYCL][CI] Add zstd to our build image

---

.github/workflows/sycl_precommit.yml
.github/workflows/sycl_windows_build_and_test.yml

Follow-up for #9589 implementing the same as it on Windows.

[SYCL][CI][WIN] Skip some checks depending on what files have changed

---

sycl/plugins/unified_runtime/ur/adapters/level_zero/ur_level_zero_queue.cpp

After the last command in an in-order queue has completed, clean up the rest of the events so they are available for later reuse.

[SYCL][UR][L0] Clean up events on queue wait

---

.github/workflows/sycl_precommit.yml

Bug-fix for https://github.com/intel/llvm/pull/9709.

[CI] Fix pre-commit job dependencies on Windows

---

sycl/plugins/cuda/pi_cuda.cpp

Report major.minor instead of major.major

[SYCL][CUDA] Fix info::device::version

---

sycl/test-e2e/Reduction/reduction_big_data.cpp
sycl/test-e2e/Reduction/reduction_complex_nums.cpp
sycl/test-e2e/Reduction/reduction_nd_N_queue_shortcut.cpp
sycl/test-e2e/Reduction/reduction_nd_reducer_skip.cpp
sycl/test-e2e/Reduction/reduction_range_1d_reducer_skip.cpp
sycl/test-e2e/Reduction/reduction_range_2d_dw_reducer_skip.cpp
sycl/test-e2e/Reduction/reduction_range_3d_rw_reducer_skip.cpp

We should not run ZE_DEBUG tests on Windows.

[SYCL] Disable the ZE_DEBUG tests on Windows

---

polygeist/lib/Dialect/Polygeist/Transforms/LoopInternalization.cpp
polygeist/test/polygeist-opt/sycl/loop_internalization.mlir

This PR does loop internalization code generation for affine loops.

[SYCL-MLIR][LoopInternalization] Transformation code generation (part 3)

---

devops/actions/e2e-tests/action.yml

[CI] Remove ROCm LD_LIBRARY_PATH setup

---

.github/workflows/aws.yml
.github/workflows/sycl_linux_build_and_test.yml

To remove code duplication and simplify caller's code.

[CI] Use reusable workflow for AWS start/stop job

---

polygeist/lib/Dialect/Polygeist/Analysis/MemoryAccessAnalysis.cpp
polygeist/lib/Dialect/Polygeist/Transforms/LoopInternalization.cpp

This PR fixes some compile time failures encountered while compiling SYCL-Bench with `LoopInternalization`.

[SYCL-MLIR][LoopInternalization] Add limitations

---

sycl/source/detail/graph_impl.hpp

Together with [PR#9949](https://github.com/intel/llvm/pull/9949):
Fix post-commit failures after [PR#9728](https://github.com/intel/llvm/pull/9728)

[SYCL][Graph] Fix unannotated fall-through between switch labels

---

sycl/source/detail/graph_impl.cpp
sycl/source/detail/graph_impl.hpp

[SYCL-MLIR] pulldown (20230619)

---

devops/dependencies.json
libclc/utils/libclc-remangler/LibclcRemangler.cpp
sycl/doc/design/DeviceConfigFile.md
sycl/doc/extensions/proposed/sycl_ext_oneapi_complex.asciidoc
sycl/doc/index.rst
sycl/include/sycl/ext/oneapi/experimental/sycl_complex.hpp
sycl/include/sycl/group_algorithm.hpp
sycl/include/sycl/handler.hpp
sycl/plugins/level_zero/CMakeLists.txt
sycl/test-e2e/GroupAlgorithm/exclusive_scan_sycl2020.cpp
sycl/test-e2e/GroupAlgorithm/inclusive_scan_sycl2020.cpp
sycl/test-e2e/GroupAlgorithm/reduce_sycl2020.cpp
sycl/test-e2e/GroupAlgorithm/support.h
sycl/test/extensions/test_complex.cpp

[SYCL-MLIR] pulldown (20230620)

---

sycl/test-e2e/AtomicRef/atomic_memory_order_seq_cst.cpp

The atomic_memory_order_seq_cst.cpp test does not currently check for buffer allocation limitations. This commit makes it consider `info::device::max_mem_alloc_size` when selecting the number of iterations.

[SYCL] Limit allocation size in atomic_memory_order_seq_cst test

---

sycl/plugins/unified_runtime/README.md

Add a readme to point contributors to the UR repository so PI changes which require changes to the UR spec are correctly handled

[SYCL][UR][Doc] Add README.md for the Unified Runtime directory

---

polygeist/lib/Dialect/Polygeist/Transforms/LoopInternalization.cpp

A pseudocode example is added to better understand the optimization for reader of the pass.

[SYCL-MLIR][NFC][LoopInternalization] Add an example

---

sycl/include/sycl/detail/pi.hpp

This PR fixes a post commit failure introduced by https://github.com/intel/llvm/pull/9635

Add __SYCL_NATIVE_CPU_PLUGIN_NAME for MacOS

---

.github/workflows/sycl_cleanup.yml

This restores sycl_cleanup action that had been removed in commit ece35ad6cb604502eb4f5296a4e0c93461aefc55.

Partially revert "[CI] Remove artifacts cleanup task (#10230)"

---

polygeist/test/polygeist-opt/sycl/loop_internalization_invalid.mlir
polygeist/test/polygeist-opt/sycl/loop_internalization_unroll.mlir

address review comment https://github.com/intel/llvm/pull/10280#pullrequestreview-1522476992.

[SYCL-MLIR][LoopInternalization] Add statistic lit tests

---

.github/workflows/sycl_precommit.yml

So that testing can be triggered with merge PRs.

[SYCL-MLIR] Run tests even if CI files are modified

---

mlir/include/mlir/Dialect/LLVMIR/LLVMIntrinsicOps.td
mlir/test/Target/LLVMIR/Import/intrinsic.ll

Apply review comments in https://reviews.llvm.org/D154842

[SYCL-MLIR] Update annotation intrinsics definition

---

.github/workflows/linux_matrix_e2e_on_nightly.yml
.github/workflows/linux_single_e2e.yml
.github/workflows/sycl_linux_build_and_test.yml
.github/workflows/sycl_nightly.yml
.github/workflows/sycl_post_commit.yml
.github/workflows/sycl_precommit.yml
devops/actions/cached_checkout/action.yml

I plan to use the extra level of explicit control to lock in build and e2e-tests steps in pre-commit in the next PR.

[CI] Change cached_checkout's bool `merge` param to `merge_ref`

---

sycl/test/check_device_code/native_cpu/native_cpu_subhandler.cpp

Improves the lit checks changes that were done in https://github.com/intel/llvm/pull/10350

[SYCL][NATIVECPU] Better lit checks for subhandler test (fix for post commit failure)

---

.github/workflows/linux_single_e2e.yml

- auto-deduce HIP_PLATFORM/AMD_ARCH CMake params
- better inputs descriptions
- Add show-pass/xfail to LIT_OPTS

[CI] Improve linux_single_e2e.yml

---

sycl/test-e2e/InvokeSimd/Regression/call_vadd_1d_loop_naive.cpp
sycl/test-e2e/InvokeSimd/Spec/simd_size/simd8.cpp

See also https://github.com/intel/llvm/issues/10369.

[SYCL][E2E] Disable tests that cause hangs on Linux GEN12

---

sycl/plugins/unified_runtime/ur/adapters/level_zero/program.cpp

Also, remove some printfs that were commented.

[SYCL][UR][L0] Correctly pass OwnNativeHandle property for Module

---

clang/docs/ClangOffloadPackager.rst

Fixed a typo and made a minor formatting to fit into 80-char line length
limit.

[Doc][OffloadPackager] Add SYCL offload kind

---

llvm/lib/IR/LLVMContextImpl.cpp

Wrong merge in this commit https://github.com/intel/llvm/commit/100d1292c40802fb4b19363292d5db6fc9172d06.
This commit is to fix it.

Fix lit tests failure

---

.github/workflows/sycl_precommit_linux.yml

To prevent security vulnerability.

[SYCL-MLIR][CI] Change `pull_request_target` to `pull_request`

---

.github/workflows/linux_single_e2e.yml

The bug has been introduced in https://github.com/intel/llvm/pull/10538, this PR fixes it.

[CI] Fix CMake opts handling

---

polygeist/include/mlir/Dialect/Polygeist/Analysis/SYCLNDRangeAnalysis.h
polygeist/lib/Dialect/Polygeist/Analysis/CMakeLists.txt
polygeist/lib/Dialect/Polygeist/Analysis/SYCLIDAndRangeAnalysis.cpp
polygeist/lib/Dialect/Polygeist/Analysis/SYCLNDRangeAnalysis.cpp
polygeist/test/lib/Dialect/Polygeist/CMakeLists.txt
polygeist/test/lib/Dialect/Polygeist/TestIDAndRangeAnalysis.cpp
polygeist/test/lib/Dialect/Polygeist/TestNDRangeAnalysis.cpp
polygeist/test/polygeist-opt/sycl/nd-range-analysis.mlir
polygeist/tools/polygeist-opt/polygeist-opt.cpp

Analysis building on the `id/range` analysis to infer `nd_range` properties.

[SYCL-MLIR] Add SYCL `nd_range` analysis

---

sycl/doc/developer/ABIPolicyGuide.md

Next one is expected to be around same time frame, Apr-July 2024

[SYCL][DOC] Close the ABI breaking changes window

---

.github/workflows/sycl_linux_build_and_test.yml

We need it present in the default branch for it to appear in the Github interface. Once it's there, I will be able to create another branch with changes to it and be able to test them.

[CI] Add workflow_dispatch trigger to sycl_linux_build_and_test.yml

---

.github/workflows/sycl_linux_build_and_test.yml

That would allow to reduce number of input parameters that is crucial to enable manual run trigger for the workflow where that number is limited to 10.

[CI] Deduce compress/decompress command based on archive extension

---

.github/workflows/sycl_precommit_linux.yml

Changes there don't have effect on pull_request_target trigger.

[CI] Don't run pre-commit if only .github/workflows was modified

---

sycl/plugins/unified_runtime/ur/adapters/level_zero/event.cpp

Avoid another loop traversal to just increment the refcount of events when creating the event list

[SYCL][UR][L0] Increment count on events on assignment

---

sycl/plugins/unified_runtime/ur/adapters/level_zero/usm.hpp

"error: 'USMMemoryProvider' has virtual functions but non-virtual destructor [-Werror,-Wnon-virtual-dtor]"

[SYCL][UR][L0] fix non-virtual destructor error

---

sycl/plugins/unified_runtime/ur/adapters/level_zero/device.cpp

Fix missing field on initializer.

[SYCL][UR] Fix device partition queries (3)

---

mlir-sycl/lib/Dialect/SYCL/Transforms/ConstantPropagation.cpp

Avoid lambda outliving captured values:
- Pass `symbolTable` by reference and capture by reference in lambda instead of defining in function body to avoid errors when it goes out of scope;
- Capture `op` by value;
- Init-capture `isConstant`
- Drop default capture and add comment explaining why
This change enables use of `llvm::make_filter_range` so no filtering needs to be done when using the range.

[SYCL-MLIR][sycl-constant-propagation] Fix `getConstantArgs` lambda

---

sycl/plugins/unified_runtime/CMakeLists.txt
sycl/plugins/unified_runtime/ur/adapters/level_zero/platform.cpp

This updates the Unified Runtime FetchContent to the v0.7 tag.

[SYCL][UR] Update Unified Runtime to v0.7

---

.github/workflows/sycl_linux_run_tests.yml
sycl/include/sycl/range.hpp
sycl/plugins/unified_runtime/pi2ur.hpp
sycl/plugins/unified_runtime/ur/adapters/cuda/queue.cpp
sycl/test/basic_tests/range.cpp

[SYCL-MLIR] pulldown (20230804)

---

clang/include/clang/Driver/Options.td

JR: [CMPLRLLVM-50215](https://jira.devtools.intel.com/browse/CMPLRLLVM-50215)

Fix build error (support -fno-gpu-rdc in clang -cc1).

---

.github/workflows/sycl_detect_changes.yml
.github/workflows/sycl_exp_precommit.yml
.github/workflows/sycl_linux_run_tests.yml
.github/workflows/sycl_precommit_aws.yml
llvm/lib/Transforms/IPO/DeadArgumentElimination.cpp
sycl/test/check_device_code/buffer_location_codegen.cpp
sycl/test/esimd/dae.cpp
sycl/test/esimd/genx_func_attr.cpp
sycl/test/esimd/slm_init_specconst_size.cpp

[SYCL-MLIR] pulldown (20230805)

---

polygeist/tools/cgeist/driver.cc

With 599f1a418518, we use clang BackendUtils rather than polygeist basic setup.
So runOptimizationPipeline is no longer needed.

[SYCL-MLIR] Remove runOptimizationPipeline

---

.github/workflows/sycl_linux_build.yml
.github/workflows/sycl_precommit_linux.yml

Missed that piece when switching pre-commit to pull_request trigger.

[CI][PreCommit] Don't skip E2E if some check-* failed

---

.github/workflows/sycl_precommit_linux.yml

First (incomplete) part has been merged in #10759.

[CI] Finally fix drivers update testing

---

llvm-spirv/lib/SPIRV/SPIRVReader.cpp
llvm-spirv/test/create-placeholders-for-phi-operands.ll
llvm-spirv/test/extensions/INTEL/SPV_INTEL_variable_length_array/basic.ll
llvm-spirv/test/extensions/INTEL/SPV_INTEL_variable_length_array/negative.ll
llvm-spirv/test/extensions/INTEL/SPV_INTEL_variable_length_array/vla_spec_const.ll

Signed-off-by: Sidorov, Dmitry <dmitry.sidorov@intel.com>

Cherry pick of 'Update stacksave and stackrestore after 25bc999d (KhronosGroup/SPIRV-LLVM-Translator/#2122)'

---

clang/test/SemaSYCL/device_has_ast.cpp
clang/test/SemaSYCL/uses_aspects_ast.cpp

Caused by commit cad3130a23daa023d5bbf42b8ec8c06aa0532abf,

Update checking aspect tests.

---

llvm/lib/Transforms/InstCombine/InstCombineLoadStoreAlloca.cpp

Fixes the LIT failure in `SYCL::esimd/wait.cpp`.

Guard b5c2a19fedc2 changes behind INTEL_SYCL_OPAQUEPOINTER_READY.

---

llvm/test/Transforms/SPIRITTAnnotations/itt_atomic_load.ll
llvm/test/Transforms/SPIRITTAnnotations/itt_atomic_store.ll
llvm/test/Transforms/SPIRITTAnnotations/itt_instrumentation_debug.ll
llvm/test/tools/sycl-post-link/device-code-split/auto-module-split-1.ll
llvm/test/tools/sycl-post-link/device-code-split/auto-module-split-2.ll
llvm/test/tools/sycl-post-link/device-code-split/auto-module-split-func-ptr.ll
llvm/test/tools/sycl-post-link/device-code-split/basic-module-split.ll
llvm/test/tools/sycl-post-link/device-code-split/one-kernel-per-module.ll
llvm/test/tools/sycl-post-link/device-globals/test_global_variable_trim_used.ll
llvm/test/tools/sycl-post-link/spec-constants/SYCL-2020.ll
llvm/test/tools/sycl-post-link/spec-constants/bool.ll
llvm/test/tools/sycl-post-link/spec-constants/default-value/device-image.ll
llvm/test/tools/sycl-post-link/spec-constants/default-value/struct-with-padding.ll
llvm/test/tools/sycl-post-link/sycl-esimd/no-sycl-esimd-split-shared-func.ll
llvm/test/tools/sycl-post-link/sycl-post-link-test.ll

- Port sycl-post-link to opaque pointers
- Update SPIRITTAnnotations tests to opaque pointers

[Opaque pointer] Port sycl-post-link and SPIRITTAnnotations tests to opaque pointers

---

sycl/source/detail/scheduler/commands.cpp
sycl/test-e2e/Basic/accessor/empty_acc_host_task.cpp

Follow-up fix for https://github.com/intel/llvm/pull/10797.

[SYCL] Fix crash on empty acc + host_task

---

polygeist/tools/cgeist/Lib/CGExpr.cc
polygeist/tools/cgeist/Lib/clang-mlir.h
polygeist/tools/cgeist/Test/Verification/conditional.cpp

Also simplify rvalue and void cases.

[SYCL-MLIR] Support lvalue-returning conditional operator

---

mlir-sycl/doc/design/SYCLGridRepresentation.md

Update the design document with the latest changes to the SYCL dialect.

[SYCL-MLIR][DOC] Update `SYCLGridRepresentation` design document

---

mlir/lib/Target/LLVMIR/ModuleImport.cpp

In the current version on our branch, `mlir-translate` can create empty LLVM global operations in the MLIR output, if the input LLVM IR module does not contain any COMDAT information (which can be omitted according to the LLVM language reference manual). The empty global operation causes the verifier to fail. 
This problem has been fixed in upstream LLVM with [this revision](https://reviews.llvm.org/D153739), but this fix has not yet landed in our branch. The changes in this PR can be reverted as soon as we receive [the revision](https://reviews.llvm.org/D153739) through pull-down, but allow us to move forward in the meantime.

[SYCL-MLIR] Avoid empty LLVM global op for COMDAT

---

sycl/include/sycl/handler.hpp

Fixes https://github.com/intel/llvm/issues/6693.

[NFC][SYCL] Fix doxygen markup in sycl/handler.hpp

---

devops/scripts/install_build_tools.sh

We use it to install intel drivers, including the later containers job.

[CI] Install curl into the base image

---

sycl/test/esimd/regression/simd_wrapper.cpp

Caused by https://github.com/intel/llvm/commit/f4c886b6aaeac0a48f3bdeda3103887599373842

Update expected note in test to fix lit failure

---

sycl/test-e2e/Matrix/SG32/element_wise_all_sizes.cpp
sycl/test-e2e/Matrix/XMX8/element_wise_all_sizes.cpp
sycl/test-e2e/Matrix/element_wise_all_sizes.cpp

[SYCL][Joint Matrix] Remove XFAIL from JM element_wise_all_sizes tests

---

devops/dependencies.json

[GHA] Uplift Linux GPU RT version to 23.22.26516.18

---

sycl/test-e2e/syclcompat/kernel/Inputs/kernel_function.cpp
sycl/test-e2e/syclcompat/kernel/Inputs/kernel_module.cpp
sycl/test-e2e/syclcompat/kernel/kernel_function.cpp
sycl/test-e2e/syclcompat/kernel/kernel_lin.cpp
sycl/test-e2e/syclcompat/kernel/kernel_win.cpp

This commit extends the tests of the kernel headers to support windows.

[SYCL][COMPAT] Kernel header tests for windows

---

sycl/include/sycl/ext/intel/experimental/esimd/detail/math_intrin.hpp

I haven't been able to reproduce this, but the fix is harmless and we have a customer who needs it.

[SYCL][ESIMD] Fix ambiguous log2 call in host code

---

sycl/include/sycl/types.hpp

Remove cmath include from device compilation flow.

[SYCL][NFC] Remove debug code from DPC++ headers

---

sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp

Previously the check was missing.

[SYCL][ESIMD] Add a check for number of blocks for 2d block store

---

sycl/include/sycl/reduction.hpp

It wasn't obvious why we don't have a WG barrier before reporting
WG has finished its work. Clarify that in the comment now.

[SYCL][Reduction] Update a comment

---

clang-tools-extra/clangd/CompileCommands.cpp
clang-tools-extra/modularize/Modularize.cpp
clang/docs/InternalsManual.rst
clang/include/clang/Driver/ClangOptionDocs.td
clang/include/clang/Driver/Driver.h
clang/include/clang/Driver/Options.h
clang/include/clang/Driver/Options.td
clang/lib/Driver/Driver.cpp
clang/lib/Frontend/CompilerInvocation.cpp
clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp
clang/lib/Tooling/InterpolatingCompilationDatabase.cpp
clang/test/Driver/dxc_debug.hlsl
clang/tools/driver/cc1as_main.cpp
clang/utils/TableGen/ClangOptionDocEmitter.cpp
clang/utils/update_options_td_flags.py
flang/docs/FlangDriver.md
flang/docs/FlangOptionsDocs.td
flang/lib/Frontend/CompilerInvocation.cpp
flang/lib/FrontendTool/ExecuteCompilerInvocation.cpp
flang/tools/flang-driver/driver.cpp
llvm/include/llvm/Option/OptTable.h
llvm/lib/Option/OptTable.cpp
polygeist/tools/cgeist/driver.cc

DO NOT SQUASH AND MERGE THIS PR
Old (Include/Exclude) API is deprecated. Use visibility API instead.

[SYCL-MLIR][cgeist] Use visibility APIs to parse arguments

---

mlir/lib/Analysis/DataFlow/DenseAnalysis.cpp
mlir/test/Analysis/DataFlow/test-last-modified.mlir
mlir/test/lib/Analysis/DataFlow/TestDenseForwardDataFlowAnalysis.cpp
mlir/test/lib/Dialect/Test/TestDialect.cpp
mlir/test/lib/Dialect/Test/TestOps.td

DO NOT SQUASH AND MERGE THIS PR
Remove assertion violated by loop-like operations.

Remove assertion in `AbstractDenseForwardDataFlowAnalysis`

---

sycl/plugins/unified_runtime/ur/adapters/level_zero/usm.hpp

Post-commit error fix for: https://github.com/intel/llvm/pull/10807

[SYCL][UR][L0] Fix USMProxyPool unused parameter errors

---

sycl/doc/extensions/supported/sycl_ext_oneapi_sub_group_mask.asciidoc

[SYCL][DOC] Fix type in spec

---

mlir/include/mlir/Dialect/SCF/IR/SCFOps.td
mlir/lib/Dialect/SCF/IR/SCF.cpp
mlir/test/Dialect/SCF/region-op.mlir

* Added into SCF dialect for now, until we decide for better place
* Op taken directly from numba-mlir https://github.com/numba/numba-mlir/blob/6dabd431f756a206c777f1030c35b53b95423f58/mlir/include/numba/Dialect/numba_util/NumbaUtilOps.td#L236
* Canonicalizations are not part of this PR to reduce scope

[mlir][RegionOp] Add RegionOp

---

libclc/ptx-nvidiacl/libspirv/images/image.cl
llvm/lib/SYCLLowerIR/SYCLPropagateAspectsUsage.cpp
llvm/test/SYCLLowerIR/PropagateAspectsUsage/global-value.ll
sycl/doc/extensions/experimental/sycl_ext_matrix/sycl_ext_intel_matrix.asciidoc
sycl/doc/extensions/experimental/sycl_ext_matrix/sycl_ext_oneapi_matrix.asciidoc
sycl/test-e2e/Regression/pf-wg-atomic64.cpp
sycl/test-e2e/Regression/same_unnamed_kernels.cpp
sycl/test-e2e/bindless_images/mipmap/mipmap_read_1D.cpp
sycl/test-e2e/bindless_images/mipmap/mipmap_read_2D.cpp
sycl/test-e2e/bindless_images/mipmap/mipmap_read_3D.cpp
sycl/test-e2e/xfail_tests.txt

[SYCL-MLIR] pulldown (20230919)

---

sycl/plugins/unified_runtime/ur/adapters/level_zero/queue.cpp

Fixes post-commit build fails in https://github.com/intel/llvm/actions/runs/6256835642/job/16988269333

[UR][L0] Do not rely on CTAD to avoid build warnings/failures

---

polygeist/tools/cgeist/Test/Verification/base_cast.cpp

Add test with different casts between base and derived classes.

[SYCL-MLIR][cgeist][test] Add `base_cast.cpp` test

---

sycl/test-e2e/Graph/submission_while_executing.cpp

See https://github.com/intel/llvm/issues/11277.

[SYCL][E2E] Disable Graph/submission_while_executing.cpp on Win

---

clang/include/clang/Driver/Options.td
clang/lib/Driver/ToolChains/Clang.cpp
clang/test/Driver/sycl-device-post-link-opt.cpp

We have these for the other tools and it is useful in this case too.

[SYCL][Driver] Add hidden option to specify sycl-post-link options

---

sycl/test/CMakeLists.txt

[SYCL] Fix typo in check-sycl log message

---

sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp

Qualify the call.
I manually verified this fixes it.

[SYCL][ESIMD] Fix ambiguous call to raw_send

---

sycl/plugins/unified_runtime/CMakeLists.txt

To pick windows build failure fix in
9265d33b3b1e538bb1d27aea29d30f2ed47859be.

[UR] Update tag to pickup windows build failure fix

---

llvm/lib/Target/AMDGPU/AMDGPUTargetMachine.cpp
llvm/test/CodeGen/AMDGPU/llc-pipeline.ll

This reverts commit dce52b456701e4fe6ba55c36571c4be34558fd9b.

Revert "Revert "AMDGPU: Move placement of RemoveIncompatibleFunctions""

---

sycl/test/check_device_code/native_cpu/native_cpu_builtins.cpp

Attempted fix for post-merge fail https://github.com/intel/llvm/pull/11443

[SYCLNATIVECPU] fixed lit test for post-merge fail

---

sycl/cmake/modules/AddBoostMp11Headers.cmake
sycl/cmake/modules/PreprocessBoostMp11Headers.cmake
sycl/include/sycl/detail/generic_type_lists.hpp
sycl/include/sycl/detail/image_accessor_util.hpp
sycl/include/sycl/detail/type_list.hpp
sycl/include/sycl/ext/oneapi/experimental/cuda/builtins.hpp
sycl/test/type_traits/integer_n_bit.cpp
sycl/test/type_traits/type_list.cpp

[SYCL] Remove recursion from type_list
About 10% compilation speed improvement for sysl.hpp (device-only).

[SYCL] Remove type list recursion

---

sycl/include/sycl/ext/intel/experimental/fpga_mem/fpga_mem.hpp
sycl/include/sycl/ext/oneapi/device_global/device_global.hpp
sycl/include/sycl/ext/oneapi/experimental/annotated_arg/annotated_arg.hpp
sycl/include/sycl/ext/oneapi/experimental/annotated_ptr/annotated_ptr.hpp
sycl/include/sycl/ext/oneapi/properties/properties.hpp
sycl/include/sycl/handler.hpp
sycl/include/sycl/queue.hpp
sycl/test-e2e/Reduction/reduction_internal.cpp

Spec: https://github.com/intel/llvm/pull/11439

[SYCL] Use new empty_properties_t alias

---

sycl/test-e2e/Reduction/reduction_range_N_vars.cpp

Same as we fixed in https://github.com/intel/llvm/pull/9112.

[SYCL][E2E] Fix use-after-free in reduction_range_N_vars.cpp

---

sycl/include/sycl/detail/generic_type_traits.hpp

Remove `TryToGetPointerT`/`TryToGetVectorT`/`TryToGetPointerVecT`. Use explicit `vec`/`multi_ptr`/`detail::Boolean` partial specializations instead. It takes less code and is easier to read.

[NFCI][SYCL] Minor refactoring in detail/generic_type_traits.hpp

---

clang/lib/Driver/ToolChains/SYCL.cpp

Based on discussion in https://github.com/intel/llvm/pull/11409#discussion_r1355757873

[SYCL][Driver][NFC] Update comment about -cl-opt-disable

---

sycl/CMakeLists.txt

We should have done it much earlier, but better late than never.

[SYCL] Bump SYCL_MINOR_VERSION

---

clang/tools/clang-linker-wrapper/ClangLinkerWrapper.cpp

This PR fixes an issue that causes extra copy.
Thanks

[LinkerWrapper][NFC] Fix extra copy issue

---

sycl/test-e2e/DeviceArchitecture/device_architecture_on_device_aot.cpp
sycl/test-e2e/Regression/static-buffer-dtor.cpp
sycl/test-e2e/USM/pointer_query.cpp

Fix some leaks and a bug inside e2e tests.

[SYCL][E2E] Fix some e2e test problems

---

sycl/plugins/level_zero/tracing.cpp
sycl/source/detail/plugin.hpp

Current instrumentation in SYCL runtime has additional overheads due to argument capture even it is not subscribed to or needed. This patch addresses this issue.

[SYCL][XPTI] Performance improvements to XPTI streams

---

sycl/source/detail/device_image_impl.hpp

Changed auto to auto& in for loops for performance improvement.

[SYCL] fix the static verifier reported issues

---

sycl/test/check_device_code/native_cpu/native_cpu_builtins.cpp

Fixes post commit failure from https://github.com/intel/llvm/pull/11685

[SYCL] [NATIVECPU] Fix postcommit failure 

---

sycl/test/esimd/regression/windows_msvc_math.cpp

by providing a declaration of the function in the test.

[SYCL][ESIMD][E2E] Safeguard windows_msvc_math.cpp from different versions of MSVC STL

---

sycl/test-e2e/ESIMD/histogram_256_slm.cpp
sycl/test-e2e/ESIMD/histogram_256_slm_spec_2020.cpp
sycl/test-e2e/ESIMD/linear/bitmap_helpers.h
sycl/test-e2e/ESIMD/linear/linear.cpp
sycl/test-e2e/ESIMD/regression/half_conversion_test.cpp
sycl/test-e2e/Plugin/interop-level-zero-image-get-native-mem.cpp
sycl/test-e2e/Regression/commandlist/Inputs/main.cpp

Fix some leaks found in e2e tests.

[SYCL][E2E] Fix some e2e tests memory leak.

---

sycl/test/extensions/annotated_usm/invalid_compile_time_properties.cpp

This is to fix the post-commit failure in #10235

[SYCL][Test] Fix annotated malloc test failure

---

sycl/plugins/unified_runtime/CMakeLists.txt

For https://github.com/oneapi-src/unified-runtime/pull/968

[OpenCL] Add version check for urProgramSetSpecializationConstants

---

sycl/doc/design/spirv-extensions/SPV_INTEL_joint_matrix.asciidoc
sycl/doc/design/spirv-extensions/SPV_INTEL_joint_matrix_legacy.asciidoc

Old version is temporary kept in SPV_INTEL_joint_matrix_legacy.asciidoc

[SPIR-V][DOC] Update SPV_INTEL_joint_matrix

---

clang/lib/Driver/ToolChains/Clang.cpp

Unused variable - clean it up.

[NFC] Warning cleanup

---

sycl/test-e2e/Matrix/runtime_query_pvc.cpp

Update the test after https://github.com/intel/llvm/pull/11837

[SYCL][Joint Matrix][E2E] Update runtime_query_pvc.cpp after recent changes

---

sycl/CMakeLists.txt

Bump minor version to align to oneapi 2024.2 upcoming release

[SYCL] Bump SYCL_MINOR_VERSION 

---

sycl/include/sycl/ext/oneapi/properties/property.hpp

This reverts commit aaab5d34246582d528c7bcaf54830513224276cb.

Revert "[SYCL] Reserve values in PropKind enum (#11944)"

---

sycl/doc/extensions/experimental/sycl_ext_oneapi_kernel_compiler.asciidoc

Fix some minor spec problems I noticed while preparing a larger change. None of these should affect the implementation.

[SYCL][Doc]Editorial fixes to kernel compiler spec

---

llvm/lib/SYCLLowerIR/ESIMD/LowerESIMD.cpp

This will make merges simpler.

[SYCL][ESIMD][NFC] Code cleanup

---

sycl/unittests/helpers/PiMock.hpp

fix post-commit error for PR https://github.com/intel/llvm/pull/11989

[SYCL] Fix post-commit error "missing field 'SanitizeType' initializer"

---

.github/workflows/sycl_linux_precommit_aws.yml

[CI] Pass NVIDIA_DISABLE_REQUIRE=1 to container options on CUDA AWS

---

sycl-fusion/passes/kernel-fusion/SYCLKernelFusion.cpp

In the unlikely edge case that an original kernel function cannot be inlined into the newly constructed fused kernel function, we have to ensure that a) the original kernel function is not deleted from the module, and b) is called with the correct calling convention and attributes.

[SYCL][Fusion] Prevent deletion of original kernel function if inlining fails

---

sycl/doc/syclcompat/README.md

Updated the documentation to make users aware that the SYCLcompat API may still suffer some breaking changes.

[SYCL][Compat][docs] Included disclaimer of syclcomapt experimental state

---

clang/lib/CodeGen/CGDebugInfo.cpp

We have changed the code in https://github.com/intel/llvm/pull/6774, but we did wrong resolution recently.

Fix wrong resolution about CGDebugInfo.cpp

---

sycl/plugins/level_zero/CMakeLists.txt

This reverts commit 30458069804e3c5624deb75e38cf114cee051f27.

Revert "[SYCL] Add delayloading for ze_loader (#11902)"

---

sycl/plugins/unified_runtime/CMakeLists.txt

UR pull request: https://github.com/oneapi-src/unified-runtime/pull/1207

[SYCL] [NATIVECPU] Remove event.hpp inclusion 

---

sycl/test-e2e/Basic/built-ins/marray_relational.cpp

[SYCL][E2E] Add the FP16 tests to marray_relational.cpp

---

sycl/doc/extensions/experimental/sycl_ext_oneapi_graph.asciidoc

Add Andrey Alekseenko @al42and to list of SYCL-Graph contributors.

[SYCL][DOC][Graph] Add Contributor to SYCL-Graph spec

---

sycl/include/sycl/ext/oneapi/bindless_images.hpp

Same as NVPTX, Intel GPU backend also needs converting a user type to a standard type, otherwise mangled builtin name is unrecognizable.

[NFC][SYCL][Bindless] apply convert_color for non-nvptx backend as well

---

sycl/doc/extensions/template.asciidoc

Add some suggestions about identifying the target audience for an extension in the Overview section.

[SYCL][Doc] Update spec template overview

---

sycl/include/sycl/ext/intel/experimental/esimd/detail/memory_intrin.hpp

[SYCL][ESIMD][NFC] Clean up remaining intrinsics to use macro

---

sycl/test-e2e/ESIMD/lsc/Inputs/lsc_slm_load.hpp
sycl/test-e2e/ESIMD/lsc/Inputs/lsc_slm_store.hpp
sycl/test-e2e/ESIMD/lsc/lsc_slm_block_load.cpp
sycl/test-e2e/ESIMD/lsc/lsc_slm_block_store.cpp

[SYCL][ESIMD]Add tests for 8/16 bit data for lsc_slm_block_load and lsc_slm_block_store API

---

sycl/doc/extensions/proposed/sycl_ext_oneapi_composite_device.asciidoc

Clarify the impact of composite devices on a platform's default context.

[SYCL][Doc] Default context with composite devices

---

sycl/include/sycl/builtins_utils_scalar.hpp
sycl/include/sycl/detail/type_traits.hpp

It's generic enough and isn't specific to builtins.

[NFC][SYCL] Move check_type_in_v to sycl/detail/type_traits.hpp

---

sycl/plugins/unified_runtime/pi2ur.hpp

Translates PI to UR and passes them the backends.

[SYCL][Graph] Handle PI flags for mem-advise op

---

sycl/test-e2e/ESIMD/matrix_transpose_glb.cpp

My bad, I merged the last PR before CI finished and my change was wrong.

[SYCL][ESIMD][E2E] Fix UNSUPPORTED line in matrix_transpose_glb.cpp

---

sycl/plugins/native_cpu/CMakeLists.txt

Updates the commit tag for the OCK.

[SYCL] [NATIVECPU] Update OneAPI Construction Kit tag

---

devops/dependencies.json

[GHA] Uplift Linux GPU RT version to 23.52.28202.14

---

sycl/include/sycl/detail/builtins.hpp
sycl/include/sycl/detail/generic_type_traits.hpp
sycl/include/sycl/detail/image_ocl_types.hpp
sycl/include/sycl/ext/oneapi/experimental/builtins.hpp

Continuation of refactoring series initiated in
https://github.com/intel/llvm/pull/12674.

[NFCI][SYCL] Introduce convertFromOpenCLTypeFor<T>(x) helper

---

clang/lib/CodeGen/CGAtomic.cpp
llvm/lib/IR/BasicBlock.cpp

1> fix conflicts.
2> Revert 5c9f7682b090.
See:
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/2357
https://github.com/intel/llvm/issues/12698

Fix conflicts.

---

devops/dependencies.json

[GHA] Uplift Linux GPU RT version to 24.05.28454.6

---

sycl/test-e2e/Assert/assert_in_kernels_win.cpp
sycl/test-e2e/Assert/assert_in_multiple_tus_one_ndebug_win.cpp
sycl/test-e2e/Assert/assert_in_multiple_tus_win.cpp
sycl/test-e2e/Assert/assert_in_one_kernel_win.cpp
sycl/test-e2e/Assert/assert_in_simultaneous_kernels_win.cpp
sycl/test-e2e/Assert/assert_in_simultaneously_multiple_tus.cpp
sycl/test-e2e/Assert/assert_in_simultaneously_multiple_tus_one_ndebug.cpp

See https://github.com/intel/llvm/issues/12797.

[SYCL][E2E] Disable multiple assert tests on Windows

---

sycl/test-e2e/Plugin/sycl-ls-unified-runtime.cpp

See https://github.com/intel/llvm/issues/12798.

[SYCL][E2E] Disable Plugin/sycl-ls-unified-runtime.cpp

---

sycl/test-e2e/ESIMD/regression/complex-lib-lin.cpp

[SYCL][ESIMD][E2E] Disable complex-lib-lin.cpp

---

sycl/test-e2e/Basic/built-ins/helpers.hpp
sycl/test-e2e/Basic/built-ins/marray_relational.cpp

This change also updated the test to verify the builtins on host. Other tests in the directory could be updated the same way if/after this PR is merged.

[SYCL][E2E] Refactor Basic/built-ins/marray_relational.cpp

---

sycl/plugins/native_cpu/CMakeLists.txt

Updates the git tag for the oneAPI Construction Kit.

[SYCL][NATIVECPU] Update OCK tag

---

sycl/doc/extensions/experimental/sycl_ext_oneapi_graph.asciidoc

- Replace incorrect use of "Preconditions" with "Constraints"
- Remove single API synopsis and replace with smaller individual synopsis for each relevant section

[SYCL][Graph] Minor spec improvements

---

.github/ISSUE_TEMPLATE/2-bug-report-cuda.yml
.github/ISSUE_TEMPLATE/3-bug-report-hip.yml

Add link to cuda/hip troubleshooting in issue template.

[CUDA][HIP] Add link to cuda/hip troubleshooting in issue template.

---

sycl/test-e2e/AddressSanitizer/common/demangle-kernel-name.cpp

Add a test for demangle kernel name for UR PR https://github.com/oneapi-src/unified-runtime/pull/1355

[SYCL][DeviceSanitizer] Add a test for demangle kernel name

---

sycl/source/detail/graph_impl.cpp

This PR fixes minor performance-related issues reported by Coverity.

[SYCL] Fix Coverity issues in source/detail/graph_impl.cpp

---

sycl/tools/sycl-ls/sycl-ls.cpp

Fixes LIT test failure in tools/sycl-ls.test.

[SYCL] Fix 'ignore-device-selectors' sycl-ls CLI option on windows

---

clang/lib/Driver/CMakeLists.txt
sycl/CMakeLists.txt
sycl/test-e2e/lit.cfg.py
sycl/test/abi/sycl_symbols_windows.dump
sycl/test/lit.cfg.py

It will be an ABI breaking release but we expect to allow such changes starting April 1st.

[SYCL] Bump SYCL_MAJOR_VERSION to "8"

---

sycl/test-e2e/LLVMIntrinsicLowering/bitreverse.cpp
sycl/test-e2e/LLVMIntrinsicLowering/common.hpp

Apply clang-format to llvm.bitreverse lowering testcase

[SYCL][NFC] Apply clang-format to bitreverse test

---

sycl-fusion/test/CMakeLists.txt

Old message: "Running LLVM lit test suite"
New message: "Running SYCL Fusion lit tests"

[SYCL][Fusion][NFC] Fix lit test suite comment message

---

.github/workflows/sycl-containers.yaml
devops/containers/ubuntu2204_intel_drivers.Dockerfile
devops/scripts/install_drivers.sh

This is a refactor to avoid passing large number of ARGs when building docker image.

[CI]: Avoid passing large number of args to dockerfile

---

sycl/test-e2e/Graph/Update/update_before_finalize.cpp
sycl/test-e2e/Graph/Update/update_nd_range.cpp
sycl/test-e2e/Graph/Update/update_range.cpp
sycl/test-e2e/Graph/Update/update_with_indices_accessor.cpp
sycl/test-e2e/Graph/Update/update_with_indices_accessor_double_update.cpp
sycl/test-e2e/Graph/Update/update_with_indices_accessor_multiple_nodes_different_indices.cpp
sycl/test-e2e/Graph/Update/update_with_indices_accessor_ordering.cpp
sycl/test-e2e/Graph/Update/update_with_indices_multiple_exec_graphs.cpp
sycl/test-e2e/Graph/Update/update_with_indices_ordering.cpp
sycl/test-e2e/Graph/Update/update_with_indices_ptr.cpp
sycl/test-e2e/Graph/Update/update_with_indices_ptr_double_update.cpp
sycl/test-e2e/Graph/Update/update_with_indices_ptr_multiple_nodes.cpp
sycl/test-e2e/Graph/Update/update_with_indices_ptr_multiple_nodes_different_indices.cpp
sycl/test-e2e/Graph/Update/update_with_indices_ptr_multiple_params.cpp
sycl/test-e2e/Graph/Update/update_with_indices_ptr_subgraph.cpp
sycl/test-e2e/Graph/Update/update_with_indices_scalar.cpp

- This is already covered by aspect requirements

[SYCL][Graph] Remove unnecessary UNSUPPORTED from update tests

---

sycl/doc/syclcompat/README.md
sycl/include/syclcompat/math.hpp
sycl/test-e2e/syclcompat/math/math_complex.cpp

Adds the documentation, functionality and tests for complex multiplication addition to SYCLcompat.

[SYCL][COMPAT] Added Complex muladd to syclcompat

---

sycl/test-e2e/Matrix/element_wise_all_ops.cpp

[SYCL][Matrix][Test] Enable element_wise_all_ops test on DG2

---

sycl/test-e2e/Matrix/joint_matrix_apply_two_matrices_impl.hpp

The test was failing on SPR. This provides a fix.
I also changed values for tM, tK, tN on AMX, setting them to the maximum to improve test coverage as they don't need to match the PVC size anymore

[SYCL][JM tests] Fix apply test on SPR

---

sycl/test-e2e/Config/kernel_from_file.cpp

To fix test failure in test config that device sanitizer is enabled.

[NFC][test-e2e][kernel_from_file] Link with libdevice sanitizer

---

sycl/plugins/unified_runtime/CMakeLists.txt

https://github.com/oneapi-src/unified-runtime/pull/1395

[UR] Bump HIP tag to 1473ed8a

---

sycl/plugins/unified_runtime/CMakeLists.txt

https://github.com/oneapi-src/unified-runtime/pull/1342

[UR] Bump CUDA tag to 1333d4a0

---

sycl/plugins/unified_runtime/CMakeLists.txt

https://github.com/oneapi-src/unified-runtime/pull/1437

[UR] Bump HIP tag to 15233fd2

---

clang/include/clang/Driver/Options.td
clang/lib/Driver/ToolChains/Clang.cpp
clang/test/Driver/no-system-debug.c
clang/test/Driver/system_debug.c

Add option -fsystem-debug to complement -fno-system-debug.

[Driver] Add option -fsystem-debug

---

llvm/lib/SYCLLowerIR/CMakeLists.txt

Has some warning fixes we want.

[SYCL] Bump vc-intrinsics version

---

sycl/plugins/unified_runtime/CMakeLists.txt

https://github.com/oneapi-src/unified-runtime/pull/1510

[UR] Bump CUDA tag to 3f5f5688

---

sycl/source/detail/plugin.hpp

Building with GCC 13.2 was showing thousands of lines of warnings due to the centrality of this header, with the compiler (rightly?) detecting that ArgsDataPtr may be dangling.
There shouldn't be any performance impact of this change as the unique_ptr should be just as cheap to initialize with nullptr as a regular pointer on the fast path.

[SYCL][XPTI] Fix dangling pointer warnings

---

.github/workflows/sycl-containers-igc-dev.yaml
.github/workflows/sycl-containers.yaml
.github/workflows/sycl-update-igc-dev-driver.yml
devops/containers/ubuntu2204_intel_drivers_igc_dev.Dockerfile
devops/dependencies-igc-dev.json
devops/dependencies.json
devops/scripts/install_drivers.sh
devops/scripts/update_drivers.py

Per discussion with @aelovikov-intel ,factor out all igc dev related code to new workflows to avoid necessary interaction with other docker images.

[CI] Factor out igc dev related code

---

sycl/test-e2e/README.md

I missed adding this when I added the param.

[SYCL][E2E][NFC] Add missing feature check to E2E doc

---

.github/workflows/sycl-linux-run-tests.yml

Need to pass igc-dev.json in as well.

[CI] Fix linux run test after refactoring for igc dev

---

sycl/test-e2e/Basic/event_default_construction.cpp

test was overlooked when fixing https://github.com/intel/llvm/pull/13419

[SYCL] add overlooked test for recent fix

---

devops/scripts/install_build_tools.sh

Install hwloc which is required by UMF (a dependency of UR).
This is needed by https://github.com/intel/llvm/pull/13343

[CI] Update dependencies in docker

---

sycl/test/regression/compile_on_win_with_mdd.cpp

Patch which causes the regression: https://github.com/intel/llvm/pull/12793
Revert of that patch: https://github.com/intel/llvm/pull/13326

[SYCL] Add test for regression after https://github.com/intel/llvm/pull/12793

---

devops/dependencies.json

[GHA] Uplift Linux GPU RT version to 24.13.29138.7

---

devops/cts_exclude_filter

https://github.com/intel/llvm/issues/13574

[CI][SYCL-CTS] Turn off failing tests

---

sycl/include/sycl/ext/intel/esimd/detail/util.hpp
sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp

This should fix post-commit issue caused by #13443

[SYCL][ESIMD] Adjust lsc_gather to SYCL APIs change

---

clang/lib/Driver/Driver.cpp
clang/lib/Driver/ToolChains/SYCL.cpp
clang/test/Driver/sycl-bfloat16-lib.cpp
clang/test/Driver/sycl-device-lib-win.cpp
clang/test/Driver/sycl-device-lib.cpp
clang/test/Driver/sycl-early-device-link.cpp
clang/test/Driver/sycl-force-target.cpp
clang/test/Driver/sycl-instrumentation.c
clang/test/Driver/sycl-no-rdc-fat-archive-win.cpp
clang/test/Driver/sycl-no-rdc-fat-archive.cpp
clang/test/Driver/sycl-no-rdc-win.cpp
clang/test/Driver/sycl-no-rdc.cpp
clang/test/Driver/sycl-offload-new-driver.c
libdevice/cmake/modules/SYCLLibdevice.cmake

Revert "[Driver][SYCL] Use LLVM-IR based device libraries for device linking"

---

sycl/test-e2e/bindless_images/device_to_device_copy.cpp

* Reduce texture sizes for consistent passing on various HW
* Remove XFAIL

[SYCL][E2E][Exp][Bindless] Fix device_to_device_copy test

---

.github/workflows/sycl-linux-run-tests.yml

Also allow excluded categories to be builded if CTS_TESTS_TO_BUILD is specified.

[CI][SYCL-CTS] List cts_exclude_filter before executing

---

sycl/include/sycl/ext/intel/experimental/esimd/detail/util.hpp

This will make internal pulldowns easier.

[SYCL][ESIMD][NFC] Seperate detail namespace in util.hpp

---

sycl/plugins/unified_runtime/CMakeLists.txt

https://github.com/oneapi-src/unified-runtime/pull/1549

[UR] Bump L0 tag to fb342f06

---

sycl/source/detail/graph_impl.cpp
sycl/source/detail/graph_impl.hpp

- Check for empty cmd group when updating node reqs
- Fix nullptr deref in reqs check

[SYCL][Graph] Fix minor issues in graph update code

---

sycl/plugins/unified_runtime/CMakeLists.txt

UR PR: https://github.com/oneapi-src/unified-runtime/pull/1499

[UR][EXP][Command-Buffer] Remove duplicated code from headers

---

sycl/doc/syclcompat/README.md
sycl/include/syclcompat/launch_experimental.hpp
sycl/include/syclcompat/syclcompat.hpp
sycl/test-e2e/syclcompat/launch/launch.cpp

add experimental launch overloads accepting SG size in SYCL

[SYCL][COMPAT] Add experimental launch overloads accepting SG size

---

sycl/plugins/unified_runtime/CMakeLists.txt

https://github.com/oneapi-src/unified-runtime/pull/1596

[CUDA][SYCL] Bump UR CUDA Tag

---

sycl/plugins/unified_runtime/CMakeLists.txt

https://github.com/oneapi-src/unified-runtime/pull/1553

[UR][HIP] Get Device From Queue

---

sycl/test-e2e/Matrix/joint_matrix_prefetch_impl.hpp

Clarification to the spec is added in https://github.com/intel/llvm/pull/13796

[SYCL][joint matrix] Add col major case to prefetch and correct the VNNI case

---

sycl/test-e2e/Matrix/joint_matrix_apply_two_matrices_impl.hpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_OOB.cpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_impl.hpp
sycl/test-e2e/Matrix/joint_matrix_out_bounds.cpp
sycl/test-e2e/Matrix/joint_matrix_out_bounds_impl.hpp

- Add row major case to the out of bounds (OOB) test, 
- Add OOB case to the performance test

[SYCL][joint matrix tests] add more out of bounds cases to the tests

---

devops/dependencies-igc-dev.json

[GHA] Uplift Linux IGC Dev RT version to igc-dev-9fd74e9

---

sycl/include/sycl/ext/oneapi/experimental/enqueue_functions.hpp

This commit adds the code_location argument to the new enqueue functions to enforce better code location information from callers.

[SYCL] Add code location information to enqueue free functions

---

devops/dependencies-igc-dev.json

[GHA] Uplift Linux IGC Dev RT version to igc-dev-4627f1f

---

sycl/plugins/unified_runtime/CMakeLists.txt

https://github.com/oneapi-src/unified-runtime/pull/1604

[UR][HIP] Implement kernel set spec constant query

---

sycl/test-e2e/Plugin/sycl-ls-unified-runtime.cpp

Closes https://github.com/intel/llvm/issues/12798.

[SYCL] Re-enable `Plugin/sycl-ls-unified-runtime.cpp`

---

sycl/include/sycl/ext/oneapi/bindless_images.hpp

For spirv path, use __invoke__ImageRead and __invoke__ImageWrite to generate image builtin represented as OpImageRead or OpImageWrite in SPIRV after llvm-spirv translation.

[SYCL][Bindless] Update spirv fetch-sampled and fetch/write-array

---

sycl/doc/syclcompat/README.md
sycl/include/syclcompat/device.hpp
sycl/test-e2e/syclcompat/device/device.cpp
sycl/test-e2e/syclcompat/device/device_filter.cpp
sycl/test-e2e/syclcompat/device/device_fixt.hpp

This PR adds functionalities for:
* Listing devices in stdout
* Filtering devices
Tests and docs updated accordingly.

[SYCL][COMPAT] Added filter_device and list_devices

---

clang/test/Driver/save-temps.c

This failure was exposed in 12949c952 [Driver] Remove a bunch of unnecessary REQUIRES constraints (#94055).

[Driver] Fix CWD test in save-temps.c.

---

sycl/test-e2e/syclcompat/memory/memory_management_test3.cpp

See https://github.com/intel/llvm/issues/14086

[SYCL][E2E] Disable memory_management_test3.cpp on Gen12 linux

---

sycl/test-e2e/DiscardEvents/discard_events_l0_inorder.cpp

See https://github.com/intel/llvm/issues/14121

[SYCL][E2E] Disable discard_events_l0_inorder.cpp on Arc

---

devops/dependencies-igc-dev.json

[GHA] Uplift Linux IGC Dev RT version to igc-dev-3bd1d5e

---

devops/dependencies-igc-dev.json

[GHA] Uplift Linux IGC Dev RT version to igc-dev-480f8b6

---

sycl/test-e2e/ESIMD/unified_memory_api/block_load_slm.cpp
sycl/test-e2e/ESIMD/unified_memory_api/block_store_slm.cpp
sycl/test-e2e/ESIMD/unified_memory_api/scatter_lacc.cpp

They pass now and one driver check was wrong.

[SYCL][ESIMD][E2E] Enable some tests on Windows

---

devops/dependencies-igc-dev.json

[GHA] Uplift Linux IGC Dev RT version to igc-dev-1e81b14

---

sycl/test-e2e/Basic/buffer/buffer_dev_to_dev.cpp

This should work. Also update test a little bit.

[SYCL][test] Remove UNSUPPORTED for HIP

---

sycl/doc/GetStartedGuide.md

Addressing https://github.com/intel/llvm/issues/13009

[SYCL][Doc] Correct installation steps for cpu/fpga runtimes

---

sycl/test-e2e/ESIMD/clz_ctz.cpp

Prepare for a new driver which fixes the failing cases.

[SYCL][ESIMD][E2E] Fix clz/ctz test

---

sycl/plugins/unified_runtime/CMakeLists.txt
sycl/test-e2e/bindless_images/read_1D.cpp
sycl/test-e2e/bindless_images/read_2D.cpp
sycl/test-e2e/bindless_images/read_2D_dynamic.cpp
sycl/test-e2e/bindless_images/read_3D.cpp
sycl/test-e2e/bindless_images/read_norm_types.cpp
sycl/test-e2e/bindless_images/read_write_1D.cpp
sycl/test-e2e/bindless_images/read_write_1D_subregion.cpp
sycl/test-e2e/bindless_images/read_write_2D.cpp
sycl/test-e2e/bindless_images/read_write_2D_subregion.cpp
sycl/test-e2e/bindless_images/read_write_3D.cpp
sycl/test-e2e/bindless_images/read_write_3D_subregion.cpp
sycl/test-e2e/bindless_images/read_write_unsampled.cpp
sycl/test-e2e/bindless_images/sampling_1D.cpp
sycl/test-e2e/bindless_images/sampling_2D.cpp
sycl/test-e2e/bindless_images/sampling_2D_half.cpp
sycl/test-e2e/bindless_images/sampling_3D.cpp

Reverts intel/llvm#13926
Broke postcommit https://github.com/intel/llvm/actions/runs/9599143964/job/26474983972

Revert "[NFC][SYCL][Bindless] Run passing e2e tests on DG2 linux"

---

.github/workflows/sycl-issues-ping-assignee.yml

Set read-all permissions on this workflow as it should not require any write permissions

[CI][OSSF]Set permissions on sycl-issues-ping-assignee

---

.github/workflows/sycl-issues-ping-assignee.yml

Fix permission on workflow so it can correctly post

[CI][OSSF] content write permission on issue ping

---

sycl/test-e2e/Basic/fpga_tests/fpga_pipes.cpp

https://github.com/intel/llvm/issues/14308

[SYCL][E2E] Disable flaky test fpga_pipes.cpp

---

sycl/test-e2e/ProfilingTag/in_order_profiling_queue.cpp

https://github.com/intel/llvm/issues/14315

[SYCL][E2E] Disable in_order_profiling_queue.cpp on more devices

---

sycl/test-e2e/Basic/intel-ext-device.cpp

ZES_ENABLE_SYSMAN isn't working if set like this.

[SYCL][E2E] Update intel-ext-device test

---

sycl/test-e2e/Graph/Explicit/host_task_last.cpp

https://github.com/intel/llvm/issues/14350

[SYCL][E2E] Disable flaky test host_task_last.cpp on Gen12 Linux

---

sycl/source/detail/kernel_compiler/kernel_compiler_sycl.cpp
sycl/source/kernel_bundle.cpp

post commit has unused var warnings that need tidying

[SYCL]  post commit warnings removal

---

sycl/source/detail/event_impl.hpp

uninitialized value causing complaint from c.v.

[SYCL] minor uninitialized value

---

devops/dependencies.json

[GHA] Uplift Linux GPU RT version to 24.22.29735.20

---

.github/workflows/sycl-linux-run-tests.yml

Needed until https://github.com/KhronosGroup/SYCL-CTS/pull/907 is merged

[CI] Fix nightly CTS build

---

sycl/plugins/unified_runtime/CMakeLists.txt

https://github.com/oneapi-src/unified-runtime/pull/1822

[UR] Bump main tag to 9d3bce6a

---

sycl/include/sycl/detail/pi.h
sycl/plugins/cuda/pi_cuda.cpp
sycl/plugins/hip/pi_hip.cpp
sycl/plugins/level_zero/pi_level_zero.cpp
sycl/plugins/native_cpu/pi_native_cpu.cpp
sycl/plugins/opencl/pi_opencl.cpp
sycl/plugins/unified_runtime/CMakeLists.txt
sycl/plugins/unified_runtime/pi2ur.hpp
sycl/plugins/unified_runtime/pi_unified_runtime.cpp
sycl/source/detail/bindless_images.cpp
sycl/unittests/helpers/PiMockPlugin.hpp

https://github.com/oneapi-src/unified-runtime/pull/1829

[UR] Bump UR and implement changes to bindless image handle types

---

sycl/plugins/unified_runtime/CMakeLists.txt

* https://github.com/oneapi-src/unified-runtime/pull/1826
* https://github.com/oneapi-src/unified-runtime/pull/1852
* https://github.com/oneapi-src/unified-runtime/pull/1849
* https://github.com/oneapi-src/unified-runtime/pull/1828
* https://github.com/oneapi-src/unified-runtime/pull/1772
* https://github.com/oneapi-src/unified-runtime/pull/1862

[UR] Bump main tag to 7e38af77

---

sycl/test-e2e/BFloat16/bfloat16_builtins.cpp
sycl/test-e2e/BFloat16/bfloat16_builtins_cuda_generic.cpp
sycl/test-e2e/BFloat16/bfloat16_type.cpp

[SYCL][E2E] Remove XFAIL from tests; fix multi-device config

---

sycl/test-e2e/ESIMD/api/functional/ctors/ctor_load_usm_fp_extra.cpp

See https://github.com/intel/llvm/issues/14650 for more information.

[SYCL][E2E] Disable ctor_load_usm_fp_extra due to linux issue

---

sycl/test-e2e/HostInteropTask/interop-task-cuda-buffer-migrate.cpp
sycl/test-e2e/HostInteropTask/interop-task-cuda.cpp

-  Add CUDA library and include path requirements for running tests on Windows.

[SYCL][E2E] Add CUDA library and include path requirements for running tests on Windows

---

clang/tools/clang-linker-wrapper/ClangLinkerWrapper.cpp
llvm/lib/Transforms/Instrumentation/AddressSanitizer.cpp

Causing build failure with -Werror.

[NFC] Remove unused var

---

sycl/source/detail/kernel_compiler/kernel_compiler_sycl.cpp

dir deletion, permissions, and relative paths. As this is mostly tidying I'm not sure we need new testing. The existing KernelCompiler tests should suffice in ensuring everything is working.

[SYCL] punchlist from sec review

---

sycl-fusion/passes/CMakeLists.txt

Fixes shared-libs build issue in https://github.com/intel/llvm/actions/runs/10099057533/job/27927417771

[SYCL] Fix postcommit build failure

---

sycl-fusion/test/materializer/debug_output.ll

Failing as per https://github.com/intel/llvm/issues/14783

[SYCL] Disable debug_output fusion test

---

devops/dependencies-igc-dev.json

[GHA] Uplift Linux IGC Dev RT version to igc-dev-2e6ebc3

---

devops/dependencies.json

[GHA] Uplift Linux GPU RT version to 24.26.30049.6

---

sycl/test-e2e/Matrix/SG32/joint_matrix_prefetch.cpp

Passing on Arc in postcommit
https://github.com/intel/llvm/actions/runs/10180580875/job/28159431987

[SYCL][E2E] Fix another matrix XPASS

---

sycl/test-e2e/Matrix/SG32/joint_matrix_prefetch.cpp

Feedback from https://github.com/intel/llvm/pull/14866

[SYCL][E2E] Fix SG32/joint_matrix_prefetch.cpp

---

sycl/source/detail/program_manager/program_manager.cpp

This would fix the post-commit fails for [14873](https://github.com/intel/llvm/pull/14873)

Revert NativePrograms addition for linkedPrograms to insert

---

sycl/doc/extensions/proposed/sycl_ext_oneapi_atomic16.asciidoc

[Doc] Update sycl_ext_oneapi_atomic16.asciidoc

---

sycl/test-e2e/AmdNvidiaJIT/kernel_and_bundle.cpp

It's failing, see [here](https://github.com/intel/llvm/issues/14989)

[SYCL][E2E] XFAIL kernel_and_bundle.cpp on HIP AMD

---

sycl/test-e2e/Matrix/SG32/joint_matrix_bf16_fill_k_cache.cpp
sycl/test-e2e/Matrix/SG32/joint_matrix_bf16_fill_k_cache_init.cpp
sycl/test-e2e/Matrix/SG32/joint_matrix_bf16_fill_k_cache_unroll.cpp
sycl/test-e2e/Matrix/SG32/joint_matrix_bf16_fill_k_cache_unroll_init.cpp
sycl/test-e2e/Matrix/SG32/joint_matrix_out_bounds.cpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache.cpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_OOB.cpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_impl.hpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_init.cpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_prefetch.cpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_unroll.cpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_unroll_init.cpp
sycl/test-e2e/Matrix/joint_matrix_out_bounds.cpp
sycl/test-e2e/Matrix/joint_matrix_out_bounds_impl.hpp

Also, this PR adds a fix for OOB test that does not comply with the spec today, it removes its XFAIL.

[SYCL][JM] Add prefetch and row major to the performance test

---

clang/include/clang/Basic/DiagnosticSemaKinds.td
clang/include/clang/Sema/SemaSYCL.h
clang/lib/Sema/SemaSYCL.cpp
clang/test/SemaSYCL/sycl-dllimport-dllexport.cpp
sycl/test-e2e/DeviceDependencies/Inputs/a.cpp
sycl/test-e2e/DeviceDependencies/Inputs/a.hpp
sycl/test-e2e/DeviceDependencies/Inputs/b.cpp
sycl/test-e2e/DeviceDependencies/Inputs/b.hpp
sycl/test-e2e/DeviceDependencies/Inputs/c.cpp
sycl/test-e2e/DeviceDependencies/Inputs/c.hpp
sycl/test-e2e/DeviceDependencies/Inputs/d.cpp
sycl/test-e2e/DeviceDependencies/Inputs/d.hpp
sycl/test-e2e/DeviceDependencies/dynamic.cpp

Allow device code to be exported by a Windows DLL.

[SYCL] Allow device code to be exported by a Windows DLL

---

clang/lib/Driver/ToolChains/Clang.cpp

Source change reference commit https://github.com/llvm/llvm-project/commit/13dd795ef108c75b1b6240832f77ca5282a2e629

Resolved build error

---

sycl/test-e2e/Assert/assert_in_multiple_tus.cpp

Flaky on DG2
https://github.com/intel/llvm/issues/15029

[SYCL][E2E] Disable assert_in_multiple_tus.cpp on Arc

---

sycl/cmake/modules/FetchUnifiedRuntime.cmake

-pre-commit PR for https://github.com/oneapi-src/unified-runtime/pull/1933

[UR][L0] Fix Driver Version check to use extension and tuple check

---

sycl/test-e2e/USM/memory_coherency_hip.cpp

[SYCL-E2E] Rename UNSET -> CLEAR in memory_coherency_hip.cpp

---

clang/lib/CodeGen/CGBuiltin.cpp
clang/test/CodeGen/fp-accuracy.c

This change due to https://github.com/llvm/llvm-project/pull/98949.

Add missing fpbuiltin math functions.

---

sycl/unittests/scheduler/GraphCleanup.cpp

Failing on Windows
https://github.com/intel/llvm/issues/15049

[SYCL] Disable SchedulerTest/StreamBufferDeallocation on Windows

---

sycl/cmake/modules/FetchUnifiedRuntime.cmake

-pre-commit PR for: https://github.com/oneapi-src/unified-runtime/pull/1955

[UR][L0] fix Coverity issues for L0 Adapter

---

sycl/test-e2e/ESIMD/addc.cpp
sycl/test-e2e/ESIMD/subb.cpp

This PR to reenable tests that were disabled on Windows as hanging but were not reproducible otherwise
Closes: https://github.com/intel/llvm/issues/14868

[ESIMD] Reenable Tests

---

sycl/test-e2e/ESIMD/addc.cpp
sycl/test-e2e/ESIMD/subb.cpp

Reverts intel/llvm#15019
The failure is still happening
https://github.com/intel/llvm/actions/runs/10403912708/job/28813946918

Revert "[ESIMD] Reenable Tests"

---

devops/dependencies-igc-dev.json

[GHA] Uplift Linux IGC Dev RT version to igc-dev-5bbe6c6

---

sycl/test-e2e/Graph/Inputs/dotp_buffer_reduction.cpp
sycl/test-e2e/Graph/Inputs/dotp_usm_reduction.cpp
sycl/test-e2e/Graph/Inputs/sub_graph_reduction.cpp
sycl/test-e2e/Graph/graph_common.hpp

Issue resulting of incomplete finer grained includes https://github.com/intel/llvm/pull/13846

[SYCL][Graph] Fix missing includes for e2e tests using reduction

---

sycl/cmake/modules/FetchUnifiedRuntime.cmake

[UR PR](https://github.com/oneapi-src/unified-runtime/pull/2006)

bump UR tag to devsan fix

---

sycl/include/sycl/ext/intel/esimd/memory.hpp

The purpose od this PR is to simplify implementation of some API by using simd_view internals

[NFC][ESIMD]Simplify the implementation by using simd_view internals

---

.github/CODEOWNERS

The codeowners should review the PR of auto lift, and follow up to merge
it timely.

[CI] Add codeowners for dependencies-igc-dev.json

---

devops/dependencies-igc-dev.json

[GHA] Uplift Linux IGC Dev RT version to igc-dev-97f373a

---

sycl/test/esimd/sycl_half_basic_ops.cpp

[SYCL][ESIMD] Fix LIT test in sycl-web

---

sycl/test-e2e/ESIMD/BitonicSortKv2.cpp

[SYCL][ESIMD][E2E] Re-enable BitonicSortKv2 on Arc

---

clang/lib/CodeGen/CodeGenModule.cpp

device global code conflict with 6e45fa95be9db5318ac7037c673c9b18a48ac5b1 
Fix failure:  Clang::CodeGenSYCL/device_global.cpp

Fix conflict resolution in Ctor for Device Global

---

sycl/source/detail/event_impl.cpp
sycl/test-e2e/Plugin/interop-level-zero.cpp

Fix the issue caught by static analyzer after #15179

[SYCL] Follow-up fix after #15179

---

sycl/source/detail/ur.cpp

This change (originally from a073a6ae21c755f3be3de5a6a78684861beb1fae) was accidentality reverted on the change from PI to UR. This patch applies the change to the UR equivalent.
The upstream bug seems to have been fixed, so the test just happened to pass on our build system.
See https://github.com/intel/llvm/pull/13367 for original change.

[SYCL] Redo "fix a hang with invalid values of ONEAPI_DEVICE_SELECTOR"

---

devops/dependencies.json

[GHA] Uplift Linux GPU RT version to 24.31.30508.7

---

libdevice/cmath_wrapper.cpp
libdevice/cmath_wrapper_fp64.cpp
libdevice/device_math.h
libdevice/fallback-cmath-fp64.cpp
libdevice/fallback-cmath.cpp
sycl/test-e2e/DeviceLib/cmath_fp64_test.cpp
sycl/test-e2e/DeviceLib/cmath_test.cpp

Add support for missing scalbln function

[SYCL] Add support for scalbln

---

sycl/source/detail/plugin.hpp

#15262 failed post-commit testing, this should fix it

Fix unused plugin member after #15262

---

sycl/cmake/modules/FetchUnifiedRuntime.cmake

Build is broken for everyone, need to use this UR commit to fix it.

[SYCL][UR] Fix OpenCL adaptor build

---

sycl/test-e2e/DeviceGlobal/device_global_static.cpp

[HIP] Don't run failing device global test on AMD

---

sycl/test-e2e/KernelCompiler/kernel_compiler_opencl.cpp
sycl/test-e2e/KernelCompiler/kernel_compiler_sycl.cpp
sycl/test-e2e/KernelCompiler/multi_device.cpp

minor changes to ensure tests are and are not run on appropriate devices

[SYCL] minor changes to kernel_compiler tests. 

---

llvm/lib/Analysis/BasicAliasAnalysis.cpp
llvm/test/Analysis/BasicAA/issue103500.ll

Cherry pick https://github.com/llvm/llvm-project/pull/103713 to fix AMD postcommit testing.
Closes: https://github.com/intel/llvm/issues/15227

BasicAA: Fix assert when indexing address spaces with different sizes (#103713)

---

.github/CODEOWNERS

The new line was overwritten by last win rules.
Fix the order.

[CODEOWNERS] Fix the last win

---

llvm-spirv/lib/SPIRV/SPIRVReader.cpp
llvm-spirv/test/image.ll

[SPIRV] Filter out illegal attributes to align with Khronos behaviour

---

sycl/cmake/modules/FetchUnifiedRuntime.cmake

For https://github.com/oneapi-src/unified-runtime/pull/2060

[UR] Suppress system errors when loading adapters on Windows

---

devops/dependencies-igc-dev.json

[GHA] Uplift Linux IGC Dev RT version to igc-dev-a20debc

---

sycl/cmake/modules/FetchUnifiedRuntime.cmake
sycl/test-e2e/Plugin/level_zero_barrier_optimization.cpp

-pre-commit Pr for https://github.com/oneapi-src/unified-runtime/pull/2087

[UR][L0] Fix urEnqueueEventsWaitWithBarrier for driver in order lists

---

sycl/test-e2e/syclcompat/memory/memory_management_test2.cpp

[E2E Test] Enable memory_management_test2

---

llvm/lib/SYCLLowerIR/ComputeModuleRuntimeInfo.cpp

Follow up from https://github.com/intel/llvm/pull/15346.

[SYCL] Add sanity checks for spec constant metadata

---

sycl/doc/syclgraph/SYCLGraphUsageGuide.md

There was a small problem with the dot product example that did not allow for correct compilation.

[SYCL][GRAPHS][DOCS] Updated the example so it compiles.

---

.github/workflows/sycl-linux-precommit.yml
devops/dependencies.json

Fixes driver installation error on CUDA https://github.com/intel/llvm/actions/runs/11034793136/job/30649588491?pr=15481

[CI] Do not install igc drivers on CUDA and AMD runners

---

sycl/test-e2e/Plugin/level_zero_device_free_mem.cpp
sycl/test-e2e/USM/memops2d/copy2d_dhost_to_shared.cpp
sycl/test-e2e/USM/memops2d/copy2d_host_to_shared.cpp
sycl/test-e2e/USM/memops2d/copy2d_shared_to_dhost.cpp
sycl/test-e2e/USM/memops2d/copy2d_shared_to_host.cpp
sycl/test-e2e/USM/memops2d/memcpy2d_dhost_to_shared.cpp
sycl/test-e2e/USM/memops2d/memcpy2d_host_to_shared.cpp
sycl/test-e2e/USM/memops2d/memcpy2d_shared_to_host.cpp

Failing on the new driver [here](https://github.com/intel/llvm/actions/runs/11259739126/job/31309872610?pr=15626).

[SYCL][E2E] XFAIL tests failing in new driver

---

devops/dependencies.json

[GHA] Uplift Linux GPU RT version to 24.35.30872.22

---

sycl/test-e2e/ESIMD/clz_ctz.cpp

We have a new enough driver now.

[SYCL][ESIMD][E2E] Test CLZ/CTZ with more types

---

.github/workflows/sycl-linux-run-tests.yml

The branch was renamed to simple "main".

[CI][CTS] Update sycl-linux-run-tests.yml

---

sycl/test-e2e/ESIMD/linear/linear.cpp

The root cause of this test failure on the new driver is that this test by design reads beyond the bounds of the input image and uses the out of boundary data in calculations for the output. New driver returns 0s for all the data read beyond the image boundaries but the old driver replicates the last read data. I am not sure if this is the driver issue or an issue with image/accessor and therefore the safest solution that will work on old and new driver is to replicate the behavior of the old driver in the test so it will work both for old and new drivers

[ESIMD] Fix linear test on new GPU driver

---

sycl/test-e2e/DiscardEvents/discard_events_check_images.cpp
sycl/test-e2e/ESIMD/group_barrier.cpp

Failing [here](https://github.com/intel/llvm/actions/runs/11452499228/job/31891617070?pr=15796), I'll bump the driver after this change.
https://github.com/intel/llvm/issues/15812

[SYCL][E2E] XFAIL tests failing on new driver

---

devops/dependencies.json

[GHA] Uplift Linux GPU RT version to 24.39.31294.12

---

sycl/test-e2e/Plugin/level_zero_device_free_mem.cpp
sycl/test-e2e/VirtualMem/vector_with_virtual_mem.cpp
sycl/test-e2e/no-xfail-without-tracker.cpp

See [here](https://github.com/intel/llvm/actions/runs/11467512551/job/31911188728).
I've updated the corresponding issues.

[SYCL][E2E] Fix two tests on new DG2 driver

---

sycl/cmake/modules/UnifiedRuntimeTag.cmake

Includes:
https://github.com/oneapi-src/unified-runtime/pull/2001
https://github.com/oneapi-src/unified-runtime/pull/2143
https://github.com/oneapi-src/unified-runtime/pull/2160

[UR] Pull in a batch of CL adapter fixes.

---

sycl/test-e2e/InvokeSimd/Regression/ImplicitSubgroup/call_vadd_1d_spill.cpp
sycl/test-e2e/InvokeSimd/Regression/call_vadd_1d_spill.cpp

They're failing and we need to wait for this tracker for the fix.

[SYCL][InvokeSimd] Disable call_vadd_1d_spill.cpp

---

sycl/test-e2e/ESIMD/frem.cpp

The version is too low, I manually verified this one is right.

[SYCL][ESIMD][E2E] Update driver check in frem test

---

sycl/doc/GetStartedGuide.md

Added instructions to compile on ARM systems

[SYCL][Doc] Add instructions to build for ARM processors

---

sycl/cmake/modules/UnifiedRuntimeTag.cmake

-pre-commit PR for https://github.com/oneapi-src/unified-runtime/pull/2228

[UR][L0] [L0] Refactor Copy Engine Usage checks for Performance

---

sycl/test-e2e/ESIMD/group_barrier.cpp

The test was wrong, we can't use this function with runtime `if`, so move them to compile time.

[SYCL][ESIMD][E2E] Fix group_barrier test on DG2

---

sycl/test-e2e/Graph/Update/update_nullptr.cpp

Test for updating a dynamic parameter with a nullptr USM parameter.

[SYCL][Graph] E2E test for nullptr dynamic parameter update

---

sycl/cmake/modules/UnifiedRuntimeTag.cmake

Pulls in https://github.com/oneapi-src/unified-runtime/pull/2302

[UR] Bump UR tag to c94dbc8

---

devops/cts_exclude_filter_L0_GPU
devops/cts_exclude_filter_OCL_CPU

[CI] Turn on test_accessor_legacy

---

.github/workflows/sycl-post-commit.yml

Reverts intel/llvm#16079
This is cancelling jobs in unexpected ways, I need to debug it and fix the problem.

Revert "[CI] Only run one post commit job on a push to a pull request in sycl-devops-pr"

---

devops/dependencies-igc-dev.json

[GHA] Uplift Linux IGC Dev RT version to igc-dev-0b4b682

---

devops/dependencies-igc-dev.json

[GHA] Uplift Linux IGC Dev RT version to igc-dev-ac93a93

---

sycl-jit/jit-compiler/lib/rtc/DeviceCompilation.cpp

Fixes post-commit failure due to an unused variable introduced by #16109.

[SYCL][RTC] Fix post-commit failure

---

sycl/source/detail/scheduler/commands.cpp
sycl/source/handler.cpp
sycl/test-e2e/Basic/empty_command.cpp

Revert "[SYCL] Honor dependencies of empty command groups"

---

sycl/cmake/modules/UnifiedRuntimeTag.cmake

Pulls in https://github.com/oneapi-src/unified-runtime/pull/2396

[UR] Bump UR tag to eb076da

---

devops/cts_exclude_filter_L0_GPU

After product change the test requires an update.

[CI][CTS] Temporarily turn off test_device

---

clang/lib/Driver/ToolChains/SYCL.cpp

Move addSingleLibrary etc into WIN32 guard, avoid unused function warnings in windows build.

[SYCL][Driver] Fix windows build warning

---

sycl/cmake/modules/UnifiedRuntimeTag.cmake

Testing PR for https://github.com/oneapi-src/unified-runtime/pull/2395

[UR][L0] fix event caching

---

sycl/cmake/modules/FetchUnifiedRuntime.cmake
sycl/cmake/modules/UnifiedRuntimeTag.cmake

URT PR: https://github.com/oneapi-src/unified-runtime/pull/2334

[UR] Interrupt-based event implementation

---

sycl/cmake/modules/UnifiedRuntimeTag.cmake

https://github.com/oneapi-src/unified-runtime/pull/2430

[UR] Update tag to 45f3d8 

---

llvm/lib/Transforms/Instrumentation/AddressSanitizer.cpp

[DeviceSanitizer] Update AddressSanitizer.cpp for coverity fix

---

devops/containers/ubuntu2204_base.Dockerfile
devops/containers/ubuntu2204_build.Dockerfile
devops/containers/ubuntu2204_intel_drivers.Dockerfile
devops/containers/ubuntu2204_preinstalled.Dockerfile
devops/containers/ubuntu2404_base.Dockerfile
devops/containers/ubuntu2404_intel_drivers.Dockerfile
devops/containers/ubuntu2404_intel_drivers_igc_dev.Dockerfile
devops/scripts/docker_entrypoint.sh

Reverts intel/llvm#16290
Discussed with Alexey offline, reverting for now until we can address some more issues.
CI failures expected, it's not actually using the changes in this PR.

Revert "[SYCL][Devops] Fix `DockerFile` linting issues discovered by trivy"

---

sycl/cmake/modules/UnifiedRuntimeTag.cmake

https://github.com/oneapi-src/unified-runtime/pull/2272/
https://github.com/oneapi-src/unified-runtime/pull/2336

[UR] Update tag to 6d4eec8c for UR#2272 and UR#2336

---

sycl/cmake/modules/FetchUnifiedRuntime.cmake
sycl/cmake/modules/UnifiedRuntimeTag.cmake

-pre-commit PR for https://github.com/oneapi-src/unified-runtime/pull/2476

[UR][L0] Fix Event Memory Leak due to no destroy on delete

---

.github/CODEOWNERS

Add more files that we need for device memory sanitizer.

[DeviceSanitizer] update code owner

---

.github/workflows/sycl-linux-run-tests.yml

It's failing due to some other CI changes.

[CI] Temporarily disable GPU reset

---

.github/workflows/sycl-linux-run-tests.yml

[SYCL][Devops] Drop `-S` flag to `sudo`

---

sycl/test/check_device_code/vector/vector_convert_bfloat.cpp

[InstCombine] Optimistically allow multiple shufflevector uses in foldOpPhi

[SYCL] Update vector_convert_bfloat after 768754807f177

---

sycl/test-e2e/Matrix/joint_matrix_bfloat16_array_impl.hpp

Fix minor issue causing the same test case repeat multiple times

[SYCL][E2E][Joint Matrix] Move break to the correct place

---

sycl/cmake/modules/FetchUnifiedRuntime.cmake
sycl/cmake/modules/UnifiedRuntimeTag.cmake

UR PR: https://github.com/oneapi-src/unified-runtime/pull/2498

[UR] Bump UR with zeCommandListImmediateAppendCommandListsExp usages fixes

---

clang/lib/Driver/ToolChains/SYCL.cpp
libdevice/cmake/modules/SYCLLibdevice.cmake
libdevice/sanitizer/msan_rtl.cpp
sycl/cmake/modules/FetchUnifiedRuntime.cmake
sycl/cmake/modules/UnifiedRuntimeTag.cmake

UR: https://github.com/oneapi-src/unified-runtime/pull/2507

[DeviceMSAN] Fix MemToShadow algorithm and VA reservation

---

devops/dependencies.json

[GHA] Uplift Linux GPU RT version to 24.48.31907.7

---

sycl/cmake/modules/UnifiedRuntimeTag.cmake

- https://github.com/oneapi-src/unified-runtime/pull/2501
- https://github.com/oneapi-src/unified-runtime/pull/2502

[UR] Update tag to ad288bb 

---

sycl/test-e2e/README.md

Enforce 80 character line length.

[NFC][Doc] Fix typos and linter issues.

---

sycl/doc/extensions/template.asciidoc

[SYCL][Doc] Update extension template copyright year

---

sycl/source/detail/os_util.cpp

Failure: https://github.com/intel/llvm/actions/runs/12601531257/job/35122811530#step:12:83

[SYCL] Fix `unused_function` error in post-commit

---

sycl/cmake/modules/FetchUnifiedRuntime.cmake
sycl/cmake/modules/UnifiedRuntimeTag.cmake

Batches the following bug fixes:
* https://github.com/oneapi-src/unified-runtime/pull/2504
* https://github.com/oneapi-src/unified-runtime/pull/2517
* https://github.com/oneapi-src/unified-runtime/pull/2524

[UR] Bump tag to 3472b5bda

---

sycl/test-e2e/Matrix/SG32/joint_matrix_bfloat16_colmajorA_colmajorB.cpp
sycl/test-e2e/Matrix/SG32/joint_matrix_colA_rowB_colC.cpp
sycl/test-e2e/Matrix/common.hpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_impl.hpp
sycl/test-e2e/Matrix/joint_matrix_bfloat16_colmajorA_colmajorB.cpp
sycl/test-e2e/Matrix/joint_matrix_bfloat16_colmajorA_colmajorB_impl.hpp
sycl/test-e2e/Matrix/joint_matrix_colA_rowB_colC.cpp
sycl/test-e2e/Matrix/joint_matrix_colA_rowB_colC_impl.hpp

with this fix joint_matrix_colA_rowB_colC.cpp is passing on CPU

[SYCL][Joint Matrix][E2E] Fix several tests

---

sycl/cmake/modules/UnifiedRuntimeTag.cmake

https://github.com/oneapi-src/unified-runtime/pull/2512

[NativeCPU] Handle local args.

---

sycl/test-e2e/OnlineCompiler/online_compiler_L0.cpp
sycl/test-e2e/OnlineCompiler/online_compiler_OpenCL.cpp

https://github.com/intel/llvm/issues/16406

[sycl-rel] Turn off OnlineCompiler tests

---

.github/workflows/sycl-rel-nightly.yml

Also use the latest image for cuda

[CI][sycl-rel] Build llvm with ubuntu2204 image

---

clang/lib/Driver/ToolChains/Clang.cpp
clang/test/Driver/sycl-spirv-backend.cpp

We introduce here SPIR-V Backend support in Clang/Driver

[Clang] Update of invoking SPIR-V Backend in Clang/Driver

---

llvm-spirv/lib/SPIRV/SPIRVRegularizeLLVM.cpp

This reverts commit aaa2e1356ed4d74502b939a548cb36c2700a3354.
As it was a workaround, and the GPU drivers are updated in CI now, we can safely remove it to align back the translator's code base to Khronos.

Revert "[SPIR-V][OpaquePointers] Temporary workaround for IGC issue (#10407)"

---

devops/dependencies.json

[GHA] Uplift Linux GPU RT version to 24.52.32224.5

---

sycl/test-e2e/ESIMD/named_barriers/loop_extended.cpp

https://github.com/intel/llvm/issues/16598

[SYCL][ESIMD][E2E] Disable loop_extended as it's flaky

---

devops/scripts/install_build_tools.sh

To be used in https://github.com/intel/llvm/pull/16648.

[CI] Install `time` in our docker images

---

sycl/cmake/modules/UnifiedRuntimeTag.cmake

UR: https://github.com/oneapi-src/unified-runtime/pull/2539

[UR] Bump with DEVICE_INFO_PROGRAM_SET_SPECIALIZATION_CONSTANTS

---

.github/workflows/sycl-linux-run-tests.yml

Built on top of https://github.com/intel/llvm/pull/16680.

[CI] Use updated nightly container in `sycl-linux-run-tests.yml`

---

sycl/tools/install.bat

Fix the script to not give unnecessary permissions.

[SYCL] Fix runtimes installation script

---

llvm/lib/SYCLNativeCPUUtils/FAtomicsNativeCPU.cpp

[SYCL][NATIVECPU] fixed module flag

---

sycl/cmake/modules/FetchUnifiedRuntime.cmake
sycl/cmake/modules/UnifiedRuntimeTag.cmake

UR PR: https://github.com/oneapi-src/unified-runtime/pull/2605

[UR][DeviceASAN] Bugfix for GetDeviceType

---

devops/cts_exclude_filter_L0_GPU

[CI][CTS] Update cts_exclude_filter_L0_GPU

---

sycl/cmake/modules/UnifiedRuntimeTag.cmake

https://github.com/oneapi-src/unified-runtime/pull/2574

[UR] fix parseDisjointPoolConfig and add tests

---

llvm/lib/SYCLLowerIR/LowerWGLocalMemory.cpp

To make the code more explicit and allow for future expansion.

[SYCL][NFC] Helper for implicit kernarg targets in LowerWGLocalMemory

---

devops/cts_exclude_filter_compfails

[CI][CTS] Turn on test_handler

---

sycl/doc/extensions/experimental/sycl_ext_matrix/sycl_ext_intel_matrix.asciidoc
sycl/doc/extensions/experimental/sycl_ext_matrix/sycl_ext_oneapi_matrix.asciidoc
sycl/source/detail/device_impl.cpp
sycl/source/detail/device_info.hpp
sycl/test-e2e/Basic/AMX_aspect.cpp
sycl/test-e2e/matrix_aspect.cpp

Also, as part of this PR, I added missing references to architectures we recently added  (BMG, LNL)

[SYCL][JM] Add Panther Lake (PTL) support to joint matrix query and aspect

---

sycl/test-e2e/Graph/lit.local.cfg

Re-enables graph tests for Arc/DG2 in CI.

[SYCL][Graph] Re-enable DG2 testing for graphs

---

sycl/test-e2e/ESIMD/named_barriers/loop.cpp

[SYCL][ESIMD][E2E] Disable loop.cpp because it's flaky

---

devops/dependencies-igc-dev.json
sycl/test-e2e/DeviceLib/imf_simd_emulate_test.cpp

[GHA] Uplift Linux IGC Dev RT version to igc-dev-d26e243

---

sycl/source/detail/graph_impl.cpp

[SYCL][Graph] Fix race in node queries

---

sycl/tools/install.bat

Fix the script to not give unnecessary permissions.

[SYCL] Fix runtimes installation script (#16719)

---

sycl/test-e2e/EnqueueNativeCommand/custom-command-multiple-dev-cuda.cpp
sycl/test-e2e/WorkGroupScratchMemory/copy_dynamic_size.cpp

See https://github.com/intel/llvm/actions/runs/13321667846

[SYCL][E2E] Disable CUDA tests sporadically failing in nightly

---

devops/dependencies-igc-dev.json

[GHA] Uplift Linux IGC Dev RT version to igc-dev-5415e63

---

sycl/test/e2e_test_requirements/no-unsupported-without-info.cpp

[SYCL] Fix unsupported checker test

---

clang/test/Driver/sycl-offload-new-driver.c
clang/test/Driver/sycl-offload.cpp

Fixes sycl-offload lit tests caused from pulldown conflicts and merge resolutions.

[Offload][PD] Fix failing lit tests in sycl-web

---

devops/dependencies-igc-dev.json

[GHA] Uplift Linux IGC Dev RT version to igc-dev-485a03a

---

.github/workflows/sycl-linux-precommit.yml

I reset the runner and disabled some tests, let's try again.
Reverts intel/llvm#17110

[CI] Re-enable BMG in precommit

---

sycl/test-e2e/LLVMIntrinsicLowering/sub_byte_bitreverse.cpp

Address feedback from https://github.com/intel/llvm/pull/17126

[SYCL][E2E] Add IGC issue link to sub_byte_bitreverse UNSUPPORTED line

---

sycl/test-e2e/ESIMD/matrix_transpose_glb.cpp

Randomly failing on various GPUs.

[SYCL][ESIMD][E2E] Disable matrix_transpose_glb again

---

sycl/test-e2e/Adapters/retain_events.cpp
sycl/test-e2e/HostInteropTask/host-task-dependency3.cpp

See:
* https://github.com/intel/llvm/issues/17236
* https://github.com/intel/llvm/issues/17235

[SYCL][E2E] Disable flaky tests on AMD

---

devops/dependencies.json

[GHA] Uplift Linux GPU RT version to 25.05.32567.17

---

sycl/test-e2e/AOT/early_aot.cpp
sycl/test-e2e/BFloat16/bfloat16_example_aot_gpu.cpp
sycl/test-e2e/SpecConstants/2020/image_selection.cpp

Currently failing in postcommit.
See https://github.com/intel/llvm/issues/17305

[SYCL][E2E] XFAIL AOT tests failing on new driver

---

devops/cts_exclude_filter_compfails

fix: https://github.com/KhronosGroup/SYCL-CTS/pull/1061

[CI][CTS] Enable test_accessor_legacy

---

sycl/test-e2e/WeakObject/weak_object_expired.cpp
sycl/test-e2e/WorkGroupMemory/basic_usage.cpp

[SYCL][E2E] Disable two flaky tests on AMD

---

sycl/test-e2e/Adapters/level_zero_batch_test_copy_with_compute.cpp

[SYCL][E2E] Disable level_zero_batch_test_copy_with_compute.cpp on BMG Windows

---

sycl/test-e2e/DeprecatedFeatures/subbuffer_interop.cpp

[SYCL][E2E] Fix a leak in test

---

sycl/source/detail/allowlist.cpp

Add traces to `SYCL_UR_TRACE` for filtering/allowing devices due to `SYCL_DEVICE_ALLOWLIST` in response to #17114.
These traces will look like this:
```
SYCL_UR_TRACE: Device allowed by SYCL_DEVICE_ALLOWLIST
SYCL_UR_TRACE:   platform: Intel(R) OpenCL
SYCL_UR_TRACE:   device: Intel(R) Xeon(R) Platinum 8380 CPU @ 2.30GHz
```
```
SYCL_UR_TRACE: Device filtered by SYCL_DEVICE_ALLOWLIST
SYCL_UR_TRACE:   platform: Intel(R) FPGA Emulation Platform for OpenCL(TM)
SYCL_UR_TRACE:   device: Intel(R) FPGA Emulation Device
```

[SYCL] Add traces for `SYCL_DEVICE_ALLOWLIST` decisions

---

.github/CODEOWNERS

* Add NVPTX and AMDGPU LLVM backends
* Add CUDA and HIP specific SYCLLowerIR passes

[CODEOWNERS] Update review paths for CUDA and HIP

---

.github/workflows/docs.yml
.github/workflows/pr-code-format.yml

[CI] Use hash for changed-files instead of tag

---

.github/workflows/sycl-linux-precommit.yml
.github/workflows/sycl-windows-precommit.yml
sycl/cts_exclude_filter/compfails

Disable the pre-commit for changes in cts_exclude_filter as it's not affected.

[CI] Ignore changes in sycl/cts_exclude_filter in pre-commit

---

sycl/source/detail/scheduler/commands.cpp

This is a cherry-pick of intel/llvm#16264 and intel/llvm#16268

[SYCL][NFC] Fix build with `clang`

---

unified-runtime/source/loader/layers/sanitizer/msan/msan_report.cpp

[DeviceMSAN] Fix typo

---

devops/dependencies-igc-dev.json

[GHA] Uplift Linux IGC Dev RT version to igc-dev-81b4de2

---

sycl/test-e2e/lit.cfg.py

Need this for Windows where there are spaces in the path.

[SYCL][E2E] Quote paths used in SDK testing

---

devops/dependencies.json

[GHA] Uplift Linux GPU RT version to 25.09.32961.7

---

sycl/test-e2e/AddressSanitizer/lit.local.cfg
sycl/test-e2e/MemorySanitizer/lit.local.cfg
sycl/test-e2e/ThreadSanitizer/lit.local.cfg

Also, convert the indentation to use spaces instead of tabs.

[DeviceSanitizer] Skip running test when other sanitizers is enabled

---

.github/workflows/sycl-detect-changes.yml

Shown working [here](https://github.com/sarnex/llvm/actions/runs/14203819229/job/39796735530?pr=2).

[CI] Actually fix detect-changes for large PRs

---

.github/workflows/sycl-windows-run-tests.yml
devops/actions/run-tests/e2e/action.yml

I think this will save around 30s for every e2e job.

[CI] Used sparse checkout for checking out e2e tests

---

.github/workflows/sycl-rel-nightly.yml

Also align some strings with regular sycl-nightly

[CI][sycl-rel] Add BMG to sycl-rel-nightly

---

devops/dependencies-igc-dev.json

[GHA] Uplift Linux IGC Dev RT version to igc-dev-b74b7ab

---

.github/workflows/sycl-rel-nightly.yml

Fix repo_ref value. I probably didn't notice it when I changed the others.

[CI] Update sycl-rel-nightly.yml

---

devops/scripts/benchmarks/benches/compute.py

This pulls in two important changes that make the results more accurate:
- Fix accuracy of time measurement in submit_kernel_ur
- Align kernel operation for submit graph in sycl

[CI][Benchmarks] update compute-benchmarks

---

unified-runtime/source/adapters/level_zero/context.cpp
unified-runtime/source/adapters/level_zero/event.cpp
unified-runtime/source/adapters/level_zero/kernel.cpp
unified-runtime/source/adapters/level_zero/memory.cpp
unified-runtime/source/adapters/level_zero/queue.cpp
unified-runtime/source/adapters/level_zero/sampler.cpp
unified-runtime/source/adapters/level_zero/v2/common.hpp

- Fix logic check during error handling after destroy calls.

[UR][L0] Fix logic check in error checking

---

sycl/test-e2e/Adapters/level_zero_events_caching_leak.cpp

[SYCL][E2E] Disable L0 event caching test on Win BMG

---

sycl/test/regression/std_array_vec_constructor.cpp

Regression test for CMPLRLLVM-66787

[SYCL] Add regression test for use of `std::array` in `sycl::vec` constructor

---

devops/dependencies-igc-dev.json

[GHA] Uplift Linux IGC Dev RT version to igc-dev-af17e0f

---

devops/scripts/benchmarks/benches/compute.py

This PR introduces USM memory allocation benchmark scenarios to compute benchmark suite.
Retargeting #17623 to the sycl branch.

[CI][Benchmark] Add compute USM allocation benchmarks

---

devops/scripts/benchmarks/benches/compute.py

This fixes a regression after #17876

[CI][Benchmarks] fix compute-benchmarks compilation

---

.github/workflows/sycl-rel-nightly.yml

[CI] Fix the workflow name

---

sycl/test-e2e/OptionalKernelFeatures/is_compatible/is_compatible_nvptx64.cpp

I fixed the LIT infra so this works now. AMDGPU one is coming later.

[SYCL][E2E] Enable is_compatible_nvptx64.cpp on Windows

---

unified-runtime/scripts/add_experimental_feature.py
unified-runtime/scripts/ctest_parser.py
unified-runtime/scripts/generate_code.py
unified-runtime/scripts/generate_docs.py
unified-runtime/scripts/generate_ids.py
unified-runtime/scripts/generate_kernel_header.py
unified-runtime/scripts/json2src.py
unified-runtime/scripts/parse_specs.py
unified-runtime/scripts/run.py
unified-runtime/scripts/util.py
unified-runtime/scripts/verify_license.py
unified-runtime/scripts/version.py

* Move copyright notices out of file `__doc__` strings and into comments
* Move function `__doc__` strings into functions

[NFC][UR] Cleanup Python generator scripts

---

devops/dependencies.json

[CI] Revert Level Zero bump yet again

---

devops/dependencies.json

I manually tested it and it finally works this time.

[CI] Hopefully successfully update Level Zero to 1.21.9

---

.github/workflows/bandit.yml
.github/workflows/sycl-issues-ping-assignee.yml
.github/workflows/sycl-rel-nightly.yml
.github/workflows/sycl-stale-issues.yml

And also disable aws-stop in sycl-rel nightly if aws-start was skipped.

[CI] Disable some workflows in forks

---

sycl/include/sycl/handler.hpp

No value in thin wrappers requiring extra instantiation for every kernel.

[SYCL][NFCI] Use `wrap_kernel` directly in the user-facing API

---

sycl/source/detail/jit_compiler.cpp

Fix post-commit checks for #17929.

[SYCL] Squash warning on Windows

---

unified-runtime/source/adapters/opencl/platform.cpp

The logic here was incorrect in cases where no platforms are available
(and thus `clGetPlatformIDs` returns `CL_PLATFORM_NOT_FOUND_KHR`).

[UR][OpenCL] Fix handling of urPlatformGet where there are no platforms

---

sycl/include/sycl/detail/array.hpp
sycl/include/sycl/handler.hpp
sycl/source/detail/cg.hpp
sycl/source/handler.cpp

Reverts [#17969](https://github.com/intel/llvm/pull/17969), based on the discussion.

[SYCL] Revert "Optimize handler::setNDRangeDescriptor"

---

sycl/test-e2e/MemorySanitizer/check_large_access.cpp

XPASSing [here](https://github.com/intel/llvm/actions/runs/14528951205)

[SYCL][E2E] Re-renable check_large_access.cpp on CPU

---

sycl/unittests/program_manager/MultipleDevsKernelBundle.cpp

See [here](https://github.com/intel/llvm/issues/18122).

[SYCL] Disable sporadically failing cache unit test

---

sycl/test-e2e/USM/hmemll.cpp

See https://github.com/intel/llvm/issues/17582

[SYCL][E2E] Disable hmell.cpp on BMG Win

---

.github/workflows/sycl-windows-run-tests.yml

[CI] Set timeout for running Windows prebuilt tests

---

unified-runtime/include/ur_api.h
unified-runtime/scripts/core/exp-async-alloc.yml
unified-runtime/source/loader/layers/validation/ur_valddi.cpp
unified-runtime/source/loader/ur_libapi.cpp
unified-runtime/source/ur_api.cpp

[UR] add missing validation layer checks for exp enqueue functions

---

unified-runtime/source/loader/layers/sanitizer/asan/asan_buffer.cpp
unified-runtime/source/loader/layers/sanitizer/msan/msan_buffer.cpp
unified-runtime/source/loader/layers/sanitizer/msan/msan_ddi.cpp
unified-runtime/source/loader/layers/sanitizer/msan/msan_shadow.cpp
unified-runtime/source/loader/layers/sanitizer/tsan/tsan_buffer.cpp
unified-runtime/source/loader/layers/sanitizer/tsan/tsan_ddi.cpp

* Release local & private shadow memory
* Release events after call urEnqueueEventsWait

[DevSanitizer] Fix event and usm leak in sanitizer layer

---

.github/workflows/sycl-windows-build.yml
.github/workflows/sycl-windows-run-tests.yml

No idea why I did this before.

[CI] Fail if early hang check fails

---

sycl/source/detail/kernel_compiler/kernel_compiler_opencl.cpp

Presently, the KernelCompiler just tries to load whatever ocloc shared library is in the environment. And if it doesn't find a compatible one, then it reports that OpenCL C compilation is not supported.  But on Windows this should be more robust, so we are adding fallback support. If the ocloc shared library in the environment isn't compatible, try the one in the OneAPI installation.

[SYCL] Add fallback support for KernelCompiler loading of ocloc

---

sycl/source/detail/kernel_compiler/kernel_compiler_opencl.cpp

coverity wants a reference. not going to argue with it.

[SYCL][NFC] small coverity fix

---

sycl/test-e2e/USM/mixed2template.cpp

See https://github.com/intel/llvm/issues/18315

[SYCL][E2E] Disable mixed2template.cpp on Win BMG

---

sycl/include/sycl/handler.hpp
sycl/source/detail/cg.hpp

The performance gain is not significant enough to justify the change.

[SYCL] Revert "Optimize setNDRangeDescriptor functions (#18132)"

---

sycl/include/sycl/ext/oneapi/experimental/enqueue_functions.hpp

Follow up PR is required to omit event creation for graph enqueue.

[SYCL] Delegate to free function submit for graph enqueue

---

xptifw/src/CMakeLists.txt

Update dep version to include fix of coverity hits https://github.com/ktprime/emhash/commit/4fc20c7c9b048651c03258460e4662c8d3a04520

[XPTI] Update emhash dependency to fix code analyzer hits

---

unified-runtime/source/adapters/cuda/enqueue.cpp
unified-runtime/source/adapters/level_zero/adapter.cpp
unified-runtime/source/adapters/opencl/enqueue.cpp
unified-runtime/source/loader/layers/tracing/ur_trcddi.cpp
unified-runtime/source/loader/layers/validation/ur_valddi.cpp

Fix of compilation errors caused by merge of https://github.com/intel/llvm/pull/17684

[UR] Fix PR #17684 - change in logs

---

unified-runtime/source/adapters/level_zero/kernel.cpp

Fix breakage in https://github.com/intel/llvm/actions/runs/14966482804/job/42038058823?pr=18370

[UR][L0] fix sign-compare error

---

unified-runtime/test/conformance/source/environment.cpp
unified-runtime/test/conformance/testing/include/uur/environment.h

Add a note to suggest checking if UR_CONFORMANCE_TARGET_TRIPLES includes
the requested target.
Depends on: https://github.com/intel/llvm/pull/18279

[UR][Test] Improve error message when kernel source is not found

---

devops/actions/cached_checkout/action.yml

We don't want to try to make a merge commit.

[CI] Do a rebase pull when updating the repo cache

---

sycl/cts_exclude_filter/compfails

https://github.com/intel/llvm/issues/18540

[CI][sycl-cts] Disable test_bit_cast

---

unified-runtime/source/adapters/cuda/command_buffer.cpp

[CUDA] Fix trailing semicolon

---

devops/dependencies.json
sycl/test-e2e/Adapters/level_zero/ext_intel_cslice.cpp
sycl/test-e2e/Adapters/level_zero/ext_intel_queue_index.cpp
sycl/test-e2e/Adapters/sycl-ls-uuid-subdevs.cpp
sycl/test-e2e/Graph/Explicit/add_nodes_after_finalize.cpp
sycl/test-e2e/Graph/Explicit/buffer_ordering.cpp
sycl/test-e2e/Graph/RecordReplay/buffer_ordering.cpp
sycl/test-e2e/GroupAlgorithm/SYCL2020/group_sort/group_and_joint_sort.cpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache.cpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_SLM.cpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_arg_dim.cpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_init.cpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_prefetch.cpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_runtime_dim.cpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_unroll.cpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_unroll_init.cpp
sycl/test-e2e/MemorySanitizer/check_large_access.cpp

[GHA] Uplift Linux GPU RT version to 25.13.33276.19

---

devops/scripts/benchmarks/benches/gromacs.py
devops/scripts/benchmarks/utils/oneapi.py

Fix the configuration of the Gromacs benchmark

[UR][Benchmark] fix the MKL path for Gromacs bench

---

.github/workflows/sycl-linux-run-tests.yml
.github/workflows/sycl-nightly.yml

It's the wrong place for this property. Move to the right one.
Test run: https://github.com/intel/llvm/actions/runs/15183290790

[CI] Move sycl-cts timeout

---

sycl/test-e2e/Graph/Explicit/basic_buffer.cpp
sycl/test-e2e/Graph/Explicit/buffer_copy.cpp
sycl/test-e2e/Graph/Explicit/buffer_copy_2d.cpp
sycl/test-e2e/Graph/RecordReplay/basic_buffer.cpp
sycl/test-e2e/Graph/RecordReplay/buffer_copy.cpp
sycl/test-e2e/Graph/RecordReplay/queue_constructor_buffer.cpp

There might be different underlying issues but all are tracked by #18668.

[Graph][E2E] Mark flakily failing LIT tests as UNSUPPORTED

---

sycl-jit/jit-compiler/lib/translation/SPIRVLLVMTranslation.cpp

[SYCL] Elide unnecessary SmallVector instance and copy

---

clang/utils/analyzer/requirements.txt

Fixes some vulnerability warnings.
I've [submitted](https://github.com/llvm/llvm-project/pull/143433) this upstream too, but ideally we can fix the warnings here first.

[clang] Update analyzer python requirement versions

---

sycl/unittests/allowlist/DeviceIsAllowed.cpp

if there are absolutely no platforms, then just skip this test

[SYCL] fix for locale test 

---

libdevice/sanitizer/asan_rtl.cpp
libdevice/sanitizer/msan_rtl.cpp

early return may cause barrier function not work.

[DevSAN] Fix logic error in function to set private base

---

sycl/cts_exclude_filter/compfails

The issue was fixed with the recent llvm-spirv PD.

[sycl-cts] Enable test_bit_cast

---

devops/dependencies.json

[GHA] Uplift Linux GPU RT version to 25.18.33578.6

---

unified-runtime/source/adapters/offload/common.hpp
unified-runtime/source/adapters/offload/device.cpp
unified-runtime/source/adapters/offload/enqueue.cpp
unified-runtime/source/adapters/offload/event.cpp
unified-runtime/source/adapters/offload/memory.cpp
unified-runtime/source/adapters/offload/platform.cpp
unified-runtime/source/adapters/offload/program.cpp
unified-runtime/source/adapters/offload/queue.cpp
unified-runtime/source/adapters/offload/ur2offload.hpp
unified-runtime/source/adapters/offload/usm.cpp

Add a macro for calling Offload API functions and returning a UR error on failure. Some Offload calls were unchecked before.

[UR][Offload] Add OL_RETURN_ON_ERR macro

---

devops/dependencies.json

I'd rather do this than update all the doc.

[CI][NFC] Restore and update Windows dependencies.json driver entry

---

llvm/lib/Transforms/Instrumentation/MemorySanitizer.cpp

Fix some mistakes in pulldown conflict resolution.

[DeviceMemorySanitizer] Fix pulldown conflict resolution error

---

.github/workflows/sycl-nightly-benchmarking.yml

This PR allows changes in https://github.com/intel/llvm/pull/19280 to be tested. This PR will be open for merging if changes in #19280 are approved.

[CI][NFC] Add placeholder workflow file for testing PR #19280

---

sycl/test-e2e/bindless_images/array/read_write_1d_subregion.cpp
sycl/test-e2e/bindless_images/read_write_1D_subregion.cpp

Releases previously unreleased handles.

[BINDLESS][E2E] Release unreleased handles in bindless tests

---

.github/workflows/sycl-linux-precommit.yml
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_unroll.cpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_unroll_init.cpp

Matrix team says this has no value and it just misses XPASSes because they are converted to UNSUPPORTED.

[CI] Don't test on OCL for igc-dev

---

sycl/test-e2e/bindless_images/read_write_2D_subregion.cpp

Fixing one case missed in https://github.com/intel/llvm/pull/19421

[BINDLESS][E2E] Release unreleased handles in bindless test pt 2

---

devops/dependencies-igc-dev.json

[GHA] Uplift Linux IGC Dev RT version to igc-dev-cee4ac4

---

devops/dependencies-igc-dev.json

[GHA] Uplift Linux IGC Dev RT version to igc-dev-554cabd

---

unified-runtime/test/conformance/enqueue/urEnqueueEventsWaitMultiDevice.cpp
unified-runtime/test/conformance/enqueue/urEnqueueKernelLaunchAndMemcpyInOrder.cpp
unified-runtime/test/conformance/enqueue/urEnqueueMemBufferFill.cpp
unified-runtime/test/conformance/enqueue/urEnqueueUSMFill.cpp
unified-runtime/test/conformance/exp_command_buffer/regression/usm_copy.cpp
unified-runtime/test/conformance/exp_command_buffer/update/kernel_handle_update.cpp
unified-runtime/test/conformance/exp_usm_context_memcpy/urUSMContextMemcpyExp.cpp

Ref: https://github.com/intel/llvm/issues/19604 https://github.com/intel/llvm/issues/19605 https://github.com/intel/llvm/issues/19607

[UR][CTS][L0] disable failing tests after compute-runtime update

---

devops/dependencies-igc-dev.json

[GHA] Uplift Linux IGC Dev RT version to igc-dev-e22e2a8

---

devops/scripts/benchmarks/benches/compute.py

Make SubmitGraph benchmarks groupings more fine-grained.
Refactor displayed names of these benchmarks to follow the convention of SubmitKernel benchmarks.
Examples:

[Benchmarks] Split SubmitGraph grouping

---

devops/scripts/benchmarks/benches/compute.py

~Requires #19652 to be merged first. Please, review the latest commit.~

[Benchmarks] Add SubmitGraph with events scenarios

---

sycl/doc/extensions/experimental/sycl_ext_oneapi_device_image_backend_content.asciidoc

Fix a few syntax errors in the example for this extension.

[SYCL][Doc] Fix specification example

---

clang/test/Driver/sycl-offload-static-lib-2-old-model.cpp

The image output option has been updated, update test to match.

Update test to match expected fatbinary option

---

devops/dependencies-igc-dev.json

[GHA] Uplift Linux IGC Dev RT version to igc-dev-82a03f3

---

devops/dependencies-igc-dev.json

[GHA] Uplift Linux IGC Dev RT version to igc-dev-64d0420

---

devops/dependencies-igc-dev.json

[GHA] Uplift Linux IGC Dev RT version to igc-dev-3c9eb3b

---

unified-runtime/source/common/CMakeLists.txt

Revert "[UR] Bump UMF to v1.1.0-dev2"

---

unified-runtime/source/adapters/level_zero/CMakeLists.txt

Follow-up from https://github.com/intel/llvm/pull/19876

[UR][L0] Fix typo in CMake install target

---

sycl/cts_exclude_filter/WIN_L0_GPU

https://github.com/intel/llvm/issues/19625

[sycl-cts] Disable test_spec_constants on Win&L0

---

devops/dependencies-igc-dev.json
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_arg_dim.cpp
sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_runtime_dim.cpp

[GHA] Uplift Linux IGC Dev RT version to igc-dev-788001e

---

sycl/test-e2e/IntermediateLib/multi_lib_app.cpp

Test is failing in CI: https://github.com/intel/llvm/issues/20023

[SYCL][E2E] Disable multi_lib_app.cpp on Windows

---

sycl/test-e2e/Experimental/clock.cpp

https://github.com/intel/llvm/issues/20146

[SYCL][E2E] Disable clock.cpp on spirv-be

---

libclc/CMakeLists.txt

Align dependency handling with 76bebb5be9da

[NFC][libspirv][CMake] Let libclc depends on libspirv-builtins

---

unified-runtime/source/adapters/offload/queue.hpp

Whoops! Looks like we were checking the flags wrong

[UR][Offload] Don't default to out of order queues

---

devops/scripts/benchmarks/html/scripts.js

Fixes clicking on data points in the dashboard tracing to a wrong url.

[Benchmarks] Fix GitHub commit link in chart clicks

---

clang/tools/clang-linker-wrapper/ClangLinkerWrapper.cpp
llvm/include/llvm/Object/SYCLBIN.h
llvm/lib/Object/SYCLBIN.cpp
llvm/unittests/Object/SYCLBINTest.cpp

getSYCLBINByteSite --> getSYCLBINByteSize

[NFC][SYCL][SYCLBIN] Fix typo in getSYCLBINByteSize method name
