intel/llvm

- .github/workflows/sycl_precommit.yml
- devops/test_configs.json
SYCL End-to-End test spend most of the time on compilation. Running them against two targets with a single compilation can reduced the load generated in half.
> [SYCL][DevOps] Switch GEN9 Linux pre-commit to fused L0/OCL task

- sycl/plugins/unified_runtime/ur/adapters/level_zero/ur_level_zero.hpp
Account for the various device ids used for PVC GPUs.
> [SYCL] [L0] Correct the device id check for PVC.

- llvm-spirv/test/builtin-functions.ll
- llvm-spirv/test/transcoding/spirv-target-types-buffer.ll
the builtin-functions one is a real issue but it was introduced before just exposed by this test, i can reproduce it in current sycl branch HEAD, i will make an internal tracker
second one is expected because of entry point wrapper thing reverted here
@kchusha should be safe to pull this now
> [SYCL][Pulldown] Fix llvm-spirv pulldown

- llvm/lib/SYCLLowerIR/CompileTimePropertiesPass.cpp
The main point of this function is the Attr, but Func was the first arg.
Closes: https://github.com/intel/llvm/issues/9370
> [SYCL][NFC] Reorder arguments of attributeToExecModeMetadata in CompileTimePropertiesPass

- sycl/test/esimd/ctor_codegen_opaque.cpp
- sycl/test/esimd/slm_init_specconst_size.cpp
- sycl/test/esimd/sycl_half_basic_ops.cpp
- sycl/test/esimd/sycl_half_basic_ops_opaque.cpp
- sycl/test/esimd/sycl_half_math_ops.cpp
- sycl/test/esimd/sycl_half_math_ops_opaque.cpp
The IR is different so the tests failed. Just make the old tests use typed pointers and add new tests for opaque pointers. We can remove the typed pointer tests at some point in the future.
There's still one ESIMD failure, I'm working on that seperately.
> [SYCL][ESIMD][LIT] Fix opaque pointer failures

- sycl/test-e2e/Basic/library_loading.cpp
- sycl/test-e2e/Basic/query_emulate_subdevice.cpp
- sycl/test-e2e/Config/allowlist.cpp
- sycl/test-e2e/DeprecatedFeatures/deprecated_sycl_device_filter.cpp
- sycl/test-e2e/OneapiDeviceSelector/backendonly_error.cpp
- sycl/test-e2e/OneapiDeviceSelector/case_sensitivity.cpp
- sycl/test-e2e/OneapiDeviceSelector/cuda_top.cpp
- sycl/test-e2e/OneapiDeviceSelector/illegal_BE_error.cpp
- sycl/test-e2e/OneapiDeviceSelector/level_zero_top.cpp
- sycl/test-e2e/OneapiDeviceSelector/no_duplicate_devices.cpp
- sycl/test-e2e/OneapiDeviceSelector/sub-devices.cpp
- sycl/test-e2e/Regression/device_num.cpp
These substitution/expansion must be used in order to run the test through run_launcher when one is specified in llvm-lit parameters.
> [SYCL][Test E2E] Fix tests not using %{run*}

- polygeist/include/mlir/Dialect/Polygeist/IR/PolygeistTypes.td
- polygeist/lib/Conversion/PolygeistToLLVM/PolygeistToLLVM.cpp
- polygeist/lib/Dialect/Polygeist/IR/PolygeistTypes.cpp
- polygeist/test/polygeist-opt/polygeist-types-invalid.mlir
- polygeist/test/polygeist-opt/polygeist-types-to-llvm.mlir
`isOpaque` indicate if a struct type is an intentionally-opaque identified struct, such a struct cannot have its body set. 
To represent all `llvm.struct` as `polygeist.struct`, we need to also allow opaque struct type.
> [SYCL-MLIR] Add `isOpaque` in `polygeist.struct`

- sycl/test-e2e/ESIMD/regression/copyto_char_test.cpp
The failure is tracked in the internal bug tracking system.
> [SYCL] Disable ESIMD/regression/copyto_char_test.cpp on failing configuration

- sycl/test-e2e/ESIMD/regression/variable_gather_mask.cpp
The failure is tracked in the internal bug tracking system.
> [SYCL] Disable ESIMD/regression/variable_gather_mask.cpp on failing configuration

- clang/include/clang/Driver/Options.td
- clang/include/clang/Driver/ToolChain.h
- clang/lib/Driver/Driver.cpp
- clang/lib/Driver/ToolChain.cpp
- clang/lib/Driver/ToolChains/Clang.cpp
- clang/lib/Driver/ToolChains/Clang.h
- clang/test/Driver/sycl-mlir.cpp
- polygeist/tools/cgeist/Lib/clang-mlir.cc
- polygeist/tools/cgeist/driver.cc
Modify driver behavior so that, if this option is found, the host code will always be compiled and raised to MLIR. Then, cgeist will receive this MLIR module as an argument via the `-sycl-use-host-module` option.
When this option is passed, two SYCL compilations are needed: one to generate the stub file to perform host compilation and another one to perform the actual device compilation (which will receive the host code as an input in MLIR format). The former one will only produce an LLVM module, so it will not be used to generate the final output.
For the device compilation to receive the host module as an input, we need to:
- Drop the regular compilation from the pipeline and add a new one which will receive both the regular input and the raised host module. This will be generated using …
> [SYCL-MLIR][driver] Add `-fsycl-raise-host` option

- sycl/include/sycl/ext/intel/esimd/memory.hpp
- sycl/test-e2e/ESIMD/accessor_gather_scatter_stateless_64.cpp
I manually ran the test on PVC.
After this change, I'll add support for more APIs per-PR.
> [SYCL][ESIMD] Support 64-bit offsets for stateless accessor gather/scatter

- sycl/test-e2e/ESIMD/regression/dgetrf.cpp
Failure is under investigation internally.
> [SYCL] Disable ESIMD/regression/dgetrf.cpp on gpu-intel-pvc

- sycl/test-e2e/AtomicRef/atomic_memory_order_seq_cst.cpp
We have an internal bug report to track investigation.
> [SYCL] Disable AtomicRef/atomic_memory_order_seq_cst.cpp on PVC

- sycl/test-e2e/XPTI/kernel/content.cpp
Reduction strategy is HW-dependent and as such number of kernel arguments vary between devices.
> [SYCL] Adjust XPTI/kernel/content.cpp to pass on more HW

- clang/lib/Driver/ToolChains/Clang.cpp
- clang/test/Driver/sycl-spirv-obj.cpp
We need to pass both of these options for correct reverse translation of SPIR-V fat objects. It should have no effect otherwise.
> [SYCL][Driver] Pass two more options to spirv-to-ir-wrapper for SPIR-V fat objects

- sycl/test-e2e/Plugin/level_zero_imm_cmdlist_per_thread.cpp
Make it pass on devices that have both compute and copy engines.
> [SYCL] Fix Plugin/level_zero_imm_cmdlist_per_thread.cpp test

- polygeist/tools/cgeist/Lib/CGCall.cc
- polygeist/tools/cgeist/Lib/clang-mlir.cc
- polygeist/tools/cgeist/Lib/clang-mlir.h
- polygeist/tools/cgeist/Test/Verification/constructors.cpp
Handle `CXXInheritedCtorInitExpr` expressions by simply calling the base constructor forwarding the input arguments to the base class constructor.
> [SYCL-MLIR][CodeGen] Handle inherited constructors

- polygeist/include/mlir/Dialect/Polygeist/Transforms/Passes.h
- polygeist/include/mlir/Dialect/Polygeist/Transforms/Passes.td
- polygeist/lib/Dialect/Polygeist/Transforms/CMakeLists.txt
- polygeist/lib/Dialect/Polygeist/Transforms/LoopInternalization.cpp
- polygeist/lib/Dialect/Polygeist/Transforms/SYCLInternalization.cpp
- polygeist/test/polygeist-opt/sycl/loop_internalization.mlir
This new pass is only partially done. In this PR, only the pass infrastructure and loop tiling are done.
It still needs to 1. query the minimum local memory size of the device ([section 4.6.4.2](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_device_information_descriptors)), 2. calculate the beneficial tile sizes, 3. decide which memory accesses are beneficial to promote, 4. promote loop accesses to local memory.
> [SYCL-MLIR] Add `LoopInternalization` pass (part 1)

- sycl/plugins/opencl/pi_opencl.cpp
This patch fixes stack smashing happened during querying of available aspects list, and also during calling `sycl-ls --verbose`. The stack smashing happened due to different sizes of `cl_bool` and `bool` types. Patch changes `cl_bool` to `bool` because there is no need in `cl_bool` in this part of the code, and also adds a (probably unnecessary) diagnostic which returns `PI_ERROR_INVALID_VALUE` - the same diagnostic is a part of OpenCL spec for `clGetDeviceInfo` function.
> [SYCL] Fix stack smashing due to different sizes of cl_bool and bool

- .github/workflows/sycl_precommit.yml
- devops/test_configs.json
- sycl/test-e2e/Config/allowlist.cpp
It would increase its duration by several minutes while eliminating 20+ minutes task completely.
> [SYCL][DevOps]  Fuse OCL CPU testing into GEN9 Linux task

- sycl/test-e2e/DiscardEvents/invalid_event.cpp
Same hang as in https://github.com/intel/llvm/issues/7330.
> [SYCL] Disable test-e2e/DiscardEvents/invalid_event.cpp on opencl:gpu

- sycl/test/esimd/esimd_verify.cpp
The updated test gets explicit options for stateless/stateful mode and gets basic check verifying that in force-stateless mode some of verifier checks still work.
> [ESIMD][LIT] Update LIT test for ESIMDVerifierPass

- sycl/test-e2e/InvokeSimd/Feature/ImplicitSubgroup/scale_double.cpp
- sycl/test-e2e/InvokeSimd/Feature/scale.cpp
- sycl/test-e2e/InvokeSimd/Feature/scale_double.cpp
We do a check with `dev.has(aspect::fp64)`, but that's a runtime check.
With InvokeSimd, we need to compile with `-fno-sycl-device-code-split-esimd` which disables any module splitting.
Usually modules are split into images based on optional device features, such as fp64, but because of the above option we only end up with a single device image that contains both fp64 and non-fp64 code because of the runtime check.
Since there can only be one image, we can't use fp64 at all on non-fp64 hardware, so a runtime check won't work.
Split the test into a non-fp64 and fp64-only version.
The above is what we do for other tests that test double conditionally on non-fp64 hardware, such as invoke_simd_conv_double.cpp
> [SYCL][InvokeSimd][E2E] Fix scale tests on hardware that doesn't support fp64

- clang/include/clang/Driver/Options.td
- clang/lib/Driver/ToolChains/Clang.cpp
- clang/lib/Driver/ToolChains/SYCL.h
- clang/test/Driver/sycl-spirv-opt.cpp
This is a hidden option and is not intended for use by end users. It has value for local testing and validation of the generated SPIR-V.
Note this is only current for forward translation. I can extend this in the future if we have a use case for reverse translation (spirv-to-ir-wrapper).
> [SYCL][Driver] Add hidden option to specify llvm-spirv arguments

- polygeist/tools/cgeist/Lib/CGCall.cc
- polygeist/tools/cgeist/Lib/CGDecl.cc
- polygeist/tools/cgeist/Lib/CGExpr.cc
- polygeist/tools/cgeist/Lib/clang-mlir.cc
- polygeist/tools/cgeist/Lib/clang-mlir.h
- polygeist/tools/cgeist/Lib/utils.cc
- polygeist/tools/cgeist/Lib/utils.h
Before this PR, member functions in `MLIRScanner` use `mlirclang::getFuncContext` or `mlirclang::getInputContext` to get the `InsertionContext`. They relies on a valid associate `Function` or a linked insertion block of the associate builder respectively, both of them are not always true, for example when `MLIRScanner` is used to create globals. 
In this PR, we construct `MLIRScanner` with `InsertionContext`, so we don't need to get it indirectly. 
Note: `FunctionContext` is renamed to `InsertionContext`.
There are 16 e2e tests affected by this problem. With this PR, they are failing somewhere else.
> [SYCL-MLIR] Construct `MLIRScanner` with `InsertionContext`

- llvm/lib/SYCLLowerIR/CMakeLists.txt
Necessary to fix shared libs build.
> [SYCL] Add ipo component into deps because SYCLLowerIR uses AlwaysInliner

- .gitattributes
This it to tell git merge.ours driver to always use sycl-mlir version.
It should be a nop op for default merge strategy.
To use merge.ours driver, you can set it in config once.
git config --global merge.ours.driver true
> [SYCL-MLIR] Always use ours when merging from other branches for CODEOWNERS

- sycl/test-e2e/Plugin/level_zero_ext_intel_cslice.cpp
- sycl/test-e2e/Plugin/level_zero_ext_intel_queue_index.cpp
Account for fewer command lists created when immediate command lists are reused across queues.
> [SYCL] [L0] Test adjustments for immediate command list recycling.

- llvm/lib/SYCLLowerIR/SYCLPropagateAspectsUsage.cpp
- llvm/test/SYCLLowerIR/PropagateAspectsUsage/gep-prop.ll
- sycl/test/extensions/properties/properties_kernel_device_has_warning.cpp
- sycl/test/warnings/aspect_perserve_srcloc.cpp
When opaque pointers are enabled, the aspect propagation pass may not currently detect the use of types in calls to functions where the type is passed as an opaque pointer. In these cases, the type can usually be detected through the source type in GEP instructions inside the corresponding functions. A common example of this is the constructors for classes marked as using aspects.
This commit fixes the detection of usage inside functions using opaque pointer arguments by extracting information about the source type from GEP instructions inside the functions.
> [SYCL] Fix detection of opaque pointer aspect usage

- sycl/test-e2e/xfail_tests.txt
Missed from https://github.com/intel/llvm/pull/9598.
> [SYCL-MLIR] Update xfail list after rebase

- sycl/test-e2e/ESIMD/regression/Inputs/dgetrf.hpp
- sycl/test-e2e/ESIMD/regression/dgetrf.cpp
Private global in the test collides with kernel arguments in GRF.
The offset must be a multiple of the register size.
> [SYCL][ESIMD] Fix a test with a esimd private global pinned to GRF

- sycl/plugins/level_zero/pi_level_zero.cpp
Check against the case that `piPlatformsGet`, where `ZeCallCount` is initialized, wasn't ever called.
> [SYCL][L0] Check if ZE call count had started

- sycl/plugins/opencl/pi_opencl.cpp
clEnqueueMemsetINTEL originally showed up in an early revision of the USM extension for OpenCL and was later replaced with clEnqueueMemFillINTEL.
> [SYCL] Replace usage of outdated memset OpenCL API

- .github/CODEOWNERS
clang-offload-bundler functionality was taken out from tool into "library" here: https://reviews.llvm.org/D129873.
This commit adjusts CODEOWNERS file so that DPC++ tools team could track changes.
> Adjust CODEOWNERS for OffloadBundler.{h,cpp} files

- mlir/lib/Conversion/SPIRVToLLVM/SPIRVToLLVM.cpp
- mlir/test/Conversion/SPIRVToLLVM/barrier-op-to-llvm.mlir
- polygeist/include/mlir/Dialect/Polygeist/Transforms/Passes.td
- polygeist/lib/Dialect/Polygeist/Transforms/CMakeLists.txt
- polygeist/lib/Dialect/Polygeist/Transforms/LoopInternalization.cpp
- polygeist/test/polygeist-opt/sycl/loop_internalization.mlir
This PR only adds a local barrier before the tiled loops, as a preparation for promoting loop memory accesses to shared local memory.
> [SYCL-MLIR][LoopInternalization] Create a local barrier before the tiled loops

- sycl/source/detail/builtins_integer.cpp
- sycl/test/regression/abs_diff_host.cpp
The existing implementation of host-side abs_diff relies on undefined behavior when the signed operations overflow. This can mean that using different compilers to build DPC++ may break the implementation. This commit changes the implementation to avoid this undefined behavior.
> [SYCL] Remove undefined behavior in host-side abs_diff

- sycl/test-e2e/lit.site.cfg.py.in
sycl_devices is used instead now, including our public and internal CI.
> [SYCL][Test E2E] Remove sycl_be/target_devices params support

- sycl/plugins/unified_runtime/ur/adapters/level_zero/ur_level_zero_device.cpp
- sycl/plugins/unified_runtime/ur/adapters/level_zero/ur_level_zero_usm.cpp
pi_bool is uint32_t and ur_bool_t is uint8_t, so to make sure correct functionality is maintained, use uint32_t as replacement for pi_bool, instead of ur_bool_t.
> [SYCL][UR][L0] Fix casting in UR for boolean

- sycl/include/sycl/accessor.hpp
- sycl/test-e2e/Basic/accessor/accessor.cpp
* Modifies accessor::ConcreteASPtrType to be `const` for `readonly` accessor to fix failing case where copying accessor<const T>::MData does not compile when src type is `const` and dest is `non-const`.
* Add test
> [SYCL] Modifies accessor::ConcreteASPtrType to be `const` for `readonly` accessor

- sycl/test/check_device_code/device_has.cpp
check_has.cpp strictly depends on order of sycl_declared_aspects and srcloc metadata which is not guaranteed by compiler.
This test aims to check IR for device_has(aspect..., we can keep sycl_declared_aspects and remove srcloc to avoid the dependency.
> [SYCL][Test] Remove check_has.cpp dependency on metadata order

- mlir-sycl/lib/Conversion/SYCLToLLVM/DPCPP.cpp
- mlir-sycl/test/Conversion/SYCLToLLVM/check-collision-typed-pointer.mlir
- mlir-sycl/test/Conversion/SYCLToLLVM/check-collision.mlir
The routine lowering sycl arrays doesn't handle collisions and assumed that, if a type is found and initialized, then it is the one expected.
Note 1: I kept naming of structs as they are even if the numbering is unrelated to dimensions, but it makes sense for reading IMO.
Note 2: I think there is still an issue with importing the host module in the cgiest generated as I doubt it cares about collisions. But that doesn't seem to impact our testing, so I'll look into it in another patch.
> [SYCL-MLIR] Prevent name collision for sycl arrays

- mlir/include/mlir/Dialect/LLVMIR/LLVMIntrinsicOps.td
- mlir/test/Target/LLVMIR/Import/intrinsic.ll
- mlir/test/Target/LLVMIR/llvmir-intrinsics.mlir
Add support for multiple intrinsics to the LLVM dialect.
These intrinsics are present in host LLVM IR, so for full host raising support, they need to be added to the LLVM dialect. 
The following intrinsics are added in this PR:
* `llvm.rint`, `llvm.nearbyint`, `llvm.lround`, `llvm.llround`, `llvm.lrint`, `llvm.llrint`
* `llvm.threadlocal.address`
> [SYCL-MLIR] Add intrinsics to LLVM dialect

- mlir/include/mlir/Dialect/LLVMIR/LLVMOpBase.td
- mlir/include/mlir/Dialect/LLVMIR/LLVMTypes.td
- mlir/lib/Dialect/LLVMIR/IR/LLVMDialect.cpp
- mlir/lib/Dialect/LLVMIR/IR/LLVMTypeSyntax.cpp
- mlir/lib/Dialect/LLVMIR/IR/LLVMTypes.cpp
- mlir/lib/Target/LLVMIR/ModuleImport.cpp
- mlir/lib/Target/LLVMIR/ModuleTranslation.cpp
- mlir/lib/Target/LLVMIR/TypeFromLLVM.cpp
- mlir/lib/Target/LLVMIR/TypeToLLVM.cpp
- mlir/test/Dialect/LLVMIR/global.mlir
- mlir/test/Dialect/LLVMIR/invalid.mlir
- mlir/test/Dialect/LLVMIR/types-invalid.mlir
- mlir/test/Dialect/LLVMIR/types.mlir
- mlir/test/Target/LLVMIR/Import/target-ext-type.ll
- mlir/test/Target/LLVMIR/llvmir-types.mlir
- mlir/test/Target/LLVMIR/target-ext-type.mlir
Add support for the `llvm::TargetExtType` to the MLIR LLVM dialect. 
Target extension types are used to represent target-specific types, which are opaque to the compiler, when using opaque pointers. 
They are relevant for us, as they are used to represent SPIR-V types such as images.
Also enforces some of the constraints defined for target extension types by the LLVM language reference manual, e.g., only `zeroinitializer` constants.
> [SYCL-MLIR] Add target extension type

- clang/lib/Driver/ToolChains/Clang.cpp
- clang/test/Driver/sycl-mlir.cpp
The experimental debug assignment tracking feature was recently enabled by default. 
When the feature is used, `llvm.dbg.assign` intrinsics are inserted. The `llvm.dbg.assign` intrinsic is currently not understood by `mlir-translate`. Therefore, deactivate the experimental debug assignment tracking in the Clang driver when the host module is intended to be raised to MLIR through `-fsycl-raise-host`.
> [SYCL-MLIR] Deactivate debug assignment tracking

- sycl/test-e2e/ESIMD/ext_math.cpp
- sycl/test-e2e/ESIMD/ext_math_fast.cpp
clang-cl driver does not understand -fno-fast-math and -fno-slp-vectorize. Usage of those options requires adding "/clang:" before the option.
> [ESIMD][LIT] Fix usage of -fno-fast-math and -fno-slp-vectorize with cl

- sycl/test/check_device_code/device_global_ptr_use.cpp
- sycl/test/check_device_code/usm_pointers.cpp
- sycl/test/extensions/bfloat16.cpp
This does not fix all of the lit tests that fail with opaque pointers enabled, but it does fix those where the test is looking for IR whose form has changed with opaque pointers enabled.
> [SYCL][OpaquePtrs] Convert some sycl tests to opaque pointers.

- sycl/source/kernel.cpp
We should retain the kernel only for opencl backend.
> [SYCL] Avoid unnecessary kernel retain

- .github/workflows/sycl_linux_build_and_test.yml
- .github/workflows/sycl_precommit.yml
I'm using https://github.com/dorny/paths-filter to implement it.
I decided to call it from `sycl_precommit.yml` so that we can potentially re-use its results between Linux/Windows tasks but that might have its own drawbacks. I don't see a possibility to just pass the result of the job between workflows (`sycl_precommit` -> `sycl_linux_build_and_test`) which means that for every value I have to thread it carefully via latter's inputs. That might complicate things in future if we'd want to run just the modified end-to-end tests instead of all of them. 
Another approach would be to run the job inside `sycl_linux_build_and_test` so that I'd have immediate access to its output from anywhere in the workflow.
> [SYCL][CI] Skip some checks depending on what files have changed

- sycl/CMakeLists.txt
For the host raising, we use `mlir-translate` to raise from LLVM IR to MLIR when the `-fsycl-raise-host` option is passed. 
Therefore, the CMake target `sycl-toolchain`/`sycl-compiler` must have a dependency on `mlir-translate` to make sure the latest version is available for the SYCL compilation flow.
> [SYCL-MLIR][NFC] Add dependency on mlir-translate

- .github/workflows/sycl_nightly.yml
- sycl/doc/developer/DockerBKMs.md
I plan to use it in post commit to merge two builds
[linux_default](https://github.com/intel/llvm/blob/ac8408c4761180835fb23ccd5183efd5c5c37d95/.github/workflows/sycl_post_commit.yml#L26-L38) and
[self_build](https://github.com/intel/llvm/blob/ac8408c4761180835fb23ccd5183efd5c5c37d95/.github/workflows/sycl_post_commit.yml#L39-L51) into one.
I can also imagine how we can use that in place of [HIP/CUDA image for E2E tests](https://github.com/intel/llvm/blob/24955697d9f08c0bc7e1f2b80182c7d967f53b70/.github/workflows/sycl_gen_test_matrix.yml#L10-L17) for PRs that only update E2E tests.
> [SYCL][CI] Create nightly container based on the "build" image

- polygeist/lib/Dialect/Polygeist/Transforms/LoopInternalization.cpp
- polygeist/test/polygeist-opt/sycl/loop_internalization.mlir
Tile changes the access order in a multi level loop nest. 
As the motivating test case is a single level loop nest, only optimize innermost loop in a perfect loop nest for the time being.
> [SYCL-MLIR][LoopInternalization] Only optimize innermost loop

- sycl/include/sycl/ext/intel/esimd/memory.hpp
- sycl/test/esimd/gather_scatter.cpp
This regressed in https://github.com/intel/llvm/commit/d04ebb03c1c891077974622c99027a72bad34b71 when we added a template arg. Since we have a template arg, we won't also call the constructor.
> [SYCL][ESIMD] Fix gather/scatter with accessors when passing scalar

- sycl/test-e2e/ESIMD/ext_math_ieee_sqrt_div.cpp
Similar to the other ext_math tests, this needs -fno-fast-math as well.
> [SYCL][ESIMD][E2E] Fix ext_math_ieee_sqrt_div on emulator

- sycl/test-e2e/ESIMD/api/functional/ctors/ctor_fill_core.cpp
- sycl/test-e2e/ESIMD/api/functional/ctors/ctor_fill_fp_extra.cpp
- sycl/test-e2e/ESIMD/api/replicate_smoke.cpp
- sycl/test-e2e/ESIMD/api/saturation_smoke.cpp
- sycl/test-e2e/ESIMD/mandelbrot/mandelbrot.cpp
- sycl/test-e2e/ESIMD/mandelbrot/mandelbrot_spec.cpp
- sycl/test-e2e/ESIMD/regression/dgetrf.cpp
- sycl/test-e2e/ESIMD/regression/math_const_fix_test.cpp
This PR is a work around for tests failing when compiled with icpx and succeeding when compiled with clang++. The root cause of that behavior is fast-math option that is enabled by default when using icpx and disabled by default when using clang++.  As a work around the affected tests will be compiled with no-fast-math option.
> [ESIMD][E2E] Temporarily disable -ffast-math option for 7 LIT tests

- .github/workflows/sycl_linux_build_and_test.yml
- devops/actions/e2e-tests/action.yml
- devops/actions/khronos_cts_test/action.yml
- devops/containers/ubuntu2204_preinstalled.Dockerfile
This was originally implemented in https://github.com/intel/llvm/pull/5678.
Start with Linux only for now. Benchmarking several compression utilities for time/size:
|         | Pack time | Upload time | Size   |
| ------- | --------- | ----------- | ------ |
| xz      | 5m 20s    | 1m 30s      | 350 MB |
| lz4     | 3s        | 3m 10s      | 660 MB |
| zstd -9 | 25s       | 2m 4s       | 467 MB |
The difference in size between xz/lz4 would result in 1m30s -> 3m increase in artifacts upload time so the pack time gain would be partially offset by that.
I don't see a way to get data about unpack from the CI, but locally on a different machine (and likely with a different build) I had this:
|      | Pack time | Unpack time |
| ---- | --------- | ----------- |
| xz   | 28m 30s   | 1m 13s …
> [SYCL][CI] Improve compression performance

- sycl/test-e2e/Plugin/level_zero_queue_priority.cpp
Explicitly enable a default context so that all queues use that context and immediate command list recycling happens as expected,
> [SYCL] [L0] Test adjustment for Windows

- polygeist/lib/Dialect/Polygeist/Transforms/Mem2Reg.cpp
- polygeist/test/polygeist-opt/llvmmem2reg.mlir
Polygeist's `mem2reg` pass currently allows allocations to be promoted even if load or store operations access a different type than allocated. This is problematic, as loads cannot be replaced by values of a different type. 
This change therefore further restricts which allocations can be promoted and only allows promotion if all loads/stores use the allocated type. This matches the implementation of LLVM's `mem2reg`.
> [SYCL-MLIR] Refine isPromotable for polygeist mem2reg

- .github/workflows/sycl_precommit.yml
This reverts commit 1db96de9f9b394fbed0b8953849108f255dd31d7.
CI seems to be stuck after this PR has been merged.
> Revert "[SYCL][CI] Cancel in-progress pre_commit job when PR is updated (#9706)"

- mlir/lib/Target/LLVMIR/ModuleTranslation.cpp
- polygeist/tools/cgeist/Lib/clang-mlir.cc
- polygeist/tools/cgeist/Test/Verification/sycl/reqd_work_group_size.cpp
- sycl/test-e2e/xfail_tests.txt
According to https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:kernel.attributes, `reqd_work_group_size` indicates that the kernel must be launched with the specified work-group size.
> [SYCL-MLIR] Add support of `sycl::reqd_work_group_size`

- polygeist/tools/cgeist/Lib/CGCall.cc
- sycl/test-e2e/xfail_tests.txt
Allow cast to the generic address space when calling a function with a `memref` argument. Address space casts to the generic address space are legal, so the cast can happen before the function call.
> [SYCL-MLIR] Allow cast to generic for memref call arguments

- libdevice/test/check_fp64.txt
> [SYCL][libdevice] Add libdevice lit test to check 'double' usage for fp32 spirv file

- clang/lib/Driver/ToolChains/SYCL.cpp
- clang/test/Driver/sycl-offload.c
When using -O0, we imply -cl-opt-disable for device.  This was incorrectly being implied when we were overriding with an optimization enabling option (-O0 -O2).  Fix the logic.
> [Driver][SYCL] Fix optimization option processing for device options

- .github/workflows/sycl_linux_build_and_test.yml
- .github/workflows/sycl_windows_build_and_test.yml
* Use LLVM_INSTALL_UTILS=ON on Windows
* Move clang-{format,tidy} installation into its own step
* Reorder lines to match between Linux/Windows
> [CI] Align installation steps between Linux/Windows

- sycl/plugins/unified_runtime/pi2ur.hpp
pi2ur was missing a conversion from UnifiedRuntime sampler info values to valid PI sampler Info values. This PR implements a valid conversion between these values.
> [SYCL][PI][UR] Fix pi2ur sampler return info

- sycl/plugins/cuda/pi_cuda.cpp
This PR fixes a performance regression wrt work-group size selection when only `sycl::range` is used.
The regression was reported in issue [#5627](https://github.com/intel/llvm/issues/5627).
We want the work-groups to be uniformly distributed but that could lead to non-optmially sized work-groups is the global work size is not an even number. Ideally, we want ensure that the work-group size is a power of two.
> [SYCL][CUDA] Add fix for local size calculation regression

- sycl/include/sycl/multi_ptr.hpp
This ctor has been previously removed, as it had conflict with existing ones.
Not having the ctor produces failures to compile some cts tests. An investigation is required.
> Adds explicit conversion of multi_ptr<T> to multi_ptr<const T>.

- clang/lib/Driver/ToolChains/Clang.cpp
- clang/test/Driver/sycl-nvptx-native-half-ty-opt.cpp
LLVM will now error out if builtins operating on half types are used without explicitly passing `-fnative-half-type` (see: https://reviews.llvm.org/D146715). PTX supports half types since [SM_53](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html?highlight=half%20precision#half-precision-floating-point-instructions).
> [SYCL] Add native half type flag for NVPTX >= SM_53

- sycl/doc/extensions/experimental/sycl_ext_oneapi_matrix/sycl_ext_oneapi_matrix.asciidoc
This PR documents the supported joint_matrix API parameters sets when using `ext_oneapi_cuda`, similar to the XMX, AMX tables added here: https://github.com/intel/llvm/pull/7964
This will allow us to point people who would like to use `joint_matrix` on a specific architecture to the extension document. E.g. https://github.com/intel/llvm/issues/8795
> [SYCL][CUDA][DOC] Added Tensor Cores supported param combinations table to joint_matrix extension doc

- sycl/source/detail/program_manager/program_manager.cpp
- sycl/test-e2e/SPVDumpUse/basic.cpp
- sycl/test-e2e/SPVDumpUse/kernel_bundle.cpp
That required to introduce an extra environment variable control - `SYCL_DUMP_IMAGES_PREFIX` to control location of the produced images.
> [SYCL] Add tests for SYCL_DUMP_IMAGES/SYCL_USER_KERNEL_SPV

- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLAttributes.h
- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLOps.h
- mlir-sycl/lib/Dialect/SYCL/IR/SYCLAttributes.cpp
- polygeist/include/mlir/Dialect/Polygeist/Transforms/Passes.td
- polygeist/include/mlir/Dialect/Polygeist/Utils/TransformUtils.h
- polygeist/lib/Dialect/Polygeist/Transforms/LoopInternalization.cpp
- polygeist/lib/Dialect/Polygeist/Utils/TransformUtils.cpp
- polygeist/test/polygeist-opt/sycl/loop_internalization.mlir
According to SYCL specification ([section 4.6.4.2](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_device_information_descriptors)), the minimum local memory size is 32KB. 
It first checks if any local memory is used, and calculate the remaining local memory available. 
If there are none, then the transformation is not performed.
Else, it creates a global with the minimum local memory size, or the require local memory if `reqd_work_group_size` is given.
> [SYCL-MLIR][LoopInternalization] Obtain local memory

- sycl-fusion/common/include/Kernel.h
This was causing build failures with some compilers.
> [SYCL][Fusion] Add missing header

- sycl/tools/abi_check.py
Patch fixes path concatenation issue. Script fails if the provided path has no trailing slash.
Should work OS independently. Manually tested on Linux.
> [SYCL] ABI check script improve path concatenation

- libdevice/cmake/modules/ImfSrcConcate.cmake
- libdevice/cmake/modules/SYCLLibdevice.cmake
- libdevice/imf/imf_fp64_dl.cpp
- libdevice/imf/imf_inline_fp32.cpp
- libdevice/imf/imf_inline_fp64.cpp
- libdevice/imf_wrapper.cpp
- llvm/tools/sycl-post-link/SYCLDeviceLibReqMask.cpp
- sycl/include/sycl/builtins.hpp
fabsf, fabs and llabs are required by deep learning frameworks, so we move fabsf and fabs to separate file imf_fp32/64_dl.cpp and add llabs to imf_fp32_dl.cpp as well.
> [SYCL][libdevice] Move fabs, fabs to imf_fp32/64_dl.cpp and add llabs

- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLAttributes.h
- mlir-sycl/lib/Dialect/SYCL/IR/SYCLAttributes.cpp
- polygeist/lib/Dialect/Polygeist/Transforms/LoopInternalization.cpp
- polygeist/test/polygeist-opt/sycl/loop_internalization.mlir
When `reqd_work_group_size` is not given, query work group size with `nd_item.get_local_range(dim)`.
Continue from https://github.com/intel/llvm/pull/9767.
> [SYCL-MLIR][LoopInternalization] Get local memory pointer without `reqd_work_group_size`

- llvm/lib/SYCLLowerIR/ESIMD/LowerESIMD.cpp
- sycl/include/CL/__spirv/spirv_ops.hpp
- sycl/include/sycl/ext/intel/esimd/detail/memory_intrin.hpp
- sycl/test/esimd/intrins_trans.cpp
We currently have a hack that relies on the type the Clang frontend generates for images, see [here](https://github.com/intel/llvm/blob/12dd0ad040ea61f1201fa9d82efd5079ce7dc6ca/sycl/include/sycl/ext/intel/esimd/detail/memory_intrin.hpp#L1171).
With opaque pointers, the Clang frontend generates image types as target extension types instead of pointers, so the hack fails.
The cleanest way to fix this would be to do the cast at reverse-translation time inside IGC, however the IGC team refused that solution.
Instead, punt the cast to inside the SPIR-V translator when converting to SPIR-V, where the type will be a pointer as well.
The `__spirv_ConvertPtrToU` function will be converted to `OpConvertPtrToU` inside the SPIR-V translator.
This is definitely still a hack, but I don't think it's …
> [SYCL][ESIMD] Use SPIR-V intrinsic to cast image object to int

- sycl/include/sycl/ext/intel/esimd/detail/simd_obj_impl.hpp
- sycl/include/sycl/ext/intel/esimd/memory.hpp
- sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp
- sycl/test-e2e/ESIMD/acc_gather_scatter_rgba_stateless_64.cpp
- sycl/test-e2e/ESIMD/accessor_stateless_64.cpp
- sycl/test-e2e/ESIMD/accessor_stateless_ctor_64.cpp
- sycl/test-e2e/ESIMD/lsc/lsc_block_load_store_stateless_64.cpp
- sycl/test-e2e/ESIMD/lsc/lsc_block_load_store_stateless_flag_64.cpp
- sycl/test-e2e/ESIMD/lsc/lsc_gather_scatter_stateless_64.cpp
This adds support for 64-bit offsets with accessors in stateless mode for the remaining APIs. Please let me know if I missed any.
Today, all of the APIs convert to 32-bit offsets with no error if passed a 64-bit offset, except for vector offset versions of `lsc_gather`, `lsc_scatter`, and `lsc_prefetch`. Do not error except in these three cases in order to preserve backward compatability.
I manually ran all of these tests on PVC and confirmed they pass with this change and fail without it.
In some cases, in stateful mode, the underlying intrinsic we call only supports 32-bit offests, so we need to convert.
> [SYCL][ESIMD] More support for 64-bit offsets with accessors in stateless mode

- sycl/include/sycl/multi_ptr.hpp
- sycl/test/multi_ptr/ctad.cpp
- sycl/test/regression/read_only_accessor_multi_ptr.cpp
This commit adjusts the multi_ptr deduction guides following the changes to the SYCL 2020 specification in
https://github.com/KhronosGroup/SYCL-Docs/pull/405.
Fixes https://github.com/intel/llvm/issues/9692.
> [SYCL] Adjust multi_ptr deduction guides

- sycl/test-e2e/lit.cfg.py
* If sycl-ls failed, the error message referenced an undefined variable
* If either the aspects or sub-group sizes were unable to be determined,
we were later referencing undefined set variables (`lit_config.error`
doesn't exit immediately).
* Error messages weren't printing stderr
CC @aelovikov-intel
> [SYCL][Test E2E] Fix errors in determining aspects/sg sizes

- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLOps.h
- mlir-sycl/include/mlir/Dialect/SYCL/Utils/Utils.h
- mlir-sycl/lib/Dialect/SYCL/CMakeLists.txt
- mlir-sycl/lib/Dialect/SYCL/Utils/CMakeLists.txt
- mlir-sycl/lib/Dialect/SYCL/Utils/Utils.cpp
- polygeist/lib/Dialect/Polygeist/Transforms/CMakeLists.txt
- polygeist/lib/Dialect/Polygeist/Transforms/LoopInternalization.cpp
As suggested in https://github.com/intel/llvm/pull/9785#discussion_r1223240361, created `Utils.[cpp|h]` for SYCL utilities.
> [SYCL-MLIR] Add SYCL `Utils.[cpp|h]`

- mlir-sycl/lib/Dialect/SYCL/IR/SYCLDialect.cpp
- mlir-sycl/test/Conversion/SYCLToLLVM/sycl-types-to-llvm.mlir
- mlir-sycl/test/Dialect/SYCL/types.mlir
- polygeist/tools/cgeist/Test/Verification/sycl/half.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/types.cpp
Drop trailing underscore from `sycl.half`, `sycl.kernel_handler` and `sycl.stream` type aliases.
> [SYCL-MLIR] Drop trailing underscore from simple unique aliases

- sycl/test/esimd/intrins_trans.cpp
- sycl/test/esimd/intrins_trans_opaque.cpp
Previously it was failing with opaque pointers.
Split the test into an opaque and non-opaque version.
There were no non-trivial changes required. It only required: 
1) Move `foo` to the bottom of the file since the that's where it is output with opaque pointers because we clone the function.
2) Change typed pointers to opaque pointers
3) Change image type pointer to target extension types
4) VC intrinsic name changes
> [SYCL][ESIMD][LIT] Add opaque pointer version of intrinsic_trans.cpp

- .github/workflows/sycl_gen_test_matrix.yml
It's generally good when the task doesn't leave any leftovers after itself. That becomes even more important when using self-hosted runners where leftovers aren't cleared by the container destruction (if one is used at all).
This is also kind of related to the root/actions/checkout/lint issue that (I believe with about 90% confidence) is not caused by the actions/checkout. Instead, it's the difference under which user the job is executed due to the containers usage.
In a nutshell, I'm trying to move our ubuntu-* tasks onto local runners and this PR is one of several change I'm making/made. I'm currently using the cuda runner because we can get by with tasks not cleaning after themselves as no real jobs are being scheduled there. However, I'm working on implementing all the necessary …
> [CI] Add cleanup for workflows/sycl_gen_test_matrix.yml

- sycl/test-e2e/AtomicRef/device_has_aspect_atomic64_level_zero.cpp
- sycl/test-e2e/Plugin/interop-level-zero-interop-task-mem-buffer.cpp
- sycl/test-e2e/Plugin/level_zero_uuid.cpp
device_has_aspect_atomic64_level_zero.cpp
interop-level-zero-interop-task-mem-buffer.cpp
level_zero_uuid.cpp
were missing to set L0 stype for a properties struct,
which would genereate an error in L0 validation layer when
enabled with ZE_DEBUG=6.
> [SYCL][Test E2E] Add stype to L0 structs

- clang/lib/Driver/ToolChains/SYCL.cpp
- clang/test/Driver/sycl-unsupported.cpp
We restrict a couple of options for SYCL device compilations and provide a warning we are doing so.  This was not working completely on Windows as we were emitting the warning, but continuing to push the options to the device compilation.  The derived argument list that is used for the device compilation is where we filter these options out.  Due to a mismanage of only manipulating the argument list when we are creating a new one, we missed this capability with Windows.
> [Driver][SYCL] Improve option restriction for device with Windows

- sycl/include/sycl/handler.hpp
- sycl/test/basic_tests/reduction/reduction_range_deduction.cpp
Currently `parallel_for` taking reduction variables take the dimensionality as a template argument. This means the range deduction guides cannot be used. This commit amends this by splitting them into separate function definitions per valid dimensionality.
This adheres to [4.9.4.2.2. parallel_for invoke](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_parallel_for_invoke):
> The parallel_for overload without an offset can be called with either a number or a braced-init-list with 1-3 elements. In that case the following calls are equivalent:
> - parallel_for(N, some_kernel) has same effect as parallel_for(range<1>(N), some_kernel)
> - parallel_for({N}, some_kernel) has same effect as parallel_for(range<1>(N), some_kernel)
> - parallel_for({N1, N2}, some_kernel) has …
> [SYCL][Reduction] Fix range deductions in reduction parallel_for

- sycl/include/sycl/handler.hpp
`cgh.fill(...)` was failing when `T` is a `sycl::vec` type, since `sycl::vec` types have no specialization for `std::is_trivially_copyable`. Since `device_copyable` is a sycl superset of trivially copyable we should use this instead in sycl headers.
I can add a test to check that `cgh.fill` works for vec types if necessary. Let me know if I should do this.
There are some other occurrences of `std::is_trivially_copyable` in the sycl headers. Let me know if I should replace more incidences.
> [SYCL] Change trivially_copyable to device_copyable

- sycl/plugins/unified_runtime/pi2ur.hpp
Also fix:
* Uninitialized stype values in UR queries
* Missing PI_KERNEL_INFO_NUM_REGS mapping
> [SYCL] Fix pi2ur conversion of bool info queries

- sycl/include/sycl/ext/intel/esimd/memory.hpp
- sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp
These don't do anything since the offsets are already 32-bit. The `convert` function does nothing if source and dest type are equal.
> [SYCL][ESIMD][NFC] Remove redundant 32-bit conversions

- mlir-sycl/lib/Dialect/SYCL/IR/SYCLDialect.cpp
- mlir-sycl/lib/Dialect/SYCL/IR/SYCLTypes.cpp
- mlir-sycl/test/Conversion/SYCLToLLVM/sycl-types-to-llvm.mlir
- mlir-sycl/test/Dialect/SYCL/invalid.mlir
- mlir-sycl/test/Dialect/SYCL/types.mlir
- polygeist/tools/cgeist/Test/Verification/sycl/half.cpp
- sycl/test-e2e/xfail_tests.txt
Allow usage of this type and performing operations between these vectors.
Conversion of this kind of vectors is not supported yet due to lack of codegen support.
> [SYCL-MLIR] Allow `sycl.half` as data type in `sycl.vec`

- sycl/test-e2e/Basic/handler/handler_mem_op.cpp
KhronosGroup/SYCL-Docs#425 clarifies that the source type for the `copy` must be device copyable. Remove the copy from `const void *` test case since it fails this assertion.
> [SYCL] Remove invalid `copy` test case

- polygeist/include/mlir/Dialect/Polygeist/Transforms/Passes.td
- polygeist/lib/Dialect/Polygeist/Transforms/LoopInternalization.cpp
As `LoopInternalization` only operate on `gpuModule`, change the pass to a `gpuModule` pass.
> [SYCL-MLIR][LoopInternalization] Change to `gpuModule` pass

- .github/workflows/sycl_precommit.yml
- devops/actions/clang-format/action.yml
Github's allocation of default ubuntu-* runners isn't reliably stable,
so keep moving tasks to self hosted runners. We don't use the cuda runner 
currently, so assign those to it for the time being. Later we should be 
able to extend those utility tasks to run on generic `Linux` class of 
self-hosted runners.
> [CI] Move lint job to self-hosted runner

- devops/scripts/install_build_tools.sh
We decided to use "zstd" instead.
> [CI] Don't install lz4

- .github/workflows/sycl_nightly.yml
That is needed so that we could use the resulting image to test PRs that only touch SYCL End-to-End tests
> [CI] Enable HIP/CUDA/ESIMD plugins in nightly build

- polygeist/include/mlir/Dialect/Polygeist/Analysis/MemoryAccessAnalysis.h
- polygeist/include/mlir/Dialect/Polygeist/Analysis/ReachingDefinitionAnalysis.h
- polygeist/include/mlir/Dialect/Polygeist/Transforms/Passes.td
- polygeist/lib/Dialect/Polygeist/Analysis/MemoryAccessAnalysis.cpp
- polygeist/lib/Dialect/Polygeist/Analysis/ReachingDefinitionAnalysis.cpp
- polygeist/lib/Dialect/Polygeist/Transforms/LoopInternalization.cpp
- polygeist/test/polygeist-opt/sycl/loop_internalization.mlir
This PR does loop internalization code generation for SCF loops.
The idea of the codegen is as follows:
Original code:
```
size_t i = item.get_global_id(0);
for (size_t k = 0; k < N; k++) {
B[i] += A[k];
}
```
Optimized code:
```
size_t i = item.get_global_id(0);
size_t x = item.get_local_id(0);
size_t wg_size = item.get_local_range(0);
auto &A_tile =
*ext::oneapi::group_local_memory<float[wg_size]>(item.get_group());
for (size_t k = 0; k < T; k+=wg_size) {
A_tile[x] = A[x+k];
group_barrier(item.get_group());
for (size_t t = k; t < k + wg_size; t++)
B[i] += A_tile[t-k];
group_barrier(item.get_group());
}
```
> [SYCL-MLIR][LoopInternalization] Transformation code generation (part 2)

- .github/CODEOWNERS
This commit changes the code-owners of the sycl/docs/design section from @intel/dpcpp-specification-reviewers to intel/llvm-reviewers-runtime. With this, the intel/llvm-reviewers-runtime would be responsible for either reviewing the design changes or assign the appropriate teams to make a design review.
> [SYCL][CODEOWNERS] Make intel/llvm-reviewers-runtime design docs codeowners

- sycl/include/std/experimental/simd.hpp
- sycl/include/sycl/ext/intel/esimd/detail/simd_mask_impl.hpp
- sycl/include/sycl/ext/oneapi/experimental/detail/invoke_simd_types.hpp
- sycl/include/sycl/ext/oneapi/experimental/invoke_simd.hpp
- sycl/test-e2e/InvokeSimd/Spec/simd_mask_merge.cpp
Users of `invoke_simd` need to use `std::experimental::simd_mask` for masks as per the spec, but once they enter ESIMD code they will likely want to use the ESIMD classes. Provide an implicit conversion from  `std::experimental::simd_mask` to `esimd::simd_mask`
Without this change, you need to use a manual loop, as all you can do is access `std::experimental::simd_mask` element-by-element.
> [SYCL][ESIMD] Allow implicit conversion from std::experimental::simd_mask to ESIMD::simd_mask

- sycl/test-e2e/KernelAndProgram/spec_constants_after_link.cpp
This test uses an interop API to create a kernel.
So, ZE_DEBUG should be disabled.
> [SYCL] Disable ZE_DEBUG test for interop

- sycl/plugins/unified_runtime/ur/adapters/cuda/tracing.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/usm.cpp
Resolves the warnings as errors reported in [post merge](https://github.com/intel/llvm/actions/runs/5266121277/jobs/9519634360) as a result of merging #9512. Additionally move pre-processor guards to resolve unused global variables which would also fail in this build configuration (clang & SYCL_ENABLE_WERROR=ON).
> [SYCL][CUDA] Fix post merge errors from #9512

- polygeist/tools/cgeist/Lib/clang-mlir.cc
Remove definition of variable `SignedType`, which is no longer used since commit ee166e0ed812cd7aea11311adb650a58501c8ef7.
> [SYCL-MLIR][NFC] Remove unused variable definition

- devops/actions/e2e-tests/action.yml
I don't think we test it anywhere in our CI pipeline.
> [CI] Remove FPGA Emulator workaround

- sycl/include/sycl/functional.hpp
These operators were changed from aliasing their `std` counterparts in https://github.com/intel/llvm/pull/9298 but a const-qualification was not added (as required by [4.17.2. Function objects](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:function-objects)).
> [SYCL] Const-qualify sycl::logical_{or, and}

- sycl/doc/extensions/proposed/sycl_ext_intel_grf_size.asciidoc
- sycl/doc/extensions/proposed/sycl_ext_intel_register_mode.asciidoc
This extension is used to specify the register mode on an Intel GPU.
Currently we only support specific register mode values on specific GPUs.
> [SYCL][DOC] Add sycl_ext_intel_grf_size extension

- .github/workflows/sycl_precommit.yml
https://github.com/intel/llvm/pull/9844 somehow caused problems with lint tasks when `origin/sycl` is newer than PR's merge base with it. I don't understand how that wasn't a problem before, but let's try to fix it.
While on it, start using sparse checkout to get
`devops/actions/cached_checkout` instead of "wget".
> [CI] Try to fix lint issues

- sycl/include/sycl/multi_ptr.hpp
- sycl/test/multi_ptr/ext_addr_spaces.cpp
The sycl_ext_usm_address_spaces extension adds the ext_intel_global_device_space address space together with additional multi_ptr constructors for creating a multi_ptr from an accessor. However, the current implementation fails to construct the multi_ptr from an accessor when the extended address space decorations are enabled (through __ENABLE_USM_ADDR_SPACE__) as it attempts to use the normal global address space decoration.
This commit fixes these constructors by doing a legal cast of the underlying global-space pointer to a ext_intel_global_device_space decorated pointer.
> [SYCL] Fix multi_ptr ctor for extended address spaces

- polygeist/lib/Dialect/Polygeist/Transforms/LoopInternalization.cpp
- polygeist/test/polygeist-opt/sycl/loop_internalization.mlir
Dimension order, `sycl.constructor` index order, `memref.view` shape order, and load/store order should all be the same.
> [SYCL-MLIR][LoopInternalization] Fix transformation code generation

- devops/actions/clang-format/action.yml
Manual testing before merging lint-related PRs didn't reveal issues but it seems to misbehave after merge. Add some debug output to root cause. I hope to address the issues during the day, if not I'm going to revert the changes in the evening.
> [CI] Add debug output for the clang-format task

- .github/CODEOWNERS
Mark newly ported UR CUDA plugin as owned by CUDA reviewer group
> [SYCL][UR][CUDA] Update CODEOWNERS for Unified Runtime CUDA Adapter

- polygeist/test/polygeist-opt/types.mlir
- polygeist/tools/cgeist/driver.cc
- polygeist/tools/polygeist-opt/polygeist-opt.cpp
Attach `MemRefInsider` interface to `llvm.array` type both in `cgeist` and `polygeist-opt`.
> [SYCL-MLIR] Allow `llvm.array` as `memref` type in `polygeist`

- sycl/doc/extensions/proposed/sycl_ext_oneapi_address_cast.asciidoc
- sycl/doc/extensions/proposed/sycl_ext_oneapi_address_space_cast.asciidoc
Splits sycl::address_space_cast into static and dynamic casts, allowing developers to avoid the overhead of address space checks at runtime.
> [SYCL][DOC] Add sycl_ext_oneapi_address_cast

- clang/lib/Driver/ToolChains/Clang.cpp
- clang/lib/Frontend/InitPreprocessor.cpp
- clang/test/Driver/sycl-esimd-force-stateless-mem.cpp
- sycl/test-e2e/ESIMD/acc_gather_scatter_rgba_stateless.cpp
- sycl/test-e2e/ESIMD/accessor_gather_scatter_stateless.cpp
- sycl/test-e2e/ESIMD/accessor_load_store_stateless.cpp
- sycl/test-e2e/ESIMD/accessor_stateless.cpp
- sycl/test-e2e/ESIMD/lsc/lsc_predicate_stateless.cpp
- sycl/test-e2e/ESIMD/lsc/lsc_surf_load_u32_stateless.cpp
- sycl/test-e2e/ESIMD/lsc/lsc_surf_load_u64_stateless.cpp
- sycl/test-e2e/ESIMD/lsc/lsc_surf_load_u8_u16_stateless.cpp
- sycl/test-e2e/ESIMD/lsc/lsc_surf_store_u32_stateless.cpp
- sycl/test-e2e/ESIMD/lsc/lsc_surf_store_u64_stateless.cpp
Right now, the `-fsycl-esimd-force-stateless-mem` flag sets the `__ESIMD_FORCE_STATELESS_MEM` macro for the device compiler only. We have some APIs that have different arguments with `__ESIMD_FORCE_STATELESS_MEM` vs without it, so getting the host compiler to not error when calling one of those functions can be frustrating for the user.
Make `-fsycl-esimd-force-stateless-mem` set `__ESIMD_FORCE_STATELESS_MEM` for the host compiler too.
I also found we had some esimd_emulator tests that were testing stateless mode, but the emulator never uses the device code and always uses host code, so it wasn't even testing stateless mode. We discussed this internally and decided to disable the tests on the emulator.
> [SYCL][ESIMD][Driver] Pass -fsycl-esimd-force-stateless-mem to host

- clang/lib/Driver/Driver.cpp
- clang/test/Driver/sycl-unique-prefix.cpp
This commit changes unique ID prefix to start with "uid" to avoid the name having a number as the first character. This is needed for IGC to correctly handle the names when used for externally visible device_global.
> [SYCL] Change unique prefix to start with "uid"

- mlir-sycl/include/mlir/Dialect/SYCL/Utils/Utils.h
- mlir-sycl/lib/Dialect/SYCL/IR/SYCLTypes.cpp
- mlir-sycl/lib/Dialect/SYCL/Utils/Utils.cpp
- polygeist/include/mlir/Dialect/Polygeist/Analysis/MemoryAccessAnalysis.h
- polygeist/include/mlir/Dialect/Polygeist/Utils/TransformUtils.h
- polygeist/lib/Dialect/Polygeist/Analysis/MemoryAccessAnalysis.cpp
- polygeist/lib/Dialect/Polygeist/Transforms/LoopInternalization.cpp
- polygeist/lib/Dialect/Polygeist/Utils/TransformUtils.cpp
- polygeist/test/polygeist-opt/sycl/loop_internalization.mlir
Change code generation of `LoopInternalization` transformation to not rely on `nd_item`. Extend the transformation to allow kernel with input `sycl::item` on top of `sycl::nd_item`.
> [SYCL-MLIR][LoopInternalization] Remove codegen dependency on `nd_item`

- clang/lib/Driver/Driver.cpp
- clang/test/Driver/sycl-offload.cpp
Icx with -fsycl option behaves as C++ compiler but it doesnot add C++ libraries at link time. So to have some alignment between compilation and link step we need icx to add C++ libraries if -fsycl option is specified.
> [Driver][sycl]Adding C++ libraries to the linker with -fsycl

- sycl/test-e2e/ESIMD/lsc/lsc_gather_scatter_stateless_64.cpp
After https://github.com/intel/llvm/commit/8b85b6400b8271cf3bcf8e91fe1cb81a2665e23a, we don't need the conversion operator so let's revert the change. I manually confirmed this compiles.
This reverts commit f448631ace2e6ea31e1f506d9444185a099981c0.
> [SYCL][ESIMD][E2E] Revert "Fix compile fail for lsc_gather_scatter_stateless_64.cpp test (#9816)"

- clang/test/CodeGen/fp-accuracy.c
- clang/test/Driver/fp-accuracy.c
They fail in post commit for a couple of days.
https://github.com/intel/llvm/issues/9934
> [SYCL][FE][Driver] Disable fp-accuracy tests

- polygeist/lib/Dialect/Polygeist/Utils/TransformUtils.cpp
- polygeist/test/polygeist-opt/sycl/detect-reduction-accessor-versioning.mlir
- polygeist/test/polygeist-opt/sycl/kernel_disjoint_specialization.mlir
- polygeist/test/polygeist-opt/sycl/licm-accessor-versioning.mlir
`sycl::constructSYCLID` can be used in the utilities functions of `VersionConditionBuilder` to have a consistent way to construct a `sycl.id`. Ideally we can directly create `sycl.constructor(id, indexes)` and lower it in `SYCLToLLVM`. When we can do that, we only need to change the `sycl::cosntructSYCLID` function.
> [SYCL-MLIR][NFC] Use `sycl::constructSYCLID` in `VersionConditionBuilder`

- sycl/test/esimd/dpas.cpp
Test function was inlined into the kernel and remained in the module.
Since begin/end CHECKs were not CHECK-LABELs a DPAS API call was matched with the code from the following function (kernel) because of inlining.
> [SYCL][ESIMD][E2E] Fix a copy-paste error in DPAS API tests

- sycl/test-e2e/ESIMD/thread_id_test.cpp
We updated the GPU driver in https://github.com/intel/llvm/commit/52a0fc8ed65d31b403fa68e24d4db8e77685171f and this test is passing on GPU now.
The test uses XFAIL so the test is actually failing in CI.
Fixes: https://github.com/intel/llvm/issues/9941
> [SYCL][ESIMD][E2E] Enable thread_id_test on GPU

- .github/workflows/sycl_post_commit.yml
1) Don't run in pre-commit to enhance security
2) Run automatically when on a push to a branch starting with
"test-devops-pr" to enable testing for CI-related changes
> [CI] Change trigger events for post commit task

- polygeist/tools/cgeist/Lib/CGExpr.cc
- polygeist/tools/cgeist/Lib/clang-mlir.cc
- polygeist/tools/cgeist/Test/Verification/sycl/array-copy.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/array-member.cpp
Construct this members in-place instead of trying to allocate the array, constructing it and then copying.
> [SYCL-MLIR] Construct array member in-place in initializer lists

- mlir-sycl/include/mlir/Dialect/SYCL/Utils/Utils.h
- mlir-sycl/lib/Dialect/SYCL/Utils/Utils.cpp
- polygeist/lib/Dialect/Polygeist/Transforms/LoopInternalization.cpp
- polygeist/lib/Dialect/Polygeist/Utils/TransformUtils.cpp
- polygeist/test/polygeist-opt/sycl/loop_internalization.mlir
`sycl.id.get` and `sycl.range.get` can directly return `index` instead of `memref<?xindex>`, by doing that we can simplify codegen to not generate the load from it after.
For example:
```
%[[VAL_6:.*]] = sycl.id.get %[[VAL_3]]{{\[}}%[[VAL_5]]] : (memref<1x!sycl_id_2_1>, i32) -> memref<?xindex>
%[[LOCALID0:.*]] = memref.load %[[VAL_6]]{{\[}}%[[VAL_4]]] : memref<?xindex>
```
can be simplified to:
```
%[[LOCALID0:.*]] = sycl.id.get %[[VAL_3]]{{\[}}%[[VAL_5]]] : (memref<1x!sycl_id_2_1>, i32) -> index
```
> [SYCL-MLIR][LoopInternalization] Simplify code generation

- devops/dependencies.json
- sycl/plugins/level_zero/CMakeLists.txt
This patch updates Level Zero Loader to version v1.11.0 because
the previous version does not support implementation of 
https://github.com/oneapi-src/level-zero-spec/pull/23 Level Zero extension, required for 
implementing sycl_ext_oneapi_device_architecture on host
Addresses https://github.com/intel/llvm/pull/9843#discussion_r1230254447
> [SYCL] Update Level Zero Loader to v1.11.0

- libclc/utils/libclc-remangler/LibclcRemangler.cpp
Since https://github.com/intel/llvm/commit/94f7c961c78d8fdbc05898cfbbf88094de45c1ad landed the `-fno-lifetime-dse` option is added to the compilation database, if using non-llvm based toolchains, this option is not compatible with clang and as tools invocation in libclc does not relay on the content of the DB, use the default, empty one.
Also fix deprecated `makeArrayRef` warning.
cc: [abagusetty](https://github.com/abagusetty)
> [LIBCLC] Use default compilation DB for ClangTool run

- sycl/include/sycl/group_algorithm.hpp
- sycl/test-e2e/GroupAlgorithm/exclusive_scan_sycl2020.cpp
- sycl/test-e2e/GroupAlgorithm/inclusive_scan_sycl2020.cpp
- sycl/test-e2e/GroupAlgorithm/reduce_sycl2020.cpp
- sycl/test-e2e/GroupAlgorithm/support.h
This PR also removes unnecessary special cases for half in the static assertions of the group algorithms (and adds corresponding tests for them) and refactors the `reduce_sycl2020.cpp`, `inclusive_scan_sycl2020.cpp`, and `exclusive_scan_sycl2020.cpp` tests a bit.
> [SYCL] Allow group algorithms to accept a function object with an explicit type

- sycl/plugins/unified_runtime/ur/adapters/level_zero/ur_level_zero_platform.cpp
this to avoid errors when enabling validation layer in L0 with ZE_DEBUG=6.
> [SYCL][UR][L0] Initialize correctly ze_command_queue_group_properties_t

- sycl/plugins/unified_runtime/ur/adapters/level_zero/ur_level_zero_program.cpp
If piProgramBuild fails, do not remove L0 build log, which is expected to be read later in piProgramGetBuildInfo.
> [SYCL][UR][L0] Do not destroy build log on piProgramBuild

- .github/workflows/sycl_linux_build_and_test.yml
We already have proper check on the `e2e-tests` job, but it depends on the `aws-start` task and that didn't have the check. That resulted in the `aws-start` being skipped whenever any of `check-*` steps failed and resulted in E2E tests not running even though we can easily run them to get better coverage.
This should make our post-commit CI more useful in presence of failures on `check-*` targets during the build stage.
> [CI] Don't skip E2E tests if only check-* steps in build fail

- .github/workflows/sycl_precommit.yml
Arbitrary PR shouldn't be able to modify the action and use it in the pre-commit CI run.
> [CI] Use devops/actions/clang-format from github.base_ref

- sycl/include/sycl/ext/intel/esimd/detail/simd_mask_impl.hpp
- sycl/include/sycl/ext/intel/esimd/detail/simd_obj_impl.hpp
- sycl/include/sycl/ext/intel/esimd/simd.hpp
- sycl/test-e2e/ESIMD/api/functional/operators/operator_assignment_glb.cpp
- sycl/test-e2e/ESIMD/api/functional/operators/operator_assignment_glb_mask.cpp
- sycl/test/esimd/simd.cpp
The implicitly generated copy assignment operator doesn't do what we need because we need vloads and vstores for globals.
Add an explicit copy assignment operator to do what we want.
Note this makes the `simd` and `simd_mask` classes not trivially move assignable or copy assignable, but that is a fundamental requirement to support globals, so it being trivially assignable was a bug.
> [SYCL][ESIMD] Fix assignment to private globals

- sycl/plugins/opencl/pi_opencl.cpp
- sycl/test/abi/pi_opencl_symbol_check.dump
Change the result of `CL_EVENT_COMMAND_EXECUTION_STATUS` from  `CL_QUEUED` to `CL_SUBMITTED` since SYCL doesn't have an equivalent to `CL_QUEUED`. This commit adds the `piEventGetInfo` symbol to the OpenCL PI plugin, which is a non-breaking ABI change. Fixes #9099.
> [SYCL][PI] Map `CL_QUEUED` to `CL_SUBMITTED`

- sycl/include/sycl/ext/oneapi/sub_group.hpp
- sycl/test-e2e/SubGroup/sub_group_by_value_semantics.cpp
According to SYCL2020 sycl::sub_group must follow by-value semantics.
> [SYCL] Fix sycl::sub_group by-value semantics

- sycl/include/sycl/ext/oneapi/sub_group.hpp
Fixes post-commit after https://github.com/intel/llvm/commit/064f332f156c606c43f4909dc041d28468b793f9
> [SYCL][NFC] Fix unused variables warning in sub_group extension

- sycl/test-e2e/Matrix/element_wise_all_ops_tf32.cpp
we remove XFAIL for cpu because sycl runtime will take care of the type and shape checking (optional kernel feature) in the future.
when that feature is done, this testcase will fail as expected and will be set XFAIL again.
> [SYCL][Matrix] Remove cpu's XFAIL for element_wise_all_ops_tf32.cpp

- mlir/lib/Analysis/DataFlow/IntegerRangeAnalysis.cpp
- mlir/test/Dialect/Arith/int-range-interface.mlir
- mlir/test/lib/Transforms/TestIntRangeInference.cpp
This problem is exposed when adding `LoopInternalization` in the pipeline and running SYCL-Bench convariance. 
The problem is only exposed when `SparseConstantPropagation` is also loaded in the solver with `IntegerRangeAnalysis`.
> [SYCL-MLIR][IntegerRangeAnalysis] Loop UB may be uninitialized

- sycl/plugins/hip/pi_hip.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/device.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/event.cpp
- sycl/test-e2e/Basic/event_profiling_info.cpp
* Call to `hipEventElapsedTime` return `hipErrorNotReady` when the timestamp has not yet been `recorded` on one or both events.  Calling `hipEventSynchronize` block until the event is ready.
* The issue showed itself when profiling sycl-blas benchmark.
* Enable support for cuda / hip in event_profiling_info.cpp
> [SYCL][CUDA][HIP] Block until the event is ready to start profiling.

- .github/workflows/sycl_detect_changes.yml
- .github/workflows/sycl_precommit.yml
[CI] Skip pre-commit jobs when CI-related files are modified
That has to be tested via auxiliary draft pull request. The pattern
would be:
- create branch `sycl-devops-pr/<name>` in *intel*/llvm repo, it will
run post-commit testing
- create PR out of that branch
- create an extra draft PR with a target branch set to the same
`sycl-devops-pr/<name>`, that will run pre-commit testing
> [CI] Skip pre-commit jobs when CI-related files are modified

- sycl/plugins/unified_runtime/ur/adapters/level_zero/ur_level_zero_device.cpp
3c35b1b59093a2b34dcaf803f995b3e3ab5c0cde dropped this previous fix by mistake: https://github.com/intel/llvm/pull/8624
> [SYCL] Fix global memory reporting for Arc

- sycl/include/sycl/builtins.hpp
We are going to change built-ins implementation from templates to overloads according to KhronosGroup/SYCL-Docs#428. This patch is intended to unblock the parallel transition of the different groups of built-ins.
> [SYCL] Add defines for built-in transition

- libclc/amdgcn-amdhsa/libspirv/group/collectives.cl
- libclc/ptx-nvidiacl/libspirv/group/collectives.cl
As the loop count is not statically known and llvm can not guarantee that the target allows remainders, this loop is not unrolled.
Fixes: https://github.com/intel/llvm/issues/9783
> [LIBCLC] Remove unnecessary unroll pragma

- sycl/plugins/unified_runtime/ur/adapters/cuda/queue.hpp
- sycl/test-e2e/KernelFusion/sync_two_queues_event_dep.cpp
This fixes a change in `hasBeenSynchronized` accidentally introduced during the UR port
> [SYCL][CUDA] Fix broken synchronization of CUstreams

- sycl/include/sycl/detail/pi.hpp
- sycl/pi_win_proxy_loader/pi_win_proxy_loader.cpp
- sycl/source/detail/online_compiler/online_compiler.cpp
- sycl/source/detail/posix_pi.cpp
- sycl/source/detail/windows_pi.cpp
- sycl/test-e2e/OnlineCompiler/online_compiler_L0.cpp
- sycl/test-e2e/OnlineCompiler/online_compiler_OpenCL.cpp
- sycl/test-e2e/OnlineCompiler/online_compiler_common.hpp
The online_compiler loads ocloc and was doing so via the function that SYCL uses to load its own Plugins. The win-proxy-loader changes that and loads the plugins earlier. I inadvertently swept the online compiler into that work, which was a mistake. It should be separate. I am restoring that separation here.
I also have a tiny fix to one of the end-to-end tests that merely avoids a deprecation warning, not worth opening a separate PR for that.
> online_compiler load via loadOSLibrary, not loadOSPlugin

- polygeist/tools/cgeist/Lib/TypeUtils.cc
- polygeist/tools/cgeist/Test/Verification/sycl/accessor-local.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/types.cpp
The specialization of `sycl::accessor` with `target::local` is a deprecated feature in SYCL 2020 and has the same semantics and restrictions as `sycl::local_accessor`. 
So far, the specialization was treated like a regular `sycl::accessor` in the MLIR compilation flow, causing issues in `KernelDisjointSpecialization` and in lowering of the subscript operator, as the implementation-specific layout of the specialization is very different from regular `sycl::accessor`. 
This patch changes the handling of the `sycl::accessor` specialization with `target::local` to make it identical to the handling of `local_accessor`, resolving the issues in compilation pipeline.
> [SYCL-MLIR] Change handling of sycl::accessor with target::local

- polygeist/lib/Dialect/Polygeist/Transforms/LICM.cpp
- polygeist/test/polygeist-opt/licm.mlir
An early exit in `canBeHoisted` (returning `true`) lead to hoisting operations which could not be hoisted because operations inside their regions used values defined inside the loop and not hoisted, e.g.:
```mlir
affine.for %arg0 = 0 to 10 {
%0 = "gen"() : () -> i32
%1 = "gen"() : () -> i32
%true = arith.constant true
scf.if %true {
arith.cmpi eq, %0, %1 : i32
}
affine.yield
}
```
would have been transformed into:
```mlir
%true = arith.constant true
scf.if #set {
scf.if %true {
arith.cmpi eq, %0, %1 : i32
}
affine.for %arg0 = 0 to 10 {
%0 = "gen"() : () -> i32
%1 = "gen"() : () -> i32
affine.yield
}
}
```
which is clearly illegal as `%0` and `%1` do not dominate their uses (in the `arith.cmpi` operation inside the `scf.if` operation, hoisted as it is has no memory effects).
By removing …
> [SYCL-MLIR][LICM] Always check that operations can be hoisted recursively

- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLOps.td
- mlir-sycl/lib/Conversion/SYCLToLLVM/DPCPP.cpp
- mlir-sycl/lib/Dialect/SYCL/IR/SYCLOps.cpp
- mlir-sycl/test/Conversion/SYCLToLLVM/sycl-constructors-to-llvm.mlir
- mlir-sycl/test/Dialect/SYCL/constructors.mlir
- mlir-sycl/test/Dialect/SYCL/invalid.mlir
This operation creates a new `sycl.id`. The following signatures are provided:
```mlir
() -> memref<1x!sycl_id_N>
(index) -> memref<1x!sycl_id_1>
(index, index) -> memref<1x!sycl_id_2>
(index, index, index) -> memref<1x!sycl_id_3>
(memref<?x!sycl_id_N>) -> memref<1x!sycl_id_N>
(memref<?x!sycl_range_N>) -> memref<1x!sycl_id_N>
(memref<?x!sycl_item_N>) -> memref<1x!sycl_item_N>
```
In addition of initializing the values, this operation also allocates the object.
> [SYCL-MLIR] Define `sycl.id.constructor` operation

- sycl/include/sycl/ext/oneapi/annotated_arg/annotated_arg.hpp
- sycl/include/sycl/ext/oneapi/annotated_arg/properties.hpp
Move the `DeducedProperties` type-trait utility from 
```include/sycl/ext/oneapi/annotated_arg/annotated_arg.hpp```
to the common header
```include/sycl/ext/oneapi/annotated_arg/properties.hpp```
so that it can be used by both `annotated_arg` and `annotated_ptr` classes.
> [SYCL][NFC] annotated_arg headers code refactor

- sycl/test-e2e/Basic/spirv_device_obj_smoke.cpp
Add a test for the most basic use case to make sure we don't break anything.
> [SYCL][E2E] Add SPIR-V fat object smoke test

- sycl/test-e2e/Plugin/interop-level-zero-image-ownership.cpp
image ownership test shouldn't be subject to mem leak check, since it intentionally creates an unbalanced create/release situation  for the purpose of testing
> [SYCL] no ze_debug mem check on image-ownership test

- sycl/test-e2e/ESIMD/api/functional/operators/operator_assignment_glb_mask.cpp
The driver uplift fixed the issues on other platforms.
> [SYCL][ESIMD][E2E] Run operator_assignment_glb_mask.cpp on non-PVC hardware

- sycl/doc/extensions/supported/sycl_ext_intel_esimd/README.md
- sycl/doc/extensions/supported/sycl_ext_intel_esimd/examples/README.md
- sycl/doc/extensions/supported/sycl_ext_intel_esimd/examples/invoke_simd.md
This change adds an invoke_simd example that scales the input data and updates related doc to point to it.
> [SYCL][ESIMD][Doc] Add invoke_simd example

- sycl/test-e2e/ESIMD/bfn.cpp
> [SYCL][ESIMD][E2E] Fix BFN test on Windows

- sycl/doc/extensions/experimental/sycl_ext_oneapi_device_global.asciidoc
- sycl/source/feature_test.hpp.in
This commit moves the sycl_ext_oneapi_device_global extension from "proposed" to "experimental" and defined the
SYCL_EXT_ONEAPI_DEVICE_GLOBAL feature test macro.
> [SYCL][Docs] Move sycl_ext_oneapi_device_global out of proposed

- polygeist/lib/Dialect/Polygeist/Transforms/LoopInternalization.cpp
- polygeist/test/polygeist-opt/sycl/loop_internalization_invalid.mlir
`LoopInternalization` is unable to correctly transform memory access with indexes that use more than one innermost loop induction variable or thread ids in the same dimension. Adding this restriction in `isCandidateAccess` to avoid incorrect transformation.
> [SYCL-MLIR][LoopInternalization] Restrict transformation

- .github/workflows/sycl_detect_changes.yml
- .github/workflows/sycl_gen_test_matrix.yml
- .github/workflows/sycl_precommit.yml
We are going to re-build the cuda runner, need to ensure CI continues working while it will be offline. The move is also good by itself as there was nothing cuda-specific in those tasks.
> [CI] Move auxilliary tasks from cuda to Linux/build runners

- .github/workflows/sycl_precommit.yml
We've switched the task to use "[Linux, build]" runners in #10074 and this option isn't needed anymore.
> [CI] Remove "--privileged" from the lint task

- .github/workflows/sycl_precommit.yml
Aligns the task with its Linux counterpart.
> [CI] Don't skip Win testing due to failing lint if ignore-lint is present

- polygeist/lib/Dialect/Polygeist/Transforms/CanonicalizeFor.cpp
- polygeist/test/polygeist-opt/whiletofor.mlir
- sycl/test-e2e/xfail_tests.txt
Fail if any of the `scf.condition` operands is defined by an operation in the before block.
> [SYCL-MLIR] Restrict `MoveWhileToFor` `-canonicalize-scf-for` applicability

- polygeist/lib/Dialect/Polygeist/Transforms/LoopInternalization.cpp
- polygeist/test/polygeist-opt/sycl/loop_internalization.mlir
- polygeist/test/polygeist-opt/sycl/loop_internalization_invalid.mlir
When promoting access like `A[ty][i]`, where `ty` is the global id of dimension 1 and `i` is the innermost loop induction variable,
we were storing to `shared_local_A[LOCALID0][LOCALID1]`, which generates incorrect result, to solve this problem, we need to use local id of the same dimension as the global id used per index, i.e., we should instead store to `shared_local_A[LOCALID1][LOCALID0]`.
The problem is exposed when running `SYCL-Bench` with `LoopInternalization`. After this PR, `SYCL-Bench` that passes without `LoopInternalization`, also passes with `LoopInternalization` end to end.
> [SYCL-MLIR][LoopInternalization] Fix code generation

- polygeist/tools/cgeist/Lib/CodeGenTypes.cc
- polygeist/tools/cgeist/Lib/utils.cc
- sycl/test-e2e/xfail_tests.txt
Nowadays the SYCL API classes live in the inline namespace `_V1` inside `sycl::`, and were wrongly classified as being `NamespaceKind::WithinSYCL` instead of `SYCL`. This PR changes the helper to look through inline namespaces.
In consequence, the check for undefined (in the dialect) SYCL types works again as intended, however we need to allow helper structs and unions defined in the API classes as well.
Lastly, the `sycl::sampler` class is actually a type that is not represented in the dialect, so I had to add the corresponding e2e test to the XFAIL list.
> [SYCL-MLIR] Skip inline namespaces in `getNamespaceKind(...)`.

- polygeist/include/mlir/Dialect/Polygeist/Transforms/Passes.h
- polygeist/include/mlir/Dialect/Polygeist/Transforms/Passes.td
- polygeist/lib/Dialect/Polygeist/Transforms/CMakeLists.txt
- polygeist/lib/Dialect/Polygeist/Transforms/SYCLRaiseHost.cpp
Add a basic skeleton for an MLIR pass raising SYCL constructs in host code from LLVM dialect to SYCL dialect.
The pass is based on patterns which will detect the relevant constructs and replace them by SYCL dialect operations.
> [SYCL-MLIR] Basic skeleton for host raising pass

- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLTypes.td
- mlir-sycl/lib/Conversion/SYCLToLLVM/DPCPP.cpp
- mlir-sycl/lib/Dialect/SYCL/IR/SYCLDialect.cpp
- mlir-sycl/test/Conversion/SYCLToLLVM/sycl-types-to-llvm.mlir
- polygeist/tools/cgeist/Lib/CodeGenTypes.cc
- polygeist/tools/cgeist/Lib/TypeUtils.cc
- polygeist/tools/cgeist/Test/Verification/sycl/types.cpp
- sycl/test-e2e/HierPar/hier_par_wgscope.cpp
This PR mechanically removes dialect support for the `h_item` class.
Rationale: Hierarchical parallelism is [earmarked to be reworked](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_hierarchical_data_parallel_kernels), so we don't want to support it as a first-class concept in SYCL-MLIR, but it's presence shouldn't break the compiler either.
> [SYCL-MLIR] Demote `h_item` class to generic handling.

- sycl/source/detail/builtins_math.cpp
- sycl/test-e2e/Basic/built-ins/host_math.cpp
Certain quotient values are off by 1 since the conversion to `int` truncates the decimal value. Use `std::round` to round to the nearest integer before converting to `int`.
> [SYCL] Fix `sycl::remquo` truncation error

- sycl/plugins/unified_runtime/ur/adapters/cuda/usm.cpp
These checks are causing issues for very large USM allocations because the `MAX_MEM_ALLOC_SIZE` reported is lower than what CUDA actually supports.
We will follow up with an update on the reported `MAX_MEM_ALLOC_SIZE`, but it makes sense to remove the checks either way, as the CUDA allocation functions will return an error if they can't allocate the memory.
> [SYCL][CUDA] Remove size checks from USM allocations

- sycl/test-e2e/InvokeSimd/Feature/ImplicitSubgroup/SPMD_invoke_ESIMD_external.cpp
- sycl/test-e2e/InvokeSimd/Feature/SPMD_invoke_ESIMD_external.cpp
These tests now pass after this commit: https://github.com/intel/llvm/commit/841768794f7ae59e592d066bb0f695f413c8c6c6
> Unexpectedly Passed Tests (2):
SYCL :: InvokeSimd/Feature/ImplicitSubgroup/SPMD_invoke_ESIMD_external.cpp
SYCL :: InvokeSimd/Feature/SPMD_invoke_ESIMD_external.cpp
> [SYCL] Remove XFAIL from SPMD_invoke_ESIMD_external.cpp

- llvm/lib/SYCLLowerIR/CompileTimePropertiesPass.cpp
- llvm/test/SYCLLowerIR/CompileTimePropertiesPass/kernel-attributes/grf-size.ll
- llvm/test/tools/sycl-post-link/grf-size-conflict.ll
- llvm/test/tools/sycl-post-link/sycl-grf-size.ll
- llvm/tools/sycl-post-link/ModuleSplitter.cpp
- llvm/tools/sycl-post-link/sycl-post-link.cpp
- sycl/doc/extensions/experimental/sycl_ext_intel_grf_size.asciidoc
- sycl/include/sycl/detail/kernel_properties.hpp
- sycl/include/sycl/ext/intel/experimental/grf_size_properties.hpp
- sycl/include/sycl/ext/oneapi/properties/properties.hpp
- sycl/include/sycl/ext/oneapi/properties/property.hpp
- sycl/include/sycl/ext/oneapi/properties/property_utils.hpp
- sycl/source/detail/program_manager/program_manager.cpp
- sycl/test-e2e/DeviceCodeSplit/grf.cpp
- sycl/test-e2e/ESIMD/large-grf.cpp
- sycl/test/extensions/properties/mock_compile_time_properties.hpp
- sycl/test/extensions/properties/properties_ctor_negative.cpp
This change implements `sycl_ext_intel_grf_size`, and in particular:
1) Moves the `sycl_ext_intel_grf_size` spec document from the `proposed` folder to the `experimental` folder, and updates the implementation status in the document to match.
2) Adds two new kernel properties `sycl::ext::intel::experimental::grf_size` and `sycl::ext::intel::experimental::grf_size_automatic`, as per the spec. `grf_size` adds the `sycl-grf-size` metadata with a value of the template parameter (`128` or `256`). `grf_size_automatic` adds the `sycl-grf-size` metadata with a value of `0`.
3) Marks the `sycl::detail::register_alloc_mode` property as deprecated, and it still works as before.
4) Updates `CompileTimePropertiesPass.cpp` to map the `sycl-grf-size` metadata added by the front-end to the …
> [SYCL] Add experimental implementation of sycl_ext_intel_grf_size

- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLHostOps.td
- mlir-sycl/lib/Dialect/SYCL/IR/CMakeLists.txt
- mlir-sycl/lib/Dialect/SYCL/IR/SYCLOps.cpp
- mlir-sycl/test/Dialect/SYCL/host.mlir
- mlir-sycl/test/Dialect/SYCL/invalid.mlir
- `sycl.host.kernel_name`: Symbol referencing a kernel. Set to replace `llvm.mlir.global` operations with constant string values referencing a kernel.
- `sycl.host.get_kernel`: Operation defining a value representing a reference to a kernel. Set to replace `llvm.mlir.addressof` operations referencing operations that can be replaced with `sycl.host.kernel_name`.
Using these operations, we can transform:
```mlir
gpu.module @kernels {
gpu.func @k0() kernel {
gpu.return
}
}
llvm.mlir.global private unnamed_addr constant @kernel_ref("k0\00") 
{addr_space = 0 : i32, alignment = 1 : i64, dso_local}
func.func @f() -> !llvm.ptr {
%0 = llvm.mlir.addressof @kernel_ref : !llvm.ptr
func.return %0 : !llvm.ptr
}
```
into:
```mlir
gpu.module @kernels {
gpu.func @k0() kernel {
gpu.return
}
} …
```
> [SYCL-MLIR] Define `sycl.host.[kernel_name|get_kernel]`

- sycl/test-e2e/OnlineCompiler/online_compiler_OpenCL.cpp
This test used to be only run on the CPU and GPU but when we moved to the `%{run}` notation, it wasn't marked as unsupported on accelerator.  It seems unsupported on accelerator. The `clCreateProgramWithIL()` call is returning and error -59 when the accelerator device is the one behind the context. I went back and checked and it has never worked on accelerator. I'll make a note in the online compiler tickets and if this is a real error, a ticket will be opened. But the test should be restored so to not be run on accelerator.
> [SYCL][E2E] Mark a test as unsupported on accelerator

- .github/workflows/linux_matrix_e2e_on_nightly.yml
Two reasons:
1) Not reliable, easy to skip testing without noticing.
2) That accidentally enabled "opencl:acc" that we don't run anywhere
else and its state isn't green, resulting in "false" failures
reported by CI.
> [CI] Don't use "target_devices: all" in linux_matrix_e2e_on_nightly.yml

- .github/workflows/sycl_windows_build_and_test.yml
Same as was done in https://github.com/intel/llvm/pull/9912 for Linux.
> [CI][WIN] Don't skip E2E tests if only check-* steps in build fail

- sycl/doc/extensions/proposed/sycl_ext_oneapi_work_group_local.asciidoc
Introduces support for work-group local allocations at program and function scope, lifting some of the restrictions of sycl_ext_oneapi_group_local_memory.
> [SYCL][DOC] Add sycl_ext_oneapi_work_group_local

- sycl/test-e2e/ESIMD/accessor_local.cpp
Fixes post-commit: https://github.com/intel/llvm/pull/10054#issuecomment-1611396641
> [SYCL][E2E] Enable ESIMD/accessor_local.cpp on Linux after the GPU driver update

- .github/CODEOWNERS
have @intel/dpcpp-nativecpu-pi-reviewers own:
sycl/plugins/native_cpu/
sycl/test/check_device_code/native_cpu/
sycl/test/native_cpu/
clang/include/clang/Basic/SYCLNativeCPUHelpers.h
clang/test/CodeGenSYCL/native_cpu_basic.cpp
clang/test/Driver/sycl-native-cpu-fsycl.cpp
clang/test/Driver/sycl-native-cpu-warn.cpp
clang/test/Driver/sycl-native-cpu.cpp
llvm/include/llvm/SYCLLowerIR/EmitSYCLNativeCPUHeader.h
llvm/include/llvm/SYCLLowerIR/PrepareSYCLNativeCPU.h
llvm/lib/SYCLLowerIR/EmitSYCLNativeCPUHeader.cpp
llvm/lib/SYCLLowerIR/PrepareSYCLNativeCPU.cpp
sycl/doc/design/SYCLNativeCPU.md
> [SYCL][CODEOWNERS] Update CODEOWNERS for Native CPU Device

- sycl/doc/extensions/proposed/sycl_ext_oneapi_named_sub_group_sizes.asciidoc
The sycl_ext_oneapi_kernel_properties extension doesn't explain that the various sub-group size properties are compatible with the SYCL_EXT_ONEAPI_FUNCTION_PROPERTY macro, so clarify that in sycl_ext_oneapi_named_sub_group_sizes.
> [SYCL][Doc] Clarify ways to set sub-group sizes

- polygeist/tools/cgeist/Lib/CodeGenTypes.cc
> [SYCL-MLIR] Pass-through uses of `sycl::private_memory`

- polygeist/include/mlir/Dialect/Polygeist/Utils/Utils.h
- polygeist/lib/Dialect/Polygeist/Transforms/SYCLRaiseHost.cpp
- polygeist/test/polygeist-opt/sycl/sycl-raise-host.mlir
- polygeist/tools/cgeist/Lib/clang-mlir.cc
- polygeist/tools/cgeist/Lib/clang-mlir.h
- polygeist/tools/cgeist/Lib/utils.cc
- polygeist/tools/cgeist/driver.cc
Transform:
```mlir
gpu.module @kernels {
gpu.func @k0() kernel {
gpu.return
}
}
llvm.mlir.global private unnamed_addr constant @kernel_ref("k0\00") 
{addr_space = 0 : i32, alignment = 1 : i64, dso_local}
func.func @f() -> !llvm.ptr {
%0 = llvm.mlir.addressof @kernel_ref : !llvm.ptr
func.return %0 : !llvm.ptr
}
```
into:
```mlir
gpu.module @kernels {
gpu.func @k0() kernel {
gpu.return
}
}
llvm.mlir.global private unnamed_addr constant @kernel_ref("k0\00") 
{addr_space = 0 : i32, alignment = 1 : i64, dso_local}
func.func @f() -> !llvm.ptr {
%0 = sycl.host.get_kernel @kernels::@k0 : !llvm.ptr
func.return %0 : !llvm.ptr
}
```
In order to do this transformation, the name of the `gpu.module` holding the kernels comes handy, so that was moved to an accessible header file. Note that this name …
> [SYCL-MLIR] Raise construct to `sycl.host.get_kernel`

- sycl/doc/extensions/supported/sycl_ext_intel_esimd/examples/README.md
- sycl/doc/extensions/supported/sycl_ext_intel_esimd/examples/invoke_simd_slm.md
Similar to my previous PR, this change adds an example of using SLM with invoke_simd. We set up SLM in SYCL code and then do our computation in ESIMD code.
> [SYCL][ESIMD][Doc] Add invoke_simd SLM example

- sycl/test-e2e/ESIMD/hardware_dispatch.cpp
Fixes post-commit: https://github.com/intel/llvm/pull/10087#issuecomment-1612735241
> [SYCL][E2E] Enable ESIMD/hardware_dispatch.cpp on Linux after the GPU driver update

- .github/workflows/sycl_linux_build_and_test.yml
- .github/workflows/sycl_windows_build_and_test.yml
- devops/actions/e2e-tests-win/action.yml
- devops/actions/e2e-tests/action.yml
- devops/actions/khronos_cts_test/action.yml
I plan to enable making releases from Github CI tasks and we'll need to use gzip compression instead of zstd as well as provide distinct names for Linux/Windows.
An alternative would be to unpack/repack in the release action, but the solution implemented in this PR seems to be clearer.
> [CI] Make build artifact archive name/compression parameters

- sycl/test-e2e/Config/allowlist.cpp
Some device names can contain square brackets. This was making the regex generated by the allowlist test invalid. This commit removes the square brakets from the generated regex.
> [SYCL][E2E] Fix allowlist test by removing special characters from the regex.

- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLHostOps.td
- mlir-sycl/test/Dialect/SYCL/host.mlir
- mlir-sycl/test/Dialect/SYCL/invalid.mlir
Change the `sycl.host.constructor` operation to take the `this*` pointer of the object to be constructed as first argument.
> [SYCL-MLIR] Add pointer to host constructor

- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLHostOps.td
- mlir-sycl/lib/Dialect/SYCL/IR/SYCLOps.cpp
- mlir-sycl/test/Dialect/SYCL/host.mlir
- mlir-sycl/test/Dialect/SYCL/invalid.mlir
Define operation assigning a kernel to a `sycl::handler`, thus pairing the handler and the kernel being launched.
> [SYCL-MLIR] Define `sycl.handler.set_kernel`

- .github/CODEOWNERS
Have @intel/sycl-graphs-reviewers with members:
* Ewan Crawford @EwanC - Codeplay
* Ben Tracy @Bensuo - Codeplay 
* Maxime France-Pillois @mfrancepillois - Codeplay
* Pablo Reble @reble - Intel
* Julian Miller @julianmi - Intel
* Stewart Dale @stdale-intel - Intel
As reviewers for the following files relating to the implementation of the [experimental SYCL-Graph extension]:(https://github.com/intel/llvm/pull/5626)
* [sycl/include/sycl/ext/oneapi/experimental/graph.hpp](https://github.com/intel/llvm/blob/sycl/sycl/include/sycl/ext/oneapi/experimental/graph.hpp)
* [sycl/source/detail/graph_impl.cpp](https://github.com/intel/llvm/blob/sycl/sycl/source/detail/graph_impl.cpp)
* [sycl/source/detail/graph_impl.hpp](https://github.com/intel/llvm/blob/sycl/sycl/source/detail/graph_impl.hpp)
* …
> [SYCL][CODEOWNERS] Update CODEOWNERS for SYCL-Graph extension

- sycl/test-e2e/USM/memops2d/copy2d_device_to_host.cpp
- sycl/test-e2e/USM/memops2d/copy2d_host_to_device.cpp
- sycl/test-e2e/USM/memops2d/memcpy2d_device_to_host.cpp
- sycl/test-e2e/USM/memops2d/memcpy2d_host_to_device.cpp
As described in https://github.com/intel/llvm/issues/10157, certain configurations of 2D USM memory copies currently fail for HIP. This commit temporarily disables these.
> [SYCL][HIP][E2E] Disable failing 2D USM tests for HIP

- polygeist/include/mlir/Dialect/Polygeist/Transforms/Passes.td
- polygeist/lib/Dialect/Polygeist/Transforms/CMakeLists.txt
- polygeist/lib/Dialect/Polygeist/Transforms/LoopInternalization.cpp
- polygeist/test/polygeist-opt/sycl/loop_internalization.mlir
- polygeist/test/polygeist-opt/sycl/loop_internalization_unroll.mlir
When `reqd_work_group_size` is not given, the work group size is unknown at compile time.
The first issue we noticed is, we allocate too much shared local memory.
However, even if we lower the shared local memory to exactly how much needed, there is still no performance gain from promoting memory accesses to shared local memory.
Loop is tiled by work group size. When work group size is not compile time know, loop is tiled by dynamic tile size. Dynamic tile size causes IGC to not unroll the tiled loop. Loop unrolling could further enable more optimizations in IGC, e.g., vectorization. If we unroll the tiled loop after promotion, performance can be improved significantly.
> [SYCL-MLIR][LoopInternalization] Unroll tiled loop after promotion

- sycl/test-e2e/DeviceArchitecture/device_architecture_on_host.cpp
Test is unexpectedly passing in both pre-commit and post-commit.
> [SYCL][E2E] Enable device_architecture_on_host for Windows

- sycl/test-e2e/xfail_tests.txt
Test was recently enabled upstream in https://github.com/intel/llvm/commit/fb607c152e6651f6684608d0b2c917c475373c31.
> [SYCL-MLIR] XFAIL ESIMD/accessor_local.cpp

- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLTypes.td
- mlir-sycl/lib/Dialect/SYCL/IR/SYCLTypes.cpp
- polygeist/lib/Dialect/Polygeist/Transforms/CMakeLists.txt
- polygeist/lib/Dialect/Polygeist/Transforms/SYCLRaiseHost.cpp
- polygeist/test/polygeist-opt/sycl/sycl-raise-host.mlir
Raise constructors initializing `sycl::buffer` and `sycl::accessor` to SYCL dialect operations (`sycl.host.constructor`) on the host side to facilitate analysis.
Also introduces a simple representation of the `sycl::buffer` type into the SYCL dialect.
> [SYCL-MLIR] Raise buffer and accessor constructors

- sycl/test-e2e/ESIMD/accessor_local.cpp
Temporary disabled until the fix is created, the issue is https://github.com/intel/llvm/issues/10138.
> [SYCL][E2E] Disable ESIMD/accessor_local.cpp on Linux 

- sycl/plugins/unified_runtime/ur/adapters/cuda/device.hpp
The destructor should be calling `cuDevicePrimaryCtxRelease`
> [SYCL][UR][CUDA] Fix typo in ur_device_handle_t

- sycl/doc/GetStartedGuide.md
LLVM project now requires CMake 3.20+.
> [SYCL][Doc] Update CMake version requirements.

- sycl/plugins/hip/pi_hip.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/command_buffer.cpp
Fixes error found in [post-commit CI](https://github.com/intel/llvm/actions/runs/5454766342/jobs/9925392005) after the merge of https://github.com/intel/llvm/pull/9992
```
/__w/llvm/llvm/src/sycl/plugins/hip/pi_hip.cpp:5635:24: error: unused parameter 'sync_point' [-Werror,-Wunused-parameter]
5635 |     pi_ext_sync_point *sync_point) {
|                        ^
/__w/llvm/llvm/src/sycl/plugins/hip/pi_hip.cpp:5691:12: error: unused parameter 'dst_row_pitch' [-Werror,-Wunused-parameter]
5691 |     size_t dst_row_pitch, size_t dst_slice_pitch,
|            ^
/__w/llvm/llvm/src/sycl/plugins/hip/pi_hip.cpp:5691:34: error: unused parameter 'dst_slice_pitch' [-Werror,-Wunused-parameter]
5691 |     size_t dst_row_pitch, size_t dst_slice_pitch,
|                                  ^
3 errors …
```
> [SYCL][HIP] Ignore unused PI command-buffer parameters

- polygeist/lib/Dialect/Polygeist/Transforms/SYCLRaiseHost.cpp
- polygeist/test/polygeist-opt/sycl/sycl-raise-host.mlir
Add patterns to raise the construction of `sycl::id` and `sycl::range` on the host side. The patterns differ from other patterns, as the constructors are usually inlined, so the pattern needs to match the initialization of the member fields directly.
> [SYCL-MLIR] Raise host construction of sycl::id and sycl::range

- buildbot/configure.py
Some minor housekeeping. We don't need the `amdgcn` and `ptx` dirs of `libclc` for SYCL compilation
> [SYCL][libclc] Removing unused SYCL targets for libclc

- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLOps.td
- mlir-sycl/lib/Conversion/SYCLToLLVM/DPCPP.cpp
- mlir-sycl/lib/Dialect/SYCL/IR/SYCLOps.cpp
- mlir-sycl/test/Conversion/SYCLToLLVM/sycl-constructors-to-llvm.mlir
- mlir-sycl/test/Dialect/SYCL/constructors.mlir
- mlir-sycl/test/Dialect/SYCL/invalid.mlir
This operation creates a new `sycl.range`. The following signatures are provided:
```mlir
(index) -> memref<1x!sycl_range_1>
(index, index) -> memref<1x!sycl_range_2>
(index, index, index) -> memref<1x!sycl_range_3>
(memref<?xsycl_range_N>) -> memref<1x!sycl_range_N>
```
In addition of initializing the values, this operation also allocates the object.
> [SYCL-MLIR] Define `sycl.range.constructor`

- polygeist/lib/Dialect/Polygeist/Transforms/CMakeLists.txt
- polygeist/lib/Dialect/Polygeist/Transforms/SYCLRaiseHost.cpp
- polygeist/test/polygeist-opt/sycl/sycl-raise-host.mlir
Detect `std::string::replace` calls receiving a pointer to a member of a `sycl::handler` and a kernel name (`sycl.host.get_kernel`) as operands and raise.
> [SYCL-MLIR] Raise constructs to `sycl.host.handler.set_kernel`

- sycl/test/basic_tests/vectors/vectors.cpp
The macro causes significant compilation time increase and swizzles can be aquired and tested using different `vec` methods, such as `.lo()` or `.odd()`.
The change reduces time spent in `vectors.cpp` test from 172s to 64s on my machine.
> [SYCL][NFC] Don't use SYCL_SIMPLE_SWIZZLES in vectors LIT test

- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLOps.td
- mlir-sycl/lib/Conversion/SYCLToLLVM/DPCPP.cpp
- mlir-sycl/lib/Dialect/SYCL/IR/SYCLOps.cpp
- mlir-sycl/test/Conversion/SYCLToLLVM/sycl-constructors-to-llvm.mlir
- mlir-sycl/test/Dialect/SYCL/constructors.mlir
- mlir-sycl/test/Dialect/SYCL/invalid.mlir
This operation creates a new `sycl.nd_range`. The following signatures
are provided:
```mlir
(memref<?xsycl_range_N>, memref<?xsycl_range_N>) -> memref<1x!sycl_nd_range_N>
(memref<?xsycl_range_N>, memref<?xsycl_range_N>, memref<?xsycl_id_N>) -> memref<1x!sycl_nd_range_N>
(memref<?xsycl_nd_range_N>) -> memref<1x!sycl_nd_range_N>
```
In addition of initializing the values, this operation also allocates
the object.
> [SYCL-MLIR] Define `sycl.nd_range.constructor`

- sycl/plugins/unified_runtime/ur/adapters/cuda/device.cpp
This patch re-introduces the fix from https://github.com/intel/llvm/pull/8765
Which seems to have been accidentally dropped by the UR port.
> [SYCL][CUDA] Fix cuDeviceGetUuid for older CUDA version

- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLMathOps.td
- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLTypes.td
- mlir-sycl/lib/Conversion/SYCLToLLVM/DPCPP.cpp
- mlir-sycl/lib/Conversion/SYCLToMath/SYCLToMath.cpp
- mlir-sycl/lib/Dialect/SYCL/IR/SYCLOps.cpp
- mlir-sycl/test/Conversion/SYCLToLLVM/sycl-aux-to-llvm.mlir
- mlir-sycl/test/Conversion/SYCLToMath/math-ops.mlir
- mlir-sycl/test/Dialect/SYCL/invalid.mlir
- mlir-sycl/test/Dialect/SYCL/math-ops.mlir
- polygeist/tools/cgeist/Lib/CGExpr.cc
- polygeist/tools/cgeist/Test/Verification/sycl/math_funcs.cpp
**Lowering:**
```mlir
%res = sycl.math.sqrt(%arg) : !sycl_half
```
⬇️
```mlir
%0 = sycl.mlir.unwrap(%arg) : !sycl_half to f16
%1 = math.sqrt(%0) : f16
%res = sycl.mlir.wrap(%1) : f16 to !sycl_half
```
⬇️
```llvm
%0 = extractvalue %"class.sycl::_V1::half" %arg, 0
%1 = call half @llvm.sqrt.f16(half %0)
%res = insertvalue %"class.sycl::_V1::half" undef, half %1, 0
```
> [SYCL-MLIR][MathOps] Add `sycl::half` support

- polygeist/tools/cgeist/Test/Verification/sycl/host_raising.cpp
- polygeist/tools/cgeist/driver.cc
If the `-sycl-use-host-module` option is used, add this pass to the pipeline, which will raise known constructs in the input module to the `sycl` dialect.
> [SYCL-MLIR] Add `-sycl-raise-host` pass to `cgeist` pipeline

- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLHostOps.td
- mlir-sycl/lib/Dialect/SYCL/IR/SYCLOps.cpp
- mlir-sycl/test/Dialect/SYCL/host.mlir
- mlir-sycl/test/Dialect/SYCL/invalid.mlir
Operation assigning an nd-range to a `sycl::handler`, setting the nd-range of the kernel to be launched.
The input nd-range can be specified either with a memref to a `sycl.nd_range` or a memref to a `sycl.range` (global size) and an optional memref to a `sycl.id` (offset).
> [SYCL-MLIR] Define `sycl.host.handler.set_nd_range`

- sycl/test-e2e/Basic/sampler/sampler.cpp
It has very limited checks of sycl::sampler so might pass on some devices/backends that don't support the aspect but that isn't guaranteed and there are ones where it fails (i.e., with an accelerator device).
> [SYCL][E2E] Require aspect-ext_intel_legacy_image in Basic/sampler/sampler.cpp

- polygeist/lib/Dialect/Polygeist/Transforms/SYCLRaiseHost.cpp
- polygeist/test/polygeist-opt/sycl/sycl-raise-host.mlir
Define `OpHostRaisePattern` and `OpInterfaceHostRaisePattern`, which all raising patterns must inherit, to restrict pattern applicability to host code.
Note that no `OpTraitRewritePattern` counterpart is defined, so future patterns matching operations by their traits may need special treatment.
> [SYCL-MLIR] Run raising patterns only in host code

- sycl/source/detail/scheduler/commands.cpp
- sycl/test-e2e/Regression/empty_accessor_use.cpp
There is currently a restriction in commands.cpp that prevents the setting of kernel arugments for accessors with zero in all three dimensions. This only affects empty 3D accessors, as others have 1-padding in the missing dimensions. Since we now allow empty accessors, this restriction should be lifted.
> [SYCL] Allow zero-sized 3D accessors

- clang/lib/CodeGen/CGBuiltin.cpp
A part of the implementation that is missing during merge.
original commit : https://github.com/intel/llvm/commit/b15bf305ca3e9ce63aaef7247d32fb3a75174531
> Add the missing part of "clang: Use new frexp intrinsic for builtins and add f16 version"

- polygeist/lib/Dialect/Polygeist/Transforms/SYCLRaiseHost.cpp
- polygeist/test/polygeist-opt/sycl/sycl-raise-host.mlir
- polygeist/tools/cgeist/Test/Verification/sycl/host_raising.cpp
Make the raising for buffers and accessors more robust by allowing number suffixes for the allocated type name and matching with a regex.
> [SYCL-MLIR] Make accessor raising more robust

- sycl/include/sycl/detail/spirv.hpp
`sycl::cl_*` types were removed from SYCL 2020 in favor of `sycl::opencl::cl_*` types. Adjusted our headers accordingly.
> [SYCL][NFC] Don't use deprecated type aliases

- sycl/doc/extensions/experimental/sycl_ext_oneapi_bindless_images.asciidoc
- sycl/doc/extensions/proposed/sycl_ext_oneapi_bindless_images.asciidoc
Replaces https://github.com/intel/llvm/pull/8307
Required for https://github.com/intel/llvm/pull/9808 and https://github.com/intel/llvm/pull/10112 .
Addressed some of the feedback on revision 3 as revision 4. Any larger changes will need to move to subsequent revisions.
> [SYCL][Doc] Bindless Images proposal revision 4

- sycl/test-e2e/CMakeLists.txt
`if ("${TARGET_DEVICES}" STREQUAL "gpu")` is never true, as `${TARGET_DEVICES}` is undefined.
> [SYCL-MLIR][NFC] `TARGET_DEVICES` is never `gpu`

- sycl/test-e2e/Basic/fpga_tests/buffer_location.cpp
- sycl/test-e2e/Basic/fpga_tests/fpga_io_pipes.cpp
- sycl/test-e2e/Basic/fpga_tests/fpga_pipes_legacy_ns.cpp
- sycl/test-e2e/Basic/fpga_tests/fpga_queue.cpp
- sycl/test-e2e/Basic/handler/interop_task.cpp
- sycl/test-e2e/Basic/multisource.cpp
- sycl/test-e2e/HostInteropTask/host-task.cpp
- sycl/test-e2e/HostInteropTask/interop-task.cpp
- sycl/test-e2e/InorderQueue/in_order_buffs.cpp
- sycl/test-e2e/KernelParams/array-kernel-param-nested-run.cpp
- sycl/test-e2e/KernelParams/array-kernel-param-run.cpp
- sycl/test-e2e/OnlineCompiler/online_compiler_common.hpp
- sycl/test-e2e/Plugin/sycl-targets-order.cpp
- sycl/test-e2e/Regression/2020-spec-constants-debug-info.cpp
- sycl/test-e2e/Regression/fp16-with-unnamed-lambda.cpp
- sycl/test-e2e/Regression/local-arg-align.cpp
- sycl/test-e2e/Regression/mad_sat.cpp
- sycl/test-e2e/Regression/set-arg-local-accessor.cpp
- sycl/test/extensions/fpga.cpp
- sycl/test/gdb/accessors.cpp
- sycl/test/regression/check_config_processing.cpp
- sycl/test/regression/copy-with-unnamed-lambda.cpp
`get_access` for host accessor is deprecated by SYCL 2020 in favor of `get_host_access`.
Note: this patch does not update all tests we have, there are still major categories skipped like `XPTI`, `Sampler`, etc.
> [SYCL][NFC] Modernize getting host accessor

- clang/test/Driver/clang-offload-bundler-standardize.c
This test fails in post-commit.
Issue: https://github.com/intel/llvm/issues/10238
> [SYCL] Disable clang-offload-bundler-standardize.c after https://github.com/intel/llvm/pull/9631

- sycl/include/sycl/accessor.hpp
- sycl/include/sycl/backend.hpp
- sycl/include/sycl/group.hpp
- sycl/include/sycl/group_algorithm.hpp
- sycl/include/sycl/group_barrier.hpp
- sycl/include/sycl/handler.hpp
- sycl/include/sycl/queue.hpp
- sycl/include/sycl/reduction.hpp
- sycl/include/sycl/sub_group.hpp
- sycl/include/sycl/types.hpp
- sycl/test-e2e/Basic/range_offset_fit_in_int.cpp
- sycl/test/basic_tests/group.cpp
`sycl::runtime_error` is deprecated in SYCL 2020. Therefore, removing its uses (at least some) from our RT headers.
This PR **does not** cover:
- some of our extensions, like `fixed_size_group` or `matrix`
- `detail/common.hpp`, because it depends on RT library update
- RT library (i.e. `source/` dir)
> [SYCL] Use sycl::exception instead of sycl::runtime_error

- polygeist/include/mlir/Dialect/Polygeist/Transforms/Passes.td
- polygeist/lib/Dialect/Polygeist/Transforms/LoopInternalization.cpp
When adding `LoopInternalizationPass` to an existing `OpPassManager`, all passes added to the `OpPassManager` are not performed when the source code doesn't contain a `gpu.module` and  `LoopInternalizationPass` is a `GPUModule` pass, which causes `check-cgeist` to fail. 
After this PR, `check-cgeist` passes with (or without) `LoopInternalization` added in the pipeline.
This reverts commit 46d6cb9f7f1fcfdeec0655702e03e8b0ce41f4b3 partially.
> [SYCL-MLIR][LoopInternalization] Revert change to `GPUModule` pass

- clang/lib/Driver/ToolChains/SYCL.cpp
- clang/test/Driver/sycl-device-lib.cpp
In AOT compilation, "bfloat16" related libdevice will be added to linking list. However, driver missed checking them when constructing llvm-link commands and "--only-needed" flag was missed in such scenario. This patch adds them to driver's check list for libdevice.
Signed-off-by: jinge90 <ge.jin@intel.com>
> [SYCL][Driver] Fix "only-needed" flag missing in SYCL AOT

- sycl/source/detail/event_impl.cpp
- sycl/source/detail/memory_manager.cpp
- sycl/source/detail/pi.cpp
- sycl/source/detail/queue_impl.cpp
- sycl/source/detail/queue_impl.hpp
- sycl/source/detail/scheduler/commands.cpp
- sycl/source/detail/xpti_registry.cpp
- sycl/source/detail/xpti_registry.hpp
Note: not all xptiTraceEnabled usages were replaced, in some cases it has no sense.
> [SYCL][XPTI] Use xptiTraceEnabled version with filter 

- .github/workflows/sycl_nightly.yml
I plan to add automatic "lastest-good-nightly" release to it, we need to extend the testing for that.
> [CI] Enable End-to-End tests in Nightly task

- .github/CODEOWNERS
have @intel/syclcompat-lib-reviewers own:
sycl/include/syclcompat/
sycl/doc/syclcompat/
sycl/unittests/syclcompat/
sycl/cmake/modules/AddSYCLLibraryUnitTest.cmake
sycl/include/syclcompat.hpp
which equates to
sycl/**/syclcompat/ @intel/syclcompat-lib-reviewers
sycl/cmake/modules/AddSYCLLibraryUnitTest.cmake @intel/syclcompat-lib-reviewers
sycl/include/syclcompat.hpp @intel/syclcompat-lib-reviewers
> [SYCL][CODEOWNERS] update CODEOWNERS for syclcompat library 

- mlir/include/mlir/Dialect/LLVMIR/LLVMIntrinsicOps.td
- mlir/test/Target/LLVMIR/Import/intrinsic.ll
- mlir/test/Target/LLVMIR/llvmir-intrinsics.mlir
Define `llvm.intr.var.annotation`, `llvm.intr.ptr.annotation` and `llvm.intr.annotation` in the `llvm` dialect as `llvm.var.annotation`, `llvm.ptr.annotation` and  `llvm.annotation` counterparts.
> [mlir][llvm] Define annotation intrinsics

- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLHostOps.td
- mlir-sycl/lib/Dialect/SYCL/IR/SYCLHostOps.cpp
Define the memory effects of the `sycl.host.constructor` operation. For now, optimistically it is assumed that any memory (pointer or memref) argument, except for the `this` pointer, will be only be read.
> [SYCL-MLIR] Define mem effects of host constructor

- polygeist/tools/cgeist/Test/Verification/sycl/host_raising.cpp
- sycl/include/sycl/detail/defines_elementary.hpp
- sycl/include/sycl/handler.hpp
Annotate arguments to make it easier to track them when raising.
> [SYCL-MLIR] Annotate handler::parallel_for arguments

- .github/workflows/sycl_detect_changes.yml
- .github/workflows/sycl_nightly.yml
This reverts commit 6b7424349ee3592909afde25f9921c4e8b83db10.
Needs adjustments in E2E-testing performed on the build as that has been enabled since #9850. Also, disable E2E on nightly in pre-commit as that requires an image with all plugins enabled.
> Revert "[CI] Enable HIP/CUDA/ESIMD plugins in nightly build (#9850)"

- sycl/doc/extensions/experimental/sycl_ext_oneapi_device_architecture.asciidoc
Update the description of the limitations in the
"sycl_ext_oneapi_device_architecture" extension.  The newly added host APIs in that extension do not have the same restrictions as the `if_architecture_is` function.
> [SYCL][Doc] Update restrictions in extension

- sycl/doc/GetStartedGuide.md
See https://github.com/intel/llvm/issues/10278 as well.
> [SYCL][Doc] Update link to the dependencies config file

- sycl/include/sycl/stream.hpp
`global_buffer` target is deprecated in SYCL 2020 in favor of `device`.
`isPlaceholder` template argument defaults to `false` and ignored in SYCL 2020.
> [SYCL][NFC] Modernize use of accessor in stream

- sycl/doc/extensions/experimental/sycl_ext_oneapi_device_architecture.asciidoc
- sycl/include/sycl/ext/oneapi/experimental/device_architecture.hpp
- sycl/source/detail/device_info.hpp
This patch combines ADL-S and RPL-S architectures for
sycl_ext_oneapi_device_architecture extension. These 
two architectures are the same.
Fixes https://github.com/intel/llvm/issues/10184
> [SYCL] Combine ADL-S and RPL-S architectures

- polygeist/lib/Dialect/Polygeist/Analysis/ReachingDefinitionAnalysis.cpp
- polygeist/test/polygeist-opt/reachingDefinitions.mlir
Extend the existing reaching definition analysis to also analyze values with type `!llvm.ptr`.
> [SYCL-MLIR] Extend reaching definition analysis to LLVM pointer

- mlir/test/Target/LLVMIR/llvmir-intrinsics.mlir
Remove `@threadlocal_test` introduced by downstream commit 11d19d5, keeping the test with the same name introduced by upstream commit df37e22.
> [SYCL-MLIR][NFC] Remove duplicated test

- sycl/test-e2e/Basic/fpga_tests/fpga_latency_control_lsu.cpp
- sycl/test-e2e/Basic/fpga_tests/fpga_lsu.cpp
This patch fixes compilation error in fpga_lsu.cpp and fpga_latency_control_lsu.cpp. Tested locally with open-source and closed-source compilers.
Currently there is no external testing with the accelerator device in open source.
> [SYCL] Update some SYCL FPGA tests after https://github.com/intel/llvm/pull/8874

- .github/workflows/sycl_linux_build_and_test.yml
- .github/workflows/sycl_macos_build_and_test.yml
LLVM's in-tree LLVM_CCACHE_BUILD=ON is deprecated - https://discourse.llvm.org/t/llvm-ccache-build-is-deprecated/68431
I wasn't able to make CMake/ccache work by using `ccache`'s arguments in the `CMAKE_CXX_COMPILER_LAUNCHER` with it failing like this:
```
"ccache --dir /__w/llvm/build_cache_sprod_shared --max-size 8G" /opt/sycl/bin/clang++ -DENABLE_OPAQUE_POINTERS=1 ...
/bin/sh: 1: ccache --dir /__w/llvm/build_cache_sprod_shared --max-size 8G: not found
```
so I decided to use environment variables to control that behavior instead.
Resolves #8336.
> [CI] Use CMAKE_*_COMPILER_LAUNCHER for ccache configuration

- .github/workflows/sycl_linux_build_and_test.yml
Sparse checkout is fast enough but allows testing CI changes as it doesn't need image update that way.
> [CI] Checkout devops/actions instead of copying from docker image

- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLTypes.td
- mlir-sycl/test/Dialect/SYCL/types.mlir
- polygeist/lib/Dialect/Polygeist/Transforms/SYCLRaiseHost.cpp
- polygeist/test/polygeist-opt/sycl/sycl-raise-host.mlir
Add field to indicate sub-buffer to SYCL dialect buffer type and detect if a `sycl::buffer` constructed in host code is a sub-buffer of another buffer.
> [SYCL-MLIR] Detect construction of sub-buffers

- sycl/include/sycl/accessor.hpp
- sycl/test/basic_tests/accessor/accessor_default_ctor.cpp
According to SYCL2020 default constructor for empty accessor shouldn't create a placeholder.
> [SYCL] Small fix for accessor default constructor

- .github/workflows/linux_single_e2e.yml
- devops/actions/cached_checkout/action.yml
We run Build/E2E tasks under different users on our amdgpu runners resulting in errors reusing the same cache under both. Separate the caches to resolve those.
> [CI] Use separate repo cache for E2E tests checkout

- sycl/.gitignore
We used to generate two header files to source directory, so .gitignore
file protected developers from committing auto-generated files.
https://github.com/intel/llvm/commit/f3b5fad81fb3291737b3c3550e0dd41e032eda20
changed the directory for emitted files from source to build. Now we
don't need this .gitignore file anymore.
> [SYCL][NFC] Remove outdated .gitignore file for SYCL library

- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLHostOps.td
- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLHostTraits.h
- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLOps.h
- mlir-sycl/lib/Dialect/SYCL/IR/CMakeLists.txt
- mlir-sycl/lib/Dialect/SYCL/IR/SYCLHostTraits.cpp
- polygeist/include/mlir/Dialect/Polygeist/Transforms/Passes.td
- polygeist/lib/Dialect/Polygeist/Transforms/SYCLRaiseHost.cpp
- polygeist/test/polygeist-opt/sycl/sycl-raise-host.mlir
- polygeist/tools/cgeist/Test/Verification/sycl/raising/host_raising_index.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/raising/host_raising_nd_range.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/raising/host_raising_range.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/raising/host_raising_range_offset.cpp
Detect arguments specifying the nd-range of a `parallel_for` invocation.
Raising of calls receiving an `nd_range` fail to be raised as we are not yet raising such constructors. Raising of calls receiving both the global size and an offset fail because we cannot detect the constructor. We will need to implement a pattern raising `nd_range` constructors to fix the former and use `ReachingDefinitionAnalysis` in the pattern implemented by this commit to fix the later.
We also define the `SYCLHostHandlerOp` to be able to find `sycl::handler` instances in a function easily.
> [SYCL-MLIR] Raise `sycl.handler.set_nd_range` constructs

- clang/lib/Driver/ToolChains/Clang.cpp
- clang/test/Driver/sycl-spirv-ext.c
SPIR-V Spec change is here: https://github.com/KhronosGroup/SPIRV-Registry/pull/179
This support is now ready to be turned on by default in the clang driver.
Thanks
> [SPIR-V][Driver] Turn on SPV extension SPV_INTEL_fpga_latency_control in the clang driver

- polygeist/lib/Dialect/Polygeist/Transforms/SYCLRaiseHost.cpp
- polygeist/test/polygeist-opt/sycl/sycl-raise-host.mlir
On the host, the body type of the accessor currently has no relevance for the analyses. However, leaving the body types empty leads to problems when parsing an MLIR file containing such an accessor type with empty body type list. Therefore, simply put `!llvm.void` for now.
> [SYCL-MLIR] Avoid empty body in accessor raising

- polygeist/include/mlir/Dialect/Polygeist/Analysis/SYCLIDAndRangeAnalysis.h
- polygeist/lib/Dialect/Polygeist/Analysis/CMakeLists.txt
- polygeist/lib/Dialect/Polygeist/Analysis/SYCLIDAndRangeAnalysis.cpp
- polygeist/test/lib/Dialect/Polygeist/CMakeLists.txt
- polygeist/test/lib/Dialect/Polygeist/TestIDAndRangeAnalysis.cpp
- polygeist/test/polygeist-opt/sycl/id-range-analysis.mlir
- polygeist/tools/polygeist-opt/polygeist-opt.cpp
MLIR analysis to infer properties of interest about instances of `sycl::id` or `sycl::range` from their construction in host code.
> [SYCL-MLIR] SYCL 'id' and 'range' analysis

- sycl/plugins/unified_runtime/ur/adapters/cuda/platform.cpp
Currently if `cuInit` fails while getting platforms it returns UR_RESULT_SUCCESS. Instead we use `UR_CHECK_ERROR` to return the correct error code.
> [PI][UR] Report error from cuInit

- devops/containers/ubuntu2204_base.Dockerfile
- devops/containers/ubuntu2204_build.Dockerfile
That is needed so that we can use that user for our E2E testing on AMD GPU same as we do on other platforms.
> [CI][Containers] Add sycl user to irc group

- sycl/plugins/unified_runtime/ur/adapters/hip/enqueue.cpp
fixes a post commit failure for hip porting [PR](https://github.com/intel/llvm/pull/9617)
> [SYCL][UR][HIP] remove unused parameter in ur hip

- .github/workflows/sycl_precommit.yml
- devops/actions/cached_checkout/action.yml
By default cached_checkout merges latest origin/sycl resulting in race condition between Build/E2E tasks. Fix it by setting it to the same specific commit hash (target branch head at the task start).
> [CI] Fix merge commit for build/e2e-tests in pre-commit

- sycl/include/sycl/detail/assert_happened.hpp
- sycl/include/sycl/queue.hpp
- sycl/source/detail/queue_impl.hpp
- sycl/source/queue.cpp
Reverts intel/llvm#10341
This change breaks post-commit checks in no-assertion configuration.
> Revert "[NFC][SYCL] Remove assert related code when NDEBUG is set"

- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLOps.td
- mlir-sycl/lib/Dialect/SYCL/IR/SYCLOps.cpp
- mlir-sycl/test/Dialect/SYCL/canonicalize.mlir
Fold constructors receiving all constant 0 values (`sycl.id.constructor(%c0...) : (index...) -> ...`) to the default constructor (`sycl.id.constructor() : () -> ...`).
> [SYCL-MLIR] Define `sycl.id.constructor` fold mechanism

- polygeist/lib/Dialect/Polygeist/Transforms/SYCLRaiseHost.cpp
- polygeist/test/polygeist-opt/sycl/sycl-raise-host.mlir
- polygeist/tools/cgeist/Test/Verification/sycl/raising/failing_host_raising_constructors.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/raising/host_raising_constructors.cpp
Raise `nd_range` constructor to `sycl.host.constructor`. This may involve allocating each argument of the constructor if the `range` and `id` instances are optimized-away.
> [SYCL-MLIR] Raise `nd_range` constructor

- sycl/plugins/unified_runtime/ur/adapters/cuda/command_buffer.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/common.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/common.hpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/context.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/device.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/enqueue.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/event.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/kernel.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/memory.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/queue.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/sampler.cpp
This was preventing out-of-tree build of the adapter for standalone use with unified runtime.
> [SYCL][CUDA] Remove SYCL dependencies from CUDA UR adapter

- .github/workflows/sycl_linux_gen12_exp.yml
This is needed to ease experiments/debugging required for transitioning CI from GEN9 to GEN12 runners.
> [CI] Add workflow to run E2E tests on GEN12

- .github/workflows/sycl_linux_gen12_exp.yml
Empty value in the variable matches everything and results in no tests being run. Instead, change the input parameter to `env` and use default value to make its update easier.
> [CI] Don't use LIT_FILTER_OUT in sycl_linux_gen12_exp.yml

- sycl/include/sycl/ext/oneapi/properties/property_utils.hpp
Include only what you use i.e. algorithm in our case.
> [SYCL][NFC] Don't include the whole mp11 library

- devops/actions/khronos_cts_test/action.yml
Most uses were replaced in https://github.com/intel/llvm/pull/10314 but khronos_ct_test/action.yml was missed because it's not enabled anywhere.
> [CI] Remove last usage of "cp -r /actions"

- devops/containers/ubuntu2204_build.Dockerfile
Those are not used after https://github.com/intel/llvm/pull/10314 and https://github.com/intel/llvm/pull/10387.
> [CI] Don't put devops/actions/* into the docker images

- .github/workflows/sycl_nightly.yml
Github's runner doesn't have enough space to build nightly.build image.
> [CI] Use self-hosted runner for containers builds

- .github/workflows/sycl_precommit_linux.yml
- .github/workflows/sycl_precommit_windows.yml
That would allow individual cancel/restart. It result in duplication of several auxiliary tasks (detect_changes/lint/matrix_generation) but those are very fast, and the overhead should be acceptable.
> [CI] Split pre-commit task into separate Linux/Windows

- sycl/include/std/experimental/simd.hpp
- sycl/include/sycl/detail/spirv.hpp
- sycl/include/sycl/ext/intel/esimd/detail/bfloat16_type_traits.hpp
- sycl/include/sycl/ext/intel/esimd/detail/elem_type_traits.hpp
- sycl/include/sycl/ext/intel/esimd/detail/half_type_traits.hpp
- sycl/include/sycl/ext/intel/esimd/detail/region.hpp
- sycl/include/sycl/ext/intel/esimd/detail/simd_mask_impl.hpp
- sycl/include/sycl/ext/intel/esimd/detail/sycl_util.hpp
- sycl/include/sycl/ext/intel/esimd/detail/tfloat32_type_traits.hpp
- sycl/include/sycl/ext/intel/esimd/detail/types.hpp
- sycl/include/sycl/ext/intel/esimd/detail/types_elementary.hpp
- sycl/include/sycl/ext/oneapi/kernel_properties/properties.hpp
- sycl/include/sycl/ext/oneapi/properties/property_utils.hpp
`inline` is implicitly applied to constexpr functions and constexpr
static data members. This change aims to align the style across the
code, where implied inline is not spelled.
> [SYCL][NFC] Remove explicit inline when implied.

- sycl/include/sycl/ext/oneapi/sub_group_mask.hpp
sub_group_mask.hpp uses CHAR_BIT defined in climits header
> [SYCL][NFC] Add missing climits include

- sycl/doc/design/PluginInterface.md
- sycl/include/sycl/detail/pi.def
- sycl/include/sycl/detail/pi.h
- sycl/plugins/cuda/pi_cuda.cpp
- sycl/plugins/esimd_emulator/pi_esimd_emulator.cpp
- sycl/plugins/hip/pi_hip.cpp
- sycl/plugins/level_zero/pi_level_zero.cpp
- sycl/plugins/opencl/pi_opencl.cpp
- sycl/plugins/unified_runtime/pi2ur.hpp
- sycl/plugins/unified_runtime/pi_unified_runtime.cpp
- sycl/source/detail/program_impl.cpp
- sycl/source/detail/program_impl.hpp
- sycl/test/abi/pi_level_zero_symbol_check.dump
- sycl/test/abi/pi_opencl_symbol_check.dump
- sycl/unittests/helpers/PiMockPlugin.hpp
This patch removes the OpenCL specific, and deprecated, entry-point
`piclCreateProgramWithSource`. This change is being made in preparation
for porting the OpenCL plugin to Unified Runtime which does not intend
to support compilation from source directly, instead this should be
performed using OpenCL specific interop via native handles.
> [SYCL][ABI-Break][PI] Remove deprecated piclCreateProgramWithSource

- sycl/test-e2e/Basic/multisource_spv_obj.cpp
The functionality of -fsycl-device-obj allows for users to specify if their generated fat object will contain LLVM-IR or SPIR-V based device binaries.  Leverage the existing multisource.cpp test, augmenting it to use -fsycl-device-obj in various manners when generating the fat objects.
> [NFC][SYCL] Add test to exercise -fsycl-device-obj

- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLOps.td
- mlir-sycl/lib/Dialect/SYCL/IR/SYCLOps.cpp
- mlir-sycl/test/Dialect/SYCL/canonicalize.mlir
Define pattern dropping `offset` argument if it has been default constructed and not modified afterwards, i.e., transform the following pattern:
```mlir
%off = sycl.id.constructor() : () -> memref<?x!sycl_id_X_>
sycl.nd_range.constructor(%gs, %ls, %off)
: (memref<?x!sycl_range_X_>,
memref<?x!sycl_range_X_>,
memref<?x!sycl_id_X_>)
-> memref<?x!sycl_nd_range_X_>
```
into:
```mlir
sycl.nd_range.constructor(%gs, %ls)
: (memref<?x!sycl_range_X_>, memref<?x!sycl_range_X_>)
-> memref<?x!sycl_nd_range_X_>
```
> [SYCL-MLIR] Define `sycl.nd_range.constructor` canonicalization pattern

- .github/workflows/sycl_post_commit.yml
- .github/workflows/sycl_precommit_windows.yml
For post-commit it would start the entire task whenever the branch is updated. For windows pre-commit it would allow the temporary workaround of creating a fake PR into that branch to trigger Windows pre-commit task (same as was done in #10434)
SYCL Nightly doesn't have "push:" trigger and it has a bug with pushing the containers even for branches that aren't "origin/sycl" so not changing it for now.
> [CI] Allow llvmspirv_pulldown branch in pre-/post-commit triggers

- sycl/include/sycl/queue.hpp
> [SYCL][NFC] Define function in a header as inline

- sycl/include/CL/__spirv/spirv_vars.hpp
- sycl/include/sycl/atomic.hpp
- sycl/include/sycl/atomic_fence.hpp
- sycl/include/sycl/detail/common.hpp
- sycl/include/sycl/detail/os_util.hpp
- sycl/include/sycl/ext/intel/esimd/detail/util.hpp
- sycl/include/sycl/group.hpp
- sycl/include/sycl/reduction.hpp
- sycl/include/sycl/stream.hpp
For member functions inline which are defined in class scope inline is
implicit and can be dropped.
For free functions static causes compiler to duplicate the body of the
function when the function is not inlined and linked with another TU
defining the same function. Using inline in this case allows compiler to
merge definitions from different TU and avoid code bloat.
> [SYCL][NFC] Clean-up usage of "static inline" functions

- .github/workflows/sycl_precommit_linux.yml
It has to be opt-in and the feature needs redesign.
> [CI] Remove support for running E2E tests on nightly builds

- sycl/plugins/unified_runtime/ur/adapters/level_zero/memory.cpp
Synchronization is done with the event. No need to add the barrier as extra synchronization point.
> [SYCL][UR][L0] Remove non-necessary barrier after copyRegion

- llvm-spirv/lib/SPIRV/SPIRVRegularizeLLVM.cpp
IGC has some issues with reverse translation of SPIR-V builtins resulting from code compiled with opaque pointers enabled. To enable opaque pointers to be enabled for offloaded code before the new driver version is propagated to CI, this change is temporarily necessary to ensure we have test coverage.
> [SPIR-V][OpaquePointers] Temporary workaround for IGC issue.

- polygeist/include/mlir/Dialect/Polygeist/Analysis/SYCLIDAndRangeAnalysis.h
- polygeist/lib/Dialect/Polygeist/Analysis/SYCLIDAndRangeAnalysis.cpp
- polygeist/test/polygeist-opt/sycl/id-range-analysis.mlir
The analysis infers an all-zeroes constant id when it runs into the default constructor and propagates information inferred for the input argument for the copy constructor.
> [SYCL-MLIR] Handle default and copy constructors in `SYCLIDAndRangeAnalysis`

- polygeist/lib/Dialect/Polygeist/Transforms/SYCLRaiseHost.cpp
- polygeist/test/polygeist-opt/sycl/sycl-raise-host.mlir
During raising of the host code, detect whether a constructed accessor requires the range and offset parameter.
> [SYCL-MLIR] Detect accessor range and offset

- sycl/test-e2e/InvokeSimd/Regression/ImplicitSubgroup/call_vadd_1d_loop_naive.cpp
Follow-up for #10409 that disabled
InvokeSimd/Regression//call_vadd_1d_loop_naive.cpp but missed InvokeSimd/Regression/ImplicitSubgroup/call_vadd_1d_loop_naive.cpp.
See also https://github.com/intel/llvm/issues/10369.
> [SYCL][E2E] Disable a test that causes hangs on Linux GEN12

- sycl/plugins/unified_runtime/pi2ur.hpp
Fix piextKernelSetArgPointer to forward the call to the correct UR entrypoint.
> [SYCL][PI] Fix piextKernelSetArgPointer

- sycl/test-e2e/ESIMD/api/replicate_smoke.cpp
- sycl/test-e2e/ESIMD/local_accessor_block_load_store.cpp
- sycl/test-e2e/ESIMD/local_accessor_gather_scatter.cpp
- sycl/test-e2e/ESIMD/local_accessor_gather_scatter_rgba.cpp
- sycl/test-e2e/InlineAsm/asm_float_imm_arg.cpp
- sycl/test-e2e/Regression/commandlist/gpu.cpp
See also https://github.com/intel/llvm/issues/10369.
> [SYCL][E2E] Disable tests that fail on Linux GEN12 runners

- sycl/include/CL/__spirv/spirv_ops.hpp
- sycl/include/CL/__spirv/spirv_types.hpp
- sycl/include/sycl/backend_types.hpp
- sycl/include/sycl/context.hpp
- sycl/include/sycl/detail/aligned_allocator.hpp
- sycl/include/sycl/detail/common.hpp
- sycl/include/sycl/detail/common_info.hpp
- sycl/include/sycl/detail/util.hpp
- sycl/include/sycl/device.hpp
- sycl/include/sycl/device_selector.hpp
- sycl/include/sycl/event.hpp
- sycl/include/sycl/exception.hpp
- sycl/include/sycl/exception_list.hpp
- sycl/include/sycl/ext/oneapi/experimental/graph.hpp
- sycl/include/sycl/ext/oneapi/experimental/group_helpers_sorters.hpp
- sycl/include/sycl/handler.hpp
- sycl/include/sycl/kernel.hpp
- sycl/include/sycl/platform.hpp
- sycl/include/sycl/properties/buffer_properties.hpp
- sycl/include/sycl/queue.hpp
- sycl/include/sycl/reduction.hpp
- sycl/include/sycl/stl.hpp
- sycl/source/detail/os_util.cpp
- sycl/source/detail/persistent_device_code_cache.cpp
- sycl/source/detail/sampler_impl.hpp
- sycl/unittests/config/ConfigTests.cpp
- sycl/unittests/kernel-and-program/PersistentDeviceCodeCache.cpp
I tried to remove as much as possible unnecessary includes from sycl/queue.hpp. While I was looking at the headers included into queue.hpp, I cleaned-up their includes as well. For instance, I noticed that we abuse stl.hpp file, which is intended to extend STL functionality rather than to be a common file to include a bunch of STL headers.
Another thing we should do in the future is to re-organize the "info descriptors" header, which today includes descriptors for all SYCL classes. For instance, there is not possible to include only device info descriptors.
> [SYCL][NFC] Clean-up includes in DPC++ headers

- .github/workflows/sycl_detect_changes.yml
Github APIs used by dorny/paths-filter limit the list of changed files so we can't reliable detect the changes when many files are changed. As such, treat those as changing everything. Note that 500 is much less than GH's limit which is around 3000.
> [CI] Treat PRs touching 500+ files as changing everything

- sycl/plugins/unified_runtime/ur/adapters/level_zero/event.hpp
As previously committed in:
https://github.com/intel/llvm/commit/dbde93f8eb96d6c7b29e2386aac7a7cd64aef84d
> [SYCL][UR][L0] Correct default for SYCL_PI_LEVEL_ZERO_FILTER_EVENT_WAIT_LIST

- llvm/include/llvm/IR/Intrinsics.h
- llvm/include/llvm/IR/Intrinsics.td
- llvm/lib/IR/Function.cpp
https://github.com/intel/llvm/commit/253a52988fe37887ba1f7741271d602083fe7dd7 Remove LLVMPointerTo intrinsic type
To fix build failure in vc-intrinsics-src , Guard it with INTEL_SYCL_OPAQUEPOINTER_READY : 
```
./sycl-web/builds/_deps/vc-intrinsics-src/GenXIntrinsics/lib/GenXIntrinsics/GenXIntrinsics.cpp:340:23: 
error: ‘PtrToArgument’ is not a member of ‘llvm::Intrinsic::IITDescriptor’
340 |   case IITDescriptor::PtrToArgument: {
|               
```
> Guard "[IR] Remove LLVMPointerTo intrinsic type (NFC)" with INTEL_SYCL_OPAQUEPOINTER_READY

- sycl/plugins/unified_runtime/ur/adapters/cuda/image.cpp
- Fixed compiler errors/warnings related to unused and uninitialized variables and parameters.
Post-commit fix for PR: https://github.com/intel/llvm/pull/10112
> [SYCL][Bindless] Fix compiler Werrors

- sycl/test-e2e/FilterSelector/filter_list_cpu_gpu_acc.cpp
- sycl/test-e2e/FilterSelector/select_device.cpp
- sycl/test-e2e/FilterSelector/select_device_acc.cpp
- sycl/test-e2e/FilterSelector/select_device_cpu.cpp
- sycl/test-e2e/FilterSelector/select_device_cuda.cpp
- sycl/test-e2e/FilterSelector/select_device_level_zero.cpp
- sycl/test-e2e/FilterSelector/select_device_opencl.cpp
Needed to properly handle run_launcher.
> [SYCL][E2E] Use %{run*} placeholder in tests

- sycl/include/sycl/async_handler.hpp
- sycl/include/sycl/backend_types.hpp
- sycl/include/sycl/buffer.hpp
- sycl/include/sycl/context.hpp
- sycl/include/sycl/detail/common.hpp
- sycl/include/sycl/detail/impl_utils.hpp
- sycl/include/sycl/detail/info_desc_helpers.hpp
- sycl/include/sycl/detail/owner_less_base.hpp
- sycl/include/sycl/detail/property_helper.hpp
- sycl/include/sycl/detail/property_list_base.hpp
- sycl/include/sycl/detail/stl_type_traits.hpp
- sycl/include/sycl/device.hpp
- sycl/include/sycl/device_selector.hpp
- sycl/include/sycl/exception_list.hpp
- sycl/include/sycl/ext/oneapi/experimental/device_architecture.hpp
- sycl/include/sycl/ext/oneapi/experimental/graph.hpp
- sycl/include/sycl/info/info_desc.hpp
- sycl/include/sycl/property_list.hpp
- sycl/include/sycl/queue.hpp
- sycl/source/detail/config.hpp
- sycl/source/detail/posix_pi.cpp
- sycl/source/detail/program_manager/program_manager.cpp
- sycl/source/detail/sampler_impl.hpp
- sycl/source/detail/sycl_mem_obj_t.hpp
The main goal of this refactoring is to reduce amount of includes to the context.hpp header.
Two new includes are added:
1. sycl/include/sycl/detail/impl_utils.hpp is intended to replace sycl/include/sycl/detail/common.hpp when only interopability with "impl" class is needed. common.hpp include is overloaded with a bunch of other functionality.
2. sycl/include/sycl/async_handler.hpp separates async_handler definiton from exception.hpp.
> [SYCL][NFC] Refactor includes in DPC++ headers

- sycl/plugins/esimd_emulator/pi_esimd_emulator.cpp
- sycl/plugins/opencl/pi_opencl.cpp
This adds references to unused function parameters to avoid build errors.
> [SYCL] Fix unreferenced parameters

- .github/workflows/sycl_detect_changes.yml
- .github/workflows/sycl_nightly.yml
This effectively reverts commit 5c10c73b1174afe887a282e6f650d364d51b6b40.
> [CI] Enable HIP/CUDA/ESIMD plugins in nightly build, 2nd attempt

- polygeist/lib/Dialect/Polygeist/Transforms/ArgumentPromotion.cpp
- polygeist/test/polygeist-opt/sycl/argpromotion_privatize.mlir
We found a blocker for the LoopInternalization pass. We need to prove that the loop it needs to optimize is uniform. Uniformity analysis fails to prove that an argument passed to the kernel body function is uniform because the gpu.func kernel calls a wrapper function which does not have private linkage. The analysis assumes there may be other unknown calls to that function, and so it needs to assume that some unknown caller may pass a non-uniform argument.
> [SYCL-MLIR][ArgumentPromotion] Privatize kernel wrapper

- polygeist/include/mlir/Dialect/Polygeist/Analysis/SYCLAccessorAnalysis.h
- polygeist/lib/Dialect/Polygeist/Analysis/CMakeLists.txt
- polygeist/lib/Dialect/Polygeist/Analysis/SYCLAccessorAnalysis.cpp
- polygeist/test/lib/Dialect/Polygeist/CMakeLists.txt
- polygeist/test/lib/Dialect/Polygeist/TestAccessorAnalysis.cpp
- polygeist/test/polygeist-opt/sycl/accessor-analysis.mlir
- polygeist/tools/polygeist-opt/polygeist-opt.cpp
MLIR analysis to infer properties of interest about instances of `sycl:accessor` from their construction in host code.
This also includes the ability to query two accessor for their potential aliasing behavior.
> [SYCL-MLIR] SYCL 'accessor' analysis

- clang/include/clang/Driver/Options.td
- clang/test/Driver/sycl-deprecated.cpp
- clang/test/Driver/sycl-offload-with-split.c
- clang/test/Driver/sycl-offload.c
- clang/test/Driver/sycl.c
- sycl/doc/UsersManual.md
The -fsycl-device-obj option replaces the -fsycl-use-bitcode option. The -fsycl-use-bitcode option is deprecated as well.  Update the documentation to reflect this fact, also update any testing using the older option with a replacement of the new option.
The use of -fsycl-use-bitcode should also emit the proper deprecation message when used on the command line.
> [SYCL][doc][NFC] Update doc and usage of -fsycl-device-obj

- .github/workflows/sycl_detect_changes.yml
We've removed support for E2E tests on nightly compiler/image in pre-commit, so these aren't used anymore.
> [CI][NFC] Remove dead code from sycl_detect_changes.yml

- sycl/doc/extensions/proposed/sycl_ext_oneapi_bindless_images.asciidoc
Made the bindless image sampler member names snake case to match SYCL convention.
> [SYCL][Doc] Bindless images proposal name fix

- polygeist/lib/Dialect/Polygeist/Transforms/SYCLRaiseHost.cpp
- polygeist/test/polygeist-opt/sycl/sycl-raise-host.mlir
The insight here is that the `get_access` method basically looks like a constructor call/invoke at the IR level, hence the existing raising pattern apply.
> [SYCL-MLIR] Raise `sycl::buffer::get_access` to a host constructor.

- polygeist/tools/cgeist/Lib/CGCall.cc
- polygeist/tools/cgeist/Test/CMakeLists.txt
- polygeist/tools/cgeist/Test/Verification/builtin.cpp
Lower __builtin_bswap* to the llvm ByteSwap op.
> [SYCL-MLIR][Polygeist] Support bswap builtin lowering

- clang/lib/Driver/Driver.cpp
Warnings seen from using a deprecated function and string usage.  Clean these up.
> [Driver][NFC] Cleanup warnings seen during the build

- sycl/test-e2e/Tracing/usm/queue_copy_released_pointer.cpp
- sycl/test-e2e/Tracing/usm/queue_single_task_nullptr.cpp
- sycl/test-e2e/Tracing/usm/queue_single_task_released_pointer.cpp
We might get different path (eg: without /) in different test env
Remove the "/" to avoid noise.
> sycl-in-tree: Allow different patch in usm testcases

- .github/workflows/linux_single_e2e.yml
- devops/scripts/install_drivers.sh
I plan to update other tasks to make use of the functionality separately.
> [CI] Implement driver update logic directly in linux_single_e2e.yml

- .github/workflows/sycl_nightly.yml
This effectively reverts changes made by
8d07b4de7c1dc867c647d751eb2ed532835299fd. The suffix was added to handle
collision between two jobs producing build artifacts. The job causing
this conflict was removed by 5504c74a5a58974844cbc2ebf2d46451614b9dca,
so suffix is not needed anymore.
> [CI][NFC] Remove idle build artifact suffix.

- sycl/doc/GetStartedGuide.md
We used to copy LLVM's requirements for the host compiler in our Get Started Guide, but it's easy to miss the updates in LLVM project requirements. This patch removes the duplication and links LLVM's up-to-date documentation.
> [SYCL][Doc] Update DPC++ prerequisites

- sycl/include/sycl/detail/defines_elementary.hpp
- sycl/source/detail/config.cpp
The only real use of the macro is in config.cpp file. The macro was used
in sycl/detail/common.hpp, but the use is commented out.
> [SYCL][NFC] Move __SYCL_STRINGIFY definition from headers

- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLHostOps.td
- mlir-sycl/lib/Dialect/SYCL/IR/SYCLOps.cpp
- mlir-sycl/test/Dialect/SYCL/host.mlir
- mlir-sycl/test/Dialect/SYCL/invalid.mlir
This operation represents the submission of a SYCL kernel (`sycl::queue::submit`). In addition to the function implementing the CGF, this operation receives the values captured (by reference) by this.
Example:
```mlir
sycl.host.submit %queue([%buff_a, %buff_b]@kernels::@k0) -> %event
: !llvm.ptr, !llvm.ptr, !llvm.ptr, !llvm.ptr
```
> [SYCL-MLIR] Define `sycl.host.submit` operation

- sycl/doc/extensions/proposed/sycl_ext_oneapi_complex.asciidoc
- sycl/include/sycl/ext/oneapi/experimental/sycl_complex.hpp
- sycl/test/extensions/test_complex.cpp
Reverts intel/llvm#9819
As mentioned in the PR https://github.com/intel/llvm/pull/9867, this introduction of literal operators creates some issues due to literal operators receiving arguments as `long double` which are not supported on device code (and only works on host side); and our worries that users will try to use it and will not understand why it does not work.
Also, user-defined literal operators should be declared with a `_` prefix to not clash with the standard literal operators when `using namespace std::literals`.
Reverting this PR will facilitate the merge of the previously mentioned PR and have a place where the issues from this introduction are listed.
Regardless of this PR, we'd still like to have support for literal operators for complex, so if you (@abagusetty) could …
> Revert "[SYCL] Adds complex Literals support to sycl::experimental::complex"

- sycl/source/detail/builtins_math.cpp
- sycl/test/regression/host_half_nextafter.cpp
Currently the host-side implementation of sycl::nextafter with sycl::half uses the float variant of std::nextafter. However, due to the conversion between half and float, the result may be unexpected. Likewise, https://github.com/KhronosGroup/SYCL-Docs/pull/440 removes the reference to single-precision floating point results.
> [SYCL] Fix nextafter with half on host

- sycl/plugins/native_cpu/CMakeLists.txt
- sycl/plugins/native_cpu/pi_native_cpu.cpp
- sycl/plugins/native_cpu/pi_native_cpu.hpp
- sycl/plugins/unified_runtime/CMakeLists.txt
- sycl/plugins/unified_runtime/pi2ur.hpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/kernel.cpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/common.cpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/common.hpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/context.cpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/context.hpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/device.cpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/device.hpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/enqueue.cpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/event.cpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/kernel.cpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/kernel.hpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/memory.cpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/memory.hpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/platform.cpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/platform.hpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/program.cpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/program.hpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/queue.cpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/queue.hpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/runtime.cpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/sampler.cpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/ur_interface_loader.cpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/usm.cpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/usm_p2p.cpp
This PR refactors the current SYCL Native CPU Implementation as a Unified Runtime adapter.
No new functionalities are added.
Contents of this PR:
- Native CPU implementation divided in multiple source files at `sycl/plugins/unified_runtime/ur/adapters/native_cpu`
- Native CPU PI plugin is now implemented through the `pi2ur.hpp` interface
- _pi_* classes have now an equivalent ur_* class
- `UR_PLATFORM_BACKEND_NATIVE_CPU` value added to `ur2piPlatformInfoValue`
> [SYCL][NATIVECPU] Refactor from PI plugin to UR adapter

- sycl/plugins/unified_runtime/ur/adapters/hip/context.cpp
- sycl/plugins/unified_runtime/ur/adapters/hip/context.hpp
- sycl/plugins/unified_runtime/ur/adapters/hip/device.cpp
- sycl/plugins/unified_runtime/ur/adapters/hip/device.hpp
- sycl/plugins/unified_runtime/ur/adapters/hip/enqueue.cpp
- sycl/plugins/unified_runtime/ur/adapters/hip/event.cpp
- sycl/plugins/unified_runtime/ur/adapters/hip/kernel.cpp
- sycl/plugins/unified_runtime/ur/adapters/hip/memory.cpp
- sycl/plugins/unified_runtime/ur/adapters/hip/platform.cpp
- sycl/plugins/unified_runtime/ur/adapters/hip/program.cpp
- sycl/plugins/unified_runtime/ur/adapters/hip/queue.cpp
- sycl/plugins/unified_runtime/ur/adapters/hip/usm.cpp
The primary context has been default for a while in CUDA PI/Adapter. See https://github.com/intel/llvm/pull/8197. 
This PR brings the HIP adapter up to speed.
It also changes the scoped context to only take a `ur_device_handle_t` since this is coupled with a native primary context in HIP
> [HIP][UR] Use primary context in HIP adapter

- .github/CODEOWNERS
HIP plugin codeownership currently falls to L0 reviewers. A more appropriate group for owning this plugin is the CUDA plugin maintainers. In the future we can consider splitting the ownership or rename the CUDA reviewers group to encapsulate both.
> [SYCL] Fix HIP plugin codeowners

- sycl/test-e2e/Matrix/XMX8/element_wise_abc.cpp
- sycl/test-e2e/Matrix/element_wise_abc.cpp
- sycl/test-e2e/Matrix/element_wise_abc_impl.hpp
Add new test for multiple elem-wise ops for different matrix types in the same kernel
> [SYCL][Joint Matrix] Add test for multiple elem-wise ops

- sycl/test-e2e/Matrix/Legacy/joint_matrix_int8_vnni_impl.hpp
- sycl/test-e2e/Matrix/joint_matrix_int8_vnni_impl.hpp
Because of missing required sub_group setting the tests were failing.
The only change is adding "[[intel::reqd_sub_group_size(SG_SZ)]]". The rest is clang-formatting.
> [SYCL][JointMatrix] Added missing required subgroup to VNNI tests

- sycl/test-e2e/Matrix/XMX8/element_wise_all_ops.cpp
- sycl/test-e2e/Matrix/XMX8/element_wise_all_ops_tf32.cpp
- sycl/test-e2e/Matrix/XMX8/element_wise_all_sizes.cpp
- sycl/test-e2e/Matrix/XMX8/joint_matrix_tf32.cpp
- sycl/test-e2e/Matrix/element_wise_all_ops.cpp
- sycl/test-e2e/Matrix/element_wise_all_ops_tf32.cpp
- sycl/test-e2e/Matrix/element_wise_all_sizes.cpp
- sycl/test-e2e/Matrix/joint_matrix_tf32.cpp
Several tests are failing due to ambiguous use of sub_group type. The root cause is using extra unnecessary namespaces.
> [SYCL][JointMatrix] Fix compilation failures due to sub_group change

- sycl/plugins/unified_runtime/ur/adapters/level_zero/event.cpp
- sycl/plugins/unified_runtime/ur/adapters/level_zero/event.hpp
collectEventsForReleaseAndDestroyPiZeEventList is the only
place where mutex is currently used.
This function is always called with event that own the
waitlist mutex taken.
Therefore the mutex is redundant and causes overhead.
With this change we save 2 mutex calls per event cleanup in
in-order-queue scenarios.
This means that when we clean while reaching the
ImmCmdListsEventCleanupThreshold, we save 2000 mutex
taking calls, which improves host overhead.
Once the mutex taking is removed, there are no other code
places where mutex is used, so removing it from codebase.
Signed-off-by: mmrozek <michal.mrozek@intel.com>
> [SYCL][L0] Remove not needed mutex

- .github/workflows/sycl_linux_build_and_test.yml
- .github/workflows/sycl_precommit_linux.yml
- .github/workflows/sycl_windows_build_and_test.yml
Github has a limit of 10 inputs for manually triggered workflows, so
remove anything unused. We can see how can re-enable them back in future,
if it will become needed.
> [CI] Remove unused/always default inputs in *build_and_test.yml

- sycl/plugins/unified_runtime/ur/adapters/cuda/device.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/device.hpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/enqueue.cpp
Cache the max local mem size so that we can call less CUDA driver entry points at `urEnqueueKernelLaunch`. Also allows us to query the value set for `SYCL_PI_CUDA_MAX_LOCAL_MEM_SIZE` using `device.get_info<sycl::info::device::local_mem_size>()`
> [CUDA][UR] Cache the max local mem size

- sycl/include/sycl/marray.hpp
- sycl/include/sycl/multi_ptr.hpp
- sycl/test/warnings/sycl_2020_deprecations.cpp
This PR introduces a fix for the `marray.hpp` and `multi_ptr.hpp` where the trait `std::enable_if` had a typo and thus was not restraining the function depending on the inner condition.
```
std::enable_if<...> // does not restrain
std::enable_if_t<...> or std::enable_if<...>::type // does restrain
```
It also fixes the test of `multi_ptr`, where when the function is called with the correct arguments, the default template argument will be used, and the second template parameter will be deduced as void, not `std::enable_if<true>`
> [SYCL] Fix std::enable_if typo

- sycl/doc/extensions/supported/sycl_ext_oneapi_local_memory.asciidoc
- Fix return type of multi_ptr; Group::address_space does not exist.
- Clarify the constructor behavior for array types.
> [SYCL][Doc] Update sycl_ext_oneapi_local_memory

- sycl/plugins/unified_runtime/ur/ur.cpp
It shadows SYCL_PI_TRACE, so not needed.Tracing at UR level would eventually move to an official UR environment variable,
Resolves: #10178
> [SYCL][UR] Remove UR_L0_TRACE

- .github/workflows/sycl_linux_build_and_test.yml
This PR treats empty matrix inputs same as '[]' in sycl_linux_build_and_test.yml because the latter is generated by the matrix generator yet we can't have that many input parameters for manual trigger. Later PR would move the call to matrix generation into this workflow (replacing 3 input parameters with just one) and would enable E2E/CTS as well.
> [CI] Enable build in manual run for sycl_linux_build_and_test.yml

- sycl/include/sycl/ext/oneapi/experimental/invoke_simd.hpp
- sycl/test/invoke_simd/return-type-struct.cpp
- sycl/test/invoke_simd/struct-arg.cpp
It doesn't work at runtime even if we make it through the compiler because of an IGC issue.
Once the IGC issue is fixed, we will need make some changes to the compiler and then lift this restriction.
> [SYCL][InvokeSimd] Add error for callee with struct return or argument

- sycl/include/sycl/half_type.hpp
half_type.hpp uses uint16_t type without including proper standard
library header.
> [SYCL] Add missing include for uint16_t type

- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLHostOps.td
- mlir-sycl/lib/Dialect/SYCL/IR/SYCLOps.cpp
- mlir-sycl/test/Dialect/SYCL/host.mlir
- mlir-sycl/test/Dialect/SYCL/invalid.mlir
Rationale for annotating the argument list rather than the op's functional type: The optionality of `$range` and `$offset` prevents the use of a custom directive, hence we would need a complete custom parser/printer for the op.
> [SYCL-MLIR] Support optional SYCL type attributes on `schedule_kernel`'s args

- sycl/plugins/unified_runtime/ur/adapters/level_zero/event.cpp
- sycl/plugins/unified_runtime/ur/adapters/level_zero/event.hpp
- sycl/plugins/unified_runtime/ur/adapters/level_zero/queue.cpp
CleanupEventListFromResetCmdList sets the event as completed under mutex.
Then releases the mutex and calls CleanupCompletedEvent.
In this method the same mutex is taken again.
This causes that we take the same mutex twice for every event in
CleanupEventListFromResetCmdList.
This change adds paramter to CleanupCompletedEvent and moves the code
from CleanupEventListFromResetCmdList to CleanupCompletedEvent, which
avoids taking the same mutex twice.
Signed-off-by: mmrozek <michal.mrozek@intel.com>
> [SYCL][L0] Optimize mutex acquisition.

- sycl/test-e2e/KernelAndProgram/level-zero-static-link-flow.cpp
- sycl/test-e2e/Plugin/level_zero_batch_test_copy_with_compute.cpp
- sycl/test-e2e/Plugin/level_zero_dynamic_batch_test.cpp
- sycl/test-e2e/Plugin/level_zero_queue_profiling.cpp
- sycl/test-e2e/Plugin/level_zero_usm_device_read_only.cpp
We use that to run the tests with ZE_DEBUG=6 to avoid unintended interaction with CHECKs in the majority of tests but that also means that tests explicitly requesting ZE_DEBUG=1 can't be executed under such scenario.
> [SYCL][E2] Add "UNSUPPORTED: ze_debug" for some tests

- clang/include/clang/Driver/Options.td
- clang/lib/Driver/ToolChains/Clang.cpp
- clang/test/Driver/sycl-spirv-to-ir-opt.cpp
This is a hidden option and is not intended for use by end users. It has value for local testing and validation of the generated SPIR-V.
This addresses a missed usecase from https://github.com/intel/llvm/pull/9569
> [SYCL][Driver] Add hidden option to specify spirv-to-ir-wrapper flags

- sycl/test-e2e/Regression/commandlist/Inputs/FindPrimesSYCL.cpp
- sycl/test-e2e/Regression/commandlist/gpu.cpp
And re-enable it (was disabled during transition to GEN12 runners).
> [SYCL][E2E] Use float instead of double in Regression/commandlist/gpu.cpp

- sycl/test-e2e/InlineAsm/asm_float_imm_arg.cpp
And re-enable it after the temporary disablement during GEN12 transition.
> [SYCL][E2E] Use float instead of double in InlineAsm/asm_float_imm_arg.cpp

- llvm/test/SYCLLowerIR/ESIMD/global_opaque_ptrs.ll
Update test to remove -opaque-pointers option since it is enabled be default now.
> [NFC][OpaquePtrs] Remove -opaque-pointers option

- sycl/plugins/unified_runtime/CMakeLists.txt
to fix: "'scoped_lock' may not intend to support class template argument deduction [-Werror,-Wctad-maybe-unsupported]"
Ref: https://github.com/oneapi-src/unified-runtime/pull/757
This error showed up after merging: https://github.com/intel/llvm/pull/10269.
> [SYCL][UR] bump UR version

- libdevice/imf/imf_fp32_dl.cpp
- libdevice/imf/imf_fp64_dl.cpp
- libdevice/imf/imf_inline_fp32.cpp
- libdevice/imf/imf_inline_fp64.cpp
- libdevice/imf_utils/integer_misc.cpp
DL framework developers require max/min functions for all data types, this PR group these required functions with other dl required functions which are located in imf_fp32/64_dl.cpp file.
> [SYCL][libdevice] Add max/min for all types to dl specific file

- sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_impl.hpp
Fix for use of non-standard multi_ptr constructors in several Joint Matrix tests exposed by #10297
> [SYCL][Joint Matrix] Resolve non-standard usage of multi_ptr

- sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp
This fixes fallout from https://github.com/intel/llvm/commit/1a5e53216b009177c73dfd6d644a5c016b71b552.
I reordered the template arguments in the review process but missed updating the LSC callsites.
We have tests for this but they don't run in CI. I manually verified the tests pass.
> [ESIMD] Fix LSC APIs that use raw_send

- sycl/test-e2e/Matrix/element_wise_all_ops_impl.hpp
Float type should be used for matrix C and bfloat16 type should be used for matrix A.
Rewritten test like that and refactored to reduce code duplication.
> [SYCL][Joint Matrix] Fix element_wise_all_ops test: use float for matrix C

- sycl/plugins/unified_runtime/pi2ur.hpp
- sycl/plugins/unified_runtime/ur/adapters/level_zero/device.cpp
- sycl/test-e2e/Plugin/level_zero_ext_intel_cslice.cpp
Fix CSLICE partitioning for PVC.
Also, fix level_zero_ext_intel_cslice to correctly test with
and without immediate command list.
Signed-off-by: Jaime Arteaga <jaime.a.arteaga.molina@intel.com>
Signed-off-by: Piotr Balcer <piotr.balcer@intel.com>
Signed-off-by: Fábio Mestre <fabio.mestre@codeplay.com>
> [SYCL][UR] Fix device partition queries (2)

- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLHostOps.td
- mlir-sycl/lib/Dialect/SYCL/IR/SYCLOps.cpp
- mlir-sycl/test/Dialect/SYCL/host.mlir
- mlir-sycl/test/Dialect/SYCL/invalid.mlir
- mlir-sycl/test/Transforms/constant-propagation.mlir
Intent: Prevent the `schedule_kernel` op from being trivially dead when all arguments are read-only, without breaking our reaching definitions analyses.
> [SYCL-MLIR] Add `handler` operand with write effect to `schedule_kernel` op

- llvm-spirv/lib/SPIRV/SPIRVWriter.cpp
- llvm-spirv/lib/SPIRV/SPIRVWriter.h
- llvm-spirv/lib/SPIRV/libSPIRV/SPIRVDecorate.h
- llvm-spirv/lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- llvm-spirv/lib/SPIRV/libSPIRV/SPIRVEntry.h
- llvm-spirv/lib/SPIRV/libSPIRV/SPIRVModule.cpp
- llvm-spirv/lib/SPIRV/libSPIRV/SPIRVModule.h
- llvm-spirv/lib/SPIRV/libSPIRV/SPIRVStream.cpp
- llvm-spirv/test/ExecutionMode.ll
- llvm-spirv/test/copy_object.spt
- llvm-spirv/test/entry-point-interfaces.ll
- llvm-spirv/test/extensions/INTEL/SPV_INTEL_inline_assembly/inline_asm_clobbers.cl
- llvm-spirv/test/extensions/INTEL/SPV_INTEL_inline_assembly/inline_asm_constraints.cl
- llvm-spirv/test/negative/unimplemented.spt
- llvm-spirv/test/right_shift.spt
This PR pulls in the following PR from upstream Khronos SPIRV-LLVM-Translator repo:
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1334
`
This is a patch to expand the collection of entry point interfaces.
In SPIR-V 1.4 and later OpEntryPoint must list all global variables in the
interface.
`
In addition, a couple of minor changes have been added to sync with latest code.
This patch addresses https://github.com/intel/llvm/issues/9958
Updated the following tests to sync with upstream as well:
llvm-spirv/test/extensions/INTEL/SPV_INTEL_inline_assembly/inline_asm_clobbers.cl
llvm-spirv/test/extensions/INTEL/SPV_INTEL_inline_assembly/inline_asm_constraints.cl
Thanks
> [llvm-spirv] Cherry pick Khronos changes to expand collection of entry point interfaces (PR #1334)

- sycl/plugins/unified_runtime/pi2ur.hpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/adapter.cpp
- sycl/test-e2e/Plugin/cuda-max-local-mem-size.cpp
The `UR_RESULT_ADAPTER_SPECIFIC_ERROR` was not returning an error to the SYCL RT which meant all errors were treated as warnings and ignored unless `SYCL_RT_WARNING_LEVEL` is set to geq 2. This changes things so the adapter specific error is now reported as such, meaning all uses `UR_RESULT_ADAPTER_SPECIFIC_ERROR` meant as warnings are now caught as errors.
> [SYCL][CUDA] Make plugin specific error return an error

- clang/lib/Driver/ToolChains/Clang.cpp
- clang/test/Driver/sycl-mlir.cpp
- llvm/lib/SYCLLowerIR/MutatePrintfAddrspace.cpp
- polygeist/tools/cgeist/Lib/clang-mlir.cc
- polygeist/tools/cgeist/Test/Verification/sycl/constructors.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/issue7835.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/kernels.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/kernels_funcs.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/single_task.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/sycl_extern_func.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/vec_add.cpp
- polygeist/tools/cgeist/driver.cc
- sycl/test-e2e/xfail_tests.txt
Hack to allow cgiest to use the clang routine to setup the llvm pipeline rather than its own. This allows to capture the SYCL specific pass setup and allows cgeist to honor clang's codegen options.
The patch also fixes a small issue in handling the libsycl unbundling.
> [SYCL-MLIR] Hack to allow polygeist to reuse the clang backend utils

- sycl/plugins/unified_runtime/ur/adapters/native_cpu/adapter.cpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/platform.cpp
This PR fixes some errors while building the Native CPU plugin:
Updated urPlatformGet signature
Added missing function urAdapterGetLastError
> [SYCL][NATIVECPU] Fixed missing changes from latest UR version

- sycl/source/detail/xpti_registry.hpp
collectors could be subscribed for only one trace type from begin-end pair. In this case the logic with filtered check causes wrong logic.
> [XPTI][SYCL] remove filtered XPTI enabling check from XPTIScope

- sycl/include/sycl/handler.hpp
Add `always_inline` attribute to `sycl::handler::parallel_for[_impl]` functions.
This way, we will avoid making some SYCL host raising patterns interprocedural.
> [SYCL-MLIR] Always inline `sycl::handler::parallel_for`

- sycl/include/sycl/handler.hpp
- sycl/test-e2e/Basic/parallel_for_offset_integral_t.cpp
According to SYCL 2020, using kernel function which accept an integral type is supported because of implicit conversion of item<1> to integral type. This patch fixes compilation failure for such case.
Fixes: https://github.com/intel/llvm/issues/9839
> [SYCL] Accept integral type in parallel_for with offsets

- polygeist/lib/Dialect/Polygeist/Transforms/SYCLRaiseHost.cpp
- polygeist/test/polygeist-opt/sycl/sycl-raise-host.mlir
- polygeist/tools/cgeist/Test/Verification/sycl/raising/host_raising_nd_range.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/raising/host_raising_nd_range_constructors.cpp
When handling an `nd_range` constructor not `memcpy`-ing its components, i.e., storing each index, insert all of the member allocas before the `nd_range` alloca and all of the constructors after its correspondent store.
> [SYCL-MLIR][sycl-raise-host] nd_range constructor: Ensure domination

- mlir-sycl/lib/Dialect/SYCL/Transforms/ConstantPropagation.cpp
- mlir-sycl/test/Transforms/constant-propagation.mlir
Propagate array arguments capturing an `llvm.addressof` operation by copying the array definition to the device module and inserting a new `llvm.addressof` operation in the kernel.
Note casting might be needed if types differ.
>  [SYCL-MLIR][sycl-constant-propagation] Propagate constant array arguments

- polygeist/lib/Dialect/Polygeist/Analysis/ReachingDefinitionAnalysis.cpp
- polygeist/test/polygeist-opt/reachingDefinitions.mlir
If the analysis runs into a non-function symbol, abort analysis to avoid breaking.
> [SYCL-MLIR][ReachingDefinition] Do not break on non-function symbols

- polygeist/include/mlir/Dialect/Polygeist/Transforms/Passes.td
- polygeist/lib/Dialect/Polygeist/Transforms/CMakeLists.txt
- polygeist/lib/Dialect/Polygeist/Transforms/SYCLRaiseHost.cpp
- polygeist/test/polygeist-opt/sycl/sycl-raise-host.mlir
This PR adds two special cases to the `set_capture` op raising, for situations we observed in SYCLbench:
1. Ignore calls/invokes to `sycl::handler::unpack`.
2. The frontend sometimes groups scalar arguments into vectors, to capture them in a single store. The pattern was extended to create `set_captured` ops *per scalar value*, to later match the expected number and kinds of arguments in the integration header.
> [SYCL-MLIR] Raise more `set_capture` ops.

- sycl/plugins/unified_runtime/pi2ur.hpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/queue.cpp
Recently in the switch to UR `urQueueCreateFromNativeHandle` changed the previous behaviour whereby a queue was created with a device taken as the default device from the context. It changed it so that the queue was created with the device argument instead. Since the sycl runtime always passes a nullptr for the device when programmers call `make_queue(nativeStream, context)`, this broke `make_queue`. This patch reverts to the previous behaviour before the switch from pi cuda to ur cuda.
Note that this should also fix `make_queue` for l0 which I also guess was broken due to the asserts meaning that this line was never reached: https://github.com/intel/llvm/blob/sycl/sycl/plugins/unified_runtime/ur/adapters/level_zero/queue.cpp#L574. But I have not tested this.
> [SYCL][CUDA] Pass device from context in create queue.

- sycl/include/sycl/range.hpp
- sycl/test/basic_tests/range.cpp
This addresses an expected change in the spec.
> [SYCL] Fix ranges to allow default constructor to 0s

- clang/lib/CodeGen/ItaniumCXXABI.cpp
Clang::CodeGenCXX/dynamic-cast-exact.cpp was failing because we still preseve non-opaque pointers version of `EmitDynamicCastToVoid` function which expects DestTy parameter as a pointer type.
9d525bf added new usage of `EmitDynamicCastToVoid` but since upstream doesn't care about typed pointers it was broken because `DestTy` parameter which doesn't exist in upstream ended up being non-pointer type.
> [clang] Fix test in pulldown

- llvm/lib/Transforms/IPO/DeadArgumentElimination.cpp
- sycl/test/check_device_code/buffer_location_codegen.cpp
- sycl/test/esimd/dae.cpp
- sycl/test/esimd/genx_func_attr.cpp
- sycl/test/esimd/slm_init_specconst_size.cpp
This change enables DAE for ESIMD kernels and adds code to fixup metadata inserted
by the SYCL FE when an argument is removed.
I found the metadata problem when running our E2E tests after enabling DAE for ESIMD but it does not seem like an ESIMD-specific issue. This change is tested by existing E2E tests.
The metadata fixup is required because downstream code in llvm-spirv assumes
the number of operands for the metadata will match the actual number of arguments
for the kernel.
Another option would be to fix the downstream code, but making the metadata be accurate
to the actual kernel the downstream code will see seemed to be a better root cause fix to me.
Let me know if you disagree with the above, or if you have a way to prevent explicitly
listing all of the metadata to fix, which I …
> [SYCL] Fixup SYCL metadata when dead argument is optimized and enable DAE for ESIMD

- llvm/lib/Transforms/Coroutines/CoroSplit.cpp
Fixes
```
LLVM::Transforms/Coroutines/coro-async-remat.ll
LLVM::Transforms/Coroutines/coro-retcon-remat.ll
```
JR: CMPLRLLVM-50207.
> Re-add bitcasts behind !INTEL_SYCL_OPAQUEPOINTERS_READY.

- clang-tools-extra/include-cleaner/unittests/CMakeLists.txt
Cherry pick to fix link error.
> Add missing clangSerialization dependency for include-cleaner unittests

- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLHostOps.td
Add `MemoryEffectsOpInterface` to `sycl.host.handler.set_kernel`, which will write the `handler` argument;
`sycl.host.handler.set_nd_range`, which will write the `handler` and read the `range` and `offset` inputs; and `sycl.host.set_captured` which will write the lambda and read the captured value.
Note `sycl.host.kernel_name` and `sycl.host.kernel_name` do not need this interface, so this patch adds the interface to all the remaining relevant host operations.
> [SYCL-MLIR] Add `MemoryEffectsOpInterface` to remaining host ops

- polygeist/lib/Dialect/Polygeist/Transforms/SYCLRaiseHost.cpp
- polygeist/test/polygeist-opt/sycl/sycl-raise-host.mlir
The frontend sometimes splits an array into multiple parts to pass it to a kernel. One example would be an array with nine elements, split into two `vector<4 x f32>` and a single scalar `f32`. 
With this change, this will be raised to a global constant of full length by putting the pieces together if they're constant, so we can reason about the constant array.
> [SYCL-MLIR] Capture split arrays during raising

- sycl/test-e2e/lit.cfg.py
If sycl-ls is not on `PATH`, the lit config will fail with this message:
env: '1': No such file or directory
It's cryptic, and it's a result of trying to use the first part of the spawned subshell's "not found" message as the path to the binary. Also, `sycl-ls` is a hard requirement for the end to end tests to run at all so we should use the one we built, and if we can't find it, we bail out with `fatal`.
This patch then, does 3 things:
1. Prefers the `sycl-ls` we should have just built; it's implicitly being tested here so we *need* it. If the user wants to use an out-of tree sycl-ls, then running lit directly gives them mechanism to do that
2. Fix the error handling to fail early with clearer and more useful error messages
3. Cleanup subprocess usage. We don't need to spawn a shell for …
> [SYCL][test-e2e] Fix lit config for sycl-ls

- sycl/include/sycl/ext/oneapi/experimental/sycl_complex.hpp
Following a review of the marray complex specialization PR (https://github.com/intel/llvm/pull/8647), where the `std::enable_if` are enabled via template type parameter. It has been asked to be switched to return type instead; this PR follows the same approach to have a coherent codebase.
Furthermore, all `std::enable_if<...>::type` has been switched to `std::enable_if_t` for coherence.
And finally, this PR also fixes a bug where the `std::enable_if` depends on the trait `is_gencomplex`, but should depend on `is_genfloat`  since the functions are specialized for `complex<T>`, `T` is the one that should be tested.
> [SYCL][EXT][COMPLEX] Enable std::enable_if via Return type instead of type template parameter

- sycl/plugins/CMakeLists.txt
- sycl/plugins/level_zero/CMakeLists.txt
We just don't need it:
1) PI interfaces are specifically marked with __SYCL_EXPORT, e.g. https://github.com/intel/llvm/blob/8e0cc4b7a845df9389a1313a3e680babc4d87782/sycl/include/sycl/detail/pi.h#L1148
2) We call to PI interfaces (except for `piPluginInit`) via a pointer from a table set up during `piPluginInit`:https://github.com/intel/llvm/blob/8e0cc4b7a845df9389a1313a3e680babc4d87782/sycl/include/sycl/detail/pi.hpp#L220
> [SYCL] Do not set CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON for plugins

- compiler-rt/test/sanitizer_common/TestCases/sanitizer_coverage_allowlist_ignorelist.cpp
This reverts commit aa4cd66c877d516406b0a53d104a776f19ba6c72.
This will resolve the following failures:
```
SanitizerCommon-asan-i386-Linux::sanitizer_coverage_allowlist_ignorelist.cpp
SanitizerCommon-asan-x86_64-Linux::sanitizer_coverage_allowlist_ignorelist.cpp
SanitizerCommon-lsan-i386-Linux::sanitizer_coverage_allowlist_ignorelist.cpp
SanitizerCommon-lsan-x86_64-Linux::sanitizer_coverage_allowlist_ignorelist.cpp
SanitizerCommon-msan-x86_64-Linux::sanitizer_coverage_allowlist_ignorelist.cpp
```
> [Sanitizers] Fix test in pulldown

- mlir-sycl/lib/Dialect/SYCL/Transforms/ConstantPropagation.cpp
- mlir-sycl/test/Transforms/constant-propagation.mlir
ND-range (`sycl.host.handler.set_nd_range`) and arguments (`sycl.host.set_captured`) are passed by value, so it is safe to move queried analysis point to these operations for the respective analysis.
> [SYCL-MLIR][sycl-constant-propagation] Change queried program point

- polygeist/include/mlir/Dialect/Polygeist/Transforms/Passes.td
- polygeist/lib/Dialect/Polygeist/Transforms/SYCLRaiseHost.cpp
This PR adds statistics to the `-sycl-raise-host` pass to track the number of successful pattern applications for raising the `sycl.host.schedule_kernel` op, as well as its precursor ops (`set_kernel`, `set_nd_range`, `set_captured`), to make it easier to spot missed raising opportunities in tests and benchmarks.
> [SYCL-MLIR] Add statistics to host raising pass.

- clang/include/clang/Basic/Attr.td
- clang/include/clang/Basic/DiagnosticSemaKinds.td
- clang/lib/Sema/SemaDeclAttr.cpp
- clang/test/SemaSYCL/vec-type-hint-2.cpp
- clang/test/SemaSYCL/vec-type-hint.cpp
According to the SYCL 2020 spec, [[sycl::vec_type_hint()]] attribute should accept arguments of the type sycl::vec type. The attribute should also be accepted with non conforming lambda syntax.
The current implementation in SYCL corresponds to the openCL version of this argument (with an additional spelling for SYCL), i.e. the attribute accepts extended vector type, floating point types and integral type. An error diagnostic is thrown for sycl:vec type. 
Since the attribute is deprecated and is not handled by any SYCL backend, and will be removed in a future version of the spec, to be minimally conformant with SYCL 2020 spec, this PR just ignores the attribute instead of adding support for sycl::vec type. Support was also added for non conforming lambda syntax
> [SYCL] Ignore vec_type_hint attribute in SYCL 2020

- .github/workflows/sycl_nightly.yml
This mode is tested by the default configuration now.
> [CI] Remove Nightly build configuration for opaque pointers

- polygeist/include/mlir/Dialect/Polygeist/Analysis/SYCLAccessorAnalysis.h
- polygeist/lib/Dialect/Polygeist/Analysis/SYCLAccessorAnalysis.cpp
- polygeist/test/polygeist-opt/sycl/local-accessor-analysis.mlir
Handle `local_accessor` as `accessor` with some key differences:
- `local_accessor` will be constructed with a `local_accessor` constructor;
- Two different local accessor will not alias;
- A local accessor will not alias with a device accessor;
- A local accessor cannot be offset or have a buffer, i.e., the only relevant information we will infer is range information;
- Joining a local accessor with a device accessor will yield top;
> [SYCL-MLIR][accessor-analysis] Handle `local_accessor` instances

- llvm/lib/SYCLLowerIR/ESIMD/ESIMDVerifier.cpp
- sycl/include/sycl/ext/oneapi/experimental/invoke_simd.hpp
- sycl/test-e2e/InvokeSimd/Spec/uniform_retval.cpp
- sycl/test/invoke_simd/return-type-uniform.cpp
The spec states that returning a `uniform` object is allowed:
"Return values of type sycl::ext::oneapi::experimental::uniform<T> are not anyhow converted, and broadcast to each work-item; every work-item in the sub-group receives the same value. NOTE: sycl::ext::oneapi::experimental::uniform<T> return type is the way to return a uniform value of simd or simd_mask type."
Update the compile-time error checking and ESIMD verifier to allow this.
> [SYCL][InvokeSimd] Allow callables to return uniform

- mlir-sycl/lib/Dialect/SYCL/Transforms/ConstantPropagation.cpp
- mlir-sycl/test/Transforms/constant-propagation.mlir
- polygeist/include/mlir/Dialect/Polygeist/Analysis/SYCLAccessorAnalysis.h
- polygeist/lib/Dialect/Polygeist/Analysis/SYCLAccessorAnalysis.cpp
Use following rules for `local_accessor`:
- Use same memory and access range
- Propagate known range
- Always use zero-initialized `id` as an offset
> [SYCL-MLIR][constant-propagation] Propagate `local_accessor` members

- polygeist/tools/cgeist/Options.h
We are aware of degradation with `Gesummv` on PVC when `DetectReduction` is enabled.
> [SYCL-MLIR][LoopInternalization] Enable by default

- polygeist/tools/cgeist/Options.h
- polygeist/tools/cgeist/Test/Verification/sycl/raising/host_raising_pipeline.cpp
- polygeist/tools/cgeist/driver.cc
Run `-sycl-constant-propagation` after `-sycl-raise-host`.
> [SYCL-MLIR] Enable -sycl-constant-propagation by default

- sycl/test/CMakeLists.txt
Single triple targets are only meant for manual run and should not be included into check-all, only check-sycl-combined-triples should be. Otherwise we are running the same tests from multiple processes resulting in race conditions (beside unnecessary work).
> [SYCL] Fix check-all after #10635

- sycl/doc/extensions/experimental/sycl_ext_oneapi_compat.asciidoc
- sycl/doc/index.rst
- sycl/doc/syclcompat/README.md
This pull request introduces a new stand alone library, `SYCLcompat`: a simplified wrapper on top of SYCL, aiming to make it more accessible to developers familiar with other heterogeneous programming models.
SYCLcompat has two primary goals:
-  Improve the adoption of SYCL. This library is designed to provide a familiar programming interface that resembles other popular heterogeneous programming models. By reducing the learning curve, it enables developers to leverage SYCL's power and features more easily.
- Source-to-Source Translation Support. SYCLcompat is also designed to facilitate automatic source-to-source translation from other heterogeneous programming models to SYCL and offer a more standardized and consistent programming interface. This feature can significantly streamline the …
> [SYCL][COMPAT][Doc] Add SYCLcompat documentation

- sycl/include/sycl/types.hpp
- sycl/test/basic_tests/types.cpp
The recent sycl::vec changes (https://github.com/intel/llvm/pull/9492)  broke they unary operations. This PR fixes them and adds some testing to avoid that in the future.
> [SYCL] Fix sycl::vec unary ops

- clang/lib/Sema/SemaDeclAttr.cpp
Fix static analyzer concern about dereferencing null value.
> [SYCL][Clang][NFC] Fix static analyzer concern

- llvm/lib/SYCLLowerIR/SYCLPropagateAspectsUsage.cpp
- llvm/test/SYCLLowerIR/PropagateAspectsUsage/exclude-aspect.ll
- sycl/test-e2e/OptionalKernelFeatures/no-fp64-optimization-declared-aspects.cpp
This PR changes `SYCLPropagateAspectsPass` to propagate aspects that come from `sycl_declared_aspects` even if they are excluded. The reason for this change is because a test like `no-fp64-optimization-declared-aspects.cpp` added in this PR would failed before with higher optimization level because 
- on the first aspect propagation pass, `fp64` is not propagated (to allow for trivial uses of `float x = 1.5` to optimized out) 
- the call to the function marked with `device_has(fp64)` is inlined on higher optimizations
- that function does not actually use `double` in its body
which means no usage of double ends up in the optimized function, leading the second aspect propagation pass to not attach `fp64` to its used aspects metadata.
> [SYCL] Propagate explicitly declared aspects even if excluded

- sycl/source/detail/scheduler/scheduler.cpp
Scheduler::checkLeavesCompletion checks status of all leaves of the buffer to see whether we can destroy that sycl::buffer. There are many scenarios when alloca commands are leaves, these commands don't have associated event and currently they are always incorrectly considered "in progress" because of that preventing buffers to be destroyed timely and deferring their destruction till the point of program termination. Skip alloca commands to fix that.
> [SYCL] Skip alloca commands when checking for leaves completion

- .github/workflows/sycl_linux_build.yml
- .github/workflows/sycl_nightly.yml
Also changes daily build upload (via github release) to only require successful build/LIT and not E2E tests.
In addition to that, I switched CUDA E2E from using AWS runner to using our self-hosted one. The load of this workflow is low so our single runner can handle that.
> [CI] Use separate Linux build/test jobs and no matrix generator in nightly

- .github/workflows/sycl_linux_build.yml
- .github/workflows/sycl_post_commit.yml
This eliminates the usage of matrix generator in post-commit, following a similar change done in pre-commit earlier.
> [CI] Use separate build/test in post-commit + add pull_request trigger

- sycl/CMakeLists.txt
Fixed the native_cpu plugin only being built if level_zero was enabled as well
> [SYCL][NATIVECPU] native_cpu plugin enable fix

- .github/workflows/sycl_precommit_windows.yml
Linux had been updated in #10720 already.
> [CI] Switch windows pre-commit pull_request_target -> pull_request

- sycl/doc/EnvironmentVariables.md
- sycl/plugins/unified_runtime/ur/adapters/level_zero/common.cpp
- sycl/plugins/unified_runtime/ur/adapters/level_zero/device.cpp
- sycl/plugins/unified_runtime/ur/adapters/level_zero/platform.cpp
- sycl/test-e2e/Basic/intel-ext-device.cpp
- sycl/test-e2e/DeprecatedFeatures/deprecated_intel_ext_device.cpp
- sycl/test-e2e/Regression/device_pci_address_bdf_format.cpp
L0 already provides an interface to access PCI information without needing to set an environment variable to access SYSMAN interfaces.
> [SYCL][UR][L0] Deprecate SYCL_ENABLE_PCI

- sycl/include/sycl/detail/vector_traits.hpp
VS2017 will require direct inclusion of `<algorhythm>` for the std::min usage in vector_traits.hpp
> [SYCL] overlooked inclusion, VS2017

- sycl/test-e2e/Reduction/reduction_reducer_op_eq.cpp
divisor may be 0 in `T Diff = (Expected / *Res) - T{1};`
> [SYCL] Update reduction_reducer_op_eq.cpp test to avoid dividing by zero

- sycl/test-e2e/Plugin/enqueue-arg-order-image.cpp
- sycl/test-e2e/Plugin/interop-level-zero-image-get-native-mem.cpp
- sycl/test-e2e/Plugin/interop-level-zero-image-ownership.cpp
- sycl/test-e2e/Plugin/interop-level-zero-image.cpp
The spir-v generation is not working correctly for legacy images at O0. There is no intention of fixing it at this time, given that the image thing is going to be completely overhauled in the future. Marking these tests as unsupported in O0.
> [SYCL] mark failing image tests as unsupported at O0. 

- sycl/doc/extensions/experimental/sycl_ext_oneapi_annotated_ptr.asciidoc
- sycl/include/sycl/ext/oneapi/experimental/annotated_ptr/annotated_ptr.hpp
annotated_ref assignment should copy the underneath pointer
> [SYCL] add deep copy for annotated_ref assignment operator

- polygeist/tools/cgeist/driver.cc
Drop `-lower-affine` pass and make code more readable by moving `-raise-scf-to-affine` and `-affine-cfg` passes creation point.
Note not dropping the pass would lead to the redundant pipeline:
```
...,lower-affine,raise-scf-to-affine,affine-cfg)
```
> [SYCL-MLIR] Drop `-lower-affine` pass

- .github/CODEOWNERS
It would be nice if the [design doc](https://github.com/intel/llvm/blob/sycl/sycl/doc/design/CommandGraph.md) and [specific E2E tests](https://github.com/intel/llvm/tree/sycl/sycl/test-e2e/Graph) for SYCL-Graphs had automatic reviewers from
[@sycl-graphs-reviewers](https://github.com/orgs/intel/teams/sycl-graphs-reviewers)
> [SYCL][CODEOWNERS] Update files owned by Graphs

- sycl/cmake/modules/AddSYCLLibraryUnitTest.cmake
The same has been done in libdevice in #7771. We need this internally where we have a build on an older RHEL with gcc in non-system location.
> [SYCL] Add CMake option to pass "--gcc-toolchain" for syclcompat unittests

- sycl/source/detail/scheduler/commands.cpp
- sycl/test-e2e/Basic/accessor/accessor.cpp
Prior to this PR, we would throw or crash when a default constructed accessor was passed to a kernel if it was not filtered out, even if it wasn't really accessed. Passing a default constructed accessor to a kernel is allowed by SYCL2020, and this PR ensures our implementation allows it.
> Allow passing default constructed accessors to kernels

- polygeist/tools/cgeist/Test/Verification/sycl/functions.cpp
Do not check mangled function name in `functions.cpp`, as this can change if the runtime is updated. It is only relevant that the operations are generated.
> [SYCL-MLIR][NFC] Drop `MangledFunctionName` check in `functions.cpp`

- sycl/plugins/unified_runtime/ur/adapters/level_zero/queue.cpp
They are only set at contextCreate time.
> [SYCL][UR][L0] Don't overwrite context's devices

- llvm/lib/IR/Constants.cpp
Causes LIT failures when parsing `blockaddr` constants.
> Guard some changes from a7ee80fab213 w/INTEL_SYCL_OPAQUEPOINTER_READY

- sycl/source/stream.cpp
Fix:
error: ‘CHAR_BIT’ was not declared in this scope
> [SYCL] Fix error ‘CHAR_BIT’ was not declared in this scope in sycl/source/stream.cpp

- mlir-sycl/lib/Dialect/SYCL/Transforms/ConstantPropagation.cpp
- Build single list of propagators;
- Rename `ConstantExplicitArg` to `ConstantExplicitArgBase`.
> [SYCL-MLIR][sycl-constant-propagation][NFC] Refactor pass

- sycl/cmake/modules/AddSYCLLibraryUnitTest.cmake
'SYCL_COMPATH_UNITTEST_GCC_TOOLCHAIN' ->
'SYCL_COMPAT_UNITTEST_GCC_TOOLCHAIN'.
Original PR: #10791
> [SYCL] Fix small typo in AddSYCLLibraryUnitTest.cmake.

- .github/workflows/sycl_precommit_linux.yml
1) That's what we used to have when using matrix, see https://github.com/intel/llvm/blob/632c2889e33bb3c43e0768b920a35da6e3267579/devops/test_configs.json#L70
2) That makes sense and I'm not sure how it worked before.
3)
https://github.com/intel/llvm/blob/632c2889e33bb3c43e0768b920a35da6e3267579/devops/containers/ubuntu2204_base.Dockerfile#L20 should enable proper pre-commit testing for drivers update for the ESIMD Emulator target (which is the main motiviation for this change).
> [CI] Use ubuntu2204_intel_drivers:latest image for ESIMD testing

- sycl/test-e2e/InvokeSimd/Spec/simd_size/simd8_platform_error.cpp
The self-check of the test changed according to the previously changed error message.
> [SYCL][InvokeSimd][E2E] Fixed simd8_platform_error.cpp self-check

- clang/include/clang/Basic/DiagnosticDriverKinds.td
- clang/include/clang/Driver/Options.td
- clang/lib/Driver/Driver.cpp
- clang/lib/Driver/ToolChains/Clang.cpp
- clang/test/Driver/sycl-mlir.cpp
- libdevice/cmake/modules/SYCLLibdevice.cmake
- sycl/test/check_device_code/cuda/ldg.cpp
- sycl/test/check_device_code/cuda/matrix/matrix-nvptx-bfloat16-test.cpp
- sycl/test/check_device_code/cuda/matrix/matrix-nvptx-double-test.cpp
- sycl/test/check_device_code/cuda/matrix/matrix-nvptx-half-float-test.cpp
- sycl/test/check_device_code/cuda/matrix/matrix-nvptx-half-half-test.cpp
- sycl/test/check_device_code/cuda/matrix/matrix-nvptx-int8-test.cpp
- sycl/test/check_device_code/cuda/matrix/matrix-nvptx-tf32-test.cpp
- sycl/test/check_device_code/cuda/matrix/matrix-nvptx-uint8-test.cpp
- sycl/test/extensions/properties/properties_kernel_device_has_warning.cpp
- sycl/test/warnings/aspect_perserve_srcloc.cpp
Make the host raising default when building for MLIR. The patch adds -fno-sycl-raise-host in order to opt out of raising.
> [SYCL-MLIR] Enable raising host by default

- clang/test/SemaSYCL/parallel_for_wrapper_attr.cpp
Add 'implicit_instantiation' to CHECK lines.
> [Clang] Update test checks after 3bfafc4f2287.

- clang/test/SemaSYCL/fpga_pipes.cpp
- clang/test/SemaSYCL/fpga_pipes_ast.cpp
- clang/test/SemaSYCL/intel-fpga-local.cpp
The referenced commit changes the wording of some diagnostics from
"'foo' attribute requires a string'
to
"expected string literal as argument of 'foo' attribute"
This patch updates those checks accordingly. Additionally, some AST
changes were necessary (in a similar way to other AST changes in the
referenced commit).
> [Clang] Update test checks after 98322d3eb431.

- llvm/lib/IR/Type.cpp
Fix some LIT failures related to target type info.
> Guard a change from e53b28c83301 with INTEL_SYCL_OPAQUEPOINTER_READY.

- llvm/lib/ExecutionEngine/ExecutionEngine.cpp
- llvm/lib/IR/AutoUpgrade.cpp
- llvm/lib/IR/Type.cpp
- llvm/lib/IR/Verifier.cpp
- llvm/lib/Transforms/Coroutines/Coroutines.cpp
- Revert "[clang] Drop some references to typed pointers (getInt8PtrTy).
NFC"
- Guard d03f4177dfbb6a910edde31acd0f14786b549bad within
INTEL_SYCL_OPAQUEPOINTER_READY
- Revert "[llvm] Drop some bitcasts and references related to typed
pointers"
- Guard e53b28c8330102bf21ac717ade2bfac9b1f09517 within
INTEL_SYCL_OPAQUEPOINTER_READY
> Guard e53b28c833010, d03f4177dfbb changes with INTEL_SYCL_OPAQUEPOINTER_READY.

- clang/lib/CodeGen/CGVTT.cpp
This is a fix of 66c18fee337fdf04f04f48e0fefb68157915b8a8
> Fix of 66c18fee337f, which guard opaque ptr changes

- sycl/plugins/unified_runtime/ur/adapters/native_cpu/context.cpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/device.cpp
Removes some unneeded UR_ASSERTS
Added initial GlobalTimeStamp implementation for `sycl-ls`.
> [SYCL][NATIVECPU] UR adapter updates

- llvm/include/llvm/SYCLLowerIR/TargetHelpers.h
- llvm/lib/SYCLLowerIR/LocalAccessorToSharedMemory.cpp
- llvm/lib/SYCLLowerIR/TargetHelpers.cpp
- llvm/test/CodeGen/NVPTX/local-accessor-to-shared-memory-basic-transformation.ll
Make sure that metadata containing the kernel function is correctly updated after local accessor to shared memory pass is run.
> [SYCL] Update kernel function metadata after local accessor pass

- libdevice/device_itt.h
- libdevice/itt_compiler_wrappers.cpp
- libdevice/itt_stubs.cpp
- libdevice/itt_user_wrappers.cpp
weak_odr attribute prohibits removing unused functions and ITT functions
are supposed to be optimized out the compiler if they are not used. The
attribute seems to be added by mistake with the common refactoring
accross the whole libdevice library.
> [libdevice] Remove weak_odr attribute from ITT functions

- sycl/doc/GetStartedGuide.md
Change the name of the Docker image recommended for building the project
from ubuntu2204_base to ubuntu2204_build. The later has NVIDIA CUDA and
AMD ROCM pre-installed and enables CUDA and HIP back-ends support.
Other changes include:
- Apply 80-char line limit.
- Minor type fixes.
- Update outdated DPC++ device compiler limitation and link to oneAPI
specifications.
> [Doc][SYCL] Update Get Started Guilde for SYCL project

- sycl/include/sycl/reduction.hpp
Intended to fix error: comparison of integer expressions of different signedness
note: unrecognized command-line option '-Wno-inconsistent-missing-override' may have been intended to silence earlier diagnostics
> [SYCL] Consistently using unsigned loop counter for reduction

- sycl/include/sycl/buffer.hpp
- sycl/test-e2e/Regression/subalign_no_alloc.cpp
This commit changes the required alignment determined by buffers to use alignof rather than some power-of-two higher than the size of the element type. This avoids the need for reallocation when the element type has a different alignment than its size.
> [SYCL] Fix require alignment in buffers

- sycl/source/detail/scheduler/graph_builder.cpp
- sycl/test-e2e/Basic/buffer/subbuffer_overlap.cpp
Before this PR we were creating a single PI sub-buffer (of a smaller size for the sycl/test-e2e/Basic/buffer/subbuffer_overlap.cpp added here).
Suprisingly, on many platforms an "out-of-partition" access didn't cause any issues and all the modified memory was copied between host/device. However, that wasn't guaranteed by the PI calls SYCL RT was performing and for some scenarios/HW the device-to-host copy after the second kernel only brought back the smaller part of the original buffer corresponding to the first smaller subbuffer.
> [SYCL] Overlapping subbuffers with different sizes need separate piMemBufferPartition

- sycl/source/builtins_generator.py
After the recent refactoring of the builtins, the generator was using the max implementation for min with a vector and scalar half argument. This commit fixes this typo, effectively making the implementation once again use the right builtin calls.
> [SYCL] Fix typo in generator for half min

- sycl/include/sycl/ext/oneapi/sub_group_mask.hpp
As part of version two of [sycl_ext_oneapi_sub_group_mask](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_oneapi_sub_group_mask.asciidoc) the copy-asssignment operator is defined as default but were deleted as part of https://github.com/intel/llvm/pull/10564. This changes them to `default` ahead of version 2 of the extension to avoid regressions.
> [SYCL] Change sub_group_mask copy-assignment operator to default

- sycl/plugins/unified_runtime/ur/adapters/cuda/usm.cpp
This should fix the post-commit build fails.
> [SYCL][CUDA] Add std::ignore for USM alloc args that are only used in an assert.

- clang/test/CodeGenSYCL/kernel-simple-instrumentation.cpp
- clang/test/Driver/sycl-instrumentation.c
- sycl/test-e2e/DeviceLib/ITTAnnotations/barrier.cpp
Minor fixes in -fsycl-instrument-device-code option tests:
1. Remove Doxygen style comments from the tests
2. Remove run command duplicate from clang/test/Driver/sycl-instrumentation.c
3. Update SYCL include header to SYCL 2020 in barrer.cpp test.
> [ITT][SYCL][NFC] Update ITT instrumentation tests

- sycl/source/detail/device_impl.cpp
- sycl/test-e2e/Basic/submit_time.cpp
`MDeviceHostBaseTime` data member of `device_impl` is supposed to be properly updated/calculated using `getCurrentDeviceTime()`. Currently it is also used to check `piGetDeviceAndHostTimer` support in
`isGetDeviceAndHostTimerSupported()` which results in wrong values stored in `MDeviceHostBaseTime` and wrong calculation of submit time. That's why use temp variables to check support of
`piGetDeviceAndHostTimer` to avoid spoiling `MDeviceHostBaseTime`.
> [SYCL] Don't spoil MDeviceHostBaseTime during isGetDeviceAndHostTimerSupported

- CONTRIBUTING.md
- README.md
The CI system no longer auto runs pre-commit activities for new contributors by default. Update the documentation to reflect the new process of needing someone to approve workload run.  Also, since i'm here, make some small constancy edits in some files I was touching.
> [DOC] Update section on new contributing and new CI flow process and other small edits

- sycl/test-e2e/AtomicRef/atomic_memory_order_seq_cst.cpp
The atomic_memory_order_seq_cst incorrectly uses discard_write access after initializing its memory. This causes failures on some hardware. This commit fixes this invalid access mode.
> [SYCL][E2E] Fix invalid discard_write in atomic_memory_order_seq_cst

- polygeist/lib/Dialect/Polygeist/Transforms/RaiseToAffine.cpp
- polygeist/test/polygeist-opt/affraise.mlir
- polygeist/tools/cgeist/CMakeLists.txt
- polygeist/tools/cgeist/Test/Verification/affineraise.cpp
- polygeist/tools/cgeist/driver.cc
Use `arith.ceildivui` to calculate new upper bounds for a raised loop, as using regular division leads to one less iteration of the loop when the division is not exact.
This way, the loop:
```mlir
scf.for %i = %lb to %ub step %step {
"foo"(%i) : (index) -> ()
scf.yield
}
```
will be transformed into:
```mlir
%0 = arith.subi %ub, %lb : index
%1 = arith.ceildivui %0, %step : index
affine.for %i = 0 to %1 {
%2 = arith.muli %i, %step : index
%3 = arith.addi %lb, %2 : index
"foo"(%3) : (index) -> ()
}
```
> [SYCL-MLIR][raise-scf-to-affine] Use ceil division to calculate ub

- sycl/unittests/CMakeLists.txt
These tests are currently disabled in the CI and ended up broken.
Since we're also currently moving to the Unified Runtime we might be able to replace most of them with the Unified Runtime CTS, or they will also need to be ported to the Unified Runtime.
So disable them by default until we figure out a proper course of action of these.
Related ticket: https://github.com/intel/llvm/issues/10688
> [SYCL] Disable PI unit tests by default

- sycl/source/detail/scheduler/commands.cpp
- sycl/source/detail/stream_impl.cpp
- sycl/test-e2e/Basic/accessor/empty_acc_host_task.cpp
- sycl/test-e2e/Basic/stream/zero_buffer_size.cpp
Follow-up fix for https://github.com/intel/llvm/pull/10797. Has to be merged after https://github.com/intel/llvm/pull/10911.
> [SYCL] Fix crash on a stream with zero-sized buffer

- llvm/lib/IR/AutoUpgrade.cpp
The revert commit b045c36ab92f4ff478dab678aaff4680fbccc7ea
Because libclc haven't support bf16 type, so the pervious commit
250f2bb2c6a9c288faeb821585e9394697c561d8 was reverted. So this commit
should be reverted too, until libclc support bf16 type.
> Revert "[llvm][NFC]Refactor AutoUpgrader case 'n'."

- clang/test/Driver/sycl-no-gpu-rdc-opaque-pointers.cpp
Fixes the following LIT regression:
Clang :: Driver/sycl-no-gpu-rdc-opaque-pointers.cpp
> [Driver][SYCL] Add `-nocudalib` to `-fno-gpu-rdc` LIT test.

- .github/CODEOWNERS
update codeowners file for 
sycl/doc/extensions/experimental/sycl_ext_oneapi_bindless_images.asciidoc @intel/bindless-images-reviewers
sycl/include/sycl/ext/oneapi/bindless* @intel/bindless-images-reviewers 
sycl/source/detail/bindless* @intel/bindless-images-reviewers
sycl/plugins/unified_runtime/ur/adapters/**/image.* @intel/bindless-images-reviewers 
sycl/test-e2e/bindless_images/ @intel/bindless-images-reviewers
> [SYCL][CODEOWNERS] Add bindless images code owners

- libdevice/cmath_wrapper.cpp
- libdevice/cmath_wrapper_fp64.cpp
- libdevice/device_math.h
- libdevice/fallback-cmath-fp64.cpp
- libdevice/fallback-cmath.cpp
- sycl/test-e2e/DeviceLib/cmath_fp64_test.cpp
- sycl/test-e2e/DeviceLib/cmath_test.cpp
Since https://github.com/intel/llvm/pull/9768 `ffast-math` no longer chooses llvm intrinsics. This highlighted that `std::round` was missing in libdevice. This fixes that.
> [SYCL][Devicelib] Add missing round in devicelib

- sycl/doc/extensions/experimental/sycl_ext_oneapi_annotated_ptr.asciidoc
- sycl/include/sycl/ext/oneapi/experimental/annotated_ptr/annotated_ptr.hpp
- sycl/test/extensions/annotated_arg/annotated_ptr.cpp
Remove `operator=(const T*)`. This one isn't deprecated because it was broken (trying to return temp as reference) and therefore can't have users.
Also add missing `const` for copy constructor.
> [SYCL] annotated_ptr API fixes part 2

- sycl/pi_win_proxy_loader/pi_win_proxy_loader.cpp
- sycl/source/detail/windows_pi.cpp
- xpti/include/xpti/xpti_trace_framework.hpp
Replaced LoadLibraryA() with LoadLibraryEx() and added SetDllDirectoryA() to remove the working directory from the standard search path. LoadLibraryExA() was used because "path" is of type c-string.
- LoadLibraryExA() <-- for ANSI (ASCII)
- LoadLibraryExW() <-- for Unicode
The libloaderapi.h header defines LoadLibraryEx as an alias which automatically selects the ANSI or Unicode version of this function based on the definition of the UNICODE preprocessor constant.
https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryexw
HMODULE LoadLibraryEx(
[in] LPCSTR lpLibFileName, //==> library path as a string
HANDLE hFile, //==> reserved as NULL for future use
[in] DWORD dwFlags //==> dwFlags determine the behavior of LoadLibaryEx(). When it is NULL, it …
> [SYCL]Replaced LoadLibraryA() with LoadLibraryEx()

- sycl/doc/extensions/experimental/sycl_ext_oneapi_matrix/sycl_ext_oneapi_matrix.asciidoc
- sycl/doc/extensions/proposed/sycl_ext_oneapi_graph.asciidoc
- sycl/doc/extensions/proposed/sycl_ext_oneapi_named_sub_group_sizes.asciidoc
- sycl/doc/extensions/proposed/sycl_ext_oneapi_root_group.asciidoc
- sycl/doc/extensions/proposed/sycl_ext_oneapi_usm_malloc_properties.asciidoc
- sycl/doc/extensions/supported/sycl_ext_oneapi_extended_atomics.asciidoc
- sycl/doc/extensions/supported/sycl_ext_oneapi_group_algorithms.asciidoc
Also removed `supported/sycl_ext_oneapi_extended_atomics.asciidoc` and `supported/sycl_ext_oneapi_group_algorithms.asciidoc` because those extensions are fully removed instead of just deprecated.
> [SYCL][Doc] Fix dead links in extension docs

- sycl/plugins/unified_runtime/ur/adapters/hip/context.hpp
- sycl/plugins/unified_runtime/ur/adapters/hip/enqueue.cpp
- sycl/plugins/unified_runtime/ur/adapters/hip/kernel.cpp
- sycl/plugins/unified_runtime/ur/adapters/hip/kernel.hpp
- sycl/plugins/unified_runtime/ur/adapters/hip/usm.cpp
This change is necessary to workaround a delightful bug in either HIP runtime, or the HIP spec.
It's discussed at length in github.com/intel/llvm/issues/7252 but for the purposes of this patch, it suffices to say that a call to `hipMemPrefetchAsync` is *required* for correctness in the face of global atomic operations on (*at least*) shared USM allocations.
The architecture of this change is slightly strange on first sight in that we reduntantly track allocation information in several places. The context now keeps track of all USM mappings. We require a mapping of pointers to the allocated size, but these allocations aren't pinned to any particular queue or HIP stream.
The `hipMemPrefetchAsync`, however, requires the associated HIP stream object, and the size of the allocation. The stream …
> Add prefetch for HIP USM allocations

- .github/workflows/sycl_linux_run_tests.yml
It was there for the matrix generator scenario, that has been removed.
> [CI] Remove deprecated drivers install

- llvm/test/tools/sycl-post-link/device-globals/test_global_variable.ll
- llvm/test/tools/sycl-post-link/device-globals/test_global_variable_drop_used.ll
- llvm/test/tools/sycl-post-link/device-globals/test_global_variable_drop_used_opaque_ptr.ll
- llvm/test/tools/sycl-post-link/device-globals/test_global_variable_name_mapping_metadata.ll
- llvm/test/tools/sycl-post-link/no-split-unused-func.ll
- llvm/test/tools/sycl-post-link/spec-constants/SYCL-2020-zeroinitializer-array-of-arrays.ll
- llvm/tools/sycl-post-link/ModuleSplitter.cpp
This allows for unused symbol removal through GlobalDCE that would happen if there were splits. Right now we have a mismatch where split modules have unused symbols removed but copied modules (no splits) do not.
> [SYCL] Do module cleanup in sycl-post-link even if there were no splits

- mlir/lib/Conversion/SPIRVToLLVM/SPIRVToLLVM.cpp
- mlir/lib/Conversion/SPIRVToLLVM/SPIRVToLLVMPass.cpp
- mlir/test/Conversion/SPIRVToLLVM/spirv-storage-class-mapping-unsupported.mlir
d76fffc introduced a new option to `-convert-spirv-to-llvm`, upstreamed by https://github.com/llvm/llvm-project/commit/12ce9fd1248c6321b343601c1a2468ac7e00c9da. Adapt our code to avoid future merge conflicts.
> [mlir][spirv] Adapt downstream `client-api` option patch after upstreaming

- sycl/unittests/helpers/PiMockPlugin.hpp
Returns a dummy commandbuffer handler in piextCommandBufferCreate Mock function
> [SYCL][Graph] Unitest bugfix

- sycl/doc/extensions/proposed/sycl_ext_oneapi_forward_progress.asciidoc
- sycl/doc/extensions/proposed/sycl_ext_oneapi_launch_queries.asciidoc
- sycl/doc/extensions/proposed/sycl_ext_oneapi_root_group.asciidoc
This extension strengthens the forward progress guarantees provided by a SYCL implementation, and exposes the guarantees of particular implementations/backends/devices via new device queries and kernel properties.
Signed-off-by: John Pennycook <john.pennycook@intel.com>
> [SYCL][Doc] Add draft forward progress extension

- .github/workflows/sycl_linux_run_tests.yml
- devops/scripts/install_drivers.sh
* Use GITHUB_TOKEN from env instead of passing via stdin
* Exit on error
* Use "set -x" to make logs more useful. Github replaces the token with
'***' so no security issue here.
It doesn't change the CI containers job yet, I plan to work on that in a
separate PR (to avoid unnecessary pre-commit CI jobs)
> [CI] Improve devops/scripts/install_drivers.sh

- .github/workflows/sycl_precommit_linux.yml
- .github/workflows/sycl_precommit_windows.yml
Containers task might or might not affect the tasks from pre-commit (depends on tasks' race conditions), so shouldn't be triggering pre-commit.
> [CI] More ignore-paths for pre-commit

- sycl/unittests/helpers/PiMockPlugin.hpp
Adds retrain/release for the CommandBuffer dummy handler in the unitest PI mock.
This fixes the CI fail in PR #10954. https://github.com/intel/llvm/actions/runs/5973326392/job/16205377150
> [SYCL][Graph] Release CommandBuffer dummy handler used by Graph Unitests

- sycl/plugins/unified_runtime/ur/adapters/hip/program.cpp
In the HIP adapter the HIP module is not set until the program is built with `urProgramBuild`, therefore we should check that the module actually needs to be unloaded in `urProgramRelease`.
The following will result in a failure, but should still be valid UR trace:
```cpp
uint8_t *source = "<some ptx>";
ur_program_handle_t prog;
urProgramCreate(context, device, sizeof(source), ptxSource, nullptr, &prog);
urProgramRelease(prog); // fails when it tries to unload the module.
```
> [SYCL][UR][HIP] Check if module needs to be unloaded

- .github/workflows/sycl_precommit_aws.yml
Revert commit 4e737e255eff3e095a4048fe04ff5c85daa9ab43 as dropping the job will be handled in the `sycl-mlir` branch instead (see #10956).
> Revert "[CI] Ignore E2E on AWS CUDA job in sycl-mlir branch (#10811)"

- llvm/test/CodeGen/X86/MergeConsecutiveStores.ll
Fixes the following LIT test regression:
LLVM :: CodeGen/X86/MergeConsecutiveStores.ll
> [CG][X86] Fix LIT test after conflict resolution.

- sycl/test-e2e/Matrix/SG32/element_wise_all_ops_tf32.cpp
- sycl/test-e2e/Matrix/SG32/joint_matrix_all_sizes.cpp
All sizes MAD and TF32 element wise ops with sub group size 32 pass on PVC now. Removing xfail.
> [SYCL][Joint Matrix] All sizes MAD and elem wise tf32 pass

- sycl/include/syclcompat/kernel.hpp
- sycl/include/syclcompat/syclcompat.hpp
- sycl/test-e2e/syclcompat/kernel/Inputs/kernel_module_lin.cpp
- sycl/test-e2e/syclcompat/kernel/kernel_function_lin.cpp
SYCLcompat primary goals and features are documented [here](https://intel.github.io/llvm-docs/syclcompat/README.html).
The PR includes the helper code to assist with kernel source-to-source translation. 
This PR only includes tests for linux environments .
> [SYCL][COMPAT] Added kernel.hpp and tests

- sycl/source/detail/program_manager/program_manager.cpp
This is an issue highlighted by Coverity, the removed condition is always false.
> [SYCL][NFC] Remove a redundant condition check

- devops/actions/build_container/action.yml
- devops/containers/ubuntu2204_intel_drivers.Dockerfile
So that we are not limited to 60 queries per IP per hour.
> [CI] Use GITHUB_TOKEN for drivers_install.sh during containers build

- sycl/doc/extensions/experimental/sycl_ext_codeplay_max_registers_per_work_group_query.md
Reduce line length to 80 characters.
Remove unnecessary white spaces and symbols from the device descriptor
table.
> [SYCL][Doc] Improve documentation readability.

- llvm/lib/SYCLLowerIR/ESIMD/ESIMDOptimizeVecArgCallConv.cpp
In the latest pulldown we started seeing `llvm.lifetime` intrinsics which previously weren't there.
The escape check was too conservative and skipping optimization if these intrinsics were present.
Skip all annotation intrinsics.
This is already locked down by vec_arg_call_conv_ext.cpp and vec_arg_call_conv_smoke.cpp, they are currently failing.
> [SYCL-Web][ESIMD] Don't consider annotation intrinsics as escapes in ESIMDOptimizeVecArgCallConv

- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLBase.td
- polygeist/include/mlir/Dialect/Polygeist/IR/PolygeistBase.td
- polygeist/tools/cgeist/Test/Verification/alignof.cpp
- polygeist/tools/cgeist/Test/Verification/sizeof.c
- polygeist/tools/cgeist/Test/Verification/sycl/constructors.cpp
Prepare for https://github.com/llvm/llvm-project/commit/863c346209e27d22157fad21d0fd730e710a3441, which will set this by default.
After that commit is in our branch, `usePropertiesForAttributes` will no longer be needed in dialect definitions.
> [SYCL-MLIR] Use properties as storage for attributes

- polygeist/lib/Dialect/Polygeist/Transforms/BareMemRefToLLVM.cpp
- polygeist/test/polygeist-opt/bareptrlowering.mlir
Lower `memref.get_global` to `llvm.getelementptr` using the correct element type, i.e., that of the global, which will be an `llvm.array`.
> [SYCL-MLIR][polygeist-to-llvm] Fix `memref.get_global` lowering

- polygeist/tools/cgeist/Lib/CGExpr.cc
- polygeist/tools/cgeist/Lib/CodeGenTypes.cc
- polygeist/tools/cgeist/Test/Verification/sycl/builtin_cache.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/builtin_types.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/image.cpp
- sycl/test-e2e/xfail_tests.txt
With the switch to opaque pointers, image types are now represented by LLVM TargetExtensionTypes. These are not allowed as element type of a `memref`. 
This therefore changes the handling to use `llvm.ptr` instead, to avoid this error. 
It re-enables three SYCL end-to-end tests that were put on the list of expected failures as part of #10941.
> [SYCL-MLIR] Fix image type handling

- libdevice/cmath_wrapper.cpp
- libdevice/cmath_wrapper_fp64.cpp
- libdevice/device_math.h
- libdevice/fallback-cmath-fp64.cpp
- libdevice/fallback-cmath.cpp
- sycl/test-e2e/DeviceLib/cmath_fp64_test.cpp
- sycl/test-e2e/DeviceLib/cmath_test.cpp
Same as https://github.com/intel/llvm/pull/10904 for cmath func `floor`
> [SYCL] Add missing cmath builtin

- clang/lib/CodeGen/ItaniumCXXABI.cpp
Fixed CodeGenSYCL/virtual-types.cpp
> [SYCL-WEB] Sync VTable related customization with sycl branch

- sycl/unittests/Extensions/CommandGraph.cpp
Adds a mutex to prevent races when inserting data into the STL map.
This PR addresses issue https://github.com/intel/llvm/issues/10985 
(i.e. it fixes the post-commit CI fail of PR https://github.com/intel/llvm/pull/10964 (https://github.com/intel/llvm/actions/runs/6001360490/job/16275376437)
> [SYCL][Graph] Fix unit test multithread finalize bug

- sycl/plugins/unified_runtime/ur/adapters/cuda/image.cpp
https://github.com/intel/llvm/pull/10691 missed these extra cases. This PR adds the needed ifdefs
> [UR][CUDA] Ifdef remaining CUDA 11 datatypes

- mlir-sycl/lib/Conversion/SYCLToLLVM/DPCPP.cpp
- mlir-sycl/test/Conversion/SYCLToLLVM/sycl-methods-to-llvm.mlir
Use correct base type for `llvm.getelementptr` operation: it should be `nd_item`, not `group`.
> [SYCL-MLIR][Opaque] Fix `nd_item.get_group_linear_id` lowering

- sycl/test-e2e/KernelAndProgram/level-zero-link-flags.cpp
- sycl/test-e2e/KernelAndProgram/level-zero-static-link-flow.cpp
Level Zero adapter does not support building programs with multiple devices yet. Modify the test to always use a single device to avoid failures on multi-GPU machines.
> [SYCL] Fix Level Zero tests on machines with multiple GPUs

- .github/workflows/sycl_post_commit.yml
for LLVM and SPIRV pulldown PR like https://github.com/intel/llvm/pull/11031
We are running duplicate post-commit tests,
one triggered on `push`, the other triggered on `pull request`.
This is to remove the branch from `push` trigger, and only do the test
on `pull request`.
> [CI] Avoid duplicate run for pulldown PR

- sycl/plugins/unified_runtime/ur/adapters/level_zero/event.cpp
- sycl/test-e2e/Plugin/level_zero_barrier_optimization.cpp
Don't insert zeCommandListAppendWaitOnEvents/zeCommandListAppendSignalEvent for queue::ext_oneapi_submit_barrier() if we have in-order queue and all events in the waitlist are from the same queue.
> [SYCL] Optimize urEnqueueEventsWaitWithBarrier for in-order queues

- llvm/lib/SYCLLowerIR/ESIMD/LowerESIMDSlmReservation.cpp
- llvm/test/SYCLLowerIR/ESIMD/slm_init_same_bb.ll
We may end up with the basic block containing the slm_init call having multiple predecessors, causing an assert. This pattern will not cause any problems as the slm_init size is the same, so just skip these basic blocks.
> [SYCL][ESIMD] Relax LowerESIMDSlmReservation assert

- sycl/pi_win_proxy_loader/pi_win_proxy_loader.cpp
- sycl/source/detail/pi.cpp
- sycl/source/detail/windows_pi.cpp
Wrongfully size of the output buffer in bytes is provided to GetModuleFileName.
Provide size in wchars instead.
> [SYCL] Provide size in wchars (not bytes) to GetModuleFileName

- sycl/source/detail/builtins_math.cpp
- sycl/test/regression/host_tanpi_double_accuracy.cpp
This commit improves the accuracy of the host-side tanpi implementation for double by reducing the argument to the [0.0, 1.0) range for uniformity and flipping the computation of tan.
> [SYCL] Improve accuracy of double tanpi host implementation

- llvm/lib/SYCLLowerIR/PrepareSYCLNativeCPU.cpp
- sycl/doc/design/SYCLNativeCPU.md
- sycl/include/CL/__spirv/spirv_vars.hpp
- sycl/include/sycl/detail/native_cpu.hpp
- sycl/test/check_device_code/native_cpu/native_cpu_builtins.cpp
- sycl/test/native_cpu/local-id-range.cpp
This PR makes it so we are using the function declarations for SPIRV work item builtins, the same as the NVIDIA and AMD targets. This greatly simplifies processing the builtins in our passes.
Due to differences in mangling, this PR temporary disable windows support for SYCL Native CPU, we will address this ASAP in a follow up PR.
> [SYCL][NATIVECPU] Use declarations for SPIRV work item builtins

- sycl/test-e2e/Matrix/SG32/joint_matrix_colA_rowB_colC.cpp
- sycl/test-e2e/Matrix/SG32/joint_matrix_down_convert.cpp
- sycl/test-e2e/Matrix/SG32/joint_matrix_out_bounds.cpp
- sycl/test-e2e/Matrix/SG32/joint_matrix_transposeC.cpp
- sycl/test-e2e/Matrix/SG32/joint_matrix_unaligned_k.cpp
- sycl/test-e2e/Matrix/joint_matrix_down_convert_impl.hpp
These tests were added for SG=16, but not for SG=32. Fixing that:
joint_matrix_colA_rowB_colC.cpp,
joint_matrix_down_convert.cpp,
joint_matrix_out_bounds.cpp,
joint_matrix_transposeC.cpp,
joint_matrix_unaligned_k.cpp
> [SYCL][Joint Matrix] Add missing tests for SG=32

- sycl/test-e2e/Matrix/SG32/joint_matrix_tf32.cpp
Enabled test on GPU. The test is expected to fail on CPU still due to functionality not yet implemented.
> [SYCL][Joint Matrix] Update xfail marking for SG32/joint_matrix_tf32.cpp

- sycl/plugins/unified_runtime/ur/adapters/cuda/usm.cpp
Resolve same issue fixed in [PR](https://github.com/intel/llvm/pull/10034)
> [SYCL][CUDA] Reintroduce removing of size checks from USM allocations

- mlir/lib/Dialect/GPU/TransformOps/GPUTransformOps.cpp
Mark helper functions as static to avoid collision with functions in Polygeist by the same name.
> [SYCL-MLIR] Mark helper functions static

- clang/include/clang/Basic/BuiltinsNVPTX.def
- clang/test/CodeGen/builtins-nvptx.c
- clang/test/CodeGenCUDA/bf16.cu
- llvm/include/llvm/IR/IntrinsicsNVVM.td
- llvm/lib/IR/AutoUpgrade.cpp
- llvm/lib/Target/NVPTX/NVPTXAsmPrinter.cpp
- llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp
- llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.h
- llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp
- llvm/lib/Target/NVPTX/NVPTXInstrInfo.td
- llvm/lib/Target/NVPTX/NVPTXIntrinsics.td
- llvm/lib/Target/NVPTX/NVPTXMCExpr.cpp
- llvm/lib/Target/NVPTX/NVPTXMCExpr.h
- llvm/lib/Target/NVPTX/NVPTXSubtarget.cpp
- llvm/lib/Target/NVPTX/NVPTXSubtarget.h
- llvm/lib/Target/NVPTX/NVPTXTargetTransformInfo.cpp
- llvm/test/CodeGen/NVPTX/bf16-instructions.ll
- llvm/test/CodeGen/NVPTX/convert-sm80.ll
- llvm/test/CodeGen/NVPTX/f16-instructions.ll
- llvm/test/CodeGen/NVPTX/math-intrins-sm80-ptx70-autoupgrade.ll
- llvm/test/CodeGen/NVPTX/math-intrins-sm86-ptx72-autoupgrade.ll
- llvm/test/CodeGen/NVPTX/param-load-store.ll
This reverts commit bfc1956b71fb0941d6abaf9bce726b4d1c012746.
With workaround landed in https://github.com/intel/llvm/pull/10695, we should be able to reland the community commit https://github.com/llvm/llvm-project/commit/250f2bb2c6a9c288faeb821585e9394697c561d8 now. This revert the revert to reland it.
> [SYCL][CUDA] Reland adding bf16 support to NVPTX

- sycl/plugins/unified_runtime/ur/adapters/level_zero/queue.cpp
- sycl/test-e2e/Plugin/interop-l0-direct.cpp
Correction to make_queue functionality. During the transition from L0 Plugin to UR Adapter a line of code in the make queue function was inadvertenty dropped. This change restores it and also modifies the associated test to do more careful checking.
> [SYCL] [UR] Fix for make_queue.

- sycl/include/syclcompat/id_query.hpp
- sycl/include/syclcompat/launch.hpp
- sycl/include/syclcompat/memory.hpp
- sycl/include/syclcompat/syclcompat.hpp
- sycl/test-e2e/syclcompat/common.hpp
- sycl/test-e2e/syclcompat/id_query/id_query.cpp
- sycl/test-e2e/syclcompat/id_query/id_query_fixt.hpp
- sycl/test-e2e/syclcompat/launch/launch.cpp
- sycl/test-e2e/syclcompat/launch/launch_fixt.hpp
- sycl/test-e2e/syclcompat/memory/local_memory.cpp
- sycl/test-e2e/syclcompat/memory/memory_common.hpp
- sycl/test-e2e/syclcompat/memory/memory_fixt.hpp
SYCLcompat primary goals and features are documented [here](https://intel.github.io/llvm-docs/syclcompat/README.html).
The PR includes the helper code to launch device code through the `launch<F>` mechanism, and the wrappers to the free function queries.
> [SYCL][COMPAT] Added id_query and launch headers

- clang/include/clang/Driver/Options.td
- clang/lib/Driver/ToolChains/Clang.cpp
- clang/test/Driver/sycl-spirv-metadata.cpp
Preserving this nonsemantic metadata can have value for internal testing, as it contains some extra information about kernel data types that may be lost otherwise.
> [SYCL][Driver] Add hidden option to preserve device metadata in SPIR-V

- sycl/test-e2e/Graph/Explicit/depends_on.cpp
- sycl/test-e2e/Graph/Explicit/enqueue_ordering.cpp
- sycl/test-e2e/Graph/Explicit/node_ordering.cpp
- sycl/test-e2e/Graph/Explicit/single_node.cpp
- sycl/test-e2e/Graph/Inputs/buffer_ordering.cpp
- sycl/test-e2e/Graph/Inputs/dotp_buffer_reduction.cpp
- sycl/test-e2e/Graph/Inputs/dotp_usm_reduction.cpp
- sycl/test-e2e/Graph/Inputs/empty_node.cpp
- sycl/test-e2e/Graph/Inputs/repeated_exec.cpp
- sycl/test-e2e/Graph/Inputs/sub_graph_execute_without_parent.cpp
- sycl/test-e2e/Graph/Inputs/sub_graph_multiple_submission.cpp
- sycl/test-e2e/Graph/Inputs/sub_graph_nested.cpp
- sycl/test-e2e/Graph/Inputs/sub_graph_reduction.cpp
- sycl/test-e2e/Graph/Inputs/sub_graph_two_parent_graphs.cpp
- sycl/test-e2e/Graph/Inputs/usm_fill.cpp
- sycl/test-e2e/Graph/Inputs/usm_fill_host.cpp
- sycl/test-e2e/Graph/Inputs/usm_fill_shared.cpp
- sycl/test-e2e/Graph/RecordReplay/dotp_in_order.cpp
- sycl/test-e2e/Graph/RecordReplay/dotp_in_order_with_empty_nodes.cpp
- sycl/test-e2e/Graph/RecordReplay/dotp_multiple_queues.cpp
- sycl/test-e2e/Graph/RecordReplay/sub_graph_in_order.cpp
- sycl/test-e2e/Graph/RecordReplay/temp_scope.cpp
- sycl/test-e2e/Graph/RecordReplay/usm_copy_in_order.cpp
- sycl/test-e2e/Graph/graph_common.hpp
- Removes usage of float from graph E2E tests to avoid precision differences between host and some GPUs
Addresses issue reported in #10860
> [SYCL][Graph][E2E] Remove float usage from Graph tests

- llvm/lib/Target/AMDGPU/SIModeRegisterDefaults.cpp
This is cherry-pick of 003cf293f632a to fix the windows build failures first.
> AMDGPU: Use const instead of constexpr to try fixing MSVC bot

- sycl/include/sycl/handler.hpp
- sycl/test/basic_tests/handler/parallel_for_arg_restrictions.cpp
According to the SYCL 2020 specification:
> The function object that represents the SYCL kernel function must take
one of: 1) a single SYCL nd_item parameter, 2) a single generic parameter (template parameter or auto) that will be treated as an nd_item parameter, 3) any other type converted from SYCL nd_item, representing the currently executing work-item within the range specified by the nd_range parameter.
However, the current implementation allows also sycl::item and any argument types convertible from a sycl::item. This commit addresses this discrepancy by disallowing anything other than sycl::nd_item and all types convertible from sycl::nd_item in this kind of parallel_for. Since this may break existing code, this new restriction is guarded by the SYCL2020_CONFORMANT_APIS …
> [SYCL] Restrict nd_range parallel_for to nd_item

- clang/lib/Frontend/InitPreprocessor.cpp
- llvm/test/SYCLLowerIR/ESIMD/acc_ptr.ll
- sycl/include/sycl/ext/intel/esimd/memory.hpp
- sycl/test-e2e/ESIMD/api/simd_view_copy_move_assign.cpp
- sycl/test/esimd/intrins_trans.cpp
* Support 64-bit offset if scalar_load() and scalar_store()
* Fix simd_view_copy_move_assign.cpp test
* Fix the test intrins_trans.cpp
This patch is only the preliminary step to final enabling of force-stateless-memory mode that should be finalized here: https://github.com/intel/llvm/pull/9452
> [ESIMD] Prepare for enabling of enforcing of stateless memory mode

- sycl/doc/syclcompat/README.md
- sycl/include/syclcompat/memory.hpp
- sycl/test-e2e/syclcompat/memory/memory_management_test1.cpp
- sycl/test-e2e/syclcompat/memory/memory_management_test2.cpp
- sycl/test-e2e/syclcompat/memory/memory_management_test3.cpp
This PR extends the memory wrapper of SYCLcompat to support allocating read only memory.
To allow the allocation of `device_memory` directly for source to source translation:
- Extended `device_memory` to support a queue parameter in its constructor, which defaults to `syclcompat::get_default_queue`
- Added device_read_only property to device memory if usm device read only extension is available for `memory_region::constant`
Documentation was already updated, except for the usm device read only extension
> [SYCL][COMPAT] Added constant memory_region for read_only memory

- sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp
We still have the overloads that take execSize as a runtime parameter, so we can't fix those ones, but we can fix the ones with it as a template parameter.
This is locked down with existing tests.
> [SYCL][ESIMD] Make raw_send mask size match exec size where possible

- sycl/source/detail/global_handler.cpp
in unloadPlugins we call piTearDown. all pi calls in sycl RT are wrapped with xpti begin/end trace if xpti tracing is enabled. It means that we could call xpti methods in unloadPlugins that requires to keep xpti objects alive.
> [SYCL] Release xpti objects after plugins unloading

- clang/test/SemaSYCL/device_has_ast.cpp
- clang/test/SemaSYCL/uses_aspects_ast.cpp
Fixes the following LIT tests:
Clang :: SemaSYCL/device_has_ast.cpp
Clang :: SemaSYCL/uses_aspects_ast.cpp
> [Clang] Update LIT tests after typo was fixed in 54091d37f28c24fa810adf2914af9299c305dd83

- sycl/plugins/unified_runtime/pi2ur.hpp
- sycl/source/detail/device_impl.cpp
- sycl/source/detail/global_handler.cpp
- sycl/source/detail/plugin.hpp
- Track when a plugin has been teardown and prevent calls to Device Release after teardown during device destruction.
> [SYCL] Prevent call to Device Release in plugins after piTearDown

- clang/include/clang/Basic/AttrDocs.td
- clang/include/clang/Basic/DiagnosticSemaKinds.td
- clang/lib/Sema/SemaStmtAttr.cpp
- clang/test/CodeGenSYCL/intel-fpga-loops.cpp
- clang/test/SemaSYCL/intel-fpga-loops.cpp
The backend doesn't support max_interleaving attribute argument > 1 at the moment.
This patch adds error diagnostic for [[intel::max_interleaving(int_argument > 1)]].
Also this patch updates max_interleaving tests based on requirement and non-neagive diagnostic messages to avoid any confusion.
> [SYCL][FPGA] Disallow 'max_interleaving' attribute argument > 1

- clang/lib/Sema/SemaSYCL.cpp
This PR improves compilation time when there are many simple range (i.e. not nd_range) parallel_for kernels and range rounding is enabled. 
More background: for the range rounding functionality, the user provided lambda is wrapped within another lambda. However, there could be attributes applied on the user lambda which are then not present on the wrapped lambda. `copySYCLKernelAttrs` is given the declaration of the wrapped lambda's `operator()` and needs to recurse through the definition to find the `operator()` declaration of the user provided lambda, and then copy the attributes up. Clearly, this does not require constructing the call graph of the whole translation unit, but only the call graph starting from the wrapped lambda.
E.g. consider the (somewhat silly) example:
```c++ …
```
> [SYCL] Don't construct the full call graph in copySYCLKernelAttrs

- sycl/source/detail/scheduler/graph_builder.cpp
- sycl/test-e2e/Scheduler/HostTaskSubBuffer.cpp
- sycl/test-e2e/Scheduler/SubBufferRemapping.cpp
sub-buffer req does not have to be remapped when setting up a host task ( the main Alloca has that covered)
> [SYCL] only remap linked host memory

- polygeist/lib/Conversion/PolygeistToLLVM/PolygeistToLLVM.cpp
- polygeist/tools/cgeist/Lib/clang-mlir.cc
Use address-space cast instead of illegal bitcast to convert between pointers in different address spaces in codegen.
> [SYCL-MLIR] Fix wrong bitcast in cgeist code-gen

- clang/lib/CodeGen/CGBuiltin.cpp
Commit 28b9e76be1be119745e903e7cb2433c35dad7152 merged 'main' to
'sycl-web'. The conflict resolution for this merge accidentally removed
logic preventing builtins from being emitted for SYCL device code on the
NVPTX target. This patch re-adds that logic.
Fixes the following LIT regressions:
Clang :: CodeGenSYCL/sycl-libdevice-cmath.cpp
> [CG] Re-add code accidentally removed in conflict resolution.

- clang-tools-extra/clangd/index/SymbolCollector.cpp
> Cherry pick of '[clangd] Fix buildbot breakages from stemming from 64366d4935d3c56ce5906a321edb2e91d4f886bc'

- sycl/doc/extensions/experimental/sycl_ext_oneapi_bindless_images.asciidoc
- sycl/plugins/unified_runtime/ur/adapters/cuda/image.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/image.hpp
- sycl/test-e2e/bindless_images/read_norm_types.cpp
- Support was added for the following image channel types:
- `unorm_int8`
- `unorm_int16`
- `snorm_int8`
- `snorm_int16`
- Reading these types through `read_image` returns the denormalized floating point data.
- A test was added for these new types.
- Support for the following packed normalized image channel types was removed from the proposal:
- `unorm_short_565`
- `unorm_short_555`
- `unorm_int_101010`
- This was done due to lack of device support. If the need for these types arises in the future, we can revisit support for these types.
> [SYCL][CUDA][Bindless] Add support for normalized channel types

- sycl/plugins/hip/CMakeLists.txt
- sycl/plugins/unified_runtime/CMakeLists.txt
- sycl/plugins/unified_runtime/ur/adapters/hip/context.cpp
- sycl/plugins/unified_runtime/ur/adapters/hip/context.hpp
- sycl/plugins/unified_runtime/ur/adapters/hip/device.hpp
- sycl/plugins/unified_runtime/ur/adapters/hip/ur_interface_loader.cpp
- sycl/plugins/unified_runtime/ur/adapters/hip/usm.cpp
- sycl/plugins/unified_runtime/ur/adapters/hip/usm.hpp
> [SYCL][UR] Implement usm memory pool for hip adapter.

- clang/include/clang/Basic/DiagnosticSemaKinds.td
- clang/lib/Sema/SemaDeclAttr.cpp
This is a followup to https://github.com/intel/llvm/pull/11044. The diagnostic should have been updated to reflect the change.
> [SYCL][NFC] Correct stale diagnostic

- sycl/doc/extensions/proposed/sycl_ext_intel_cache_controls.asciidoc
This is a proposal to add cache control properties to annotated pointers to control at a fine grain where and how data is cached.
> [SYCL] Proposed cache control properties for annotated_ptr.

- clang/include/clang/Sema/Sema.h
- clang/lib/CodeGen/CodeGenModule.cpp
- clang/test/CodeGenSYCL/Inputs/sycl.hpp
- clang/test/CodeGenSYCL/check-direct-attribute-propagation.cpp
- clang/test/CodeGenSYCL/device_global.cpp
- clang/test/CodeGenSYCL/device_has.cpp
- clang/test/CodeGenSYCL/function-attrs.cpp
- clang/test/CodeGenSYCL/functionptr-addrspace.cpp
- clang/test/CodeGenSYCL/loop_unroll.cpp
- clang/test/CodeGenSYCL/nontrivial_device_copyable.cpp
- clang/test/CodeGenSYCL/sycl-cuda-host-device-functions.cu
- clang/test/CodeGenSYCL/sycl-device-static-init.cpp
- clang/test/CodeGenSYCL/uses_aspects.cpp
- sycl/test/check_device_code/device_has.cpp
- sycl/test/extensions/properties/properties_kernel_device_has_macro.cpp
In getLLVMLinkageForDeclarator, CUDA device functions are given internal linkage to allow improved IPO. The same optimizations would also be useful for SYCL. However, as multiple translation units are a possibility here, it cannot be done exactly the same way. There are a number of extra considerations that need to be made.
- If a device function or object is annotated with the SYCL_EXTERNAL macro, it may be called from a different module and its handling should not be touched.
- If a device function or object is not annotated with the SYCL_EXTERNAL macro, it may not be called from a different translation unit unless that other translation unit provides its own definition of it. As such, if other optimizations remove all references in the current module, the function or object itself can …
> [SYCL] Change linkage to linkonce_odr unless SYCL_EXTERNAL.

- mlir-sycl/include/mlir/Dialect/SYCL/Analysis/ConstructorBaseAnalysis.h
- mlir-sycl/include/mlir/Dialect/SYCL/Analysis/SYCLAccessorAnalysis.h
- mlir-sycl/include/mlir/Dialect/SYCL/Analysis/SYCLBufferAnalysis.h
- mlir-sycl/include/mlir/Dialect/SYCL/Analysis/SYCLIDAndRangeAnalysis.h
- mlir-sycl/include/mlir/Dialect/SYCL/Analysis/SYCLNDRangeAnalysis.h
- mlir-sycl/lib/Dialect/SYCL/Analysis/CMakeLists.txt
- mlir-sycl/lib/Dialect/SYCL/Analysis/SYCLAccessorAnalysis.cpp
- mlir-sycl/lib/Dialect/SYCL/Analysis/SYCLBufferAnalysis.cpp
- mlir-sycl/lib/Dialect/SYCL/Analysis/SYCLIDAndRangeAnalysis.cpp
- mlir-sycl/lib/Dialect/SYCL/Analysis/SYCLNDRangeAnalysis.cpp
- mlir-sycl/lib/Dialect/SYCL/Transforms/CMakeLists.txt
- mlir-sycl/lib/Dialect/SYCL/Transforms/ConstantPropagation.cpp
- mlir-sycl/test/CMakeLists.txt
- mlir-sycl/test/lib/CMakeLists.txt
- mlir-sycl/test/lib/Dialect/CMakeLists.txt
- mlir-sycl/test/lib/Dialect/SYCL/CMakeLists.txt
- mlir-sycl/test/lib/Dialect/SYCL/TestAccessorAnalysis.cpp
- mlir-sycl/test/lib/Dialect/SYCL/TestBufferAnalysis.cpp
- mlir-sycl/test/lib/Dialect/SYCL/TestIDAndRangeAnalysis.cpp
- mlir-sycl/test/lib/Dialect/SYCL/TestNDRangeAnalysis.cpp
- polygeist/include/mlir/Dialect/Polygeist/Analysis/MemoryAccessAnalysis.h
- polygeist/lib/Dialect/Polygeist/Analysis/CMakeLists.txt
- polygeist/lib/Dialect/Polygeist/Analysis/MemoryAccessAnalysis.cpp
- polygeist/lib/Dialect/Polygeist/Transforms/LoopInternalization.cpp
- polygeist/test/lib/Dialect/Polygeist/TestMemoryAccessAnalysis.cpp
- polygeist/tools/polygeist-opt/CMakeLists.txt
Refactor the analyses deriving properties of interest about SYCL objects from their construction in host code. 
* Move the analyses from the `polygeist` folder to the `mlir-sycl` directory.
* To that end, invert the dependency relation between the libraries. The more specialized SYCL analysis library (`MLIRSYCLAnalysis`) now depends on the less specialized Polygeist analysis library (`MLIRPolygeistAnalysis`). Transforms from both Polygeist and SYCL can still use the SYCL-specific analyses if required.
* Factor out common code shared by the four analyses into a CRTP base class.
Tests for the analysis have not been moved, as this would require `sycl-mlir-opt` to be significantly extended and define the same interface extensions (e.g., for `memref`) as `polygeist-opt`.
> [SYCL-MLIR][NFC] Refactor SYCL analyses

- sycl/plugins/unified_runtime/ur/adapters/hip/device.hpp
- sycl/plugins/unified_runtime/ur/adapters/hip/usm.cpp
Fixes https://github.com/intel/llvm/actions/runs/6154418223/job/16699759620
> [SYCL][UR] Remove unused MaxAllocSize member variable and fix unused parameter 'Alignment' warning

- sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp
It seemed to work before, but after https://github.com/intel/llvm/commit/cc3fd43996456b397117ea33bf8c0fef5b16959e where we started to use execSize for the mask size, we hit a compile time assert because we try to make a 0-length mask.
This is locked down with existing tests, but they run on PVC only. I manually confirmed this fixes it.
> [SYCL][ESIMD] Use correct execSize in LSC functions

- sycl/plugins/unified_runtime/ur/adapters/level_zero/context.cpp
Modified the return value for UR_CONTEXT_INFO_USM_FILL2D_SUPPORT and UR_CONTEXT_INFO_USM_MEMCPY_2D_SUPPORT to return uint8_t instead of uint32_t to comply with unified-runtime conformance test.
> [SYCL][UR][L0] Use uint8_t instead of uint32_t for 2 cases of urContextGetInfo

- mlir-sycl/CMakeLists.txt
- mlir-sycl/test/Analysis/accessor-analysis.mlir
- mlir-sycl/test/Analysis/buffer-analysis.mlir
- mlir-sycl/test/Analysis/id-range-analysis.mlir
- mlir-sycl/test/Analysis/local-accessor-analysis.mlir
- mlir-sycl/test/Analysis/nd-range-analysis.mlir
- mlir-sycl/tools/sycl-mlir-opt/CMakeLists.txt
- mlir-sycl/tools/sycl-mlir-opt/sycl-mlir-opt.cpp
- polygeist/tools/polygeist-opt/CMakeLists.txt
- polygeist/tools/polygeist-opt/polygeist-opt.cpp
Migrate the tests for the SYCL constructor-based analyses to the
mlir-sycl directory.
To that end, migrate the test passes from polygeist-opt to
sycl-mlir-opt.
Signed-off-by: Lukas Sommer <lukas.sommer@codeplay.com>
> [SYCL-MLIR][NFC] Migrate SYCL analyses tests

- sycl/test-e2e/NonUniformGroups/fixed_size_group.cpp
- sycl/test-e2e/NonUniformGroups/fixed_size_group_algorithms.cpp
- sycl/test-e2e/NonUniformGroups/tangle_group_algorithms.cpp
- sycl/test-e2e/SubGroupMask/Basic.cpp
Some tests weren't exiting early if size 32 sgs are not supported on device. This fixes this behaviour.
> [SYCL] Add early exit for devices that don't support size 32 subgroups

- sycl/doc/extensions/experimental/sycl_ext_oneapi_bindless_images.asciidoc
Add the missing `sycl::queue` overload variants to the standalone functions in the proposal.
> [Bindless][Proposal] Add overload with sycl::queue to standalone functions

- llvm/lib/SYCLLowerIR/RenameKernelSYCLNativeCPU.cpp
Actually use `ModuleChange` variable, so the condition is not always falling to "false" branch
> [SYCL][NATIVECPU] Fix unused condition

- sycl/test-e2e/bindless_images/read_sampled.cpp
This PR remove the deprecation warning from using `sycl::fract` with raw pointer in test `read_sampled.cpp`by the use of `multi_ptr` as argument.
> [SYCL][Bindless] Remove deprecation warning from sycl::fract

- sycl/plugins/unified_runtime/CMakeLists.txt
- sycl/plugins/unified_runtime/ur/adapters/level_zero/context.cpp
- sycl/plugins/unified_runtime/ur/adapters/level_zero/context.hpp
- sycl/plugins/unified_runtime/ur/adapters/level_zero/usm.cpp
- sycl/plugins/unified_runtime/ur/adapters/level_zero/usm.hpp
- sycl/test-e2e/USM/usm_pooling.cpp
This also makes SharedReadOnly allocations tracking obsolete.
> [SYCL][UR][L0] Replace memory type look-up with UMF tracking

- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLTypes.h
- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLTypes.td
- mlir-sycl/lib/Dialect/SYCL/IR/SYCLOps.cpp
- mlir-sycl/lib/Dialect/SYCL/IR/SYCLTypes.cpp
- polygeist/tools/cgeist/Lib/clang-mlir.cc
Define `isBaseClass` checking DPC++'s class hierarchy.
> [SYCL-MLIR][sycl] Define `isBaseClass` function

- sycl/source/detail/device_impl.cpp
- sycl/source/detail/plugin.hpp
- Using Teardown tracking of "pluginReleased", check if the plugin is released before each call to a plugin's functions.
> [SYCL] Check if Plugin before all calls to a plugin API

- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLTypes.td
Add trait expressing `sycl::local_accessor<DataT, Dimensions>` derives from `sycl::detail::OwnerLessBase<local_accessor<DataT, Dimensions>>`.
This is needed so that we can `sycl.cast` from `local_accessor` to `OwnerLessBase`,
making our dialect more DPC++-specific, but also making it work with current's
approach.
> [SYCL-MLIR][sycl] Add `SYCLInheritanceTypeTrait<OwnerLessBaseType>` trait to `LocalAccessor`

- libdevice/cmath_wrapper.cpp
- libdevice/cmath_wrapper_fp64.cpp
`nearbyint` was missing for NVPTX. `nearbyint` is not found in `libclc`, so instead of the usual `libdevice->libclc->native_bc_lib` it was necessary to just skip libclc and go straight to the `__nv` symbols which are found in nvvm libdevice.
> [SYCL][CUDA] Add missing nearbyint

- mlir/include/mlir/IR/Block.h
- mlir/include/mlir/IR/OpBase.td
- mlir/include/mlir/IR/OpDefinition.h
- mlir/lib/IR/Block.cpp
- mlir/test/mlir-tblgen/gen-dialect-doc.td
- mlir/tools/mlir-tblgen/OpFormatGen.cpp
DO NOT SQUASH AND MERGE THIS PR.
Avoid member functions duplication caused by SingleBlockImplicitTerminator now implying SingleBlock (since 0ac21e654f194a0f7c9f5afe42e11924c546f89e). Use `std::enable_if` to provide different definitions to `push_back` and `insert`.
>  [mlir] Remove duplicated SingleBlockImplicitTerminator member functions 

- polygeist/include/mlir/Dialect/Polygeist/IR/PolygeistOps.td
- polygeist/lib/Conversion/PolygeistToLLVM/PolygeistToLLVM.cpp
- polygeist/lib/Dialect/Polygeist/IR/PolygeistOps.cpp
Verify `llvm.ptr`'s address space and `memref` memory space are compatible:
- At verification time, we can check whether both use their defaults, which are compatible, or the memory space is expressed as an integer attribute with the same value as the address space.
- At conversion time, we can extend this by checking the converted memory space attribute is compatible with the address space.
> [SYCL-MLIR][polygeist] Verify `pointer2memref` and `memref2pointer`

- sycl/source/detail/queue_impl.cpp
- sycl/source/detail/queue_impl.hpp
- sycl/source/detail/scheduler/commands.cpp
- sycl/source/detail/scheduler/commands.hpp
- sycl/source/detail/scheduler/graph_builder.cpp
- sycl/source/detail/scheduler/scheduler.cpp
- sycl/source/detail/scheduler/scheduler.hpp
The KernelFusionCmd keeps a references to the queue on which it was submitted. However these commands are also kept on the side in order to ensure event validity and are only reset when start fusion is called again on the same queue.
This forces queue_impl and events to be kept alive as the command keeps the last reference until the sycl shutdown procedure.
The patch forces 1) the command to reset it pointers to the queue once enqueued and 2) to clean up the KernelFusionCmd attached to the queue to free up events.
Note: there is no new test as kernel fusion already cover this and I'm not too sure on how to approach it. I'm happy to try out any suggestion.
> [SYCL][KernelFusion] Ensure queue_impl is not unnecessarily referenced

- libclc/ptx-nvidiacl/libspirv/images/image.cl
- sycl/test-e2e/bindless_images/mipmap/mipmap_read_1D.cpp
- sycl/test-e2e/bindless_images/mipmap/mipmap_read_2D.cpp
- sycl/test-e2e/bindless_images/mipmap/mipmap_read_3D.cpp
This commit adds support for data types smaller then 32-bit for mipmaps.
The added types are short, short2, short4, ushort, ushort2, ushort4, char, char2, char4, uchar, uchar2, uchar4, half, half2, and half4. Mipmap tests have been modified to test all valid data types. `image.cl` has also been refactored to reduce code duplication.
> [SYCL][Bindless] Add support for mipmap data types smaller than 32-bit

- clang/test/CodeGenSYCL/sycl-cuda-host-device-functions.cu
- llvm/cmake/modules/TableGen.cmake
- mlir/lib/Dialect/Vector/Transforms/LowerVectorTranspose.cpp
- mlir/lib/Dialect/Vector/Utils/VectorUtils.cpp
- mlir/lib/Dialect/X86Vector/Transforms/AVXTranspose.cpp
- mlir/test/Dialect/Vector/vector-transpose-lowering.mlir
- mlir/test/Target/LLVMIR/llvmir-intrinsics.mlir
- sycl/test-e2e/Matrix/Legacy/joint_matrix_int8_vnni_impl.hpp
- utils/bazel/llvm-project-overlay/mlir/BUILD.bazel
https://github.com/intel/llvm/pull/11201/commits/8e06edfccb8436a23a9ef206745280f4d63fe70c: `INTEL_SYCL_OPAQUEPOINTER_READY` was removed, so user of it can also be removed.
https://github.com/intel/llvm/pull/11201/commits/736c79bcc4adf97838e89de89114b4339c07ae92: This upstream commit is missed from merging.
https://github.com/intel/llvm/pull/11201/commits/4684cb3c4d62b81c139da7047843a085158af2c5: Non functional changes to be more similar to `sycl` branch to reduce chances of merge conflict.
Please do not squash and merge this PR.
> [SYCL-MLIR] Sync with `sycl` branch 

- sycl/test-e2e/Regression/same_unnamed_kernels.cpp
I believe the issue was that the tests wasn't getting the CUDA target flags properly and this would have been fixed as part of the E2E tests rework (in https://github.com/intel/llvm/pull/9336).
Fixes: https://github.com/intel/llvm/issues/9174
> [SYCL][CUDA] Re-enable same_unnamed_kernels test

- llvm/lib/SYCLLowerIR/SYCLPropagateAspectsUsage.cpp
- llvm/test/SYCLLowerIR/PropagateAspectsUsage/global-value.ll
- sycl/test-e2e/Regression/pf-wg-atomic64.cpp
Before this PR, the `pf-wg-atomic64.cpp` (from this PR) fails because the `atomic64` aspect was not propagated to the calling kernel. The reason is:
- With opaque pointers disabled, since the `this` parameter of the constructor of `atomic_ref` would have a type of `atomic_ref*`, the call to the constructor of `atomic_ref` would be enough to propagate the `atomic64` aspect to the kernel. With opaque pointers enabled, this would not be the case: the `this` parameter would just be a `ptr`. 
- Additionally, for some reason I am unsure of, the code generated for `parallel_for_work_group` (and not, say, for `parallel_for`) has the pointer for `feature` generated as a global variable instead of generated from an `alloca` instruction. If there were an `alloca` of an `atomic_ref`, there would be …
> [SYCL] Propagate aspects from global variables

- sycl/doc/extensions/experimental/sycl_ext_matrix/sycl_ext_intel_matrix.asciidoc
- sycl/doc/extensions/experimental/sycl_ext_matrix/sycl_ext_oneapi_matrix.asciidoc
@gmlueck, in https://github.com/intel/llvm/pull/7964, we explicitly deleted the copy ctor and assign op because we added `joint_matrix_copy` that is used to actually copy matrix data.
However, when deleting them in implementation, failures occur as `joint_matrix_mad` uses them.
This PR proposes to change the signature of `joint_matrix_mad` so these ctors are not used.
> [SYCL][Matrix spec] keep deletion of assign op and copy ctor but change signature of joint_matrix_mad

- mlir/include/mlir/Dialect/LLVMIR/LLVMOps.td
- mlir/lib/Dialect/LLVMIR/IR/LLVMDialect.cpp
- mlir/lib/Target/LLVMIR/ModuleImport.cpp
- mlir/lib/Target/LLVMIR/ModuleTranslation.cpp
- mlir/test/Dialect/LLVMIR/global.mlir
- mlir/test/Dialect/LLVMIR/invalid.mlir
- mlir/test/Target/LLVMIR/Import/target-ext-type.ll
- mlir/test/Target/LLVMIR/target-ext-type.mlir
- polygeist/tools/cgeist/Lib/CGExpr.cc
DO NOT SQUASH THIS PR!
5d2dc9ae9bccaf615e5755d28a07d927d2b0de0d in this PR is a reflection of https://github.com/llvm/llvm-project/pull/66510. It changes the LLVM dialect to use the recently introduced `llvm.mlir.zero` operation (zero-initializer) for target extension types, rather than zero-valued integer constants. This commit can be reverted once we receive https://github.com/llvm/llvm-project/pull/66510 in pull-down and does not need to be reviewed.
7450fa6f7b61229e7af1ba9a0d8dacc7628f97d1 changes the `cgeist` frontend to correctly use that new operation for initialization of target extension type values. Review can be limited to the changes in this commit.
> [SYCL-MLIR] Use llvm.mlir.zero operation for target extension type

- sycl/test-e2e/ESIMD/slm_init_no_inline.cpp
> [SYCL][ESIMD][E2E] Fix slm_init_no_inline compiler flags on Windows

- sycl/plugins/unified_runtime/CMakeLists.txt
- sycl/plugins/unified_runtime/pi2ur.hpp
- sycl/plugins/unified_runtime/pi_unified_runtime.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/adapter.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/command_buffer.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/ur_interface_loader.cpp
- sycl/plugins/unified_runtime/ur/adapters/hip/adapter.cpp
- sycl/plugins/unified_runtime/ur/adapters/hip/command_buffer.cpp
- sycl/plugins/unified_runtime/ur/adapters/hip/ur_interface_loader.cpp
- sycl/plugins/unified_runtime/ur/adapters/level_zero/adapter.cpp
- sycl/plugins/unified_runtime/ur/adapters/level_zero/command_buffer.cpp
- sycl/plugins/unified_runtime/ur/adapters/level_zero/ur_interface_loader.cpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/adapter.cpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/command_buffer.cpp
- sycl/plugins/unified_runtime/ur/adapters/native_cpu/ur_interface_loader.cpp
Reverts intel/llvm#11155. I'm almost sure this is what broke our CI for the past few days.
> Revert "[PI][UR][HIP][CUDA][L0][NCPU] Pull in latest UR fixes."

- sycl/test-e2e/NonUniformGroups/fixed_size_group.cpp
- sycl/test-e2e/NonUniformGroups/fixed_size_group_algorithms.cpp
- sycl/test-e2e/NonUniformGroups/tangle_group_algorithms.cpp
- sycl/test-e2e/SubGroupMask/Basic.cpp
- sycl/test-e2e/syclcompat/util/util_logical_group.cpp
- sycl/test-e2e/syclcompat/util/util_permute_sub_group_by_xor.cpp
- sycl/test-e2e/syclcompat/util/util_select_from_sub_group.cpp
- sycl/test-e2e/syclcompat/util/util_shift_sub_group_left.cpp
- sycl/test-e2e/syclcompat/util/util_shift_sub_group_right.cpp
Many AMD devices don't support size 32 subgroups. This patch skips tests for such devices. Same as https://github.com/intel/llvm/pull/11104
> [SYCL] Mark tests that require size 32 subgroups with "REQUIRES: sg-32"

- .github/workflows/sycl_windows_build_and_test.yml
I've created `WindowsCILock` environment and put
@intel/dpcpp-devops-reviewers into *workflow* reviewers list. Tasks using this environment will need to be approved by a member of this team before they run.
Once CI is stabilized I'm going to clear the box to require those reviews but keep the workflow files change so that we can lock the CI in future. I'm also planning in implementing the same for Linux pre-commit later.
> [CI] Lock Windows CI

- sycl/doc/extensions/experimental/sycl_ext_codeplay_kernel_fusion.asciidoc
- sycl/doc/extensions/experimental/sycl_ext_oneapi_graph.asciidoc
- sycl/doc/extensions/experimental/sycl_ext_oneapi_graph_fusion.asciidoc
- sycl/doc/extensions/proposed/sycl_ext_oneapi_graph_fusion.asciidoc
Experimental SYCL extension proposal for kernel fusion on top of the [SYCL graphs API](https://github.com/reble/llvm/blob/sycl-graph-update/sycl/doc/extensions/proposed/sycl_ext_oneapi_graph.asciidoc).
Constructing the sequence of kernels to fuse is completely left to the graphs proposal, which provides two APIs to this end. One recording API similar to the fusion mode for queues in the initial kernel fusion proposal, and an explicit graph construction APIs. Both APIs are supported for kernel fusion.
This proposal mainly introduces a number of properties to trigger fusion of the graph and internalization of dataflow in the fused kernel.
This proposal continues some of the ideas of the [experimental SYCL extension for kernel fusion](https://github.com/intel/llvm/blob/sycl/sycl/doc/extension …
> [SYCL][Doc] Graph fusion extension proposal

- llvm/lib/Transforms/Vectorize/VectorCombine.cpp
- llvm/test/Transforms/VectorCombine/SPIR/skip-vector-load-vectorize.ll
One of the operations VectorCombine does is to change scalar loads + insertelement into vector loads + shufflevector.
It heavily uses the TTI to determine if it is beneficial to do this. However, for SPIR targets, we don't know what the final hardware is and the TTI uses default values. This gives a misleading view into the target. 
The pass aggressively performs the above transformation even if the new cost is equal to the old cost (which it is here, both are 1) because it claims the backend can undo it if it wants, however other passes such as SROA transform the IR significantly based on the changes to liveness from instructions introduced here, so it becomes unrealistic to undo this in a later pass.
I did not disable the pass overall because it still does beneficial transformations in …
> [SYCL] Disable VectorCombine load insert vectorization for SPIR targets 

- llvm/lib/Transforms/Vectorize/CMakeLists.txt
We need to explicitly link against TargetParser for shared library builds because we are using `Triple` in this shared library now.
> Fix shared library build

- sycl/plugins/unified_runtime/ur/adapters/cuda/common.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/common.hpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/enqueue.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/event.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/image.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/kernel.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/memory.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/platform.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/program.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/queue.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/usm.cpp
- sycl/plugins/unified_runtime/ur/adapters/hip/common.cpp
- sycl/plugins/unified_runtime/ur/adapters/hip/common.hpp
- sycl/plugins/unified_runtime/ur/adapters/hip/enqueue.cpp
- sycl/plugins/unified_runtime/ur/adapters/hip/event.cpp
- sycl/plugins/unified_runtime/ur/adapters/hip/kernel.cpp
- sycl/plugins/unified_runtime/ur/adapters/hip/memory.cpp
- sycl/plugins/unified_runtime/ur/adapters/hip/platform.cpp
- sycl/plugins/unified_runtime/ur/adapters/hip/program.cpp
- sycl/plugins/unified_runtime/ur/adapters/hip/queue.cpp
- sycl/plugins/unified_runtime/ur/adapters/hip/usm.cpp
`UR_CHECK_ERROR` was designed to return `ur_result_t`, however in practice it was guaranteed to only ever return `UR_RESULT_SUCCESS`, as other paths would either terminate, abort or throw.
This in turns leads to poor quality/error prone code, as the codebase was littered with:
* statements not checking the return value - depending on the compiler generating a warning,
* extra check on the return which was only ever going to be true.
Some care was required, as the codebase has a habit of accumulating err codes across branches, so depending on the use case the initial value of `ur_result_t Result`s had to be set accordingly (now that `UR_CHECK_ERROR` does not return).
> [SYCL][NFC] Make UR_CHECK_ERROR a void return macro

- polygeist/tools/cgeist/Lib/Attributes.cc
- polygeist/tools/cgeist/Lib/Attributes.h
- polygeist/tools/cgeist/Lib/clang-mlir.cc
- polygeist/tools/cgeist/Test/Verification/sycl/noreturn.cpp
SYCL does not support C++ exceptions or termination in device code, so this attribute cannot appear in device code.
> [SYCL-MLIR][cgeist] Remove `noreturn` attribute in SYCL device code

- clang/include/clang/Driver/Options.td
- clang/lib/Driver/ToolChains/Clang.cpp
Remove the positive option and keep only the negative option. The option was added only a couple of days ago and nobody should be using it. It is a hidden option as well.
Based on feedback from https://github.com/intel/llvm/pull/11037#discussion_r1328955361
> [SYCL][Driver] Remove -fsycl-esimd-build-host-code

- sycl/doc/extensions/experimental/sycl_ext_oneapi_graph.asciidoc
The specification section defining the interaction with `sycl_ext_oneapi_bindless_images` should be one level lower in the heirarchy.
> [SYCL][Graph] Fix spec section numbering

- sycl/plugins/unified_runtime/ur/adapters/level_zero/platform.cpp
Based on the existence of NPU driver for L0, GPU flag is now passed to zeInit
> [SYCL][UR][L0] Modify flag for zeInit

- sycl/include/sycl/ext/intel/experimental/esimd/memory.hpp
- sycl/test/esimd/check_lsc.cpp
Using explicit enum will make the function and if-conditions more readable
> [SYCL][ESIMD] Refactor 2D block restrictions function

- sycl/doc/extensions/experimental/sycl_ext_oneapi_properties.asciidoc
Code block was missing closing ` ``` `.
> [SYCL][Doc] Fix formatting in sycl_ext_oneapi_properties

- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLHostOps.td
- mlir-sycl/lib/Dialect/SYCL/IR/SYCLOps.cpp
- mlir-sycl/test/Dialect/SYCL/host.mlir
- mlir-sycl/test/Dialect/SYCL/invalid.mlir
This PR removes the definition and IR tests for the `sycl.host.kernel_name` op which is no longer used by our host raising pass.
> [SYCL-MLIR][NFC] Remove unused `sycl.host.kernel_name` op.

- mlir-sycl/test/Conversion/SYCLToLLVM/sycl-grid-ops-to-llvm.mlir
- mlir-sycl/test/Conversion/SYCLToLLVM/sycl-methods-to-llvm.mlir
- polygeist/lib/Conversion/PolygeistToLLVM/PolygeistToLLVM.cpp
- polygeist/lib/Dialect/Polygeist/Transforms/BareMemRefToLLVM.cpp
- polygeist/lib/Dialect/Polygeist/Transforms/CMakeLists.txt
- polygeist/test/polygeist-opt/polygeist-to-llvm.mlir
- polygeist/tools/cgeist/Test/Verification/sycl/constructors.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/issue7835.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/sycl_extern_func.cpp
Patterns lowering `memref.alloc[a]` are now based on the ones in `-finalize-memref-to-llvm`. Changes:
- `memref.alloca`: allow dynamic shapes in lowering;
- `memref.alloc`: enforce no alignment, this would produce invalid code;
- `malloc` and `free` functions are now uniqued after lowering to prevent symbol duplication.
These changes are needed in `cgeist` frontend when we reduce `llvm.func` usage:
- `malloc/free` uniquing is compulsory as `func.func` lowering would lead to two definitions otherwise;
- Lowering changes motivated by `memref.alloc` lowering testing. Will futureproof `cgeist` codegen.
> [SYCL-MLIR][polygeist-to-llvm] Revamp alloc-like lowering patterns

- sycl/test-e2e/Annotated_arg_ptr/annotated_arg.cpp
- sycl/test-e2e/Annotated_arg_ptr/annotated_ptr.cpp
See https://github.com/intel/llvm/issues/11224. It seems that whenever those fail (flakily), the entire run time outs and other (hanging) tests aren't killed properly and remain as zombie processes affecting subsequent CI runs. Disable those tests for now.
> [SYCL][E2E] Disable Annotated_arg_ptr tests on Win

- polygeist/tools/cgeist/Test/Verification/sycl/sycl-optlevel.cpp
Add test checking `sycl-optlevel` is added to functions by the LLVM pipeline.
> [SYCL-MLIR][cgeist][test] Add `sycl-optlevel` attribute test

- sycl/source/detail/global_handler.cpp
- sycl/source/detail/global_handler.hpp
- sycl/source/detail/queue_impl.cpp
- sycl/source/detail/scheduler/scheduler.cpp
- sycl/source/detail/scheduler/scheduler.hpp
Test is a scheduler instance is alive before before attempting to cleanup fusion commands.
Hopefully addresses https://github.com/intel/llvm/pull/10948#issuecomment-1732066144 (I cannot locally reproduce the issue)
> [SYCL][KernelFusion] Prevent unnecessary scheduler creation

- polygeist/lib/Dialect/Polygeist/Transforms/LoopInternalization.cpp
Drop assert that can be triggered, e.g., when a memref layout is not the identity.
> [SYCL-MLIR][loop-internalization] Drop assert expecting valid memory access analysis result

- sycl/doc/extensions/experimental/sycl_ext_oneapi_annotated_ptr.asciidoc
- sycl/doc/extensions/experimental/sycl_ext_oneapi_kernel_arg_properties.asciidoc
- sycl/include/sycl/ext/oneapi/experimental/annotated_ptr/annotated_ptr.hpp
- sycl/include/sycl/ext/oneapi/experimental/common_annotated_properties/properties.hpp
Move alignment from annotated_ptr specific property to a common property
> [SYCL] Change alignment to common property

- sycl/doc/extensions/experimental/sycl_ext_oneapi_annotated_arg.asciidoc
- sycl/include/sycl/ext/oneapi/experimental/annotated_arg/annotated_arg.hpp
- sycl/include/sycl/ext/oneapi/experimental/annotated_ptr/annotated_ptr.hpp
- sycl/test-e2e/Annotated_arg_ptr/annotated_arg.cpp
Added device copyable traits for annotated_arg. If the type `T` is device copyable, then the type `annotated_arg<T, ...>` is also device copyable.
For example, consider the following code: 
```c++
#include <sycl/sycl.hpp>
#include <sycl/ext/intel/fpga_extensions.hpp>
#include <sycl/ext/intel/ac_types/ac_fixed.hpp>
#include "ExceptionHandler.h"
#include "TestConfigSelector.h"
using namespace sycl;
using namespace ext::intel::experimental;
using namespace ext::oneapi::experimental;
using ac_fixed_type = ac_fixed<10, 5, true>;
int main() {
struct MyIP {
annotated_arg<ac_fixed_type> a;
void operator()() const {};
};
queue q(testconfig_selector_v, &m_exception_handler);
ac_fixed_type a = 5;
q.single_task(MyIP{a}).wait();
return 0;
}
```
This code generates the following static assertion …
> [SYCL] Add device copyable trait for annotated_arg

- sycl/doc/extensions/experimental/sycl_ext_oneapi_graph.asciidoc
…raph
we can use a different queue to replay a graph than the graph is created or recorded, but with the same context and device.
> [SYCL-Graph][Doc] Add queue requirement when replay a graph

- mlir/lib/Target/LLVMIR/ModuleTranslation.cpp
- polygeist/tools/cgeist/Lib/clang-mlir.cc
- polygeist/tools/cgeist/Test/Verification/sycl/default_sub_group_size.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/esimd_metadata.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/named_sub_group_size.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/reqd_sub_group_size.cpp
Add sub-group size metadata following these rules:
- Follow SYCL 2020 rules, i.e., no propagation of these attributes when functions are called from a kernel;
- Use `reqd_sub_group_size()` value if available, this can be numeric or a named value `("automatic"` or `"primary"`);
- Get `fsycl-default-sub-group-size` value if available;
- For `sycl_explicit_simd` kernels, set `intel_reqd_sub_group_size` to `1`.
> [SYCL-MLIR][cgeist] Add sub-group size metadata to kernels

- sycl/include/sycl/sycl.hpp
- sycl/test/basic_tests/no_math_in_global_ns.cpp
https://github.com/intel/llvm/pull/11274 and
https://github.com/intel/llvm/pull/11196 could break customers code that relied on implicit inclusion of those headers. Don't break it before the next ABI breaking window.
> [SYCL] Include <complex>/<cmath> from sycl.hpp, unless SYCL2020_CONFORMANT_APIS

- clang/lib/Driver/ToolChains/SYCL.cpp
It breaks device lib linking, -only-needed is used only in the device lib link and not in the device obj link.
This reverts commit 0d5acd48457109cc9f15a7a258aa5c8cc6c22220.
> [SYCL][Driver] Revert "Fix fno-gpu-rdc SYCL libraries linking not using opaque pointers"

- clang/test/Driver/sycl-offload-new-driver.c
In somecase we may use ld from different path to build the compiler,
assuming `/usr/bin` will cause unecessary lit failure.
> [NFC][Driver] Don't assume ld path in sycl-offload-new-driver test

- clang/lib/Driver/ToolChains/SYCL.h
- clang/test/Driver/sycl-native-cpu.cpp
This PR fixes the SYCL toolchain to pass the debug format used for the host compilation to the device compilation.   
Without this patch mismatching debug formats could lead to corrupt debug information and link errors.
> [SYCL][NATIVECPU] Fix for mismatching debug format between host and device 

- sycl/test-e2e/Basic/interop/interop_all_backends.cpp
All CI backends (cuda, hip, l0, opencl) currently support these three types of interop, that are probably the most important cases, but a complete e2e test did not previously exist. opencl is also the only backend with an existing test-e2e that calls make_* for these three sycl objects.
This adds a short test-e2e corresponding to e.g. https://github.com/intel/llvm/pull/10526.
> [SYCL] Added test-e2e for queue, device, and event interop.

- sycl/test-e2e/Graph/submission_while_executing.cpp
The test behaviour was indeterministic.
This PR improves the test to make it deterministic. 
The data size has also been reduced to avoid risk of an "out of memory" exception.
Addresses Issue: #11277
https://github.com/intel/llvm/issues/11277
> [SYCL][Graph] Bugfix test e2e Graph/submission_while_executing.cpp

- sycl/doc/extensions/experimental/sycl_ext_oneapi_bindless_images.asciidoc
- sycl/include/sycl/ext/oneapi/bindless_images.hpp
Assert the restrictions on reading/writing coordinate types and mipmap anisotropic viewing gradient types
> [Bindless][SYCL] read/write images with only acceptable coordinate types

- sycl/test-e2e/Graph/Threading/submit.cpp
Multihtread `finalize.cpp` e2e was written to test both finalize and submit processes. 
This test was based on strong assumptions about backend's kernel ordering, and was unstable. 
Since the behaviour of the finalize process in multi-threaded environment is already tested by a unitest, we (re)focused this test to verify concurrent submissions only. 
The test is therefore renamed submit.cpp
> [SYCL][Graph] Improve multithread e2e tests

- polygeist/include/mlir/Dialect/Polygeist/Utils/Utils.h
- polygeist/lib/Conversion/PolygeistToLLVM/PolygeistToLLVM.cpp
- polygeist/lib/Dialect/Polygeist/Transforms/BareMemRefToLLVM.cpp
- polygeist/lib/Dialect/Polygeist/Utils/CMakeLists.txt
- polygeist/lib/Dialect/Polygeist/Utils/Utils.cpp
- polygeist/test/polygeist-opt/polygeist-to-llvm-abi-break.mlir
- polygeist/test/polygeist-opt/polygeist-to-llvm.mlir
DO NOT SQUASH AND MERGE THIS PR
Review just 77c5a7bbdced2361fe46ec1d529c0b703119805a.
cec61ea9e397e4dc26c7188e0b40398726036f6c caused errors if `-loop-internalization` introduced non-bare pointer convertible code. This PR reverts that commit and verifies we are not breaking ABI before conversion to `llvm` dialect.
> Allow non-bare pointer convertible `memref` types in non-ABI breaking code

- sycl/include/sycl/buffer.hpp
- sycl/test/basic_tests/buffer/buffer_for_not_device_copyable.cpp
- sycl/test/basic_tests/implicit_device_copyable_types.cpp
Fixes https://github.com/intel/llvm/issues/5005.
> [SYCL] Verify that buffer's type is device copyable

- sycl/doc/extensions/supported/sycl_ext_oneapi_queue_priority.asciidoc
- sycl/plugins/unified_runtime/ur/adapters/cuda/queue.cpp
- sycl/plugins/unified_runtime/ur/adapters/cuda/queue.hpp
- sycl/test-e2e/Plugin/cuda_queue_priority.cpp
The E2E test assumes that the device supports priorities (sm_35 or newer).
> [SYCL][CUDA] Implement ext_oneapi_queue_priority

- sycl/unittests/queue/GetProfilingInfo.cpp
Testcases there verify behavior of `device_impl::getCurrentDeviceTime` but some parts of it are cached inside SYCL RT. For the unittest to be reliable we have to use a "new" device for each testcase. Do so by redefining `piDevicesGet`.
> [SYCL] Fix GetProfilingInfo.cpp unittest

- devops/dependencies.json
- sycl/test-e2e/Assert/assert_in_kernels.cpp
- sycl/test-e2e/Assert/assert_in_multiple_tus.cpp
- sycl/test-e2e/Assert/assert_in_multiple_tus_one_ndebug.cpp
- sycl/test-e2e/Assert/assert_in_one_kernel.cpp
- sycl/test-e2e/Assert/assert_in_simultaneous_kernels.cpp
- sycl/test-e2e/Assert/assert_in_simultaneously_multiple_tus.cpp
- sycl/test-e2e/Assert/assert_in_simultaneously_multiple_tus_one_ndebug.cpp
- sycl/test-e2e/ESIMD/assert.cpp
- sycl/test-e2e/ESIMD/slm_block_load_store.cpp
- sycl/test-e2e/Graph/Explicit/buffer_ordering.cpp
- sycl/test-e2e/Graph/RecordReplay/buffer_ordering.cpp
> [GHA] Uplift Linux GPU RT version to 23.30.26918.9

- sycl/test-e2e/Graph/Inputs/buffer_ordering.cpp
`buffer_ordering.cpp` did not meet the Graph specification. Buffers must outlive the Graph that uses them.
The buffer-ordering test has been updated to fulfill this property.
Closes Issue: #11374
> [SYCL][Graph] Bugfix buffer_ordering: make buffers outlives graph

- mlir-sycl/lib/Dialect/SYCL/IR/SYCLDialect.cpp
- mlir-sycl/test/Dialect/SYCL/types.mlir
`host_task` attribute shall be aliased to `ht`.
> [SYCL-MLIR][sycl] Define alias for `host_task` attribute

- polygeist/tools/cgeist/Test/Verification/sycl/undeftypes.cpp
Make test independent of the
`CGEIST_DEFAULT_ALLOW_UNDEFINED_SYCL_TYPES` option.
> [SYCL-MLIR][cgeist][test] Fix `Verification/sycl/undeftypes.cpp`

- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLTypes.h
- mlir-sycl/include/mlir/Dialect/SYCL/IR/SYCLTypes.td
- mlir-sycl/lib/Dialect/SYCL/Analysis/AliasAnalysis.cpp
- mlir-sycl/lib/Dialect/SYCL/IR/SYCLOps.cpp
- mlir-sycl/lib/Dialect/SYCL/IR/SYCLTypes.cpp
- polygeist/tools/cgeist/Lib/CGExpr.cc
- polygeist/tools/cgeist/Lib/CodeGenTypes.cc
- polygeist/tools/cgeist/Lib/TypeUtils.cc
- polygeist/tools/cgeist/Lib/TypeUtils.h
- polygeist/tools/cgeist/Lib/clang-mlir.cc
`SYCLType` is the base class of all `sycl` dialect types. Replace `isSYCLType` instances with `llvm::isa<mlir::sycl::SYCLType>` or `mlir::sycl::SYCLType::classof`.
> [SYCL-MLIR][sycl] Define `SYCLType` base class for `sycl` dialect types

- llvm/test/tools/sycl-post-link/spec-constants/remove-dead-private-constants.ll
- llvm/tools/sycl-post-link/ModuleSplitter.cpp
- llvm/tools/sycl-post-link/sycl-post-link.cpp
- sycl/test/esimd/genx_func_attr.cpp
This PR resolves https://github.com/intel/llvm/issues/9962
This change calls cleanup as the final step in sycl-post-link before writing the module into file. This helps to remove several dead variables. Some of these 'dead' variables seem to get translated to erroneous SPIR-V code resulting in spirv-val failures.
In addition to improving code size, this change help to resolve such errors as a side-effect.
Thanks
Sincerely
> [sycl-post-link] Call cleanup at the very end of sycl-post-link

- polygeist/tools/cgeist/Lib/CGCall.cc
- polygeist/tools/cgeist/Lib/clang-mlir.cc
- polygeist/tools/cgeist/Test/Verification/omitarg.cpp
Omit clang arguments with no MLIR/LLVM IR counterpart, e.g., empty
structs.
> [SYCL-MLIR][cgeist] Omit clang ignored arguments

- sycl/test-e2e/Graph/Explicit/buffer_ordering.cpp
- sycl/test-e2e/Graph/RecordReplay/buffer_ordering.cpp
PR #11380 fixed the reported issue with buffer_ordering tests. 
This PR re-enables these tests.
> [SYCL][Graph] Re-enable buffer_ordering tests

- sycl/include/sycl/ext/oneapi/experimental/annotated_arg/annotated_arg.hpp
- sycl/include/sycl/ext/oneapi/properties/properties.hpp
- sycl/include/sycl/types.hpp
- sycl/test/basic_tests/is_device_copyable_neg.cpp
Two benefits:
1) Errors are cleaner now
2) User-provided partial specialization cannot cause "ambiguous partial
specialization" error anymore. We use those internally as well, so
that has been simplified too.
> [SYCL] Simplify sycl::is_device_copyable implementation

- sycl/test/check_device_code/fpga_datapath_local.cpp
- sycl/test/check_device_code/fpga_mem_local.cpp
Caused by https://github.com/intel/llvm/pull/10849 
Due to the fact that if the test are run on a compiler that was compiled with `--hip --cuda`. This causes the LLVM IR variable names to be obfuscated from `%empty` to `%0`. The failing LIT tests relied on that names being intact.
> [SYCL] Fix test/check_device_cod/fpga_*_local.cpp for asserts disabled in compiler

- sycl/include/sycl/reduction.hpp
It uses `std::optional` as a member so we need to provide partial specialization for it (no reflection in C++).
> [SYCL] Mark detail::ReducerElement as device-copyable

- sycl/source/detail/device_image_impl.hpp
- sycl/source/detail/kernel_bundle_impl.hpp
- sycl/test-e2e/SpecConstants/2020/image_selection.cpp
Now SYCL tools can generate device image where specialization constants are replaced with default values in addition to original device image. This patch implements selection of such device image when possible. It is possible when specialization constant values are not set for the device image.
When specialization constants are used we always work with kernel_bundle and obtain kernel object to enqueue via get_kernel method of the kernel_bundle. This is the point when device image is selected. Before we were selecting the first image containing the kernel. Now image selection was modified to take into account new device images where specialization constants are replaced with default values.
> [SYCL] Selection of device images where spec consts are replaced with default

- sycl/source/detail/program_manager/program_manager.cpp
- sycl/test-e2e/ESIMD/grf.cpp
All the pieces were there because it's already supported in normal SYCL, and we just updated the GPU driver which added support for auto GRF in VC.
> [SYCL][ESIMD] Support Auto GRF size specification

- libclc/utils/prepare-builtins.cpp
AMDGPU remove incompatible functions pass replaces all uses of functions that use GPU features  incompatible with the current GPU with null then deletes the function. This didn't use to cause problems, as all of libclc functions were inlined prior to incompatible functions pass. Now that the inliner runs later in the pipeline we have to remove all of the target features, so libclc functions will not be earmarked for deletion.
NOTE: I've also reverted the pulldown revert commit to make sure that the original error condition is recreated, hence this PR should not be squashed prior to merging.
Fixes: https://github.com/intel/llvm/issues/10816
> [SYCL][LIBCLC] Remove target features attributes when compiling for AMD

- sycl/plugins/unified_runtime/CMakeLists.txt
Piotor has refactor the cmake for windows build to improve the fix,
we also enabled local copy to avoid leaking path.
we should pick them up .
> [UR][L0] Pick up improve fix for windows build and localcopy feature

- .github/workflows/sycl_precommit_linux.yml
I was wrong - these are different GPUs and not multiple names for the same.
> [CI] Rename ATS-M -> Intel Arc A-Series Graphics in pre-commit task

- polygeist/tools/cgeist/Options.h
- polygeist/tools/cgeist/Test/Verification/sycl/nop_kernel.hpp
- polygeist/tools/cgeist/Test/Verification/sycl/raising/host_raising_captures.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/raising/host_raising_id_constructors.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/raising/host_raising_index.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/raising/host_raising_nd_range.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/raising/host_raising_nd_range_constructors.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/raising/host_raising_pipeline.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/raising/host_raising_range.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/raising/host_raising_range_constructors.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/raising/host_raising_range_offset.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/raising/host_raising_schedule_kernel.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/sycl_use_host_module.cpp
- polygeist/tools/cgeist/driver.cc
Add `-no-early-drop-host-code` cgeist hidden option to revert this behaviour.
> [SYCL-MLIR][cgeist] Early drop host code by default when raising

- libclc/amdgcn-amdhsa/libspirv/atomic/atomic_sub.cl
This PR changes the use of `atomic_sub` to `atomic_add` with a negated `val`. Doing so extends the number of cases in which the atomic operation will work, since support for `atomic_add` is more common than `atomic_sub`, especially at the PCIe level.
> [SYCL][HIP] Change atomic sub to atomic add (-val)

- sycl-fusion/jit-compiler/lib/KernelFusion.cpp
- sycl/test-e2e/KernelFusion/cached_ndrange.cpp
This PR fixes an oversight in the cache implementation: Kernels fused over homogeneous ND ranges (i.e. no ID remapping required) can in be reused on different ND ranges, but then must be launched with the current range, not the one present when the fused kernel first entered the cache.
> [SYCL][Fusion] Use correct range for cached, fused kernels

- .github/CODEOWNERS
Replace the listing of individual team members as CODEOWNERS with the recently established Github team.
> [SYCL][Fusion][NFC] Use reviewer team as codeowners

- sycl/test/native_cpu/no-opt.cpp
The test was missing a `RUN` directive.
> [SYCL] [NATIVECPU] Fix no-opt.cpp test

- polygeist/tools/cgeist/Lib/CGExpr.cc
- polygeist/tools/cgeist/Test/Verification/ternary_member.cpp
- sycl/test-e2e/xfail_tests.txt
Bool members are stored as `i8`, so they need to be converted to `i1` before they can be used in the `scf.if` generated for the ternary operator.
> [SYCL-MLIR] Fix ternary operator on bool members

- sycl/include/sycl/handler.hpp
- sycl/source/detail/graph_impl.cpp
- sycl/source/detail/graph_impl.hpp
- sycl/source/handler.cpp
- sycl/test-e2e/Graph/RecordReplay/barrier_with_work.cpp
- sycl/unittests/Extensions/CommandGraph.cpp
Adds support to handle barrier enqueuing with Record&Replay API. Barriers are implemented as empty nodes enforcing the required dependencies.
Adds tests that check:
1) correctness of graph structure when barriers have been enqueued, 
2) processing behavior, 
3) exception throwing if barriers are used within explicit API.
Notes:
1) Barriers can only be used with Record&Replay API, since barriers rely on events to enforce dependencies.
2) The scope of a barrier is limited to the Graph in which the barrier was added. As a result, if a barrier with no explicit events to wait for is part of a graph, when the graph is executed this barrier waits for all the kernels/operations in the graph that were previously submitted. However, the barrier does not wait for kernels/operations outside the graph …
> [SYCL][Graph] Support for sycl_ext_oneapi_enqueue_barrier extension

- sycl/unittests/Extensions/CommandGraph.cpp
Fixes post commit CI fail https://github.com/intel/llvm/actions/runs/6470268418/job/17566091513
```
/__w/llvm/llvm/src/sycl/unittests/Extensions/CommandGraph.cpp:1459:12: error: backslash and newline separated by space [-Werror,-Wbackslash-newline-escape]
1459 |   //     /|\
|            ^
1 error generated.
```
This was occuring due to a trailing whitespace character in the comment that was introduced in https://github.com/intel/llvm/pull/11418#discussion_r1352766009
> [SYCL][Graph] Remove trailing comment whitespace

- sycl/test-e2e/InvokeSimd/Regression/ImplicitSubgroup/slm_load_store.cpp
`test-e2e/InvokeSimd/Regression/ImplicitSubgroup/slm_load_store.cpp` wasn't updated together with
`test-e2e/InvokeSimd/Regression/slm_load_store.cpp` that it includes in https://github.com/intel/llvm/pull/11427. Do it now.
> [SYCL][E2E] Add REQUIRES-INTEL-DRIVER to a test

- .gitattributes
This is to tell git merge.ours driver to always use sycl version.
It should be a nop op for default merge strategy.
To use merge.ours driver, you can set it in config once.
git config --global merge.ours.driver true
This is to avoid trivial conflict in CODEOWNERS break pulldown
automation.
> [Pulldown] Always use ours when merging from other branches for CODEOWNERS

- clang/lib/Driver/Driver.cpp
- clang/lib/Driver/ToolChains/Clang.cpp
- clang/lib/Driver/ToolChains/SYCL.cpp
- clang/lib/Driver/ToolChains/SYCL.h
- clang/test/Driver/sycl-offload-new-driver.c
Adds support for a handful of linker wrapper options that are part of the new offload model support.
--sycl-device-libraries=libs provides a comma separated list of
libraries that are used during the device link
--sycl-device-library-location=dir the location in which the device
libraries reside.
--sycl-post-link-options=opts all options as specified by the user
via the -Xdevice-post-link option.
--llvm-spirv-options=opts all options as specified by the user via
the -Xspirv-translator option.
Does some refactoring for what libraries are added, moving the functionality to the SYCL based toolchain.
These options are documented in the following design document: sycl/doc/design/OffloadDesign.md
> [Driver][SYCL][clang-linker-wrapper] Add support for additional linker wrapper options

- sycl/include/sycl/queue.hpp
Don't instantiate std::function just to check invocable.
> [SYCL] Simplify invocable check

- clang/lib/Driver/ToolChains/SYCL.cpp
- clang/test/Driver/sycl-offload.c
The runtime already handles it so it's passed twice right now actually, and the runtime skips some broken cases already but it's getting passed to the backend in those broken cases because we're adding it here.
> [SYCL][Driver] Do not pass -cl-opt-disable for JIT

- sycl/test-e2e/ESIMD/api/functional/common.hpp
- sycl/test-e2e/Regression/half_operators.cpp
Turns out this is not valid, just do it in a simpler way.
> [SYCL][E2E] Fix strict aliasing violation in tests

- llvm/lib/SYCLLowerIR/PrepareSYCLNativeCPU.cpp
This will causing warning and become error when building with -Werror.
> [SYCL] Remove unused NativeCPUGlobalAS

- clang/lib/Sema/SemaDeclAttr.cpp
- clang/test/SemaSYCL/intel-fpga-local-ast.cpp
- clang/test/SemaSYCL/intel-fpga-local.cpp
This patch adds a warning for duplicate attributes but not if it's one we've implicitly added and drop any duplicates for FPGA attributes below:
1. [[intel::simple_dual_port]]
2. [[intel::fpga_register]]
3. [[intel::singlepump]]
4. [[intel::doublepump]]
> [SYCL][FPGA] Drop duplicate attributes

- sycl/include/sycl/detail/cg_types.hpp
- sycl/source/detail/queue_impl.hpp
- sycl/source/detail/scheduler/commands.cpp
- sycl/source/detail/scheduler/scheduler.cpp
- sycl/test-e2e/Basic/profile_host_task.cpp
Use `HostProfilingInfo` to record profiling info for host tasks, and disable calls to `isGetDeviceAndHostTimerSupported` for host device. Fixes #11504.
> [SYCL] Enable profiling info for `host_task`

- sycl/include/sycl/detail/group_sort_impl.hpp
This commit removes the UB caused due to reinterpreting the scratch memory supplied to the group sort algorithms by replacing the strict aliasing violation with memcpy. To help simplify the usage of this, a wrapper class around the scratch memory is introduced to handle common access patterns.
> [SYCL] Fix UB in group sort scratch memory access

- sycl/plugins/unified_runtime/CMakeLists.txt
We have updated UR after https://github.com/intel/llvm/pull/11343 was posted,
However, when the PR was merged, it accidentally rollbacked UR.
This is to fix the rollback and also added comments in CMakeLists.txt to
help avoiding future accidental rollback.
> [UR] Fix accidentally rollback in 7812fa95e2c

- sycl/include/sycl/ext/intel/esimd/common.hpp
The FP atomic operations add the restrictions to the target device to be at least ACM (any GPU that has LSC feature). This case is not the only when using some features (types, or vector lengths) adds such extra HW restrictions. There is no reason for fmax/fmin/etc to be special.
The warning used to signal about extra FP requirements was the obsolete messages/warning, which is rather abuse of warnings system. Also, the warnings printed for FP atomics were extremely annoying and polluted the compiler output with no good benefit from it. As a result some customers simply disabled 'obsolete' warnings completely, which is also bad as they will not see really important warnings about API that is deprecated and needs replacement in user's programs.
> [ESIMD][NFC] Remove compilation warning on FP atomics usage

- sycl/source/detail/scheduler/graph_builder.cpp
Skip the (potentially expensive) cyclic dependency check if there's only one queue in fusion mode.
> [SYCL][Fusion] Short-circuit the cyclic dependency check in common case

- sycl/test-e2e/GroupAlgorithm/SYCL2020/sort.cpp
https://github.com/intel/llvm/pull/11442 fixed an issue with UB causing failures in group sorting implementations on certain hardware. This fixed the sycl/test-e2e/GroupAlgorithm/SYCL2020/sort.cpp on DG2 and so this commit enables this test.
> [SYCL][E2E] Enable sort test on DG2

- sycl/doc/design/KernelFusionJIT.md
Add relevant information to sycl/doc/design/KernelFusionJIT.md, including: information on the pass performing the required transformations, restrictions on the input nd-ranges and brief description of the process.
> [SYCL][FUSION][DOC] Document fusion of kernels with different nd-ranges

- sycl/plugins/unified_runtime/pi_unified_runtime.cpp
`releaseAdapters` will already call `urTearDown` so we remove this redundant call which was causing segfaults in some cases.
> [UR] Don't unload UR twice

- polygeist/tools/cgeist/Lib/clang-mlir.cc
- polygeist/tools/cgeist/Test/Verification/sycl/vector_not.cpp
This PR adds codegen support for applying the bitwise not operator (`~`) on SYCL integer vectors.
> [SYCL-MLIR] Support bitwise-not on integer vectors

- polygeist/tools/cgeist/Lib/CGExpr.cc
- polygeist/tools/cgeist/Test/Verification/calloc.c
- polygeist/tools/cgeist/Test/Verification/fscanf.c
- polygeist/tools/cgeist/Test/Verification/fw.c
- polygeist/tools/cgeist/Test/Verification/fwfree.c
- polygeist/tools/cgeist/Test/Verification/malloc.c
- polygeist/tools/cgeist/Test/Verification/palloc.c
- polygeist/tools/cgeist/Test/Verification/sycl/issue7835.cpp
- polygeist/tools/cgeist/Test/polybench/datamining/correlation/correlation.c
- polygeist/tools/cgeist/Test/polybench/linear-algebra/kernels/2mm/2mm.c
- polygeist/tools/cgeist/Test/polybench/medley/nussinov/nussinov.c
- sycl/test-e2e/xfail_tests.txt
When bitcasting:
1. Cast to desired type using original address space;
2. Cast address space.
Special care is taken when source and destination type have different pointer representation (memref vs pointer).
> [SYCL-MLIR][cgeist] Revamp `bitcast` cast kind

- sycl/source/detail/graph_impl.cpp
- sycl/source/detail/scheduler/commands.cpp
- sycl/source/handler.cpp
- sycl/test-e2e/Graph/Explicit/kernel_bundle.cpp
- sycl/test-e2e/Graph/Explicit/multiple_kernel_bundles.cpp
- sycl/test-e2e/Graph/Inputs/kernel_bundle.cpp
- sycl/test-e2e/Graph/Inputs/multiple_kernel_bundles.cpp
- sycl/test-e2e/Graph/RecordReplay/kernel_bundle.cpp
- sycl/test-e2e/Graph/RecordReplay/multiple_kernel_bundles.cpp
- sycl/unittests/Extensions/CommandGraph.cpp
- Adds support for using kernel-bundle in Graph.
- Adds tests checking that kernel bundles can be used with the Record&Replay API and the Explicit API.
> [SYCL][Graph] Support for kernel-bundle

- clang/include/clang/Driver/Options.td
- clang/lib/Driver/ToolChains/SYCL.cpp
- clang/lib/Driver/ToolChains/SYCL.h
- clang/test/Driver/sycl-ftarget-register-alloc-mode.cpp
- sycl/doc/UsersManual.md
- sycl/source/detail/program_manager/program_manager.cpp
- sycl/test-e2e/KernelAndProgram/target_register_alloc_mode.cpp
We finally are using a new enough IGC driver in CI so we can implement this. The option was approved a while back by the options group.
This change adds a new option `-ftarget-register-alloc-mode`. It is specified as follows:
`-ftarget-register-alloc-mode=DeviceName0:Mode0[,DeviceName1:Mode1...]`
Currently the only valid device name is `pvc`, but I developed this change to be extendable in the future.
The valid modes are:
auto -> request the backend to use heuristics to pick a register alloc mode
small -> use small grf mode
large -> use large grf mode
default -> provide no specification to the backend on what register alloc mode to use.
The default value if not specified is `pvc:default`, so provide no specification to the backend in any case for any hardware. I will begin an internal …
> [SYCL] Add support for -ftarget-register-alloc-mode

- sycl/doc/extensions/experimental/sycl_ext_oneapi_auto_local_range.asciidoc
Fix some syntax errors in the extension specification for `auto_range`. Since `auto_range` is a function, we need to add parens to call it.  We also need braces around the integral `N` when it is used to construct an anonymous `range`.
> [SYCL][DOC] Fix syntax errors in auto_range spec

- sycl/test-e2e/syclcompat/memory/memcpy_3d.cpp
- sycl/test-e2e/syclcompat/memory/memcpy_3d2.cpp
There's a bug when using the `opencl:cpu` backend where adjacent tests sometimes allocate the same memory region for both `std::malloc` and `sycl::malloc_device`. This causes a crash with `-34`, `CL_INVALID_CONTEXT`.
This PR works around this by using `sycl::malloc_host` instead of `std::malloc` in the intermittently failing tests. A separate bug report will be submitted once a minimal reproducer has been developed.
> [SYCL][COMPAT] Updated pitched_memory tests to use malloc_host

- clang/test/CodeGenSYCL/function-attrs.cpp
2dc6579f6fb12470559a68886c2a4aecaa8495dd updated the function-attrs test using script using llorg driver. 
This is update it using sycl driver.
> [SYCL-WEB][SYCL] Update function-attrs for sycl branch

- sycl/doc/syclcompat/README.md
- sycl/include/syclcompat/atomic.hpp
This PR modifies the wrapper to the atomic free functions:
- Extends half of the existing free functions with the `sycl::memory_scope` parameter. This unifies the interface with the rest of the API. 
- To preserve functionality `memoryScope` defaults to `sycl::memory_scope::device`
- README.md has been updated to reflect the new interface.
- README.md has also been updated to include the missing documentation for `class atomic`.
> [SYCL][COMPAT] Updated atomic ops with memoryOrder template parameter

- sycl/test-e2e/syclcompat/util/util_find_first_set.cpp
- sycl/test-e2e/syclcompat/util/util_permute_sub_group_by_xor.cpp
- sycl/test-e2e/syclcompat/util/util_select_from_sub_group.cpp
- sycl/test-e2e/syclcompat/util/util_shift_sub_group_left.cpp
- sycl/test-e2e/syclcompat/util/util_shift_sub_group_right.cpp
A set of memory leaks were reported for SYCLcompat tests in issue https://github.com/intel/llvm/issues/11574
This PR addresses them.
> [SYCL][COMPAT][Test] Fix mem leaks on syclcompat util tests

- clang/lib/Driver/ToolChains/Clang.cpp
Passing the overly specific triple to `clang-offload-deps` caused the device code to be dropped in application builds involving static libraries.
> [SYCL-MLIR] Suppress environment suffix to be passed to `clang-offload-deps`

- sycl/test-e2e/DeviceLib/built-ins/ext_native_math.cpp
See https://github.com/intel/llvm/issues/11562
This test failure has been reproduced locally on CUDA 12.1 and 12.2. Earlier versions appear to work. https://github.com/intel/llvm/pull/11436/files could also be related to this failure.
> [SYCL][CUDA] Xfail ext-native-math.cpp test.

- .github/CODEOWNERS
Now intel/llvm-reviewers-cuda owns these paths.
> [SYCL][CUDA] Added some cuda specific paths to CODEOWNERS.

- sycl/test-e2e/GroupAlgorithm/SYCL2020/exclusive_scan.cpp
- sycl/test-e2e/GroupAlgorithm/SYCL2020/inclusive_scan.cpp
- sycl/test-e2e/GroupAlgorithm/different_types.cpp
- sycl/test-e2e/GroupAlgorithm/exclusive_scan_sycl2020.cpp
- sycl/test-e2e/GroupAlgorithm/inclusive_scan_sycl2020.cpp
- sycl/test-e2e/Regression/exclusive-scan-char-short.cpp
- sycl/test-e2e/UserDefinedReductions/user_defined_reductions.cpp
- sycl/test-e2e/helpers.hpp
To adhere to [LLVM host compiler requirements](https://github.com/intel/llvm/blob/sycl/llvm/docs/GettingStarted.rst#host-c-toolchain-both-compiler-and-standard-library), this PR removes uses of std::exclusive_scan/inclusive_scan/reduce in some end to end tests, as they are not supported in GCC 7.4
> [SYCL][NFC] Do not use std::exclusive_scan/inclusive_scan/reduce in tests

- sycl/source/detail/graph_impl.cpp
- sycl/source/detail/scheduler/commands.cpp
Only finalize a modifiable `command_graph` for the SYCL device that was passed on construction. We
currently finalize for every device in the context, which is unnecessary overhead and may lead to
unintended interactions with buffers used in these contexts.
PR also includes code to start waiting on for deps when adding commands to a command graph. This prevents issues where allocation commands with dependent copies could be delayed due to device being busy and execute in an incorrect order with regards to future command graph executions.
> [SYCL][Graph] Finalize Graph for single device

- sycl/include/sycl/ext/intel/experimental/fpga_lsu.hpp
- sycl/include/sycl/ext/intel/experimental/fpga_utils.hpp
- sycl/include/sycl/ext/intel/experimental/pipes.hpp
- sycl/include/sycl/ext/oneapi/latency_control/properties.hpp
Clean up the experimental latency control headers by leveraging `add_ir_annotations_member`.
No change to the user APIs.
FPGA BE support: https://github.com/intel-innersource/applications.fpga.oneapi.products.acl-source/pull/1609
Local E2E tests combining this change and the FPGA BE change:
- On LSUs: https://psg-sc-arc.sc.intel.com/p/psg/swip/w/shuoniu/git/shuoniu.latency-control-prototype/add_ir_annotations_member/build/lsu.prj/reports/report.html
- On blocking pipes: https://psg-sc-arc.sc.intel.com/p/psg/swip/w/shuoniu/git/shuoniu.latency-control-prototype/add_ir_annotations_member/build/blocking_pipe.prj/reports/report.html
- On non-blocking pipes: https://psg-sc-arc.sc.intel.com/p/psg/swip/w/shuoniu/git/shuoniu.latency-control-prototype/add_ir_annotations_member/build/non_blocking_pip …
> [SYCL] [FPGA] Leverage `add_ir_annotations_member` in latency controls

- sycl/test-e2e/Graph/RecordReplay/barrier_with_work.cpp
All the SYCL-Graph tests currently require the `no_immediate_command_list` to be set on queue creation to run portably across all hardware. This property was missing from the `barrier_with_work.cpp` test, resulting in fails on some hardware.
> [SYCL][Graph] Add missing no_immediate_command_list property

- sycl/doc/EnvironmentVariables.md
Level Zero added a new environment variable `ZE_FLAT_DEVICE_HIERARCHY` that affects the way devices are exposed to high-level languages like SYCL.  Describe how this affects `ONEAPI_DEVICE_SELECTOR`.
> [SYCL][Doc] Update doc for ONEAPI_DEVICE_SELECTOR

- sycl/test-e2e/Graph/Explicit/basic_buffer.cpp
- sycl/test-e2e/Graph/Explicit/buffer_copy_host2target.cpp
- sycl/test-e2e/Graph/Explicit/buffer_copy_host2target_2d.cpp
- sycl/test-e2e/Graph/Explicit/buffer_copy_host2target_offset.cpp
- sycl/test-e2e/Graph/Explicit/temp_buffer_reinterpret.cpp
- sycl/test-e2e/Graph/Explicit/usm_copy.cpp
- sycl/test-e2e/Graph/RecordReplay/basic_buffer.cpp
- sycl/test-e2e/Graph/RecordReplay/buffer_copy_host2target.cpp
- sycl/test-e2e/Graph/RecordReplay/buffer_copy_host2target_2d.cpp
- sycl/test-e2e/Graph/RecordReplay/buffer_copy_host2target_offset.cpp
- sycl/test-e2e/Graph/RecordReplay/temp_buffer_reinterpret.cpp
- sycl/test-e2e/Graph/RecordReplay/usm_copy.cpp
- sycl/test-e2e/Graph/RecordReplay/usm_copy_in_order.cpp
The following 13 graphs tests originally disabled by https://github.com/intel/llvm/issues/11434 now pass on the Arc post commit testing after the merge of https://github.com/intel/llvm/pull/11565
```
Unexpectedly Passed Tests (13):
SYCL :: Graph/Explicit/basic_buffer.cpp
SYCL :: Graph/Explicit/buffer_copy_host2target.cpp
SYCL :: Graph/Explicit/buffer_copy_host2target_2d.cpp
SYCL :: Graph/Explicit/buffer_copy_host2target_offset.cpp
SYCL :: Graph/Explicit/temp_buffer_reinterpret.cpp
SYCL :: Graph/Explicit/usm_copy.cpp
SYCL :: Graph/RecordReplay/basic_buffer.cpp
SYCL :: Graph/RecordReplay/buffer_copy_host2target.cpp
SYCL :: Graph/RecordReplay/buffer_copy_host2target_2d.cpp
SYCL :: Graph/RecordReplay/buffer_copy_host2target_offset.cpp
SYCL :: Graph/RecordReplay/temp_buffer_reinterpret.cpp …
```
> [SYCL][Graph] Reenable passing Graph tests on Arc

- libdevice/cmath_wrapper.cpp
- libdevice/cmath_wrapper_fp64.cpp
`rintf` was missing for NVPTX.
> [SYCL][CUDA] Add missing rintf

- sycl/doc/extensions/experimental/sycl_ext_oneapi_device_global.asciidoc
Two issues have been identified with the wording of the `device_image_scope` property.
1. The spec doesn't currently state that all accesses to the device_global from device code must be from the same device.
*  In the JiT flow you can build a device_image containing a device_global and then run kernels from that device_image on multiple targets.  By the current wording of the spec, we were worried that, even with device_image_scope, a user could expect that device_global to retain its value across device.
2. The spec doesn't constrain which queues can be used to access a device_global from host code.  
* A queue is associated with a specific device.  We were worried that it’s legal to copy to/from a device that doesn’t use a device_image_scope device_global and that that would require …
> [SYCL][Doc] device_global: device_image_scope Update

- .github/CODEOWNERS
When possible, we should have teams owning segments of code when there is multiple owners involved. Switching matrix stuff to follow this pattern
> [NFC][Devops] CODEOWNERS: update matrix ownership to team instead of induvials

- sycl/include/sycl/handler.hpp
- sycl/test/basic_tests/handler/parallel_for_arg_restrictions.cpp
Before #10864, our header implementation allowed kernels with an auto& parameter, e.g. `q.parallel_for(1, [=](auto &id) {})` , but strictly speaking, this would not follow the criteria in [4.9.4.2.2. parallel_for invoke](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_parallel_for_invoke). After that PR, this behavior unintentionally became disallowed. This PR restores the old behavior while disallowing it under `-DSYCL2020_CONFORMANT_APIS`.
> [SYCL] Re-allow auto& parameter in range parallel_for

- sycl/test-e2e/Matrix/Legacy/joint_matrix_bfloat16_rowmajorA_rowmajorB_impl.hpp
- sycl/test-e2e/Matrix/common.hpp
- sycl/test-e2e/Matrix/joint_matrix_bf16_fill_k_cache_impl.hpp
Resolves https://github.com/intel/llvm/issues/11603
> [SYCL][Joint Matrix] Fix for flaky joint_matrix_all_sizes

- sycl/test-e2e/bindless_images/read_norm_types.cpp
Update `read_norm_types.cpp` test to use the newest API instead of the deprecated `free_image_mem`.
> [SYCL][Bindless] Update test with non-deprecated funcs

- sycl/test-e2e/Graph/Explicit/basic_buffer.cpp
- sycl/test-e2e/Graph/Explicit/buffer_copy_host2target.cpp
- sycl/test-e2e/Graph/Explicit/buffer_copy_host2target_2d.cpp
- sycl/test-e2e/Graph/Explicit/buffer_copy_host2target_offset.cpp
- sycl/test-e2e/Graph/Explicit/temp_buffer_reinterpret.cpp
- sycl/test-e2e/Graph/Explicit/usm_copy.cpp
- sycl/test-e2e/Graph/RecordReplay/basic_buffer.cpp
- sycl/test-e2e/Graph/RecordReplay/buffer_copy_host2target.cpp
- sycl/test-e2e/Graph/RecordReplay/buffer_copy_host2target_2d.cpp
- sycl/test-e2e/Graph/RecordReplay/buffer_copy_host2target_offset.cpp
- sycl/test-e2e/Graph/RecordReplay/temp_buffer_reinterpret.cpp
- sycl/test-e2e/Graph/RecordReplay/usm_copy.cpp
- sycl/test-e2e/Graph/RecordReplay/usm_copy_in_order.cpp
PR #11602 renabled some Graph test-e2e tests which started passing on Arc in post-commit CI after the merge of https://github.com/intel/llvm/pull/11565. However, these passes are not guaranteed to be deterministic. See post-commit https://github.com/intel/llvm/actions/runs/6580530144/job/17879085527 run where `Graph/RecordReplay/buffer_copy_host2target_offset.cpp` failed after being renabled.
Mark the tests reenabled by #11602 as unsupported to keep post-commit CI clean by skipping the tests on Arc, until support for the Arc target in the Graph tests can be investigated properly.
> [SYCL][Graph] Mark re-enabled Graph Arc tests as unsupported

- polygeist/lib/Dialect/Polygeist/Analysis/UniformityAnalysis.cpp
- polygeist/tools/cgeist/Lib/CGExpr.cc
- polygeist/tools/cgeist/Lib/clang-mlir.h
- polygeist/tools/cgeist/Test/Verification/complex.cpp
- polygeist/tools/cgeist/Test/Verification/consabi.cpp
- polygeist/tools/cgeist/Test/Verification/constructors.cpp
- polygeist/tools/cgeist/Test/Verification/memcpyconstructor.cpp
- polygeist/tools/cgeist/Test/Verification/refptrabi.cpp
- polygeist/tools/cgeist/Test/Verification/reinterpret_cast.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/issue7835.cpp
- polygeist/tools/cgeist/Test/Verification/sycl/structvec.cpp
- polygeist/tools/cgeist/Test/elaborated-init.cpp
Replace constructors which are equivalent to a `memcpy` intrinsic with `llvm.intr.memcpy`. These constructors must:
- Not be SYCL constructors, be copy or move constructors and:
- Be trivial and belong to record types not inserting extra padding, or
- Belong to unions and be defaulted.
SYCL constructors are not lowered to `llvm.intr.memcpy` at this stage, as this would lead to information loss. Instead, they shall be lowered when lowering from `sycl` to `llvm`.
> [SYCL-MLIR][cgeist] Lower memcpyable constructors to memcpy intrinsic

- sycl/test-e2e/Basic/library_loading.cpp
library_loading.cpp test is dependent on the ordering in which libraries are loaded, causing failures in some builds. This commit addresses that dependency by running FileCheck on each loaded library separately.
> [SYCL][E2E] Remove reliance on library loading ordering in test

- clang/lib/Sema/SemaStmt.cpp
- clang/test/SemaSYCL/sycl-seh.cpp
Rather issue an immediate diagnostic about the use of SEH, emit them deferred similar to what is done for C++ exceptions.
> [SYCL] Defer diagnostics about usage of SEH
